### ISSUE TITLE
[ACTION] - Zoom -> Update a Meeting

### ISSUE THREAD

**Issue by slachs** [PipedreamHQ/pipedream#1005]
This would be very useful to setup automation based on a schedule external to Zoom, where a generic room is reused for specific topics

**Comment by dylburger** [comment]
@slachs this should be published under the **Zoom** app with the title **Update Meeting**. See [this example workflow](https://pipedream.com/@dylburger/update-zoom-meeting-p_ezCA5r5/edit). Let me know if that helps or if you observe anything off with the action.
