### ISSUE TITLE
Monday.com

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10076]
### App
Monday.com

### Summary:
Monday has updated their API

### Details:
The new version of the Monday API has some breaking changes with the integration you have. This is preventing (in our case) create items on Monday's boards.

Are you aware of this and do you plan to update to the latest Monday API?

### Screenshots:
https://developer.monday.com/api-reference/docs/migrating-to-v-2023-10
![Screenshot]()

**Comment by malexanderlim** [comment]
Hi, we're aware of this and the fix is currently in QA. This should be released shortly.
https://github.com/PipedreamHQ/pipedream/issues/10017

Thanks!
