### ISSUE TITLE
[IMPROVEMENT] Update Frontegg connection popup

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10080]
**Is your feature request related to a problem? Please describe.**
On the Frontegg connection popup, we instructed the user to go to environments to get the API Key
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/a396c496-87f4-4c3e-97c2-9bba4a32e58d)

But on the Frontegg UI, the user must access User icon on the top right > Administration > API Tokens to generate ones
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/0268b601-90f0-4d2d-8456-1c15b41ea4c3)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/15f4b3c8-b40c-49a3-9c87-72a2f431aaa7)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
