### ISSUE TITLE
[ACTION] Webex Teams

### ISSUE THREAD

**Issue by jrogers512** [PipedreamHQ/pipedream#1008]
https://developer.webex.com/docs/api/getting-started

Everything in here is likely useful to someone, but in particular I would start with "send <message> to <room> using bot's <token>"

`
            curl -X POST \
            --header "Authorization: Bearer $WEBEX_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{"roomId" : "'"$WEBEX_ROOM"'","markdown" : "'"$MSG"'"}' \
            https://webexapis.com/v1/messages
`

**Comment by dylburger** [comment]
@jrogers512 thank you for the request! I've updated the ticket to note that we need to add Webex Teams as an integrated app. We'll work on that, which will allow us to create actions like this tied to the Webex Teams app.

**Comment by dylburger** [comment]
@jrogers512 we've added Webex as an integrated app: https://pipedream.com/apps/cisco-webex .

Would you be interested in helping to develop actions for Webex? Anyone can develop actions on Pipedream - [see the docs here](https://pipedream.com/docs/components/quickstart/nodejs/actions/). We're happy to help support you in any way.

**Comment by james-mcmichael** [comment]
Is there any chance that we could get the ability to set alternate scopes for the OAuth integration?

spark:all only allows access to the Webex Messaging (formerly Teams) part, and there is also the meetings API that uses the 'meeting' scopes.

For example, to later the controls of a meeting we need 'meeting:controls_write'

**Comment by dannyroosevelt** [comment]
Thanks for raising, @james-mcmichael! Is the `meeting:controls_write` the only other scope you're interested in accessing right now?

**Comment by james-mcmichael** [comment]
Hello @dannyroosevelt, `meeting:controls_read` & `meeting:controls_write` are the two I'm looking to use at the moment.

Effectively I'm using Pipedream to receive an inbound webhook from Webex every time a meeting is started, from here I can take the meeting ID, and then use a HTTP PUT request to update the in progress meeting to enable recording.

It allows for a method of auto-recording, for compliance purposes, so the above scopes are the ones that allow me to view the state and set recording as required.

Ideally it would be useful if we could integrate our own Integrations from Webex, whereby we can create a Webex Integration that allows us to set the required scopes and returns the Client ID, Client Secret, and the Authentication URL for the OAuth integration.

This way we could set our own scopes via the Webex Integrations API.

**Comment by dannyroosevelt** [comment]
@james-mcmichael thanks for the info -- the use case makes perfect sense. I've set up a "custom app" that you should be able to use to accomplish your goal: https://pipedream.com/apps/cisco-webex-custom-app.

Please let me know if that works for you and if you have any questions!

**Comment by james-mcmichael** [comment]
@dannyroosevelt that's perfect and is exactly what I needed. I think I'll be able to play around with setting up quite a few integrations via the custom app.

My auto-recording function is working perfectly, so time to start playing with some more features.

Many thanks!

**Comment by dannyroosevelt** [comment]
Closing out this original ticket and moving the new dev work to this one: https://github.com/PipedreamHQ/pipedream/issues/2518

**Comment by kmccarron76** [comment]
> @jrogers512 we've added Webex as an integrated app: https://pipedream.com/apps/cisco-webex .
> 
> Would you be interested in helping to develop actions for Webex? Anyone can develop actions on Pipedream - [see the docs here](https://pipedream.com/docs/components/quickstart/nodejs/actions/). We're happy to help support you in any way.

@dylburger I'm new to pipedream. I am working on a project to migrate from Cisco's on-prem Collaboration platform to Webex Calling. If I identify use cases for potential pipedream triggers and actions as I progress, is it ok to describe what might be useful for that process?

**Comment by malexanderlim** [comment]
Hi @kmccarron76 , please do! If there are triggers and actions that would be useful for your Webex workflows that you think may help others as well, you can submit these at https://pipedream.com/support - click `Request changes to an existing integration`, and describe the components that you're looking for there. 

The requested components will then go into our backlog for prioritization, but if you'd like to contribute to our registry yourself, our [docs](https://pipedream.com/docs/components/quickstart/nodejs/actions/) should be a good starting point and our team can review the PRs that you submit.
