### ISSUE TITLE
[Components] bland-ai

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10092]
# bland-ai
## URLs
- https://docs.bland.ai/api-v1/post/calls
#### Prompt
Analyzes an input call, extracting structured data and providing insights. Necessary props include the call record or stream. Pipedream facilitates real-time analysis to answer a variety of queries.
#### URLs
- https://docs.bland.ai/api-v1/post/calls-id-analyze
#### Prompt
Terminates a currently ongoing call. Required props are the unique call identity. Use this action to effectively control call sessions executing in Pipedream.
#### URLs
- https://docs.bland.ai/api-v1/post/calls-id-stop
#### Prompt
Retrieves the transcript of a specified call post-completion. Essential props include unique call ID. This action enables real-time and post-call analysis and insights with the transcript data.
#### URLs
- https://docs.bland.ai/api-v1/get/calls-id

**Comment by malexanderlim** [comment]
@vunguyenhung Sergio's added creds in 1Password that should go to me - please ping me when you're ready to test!

**Comment by malexanderlim** [comment]
API credentials have been added to the shared vault. Let me know if you're still blocked Leo!
