### ISSUE TITLE
[Google Appsheet]

### ISSUE THREAD

**Issue by happyscribe6431** [PipedreamHQ/pipedream#10107]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @happyscribe6431 

Thanks for the request There is a base integration for Google Sheet at https://pipedream.com/apps/google-appsheet
