### ISSUE TITLE
[Components] expedy

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10101]
# expedy
## URLs
- https://expedy.stoplight.io/docs/api-v2
#### Prompt
Sends a print job to the designated thermal printer using its unique identifier (UID). Required props include 'printerUID' for the designated printer and 'printer_msg' for the content to be printed.
#### URLs
- https://expedy.stoplight.io/docs/api-v2/01132c3490c8b-create-a-print-job

**Comment by luancazarine** [comment]
I couldn't create account.
