### ISSUE TITLE
[TRIGGER] Notion Updated Page In Database Trigger does not work

### ISSUE THREAD

**Issue by jkfletch** [PipedreamHQ/pipedream#10111]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Notion Updated Page In Database Trigger does not work
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
Notion Updated Page In Database Trigger does not work

**Comment by bartkei** [comment]
I have the same problem. It never seems to work and gives the error: Error, please try again. 
I reconnected notion many times but it always gives the same problem.

It's this trigger: https://pipedream.com/apps/notion/triggers/updated-page

![error](https://github.com/PipedreamHQ/pipedream/assets/158099424/77ef641c-ebc8-4784-aee2-6994904076c9)

**Comment by andrewjschuang** [comment]
Can you try reconnecting from a incognito window? That way you'll be prompted to select all databases you want to share with Pipedream.

**Comment by bartkei** [comment]
Thanks for your quick reply,
Incognito doesn't seem to help, I get the same error. 
I just don't get to see a list with my shared databases. 
I also created a new notion account to see if that was the problem but it also gives this error.

**Comment by andrewjschuang** [comment]
Thanks for providing the details. We're looking into it!

**Comment by bartkei** [comment]
Thanks for the help!
I hope there will be a fix available soon!

**Comment by malexanderlim** [comment]
Hi @bartkei @jkfletch , I pushed a fix for this yesterday - please let me know if this is working for you now!

**Comment by bartkei** [comment]
It is working like a charm again. 
Thanks for the great service!

**Comment by jkfletch** [comment]
So I have a question on this trigger.  Is there a way to have it to where it does not send the trigger when the database entry is created, but only when the specified fields are updated.  Testing my workflow to notify users on a specific day when a formula field is updated, but it is also sending out a notification when the page is created as well.

**Comment by jkfletch** [comment]
This could be a selectable option in the trigger deployment, something like "include page creation" with a true or false option.

**Comment by jkfletch** [comment]
@malexanderlim Are you able to speak on this feature integration?  Thank you

**Comment by jkfletch** [comment]
@malexanderlim https://github.com/PipedreamHQ/pipedream/issues/10223
