### ISSUE TITLE
[BUG] Airtable - List Records in View action failed when the view has more than 500 records

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10130]
**Describe the bug**
I have an Airtable view with 1058 records
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/4ca857b0-3343-48ba-aa3c-7425823ebe19)

Use the Airtable - List Records in View action shows the error 
```
{"errors":[{"error":"RATE_LIMIT_REACHED","message":"Rate limit exceeded. Please try again later"}]}
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/1bcca60b-1584-46c6-acc3-4b8d59ab6af3)

I think it's because we send more than 5 requests concurrently to Airtable that we hit the rate limit. We should add delay of 1 second after every 5 calls

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1706580265844129

**Comment by malexanderlim** [comment]
Confirming that I can reproduce the behavior. This is also recommended per Airtable's documentation here:
https://support.airtable.com/docs/managing-api-call-limits-in-airtable#:~:text=Airtable%20enforces%20a%20rate%20limit,before%20subsequent%20requests%20will%20succeed.
