### ISSUE TITLE
[omniovre]

### ISSUE THREAD

**Issue by YANYImf** [PipedreamHQ/pipedream#10132]
**Name of omniovre / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @YANYImf Thanks for the request,
https://pipedream.com/apps/omnivore is integrated.
