### ISSUE TITLE
[BUG] Omnisend connection popup leads to the outdated link

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10133]
**Describe the bug**
The Omnisend connection popup leads to the outdated link: `https://app.omnisend.com/#/my-account/integrations/api-keys`
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/4ba0e8fb-d992-450b-b42e-e35b8e5792f2)

The new link should be: `https://app.omnisend.com/integrations/api-keys`

**Comment by malexanderlim** [comment]
Thanks Leo, I've updated this!
