### ISSUE TITLE
[Components] facebook_marketing_api

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10140]
# facebook_marketing_api
## URLs
- https://developers.facebook.com/docs/marketing-api/audiences/overview
#### Prompt
Creates a new custom audience in Facebook. Props: name, description.
#### URLs
- https://developers.facebook.com/docs/marketing-api/audiences/guides/custom-audiences/
- https://developers.facebook.com/docs/graph-api/reference/user/adaccounts
#### Prompt
Adds an email address to a custom audience segment within Facebook. Please use async options to list custom audiences.

**Comment by malexanderlim** [comment]
@vunguyenhung , my mistake I forgot to add you as a tester of the application. Just added you - can you retest when you get a chance?
