### ISSUE TITLE
Azure Speech Service

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10155]
### App
Azure Speech Service
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/

**Comment by sergio-eliot-rodriguez** [comment]
Rest APIs
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/rest-speech-to-text

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/azure-speech-service?via=go
