### ISSUE TITLE
[SOURCE] Zoom: New Registrant

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1015]
**Describe the event source. What app, what event?**
Zoom

New Registrant | Triggers when a new registrant is added to a webinar.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://marketplace.zoom.us/docs/api-reference/zoom-api

**Comment by dylburger** [comment]
Closing since we support via custom events
