### ISSUE TITLE
[BUG] Postmark `$auth` does not include Account token

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10203]
**Describe the bug**
When connecting to Postmark, I need to define both Account token and Server token
<img width="443" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/29c72941-150a-495e-b19c-b4c073fec586">

But when I tried to use `this.postmark.$auth` in my code, I only see the `this.postmark.$auth.api_key` field that contains the Server Token
<img width="617" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/05ddb069-48ab-4bd9-a31c-cd6555bc889f">

This make me unable to use API that requires Account Token. For example, in the image below I tried to use the Get Domain API:
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/06b5d34f-639a-453e-8d42-3921c851a0e8)

**Expected behavior**
Please update `this.postmark.$auth` to include both Server Token and Account Token. After it is done, we'll need to change all actions code to use the respective token

**Comment by luancazarine** [comment]
Hi @vunguyenhung, this was updated by @malexanderlim a few days ago.
![Captura de tela 2024-02-02 103131](https://github.com/PipedreamHQ/pipedream/assets/5638699/1a0fc59c-bd63-4f34-8920-c2215435fc10)
