### ISSUE TITLE
[SOURCE] Hubspot: New Event Sources

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1021]
**Describe the event source. What app, what event?**
Hubspot

**New Ticket** | Triggers when a new ticket is available.
**New Line Item** | Triggers when a new line item is available.
**New Product** | Triggers when a new product is available.
**New Deal Property Change** | Triggers when a specified property is provided or updated on a deal.
**New Ticket Property Change** | Triggers when a specified property is provided or updated o a ticket.
**New Social Media Message** | Triggers when a message is posted from HubSpot to the specified social media channel.
**New Contact Property Change** | Triggers when a specified property is provided or updated on a contact.
**Email Subscriptions Timeline** | Triggers when new email timeline subscription added for the portal.
**New Company Property Change** | Triggers when a specified property is provided or updated on a company.
**Company Updated** | Triggers when a company is modified.
**Line Item Updated** | Triggers when a line item is modified.
**Product Updated** | Triggers when a product is modified.
**Watch CRM Objects** | Triggers when a CRM Object is created or modified.
**Watch Records** | Triggers when a contact, a company, or a deal has been created or modified.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.hubspot.com/docs/api/overview

**Comment by dannyroosevelt** [comment]
This is ready for release!
