### ISSUE TITLE
Triggers - TickTick

### ISSUE THREAD

**Issue by LauraM-Ramos** [PipedreamHQ/pipedream#10220]
[[APP]] TickTick Triggers

- New Task Created
- New Task Completed

The lack of support is preventing me from building workflows.

https://developer.ticktick.com/docs#/openapi

There are no triggers just steps. I want a trigger for when a new task is created and a new task is completed, like the ones for Todoist.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @LauraM-Ramos 

Thanks for your request!
Like implied on your text TickTick is integrated](https://pipedream.com/apps/ticktick?via=go) so I'll triage for component developments to complement the existing integration with triggers too.

Best,
Sergio

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
@LauraM-Ramos if you wanted you could jump building the triggers your self as per Dylan's message which is automated, otherwise just wait and the team will get to this and build the components.
