### ISSUE TITLE
[SOURCE] Reddit: New Event Sources

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1022]
**Describe the event source. What app, what event?**
Reddit

**New Comment by User** | Triggers when a new comment is created by a certain user.
**New Hot Post in Subreddit** | Triggers when there is a new hot post in the top 10 of a subreddit.
**New Post or Comment Matching Search** | Triggers when there is a new post or comment that matches a search string.
**New Link** | Triggers when a new link is submitted.
**New Link Submitted by User** | Triggers when a new link is submitted by a user.
**New Link in a Subreddit** | Triggers when a new link is submitted or updated in a given subreddit.
**New Subreddit** | Triggers when a new subreddit is posted by a user.
**New Comment in a Subreddit** | Triggers when a new comment is posted in a subreddit.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://www.reddit.com/dev/api/

**Comment by dylburger** [comment]
We're actually working on these separately now, so this is a duplicate.
