### ISSUE TITLE
[Notion] Update Page in Database Trigger also triggers for created page

### ISSUE THREAD

**Issue by jkfletch** [PipedreamHQ/pipedream#10223]
**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
So I have a question on this trigger. Is there a way to have it to where it does not send the trigger when the database entry is created, but only when the specified fields are updated. Testing my workflow to notify users on a specific day when a formula field is updated, but it is also sending out a notification when the page is created as well.
This could be a selectable option in the trigger deployment, something like "include page creation" with a true or false option.

**Do you have a workaround?**
No

**Comparable features in other tools?**
No

**Additional context**
No

**Comment by jkfletch** [comment]
Is this possible?

**Comment by jkfletch** [comment]
Will this functionality be applied to the Notion Trigger 'Updated Page in Database'?

**Comment by michelle0927** [comment]
> Will this functionality be applied to the Notion Trigger 'Updated Page in Database'?

@jkfletch Yes, once it's published, it will apply to the trigger "Update Page in Database".

**Comment by jkfletch** [comment]
Awesome, thank you! (:
