### ISSUE TITLE
[SOURCE] Microsoft Teams: New Event Sources

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1023]
**Describe the event source. What app, what event?**
Microsoft Teams

**New Channel** | Triggers when a new channel is created within a team.
**New Channel Message** | Triggers when a new message is posted in a channel.
**New Chat** | Triggers when a new chat is created.
**New Chat Message** | Triggers when a new message is received in a chat.
**New Team Member** | Triggers when a new member is added to a team.
**New Team** | Triggers when a new Microsoft Team or Office 365 group is created.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0

**Comment by sergioeliot2039** [comment]
The Microsoft Teams app in Pipedream uses Microsoft Graph but is missing scopes.
I.e trying the /me/joinedTeam breaks asking forthese scopes:

> "Missing scope permissions on the request. API requires one of 'Team.ReadBasic.All, TeamSettings.Read.All, TeamSettings.ReadWrite.All, User.Read.All, Directory.Read.All, User.ReadWrite.All, Directory.ReadWrite.All'. Scopes on the request 'Chat.Read, Chat.ReadWrite, email, openid, profile, User.Read'""


So it's either the Pipedream app for MS Teams have those scopes granted, or the issue #1063 is resolved, where users can bring their own app's client id/secrets and grant the scopes to their apps.

**Comment by sergioeliot2039** [comment]
Now, Microsoft Teams supports certain types of webhooks that are not helpful for building the requested sources. For example [Outgoing Webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-outgoing-webhook?tabs=urljsonpayload%2Cdotnet) are used as a bot proxy in a Teams channel. When the bot is mentioned on a chat inside a channel,  it will post data to an outside URL.

For the sources in the issue, we will need to use polling. I made a search for the scopes that are needed in each source.

**New Channel** one of the following scopes:
ChannelSettings.Read.All, Channel.ReadBasic.All, ChannelSettings.ReadWrite.All, Group.Read.All, Directory.Read.All, Group.ReadWrite.All, Directory.ReadWrite.All

**New Channel Message**
ChannelMessage.Read.All

**New Chat** One of the following scopes:
ChatSettings.Read.Chat*, ChatSettings.ReadWrite.Chat*, Chat.Manage.Chat*, Chat.ReadBasic.All, Chat.Read.All, Chat.ReadWrite.All

**New Chat Message**
Chat.Read.All

**New Team Members** One of the following scopes:
GroupMember.Read.All GroupMember.ReadWrite.All

**New Team** One of the following scopes:
New Team, one of the following:
Directory.AccessAsUser.All, Directory.Read.AllDirectory.Read.All, Directory.ReadWrite.AllDirectory.ReadWrite.All,
Group.Read.AllGroup.Read.All, Group.ReadWrite.AllGroup.ReadWrite.All, GroupMember.Read.All,

**Comment by Hassan-Abbas-SQA** [comment]
@michelle0927 can you please help me find out whats the issue?
![image](https://user-images.githubusercontent.com/104946677/173464266-3bc81b8c-3ce8-4281-b4d5-8939bf7c3a92.png)

**Comment by sergioeliot2039** [comment]
i bet @michelle0927 could extend more, but essentially, that error says the data for possible options on prop `team` is incorrect. maybe check "Props" on the components api documentation https://pipedream.com/docs/v1/components/api/#props

**Comment by michelle0927** [comment]
> @michelle0927 can you please help me find out whats the issue? 

I can look into it more tomorrow, but I wonder if it could have to do with the type of account. The Microsoft Teams API only works for paid or developer accounts, not regular free accounts. If it is a developer account you're using, maybe try reconnecting the account in Pipedream? There were some scopes recently added.

**Comment by Hassan-Abbas-SQA** [comment]
@michelle0927 thanks for letting me know iam currently using the free account I'll give it a try with developer account

**Comment by Hassan-Abbas-SQA** [comment]
@michelle0927 All of the Triggers works perfectly fine, just need minor change in the description of "new-team-member" it is "Emit new event when a new channel is created within a team" it should be "Emit new event when a new member is added to the channel within a team"

**Comment by michelle0927** [comment]
> @michelle0927 All of the Triggers works perfectly fine, just need minor change in the description of "new-team-member" it is "Emit new event when a new channel is created within a team" it should be "Emit new event when a new member is added to the channel within a team" let me know when you do so i can move ticket for release 😃

@Hassan-Abbas-SQA Oops. 😄 I updated the description with this commit - https://github.com/PipedreamHQ/pipedream/pull/3078/commits/bea9ba56cdf069b7f9f81ef9c8c14c2ce585ed7a

**Comment by dannyroosevelt** [comment]
This is ready for release!
