### ISSUE TITLE
Pipedream style guidelines are incompatible with Salesforce Metadata API (and others)

### ISSUE THREAD

**Issue by jhaisley** [PipedreamHQ/pipedream#10249]
The pipedream style guideline requires lowercase props, however many other systems are case sensitive, including the Salesforce Metadata API & deployment tools.  

Strict enforcement of the style guide would also break compatibility or potential compatibility with many other APIs, including certain firebase APIs, Genesys APIs, ESRI's APIs, so this issue is not at all limited to Salesforce. 

@jhaisley , thanks for your contribution! I'm going to request that one of our component devs make a few edits here for usability, and then we can ship this. For consistency and per the Pipedream style guidelines, we will be modifying the casing of the props per @luancazarine suggestion.

_Originally posted by @malexanderlim in https://github.com/PipedreamHQ/pipedream/pull/10206#pullrequestreview-1864133363_

**Comment by malexanderlim** [comment]
@jhaisley , I've responded in the original ticket, and will close this for now as we've aligned on the casing you suggested being appropriate for what you described.

**Comment by jhaisley** [comment]
> @jhaisley , I've responded in the original ticket, and will close this for now as we've aligned on the casing you suggested being appropriate for what you described.

@malexanderlim would it make sense to change the style guideline to define exceptions?  Salesforce certainly isn't the only time this would apply. The exception to the general camelCase style guideline would be for cases where external integration or consistency within a component requires different naming conventions.

**Comment by malexanderlim** [comment]
@jhaisley , I noticed that our documentation doesn't strictly define the casing of props - the only mention of lower/camel-casing are in other areas of our docs.

For our internal component development review guidelines - I will ensure that we take that into account in the PR review process, specifically adding in what you shared:
> The exception to the general camelCase style guideline would be for cases where external integration or consistency within a component requires different naming conventions.
