### ISSUE TITLE
Postmark Inbound Email Trigger - not able to create trigger "ErrorCode":10,"Message":"Request does not contain a valid Server token."

### ISSUE THREAD

**Issue by Swieter** [PipedreamHQ/pipedream#10254]
In Pipedream I created my Postmark account bringing over my Postmark Account and Server API key.
I then try to create the Postmark Inbound Email trigger.
When I click "create source" I get an error and the trigger is not created.

I'm seeing a handful of messages.  Screenshot attached.
<img width="1542" alt="Screenshot 2024-02-06 at 3 14 18 PM" src="https://github.com/PipedreamHQ/pipedream/assets/1411788/80e3c1dd-5642-4c98-9103-0232ed3a19e4">

Maybe the smoking gun is:
Getting a 401 with "{"ErrorCode": 10, "Message": "Request does not contain a valid Server token."}"

My expectation would be no error and the trigger is created.  
I'm in Chrome.  

My Postmark account is brand new.  In Postmark I see my account is in "Test Mode" but I believe this shouldn't limit the API's capabilities.

**Comment by Swieter** [comment]
Here is the full log.
In the field marked X-Postmark-Server-Token it looks like it is the Account token, not server.

`2024-02-06T16:36:00
log
export: debug - {
  "status": 401,
  "statusText": "Unauthorized",
  "headers": {
    "date": "Tue, 06 Feb 2024 21:35:59 GMT",
    "content-type": "application/json; charset=utf-8",
    "content-length": "75",
    "connection": "keep-alive",
    "cache-control": "private",
    "x-pm-apierrorcode": "10",
    "strict-transport-security": "max-age=16000000;",
    "vary": "Origin"
  },
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json",
      "Content-Type": "application/json",
      "X-Postmark-Server-Token": "REMOVED FOR SECURITY - it looks like it is the ACCOUNT TOKEN",
      "User-Agent": "axios/1.6.7",
      "Content-Length": "77",
      "Accept-Encoding": "gzip, compress, deflate, br"
    },
    "url": "https://api.postmarkapp.com/server",
    "method": "put",
    "data": "{\"InboundHookUrl\":\"https://REMOVED FOR PRIVACY.m.pipedream.net\"}"
  },
  "data": {
    "ErrorCode": 10,
    "Message": "Request does not contain a valid Server token."
  }
}`

**Comment by malexanderlim** [comment]
Hi @Swieter , thanks for flagging this issue. Can you try reconnecting your account and trying again?
