### ISSUE TITLE
[ACTION] OpenAI TTS

### ISSUE THREAD

**Issue by gotta-be-dc** [PipedreamHQ/pipedream#10258]
**Is there a specific app this action is for?**
OpenAI

**Please provide a link to the relevant API docs for the specific service / operation.**
https://platform.openai.com/docs/guides/text-to-speech

**Comment by malexanderlim** [comment]
Hi @gotta-be-dc , this action exists under the OpenAI App:
https://pipedream.com/apps/openai/actions/create-speech
