### ISSUE TITLE
[SOURCE] Mailchimp: New Event Sources

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1026]
**Describe the event source. What app, what event?**
Mailchimp

**New Audience** | Triggers when a new audience is added to your Mailchimp accounts.
**New Campaign** | Triggers when a new campaign is created or sent.
**New Subscriber** | Triggers when a new subscriber is added to an audience.
**New Subscriber in Segment or Tag** | Triggers when a subscriber is added to a segment or tag within an audience.
**New Unsubscriber** | Triggers when any current subscriber unsubscribes from an audience.
**New or Updated Subscriber** | Triggers when a subscriber is added or updated in an audience.
**New Customer** | Triggers when a new customer is added to a selected store.
**Email Opened** | Triggers when a recipient opens an email in a specific campaign.
**Link Clicked** | Triggers when a recipient clicks a pre-specified link in your campaign.
**New Order** | Triggers when a new order is created.
**New List Event** | Triggers when an event occurs on a list.
**New List** | Triggers when a new list is created.
**New or Updated List Segment** | Triggers when a segment is created or updated.
**New File** | Triggers when a new file is added.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://mailchimp.com/developer/marketing/api/

**Comment by dannyroosevelt** [comment]
@sergioeliot2039 is there a PR for this? I see it's "in review" but I think maybe that's a mistake?

**Comment by js07** [comment]
PR for this issue: https://github.com/PipedreamHQ/pipedream/pull/1289

**Comment by dannyroosevelt** [comment]
@michelle0927 this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
