### ISSUE TITLE
[Components] reputation_lyncs

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10270]
# reputation_lyncs
## URLs
- https://documenter.getpostman.com/view/25361963/2s93Xzw2bS#intro
#### Prompt
Emit new event when a new customer is added to the system. You need to config the customer ID as the required prop. Optional props like 'customer name' or 'customer phone' can help specify more accurate events.
#### Prompt
Adds a new customer to the ReputationLync platform. Requires the customer's full name as the 'full-name' prop. Optionally, an email can be provided using the 'email' prop and a phone number using the 'phone' prop.

**Comment by michelle0927** [comment]
Can't login
<img width="1043" alt="Screenshot 2024-02-08 at 2 24 46 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/a8a61880-8c57-41f5-908c-6b28f237690e">
