### ISSUE TITLE
[SOURCE] Jira: New Event Sources

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1028]
**Describe the event source. What app, what event?**
Jira

**New Project** | Triggers when a project is added.
**New Issue** | Triggers when you add an issue to a project.
**Updated Issue** | Triggers when an issue is updated.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developer.atlassian.com/server/jira/platform/rest-apis/

**Comment by feyzullah** [comment]
All event sources are also asked in [this issue](https://github.com/PipedreamHQ/pipedream/issues/415) . Can be closed.
