### ISSUE TITLE
[BUG] Monday.com - multiple reports of bugs after API version upgrade

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#10318]
**Describe the bug**
There have been a few user reports of issues post API version upgrade for Monday.com.

1. When one user attempts to Create Item, the List Groups async options call fails with:
`Failed to list groups: Type mismatch on variable $boardId and argument ids ([ID!]! / Int])`
https://github.com/PipedreamHQ/pipedream/assets/42158621/b3ece6a4-d435-4748-b47f-d47382cadfd6

I'm not sure why this is happening, because looking at the update in https://github.com/PipedreamHQ/pipedream/pull/10029 , I see that boardId was updated to ID! across the board.

2. Another user has reported the webhooks for New Sub-Item Column Value Updated (Instant) and New Column Value Updated (Instant) are failing with the following error:

```2024-02-06T11:15:33
error
Error: Should send 'token' as an option or call mondaySdk.setToken(TOKEN)
at MondayServerSdk.api (/var/task/node_modules/monday-sdk-js/src/server.js:29:23)
at Object.makeRequest (file:///var/task/user/monday.app.mjs:141:21)
at Object.getItem (file:///var/task/user/monday.app.mjs:160:35)
at Object.run (file:///var/task/user/sources/common/common-webhook.mjs:99:36)
at /var/task/index.js:122:72
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async exports.main [as handler] (/var/task/index.js:60:20)```

**Comment by michelle0927** [comment]
@malexanderlim 
1. I haven't been able to reproduce the type mismatch error yet. Are we certain the user is using the most recent version?
2. In the second error, I can see from the line numbers that it's using the older version of the app file. From #10029 :
<img width="508" alt="Screenshot 2024-02-09 at 10 43 18 AM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/5072ef80-d05b-453b-a9ad-bc4831b81953">

**Comment by malexanderlim** [comment]
Closing this bug, as it looks like the issue was due to an API Key that was given a version extension, which sets it to an older version header on Monday.com's backend.
