### ISSUE TITLE
[Google Drive]

### ISSUE THREAD

**Issue by JuggernotAI** [PipedreamHQ/pipedream#10327]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
You can see that [Google Drive](https://pipedream.com/apps/google-drive?via=go) is integrated.

However, let us know: what are you trying to do @JuggernotAI ?

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/google-drive Hi there, @JuggernotAI , Goole Drive is integrated, but why don't let us know what you are trying to do so that we can advise?

**Comment by sergio-eliot-rodriguez** [comment]
Without more details, we need to close this issue.
