### ISSUE TITLE
google drive[APP]

### ISSUE THREAD

**Issue by JuggernotAI** [PipedreamHQ/pipedream#10326]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
I see this is a duplicated request. let's close this and follow you request on https://github.com/PipedreamHQ/pipedream/issues/10326
