### ISSUE TITLE
[APP]trigger

### ISSUE THREAD

**Issue by Mcrypto143** [PipedreamHQ/pipedream#10334]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @Mcrypto143 

Thanks for your request and  being a [Pipedream](https://pipedream.com?via=go) user.

Could you please kindly provide more details about the app you would like to see integration at the [app store](https://pipedream.com/explore?via=go) 

E,g, one important data we need to move forward with your request is the official website of the app you would like to see integrated. Please your help

**Comment by sergio-eliot-rodriguez** [comment]
Without more details, we need to close this issue.
