### ISSUE TITLE
[SOURCE] PostgreSQL: New Event Sources

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1034]
**Describe the event source. What app, what event?**
PostgreSQL

**New Table** | Triggers when you add a new table.
**New Column** | Triggers when you add a new column.
**New Row** | Trigger when you add a new row.
**New or Updated Row** | Triggers when a row is added or modified.
**New Row (Custom Query)** | Triggers when new rows are returned from a custom query that you provide.

**Comment by dannyroosevelt** [comment]
@michelle0927 this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
