### ISSUE TITLE
[APP] Castmagic

### ISSUE THREAD

**Issue by jimbanks** [PipedreamHQ/pipedream#10359]
**Name of app / service** - Castmagic

**Link to developer documentation** - https://docs.castmagic.io/

**Is lack of support preventing you from building workflows, or do you have a workaround?** - I could use Zapier but I wanted to move all my automations to Pipedream

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** - I'm trying to get AI generated content created in Castmagic into Notion.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @jimbanks 

Thank you for the request.
I've taken care of a base integration for Castmagic at Pipedream and should be published soon 

Cheers

**Comment by sergio-eliot-rodriguez** [comment]
Base integration for Castmagic has been rolled out https://pipedream.com/apps/castmagic?via=go
follow https://github.com/PipedreamHQ/pipedream/issues/10577 for Catmagic based components
