### ISSUE TITLE
[SOURCE] Pipedrive: New Event Sources

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1037]
**Describe the event source. What app, what event?**
Pipedrive

- [x] **New Deal** | Triggers when a new deal is created.
- [x] **Updated Deal** | Triggers when an existing deal is updated.
- [x] **New Person** | Triggers when a new person is created.
- [x] **Updated Person** | Triggers when an existing person is updated.
- [ ] **Deal Matching Filter** | Triggers when a deal matches a Pipedrive filter.
- [ ] **Updated Deal Stage** | Triggers when a deal's stage is updated.
- [ ] **New Activity** | Triggers when a new activity is created.
- [ ] **Activity Matching Filter** | Triggers when an activity matches a Pipedrive filter.
- [ ] **New Note** | Triggers when a new note is created.
- [ ] **New Organization** | Triggers when a new organization is created.
- [ ] **Organization Matching Filter** | Triggers when an organization matches a Pipedrive filter.
- [ ] **Updated Organization** | Triggers when an existing organization is updated.
- [ ] **Person Matching Filter** | Triggers when a person matches a Pipedrive filter.
- [ ] **New Lead** | Triggers when a new lead is created.
- [ ] **New or Updated Product** | Triggers when a product is added or updated.
- [ ] **New or Updated Note** | Triggers when a note is added or updated.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.pipedrive.com/docs/api/v1/

**Comment by dannyroosevelt** [comment]
@jcortes this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
