### ISSUE TITLE
[IMPROVEMENT] Migrate from Nordigen to GoCardless

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10377]
**Is your feature request related to a problem? Please describe.**
GoCardless acquired Nordigen and the Nordigen endpoint will slowly stop working. GoCardless team requires us to use Connection String: `https://bankaccountdata.gocardless.com/api/v2/`

Here's the email from GoCardless team
```
Dear user,

We are contacting you to make sure you are using an up-to-date base_url for the GoCardless Bank Account Data API.
This small but important change which should be easy to make for anyone in your team who has access to the production setup of your service. The new connection string should be:
https://bankaccountdata.gocardless.com/api/v2/

The legacy URLs such as ob.nordigen.com and ob.gocardless.com will stop working on the 20th of February.

If you are using any of our public libraries, they are updated and can be found here:
https://developer.gocardless.com/bank-account-data/libraries

We would also like to inform you that there is maintenance window (with downtime) scheduled for 20.02.2024 between 03:00 and 05:00 UTC. You follow its progress on our statuspage:
https://status.nordigen.com/

If you have any questions, feel free to contact support by replying to this mail and will be happy to assist you.

Working on an ever better service,
Bank Account Data Team
```

**Comment by LucBerge** [comment]
@vunguyenhung The GoCarless picture is missing https://pipedream.com/apps/nordigen

**Comment by malexanderlim** [comment]
<img width="1262" alt="Screenshot 2024-02-21 at 10 43 15 AM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/9d9211bc-b7a9-4b64-9f9c-5d60af196a64">
Hey @LucBerge  - it may just be cached on your side, can you try to hard-refresh?

**Comment by LucBerge** [comment]
Hey, that is the problem

> <img alt="Screenshot 2024-02-21 at 10 43 15 AM" width="1262" src="https://private-user-images.githubusercontent.com/42158621/306737493-9d9211bc-b7a9-4b64-9f9c-5d60af196a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDEzMTUsIm5iZiI6MTcwODU0MTAxNSwicGF0aCI6Ii80MjE1ODYyMS8zMDY3Mzc0OTMtOWQ5MjExYmMtYjdhOS00YjY0LTlmOWMtNWQ2MGFmMTk2YTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE4NDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYjEzZGQxMTZhOWM2MWYwMjZlYTYyNjg4YTVkNjBiM2FmNmFiMDY3MDE1Mzg0MWQ0Nzk4NzFjOTA3NTkxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GI3BH8CVRBpDl9O5h80ax29rvqklvkK9vcgCKzRutDU"> Hey @LucBerge - it may just be cached on your side, can you try to hard-refresh?

Not the cache. That is the problem: Why isn't it that ?

![](https://pbs.twimg.com/profile_images/1586003421492125696/PRzcW6KB_400x400.png)

**Comment by malexanderlim** [comment]
I see. I've updated it to the new logo! Thanks.

**Comment by malexanderlim** [comment]
We repurposed the Noridgen integration and renamed it to GoCardless and updated the API endpoints behind the scenes - otherwise users would need to recreate their workflows using a new GoCardless application altogether.

**Comment by LucBerge** [comment]
Yes but one day you will have to do the migration, no?

**Comment by malexanderlim** [comment]
Thanks, I'll update the description. The migration has been completed on the back-end - the only thing of Nordigen that will stay is the name slug. We had to weigh the decision of having a more seamless transition behind the scenes, but keeping the  nameslug as `nordigen`, versus having users transition to a completely new app and having to rebuild their workflows with the new Gocardless app.
