### ISSUE TITLE
[FEATURE] Improve Appointedd Connection popup to instruct users to use V1 token

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10378]
**Is your feature request related to a problem? Please describe.**
When the user access https://app.appointedd.com/management/settings/api, they see 2 types of APIs: 1) Appointedd API V2 clients and 2) Appointedd API
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/5f1eebf3-22a2-48e1-883d-d4c6fa8f44f8)

But on our, Appointedd Connection popup, we do not stated which API type to use
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/4e3ea665-38df-4b8b-8e55-0ea7fbaed1cb)

**Describe the solution you'd like**
Improve the Appointedd Connection popup to add image that highlight the API Key that the user need to use
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/7876bfbc-1d9e-425e-ad40-8a832057368e)

**Comment by malexanderlim** [comment]
Thanks for the suggestion Leo - added!
