### ISSUE TITLE
[SOURCE] Bitbucket:  Watch User, Watch Team

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1038]
**Describe the event source. What app, what event?**
Bitbucket

Watch a User | Triggers when an event occurs from any repository belonging to the user.
Watch a Team | Triggers when an event occurs from any repository belonging to the team account.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developer.atlassian.com/bitbucket/api/2/reference/

**Comment by dannyroosevelt** [comment]
@bush4u why is this blocked?

**Comment by bush4u** [comment]
> @bush4u why is this blocked?

The webhook endpoints for the two tasks are not clear to me, and I am finding it a bit hard to understand how to go about the triggers. 
So I put it on block so I can do more research and have a clearer view of how best to implement the task.

**Comment by dannyroosevelt** [comment]
> > @bush4u why is this blocked?
> 
> The webhook endpoints for the two tasks are not clear to me, and I am finding it a bit hard to understand how to go about the triggers. So I put it on block so I can do more research and have a clearer view of how best to implement the task.

Can you post in one of the component dev channels so the team can help unblock you?

**Comment by bush4u** [comment]
![image](https://user-images.githubusercontent.com/68253993/170608948-8b3b9e13-8a0e-4f79-a085-3fe0b098d409.png)

Teams endpoint has been deprecated.
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/

Task **Watch a Team | Triggers when an event occurs from any repository belonging to the team account.** could not be implemented
