### ISSUE TITLE
[SOURCE / ACTION] - Eventbrite Triggers & Actions

### ISSUE THREAD

**Issue by JKasmire** [PipedreamHQ/pipedream#1040]
Eventbrite 

https://www.eventbrite.com/platform/api

Currently, there are a few things we would like to automate that we cannot currently (export registered participants in events is one, export new followers, etc.) 

E.g. 
* When a scheduled event is finished (or 24 hours after finishing... Whatever) export all registered participants
* Once per month, export all new followers since the previous month.

**Comment by joseph-allen** [comment]
This would be helpful

**Comment by todsac** [comment]
Can you both clarify what the ask is here?  Eventbrite is currently integrated in Pipedream - https://pipedream.com/apps/eventbrite.  Are you requesting specific triggers or actions related to EventBrite or is the current integration not supporting this specific API request?

**Comment by joseph-allen** [comment]
A Trigger for events ending
Actions for:
* Export event summary
* Export event attendees
* Create Events 

would cover my use cases
