### ISSUE TITLE
[APP] Fitbit

### ISSUE THREAD

**Issue by pdziewa** [PipedreamHQ/pipedream#1041]
**Name of app / service**
Fitbit

**Link to developer documentation**
https://dev.fitbit.com/build/reference/web-api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Just OAuth handling, would be fine.

**Comment by todsac** [comment]
Workflow Example - https://pipedream.com/@tod/fitbit-api-integration-example-p_13CgdNd/
Marketplace - [Fitbit API Integrations](https://pipedream.com/apps/fitbit)
