### ISSUE TITLE
[IMPROVEMENT] Improve Airbyte connection popup to include link to Airbyte portal

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10436]
**Is your feature request related to a problem? Please describe.**
The Airbyte connection popup does not include the link to the Airbyte Portal which is https://portal.airbyte.com/
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/4a647449-07c7-4fe9-9ac5-a08bb6d63fd1)

**Describe the solution you'd like**
Update the instruction to
```
Sign in to your [Developer Portal](https://portal.airbyte.com/), and generate your API Key from "API Keys" on the left navigation menu.
```

**Comment by malexanderlim** [comment]
Thanks for flagging Leo, this has been updated.
