### ISSUE TITLE
[BUG] Texts are gone on screenshots made with puppeteer.

### ISSUE THREAD

**Issue by repwidg** [PipedreamHQ/pipedream#10437]
**Describe the bug**
Texts are gone on screenshots made with puppeteer.

**To Reproduce**
```js
import { puppeteer } from '@pipedream/browsers';
export default defineComponent({
  async run() {
    const browser = await puppeteer.browser()
    const page = await browser.newPage()
    await page.goto('https://pipedream.com/')
    await page.screenshot({
      path: '/tmp/1.png'
    })
    await browser.close()
  }
})
```

**Screenshots**
Result:
![1](https://github.com/PipedreamHQ/pipedream/assets/160206876/5cf712e6-7181-4a20-8263-2a0d7ba5b974)

**Additional context**
Used to work fine a few weeks ago.
Workflows made previously are still working fine.
The problem starts when I make a change to a workflow and deploy it.
Could it be related to the node js version?

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
