### ISSUE TITLE
[APP] streamwish

### ISSUE THREAD

**Issue by DubToonIndia** [PipedreamHQ/pipedream#10440]
**StramWish website / upload video**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
https://streamwish.com/
https://streamwish.com/api.html

**Comment by sergio-eliot-rodriguez** [comment]
This has been integraed https://pipedream.com/apps/streamwish?via=go
