### ISSUE TITLE
Home Connect API ( for all smart bosch / siemens appliances ) - OAUTH

### ISSUE THREAD

**Issue by kdejaeger** [PipedreamHQ/pipedream#10454]
Home Connect API

[**Link to developer documentation**](https://api-docs.home-connect.com/authorization/)

I'd like to let pipedream handle the oauth authorization so I can easily send commands.

**Comment by kdejaeger** [comment]
When done, ask bosch to put a link to pipedream on this page ... : https://developer.home-connect.com/integrations

**Comment by sergio-eliot-rodriguez** [comment]
Hi @kdejaeger This has been integrated)))
https://pipedream.com/apps/home-connect?via=go

**Comment by kdejaeger** [comment]
I'm stuck here:
![image](https://github.com/PipedreamHQ/pipedream/assets/279268/22358f9c-d132-418e-bced-3be2ef070337)

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim like with Ruly, issue where Home Connect app isn't open to all users.

**Comment by kdejaeger** [comment]
@sergio-eliot-rodriguez So how do we get passed this error message? We wait till pipedream fixes the oauth app configuration?

**Comment by malexanderlim** [comment]
Hi @kdejaeger , I'm reaching out to Home Connect regarding the best path forward. We have two options:
1. Go through the process for creating a public integration on Home Connect - I've reached out to their team to determine the LOE of supporting this.
2. Create a Home Connect (developer app) setup - and you would create an application on the Home Connect side, using Pipedream's redirect URI and we would handle the auth.

**Comment by kdejaeger** [comment]
Thanks for the update.

**Comment by malexanderlim** [comment]
@kdejaeger unfortunately, we've had to disable the integration as Home Connect does not allow the use of their application or their branding without a formal partnership. I'll keep this thread updated with our progress.
