### ISSUE TITLE
Gmail

### ISSUE THREAD

**Issue by Mohammed-Hamza123** [PipedreamHQ/pipedream#10460]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by Mohammed-Hamza123** [comment]
idk

**Comment by Mohammed-Hamza123** [comment]
idk

**Comment by sergio-eliot-rodriguez** [comment]
gmail is integrated https://pipedream.com/apps/gmail?via=go
