### ISSUE TITLE
[APP] Timetonic

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#10474]
**Name of app / service**
Timetonic

**Link to developer documentation**
https://timetonic.com/live/apidoc/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Trigger:
- Record added
- Record updated
- Record deleted

Actions:
- Create record
- Update record
- Delete record

**Comment by sergio-eliot-rodriguez** [comment]
Hi @LucBerge 

Timetonic is now integrated at https://pipedream.com/apps/timetonic

Consider following #11734 for components too.

**Comment by sergio-eliot-rodriguez** [comment]
Timetonic components ready too https://pipedream.com/apps/timetonic#popular-timetonic-triggers
