### ISSUE TITLE
[APP]Directus

### ISSUE THREAD

**Issue by cuongtqtran** [PipedreamHQ/pipedream#1047]
**Name of app / service**
Directus 9
**Link to developer documentation**
https://docs.directus.io/reference/api/authentication/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Create a item
https://docs.directus.io/reference/api/rest/items/#create-an-item

**Comment by todsac** [comment]
@cuongtqtran - can you please test this integration and confirms that it works for you?  No actions created yet.

Workflow - https://pipedream.com/@tod/directus-api-integration-example-p_WxCQldp/
Marketplace - https://pipedream.com/apps/directus

**Comment by cuongtqtran** [comment]
I tested Directus App, it work fine👌
