### ISSUE TITLE
[TRIGGER] Chargebee: New Triggers

### ISSUE THREAD

**Issue by worldspawn** [PipedreamHQ/pipedream#10472]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

More events needed for chargebee including:
- subscription_activated
- subscription_renewed
- payment_refunded
- invoice_updated

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

https://apidocs.chargebee.com/docs/api/events

When I went through and compared what my employer needed versus what was supported this is how it went (X is not supported):
![image](https://github.com/PipedreamHQ/pipedream/assets/819581/d6d6cfc2-c13c-4ad9-a51e-9bcbbd849483)

subscription_activated, subscription_renewed, payment_refunded and invoice_updated are must haves for us.

**Comment by worldspawn** [comment]
> subscription_activated. Triggered after the subscription has been moved from "Trial" to "Active" state

In comparison, subscription created is a fairly "who cares" event.

**Comment by worldspawn** [comment]
Also, all the implemented events hide the 'occurred_at' that is sent by chargebee.

**Comment by malexanderlim** [comment]
Chargebee - New Event
- Have the full list of available events available, and show the `occurred_at` time for the event.

**Comment by worldspawn** [comment]
Thank you muchly :)

**Comment by worldspawn** [comment]
Hi guys, I just tried to use the new multi-event trigger. Theres a few issues, firstly the occured_at field of the event payload is still no being surfaced from what i can see.

Also the actual name of the event that triggered the workflow is not surfaced either.

Heres a sample payload that chargebee sends to webhooks:

```
 {
    "id": "ev_1234",
    "occurred_at": 1730865140,
    "source": "api",
    "user": "full_access_key_v1",
    "object": "event",
    "api_version": "v2",
    "content": {
        "subscription": {
                        //omitted for brevity
        },
        "customer": {
            //omitted for brevity
    },
    "event_type": "subscription_created",
    "webhook_status": "not_configured",
    "webhooks": [{
        "id": "whv2_AzZiTsU4sdYRk71FG",
        "webhook_status": "not_applicable",
        "object": "webhook"
    }]
}
```

So i'm seeing the subscription and customer objects being surfaced in the trigger but all the root fields are being swallowed. **CRITICAL FIELDS** here are `event_type` and `occurred_at`. I'd like to see new object off the "event" field that contains these two fields. Having the event id is probably a useful thing too.

![Image](https://github.com/user-attachments/assets/e20e02d7-2091-48d5-92cd-1fc17dad7ecf)

Please add this 🙏
