### ISSUE TITLE
Vitally.io

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10478]
### App
Vitally.io
https://docs.vitally.io/pushing-data-to-vitally/using-the-vitally-api/https-analytics-api/analytics-api-organization

**Comment by malexanderlim** [comment]
I'm not sure what the request is here. Closing this unless we get further detail from the customer.

**Comment by sergio-eliot-rodriguez** [comment]
Since Vitally is integrated -- https://pipedream.com/apps/vitally?via?go
I'm guessing their request is about creating an action to create/update an organization
