### ISSUE TITLE
[IMPROVEMENT] Slack Bot Feature parity with Slack

### ISSUE THREAD

**Issue by jhaisley** [PipedreamHQ/pipedream#10482]
**Slack Bot**

The Slack Bot integration should have feature parity with the Slack  integration.

**Comment by sergio-eliot-rodriguez** [comment]
fyi @malexanderlim not an new app integration request

**Comment by jhaisley** [comment]
> fyi @malexanderlim not an new app integration request

I wasn't sure if this should have the app label or not, and ended up going with improvement, was that correct?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by jhaisley** [comment]
> Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

Hi, I forgot this request was out there, but I was just looking for feature parity between the Slack and Slack Bot integrations.
