### ISSUE TITLE
[FEATURE] Snowflake - Add database and schema props

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#10485]
**Is your feature request related to a problem? Please describe.**
Instead of having to create multiple separate account connections to work with different databases and schemas, we should have props to specify these. This will allow the end-user to use our components more seamlessly, as they will be able to specify the Database - Schema - Table, which is both more flexible and makes the List Columns call more fail-proof.

**Comment by dxkaufman** [comment]
@michelle0927 @vunguyenhung I can't seem to find these options anywhere in the UI.  What am I missing?

**Comment by dannyroosevelt** [comment]
@dxkaufman can you try either adding this action:
https://pipedream.com/apps/snowflake/actions/execute-sql-query

or clicking here in the UI?

![Image](https://github.com/user-attachments/assets/7b834d59-cb57-49c2-acab-492f03792b43)

**Comment by dxkaufman** [comment]
Hi @dannyroosevelt, I have a number of Snowflake Execute SQL Query actions, such as this one:

<img width="304" alt="Image" src="https://github.com/user-attachments/assets/f724f9c8-1cfc-4af5-b4de-0c84b4ba605d" />

I don't see any way to pick the database and schema in that action:

<img width="656" alt="Image" src="https://github.com/user-attachments/assets/8423a8f9-7f55-4f89-b254-191ab93b74e8" />

**Comment by dannyroosevelt** [comment]
Oh, yea right now you define the db and schema when you configure the account for Snowflake. So if you need to connect to a different db, you can just connect another account. That may not be totally ideal, but that's the current state.

**Comment by dxkaufman** [comment]
OK.  I filed an enhancement request to enable setting the entire context on a per-step basis... there should be 3 drop-downs available once you pick an account, warehouse, role, and database/schema, where you can pick those 4 elements for use with the current step.
