### ISSUE TITLE
Instagram & TikTok

### ISSUE THREAD

**Issue by ablac** [PipedreamHQ/pipedream#10498]
**Name of app / service**
Instagram & TikTok

**Link to developer documentation**
https://developers.facebook.com/docs/instagram-api/
https://developers.tiktok.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
The lack of support for these is preventing me from signing up for a premium account, as the free account works for youtube, and due to not having support for Instagram and TikTok i need a seperate service for those. If you had Instagram and Tiktok intigragation to be able to upload content, i wouldnt need the other service, and would get a premium account with you guys.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Upload content, Set Description, and Title, Hash tags, ETC. Very similar to the youtube upload option.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there, thanks for the request.

We are trackng Instagram here: https://github.com/PipedreamHQ/pipedream/issues/445

currently blocked.

We are tracking Tiktok here: https://github.com/PipedreamHQ/pipedream/issues/2324
