### ISSUE TITLE
If a workflow writes to console.error, indicate this in the Event log (an icon, or color the time in red

### ISSUE THREAD

**Issue by rcmontrose** [PipedreamHQ/pipedream#105]
**Is your feature request related to a problem? Please describe.**
I have to manually go through each run to see if there are any console.error logs written, indicating a problem I have caught. 

**Describe the solution you'd like**
When I look at the Event log (the column listing each event), I would like to see some indication that the workflow has written to console.error. I can then know to review the output to see what happened.  Either an icon (like is used in the output) or coloring the event time and execution time in Red.

![image](https://user-images.githubusercontent.com/59274633/78158289-a5e38a80-7406-11ea-9ab2-50df32f2cd22.png)

**Do you have a workaround?**
I have added $send.email to the important console.error places.

**Comparable features in other tools?**
n/a

**Additional context**
n/a

**Comment by dylburger** [comment]
@rcmontrose I was thinking about this one more and had one question: are you printing `console.error` logs when the workflow executes successfully? Or are you only printing these errors when your workflow fails and you catch the error?

Pipedream will mark the event in the event log red if you manually throw a custom error (e.g. `throw new Error("your error")`). We often use this to handle error conditions in a custom way, for example, throwing an error if a critical workflow doesn't contain the necessary data:

```javascript
if (!body.data) {
  throw new Error("Critical data missing")
}
```

Throwing the error marks the event red, and ensures we get notified via the global error workflow.

Mainly I'm curious if you'd be able to use `throw` in this way to solve this, or if you need the `console.error` logs to serve another purpose.
