### ISSUE TITLE
[Components] token_metrics

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10515]
# token_metrics
## URLs
- https://developers.tokenmetrics.com/docs/getting-started
- https://developers.tokenmetrics.com/reference/tokens
- https://developers.tokenmetrics.com/reference/trader-grades
- https://developers.tokenmetrics.com/reference/market-metrics

#### Prompt
Get the list of coins and their associated TOKEN_ID supported by Token Metrics. https://developers.tokenmetrics.com/reference/tokens
#### Prompt
Get the list of short term grades. The required props are token_id, startDate and endDate https://developers.tokenmetrics.com/reference/trader-grades
#### Prompt
Get the Market Analytics from Token Metrics. The required props are startDate and endDate https://developers.tokenmetrics.com/reference/market-metrics

**Comment by lcaresia** [comment]
@vunguyenhung Removed the action with bug, it's a problem with API.
