### ISSUE TITLE
[FEATURE] Shopify Developer App - Support StoreFront API

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10555]
**Is your feature request related to a problem? Please describe.**
Currently, Shopify Developer App only support [Admin API](https://shopify.dev/docs/api/admin) and the connection popup only allow customer to input Admin Access Token
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/7425de0d-4115-4305-8e0f-72d0314c6a71)

A Customer is requesting to use [StoreFront API](https://shopify.dev/docs/api/storefront) which have not supported yet.

**Describe the solution you'd like**
We'll need to allow customer to add the StoreFront Access Token to the connection popup as an **optional field** and expose it on `$auth` prop in the action code.

**Additional context**
Requested by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1708565496384619

**Comment by zecul** [comment]
Thanks for writing this up Leo!

I need this to access checkout so I can send rates from shippo to my shopify checkouts.

**Comment by malexanderlim** [comment]
I've added the new Storefront API Access Token as an optional field when connecting your account.
