### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10560]
### App
Matrix
https://matrix.org/docs/chat_basics/matrix-for-im/

**Comment by sergio-eliot-rodriguez** [comment]
Matrix is duplicated 
By [MichaelHinrichs](https://github.com/PipedreamHQ/pipedream/issues?q=is%3Aissue+is%3Aopen+author%3AMichaelHinrichs) on #9522 
In conjunction with Element app #3047 
Apparently implied on Beeper #7508
