### ISSUE TITLE
[Components] zixflow

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10573]
# zixflow
#### Prompt
Creates a new activity or task within Zixflow. Required props are the task title and task description. Optional props include due date and assigned members.
#### Prompt
Updates an existing activity or task in Zixflow. The activity ID is a required prop. Optional props could be changes to the task title, task description, due date, or assigned members.
#### Prompt
Removes an existing activity or task from Zixflow. The only required prop is the activity ID.

**Comment by lcaresia** [comment]
@vunguyenhung 

![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/60a0566b-741e-4dd7-bcbd-38c217aba8a3)
![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/e8c84d2c-ebaa-401e-8ed9-7da9162643b2)
![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/3d9819f9-8e01-4689-a579-4c51f2f2b007)
