### ISSUE TITLE
[APP] ArcGIS

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10587]
### App
ArcGIS Online
https://developers.arcgis.com/documentation/mapping-apis-and-services/security/oauth-2/

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Sergio used this issue to test out a workflow. I'm creating a new app request for ArcGIS Online
