### ISSUE TITLE
[BUG] Can not connect to Ticktick

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10596]
**Describe the bug**
When I tried to reconnect to Ticktick, I faced an error on the OAuth popup
<img width="712" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/1656539b-83c2-4207-a62b-89fc1e88da66">

You can use my Ticktick credentials in 1PW to reproduce

**Comment by malexanderlim** [comment]
Closing this for now per offline conversation.
