### ISSUE TITLE
The Ability to run multiple queries in a Gogole Cloud BigQuery Run Query Action

### ISSUE THREAD

**Issue by ph-cxt** [PipedreamHQ/pipedream#10605]
**Is your feature request related to a problem? Please describe.**
I have a workflow that uses 5 Google Cloud steps. It kept throwing Out Of Memory errors (see Slack thread: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1708956374819719)  This is apparently caused because the libraries load for each step and those libraries are huge.

**Describe the solution you'd like**
One solution is that I can combine multiple queries into one step, that would reduce the amount of memory used.

**Do you have a workaround?**
Not really. will likely have to use a Code step to solve this

**Comparable features in other tools?**
N/A

**Additional context**
Overall, this is a fairly simple workflow, but it consistently runs out of memory.  Another soltuion would be to only load libraries once, I suppose.... I am sure there is architectural reason why they load per step.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by ph-cxt** [comment]
I don't know anything about Github or branching or contributing to open
source. I did however solve this problem with help from your AI generator
and some google search and if this is helpful, feel free to steal it! ;)


import { axios } from ***@***.***/platform";
import { BigQuery } from ***@***.***/bigquery";

export default defineComponent({
  props: {
    google_cloud: {
      type: "app",
      app: "google_cloud",
    },
    queries: {
      type: "string[]",
      label: "Queries",
      description: "The SQL queries to run on Google BigQuery",
    },
    querynames: {
      type: "string[]",
      label: "Name Queries in Order",
      description: "The names of the SQL queries in the above array",
    },
  },
  async run({ steps, $ }) {
    const credentials = JSON.parse(this.google_cloud.$auth.key_json);
    const { project_id: projectId } = credentials;
    const bg = new BigQuery({
      credentials,
      projectId,
    });

    const results = [];


    var i = 0;

    for (const queryString of this.queries) {
      const query = { "query": queryString, "location": 'US' };

      try {
        const [
          job,
        ] = await bg.createQueryJob(query);

        const response = await job.getQueryResults();
        results.push( { "QueryName" : this.querynames[i], "Response" :
response });
      } catch (error) {
        console.log(JSON.stringify(error.errors, null, 2));
        throw error;
      }
      i++;
    }
    return { "results" : results} ;
  },
});

**Comment by malexanderlim** [comment]
Awesome! Happy to hear that you were able to figure this out with the help of our handy AI Chatbot, Pi! 🙏
