### ISSUE TITLE
[BUG] RSS: New Item in Feed source does not emit new event when Published After Than is NOT specified

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10626]
**Describe the bug**
RSS feed does not emit new event when Published After Than is NOT specified

**To Reproduce**
1. Create a new RSS: New Item in Feed source with the Feed URL: `https://tsn.ua/rss/full.rss` without setting Published After Than prop
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/99b6181d-0b68-4730-a562-565cb0a2ccdc)
2. Wait until there's a new rss item, then click Run Now
3. Observe that there's no event emitted

When I specify Published After Than prop, I can see new event emitted normally
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/3aec5912-b1ae-4b2d-b934-28234ad954a5)

**Expected behavior**
The RSS source should use the source creation time as Published After Than prop and emit new event correctly

**Comment by andrewjschuang** [comment]
We found that the issue occurs from handling a large RSS feed. Without configuring the `Published After` prop, the trigger emits all events from the start. This causes overload, crashing the trigger due to the excessive volume of events

**Comment by andrewjschuang** [comment]
We should make the default value the past 1 or 2 days
cc @malexanderlim wdyt?

**Comment by malexanderlim** [comment]
I think that makes sense Andrew - past day seems reasonable to me.

Can we set the `Published After` to default to CURRENT_DATE - 1 Day, and make it a required field?
