### ISSUE TITLE
bitrix24

### ISSUE THREAD

**Issue by yousseftarek2001** [PipedreamHQ/pipedream#10631]
**bitrix24**

**[Link to developer documentation](https://helpdesk.bitrix24.com/open/1332445/)**

**i want to send from bitrix24 to QuickBooks any invoice i create automatically **

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Duplicated request, we are tracking Bitrix24 here: https://github.com/PipedreamHQ/pipedream/issues/4053
Feel free to follow there, if you'd like
