### ISSUE TITLE
[ACTION] Send message to Basecamp Campfire using Chatbots

### ISSUE THREAD

**Issue by EjDadivas** [PipedreamHQ/pipedream#10645]
Hello, I'd like to request for an action that creates a line for Campfire Chatbots in Basecamp

Here is Basecamp's guide for creating chatbots: [Basecamp Chatbot](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#create-a-chatbot)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by michelle0927** [comment]
@malexanderlim I believe the Basecamp Action, "Create Campfire Message" already accomplishes this.

**Comment by malexanderlim** [comment]
That looks right to me @michelle0927. @EjDadivas - can you confirm if this works for you? Create Campfire Message action that we've built creates a campfire line (https://github.com/basecamp/bc3-api/blob/master/sections/campfires.md#create-a-campfire-line)

**Comment by EjDadivas** [comment]
The Create a Campfire Message action is sending a message from the connected account to the Campfire Chat but not through the Chatbot. Creating a line through a Chatbot is different and requires the `lines_url` of a Chatbot https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md
