### ISSUE TITLE
[BUG] Dropbox Create Shareable Url action not able to create a File path url

### ISSUE THREAD

**Issue by 1101blueli** [PipedreamHQ/pipedream#10699]
Dropbox Create Shareable URL action can only return a downloadable Folder URL 

Here I have input a file path, but result a folder type share URL
![unnamed (3)](https://github.com/PipedreamHQ/pipedream/assets/55223003/571d79f2-c8ea-4716-92c6-b56e4b35b464)

Thanks

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
