### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10698]
### App
Twitter

### Summary:
The media fields are not returned

### Details:
The twitter get DM source is not returning everything correctly. When I run the same command that the source is, my response has the media expansions which includes the URL. In the log I can see the command being run includes the media expansions and url field I highlighted in my test code, but the resulting object coming back from the source does not. I think this is something todo with how totalDatais built within this file. But I cannot see why some of the response payload is left out.  Without the URL, the image cannot be retrieved. The downside is the workaround is to make an added call to dm_events which has an incredibly restrictive rate limit.

### Screenshots:
https://files.slack.com/files-pri/TMZFXGSBF-F06MLBY34EA/image.png
![Screenshot](https://storage.tally.so/private/image-8-.png?id=NDXJDB&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik5EWEpEQiIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcwOTU2NjQyNH0.4tIEcTUVrvqlIZzCNBmVn6Lf7008t3TlcNR7CT1U7uI&signature=c7a8c2ab815313399a971777bfd6c5d52f8549796103efe7ba5278c234cbf83b)

**Comment by ph-cxt** [comment]
![image (7)](https://github.com/PipedreamHQ/pipedream/assets/159645876/aaea040c-6a5b-4f3c-91fc-77d109ada693)
![image (6)](https://github.com/PipedreamHQ/pipedream/assets/159645876/96b73499-75f4-4e8a-8313-0b09a01759a8)
