### ISSUE TITLE
[BUG] Long console.log strings can cause output lines to overlap

### ISSUE THREAD

**Issue by rcmontrose** [PipedreamHQ/pipedream#107]
**Describe the bug**
If you have a very long string output in console.log, the display at the end of the step will appear with some of the output lines overlapping (see attached)

**To Reproduce**
1. Create a console.log string with lots of output. I had 3 console.log lines with Base64 strings of about 100K each.

**Expected behavior**
The console.log printout to be readable.

**Screenshots**
![jibberish_console log](https://user-images.githubusercontent.com/59274633/77971966-b801e380-72b5-11ea-8267-5646515fc92e.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Build 18362.19h1
 - Browser Chrome
 - Version 80.0.3987.149

**Comment by dylburger** [comment]
@rcmontrose are you still observing this? We've made a number of changes to our UI since then, and I was curious if it was still an issue.

**Comment by dylburger** [comment]
Closing, but please let us know if you observe this issue again.
