### ISSUE TITLE
time doctor integration

### ISSUE THREAD

**Issue by aervinnalmiraecomexperts** [PipedreamHQ/pipedream#10712]
**Name of app / service** Time Doctor

**Link to developer documentation** https://timedoctor.redoc.ly/#tag/Projects

**Is lack of support preventing you from building workflows, or do you have a workaround?** yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** I want to use it for trigger or part of the workflow steps. I'm using an API which works fine when I run it from the API site but for some reason, using the same nodejs and the token, it gives me permission error when I run it in Pipedream

**Comment by sergio-eliot-rodriguez** [comment]
Hi @aervinnalmiraecomexperts 

So, Time Doctor was recently added a base integration https://pipedream.com/apps/time-doctor?via=go

Do you mean that this permission error is thrown out when you connect Time Doctor account in Pipedream via this integration?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
