### ISSUE TITLE
[Components] hippo_video

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10752]
# hippo_video
## URLs
- https://help.hippovideo.io/support/solutions/articles/19000095978-api-authorization
#### Prompt
Emits new event when a video generates a new lead. This trigger requires video_id prop.
#### URLs
- https://help.hippovideo.io/support/solutions/articles/19000095984-video-reports-api
#### Prompt
Emits new event when a personalized video is generated. This trigger requires no user-configured props.
#### URLs
- https://help.hippovideo.io/support/solutions/articles/19000095986-generate-personalized-videos-through-api
#### Prompt
Emits new event whenever a visitor watches a video. This trigger requires video_id prop.
#### URLs
- https://help.hippovideo.io/support/solutions/articles/19000095984-video-reports-api
#### Prompt
Sends a personalization request for a specified video. Requires prop: 'video_id' that corresponds to the video to be personalized.
#### URLs
- https://help.hippovideo.io/support/solutions/articles/19000099793-bulk-video-personalization-and-tracking-api
#### Prompt
Uploads a video from a given URL. Required prop: 'video_url', the URL pointing to the video to be uploaded.
#### URLs
- https://help.hippovideo.io/support/solutions/articles/19000100703-import-api
#### Prompt
Creates a new contact in hippo_video. Requires props: 'contact_name' and 'contact_email'. Optional prop: 'contact_phone_number'.
#### URLs
- https://documenter.getpostman.com/view/5278433/Tz5naxpW#a4d73ffe-a2b6-4d68-a1ee-9fbc1417a955

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-hippo_video-dc6aa0474ee341ca9035705bab69a36e

Hi @vunguyenhung, about the video upload action, their API doesn't support uploading a file, only sending a URL
