### ISSUE TITLE
[Components] fogbugz

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10754]
# fogbugz
## URLs
- https://api.manuscript.com/#Introduction
#### Prompt
Emit new event when there's a new case under a specified filter. Note this may not effectively work for filters that generate results too long, or filters with more than 50,000 cases, especially if your FogBugz site is running Ocelot. Required props: FilterId
#### URLs
- https://api.manuscript.com/#List-Filters
- https://api.manuscript.com/#List-Cases
#### Prompt
Emit new event instantaneously when something significant happens to a case.
#### URLs
- https://api.manuscript.com/#View-a-Case
#### Prompt
Emit new event when a new person or a user is created in FogBugz. It effectively tracks the addition of new users in the system.
#### URLs
- https://api.manuscript.com/#List-People
#### Prompt
Creates a new case on FogBugz. Please add all optional props.
#### URLs
- https://api.manuscript.com/#Create-a-New-Case
#### Prompt
Edits an existing user in FogBugz. Required prop: userID as ixPerson. Please add all off the optional props. 
#### URLs
- https://api.manuscript.com/#Edit-Person
#### Prompt
Gets a list of projects in FogBugz. No required props. This can be used to quickly view all projects and their details.
#### URLs
- https://api.manuscript.com/#List-Projects

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-fogbugz-11630d25a85140459a408e593eb89d89

Hi @vunguyenhung, their webhook only sends a new message when you update some information, updating the status won't fire the source.

**Comment by luancazarine** [comment]
> Hey @luancazarine, are you able to test the source successfully on your side? I've both resolved and updated the case name but no event emitted. Still the same issue

Hi @vunguyenhung, here is the test
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/d40f3d9c-5e66-43e1-83b0-99e4517f5431)
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/4672e699-fff8-445d-8b65-7a8dcb098e30)
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/48ac55f9-541d-4ae7-9c6e-30f642feb40d)

**Comment by luancazarine** [comment]
> Hi @luancazarine, I still face the same issue for the latest code as in the test report. Would you mind checking if you have pushed all changes?

I'm so sorry about that @vunguyenhung. Now it's right!
