### ISSUE TITLE
[Components] google-cloud-translate

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#10778]
# google_cloud_translate
## URLs
- https://cloud.google.com/translate/docs/basic/translating-text
#### Prompt
To translate text, make a POST request and provide JSON in the request body that identifies the language to translate to (target) and the text to translate (q). Please use async options to provide a dropdown for supported languages.
#### URLs
- https://cloud.google.com/translate/docs/basic/discovering-supported-languages

**Comment by michelle0927** [comment]
@malexanderlim @ctrlaltdylan Is this issue resolved by https://github.com/PipedreamHQ/pipedream/pull/10809?
