### ISSUE TITLE
[Components] sendy

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10775]
# sendy
## URLs
- https://sendy.co/api
#### Prompt
Adds a new subscriber or updates existing subscriber's details for a specific list. Required props include 'list_id' which is the ID of the target list, and 'email' as subscriber's email. Optional props can be any other subscriber information fields like 'name', 'country', etc.
#### URLs
- https://sendy.co/api#subscribe
#### Prompt
Creates a new draft campaign ready to be filled in with details. Required prop is 'from_name', 'from_email', 'reply_to', 'title', 'subject', 'html_text', 'brand_id', 'track_opens' and 'track_clicks'. Optional props can include 'plain_text', 'list_ids', 'segment_ids', 'exclude_list_ids', 'exclude_segments_ids', 'query_string', 'schedule_date_time' and 'schedule_timezone'. The prop 'send_campaign' will be always 1 
#### URLs
- https://sendy.co/api#create-send-campaigns
#### Prompt
Removes a subscriber from a specified list. Required props include 'list_id' and 'email' to identify the subscriber to be removed.
#### URLs
- https://sendy.co/api#unsubscribe

**Comment by sergio-eliot-rodriguez** [comment]
App

Sendy
Context front #5396
https://sendy.co/api
Triggers

    New Subscriber
    New Campaign

Actions

    Send a Campaign
    Add a Subscriber
    Delete a Subscriber
