### ISSUE TITLE
Issue with card expiration date form

### ISSUE THREAD

**Issue by AndreaVacca** [PipedreamHQ/pipedream#1079]
Hi I manage the site https://prodotti-cannabis.it/ . 

I'm having a small issue with the Viva Wallet for Woocommerce plugin. Some of the customers find themselves unable to input the card expiration date correctly. Basically the "/" between the month and year digits doesn't show (ex.: customer types 01/22 and the form shows 0122). The system considers it as an incorrect date format. However, if the date is copy-pasted from a text file or something like that, it shows and it's accepted as correct.

**Comment by dylburger** [comment]
@AndreaVacca is your question related to an issue you're seeing in https://pipedream.com?
