### ISSUE TITLE
[APP]ServerAvatar

### ISSUE THREAD

**Issue by cuongtran-talent** [PipedreamHQ/pipedream#108]
**Name of app / service**
ServerAvatar

**Link to developer documentation**
https://serveravatar.com/api-docs/endpoint/application-domain/create.html
Bear Authorize Header

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Create an application domain (https://serveravatar.com/api-docs/endpoint/application-domain/create.html)

**Comment by todsac** [comment]
@cuongtran-talent - I have integrated ServerAvatar.  Would you be open to testing and confirming the integration works?
