### ISSUE TITLE
[BUG] New Bookmark Source in Raindrop is retrieving old bookmarks too

### ISSUE THREAD

**Issue by EjDadivas** [PipedreamHQ/pipedream#10807]
I deployed this workflow again and added 1 bookmark in my raindrop account and it still retrieved old bookmarks,
Related to this issue: [#10697](https://github.com/PipedreamHQ/pipedream/issues/10697)

![image](https://github.com/PipedreamHQ/pipedream/assets/99721216/d4ca455f-328b-4602-b554-ec2ad4d5b253)

**Comment by EjDadivas** [comment]
Hi @vunguyenhung, I think to effectively reproduce this, first, you have to have a raindrop account that has saved bookmarks from maybe months or years ago.

**Comment by EjDadivas** [comment]
I was thinking of maybe including the created date of the bookmark in the query paramaters when retrieiving all bookmarks and would look like this. But instead we replace it with the year and month that this workflow has been deployed.
```
https://api.raindrop.io/rest/v1/raindrops/0?search=created%3A>2024-03%20
```

https://developer.raindrop.io/v1/raindrops/multiple
https://help.raindrop.io/using-search/#operators

**Comment by EjDadivas** [comment]
May I know how to get the latest deployment date?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
