### ISSUE TITLE
SP-API (Amazon Selling Partner API)

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10814]
### App
SP-API (Amazon Selling Partner API)
https://developer.amazonservices.com/

### Sources
I'm just getting started with Pipedream and SP-API so I'm not sure of the details. We have a descent size seller account that does $300K-$500K in sales each month. Most workflows would be triggered on a schedule. I'd also like to be triggered when a new inbound shipments to FBA are created.

### Actions
Need to make requests from this api to get things like sales orders using various search criteria like date ranges and buyer email and order id. Requests for inventory levels at FBA fulfillment centers will be needed. We'll need to save formatted data that's collected from several sources and then provide charting style dashboards to visualize this data. Not sure yet what we'll use as a display app but it will likely be something like smartsheets or clickup or another saas app that has good charting features. Most functionality will focus on managing on-hand stock levels and supply chain levels that are constantly depleted as sales occur and inventory is move along the chain. This will also provide the tools needed to drive automated just-in-time reordering and production of the right items at the right time and of the right quantities.

**Comment by ActiveHawk** [comment]
Please keep in mind that the Amazon Seller API used to be called Amazon MWS (before being renamed to SP-API) and there are still lots of old how-to content out there. Also, just late 2023 Amazon simplified the authentication process of SP-API and stopped requiring configuration of AWS IAM credentials and requests no longer have to be signed.  Here is a good link on the steps required now. https://youtu.be/gp5kTI8I3pU?si=HwEGD3-eJJW-Q8je

**Comment by ActiveHawk** [comment]
How to make SP-API requests in 2024 - Big Update from Amazon https://youtu.be/gp5kTI8I3pU?si=HwEGD3-eJJW-Q8je

**Comment by sergio-eliot-rodriguez** [comment]
I'm closing this one because it is duplicated, apparently job is mostly done per https://github.com/PipedreamHQ/pipedream/issues/1938
