### ISSUE TITLE
[one drive]

### ISSUE THREAD

**Issue by raj-exitando** [PipedreamHQ/pipedream#10824]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
One Drive is integrated at https://pipedream.com/apps/microsoft-onedrive?via=go
but let us know if you need a One Drive based component not supported yet.

**Comment by raj-exitando** [comment]
Need a document for connecting between one drive and Talend
  
  
  

----------------------------------------

**Comment by sergio-eliot-rodriguez** [comment]
There are many document related components for One Drive: 

actions: https://pipedream.com/apps/microsoft-onedrive#popular-microsoft-onedrive-actions

triggers: https://pipedream.com/apps/microsoft-onedrive#popular-microsoft-onedrive-triggers

check out if the one you need is there.

to create logic that uses One Drive and Talend you'll need to create a workflow, here is a guide on how to build workflows: https://pipedream.com/docs/workflows

**Comment by raj-exitando** [comment]
Thanks
  
  
  

----------------------------------------
