### ISSUE TITLE
[APP] Harmonic

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#10827]
**Name of app / service**
Harmonic

**Link to developer documentation**

https://console.harmonic.ai/docs/api-reference/introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Enrich company
Enrich person

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by email, copied sergio@pk integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Harmonic has been integrated https://pipedream.com/apps/harmonic?via=go

**Comment by sergio-eliot-rodriguez** [comment]
1 week&nbsp; follow up

**Comment by sergio-eliot-rodriguez** [comment]
14 days follow up

**Comment by malexanderlim** [comment]
@sergio-eliot-rodriguez please disable this automation as it looks to be integrated!

**Comment by sergio-eliot-rodriguez** [comment]
Disabled
