### ISSUE TITLE
[IMPROVEMENT] Notion: Find Page by Title - Exact Match

### ISSUE THREAD

**Issue by RonNekrash** [PipedreamHQ/pipedream#10836]
**Is there a specific app this action is for?**
Notion

**Please provide a link to the relevant API docs for the specific service / operation.**
This action will get the title of page I'm looking for by the exact title name.
The "Find Page" action that exists returns page that the provided string in contained in the page title, and this provides bad results. (cannot return the right page when the title values are SHA-256 hashes)

please help.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
