### ISSUE TITLE
[ACTION] Apollo.io

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#10847]
**Is there a specific app this action is for?**

Apollo.io

**Please provide a link to the relevant API docs for the specific service / operation.**
Search for Contacts: https://apolloio.github.io/apollo-api-docs/?shell#search-for-contacts
Search for Accounts: https://apolloio.github.io/apollo-api-docs/?shell#search-for-accounts
Search for a Sequence: https://apolloio.github.io/apollo-api-docs/?shell#searching-for-sequences

**Comment by malexanderlim** [comment]
Merging with https://github.com/PipedreamHQ/pipedream/issues/11090.
