### ISSUE TITLE
[Components] blazemeter

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10841]
# blazemeter
## URLs
- https://api.blazemeter.com/functional/#introduction
- https://api.blazemeter.com/functional/#basics
- https://api.blazemeter.com/functional/#projects

#### Prompt
List projects from a specified workspace. https://api.blazemeter.com/functional/#projects-list
#### Prompt
List all workspaces associated with the specified account. https://api.blazemeter.com/functional/#workspaces-list
#### Prompt
Create the project with the following props: name, description and workspaceId. https://api.blazemeter.com/functional/#create-a-project

**Comment by lcaresia** [comment]
@vunguyenhung 
![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/1fb38133-6d6a-42a7-bafa-7d53d5e28fd8)
