### ISSUE TITLE
[APP] Microsoft Power Bi

### ISSUE THREAD

**Issue by Mukul0208** [PipedreamHQ/pipedream#10849]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @Mukul0208 thanks for the request.

We have Power Bi integrated https://pipedream.com/apps/microsoft-power-bi?via=go

Let us know if you see what you need there. Scroll down to, and expand Popular Microsoft Power BI Triggers, and Popular Microsoft Power BI Triggers sections to see if the components required are ready.
