### ISSUE TITLE
[Components] dux-soup

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10845]
# dux-soup
#### Prompt
Queues a connection request to actively connect with a targeted profile. Requires target profile's ID as a mandatory prop.
#### Prompt
Queues a direct message that will be sent to the targeted profile. Requires target profile's ID and the message as a mandatory prop.
#### Prompt
Queues a profile save action to store the targeted profile as a lead. Requires target profile's ID as a mandatory prop.

**Comment by malexanderlim** [comment]
Please ping @malexanderlim for account information when picked up!
