### ISSUE TITLE
[Zoho Notebook]

### ISSUE THREAD

**Issue by peshak2008** [PipedreamHQ/pipedream#10848]
**Name of app / service**
Integrate with Zoho notebook

**Link to developer documentation**
I could not find their api link. I see Make integrate with it, so I thought it might exist
**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have workaround
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
create note. Thanks!

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the request @peshak2008 

Apparently, Zoho Notebook doesn't have an API as of writting.

https://www.zoho.com/developer/rest-api.html

**Comment by malexanderlim** [comment]
Good point @peshak2008 - they may have an unlisted API. I've reached out to their team for additional information.

**Comment by peshak2008** [comment]
Thanks for the replies. Agreed, I could not either find API page. I had a feeling they are using a tool called Zoho Flow from quick search, but did not double check. Hope this helps.

**Comment by peshak2008** [comment]
Feel free to close the ticket if you decide not to pursue this effort. All good.

**Comment by malexanderlim** [comment]
I've engaged the Zoho Notebook team. Stay tuned!

**Comment by malexanderlim** [comment]
The base integration is ready. The team will work on components next!

**Comment by peshak2008** [comment]
Thanks for the quick feature addition. Cannot wait to try it out.
