### ISSUE TITLE
E-gmail

### ISSUE THREAD

**Issue by lshsusbak** [PipedreamHQ/pipedream#10855]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @Ishsusbak

Thanks for the request, is this the Gmail you are looking for https://pipedream.com/apps/gmail ?

Otherwise could you please provie the apps website you are looking for on Pipedream?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
