### ISSUE TITLE
i want to send payment details on  esp32 board

### ISSUE THREAD

**Issue by arjunrobozzlab** [PipedreamHQ/pipedream#10858]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @arjunrobozzlab 

Thanks for the request. Can you please provide the related application's website?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
