### ISSUE TITLE
GOOGLE DRIVE: NEW OR MODIFIED FILES

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10850]
### App
GOOGLE DRIVE: NEW OR MODIFIED FILES

### Summary:
Source does not receive events

### Details:
The source does not receive events when a new file is added to the selected folder on a shared Google drive

### Screenshots:
No screenshots included

**Comment by malexanderlim** [comment]
Not enough information to troubleshoot.
