### ISSUE TITLE
[APP] fly.io

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#10902]
**Name of app / service**
fly.io

**Link to developer documentation**
https://fly.io/docs/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by thomasfr** [comment]
For me i would like to see trigger integrations for machine state changes like `started`, `stopped`, `deleted`. I dont know if the api is revealing this information but it would be great to be able to distinguish between a manual triggered `stop` or when the machine automatically gets `suspended`.
In addition to that it would be great to be able to get a trigger for scale in / out events per application and triggers for activities on fly.io

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/fly-io :)

**Comment by sergio-eliot-rodriguez** [comment]
Hi @thomasfr 

Thanks for your request. We rolled out some triggers and actions, does any of those work for you?

IF you don't see what you need, would you mind flagging a [new issue](https://github.com/PipedreamHQ/pipedream/issues/new?assignees=&labels=enhancement%2C+good+first+issue%2C+help+wanted%2C+trigger+%2F+source&projects=&template=new-trigger---event-source.md&title=%5BTRIGGER%5D) specifically for them?

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/2c3ffac5-0c19-43d6-a672-c11ca30986aa)
