### ISSUE TITLE
[ACTION] Salesforce Integration -> look for a contact by a specific field, if OK "do nothing", if KO "create new contact"

### ISSUE THREAD

**Issue by tomilagom** [PipedreamHQ/pipedream#1098]
Is it possible to look-up an object?

**Comment by dylburger** [comment]
Hi @tomilagom , would you be able to format a SOQL query to fetch the object you're looking for. We provide a **SOQL Search** action that allows you to run a SOQL query against the connected instance:

<img width="438" alt="Screen Shot 2021-03-18 at 12 52 26 PM" src="https://user-images.githubusercontent.com/242668/111689157-ea6b6000-87e8-11eb-89b3-54c333aac380.png">

Then, you can [run any Node.js code](https://pipedream.com/docs/workflows/steps/code/) to deal with the response from that step. I'd recommend adding the Salesforce **Create Contact** action below the **SOQL Search** action, then click into the code for the Create Contact action, modifying it to add a conditional statement that implements the logic you describe, loosely:

```javascript
if (contact exists from SOQL search step) {
  // run the original code in the Create Contact action
}
```

Let us know if that helps.

**Comment by tomilagom** [comment]
Great thank you!
