### ISSUE TITLE
[BUG] Illumidesk: On connection popup, remove API Key page link to avoid confusion

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10996]
**Describe the bug**
On Illumidesk connection popup, the API Key page link is `https://pipedreamdev.illumidesk.com/app/edit-campus/api-key` that leads to pipedreamdev campus
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/df305f6c-080e-474d-85d1-7b8e6f79bd57)

As every user has different subdomain, we need to remove the API Key page link to avoid confusion. I think the current instruction is clear enough

**Comment by malexanderlim** [comment]
Thanks for the suggestion Leo. All set here!
