### ISSUE TITLE
[ACTIONS] DynamoDB actions

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#110]
Reading and writing to a table

**Comment by sergioeliot2039** [comment]
Update Global Table
Action: https://pipedream.com/actions/a_elirXO/edit
Workflow: https://pipedream.com/@sergio/dynamodb-update-global-table-p_JZCy29d/edit
Describe Global Table Settings
Action: https://pipedream.com/actions/a_a4ir6X/edit
Workflow: https://pipedream.com/@sergio/dynamodb-describe-global-table-settings-p_xMCNa5l/edit
Restore Table From Backup
Action: https://pipedream.com/actions/a_OOibeQ/edit
Workflow: https://pipedream.com/@sergio/dynamodb-restore-table-from-backup-p_NMC9MLp/edit
Delete Backup
Action: https://pipedream.com/actions/a_NqilBe/edit
Workflow: https://pipedream.com/@sergio/dynamodb-delete-backup-p_gYCMyLG/edit
Describe Global Table
Action: https://pipedream.com/actions/a_G1ilak/edit
Workflow: https://pipedream.com/@sergio/dynamodb-describe-global-table-p_vQCg1vJ/edit
Create Global Table
Action: https://pipedream.com/actions/a_A6iWgX/edit
Workflow: https://pipedream.com/@sergio/dynamodb-create-global-table-p_brCLgYY/edit
Untag Resource
Action: https://pipedream.com/actions/a_3Li6Gw/edit
Workflow: https://pipedream.com/@sergio/dynamodb-untag-resource-p_jmCvoWk/edit
Tag Resource
Action: https://pipedream.com/actions/a_NqilQe/edit
Workflow: https://pipedream.com/@sergio/dynamodb-tag-resource-p_MOC3Yxx/edit
Export Table To Point In Time
Action: https://pipedream.com/actions/a_3Li6gw/edit
Workflow: https://pipedream.com/@sergio/dynamodb-export-table-to-point-in-time-p_ljCbZyY/edit
Create Backup
Action: https://pipedream.com/actions/a_nji8E6/edit
Workflow: https://pipedream.com/@sergio/dynamodb-create-backup-p_q6CbMbq/edit
Execute Statement
Action: https://pipedream.com/actions/a_l0i7r1/edit
Workflow: https://pipedream.com/@sergio/dynamodb-execute-statement-p_pWCYYjD/edit
Put Item
Action: https://pipedream.com/actions/a_RAiXL5/edit
Workflow: https://pipedream.com/@sergio/dynamodb-put-item-p_yKCJJp1/edit
Delete Table
Action: https://pipedream.com/actions/a_vgipVw/edit
Workflow: https://pipedream.com/@sergio/dynamodb-delete-table-p_ZJCbqDK/edit
Update Table
Action: https://pipedream.com/actions/a_nji8GN/edit
Workflow: https://pipedream.com/@sergio/dynamodb-update-table-p_YyCooGL/edit
Update Table
Action: https://pipedream.com/actions/a_nji8GN/edit
Workflow: https://pipedream.com/@sergio/dynamodb-update-table-p_JZCyyPx/edit
Update Time To Live
Action: https://pipedream.com/actions/a_B0imob/edit
Workflow: https://pipedream.com/@sergio/dynamodb-update-time-to-live-p_3nCaav6/edit
Scan
Action: https://pipedream.com/actions/a_bKirwV/edit
Workflow: https://pipedream.com/@sergio/dynamodb-scan-p_G6C662P/edit
Query
Action: https://pipedream.com/actions/a_2wieBa/edit
Workflow: https://pipedream.com/@sergio/dynamodb-query-p_o7CNNB9/edit
Execute Statement
Action: https://pipedream.com/actions/a_a4irYb/edit
Workflow: https://pipedream.com/@sergio/dynamodb-execute-statement-p_pWCYYjD/edit
Describe Table
Action: https://pipedream.com/actions/a_G1ilAg/edit
Workflow: https://pipedream.com/@sergio/dynamodb-describe-table-p_7NCllmD/edit
List Tables
Action: https://pipedream.com/actions/a_A6iWBv/edit
Workflow: https://pipedream.com/@sergio/dynamodb-list-tables-p_jmCvvqA/edit
Create Table
Action: https://pipedream.com/actions/a_dvirB4/edit
Workflow: https://pipedream.com/@sergio/dynamodb-create-table-p_JZCyylM/edit
Update Item
Action: https://pipedream.com/actions/a_WYi4nE/edit
Workflow: https://pipedream.com/@sergio/dynamodb-update-item-p_ljCbbGl/edit
Delete Item
Action: https://pipedream.com/actions/a_Mdiem8/edit
Workflow: https://pipedream.com/@sergio/dynamodb-delete-item-p_6lC11Ap/edit
Get Item
Action: https://pipedream.com/actions/a_A6iWNG/edit
Workflow: https://pipedream.com/@sergio/dynamodb-get-item-p_o7C8M7/edit
