### ISSUE TITLE
[Components] vybit

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11028]
# vybit
## URLs
- https://www.vybit.net/#trigger
#### Prompt
Send a Vyb to a specified target. Please use async options to list vybs, and have additional options with message, image url, link url and log.

**Comment by malexanderlim** [comment]
[Vybit Integration.pdf](https://github.com/PipedreamHQ/pipedream/files/14643000/Vybit.Integration.pdf)

Additional docs here^
