### ISSUE TITLE
[APP] 2markdown.com: extract website content

### ISSUE THREAD

**Issue by ChristianSch** [PipedreamHQ/pipedream#11025]
**Name of app / service**
2markdown.com

**Link to developer documentation**
https://2markdown.com/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**
The workaround is to implement the API call on your own.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Whatever the user can think of.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @ChristianSch 

Are you 2markdown developer?

is there a good, squared logo we can use for 2markdown.

I tried twitter and I see it has your profile pic.

**Comment by ChristianSch** [comment]
Hi @sergio-eliot-rodriguez ,

Somehow this slipped my radar, sorry! Would this suffice?

![apple-touch-icon-180x180](https://github.com/PipedreamHQ/pipedream/assets/6138133/63b1054c-5c49-4cfa-8937-46fc35b33aa8)

**Comment by malexanderlim** [comment]
All set!

**Comment by sergio-eliot-rodriguez** [comment]
Base integration at -- https://pipedream.com/apps/2markdown

Feel free to contribute on component developments with this guide -- https://pipedream.com/docs/components#sharing-components otherwise our developers will get to build this soon.

**Comment by ChristianSch** [comment]
Thank you folks, appreciate that!
