### ISSUE TITLE
[Components] zoho-notebook

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11039]
# zoho-notebook
#### Prompt
Emit new event when an Audio Card is created. No required props.
#### Prompt
Emit new event when a Checklist Card is created. No required props.
#### Prompt
Emit new event when a note card is created in a specific notebook. A notebook prop should be configured to notify the exact notebook which note card belongs.
#### Prompt
Creates a new notebook. Required props: 'notebook_name' - the name of the new notebook. Optional props: 'color' - the color of the notebook cover, 'description' - a brief summary of what the notebook is about.
#### Prompt
Creates a new notecard within a specified notebook. Required props: 'notebook_id' - the identifier of the notebook where the note should be created, 'notecard_name' - the title of the notecard. Optional props: 'content' - the main content of the notecard, 'tags' - any tags that should be associated with the notecard for easy searching.
#### Prompt
Retrieve a list of all notebooks created by the user. No required props for this action. Optional props: 'tag' - filter out notebooks that do not have the given tag.

**Comment by malexanderlim** [comment]
Please ping @malexanderlim for documentation (private)
