### ISSUE TITLE
[SOURCE] Microsoft OneDrive: New File

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1103]
**Describe the event source. What app, what event?**

I'd like to trigger a workflow when a new file is added to my OneDrive drive. Optionally, I want to watch a specific folder. If the folder is blank, I'd like to watch for any new file in my drive.

Otherwise, I'd like the source to operate like the Dropbox - New File source (e.g. I'd like to implement the **Recursive** option, and other props like download URL- in general we should attempt to map these props to their equivalent functions in OneDrive). 

If there's any other OneDrive-specific logic that Zapier, Integromat or other triggers implement that we should here, we should implement that functionality, as well.

**Comment by dannyroosevelt** [comment]
@dylburger do you have any state on this? It doesn't look like it's been reviewed, but do you know if it's in progress?

**Comment by dannyroosevelt** [comment]
@js07 this was originally written by Jay, who is no longer working with us, and Jonathon had done most of the review (he's also not working much w/ us lately), but it should be ready for another review. If there are changes to make here, feel free to just implement them yourself and drop it in "Ready for QA" when you're done.

**Comment by dannyroosevelt** [comment]
@js07 this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)

**Comment by dannyroosevelt** [comment]
Not sure why this tagged Jacob -- should've tagged @vellames-turing -- this is ready to go
