### ISSUE TITLE
[APP] Canvas LMS

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1106]
Hello team - loving building with Pipedream - thank you.

We wish to build with the Canvas LMS API. This is a learning management system used by our school and many other institutes all over the world.

Their API documentation is here:
https://canvas.instructure.com/doc/api/file.oauth.html

Happy to do all the testing and contribute some actions.

Many thanks again.

Kind regards,
Paul

_Originally posted by @accellier in https://github.com/PipedreamHQ/pipedream/discussions/1105_

**Comment by todsac** [comment]
@accellier - are you open to helping us test this integration?  https://pipedream.com/apps/canvas

**Comment by accellier** [comment]
@todsac yes absolutely! Apologies for late response - I missed the notification.

**Comment by accellier** [comment]
@todsac I couldn't see anything at that URL.

**Comment by todsac** [comment]
Apologies, it was admin only.  Please try again.

**Comment by todsac** [comment]
Also, are you in our Slack?  It may be easier to DM there for testing.

**Comment by dylburger** [comment]
@accellier I just wanted to check in to see if you had a chance to test this integration after Tod made it available. Let us know if you see any issues and we can take a look!
