### ISSUE TITLE
[APP] Baserow

### ISSUE THREAD

**Issue by gehtalles-de** [PipedreamHQ/pipedream#1107]
Baserow // baserow.io

https://baserow.io/docs/getting-started%2Fapi

It's possible to get it working without the app integration but it would be nice to have

It would be nice to be able to use all triggers that Airtable has.

An integration would make this beautiful project more known and maybe push their development :)

**Comment by dylburger** [comment]
Great, thank you for the request @gehtalles-de . We'll take a look ASAP.

**Comment by todsac** [comment]
@gehtalles-de - Baserow has been integrated.  Please let us know if this works for you.  Would you be interested in developing the relevant triggers for this app?

https://pipedream.com/apps/baserow

**Comment by dylburger** [comment]
@gehtalles-de did you have a chance to test the integration? I just wanted to make sure it was working OK for you.
