### ISSUE TITLE
Params in type string but instead it needs to be type of array [Sendinblue app integration]

### ISSUE THREAD

**Issue by zeshhaan** [PipedreamHQ/pipedream#1108]
**Describe the bug**
`ListID` param in Sendinblue app integration is declared as a type of string but instead it should be an array of integers

**To Reproduce**
1. Go to choose an action
2. Search and Click on the app - Sendinblue, and integrate it to the workflow
3. Scroll down to the `listID` in params section, enter a number
4. See Error  
  

![image](https://user-images.githubusercontent.com/34814964/111900959-5bb24980-8a5b-11eb-8808-622ddbf548aa.png)

**Expected behavior**
  
Instead of string, `listID` field should be of type array. 
Attaching the corrected schema which ran successfully.
![image](https://user-images.githubusercontent.com/34814964/111901036-b21f8800-8a5b-11eb-85e1-e99da15a2dab.png)

[link](https://developers.sendinblue.com/) to their api documentation

**Comment by dylburger** [comment]
Thank you for reporting @zeshhaan . This is actually a community-developed action created by @cuongtqtran. Cuong, does this look like something you could fix?

**Comment by cuongtqtran** [comment]
I fixed it, thanks for report! @zeshhaan
