### ISSUE TITLE
Pipedrive e alexa

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11092]
### App
Pipedrive e alexa
https://pipedream.com/@farinazzo/projects/proj_JPsNArg/get-simulation-results-with-amazon-alexa-api-on-new-deal-from-pipedrive-api-p_xMCyWZa/build

### Sources
Gostaria de integrar o pipedrive com a alexa.

### Actions
Integração de atividade do pipedrive com a alexa

**Comment by sergio-eliot-rodriguez** [comment]
Both apps are integrated 

https://pipedream.com/apps/pipedrive

https://pipedream.com/apps/amazon-alexa

And both have components available, there are triggers for Pipedrive. 

Including trigger on new deal in Piprdrive

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/67805805-980f-4142-8028-0dd34f8e1dc8)


As well as Get Simulation results in Alexa

https://pipedream.com/apps/amazon-alexa/actions/get-simulation-results

User wants help with a workflow.
