### ISSUE TITLE
[BUG] Zoho Creator Trigger returning Error 2930 when loading reports

### ISSUE THREAD

**Issue by esnyder-rve** [PipedreamHQ/pipedream#11091]
**Describe the bug**
Error 2930 is returned from Zoho when trying to select a report from an application for the Zoho Creator Trigger.

**To Reproduce**
1. Add Zoho Creator Trigger (either "New Record" or "New or Updated Record"
2. Add or select account
3. Set polling interval
4. Select application
5. Attempt to select report

**Expected behavior**
A list of reports for the application should be listed.

**Screenshots**
![image](https://github.com/PipedreamHQ/pipedream/assets/61027950/9e4e704f-61b3-43b5-975b-e3df7eee8648)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser: Vivaldi (Chromium-based)
 - Version: 6.6.3271.50

**Additional context**
First time using Pipedream.

**Comment by michelle0927** [comment]
Hi, @esnyder-rve. I haven't been able to reproduce the error you're seeing. Can you verify that your Creator App has API Access enabled under User Permissions?

<img width="874" alt="Screenshot 2024-03-25 at 5 23 45 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/c7de00d7-42b9-4ebb-b950-6964db96771e">

**Comment by esnyder-rve** [comment]
@michelle0927 Yes, both the read and write permissions have API access enabled.
Screenshot of the read permissions:
![image](https://github.com/PipedreamHQ/pipedream/assets/61027950/58361b4e-ed7f-435e-bf62-ebda33f06e78)

**Comment by michelle0927** [comment]
@esnyder-rve Is the account you log into a "Super Admin"? I was able to reproduce the 2930 error by creating and using a separate user/administrator account. Even when the user is set as "Administrator", I'm unable to load the list of Reports. Using the "Super Admin" account, I'm able to list the Reports.

<img width="568" alt="Screenshot 2024-03-27 at 12 25 10 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/235218f6-7f5e-4437-a824-c05b4bad0599">

**Comment by esnyder-rve** [comment]
Ok, that is what the problem is. The application is under the Super Admin account, but I just have a regular admin account.

**Comment by esnyder-rve** [comment]
Just found out we are using Creator 5

**Comment by michelle0927** [comment]
@esnyder-rve I discovered where the bug was that's causing this error. I've created a PR to fix it, and you can follow it's progress here: https://github.com/PipedreamHQ/pipedream/pull/11203
