### ISSUE TITLE
[Components] recharge

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11103]
# recharge
## URLs
- https://developer.rechargepayments.com/2021-11
#### Prompt
Emits new event whenever a new customer is registered. Props include customer_id (Required), customer_email (Optional).
#### Prompt
Emits new event whenever a new order is placed. Props include order_id (Required), customer_id (Optional), product_id (Optional).
#### Prompt
Emits new event whenever a new subscription is purchased by a customer. Props include customer_id (Required), subscription_id (Required), product_id (Optional).
#### Prompt
Creates a new subscription. Required props: customer-id, product-id. Optional props: address-id, discount-id. Use this to allow a customer to subscribe to a product.
#### Prompt
Cancels an existing subscription. Required prop: subscription-id. Use this to cancel a previously active subscription.
#### Prompt
Updates an existing customer. Required prop: customer-id. Optional props: name, email, address-id. Use this to update the details of an existing customer.

**Comment by GTFalcao** [comment]
@vunguyenhung I was not able to get a valid 'External Variant ID' for 'Create Subscription', as the only product listed does not have variants. However, I added async options for this to facilitate usage for actual users. All other issues were also fixed and tested.
