### ISSUE TITLE
[Components] teamioo

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11101]
# teamioo
## URLs
- https://demo.teamioo.com/teamiooAPI
#### Prompt
Emit new event when a new URL is bookmarked in a group. You need to configure the group prop.
#### URLs
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,groups,-Returns%20all%20open
- https://demo.teamioo.com/teamiooAPI#:~:text=GET%20Endpoints-,/bookmarks,-Returns%20latest%20group
#### Prompt
Emit new event when a new contact (client) is added to a group. Required props is groupId.
#### URLs
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,groups,-Returns%20all%20open
- https://demo.teamioo.com/teamiooAPI#:~:text=%5B2%5D-,/clients,-Returns%20latest%20group
#### Prompt
Emit new event when a new member is added to a group. Required props: groupId.
#### URLs
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,groups,-Returns%20all%20open
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,groupMembers,-Returns%20members%20of
#### Prompt
Saves a website URL to the bookmarks. The props, 'url' and 'bookmark_type' are required. 'bookmark_type' can either be 'personal' or 'group'. An optional prop 'title' can be included to give the bookmark a custom name.
#### URLs
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,groups,-Returns%20all%20open
- https://demo.teamioo.com/teamiooAPI#:~:text=%5B3%5D-,Creating%20content,-POST%20Endpoints
#### Prompt
Creates a new calendar event. The props, 'event_title', 'start_time', 'end_time' and 'event_type' are required. 'event_type' can be 'personal', 'office', or 'group'. An optional prop 'location' can be added to specify the meeting place.
#### URLs
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,calEventTypes,-Returns%20all%20available
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,users,-Returns%20all%20platform
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,groups,-Returns%20all%20open
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,calEvents,-Creates%20a%20new
#### Prompt
Creates a new task. The props, 'task_title' and 'task_type' are required. 'task_type' can be 'personal' or 'group'. Optional props are 'due_date', 'assigned_to' and 'priority_level' to specify due date, whom the task is assigned to and the urgency of the task respectively.
#### URLs
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,groups,-Returns%20all%20open
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,users,-Returns%20all%20platform
- https://demo.teamioo.com/teamiooAPI#:~:text=/-,tasks,-Creates%20a%20new

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-teamioo-05641d3f699f4798b7ddbc25c889403c

Hi @vunguyenhung, If you don't choose a specific group, it will trigger for any group
