### ISSUE TITLE
[Components] confluence

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11104]
# confluence
## URLs
- https://developer.atlassian.com/cloud/confluence/rest/v1/
#### Prompt
Emit new event whenever a new page or blog post is created. Required props: Space key to specify space.
#### Prompt
Emit new event when a blog post is created or updated. Required props: Space key. Optional props: Specific blog post key for filtering.
#### Prompt
Emit new event when a page is created or updated. Required props: Space key. Optional props: Specific page key for filtering.
#### Prompt
Creates a new page or blog post on Confluence. Needs props for post type, title, and content. Optional props are space, parent page, and labels.
#### Prompt
Removes a page or blog post from Confluence by its ID. Needs props for post type and post ID. Use with caution, the action is irreversible.
#### Prompt
Updates a page or blog post on Confluence by its ID. Needs props for post type, post ID, and new content. Optional props are new title, space, and parent page.

**Comment by michelle0927** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-confluence-28b610a0410d41aaa05e742c59dd4352

- For "Create Post", the API does not support props for "Parent Page" or "Labels". https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-blog-post/#api-blogposts-post

- For listing posts, the API allows retrieving posts with the status `current`, `deleted`, or `trashed`, but I don't see a way to list `draft` posts. https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-blog-post/#api-blogposts-get
