### ISSUE TITLE
[BUG] Twitch: Streams by Streamer (Instant) source never emits.

### ISSUE THREAD

**Issue by ItsRauf** [PipedreamHQ/pipedream#1112]
**Describe the bug**
The Streams by Streamer (Instant) source never emits.

**To Reproduce**
1. Go to Sources.
2. Add a new source and choose the `Twitch: Streams by Streamer (Instant)` source.
3. Add username of streamer (ex. ludwig, ninja, philza, etc.)
4. Watch the source never emit an event.

**Expected Behavior:**
The source should emit an event.

**Actual Behavior:**
The source never emits an event.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome
 - Version: 79.0

**Comment by dylburger** [comment]
Thanks @ItsRauf , I can reproduce and we're looking into it.
