### ISSUE TITLE
[Components] leiga

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11135]
# leiga
## URLs
- https://apidog.com/apidoc/shared-5a741107-c211-410f-880c-048d1917c984/api-3741819
#### Prompt
Emit new event when there is a new issue in Leiga. Props: You are required to provide the project in which you wish to monitor for new issues.
####URLs
- https://apidog.com/apidoc/shared-5a741107-c211-410f-880c-048d1917c984/api-3741892
#### Prompt
Emit new event when an existing issue is updated in Leiga. Props: You need provide the specific issue you want to track for updates.
####URLs
- https://apidog.com/apidoc/shared-5a741107-c211-410f-880c-048d1917c984/api-3741892
#### Prompt
Emit new event when an issue is deleted in Leiga. Props: You need to input the particular issue you want to detect for deletes.
####URLs
- https://apidog.com/apidoc/shared-5a741107-c211-410f-880c-048d1917c984/api-3741892
#### Prompt
Creates a new issue within Leiga. Requires a prop representing the issue's title and a description. Takes optional props for assigning the issue to a user, setting a priority level, or associating with a project.
####URLs
- https://apidog.com/apidoc/shared-5a741107-c211-410f-880c-048d1917c984/api-3741813
- https://apidog.com/apidoc/shared-5a741107-c211-410f-880c-048d1917c984/api-3741833

**Comment by luancazarine** [comment]
Hi @vunguyenhung, could you update your action and try again please? because the tags are already passing the id.
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/89432a0e-51b8-4cdb-b6ce-72c4be6d9fc4)
