### ISSUE TITLE
Cliniko and Highlevel

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11149]
### App
Cliniko and Highlevel
https://docs.api.cliniko.com/developer-portal/

### Sources
What I am looking to do is to connect Cliniko with my GoHighLevel account. So when I have a contact book in for an appointment with Cliniko, they will automatically update as a contact in GHL. 

### Actions
I suppose the action would be update opportunity or contact in GHL

**Comment by alexchambers2507** [comment]
For Cliniko, I am looking to trigger once a new contact is created (old or new) through an appointment booking

**Comment by sergio-eliot-rodriguez** [comment]
GoHighLevel is integrated

https://pipedream.com/apps/gohighlevel
https://pipedream.com/apps/highlevel-oauth

Cliniko too
https://pipedream.com/apps/cliniko

**Comment by alexchambers2507** [comment]
Hi Sergio,

I understand the two of them are integrated but I am having trouble building the integration between the two. Is that something you can help with?

**Comment by sergio-eliot-rodriguez** [comment]
Hi Alex, someone from the team will help you build the necessary components you requesting.

**Comment by alexchambers2507** [comment]
Hi there Leo,

Would it be possible to discuss this over a brief chat? To see how I can
implement it?

Thanks,
Alexander

**Comment by sergio-eliot-rodriguez** [comment]
Alex, to chat with the team you can join our public Slack-space here: https://join.slack.com/t/pipedream-users/shared_invite/zt-2bftue1w1-dkBvc_3UQAF99Qgg2zkhzg ask about this in the #help or #general channel

It's not clear which specific part you want help with, but I'll try to give you a couple of heads up.
If you need help building a workflow that use two different apps to accomplish certain automatoin logic, you will need to build a workflow, see: https://pipedream.com/docs/workflows

If you mean creating the components Leo has triaged onto different tickets, you could contribute to Pipedream component registry to: https://pipedream.com/docs/components/api

Finally,

> Need professional support with building a workflow or a large project? Connect with a Pipedream Partner.

https://tally.so/r/w72dJa
