### ISSUE TITLE
JOPLIN

### ISSUE THREAD

**Issue by mayorgergich** [PipedreamHQ/pipedream#11142]
**Name of app / service**
Joplin
**Link to developer documentation**
https://joplinapp.org/help/
**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have no work around
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
No

**Comment by sergio-eliot-rodriguez** [comment]
This is now integrated https://pipedream.com/apps/joplin
