### ISSUE TITLE
[APP] Alchemer (formerly SurveyGizmo)

### ISSUE THREAD

**Issue by oliviermills** [PipedreamHQ/pipedream#1114]
The API is here: https://apihelp.alchemer.com/help/objects-v5
It uses `api_token` and `api_token_secret` that is provided within the account.
No OAuth available, so just safe storing of those 2 values would work.

I am writing a bunch of actions.. happy to share!

**Comment by todsac** [comment]
@oliviermills - would you mind testing out this integration?  

https://pipedream.com/apps/alchemer

**Comment by dylburger** [comment]
@oliviermills I just wanted to check in to see if you had a chance to test this integration. If you see anything that's not working, we're happy to address.

**Comment by oliviermills** [comment]
Yes! It works great. Any reason you went with v4 over [v5](https://apihelp.alchemer.com/help/objects-v5) of the API?
[Here](https://pipedream.com/@omillscawst/alchemer-test-workflow-p_mkC5noL) is a simple sample workflow
And [here](https://pipedream.com/actions/a_VpikXm) is a published action. Will add more!

**Comment by dylburger** [comment]
Thanks @oliviermills ! @todsac , was there a specific reason you chose the v4 API integration over v5?

**Comment by todsac** [comment]
No reason.  I updated the test request to - https://api.alchemer.com/v5/account.

Please let me know if this works for you - https://pipedream.com/apps/alchemer
