### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by AM1957** [PipedreamHQ/pipedream#11146]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Dropbox is integrated: https://pipedream.com/apps/dropbox

Can you let us know what you were trying to do?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
