### ISSUE TITLE
[APP] sendSMS

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11180]
### App
SendSMS
Sendsms.ro/api

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by neamtua** [comment]
Hello @sergio-eliot-rodriguez. I represent the team that handles integrations for sendSMS. We need some help getting the action published. From what we understand we need someone from your team to put the app on your git.
Can you help out with this please?

**Comment by sergio-eliot-rodriguez** [comment]
Hello @neamtua 

Got it! We reached out via email. Your team said they'll provide a demo account for us to add the app to the git repo. Once done that, you'll be able to tackle the action. In the email Ramona, Liviu, and Ionot are cc'ed.

**Comment by neamtua** [comment]
Hello, any update on this? What are the next steps? Thank you.

**Comment by sergio-eliot-rodriguez** [comment]
14 days follow up

**Comment by sergio-eliot-rodriguez** [comment]
Hello @neamtua 

We have rolloed out the base integration and you can see the app on git

[https://pipedream.com/apps/sendsms](https://pipedream.com/apps/sendsms?via=go)

You may have already our docs for Action development -- https://pipedream.com/docs/components/actions-quickstart

Let us know if while building the actions you need help from us, we'll support you in anyway we can.

Thank you
