### ISSUE TITLE
Bitquery [APP]

### ISSUE THREAD

**Issue by all4kicks888** [PipedreamHQ/pipedream#11199]
**Name of app / service**
Bitquery
https://bitquery.io/

**Link to developer documentation**
https://docs.bitquery.io/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Not specified

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Not specified

**Comment by sergio-eliot-rodriguez** [comment]
Bitquery has been integrated https://pipedream.com/apps/bitquery
