### ISSUE TITLE
[FEATURE REQUEST] Better UI and UX

### ISSUE THREAD

**Issue by elibroftw** [PipedreamHQ/pipedream#112]
If relevant I use Firefox.

1. Why is the signed-in page the same as the home page for requestbin?
- It should show my request bins, etc.
2. Sometimes when I click the sign-in button, nothing happens and I have to refresh the page for the website to register that I signed in (probably is using cache).
3. Dark theme!
4. The user menu could have more stuff (option for dark theme)
5. Within a request bin when viewing data, have an option to change default view from "structured" to "pretty" or "raw"
6. Request bin should have an option to be deleted. I'm not sure how to delete a request bin I don't need
7. Integrate Requestbin pages with Workflows (and your other services) so that I can just go to my workflows instead of either creating "a programmable bin" and then canceling it or having to type in another URL. Vice versa as well.
8. Regarding creating a workflow, please specify the type of event more clearly, although trial and error to figure something out is good for me, I don't think it benefits everyone in the same way it benefits me.
9. This GitHub issue template should have a template title as well

**Comment by dylburger** [comment]
We've substantially improved the UI for Pipedream event sources to capture most of this feedback, or have broken out feedback (e.g. for dark mode) into other tickets. If we're still lacking something you'd like to see, please open individual tickets for those features. Closing this ticket.

**Comment by elibroftw** [comment]
Can you guys transfer over request bins to use the new version? That's the only issue.

**Comment by dylburger** [comment]
No, we don’t plan to migrate bins from RequestBin over to Pipedream.
