### ISSUE TITLE
[APP] Tripadvisor

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#11200]
**Name of app / service**
Tripadvisor

**Link to developer documentation**
https://tripadvisor-content-api.readme.io/reference/overview

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Trigger:
- New review (with timer)
- New photo (with timer)

Actions:
- [Location Details](https://tripadvisor-content-api.readme.io/reference/getlocationdetails) provides access to comprehensive information about a location such as name, address, rating, and URLs for the listing on Tripadvisor.
- [Location Photos](https://tripadvisor-content-api.readme.io/reference/getlocationphotos) provides access to high-quality recent photos for a specific location.
- [Location Reviews](https://tripadvisor-content-api.readme.io/reference/getlocationreviews) provides most recent reviews for a specific location.
- [Location Search](https://tripadvisor-content-api.readme.io/reference/searchforlocations) returns a list of locations for a given search query.
- [Nearby Location Search](https://tripadvisor-content-api.readme.io/reference/searchfornearbylocations) returns a list of locations found near the given latitude/longitude.

**Comment by sergio-eliot-rodriguez** [comment]
Trip advisor content api was integrated https://pipedream.com/apps/tripadvisor-content-api

**Comment by GTFalcao** [comment]
Looks like this has already been developed at #11268

**Comment by LucBerge** [comment]
Commit do not reference the issue https://github.com/PipedreamHQ/pipedream/commit/1652b8f20f0ffa61fde3b6d9c5402bfc9a6b293c

App is now integreted.

Should I open a new issue for the triggers and actions?
