### ISSUE TITLE
[Components] google_postmaster_tools_api

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11237]
# google_postmaster_tools_api
## URLs
- https://developers.google.com/gmail/postmaster/reference/rest
#### Prompt
Emits a new event when TrafficStats match certain criteria. Please use async options to List Domains. 

Please include optional props for IP Reputation and Domain Reputation, and have dropdown options that the user can select. Please also include an optional prop for User Reported Spam Ratio Greater than (When user reported spam ratio is greater than, or equal to what the user provides) - essentially enabling an event to emit if the ratio crosses a certain threshold. 

Include optional props for spfSuccessRatio Less Than, dkimSuccessRatio Less Than, dmarcSuccessRatio Less Than, outboundEncryptionRatio Less Than, inboundEncryption Ratio Less Than - these will emit events any time the above ratios fall below the user-provided threshold, with a default of 1. 

Include a prop for Delivery Error (with additionalProps for errorType), and errorRatio greater than. 

#### URLs
- https://developers.google.com/gmail/postmaster/reference/rest/v1/domains.trafficStats/get
- https://developers.google.com/gmail/postmaster/reference/rest/v1/domains.trafficStats#TrafficStats
- https://developers.google.com/gmail/postmaster/reference/rest/v1/domains/list

**Comment by malexanderlim** [comment]
@vunguyenhung,  have you had a chance to re-review yet? Hoping to get this one shipped soon!
