### ISSUE TITLE
[ACTION] Version Bump for Shopify graphql API

### ISSUE THREAD

**Issue by luffy2095** [PipedreamHQ/pipedream#11241]
**Is there a specific app this action is for?**
Yes, Pipedream's shopify app install trigger

**Please provide a link to the relevant API docs for the specific service / operation.**
Shopify's 23-04 version is deprecated as of 1st April, Please update to 24-04 in
https://github.com/PipedreamHQ/pipedream/blob/master/components/shopify_partner/shopify_partner.app.mjs

https://shopify.dev/docs/api/release-notes/previous-versions/2023-04

**Comment by malexanderlim** [comment]
@luffy2095 , this is complete. You will need to re-add your trigger to pick up the change.
