### ISSUE TITLE
[FEATURE] Improve BigCommerce connection popup instruction

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#11260]
**Is your feature request related to a problem? Please describe.**
On the BigCommerce connection popup, there's instruction on where to get the API Access Token
```
Navigate to Advanced Settings > API Accounts > Create API Account
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/5c1fe06f-b9dd-4703-8045-98cc199725b5)

But in the new BigCommerce UI, there's no Advanced Settings
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/b55f7320-c9ee-4a78-a8eb-937e3939bc06)

in the new UI, we can find the Token required via `Settings > API > Store-level API accounts`
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/0d385373-bed5-4651-aad8-8e84508296fb)

**Describe the solution you'd like**
Update the instruction to
```
Navigate to Settings > API > Store-level API accounts
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/da673253-33f3-4e6b-87b0-90bc7c2a4fc1)

**Comment by malexanderlim** [comment]
Thanks for the suggestion Leo - shipped this update!
