### ISSUE TITLE
[FEATURE] Improve Cliniko connection popup instruction

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#11261]
**Is your feature request related to a problem? Please describe.**
Currently the Cliniko connection popup does not have instruction for user to get the API key on the UI
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/dbd853b8-61b9-4875-b623-61474b641b72)

**Describe the solution you'd like**
We should add the instruction for user the get the API key on the UI
```
Navigate to your Profile (Bottom Left) > My Info > Manage API Keys

To access Manage API Keys section, you need to enable `Allow yourself to create and use API keys` switch
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/b40399a5-9628-44d5-985b-115c9966891e)

**Comment by malexanderlim** [comment]
Thanks for clarifying these instructions - I've added your language and some links as well.
