### ISSUE TITLE
[FEATURE] Add an option to hide sensitive fields in a workflow

### ISSUE THREAD

**Issue by zeshhaan** [PipedreamHQ/pipedream#1127]
I was planning to share my screen to my colleague on setting up nodemailer but didn't feel confident as my mail's password is exposed and Pipedream didn't have an option to hide/show toggle.

I would like pipedream to have password field to be toggled hidden at first place and treat it as sensitive field unlike all other fields

Thank you! ❤️

**Comment by dylburger** [comment]
@zeshhaan our recommendation here is to use [environment variables](https://pipedream.com/docs/environment-variables/) to store sensitive data, instead of including them directly as params. Environment variables hide their associated values by default. 

Would that work for you?

**Comment by zeshhaan** [comment]
That is perfect and works for me. Thanks again 👍

**Comment by dylburger** [comment]
Great, thanks!
