### ISSUE TITLE
powerpoint[APP]

### ISSUE THREAD

**Issue by KanakGupta05** [PipedreamHQ/pipedream#1128]

**Comment by dylburger** [comment]
Hi @KanakGupta05 , thanks for the request. Would you mind linking to the docs of the PowerPoint API you're using? I didn't immediately see a REST or related API for PowerPoint. 

What kind of operations are you trying to perform within Pipedream on PowerPoint files?

**Comment by dylburger** [comment]
Closing due to lack of information. Feel free to re-open if you can provide more detail.
