### ISSUE TITLE
[BUG] Workflow V2 - When creating Airtable New Records trigger, cannot click to Connect Airtable (OAuth) Account button

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#11280]
**Describe the bug**
Workflow V2 - When creating Airtable New Records trigger, cannot click to Connect Airtable (OAuth) Account button
<img width="836" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/86d9d385-f005-4428-929e-721dc140cafd">

**To Reproduce**
I only can see this behavior on user account, please enable God Mode and access this workflow https://pipedream.com/@alphabetworkersunion/projects/proj_0psrjbe/pa-petition-data-sync-p_A2CdMVO/build

User's workspace url: https://api.pipedream.com/admin/orgs/o_3EImez

**Additional context**
Reported by a user via email. Front Message ID: msg_1lhresw7

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
