### ISSUE TITLE
[ACTION] Sendgrid: Send Email action should support attachments

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1129]

**Comment by dylburger** [comment]
We should create a component action for sending email using Sendgrid, and add support for this when we do.

**Comment by dannyroosevelt** [comment]
@sergioeliot2039 does the "Send Email" action in https://github.com/PipedreamHQ/pipedream/pull/1288 support attachments? If so we can probably close this issue since it's mostly a duplicate of https://github.com/PipedreamHQ/pipedream/issues/1248

**Comment by sergioeliot2039** [comment]
Yes , it does.
I am closing this issue now.
