### ISSUE TITLE
[BUG] YouTube Data API is throttled

### ISSUE THREAD

**Issue by SuperSajuuk** [PipedreamHQ/pipedream#1130]
**Describe the bug**
I'm currently working to build a simple webhook that is posted to when someone uploads a YouTube video. Since I don't know when the video will be uploaded, I check once an hour. This fails because it returns a 403 Forbidden for " you have reached your quota " but I'm just using the default youtube applet code thats provided by Pipedream?

**To Reproduce**
1. Create a YouTube Data API Workflow
2. Link it to a channel
3. Run it once

**Expected behavior**
The event is received

**Screenshots**
403 Forbidden

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v1909
 - Browser Chrome latest

**Additional context**
I have checked on this repo and this has been an issue in the past, so presumably its just a case of the quotas having to be increased again.

EDIT: apologies if this was not appropriate to post here, but the other platforms I don't have an account on and I don't expect to use them so didn't want to go to a lot of effort making an account I would have to just delete later. :P

**Comment by dylburger** [comment]
Hi @SuperSajuuk , would you mind clicking the **Share** button in the top-right of your workflow, and share it with dylan@pipedream.com?

We set both a user-specific quota and a global quota for the YouTube Data API. Currently I'm able to initiate API requests to YouTube using the Pipedream OAuth app with a test account, so it's possible you're hitting the user-level quota, and seeing the workflow will help me dig in further.

**Comment by SuperSajuuk** [comment]
> Hi @SuperSajuuk , would you mind clicking the **Share** button in the top-right of your workflow, and share it with [dylan@pipedream.com](mailto:dylan@pipedream.com)?
> 
> We set both a user-specific quota and a global quota for the YouTube Data API. Currently I'm able to initiate API requests to YouTube using the Pipedream OAuth app with a test account, so it's possible you're hitting the user-level quota, and seeing the workflow will help me dig in further.

Done! ❤

**Comment by dylburger** [comment]
@SuperSajuuk I identified the source of this issue. On the initial run of the trigger, we attempt to fetch a number of sample videos for the specified user, and the user you specified had so many videos that we hit the YouTube quota just from trying to list those sample videos. 

We're optimizing how we fetch these initial videos and should have an approach that keeps you under limits. I'll let you know when we have a new version of the trigger for you to test.

**Comment by dylburger** [comment]
@SuperSajuuk would you mind creating a brand new YouTube trigger and try this again?

**Comment by SuperSajuuk** [comment]
> @SuperSajuuk would you mind creating a brand new YouTube trigger and try this again?

@dylburger Hi! I created one overnight (via my ipad no less lol) and can confirm its all working as intended now and I'm able to see 10 test results for which I was able to create the proper webhook cell step to post over to a Discord webhook! Thanks for the work on making this possible ❤❤❤

**Comment by dylburger** [comment]
Great to hear. @michelle0927 deserves all the thanks!

**Comment by michelle0927** [comment]
Awesome! Glad this is working for you!
