### ISSUE TITLE
Teamleader Focus: email address no longer working

### ISSUE THREAD

**Issue by bobhuf** [PipedreamHQ/pipedream#11383]
Email adress no longer passed to Teamleader Focus 'create contact' & 'create deal' actions. No changes on our end for months.

**Comment by bobhuf** [comment]
Somehow this:
Email: {{steps.trigger.event.body.email}}

Was changed to this:
Email: {{steps.trigger.event.body["E-mail"]}}

To illustrate:
![Scherm­afbeelding 2024-04-11 om 20 55 33](https://github.com/PipedreamHQ/pipedream/assets/4223412/62ab3d6c-eea6-4e6c-a907-5a146a0878c7)

What has happened here?

**Comment by malexanderlim** [comment]
@bobhuf , can you share a link to your workflow and [enable sharing](https://pipedream.com/docs/troubleshooting#how-do-i-share-my-workflow-with-support) with Pipedream support?

**Comment by bobhuf** [comment]
Done. https://pipedream.com/@bobhufkens/projects/proj_LosyqpG/teamleader-sync-p_ZJCwRb2/

**Comment by bobhuf** [comment]
My workflow was working just fine until recently. When I tested the workflow I noticed the email token had changed from {{steps.trigger.event.body.email}} to {{steps.trigger.event.body["E-mail"]}}.

My question remains; why did I have to replace _...body.email_ with _...body.["E-mail"]_?
