### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by ananduse** [PipedreamHQ/pipedream#1142]
some time we need to plan smtp mail

**Comment by dylburger** [comment]
Hi @ananduse , you can connect to an SMTP server using a variety of Node.js packages, which you can use within Pipedream just by [requiring the package in a code step](https://pipedream.com/docs/workflows/steps/code/#using-npm-packages). 

[Nodemailer](https://nodemailer.com/about/) is the most popular of these, and we have instructions for using that package [here](https://pipedream.com/community/t/how-do-i-send-an-email-using-my-outlook-account/203).

Let us know if that helps.
