### ISSUE TITLE
[Components] tapform

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11485]
# tapform
#### Prompt
Emit new event when there is a new lead received from your Tapform instance. Required props are: Tapform instance ID.

**Comment by luancazarine** [comment]
Hi @malexanderlim @dylburger @sergio-eliot-rodriguez 
I didn't find any tapform api documentation

**Comment by malexanderlim** [comment]
@luancazarine only one endpoint exposed to us thus far:

Get Recent Leads (can use for implementing polling trigger) 
```curl --location 'https://apimvp.tapform.io/api/leads/zapier-leads' \
--header 'tapform-api-key: YOUR_TAPFORM_API_KEY'```
