### ISSUE TITLE
Shopify Partners

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11508]
### App
Shopify Partners

### Summary:
Config error - Uninstall events

### Details:
For some reason, setting up the uninstall trigger using the Shopify Partners app presents a configuration error. Have tried fresh linking my account 3 times. Even when skipping and clicking deploy it bring me back to the screen below.

I have tried setting it up from fresh, a completely brand new work flow and still doesn't work.

### Screenshots:
https://www.loom.com/share/f835c1ab46f24afda14b89608d0c5082
![Screenshot]()

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
