### ISSUE TITLE
[Components] greenhouse

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11589]
# greenhouse
## URLs
- https://developers.greenhouse.io/harvest.html
#### Prompt
Emit new event when a candidate's application or status changes. Required prop is 'Candidate Id'.
#### URLs
- https://developers.greenhouse.io/harvest.html#get-retrieve-activity-feed
#### Prompt
Emit new event when a candidate submits a new application. Required prop is the application details.
#### URLs
- https://developers.greenhouse.io/harvest.html#get-retrieve-candidate
#### Prompt
Emit new event when a new interview is scheduled within a specific time period. Required prop is the schedule detail and time period.
#### URLs
- https://developers.greenhouse.io/harvest.html#get-list-scheduled-interviews
#### Prompt
Creates a new candidate entry. Required props are candidates name, email, and contact. Optional props include candidate address, summary, skills.
#### URLs
- https://developers.greenhouse.io/harvest.html#post-add-candidate
#### Prompt
Creates a new prospect entry. Required props are prospect's name, email, and contact. Optional props are prospect's address, qualifications, skills, etc.
#### URLs
- https://developers.greenhouse.io/harvest.html#post-add-prospect
#### Prompt
Adds an attachment to a specific candidate or prospect. Required prop is candidate ID and the attachment file. Optional props are attachment description, tags.
#### URLs
- https://developers.greenhouse.io/harvest.html#post-add-attachment

**Comment by malexanderlim** [comment]
I've applied to become a Greenhouse partner and will update this ticket when we have a sandbox environment available for development.

**Comment by malexanderlim** [comment]
Sandbox credentials have now been added to 1Pass.

**Comment by luancazarine** [comment]
Hi @vunguyenhung, I just fixed the points you listed, but there's one I couldn't change.
The source watch-candidate: there's only one endpoint in their API where we can list activities which is https://developers.greenhouse.io/harvest.html#get-retrieve-activity-feed
this endpoint requires a candidate Id

**Comment by luancazarine** [comment]
Hi @vunguyenhung, could you try again?
I don't know what happened, I couldn't reproduce the error
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/c41e2264-a148-4440-a42c-7761d10e9d43)
