### ISSUE TITLE
[BUG] RSS Feed Creation error

### ISSUE THREAD

**Issue by victormithouard** [PipedreamHQ/pipedream#1158]
Issue
RSS Feed Creation raise an error 500 on a valid feed

Steps to reproduce
- Create an RSS feed trigger or new RSS source (https://pipedream.com/sources/new)
- Use the following (valid) RSS https://news.un.org/feed/subscribe/en/news/topic/human-rights/feed/rss.xml

Expected behavior
RSS Feed gets creaed without error

Error Screenshot attached
<img width="851" alt="Screen Shot 2021-04-11 at 9 17 58 PM" src="https://user-images.githubusercontent.com/50637479/114328728-71230c80-9b0b-11eb-9204-309b2abbfd72.png">

**Comment by dylburger** [comment]
@victormithouard thank you for raising. This should be fixed. Would you mind trying one more time?

**Comment by victormithouard** [comment]
Fixed 👍 Thank a lot
