### ISSUE TITLE
[IMPROVEMENT] Improve smarroutes connection popup

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#11595]
**Is your feature request related to a problem? Please describe.**
Currently, we instruct the user to request the API key from smartroute support
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/257a6c77-5410-48a2-a9bf-bded440c2ffa)

Though we can generate API Key on the UI from `Settings (Bottom left) > Advanced Settings - Integrations > SmartRoutes Open API > Generate API Key`
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/c01143c1-8363-4d03-a779-9d2a1df22217)

**Describe the solution you'd like**
We should improve smarroutes connection popup with the new instruction as below

To generate API Key, access `Settings (Bottom left) > Advanced Settings - Integrations > SmartRoutes Open API > Generate API Key`

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
