### ISSUE TITLE
[IMPROVEMENT] Improve Softr connection popup

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#11606]
**Is your feature request related to a problem? Please describe.**
On the Softr connection popup, there's no instruction for user to input the `Domain` prop
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/da2bd095-bc3e-42c3-bc3c-bc346787b52f)

**Describe the solution you'd like**
On the Softr connection popup, we can add the instruction for the user to input the `Domain`:

To get the Domain, access your app on Softr > Publish, then copy the Subdomain shown there. For example `joel3859.softr.app`
<img width="344" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/c7d391a2-a4c9-4458-bf55-44e2d0e4dfde">

Note: Make sure to **publish your Softr app** first.

**Comment by malexanderlim** [comment]
Thanks for the suggestion @vunguyenhung  - I've implemented the new copy.
