### ISSUE TITLE
[BUG]  add-package google-ads

### ISSUE THREAD

**Issue by JeffButler** [PipedreamHQ/pipedream#11604]
When running adding

# pipedream add-package google-ads

There is a bug in the package with the requirements.txt files.

`
The conflict is caused by:
    The user requested protobuf==5.26.1
    google-ads 23.1.0 depends on protobuf<5.0.0 and >=4.25.0
    The user requested protobuf==5.26.1
    google-ads 23.0.0 depends on protobuf<5.0.0 and >=4.25.0
    The user requested protobuf==5.26.1
    google-ads 22.0.0 depends on protobuf!=3.18.*, !=3.19.*, <5.0.0dev and >=3.12.0
    The user requested protobuf==5.26.1
    google-ads 21.3.0 depends on protobuf!=3.18.*, !=3.19.*, <5.0.0dev and >=3.12.0
    The user requested protobuf==5.26.1
    google-ads 21.2.0 depends on protobuf!=3.18.*, !=3.19.*, <5.0.0dev and >=3.12.0
    The user requested protobuf==5.26.1
    google-ads 18.0.0 depends on protobuf!=3.18.*, !=3.19.*, <=3.20.0 and >=3.12.0
    The user requested protobuf==5.26.1
    google-ads 17.0.0 depends on protobuf!=3.18.*, !=3.19.*, <=3.20.0 and >=3.12.0
    The user requested PyYAML==6.0.1
    google-ads 16.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 15.1.1 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 15.1.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 15.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 14.1.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 14.0.1 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 14.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 13.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 12.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 11.0.2 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 11.0.1 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 11.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 10.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested protobuf==5.26.1
    google-ads 9.0.0 depends on protobuf<4.0.0 and >=3.13.0
    The user requested protobuf==5.26.1
    google-ads 8.2.0 depends on protobuf<4.0.0 and >=3.13.0
    The user requested protobuf==5.26.1
    google-ads 8.1.0 depends on protobuf<4.0.0 and >=3.13.0
    The user requested protobuf==5.26.1
    google-ads 8.0.0 depends on protobuf<4.0.0 and >=3.13.0
    The user requested protobuf==5.26.1
    google-ads 7.0.0 depends on protobuf<4.0.0 and >=3.13.0
    The user requested PyYAML==6.0.1
    google-ads 6.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 5.1.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 5.0.4 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 5.0.3 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 5.0.2 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 5.0.1 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 5.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 4.1.1 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 4.1.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 4.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 3.3.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 3.2.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 3.1.2 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 3.1.1 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 3.1.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 3.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 2.4.1 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 2.4.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 2.3.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 2.2.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 2.1.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 2.0.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 1.3.1 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 1.3.0 depends on PyYAML<6.0 and >=5.1
    The user requested PyYAML==6.0.1
    google-ads 1.2.0 depends on PyYAML<5.0 and >=4.2b1
    The user requested PyYAML==6.0.1
    google-ads 1.1.1 depends on PyYAML<5.0 and >=4.2b1
    The user requested PyYAML==6.0.1
    google-ads 1.1.0 depends on PyYAML<5.0 and >=4.2b1
    The user requested PyYAML==6.0.1
    google-ads 1.0.1 depends on PyYAML<5.0 and >=4.2b1
    The user requested PyYAML==6.0.1
    google-ads 1.0.0 depends on PyYAML<5.0 and >=4.2b1
    The user requested PyYAML==6.0.1
    google-ads 0.7.0 depends on PyYAML<5.0 and >=4.2b1
    The user requested PyYAML==6.0.1
    google-ads 0.6.0 depends on PyYAML<5.0 and >=4.2b1
    The user requested PyYAML==6.0.1
    google-ads 0.5.2 depends on PyYAML<5.0 and >=4.2b1
    The user requested PyYAML==6.0.1
    google-ads 0.5.1 depends on PyYAML<4.0 and >=3.11
    The user requested PyYAML==6.0.1
    google-ads 0.5.0 depends on PyYAML<4.0 and >=3.11
    The user requested PyYAML==6.0.1
    google-ads 0.4.0 depends on PyYAML<4.0 and >=3.11
    The user requested PyYAML==6.0.1
    google-ads 0.3.0 depends on PyYAML<4.0 and >=3.11
    The user requested PyYAML==6.0.1
    google-ads 0.2.0 depends on PyYAML<4.0 and >=3.11
    The user requested PyYAML==6.0.1
    google-ads 0.1.0 depends on PyYAML<4.0 and >=3.11
`

**Comment by JeffButler** [comment]
when you add 
```
# pipedream add-package google-ads
```
At the top of a python file.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
