### ISSUE TITLE
RelevanceAI

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11625]
### App
RelevanceAI
https://relevanceai.com/docs/agent/agent-api

### Sources
Execute a Tool -> Triggers a tool.
Make an API Call -> Performs an arbitrary authorized API call.
Message an Agent -> Sends a message to an agent to either start a new conversation or send an additional message to an existing conversation.
List Agents -> Returns a list of agents.
List a Conversation's Messages ->Returns a list of messages for a conversation.
List an Agent's Conversations -> Returns a list of conversations for an agent.
List Tools -> Gets a list of tools.

### Actions
I want to be able to start a workflow here, trigger a tool at relevance, get the result back here, then continue my workflow.
I want to be able to use pipedream as the trigger source, then trigger an agent and give them some data. eg If I got a new email It'll trigger pipedream, then extract all attachments, send them to the agent.

**Comment by sergio-eliot-rodriguez** [comment]
This looks duplicated, at least the app integration -- we rolled it out as "Relevance AI" https://pipedream.com/apps/relevance-ai
