### ISSUE TITLE
[FEATURE] Improve Reusable Actions Actionbar & Editor

### ISSUE THREAD

**Issue by chrigi** [PipedreamHQ/pipedream#1162]
**Is your feature request related to a problem? Please describe.**

When creating a re-usable action through Sidebar -> Actions -> New, an Editor opens. This editor features an action bar below the code editor with a huge, red "HIDE" button, a green "SAVE" button, undocumented version field, green "PUBLISH" button.

This is all a bit jumbled together:
- The HIDE interaction is not the main thing you want to do in that view but it takes precedent over all other actions also, you can't hide an action from the list, compared to the workflows which you can archive from the ... menu in the list view. (also why is it called hide in the context of actions but archive for worklfows?)
- The version field should probably get a label so users know what it is, instead of just being two unlabeled inputs. It might also be good to promote the field to the top and save it even for unpublished actions or alternatively only show it when you publish becasue you can fill it out even if you are just saving but it won't get re-populated when you re-open a draft action 

**Describe the solution you'd like**
See above

**Do you have a workaround?**
It's functional in the current state. No workaround needed.

**Comparable features in other tools?**
The Action editor would probably benefit if it was re-using the workflow editor as that one offers all the necessary UI things.

**Comment by chrigi** [comment]
Also there seems to be an issue with params. I tried to add a new param to a new version of an already published action and when doing that I had to save the action, return to the list, open it again and only then was it added to the params list/schema.

**Comment by dylburger** [comment]
@chrigi thanks for the feedback here. We're very close to releasing a brand new action development model that will address some of these issues. We'll be sharing details of that [in our community](https://pipedream.com/community) and via email. I'd love to know what you think of that once we ship it.

**Comment by chrigi** [comment]
@dylburger Oh great to hear! Can't wait to try it out :) And thanks for the community link, I guess in the future, stuff like this should be posted there then.

**Comment by dylburger** [comment]
No worries, Github is still a perfectly acceptable place to post feature requests, even if they're encompassing of a few specific tasks (we might break them out into specific issues for our own tracking). The community is also a fine place to get help. Whatever's easiest for you works for us!
