### ISSUE TITLE
[IMPROVEMENT] Improve FourceManager connection popup link to API Key

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#11637]
**Is your feature request related to a problem? Please describe.**
Currently, the ForceManager connection popup link to API key is `https://app3.forcemanager.net/views/settings.aspx`
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/fff78850-7bc3-4b34-9faa-7461f8509051)

Which leads to a blank page
<img width="1308" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/e92802ea-4f48-4e54-b647-f565922a5d8f">

**Describe the solution you'd like**
The correct link should be: https://app.forcemanager.net/#/settings/api

**Comment by malexanderlim** [comment]
Thanks for the suggestion - all set.
