### ISSUE TITLE
[FEATURE] Multi-Step Actions

### ISSUE THREAD

**Issue by chrigi** [PipedreamHQ/pipedream#1163]
**Is your feature request related to a problem? Please describe.**
When creating a re-usable action I can only define it's function with a single, self created code block. It's not possible to compose an action of a combination of multiple code steps or existing actions.

**Describe the solution you'd like**
It would be very useful to extend the re-usable actions into something like "sub-workflows" where you can define action-global input params and then compose an action workflow which is a composition of multiple actions just like in a workflow. To a user of this action, it only presents itself as a single action with params (which of course can get expanded into it's sub actions).

**Do you have a workaround?**
All action code can be inspected so you can compose all actions together into one code step.

**Additional context**
One of the usecases I stumbled upon was that I wanted to create an action that fetches data from an API, transforms it and returns that data. Of course I could just do all of that in a single step but to further code re-use I would have loved to do it in two steps so I could use the standard fetch action and a transform step which might be another re-usable action I created and share among multiple workflows & actions.

**Comment by dylburger** [comment]
@chrigi If you had the ability to set global workflow params, would that solve your core use case?

For example, you could develop a workflow template that composed three actions. Then any time you needed to use those actions as a group, you could copy that template and be presented with a single place to enter data that would feed into those actions (instead of having to add each action manually and enter its data in individual params). So the _workflow_ would compose the actions, but the "global params input" would allow you to quickly fill in all the information necessary for those actions to run.

In general we see actions as atomic units, and workflows as the mechanism for composition. So I'm curious if better workflow templating features would solve your use case. The idea of "sub-workflows" and logical groups of actions is quite interesting, though, so I'm just trying to better understand the ask.

**Comment by chrigi** [comment]
@dylburger I am not 100% sure my interpretation of your suggestion is what you wanted to say, so let me elaborate, maybe I had the correct interpretation :)

Yes, I think leaving Actions as atomics and using the workflows as a composition method would work very well.

I do think that if there was such a feature like "sub-workflows" it could be argued that there is no need for custom actions anymore as a single action "sub-workflow" would technically be the same as a custom action but that's a philosophical point not that important to this discussion.

I am not sure how you imagine that such a template workflow with a global parameter input would fit into the current system and what how you imagine the use of such a thing.

I think in the current system it's a bit clumsy as I think a workflow is expected to have at least a source/trigger and it's implied to also have and end action. So defining a workflow as a template and gathering all customizable inputs into a workflow global input param list would only result in "init" templates which one might use to start a new workflow. It would also make discovery very hard (discovery of actions and workflows is pretty rough at the moment but I guess that is something you might change in the future). Adding actions of such a template to an existing one might not work due to source/drain laready existing there. Also, by treating them as templates which would streamline the setup by simply filling out the params and then getting the contained actions copied over would make it impossible to version the template as you could never really change it as everyone who used it couldn't upgrade to the newest version.

But in general I think using the workflows for this is the better way than to intoduce multi-step actions. The things I see as issues could be solved something like so:
- Introduce a "Pipedream Action Trigger" one could use as a "source" in a workflow, this would label such a workflow as a "sub-workflow"
- The workflow global input param list could be automatically generated from all the actions inputs

This could be versioned just like actions and another workflow could then add it like you can add actions. It could look similar to a normal action step, offer to add a name, present the params and have a way to expand the contained actions and eject. It would consume the output of the preceeding action and output it's own results. This might still be a tricky thing as there is currently no "previous output" field to chain actions without knowing their names (but I saw a discussion about this in another GitHub issue) but with input params this should not be a problem as the mapping can just be done manually there.

This way you could re-use a workflow just like an action, version it and upgrade it (as long as you don't modify it, like actions at the moment, maybe even with an upgrade button in the future as another GitHub issue asks for).

Is this similar to what you suggested?

While talking abut re-use and multi-step: Maybe something like this could also be extended to Sources?
There I have an even bigger need for something like this. My use-case is as follows:
Sadly many sites nowadays don't offer RSS feeds or if they do, they only offer ones with links to their pages without content. To create a useful source of these things I alwys have to the same thing:

- Define an RSS Source or a Cron Trigger (if I have to call an API as there is no RSS)
- Filter out already seen items (for API calls, RSS source does this for me)
- Parse the returned item(s) and re-format them
- Maybe load additional data to fill out the missing things

For me all of this together is 1 source and I would love to define such a source to be re-usable among many workflows.
If I have workflow that outputs these items to Telegram and another to Discord, currently I have to re-build all of this in every workflow. Thanks to the "load data from API X", "Format data from X", "Filter data" actions I created it's not that hard but a lot of duplication. Also every workflow has their own cron trigger, so if I have 10 workflows with this, the API get's hit 10 times and I have 10 states of seen items, etc. If I could combine all of this into a re-usable, multi-step source, then this source would only have to run once and could trigger all 10 workflows with the same output. 

This would kind of mean that Sources could become something like workflows themselves with a global state that spans over all workflows that use them.

**Comment by chrigi** [comment]
Thanks a lot for the new component actions/source :) that kind of does everything I need and allows me to compose the actions/sources with re-usable code.

The docs regarding Components and the CLI are a huge mess at the moment though. As stuff like that should probably be discussed on the community, I made a comment there: https://pipedream.com/community/t/actions-improved-open-source-now-in-beta/606/2?u=chrigi

**Comment by dylburger** [comment]
Great thank you for the feedback, Chris
