### ISSUE TITLE
[ACTION]How to use Discord Bot to set user NickName?

### ISSUE THREAD

**Issue by chun1617** [PipedreamHQ/pipedream#1167]
I found the discord.js can do so, but I am not sure how can I do in Pipedream.
Can someone give advice? Thank you so much!

**Comment by dylburger** [comment]
Hi @chun1617 , thanks for reaching out. Are you using your own bot (via the **Discord Bot** integration), or delivering a message to Discord using the **Discord Webhook** integration)?

**Comment by dylburger** [comment]
Closing due to lack of information. If you can provide some more details on specifically what you're trying to do, I'm happy to help.
