### ISSUE TITLE
[APP] Botpress

### ISSUE THREAD

**Issue by peter-hanzo** [PipedreamHQ/pipedream#11687]
**[botpress.com](https://botpress.com/)**

**[Link to developer documentation](https://botpress.com/docs/developers/)**

**does not block work, but I want to improve the convenience of work**

**I want to see all the functions similar to "bot telegram"**

**Comment by sergio-eliot-rodriguez** [comment]
Hi there @peter-hanzo 

Happy to announce that we have rolled out a base integration for Botpress: https://pipedream.com/apps/botpress
