### ISSUE TITLE
[APP] Frame.io

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1168]
https://docs.frame.io/docs/welcome

**Comment by todsac** [comment]
Frame.io integration - https://pipedream.com/apps/frame

It would be good to get an end to end test from a Frame.io user

**Comment by LiBearden** [comment]
Hey @dylburger, thanks for creating this!

Our new developer site with updated documentation is located here:
https://developer.frame.io

And I've got a couple of sample actions and an example workflow, here:
https://pipedream.com/@li-bearden?tab=actions

Feel free to reach out to me if y'all have any additional questions regarding our core or Cloud Devices APIs, or would like more context on common customer workflows and use case scenarios as you research the platform 👍🏽 

Kind regards,
Elliot B.

**Comment by dylburger** [comment]
Thanks @LiBearden ! Could you do me a favor and click the **Connect Frame and run** button on [this page](https://pipedream.com/apps/frame) to see if the integration works OK for you?

**Comment by LiBearden** [comment]
You're welcome! @dylburger Yes, the connection there works for me, and I replaced the API token stored in my environment variable of the sample workflow with the Oauth connection, and that works as well 👍🏽

**Comment by dylburger** [comment]
Thanks @LiBearden !
