### ISSUE TITLE
[ACTION] Twitch get subscribed channels

### ISSUE THREAD

**Issue by Fabian9799** [PipedreamHQ/pipedream#1169]
It is currently only possible to get data from twitch as a source and not as a action.

It would be great to get the list of the channels i am currently subscribed to, to use it for notifications when they go live or just to make a json api with it to use.

I am not specifically asking for the "get subscribed channels" feature just in general infos about the connected twitch channel, but that is the one i would be using the most

**Comment by dylburger** [comment]
@Fabian9799 are you relatively comfortable writing Node.js code? Anyone on Pipedream can [create an action](https://pipedream.com/docs/components/quickstart/nodejs/actions/), and I was curious if you'd be interested in helping us develop this.

**Comment by Fabian9799** [comment]
I am only confident with some libraries but not really with the twitch api. but i can try to make something

**Comment by dannyroosevelt** [comment]
@Fabian9799 FYI it looks like we now support what you're trying to do -- check out these Twitch actions: 
https://pipedream.com/apps/twitch#popular-twitch-actions
