### ISSUE TITLE
[ACTION] Zoom Admin: List Rooms

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#117]
https://marketplace.zoom.us/docs/guides/zoom-rooms/zoom-rooms-api

**Comment by sergioeliot2039** [comment]
Workflow showing action here:
https://pipedream.com/@sergio/zoom-admin-list-rooms-p_q6CVNG/edit
Action url:
https://pipedream.com/actions/a_xqiqVp/edit
