### ISSUE TITLE
Outgrow

### ISSUE THREAD

**Issue by prahllad** [PipedreamHQ/pipedream#1170]
https://outgrow.co

https://outgrow.co

Actually outgrow as a product we have connected to lots of crm and zapier also , so now our user wants us to listed over pipedream also. 

we want trigger that can fetch new leads from our endpoint and user can use those in next integrations.

**Comment by prahllad** [comment]
Any Docs available , how Can I crate an app or integrate Outgrow in pipedream.

**Comment by dylburger** [comment]
@prahllad thanks for raising, we're working on the integration and will let you know when it's complete!

**Comment by todsac** [comment]
@prahllad - we have a working version of the Outgrow integration.  Are you open to test and make sure it meets your needs?

**Comment by prahllad** [comment]
HI,
I have checked this Outgrow integration, but It's not solving the problem,
It would be best if post authentication , I can select my outgrow content
piece here in pipedream, so based on my selection of outgrow
form/survey/content piece  in pipedream if we can fetch data or outgrow can
send leads to pipedream, so further I can execute script or any crm tools
to send my leads .
*Prahllad Roy*,
t : +91 8968926234 | e : ***@***.*** ***@***.***>

**Comment by todsac** [comment]
Prahllad - I am trying to understand the nuance of your request.  In Pipedream terms, are you saying that you would like an Outgrow event source that can trigger a workflow when a New Lead is created?  So, you would authenticate your Outgrow account and then receive events when New Leads are created.

**Comment by prahllad** [comment]
Yes, that is correct.
*Prahllad Roy*,
t : +91 8968926234 | e : ***@***.*** ***@***.***>

**Comment by dylburger** [comment]
@prahllad thanks for the request, we're tracking that trigger at #1303 and closing this issue since it covers the app integration itself.

Would you be open to creating this trigger yourself? Anyone can develop these on Pipedream. You can [read more about that dev process here](https://pipedream.com/docs/components/quickstart/nodejs/sources/).
