### ISSUE TITLE
Developer Execution Controls should be tighter by default [FEATURE] 

### ISSUE THREAD

**Issue by ice-fly** [PipedreamHQ/pipedream#1175]
**Is your feature request related to a problem? Please describe.**
The defaults for a free developer account allow the Invocations/Compute constraints to be chewed through very quickly and make it seem like the service isn't viable for large projects.

**Describe the solution you'd like**
Change the default Execution Controls to be tighter if you're using a developer account

**Do you have a workaround?**
User Changes manually

**Comparable features in other tools?**
**Additional context**
Personal opinion, but would also benefit pipedream's hosting cost by preventing wasted triggers by n00bs like me from burning up compute/invocations needlessly.

**Comment by dylburger** [comment]
@ice-fly thanks for the request. Can you elaborate on what you mean when you want the execution controls to be "tighter"?

**Comment by dylburger** [comment]
@ice-fly I just wanted to check in again to see if you can provide more detail on the specific feature you'd like to see here.

Did you notice we have a [Professional Tier](https://pipedream.com/pricing) that lets you run as many invocations as you'd like? What kind of workflow were you running that caused you to run through all of your invocations?
