### ISSUE TITLE
[Components] zip_archive_api

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11789]
# zip_archive_api
## URLs
- https://archiveapi.com/rest-api/file-compression/

**Comment by GTFalcao** [comment]
@vunguyenhung @malexanderlim I've commented on a usability concern on this issue's PR - it seems this API supports file uploading (via form-data), if that's the case, our components should probably support that as well.

**Comment by malexanderlim** [comment]
Thanks @GTFalcao . @lcaresia , could you implement to accept files both via File URL / using Form Data / application/octet-stream as well, to maintain maximum flexibility here?
