### ISSUE TITLE
[BUG] Vryno Node.js sample code is invalid

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#11799]
**Describe the bug**
Executing Vryno Node.js sample code resulted in error
```
ReferenceError
custom_fields is not defined
```

![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/9cba9a28-d314-41dd-b2e9-5d38c4b5685e)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/1c7df646-3dbb-43af-9acd-20f8b15413b1)

**Comment by malexanderlim** [comment]
Hey @vunguyenhung - can you retry? Thanks @sergio-eliot-rodriguez for all the help in getting the request fixed.
