### ISSUE TITLE
[BUG] Hubspot - New Event source throws missing scope error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#11810]
**Describe the bug**
I created a Hubspot - New Event source that track companies
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/94ba1be0-fa38-4682-9b84-352020ca7068)

Though there's no event emitted, in the source log, I see error
```
Your app doesn't the have scopes needed to make this call. Do you have access to the 'business-intelligence' scope?  Missing auth details: event-detail-read,web-analytics-api-access
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/172c75be-3789-4040-b51d-0a9a4769060a)

**Additional context**
Raise by a customer here https://pipedream-users.slack.com/archives/CPTJYRY5A/p1714677340626029

**Comment by michelle0927** [comment]
@vunguyenhung I was able to reproduce this using a free account, but not with a developer account. [The documentation](https://developers.hubspot.com/docs/api/events/event-analytics) says that Event Analytics are for

> Marketing Hub Enterprise, Sales Hub Enterprise, Service Hub Enterprise, or CMS Hub Enterprise only 

Is the account you're using one of those, or is it a free account?
