### ISSUE TITLE
[app] Crisp Chat

### ISSUE THREAD

**Issue by lestervisser** [PipedreamHQ/pipedream#11824]
Crisp Chat

https://docs.crisp.chat/references/rest-api/v1/

**Comment by sergio-eliot-rodriguez** [comment]
Hi @lestervisser 

Thanks for the request, Crisp Chat shows integrated in the app store as just "Crisp" -- https://pipedream.com/apps/crisp

Based on what you are trying to accomplish with this app, which Triggers and Actions would you need from Crisp Chat?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
