### ISSUE TITLE
[ACTION] MongoDb - Find a document

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#11832]
**Is there a specific app this action is for?**

MongoDb

**Please provide a link to the relevant API docs for the specific service / operation.**

Should be a thin wrapper around the `findOne` method on MongoDb Node.js:

`db.collection('example').findOne(filter, options)`

API docs: https://www.mongodb.com/docs/drivers/node/current/usage-examples/findOne/

**Comment by malexanderlim** [comment]
Collapsing into a single ticket here https://github.com/PipedreamHQ/pipedream/issues/11834
