### ISSUE TITLE
[ACTION] MongoDb - Update Many Documents

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#11833]
**Is there a specific app this action is for?**

MongoDb

**Please provide a link to the relevant API docs for the specific service / operation.**

`db.collection('example').updateMany( filter, operation )`

API Docs: https://www.mongodb.com/docs/drivers/node/current/usage-examples/updateMany/

**Comment by malexanderlim** [comment]
Collapsing into a single ticket here https://github.com/PipedreamHQ/pipedream/issues/11834
