### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by blizam** [PipedreamHQ/pipedream#11836]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

Shopify Developer App - Product Update

Similar/Same-as the Product Create... it's listed as "Instant" so I'm assuming that it's using a webhook

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

https://help.shopify.com/en/manual/orders/notifications/webhooks

**Comment by malexanderlim** [comment]
Hi @blizam , can you try using the **Shopify - New Event Emitted** trigger? This is a catch-all, and includes `products/update`.

**Comment by blizam** [comment]
Thank you, I will take a look at that.
