### ISSUE TITLE
[APP] Integrate with the Whatsapp Business App (not API platform)

### ISSUE THREAD

**Issue by diegotkt** [PipedreamHQ/pipedream#11848]
**Name of app / service**
Whatsapp Business app on ios and android

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Right now it's preventing me from building workflows.
- I already use my pro phone number with the whatsapp business app, 
- Despite pipedream being integrated with the (much more complex) Whatsapp Business API platform, I can't use the same number for both API platform and WAB app

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
If you look at what zapier implemented, it took me 2 min to setup and have msg's send to my phone. I'm not paying for zapier though, so I can't build my more complex workflows there.

![image](https://github.com/PipedreamHQ/pipedream/assets/86481598/4b86da48-580b-492c-9223-8ec3044de762)

**Comment by sergio-eliot-rodriguez** [comment]
:S

**Comment by diegotkt** [comment]
🥸

**Comment by sergio-eliot-rodriguez** [comment]
Hi @diegotkt 

Can you help us by pointing us to any documentation for software/integrations of the WhatsApp app for iOs and Android?

I keep getting search results about using the Business API platform.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
