### ISSUE TITLE
Jira integration

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11890]
### App
Jira integration

### Summary:
Access denied error

### Details:
I'm trying to create a workflow to add a comment into Jira using Microsoft Planner and the Add Comment to Issue from Jira API option.

### Screenshots:
No screenshots included

**Comment by malexanderlim** [comment]
There's not enough detail in this request to troubleshoot. If you are the author, can you please add more detail? Where are you seeing the Access denied error?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
