### ISSUE TITLE
Hubspot - New Events not working as expected

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11894]
### App
Hubspot

### Summary:
The source is not triggered when a Quote is created or updated

### Details:
When a Quote is created and updated in Hubspot, it does not trigger test events and therefore the workflow cannot be set up.

**Comment by malexanderlim** [comment]
@Component Dev -- doing some testing, the [New Event](https://pipedream.com/apps/hubspot/triggers/new-event) trigger does not appear to be working - are the objects supposed to reload when you choose a new object type?

**Comment by michelle0927** [comment]
May be a duplicate of https://github.com/PipedreamHQ/pipedream/issues/11810?

**Comment by michelle0927** [comment]
@andrewjschuang Can you confirm that the account is either a developer account or one of: "Marketing Hub Enterprise, Sales Hub Enterprise, Service Hub Enterprise, or CMS Hub Enterprise only"?
