### ISSUE TITLE
[FEATURE] Helm Chart for k8s deployment

### ISSUE THREAD

**Issue by Startouf** [PipedreamHQ/pipedream#11926]
**Is your feature request related to a problem? Please describe.**
Hello, we are deploying open sources apps on k8s. There seem to be some helm charts available on similar apps (like activepieces) 

**Describe the solution you'd like**
A helm chart easy to deploy on kubernetes

**Do you have a workaround?**
No

**Comparable features in other tools?**
activepieces Helm chart https://artifacthub.io/packages/helm/meyercharts/activepieces

**Additional context**
N/A

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
