### ISSUE TITLE
[Components] pidj

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11935]
# pidj
## URLs
- https://pidj.co/wp-content/uploads/2021/05/Pidj-API-Technical-Document.pdf  https://gopidj.com/apis/rest
#### Prompt
Initiates a process to add a new contact to your pidj account. Required props include contact’s information. Optional props include additional notes or tags related to the contact.
#### URLs
- https://pidj.co/wp-content/uploads/2021/05/Pidj-API-Technical-Document.pdf
- https://pidj.co/wp-content/uploads/2023/06/Pidj-API-Technical-Document-v3-1.pdf
- https://gopidj.com/apis/rest
#### Prompt
Sends a text message to a specified phone number from your pidj account. Required props include the recipient's phone number and message text. Optional props could be scheduled send time.
#### URLs
- https://pidj.co/wp-content/uploads/2021/05/Pidj-API-Technical-Document.pdf
- https://pidj.co/wp-content/uploads/2023/06/Pidj-API-Technical-Document-v3-1.pdf
- https://gopidj.com/apis/rest
#### Prompt
Triggers a pre-configured text survey to a specific contact. Requires the contact's information and the survey id as props. Optionally, can include schedule time for survey initiation.
#### URLs
- https://pidj.co/wp-content/uploads/2021/05/Pidj-API-Technical-Document.pdf%20%20https:/gopidj.com/apis/rest
- https://pidj.co/wp-content/uploads/2023/06/Pidj-API-Technical-Document-v3-1.pdf

**Comment by sergio-eliot-rodriguez** [comment]
@luancazarine news from Pidj,

they had a problem with their provider, 
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/5e72401a-bf7e-4010-82b8-40a29ec1be0f)

**Comment by sergio-eliot-rodriguez** [comment]
And looks like you can send message now.

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/f15f6a12-0e29-40e2-bcc2-79bef834d19e)

one observation, for some reason to send the message it accepted the number formatted with white space after country code and hypens as separators such as in `1 123-456-7890`
