### ISSUE TITLE
https://pipedream.com/apps/google-calendar

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11940]
### App
https://pipedream.com/apps/google-calendar

### Summary:
Calendar can not write

### Details:
The write scope of the calendar is missing, hence I can not subscribe to a new calendar on behalf of a user for example. 
The needed scope is 'https://www.googleapis.com/auth/calendar' - how can I add this scope to the existing OAuth token?

### Screenshots:
No screenshots included

**Comment by malexanderlim** [comment]
Replied via Front

**Comment by joscha** [comment]
I believe this request came from me; I haven't tried it yet, but presumably the new custom OAuth clients (https://pipedream.com/docs/connected-accounts/oauth-clients) would solve this?

**Comment by dannyroosevelt** [comment]
> I believe this request came from me; I haven't tried it yet, but presumably the new custom OAuth clients (https://pipedream.com/docs/connected-accounts/oauth-clients) would solve this?

@joscha yes definitely -- please let me know if you're able to get that setup and if you run into any issues.
