### ISSUE TITLE
[APP] Looker Studio

### ISSUE THREAD

**Issue by henrywangnl** [PipedreamHQ/pipedream#11942]
**Name of app / service**
Looker Studio api to manage Looker Studio assets (reports, data sources)

**Link to developer documentation**
https://developers.google.com/looker-studio/integrate/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes I need an app to manage oauth

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Just need the auto

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/looker-studio
