### ISSUE TITLE
benzinga[APP]

### ISSUE THREAD

**Issue by RAMSTO39** [PipedreamHQ/pipedream#1195]

**Comment by todsac** [comment]
@RAMSTO39 - can you help test this integration?  we are struggling to get a test account from Benzinga.

https://pipedream.com/apps/benzinga

**Comment by todsac** [comment]
Here is what they are asking for - "All we need is the clients name or email they used to setup a licensing agreement with Benzinga."  You can DM me on [Slack](https://pipedream.com/community) or email me at tod [at] pipedream.com.

**Comment by todsac** [comment]
@RAMSTO39 - trying one more time.  please let me know.
