### ISSUE TITLE
[APP] Draftable

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#1197]
**Name of app / service**: Draftable: PDF comparisons

**Link to developer documentation**: https://api.draftable.com/reference/authentication

**Comment by todsac** [comment]
Nacho - I implemented the first version.  I am curious what you think would be the test request.

https://pipedream.com/apps/draftable

**Comment by nachocab** [comment]
Thanks, Tod. 

I'm not sure, but maybe testing a publicly accessible pdf against itself?
