### ISSUE TITLE
[BUG] Slack direct message interpolation doesn't work for `$`

### ISSUE THREAD

**Issue by joscha** [PipedreamHQ/pipedream#11990]
**Describe the bug**
When using the slack direct message action and using a value from a previous step that has a dollar sign (`$`) in it, the interpolation doesn't work and it throws an error

**To Reproduce**
1. Create a workflow
2. Add a Slack direct message action
3. add an interpolation to the `Text` field that contains a `$`, e.g. `{{steps.my_step.$return_value}}`
4. Run it

**Expected behavior**
It should interpolate and THEN send the message further to the Slack API.

Escaping in any way, e.g. `{{steps.my_step.\$return_value}}` doesn't seem to make a difference.

I can't actually find the interpolation code in this repository here, it might be closed source as it's part of the product itself.
Given that other interpolations with `{{}}` work, my assumption is that somewhere it doesn't match `$` correctly.

**Screenshots**

Setup:

<img width="671" alt="scan_-_Build_-_Pipedream" src="https://github.com/PipedreamHQ/pipedream/assets/188038/7888937a-62ea-4a8e-bdbb-4a57b2768060">

error:

<img width="551" alt="scan_-_Build_-_Pipedream" src="https://github.com/PipedreamHQ/pipedream/assets/188038/c3e08280-5e39-4504-9596-09e60a6354d3">

**Comment by joscha** [comment]
@vunguyenhung you can see the full text in the screenshot above (except for a sensitive URL which I have masked). Can you try this text? The URL itself without the interpolation containing `$` works, so I don't suspect this to be the issue, but if you can still not reproduce it, I can send you the workflow ID via the pipedream support channel.

**Comment by joscha** [comment]
> @joscha  Would escaping the backticks like this works for you?

Oh, I wasn't aware the back ticks needed to be escaped. Apologies I had missed that they could be an issue.
I assumed they'd be sent verbatim as the text block was going to be processed. Escaping is not a problem at all, will the text still show up as inline code in Slack?
And can you make sense of the error message relating to the `$`? If this error message is constructed by pipedream it might make sense to improve it?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
