### ISSUE TITLE
Google Slides >  Merge Data

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11998]
### App
Google Slides >  Merge Data

### Summary:
Placeholders And Image URLs part does not replace place holder images, inserting objectId as key or contentUrl as key does not work

### Details:
Merging based on text box place holder value works fine. Attempts to use Image place holder replacement doesn't work, I've attempted to use objectId of that page element, have attempted to use contentUrl of the place holder image element and no matter what I do, it is unable to find-n-replace.

Also issue with the description of the element for both text & imager:
"The placeholders and texts to be merged into the presentation. So the key should be the placeholder ID and the value should be the text to be merged. As a placeholder example you can use {{name}} and the value can be John Doe."

That's for text box data, that description is wrong. Using objectId doesn't work on text, I have to specify the Placeholder text content not the objectId. 

### Screenshots:
No screenshots included

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
