### ISSUE TITLE
shopify

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12001]
### App
shopify

### Summary:
error message with  CRM Product Orders > Shopify Order Fulfillment Automation 

### Details:
I'm setting up a webook to integrate my CRM (gohighlevel) with shopify.  I've created an app in shopify, enabled read and write orders, I've linked up the products in my CRM with shopify via a google sheet.  The first two steps have the green tick.  Then nodes have errors, and the final step, the shopify developer app has an error message.  I've attached a screenshot.  Could you please take a look.  

I have an issue to do with 'orders'?  I've enabled 'write' and 'read' orders in the app... can you think of anything else that might be stopping this get cleared?

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-05-20-at-11.16.44-am.png?id=qDBbQk&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InFEQmJRayIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcxNjE2OTI2M30.1_RhcsL5fYSWakvd9pKaw_aTfLpj7QAtQAUrYluG-bg&signature=55757891f0aaa6d5b97d1bd2b8567eaa5b8ea705a14d5be7c54a91ec91579a27)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
