### ISSUE TITLE
LocateInv [APP]

### ISSUE THREAD

**Issue by optimumdinosaur** [PipedreamHQ/pipedream#1200]
[Locate Inventory system](https://locateinv.com/)
This one's API-key based.

**Comment by todsac** [comment]
@optimumdinosaur (John) - Can you test the initial integration?

https://pipedream.com/apps/locate

**Comment by todsac** [comment]
Ok, I updated.  Can you click "Connect Locate and Run" and test the integration?

https://pipedream.com/apps/locate

**Comment by optimumdinosaur** [comment]
Sorry; my format for the header wasn't very clear. The Authorization header should be "Basic " followed by a base64 encoded version of "{key}:{key}". I set it up on my own machine like this:
`var dblkey = `${key}:${key}`;
var bufferObj = Buffer.from(dblkey, "utf8");
var encodedDblKey = bufferObj.toString("base64");
var auth_header = `Basic ${encodedDblKey}``

Thanks again for your quick and very appreciated help!

**Comment by todsac** [comment]
That is what I had before.  Did you try it and it didn't work?

**Comment by optimumdinosaur** [comment]
Oh jeez; I'm sorry. That seems to be working!

**Comment by todsac** [comment]
Great!
