### ISSUE TITLE
[ACTION] Change API host on Toggl actions

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1207]
Toggl is moving their API host to api.track.toggl.com. We'll need to update all Pipedream actions accordingly.

**Comment by sergioeliot2039** [comment]
Actions were updated to use the new API host.
Enhancements to the code base were done too, such as using validation on required parameters, proper use of a non-deprecated method for using node.js' Buffer when signing requests.

Workflows using the modified actions:
Get time entry details
https://pipedream.com/@sergio/toggl-get-time-entry-details-p_BjC9roB/edit

Stop time action
https://pipedream.com/@sergio/toggl-stop-time-action-p_7NCPZa/edit

Create project
https://pipedream.com/@sergio/toggl-create-project-p_brC8pk/edit

Create time entry
https://pipedream.com/@sergio/toggl-create-time-entry-p_pWC6RK/edit

Create task
https://pipedream.com/@sergio/toggl-create-task-p_mkCaJb/edit

Create client
https://pipedream.com/@sergio/toggl-create-client-p_8rCOVP/edit

Start time entry
https://pipedream.com/@sergio/toggl-start-time-entry-p_vQCOYa/edit
