### ISSUE TITLE
[APP] Qdrant

### ISSUE THREAD

**Issue by Anush008** [PipedreamHQ/pipedream#12096]
**Name of app / service**
Qdrant

**Link to developer documentation**
https://qdrant.tech/documentation/

## Description

Hey guys. Greetings from Qdrant 👋.

We've built some actions for interfacing with Qdrant in Pipedream that we intend to contribute. Could you please init a `qdrant` app for us? We can then PR our actions to the app.

**Comment by sergio-eliot-rodriguez** [comment]
And let us know if any help is needed here or on our Slack thread. Cheers
