### ISSUE TITLE
[FEATURE] Named Versions for Workflows (maybe Actions too?)

### ISSUE THREAD

**Issue by eltonmorais** [PipedreamHQ/pipedream#1210]
**Is your feature request related to a problem? Please describe.**
Every code we save generates a version number. It's quite common that we get lost on those numbers. In which one I made that specific change? The previous number it's the last valid version, or it was just some `'` or `,` fix? So we have to dig and navigate through many version numbers.

**Describe the solution you'd like**
It was awesome if we could name any version we want. Not obligatory. Just those we found relevant. The `name `would be shown exactly the way the number is. But with the `name` instead of the `number`. A plus would be the ability to filter the list to show only named versions.

**Do you have a workaround?**
No. 

**Comparable features in other tools?**
It would be like a commit comment, BUT simpler, with the ability to name it after creation, when I want, not only on commit.

**Comment by dylburger** [comment]
@eltonmorais If you had a way to manage workflows in your own Git repo, and assign Git tags to specific commits, would that solve your use case? Or would you still want a way to assign names to specific Pipedream deploys?

I'm generally curious if you'd prefer to work in the Pipedream UI or, if we had a way to develop workflows locally, you'd want to manage workflows that way.

**Comment by eltonmorais** [comment]
@dylburger , for me, manage them in a Git Repo would be awesome and solve my needs for sure.

**Comment by dylburger** [comment]
Nice, that's good feedback, thanks!

**Comment by eltonmorais** [comment]
@dylburger , I'm trying the new Actions right now. I think that it will be awesome. I didn't tested yet, but I think that I will be allowed to include files and work some Actions as more complex elements, with classes and all I need. Well, let's see...

But I'm writing here to tell a "not good" part.

The former PipeDream UI for Actions isn't as powerfull as the new version. BUT it was more accessible for newbies. People that don't even use node yet, but can create a few lines. People that don't works regularly with versioning...

Remove that UI from PipeDream it's a bad move IF YOU PLAN to help those people. I think you should, because the more experienced developers are a shorter public, and sometimes use their own server...

Well, just a feedback. I love the enlarged bounderies that the cli version gave me, but I just can't recommend PipeDream for a bunch of friends that just can't work with the new version.

**Comment by dylburger** [comment]
@eltonmorais I hear you completely, and it's very valid feedback. We considered this tradeoff a lot when developing this new version of actions.

Our hope is that we can make the current process even simpler (so that you could author actions in the UI again, for example). I would hope the tooling improvements with the CLI / local dev environment will also improve dramatically over time, so that it's friendlier to people less familiar with Node.

We certainly don't have all of the answers yet, but the issues you raised are top-of-mind for us, and I shared this feedback with the team.

**Comment by dylburger** [comment]
@eltonmorais since you mentioned a Git integration would solve this use case for you, I'm going to close this ticket, if you don't mind. I've linked this discussion to that ticket so we can discuss it more when we ship that feature.
