### ISSUE TITLE
[BUG] ErrorCannot find module '/opt/ee/node_modules/cheerio/lib/index.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by midanilo** [PipedreamHQ/pipedream#1211]
**Describe the bug**
I have a workflow working with cheerio and today (06) after about 12:00 PM (-3 UTC - Brazilian time), it's has stopped to work and I'm receiving this error:

ErrorCannot find module '/opt/ee/node_modules/cheerio/lib/index.js'. Please verify that the package.json has a valid "main" entry

**To Reproduce**
- Import cherrio package to nodejs code and try to consume then

**Expected behavior**
Returns the body as jquery like style.

**Additional context**
The workflow was working without any problem, is something changes in pipedream platform?
I have already check service status page and everything appears to be normal.

**Comment by dylburger** [comment]
Hi @midanilo , would you mind sharing the specific `cheerio` code you're using? I just created an [example workflow](https://pipedream.com/@dylburger/cheerio-example-p_brCgGMm/edit) from the `cheerio` `README` and it appears to work OK:

```javascript
const cheerio = require('cheerio');
const $ = cheerio.load('<h2 class="title">Hello world</h2>');

$('h2.title').text('Hello there!');
$('h2').addClass('welcome');

$.html();
```

**Comment by dylburger** [comment]
Actually, it looks like [this may have been an issue with the `1.0.0-rc.8` version](https://github.com/cheeriojs/cheerio/issues/1843) of the package. They immediately shipped a new version — `v1.0.0-rc.9` — that addressed this.

**Comment by midanilo** [comment]
Hi @dylburger,

Below some piece of my code, basically I query the gym calendars to check classes availability and send me an email when some of that is available.
I tried to run again the workflow, but I still receiving this error.
Is it possible to force a reload of package or set a specific version?

`const consultaHorario = async (data) => {
  const config = { 
    url: `https://www.beeat.com.br/calendario/${data}`,
  };

  const html = await require("@pipedreamhq/platform").axios(this, config);

  const cheerio = require('cheerio');

  const $ = cheerio.load(html);
  let obj = {};

  $('.dias-semana .box-title h4').each(function(k, v) {
    obj[$(v).text()] = null;
  });

  $('.col-horario').each(function(k, v) {
    let horario = {};

    $(v)
    .find('.horario')
    .each(function(k2, el) {
      horario[$(el).find('.inicio').text().replace(/\n/g, "").trim().split(" ")[0]] =
        {
          professor: $(el).find('h2').text().replace(/\n/g, "").trim(),
          duracao: $(el).find('h3').text().replace(/\n/g, "").trim(),
          link: $(el).find('a').attr("href")
        }
      });

    obj[Object.keys(obj)[k]] = horario;
  });

  return obj;
};

// sample call to query calendar from a gym
let consulta = await consultaHorario('07-05-2021');

// do some stuff...
`

**Comment by dylburger** [comment]
@midanilo can you try deploying a new version of your workflow (just add a space after a line, for example, or make another trivial change)? That should create a new execution environment with the new version of the package. Let me know if that works.

**Comment by midanilo** [comment]
> 
> 
> @midanilo can you try deploying a new version of your workflow (just add a space after a line, for example, or make another trivial change)? That should create a new execution environment with the new version of the package. Let me know if that works.

easy peasy solution!
hahaha!
it worked!

Thanks!

**Comment by dylburger** [comment]
Glad to hear!
