### ISSUE TITLE
[Components] ispring_learn

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12126]
# ispring_learn
## URLs
- https://ispringhelpdocs.com/ispring-learn/api-documentation-10685383.html
#### Prompt
Emit new event when courses or materials in a course are completed successfully. Required props: course or material ID.
#### URLs
- https://ispringhelpdocs.com/ispring-learn/registering-a-new-subscriber-62863673.html
- https://ispringhelpdocs.com/ispring-learn/adding-a-subscription-62863687.html
#### Prompt
Emit new event when new user is registered. Required props: user registration data; optional: user profile data.
#### URLs
- https://ispringhelpdocs.com/ispring-learn/registering-a-new-subscriber-62863673.html
- https://ispringhelpdocs.com/ispring-learn/adding-a-subscription-62863687.html
#### Prompt
Emit new event when learners are enrolled in courses. Required props: course ID and learner's user ID; optional: enrollment date.
#### URLs
- https://ispringhelpdocs.com/ispring-learn/registering-a-new-subscriber-62863673.html
- https://ispringhelpdocs.com/ispring-learn/adding-a-subscription-62863687.html
#### Prompt
Allows to modify the properties of a specific user on iSpring Learn. Props required: User ID, fields to be updated.
#### URLs
- https://ispringhelpdocs.com/ispring-learn/getting-a-list-of-users-page-by-page-22610347.html
- https://ispringhelpdocs.com/ispring-learn/updating-user-profile-10684933.html
#### Prompt
Fetches the list of user enrollments on iSpring Learn. Props required: filters (to narrow down the results).
#### URLs
- https://ispringhelpdocs.com/ispring-learn/getting-a-list-of-courses-page-by-page-22610353.html
- https://ispringhelpdocs.com/ispring-learn/getting-a-list-of-users-page-by-page-22610347.html
- https://ispringhelpdocs.com/ispring-learn/getting-a-list-of-enrollments-17304245.html
#### Prompt
Enrolls users to the specified courses on iSpring Learn. Props required: User IDs, course IDs.
#### URLs
- https://ispringhelpdocs.com/ispring-learn/getting-a-list-of-users-page-by-page-22610347.html
- https://ispringhelpdocs.com/ispring-learn/getting-a-list-of-courses-page-by-page-22610353.html
- https://ispringhelpdocs.com/ispring-learn/creating-an-enrollment-17304228.html

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-ispring_learn-11a1287f08fe4059bc37b201e74ac229

Hi @vunguyenhung.
Could you try again? I couldn't reproduce the error
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/7c387c72-d553-4c23-bc26-743822c91073)
