### ISSUE TITLE
[Google generative ai]

### ISSUE THREAD

**Issue by mohit943** [PipedreamHQ/pipedream#12136]
Ai model

**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @mohit943 

Thanks for the request.

Can you please share the URL for this app's website and API documentation?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
