### ISSUE TITLE
[BUG] Create new account form's test connection button always fail

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#12144]
**Describe the bug**
When you create a new account in workflow builder with valid auth credentials, the test connection button always fails. If I disregard it, save the connection and use it in an action, it works fine.

**To Reproduce**
1. Go to some app featured in the martketplcae, such as Qdrant https://pipedream.com/apps/qdrant
2. Click on 'Connect <app> and run'
3. Follow on screen steps to create a workflow
4. On the right code editor, click "Select <app> account"
5. Hit "Create new account"
6. Enter working, valid auth credentials
7. Hti test connection

**Expected behavior**
Test connection should pass

**Screenshots**
Test connection always fail even if auth creds are correct
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/5dc95645-0267-4013-8f60-70dc0eb2662e)
if you disregard and run the workflow, it works.
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/fb3167b7-cfff-4afc-a42c-fdbb525350c1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 126.0

**Additional context**
Reported by Qdrant app representative via Slack https://pipedream-users.slack.com/archives/C0229H2JNA3/p1716778236772599?thread_ts=1716488340.834129&cid=C0229H2JNA3

See Qdrant¿s auth cred to test at 1PW

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
