### ISSUE TITLE
Event History: Usability improvement (quick win)

### ISSUE THREAD

**Issue by bacherjo** [PipedreamHQ/pipedream#12142]
**Is your feature request related to a problem? Please describe.**
Sometimes I have dozens or even hundreds of failed workflows (due to some failing partner system) and must replay the events manually. Since there is still no "multi replay" feature I have to go to event history and click "replay" manually on each line. This takes 1-2 seconds, then opens a popup where I can cancel or inspect, I cancel. Then I must do the same with the next line, but meanwhile I have lost the focus which line is next. this is very annoying.

**Describe the solution you'd like**
Can the replay work like in the workflow itself, where I can just click the three dots and choose "Replay" and that's it. No popup required. This would make things MUCH faster. 
Also, same as in the workflow,  i coudl click "Replay" and then "Delete" and I am done and keep the history clean. No popups please!

**Do you have a workaround?**
Yes I have an excel sheet with 21 lines numbered, and I place it right to my pipedream history window, so that I know which line I have clicked. what a shame.

**Comparable features in other tools?**
We need better filtering and "mass replay" in the event history, as i other tools. But this my feature requests is probably easy to do beforehand.

**Additional context**
Thank you!

**Comment by bacherjo** [comment]
Hi @vunguyenhung yes the batch features would help, but I assume it will be kong until something is finished, so I proposed the "quick win" if you just remove the annyoing popup that appears afeter event replay.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by bacherjo** [comment]
Hi @dylburger I am wondering what more information you might need, except for my descriptions why the event history is a pain and my suggestion, to at least remove the annoying confirmation popups so to make it a bit more usable.
Regards, Johannes

**Comment by dannyroosevelt** [comment]
@bacherjo sorry, that was just a workflow automation gone awry 😄 

This is a great suggestion, we'll run it by the team.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
@bacherjo we did you one better and shipped support for bulk replay and delete!
https://pipedream.com/docs/event-history#bulk-actions

**Comment by bacherjo** [comment]
Hi @dannyroosevelt 
this is great - thanks a lot!

BUT: I noticed that replayed events are no longer marked as "replayed" in the inspector. All events are just showing the green cheeckmark. Before, there was an icon with green checkmark and a replay sign.

**Comment by dannyroosevelt** [comment]
> Hi @dannyroosevelt this is great - thanks a lot!
> 
> BUT: I noticed that replayed events are no longer marked as "replayed" in the inspector. All events are just showing the green cheeckmark. Before, there was an icon with green checkmark and a replay sign.

We've actually never displayed any indication that events have been replayed, only that an event was from a replay. I agree that'd be really valuable to display though, potentially with some type of visual link between the original event and the replay.
