### ISSUE TITLE
[APP] Turso

### ISSUE THREAD

**Issue by nbbaier** [PipedreamHQ/pipedream#12157]
**Name of app / service**
Turso, a cloud based sqlite servie

**Link to developer documentation**
https://docs.turso.tech/introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Not currently, but I think it would be nice to have.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Would be great to have a Turso integration that mirrors the integrations for MySQL and Postgres

**Comment by sergio-eliot-rodriguez** [comment]
Hi @nbbaier 

Thanks for the request, Turso has now been integrated

https://pipedream.com/apps/turso
