### ISSUE TITLE
[ZOHO Maketing Hub]

### ISSUE THREAD

**Issue by GabrielDillenburg** [PipedreamHQ/pipedream#1216]

**Comment by todsac** [comment]
Gabriel - can you clarify which apps / scopes you would want for a marketing hub integration?  are you referring to all the apps in the Marketing Plus product (https://www.zoho.com/marketingplus/?src=top-header&ireft=Marketing%20Automation-bu)?

**Comment by dylburger** [comment]
Closing due to lack of information
