### ISSUE TITLE
[BUG] Object prop, when there're many fields, the UI is overflowed and can not scroll in Workflow V2 and Workflow V3

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12177]
**Describe the bug**
Please check [the workflow by the customer here > create_intraanaes_notes](https://pipedream.com/@capserdang/projects/proj_e5sKL5/tally-census-adult-core-wa-passover-intraanaes-postop-review-kpis-dxt-carotid-puncture-aps-p_5VConyk/build)

Workflow V3
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/ffd0534d-ae2d-44fe-9609-fc329c5b135a)

Workflow V2
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/7f7d379f-fd01-43e6-a443-801c55a10ff4)

**Additional context**
Reported by a customer here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1717149149895129

**Comment by malexanderlim** [comment]
This has been fixed.
