### ISSUE TITLE
[Components] flippingbook

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12200]
# flippingbook
## URLs
- https://apidocs.flippingbook.com/#flippingbook-public-apis-general-information
#### Prompt
Emit new event when a new flipbook is created. There are no required or optional props for this trigger.
#### URLs
- https://apidocs.flippingbook.com/#emit-new-event-when-a-new-flipbook-is-created
#### Prompt
Emit new event when there are any interactions with a trackable link. The link is a required prop, it's the unique link that user wants to track.
#### URLs
- https://apidocs.flippingbook.com/#link-tracking
- https://apidocs.flippingbook.com/#http-methods
- https://apidocs.flippingbook.com/#request-parameters
#### Prompt
Emit new event when a new lead is created via a lead capture form. The form ID is a required prop, it signifies the particular form where the lead was captured from. An optional prop may include the lead details.
#### URLs
- https://apidocs.flippingbook.com/#create-a-new-lead
- https://apidocs.flippingbook.com/#get-lead-details
- https://apidocs.flippingbook.com/#update-a-lead
- https://apidocs.flippingbook.com/#delete-a-lead
#### Prompt
Generates a new flipbook from an input PDF file. Users are required to input a PDF file of maximum size 100 MB as prop.
#### URLs
- https://apidocs.flippingbook.com/#post-upload
#### Prompt
Edits an existing flipbook by replacing it with a new input PDF file. Users should provide the ID of the flipbook to be updated as a mandatory prop, along with the new PDF file below 100 MB.
#### URLs
- https://apidocs.flippingbook.com/#replace-flipbook
#### Prompt
Locates a specific flipbook using the provided title as prop. The action returns details of the flipbook that matches the input title.
#### URLs
- https://apidocs.flippingbook.com/#get-flipbook-title-details-by-id

**Comment by sergio-eliot-rodriguez** [comment]
This is a caveat about FlippingBook's triggers sent by app developers:

> Glad to hear that! There's one thing I wanted to bring to your attention (even though it is in the API docs): **The trigger that fires when you open a Trackable link is fired only for the first 10 times you open a link. T**his is by design but may cause confusion during testing when you are suddenly faced with a situation where it looks like it doesn't work anymore!
