### ISSUE TITLE
[BUG] Help text for new user doesn't recognize new connected account

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#1222]
**Describe the bug**
I signed up a new user today for testing (ray@camdenfamily.com), and have noticed some helper text on top. I've made an account (with Twitter), but I still see the helper text suggesting I do that:

![image](https://user-images.githubusercontent.com/393660/117886622-19480480-b275-11eb-928c-e6bded060146.png)

I created the account via the workflow process, not the Account UI itself, and I'd be willing to bet most people will do that as well.

**To Reproduce**
1. Make a new user.
2. Make a new workflow and use something that requires a connected account.
3. Go to the Accounts page, you will see your new account, but also the help text doesn't think you actually did it.

**Screenshots**
See above.

**Comment by dylburger** [comment]
We have a fix on a branch with some other changes, should go out soon!

**Comment by dylburger** [comment]
This was fixed soon after the issue was opened. Closing now!
