### ISSUE TITLE
[APP] Zenkit

### ISSUE THREAD

**Issue by jgeofil** [PipedreamHQ/pipedream#1227]
**Name of app / service**
Zenkit
**Link to developer documentation**
https://base.zenkit.com/docs/api/overview/introduction
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
New task
Task completed

**Comment by todsac** [comment]
@jgeofil - I have integrated Zenkit.  Here is the base integration - https://pipedream.com/apps/zenkit

Are you interested in developing the actions and/or triggers?
