### ISSUE TITLE
SQL service: support deletion of tables

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#123]

**Comment by sreejith-ms** [comment]
@dylburger 

My tables and data are not getting removed even after 30 days.
I need to delete all the tables and data, what to do?

**Comment by dylburger** [comment]
@sreejith-ms can you email support@pipedream.com with your Pipedream username and the names of the tables you'd like us to delete for confirmation ?

**Comment by dylburger** [comment]
To clarify for others - data is deleted from the SQL service after 30 days, according to the [retention policy](https://docs.pipedream.com/destinations/sql/#data-retention) of the SQL service. 

Table _metadata_ is retained after 30 days. So if you don't send any data to a specific table for 60 days, for example, all of the data delivered to that table will have been automatically deleted. But you'll still see the table schema listed at https://pipedream.com/sql. This is by design - we don't want to automatically delete your table schema if you happen to have a period of > 30 days for which no data is delivered to the service.

**Comment by dylburger** [comment]
The SQL Service will be shutting down on Feb 10th, 2022 (you can read more details in [this post](https://pipedream.com/blog/shutting-down-the-sql-service/)). As a result, we're closing this issue.

Let us know if you have any questions at all.
