### ISSUE TITLE
[BUG] Add link to Discourse on Support page

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#1231]
**Describe the bug**
The support page (https://pipedream.com/docs/support/) does not link to the Discourse forum.

**Expected behavior**
A link. ;)

Also... does it make sense to have GitHub Discussions *and* Discourse? I'd maybe kill off the GH Discussions, but I don't know well it's working for yall. On the Support page though I'd focus on one.

**Comment by dylburger** [comment]
@cfjedimaster good catch. I link to https://pipedream.com/support now in the **Community and Support** section of the sidebar, replacing the duplicate, standalone docs page.
