### ISSUE TITLE
[BUG] Pipedream POST /v1/workflows API does not update Custom Trigger props

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12327]
**Describe the bug**
The Pipedream [POST /v1/workflows API](https://pipedream.com/docs/rest-api#create-a-workflow) does not update User-created trigger props

**To Reproduce**
1. Create a Custom Source and publish it, here's the code I use
```js
// Core HTTP component
export default {
  key: "test-source",
  name: "Test Source Leo",
  description: "Emit a test event every run",
  version: "0.0.1",
  type: "source",
  props: {
    testBoolean: {
      type: "boolean",
      label: "Test Boolean",
      description: "Test Boolean",
      optional: true,
      default: false,
    },
    testString: {
      type: "string",
      label: "Test String",
      description: "Test String",
      optional: true,
      default: "200",
    },
  },
  async run() {
    const body = {
      testBoolean: this.testBoolean,
      testString: this.testString,
    };
    const summary = JSON.stringify(body);

    this.$emit(body, {
      summary,
    });
  },
};
```

2. After publishing the source, add it as a trigger on a workflow
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/2e7ff3a1-a520-4489-8290-60457594976b)

3. On Workflow setting, select `Instantiate via API`, enable `Include all props`
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/15f03416-7568-47e4-aed3-7d885fe5ff4f)

Notice the template values:
- testBoolean: true
- testString: Test String 1631

4. On the API Request, update the trigger prop values 
<img width="643" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/1e5dd187-31d9-4dee-a223-90efddf6f76c">

- testBoolean: false
- testString: Test String Updated 1632

5. Observed that in the created workflow, the updated props does not applied
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/eb12d2a7-1df4-4670-9a69-009120d5cf93)

This behavior is mismatch with the case where I use Pipedream's sources:
- My template has a Slack New Message trigger, with the Channels prop set to 3 channels
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/50ee432f-e2f1-4dea-8e75-45b5b99d1e98)

- On the Instantiate via API popup, I can see the channels prop are stated as conversations field
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/83736f39-b574-48df-9ca5-30ffd0a9cc7f)

- Then on my POST /v1/workflows payload, I removed other 2 channels, then send the request
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/f71a6a2c-f7eb-4384-ac5f-ae1f8cc30b65)

- After the request resolved, checked the new workflow, I see that it only have 1 channel set
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/6ed80ca4-38e8-49f0-93f1-3a982fd90b5a)

**Expected behavior**
We should update the behavior for it to match with the case where I use the Pipedream source.

I believe this is because the new workflow **used the same source (in case of User Custom Source) as the template.**

**Additional context**
Reported by a Business Customer: https://app.frontapp.com/open/cnv_n9va79j?key=MdRZGTo8NaTTLSeLINZzQpWxUWje9ef1

**Comment by malexanderlim** [comment]
This has been fixed! I've validated this and confirmed that I am now able to modify prop values for triggers without issues.
