### ISSUE TITLE
[BUG] Hitting Enter in Auth window causes page reload

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#1233]
**Describe the bug**
I'm in a workflow with a Fauna DB step. I clicked the button to open the auth window. In there I entered my key, then a nickname, and then hit enter. Instead of submitting the form, it caused the window to load and my auth was not saved.

**To Reproduce**
1. Go to a Fauna step w/o authentication.
2. Click to add auth
3. Enter key and nickname
4. Hit the enter key

**Expected behavior**
That it would save my key/nickname.

**Comment by dylburger** [comment]
Should be fixed in ~10 min after this deploy. Thanks for letting us know!
