### ISSUE TITLE
[FEATURE] Add SQL Proxy support to Snowflake

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#12342]
**Is your feature request related to a problem? Please describe.**
In order for Snowflake to support the new [SQL Proxy](https://pipedream.com/docs/databases#enabling-the-shared-static-ip), the components code needs to implement the interface defined in [`@pipedream/platform`](https://github.com/PipedreamHQ/pipedream/blob/master/platform/lib/sql-proxy.ts).

**Describe the solution you'd like**

Specifically, the `snowflake.app.mjs` module must implement these methods:
1. ~`getClientConfiguration`: a method that takes no arguments, and returns an object that can be fed directly to the Snowflake SDK when creating a new client/connection~ (already implemented in #12357)
2. `executeQuery`: this method should be **the only one** that actually makes the request to Snowflake, and every Snowflake component should call it when they need to query the DB. You can look at the [MySQL](https://github.com/PipedreamHQ/pipedream/tree/master/components/mysql) and [PostgreSQL](https://github.com/PipedreamHQ/pipedream/tree/master/components/postgresql) components in case you need examples since these 2 apps already support the SQL Proxy.
3. `proxyAdapter`: the SQL Proxy has its own logic to call the DB, and it expects the query and parameters to be structured in a certain way, which could be different from the structure expected by the `executeQuery` method in the components. The SQL Proxy will call this method so that whatever the components send to `executeQuery` the Proxy can transform that data into something that it can use safely.

**Do you have a workaround?**
No, without these changes we can't support Snowflake in the SQL Proxy.

**Comparable features in other tools?**
N/A

**Additional context**
1. MySQL PR: https://github.com/PipedreamHQ/pipedream/pull/11201
2. PostgreSQL PR: https://github.com/PipedreamHQ/pipedream/pull/11202

**Comment by dannyroosevelt** [comment]
We should also use this as an opportunity to support an additional authentication method for Snowflake: `private_key`. This field doesn't yet exist on the Snowflake app, but we'll add it when this work is in progress. When configured, the `$auth` object will contain _either_ `password` _or_ `private_key`.

**Comment by jverce** [comment]
> We should also use this as an opportunity to support an additional authentication method for Snowflake: `private_key`. This field doesn't yet exist on the Snowflake app, but we'll add it when this work is in progress. When configured, the `$auth` object will contain _either_ `password` _or_ `private_key`.

This was done in #12357
