### ISSUE TITLE
[BUG] Gmail Developer App - Download Attachment action should only return file path to tmp dir

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12356]
**Describe the bug**
Currently, the Gmail (Developer App) - Download Attachment action [returns the whole attachment data](https://github.com/PipedreamHQ/pipedream/blob/5349474ca3d42e8aaee3555fc63c97e457bc4382/components/gmail_custom_oauth/actions/download-attachment/download-attachment.mjs#L48) which might **cause `Function Payload Limit Exceeded` if the payload is larger than 6mb**

In the Gmail (Developer App) - Download Attachment action, please only return the filePath

**Additional context**
Reported by a customer here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1718019046233869

**Comment by DelicateAlchemy** [comment]
Can I get a bump on this?

**Comment by DelicateAlchemy** [comment]
<img width="963" alt="Screenshot 2024-06-29 at 16 14 06" src="https://github.com/PipedreamHQ/pipedream/assets/102681446/f658c45d-e545-41ba-85cc-f4d3bd44b47d">
Just an update - I tried writing some custom code in node instead and I am getting the same error
