### ISSUE TITLE
[APP] - HighRise

### ISSUE THREAD

**Issue by Lucas-Munisteri** [PipedreamHQ/pipedream#1235]
Highrise is a defunct CRM from the makers of basecamp. 

https://github.com/basecamp/highrise-api

**Comment by todsac** [comment]
Demo - https://pipedream.com/apps/highrise

Open question is whether we should consider Oauth given that we have it already for Basecamp.  However, the Highrise product is at end of life and we cannot test on our end moving forward.

**Comment by dylburger** [comment]
@Lucas-Munisteri if you have a chance, would you mind testing this integration and let us know if it works for you?

**Comment by dylburger** [comment]
Closing this since the app is integrated, but let us know if you have any issues / questions about the integration
