### ISSUE TITLE
[APP] Zoho Projects

### ISSUE THREAD

**Issue by natpalmer-e4o4** [PipedreamHQ/pipedream#1237]
**Name of app / service**

Zoho Projects

**Link to developer documentation**

[Developer Documentation](https://zoho.com/projects/help/#for-developers)

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I could in theory create pipelines to interface with Zoho Projects given the amount of flexibility currently built into PipeDream, however it would simply not be time-effective over implementing the same functionality in an on-premise solution.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

I would like to have an action available to enter time in the Timesheets section based on external triggers, as well as triggers for when a new task is assigned to my user.

**Comment by dannyroosevelt** [comment]
@natpalmer-e4o4 apologies for the delay in getting this one live -- we just released a basic integration here: https://pipedream.com/apps/zoho_projects.

If you're interested in developing any actions or triggers for Zoho Projects, all our components are open source and hosted in GitHub. Check out our [getting started guide here](https://pipedream.com/docs/components/guidelines/#getting-started).

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
