### ISSUE TITLE
[BUG] Basecamp - Column ID prop only show columns on the first Card Table

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12378]
**Describe the bug**
Basecamp - Column ID prop only show columns on the first Card Table

**To Reproduce**
1. On Basecamp, I have 2 Card tables:
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/e3bfca99-a42b-4671-823c-5b69ad470aba)

Card Table 1 has the following columns
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/93f5e317-4aaa-4ba9-b378-042be001ede0)

Card Table 2 has the following columns
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/ad4ce020-7225-48c9-86b6-bcfea93d2aee)

Though the Column ID prop only show columns from the first Card Table - which is Card Table 1
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/80591b28-2a1b-4c5f-9656-c4c46a41ecea)

**Expected behavior**
The Column ID prop should show columns from all Card Tables. With the following format:
- {Card Table Name}/{Column Name}

For example: `Card Table 1/Column 1`

**Additional context**
Reported by a customer here: https://app.frontapp.com/open/cnv_na7ru87?key=gzqjvPvYKC0KT946RrdygcbLlu1asSGm

**Comment by kramosv77** [comment]
Hello, is there any progress? Is there an estimated date to resolve the detail presented? Tks.
