### ISSUE TITLE
[IMPROVEMENT] Peaka Connection Popup - Update API Key prop description

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12372]
**Is your feature request related to a problem? Please describe.**
On the Peaka connection popup, the `API Key` description as follow:
```
To get your API Key, sign in and go to one of your projects under "Projects" > "My Projects". In your project's page, click the gear icon on at the top left of the page, and go to "API Keys".
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/768e3038-c6f7-4b67-ba67-f569a4ce8014)

But the Project Key API did not work
<img width="437" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/c19841a4-9059-4bc5-8e19-e65c0f60140e">

We need to use Partner API Key, which is in the `Developer` tab. The `Developer` tab is enabled by contacting Peaka Customer Support.
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/33fc1eda-7a3e-48a3-a281-023fb7134115)

**Describe the solution you'd like**
- On Peaka Connection Popup, please update `API Key` prop description to instruct user contacting Peaka Customer Support for Partner API Key
- Also remove the optional Project ID prop, as all action currently allow user to select Project ID

**Comment by malexanderlim** [comment]
Thanks for the suggestion @vunguyenhung  - I've updated the connection instructions accordingly.
