### ISSUE TITLE
[BUG] Event History - "Build from Event" feature does not select events from Builder UI

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12371]
**Describe the bug**
On Event History, when clicking on the "Build from Event" button, the UI switched to the Builder UI, but it does not select the right event

**To Reproduce**
1. On the Event History, select an event
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/f74a37bb-8bb0-4e2a-9042-ebf7e365f63f)
See that the event timestamp is `1718082946`
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/87a042ff-2fd7-4f5c-8b35-cee09b80e0c6)
2. Then click on "Build from Event" button
3. Observe that on the Builder UI, it is selecting incorrect event (timestamp `1718078050`)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/ec8138fd-d255-4759-9f43-a13e226e7efa)

**Expected behavior**
The Builder UI should select the correct event selected from the Event History

**Additional context**
Raised by a customer here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1718087880795569

**Comment by tjk** [comment]
Resolved (see https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1718241356963919?thread_ts=1718087880.795569&cid=CMZG4EBJ9)
