### ISSUE TITLE
[TRIGGER] Okta Event

### ISSUE THREAD

**Issue by justinr1234** [PipedreamHQ/pipedream#12410]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

I'd love to listen for Okta events https://developer.okta.com/docs/reference/api/event-types/ in order to do provisioning and deprovisioning on apps that don't natively support it (like Harvest time tracker).

Zapier has an integration for this already, but I prefer to use Pipedream.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

https://developer.okta.com/docs/reference/api/event-types/

**Comment by malexanderlim** [comment]
Hi @justinr1234 , we've just landed support for this - let me know if you have any feedback for us once you've had a chance to give it a try!
