### ISSUE TITLE
[APP] ProcFu.com

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#12419]
**Name of app / service**
ProcFu

**Link to developer documentation**
http://help.procfu.com/functions-api.php

**Comment by sergio-eliot-rodriguez** [comment]
Hi @marcelocecin 

Happy to annouce we have a base integration ready https://pipedream.com/apps/procfu

however you'll need to add to whitelist your workflow's IP for now. They are shown in the response when you call ProcFu.

**Comment by malexanderlim** [comment]
@marcelocecin , are you on the Pipedream Business plan? ProcFu requires users to whitelist the IP address of their traffic, and I've reached out to their team to inquire to see if they can whitelist the `us-east-1` IP range of AWS (where our traffic originates from.) 

If they are unable to do this though, you'd need to run the workflow in virtual private clouds (VPCs), which is available on the Pipedream **Business** plan - just wanted you to be aware of the limitation with the current setup.

**Comment by marcelocecin** [comment]
@malexanderlim they said it was not possible to include the region
via code, I can make requests using a proxy configuration
I don't know if it would be viable to include the option to also configure a proxy for a new account

**Comment by malexanderlim** [comment]
@marcelocecin can you elaborate on what you mean here? Would you be using Pipedream [VPCs](https://pipedream.com/docs/workflows/vpc) for this and whitelisting this on the ProcFu side?

**Comment by marcelocecin** [comment]
<img width="767" alt="" src="https://github.com/PipedreamHQ/pipedream/assets/2955762/314d75fd-08dd-4375-a65c-941480e7d75c">

**Comment by malexanderlim** [comment]
Thanks for clarifying.
