### ISSUE TITLE
[APP] Certifier

### ISSUE THREAD

**Issue by mariczne** [PipedreamHQ/pipedream#12418]
**Name of app / service**
Certifier

**Link to developer documentation**
https://developers.certifier.io/reference/introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It is preventing us from contributing a custom component due to [this issue](https://pipedream.com/community/t/why-does-my-custom-component-in-gitpod-say-app-is-not-valid-when-i-try-to-run-it/10437).

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
We plan to create the integration ourselves and contribute to the main repo.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @mariczne 

Happy to announce that we have added the Certified app: https://pipedream.com/apps/certifier

Let us know if you run into any issues while building the integration and we will support you in anyway we can.
