### ISSUE TITLE
Custom OAuth Scopes for Xero

### ISSUE THREAD

**Issue by LloydVickeryASI** [PipedreamHQ/pipedream#12446]
**Name of app / service** Xero Purchase Orders scope required

**Link to developer documentation** https://developer.xero.com/documentation/api/accounting/purchaseorders

**Is lack of support preventing you from building workflows, or do you have a workaround?** Yes, preventing me from creating Purchase Orders. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by LloydVickeryASI** [comment]
Ah, nevermind sorry. It turns out you need to include the Xero-Tenant-Id as a custom header or you will get an unauthorised error. https://developer.xero.com/documentation/guides/oauth2/tenants/

**Comment by sergio-eliot-rodriguez** [comment]
For anything Pipedream related let us know! :)
