### ISSUE TITLE
[BUG] Ecwid source - New paid order throws 403 error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12468]
**Describe the bug**
After creating the Ecwid source - New paid order, the source always throw 403 error for every run. Checking the Authentication header, it seems like we did not pass the token correctly
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/f3b7680f-19c7-4bd7-b7c9-11ca7f24ab94)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/e9a3f65a-ff20-4854-b80e-e2ab46dcc196) 

I'm not sure if this is an App issue or Component issue, so @sergio-eliot-rodriguez, could you do a check first to see if this is an app issue?

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1718104919654259

**Comment by sergio-eliot-rodriguez** [comment]
Hi @vunguyenhung 

I checked. It appears that this is a component issue. The reason being is that when adding a new Ecwid app connection, it will prompt for store id and secret token customfields

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/5f805396-bc53-4d61-8f1d-203c4ca55f6b)


however internally they are named an store_id and client_secret as variable when you debug the $auth object

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/e5419e49-f1b3-479f-95c5-532792766bc2)


when a new app is integrated to the registry apparently the app only contains a reference to the $object, here is for the Keen app (that has no components as of writting)

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/81790612-c990-4bf3-9943-840e15b94327)

however, then components are developed, certain methods are defined such us those passing over the custom fields whereever they are used. in the case fpor ecwid it appears that client_secret is being passed in one of the helper methods as access_token

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/958df988-f56e-4e76-8651-fefc2b9b094d)


in this case the

>     _accessToken() {
>       return this.$auth.oauth_access_token;
>     },

method should be modified to return client_secret instead

**Comment by sergio-eliot-rodriguez** [comment]
here's a heads up @vunguyenhung apparently the ecwid account was downgraded and you may have issues down the road, when using the test request it returns 402 payment needed, and in control panel shows suspended status.

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/ff2f7e7c-106f-4368-a23a-5bda28585f58)
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/89ee8bf4-f8dc-4b05-a6a4-f944a09dc76e)
