### ISSUE TITLE
[FEATURE] I want to view and manage components via a UI

### ISSUE THREAD

**Issue by psavkar** [PipedreamHQ/pipedream#1249]
> It would also be amazing if the custom actions would at least be listed in the UI just the same way custom sources are. Currently I can’t see my custom action anywhere but in the workflow editor and can’t delete/unpublish it from the UI.

https://pipedream.com/community/t/actions-improved-open-source-now-in-beta/606/2

**Comment by dylburger** [comment]
When we tackle the configuration of auth in components, see https://pipedream-users.slack.com/archives/CPTJYRY5A/p1636274779239600

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by dannyroosevelt** [comment]
This is available to try in early Alpha! https://pipedream.com/alpha

Feedback is welcome via [Slack](https://join.slack.com/t/pipedream-users/shared_invite/zt-11sazmsg0-oS2VW~mZfhtk3XfEEvb~JA), [GitHub](https://github.com/PipedreamHQ/pipedream/issues), or [Discourse](https://pipedream.com/community)!
