### ISSUE TITLE
git, tar, gcc and g++ should be added to the Pipedream component execution environment

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#125]
In my standard Node environment, I can `npm install` a package directly from a Github repo, and `require` the package once it's been installed.

Pipedream `npm install`s packages referenced in the `require` statement, but there's currently no way to  `require` a package via `git` or `ssh` URL, since `git` isn't installed in the environment that installs npm packages. I need to do this to install a package I forked in Github.

Moreover, `tar` is required for installing certain packages (e.g. `markdown-pdf`), so I'd like to see that added to the environment, too.

**Comment by dylburger** [comment]
Another failing package: https://github.com/microsoft/PhoneticMatching#example

**Comment by ctrlaltdylan** [comment]
Another example here,`bbopen` with pip:
https://github.com/PipedreamHQ/pipedream/issues/5326

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
