### ISSUE TITLE
Tauri

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12500]
### App
Tauri
https://tauri.app/v1/api/js/

**Comment by sergio-eliot-rodriguez** [comment]
Had another look at this one and it turns out this is a library 

> Build smaller, faster, and secure cross-platform applications with a web frontend. 

You install it via npm, in case they need users could install it via npm:

> 
npm create tauri-app@latest

per their [Quickstart guide](https://tauri.app/v1/guides/getting-started/setup)
