### ISSUE TITLE
I'm having issues syncing my Google Calendar into my Planning Center Calendar.

### ISSUE THREAD

**Issue by YalundaJ** [PipedreamHQ/pipedream#12526]
I'm not a stronger coder by any means. I'm using Pipedream to create a sync between my Google Calendar and my Planning Center calendar, but I'm having some issues at the custom request step and the code step. The code I've created is below. Can someone guide me?

import http from "../../http.app.mjs";

export default {
  key: "http-custom-request",
  name: "Send any HTTP Request",
  description: "Send an HTTP request using any method and URL. Optionally configure query string parameters, headers, and basic auth.",
  type: "action",
  version: "1.1.1",
  props: {
    http,
    httpRequest: {
      propDefinition: [
        http,
        "httpRequest",
      ],
    },
    includeHeaders: {
      type: "boolean",
      label: "Include Response Headers",
      description: "Optionally export the full response headers",
      optional: true,
    },
  },
  async run({ $ }) {
    const response = await this.httpRequest.execute();

    if (this.includeHeaders) {
      $.export("headers", response.headers);
    }

    return response;
  },
};

**Comment by sergio-eliot-rodriguez** [comment]
If you want to create an event in Planning Calendar when a new event is created in Google Calendar, then you need to start your workflow with "New Created or Updated Event" : https://pipedream.com/apps/google-calendar/triggers/new-or-updated-event-instant

There are many other Google Calendar based triggers you can look for more https://pipedream.com/apps/google-calendar#popular-google-calendar-triggers if you need.

Now the Planning Calendar app in [Pipedream](https://pipedream.com/apps/planning-center) doesn't have components developed yet but you can request by filing a [new issue](https://github.com/PipedreamHQ/pipedream/issues/new?assignees=&labels=enhancement%2C+good+first+issue%2C+help+wanted%2C+trigger+%2F+source&projects=&template=new-trigger---event-source.md&title=%5BTRIGGER%5D).

Id' recommend you focus on the Workflows section of Pipedream documentation: https://pipedream.com/docs/workflows

Specifically you'll want to check about starting workflow based on app triggers: https://pipedream.com/docs/workflows/triggers#app-based-triggers and then you may need to use app based actions: https://pipedream.com/docs/workflows/actions

Now for the type of help you are looking, besides the links I just shared with you, it is better you file your question on our Discourse [community](https://pipedream.com/community/), and [Join our community](https://join.slack.com/t/pipedream-users/shared_invite/zt-2bftue1w1-dkBvc_3UQAF99Qgg2zkhzg) and ask it on the #help channel.

Good luck
