### ISSUE TITLE
[APP] Ongage

### ISSUE THREAD

**Issue by compwright** [PipedreamHQ/pipedream#1252]
**Name of app / service**

Ongage

**Link to developer documentation**

https://ongage.atlassian.net/wiki/spaces/HELP/pages/13795818/API

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I would very much not like to have to specify credentials on each Ongage action that I create. Ongage does not use OAuth, and the app would simply store `username`, `password`, and `account_code`.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

I am happy to contribute those. An action to subscribe to a list would be the bare minimum.

**Comment by todsac** [comment]
Jonathan (@compwright) - Our account doesn't have API access so I can't confirm the app is setup correctly.  Would you mind testing?  I believe it is correct but verifying would help.  Also, please let me know how we can support you in the development of the event sources or actions.

https://pipedream.com/apps/ongage

**Comment by compwright** [comment]
The authentication setup is certainly correct. Based on what you sent me, I
created and tested the workflows below.

I would like to see the Ongage app published for storing credentials, and
to see public actions for the following common Ongage integration use cases:

   - Subscribe -
   ***@***.***/ongage-subscriber-proxy-p_JZCGGzm
   - Update subscriber -
   ***@***.***/ongage-update-demo-p_zACnnNe
   - Find subscriber -
   ***@***.***/ongage-find-subscriber-demo-p_WxCqqaB

If there are others you'd like to see included in the list, I can whip up
additional ones easily enough.

Thanks for the quick response!!

Jonathon

Sent via Superhuman ***@***.***>

**Comment by todsac** [comment]
I am not as close to this app so trust your judgment as to what would be valuable for Ongage customers.

Btw, we recently announced an updated model for public actions. Have you seen the update?  Here are the docs - https://pipedream.com/docs/components/quickstart/nodejs/actions/#overview

The short story is that you can develop components locally using your preferred code editor (and maintain your code in your own Github repo) and deploy or publish using Pipedream's CLI.

It would be ideal to get these actions developed in the new model if you are up for it.

**Comment by compwright** [comment]
@todsac yep, on it
