### ISSUE TITLE
[BUG] Snowflake - The schema box shows error when Use Shared Static IP = TRUE

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12535]
**Describe the bug**
The schema box shows error when I use the connection with Use Shared Static IP = TRUE
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/22ed1dd7-74eb-48e0-a2cd-ad4d39c1f0f9)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/a4650082-930c-4391-afaa-f6ab52085a96)

Note that I do **not** restrict IP address to my Snowflake instance. I can query it when Use Shared Static IP = FALSE
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/c8ee2c74-3d84-4988-b014-0766442c8aee)

**To Reproduce**
The setup as below:
a. Account
b. Username
c. Use Shared Static IP: TRUE
d. Warehouse
e. Database
f. Schema
g. Role
h. Password

**Expected behavior**
The schema box should show my database tables and their schema correctly

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
