### ISSUE TITLE
[BUG] Snowflake - Connection popup "Test Connection" button throw error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12533]
**Describe the bug**
Snowflake - Connection popup "Test Connection" button throw error
```
this.snowflake.collectRows is not a function
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/86d6a69c-366f-4482-b99f-6cc10a4ba925)

**To Reproduce**
1. The setup as below:
  a. Account
  b. Username
  c. Use Shared Static IP: TRUE or FALSE
  d. Warehouse
  e. Database
  f. Schema
  g. Role
  h. Password

**Expected behavior**
The Test Connection button should works 

**Note**
After saving the connection with `Use Shared Static IP = FALSE`, I can still execute the action
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/8a5f3743-951a-4fac-8d5e-c0c0a4050b62)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
