### ISSUE TITLE
[BUG] Snowflake - Components failed when Use Shared Static IP = TRUE

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12536]
**Describe the bug**
Actions
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/0b956f0b-f93f-4b83-a2f1-fb97848d0533)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/dd9e9f77-85f7-4111-a558-c69d84fecb3e)

Sources
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/f4878ef6-89b9-4a4f-85e2-6187a1e49a5c)

**To Reproduce**
The setup as below:
a. Account
b. Username
c. Use Shared Static IP: TRUE
d. Warehouse
e. Database
f. Schema
g. Role
h. Password

**Expected behavior**
The actions & sources should work

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
