### ISSUE TITLE
[BUG] Snowflake - The schema box shows empty result when Use Shared Static IP = FALSE

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12534]
**Describe the bug**
The schema box shows empty result.
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/c355dcc8-98a3-4c1b-9472-3ac5bcbe3f21)

**To Reproduce**
The setup as below:
a. Account
b. Username
c. Use Shared Static IP: FALSE
d. Warehouse
e. Database
f. Schema
g. Role
h. Password

**Expected behavior**
The schema box should show my database tables and their schema

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
