### ISSUE TITLE
[Components] dropboard

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12560]
# dropboard
## URLs
- https://dropboard.readme.io/reference/getting-started-dropboard
#### Prompt
Emit new event when a candidate profile is created. Optional props: 'jobId', 'clientId' and 'hiringManagerEmail'.
#### URLs
- https://dropboard.readme.io/reference/webhooks-candidates
- https://dropboard.readme.io/reference/webhooks-candidates-delete
#### Prompt
Emit new event when a member is added to a recruiting client (Recruiter plan only). Optional props: 'clientId'.
#### URLs
- https://dropboard.readme.io/reference/webhooks-client-members
- https://dropboard.readme.io/reference/webhooks-client-members-delete
#### Prompt
Emit new event when a new job is created. Required props: job details, recruiting client ID. Optional props: job ID.
#### URLs
- https://dropboard.readme.io/reference/webhooks-jobs
- https://dropboard.readme.io/reference/webhooks-jobs-delete
#### Prompt
Creates a new job within Dropboard. Required props include 'title', 'description', and 'hiringManagerEmails'. Optional props could be 'clientId', 'status', 'location', 'qualifications', 'responsibilities', 'compensation', 'openDateStart', 'openDateEnd' and 'jobCode'.
#### URLs
- https://dropboard.readme.io/reference/jobs-post
#### Prompt
Creates a new client within Dropboard. Note this is available only for Recruiter plan users and may incur additional charges based on your organization's plan. Required props: Client's name. Optional props: 'clientPlanId'.
#### URLs
- https://dropboard.readme.io/reference/clients-post
#### Prompt
Looks for a client within Dropboard. If not found, it will create a new one. Required props: Client's name. Optional props: 'clientPlanId'.
#### URLs
- https://dropboard.readme.io/reference/clients
- https://dropboard.readme.io/reference/clients-post

**Comment by malexanderlim** [comment]
@vunguyenhung , can you confirm if you're still observing this behavior? I connected an account 10 days ago, with no account disconnection issues.
