### ISSUE TITLE
[Components] noor

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12612]
# noor
## URLs
- https://usenoor.notion.site/API-434b3162d0194b19b0f211bd20377723
#### Prompt
This feature sends a text message in a specified thread. Key prop to be configured is the 'thread_id' to determine where the message is to be sent. Other optional props include 'message_content' and 'user_id' for defining the message content and the sender, respectively.

**Comment by lcaresia** [comment]
![image](https://github.com/user-attachments/assets/df20d32a-a565-4090-a1f0-e25e17480df9)
