### ISSUE TITLE
[APP] Control D

### ISSUE THREAD

**Issue by yegors** [PipedreamHQ/pipedream#12634]
**Name of app / service**
Control D

**Link to developer documentation**
https://docs.controld.com/reference/get-started

**Is lack of support preventing you from building workflows, or do you have a workaround?**
N/A - I'm the developer 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Similar to https://pipedream.com/apps/nextdns

**Comment by sergio-eliot-rodriguez** [comment]
Hi @yegors 

Thanks for the request,

here is a base integration feel free to test it out and let us know any feedback.

https://pipedream.com/apps/control-d

I-ll update you when a new issue for components is auto generated by the system so you can complement with components needed.

Cheers,
Sergio

**Comment by yegors** [comment]
Thanks, will check this out. If you could update the logo to: https://drive.google.com/drive/folders/1uMQq-pBrHOig5CUli5CJZqBOsqAv-GVf?usp=drive_link

That would be awesome.

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim can you pls update [Control-D](https://pipedream.com/apps/control-d)'s logo to ones in the Google Drive shared by Yegors. Apparently the ones named app_icon_1 and glyph_color are squared logos and will PD's UI.

**Comment by malexanderlim** [comment]
All set!
