### ISSUE TITLE
[ACTION] support getSchema and executeQueryAdapter in additional apps

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#12647]
We recently released support for a [first-class SQL editor and schema explorer](https://pipedream.com/docs/databases/working-with-sql) for certain database apps.

To extend these features to additional database types, we need to add support for the `getSchema` and `executeQueryAdapter` methods in app file for any new apps we want to support. See here for more info:
https://pipedream.com/docs/components/guidelines#database-components

We should add support for these methods in these apps:
[] supabase
[] microsoft_sql_server
[] azure_sql

Then create a generic "Execute SQL Query" action for each of those apps, similar to https://github.com/PipedreamHQ/pipedream/blob/master/components/postgresql/actions/execute-custom-query/execute-custom-query.mjs

**Comment by Garvitpant777** [comment]
can i work on this?

**Comment by malexanderlim** [comment]
@Garvitpant777 , this issue is already assigned to one of our component developers. You are welcome to work on a different PR as you see fit though!
