### ISSUE TITLE
[APP] CapsuleCRM

### ISSUE THREAD

**Issue by martinsotirov** [PipedreamHQ/pipedream#1265]
https://capsulecrm.com

**Comment by todsac** [comment]
@martinsotirov - I have built the base integration with CapsuleCRM.  You can test it here - https://pipedream.com/apps/capsule

Would you be interested in developing the triggers or actions for this app?  Here are the component docs - https://pipedream.com/docs/components/

**Comment by martinsotirov** [comment]
Thanks @todsac. I'm gonna give it a try. I'm still trialing CapsuleCRM so I might not stay with it but it would be a good exercise in working with pipedream.

**Comment by todsac** [comment]
Sounds great.  Please let us know how we can help and feel free to join us on Slack. https://pipedream.com/community
