### ISSUE TITLE
Multiple file upload support for Dropbox

### ISSUE THREAD

**Issue by denisbetsi** [PipedreamHQ/pipedream#12666]
**Is there a specific app this action is for?**
Dropbox App

**Please provide a link to the relevant API docs for the specific service / operation.**
Same API, allow for ran array of files, each item in array should allow for { source, destination }

**Comment by Garvitpant777** [comment]
can i work on this?

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
