### ISSUE TITLE
[BUG] Brevo - Add or Updated Contact failed to update contact

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12687]
**Describe the bug**
Selecting the existing contact for updating throw error
```json
{"code":"duplicate_parameter","message":"Contact already exist"}
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/dfcc3517-6555-4818-9b23-65ad87425f92)

**Expected behavior**
The action should update the contact instead. Maybe we can set updateEnabled parameter to true, as [per the documentation](https://developers.brevo.com/reference/createcontact).

**Comment by alexreg** [comment]
@vunguyenhung Thanks for continuing to look into this.
