### ISSUE TITLE
[BUG] Dropboard - Access Token expired after few minutes

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12695]
**Describe the bug**
Authenticate to Dropboard, after a few minutes, I faced an error
```
Invalid token: access token has expired
```

![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/f81b685d-f64b-41b2-8fba-ab62b15c9f4e)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/c0dfa873-ae43-4633-abe6-cddbc2fd5b3a)

**Comment by malexanderlim** [comment]
I've reached out to the Dropboard team to troubleshoot further here. Looking at the logs, it appears that this is breaking at the refresh token process, as a new refresh token is not returned, therefore, the token is only valid for a single session.

**Comment by malexanderlim** [comment]
Hi @vunguyenhung , Dropboard has updated their refresh token cadence so this should no longer be an issue. Can you let me know if you're still able to reproduce this error?
