### ISSUE TITLE
[Components] KrispCall

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12729]
# krispcall
## URLs
https://documenter.getpostman.com/view/32476792/2sA3dxFCaL
#### Prompt
Emit new event when a new contact is created. No prop required. The action must be 'new_contact'
#### URLs
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#9ec5e79e-3daa-4c5d-96ef-e4e0308354e1
#### Prompt
Emit new event when a new SMS or MMS is sent. No prop required. The action must be 'new_sms_or_mms'
#### URLs
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#9ec5e79e-3daa-4c5d-96ef-e4e0308354e1
#### Prompt
Emit new event when a new Voicemail is sent. No prop required. The action must be 'new_voicemail'
#### URLs
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#9ec5e79e-3daa-4c5d-96ef-e4e0308354e1
#### Prompt
Creates a new contact. Required props: 'number'. Optional props: 'name', 'email', 'company' and 'address'.
#### URLs
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#b32a8885-8067-4c61-ba81-0620eeac3d35
#### Prompt
Send a new SMS to a number. Required props: 'from_number', 'to_number' and 'content'. from_number has async opts.
 comments.
#### URLs
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#54023dea-6d85-4ff4-af89-36810de36c3f
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#7c4688ab-280d-4ad9-80f6-ee932c2be4fd
#### Prompt
Send a new MMS to a contact. Required props: 'from_number', 'to_number', 'content' and 'medias'. from_number has async opts.
 comments.
#### URLs
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#54023dea-6d85-4ff4-af89-36810de36c3f
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#7c4688ab-280d-4ad9-80f6-ee932c2be4fd
#### Prompt
Deletes a list of contacts. Required props: 'contactIds'. contactIds has async opts.
#### URLs
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#ce622362-e390-41cc-9c9e-3e84671ccc27
- https://documenter.getpostman.com/view/32476792/2sA3dxFCaL#6ab169f5-7858-4af5-b73d-62c2ac9d8397

**Comment by sergio-eliot-rodriguez** [comment]
Base integration live: https://pipedream.com/apps/krispcall
