### ISSUE TITLE
[APP] LambdaTest

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#12745]
**Name of app / service**
LambdaTest

**Link to developer documentation**
https://www.lambdatest.com/support/api-doc/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes i need it.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
As much of the full API as possible.

**Comment by sergio-eliot-rodriguez** [comment]
LambdaTest has been integrated https://pipedream.com/apps/lambdatest
