### ISSUE TITLE
[BUG] Microsoft SQL Server - Connection popup test connection failed when setting trustServerCertificate = FALSE

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12760]
**Describe the bug**
I use with ngrok to expose my MSSQL instance to the internet. Then on Microsoft SQL Server Connection Popup, I set the trustServerCertificate = FALSE and click `Test Connection`.

The `Test Connection` failed with error
```
Failed to connect - self-siged certificate
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/a7487722-8222-45ad-9f89-29a24611a55d)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/1f86c711-c431-476e-a688-b99cd89fcf6d)

**Comment by malexanderlim** [comment]
@vunguyenhung , I think this is expected as you need to set trustServerCertificate = true for self-signed certs.
