### ISSUE TITLE
[BUG] Azure SQL - Connection Popup Test Connection button always throw error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12761]
**Describe the bug**
On Azure SQL connection popup, the Test Connection button always throw error
```
The "encrypt" property must be set to "strict", or of type boolean.
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/2eabbea3-1368-45e3-b685-c2cca2c52167)

This error happens for both case when `Encrypt` is TRUE or FALSE

**Comment by malexanderlim** [comment]
This has been fixed. Thanks for flagging, @vunguyenhung !
