### ISSUE TITLE
Agenty

### ISSUE THREAD

**Issue by nelsoncfox** [PipedreamHQ/pipedream#1286]
Agenty

https://www.agenty.com/docs/

No, just using webhooks.

Triggers when a Agent job is finished.

**Comment by todsac** [comment]
The Agenty.com app has been integrated into Pipedream.  https://pipedream.com/apps/agenty

Are you interested in developing the event source to trigger on "Agent job is finished"?

**Comment by dylburger** [comment]
Closing this since the app is integrated, but let us know if you have any issues / questions about the integration
