### ISSUE TITLE
[APP] Airfocus

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#12865]
**Name of app / service**
Airfocus

**Link to developer documentation**
https://developer.airfocus.com/endpoints.html

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Full functionality.

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pd, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Airfocus is now integrated https://pipedream.com/apps/airfocus
