### ISSUE TITLE
[APP] Itemize.com

### ISSUE THREAD

**Issue by sjn001tvh** [PipedreamHQ/pipedream#1287]
I would like to request that the App Itemize.com be included with the Pipedream workflow apps.  This app allows you to take a picture of a receipt, and it automatically gathers and organizes the information from the receipt, such as Vendor, sub total, tax, and total.  The Itemize app does have api calls.

**Comment by todsac** [comment]
@sjn001tvh - We do not have an Itemize.com account so can't test the integration end to end.  Can you help us test? Here is a first version of the integration - https://pipedream.com/apps/itemize.

**Comment by sjn001tvh** [comment]
Yes. I would be happy to help test.  
Thanks,
Scott.
    On Tuesday, June 1, 2021, 03:38:15 PM PDT, Tod Sacerdoti ***@***.***> wrote:  
 
 


@sjn001tvh - We do not have an Itemize.com account so can't test the integration end to end. Can you help us test? Here is a first version of the integration - https://pipedream.com/apps/itemize.

**Comment by todsac** [comment]
Great.  Please visit https://pipedream.com/apps/itemize and test it out.
