### ISSUE TITLE
cloudmersive app[APP]

### ISSUE THREAD

**Issue by sjn001tvh** [PipedreamHQ/pipedream#1290]
Cloudmersive has api calls that convert xlsx to csv files without having to install excel.  I can't seem to find any other apps on the list that will do that type of conversion.

**Comment by todsac** [comment]
@sjn001tvh - I have completed the base integration of Cloudmersive and used the Validate Email action as the example test request.  Here is a demo - https://pipedream.com/apps/cloudmersive

Are you comfortable building out the necessary actions to solve your xlsx to csv?

**Comment by sjn001tvh** [comment]
Wow!  That was a quick response.  I try it out shortly.
Thanks,
Scott.
Note:  I was doing some api calls with dropbox, and within the dropbox api documentation there a long list of calls that don't seem to be available directly from the connections within the api using Pipedream.  One of these is the list_folders.  When I tried their calls from their utilities, it works, but I can't seem to get the right connections to get it to work with Pipedream.  There's a find folder in the dropbox api calls linked from Pipedream, but I need to get a list of folders from my dropbox directories.  Am I missing something, or is that call not yet connected with Pipedream?  If so, then I'll have to learn how to create their calls using the HTTP/webhook.  I just haven't got it mastered yet.
    On Tuesday, June 1, 2021, 04:14:30 PM PDT, Tod Sacerdoti ***@***.***> wrote:  
 
 


@sjn001tvh - I have completed the base integration of Cloudmersive and used the Validate Email action as the example test request. Here is a demo - https://pipedream.com/apps/cloudmersive

Are you comfortable building out the necessary actions to solve your xlsx to csv?

**Comment by todsac** [comment]
Great.  Please let me know when you have a chance to test.

On Dropbox, are you aware that you can add any actions (ie, API calls in your note above) to the Pipedream app?  Here is the quickstart - https://pipedream.com/docs/components/quickstart/nodejs/actions/

**Comment by sjn001tvh** [comment]
It may take me a few more days to devote time to the project.
Scott.
    On Wednesday, June 2, 2021, 10:50:26 AM PDT, Tod Sacerdoti ***@***.***> wrote:  
 
 


Great. Please let me know when you have a chance to test.

On Dropbox, are you aware that you can add any actions (ie, API calls in your note above) to the Pipedream app? Here is the quickstart - https://pipedream.com/docs/components/quickstart/nodejs/actions/

**Comment by dylburger** [comment]
Closing this since the app is integrated, but let us know if you have any issues / questions about the integration
