### ISSUE TITLE
[APP] databricks

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#12914]
**Name of app / service**
databricks
**Link to developer documentation**
https://docs.databricks.com/en/machine-learning/feature-store/python-api.html
https://docs.databricks.com/en/reference/mlflow-api.html
https://docs.databricks.com/en/machine-learning/foundation-models/index.html
https://docs.databricks.com/en/dashboards/tutorials/workspace-lakeview-api.html
https://docs.databricks.com/en/reference/spark.html

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes. I need it.
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Full functionality.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @MichaelHinrichs 

Thanks for the request.

databricks is integrated: https://pipedream.com/apps/databricks

can you let us know any specific actions/trigger you need?

**Comment by MichaelHinrichs** [comment]
I need to start remembering to check.
