### ISSUE TITLE
[APP] Cliniko

### ISSUE THREAD

**Issue by ajedwards** [PipedreamHQ/pipedream#1292]
Cliniko

https://github.com/redguava/cliniko-api 

Workaround: Vanilla HTTP calls with axios.

The Cliniko API uses HTTP Basic authentication, with an API Key as the username, and no password. 😰
No OAuth.

I would like to try my hand at submitting a PR for a few actions we need (get Contact, Patient and Practitioner by ID), but I understand that you have to set up the managed auth on your end first?

**Comment by todsac** [comment]
@ajedwards - I have set up the app for managed auth.  I am not familiar with Cliniko and don't have an account so it is possible there may be an error in the setup.  Can you please test the basic test request and make sure it works for you? 

https://pipedream.com/apps/cliniko

**Comment by ajedwards** [comment]
Works great. Thanks @todsac 😃
