### ISSUE TITLE
[APP] Remote Retrieval

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12924]
### App
Remote Retrieval
https://www.remoteretrieval.com/api-documentation/

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pd, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Integrated https://pipedream.com/apps/remote-retrieval
