### ISSUE TITLE
Zoho Cliq App Connection [APP]

### ISSUE THREAD

**Issue by celestebancos** [PipedreamHQ/pipedream#1293]
I'd love an easy way to connect with my Zoho Cliq account:

https://www.zoho.com/cliq/help/restapi/v2/#cliq_rest_api

**Comment by dylburger** [comment]
Thank you for the request @celestebancos . We'll take a look ASAP!

**Comment by malexanderlim** [comment]
Hi @celestebancos , this integration is complete! https://pipedream.com/apps/zoho-cliq
