### ISSUE TITLE
[BUG] OpenAI - Dall-E action exports image as base64 causing error workflow payload exceeded

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12943]
**Describe the bug**
Currently, when setting the Response Format is Base64 JSON, if the image is too large, the user will likely to hit Pipedream error: payload limit exceeded

**Expected behavior**
- In the Response Format prop, replace `Base64 JSON` to `Image in tmp dir` which write image to tmp directly. Returns the file path only. Do NOT export the base64 data.

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1721479010442189?thread_ts=1721435661.306959&channel=CPTJYRY5A&message_ts=1721479010.442189

**Comment by malexanderlim** [comment]
@vunguyenhung , would it be better to let the user decide whether to return the image as `Base64 JSON` or `Image in tmp directory` (recommended for large images)? I'm not as clear on how often this fails.
