### ISSUE TITLE
Obsidian

### ISSUE THREAD

**Issue by tymdc** [PipedreamHQ/pipedream#12951]
**Name of app / service**
Obsidian 

**Link to developer documentation**
https://docs.obsidian.md/Home

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have a workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
goal: make it so that a tasks in todoist automatically create pages in obsidian, where the section in todoist corresponds to the folder in obsidian. Also, triggering the completion of the task in todoist to triggers the corresponding obsidian page to move to the 'completed' folder

**Comment by sergio-eliot-rodriguez** [comment]
We are tracking Obsidian at: https://github.com/PipedreamHQ/pipedream/issues/6144

There is no API, I reached out again after a while but they told me

> 
Obsidian is all local files on a device, there is no API. You just create files on the device and Obsidian will pick them up.

**Comment by sergio-eliot-rodriguez** [comment]
Feel free to follow #6144
