### ISSUE TITLE
[APP] LLMWhisperer

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#12966]
**Name of app / service**
LLMWhisperer

**Link to developer documentation**
https://docs.unstract.com/llm_whisperer/apis/llm_whisperer_apis_intro
https://docs.unstract.com/llm_whisperer/javascript_client/llm_whisperer_javascript_client_documentation

**Comment by sergio-eliot-rodriguez** [comment]
@marcelocecin thanks for the request

LLMWhisperer has been integrated https://pipedream.com/apps/llmwhisperer

**Comment by marcelocecin** [comment]
hello, please update to v2
https://docs.unstract.com/llmwhisperer/llm_whisperer/apis/llm_whisperer_apis_intro/

**Comment by sergio-eliot-rodriguez** [comment]
Tracking at #15340
