### ISSUE TITLE
[BUG] Python code action throws `Mysql2::Error: Data too long for column 'code' at row 1` error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12964]
**Describe the bug**
This is an edge case, a user reported that their Python action always throw the error `Mysql2::Error: Data too long for column 'code' at row 1`. 

I can reproduce this issue by creating a Python code with 7000 lines
![image](https://github.com/user-attachments/assets/d1ba84ea-e24f-4ef0-8bbc-b2710a1ec1e4)
![image](https://github.com/user-attachments/assets/c5158ccc-66df-40bb-ae7d-164dd6d92f7c)

**Additional context**
Reported by a user here: https://app.frontapp.com/open/cnv_noprsnb?key=9z8pGUkYEN3qXHTmdqkDydLTxa-1nB-w

**Comment by parisetflorian** [comment]
@dylburger Hey Dylan, this issue has one of our project stuck. Would be great if it could be addressed quickly. Thanks!

**Comment by andrewjschuang** [comment]
Hey @parisetflorian, we don't plan to increase the size limit of code steps as doing this will bring consequences into the platform for such specific use case.
We do plan on [supporting custom actions in Python](https://github.com/PipedreamHQ/pipedream/issues/6759) like in Node.js though so we'll offer a better way of reusing shared code and unlock more use cases than we currently do.

**Comment by PlatFlat** [comment]
Hi @andrewjschuang / @PipedreamHQ Team.

We hope you could revisit this issue allow us to run our codes in one single action steps. 

We tried optimizing & shortening our codes lines but our methods are tightly coupled, the class methods depend on each other. 

Therefore I believe we can't split the method into different actions as each action run in isolation.
