### ISSUE TITLE
Capsule CRM API Adaptor? [APP]

### ISSUE THREAD

**Issue by sparkybrit** [PipedreamHQ/pipedream#12960]
**Name of app / service**

Capsule CRM

**Link to developer documentation**

https://developer.capsulecrm.com/?utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&mp_acc=30494&mp_cam=21456343908&mp_grp=&mp_ad=&mp_src=x&mp_tgt=&mp_kw=&mp_mt=&mp_net=adwords&gad_source=1&gclid=CjwKCAjwqf20BhBwEiwAt7dtdXc28YLPowYjOAhM-WJwLMqiaotDZl8Q70FcS39BBfu_R5Xla9uCwBoC2zUQAvD_BwE

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

one-off export is sufficient for now

**Comment by sergio-eliot-rodriguez** [comment]
Hi @sparkybrit 

Thanks for the request.

Capsule CRM is integrated at: https://pipedream.com/apps/capsule

However I see that doesn't have much components develop. Can you elaborate on what you are trying to do?
E.g. What do you mean for "one-off export"? 

With this information I am able to triage properly for components development addressing your use case.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
