### ISSUE TITLE
[Components] launchnotes

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13017]
# launchnotes
## URLs
- https://help.launchnotes.com/en/articles/5129003-getting-started-with-the-api   https://developer.launchnotes.com/index.html
#### Prompt
Emit new event when an announcement is published. The required prop for this trigger is the 'announcement ID'. Optional props can include the 'announcement type' or 'category'.
#### URLs
- https://help.launchnotes.com/en/collections/3463062-getting-started-with-launchnotes
- https://help.launchnotes.com/en/collections/3463082-integrations
#### Prompt
Emit new event when a new project subscription is created. The required props for this trigger are the 'project ID' and 'subscriber ID'. An optional prop could be the 'subscription type'.
#### Prompt
Emit new event when an announcement is scheduled. The required prop for this trigger is the 'announcement ID'. Optional props can include the 'schedule time' or 'announcement category'.
#### URLs
- https://help.launchnotes.com/en/collections/3463082-integrations
#### Prompt
Adds a new subscriber to the current LaunchNotes project. Requires the 'email' prop for the subscriber's email address. [Optional props] Consider 'username' for identifying the user.
#### URLs
- https://help.launchnotes.com/en/collections/3463062-getting-started-with-launchnotes
- https://help.launchnotes.com/en/collections/3957277-activating-your-account-and-getting-help
- https://help.launchnotes.com/en/collections/3463082-integrations
#### Prompt
Generates a draft announcement for the LaunchNotes project. The 'title' prop is mandatory to define the announcement title. You might consider optional props such as 'text' to include announcement body.
#### URLs
- https://help.launchnotes.com/en/collections/3463062-getting-started-with-launchnotes
- https://help.launchnotes.com/en/collections/3463082-integrations

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-launchnotes-e09f946510e1457384704d1ee0e96b99

Hi @vunguyenhung, I couldn't reproduce the source error.

The inicial events with 3 tests
![image](https://github.com/user-attachments/assets/d4b612d1-146a-43ea-8433-9f1e3a9387e1)
![image](https://github.com/user-attachments/assets/07cb3f69-288b-4a6e-a150-6e385c7ddcaf)

The I scheduled 2 more
![image](https://github.com/user-attachments/assets/fd19f2cb-4cbb-43ab-a473-d61b6eda3704)

and it worked
![image](https://github.com/user-attachments/assets/408b1e97-cd4d-4e9e-a76b-a3580d66f07e)
