### ISSUE TITLE
[APP] Are.na

### ISSUE THREAD

**Issue by tkalejaiye** [PipedreamHQ/pipedream#13028]
**Name of app / service**
Are.na

**Link to developer documentation**
https://dev.are.na/documentation

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have a workaround, but this would make life easier

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

I'd like to contribute the actions and triggers for this app myself 😊

**Comment by malexanderlim** [comment]
@tkalejaiye , the app is now live - feel free to contribute components when you are ready!

**Comment by tkalejaiye** [comment]
Awesome! Thanks @malexanderlim
