### ISSUE TITLE
[OAUTH SCOPE] New scope for Fitbit

### ISSUE THREAD

**Issue by edreyyo** [PipedreamHQ/pipedream#13024]
**Which application needs a scope added?**
Fitbit

**What scope(s) need to be added?**
`irn`

**Please provide a link to the relevant API docs for scopes.**
Fitbit recently added endpoints for getting irregular rhythm notification alerts. These require the new scope `irn`: https://dev.fitbit.com/build/reference/web-api/developer-guide/application-design/#Scopes

**Comment by malexanderlim** [comment]
I've opened up a thread with the Fitbit team here, as I tried to add the scope but it was returning an invalid scope error during the OAuth flow.

Feel free to follow along below, or I'll update this thread once I hear back.
https://community.fitbit.com/t5/Web-API-Development/Invalid-scope-error-when-adding-irn-scope/m-p/5639108#M16462

**Comment by edreyyo** [comment]
Thanks for the update, as well as following-up with the Fitbit team. I'll keep an eye on the linked thread. Much appreciated.

**Comment by edreyyo** [comment]
Hi @malexanderlim The Fitbit team have replied. It seems the docs were incorrect. The correct scope name is `irregular_rhythm_notifications` _not_ `irn` 😅

**Comment by malexanderlim** [comment]
Thanks @edreyyo - I've added the scope and tested the flow, and can confirm that the irregular rhythm notifications is a selectable scope.

**Comment by edreyyo** [comment]
@malexanderlim I can confirm it's working. Thanks for adding the scope so quickly.
