### ISSUE TITLE
RingCentral integration

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13037]
### App
RingCentral integration

### Summary:
Call action not returning agent info

### Details:
When we are calling a ring central trigger to trace activities being done by an agent, the returning information does not provide the name or phone number of the agents when the agent picks up the phone that triggers in action. This is causing our code not to be able to update tickets in our system, which is gorgias, with the agent's information after they pick up a call

### Screenshots:
No screenshots included

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
