### ISSUE TITLE
Quickbooks Online 

### ISSUE THREAD

**Issue by ital0000** [PipedreamHQ/pipedream#13046]
**Name of app / service**
Qiuckbooks online

**Link to developer documentation**
https://developer.intuit.com/app/developer/qbo/docs/develop

**Is lack of support preventing you from building workflows, or do you have a workaround?**
preventing us from building workflow

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
We would like to sync any custom contact (customer) proprety, invoice property, and/or product property to HubSpot

**Comment by sergio-eliot-rodriguez** [comment]
Hi @ital0000 

Thanks for the request . Quickbooks Online is integrated simply as "Quickbooks" https://pipedream.com/apps/quickbooks

Note that this is labeled as Premium app>
![image](https://github.com/user-attachments/assets/aedcd97d-c61f-40f4-87a4-42c82b0dc44e)


meaning you need to on the Advanced plan at current pricing, https://pipedream.com/pricing

![image](https://github.com/user-attachments/assets/e1477315-ac32-45e8-9f5b-ec1d17358947)

**Comment by sergio-eliot-rodriguez** [comment]
I'm triaging your request for trigger/source development

**Comment by malexanderlim** [comment]
Tracking in https://github.com/PipedreamHQ/pipedream/issues/13582
