### ISSUE TITLE
[APP] Short.io

### ISSUE THREAD

**Issue by rawkode** [PipedreamHQ/pipedream#1305]
**Name of app / service**
Short.io

**Link to developer documentation**

https://developers.short.io/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Can use ENV, as integration is only a standard API token

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

No

**Comment by todsac** [comment]
David (@rawkode) - I have added Short.io.  Please let me know if you have any issues with the integration. 

Marketplace - https://pipedream.com/apps/short
Workflow Example - https://pipedream.com/@tod/p_A2CMbVy/

**Comment by rawkode** [comment]
Thanks!
