### ISSUE TITLE
[APP] CommerceTools

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#1306]
**Name of app / service**
CommerceTools

**Link to developer documentation**
https://docs.commercetools.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No workarounds

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Sources:
- [API extensions](https://docs.commercetools.com/api/projects/api-extensions) (synchronous extensions to the existing API's)
- [Subscriptions](https://docs.commercetools.com/api/projects/subscriptions) (similar to webhooks)
- [Messages](https://docs.commercetools.com/api/projects/messages) (pull-based event source)

Actions:
- (All the CRUD actions available for all the entities available in [the docs](https://docs.commercetools.com/api/)

**Comment by todsac** [comment]
Jay - This API requires a dynamic scope such as manage_project:{projectKey} which we currently don't support.  We are looking into it.  Let me know if there is any urgency behind this integration.

**Comment by todsac** [comment]
https://pipedream.com/apps/commercetools
