### ISSUE TITLE
Thinkific - New Event (Instant)

### ISSUE THREAD

**Issue by lsatmadesimple** [PipedreamHQ/pipedream#13086]
Coming from the Thinkific app integration into Pipedream, I need a new event source triggered when an enrolled student logs into my Thinkific course. (I would need the trigger to be log-ins just from student/users enrolled in specific courses, or alternatively, log-ins from students that are part of a specific "group" on my Thinkific course. 

https://developers.thinkific.com/api/api-documentation/

**Comment by malexanderlim** [comment]
Component Devs, can we have a generic webhook trigger New Event that users can subscribe to any of the available [topics](https://support.thinkific.dev/hc/en-us/articles/4422658311703-Webhooks-Documentation)? This should solve for this use case, and is much more flexible.
