### ISSUE TITLE
[ACTION] Twilio - Detect Landline Phone Number

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13084]
**Is there a specific app this action is for?**
Twilio

**Please provide a link to the relevant API docs for the specific service / operation.**
https://www.twilio.com/en-us/blog/filter-landlines-lookup-sms

**Comment by jakers1776** [comment]
https://www.twilio.com/en-us/blog/filter-landlines-lookup-sms

**Comment by jakers1776** [comment]
ok can we get the part of that output that signifies whether or not the phone number is a landline
