### ISSUE TITLE
[TRIGGER] New Refund Created (Instant) from Shopify Developer App

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#13085]
The event is a refund issued on shopify.

(https://shopify.dev/docs/api/admin-rest/2024-07/resources/event)
refund_success

Refund is currently one of the events that will trigger Order Updated trigger, but so many other events trigger it thats its expensive to only monitor it for refunds. 

New Event Emitted (Instant) from Shopify Developer App can also be filtered for refunds/create but it doesn't pull in nearly as much info as the corresponding New Order Created (Instant) from Shopify Developer App trigger.

It should hopefully be very similar to https://github.com/PipedreamHQ/pipedream/blob/master/components/shopify_developer_app/sources/new-paid-order/new-paid-order.mjs I'd like to be able to issue store credit/debit based on orders/refunds and right now I can only get new orders efficicently. Hopefully others could find many other uses for Refund sent (inventory/shipping etc etc)

**Comment by zecul** [comment]
I have this working by adding a "get order" step to the New Event Emitted (Instant) from Shopify Developer App (refund) step

so no major rush if you dont think many others would use it

**Comment by malexanderlim** [comment]
Component Devs, can we add a new prop for Order Event [Type](https://shopify.dev/docs/api/admin-rest/2024-07/resources/event#:~:text=comment%20was%20created.-,Order%20events,-Order%20events%20can) for filtering on the New Updated Order trigger?

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/TRIGGER-New-Refund-Created-Instant-from-Shopify-Developer-App-afb1fadafaf14b64b5cb4b50bdd2d8a6

Hi @vunguyenhung, Do your objects have metafield and private Metafield defined? This source filters all objects that match these settings. Otherwise it is ignored.
