### ISSUE TITLE
Deputy app uses old logo - please update

### ISSUE THREAD

**Issue by ajedwards** [PipedreamHQ/pipedream#1309]
The [Deputy app](https://pipedream.com/apps/deputy) still uses the **old ('inverted badge') Deputy logo**. Deputy [refreshed their brand](https://www.deputy.com/au/blog/deputy-new-look-shifting-our-brand-forward), including a [new ('spark') logo](https://www.deputy.com/g-assets/deputy-logo.png) (below), earlier this year.

![new logo](https://www.deputy.com/g-assets/deputy-logo.png)
**New 'spark' logo**: https://www.deputy.com/g-assets/deputy-logo.png

Any chance we could get the logo updated please? Low priority, but hopefully a quick fix :)

**Comment by todsac** [comment]
This has been updated.  It may take a few hours to propagate through all our systems.
https://pipedream.com/apps/deputy
