### ISSUE TITLE
[BUG] Broken link to Travis API

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#13104]
**Describe the bug**
Error 503, Service Temporarily (perminantly) Unavailable.

**To Reproduce**
1. Create a new connection to Travis CI
2. Click on "Travis CI API docs"
3. See error

**Additional context**
Change ".org" to ".com".

**Comment by malexanderlim** [comment]
Thanks for flagging - I've updated the docs link!
