### ISSUE TITLE
[APP] Google Fit

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#1310]
**Name of app / service**: Google Fit

**Link to developer documentation**: https://developers.google.com/fit/rest/v1/get-started

**Comment by miguelrochefort** [comment]
This would also enable partial Apple Health support since Google Fit can sync with it.

**Comment by nachocab** [comment]
Any updates on this? 😅

**Comment by sergio-eliot-rodriguez** [comment]
Hi @nachocab 

Sorry for the terrible delay here. I have submitted this app for Pipedream approval. Likely we still need to get green light from Google.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @nachocab 

The Google Fit app was released as a Custom, Developer app -- https://pipedream.com/apps/google-fit-developer-app
