### ISSUE TITLE
[APP] - Dear

### ISSUE THREAD

**Issue by xbrandonx** [PipedreamHQ/pipedream#1311]
https://dearsystems.com/

https://dearinventory.docs.apiary.io/

**Comment by todsac** [comment]
Marketplace - https://pipedream.com/apps/dear
Workflow Example - https://pipedream.com/@tod/dear-api-integration-example-p_WxCq3YP

@xbrandonx - please let me know if you are interested in adding any actions or event sources, and if you need any help doing so. Docs -https://pipedream.com/docs/components/

**Comment by xbrandonx** [comment]
@todsac thank you for the incredibly quick turnaround I am going to take a look today.
The primary use case is for an Airtable New Record > Dear Advance Purchase Order 
Is this endpoint included ? 
https://dearinventory.docs.apiary.io/#reference/purchase/advanced-purchase

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
