### ISSUE TITLE
[Components] opsgenie

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13193]
# opsgenie
#### Prompt
Creates an alert within the OpsGenie platform. Required props: 'message' - the content of the alert. Optional props: 'alias' - a unique identifier for the alert, 'description' - detailed information about the alert, 'responders' - teams, users, escalations and schedules that the alert will be routed to.

**Comment by lcaresia** [comment]
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-opsgenie-d06560a2b8924d498dfbd3e241ed5496

@vunguyenhung I think is missing some information on Notion page, can you check?

**Comment by lcaresia** [comment]
Hey @vunguyenhung, can you test again?

![WhatsApp Image 2024-09-12 at 13 06 13](https://github.com/user-attachments/assets/1608fdd2-9af8-4dac-9e8b-58d325be0199)
![WhatsApp Image 2024-09-12 at 13 05 13](https://github.com/user-attachments/assets/77fa5c4f-f147-43cb-97e3-125128bc6fbd)
