### ISSUE TITLE
[Components] gocanvas

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13194]
# gocanvas
#### Prompt
Emit new event when a new submission is uploaded to the specified GoCanvas application. Required props: Application ID. Optional props: Submission ID for getting dynamic fields.
#### Prompt
Creates a dispatch item in GoCanvas. Required props include a dispatch enabled GoCanvas App.
#### Prompt
Removes a specific dispatch from GoCanvas. The 'Description' of the dispatch to be deleted is a required prop.
#### Prompt
Synchronizes GoCanvas reference data file with Google Sheets. You need to specify the Reference Data file to be synced as a prop.

**Comment by michelle0927** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-gocanvas-135bf548bb5e81738979c4ab0e6c04fa

Hi @vunguyenhung, I'm able to successfully list forms using the account in 1Pwd. Are you sure you have the correct username & API key entered? Does the test request work for you (does it return forms in XML)?
