### ISSUE TITLE
Teams / Organizations

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#132]
Orgs should have the following properties:

* I want workflows and other entities to be owned by an org, like they do on Github, for example.
* Users can be added to orgs with specific permissions to edit, view, etc.
* Environment variables, connected accounts, and other objects can be owned by orgs.

If you have another specific cases, please let us know in the comments below.

**Comment by davetapley** [comment]
Just to add on to list: Billing would be nice 👌🏻

**Comment by todsac** [comment]
Dave - The Teams plan is currently live in alpha and we are currently onboarding customers. Are you interested in joining the alpha? Also, can you clarify what you mean by Billing?  We support billing for teams as part of the new product but I am not sure that is what you mean.

**Comment by davetapley** [comment]
@todsac great! I'd definitely be interested in joining alpha 😁 

I'm sure your 'billing for teams' is what I was thinking, it just wasn't explicitly called out on this issue.

**Comment by dylburger** [comment]
@davetapley thank you for the feedback!

Would you mind finding [30 min of mutual time here](https://calendly.com/d/nj3s-twkf/pipedream-teams-discussion?month=2021-06) where Tod and I can chat with you about Teams? We're using these sessions as customer interviews (we'd love to hear what else you'd like to see) and to tell you more details about Teams / Orgs.

(anyone else who's interested in Teams and who wants to join the alpha can [sign up here](https://calendly.com/d/nj3s-twkf/pipedream-teams-discussion?month=2021-06), as well).

**Comment by dylburger** [comment]
Organizations are now live! You can [create an organization here](https://pipedream.com/organizations/new) and [read more in our docs](https://pipedream.com/docs/orgs/).
