### ISSUE TITLE
[Components] ortto

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13209]
# ortto
## URLs
- https://help.ortto.com/a-250-api-reference
#### Prompt
Emit new event when a contact is created in your Ortto account.
#### URLs
- https://help.ortto.com/a-258-retrieve-one-or-more-people-get
#### Prompt
Emit new event when a organization is created in your Ortto account.
#### URLs
- https://help.ortto.com/a-277-retrieve-one-or-more-organizations-get
#### Prompt
Emit new event when a contact is updated in your Ortto account.
#### URLs
- https://help.ortto.com/a-258-retrieve-one-or-more-people-get
#### Prompt
Emit new event when a organization is updated in your Ortto account.
#### URLs
- https://help.ortto.com/a-277-retrieve-one-or-more-organizations-get
#### Prompt
Creates a unique activity for a user. Can optionally initialize a new record beforehand. The 'activityName' prop is required to specify the activity to be created. The 'recordID' prop is optional and can be used to assign the activity to a preexisting record.
#### URLs
- https://help.ortto.com/a-273-create-a-custom-activity-definition-create#Request-body
#### Prompt
Allows a user to opt out from all SMS communications. The 'userID' prop is required to specify who to opt out. No optional props are suggested as Pipedream runs these actions.
#### URLs
- https://help.ortto.com/a-258-retrieve-one-or-more-people-get
- https://help.ortto.com/a-257-create-or-update-one-or-more-people-merge
#### Prompt
Initializes a new record(person, organization) or updates a preexisting record in the Ortto account. The 'recordType' prop is required to choose between 'person' and 'organization'. Plus, the 'data' prop is necessary, which includes details of the record. No optional props are suggested.
#### URLs
- https://help.ortto.com/a-257-create-or-update-one-or-more-people-merge
- https://help.ortto.com/a-278-create-or-update-one-or-more-organizations-merge

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-ortto-151bf548bb5e81a3aef3f5541d66088b

Hi @vunguyenhung,
The documentation you posted about the Create Custom Activity is actually the Create Custom Activity Definition. 
The right one is: https://help.ortto.com/a-271-create-a-custom-activity-event-create.

And the create person I couldn't reproduce the error, here is working well
![image](https://github.com/user-attachments/assets/8646f8d6-f189-4143-a411-47184e7903a2)
![image](https://github.com/user-attachments/assets/5d86c936-2de2-4d0b-aad8-a62a16585b1a)

**Comment by luancazarine** [comment]
> 2. The action props gave no clues for users on how to input the values. Please add the example to prop description

Hi @vunguyenhung, Each activity has its own json structure, so I think any example I add won't be good, that's why I added the message 'You can find the attributes by clicking on the activity definition and on the Developer button'. Doesn't it make sense?
