### ISSUE TITLE
google chat

### ISSUE THREAD

**Issue by kabalos09** [PipedreamHQ/pipedream#1322]
Do you have any integration as well to Google Chat App?

**Comment by kabalos09** [comment]
Hope you have an integration as well to Google Chat App

**Comment by dylburger** [comment]
https://developers.google.com/chat

**Comment by earthpyy** [comment]
+1 for this!

**Comment by malexanderlim** [comment]
@kabalos09 @earthpyy , tracking development of components here: https://github.com/PipedreamHQ/pipedream/issues/6807

If there are other triggers or actions you'd like to see, please comment in the ticket that I shared. Thanks!

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/google-chat
