### ISSUE TITLE
[Components] tremendous

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13235]
# tremendous
#### Prompt
Create a new order with a unique email reward. The props required are the order details like the user's name, email, and the reward details like reward type, value, etc. The optional props can be details like scheduled delivery time, custom message for the reward, etc.

**Comment by GTFalcao** [comment]
Thanks for providing the sandbox account Sergio - I was able to validate this now as well, which I could not before.

There were several props not documented as required, but that were so in practice - I've added them, and adjusted some of the existing ones, and was able to create a successful reward.
