### ISSUE TITLE
[APP] buffer

### ISSUE THREAD

**Issue by Abinashdehury** [PipedreamHQ/pipedream#13246]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Duplicated request, feel free to follow https://github.com/PipedreamHQ/pipedream/issues/6189

Can you ideally upvote Buffer API because for now it's close for new developers?

> As of October 14th, 2019, Buffer no longer supports the registration of new developer applications. Applications created prior to this date will retain access to the Buffer Publish API. Please visit our [Changelog page](https://buffer.com/developers/api/logs) for more details.

Please upvote the [API feature suggestion](https://suggestions.buffer.com/p/schedule-and-publish-via-api).

Thanks!
