### ISSUE TITLE
[APP] Nextcloud

### ISSUE THREAD

**Issue by mgrunwald74** [PipedreamHQ/pipedream#1327]
Please add nextcloud.
[Nextcloud File Sync](https://nextcloud.com/)

Developer Docs:
[Nextcloud WebDAV Basic API](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#webdav-basics)

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated now https://pipedream.com/apps/nextcloud?via=go
