### ISSUE TITLE
Samsung SmartThings integration [APP]

### ISSUE THREAD

**Issue by MBraedley** [PipedreamHQ/pipedream#1329]
I have made great use of Pipedream setting up a handful of automations, but one of the biggest things I'm missing is a SmartThings integration.  I have one automation right now through IFTTT, but I'd like to move it over to Pipedream so that everything is in one place, and also so that I can have a little more customizability.

**Comment by todsac** [comment]
@MBraedley - Can you test this integration and confirm that it solves your use case?

https://pipedream.com/apps/smartthings

If so, are you interest in contributing the triggers and/or actions for the app?

**Comment by MBraedley** [comment]
I actually want to use SmartThings as a trigger.  The IFTTT recipe is triggered by me turning on my TV (which, for all intents and purposes, acts the same as flipping a light switch) which then activates a webhook.  It does look like the API token was accepted, although I haven't fully tested that.

**Comment by dylburger** [comment]
@MBraedley are you relatively familiar with Node.js? Anyone can actually author a trigger on Pipedream. Check out the [development docs here](https://pipedream.com/docs/components/quickstart/nodejs/sources/). Would you be interested in helping to develop this trigger? We're happy to assist in any way and show some examples that will help.

**Comment by MBraedley** [comment]
I am not a web dev by any stretch of the imagination, but I'm generally capable of updating existing code when necessary.  I may look at this again this weekend (as well as the SmartThings API), but don't really have the time right now to dig into it.

**Comment by dylburger** [comment]
OK thanks. I'm closing this issue since it's related to the core app integration, and I opened [a separate issue](https://github.com/PipedreamHQ/pipedream/issues/1331) to track the development of triggers / sources for Samsung SmartThings.
