### ISSUE TITLE
I need to edit existing credentials for an app

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#133]
The primary use case is for key-based apps: I've linked a specific connected account in many workflows, then I rotate my API keys (best practice), and need to change the API key in Pipedream. Today, I have to:

* Add new credentials
* Unlink the old credentials in every step where I'm referencing them, linking the new credentials to the step.

Ideally, I'd just be able to edit the API key for the original linked credentials. This way, I only have to update the key in one place, instead of changing the credentials I reference in _multiple_ places.

**Comment by zeshhaan** [comment]
Interestingly, apps like Webflow shows the key only when it's generated for the first time. So if we don't remember the key thereafter, we will need to request a new one _invalidating the old one_. This breaks the workflows associated with the old key. Copying the key in the first instance when it's generated is what's intended. But wouldn't it be nice to have the key to show/hide on a toggle in Pipedream?

![image](https://user-images.githubusercontent.com/34814964/102607614-95b73b00-414e-11eb-8cd0-1eeff21f763b.png)

**Comment by dylburger** [comment]
This is now supported. You can click on the ellipsis to the right of any account in https://pipedream.com/accounts and you'll see the option to Reconnect:

<img width="255" alt="Screen Shot 2021-03-25 at 4 13 12 PM" src="https://user-images.githubusercontent.com/242668/112555272-1c4e6a80-8d85-11eb-9a09-bd8810ba84f1.png">

For any API-key apps, this opens up your existing account details, where you can modify them.

**Comment by zeshhaan** [comment]
Thank you!
