### ISSUE TITLE
Marketo Integration

### ISSUE THREAD

**Issue by jpcbr** [PipedreamHQ/pipedream#1330]
https://developers.marketo.com/rest-api/

**Comment by todsac** [comment]
We are looking into Marketo and have applied to the Adobe Exchange Program to get a Sandbox account.

**Comment by sergio-eliot-rodriguez** [comment]
@todsac  @malexanderlim 
any update with Marketo and the Adobe Exchange Program?
i looked into it and applying for a technology partnership with adobe could be good
https://partners.adobe.com/technologyprogram/experiencecloud/registration.html
i was deterred to apply with my at pipekit email as this looks very official, if you enter an at pipedream address the apply form will retrieve Pipedream physical address.

**Comment by malexanderlim** [comment]
@jpcbr , do you happen to have a Marketo account that you can provision us a sandbox for? We have not been able to get an account provisioned, and would like to move this forward if you can help us to test. Alternatively, we could set up the scaffolding if you are able to test it once it is set up. Let us know!

**Comment by sergio-eliot-rodriguez** [comment]
Marketo has been integrated https://pipedream.com/apps/marketo
