### ISSUE TITLE
get data from firebase database 

### ISSUE THREAD

**Issue by vishalocta** [PipedreamHQ/pipedream#1332]
please create a flow where we can fetch data from firebase database, mainly CRUD functions.  I have tried firebase authentication sdk but something feels empty unable to get data from firebase database even after configuring the database in sdk intilizations .

**Comment by dylburger** [comment]
@vishalocta did you know that anyone can create their own actions in Pipedream? [See our developer docs here](https://pipedream.com/docs/components/quickstart/nodejs/actions/). Would you be interested in contributing actions for Firebase?

**Comment by vishalocta** [comment]
I have no idea how I can contribute. I will look into actions.
