### ISSUE TITLE
[APP] Coinmarketcap

### ISSUE THREAD

**Issue by jackrabbithanna** [PipedreamHQ/pipedream#1339]
A recipe for being able to connect to coinmarketcap price feeds on a periodic basis, and then be able to discord server channel would be brilliant

Absolutely loving the service right now, using Twitter, Github, Youtube, Twitch feeds

**Comment by todsac** [comment]
Coinmarketcap is integrated - https://pipedream.com/apps/coinmarketcap. Are you interested in adding any actions or triggers for the app?

**Comment by jackrabbithanna** [comment]
I must have missed it .. I was able to just make a HTTP API call and parse the response and send to the discord channel... so managed it more "manually" .. 

Can close this issue.
