### ISSUE TITLE
[ACTION / SOURCES] Moneybird

### ISSUE THREAD

**Issue by zulfikarsorgucu** [PipedreamHQ/pipedream#1342]
I am searching for the Moneybird actions.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dannyroosevelt** [comment]
https://developer.moneybird.com/

### Triggers
- New Contact
- New Quote
- New Sales Invoice

### Actions
- Create Contact
- Create Sales Invoice
- Create Quote

**Comment by dannyroosevelt** [comment]
This is ready for release!
