### ISSUE TITLE
[BUG] Discord Webhook Error 400 when using embeds

### ISSUE THREAD

**Issue by Metalliguitare** [PipedreamHQ/pipedream#1344]
Hello,
While using the message field works, using embeds with the discord webhooks advanced action cause systematic Error 400

**To Reproduce**
1.Create a discord webhook advanced action
2.Copy paste the example embed array : `[{"description":"Use markdown including *Italic* **bold** __underline__ ~~strikeout~~ [hyperlink](https://google.com) code"}]`
3.Save&Deploy

**Comment by dylburger** [comment]
@Metalliguitare thanks for reporting. I updated the instructions to correctly reference the value you should use:

```javascript
{{ [{"description":"Use markdown including *Italic* **bold** __underline__ ~~strikeout~~ [hyperlink](https://google.com) code"}] }}
```

This wraps the embeds array using our [expression syntax](https://pipedream.com/docs/workflows/steps/params/#entering-expressions). Let me know if that helps.
