### ISSUE TITLE
Attio Integration

### ISSUE THREAD

**Issue by kesslerio** [PipedreamHQ/pipedream#13468]
**Name of app / service**
Attio

**Link to developer documentation**
https://developers.attio.com/reference/get_v2-objects

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No, workaround.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
see: https://zapier.com/apps/attio/integrations

**Comment by sergio-eliot-rodriguez** [comment]
HI @kesslerio 

Thanks for the request, we have rolled out a base integration for Attio as well as some nocode components too.

https://pipedream.com/apps/attio
