### ISSUE TITLE
[BUG] Airfocus connection popup - Test connection always failed

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13484]
**Describe the bug**
I put in valid API Key and click the Test Connection button, but it failed
![image](https://github.com/user-attachments/assets/4739417e-6066-4215-89ff-6ce2be431d69)

Error detail
![image](https://github.com/user-attachments/assets/edbfa63b-98a9-4a1f-8e33-c8bdf46d9016)

Additionally, the Workspace ID is optional
![image](https://github.com/user-attachments/assets/fbb097a1-fec2-4de0-84c3-bfee51ab55fe)

Though without it, the sources and actions would fail
![image](https://github.com/user-attachments/assets/cbbade60-e4d9-4523-a7e5-8c036201369b)
![image](https://github.com/user-attachments/assets/4b705a19-28e5-42aa-b15e-98f53f03ae82)

**Comment by malexanderlim** [comment]
@vunguyenhung can you let me know if this is still an issue? Should be fixed now.
