### ISSUE TITLE
[BUG] Paradym - Test Connection on the connection popup always failed

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13492]
**Describe the bug**
On Paradym connection popup - The Test Connection button always failed 
![image](https://github.com/user-attachments/assets/2c31a027-9d77-44bf-8cad-4f273c92e24c)

![image](https://github.com/user-attachments/assets/6555e5ea-ec93-4d60-a81a-fbbd71045ee1)

Even when the API Key I pass in is correct. I can execute the action with it
![image](https://github.com/user-attachments/assets/23f84cf1-9ccc-4a30-a35e-51c230140df3)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by malexanderlim** [comment]
Thanks for flagging @vunguyenhung - I've made a few tweaks and this should now be fixed.
