### ISSUE TITLE
[FEATURE] Airtable Sources - Add "Limit to View" props so that events only emitted for records in selected view

### ISSUE THREAD

**Issue by shennan-iterative** [PipedreamHQ/pipedream#13508]
**Is your feature request related to a problem? Please describe.**
Zapier supports a "Limit to View" option which reduces the amount of data retrieved via servers. This also allows us to streamline data extraction by scoping the search space.

**Describe the solution you'd like**
Build an option field that queries the table to select the view to use.

**Do you have a workaround?**
Only workaround is to code it manually, which is quite tedious.

**Comparable features in other tools?**
Is this feature or one like it available in another platform? If so, we'd love to hear what you like about that implementation.

**Additional context**
![CleanShot 2024-08-13 at 17 13 39](https://github.com/user-attachments/assets/e67b722e-047d-4d24-a5d4-09e54e7d6309)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
