### ISSUE TITLE
[BUG] DropInBlog - Connection popup improvement

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13521]
**Describe the bug**
The Connection popup - Test Connection button requires Public API Key
![image](https://github.com/user-attachments/assets/67b6a255-dd93-4e30-8609-9bbd967c6861)

While the action requires Private API Key
![image](https://github.com/user-attachments/assets/72f8e5cc-a10a-4153-8df7-4e3467280302)

But some props require Public API Key
![image](https://github.com/user-attachments/assets/11988397-901c-4570-8a58-f3ae68e515d9)

This causes confusion for users whether to use Private API Key or Public API Key. To have Pipedream actions and sources work correctly, it needs to have both Private Key and Public Key

**Expected behavior**
1. Add Private Key and Public Key props. Both of them should be required
2. Improve the Test Connection button to be executed successfully when both Private Key and Public Key are present

**Comment by malexanderlim** [comment]
Thanks for the testing here @vunguyenhung - I've added new props for both public and private api keys here.
