### ISSUE TITLE
[APP] Runware

### ISSUE THREAD

**Issue by dep** [PipedreamHQ/pipedream#13584]
**Name of app / service**

Runware

**Link to developer documentation**

https://docs.runware.ai/en/getting-started/introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**

No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
> 
REST API will be available soon, we are working on it.

As of writing, API is Runware Websockets only, per [documentation](https://docs.runware.ai/en/getting-started/how-to-connect#websockets).

**Comment by sergio-eliot-rodriguez** [comment]
Hi Danny @dep 

Are there any specific triggers and/or actions you'd need for your Runware use case? We could build those into nocode components available out of the box with our Runware base integration at Pipedream.

**Comment by dep** [comment]
I think the most basic Action would be a step that would take a prompt as an argument and return a URL to the rendered image in the return value.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @dep 
we have rolled out a base integration for Runware: https://pipedream.com/apps/runware
as of the action you need, can you please check if our action "create task" is helpful to your case?
you can check that out #14361

**Comment by dep** [comment]
Thank you @sergio-eliot-rodriguez !
