### ISSUE TITLE
[FEATURE] Slack/Slack Bot Updates

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#13587]
1. Update Slack Bot integration with usability updates from Slack app
2. Update Upload File action to utilize upload v2 ahead of sunset

The original files upload method `files.upload` is being sunset, and users who have created apps after May 2024 are running into issues as they are unable to use the Upload File action without hitting errors.
![image (9)](https://github.com/user-attachments/assets/e0903052-31f8-4d31-9d87-6aa73e358667)

This request is to refactor our Slack / Slack Bot - Upload File action to use the upload v2 method:
https://api.slack.com/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay#prepare

**Comment by michelle0927** [comment]
For reference, Slack usability updates - https://github.com/PipedreamHQ/pipedream/pull/12265
