### ISSUE TITLE
[Usability Audit] Gmail

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#13581]
In preparation of having Restricted Scopes provisioned on our Pipedream Gmail client, which will unlock our components to a much larger group of users, we should do a usability audit on all of the components. 

The easiest way to do this would most likely be to testing using Gmail (Developer App), and roll out changes on both Gmail (Developer App) as well as Gmail app.

**Comment by michelle0927** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Usability-Audit-Gmail-28b7295557e349ec933d7a7613b12e9b

@vunguyenhung The "Update Primary Signature" action requires this scope: `https://www.googleapis.com/auth/gmail.settings.basic`. Try reconnecting your account and adding that scope to the "Space Separated Scopes" field.
