### ISSUE TITLE
[APP] Instagram for Business Integration

### ISSUE THREAD

**Issue by ellealexandrova** [PipedreamHQ/pipedream#13592]
**Name of app / service**: Instagram for Business

**Link to developer documentation**: https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/get-started

**Is lack of support preventing you from building workflows, or do you have a workaround?**: In order to have api permissions for post creation, you need an app, so there is no workaround using Pipedream atm that I am aware of.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
![image](https://github.com/user-attachments/assets/4ab43347-8d2c-40a1-8d3d-cb452f9397f2)

**Comment by sergio-eliot-rodriguez** [comment]
Duplicated. We are tracking Instagram at #445, please follow there, if you'd like.
