### ISSUE TITLE
[APP] Docuseal

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#13594]
**Name of app / service**
Docuseal

**Link to developer documentation**
https://www.docuseal.co/signing-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Sign a document

**Comment by sergio-eliot-rodriguez** [comment]
Hi @LucBerge 

Thanks for the request. A base integration for DocuSeal is now available -- https://pipedream.com/apps/docuseal
