### ISSUE TITLE
[obsidian]

### ISSUE THREAD

**Issue by reneurishme** [PipedreamHQ/pipedream#13603]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Obsidian is being tracked at https://github.com/PipedreamHQ/pipedream/issues/6144, feel free to follow, if you'd like

In case you think this is an error, let us know
