### ISSUE TITLE
[components] supabase_management_api

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#13637]
# supabase_management_api
## URLs
- https://supabase.com/docs/reference/api/introduction
#### Prompt
Emits new event when a database backup is completed for a project. Requires project ref as input.
#### Prompt
Generates TypeScript types based on the current database schema for a specified project. Requires project ref and optionally included schemas as inputs.
#### Prompt
Creates a new Supabase project within a specified organization. Requires organization ID, project name, database password, and region as inputs. Optionally accepts desired instance size and template URL.

**Comment by michelle0927** [comment]
@vunguyenhung 

<img width="1311" alt="Screenshot 2024-08-29 at 10 31 29 AM" src="https://github.com/user-attachments/assets/0f86903e-796f-429b-a611-d9b8b186af40">
<img width="1355" alt="Screenshot 2024-08-29 at 10 32 21 AM" src="https://github.com/user-attachments/assets/f749fae2-6bae-470e-8a7b-62937a6c792f">
