### ISSUE TITLE
Kiwi browser 

### ISSUE THREAD

**Issue by sjn001tvh** [PipedreamHQ/pipedream#1365]
Greetings.  Could you see if Kiwi Browser has api calls that would open a website using the Pipedream api calls.  Thanks.

**Comment by dylburger** [comment]
@sjn001tvh are there specific API docs you're looking at? Or can you tell me more about what you're trying to do? Is this a similar use case to Puppeteer?

**Comment by sjn001tvh** [comment]
Hi Dylan,
Kiwi browser is an app on my phone that provides Chrome functionality, and allows me to display and execute an html file using this browser from my phone.  
I know that you have a lot of requests, and I'm not sure whether you remember some of the tasks that I'm trying to accomplish.  But you did ask me to explain a little bit more about what I'm trying to do.  So I'm hoping you'll indulge me for a few moments while try to explain my objectives.  
First, I'm so impressed with Pipedream.  It's the coolest utility that I have found.  I've been able to accomplish almost everything that I have wanted to do in order to transfer Contact information from my phone into ClickUp, without requiring me to reenter any information by hand from my phone into ClickUp.  It works seamlessly, and it's all through the workflow steps using Dropbox and ClickUp api calls within Pipedream.  So kudos to you and your team.  What a great service, and for my purposes it's very cost effective.
The challenge I'm faced with pertains to continuing the process in ClickUp.  Once a new contact is created in ClickUp, the step that immediately follows, always incudes the creation of a new project, and included with that, is the new contact record, and the need to create a link between the client and the new project.  This is all doable within ClickUp, both on my phone and my laptop.  
However, as a self employed general contractor, when I get a call from a prospective client, I'm usually on a job and my phone is the only input device that I have avialable to me at that moment.  Entering information using my phone as the input device, is not the same as using a keyboard.  ALL UTube videos and documentation pertaining to ClickUp, invariably show a person on a computer using their keyboard and mouse.  Not ONE, shows someone using the phone to enter and manipulate information using a smart phone.
Entering text into any app on my phone is performed in one of 2 ways, I either can speak into the phone, and depending on the app, it captures my voice and converts it into text; or, I enter text using a my right hand index finger, holding my phone with my left hand (I'm right handed, probably the opposite for a left handed person).  I'm not a person of the younger generation, who can use their thumbs to quickly type information into my phone, so my only typing method is to use my index finger, and I simply distain and try avoid this method, because I'm always hitting an 'o' when I wanted an 'i', or vise versa, etc.  It's just frustrating.  I try to avoid answering text messages for the same reason.
When I create a project, especially after receiving a call from a prospective client, I gather certain pieces of information.  Their name, their address, the type of their project and the project description, and an approximate date to visit them to make the initial project assessment.  All this is easily done in ClickUp using a keyboard and mouse.  However, that's a lot of information that is overwhelmingly difficult and time consuming to enter into ClickUp on my phone app using my index finger to enter the text into the appropriate fields and create the links.  Trying to convey this concept to ClickUp support, it's difficult for them to understand, because they've designed everything to be used from a keyboard and mouse.
So I have devised a method to assist me in getting the information from my phone to ClickUp.  When I create a new Contact Record in ClickUp, I already have access to information from ClickUp to create the project.  The new contact is the Project Owner, got it.  Now I need to indicate the project Type.  In ClickUp, I have a CustomField as a dropdown list that contains a list of project types, such as, HandymanTasks, RemodelTasks, Decks, Fences, Garages, InteriorDesign, etc.  I can access that list and place the results into an html <select> element, which allows me to use my finger to select from the list without having to type the entire name of the project type, or require me to remember the specific code for it.  
Next is the description of the project, which could vary from a single line item, to a fairly descriptive paragraph.  To accomplish this task, I'm using an app on my phone called VoiceNotes, which transcribes my vocal input to text, and allows me to save the information into a specific folder in my Dropbox account.   That file can then be imported into an <input> element in the html file.
Finally, the appointment.  Not all the time do I commit to an appointment with the new client during the call,  but I do make a commitment to him/her, to contact them within the next several days or by the following week, to secure a time.  I need to make sure that I log that type of commitment.  So I have several buttons and/or dropdown lists to include followup information to trigger notifications within ClickUp as I move that information from the html document and update ClickUp projects and appointment calendar.
Dropbox does not allow the api calls to display the hmtl document, only it's contents, and I can't seem to find any other app that will help me accomplish the flow of this task.  I need to call an api that will allow the html file to be viewed and executed as if it was displayed by a browser on my laptop, and I need to be able to determine whether it's being displayed and used from my phone or my laptop, so that I can format the sizes of the elements, to match the needs of the input.  
Thus, the need for a browser for my phone in order to display either the website that contains the html file for the project input, or any other utility that will display the html file on my phone, and allow me to enter and/or quickly select information and/or the options to create the project and set the appointment or notification in Clickup to remind me to set the appointment when I return using my laptop, keyboard, and mouse.
This is why I was researching Kiwi browser.  I installed it on my phone, entered my website, and the website displayed perfectly.  Now the challenge is to get Pipedream api call to actually open a website within the steps of a workflow, and wait for a callback, when the html file gets "POST"ed.
I apologize for being so verbose.  But I hope this helps.  Kiwi browser may not be the answer, because I'm not sure it has api calls that can be implemented. What I'm really after in an app with api calls that will process an html file from a smart phone, and that Pipedream can support it with a callback function that triggers an action, either in the same workflow, or triggers another workflow.
Thanks for listening.
Scott.    On Thursday, June 24, 2021, 11:17:45 AM PDT, Dylan J. Sather ***@***.***> wrote:  
 
 


@sjn001tvh are there specific API docs you're looking at? Or can you tell me more about what you're trying to do? Is this a similar use case to Puppeteer?

**Comment by dylburger** [comment]
@sjn001tvh sorry for the late follow up here. I read through your note. I believe the best way to solve your use case would be to create your own HTML form that POSTs the data to a Pipedream HTTP endpoint, or use an app on your phone to submit form data specific to your use case (e.g. I use iOS Shortcuts for this purpose, which can send any data you enter in a form in an HTTP request). That gives you full control over the data you'd like to enter.

I looked into Kiwi, and I don't see an API that would allow you to do what you're asking.

#1589 might also be related to your use case - feel free to follow that.
