### ISSUE TITLE
[APP] TickTick

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1367]
https://developer.ticktick.com/docs#/openapi

**Comment by DoMoreStressLess** [comment]
Yes, please!!  This would be super helpful for me and many of my clients.

**Comment by todsac** [comment]
Here is a first version.  Please confirm this works for you - https://pipedream.com/apps/ticktick

**Comment by DoMoreStressLess** [comment]
Thank you!  I'll share with my clients.

**Comment by dylburger** [comment]
Thanks @DoMoreStressLess !
