### ISSUE TITLE
[APP]  Unthread

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#13683]
**Name of app / service**

Unthread

**Link to developer documentation**

https://docs.unthread.io/api-introduction/using-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

No workaround, would like to have events triggers in Pipedream.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Read / Write for most objects, actions relating to conversations and customers.

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pd, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Hi @johndbritton  thanks for the request.
We rolled out a base integration for Unthread at: https://pipedream.com/apps/unthread
