### ISSUE TITLE
[APP] apipie.ai

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#13695]
**Name of app / service**
apipie.ai

**Link to developer documentation**
https://apipie.ai/docs/api/introduction

**Comment by Toocky** [comment]
Hi, one of the founders of APIpie here,

Thanks for the mention, if anyone is interested in integrating us then please reach out on our discord and we will be happy to give some free credit to help with the process.

https://discord.gg/hs82THc9Tw

**Comment by sergio-eliot-rodriguez** [comment]
Thank you @Toocky 

@malexanderlim i was about to tackle this one today, however the app slug for this app `apipie_ai` is taken with internal status of "other", can you check if this app is in good state to move it back to the app store? 
in anycase, i could use a different appslug, and submit for i was able to gen an api key and use it with a simple "fetch models" endpoint, good for test request, plus we could take the offer from Toocky to get credits for the chat completions, text to speech conversion and other valuable endpoints.

**Comment by sergio-eliot-rodriguez** [comment]
APIpie has now a base integration at https://pipedream.com/apps/apipie-ai

**Comment by sergio-eliot-rodriguez** [comment]
@Toocky Hi there! I'm Sergio from the Pipedream integrations team.

We launched a base integration for APIpie.ai a while back, and we are now getting ready to roll out some updates and add new pre-build components to the Pipedream app store.

I saw your offer here for free credits to help with the integration process. We'd love to take you up on that so we can properly test these new features.

Could you please apply some developer credits to our account?

* **Username:** `pipedreamdev`
* **Email:** `sergio[at]pipedream[dot]com`

Let me know if you need any extra details from my end to get this set up. Thanks for the support!
