### ISSUE TITLE
[BUG] Handling of timer-based events

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#1369]
**Describe the bug**
Some event sources that are triggered by a timer rely on the input events to be in a certain format.
In some cases that format is not accurate and can potentially break the expected behaviour of the event source.

For example, most of the [Google Drive event sources](https://github.com/PipedreamHQ/pipedream/tree/master/components/google_drive/sources) expect the timer-based events to contain an `interval_seconds` attribute, which is not a valid assumption. An example of this can be observed here:
https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/sources/common-webhook.js#L71

If the timer is configured using a **cron** expression for example, the `interval_seconds` attribute is not present, but it is in fact "replaced" by the `cron` attribute.

The only invariant for timer-based events is that they contain a `timestamp` attribute, and any logic around the `interval_seconds` attribute must be refactored to guarantee the expected behaviour.

**Comment by dylburger** [comment]
Timer-based emitters now have a well-defined interface across event sources and workflows! Example:

```json
{
  "timestamp": 1650879563,
  "timezone_utc": {
    "date": {
      "day": 25,
      "month": 4,
      "year": 2022
    },
    "iso8601": {
      "date": "2022-04-25",
      "time": "09:39:23+00:00",
      "timestamp": "2022-04-25T09:39:23+00:00"
    },
    "metadata": {
      "day_name": "Monday",
      "day_of_week": 1,
      "start_of_week": "2022-04-25"
    },
    "pretty": {
      "date": "Apr 25, 2022",
      "time": "9:04:23 AM",
      "time_24h": "09:39:23"
    },
    "time": {
      "hour": 9,
      "millisecond": 874,
      "minute": 39,
      "second": 23
    },
    "timezone": "UTC"
  },
  "timezone_configured": {
    "date": {
      "day": 25,
      "month": 4,
      "year": 2022
    },
    "iso8601": {
      "date": "2022-04-25",
      "time": "09:39:23+00:00",
      "timestamp": "2022-04-25T09:39:23+00:00"
    },
    "metadata": {
      "day_name": "Monday",
      "day_of_week": 1,
      "start_of_week": "2022-04-25"
    },
    "pretty": {
      "date": "Apr 25, 2022",
      "time": "9:04:23 AM",
      "time_24h": "09:39:23"
    },
    "time": {
      "hour": 9,
      "millisecond": 874,
      "minute": 39,
      "second": 23
    },
    "timezone": "UTC"
  },
  "interval_seconds": 82080
}
```
