### ISSUE TITLE
[APP] Monday.com Custom OAuth

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13704]
**Name of app / service**
Monday.com

**Link to developer documentation**
https://developer.monday.com/apps/docs/oauth

**Is lack of support preventing you from building workflows, or do you have a workaround?**
A customer is asking for Monday.com OAuth client to buid their own Monday.com App. They might also need to use [BYOA feature](https://pipedream.com/docs/connected-accounts/oauth-clients). 

Front link: https://app.frontapp.com/open/cnv_nznrcef?key=PnJp2og_PiG2SkT6KscqWAQWdtKUIufV

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
No

**Comment by BlinnoSimon** [comment]
@vunguyenhung @dylburger any update on this or ETA?

**Comment by dannyroosevelt** [comment]
> @vunguyenhung @dylburger any update on this or ETA?

Hi @BlinnoSimon, to confirm, I see our Monday integration currently uses an API key to authenticate. We can look into updating it to use OAuth instead, but is there a piece of functionality you're blocked on in the meantime? I want to make sure we're solving whatever problem you're running into.

**Comment by BlinnoSimon** [comment]
Hi @dannyroosevelt 

Thanks for your quick reply! We need OAuth to build an app in monday.com. Unfortunately, this is not possible via API Key.  
We are a big monday.com partner from Europe and would like to build apps with no-code. This is the only thing that prevents us from starting.

**Comment by dannyroosevelt** [comment]
> Hi @dannyroosevelt
> 
> Thanks for your quick reply! We need OAuth to build an app in monday.com. Unfortunately, this is not possible via API Key. We are a big monday.com partner from Europe and would like to build apps with no-code. This is the only thing that prevents us from starting.

Got it, thanks for the context. We're looking into this now.

**Comment by BlinnoSimon** [comment]
> > Hi @dannyroosevelt
> > Thanks for your quick reply! We need OAuth to build an app in monday.com. Unfortunately, this is not possible via API Key. We are a big monday.com partner from Europe and would like to build apps with no-code. This is the only thing that prevents us from starting.
> 
> Got it, thanks for the context. We're looking into this now.

Thanks great! If you need any additional information, please let me know, happy to help.

**Comment by dannyroosevelt** [comment]
@BlinnoSimon I just published this app:
https://pipedream.com/apps/monday-oauth

Can you let me know if that works for you? We don't currently have any triggers or actions created for that version of the app, but we can get those added.

**Comment by BlinnoSimon** [comment]
> @BlinnoSimon I just published this app: https://pipedream.com/apps/monday-oauth
> 
> Can you let me know if that works for you? We don't currently have any triggers or actions created for that version of the app, but we can get those added.

Hi Danny

Thank you amazing! I've tried to use it and could set it up but I'm not sure if this is possible what I'm trying to achieve. In Pipedream I need to select one account, and it's not dynamically afterwards. 

Fixed Connection
![image](https://github.com/user-attachments/assets/7a2bd1c0-cf2d-47d4-980d-9328f342532d)

In monday.com Apps when the user first time using the app they need to give permission. Is this even possible with Pipedream? https://developer.monday.com/apps/docs/oauth

I hope you get my idea, otherwise let me know.

**Comment by dannyroosevelt** [comment]
Ah interesting, yea it sounds maybe like Connect is what you're looking for. Can you tell me a bit more about what you're trying to do in general?

**Comment by BlinnoSimon** [comment]
> Ah interesting, yea it sounds maybe like Connect is what you're looking for. Can you tell me a bit more about what you're trying to do in general?

Sure!
In monday.com there is an App Marketplace where you can publish apps. We already have 1-2 apps there, but of course we have to write them in code and host them on AWS or monday Code. For the other cases we use Make.com for integrations and apps for our customers. We are now looking for a way to create the monday.com apps in “no-code” and we thought Pipedream might work. We can also set up a call if you want me to show you everything.

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/monday-oauth
