### ISSUE TITLE
[BUG] Konfhub connection popup - Test Connection button throws error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13714]
**Describe the bug**
On Konfhub connection poup - Test Connection button throws error when there's API Key added
![image](https://github.com/user-attachments/assets/0f385978-fbe8-4b24-9ac2-626820a758ae)
![image](https://github.com/user-attachments/assets/1684bb37-023f-4211-83aa-08f69ebabcb6)

Also, the Event ID and Email props are redundant, as they should be included in action/source props
![image](https://github.com/user-attachments/assets/f34bc807-c27e-405f-afc2-6409318b6863)

**Comment by malexanderlim** [comment]
I've removed the test request and scaffolding as event id and email should not be collected as a custom field, but rather as props for the actions. @vunguyenhung can you retest and let me know if this is working now for you? One caveat, without a test request configured, the test connection button still shows up and always gives success but the actions should work.
