### ISSUE TITLE
[BUG] Update Adalo components to use collection_id from $auth

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13723]
**Describe the bug**
I add API Key and App ID to the Adalo connection popup, then I click the Test connection button, but it failed with 403 error
![image](https://github.com/user-attachments/assets/e1846ba1-9da0-4779-bd5e-dc3e78bfe6cc)
![image](https://github.com/user-attachments/assets/1e7011a0-7ced-4112-a720-b67dfded8eaa)

Eventhough the action works fine with the API Key and App ID I provided
![image](https://github.com/user-attachments/assets/c344b95f-313c-4e98-afdd-31848186832f)

**Comment by malexanderlim** [comment]
I've made `collection_id` a custom field for account connection, as it is required for all requests here and there's no endpoint to list collections. Once you reconnect and input, the test request should work as expected. 

The components will need to be updated though to use collection_id from $auth

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
