### ISSUE TITLE
[Components] gptzero_detect_ai

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13763]
# gptzero_detect_ai
## URLs
- https://gptzero.stoplight.io/docs/gptzero-api/5bf295g49gwxp-gpt-zero-api
#### Prompt
This endpoint takes in file(s) input and returns the model's result. By default, the maximum number of files that can submitted simulatenously is 50, and the max file size for all files combined is 15 MB. Each file's document will be truncated to 50,000 characters. Required prop: 'files'. optional prop: 'version'.
#### URLs
- https://gptzero.stoplight.io/docs/gptzero-api/0a8e7efa751a6-ai-detection-on-an-array-of-files
#### Prompt
This endpoint takes in a single text input and returns runs AI detection. The document will be truncated to 50,000 characters. Required prop: 'document'. optional props: 'version' and 'multilingual'.
#### URLs
- https://gptzero.stoplight.io/docs/gptzero-api/d2144a785776b-ai-detection-on-single-string

**Comment by sergio-eliot-rodriguez** [comment]
@luancazarine we have a new api key with higher limit usage provided by GPT Zero, It copied it to 1PW. I tested and it works.
