### ISSUE TITLE
[Components] scrapfly

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13774]
# scrapfly
## URLs
- https://scrapfly.io/docs
#### Prompt
Retrieve current subscription and account usage details. The output may provide insights about the plan type, usage status, remaining requests and other specific account information. No input props required.
#### URLs
- https://scrapfly.io/docs/account#api
#### Prompt
Extract data from a specified web page. The URL of the web page is the required prop. The output is the page content in HTML or Text and Markdown (LLM). Required props are: 'url' and 'key'.Additional optional props may include specific scrapfly parameters for scraping.
#### URLs
- https://scrapfly.io/docs/scrape-api/getting-started
- https://scrapfly.io/docs/scrape-api/getting-started#spec
#### Prompt
Automate content extraction from any text-based source using AI, LLM and custom parsing. The input props required are 'key', 'body' and 'content_type'. The output would be structured data derived from the source.
#### URLs
- https://scrapfly.io/docs/extraction-api/getting-started?language=node_js
- https://scrapfly.io/docs/extraction-api/getting-started#spec

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-scrapfly-a9bec31f3a89494eb34dc239a7bd47b6

Hi @vunguyenhung, The problem with the scrape-page action isn't the format markdown, actually it's the country, It must be lowercase, but anyway I've added options to select
