### ISSUE TITLE
Zoho Books

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13791]
### App
Zoho Books

### Summary:
When attempting to connect a new account to Zoho Books, it fails on the redirect to the callback.

### Details:
When attempting to connect a new account to Zoho Books, it fails on the redirect to the callback with the tokens to Pipedream. I end up getting a "Pipedream encountered an error when connnecting to your account" message.

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-09-01-105716.png?id=MaBBWg&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1hQkJXZyIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcyNTIwMjY1OX0.vy8h6miRB2SS4dqI9WoLa8UnuRw0h1U0jqxeBZVoYgM&signature=83b0580faf8292a008f4afa964c5a4d12709e78b22498da8a3c933ce2a3bbcfc)

**Comment by malexanderlim** [comment]
This was an issue due to a breaking change in the **Zoho Inventory** API. You will need to reconnect your account, with your `organization_id` in order to fix this.
