### ISSUE TITLE
[Components] fakturoid

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13809]
# fakturoid
## URLs
- https://www.fakturoid.cz/api/v3
#### Prompt
Emit new event when an invoice status changes to 'Overdue' or 'Paid'. Props required: invoice_id, new_status.
#### URLs
- https://www.fakturoid.cz/api/v3/invoices
- https://www.fakturoid.cz/api/v3/invoice-payments
- https://www.fakturoid.cz/api/v3/events
- https://www.fakturoid.cz/api/v3/webhooks
#### Prompt
Emit new event when a contact is added in fakturoid. No props required.
#### URLs
- https://www.fakturoid.cz/api/v3
- https://www.fakturoid.cz/api/v3/authorization
- https://www.fakturoid.cz/api/v3/users
- https://www.fakturoid.cz/api/v3/account
- https://www.fakturoid.cz/api/v3/subjects
- https://www.fakturoid.cz/api/v3/webhooks
#### Prompt
Emit new event when a new invoice is created in fakturoid. Optional prop: customer_id to filter invoices to a specific customer.
#### URLs
- https://www.fakturoid.cz/api/v3
- https://www.fakturoid.cz/api/v3/authorization
- https://www.fakturoid.cz/api/v3/users
- https://www.fakturoid.cz/api/v3/account
- https://www.fakturoid.cz/api/v3/invoices
- https://www.fakturoid.cz/api/v3/invoice-payments
- https://www.fakturoid.cz/api/v3/invoice-messages
- https://www.fakturoid.cz/api/v3/events
- https://www.fakturoid.cz/api/v3/webhooks
#### Prompt
Creates a new invoice. Requires 'contact_id' and 'lines' props to establish associated contact and invoice items. Optionally, 'number', 'due', and 'note' props may be provided to assign the invoice number, due date and additional notes.
#### URLs
- https://www.fakturoid.cz/api/v3/subjects
- https://www.fakturoid.cz/api/v3/invoices
#### Prompt
Cancels an existing invoice or revokes previous cancellation. Requires 'invoice_id' prop denoting the identification number of the relevant invoice.
#### URLs
- https://www.fakturoid.cz/api/v3/invoices
#### Prompt
Executes payment for an invoice or removes an already applied payment. Requires 'invoice_id' prop defining the specific invoice to be targeted. Optional 'payment_value' prop can be provided to stipulate payment amount.
#### URLs
- https://www.fakturoid.cz/api/v3/invoices
- https://www.fakturoid.cz/api/v3/invoice-payments

**Comment by sergio-eliot-rodriguez** [comment]
Unless better opinion @dannyroosevelt 
looks like webhooks can't be implemented via the API. this is what fakturoid said after back and forth:

> 
> I'm not sure what exactly do you mean by registering them programmatically? In this context users need to set the webhooks up themselves, the integration can't do it for them automatically - if that's what you meant.
> 
> Regards 🤖

**Comment by sergio-eliot-rodriguez** [comment]
so maybe implement the source by api polling instead of webhook base (?)

**Comment by dannyroosevelt** [comment]
Yea sounds good, thanks Sergio
