### ISSUE TITLE
[IMPROVEMENT] Chainware AI - Remove Wallet Address on connection popup

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13812]
**Is your feature request related to a problem? Please describe.**
Currently Chainware AI connection popup requires Wallet Address
![image](https://github.com/user-attachments/assets/c54cad03-9e43-456c-90a1-7d02ac8f16dd)

Though the action also requires the Wallet Address prop 
![image](https://github.com/user-attachments/assets/14637b02-9071-45ef-8a83-f7a87c39f3a0)

**Describe the solution you'd like**
I think it will be more flexible to have the Wallet Address prop in the action, so we can remove the Wallet Address prop in the connection popup

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
