### ISSUE TITLE
[Components] infolobby

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13810]
# infolobby
## URLs
- https://infolobby.com/site/apidocs/
#### Prompt
Post a comment on an existing InfoLobby table record. Required props are recordID and commentText. An optional prop could be commenterName to provide the name of the person making the comment.
#### URLs
- https://infolobby.com/site/apidocs/
- https://infolobby.com/site/apidocs/3/working-with-records/
- https://infolobby.com/site/apidocs/4/working-with-record-comments/

**Comment by lcaresia** [comment]
`update-record` and `create-record` returns a weird error, so I removed that actions.

![image](https://github.com/user-attachments/assets/d86fe0ec-6fae-4c5e-ae95-3ff482b15908)
