### ISSUE TITLE
[TRIGGER] lobste.rs

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1387]
I'd like to trigger a workflow when a new item is added to pages like https://lobste.rs/threads/adamgordonbell

**Comment by todsac** [comment]
I believe this can be done with the RSS trigger.  For example, https://lobste.rs/newest/adamgordonbell.rss.

We could create a Lobste.rs specific one like we have done for HackerNews.

**Comment by todsac** [comment]
For comments, they recommend this path - https://lobste.rs/s/lc58pw/what_are_you_doing_this_week.json

See - https://github.com/lobsters/lobsters/issues/225

**Comment by malexanderlim** [comment]
Currently blocked on submitting this due to issue with submitting apps with no auth type.
