### ISSUE TITLE
[APP] Wise (formerly Transferwise)

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#1389]
**Name of app / service**
Wise (formerly Transferwise)

**Link to developer documentation**
https://api-docs.wise.com/#wise-platform-api

The default action should be this one: https://api-docs.transferwise.com/#payouts-guide-get-your-profile-id

It might not be possible to create an app for everyone using PipeDream, but I'd like a place to store my API key and the associated profile id and borderless account id.

The way it works is that once you generate an API key, you have to get your profile ids (personal and/or business):

    curl -X GET https://api.transferwise.com/v1/profiles -H "Authorization: Bearer <WHATEVER>"

Then you have to check your account balance to get your borderless account id:

    curl -X GET "https://api.transferwise.com/v1/borderless-accounts?profileId={profileId}" -H "Authorization: Bearer <WHATEVER>"

Then you can get your statements or anything else. For example:

    curl -X GET "https://api.transferwise.com/v3/profiles/{profileId}/borderless-accounts/{borderlessAccountId}/statement.json?currency=USD&intervalStart=2021-04-01T00:00:00.000Z&intervalEnd=2021-07-09T23:59:59.999Z&type=COMPACT" -H "Authorization: Bearer <WHATEVER>"

**Comment by todsac** [comment]
Nacho - Please let me know if this is what you had in mind:
https://pipedream.com/apps/wise

**Comment by nachocab** [comment]
Thanks, Tod.

It would be even better if besides the API key, I could also add two more fields:

- profile id
- borderless account id

The same API token can access multiple profile ids, each associated with multiple borderless account ids

**Comment by nachocab** [comment]
Also, the URL should probably be `api.transferwise.com` instead of the sandbox

**Comment by todsac** [comment]
The issue with including the profile ID and borderless account ID is that it will then force a user to have a different authentication with each unique profile id.  Is that ideal?  Usually, we keep the custom fields to the absolute minimum requirements to access the API and then encourage the use of environment variables for sub-account use cases.  I assume there are some use cases where a user would want to access multipe profile IDs correct?

I changed the URL.

**Comment by nachocab** [comment]
> The issue with including the profile ID and borderless account ID is that it will then force a user to have a different authentication with each unique profile id. Is that ideal?

I guess I can add that information as environment variables. No problem, then 👍
