### ISSUE TITLE
dbt Cloud - Cannot connect account

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13940]
### App
dbt Cloud

### Summary:
Cannot authenticate with dbt Cloud

### Details:
I am attempting to setup a connection with dbt Cloud but Pipedream cannot authenticate. I have attempted using multiple service keys with different permissions, including account admin. I think the issue may be related to the region, as our account is on dbt's newer multi-cell region (North America Multi-cell). We also have a static access url (https://aq567.us1.dbt.com/). I have attached a screenshot of what I am entering into the Pipedream integration config but it still is not working. 

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-09-12-at-8.42.24-PM.png?id=kNNE1d&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImtOTkUxZCIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcyNjE5MTg4OH0.rPh-NGtMjM8_UMRs9h6UV_9QTNA6dM4DtI83Jv4y0A0&signature=40b868ea0fe848a6ee6711f220555b4033c0e5583d8dce882a6fb1626a183bf6)

**Comment by dannyroosevelt** [comment]
I have an account that works and I can't repro the issue. @vunguyenhung does this seem to be related to a static URL? Or the multi-cell region support like the original issue suggests?

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by dannyroosevelt** [comment]
This should be fixed now
