### ISSUE TITLE
[Components] zenventory

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13944]
# zenventory
## URLs
- https://docs.zenventory.com
#### Prompt
Emit new event every time a customer order is created. The main prop to set is the order ID. Other good optional props can be order status and the customer ID.
#### URLs
- https://docs.zenventory.com/#tag/customer_order/paths/~1customer-orders/get
#### Prompt
Emit new event when a purchase order is created. This involves configuring the purchase order ID and can optionally include the vendor ID and order status.
#### URLs
- https://docs.zenventory.com/#tag/purchase_order/paths/~1purchase-orders/get
#### Prompt
Emit new event when a new item is created. The only required prop is the item ID. Optional props can be item category and the supplier ID.
#### URLs
- https://docs.zenventory.com/#tag/items/paths/~1items/get
#### Prompt
Creates a new inventory item in Zenventory. Props consists of item data: name, quantity, etc.
#### URLs
- https://docs.zenventory.com/#tag/items/paths/~1items/post
#### Prompt
Creates a new customer order in Zenventory. Props include customer information and order details.
#### URLs
- https://docs.zenventory.com/#tag/customer_order/paths/~1customer-orders/post

**Comment by sergio-eliot-rodriguez** [comment]
Btw Allocadance #13950 and Zenventory are meant to have the same components

**Comment by sergio-eliot-rodriguez** [comment]
From the conversation with Allocadance, Zenventory app developers:
...

> I am the product manager for both [Allocadence](https://www.allocadence.com/) & [Zenventory](https://www.zenventory.com/) (sister applications serving different verticals but both for warehouse operations, lots of shared code).  It would make sense for you guys to approach both integrations at once:  The API URLs are different, but the endpoints and API functionality are otherwise exactly the same (you'll get two integrations for the development work of 1).

**Comment by sergio-eliot-rodriguez** [comment]
I reached out to Zenventory asking them to extend the trial.

**Comment by sergio-eliot-rodriguez** [comment]
FYI these are the components that app developers recommended to implement. 
i'm not sure if all of them are possible in both applications Zenventory/Allocadence:

Some core functions that would be good support as a starting point:

>     TRIGGERS
>         [New Customer Order Created](https://docs.zenventory.com/#tag/customer_order/paths/~1customer-orders/get)
>         [New Purchase Order Created](https://docs.zenventory.com/#tag/purchase_order/paths/~1purchase-orders/get)
>         [New Item Created](https://docs.zenventory.com/#tag/items/paths/~1items/get)
>     ACTIONS
>         [Create a Customer Order](https://docs.zenventory.com/#tag/customer_order/paths/~1customer-orders/post)
>         [Create a Purchase Order](https://docs.zenventory.com/#tag/purchase_order/paths/~1purchase-orders/post)
>         [Create an Item](https://docs.zenventory.com/#tag/items/paths/~1items/post)
