### ISSUE TITLE
[Components] allocadence

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13950]
# allocadence
## URLs
- https://docs.allocadence.com/
#### Prompt
Emit new event when a new customer order is created. Required props: customer ID, product ID. Optional props: order details, delivery mode
#### URLs
- https://docs.allocadence.com/#tag/customer_order/paths/~1customer-orders/get
#### Prompt
Emit new event when a new purchase order is created. Required props: supplier ID, product ID. Optional props: quantity, delivery date
#### URLs
- https://docs.allocadence.com/#tag/purchase_order/paths/~1purchase-orders/get
#### Prompt
Creates a new customer order. Required props: customer information, product details, shipping address. Optional props: special instructions for order.
#### URLs
- https://docs.allocadence.com/#tag/customer_order/paths/~1customer-orders/post
#### Prompt
Generates a new purchase order. Required props: supplier details, product details, delivery address. Optional props: order deadline, additional instructions.
#### URLs
- https://docs.allocadence.com/#tag/purchase_order/paths/~1purchase-orders/post

**Comment by sergio-eliot-rodriguez** [comment]
Btw Allocadance and Zenventory #13944 are meant to have the same components

**Comment by sergio-eliot-rodriguez** [comment]
From the conversation with Allocadance, Zenventory app developers:
...

> I am the product manager for both [Allocadence](https://www.allocadence.com/) & [Zenventory](https://www.zenventory.com/) (sister applications serving different verticals but both for warehouse operations, lots of shared code).  It would make sense for you guys to approach both integrations at once:  The API URLs are different, but the endpoints and API functionality are otherwise exactly the same (you'll get two integrations for the development work of 1).
