### ISSUE TITLE
Add CompanyCam to your connections

### ISSUE THREAD

**Issue by StetsonRamey** [PipedreamHQ/pipedream#1395]
Might be a one off for me, and I'm working around you not having an integration so if you've got higher priority stuff, all good.  This would be handy for me though:

https://companycam.com/
https://docs.companycam.com/reference

Thanks PipeDream!

**Comment by todsac** [comment]
Do you have a contact at the company?  This integrations requires a client id, which their docs say we "can get from your CompanyCam representative."

**Comment by todsac** [comment]
FYI - I am in touch with CompanyCam and they are providing the credentials.

**Comment by todsac** [comment]
@StetsonRamey - We have a first version of the integration up -- https://pipedream.com/apps/companycam

Please let us know if you are able to add [triggers or actions](https://pipedream.com/docs/components/).

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
