### ISSUE TITLE
Add Instagram app

### ISSUE THREAD

**Issue by techxquad** [PipedreamHQ/pipedream#13971]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hey buddy @techxquad 
Thanks for the request. Instagram is very much upvoted by our users.
Would you mind following the request to add Instagram app in issue #445?
I'm closing your request as duplicated.
Thanks
