### ISSUE TITLE
[APP] Twitch OAuth authorization code flow

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1398]
Twitch

https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-authorization-code-flow

Twitch has a separate authorization flow that's required for working with Chatbots/IRC. The workaround to retrieve a list of user subscriptions via the chatbot will need oauth tokens from this auth flow.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @michelle0927 

This appears to have been integrated -- https://pipedream.com/apps/twitch

Per the access token configuration, that is using authorizatino code grant

accessToken
POSThttps://id.twitch.tv/oauth2/token
content-type: application/x-www-form-urlencoded
accept: application/json
client_id={{oauth.client_id}}&client_secret={{oauth.client_secret}}&redirect_uri={{oauth.redirect_uri}}&grant_type=**authorization_code**&code={{oauth.code}}

And the other Twitch app https://pipedream.com/apps/twitch-developer-app
is using client_credentilas grant.

However if there's a mistake or something is missing let us know. 

Thanks,
Sergio
