### ISSUE TITLE
[APP] Unthread.io

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#13993]
**Name of app / service**

Unthread.io

**Link to developer documentation**

https://docs.unthread.io/api-introduction/using-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

No workaround, they have Zapier support built in.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Triggers for the various webhooks provided by Unthread as well as actions for the primary API endpoints

**Comment by sergio-eliot-rodriguez** [comment]
@johndbritton thanks for the request.

As you may have seen, there is already a base integration for Unthread.io:
https://pipedream.com/apps/unthread

And we have developed certain actions:
![image](https://github.com/user-attachments/assets/c6b203a0-11e1-4d95-8c5a-934b78bd77da)


Can you please explicitly specify the triggers and actio

> ns (components) you'd like to see?
> 
> You can see issue #3542 for an example of a request with components explicitely specified:
> App
> 
> Affinity
> Triggers
> 
>     New Organization
>     Field Value Changes
>     New List Entry
>     New List
>     New Opportunity
>     New Person
> 
> Actions
> 
>     New Organization List Entry
>     New Opportunity List Entry
>     New Person List Entry
>     Create a Organization
>     Add a Person, Organization, or Opportunity to a List

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
