### ISSUE TITLE
[Action] TestMonitor - Create a new Test Result

### ISSUE THREAD

**Issue by MadTinker** [PipedreamHQ/pipedream#13990]
**Is there a specific app this action is for?**
TestMonitor API

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.testmonitor.com/#tag/Test-Results/operation/PostTestResult

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Action-TestMonitor-Create-a-new-Test-Result-153bf548bb5e810ab7adf8ef40031ce9

Hi @vunguyenhung, You should get the URL from links, not endpoints. Endpoints are used by APIs.
![image](https://github.com/user-attachments/assets/f2fc0b52-51d9-44c9-9fd8-e409f1fe2b0c)
