### ISSUE TITLE
Zoho WorkDrive [APP]

### ISSUE THREAD

**Issue by camcodirect** [PipedreamHQ/pipedream#1400]
Zoho WorkDrive is Zoho's cloud drive product. It is a major component of the Zoho ecosystem and is highly extensible. 

[WorkDrive API Docs](https://writer.zohopublic.com/writer/published/ankqibdb934759c6446bca8899b2f426428fc)

**Comment by todsac** [comment]
@camcodirect - Here is a first version.  Please let us know if there are an issues or additional scopes needed. 

Here are the scopes we used:
- WorkDrive.files.CREATE
- WorkDrive.files.READ
- WorkDrive.files.UPDATE
- WorkDrive.files.DELETE
- WorkDrive.team.READ
- WorkDrive.workspace.CREATE
- WorkDrive.workspace.UPDATE
- WorkDrive.workspace.DELETE
- ZohoSearch.securesearch.READ

**Comment by camcodirect** [comment]
Amazing. Looks great!
