### ISSUE TITLE
[APP] Pushsafer

### ISSUE THREAD

**Issue by appzer** [PipedreamHQ/pipedream#1404]
Hello,

how i can add the push-notification service pushsafer.com in pipedream?

API description:
https://www.pushsafer.com/en/pushapi

Kevin

**Comment by dylburger** [comment]
Thanks for raising @appzer . We’ll take a look at this integration ASAP!

**Comment by todsac** [comment]
Appzer - we have added an initial Pushsafer integration.  Please confirm this works for you.

https://pipedream.com/apps/pushsafer

**Comment by appzer** [comment]
Hi, thanks for integration, but there are some errors. Please use the code below:

```
return await require("@pipedreamhq/platform").axios(this, {
  url: 'https://www.pushsafer.com/api',
  params: {
    "k": '${auths.pushsafer.private_key}',
    "d": '${auths.pushsafer.device}',
    "t": 'Title',
    "m": 'Message',
  },
})
```

It is possible that user can add more parameters to the code above by themselve?

f.e.

```
return await require("@pipedreamhq/platform").axios(this, {
  url: 'https://www.pushsafer.com/api',
  params: {
    "k": '${auths.pushsafer.private_key}',
    "d": '${auths.pushsafer.device}',
    "t": 'Title',
    "m": 'Message',
    "i": '12',
    "c": '#FF0000',
    "s": '5',
  },
})
```

**Comment by todsac** [comment]
The base test request is just meant to demonstrate a working API call.  You can author and submit any actions you want to our marketplace and can, of course, modify the code yourself for your own use cases.

See documentation for actions - https://pipedream.com/docs/components/quickstart/nodejs/actions/

**Comment by appzer** [comment]
thanks a lot

**Comment by appzer** [comment]
the api endpoint is wrong!
Please change from https://www.pushsafer.com/api-m to https://www.pushsafer.com/api

**Comment by todsac** [comment]
Updated. Please let me know if this is all set.

**Comment by appzer** [comment]
thanks a lot, now everything fits
