### ISSUE TITLE
[Components] highergov

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14050]
# highergov
## URLs
- https://docs.highergov.com/import-and-export/api
#### Prompt
Emit new event when a pursuit is added to the pipeline. No required or optional props for configuration.
#### URLs
- https://docs.highergov.com/import-and-export/zapier-integration#subscribe
- https://docs.highergov.com/import-and-export/zapier-integration#unsubscribe

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-highergov-10bbf548bb5e81fbba7deb06c83b1166

Hi @vunguyenhung, the api-key description from account creation was wrong, please create a new one and try again.

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-highergov-10bbf548bb5e81fbba7deb06c83b1166

Hi @vunguyenhung, you will no longer receive webhooks on 1pw account because the trial has ended and the starter plan has no integrations.

**Comment by luancazarine** [comment]
Hi @vunguyenhung. You must go to 'opportunities', select an item from the list and choose a pipeline at the top right of the screen. Notifications will appear in the bottom right corner and the source will be triggered.

![image](https://github.com/user-attachments/assets/ced0ee9b-0e64-4bb7-b985-d3d2b99eb48b)
![image](https://github.com/user-attachments/assets/07437f25-9ba3-440e-820e-113a5076bd59)
![image](https://github.com/user-attachments/assets/daf90c62-2ec3-4afb-a75b-e165c0b0a0c6)
![image](https://github.com/user-attachments/assets/b1ebba19-8e18-49b1-b189-4409e43d4ccb)
![image](https://github.com/user-attachments/assets/0f8c4876-7a0b-428d-96c7-4d6607749d08)
