### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14072]
### App
Github
https://docs.github.com/en/rest

### Sources
I would expect to see "A pull request was approved", "A pull request has requested changes", "A pull request has received a new comment" in here. Those are pretty fundamental events on a Github PR.

### Actions
Various

**Comment by dep** [comment]
Slack thread for context:

https://pipedream-users.slack.com/archives/CPTJYRY5A/p1727177232788109

![image](https://github.com/user-attachments/assets/8d6997c5-5579-4a60-a2a0-c9b2b1d105b5)
