### ISSUE TITLE
[ACTION] Assign / remove role from discord user

### ISSUE THREAD

**Issue by sirloinofbeef** [PipedreamHQ/pipedream#1407]
I would love to be able to assign / remove roles from discord users.

**Comment by dylburger** [comment]
@sirloinofbeef Thanks for the request. Did you know that you could [create your own actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [publish them](https://pipedream.com/docs/components/guidelines/) for any Pipedream user to use? You can find a number of other example actions [in the `components/` directory of this repo](https://github.com/PipedreamHQ/pipedream/tree/master/components). 

Would you be interested in developing this? We're happy to help with any questions. If not, we can add this to our backlog.

**Comment by hawkeone** [comment]
As much as I would love to develop it, it's a bit beyond my abelites.

**Comment by sirloinofbeef** [comment]
As much as I would like to develop it, it's a beyond my abilities sorry.

**Comment by dylburger** [comment]
This should be addressed by #1439
