### ISSUE TITLE
[Components] Newer Loops.so Components

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#14081]
**Name of app / service**

Loops.so

**Link to developer documentation**

https://loops.so/docs/api-reference/intro

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Yes, they support Make and Zapier but not Pipedream.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

- [ ] Contacts
  - [ ] Create
  - [ ] Update
  - [ ] Find
  - [ ] Delete
- [ ] List Mailing Lists
- [ ] Send Event
- [ ] Send Email
- [ ] List Custom Fields

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the request @johndbritton , There is a base integration for Loops.so https://pipedream.com/apps/loops-so

I am triaging for component development.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
