### ISSUE TITLE
[APP] Buffer

### ISSUE THREAD

**Issue by mboveiri** [PipedreamHQ/pipedream#1411]
**Name of app / service**

Buffer 

**Link to developer documentation**

https://buffer.com/developers/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

cause it's a gateway for publish to popular social networks (Facebook,Instagram,Linkedin,..), it can be shortcut for that before original apps gets ready.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by todsac** [comment]
"As of October 14th, 2019, Buffer no longer supports the registration of new developer applications."

We would be happy to add but don't see a path to get an application approved.  Do you know anyone there?
