### ISSUE TITLE
[APP] Parsera

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#14127]
**Name of app / service**
https://parsera.org

**Link to developer documentation**
https://docs.parsera.org/api/getting-started/
https://docs.parsera.org/api/proxy/

**Comment by sergio-eliot-rodriguez** [comment]
Hi @marcelocecin thanks for the request.

Here's a base integration ready for Parsera -- https://pipedream.com/apps/parsera
