### ISSUE TITLE
[TRIGGER] New Epic Creation In Gitlab

### ISSUE THREAD

**Issue by teveteam** [PipedreamHQ/pipedream#14128]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

The event of creating a new epic in Gitlab.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

Link to epics API documentation (deprecated)
https://docs.gitlab.com/ee/api/epics.html

Link to Work Items API documentation
https://handbook.gitlab.com/handbook/engineering/architecture/design-documents/work_items/

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
