### ISSUE TITLE
[FEATURE] Ability to clone existing actions

### ISSUE THREAD

**Issue by krampepampe** [PipedreamHQ/pipedream#1412]
**Is your feature request related to a problem? Please describe.**
Some APIs like hunter.io do not offer bulk requests which basically means that I have to create multiple actions for each request. But to add a new action involves some time.

**Describe the solution you'd like**
Would be great to be able to just copy existing actions

**Do you have a workaround?**
Add new actions.

**Comparable features in other tools?**
I think in zapier it is possible

**Additional context**

**Comment by dylburger** [comment]
@krampepampe we're tracking the ability to duplicate any step (which would cover actions) at #597, so I'm closing this (this issue will be linked to that one) so that we can track in one place.
