### ISSUE TITLE
[Components] helpspot

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14147]
# helpspot
## URLs
- https://support.helpspot.com/index.php?pg=kb.book&id=6
#### Prompt
Emit new event when a new request is created. No required props.
#### URLs
- https://support.helpspot.com/index.php?pg=kb.page&id=163#customer.getRequests
#### Prompt
Emit new event based on a search. Required props include the search query.
#### URLs
- https://support.helpspot.com/index.php?pg=kb.page&id=163#customer.getRequests
#### Prompt
Emit new event when a request is updated. Required props include the request ID.
#### URLs
- https://support.helpspot.com/index.php?pg=kb.page&id=163#customer.getRequests
#### Prompt
Updates an existing user request. Required props include xRequest id, which is needed to identify the specific request that needs to be updated.
#### URLs
- https://support.helpspot.com/index.php?pg=kb.page&id=163#customer.getRequests
- https://support.helpspot.com/index.php?pg=kb.page&id=163#request.update
#### Prompt
Creates a new user request. At least one of the following props is needed; first name, last name, user id, email, or phone. These provide identification details for the request.
#### URLs
- https://support.helpspot.com/index.php?pg=kb.page&id=163#request.create

**Comment by luancazarine** [comment]
Hi @vunguyenhung, I couldn't reproduce the error. I created a new request with Id 12422 and the source triggered the new request

![image](https://github.com/user-attachments/assets/66dc0228-5ef7-41a8-9834-f5c5b9f8362c)
![image](https://github.com/user-attachments/assets/7511e66e-e1e3-4598-ab7b-c4c5a2cc2e6d)

**Comment by luancazarine** [comment]
Hi @vunguyenhung I created a new source in your workspace 
![image](https://github.com/user-attachments/assets/300471dc-fc52-4a12-9a10-2b1306745676)
Then I created two new requests with Ids: 12434 and 12435
![image](https://github.com/user-attachments/assets/03a3ae7d-7487-4629-b21b-f6187da8f6c2)
And they are there in the source
![image](https://github.com/user-attachments/assets/295aa463-18a8-4e32-863d-befb5b3c715f)
