### ISSUE TITLE
[FEATURE] Make the env var editing modal bigger

### ISSUE THREAD

**Issue by n-h-n** [PipedreamHQ/pipedream#1414]
**Is your feature request related to a problem? Please describe.**
I'm probably abusing environment variables, but sometimes I like to stick an entire JSON map in an env var to parse in the code to an actual object. However the editing pane for it is kind of annoying since it expects a short environment variable. I'm aware of env var character limits and don't anticipate to hit it, but still need a medium-sized JSON map without having to scroll a limited editing pane.

**Describe the solution you'd like**
Could you make the editing modal bigger?

**Do you have a workaround?**
Yeah, I can scroll for now. It's a visual thing.

**Comparable features in other tools?**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/26447704/126213199-75c030c3-13e0-4ed4-97bd-061a6467885e.png)

**Comment by dylburger** [comment]
Noted, thanks for the request @n-h-n

**Comment by dylburger** [comment]
You should now be able to click and drag the text box to increase its area. See screenshot below:

<img width="753" alt="Screen Shot 2022-02-22 at 12 14 47 PM" src="https://user-images.githubusercontent.com/242668/155211746-232c7459-37af-46b7-a19a-bfa92dfced26.png">

**Comment by n-h-n** [comment]
🎉 🥂 thanks @dylburger and Pipedream team
