### ISSUE TITLE
OVERLEDGER - ADDITIONAL ACTIONS REQUEST

### ISSUE THREAD

**Issue by philbuuza** [PipedreamHQ/pipedream#14150]
Hello Pipedream Team,

We are from Quant Network, the creators of Overledger. First, we want to express our appreciation for the integration of Overledger into Pipedream—it has been an incredibly useful tool for us and others working with multi-chain interoperability.

We would like to propose an enhancement to the current Overledger component in Pipedream. Specifically, we are requesting the addition of actions to:

Read data from a smart contract via Overledger.
Write data to a smart contract through a transaction using Overledger.
These features would greatly enhance the utility of the integration, especially for users who rely on interacting with smart contracts across multiple blockchains.

We hope this request aligns with the goals of Pipedream, and we are more than happy to provide additional technical details or collaborate on this effort in any way.

Thank you for considering this enhancement, and we look forward to your response!

Best regards,
Phil Buuza
Blockchain Research Developer
Quant Network

**Comment by philbuuza** [comment]
Hi Pipedream  Team, thank for your reply,

I will try to give as much information about this as possible to give more clarity on what we would like implemented.

As part of our Third party integrations at Quant we have Zapier and Make have created an OVERLEDGER integration and have them in out developer docs explaining what each offers:

Zapier
Github - https://github.com/quantnetwork/overledger-zapier-app-user-guide
Dev docs quant - https://developers.quant.network/docs/using-overledger-on-make-copy
Actions:
1- Reading data -
2- Monitoring data

Make:
GitHub - https://github.com/quantnetwork/overledger-make-app-user-guide
Dev doc quant - https://developers.quant.network/docs/using-overledger-on-make
Actions:
1- Reading data
2-Monitoring data
3-Writing data 

 these are predominantly no code. We would like to add Pipedream to this list and like the low code/custom code options your platform offers the user as it allows for a richer developer experience if needed. 

The Make integration as above has the ability to read, monitor and write data to  to blockchains. Currently on the pipedream you can monitor data  (new contract event or account transactions) and we would like the ability to read data from a smart contract as well as writing data (sign transactions). You seems to have the prepare smart contract tranx:

(https://github.com/PipedreamHQ/pipedream/blob/master/components/overledger/actions/prepare-smart-contract-transaction/prepare-smart-contract-transaction.mjs)  

and execute signed transactions:

 (https://github.com/PipedreamHQ/pipedream/blob/master/components/overledger/actions/execute-signed-transaction/execute-signed-transaction.mjs) 

prebuilt actions but we would like the sign a transaction action added to complete the Prepare-sign-execute pattern of overledger:

https://developers.quant.network/docs/pattern-prepare-sign-execute.

Here is our developer docs API reference on singing transactions:

https://developers.quant.network/reference/sandboxsigning


Please feel free to get in touch for anythinf further and look forward to what your take/solution to this will be

kind regars
Phil

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
