### ISSUE TITLE
Nile

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14154]
### App
Nile
https://www.thenile.dev/docs/reference/api-reference

### Sources
New user added

### Actions
Create new user? Not sure what else

**Comment by sergio-eliot-rodriguez** [comment]
@dannyroosevelt i started looking into this but for now i'm getting error accessing the api. i will get back to this troubleshoot this later

now, not sure if you are interested in an integration using the db client with node.js? this is a separate programming interface to work directly with a Nile database.  https://www.thenile.dev/docs/getting-started/languages/node This should be a great app for the SQL editor built into Pipedream. Please let me know if you'd like this too be integrated as a separate app. 
here is an screenshot of nile's node.js sdk accessing data via a pd workflow:
![image](https://github.com/user-attachments/assets/011e1479-12c1-4640-90e9-f543226b1a3e)

**Comment by dannyroosevelt** [comment]
Yea that makes sense to me, and ideally we can add support for `executeQuery()` and `getSchema()`:
https://pipedream.com/docs/components/guidelines#database-components

**Comment by sergio-eliot-rodriguez** [comment]
Base integration for Nile Database https://pipedream.com/apps/nile-database is ready.

**Comment by michelle0927** [comment]
I haven't been able to list or create users through the Nile API due to internal server errors. I've contacted their support, and I created a separate issue for the "Create User" and "New User Added" components. https://github.com/PipedreamHQ/pipedream/issues/14222

I was able to create the "Execute Query" action using the SQL Prop, and created a PR for that action. https://github.com/PipedreamHQ/pipedream/pull/14223

**Comment by sergio-eliot-rodriguez** [comment]
@michelle0927 i am in touch with the Nile team too. This is the explanation they game me:

> I'm sorry for the friction here. Let me try to clarify some things: 


> First, Nile has both "developers" and "users".
> Developers are Nile's customers. They are the ones creating databases and building applications that uses these databases. 
> Users are our customers' customers. They use the applications that the developers build. Users can access some APIs (like creating and listing tenants), but they can't create databases or query them directly (they always go through applications that developers built). 

I then, to make sure I understood, came up with an scenario where a developer creates a Learning Management System app, where each instance of this LMS app will have its own users. They then clarified my analogy and provided examples for the user things:

> Small correction to the LMS scenario: When a developer sells LMS to a customer, they will typically create a new tenant and new users for that customer within an existing, multi-tenant, database on Nile. This can be done by the developer (or their sales team), or it can be a self serve part of the app. You can try our live examples (such as https://nextjs-quickstart-niledatabase.vercel.app/) to get a sense of what its like - you will create a user, and then create tenants all in the app, and can access data for the tenants you created. 

So I'd say check out the example meanwhile I need to upgrade the app to OAuth 2.0 I have it on my list will get to this Asap.

**Comment by dannyroosevelt** [comment]
> I then, to make sure I understood, came up with an scenario where a developer creates a Learning Management System app, where each instance of this LMS app will have its own users. They then clarified my analogy and provided examples for the create user part:
> 
> >

So it sounds like we should make sure to configure the app for Pipedream as the developer. Is that what OAuth will enable, @sergio-eliot-rodriguez ?

**Comment by sergio-eliot-rodriguez** [comment]
yes, on the OAuth 2.0 piece they explained we will be able to create credentials

> Option 2: Use OAuth2 to get authorized access to act as the developer. 
> This isn't yet documented, but .... you get back a token that you can then use with developer APIs (list databases, create database, create credentials). With these credentials, you can access any database that the developer owns.

**Comment by sergio-eliot-rodriguez** [comment]
that will issue an access token, the access token can be used to create credentials (a.ka. create users, be the API). This must be the jwt that appears in their documentation but they don't mention where to get it.
