### ISSUE TITLE
Gainsight

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14208]
### App
Gainsight
https://support.gainsight.com/PX/API_for_Developers#Available_APIs_and_SDKs

**Comment by sergio-eliot-rodriguez** [comment]
This is a base integration for Gainsight PX, the product for which the API documentation was provided: https://pipedream.com/apps/gainsight-px 
@malexanderlim had an account.

Switching to Gainsight NXT, which is the product obtained by @dylburger via the demo.

**Comment by sergio-eliot-rodriguez** [comment]
Base integration for Gainsight NXT (was named as "Gainsight" in plain)
https://pipedream.com/apps/gainsight-nxt
