### ISSUE TITLE
ChurnZero

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14209]
### App
ChurnZero
https://churnzero.com/features/rest-api/

**Comment by dylburger** [comment]
When we asked to build the integration, ChurnZero's team said:

> We do allow customers to interact with our API for data syncing and automation. However, when it comes to native integrations, our dev/product team has a stance currently to build those in-house. This approach ensures consistency in the user experience, maintains the quality of our platform, and aligns with our customer demand-driven roadmap.

We're closing this ticket as a result. If you're a ChurnZero customer and need this integration, please reach out to their team directly.
