### ISSUE TITLE
[Components] Docnify

### ISSUE THREAD

**Issue by rickafds** [PipedreamHQ/pipedream#14201]
**Name of app / service**
Docnify
**Link to developer documentation**
https://docnify.io
**Is lack of support preventing you from building workflows, or do you have a workaround?**
I need this in the my workflow
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
