### ISSUE TITLE
[ACTION] Create a New Link - Add folderID parameter

### ISSUE THREAD

**Issue by raphaelvarieras** [PipedreamHQ/pipedream#14216]
Add support for folderID in the current link creation action.
Ref: https://github.com/PipedreamHQ/pipedream/issues/1305

**Is there a specific app this action is for?**
Short.io

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.short.io/reference/post_links

**Comment by raphaelvarieras** [comment]
Sure - the issue is that selecting the folder ID in which the short link is created is not an available option int the action as it is today. The request here is to add it.

**Comment by raphaelvarieras** [comment]
Hi! How long before it's released, typically?

**Comment by malexanderlim** [comment]
@raphaelvarieras , typically, it is released within the day that it is QA'd - sorry that this one slipped by!
