### ISSUE TITLE
[Components] attio

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14210]
# attio
## URLs
- https://developers.attio.com/reference
#### Prompt
Emit new event when a record, like person, company, or deal, is added to a list. Props required: list id.
#### URLs
- https://developers.attio.com/reference/webhooks-list-entrycreated
#### Prompt
Emit new event when new record, such as person, company or deal gets created. Props required: record type.
#### URLs
- https://developers.attio.com/reference/webhooks-recordcreated
#### Prompt
Emit new event when values on a record, like person, company or deal, get updated. Props required: record id, record type, and attributes to monitor.
#### URLs
- https://developers.attio.com/reference/post_v2-webhooks
#### Prompt
Creates or updates a specific record such as a person or a deal. If the record already exists, it's updated. Otherwise, a new record is created. Required props include 'record type' and 'record ID'. An optional prop could be 'record attribute'.
#### URLs
- https://developers.attio.com/reference/patch_v2-objects-object
#### Prompt
Creates a new note for a given record. The note will be linked to the specified record. Required props are 'note content' and 'record ID'. An optional prop could be 'note title'.
#### URLs
- https://developers.attio.com/reference/post_v2-notes
#### Prompt
Deletes an existing entry from a specific list. The targeted list entry will be removed. Required props are 'list ID' and 'entry ID'. There are no optional props for this action.
#### URLs
- https://developers.attio.com/reference/delete_v2-lists-list-entries-entry-id

**Comment by dannyroosevelt** [comment]
This is blocked until our OAuth app is approved, will comment here when that happens.

**Comment by dannyroosevelt** [comment]
> This is blocked until our OAuth app is approved, will comment here when that happens.

FYI @michelle0927 our app should be live and working now

**Comment by sergio-eliot-rodriguez** [comment]
Getting this notifications in my email (3 so far):

<html><body>

Hi Sergio,
--



</body>
</html>Hi Sergio,

We're having trouble delivering data to a webhook associated with your Attio account. Webhooks are used to notify your server about events that happen in your Attio account, such as an entry changing status in a kanban view.

The failing webhook endpoint is:
https://d4f7ad222d2045408068d3854d7252e9.m.pipedream.net/

We've attempted to notify the endpoint and received an invalid response. If this endpoint is important to your integrations, please fix the issue. If you don't need the webhook endpoint, an admin can delete it from your Attio developer settings.

You need to return anything between a HTTP 200 to 299 for the webhook to be considered successfully delivered.

For more details on the errors, please refer to the [developer documentation](https://developers.attio.com/docs/using-webhooks?utm_source=postmark&utm_medium=email&utm_campaign=webhook_degraded#webhooks).
This email is the last time we will reach out to you before disabling the webhook. If we don't receive a successful response from the webhook within the next 7 days then it will be permanently disabled.

Thanks,

The Attio Team
