### ISSUE TITLE
adafruit io

### ISSUE THREAD

**Issue by Guy1224** [PipedreamHQ/pipedream#14227]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
There is a base integration for Adatafuit IO at our app store: https://pipedream.com/apps/adafruit-io

are there any components trigger or actions that you need for your use case?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
