### ISSUE TITLE
[APP] ngrok.com

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#14239]
**Name of app / service**
ngrok.com

**Link to developer documentation**
https://ngrok.com/docs/api/#quickstart
https://github.com/ngrok/ngrok-api-python

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the request @marcelocecin 
We rolled out a base integration for ngrok: https://pipedream.com/apps/ngrok
