### ISSUE TITLE
[APP] HelpScout

### ISSUE THREAD

**Issue by ajedwards** [PipedreamHQ/pipedream#1425]
**Help Scout**
https://developer.helpscout.com/

> This is an HTTPS-only API and it uses OAuth 2.0 authorization, implementing Authorization Code and Client Credential flows.

Lack of support is preventing me from building maintainable production workflows.

Particularly interested in these triggers and actions:

- Conversation Created, Conversation Status Updated, Conversation Customer Reply & Agent Reply triggers
- Create Customer, Update Customer, Create Conversation, and Update Conversation actions.

**Comment by todsac** [comment]
@ajedwards - here is a first version of the integration.  please let us know if this works for you - https://pipedream.com/apps/helpscout.

Are you interested in adding the [actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)?

**Comment by ajedwards** [comment]
Hey many thanks Tod. The new integration is working great, although it looks like you misspelled '**Help Scout**' as "Helpscout"?

I am interested in adding the actions and sources, nut not sure when I will find the time.

**Comment by todsac** [comment]
Ok, I will update the name.  Note that the nameslug will need to change from helpscout to help_scout.  I will let you know when it is updated.

**Comment by todsac** [comment]
FYI - this has been updated and the nameslug has been changed.  Please update your workflow.  Also, let me know if I can close this issue out.

**Comment by ajedwards** [comment]
Awesome. Thanks Tod. Appreciate your prompt help with this 🙂 

Happy to close it out.

**Comment by petros** [comment]
Hi, is Help Scout still available as an APP? I am trying to find it here and I cannot:

<img width="951" alt="CleanShot 2022-04-08 at 10 21 59" src="https://user-images.githubusercontent.com/28818/162385020-237dbdb2-8aad-4844-8771-10e926d26d23.png">

Is it only available for actions maybe?
