### ISSUE TITLE
[FEATURE] Pipedream IPs for PostgreSQL Access (for whitelist)

### ISSUE THREAD

**Issue by vignesh8458** [PipedreamHQ/pipedream#1426]
Hello Team,

I am using PostgreSQL for the database. I would like to whitelist the Pipedream IPs for accessing the PostgreSQL server database due to security reasons.

Can you please share the pipedream IPs?

**Comment by dylburger** [comment]
Hi @vignesh8458 , currently we don't have a fixed set of outbound IPs for DB traffic, but we're tracking that in #178 if you'd like to follow.

In the meantime, take a look at [these docs](https://pipedream.com/docs/workflows/networking/#non-http-traffic-databases-etc) for some suggested workarounds. 

Let me know if that helps. Thanks!
