### ISSUE TITLE
[BUG] Smartsuite - Connection popup Test Connection button failed with not found error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14280]
**Describe the bug**
I have this Smartsuite account setup as in the image below
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/f87e0743-f78c-4106-a8b4-ed21a69bf6ea">

Then I setup the API Key and Account ID to Pipedream connection poup
![image](https://github.com/user-attachments/assets/34cf5585-cd98-436b-927f-8e36e7620165)

Then I click the Test Connection button, it throws not found error
![image](https://github.com/user-attachments/assets/edb430e6-9c5f-4fc2-b5e8-6b0daa5cc9f0)

Save the connection anyway and test the action, they still works
![image](https://github.com/user-attachments/assets/2be98ae7-5869-4ca9-b8dd-346f06913522)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
