### ISSUE TITLE
[APP] runpod.io

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#14290]
**Name of app / service**
https://runpod.io

**Link to developer documentation**
https://docs.runpod.io/sdks/overview
https://github.com/runpod/js-sdk
https://github.com/runpod/runpod-python
https://github.com/runpod/go-sdk

**Comment by sergio-eliot-rodriguez** [comment]
Hi @marcelocecin thanks for the request.

a base integration for RunPod has been published: https://pipedream.com/apps/runpod
