### ISSUE TITLE
[FEATURE] Chargify (Maxio) - Improve connection popup to add instructions for Subdomain and API Key

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14297]
**Is your feature request related to a problem? Please describe.**
The current Chargify API connection popup does not have instruction for user to input `subdomain` and `api_key`. It leads to the API Doc - which is not user-friendly
![image](https://github.com/user-attachments/assets/3635da8d-929d-441a-824b-1e3c5c4fd3c0)

**Describe the solution you'd like**
Add the following instructions:
- Subdomain: Subdomain is the first part of your Chargify URL. For example, if your Chargify URL is `https://pipedreamdev.chargify.com/`, then your subdomain is `pipedreamdev`
- API Key: You can generate the API Key by accessing Left Side Bar > Config > Integrations > New API Key

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
