### ISSUE TITLE
[BUG] Formcarry - Test Connection button throws error 502

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14299]
Steps to reproduce:
I create a new account in Form carry and copy the API key in the image as below
![image](https://github.com/user-attachments/assets/b14a1b0b-bdc6-414d-b8da-f3beb2a678bd)
Then I setup the API key to Pipedream connection popup
![FireShot Capture 013 - New Source - Pipedream - pipedream com](https://github.com/user-attachments/assets/8ec7e614-0c2c-4fdf-a517-e46429b05221)
Then I click the Test connection button, it throws 502 error\
![image](https://github.com/user-attachments/assets/76bb7175-74bd-4df1-ab76-2431fd135e4a)
I save the connection anyway and it still work
![image](https://github.com/user-attachments/assets/6274425a-969e-45b2-a994-e4938b2524dc)
Expected behavior:  The test connection button should work correctly

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
