### ISSUE TITLE
[ACTION] Slack new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1429]
**Is there a specific app this action is for?**
Slack

**Please provide a link to the relevant API docs for the specific service / operation.**
https://api.slack.com/apis

**Find User by Name** | Find a user by matching against their real name
**Find User by Username** | Find a user by their username
**Set Channel Topic** | Set the topic on a selected channel
**Add Reminde**r | Add a reminder for yourself or a teammate
**Update Profile** | Update basic profile field such as name or title
**Set Status** | Set your Slack status to the given text and emoji
**Invite User to Channel** | Invite an existing user to an existing channel
**Find Message** | Find a Slack message
**Find User by Email** | Find a user by matching against their email
**Find User by Id** | Find a user by their ID
**Get Public Channel Message** | Return a message with a given ID from a specified public channel
**Get Private Channel Message** | Return a message with a given ID from a specified private channel
**Update Message** | Update a message
**Delete Message** | Delete a message
**List Replies** | Retrieve a thread of messages posted to a conversation
**List Channels** | Return a list of all channels in a workspace
**List Members in Channel** | Retrieve members of a channel
**Get Channel** | Return information about a workspace channel
**Archive Channel** | Archive a channel
**Unarchive Channel** | Unarchive a channel
**Set Purpose of Channel** | Change the purpose of a channel
**Join Channel** | Join an existing channel
**Leave Channel** | Leave a channel
**List Files** | Return a list of files within a team
**Get File** | Return information about a file
**Download File** | Download a file
**Upload File** | Upload a file
**Create Text File** | Create a text file
**Delete File** | Delete a file
**List Users** | Return a list of all users in a workspace
**Kick User** | Remove a user from a channel
**Add Star** | Add a star to an item on behalf of the authenticated user
**Remove Star** | Remove a star from an item on behalf of the authenticated user
**List Reminders** | List all reminders for a given user
**Get Reminder** | Return information about a reminder
**Complete Reminder** | Complete a reminder
**Create Reminder** | Create a reminder
**Delete Reminder** | Delete a reminder

**Comment by michelle0927** [comment]
Related issue for new Slack event sources: https://github.com/PipedreamHQ/pipedream/issues/1010
These two issues should be completed together.

**Comment by masonwoodford** [comment]
Hello do you need any help implementing the slack actions?

**Comment by dylburger** [comment]
@masonwoodford yes, we’d love help implementing these. 

You can take a look at our [action development quickstart](https://pipedream.com/docs/components/quickstart/nodejs/actions/) for an overview of how actions work. Take a look at the `components/` directory in this repo to see some example actions. 

Let me know if you have any questions and we’re happy to help.

**Comment by masonwoodford** [comment]
Should all of these actions and all of the event sources in #1010 be submitted as one pr or are you tackling this piece meal?

**Comment by dylburger** [comment]
Generally I’ll submit all of the components for an app in a single PR, but you can create as many components as you have time for and just submit a PR when you’re ready.

**Comment by masonwoodford** [comment]
Ok thanks!

**Comment by masonwoodford** [comment]
For the actions that return things how should that be formatted? Currently it is being returned in a format like this:
![Screenshot (269)](https://user-images.githubusercontent.com/63433735/126884609-521939af-847c-435b-b6ea-2cd6b01ef2af.png)

**Comment by dylburger** [comment]
That response format looks fine, thanks for asking. You may have already seen, but [these are the component guidelines](https://pipedream.com/docs/components/guidelines/#guidelines-patterns) we review on pull requests.
