### ISSUE TITLE
[Components] imagior

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14295]
# imagior
## URLs
- https://docs.imagior.com/
#### Prompt
Emit new event when a new template is created. No additional props required.
#### URLs
- https://docs.imagior.com/getting-started/create-design-template
- https://docs.imagior.com/getting-started/generate-api-key
- https://docs.imagior.com/api-reference/image-generate
- https://docs.imagior.com/api-reference/retrieve-all-templates
- https://docs.imagior.com/api-reference/retrieve-template-elements
#### Prompt
Generates a unique and robust image using a provided template. Required props include 'template_id' to specify the template to be used. Optional props include 'image_parameters' to customize the appearance of the image. This action is reliant solely on the Imagior platform.
#### URLs
- https://docs.imagior.com/getting-started/generate-api-key
- https://docs.imagior.com/getting-started/first-api-call
- https://docs.imagior.com/api-reference/image-generate
- https://docs.imagior.com/api-reference/retrieve-all-templates
- https://docs.imagior.com/api-reference/retrieve-template-elements
- https://docs.imagior.com/api-reference/retrieve-basic-template-elements

**Comment by michelle0927** [comment]
@vunguyenhung The screenshot of the generate-image action in the report above shows the "Update" button in the top right. You may need to click "Update" to test the most recent version.
