### ISSUE TITLE
OpenAI - Add audio functionality to Chat action

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14327]
### App
OpenAI
https://openai.com/index/introducing-the-realtime-api/

### Actions
This is a request to update chat completion workflow to accept audio input, as that is now supported

**Comment by Stvad** [comment]
> Audio in the Chat Completions API will be released in the coming weeks, as a new model gpt-4o-audio-preview. With gpt-4o-audio-preview, developers can input text or audio into GPT-4o and receive responses in text, audio, or both.

Looking at model options rn, I can select `gpt-4o-audio-preview` model, but not supply the audio as an input

**Comment by malexanderlim** [comment]
@Stvad , it looks like the API documentation in chat completions has not been updated to include audio yet - as soon as it is ready and documented, we will update the chat completions action. Thanks!
https://platform.openai.com/docs/api-reference/chat/create

**Comment by Stvad** [comment]
It seems like they updated it, the link you posted now mentions audio and links out to https://platform.openai.com/docs/guides/audio?audio-generation-quickstart-example=audio-in

**Comment by malexanderlim** [comment]
Awesome - we'll be sure to get the Chat action updated with the audio functionality! Thank you for flagging @Stvad.
