### ISSUE TITLE
[Components] smstools

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14370]
# smstools
## URLs
- https://www.smstools.com/en/sms-gateway-api
#### Prompt
Emits new event when a new inbound message was received. This trigger scans the system for new inbound SMS, acting as a prop. No input is required. Good for building responses to inbound messages.
#### URLs
- https://www.smstools.com/en/sms-gateway-api/get_inbox_all
#### Prompt
Adds a new contact to an existing contact list. Required props include 'phone' and 'groupId' which group id has async opts from groups. The optional props are 'firstname', 'lastname', 'birthday', 'extra1 to extra8' and 'unsubscribed'
#### URLs
- https://www.smstools.com/en/sms-gateway-api/get_groups
- https://smstools.com/en/sms-gateway-api/add_contact
#### Prompt
Adds a contact to the opt-out list, stopping further communications. Required prop is 'contact', which has async props from contacts.
#### URLs
- https://www.smstools.com/en/sms-gateway-api/get_all_contacts
- https://www.smstools.com/en/sms-gateway-api/add_optout
#### Prompt
Sends a SMS or Whatsapp message to a specified contact. Required props are 'message', 'to' and 'and 'sender', which the prop 'to' has async props from contacts and 'sender' has async props from sender ids. The optional props are 'date', 'reference', 'test' and 'subid' which subid has async props from sub accounts
#### URLs
- https://www.smstools.com/en/sms-gateway-api/list_sub
- https://www.smstools.com/en/sms-gateway-api/get_senderids
- https://www.smstools.com/en/sms-gateway-api/get_all_contacts
- https://www.smstools.com/en/sms-gateway-api/send_message

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-smstools-129bf548bb5e81ed9760cf4e2b0ee13d

Hello @vunguyenhung, as far as I understand, incoming message is when you receive a message from a recipient, not when you send it.
