### ISSUE TITLE
[Components] enrichley

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14387]
# enrichley
## URLs
- https://enrichley.readme.io/reference/getting-started-with-your-api
#### Prompt
Checks the validity of a single email address using enrichley's specific algorithm. It requires a 'email' prop that needs to be supplied with a valid email string. Note: the verification through enrichley is not 100% foolproof, there may be some false-positive or false-negative results but it helps reduce such scenarios significantly
#### URLs
- https://enrichley.readme.io/reference/validatesingleemail
- https://enrichley.readme.io/reference/getapikeydetails

**Comment by sergio-eliot-rodriguez** [comment]
@michelle0927 Enrichley got back to us and they added some cretis to the account:
