### ISSUE TITLE
[ACTION] Twitter new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1438]
**Is there a specific app this action is for?**
Twitter

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developer.twitter.com/en/docs/twitter-api

**Create Tweet** | Create a tweet
**Add User to List** | Add user to list
**Search Users** | Find information about a specific user
**Update Profile Image** | Updates your profile images
**Send a Message** | Sends a new direct message to a selected user
**List Messages** | Returns all direct messages within the last 30 days. Sorted in reverse chronological order
**Get a Message** | Returns a single direct message by ID
**Delete a Message** | Deletes the direct message by ID
**List User Tweets** | Return a collection of the most recent tweets posted by a user
**Get User Tweet** | Return a single tweet specified by ID
**Delete Tweet** | Remove a posted tweet
**List Retweets** | Return a collection of up to 100 recent tweets or user IDs belonging to users who have retweeted the tweet by ID parameter
**Retweet/Unretweet Tweets** | Retweet or untweet a tweet and return the original tweet with retweet details embedded
**List Followers** | Return a collection of user objects for users following the specified user
**List Likes** | Return the most recent tweets liked by you or the specified user
**Like/Unlike Tweet** | Like or unlike the tweet specified specified in the ID parameter
**List Lists** | Return all lists the authenticated or specified user subscribes to including their own
**List Mentions** | Return the 20 most recent mentions for the authenticated user
**Get User** | Return information about the user specified by ID or screen name parameter
**List Pending Followers Requests** | Return a collection of numeric IDs for every user who has a pending request to follow the authenticated user

**Comment by dannyroosevelt** [comment]
@michelle0927 are you actively working on this?

**Comment by michelle0927** [comment]
I got stuck on the Update Profile Image action, and then got busy with other things. I’ve completed the other actions. Shall I create a PR for those?

**Comment by dannyroosevelt** [comment]
Yep that sounds great! Thanks Michelle
