### ISSUE TITLE
[ACTION] Discord Bot new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1439]
**Is there a specific app this action is for?**
Discord Bot

**Please provide a link to the relevant API docs for the specific service / operation.**
https://discord.com/developers/docs

**Rename Channel** | Rename a channel to a specified name you choose
**Remove User Role** | Remove a chosen role from the specified user
**Add Role** | Assign a role to a user
**Find Channel** | Find an existing channel by name
**Find User** | Find an existing user by name
**Create Guild Channel** | Create a new channel for the guild
**Create Channel Invite** | Create a new invite for the channel
**Modify Channel** | Update a channel's settings
**Delete Channel** | Delete a Channel
**List Channel Invites** | Return a list of invitees for the channel
**List Channels** | Return a list of channels
**List Guild Members** | Return a list of guild members
**List Users that Reacted with Emoji** | Return a list of users that reacted with a specified emoji

**Comment by dylburger** [comment]
Work in progress: https://github.com/PipedreamHQ/pipedream/pull/1689

**Comment by michelle0927** [comment]
These are a few additional actions for Discord Bot. They were originally listed under Discord Webhook, but actually belong here.
**Get Message** | Return a specific message in a channel
**Delete Message** | Delete a message
**List Channel Messages** | Return the messages for a channel
**Post Reaction with Emoji** | Post a reaction for a message with an emoji

**Comment by dylburger** [comment]
This is done!
