### ISSUE TITLE
Beaconchain

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14414]
### App
Beaconchain
https://pipedream.com/@beaconchain/invite?toke--monitoring-endpoint 'https://beaconcha.in/api/v1/client/metrics?apikey=JDJhJDEwJGpvNTVLS1o5&machine=BSC'n=1f152be11b45629d85028335c2942ff9

### Sources
https://pipedream.com/@beaconchain/invite?toke--monitoring-endpoint 'https://beaconcha.in/api/v1/client/metrics?apikey=JDJhJDEwJGpvNTVLS1o5&machine=BSC'n=1f152be11b45629d85028335c2942ff9

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated: https://pipedream.com/apps/beaconchain
