### ISSUE TITLE
[APP]Instagram

### ISSUE THREAD

**Issue by daoqub** [PipedreamHQ/pipedream#14418]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the request @daoqub 
We are tracking Instagram at #445 , feel free to follow there, if you'd like.
