### ISSUE TITLE
WawMart

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14429]
### App
WawMart
http://foursquare.com/user/593037826

### Sources
X-CODE

### Actions
Airtable.com

**Comment by sergio-eliot-rodriguez** [comment]
The WawMart page at Foursquare provided as the app URL links to WawMart facebook page, which is borken, and to X/Twitter page which list about a singer.

Airtable.com is integrated at https://pipedream.com/apps/airtable-oauth
and X-CODE is a IDE by APple that doesn't seem an app to be integrated with Pipedream.

Closing this but if you believe this is an error let us know.
