### ISSUE TITLE
Zoho Desk

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14420]
### App
Zoho Desk

### Summary:
After accepting the scopes in the oauth workflow, pipedream returns an error.

### Details:
After accepting the scopes in the oauth workflow, pipedream returns an error. This is happening with multiple zoho desk accounts. I have reached out to Zoho support as well but they're requiring logs from the pipedream side.

### Screenshots:

![Screenshot](https://storage.tally.so/private/pipedreamerror.jpg?id=D7lpXR&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkQ3bHBYUiIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcyOTc3NzAzMH0.vge8wopPqDKfCJ2NUSoHWzLn2Cl5EmVD5qVKi6iEZno&signature=3fde9cc0334cc4f96f079c5cb92d833f04da7970861456b678f8f795f1944214)

**Comment by malexanderlim** [comment]
This was due to an outage on the Zoho side - have reached back out to the reporting customers and they were successfully able to reconnect.
