### ISSUE TITLE
[ACTION] OpenAI - Vector Store and Vector Store Files actions

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14432]
**Is there a specific app this action is for?**
OpenAI

**Please provide a link to the relevant API docs for the specific service / operation.**
Please implement actions following the APIs in OpenAI Vector Stores and Vector Store Files
- https://platform.openai.com/docs/api-reference/vector-stores
- https://platform.openai.com/docs/api-reference/vector-stores-files

Including:
- Create, List, Retrieve, Delete Vector Stores
- Create, List, Retrieve, Delete Vector Store Files

Requested by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1729751670031259

**Comment by yqup** [comment]
So cool to see the professionalism and speed of the Pipedream team.. Thank you
