### ISSUE TITLE
[APP] BigDataCorp

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#14434]
**Name of app / service**
bigdatacorp

**Link to developer documentation**
https://docs.bigdatacorp.com.br/plataforma/docs/bem-vindo
https://docs.bigdatacorp.com.br/plataforma/reference/health-check-pessoas

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pd, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the request @marcelocecin 
BigDataCorp has now a base integration: https://pipedream.com/apps/bigdatacorp
