### ISSUE TITLE
[ACTION] Google Calendar new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1444]
**Is there a specific app this action is for?**
Google Calendar

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.google.com/calendar/api/v3/reference

**Quick Add Event** | Create an event from a piece of text. Google parses the text for date, time, and description info
**Create Detailed Event** | Create an event by defining each field
**Update Event** | Update an event
**Add Attendees to Event** | Invite one or more persons to an existing event
**Delete Event** | Delete an event
**Create Calendar** | Create a new calendar
**Find Event** | Find an event in your calendar. Optionally, create one if none are found
**Get Event** | Return metadata for an event
**List Calendars** | Return the calendars on the user's calendar list
**Get Calendar** | Return metadata for a calendar
**Update Calendar** | Update an existing calendar
**Delete Calendar** | Delete a calendar
**Clear Calendar** | Clear a primary calendar. Deletes all events associated with the primary calendar of an account
**List Access Control Rules** | Return the rules in the access control list for a calendar
**Get Access Control Rule** | Return metadata of an access control rule
**Create Access Control Rule** | Create a new access control rule
**Update Access Control Rule** | Update an existing access control rule
**Delete Access Control Rule** | Delete an access control rule
**Get Free/Busy Information** | Return free/busy information for a set of calendars

**Comment by aggmoulik** [comment]
Hi @michelle0927 If this issue is not taken, I would love to work on the issue. For ease, can you assign this issue to me ?

**Comment by michelle0927** [comment]
@aggmoulik Thanks for taking this on! If you haven't already, take a look at the documentation about creating actions in Pipedream. And feel free to reach out in Slack with any questions.
https://pipedream.com/docs/components/actions/#creating-your-own-actions

**Comment by aggmoulik** [comment]
Should I add all the actions in one PR ?

**Comment by michelle0927** [comment]
@aggmoulik If you can add all the actions in one PR, that'd be great, but anything you can contribute is appreciated. You'll want to create the actions locally and then publish them to your account through the Pipedream CLI to test them. This Quickstart guide has some instructions and examples to help get started.

**Comment by aggmoulik** [comment]
Hey @michelle0927 I want to confirm about the action update event as this is kinda looks generalised, should I give every parameter to whatever they want to.

**Comment by michelle0927** [comment]
@aggmoulik I like to use Zapier.com as a reference. Take a look at their Update Event action for Google Calendar and make sure to include at least the parameters that they do. For optional parameters, remember to use `optional: true` and include a default value if appropriate.

**Comment by dannyroosevelt** [comment]
Hey @aggmoulik are you still actively working on this PR? Let us know when you're ready for a review so we can get these actions live!

**Comment by dannyroosevelt** [comment]
Whoever picks this up -- I'm not sure the current state of the PR, so please go ahead and review and implement the suggested changes.

**Comment by dannyroosevelt** [comment]
@jcortes this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
