### ISSUE TITLE
[FEATURE] Jira - Add `Override existing webhooks` optional prop to all sources

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14440]
**Is your feature request related to a problem? Please describe.**
Jira only allow one webhook at a time
![image](https://github.com/user-attachments/assets/d2122702-1b2f-47c3-bb97-5c692016e2f3)

Though Jira does not offer the UI for users to manually delete webhooks. Hence, users are usually blocked if they see the error above.

**Describe the solution you'd like**
Add the optional prop `Override existing webhooks` to delete all existing webhook before creating a new Pipedream source.
Details:
- label: Override existing webhooks
- type: boolean
- default: false
- description: Override existing webhooks with this new Pipedream source's webhook. Recommend to set this to `True` if you have an existing Jira webhook that you no longer use and want to override with the new Pipedream source.

**Do you have a workaround?**
No

**Additional context**
Raised by a customer here: https://app.frontapp.com/open/cnv_ogxxarr?key=1WP31Azp-LejRZjHQYrptAcdBGZIYtVE

**Comment by michelle0927** [comment]
Blocked while waiting on additional scopes.
