### ISSUE TITLE
[APP] E2B

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#14449]
**Name of app / service**
https://e2b.dev

**Link to developer documentation**
https://e2b.dev/docs/quickstart

**Comment by sergio-eliot-rodriguez** [comment]
THis now has a base integration https://pipedream.com/apps/e2b

**Comment by malexanderlim** [comment]
@marcelocecin , we shipped the integration along with a preconfigured action to Run Code within the E2B sandbox. Can you share how you intend to use the E2B integration now that it is live, so we can better understand the use case and ensure that the integration and action is what you're looking for?

**Comment by marcelocecin** [comment]
@malexanderlim Hi Michael, I haven't developed any projects yet. I found the platform interesting, so I opened the issue.
