### ISSUE TITLE
[APP]  NinjaOne

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14448]
### App
NinjaOne
https://app.ninjarmm.com/apidocs/?links.active=core#/

**Comment by lanceretter** [comment]
also, here's their beta documentation https://app.ninjarmm.com/apidocs-beta/core-resources - might be easier to read

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pd, michael@pd, integrations@pd

**Comment by lanceretter** [comment]
What's the comment mean? Were we able to add the integration?

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim is this a good case for the "Non official OAuth"  https://app.ninjarmm.com/apidocs/?links.active=authorization ?

**Comment by malexanderlim** [comment]
@sergio-eliot-rodriguez I've reached out to their API team to request access to an account for development - will update on this thread with the progress.
