### ISSUE TITLE
Apple Reminders

### ISSUE THREAD

**Issue by bgrnaymane** [PipedreamHQ/pipedream#14457]
**Apple Reminders**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the request  @bgrnaymane .
Would you mind sharing the API documentation for Apple Reminders?
I'm assuming this app website is: https://www.icloud.com/reminders

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
