### ISSUE TITLE
[BUG] Checkvisit - Test Connection button failed

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14495]
**Describe the bug**
Test Connection button failed when creating source

**To Reproduce**
1. I tried to generate a new token
![i1](https://github.com/user-attachments/assets/949a6d37-dbc3-4ff4-8699-dff85585f5ff)

2. I am unable to connect
![image (1)](https://github.com/user-attachments/assets/1e41ccfe-3e86-4c60-a4df-660ee37e54c7)

3. I tried to save the account and actions work nicely

![image (2)](https://github.com/user-attachments/assets/43760927-c715-43f8-8aac-bb644195c8fc)

**Comment by malexanderlim** [comment]
Thanks for flagging, @vunguyenhung - this is fixed!
