### ISSUE TITLE
[TRIGGER] Google Sheets: any cell change

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#145]
I'd like a trigger that emits a new event each time a new cell is added / updated, with the details of the update.

**Comment by todsac** [comment]
New Spreadsheet Row | Triggered when a new row is added to the bottom of a spreadsheet.
New or Updated Spreadsheet Row | Triggered when a new row is added or modified in a spreadsheet.

I have read that you may want to break out these triggers for Team drive:
New Spreadsheet Row (Team Drive) | Triggered when a new row is added to the bottom of a spreadsheet
New or Updated Spreadsheet Row (Team Drive) | Triggered when a new row is added or modified in a spreadsheet

Others?

**Comment by michelle0927** [comment]
New Spreadsheet Row | Triggered when a new row is added to the bottom of a spreadsheet (works with User Drives & Team Drives).
Uses Method: spreadsheets.get 
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get

New or Updated Spreadsheet Row | Triggered when a new row is added or modified in a spreadsheet (works with User Drives & Team Drives).
Uses Method: spreadsheets.values.get
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get

Both use Google Drive API webhooks to watch for changes.
Method: changes.watch
https://developers.google.com/drive/api/v3/reference/changes/watch
Method: changes.list
https://developers.google.com/drive/api/v3/reference/changes/list
