### ISSUE TITLE
[Components] ignisign

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14570]
# ignisign
## URLs
- https://ignisign.io/docs/category/ignisign-api
#### Prompt
Emit new event when a signature proof is generated. No props required.
#### URLs
- https://ignisign.io/docs/ignisign-api/add-webhook-endpoint
- https://ignisign.io/docs/ignisign-api/check-webhook-event-token
- https://ignisign.io/docs/ignisign-api/remove-webhook-endpoint
- https://ignisign.io/docs/webhooks/signatureProof
#### Prompt
Creates a new signer entity in Ignisign. Props required: 'signerProfileId' and 'firstName' (the name of the signer), 'email' (the email of the signer). Optional prop: 'externalId', 'lastName', 'phoneNumber', 'nationality', 'birthDate', 'birthPlace' and 'birthCountry'.
#### URLs
- https://ignisign.io/docs/ignisign-api/get-signer-profiles
- https://ignisign.io/docs/ignisign-api/create-signer
#### Prompt
Initiates a document signature request through Ignisign. Required props: 'documentId' (the unique identifier for the document to be signed), 'signerId' (the unique identifier of the signer).
#### URLs
- https://ignisign.io/docs/core-concepts/Signature_Requests
- https://ignisign.io/docs/ignisign-api/init-signature-request
- https://ignisign.io/docs/ignisign-api/get-paginate-application-signers
- https://ignisign.io/docs/ignisign-api/init-document
- https://ignisign.io/docs/ignisign-api/update-signature-request
- https://ignisign.io/docs/ignisign-api/publish-signature-request
#### Prompt
Retrieves a proof file for a specific signature. Required props: 'signRequestId' (the identifier of the signature request you want to get the proof for). This action returns a proof file that can be used to verify the signature.
#### URLs
- https://ignisign.io/docs/ignisign-api/check-document-authenticity

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-ignisign-138bf548bb5e81ddb795cf68335640bd

Hi @vunguyenhung. The title prop is not duplicated, this is a UI bug, when a prop has the optional field removed, this happens. just click on the title below and it will disappear.
