### ISSUE TITLE
[ACTION] MySQL new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1457]
**Is there a specific app this action is for?**
MySQL

**Please provide a link to the relevant API docs for the specific service / operation.**
https://www.npmjs.com/package/mysql2

**New Row** | Adds a new row
**Update Row** | Updates an existing row
**Find Row** | Finds a row in a table via a lookup column
**Execute Query** | Find row(s) via a custom query 
**Delete Row** | Delete an existing row
**Execute Stored Procedure**

**Comment by dannyroosevelt** [comment]
This is ready for release!
