### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by Armand40700** [PipedreamHQ/pipedream#14599]
**Name of app / Twitter**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @Armand40700 Thanks for the request,
Twitter is technically integrated but it has been hidden probably because of changes on API terms due to its acquisition.
Please check later on:
https://pipedream.com/apps/twitter
