### ISSUE TITLE
adafruit

### ISSUE THREAD

**Issue by THIRUMALAIFOOTWEARS** [PipedreamHQ/pipedream#14591]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @THIRUMALAIFOOTWEARS thank you for your request?
Can you share more about your use case? What trigger and actions do you need for your use case?
we have a base integration for Adafruit at https://pipedream.com/apps/adafruit-io

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
