### ISSUE TITLE
[TRIGGER] Slack - New User

### ISSUE THREAD

**Issue by albandum** [PipedreamHQ/pipedream#14596]
We want to trigger a welcome message to new Slack users

**Comment by Jetoson** [comment]
@albandum can I work on this?

**Comment by albandum** [comment]
Hi, of course :D

**Comment by malexanderlim** [comment]
Hi @Jetoson , we appreciate your desire to contribute for this component - however, this one specifically would be better developed internally as it touches some parts of our codebase, e.g. `apphooks` which are not documented. Please feel free to pick up another ticket from the board, though!

@albandum  - I've added this one to the board to be prioritized.

**Comment by malexanderlim** [comment]
To component devs:

Webhook event: `team_join` - confirmed that this is currently supported by the apphook.
https://api.slack.com/events/team_join
