### ISSUE TITLE
[Components] Share components between monday.com apps

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#14603]
We created a new OAuth app for monday.com - this request is to port the existing components for the API key implementation over from `monday` (api key) to the new `monday_oauth` (oauth) app.

In order to test this, please ping @malexanderlim and I will share a link to install the app.

**Comment by malexanderlim** [comment]
Hey @vunguyenhung - please ping me and we can pair on this - I'm not able to reproduce this specific error when using my own custom oauth client, and would like to dig in on the exact flow that is breaking here.

**Comment by michelle0927** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Share-components-between-monday-com-apps-13bbf548bb5e81ee9225e80771dc6271

Hi @vunguyenhung. Can you verify that the Monday app you're connecting with has the following [scopes](https://developer.monday.com/apps/docs/oauth)?
- updates:read
- updates:write
- webhooks:read
- webhooks:write

**Comment by malexanderlim** [comment]
Hi @vunguyenhung , @michelle0927 and I were not able to reproduce this behavior. Can you ping me when you're online and we can pair and take a look at this one together?
