### ISSUE TITLE
[ACTION] Loops.so - Add to Mailing List

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#14614]
**Is there a specific app this action is for?**

Loops.so

**Please provide a link to the relevant API docs for the specific service / operation.**

The "Create Contact" action should support sending the optional `mailingLists` property. The values of that property need to be fetched from the Loops.so API.

Additionally, there should probably be an action to add a contact to a mailing list.

**Comment by johndbritton** [comment]
It should also be possible to set all of these properties from the "Create Contact" action:
<img width="511" alt="Screenshot 2024-11-08 at 1 35 14 PM" src="https://github.com/user-attachments/assets/2a82131a-0eaf-429f-80bf-d9457c73cde3">

**Comment by praneeth622** [comment]
Hi @johndbritton , here’s a summary of the solution for the "Create Contact" action with support for the `mailingLists` property in Loops.so.

### Solution Overview
The "Create Contact" action in Loops.so enables you to add a new contact with various configurable properties, including optional support for associating the contact with specific mailing lists. 

### Supported Properties for `Create Contact`
The following fields are available when creating a contact:
- **Last Name (`lastName`)**: The contact's last name.
- **Email (`email`)**: The contact's email address (required).
- **Notes (`notes`)**: Any additional information about the contact.
- **Source (`source`)**: Identifies the origin of the contact, e.g., `"API"`.
- **User Group (`userGroup`)**: Specifies the group to which the contact belongs.
- **User ID (`userId`)**: A unique identifier for the contact.

### Example JSON Payload
```json
{
  "email": "example@example.com",
  "lastName": "Doe",
  "notes": "Important client",
  "source": "API",
  "userGroup": "premium_users",
  "userId": "12345"
}
```

### Mailing Lists Support
The `mailingLists` property allows for optional inclusion of mailing lists to which the contact should be subscribed. This property is available in the Loops.so API.

### Relevant Documentation Links
- [API Introduction](https://loops.so/docs/api-reference/intro)
- [Create Contact Documentation](https://loops.so/docs/api-reference/create-contact)
- [Mailing Lists Management](https://loops.so/docs/quickstart)

This setup should provide flexibility for adding and managing contacts, including support for associating them with mailing lists. Please let me know if there are any other requirements!

**Comment by johndbritton** [comment]
I understand that the property is available in the API, however in the Pipedream UI for the Create Contact action it's not possible to specify arbitrary parameters, unless I'm missing something.
