### ISSUE TITLE
binance

### ISSUE THREAD

**Issue by Riadh000** [PipedreamHQ/pipedream#14612]
**binance / trading panel **

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Duplicate request, we are tracking Binance #5368 
@Riadh000 is "Trading Panel" a separte applicafrom from Binance, if so can you please share the website.? or is "trading panel" an area, or part of Binance?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
