### ISSUE TITLE
[ACTION] Apollo.io - People Enrichment

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#14615]
**Is there a specific app this action is for?**

Apollo.io

**Please provide a link to the relevant API docs for the specific service / operation.**

The People Enrichment action doesn't have full support for all of the parameters listed here: https://docs.apollo.io/reference/people-enrichment

In particular, I would like to use the `linkedin_url` parameter.

**Comment by Appilot-dev** [comment]
We made  a reddit bot in 2024 but it functions through your phone remotely with a web dashboard no ADB or wire needed, a reddit karma bot that mimics human behavior through a learning script for the bot that shadows top Reddit's contributor for that week and manages an account of reddit.


The same can be done for the platform of your choice automating post scheduling of top LinkedIn professionals in your industry

You can check it's commenting features and how we made it happen in our [Git's repository](https://github.com/Appilot-dev/Reddit-Android-Karma-Farming-Bot)

How you can control the bot’s speed and never get banned again.

**Comment by praneeth622** [comment]
Hi @johndbritton ,

To address your query about alternative documentation or a clearer explanation regarding the `linkedin_url` parameter in the Apollo.io People Enrichment API, here’s a more detailed look into the issue and some resources that may help clarify things further.

### Overview of Apollo.io API

Apollo.io offers a comprehensive API that helps users enrich contact data, manage leads, and automate various aspects of sales workflows. The **People Enrichment** endpoint specifically allows you to retrieve detailed information about individuals based on parameters like name, email, or LinkedIn URL.

### Key Parameters in People Enrichment

When interacting with the API, you can use the following key parameters to enrich your data:

- **id**: Unique identifier for the person in Apollo's database.
- **first_name**: First name of the person.
- **last_name**: Last name of the person.
- **name**: Full name of the person.
- **linkedin_url**: URL of the person's LinkedIn profile.
- **title**: Job title of the person.
- **email_status**: Email verification status.
- **photo_url**: URL for the person's photo.
- **employment_history**: Array with the person's previous employment roles.

### Understanding `linkedin_url`

The `linkedin_url` parameter is intended to enhance contact enrichment by linking a person's LinkedIn profile to other data points. While the Apollo.io documentation may not fully explain all its potential uses or limitations, this parameter is typically included in API requests to retrieve enriched data.

### Alternative Documentation and Resources

1. **Apollo REST API Overview**:
   This article provides general guidance on how to configure and use Apollo's API, including examples for several endpoints, authentication, and request formatting.
   - [Apollo REST API Documentation](https://knowledge.apollo.io/hc/en-us/articles/4416173158541-Use-the-Apollo-REST-API)

2. **Pipedream Integrations**:
   Pipedream offers an integration platform that works with Apollo.io. Their documentation provides practical examples of using the Apollo API within workflows, which might offer further insight into how the `linkedin_url` parameter can be used in different contexts.
   - [Apollo.io on Pipedream](https://pipedream.com/apps/apollo-io)

3. **API Testing with Postman**:
   Testing your API requests in Postman can help you experiment with different parameters, including `linkedin_url`, and observe how the API responds. This can help clarify its behavior and limitations.

By leveraging these resources and guidelines, you should have a better understanding of how to utilize the Apollo.io People Enrichment API, especially in relation to the `linkedin_url` parameter.

Let me know if you need further clarification or assistance!

Citations:
[1] [Apollo People Enrichment Docs](https://docs.apollo.io/reference/people-enrichment)
[2] [Apollo REST API Overview](https://knowledge.apollo.io/hc/en-us/articles/4416173158541-Use-the-Apollo-REST-API)
[3] [Apollo.io on Pipedream](https://pipedream.com/apps/apollo-io)

**Comment by johndbritton** [comment]
I understand the parameter and the API. This issue is because the "People Enrichment" action in Pipedream doesn't allow specifying all of the parameters available in the API, like `linkedin_url`.

<img width="569" alt="Screenshot 2024-11-11 at 1 05 24 PM" src="https://github.com/user-attachments/assets/ce9ff19c-f47f-4f3f-9e36-a498a54de8c5">
