### ISSUE TITLE
[ACTION] Stripe new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1462]
**Is there a specific app this action is for?**
Stripe

**Please provide a link to the relevant API docs for the specific service / operation.**
https://stripe.com/docs/api

Payment Intents ([guide](https://stripe.com/docs/payments/payment-intents), [reference](https://stripe.com/docs/api/payment_intents))

- [x] **List Payment Intents** | Retrieves a list of payment intents or filters by customer ID
- [x] **Create a Payment Intent** | Creates a payment intent
- [x] **Retrieve a Payment Intent** | Retrieves the details of a payment intent that has previously been created
- [x] **Confirm a Payment Intent** | Confirms a payment intent by its ID. Upon confirmation, the payment intent will attempt to initiate a payment
- [x] **Capture a Payment Intent** | Captures an existing uncaptured payment intent by its ID
- [x] **Update a Payment Intent** | Updates the specific payment intent by setting the values of the parameters passed
- [x] **Cancel a Payment Intent** | Cancels a payment intent by its ID. For payment intents with status 'requires capture' the remaining capturable amount will automatically be refunded

[Customers](https://stripe.com/docs/api/customers)

- [x] **List Customers** | Retrieves a list of customers filtered by criteria
- [x] **Create a Customer** | Creates a new customer object
- [x] **Retrieve a Customer** | Retrieves the details of an existing customer
- [x] **Update a Customer** | Updates the specified customer by setting the values of the parameters passed
- [x] **Delete a Customer** | Permanently delete a customer. It cannot be undone

Refunds ([guide](https://stripe.com/docs/refunds), [reference](https://stripe.com/docs/api/refunds))

- [x] **List All Refunds** | Returns a list of all refunds you've previously created
- [x] **Create a Refund** | Creates a new refund
- [x] **Retrieve a Refund** | Retrieves the details of an existing refund
- [x] **Update a Refund** | Updates the specified refund by setting the values of the parameters passed

Payouts ([guide](https://stripe.com/docs/payouts), [reference](https://stripe.com/docs/api/payouts))

- [x] **List All Payouts** | Returns a list of existing payouts sent to third-party bank accounts or that Stripe has sent you
- [x] **Create a Payout** | To send funds to your own bank account, you create a new payout object
- [x] **Cancel a Payout** | Cancels a previously created payout
- [x] **Retrieve a Payout** | Retrieves the details of an existing payout
- [x] **Update a Payout** | Updates the specific payout by setting the values of the parameters passed

Balance ([guide](https://stripe.com/docs/connect/account-balances), [reference](https://stripe.com/docs/api/balance))

- [x] **Retrieve Balance** | Retrieves the current account balance
- [x] **List All Balance History** | Returns a list of transactions that have contributed to the Stripe account balance
- [ ] ~~**Retrieve a Balance Transaction** | Retrieves the balance transaction with the given ID~~

Invoices ([guide](https://stripe.com/docs/invoicing/sending), [reference](https://stripe.com/docs/api/invoices))

- [x] **Search Invoices** | Retrieves a list of invoices filtered by criteria
- [ ] ~~**List All Invoice Line Items** | Retrieves a list of invoice line items by the invoice ID~~
- [x] **Create an Invoice** | Creates a new invoice by the customer ID
- [x] **Retrieve an Invoice** | Retrieves the details of an existing invoice with the given ID
- [x] **Update an Invoice** | Updates the specified invoice by setting the values of the parameters passed
- [x] **Finalize a Draft Invoice** | Finalizes a draft invoice by its ID
- [x] **Void or Delete an Invoice** | Permanently deletes a draft invoice, or voids a finalized or subscription invoice with the given ID. This cannot be undone
- [x] **Write off Invoice** | Write off an uncollectible invoice
- [ ] ~~**Search Invoice Items** | Retrieves a list of invoice items filtered by criteria~~
- [x] **Create an Invoice Item** | Creates a new invoice item to be added to a draft invoice
- [x] **Retrieve and Invoice Item** | Retrieves the details of an existing invoice item with a given ID
- [x] **Update an Invoice Item** | Updates the specified invoice item by setting the values of the parameters passed
- [x] **Delete an Invoice Item** | Permanently delete an invoice item which is not attached to invoices, or if it's attached to a draft invoice

Checkout Sessions ([guide](https://stripe.com/docs/payments/checkout), [reference](https://stripe.com/docs/api/checkout/sessions))

- [x] **Retrieve a Checkout Session** | Retrieve a details of a checkout session and all of it's line items with the given ID

Prices ([guide](https://stripe.com/docs/billing/prices-guide), [reference](https://stripe.com/docs/api/prices))

- [x] **Retrieve a Price** | Retrieves the details of a price with the given ID

Metered Billing ([guide](https://stripe.com/docs/billing/subscriptions/metered-billing), [reference](https://stripe.com/docs/api/usage_records))

- [x] **Create a Usage Record** | Creates a usage record for a specified subscription item and date, and fills it with a quantity

**Comment by whatbuylists** [comment]
For this request: #1546, please add support for:
1. Retrieving a product's metadata after a trigger of either:
- checkout.session.completed
- Credit card has been charged

or, please support the following sequence of actions after trigger=checkout.session.completed:
1. Retrieve a session from the payment_intent ID returned by checkout.session.completed and expand its line items to get price ID
        https://stripe.com/docs/api/checkout/sessions/line_items or,
        https://stripe.com/docs/api/checkout/sessions/retrieve
        https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-line_items-data-price

2. Retrieve a product and its metadata using the price ID from the previous step
        https://stripe.com/docs/api/prices/retrieve

Thanks!
