### ISSUE TITLE
[Components] zoho-books

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14645]
# zoho-books
#### Prompt
Emit new event when a new customer is created. No additional props are necessary to set.
#### Prompt
Emit new event when a new expense is created. The user needs to set the expense category as a required prop.
#### Prompt
Emit new event when a new sales invoice is generated. Required props include the product/item and the customer receiving the invoice.
#### Prompt
Initiates the creation of a new estimate. Requires props including customer name and estimate details.
#### Prompt
Allows the search of an existing invoice. Requires an invoice ID as a prop to locate the specific invoice.
#### Prompt
Initiates the creation of a new customer. Requires props such as customer name and contact details.

**Comment by malexanderlim** [comment]
Awaiting Zoho Webhook documentation

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-zoho-books-150bf548bb5e8156b239cec3f6465a4b

Hi @vunguyenhung 
Just one point
- Improvement needed - Invoice Number & Date props description are incorrect

I'm not sure exactly what this description means but it's right
![image](https://github.com/user-attachments/assets/9b3b830c-f00a-4290-8880-c7382ada3fb6)

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-zoho-books-150bf548bb5e8156b239cec3f6465a4b

Hi @vunguyenhung, I'm sorry but I couldn't reproduce the error
