### ISSUE TITLE
Zoho Books

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14644]
### App
Zoho Books

### Summary:
Zoho Books greyed out in integration list

### Details:
We have premium on our account, but I'm not able to configure triggers for Zoho Books, it won't let me select it in the integration list.

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-11-13-142433.png?id=qVY2L8&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InFWWTJMOCIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTczMTUyNTkxMX0.iqVmZkoeHae59k7of5GFaBX_F2vG6QPX46kkbvkCwKU&signature=d3d4e4c85c3e29468bc3c06ee71e7cb16a930e40445f6ba728cd6dd87d529e5c)

**Comment by malexanderlim** [comment]
No triggers are currently available for Zoho Books. These should be available pending https://github.com/PipedreamHQ/pipedream/issues/14645 - please follow the Github issue for tracking.
