### ISSUE TITLE
[ACTION] Firebase/Firestore new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1464]
**Is there a specific app this action is for?**
Firebase Admin SDK

**Please provide a link to the relevant API docs for the specific service / operation.**
https://firebase.google.com/docs/reference/admin

**Create a Document** | Creates a new document
**List Documents** | Lists documents in a collection
**Update a Document** | Updates or inserts a document
**Create or Replace Firebase Realtime Database Record** | Creates or replaces a child object within your Firebase Realtime Database

**Comment by dannyroosevelt** [comment]
@michelle0927 this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
