### ISSUE TITLE
[ACTION] MongoDB new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1465]
**Is there a specific app this action is for?**
MongoDB

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.atlas.mongodb.com/api/

**Create a New Document** | Create a new document in a collection of your choice
**Delete a Document** | Delete a single document by ID
**Insert a Document** | Insert a new document into the database
**Retrieve a Document** | Retrieves a single document by ID
**Update a Document** | Updates a single document by ID
**Search Documents** | Search for specific documents or return all documents

**Comment by vellames-turing** [comment]
Hey @michelle0927 . What's the difference between "Create a New Document" and "Insert a Document"?

**Comment by michelle0927** [comment]
> Hey @michelle0927 . What's the difference between "Create a New Document" and "Insert a Document"?

I think the difference is that Zapier calls the action "Create a New Document", and Integromat calls it "Insert a Document". :) I don't have a MongoDB set up to test them, but from what I can tell, they do the same thing. I'd say just disregard one, and call the other one whatever you think will be clearest to the user.
