### ISSUE TITLE
[BUG] Html_to_image 0 - Test connection failed

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14659]
**Describe the bug**
I put the correct API Key and click the Test Connection button, though it failed with the following error
![image](https://github.com/user-attachments/assets/64786355-edc4-47a8-b81b-f2589b051e46)

Maybe we can use another API not requiring credit to test. If there's no such API, kindly close the ticket 🙏

**Comment by malexanderlim** [comment]
Confirmed that this is working now.
