### ISSUE TITLE
[APP] xAI

### ISSUE THREAD

**Issue by justinr1234** [PipedreamHQ/pipedream#14666]
**Name of app / service**

xAI

**Link to developer documentation**

https://docs.x.ai/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**

No, but I don't know how to share the api key in a pipedream team way

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Nope, just need the auth really

**Comment by sergio-eliot-rodriguez** [comment]
Base integration at: https://pipedream.com/apps/x-ai
