### ISSUE TITLE
[ACTION] Mailchimp new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1467]
**Is there a specific app this action is for?**
Mailchimp

**Please provide a link to the relevant API docs for the specific service / operation.**
https://mailchimp.com/developer/marketing/api/

**Search Campaigns** | Searches for the campaigns
**Get a Campaign** | Gets metadata of a specific campaign
**Get a Campaign Report** | Gets a campaign report
**Create a Campaign** | Creates a new campaign
**Update a Campaign** | Updates an existing campaign
**Perform a Campaign Action** | Performs a campaign action
**Edit a Campaign Template Content** | Edits a defined content area of a custom HTML template
**Delete a Campaign** | Deletes a campaign
**Search Subscribers** | Searches for the subscribers
**Get a Subscriber** | Gets metadata of a subscriber by email
**Add/Update a Subscriber** | Adds an email address to a subscriber list
**Edit a Subscriber** | Edits an existing subscriber
**Delete a Subscriber** | Archives or permanently deletes a subscriber
**Search Lists** | Searches for the lists
**Get a List** | Gets metadata of a specified list
**Create a List** | Creates a new list
**Update a List** | Updates an existing list
**Delete a List** | Deletes a list
**Lists Segment Members** | Retrieves a list of all segment members
**Add a Member to a Segment** | Adds a new member to a static segment
**Remove a Member from a Segment** | Removes a member from the specified static segment
**List List's Activities** | Retrieves up to the previous 180 days of daily detailed aggregated activity stats for a list
**List List Members' Activities** | Get the last 50 events of a member's activity on a specific list
**List Member Tags** | Retrieves a list of all member tags
**Add/Remove Member Tags** | Adds or removes tags from a list member
**Add Subscriber to Tag** | Add an email address to a tag within an audience. Note: the email address must already be subscribed to the audience
**Remove Subscriber from Tag** | Removes an existing subscriber by email address from a tag within an audience. Note: the email address must already be subscribed to the audience
**Send Campaign** | Sends a campaign draft. PLEASE NOTE: This action sends an email to everyone signed up to the Campaign
**Add Note to Subscriber** | Adds a new note to an existing subscriber
**Create a Custom Event** | Creates a custom event for an existing subscriber
**Find Customer** | Finds a customer by an email address

**Comment by bush4u** [comment]
Done!
Search Campaigns | Searches for the campaigns
Get a Campaign | Gets metadata of a specific campaign
Get a Campaign Report | Gets a campaign report
Update a Campaign | Updates an existing campaign
Perform a Campaign Action | Performs a campaign action - Not found
Edit a Campaign Template Content | Edits a defined content area of a custom HTML template -To be thoroughly tested
Delete a Campaign | Deletes a campaign
Search Subscribers | Searches for the subscribers - Exist as find member
Search Lists | Searches for the lists
Get a List | Gets metadata of a specified list
Create a List | Creates a new list
Update a List | Updates an existing list
Delete a List | Deletes a list
Lists Segment Members | Retrieves a list of all segment members
Add a Member to a Segment | Adds a new member to a static segment
Remove a Member from a Segment | Removes a member from the specified static segment
List List's Activities | Retrieves up to the previous 180 days of daily detailed aggregated activity stats for a list
List List Members' Activities | Get the last 50 events of a member's activity on a specific list
List Member Tags | Retrieves a list of all member tags
Add/Remove Member Tags | Adds or removes tags from a list member
Delete a Subscriber | Archives or permanently deletes a subscriber - Done as  Delete a List Member


These exists
Create a Campaign | Creates a new campaign - Exist
Send Campaign | Sends a campaign draft. PLEASE NOTE: This action sends an email to everyone signed up to the Campaign -Exist
Add Note to Subscriber | Adds a new note to an existing subscriber - Exist
Add/Update a Subscriber | Adds an email address to a subscriber list - Exist




Cannot find These
Create a Custom Event | Creates a custom event for an existing subscriber
Find Customer | Finds a customer by an email address
Get a Subscriber | Gets metadata of a subscriber by email - Assumed to be find-member
Edit a Subscriber | Edits an existing subscriber
Add Subscriber to Tag | Add an email address to a tag within an audience. Note: the email address must already be subscribed to the audience
Remove Subscriber from Tag | Removes an existing subscriber by email address from a tag within an audience. Note: the email address must already be subscribed to the audience - Assumed to be add-remove-member-tags

Subscribers seems to be same as members.

**Comment by dannyroosevelt** [comment]
This is ready for release!
