### ISSUE TITLE
[Components] grain

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14678]
# grain
## URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9
#### Prompt
Emit new event when a highlight that matches the filter is added. No props are required. The webhook type is 'added'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Emit new event when a story that matches the filter is added.  No props are required. The webhook type is 'added'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Emit new event when a recording that matches the filter is added.  No props are required. The webhook type is 'added'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Emit new event when a highlight that matches the filter is updated. No props are required. The webhook type is 'updated'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Emit new event when a story that matches the filter is updated. No props are required. The webhook type is 'updated'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Emit new event when a recording that matches the filter is updated. No props are required. The webhook type is 'updated'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Emit new event when a highlight that matches the filter is removed. No props are required. The webhook type is 'removed'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Emit new event when a story that matches the filter is removed. No props are required. The webhook type is 'removed'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Emit new event when a recording that matches the filter is removed. No props are required. The webhook type is 'removed'.
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#5cadcc510d6c40fc9fbaf3cb3b526845
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#05d8cd1217744e33bba3ff0541bbf78e
#### Prompt
Fetches a specific recording by its ID from Grain, and optionally the transcript and intelligence notes. Required prop is recordId which has async options. Optional props may include 'transcript_format' and 'intelligence_notes_format' if the user wishes to retrieve these associated features along with the recording. Please include all optional props, and enable the user to easily select a transcript, intelligent notes format, and intelligence notes (key points, summary) 
#### URLs
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#76f9b3d8caea4b46b374191f6d9c360e
- https://grainhq.notion.site/Grain-Public-API-877184aa82b54c77a875083c1b560de9#7b7d0bf176cd44789407b14cdd879f2d

**Comment by malexanderlim** [comment]
Waiting on developer account to be linked to dev client.

**Comment by malexanderlim** [comment]
Account has been added to 1Pass.
