### ISSUE TITLE
MailerLite - Update hyperlink on connection popup

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14682]
**Is your feature request related to a problem? Please describe.**
The hyperlink on MailerLite connection poup leads to https://app.mailerlite.com/integrations/api/, which is no longer valid
![image](https://github.com/user-attachments/assets/ccf637d2-417d-4c96-9849-892588b7a3c1)

The valid link should be:
https://dashboard.mailerlite.com/integrations/api

**Additional context**
https://github.com/PipedreamHQ/pipedream/issues/14669

**Comment by malexanderlim** [comment]
Thanks for flagging @vunguyenhung - I've updated the link.
