### ISSUE TITLE
slidecart[SOURCE]

### ISSUE THREAD

**Issue by RaphaTostes** [PipedreamHQ/pipedream#1470]
Hello, i'm having a problem triyng to do a slide cart for shopify that works! If someone have some codes to help me I will be forever grateful.

**Comment by compwright** [comment]
Are you talking about this? https://apphq.co/apps/slide-cart

Can you elaborate on what you are looking for?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
