### ISSUE TITLE
OpenSea

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14722]
### App
OpenSea

### Summary:
OpenSea API Test Connection Failed

### Details:
When creating a new OpenSea Account and entering my OpenSea API Key, the Test Connection fails.
I can confirm that my OpenSea API Key is Valid and am able to successfully use the API on OpenSea's API Docs website.
See screenshots attached.  (Middle portion of API Key has been obfuscated)
Screenshot 1  (OpenSea Connection - Pipedream.png) - Pipedream OpenSea Account connection configuration
Screenshot 2 (Test Conneciton Failed - Pipedream.png)- Pipedream OpenSea Account Test Conneciton Error
Screenshot 3 ((Get NFT OpenSea.png) - OpenSea API Key successfully used to retrieve an NFT metadata

### Screenshots:

![Screenshot](https://storage.tally.so/private/OpenSea-failed---Pipedream.zip?id=oGQMeP&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im9HUU1lUCIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTczMjM5MTgyNn0.v2Du7RoTKt71eX4Hd_YeQeh-K-NGpWcNJ-ZV713dLMY&signature=fdd3b312d3978feacaecf44b124f2f9194518134d0b0d55aa7f15f899add6f0f)

**Comment by twichalot** [comment]
Proper Screenshots Attached here.
![Get NFT OpenSea](https://github.com/user-attachments/assets/02e0b810-d7d7-403e-aa4d-3f943ef835ff)
![OpenSea Connection - Pipedream](https://github.com/user-attachments/assets/141b6c54-00d8-4347-b19c-0f6831c9e020)
![Test Conneciton Failed - Pipedream](https://github.com/user-attachments/assets/fc116562-5eda-458e-8bbd-4d3da1f7212c)

**Comment by twichalot** [comment]
Thank you for the response.  I will try this soon and let you know.

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim we may need to update OpenSea's test request, components to use api version 2.

v1 was deprecated on December 2023:

> V1 Deprecation
> As of October 4th, 2023, OpenSea will cease providing ongoing support for any V1 endpoints. We understand the potential impact of the migration from V1 to V2 on those in the Web3 ecosystem, and are providing a 2-month period for applications to fully make this transition. On Decemb

See [API V2 Fully Supported](https://docs.opensea.io/changelog/api-v2-fully-supported) notice.

As of API Keys, it has to be requested
> 
> API FAQs
> How can I obtain an API Key?
> Please follow the instructions [here](https://docs.opensea.io/reference/api-keys).

OpenSea account, app was handled before we had the 1PW system, can't find it in my older app sheets in case I submitted thisone.

**Comment by malexanderlim** [comment]
@twichalot I've updated the test connection endpoint to V2 APIs - you should be able to test your connection without issues. @sergio-eliot-rodriguez thank you for flagging.

**Comment by twichalot** [comment]
> @twichalot I've updated the test connection endpoint to V2 APIs - you should be able to test your connection without issues. @sergio-eliot-rodriguez thank you for flagging.

Thank you!   The test was successful.  I appreciate the fix!
