### ISSUE TITLE
Flyin' T Bouique

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14801]
### App
Flyin' T Bouique
https://printify.com/app/account/api

### Sources
going from square to printify for my customers easliy. I would like then to access my printify store from my square account. All billing information should be directed to my square account, www.flyint.co

**Comment by sergio-eliot-rodriguez** [comment]
I filled out the Register your App form at https://developers.printify.com/#oauth-2-0 to get OAuth access.

**Comment by sergio-eliot-rodriguez** [comment]
Ok Printify is integrated: https://pipedream.com/apps/printify

can the user confirm about the required source?

Apparently when a New User is created in Printify, then n a user should be created in Square, is this correct?

So, the source to develop is.

"New User" source for the Printify app

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
