### ISSUE TITLE
[APP] Gistly

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14802]
**Name of app / service**
Gisly 

**Link to developer documentation**
https://gist.ly/youtube-transcript-api#doc

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Code actions

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
See ticket: https://github.com/PipedreamHQ/pipedream/pull/14763/files

**Comment by sergio-eliot-rodriguez** [comment]
Base integration ready
https://pipedream.com/apps/gistly
