### ISSUE TITLE
fal AI API

### ISSUE THREAD

**Issue by jaykay-git** [PipedreamHQ/pipedream#14800]
Answer: fal AI API

Answer: https://docs.fal.ai/

Answer: Yes. I will be using fal.ai for my application.  It is the most cost effective way to go.

Answer: Don't know yet what it will take to support the fal API in Pipedream because I have never used Pipedream.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @jaykay-git 

Thanks for the request. We have a base integration for Fal AI available: https://pipedream.com/apps/fal-ai?via=go

Finally, welcome to Pipedream! Happy to support you in anyway we can.
