### ISSUE TITLE
[ACTION] Upsert Records into Salesforce 

### ISSUE THREAD

**Issue by daniel-adayev-prefect** [PipedreamHQ/pipedream#14812]
[**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm)

Upsert functionality would greatly reduce compute and time required having to check if records exist in our system before pushing them in.

**Comment by GTFalcao** [comment]
@vunguyenhung not any field can be used as the external ID field, I tested this and the API returns an error. Therefore, only fields that are actually marked as an external id field can be used, and the prop filters to show only those.

A field can be created in the Salesforce interface in Object Manager, and marked as an external ID field.

**Comment by GTFalcao** [comment]
My mistake, that happened due to moving the method out of the app, to avoid having to bump all components' versions. Fixed.

**Comment by GTFalcao** [comment]
@vunguyenhung I've tested this again successfully, creating a new field with the same specifications as yours.

I believe the field you created was not marked as an external ID field - your screenshot shows the checkbox is not marked, here is the field I created:

![image](https://github.com/user-attachments/assets/28654ca6-e7d8-4a44-9035-99287bac2907)
