### ISSUE TITLE
[ACTION] Refactor Asana actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1481]
The existing component actions for Asana were programmatically converted from legacy actions and need to be refactored to use async options (and any other relevant changes).

**Is there a specific app this action is for?**
Asana

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.asana.com/docs/php

**List Tasks** \| Retrieves tasks of a workspace, project, tag or assignee
**Create a Task or Subtask** \| Creates a task or subtask
**Delete a Task** \| Deletes a task
**Add a Task to a Project** \| Adds a task to a project or section at a specific location
**Create a Project** \| Creates a project
**Update a Custom Field** \| Updates a custom field

**Comment by michelle0927** [comment]
Related issue for new Asana event sources: https://github.com/PipedreamHQ/pipedream/issues/1036
These two issues should be completed together.

**Comment by dannyroosevelt** [comment]
@lcaresia this is ready for release!

**Comment by dannyroosevelt** [comment]
@lcaresia this is ready for release!

**Comment by dannyroosevelt** [comment]
@lcaresia this is ready for release!
