### ISSUE TITLE
[ACTION] Pipedrive new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1482]
**Is there a specific app this action is for?**
Pipedrive

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.pipedrive.com/docs/api/v1/

- [x] **Create a Deal** \| Creates a deal
- [x] **Update a Deal** \| Updates a deal
- [x] **Create an Organization** \| Creates an organization
- [x] **Create a Person** \| Creates a person
- [x] **List Persons** \| Searches for persons
- [x] **Create an Activity** \| Creates an activity
- [ ] **Delete a Deal** \| Deletes a deal
- [ ] **Get a Deal** \| Returns details of a specific deal
- [ ] **List Deals** \| Searches for deals
- [ ] **List Deals in a Pipeline** \| Lists deals in a specific pipeline across all its stages
- [ ] **List Deals in a Stage** \| List deals in a specific stage
- [ ] **Add Product to a Deal** \| Adds a product to a deal
- [ ] **Update Product Attachment Details** \| Updates product attachment details of the deal-product (a product already attached to a deal)
- [ ] **Deletes an Attached Product** \| Deletes a product attachment from a deal
- [ ] **List Products in a Deal** \| List products attached to a deal
- [ ] **Add a Participant to a Deal** \| Adds a participant to a deal
- [ ] **List Persons in a Deal** \| Lists all persons associated with a deal, regardless of whether the person is the primary contact of the deal or added as a participant
- [ ] **List Files in a Deal** \| List files associated with a deal
- [ ] **List Activities in a Deal** \| Lists activities associated with a deal
- [ ] **Update an Organization** \| Updates an organization
- [ ] **Delete an Organization** \| Deletes an organization
- [ ] **Get an Organization** \| Returns the details of an organization
- [ ] **List Organizations** \| Searches for organizations
- [ ] **Update an Organization Field Value** \| Updates an organization field value
- [ ] **Update a Person** \| Updates a person
- [ ] **Delete a Person** \| Deletes a person
- [ ] **Get a Person** \| Return the details of a person
- [ ] **Create a Product** \| Creates a product
- [ ] **Update a Product** \| Updates a product
- [ ] **Delete a Product** \| Deletes a product
- [ ] **Get a Product** \| Returns data about a specific product
- [ ] **List Products** \| Searches for products
- [ ] **Create a Note** \| Creates a note
- [ ] **Update a Note** \| Updates a note
- [ ] **Delete a Note** \| Deletes a note
- [ ] **Get a Note** \| Returns details about a specific note
- [ ] **List Notes** \| Searches for notes
- [ ] **Update an Activity** \| Updates an activity
- [ ] **Delete an Activity** \| Deletes an activity
- [ ] **Get an Activity** \| Returns details of a specific activity
- [ ] **List Activities** \| Searches for activities
- [ ] **Update Mail Thread Details** \| Updates the properties of a mail thread
- [ ] **Delete a Mail Thread** \| Marks mail thread as deleted
- [ ] **Get a Mail Thread** \| Returns a specific mail thread
- [ ] **Get a Message** \| Returns data about a specific mail message
- [ ] **List Mail Threads** \| Returns mail thread in a specified folder ordered by most recent messages within
- [ ] **List Messages in a Thread** \| Get mail messages inside specified mail thread
- [ ] **Add a Follower** \| Add follower to an object of selected type (deals, organizations, persons)
- [ ] **Delete a Follower** \| Deletes a follower from a deal
- [ ] **List Followers** \| List followers of an object of selected type (deals, organizations, persons, products, users)
- [ ] **Get a User** \| Returns data about a specific user within the company
- [ ] **List Users** \| Returns data about all users
- [ ] **Upload a File** \| Lets you upload a file and associate it a deal, person, organization, activity, or product
- [ ] **Download a File** \| Downloads a file
- [ ] **List Pipelines** \| Returns data about all pipelines
- [ ] **List Stages** \| Returns data about all stages
- [ ] **Search for Items** \| Performs a search from multiple item types
- [ ] **Create Lead** \| Creates a new lead

**Comment by michelle0927** [comment]
Related issue for new Pipedrive event sources: https://github.com/PipedreamHQ/pipedream/issues/1037
These two issues should be completed together.

**Comment by dannyroosevelt** [comment]
@jcortes this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)

**Comment by dannyroosevelt** [comment]
@jcortes this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
