### ISSUE TITLE
[BUG] Ortto - Connection Popup improvement

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#14823]
**Describe the bug**
## Test Connection Button
The Ortto Test Connection button failed with error code 400
![image](https://github.com/user-attachments/assets/15378898-3010-4747-83b8-e0a868235bfc)

Click Save Anyway, I can still create the source
![image](https://github.com/user-attachments/assets/9ef182ed-197a-47a9-ac4d-9f27b73a4c09)

## Connection Popup instruction
The instruction is "Go to ”More” > “Data sources” > ”New data source” > ”Custom API (Advanced)”"
![image](https://github.com/user-attachments/assets/c74d9d18-fd64-456a-a914-6960d963168b)

But the actual API Key is under "Left Side Bar > CDP > Data sources > New data source"
![image](https://github.com/user-attachments/assets/aed3c861-8de2-462e-831f-8fc0fcac4134)

Select the Data Source
![image](https://github.com/user-attachments/assets/ad267152-086a-4003-8738-6f8dfea14ba0)

Then Copy the API Key there
![image](https://github.com/user-attachments/assets/58951dbd-0f77-41e7-94d9-adaf87eaa485)

**Comment by malexanderlim** [comment]
Thanks for flagging - I've updated the description along with the test request.
