### ISSUE TITLE
[Components] google-chat

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14839]
# google-chat
## URLs
- https://developers.google.com/workspace/chat/api/reference/rest
#### Prompt
This action allows the user to independently send a message in Google Chat. The main required prop is 'text' representing the content of the message. An optional prop could be 'thread_id' to send the message in a specific thread.

**Comment by michelle0927** [comment]
@malexanderlim Is this the same as the existing Google Chat [Create Message](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_chat/actions/create-message/create-message.mjs) action, or would Send Message be different?

**Comment by malexanderlim** [comment]
Sorry Michelle! Was testing out an automated workflow here and meant to close this.
