### ISSUE TITLE
[ACTION] GitLab new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1485]
**Is there a specific app this action is for?**
GitLab

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.gitlab.com/ee/api/

**Search Projects** \| Returns a list of projects of which the authenticated user is a member
**List Owned Projects** \| Returns the user's list of projects
**List a Project's Users** \| Retrieves the repository contributors list
**Get a Project** \| Retrieves a specific project owned by the user and identified by name, ID or namespace.
**Get an Issue** \| Returns a single project issue
**Search Issues** \| Returns all issues created by the authenicated user.
**List Project Issues** \| Returns a list of a project's issues
**List Milestone Issues** \| Retrieves all issues assigned to a single project milestone
**List Issues that close on Merge** \| Get issues that would be closed by merging the provided merge request
**Create an Issue** \| Creates a new project issue
**Update an Issue** \| Updates an existing project issue. This call is also used to mark an issue as closed
**Delete an Issue** \| Deletes an issue
**List Issue Notes** \| Returns the comments of a commit in a project
**Get an Issue Note** \| Returns a single note for a specific project issue.
**Creates an Issue Note** \| Creates a new note to a single project issue
**Update an Issue Note** \| Modifies an existing note of an issue
**List Commit Comments** \| Returns the comments of a commit in a project
**Search Repository Commits** \| Returns a list of repository commits in a project
**Get a Commit** \| Returns a specific commit identified by the commit hash or name of a branch or tag
**Get a Diff of a Commit** \| Returns the diff of a commit in a project
**Post a Comment to Commit** \| Adds a comment to a commit
**Cherry Pick a Commit** \| Cherry picks a commit to a given branch
**Search Merge Request** \| Retrieves all merge requests for a project
**List Merge Request Changes** \| Retrieves the list of changes for a specified merge request
**List Merge Requests Closing an Issue** \| Retrieves all merge requests that will close a specified issue when merged
**Get a Merge Request** \| Shows information about a single merge request
**Get a Merge Request Commits** \| Get a list of merge request commits
**Create a Merge Request** \| Creates a new merge request
**Update a Merge Request** \| Updates an existing merge request. You can change the target branch, title, or even close the merge request
**Create a Todo on Merge Request** \| Manually creates a todo for the current user on a merge request
**Accept a Merge Request** \| Merges changes submitted with merge request
**Delete a Merge Request** \| Only for admins and project owners. Soft deletes the merge request
**Cancel Merge When Pipeline Succeeds** \| Cancels a merge request when the pipeline succeeds
**List Merge Request Notes** \| Returns a list of all notes for a single merge request
**Get a Merge Request Note** \| Returns a single not for a given merge request
**Create a Merge Request Note** \| Creates a new note for a single merge request
**Update a Merge Request Note** \| Modifies an existing note of a merge request
**List Repository Contributors** \| Retrieves repository contributors list
**List Repository Tree** \| Returns a list of repository files and directories in a project
**Get a File from Repository** \| Allows you to receive information about a file in the repository like name, size, content
**Get a Raw File from Repository** \| Returns contents from a repository
**Create a File in a Repository** \| Creates a file in a repository
**Delete a File in a Repository** \| Deletes an existing file in a repository
**Search Repository Brances** \| Returns a list of repository branches from a project
**Get a Repository Branch** \| Returns a single project repository branch
**Create a Repository Branch** \| Creates a single project repository branch
**Delete a Repository Branch** \| Deletes a single project repository branch
**Search Pipelines** \| Retrieves all pipelines for a given project
**Get a Pipeline** \| Returns a single pipeline for a given project
**Retry Failed Jobs in a Pipeline** \| Retries failed builds in a pipeline
**Create a Pipeline** \| Creates a new pipeline for a given project
**Cancel a Pipeline's Jobs** \| Cancels a pipeline's builds
**List Jobs** \| Returns a list of builds in a project
**Get a Job** \| Retrieves a single build of a project
**Cancel a Job** \| Cancels a single build of a project
**Play a Job** \| Triggers a manual action to start a build
**Erase a Job** \| Erases a single build of a project (remove build artifacts and build a trace)
**Keep Artifacts** \| Prevents artifacts from being deleted when expiration is set
**List Repository Tags** \| Returns a list of repository tags from a project, sorted by name in reverse alphabetical order
**Get a Tag** \| Returns a specific repository tag determined by its name
**Create a Tag** \| Creates a new tag in the repository that points ot the supplied ref
**Delete a Tag** \| Deletes a tag
**List Todos** \| Returns a list of todos. When no filter is applied, it returns all pending todos for the current user
**Create a Todo** \| Manually creates a todo for the current user on an issue
**Mark a Todo as Done** \| Marks a single pending todo given by its ID for the current user as done
**List Labels** \| Returns all labels for a given project
**Get a Label** \| Returns details about a label
**Create a Label** \| Creates a new label for the given repository with the given name and color
**Update a Label** \| Updates a label
**Delete a Label** \| Deletes a label
**List Milestones** \| Returns a list of project milestones
**Get a Milestone** \| Returns a single project milestone
**Create a Milestone** \| Creates a project milestone
**List Variables** \| Returns a list of project's build variables
**Get a Variable** \| Retrieves the details of a project's specific build variable
**Create a Variable** \| Creates a build variable
**Update a Variable** \| Updates a project's build variable
**Delete a Variable** \| Removes a project's build variables
**List Snippet Notes** \| Returns a list of all notes for a single snippet.
**Get a Snippet Note** \| Returns a single note for a given snippet
**Create a Snippet Note** \| Creates a new note for a single snippet
**Update a Snippet Note** \| Modifies an existing note of a snippet
**Search Groups** \| Returns a list of all groups
**Create a Group** \| Creates a group
**List Deployments** \| Returns a list of deployments in a project
**Get a Deployment** \| Returns a specific deployment of a project
**Create a Release** \| Adds release notes to the existing git tag
**Update a Release** \| Updates the release notes of a given release
**Get My Info** \| Returns details about an account
**Executes a GraphQL Query** \| Performs an arbitrary authorized GraphQl query

**Comment by dannyroosevelt** [comment]
@andrewjschuang this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
