### ISSUE TITLE
[ACTION] Google Docs new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1487]
**Is there a specific app this action is for?**
Google Docs

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.google.com/docs/api

**Create Document from Text** \| Create a new document from text. Also supports limited HTML
**Upload Document** \| Copy an already-existing file from another service to Docs. Will convert the file to Google Doc format if possible
**Create Document from Template** \| Creates a new doc based on an existing one and can replace any placeholder variables found in your template doc, like {{name}}, {{email}}, etc.
**Find a Document** \| Search for a specific document by name. Optionally, create one if none are found
**List Documents** \| Retrieves a list of documents
**Insert an Image to a Document** \| Inserts a new image with URL to a document.
**Replace an Image with a New Image** \| Replaces an existing image with a new image with URL in the document.
**Replace a Text in a Document** \| Replaces an old text by a new text in a document
**Download a Document** \| Downloads a document to a required format
**Deletes a Document** \| Deletes a document
**Make All Links in a Document Clickable** \| Makes all links in a document clickable

**Comment by LucBerge** [comment]
> Create Document from Text | Create a new document from text. Also supports limited HTML.

This is a Google Drive action : [Create file from text](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/create-file-from-text/create-file-from-text.mjs)

> Upload Document | Copy an already-existing file from another service to Docs. Will convert the file to Google Doc format if possible.

This is a Google Drive action: [Upload file](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/upload-file/upload-file.mjs)

> Create Document from Template | Creates a new doc based on an existing one and can replace any placeholder variables found in your template doc, like {{name}}, {{email}}, etc.

PR in progress #2436

> Find a Document | Search for a specific document by name. Optionally, create one if none are found.

This is a Google Drive action: [Find file](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/find-file/find-file.mjs)

> List Documents | Retrieves a list of documents

This is a Google Drive action: `list_files_matching_filename` (No source code)

> Insert an Image to a Document | Inserts a new image with URL to a document.

No corresponding action yet. Can maybe be done using batch update.

> Replace an Image with a New Image | Replaces an existing image with a new image with URL in the document.

No corresponding action yet. Can maybe be done using batch update.

> Replace a Text in a Document | Replaces an old text by a new text in a document

No corresponding action yet. It can be done using a batch update.

> Download a Document | Downloads a document to a required format

This is a Google Drive action: [Download file](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/download-file/download-file.mjs)

> Deletes a Document | Deletes a document

This is a Google Drive action: [Delete file](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/delete-file/delete-file.mjs)

> Make All Links in a Document Clickable | Makes all links in a document clickable

No corresponding action yet. Can maybe be done using batch update.

**Comment by LucBerge** [comment]
@michelle0927 I suggest you to edit your issue: Half of the actions you described are Google Drive action and already exists.

**Comment by andrewjschuang** [comment]
Updating the checklist:

 - Create Document from Template: #2436 - thanks for the contribution!
 - Insert an Image to a Document - #2725
 - Replace an Image with a New Image - #2725
 - Replace a Text in a Document - #2725

Actions:

  - [x]  **Create Document from Text** | Create a new document from text. Also supports limited HTML
  - [x]  **Upload Document** | Copy an already-existing file from another service to Docs. Will convert the file to Google Doc format if possible
  - [X]  **Create Document from Template** | Creates a new doc based on an existing one and can replace any placeholder variables found in your template doc, like {{name}}, {{email}}, etc.
  - [x]  **Find a Document** | Search for a specific document by name. Optionally, create one if none are found
  - [x]  **List Documents** | Retrieves a list of documents
  - [X]  **Insert an Image to a Document** | Inserts a new image with URL to a document.
  - [X]  **Replace an Image with a New Image** | Replaces an existing image with a new image with URL in the document.
  - [X]  **Replace a Text in a Document** | Replaces an old text by a new text in a document
  - [x]  **Download a Document** | Downloads a document to a required format
  - [x]  **Deletes a Document** | Deletes a document
  - [ ]  **Make All Links in a Document Clickable** | Makes all links in a document clickable

**Comment by dannyroosevelt** [comment]
@andrewjschuang this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
