### ISSUE TITLE
[APP] eBay API

### ISSUE THREAD

**Issue by rbarisic-lme** [PipedreamHQ/pipedream#14889]
eBay

[**Link to developer documentation**
](https://developer.ebay.com/develop)

The eBay API is just a brainmelt if you don't have a https server running and want to work locally

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- Get Orders
- Ship Orders
- Get Inventory

**Comment by sergio-eliot-rodriguez** [comment]
Nice Zangieff toon in profile pic!

Please follow #6211, we are tracking eBay there :) 
Thanks

**Comment by sergio-eliot-rodriguez** [comment]
Dear @rbarisic-lme 

We have rolled out a [base integration](https://pipedream.com/apps/ebay?via=go) for eBay. I apologize for the extreme delay on this.
Hope you can still leverage for your integrations.

All the best,
Sergio Eliot Rodriguez
Pipedream Integrations team

**Comment by sergio-eliot-rodriguez** [comment]
Tracking your components at https://github.com/PipedreamHQ/pipedream/issues/17804
