### ISSUE TITLE
Google Business Profile

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14895]
### App
Google Business Profile
https://developers.google.com/my-business/content/overview

**Comment by sergio-eliot-rodriguez** [comment]
Documentedly, Google Business Profile require one of the following scopes to work:

> Authorization Scopes
> Requires one of the following OAuth scopes:
> 
> https://www.googleapis.com/auth/business.manage
> https://www.googleapis.com/auth/plus.business.manage

in [Implement OAuth with Business Profile APIs](https://developers.google.com/my-business/content/implement-oauth)

Pipedream app "Google My Business" uses the `https://www.googleapis.com/auth/business.manage` scope

THe app can be located at https://pipedream.com/apps/google-my-business
Is this app useful for the use case?

**Comment by malexanderlim** [comment]
I've renamed the app from **Google My Business** to **Google Business Profile** for searchability, and to conform to the naming convention of the broader set of APIs.
