### ISSUE TITLE
[FEATURE] See all keyboard shortcuts using ?

### ISSUE THREAD

**Issue by siraj-samsudeen** [PipedreamHQ/pipedream#1491]
Thanks for this great tool - I have just spent half-a-day and working on the first tutorial. So far looks very interesting...

In almost all other apps I use, I press `?' and I am able to see the keyboard shortcuts, but it is not working here. I have tried to search for Keyboard shortcuts in the docs/community and in the open/closed issues but could not find any reference. I did find a mention to custom keyboard shortcuts but could not really find a single place where they are all listed in the docs. Please create a page and make it available via a standard shortcut like ?. I really want to speed up navigating between steps, running a test event without scrolling up and down.

**Comment by dylburger** [comment]
Thanks @siraj-samsudeen , I love the `?` idea and I agree we can improve the docs on keyboard shortcuts. I opened #1492 to track that, as well.

**Comment by dylburger** [comment]
This is available in the new version of the workflow builder! Click `Cmd` + `?` on a Mac or Windows button + `?` on a PC to see all available shortcuts.
