### ISSUE TITLE
[BUG] Hubspot actions can't be configured with end user auth

### ISSUE THREAD

**Issue by js07** [PipedreamHQ/pipedream#14913]
**Describe the bug**
Hubspot actions that make a Hubspot API call in `additionalProps` can't be configured when "Use end user auth via Connect" is enabled.

_Previously, this was not an issue since Pipedream-managed auth was the only auth type._

**To Reproduce**
1. Add the Hubspot **Search CRM** action to a workflow
2. Toggle "Use end user's auth via Connect"
3. Select "Contacts" in the dropdown for **Object Type**
4. See axios error and no additional fields for searching or creating an object

**Expected behavior**
I should be able to successfully configure the action when I have "Use end user auth via Connect" enabled:
1. The **Search Property**, **Search Value**, and **Additional properties to retrieve** props should be shown (without options) even if the Hubspot API call in `additionalProps` fails.
2. If **Create if not found?** is `true`, I should be able to enter an expression for a JSON object if properties can't be fetched. _This applies to all of the "Create *" and "Update *" Hubspot actions._

(This would be similar to the [fallback](https://github.com/PipedreamHQ/pipedream/blob/46e7530d240251261c8f64dd8e38b104e4b3c3a3/components/google_sheets/actions/add-single-row/add-single-row.mjs#L100) used in the Google Sheets Add Single Row action.)

**Screenshots**

Current behavior:
<img width="687" alt="ac6dc9e" src="https://github.com/user-attachments/assets/0a747699-7200-4f7e-8246-71384707150a">

These props should be shown:
<img width="678" alt="fc39843" src="https://github.com/user-attachments/assets/2ec926be-9275-4de8-a7c7-a37f866ae650">

**Comment by michelle0927** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/BUG-Hubspot-actions-can-t-be-configured-with-end-user-auth-15bbf548bb5e817188a6cf47a07fee14

@vunguyenhung I haven't been able to reproduce the error in `create_engagement` with `hs_timestamp`. Would you mind testing it once more?
