### ISSUE TITLE
[Components] pennylane

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14952]
# pennylane
## URLs
- https://pennylane.readme.io/
#### Prompt
Emit new event when a billing subscription is created. Props to configure include required billing subscription filters to narrow down the results.
#### URLs
- https://pennylane.readme.io/reference/billing_subscriptions-get-1
#### Prompt
Emit new event when a new invoice is created or imported. Props to configure include required invoice filters to specify criteria and optional date range filters for better precision.
#### URLs
- https://pennylane.readme.io/reference/customer_invoices-get-1
#### Prompt
Emit new event when a new customer is created. Props to configure include optional tags or customer metadata to filter specific types of customers.
#### URLs
- https://pennylane.readme.io/reference/customers-get-1
#### Prompt
Create a new customer in Pennylane. Props required include customer details such as name, email, and contact information. Optional props can include address or additional metadata.
#### URLs
- https://pennylane.readme.io/reference/customers-post-1
#### Prompt
Create a billing subscription for a customer. Props required include customer ID, subscription plan ID, and billing frequency. Optional props can include discounts or custom notes.
#### URLs
- https://pennylane.readme.io/reference/billing_subscriptions-post-1
#### Prompt
Generate a new invoice for a customer. Props required include customer ID, invoice items, and payment terms. Optional props can include tax details or invoice footer customization.
#### URLs
- https://pennylane.readme.io/reference/customer_invoices-post-1

**Comment by luancazarine** [comment]
There is a bug with the account connection, so as discussed with @malexanderlim, I'm moving it to locked for now.

**Comment by malexanderlim** [comment]
@luancazarine the bug is now corrected - let me know if this works for you now!
