### ISSUE TITLE
[Components] boldsign

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14976]
# boldsign
## URLs
- https://developers.boldsign.com/api-overview/getting-started/?region=us
#### Prompt
Emit new event when a document is completed by all the signers. Optional props are: 'SentBy', 'Recipients', 'SearchKey', 'Labels' and 'BrandIds'. SentBy and BrandIds props have async options. Prop Status must be 'Completed'.
#### URLs
- https://developers.boldsign.com/documents/list-documents/?region=us
- https://developers.boldsign.com/sender-identities/list-identities/?region=us
- https://developers.boldsign.com/branding/list-brands/?region=us
#### Prompt
Emit new event when a document is sent to a signer. Optional props are: 'SentBy', 'Recipients', 'SearchKey', 'Labels' and 'BrandIds'. SentBy and BrandIds props have async options. Prop TransmitType must be 'Sent'.
#### URLs
- https://developers.boldsign.com/documents/list-documents/?region=us
- https://developers.boldsign.com/sender-identities/list-identities/?region=us
- https://developers.boldsign.com/branding/list-brands/?region=us
#### Prompt
Emit new event when a document is declined by a signer. Optional props are: 'SentBy', 'Recipients', 'SearchKey', 'Labels' and 'BrandIds'. SentBy and BrandIds props have async options. Prop Status must be 'Declined'.
#### URLs
- https://developers.boldsign.com/documents/list-documents/?region=us
- https://developers.boldsign.com/sender-identities/list-identities/?region=us
- https://developers.boldsign.com/branding/list-brands/?region=us
#### Prompt
Send documents for e-signature using a BoldSign template. Required props include 'template_id'. Optional props include 'title', 'message', 'roles', 'brandId', 'labels', 'disableEmails', 'disableSMS', 'hitDocumentId', 'enableAutoReminder', 'reminderDays', 'reminderCount', 'cc', 'expiryDays', 'enablePrintAndSign', 'enableReassign', 'enableSigningOrder', 'disableExpiryAlert', 'documentInfo', 'onBehalfOf', 'roleRemovalIndices', 'documentDownloadOption', 'formGroups', 'files', 'fileUrls', 'recipientNotificationSettings', 'removeFormFields', 'enableAuditTrailLocalization'. BrandId prop has async options, at least files or fileUrls must be provided.
#### URLs
- https://developers.boldsign.com/documents/send-document-from-template/?region=us
- https://developers.boldsign.com/branding/list-brands/?region=us

**Comment by luancazarine** [comment]
Hi @vunguyenhung, the 'Sent By' prop does not list users, it lists senders. as you can see [here](https://developers.boldsign.com/sender-identities/list-identities/?region=us) and [here](https://developers.boldsign.com/documents/list-documents/?region=us#:~:text=Mail%20ID%20of%20the%20sender)
