### ISSUE TITLE
[ACTION] ClickUp new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1498]
**Is there a specific app this action is for?**
ClickUp

**Please provide a link to the relevant API docs for the specific service / operation.**
https://clickup.com/api

**Create Folder** \| Creates a new Folder
**Post a Task Comment** \| Post a comment to a task
**Post Attachment** \| Post an attachment to a task
**New Checklist** \| Add a checklist to a task
**Time Tracked** \| Add time tracked to a task
**List All Tasks** \| Retrieves all tasks for a specific list
**List Subtasks for a Task** \| Retrieves all subtasks for a specified task
**List Filtered Tasks** \| Retrieves tasks for a specific workplace
**List All Task Members** \| Retrieves all task members
**List Task Templates** \| Retrieves all task templates
**Get a Task** \| Retrieves details about a specific task or subtask
**Create a Task from a Template** \| Creates a task from a specific template
**Edit a Task** \| Updates a task
**Edit a Task with Custom Fields** \| Updates a task
**Delete a Task** \| Deletes a specific task
**List All Lists** \| Retrieves all lists for a specific folder
**List All Folderless Lists** \| Retrieves all space lists
**List All List Views** \| Retrieves all list views
**List All List Members** \| Retrieves all list members
**Get a List** \| Retrieves details about a specific list
**Create a Folderless List** \| Creates a folderless list
**Edit a List** \| Updates a List
**Delete a List** \| Deletes a list
**List All Folders** \| Retrieves all folders for a specific space
**Get a Folder** \| Retrieves details about a specific folder
**Edit a Folder** \| Updates a folder
**Delete a Folder** \| Deletes a folder
**List All Spaces** \| Retrieves all spaces belonging to a specific team
**Get a Space** \| Retrieves details about a specific space
**Create a Space** \| Creates a space
**Edit a Space** \| Updates a space
**Delete a Space** \| Deletes a specific space
**Create a Target** \| Creates a goal target
**Edit a Target** \| Updates a goal target
**Delete a Target** \| Deletes a target
**List All Goals** \| Retrieves all workspace goals
**Get a Goal** \| Retrieves details about a specific goal
**Create a Goal** \| Creates a new workspace goal
**Edit a Goal** \| Updates a goal
**Delete a Goal** \| Deletes a specific goal
**List All Comments** \| Retrieves all comments for a specific task, view, or list
**Post a View Comment** \| Posts a comment to a view
**Post List Comment** \| Posts a comment to a list
**Update a Comment** \| Updates a list or task comment
**Delete a Comment** \| Deletes a list or task comment
**List All Space Views** \| Retrieves all space views
**List All Team Views** \| Retrieves all team views
**List All Folder Views** \| Retrieves all folder views
**List All View Tasks** \| Retrieves all tasks for a specific view
**Get a View** \| Retrieves details about a specific view
**List All Space Tags** \| Retrieves all tags of a specific space
**Create a Space Tag** \| Creates a new tag for a specific space
**Add Tag to a Task** \| Adds tag to a task
**Remove Tag from a Task** \| Removes a tag from a specific task
**Edit a Space Tag** \| Updates a space tag
**Delete a Space Tag** \| Deletes a space tag
**Create a Checklist Item** \| Creates an item in a checklist
**Edit a Checklist** \| Updates checklist name and/or position
**Edit a Checklist Item** \| Updates a checklist item
**Delete a Checklist** \| Deletes a specific checklist
**Delete a Checklist Item** \| Deletes a specific checklist item
**List Time Entries** \| Retrieves a list of time entries within a date range
**Get a Time Entry** \| Gets a specified time entry
**List Time Entry's History** \| Retrieves a list of time entry's histories
**Create a Time Entry** \| Creates a new time entry manually
**Start/Stop a Timer** \| Starts or stops a timer
**Update a Time Entry** \| Updates an existing time entry
**Delete a Time Entry** \| Deletes a time entry
**List Tracked Time** \| Retrieves tracked time for a specific task
**Edit Time Tracked** \| Updates tracked time
**Delete Time Tracked** \| Deletes tracked time
**Add a Dependency** \| Adds a dependency to a task
**Delete a Dependency** \| Removes a dependency of tasks
**List All Accessible Custom Fields** \| Retrieves all custom fields for a specific list
**List All Workspaces** \| Retrieves all workspaces
**Invite a User to a Workspace** \| Invites a user to a selected workspace

**Comment by dannyroosevelt** [comment]
@lcaresia this is ready for release!
