### ISSUE TITLE
[ACTION] Lusha: Prospecting APIs

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#14992]
# lusha
## URLs
- https://www.lusha.com/docs/
#### Prompt
Search for contacts using filters. Optional props can include names, jobTitles, jobTitlesExactMatch, countries, seniority, Departments, existingDataPoints and location.
#### URLs
- https://www.lusha.com/docs/#contactcompany-search
#### Prompt
Search for company using filters. Optional props can include names, domains, locations, sizes, revenues, sicCodes and naicsCodes.
#### URLs
- https://www.lusha.com/docs/#contactcompany-search
#### Prompt
Enrich contacts based on IDs. Props required include requestId and contactIds.
#### URLs
- https://www.lusha.com/docs/#contact-enrich
#### Prompt
Enrich companies based on IDs. Props required include requestId and companyIds.
#### URLs
- https://www.lusha.com/docs/#company-enrich

**Comment by luancazarine** [comment]
Hi @dannyroosevelt, Lusha API is an enterprise feature only. Could you contact them to get a dev account?
![image](https://github.com/user-attachments/assets/4cc7bf9f-b9ad-4694-8091-959b73a99d19)

**Comment by dannyroosevelt** [comment]
Yea, on it. Do you want to try and stub out the actions as best you can, then when we get an API key we can use, you can test them end to end?

**Comment by dannyroosevelt** [comment]
> Hi @dannyroosevelt (cc @malexanderlim ), is there any update on the Lusha account?

not yet, bugging them now
