### ISSUE TITLE
[APP] Helcim

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14998]
### App
helcim
https://www.helcim.com/developer-api/

### Sources
booking on setmore 

### Actions
payment received when booked from setmore

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pd, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Helcim is integrated -- https://pipedream.com/apps/helcim

**Comment by sergio-eliot-rodriguez** [comment]
can the user elaborate on the "payment received when booked from setmore" action?

please follow "New Booking" action at #15030
