### ISSUE TITLE
[APP] Instagram

### ISSUE THREAD

**Issue by ReggieNora** [PipedreamHQ/pipedream#15029]
**Name of app / service**
Instagram

**Link to developer documentation**
https://developers.facebook.com/docs/instagram-platform/instagram-api-with-facebook-login/content-publishing

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, it is and currently I do not have a workaround for this. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Mainly, I think it would be awesome to have a trigger that will put up a post with hashtags included.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @ReggieNora 

An instagram integration has been blocked because of an approval process with Facebook.
Instagram has been greatly upvoted on Pipedream and we are tracking it at #445, so feel free to follow there, if you'd like.
Closing as duplicate request.

Thank you
