### ISSUE TITLE
squarespace-firebase- 8/13/2024, 4:50 PM

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#15033]
### App
squarespace-firebase- 8/13/2024, 4:50 PM

### Summary:
Outdated Firebase SDK

### Details:
We are being affected by https://github.com/firebase/firebase-admin-node/issues/2778 because the Firebase SDK version is 13.0.0, and this is fixed in 13.0.1.

We need the SDK updated, ideally within the next two business days.

### Screenshots:
No screenshots included

**Comment by WindowsUser** [comment]
The linked commits/PR would not seem to have fixed this, as we still get the same error.

`Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "The incoming JSON object does not contain a client_email field".`

Most importantly it still says it's on version 13.0.0. The linked PR/commit does not appear to have changed that.

**Comment by andrewjschuang** [comment]
@WindowsUser just to make sure, did you update the action? If it's a trigger, you'd have to create a new one.
Could you share what is the component name and version? You should see that info in the Details section of the component while in the workflow inspector
