### ISSUE TITLE
BSP Solo Migration - 9/2/2024, 7:40 PM

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#15057]
### App
BSP Solo Migration - 9/2/2024, 7:40 PM

### Summary:
Still Not Fixed: Outdated Firebase Admin SDK

### Details:
The previous issue, #15033, did not get fixed by the PR's and commits that purported to do so. We still get this every day:

`
Error

Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "The incoming JSON object does not contain a client_email field".
Details

    at null.null (/pipedream/dist/code/dca91ca86b38d2999b8e2cc5e8ac19c846ecf18fbeee9cb18d24e1698f96d784/node_modules/.pnpm/firebase-admin@13.0.0/node_modules/firebase-admin/lib/app/firebase-app.js:87:19)
    at null.disableUserByEmail (file:///pipedream/dist/code/dca91ca86b38d2999b8e2cc5e8ac19c846ecf18fbeee9cb18d24e1698f96d784/component.mjs:40:28)
    at Object.run (file:///pipedream/dist/code/dca91ca86b38d2999b8e2cc5e8ac19c846ecf18fbeee9cb18d24e1698f96d784/component.mjs:74:7)
    at null.executeComponent (/var/task/launch_worker.js:292:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:792:28)`

As said before, this is us being affected by https://github.com/firebase/firebase-admin-node/issues/2778 and we know it is still this issue because the version in the file paths is still 13.0.0. Again, this needs to be fixed with priority.

### Screenshots:
No screenshots included

**Comment by Troy674** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by WindowsUser** [comment]
That appears to be a generic GitHub help line, not a Pipedream-specific one.

**Comment by andrewjschuang** [comment]
This is Pipedream's issue cards. What is BSP Solo Migration?

**Comment by sergio-eliot-rodriguez** [comment]
Looks more like helpline for Firebase on their firebase-admin-node GItHub repository.

User flagged issue in the wrong repo, imo. (if this is a mistake feel free to reopen)

**Comment by sergio-eliot-rodriguez** [comment]
Reopened, having second thoughts. Let's await user for further input.

**Comment by WindowsUser** [comment]
Indeed, as clearly shown in the aforementioned Firebase admin issue (2778),
they have already fixed it in a new version and what Pipedream needs to do
is update to that version, which the previous commit in the other issue did
not do at all. The only reason it would be an issue for Firebase is if the
Node SDK specifically is not yet available in that version.

**Comment by sergio-eliot-rodriguez** [comment]
I understand now.
So the stracktrace says PD is using 13.0.0 of the Firebase Admin SDK.
Now, PD should update its Firabse related components to use a newer Firebase Admin SDK such that includes the fix.
Ok, so I'll leave it open. 

cc @malexanderlim revisit of #15033 

As of "BSP Solo Micrgration" you are doing some migration on a software called BSP Solo which like needs to use Firebase Admin SDK.

**Comment by sergio-eliot-rodriguez** [comment]
Unsure if you tried this: from @andrewjschuang 's input in the 15033

> @WindowsUser just to make sure, did you update the action? If it's a trigger, you'd have to create a new one.
> Could you share what is the component name and version? You should see that info in the Details section of the component while in the workflow inspector

**Comment by WindowsUser** [comment]
This isn't a migration anymore per se. It's an already-running integration
that broke with the regression.

**Comment by WindowsUser** [comment]
This is not a trigger action. We shouldn't need to update the code itself
unless doing so clears some cache. I can't attempt that remedy until later
today or tomorrow in any case.

**Comment by malexanderlim** [comment]
@WindowsUser I updated the Firebase version here: https://github.com/PipedreamHQ/pipedream/pull/15062

Can you remove and re-add the trigger, or update the action and let me know if it works for you now?

**Comment by WindowsUser** [comment]
This looks more like what we're looking for. I'll see if I can try tonight
(being out of town means limited laptop access).

**Comment by WindowsUser** [comment]
Unfortunately, it did not work. I tried creating a new trigger but the step still uses version 13.0.0 and (thus, likely) returns the same exact error when I do "run now".

**Comment by WindowsUser** [comment]
As for component version, I think this is what you're referring to:

`Message:Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "The incoming JSON object does not contain a client_email field".Total Duration:6,504 msExecution Start:2024-12-24T09:15:13.541ZExecution End:2024-12-24T09:15:20.045ZSteps Executed:6 / 11credits:2Version:202 (d_1gsQrggo)`

**Comment by andrewjschuang** [comment]
I was able to locate your workflow using the deployment version you shared, thanks. Looks like it needed a new updated deployment. @WindowsUser could you please try again now?

**Comment by WindowsUser** [comment]
Confirming the issue is resolved, but for future reference, I thought I did redeploy. I guess it did not go through properly because it did not update the version.
