### ISSUE TITLE
[BUG] OpenAI - Chat with Assistant failed

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#15059]
**Describe the bug**
I got an error when executing the action as is
![image](https://github.com/user-attachments/assets/75c34a74-ba14-4a5a-95c0-c95b9963616d)

When loading the `Assistant` prop, it shows error `The v1 Assistants API has been deprecated. Please try again by setting the header 'OpenAI-Beta: assistants=v2'. See the migration guide for more information: https://platform.openai.com/docs/assistants/migration`
![image](https://github.com/user-attachments/assets/e423453e-5e81-4152-8389-6a7ab0edf6c1)

**Additional context**
Raised by a user here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1734883624308889

**Comment by yqup** [comment]
Thanks for the quick fix
