### ISSUE TITLE
[ACTION] IFTTT new action

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1505]
**Is there a specific app this action is for?**
IFTTT

**Please provide a link to the relevant API docs for the specific service / operation.**
https://platform.ifttt.com/docs/api_reference

**Send Data** | Sends data to an applet. It can execute a specific applet

**Comment by dannyroosevelt** [comment]
@andrewjschuang this is ready for release!

**Comment by andrewjschuang** [comment]
@dannyroosevelt can you approve the PR for me so I can merge it?
Thanks
