### ISSUE TITLE
[BUG] Google Analytics - Pipedream OAuth connected account failed to execute `Run Report in G4` with `insufficient authentication scopes` error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#15060]
**Describe the bug**
I connected a new Google Analytics account with Pipedream OAuth and execute the Run Report in G4, then I see the error 
```

AxiosError - Request failed with status code 403
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.analytics.data.v1beta.BetaAnalyticsData.RunReport",
          "service": "analyticsdata.googleapis.com"
        }
      }
    ]
  }
}

```
![image](https://github.com/user-attachments/assets/8cd1256c-1dbe-4f01-8b5b-359a303f178c)

**Additional context**
Raised by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1734853550140279

**Comment by malexanderlim** [comment]
Inadvertent scope update - re-added `https://www.googleapis.com/auth/analytics.readonly` and this is working correctly. @vunguyenhung when you have a chance, could you validate?

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
