### ISSUE TITLE
[ACTION] Amazon SES new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1506]
**Is there a specific app this action is for?**
Amazon SES

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.aws.amazon.com/ses/index.html

**Send a Message** \| Sends an email message
**List Email Templates** \| Retrieves a list of email templates
**Create an Email Template** \| Creates a new email template
**Get an Email Template** \| Retrieves a specified email template
**Update an Email Template** \| Updates an existing email template
**Delete an Email Template** \| Deletes an email template
**List Contact Lists** \| Retrieves a list of contact lists
**Create a Contact List** \| Creates a new contact list
**Get a Contact List** \| Retrieves a specified contact list
**Update a Contact List** \| Updates an existing contact list
**Delete a Contact List** \| Deletes a contact list
**List Contacts** \| Retrieves a list of contacts in a specified contact list
**Create a Contact** \| Creates a new contact
**Get a Contact** \| Retrieves a specified contact
**Update a Contact** \| Updates an existing contact
**Delete a Contact** \| Deletes a contact
**List Configuration Sets** \| Retrieves a list of configuration sets
**Get a Configuration Set** \| Retrieves a specified configuration set
**Create a Configuration Set** \| Creates a new configuration set
**Create a Configuration Set Event Destination** \| Creates a new configuration set event destination
**Delete a Configuration Set** \| Deletes a configuration set

**Comment by andrewjschuang** [comment]
Depends on #2302.

**Comment by andrewjschuang** [comment]
@dylburger @ctrlaltdylan I can do the refactoring of #2637 with this issue

**Comment by dannyroosevelt** [comment]
This is ready for release!
