### ISSUE TITLE
[APP] scrapegraphai.com

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#15072]
**Name of app / service**
scrapegraphai.com

**Link to developer documentation**
https://scrapegraphai.com/documentation

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the request @marcelocecin 
A base integration for scrapepgrahai has been released at [https://pipedream.com/apps/scrapegraphai](https://pipedream.com/apps/scrapegraphai?via=go)
