### ISSUE TITLE
[ACTION] Coda new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1509]
**Is there a specific app this action is for?**
Coda

**Please provide a link to the relevant API docs for the specific service / operation.**
https://coda.io/developers/apis/v1

**Create a Doc** \| Creates a new Coda doc
**List Docs** \| Returns a list of Coda docs accessible by the user
**Copy Doc** \| Creates a copy of the specified Coda doc
**Create a Row** \| Creates a row in a selected table
**Update a Row** \| Updates a specified row in the table
**Upsert a Row** \| Creates a new row or updates existing rows if any upsert key columns are provided. When upserting, if multiple rows match the specified key column(s), they will all be updated with the specified value
**Find Row** \| Searches for a Coda row in the selected table using a column match search

**Comment by djs-djs** [comment]
I can assist with this issue--thanks

**Comment by dylburger** [comment]
@djs-djs that’s great, very much appreciated! If you haven’t seen our action development docs yet, take a look here: https://pipedream.com/docs/components/quickstart/nodejs/actions/ . We’re happy to help with any questions.

**Comment by dylburger** [comment]
This should naturally address #1885 . Please make sure to use the new Coda API endpoints
