### ISSUE TITLE
[ACTION] Figma new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1511]
**Is there a specific app this action is for?**
Figma

**Please provide a link to the relevant API docs for the specific service / operation.**
https://www.figma.com/plugin-docs/api/api-overview/

**Post a Comment** \| Posts a comment to a file
**List Comments** \| Lists all comments left on a file

**Comment by vellames-turing** [comment]
Hey @dannyroosevelt. I think we have some problem with `figma app`. I am trying to link my account but nothing happens if I try to do it from the workflow. If I try to create via accounts page. A new tab is opening asking me to connect my account, but when I click on it, the tab is closed and nothing happens. The account is not created on Pipedream.

**Comment by dmathukorala** [comment]
Unable to login to Figma app

![image](https://user-images.githubusercontent.com/13300533/160833456-8052a10c-5c5a-470b-a9f3-0792a11a6ad5.png)

Scopes are invalid
Request Curl

curl "https://www.figma.com/oauth?client_id=91uXB2h88k15Gt52gstg45&redirect_uri=https^%^3A^%^2F^%^2Fapi.pipedream.com^%^2Fconnect^%^2Foauth^%^2Foa_J3dieG^%^2Fcallback&response_type=code&scope=&state=dV9xbGhwRURMfGU2NTQwOTBiMDdiZjQyZjIyZDkyYWVhYTUwNjQ0NTVl" ^
  -H "authority: www.figma.com" ^
  -H "cache-control: max-age=0" ^
  -H "sec-ch-ua: ^\^" Not A;Brand^\^";v=^\^"99^\^", ^\^"Chromium^\^";v=^\^"99^\^", ^\^"Google Chrome^\^";v=^\^"99^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  -H "upgrade-insecure-requests: 1" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36" ^
  -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" ^
  -H "sec-fetch-site: none" ^
  -H "sec-fetch-mode: navigate" ^
  -H "sec-fetch-user: ?1" ^
  -H "sec-fetch-dest: document" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "cookie: experiment_seed=122701; ajs_anonymous_id=^%^223396a54d-a68e-4d5a-bf07-1652f983926e^%^22; figma.ref=eyJ1cmwiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vIiwibmFtZSI6Ikdvb2dsZSIsInR5cGUiOiJ1bmtub3duIn0^%^3D; local_experiments=^%^22e30=^%^22; _gcl_au=1.1.1680804255.1648641125; _fbp=fb.1.1648641129345.1334254087; cb_anonymous_id=^%^22f82bf62a-fe24-4e40-96c2-f76c5c90ca1a^%^22; cb_user_id=null; cb_group_id=null; ajs_anonymous_id=^%^223396a54d-a68e-4d5a-bf07-1652f983926e^%^22; _ga=GA1.2.637934648.1648642382; _gid=GA1.2.1368523954.1648642382; recent_user_data=^%^22eyJjb21tdW5pdHlVc2VySWQiOm51bGwsImNvbW11bml0eVByb2ZpbGVJZCI6IjEwOTA5NzE5MzkwMDQzNTI2MTYiLCJmaWxlQnJvd3NlclVzZXJJZCI6IjEwOTA5NzE5Mzg4NTQxODM3MTciLCJ1c2VySWRUb09yZ0lkIjp7IjEwOTA5NjY1OTM5NDU4OTU3MjgiOm51bGwsIjEwOTA5NzE5Mzg4NTQxODM3MTciOm51bGx9fQ==^%^22; __Host-figma.authn=^%^7B^%^221090971938854183717^%^22^%^3A^%^22figtkn.authn.BKJKuaJKaDUqsubtlpqsfL^%^22^%^7D; __Host-figma.embed=^%^7B^%^221090971938854183717^%^22^%^3A^%^22figtkn.embed.DkrnR7mBOttumvZ2TSpfq8^%^22^%^7D; figma.mst=^%^7B^%^221090971938854183717^%^22^%^3A^%^22stv2-1090971938854183717-93791e36a082d6bedddf6caeb5854ad459ffab3eb6aba6588fad935c0fa615c5-1648642815^%^22^%^7D; figma.mst.embed=^%^7B^%^221090971938854183717^%^22^%^3A^%^22stv2-1090971938854183717-1a58241fcde52d54b85d155e7912f0fa7f464310ea2300e3e497472038063d2a-1648642815^%^22^%^7D; figma.session=BAh7B0kiCmZsYXNoBjoGRUZ7AEkiD3Nlc3Npb25faWQGOwBUbzodUmFjazo6U2Vzc2lvbjo6U2Vzc2lvbklkBjoPQHB1YmxpY19pZEkiRTg3MGE0YmRlYTE0NDU1OTk0OWQ1MDk4NDU1MzM2NDJkZWNiNTc3NTNkNTFjZmE4NjMwYjc0ZTY5ZDI1YzZhOTMGOwBG--59f081c5a7da1bdc6ab295f5672599d86f40ebc7" ^
  --compressed

cc - @dannyroosevelt

**Comment by dannyroosevelt** [comment]
Good catch @dmathukorala, not sure how that happened but it should be fixed again -- please give it another try.

**Comment by dannyroosevelt** [comment]
@vellames-turing this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
