### ISSUE TITLE
[FEATURE] Improve Reddit sources to use global search endpoint

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1513]
I want to search for posts by title (e.g. in the **Comments for a Post** source), so I can quickly find the post I want to watch for new events. Reddit implements [a global search API](https://www.reddit.com/dev/api/#GET_search) that we can restrict to returning links, which should allow us to implement an endpoint with search and async options.

**Comment by lcaresia** [comment]
Added a action `search-post`, need test too.
