### ISSUE TITLE
[APP] UiPath 

### ISSUE THREAD

**Issue by wmuza** [PipedreamHQ/pipedream#1515]
**Name of app / service**
UiPath 

**Link to developer documentation**
https://docs.uipath.com/automation-cloud/docs/setting-up-the-external-application

**Is lack of support preventing you from building workflows, or do you have a workaround?**
We need the auth part to be handled by pipedream so that we focus on code

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
A few from these will be ok: https://www.postman.com/uipath/workspace/uipath-s-public-workspace/collection/3707132-3352a9ee-f622-4cad-ae89-cf8485dc0d6e?ctx=documentation

**Comment by todsac** [comment]
@wmuza - In the UiPath docs it says "you must be an organization administrator to perform the tasks described on [this page](https://docs.uipath.com/automation-cloud/docs/managing-external-applications)." Would you be open to joining us on Slack to get this integration setup?  We mostly have it done but need someone with UiPath account to test and confirm, and we have a couple of questions.

**Comment by wmuza** [comment]
@todsac yes lets get it done on slack. I am in pipedream slack account. I have sent a DM

**Comment by wmuza** [comment]
Thank you @todsac for implementing the UiPath app on pipedream. I am delighted to say that it works beautifully and it removed the pain point of working with UiPath Api. I am going to create actions for the app and publish them for anyone to use.

Well done team Pipedream
