### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by bmrejen** [PipedreamHQ/pipedream#1516]
Hi, it would be great to be able to integrate Line or Wechat !

**Comment by dylburger** [comment]
@bmrejen thanks for reaching out. We have a LINE integration here: https://pipedream.com/apps/line . Are you looking for a specific trigger or action?

**Comment by bmrejen** [comment]
I would like to export the chat content of the group and send it by mail at the end of the day. Do you think this is possible with this API?

**Comment by dylburger** [comment]
@bmrejen I don't see a specific API endpoint in [the LINE API docs](https://developers.line.biz/en/reference/messaging-api/) to retrieve lists of messages in groups. Would you mind taking a look to see if you can find anything different, or perhaps reach out to the LINE team to ask?

If an API endpoint exists for what you need, I'm happy to open an issue tracking a Pipedream action for you.

It looks like you can also configure [webhooks](https://developers.line.biz/en/reference/messaging-api/#webhooks) that will send new messages to an HTTP URL. If you [create a new workflow](https://pipedream.com/new) and choose the **HTTP API** trigger, you can copy that URL into the LINE UI for configuring webhooks and start sending new messages there.

Let me know if that helps.
