### ISSUE TITLE
[ACTION] Zoho CRM new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1524]
**Is there a specific app this action is for?**
Zoho CRM

**Please provide a link to the relevant API docs for the specific service / operation.**
https://www.zoho.com/crm/developer/docs/api/v2/

**Create Object** \| Creates a new object
**Convert Lead** \| Convert an existing lead to contact and account

**Comment by kok426** [comment]
https://github.com/PipedreamHQ/pipedream/projects/1#card-65428056

**Comment by kok426** [comment]
https://github.com/PipedreamHQ/pipedream/projects/1#card-65428056
