### ISSUE TITLE
[ACTION / SOURCE] Postmark new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1527]
**Is there a specific app this action is for?**
Postmark

**Please provide a link to the relevant API docs for the specific service / operation.**
https://postmarkapp.com/developer/api/overview

### Triggers
- New message received
- New email opened

### Actions
- Send an email
- Send an email with template

**Comment by GTFalcao** [comment]
@andrewjschuang @lcaresia Thank you both for your very thorough reviews. I've checked and replied to all the comments, and significantly improved the code reusability and adherence to the good practices that you've suggested.

**Comment by Hassan-Abbas-SQA** [comment]
In action: Send an email > HTML body must be required to receive "New Email Opened" trigger events.
please update the hints for this scenario

**Comment by GTFalcao** [comment]
To make sure the user is not caught off-guard by this [limitation documented by Postmark](https://postmarkapp.com/developer/user-guide/tracking-opens#limitations), I've updated the descriptions for the following props:

[Source: new email opened] Track opens by default
[Action: send single email] HTML Body
[Action: (both)] Track opens

@Hassan-Abbas-SQA

**Comment by dannyroosevelt** [comment]
This is ready for release!
