### ISSUE TITLE
[ACTION] Segment new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1530]
**Is there a specific app this action is for?**
Segment

**Please provide a link to the relevant API docs for the specific service / operation.**
https://segment.com/docs/config-api/

**Identify** \| Identifies a user
**Track** \| Records a user's actions
**Group** \| Associates an individual user with a group
**Alias** \| Associates one identity with another or merges two identities

**Comment by michelle0927** [comment]
Related issue: https://github.com/PipedreamHQ/pipedream/issues/106

**Comment by dannyroosevelt** [comment]
@jcortes this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
