### ISSUE TITLE
[ACTION] Raindrop new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1532]
**Is there a specific app this action is for?**
Raindrop

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developer.raindrop.io/

**Create Item** | Creates an item
**List Bookmarks** \| Lists bookmarks
**Create a Bookmark** \| Creates a new bookmark
**Get a Bookmark** \| Gets a bookmark
**Update a Bookmark** \| Updates a bookmark
**Delete a Bookmark** \| Deletes a bookmark
**List Collections** \| List collections
**Create a Collection** \| Creates a collection
**Get a Collection** \| Gets a collection
**Update a Collection** \| Updates a collection
**Delete a Collection** \| Deletes a collection
**Parse HTML Bookmark File** \| Extracts importable bookmarks from an HTML bookmark file

**Comment by michelle0927** [comment]
Related issue for new Raindrop event source: https://github.com/PipedreamHQ/pipedream/issues/926
These two issues should be completed together.

**Comment by dannyroosevelt** [comment]
This is ready for release!

**Comment by dannyroosevelt** [comment]
This is ready for release!
