### ISSUE TITLE
[Actions and Triggers] Xero Accounting new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1537]
**Is there a specific app this action is for?**
Xero Accounting 

### Triggers 
https://developer.xero.com/documentation/guides/webhooks/overview#events

- New or updated contact
- New or updated invoice
- New or updated subscription

Please make sure to add a `string[]` proptype to each trigger so users can select either New or Updated events, or both

### Actions 
https://developer.xero.com/documentation/api/accounting/overview/

- **Create/Update Contact** \| Creates a new contact or updates a contact if a contact already exists
- **Create Bill** \| Creates a new bill (Accounts Payable)
- **Add Items to Existing Sales Invoice** \| Adds line items to an existing sales invoice
- **Find Contact** \| Finds a contact by name or account number. Optionally, create one if none are found
- **Find Invoice** \| Finds an invoice by number or reference

**Comment by LucBerge** [comment]
[Xero](https://www.xero.com/us/partner-programs/banking-partners/) is a third-party provider accessing bank APIs. Maybe your bank is also compatible with [Nordigen](https://nordigen.com/en/blog/list-all-banking-apis-updated/) third-party provider ?

**Comment by bush4u** [comment]
I got this error while trying to connect to **Xero accounting account**

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/68253993/163859036-713f3b1f-0764-453f-91d6-1cf0fe794080.png">
![image](https://user-images.githubusercontent.com/68253993/163859100-13322e64-54b9-471e-8e15-5ce4867ca3da.png)

**Comment by dylburger** [comment]
@bush4u Can you try again? Xero just helped us increase this limit.

**Comment by bush4u** [comment]
Clarification is needed on the subscription trigger. 

- Get subscription API return a 404 not found. 
- I felt i needed to subscribe to apps first, but the endpoint still returns 404 Error

API Doc  https://developer.xero.com/documentation/api/xero-app-store/subscriptions/#get-subscription

I am done with all the tasks except this.

**Comment by dannyroosevelt** [comment]
This is ready for release!
