### ISSUE TITLE
[BUG] Pipedream CLI installer fails on Apple M1

### ISSUE THREAD

**Issue by compwright** [PipedreamHQ/pipedream#1541]
**Describe the bug**

The following error occurs during installation:
> Architecture currently not supported. Please file an issue at https://github.com/PipedreamHQ/pipedream/issues

**To Reproduce**

Use the installation script to [install the Pipedream CLI](https://pipedream.com/docs/cli/install/#macos) on an Apple M1 device:

```
curl https://cli.pipedream.com/install | sh
```

**Desktop (please complete the following information):**
 - OS: `darwin` (Mac OS X Big Sur v11.5.1)
 - Architecture: `amd64`

**Comment by compwright** [comment]
If supported, the current build download URL for my system would be https://cli.pipedream.com/darwin/amd64/0.1.52/pd.zip.

**Comment by dylburger** [comment]
Fixed, thanks for reporting
