### ISSUE TITLE
[APP] Support for Outlook please?

### ISSUE THREAD

**Issue by whatbuylists** [PipedreamHQ/pipedream#1545]
Hi Pipedream,

Will you be adding support for Outlook or Gmail anytime soon?

**Comment by todsac** [comment]
@whatbuylists - I created a first version of an Outlook integration.  Can you let me know if this works for your needs?  https://pipedream.com/apps/microsoft-outlook

Also, the Gmail app is being tracked here - https://github.com/PipedreamHQ/pipedream/issues/182

**Comment by todsac** [comment]
Also, please confirm these scopes are sufficient:
email
offline_access
openid
profile
Mail.Read
WriteMail.Send
MailboxSettings.ReadWrite
User.Read

**Comment by whatbuylists** [comment]
Thanks Tod. I am trying to set up Outlook access to send a simple text message with a URL received from these steps which I am having issues with: https://github.com/PipedreamHQ/pipedream/issues/1546

Not a coder so can't really identify the scopes but all I will need is the ability to take a customer email address from a stripe checkout session and a url from the steps in the link above and send them a simple text message with that url - the message can be in the body or the subject.

Thank again! If I could get some help on the second request would be much appreciated


________________________________

**Comment by whatbuylists** [comment]
Hi Tod,

I created a http API request flow which ends with Outlook sending an email with parameters from previous steps. Am I sending the variables correctly? 

![image](https://user-images.githubusercontent.com/88419862/128290843-5d44409e-57b2-4465-8c66-dda0f77d2f83.png)

**Comment by todsac** [comment]
@whatbuylists - support requests should live on https://pipedream.com/community.
