### ISSUE TITLE
[ACTION] need help to get product metadata from customer checkout session

### ISSUE THREAD

**Issue by whatbuylists** [PipedreamHQ/pipedream#1546]
Hi, I want to do the following but I can't find a way to retrieve the price. Can I get some help?

1. Listen to checkout.session.completed to get payment_intent ID
2. Retrieve that session again, expanding line_items https://stripe.com/docs/api/checkout/sessions/retrieve
3. Finally from that expanded response you will have the price id (https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-line_items-data-price)
4. Retrieve the ProductID using that price ID (https://stripe.com/docs/api/prices/retrieve)
5. Retrieve the Product and finally find your Metadata
6. Email the metadata to the customer email address found in step 1

**Comment by whatbuylists** [comment]
I wasn't able to do what I wanted to with the default Stripe options. If someone knows how I can do it with just the existing Stripe integration options, would appreciate the advice.

Meanwhile I am trying to write my own https requests based on the steps given above. I am running into authorization issues with Stripe. Is this because Stripe requires that requests be sent over https and Pipedream uses http?

**Comment by compwright** [comment]
@whatbuylists it might be more straightforward to get the price via this line items API: https://stripe.com/docs/api/checkout/sessions/line_items

**Comment by compwright** [comment]
@whatbuylists also we are planning to add a number of Stripe actions, you can track progress or request additions here: https://github.com/PipedreamHQ/pipedream/issues/1462

**Comment by whatbuylists** [comment]
> @whatbuylists it might be more straightforward to get the price via this line items API: https://stripe.com/docs/api/checkout/sessions/line_items

Thank you @compwright for the API suggestion. Before I check it out, could I get some help with this error I am seeing - I am trying to query the price after setting up the trigger for checkout.sesssion.completed (I am not a coder and learned about APIs just this week so forgive me for blatant mistakes):
![image](https://user-images.githubusercontent.com/88419862/128242575-51b261f7-c045-4a73-b653-0286a7c6d65f.png)

**Comment by whatbuylists** [comment]
> @whatbuylists also we are planning to add a number of Stripe actions, you can track progress or request additions here: #1462

Thank you, I have added 2 enhancement requests

**Comment by todsac** [comment]
The right place for support requests is https://pipedream.com/community.  We don't provide coding support so you may want to ask the broader community or hire a developer.

**Comment by whatbuylists** [comment]
> The right place for support requests is https://pipedream.com/community. We don't provide coding support so you may want to ask the broader community or hire a developer.

I will ask the community, thanks

**Comment by whatbuylists** [comment]
> > The right place for support requests is https://pipedream.com/community. We don't provide coding support so you may want to ask the broader community or hire a developer.
> 
> I will ask the community, thanks

https://pipedream.com/community/t/cant-get-stripe-api-authorization-to-work/926
