### ISSUE TITLE
[SOURCE] Netlify Form Submission

### ISSUE THREAD

**Issue by compwright** [PipedreamHQ/pipedream#1548]
**Describe the event source. What app, what event?**
Netlify Form Submission

Trigger when a Netlify Form is submitted. In the configuration options, you can choose to be notified for a single specific form, or for all verified submissions to any form on your site.

This source should subscribe to the Netlify webhook on deploy, and poll for sample events.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://docs.netlify.com/forms/notifications/
https://docs.netlify.com/api/get-started/#hooks
https://open-api.netlify.com

**Comment by dannyroosevelt** [comment]
https://pipedream.com/apps/netlify/triggers/new-form-submission
