### ISSUE TITLE
[TRIGGER] Hubspot: { Edit, Delete } Blog Post

### ISSUE THREAD

**Issue by hannasolliestoraker** [PipedreamHQ/pipedream#1551]
Wish to request a new event source for HubSpot, to emit an event when a blog post is deleted. Also would be great to emit an event whenever a blog post is edited.

**Comment by dylburger** [comment]
@hannasolliestoraker thanks for the request!

Were you aware that you can build and publish your own event sources for anyone to use? Take a look at our [quickstart on developing sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/).

Would you be open to developing these? We're happy to help in any way.

If you don't have the time, would you be willing to reach out to Hubspot to request they build these? We're working with more apps in this capacity and it helps if the request comes directly from a customer.

**Comment by dylburger** [comment]
We should address #2995 with this, as well

**Comment by dannyroosevelt** [comment]
This is ready for release!
