### ISSUE TITLE
[APP] Include Sharpspring.com as an integration

### ISSUE THREAD

**Issue by vandgr** [PipedreamHQ/pipedream#1554]
### Please add sharpspring integration to pipedream

https://help.sharpspring.com/hc/en-us/articles/360034119252-Understanding-SharpSpring-Open-API-Methods

https://help.sharpspring.com/hc/en-us/articles/115003079951-Understanding-SharpSpring-Open-API-Schema

**Comment by todsac** [comment]
@vandgr - It doesn't appear we can get a free account quickly with SharpSpring.  Are you open to testing the integration and working with us to complete it?  

Here is v1 - https://pipedream.com/apps/sharpspring - and we need to identify the appropriate default test request.

**Comment by vandgr** [comment]
@todsac - I provided the api keys to my pipedream instance. I am not so experienced to do it, but I will try.

**Comment by dylburger** [comment]
@vandgr I just wanted to check in to see if you got this working, or if you needed any further assistance.

**Comment by dylburger** [comment]
Closing this since the app is integrated, but let us know if you have any issues / questions about the integration
