### ISSUE TITLE
Provide a visual indication of workflow success / error state on workflow dashboard

### ISSUE THREAD

**Issue by Juslesiasru** [PipedreamHQ/pipedream#156]
I received a mail that said "you've reached the 80%..." then a second one whith 100%
It's the only way to know that my WFs aren't working without going into each of them.

It would be nice to have a warning icon in the main dashboard that says if the WF is not runnning good.
You could also have a "working" icon that says that everything is ok
That way the user knows immediatly and quickly if his WF is running good or not.

Without it we have to go check every single one.

For the quota problem it's not hard to know that everyworkflow aren't working but i suggest it for all the others problems that could happen.

**Comment by dylburger** [comment]
Related - "Feature request ― Last Error column. So we can quickly see birdseye the most recent errors."

**Comment by dylburger** [comment]
This is done! You'll see a clear error at the top of the Pipedream UI now.
