### ISSUE TITLE
[APP] SendGrid Web API

### ISSUE THREAD

**Issue by mtrontz-the-dev** [PipedreamHQ/pipedream#1560]
Please add SendGrid to your list of Sources!

**Comment by dylburger** [comment]
@mtrontz-the-dev I realized we had completed a couple of **Sendgrid** sources that we hadn't yet published. I just did. You'll see two new event sources if you visit https://pipedream.com/sources/new :

<img width="447" alt="Screen Shot 2021-08-07 at 5 40 22 PM" src="https://user-images.githubusercontent.com/242668/128617161-d4a48678-66ae-4d60-b80d-570d6ba74edb.png">

Let me know if that helps or if you're looking for another source in particular.

Were you also aware that you can [develop your own sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Let me know if you have any questions / need any help on that.

**Comment by mtrontz-the-dev** [comment]
@dylburger 
 Excellent, thank you! I will test it out now and lyk how it goes. As for developing my own sources, that is what I had started doing initially, and I was just testing it out when you replied. (which was very quickly btw!) I am grateful for your quick response, and, honestly, shocked at how quickly this was implemented. I am sure many more questions will come up for me in the near future, so as soon as one pops up that I cannot figure out myself, I will certainly reach out. Thanks again!

**Comment by dylburger** [comment]
Great, thanks! I’ll close this issue for now, but feel free to raise another if you have any questions.

**Comment by mtrontz-the-dev** [comment]
Hello again, I ran into a bit of  a bump, and for the life of me, I cannot figure out what I am doing wrong. I am unsure where to send requests for help like this, so I hope this is ok just this once. So my problem is that now I have been able shift into the pipedream SQL service that you have, and my data tables are being stored correctly, I think, but no matter what I do, I cannot query any of my data! I have read through a bunch of your docs, as well as a bunch of background/basics on SQL, yet I am still completely lost! Honestly, up until now I have mainly used MongoDB, firebase, and other json document databases, mainly for this exact reason. I was never any good at stringing together a logical SQL query for my life, and now I am unsure what to do. The convenience of being able to load all of my data that flows through pipedream into a database hosted on the same platform is extremely valuable to myself, as well as my partners and clients. I hope I am not causing any frustrations, but really, any help would be wonderful. Maybe as a feature request, can you possibly provide prebuilt queries or some kind of GUI with buttons and dropdowns as opposed to relying on the users own SQL knowledge? I am really excited to finally be getting into the swing of this, and feel like this would be the last hump for us before having the perfect platform! I will add the feature request to the correct area so that it is formerly published, so that I follow protocol. Looking forward to hearing back!

**Comment by dylburger** [comment]
@mtrontz-the-dev 

> Maybe as a feature request, can you possibly provide prebuilt queries or some kind of GUI with buttons and dropdowns as opposed to relying on the users own SQL knowledge?

I definitely hear you on the request, but this is hard in our specific case because you can send _any_ data to the SQL service, so no single query would work for all users. I think this kind of information is best put into our docs / tutorials as you note. 

If it helps, the SQL Service uses [Presto SQL](https://pipedream.com/docs/destinations/sql/#sql-dialect), so you'll want to take a look at the docs for that (linked in that section). There are some subtle differences between Presto and other dialects, so hopefully that helps point you in the right direction.

Since you also asked about where to ask these questions, check out https://pipedream.com/support . Discourse and Slack are generally the best place to ask for help.

**Comment by mtrontz-the-dev** [comment]
@dylburger 
Excellent, thank you again. I will check those out now
