### ISSUE TITLE
[APP] Etsy

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#1569]
**Name of app / service**
Etsy

**Link to developer documentation**
https://www.etsy.com/developers/documentation

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Probably the same as [Shopify](https://github.com/PipedreamHQ/pipedream/tree/master/components/shopify/sources)

**Comment by todsac** [comment]
This is blocked on the PKCE code challenge requirement - https://developers.etsy.com/documentation/essentials/authentication/#proof-key-for-code-exchange-pkce

**Comment by asksock** [comment]
Hope Pipedream can add Etsy.
API: https://developers.etsy.com/documentation/
Why PKCE code challenge requirement is matter?

**Comment by zalmanlew** [comment]
Is it yet possible to add Etsy support?

**Comment by zalmanlew** [comment]
It's worth noting that Make currently has a large offering of "components" for Etsy.

https://www.make.com/en/help/app/etsy

**Comment by malexanderlim** [comment]
Hi @asksock, @zalmanlew -- we're happy to announce that we've just shipped support for PKCE code challenge requirements, unblocking our Etsy development. We've built the basic integration, and will be developing triggers and actions. 

Please let us know if there are particular triggers and actions that you'd like to see, and we'd be happy to prioritize building these.

**Comment by zalmanlew** [comment]
@malexanderlim some ideas

### Triggers
- New Transaction
- Listing Updated
 
### Actions
- Create Listing
- Update Listing
- Delete Listing
- Get Listing
- Get Transaction

**Comment by malexanderlim** [comment]
Thank you @zalmanlew - I've added your suggestions here: https://github.com/PipedreamHQ/pipedream/issues/7247, please follow along to track the progress.
