### ISSUE TITLE
[APP] Microsoft Teams

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#158]

**Comment by sergioeliot2039** [comment]
The Microsoft Teams app in Pipedrea uses  Microsoft Graph, but is missing scopes.
I.e trying the /me/joinedTeam breaks asking forthese scopes:

> "Missing scope permissions on the request. API requires one of 'Team.ReadBasic.All, TeamSettings.Read.All, TeamSettings.ReadWrite.All, User.Read.All, Directory.Read.All, User.ReadWrite.All, Directory.ReadWrite.All'.  Scopes on the request 'Chat.Read, Chat.ReadWrite, email, openid, profile, User.Read'""

So it's either the Pipedream app for MS Teams can have those scopes granted, or the issue https://github.com/PipedreamHQ/pipedream/issues/1063 is resolved, where a users can bring their own app's client id/secrets and grant the scopes to their apps.

**Comment by todsac** [comment]
Which of these scopes is not admin only?

**Comment by sergioeliot2039** [comment]
These ones:
Channel.ReadBasic.All
Helpful for: New Channel

Chat.Read.All
For New Chat, New Chat Message

Directory.Read.All
For New Team

Unfortunately,  New Channel Message and New Team member require scopes that are admin only (such as ChannelMessage.Read.All, TeamMember.Read.All)

**Comment by todsac** [comment]
Great.  I added:
Channel.ReadBasic.All
Chat.Read.All
Directory.Read.All

Should we create an additional app for MS Teams Admins?  We did this for
Zoom - https://pipedream.com/apps/zoom-admin

**Comment by sergioeliot2039** [comment]
Yes, that is definitely a good idea.

Some input to consider. Many of Microsoft services are accessed through the Microsoft Graph API, i.e. Sharepoint, this means we may have a regular app for Sharepoint, and another for Sharepoint admin, and so on for other Microsoft services that use MS Graph API for programmatic access. I don’t know how Pipedream works when connecting an app internally, so I wonder if it is technically possible to have just two Pipedream apps for MS Graph API (non admin, and admin only) and sort of add the needed scopes depending on the app being by the user when connecting an app to the Pipedream workspace.

Furthermore, I noticed other concurrent services require an app to be installed directly into the services being connected when admin consent is required.

***@***.***D77E68.8477EEF0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sergioeliot2039** [comment]
@dylburger Further scopes are needed. Some are due to further scopes needed in order to support some of the dynamic props values. Some others are after a review on the Microsoft Teams actions. (Initially, I only requested scopes for Microsoft Teams sources). At the moment I have in my fork 7 components, but marked again as blocked. The following is my post I did on[ Microsoft Teams actions issue 1422] with more scopes required:(https://github.com/PipedreamHQ/pipedream/issues/1422):

> we will need scopes added to the microsoft teams app for addressing actions too (we addressed scopes for sources before).
> when starting working on sources, i ran into scopes issues when creating dynamic options for props, some of which of the microsoft teams methods would be used by actions too, so here are divided on whether the required scope are for pipedream's microsoft teams app or for microsoft teams admin app.
> 
> microsoft app
> Send Channel Message -- ChannelMessage.Send
> Send Chat Message -- Chat.ReadWrite
> List Joined Teams -- Team.ReadBasic.All
> Get a Team -- Team.ReadBasic.All
> Create Team -- Team.Create
> Search Users -- People.Read
> 
> microsoft app admin
> Create Channel -- Channel.Create
> List All Teams and Groups -- Group.Read.All
> Create 365 Group -- Group.ReadWrite.All
> Update Team -- TeamSettings.ReadWrite.All
> Delete Team or Group -- Group.ReadWrite.All
> Update Channel -- ChannelSettings.ReadWrite.All
> Delete Channel -- Channel.Delete.All
> Add Member to Group -- GroupMember.ReadWrite.All
> 
> Couldn't find required scope for action Create Team from Group , so we might need to update scopes later for this one. Hopefully it is including in this list.

**Comment by dylburger** [comment]
Thanks for the details, Sergio. @dannyroosevelt @todsac do y'all have bandwidth to investigate this with Sergio? In addition to the scopes issue, we had an open question re: whether we should create a separate admin app for admin-level scopes, a la Zoom.

**Comment by dannyroosevelt** [comment]
Ok so it looks like we need these new scopes for the existing Microsoft Teams Admin app:

```
Create Channel -- Channel.Create
List All Teams and Groups -- Group.Read.All
Create 365 Group -- Group.ReadWrite.All
Update Team -- TeamSettings.ReadWrite.All
Delete Team or Group -- Group.ReadWrite.All
Update Channel -- ChannelSettings.ReadWrite.All
Delete Channel -- Channel.Delete.All
Add Member to Group -- GroupMember.ReadWrite.All
```

@todsac can you help facilitate?

**Comment by marcoaleixo** [comment]
Is this still being developed? :D

**Comment by dannyroosevelt** [comment]
> Is this still being developed? :D

We have a [basic integration](https://pipedream.com/apps/microsoft-teams) in place with Microsoft Teams today, which will let make authenticated request to their API, and the we have a set of pre-built actions and triggers in the queue to be developed. 

We'll get you an update on those asap.

**Comment by dannyroosevelt** [comment]
> Is this still being developed? :D

@marcoaleixo we finally shipped the actions and triggers for Microsoft Teams! Check them out here: 
https://pipedream.com/apps/microsoft-teams
