### ISSUE TITLE
[APP] Add Firebase Support

### ISSUE THREAD

**Issue by baghdadraza** [PipedreamHQ/pipedream#1580]

**Comment by dylburger** [comment]
@baghdadraza we support the **Firebase Admin SDK**: https://pipedream.com/apps/firebase-admin-sdk . 

You can also write any Node.js code on Pipedream and store any secrets as [environment variables](https://pipedream.com/docs/environment-variables/), so you should be able to use any Firebase Node.js client and add any Firebase credentials in that way.

Will either of those options work for your case?

**Comment by dylburger** [comment]
Closing this since the app is integrated, but let us know if you have any issues / questions about the integration
