### ISSUE TITLE
[APP] Accelo

### ISSUE THREAD

**Issue by alexjhart** [PipedreamHQ/pipedream#1584]
https://api.accelo.com/

**Comment by todsac** [comment]
@alexjhart - Here is the first version of the integration:
https://pipedream.com/apps/accelo

Please let us know if this works for you and if you would be interested in building out any of the triggers or actions for this app.

**Comment by alexjhart** [comment]
Hi @todsac . Thank you for the quick turn around on this. Yes, I'd be happy to help with triggers/actions. How can I set the scope on this? If a write action needs to be performed, that needs to be set.

**Comment by todsac** [comment]
We currently do not allow dynamic scopes unique to each action.  We will in the future and are tracking that issue [here](https://github.com/PipedreamHQ/pipedream/issues/1840).  Our current strategy is to include the most commonly used scopes by default in the app.  Do you know what scopes we should include?  Currently, we don't have any scopes by default for Accelo.

**Comment by alexjhart** [comment]
write(all) would cover read/write for everything. It's overly permissive, but will work until #184 has been addressed.

**Comment by todsac** [comment]
@alexjhart  - write(all) has been added. if you join us on our public [Slack](https://pipedream.com/support) we can help with any questions on the trigger / action development.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
