### ISSUE TITLE
[FEATURE] add tweeter developer app yo get retweet

### ISSUE THREAD

**Issue by gauloics** [PipedreamHQ/pipedream#1588]
user authentication is more restricted than app authentication

**Comment by dylburger** [comment]
@gauloics did you see that we provide a [**Twitter Developer App** integration](https://pipedream.com/docs/apps/twitter/#twitter-developer-app-integration) that lets you enter your own app's credentials, where you would control the app's scopes?

Let me know if that helps or if you were asking about something different.

**Comment by gauloics** [comment]
Thanks, I'll try again later, the past few days have been a bit busy

**Comment by dylburger** [comment]
No worries. I’m going to close this issue for now, but if you have any questions on how the developer app integration works, please reach out at https://pipedream.com/community

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
