### ISSUE TITLE
supabase

### ISSUE THREAD

**Issue by SHACOIN-TOKEN** [PipedreamHQ/pipedream#1601]
https://app.supabase.io/

**Comment by todsac** [comment]
@SHACOIN-TOKEN - Here is a first version of the integration:  https://pipedream.com/apps/supabase

Please let me know if you would be interested in building the [sources](https://pipedream.com/docs/event-sources/) or [actions](https://pipedream.com/docs/components/actions) for this app.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
