### ISSUE TITLE
[SOURCE] Brex

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#1602]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
**New Transaction** | Triggers when a new transaction occurs

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developer.brex.com/openapi/accounting_api/#operation/getTransactions

Note: This endpoint supports both PENDING and POSTED transactions. For now, this endpoint will only return posted transactions. However, you should build against it assuming it returns both PENDING and POSTED.  It would nice to be able to handle this well as some users will only want one or both.

We have access to the API in staging so have the necessary credentials to get this up and running.

**Comment by dannyroosevelt** [comment]
We didn't build a trigger for transactions, but we have a trigger on new transfers, since what's the their webhook supports today.
