### ISSUE TITLE
Environment variables quota

### ISSUE THREAD

**Issue by muratmat** [PipedreamHQ/pipedream#161]
Because environment variables are a precious resource, it would be nice to have information on the current quota (i.e. something like "14k of 64k used" or "14k used / 50k free" or a classic colored fill bar showing the quota).

Thanks!

**Comment by dylburger** [comment]
@muratmat this limit is no longer in place - you can save well above `64KB` of total data across env vars, and we impose no direct limit on the sum of the size of env vars anymore. Closing this ticket as a result.
