### ISSUE TITLE
[FEATURE] A More Flexible Pipedream (no?)SQL Service for the 21st Century  

### ISSUE THREAD

**Issue by mtrontz-the-dev** [PipedreamHQ/pipedream#1614]
I was never any good at stringing together a logical SQL query for my life, and now I am unsure what to do. The convenience of being able to load all of my data that flows through pipedream into a database hosted on the same platform is extremely valuable to myself, as well as my partners and clients, and the only bottleneck is having to manually type out SQL like its 1999! As a feature request, can you possibly provide prebuilt queries or some kind of GUI with buttons and dropdowns as opposed to relying on the users own SQL knowledge? Better yet, why query at all? You could leave that as an option, but since all data is imported as JSON anyways, is it possible to have an option to visually explore the data in the same way Firebase Databases do? (Firestore & Realtime DB by far my favorite to use right now!) I hope this suggestion is helpful in some way! Maybe others who are not as skilled in SQL like myself could agree/share their thoughts?

**Comment by dylburger** [comment]
@mtrontz-the-dev if we had a seamless integration with Firebase databases (for example), where you could easily write / read data from there, would that work for you?

We would prefer to improve our integrations with the best-in-class databases for two reasons:

* They already provide most of the functionality you need, and will continue innovating better than we could.
* Different users have different needs for databases, so it's difficult to solve the needs of all users with a single product.

The good news is, we plan to continue to tighten the integrations with partners to make it as simple as possible to work with them (hence my original question). So if you have advice on how we could simplify that integration, let me know.

We also plan to improve the capabilities of workflow storage (for example, [we plan to support reading / writing to a shared key-value store](https://github.com/PipedreamHQ/pipedream/issues/192), across workflows, [like you can with `$checkpoint`](https://pipedream.com/docs/workflows/steps/code/state/)).

I'm going to close this issue for those reasons, but again I'd love to hear your feedback re: how we can improve the integrations with the databases you use, so feel free to keep commenting here.

**Comment by mtrontz-the-dev** [comment]
@dylburger 
I see your point here. As the main goal of the platform is seamless integration with other services, it would not make sense to have to rebuild functionality that is already available.
 I would certainly be satisfied with a Firebase Database integration, for sure, assuming that I would be able to see and manipulate the data from within pipedream. I am actually using Firebase separately right now, and my ultimate dream is to be able to use all of these amazing services that are offered within a single integrated platform. I know that you currently support the option to use ANY NPM package, as long as I am able to write the functions myself, so that is what I have been attempting to do.
For advice on how better to integrate with your current partners, I normally wouldn't presume to be in a position to offer advice (*blushing*), but in this case, my journey through the SaaS forest will come in handy. Are you familiar with a platform called Retool? I think when I suggested the SQL GUI, that is what I had in mind, but completely aside from the "GUI" aspect, (which on retool, left me wanting), the ability to connect multiple data stores, manipulate and display the data in ways that (almost) feel natural, and a very well thought out debugging terminal, I think that if you were able to take the best parts of that platform, combine it with your already very dense partner ecosystem, that would make for an incredible product. Come to think of it, is it possible to integrate Pipedream with Retool, even manually? I will explore this further and report back on that, but essentially that is my thought.
Anyways, I am really excited to continue developing my solutions on your platform, and I look forward to seeing you guys continue to grow. I am especially excited to hear of the shared key/value store! Thanks again for your help, and for the great service! I definitely will continue to bring my ideas forward, and hopefully at least some of them will make sense, lol.

**Comment by dylburger** [comment]
Yes, we are big fans of Retool. That's an interesting idea - we'll brainstorm more about it.

**Comment by malexanderlim** [comment]
Just wanted to let folks on this thread know that Retool has a basic integration built out as of today, and we will be developing triggers and actions shortly!
