### ISSUE TITLE
http://10.0.1.25:45501

### ISSUE THREAD

**Issue by tapas-kumar** [PipedreamHQ/pipedream#1616]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
@tapas-kumar did you mean to request a specific app integration?

**Comment by tapas-kumar** [comment]
I was trying to test the above url as part of CTF.

**Comment by dylburger** [comment]
That’s a service on your local network that Pipedream doesn’t have access to. You’ll need to use a service like ngrok to expose that service at a public, internet-addressable  URL.

Either way, this doesn’t sound like an app integration that we’d provide to all users (that’s the purpose of these issues), so I’m going to close this ticket. If you need more help setting up your workflow, please reach out at https://pipedream.com/community .
