### ISSUE TITLE
[ACTION] Sendgrid - Parse Inbound Email

### ISSUE THREAD

**Issue by SeanFeldman** [PipedreamHQ/pipedream#1617]
**Is there a specific app this action is for?**

SendGrid parse inbound email

**Please provide a link to the relevant API docs for the specific service / operation.**

https://github.com/sendgrid/sendgrid-nodejs/issues/482

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by michelle0927** [comment]
@SeanFeldman I wonder if instead of an action, this would be better as a source/trigger using an [Inbound Parse Webhook](https://docs.sendgrid.com/api-reference/settings-inbound-parse/create-a-parse-setting)? As an action, would the email be coming from a previous step in the workflow?

**Comment by SeanFeldman** [comment]
@michelle0927 that's what I've ended up going with. It works really well.
