### ISSUE TITLE
[APP] Coin market cap

### ISSUE THREAD

**Issue by BeeXD** [PipedreamHQ/pipedream#1623]
**Name of app / service**
Coin market cap
**Link to developer documentation**
https://coinmarketcap.com/api/documentation/v1/
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Nope

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Get the prices when it get rised or gets down

**Comment by dylburger** [comment]
@BeeXD thanks for the request. We have a CoinMarketApp integration [here](https://pipedream.com/apps/coinmarketcap). 

Were you specifically looking for CoinMarketCap triggers (run a workflow any time a price changes)?

**Comment by BeeXD** [comment]
> 
> 
> @BeeXD thanks for the request. We have a CoinMarketApp integration [here](https://pipedream.com/apps/coinmarketcap).
> 
> Were you specifically looking for CoinMarketCap triggers (run a workflow any time a price changes)?

Ah thanks i could not find. Thamls
