### ISSUE TITLE
[APP] Process.St

### ISSUE THREAD

**Issue by bsommardahl** [PipedreamHQ/pipedream#1624]
**Name of app / service**
Process Street / Process.st

**Link to developer documentation**
https://developer.process.st/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I can't build workflows without the ability to trigger from tasks in my Process.St workflows

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Triggers:
- Workflow run started
- Task Checked

Actions:
- Run workflow
- Find workflow run
- Update workflow run

**Comment by todsac** [comment]
@bsommardahl - Here is the base version of the integration: https://pipedream.com/apps/process-street.  Can you test and confirm this works for you?

Would you be interested in building out the triggers or actions?

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
