### ISSUE TITLE
[TRIGGER] Slack New User

### ISSUE THREAD

**Issue by bsommardahl** [PipedreamHQ/pipedream#1626]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Slack's API exposes access activity like logins. It's useful sometimes to trigger off of someone's first login to run some welcome actions or log the activity in a database elsewhere. It will probably require some polling, but we could hit the `team.accessLogs` endpoint periodically to see if anyone's `date_first` is within the last few minutes and, if so trigger an event in Pipedream with user details.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://api.slack.com/methods/team.accessLogs

**Comment by dylburger** [comment]
@bsommardahl thanks for the request! We're working on support webhooks for these type of operations, which would expose a stream of real-time events for you to work with. That's on the backlog and will take a little bit of time to complete.

In the meantime, I think the polling approach you mention is sound, and would totally work. Did you know that [you can build your own sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/) and publish them for anyone on the platform to use? We'd love the help if you were keen to tackle it, and we're happy to support you in any way (we have a #contribute channel in our [public Slack](https://pipedream.com/support) where we can answer any questions).
