### ISSUE TITLE
[FEATURE] Reusable Steps

### ISSUE THREAD

**Issue by bsommardahl** [PipedreamHQ/pipedream#1627]
**Is your feature request related to a problem? Please describe.**
There are times when I either have to repeat a step or store a step behind a webhook trigger to be able to call it often. The problem with repeating steps by copy/paste is duplicate code that has to change in several places. Hiding behind webhooks works okay, but it doesn't allow me to re-use outputs.

**Describe the solution you'd like**
I would like to be able to save steps as "reusable" and be able to include them in future workflows. I'd like to change the code in my reusable step and that change affect all workflows that use it.

**Do you have a workaround?**
Yes, I can use workflows triggered by webhooks to encapsulate the logic.

**Comparable features in other tools?**
Not that I know of.

**Comment by dylburger** [comment]
@bsommardahl thanks for the request. Have you seen that you can [develop your own actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? That's the best way to create reusable code you can use across workflows.

I also keep code in a custom npm package that I publish and use on Pipedream. You can [read more about that option here](https://pipedream.com/docs/workflows/steps/code/nodejs/sharing-code/).

Does that help?

**Comment by bsommardahl** [comment]
@dylburger You're right that the option exists. I'm glad you mentioned it here... I will definitely use that option! 

On the other hand, since we're already setting up steps in the UI and customizing them, it would be great to have an option in the UI to save steps to a reusable library.

**Comment by dylburger** [comment]
@bsommardahl yes, I hear you. We're tracking that in #1249 if you'd like to follow there.
