### ISSUE TITLE
[FEATURE] Group workflows (will help to organize after creating many)

### ISSUE THREAD

**Issue by andre-brunetta** [PipedreamHQ/pipedream#1631]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to organize my workflows

**Describe the solution you'd like**
Possibility to create "folders" to group workflows by subject, function, similarity, etc.

**Comparable features in other tools?**
Simple UI to create folders and the possibility to drag and drop workflows to them

**Comment by dylburger** [comment]
Hi @andre-brunetta , we're tracking at #203 if you'd like to follow there.

**Comment by andre-brunetta** [comment]
That's great, thanks @dylburger 🙏
