### ISSUE TITLE
Paypal

### ISSUE THREAD

**Issue by adgower** [PipedreamHQ/pipedream#1641]
**Name of app / service**
Paypal

**Link to developer documentation**
https://developer.paypal.com/docs/api-basics/notifications/webhooks/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have a work around.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
