### ISSUE TITLE
[APP] Freshstatus

### ISSUE THREAD

**Issue by nerdyjohnny** [PipedreamHQ/pipedream#1643]
Freshstatus

https://support.freshstatus.io/support/solutions/articles/50000003646-freshstatus-api-documentation#List-Incident-updates-by-Incident-ID

Unable to work around

Able to request Incidents and their status as long with Scheduled Maintenaces

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by todsac** [comment]
@nerdyjohnny - Here is a first version of the integration:  https://pipedream.com/apps/freshstatus.  Can you test and confirm it works for you?  Also, are you interested in building out the sources and actions for this app?

**Comment by nerdyjohnny** [comment]
The integration is able to connect to the API successfully! Im slowly working on trying to get it to execute with my workflow successfully.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
