### ISSUE TITLE
[BUG] $checkpoint not being updated correctly (intermittent)

### ISSUE THREAD

**Issue by andre-brunetta** [PipedreamHQ/pipedream#1647]
I've been using $checkpoint for a while now in most of my workflows, but recently (last few days) I've noticed a (new) bug where it doesn't gets updated correctly. It's intermittent (couldn't find a pattern) but it's happening consistently.
Does anyone noticed something like that in the last few days?

**Comment by dannyroosevelt** [comment]
It sounds like maybe this was resolved with limiting the concurrency on the trigger, but let me know if not! Slack convo for context: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1630432664088100?thread_ts=1630397814.069800&cid=CPTJYRY5A

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
