### ISSUE TITLE
[FEATURE] Allow editing event before re-emitting

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#1650]
It would be great if I could right click an event in the sidebar and edit the event properties before re-running it:

![CleanShot 2021-09-01 at 09 40 42@2x](https://user-images.githubusercontent.com/27538/131632242-a063ca08-ae8c-4ec4-be41-c0b875e9c7a0.png)

My current workaround is to copy the JS value, edit it and send as a curl event to the workflow's endpoint (although this doesn't always work if I have a Source as a trigger)

**Comment by dylburger** [comment]
Yes makes total sense. We're tracking this in #175 if you don't mind following there.
