### ISSUE TITLE
doc on CJS and ESM packages

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#1654]
context: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1630612654012700?thread_ts=1630602896.008900&cid=CPTJYRY5A

**Comment by cfjedimaster** [comment]
My 2 cents, even a rough, "This is in flux" doc would be really good. I bet this is going to hit people quite a bit and pretty soon.

**Comment by dylburger** [comment]
Take a look at https://pipedream.com/docs/workflows/steps/code/#commonjs-vs-esm-imports and let me know if that helps

**Comment by cfjedimaster** [comment]
I think this is great - thank you! (Because I know I'll forget and need it later. ;)
