### ISSUE TITLE
Airtable cronjob won't stop

### ISSUE THREAD

**Issue by Gecky** [PipedreamHQ/pipedream#1658]
**Describe the bug**
The cronjob related to Airtable's trigger "New Records in View" won't stop.

**To Reproduce**
1. Create an Airtable "New Records in View" trigger.
2. Set schedule to one minute.
3. Try to pause the workflow, the step trigger or the source (in the latter the "pause" won't work)
4. You will still see the calls from the workflow and the quota going down.

**Expected behavior**
The cronjob should stop in all these occurrences:
+ Paused workflow
+ Disabled step trigger in workflow
+ Paused the source

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave

**Temporary solution**
Just set the cron to once a month since I didn't want to delete the workflow.

**Comment by dylburger** [comment]
@Gecky would you mind emailing your Pipedream username to support@pipedream.com? I'd like to take a look at the resources in your account to review this issue more.

**Comment by dylburger** [comment]
Since we're discussing this issue over email, I'm going to close this issue
