### ISSUE TITLE
[BUG] Thumbnails cannot be set using youtube api (Quota exceeded, always)

### ISSUE THREAD

**Issue by zvictor** [PipedreamHQ/pipedream#1661]
I have a [workflow](https://pipedream.com/@folkwisdom/dailyemotions-upload-p_BjCA6Ar) with the following steps:
1. a video and an image are fetched from GDrive
2. the video is uploaded to youtube
3. the image is set as the thumbnail of the video

Steps 1 and 2 work well but 3 fails with `request cannot be completed because you have exceeded your quota`.
That's very weird because **there is enough quota to upload the video multiple times but there is no quota to set the thumbnail once**!

![image](https://user-images.githubusercontent.com/181076/132328008-075731ee-bb85-4844-aa97-30423aa6e06e.png)

Notes:
* After trying multiple times, step 2 also started throwing the quota error. I waited for 24h and then only step 3 started failing again.
* I also posted in the [forum](https://pipedream.com/community/t/exceeded-quota-in-youtube-steps/1183).
* The account is new and I haven't run the workflow exhaustively:
![image](https://user-images.githubusercontent.com/181076/132329653-72b2da48-9d5f-4b85-b19d-a67591dd15f5.png)

**Comment by dylburger** [comment]
@zvictor we should have raised the YouTube per-user quota enough to let you perform both operations (more details from @dannyroosevelt [in the Discourse thread](https://pipedream.com/community/t/exceeded-quota-in-youtube-steps/1183/2
). I'm going to close this issue out so we can continue the discussion there.
