### ISSUE TITLE
[BUG] sources/new-message/new-message.js (editable)

### ISSUE THREAD

**Issue by gauloics** [PipedreamHQ/pipedream#1681]
app twitter developer, to receive DM events, why is the message I sent also showing up. isn't it already filtered as in the attachment
![IMG_20210910_092605](https://user-images.githubusercontent.com/742131/132789974-a774241a-328d-4605-a04b-e2bf6ed183a0.jpg)

**Comment by dylburger** [comment]
@gauloics just to confirm, are you saying that messages you send also show up when you run the source?

I'm not able to reproduce on my end. Just to confirm, are you sending messages from the account that owns the Twitter Developer app? Those are the only messages this source will filter out.

If you'd like, you can also modify the source code to filter out any other messages, from any other specific users. That might be the best approach here.

Let me know if that helps.

**Comment by gauloics** [comment]
I use another user account that has been authenticated by the app
So, how to filter outgoing messages?

**Comment by dylburger** [comment]
You can add a line in the Node.js code just below the line you highlighted to read:

```javascript
&& directMessage.message_create.sender_id != "<your account id here>"
```

you can find your account ID [using a tool like this](https://codeofaninja.com/tools/find-twitter-id/).
