### ISSUE TITLE
[APP] Tumblr

### ISSUE THREAD

**Issue by enigmalea** [PipedreamHQ/pipedream#1688]
**Name of app / service** Tumblr

**Link to developer documentation** https://www.tumblr.com/docs/en/api/v2

**Is lack of support preventing you from building workflows, or do you have a workaround?** Lack of support is preventing me from building workflows.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Simply interested in posting to tumblr automatically right now (I want to build a workflow from twitter to tumblr).

Eventually, it would be amazing if I could have a workflow that automatically detected mentions on tumblr which then sent the post where a blog was mentioned into drafts or queue.

**Comment by todsac** [comment]
Here is a first version of the integration - https://pipedream.com/apps/tumblr

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration

**Comment by sydstarwave** [comment]
I'm particularly new at using Pipdream, but it doesn't seem possible to use Tumblr as a source, am I missing something?

**Comment by dylburger** [comment]
Hi @sydstarwave yes, we don't yet have any Tumblr sources. This ticket tracked the [base app integration](https://pipedream.com/apps/tumblr), which allows you to connect to the Tumblr API from workflows. Sources and actions are built separately. 

Did you know that [anyone can author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.
