### ISSUE TITLE
[APP] Notion as a Trigger

### ISSUE THREAD

**Issue by 0x161e-swei** [PipedreamHQ/pipedream#1691]
**Name of app / service**
Notion

**Link to developer documentation**
https://developers.notion.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Precent from building auto database updates based on new database modifications.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Use notion database changes as a trigger of a workflow.

**Comment by dylburger** [comment]
@0x161e-swei believe it or not, we have a PR in progress for Notion sources! Please follow [this issue](https://github.com/PipedreamHQ/pipedream/issues/1228) for updates.
