### ISSUE TITLE
[APP] Minio 

### ISSUE THREAD

**Issue by saggiyogesh** [PipedreamHQ/pipedream#1695]
Option to use [mioio](https://minio.io/) as Destination.

**Comment by dylburger** [comment]
@saggiyogesh is there a specific min.io API you'd like to connect to? I didn't see docs for an HTTP API, so I wanted to ask if there was another integration you needed to use.

Are there specific min.io operations you'd like to perform?

**Comment by saggiyogesh** [comment]
Minio's APIs are S3 compatible. Minio is self hosted block storage library, compatible with AWS S3.

**Comment by dylburger** [comment]
Thanks. Would your ideal integration provide a way for you to enter an AWS access / secret key, and then connect to Minio via [their npm package](https://www.npmjs.com/package/minio), like this?

```javascript
var Minio = require('minio')

var minioClient = new Minio.Client({
    endPoint: 'play.min.io',
    port: 9000,
    useSSL: true,
    accessKey: <access key>,
    secretKey: <secret key>
});
```

I had another question, too: does Minio provide the option to self-host? Or is the `endPoint` specific to your account, or different for different users?

**Comment by saggiyogesh** [comment]
Yes, we may self host it, docker image is available . Endpoint is our choice.

**Comment by dylburger** [comment]
Thanks, this is on the backlog and I'll let you know when it's done.

**Comment by sergio-eliot-rodriguez** [comment]
Sorry for the delyar @saggiyogesh , Minio has been integrated https://pipedream.com/apps/minio
