### ISSUE TITLE
[APP] Bridge API (by Bankin)

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#1698]
**Name of app / service**
Bridge API

**Link to developer documentation**
https://docs.bridgeapi.io/reference

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Lack of support is not preventing me from building the workflows, I just don't have enought time. I'll try to do it soon...

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- Triggers/Sources
  - New transaction
- Actions
  - List transactions

**Comment by todsac** [comment]
Luc - We are working on this integration.  Are you open to test it with us?  If so, are can you DM me on [Slack](https://pipedream.com/support)?

**Comment by LucBerge** [comment]
The reason I wanted to use Bridge API is because they provide easy acces to hundreds of bank APIs. But after signing up I realized that it is a 30 day free trial and I won't pay. I will instead use my free bank API : https://developer.lcl.fr/catalog
