### ISSUE TITLE
[App] Padlet

### ISSUE THREAD

**Issue by rrcobb** [PipedreamHQ/pipedream#1699]
**Padlet**

**link to docs**

- https://padlet.readme.io/docs/getting-started (looks deprecated 😞 )
- https://padlet.helpdocs.io/l/en/backpack-for-schools/how-to-add-padlet-to-lms-1p3 

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Yes. I'm not totally sure if there's an API to hit, I have not found a workaround.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

- when a student responds to a padlet, I'd like to be able to get the content and metadata from that post and use it in further workflows (e.g. batch these up and send me summaries in Discord or Slack)
- I don't know yet exactly what I'd do with automatic creation of Padlets or responses, but I figure that'd be awesome, and I'd figure out a use for it.

This might be one to close out, it looks like Padlet has deprecated the API, so it could be unstable anyway. 😭

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
