### ISSUE TITLE
CGC Census Data[TRIGGER]

### ISSUE THREAD

**Issue by Uatu-The-Watcher** [PipedreamHQ/pipedream#1701]
CGC Census Data

**Comment by dylburger** [comment]
@Uatu-The-Watcher can provide a few more pieces of information?

- A link to the API docs of the service?
- What specific event(s) do you want the trigger to operate on? In other words, what data is the service producing that you want to listen for?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
