### ISSUE TITLE
[TRIGGER] Google Calendar timer

### ISSUE THREAD

**Issue by MarLarsen** [PipedreamHQ/pipedream#1712]
Would be nice if you could post a list of todays events from a google calendar to a discord channel at either midnight or another specific time.

**Comment by dylburger** [comment]
@MarLarsen this should be possible with [the following workflow](https://pipedream.com/@dylan/get-events-from-today-p_KwCwqKB/edit). I've pulled all calendar events for the current day, returning them in the Google Calendar step.

You can add a step to your workflow and search for **Discord Webhook**, where you'll find actions to send messages to a Discord channel.

If you need more help on this workflow, I'd suggest reaching out in our community at https://pipedream.com/community !
