### ISSUE TITLE
eversign

### ISSUE THREAD

**Issue by hardspoon** [PipedreamHQ/pipedream#1725]
eversign

https://eversign.com/api/documentation

Create Document
Create Template
Use Template
Get Document/Template
List Documents
List Templates
Send Reminder

**Comment by todsac** [comment]
@hardspoon - here is the base version of the Eversign integration - https://pipedream.com/apps/eversign

Are you interested in adding the triggers or actions?

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
