### ISSUE TITLE
Sorting of env variables

### ISSUE THREAD

**Issue by muratmat** [PipedreamHQ/pipedream#173]
Because my workflows are getting bigger and bigger, I ended up with lot of environment variables (API keys, external services end-points urls, and so on).

I would suggest, within "Settings" section, to have such env variables sorted by name (ascending and/or descending). Because it is getting really hard to find the right env variable while I'm writing new code, it would be really nice to have an arrow icon (up/down) that implements the sorting, like in the workflows list.

Many thanks!

**Comment by dylburger** [comment]
@muratmat @mfabbri77 this is implemented in the new environment variables UI we just shipped!
