### ISSUE TITLE
[BUG] When editing a workflow and changing the source, it's possible to lose your changes

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#1736]
**Describe the bug**
I have an existing workflow with a source. I removed that source and added the Twitter Search source. I configured it, and because I saw it first, I hit *Deploy*, not create. This deployed the workflow w/o a source and I lost my configuration.

**To Reproduce**
As above, I think it's pretty clear. ;)

**Expected behavior**
Make the Deploy operation either prompt the user to Create the source or have it automatically create it.

**Comment by dylburger** [comment]
@cfjedimaster I believe this specific UX is a little more clear in the new workflow builder. We now grey out the Deploy option while you're configuring your source, before you create it:

<img width="186" alt="Screen Shot 2022-02-22 at 11 08 29 AM" src="https://user-images.githubusercontent.com/242668/155201777-b0b6498a-559e-4c18-b366-c4bcb6aad5c4.png">
