### ISSUE TITLE
[BUG] Ghost - Member Created source fails to deploy

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1758]
When I create the **Ghost** -> **Member Created** event source, I observe the following error

<img width="850" alt="Screen Shot 2021-10-04 at 5 12 19 PM" src="https://user-images.githubusercontent.com/242668/135940957-ea7d31e8-4e17-4a03-b5fa-b667abfa4f19.png">

**Comment by russkiimike** [comment]
Bump as I am having the same issue

**Comment by dannyroosevelt** [comment]
the original issue is resolved! looks good to me.

**Comment by russkiimike** [comment]
Awesome! Seems to work, gonna try and setup a workflow now.
