### ISSUE TITLE
I want to filter events in my inspector for a workflow so I can view all events that yielded an error

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#176]
Some workflows trigger errors with a high frequency, since they hit unreliable APIs. Or I might receive messy source data, which triggers errors because it's not of the expected format.

I already get notified of these errors, but when I visit my workflow, I need to quickly filter on errors so I can see them in one place. This lets me easily replay them one by one.

**Comment by ctrlaltdylan** [comment]
You can use the **Event History** feature to filter by status & filter by a single workflow. I would say this resolves this request.
