### ISSUE TITLE
I'd like a list of public IP addresses tied to traffic sent from my workflow

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#178]
For example, I'd like to query a Postgres DB from a workflow, and I need to add a network ACL to expose port 5432 to a limited set of IPs. So I'd like to know the IP address(es) from which the request will come.

Ideally, this would be provided in a publicly-accessible data exchange format (for example, [AWS provides theirs as a JSON doc](https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html)), so I can update firewall or network rules programmatically.

**Comment by tommyrowe** [comment]
hey @dylburger! any plans to restrict mySQL requests to a set array of IPs? I'm ready to take a crack at the bastion server solution, but just wanted to ask with crossed fingers and toes first 😅

**Comment by dylburger** [comment]
@tommyrowe We're working on this right now! Still in the early phases, but we'll announce here when it's ready to test.

**Comment by tommyrowe** [comment]
copy that @dylburger. happy to help test in the wild when the time comes. thanks for the reply and update!

**Comment by heynando** [comment]
i need whitelist ips for binance api trading which only allows whitelisted ips to trade

**Comment by renattomachado** [comment]
+1

**Comment by FigmentNathan** [comment]
+1

**Comment by alexjordi** [comment]
+1

**Comment by mperzov** [comment]
+1

**Comment by jingconan** [comment]
+1, this feature is very important for us. We need to whitelist IP and use PipeDream to issue MySQL queries.

**Comment by Vince-GMG** [comment]
+1

**Comment by gregonarash** [comment]
@dylburger +1, lack of fix IPs was causing a major debate about potential implementation of Pipedream in corporate project. Some dev ops people operate single whitelisted IPs added to security groups.  I would say this clearly will convert into adoption, by bigger entities.

**Comment by dylburger** [comment]
@gregonarash @Vince-GMG @jingconan @mperzov @alexjordi @renattomachado Thanks for all the feedback. We just implemented virtual private clouds (VPCs) for our [Business customers](https://pipedream.com/pricing). You can dedicated VPCs in Pipedream and configure specific workflows to run in that network. The VPC is unique to your workspace — no other customer workflows will run there — and it has a unique egress IP that you can whitelist on your firewalls. A lot of customers wanted truly dedicated egress IPs so they could ensure no other traffic would originate from that IP, so we decided to start here.

If you're interested in, please email me at dylan [at] pipedream [dot] com and I can help set this up on your workspace. We can also offer monthly billing for the Business plan if the annual option on the site isn't an option — just let me know when you reach out.

**Comment by dylburger** [comment]
This is live! https://pipedream.com/docs/workflows/vpc/
