### ISSUE TITLE
[APP] Amara

### ISSUE THREAD

**Issue by joelmiles** [PipedreamHQ/pipedream#1783]
**Amara**

**https://apidocs.amara.org/**

**Currently using the HTTP / Webhook action and the Amara API guide to build actions by hand.  It's not as user-friendly, but it works.**

**The action I could make the most use of right away is "Add a video" (https://apidocs.amara.org/#add-a-video).  On the receiving/notification side, the "subtitles-published" (https://apidocs.amara.org/#video-notifications) would be the most useful to me currently.**

**Comment by dannyroosevelt** [comment]
@joelmiles FYI this work is in progress now -- check out this issue to track the progress and to see what actions and triggers we're intending to build out. Feel free to comment on that issue if you have any specific feedback! https://github.com/PipedreamHQ/pipedream/issues/1788
