### ISSUE TITLE
[ACTION] Amara actions

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#1788]
https://apidocs.amara.org/

- "Add a video" (https://apidocs.amara.org/#add-a-video). 
- "Subtitles-published" (https://apidocs.amara.org/#video-notifications) 
- ...anything else?

**Comment by joelmiles** [comment]
Another action that I'm using today which would be great to have codified is "Fetch raw subtitles" (https://apidocs.amara.org/#fetch-raw-subtitles).  Any chance that could be added?

**Comment by dannyroosevelt** [comment]
@jcortes while you're working on this can you also add that additional action?

**Comment by dannyroosevelt** [comment]
I just requested access to Amara's Enterprise plan so we can test the dependent endpoints.

**Comment by joelmiles** [comment]
I have an Enterprise account so if that's useful for helping move anything along quicker, I'm happy to assist where I'm able.  There's probably no substitute for seeing the real data in your own environment, but if there's utility in me helping by using our account, let me know what you'd like me to do.

**Comment by dannyroosevelt** [comment]
@joelmiles that'd definitely be helpful! Especially since you'll actually be using these 😄 

If you're able and willing, the easiest way to test this out is to,
1. Checkout the linked PR: `gh pr checkout 1875` 
2. To test a source, see here: https://pipedream.com/docs/components/api/#managing-sources
3. To test an action, see here: https://pipedream.com/docs/components/api/#managing-actions

I'll continue working on getting access to an Enterprise plan so we can help test, but your feedback is definitely appreciated and valued!

**Comment by dannyroosevelt** [comment]
@joelmiles we've just published the Amara [triggers](https://pipedream.com/apps/amara#popular-amara-triggers) and [actions](https://pipedream.com/apps/amara#popular-amara-actions).

Can you please go ahead and try them out and let us know if you run into any issues or if you have any feedback?

Thanks!
