### ISSUE TITLE
[APP] bit.io

### ISSUE THREAD

**Issue by steamystreams** [PipedreamHQ/pipedream#1793]
**Name of app / service**
Bit.io
**Link to developer documentation**
https://docs.bit.io/docs/connecting-via-nodejs
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Have workaround
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
@steamystreams here you go -- https://pipedream.com/apps/bit-io

Let us know if you have any questions getting started!
