### ISSUE TITLE
[APP] PDF.co

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#1794]
**Name of app / service**
PDF.co
**Link to developer documentation**
https://pdf.co/rest-web-api
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
https://pipedream.com/apps/pdf-co
