### ISSUE TITLE
[WhatsApp integration via Online Live Support]

### ISSUE THREAD

**Issue by harismateen** [PipedreamHQ/pipedream#1800]
**Name of app / service**
WhatsApp
**Link to developer documentation**
https://www.getpostman.com/collections/a2656e80b38da6edacce

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Would like to send whatsapp notification

**Comment by harismateen** [comment]
> @hamermike thank you for your request. one favor, can you please provide a better documentation url? check out this one for telegram: https://core.telegram.org/api#getting-started the link you provided is a description of the available methods in the integration, but it misses key information such as how to authorize a user, which authorization protocol to use, which scopes are required for each integration method, and so on. i would appreciate if you provide the actual developer or api documentation link for the app you want integrated, where a postman collection you provided would be just a part of it.

thanks, I have emailed you the details, pls do inform if you didn't receive it

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by harismateen** [comment]
> Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

Hi, I have emailed details earlier to Sergio, I just sent Dylan also to his gmail address, could you please check'?

**Comment by dylburger** [comment]
@harismateen yes I apologize, this was closed by mistake. @sergioeliot2039 do you have enough information to do the integration, or do you need anything else?

**Comment by sergioeliot2039** [comment]
@dylburger the information that @harismateen looks complete, however maybe I will be reaching out as I make process. also will reach out for prioritization internally for the other pd tasks i have ongoing, but yes, definetely on my backlog.

**Comment by harismateen** [comment]
> @dylburger the information that @harismateen looks complete, however maybe I will be reaching out as I make process. also will reach out for prioritization internally for the other pd tasks i have ongoing, but yes, definetely on my backlog. 

Thanks, pls feel free to drop me an email, may i check how long you need to add the Online Live Support there?

**Comment by sergioeliot2039** [comment]
for triage, i am posting here these details for implementation that @harismateen  sent me, I'm hiding the password though.

> As per the discussion over github issues, pls find the credentials below and API docs -
> github: https://github.com/PipedreamHQ/pipedream/issues/1800
> Basically we are alternative of Chat API, and we would like to offer our users to use pipedream as well while using WhatsApp integration via Online Live Support
> Credentials:
> https://api.online-live-support.com/
>  Username: demo-account
>  Pass: **hidden**
>  API Docs: https://api.online-live-support.com/apidoc.php
>  Guide: https://docs.online-live-support.com/

**Comment by dannyroosevelt** [comment]
Got it, thanks Sergio.

@harismateen here is a basic framework for the integration: https://pipedream.com/apps/online-live-support

Can you please let me know if you have a higher quality logo and a description we can use? 

Regarding enabling specific Actions and Triggers for customers to use, Pipedream is open source -- if you're interested in building out the integration, I recommend [starting here](https://pipedream.com/docs/components/quickstart/nodejs/actions/#quickstart-action-development).

**Comment by harismateen** [comment]
> Got it, thanks Sergio.
> 
> @harismateen here is a basic framework for the integration: https://pipedream.com/apps/online-live-support
> 
> Can you please let me know if you have a higher quality logo and a description we can use?
> 
> Regarding enabling specific Actions and Triggers for customers to use, Pipedream is open source -- if you're interested in building out the integration, I recommend [starting here](https://pipedream.com/docs/components/quickstart/nodejs/actions/#quickstart-action-development).

Great - 
Can you put 
"Thanks, 
Can you put the name as WhatsApp by Online Live Support?"
Can i get your email?

**Comment by dannyroosevelt** [comment]
I've updated the name. If you need additional support feel free to comment here or explore our community at pipedream.com/support.

**Comment by harismateen** [comment]
Thanks  - i have added logo here as well - 
<img width="214" alt="online-live-support-Whatsapp-CRM-solution" src="https://user-images.githubusercontent.com/38554929/141063680-42470715-d28d-4d41-84f6-cd4caceedc46.png">

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
