### ISSUE TITLE
[BUG] Not able to select a 0 integer option from props

### ISSUE THREAD

**Issue by jcortes** [PipedreamHQ/pipedream#1807]
**Describe the bug**
I'm not able to select an option from props when the `value` of that is `integer` `0`

**To Reproduce**
1. Create an action with prop type `integer`
Something like this
```
export default {
  key: "my_app-select-type",
  name: "Select a type",
  description: "Select a type",
  type: "action",
  version: "0.0.1",
  props: {
    type: {
      type: "integer",
      label: "Type",
      description: "Please select a type.",
      options() {
        return [
          {
            label: "Text",
            value: 0,
          },
        ];
      },
    },
  },
  async run() {
    return {};
  },
};
```

2. Then publish it with your own account
3. Test it like in the screenshot

**Expected behavior**
I would expect to select the option with integer `0` as the `value`.

**Screenshots**
https://user-images.githubusercontent.com/506051/137963337-83b33d31-a334-42e0-9db7-28a8af2c969c.mov

**Desktop (please complete the following information):**
 - OS: macOS BigSur 11.6 (20G165)
 - Browser: Chrome
 - Version: 94.0.4606.81 (Official Build) (arm64)

**Comment by dylburger** [comment]
Confirmed, thanks for raising @jcortes

**Comment by dylburger** [comment]
@jcortes Could you check to see if this is still an issue in the new workflow builder?

**Comment by jcortes** [comment]
> @jcortes Could you check to see if this is still an issue in the new workflow builder?

@dylburger this has been fixed, thanks!
