### ISSUE TITLE
[BUG] The application is not validating min and max range

### ISSUE THREAD

**Issue by vellames-turing** [PipedreamHQ/pipedream#1812]
**Describe the bug**
The application is not validating the min and max props. The app shows a message asking for the specified range, but it does not validate it. The user can insert a value outside of the min and max range, as can be seen in the screenshot

**To Reproduce**
1. Go to any action/source with props with min/max
2. Input a value outside the range
3. See error

**Expected behavior**
The application should not allow the user to insert values outside of the property range

**Screenshots**
![Screen Shot 2021-10-13 at 5 09 04 PM](https://user-images.githubusercontent.com/91911778/138004231-f01d9811-64b4-4bb0-9ed5-c2aadcc37b0e.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.3.1
 - Browser: Chrome
 - Version: Version 94.0.4606.81 (Official Build) (arm64)

**Component Example**
https://pastebin.com/raw/eXfWimjr

**Comment by dylburger** [comment]
Thanks. It looks like we're highlighting the field in red, but still allowing deploy, so we need to address that UX:

<img width="598" alt="Screen Shot 2021-10-19 at 6 58 57 PM" src="https://user-images.githubusercontent.com/242668/138015312-91411ebf-3878-41bb-81b2-f4c3182f8dbd.png">

**Comment by dylburger** [comment]
@vellames-turing Could you check to see if this is still an issue in the new builder?

**Comment by dylburger** [comment]
@vellames-turing This is out in production now! Try publishing the component and adding it as a step in the new workflow builder.
