### ISSUE TITLE
[APP] Confection

### ISSUE THREAD

**Issue by areknawo** [PipedreamHQ/pipedream#1817]
**Name of app/service**

[Confection](https://confection.io/)

**Link to developer documentation**

The authentication is currently based on 2 keys:
- *Account Id*
- *Secret key*

**Is lack of support preventing you from building workflows, or do you have a workaround?**

We have a workaround, so not really. However, we want to make Confection integration easy for Pipedream users, so an app and entry in Pipedream's marketplace is necessary.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

We already have 3 triggers, and 2 actions developed and pretty much ready to be submitted. Currently, they receive the keys through secret props, but that's suboptimal for end users. When the app's ready, we'll connect properly and test it with our components to then submit PR.

**Comment by dannyroosevelt** [comment]
@areknawo we got Confection integrated into Pipedream: https://pipedream.com/apps/confection

Let us know if you have any questions and if we can help with any of your component development!

**Comment by getconfection** [comment]
Hi, there: Could we change our description from: 

_Confection is a new kind of product: a data generator for the privacy-first world._

... to:

_Confection collects, stores, and distributes data in a way that's unaffected by client-side disruptions involving cookies, cross-domain scripts, and device IDs. It's also compliant with global privacy laws so it’s good for people too._

Thank you very much.

cc: @areknawo

**Comment by dylburger** [comment]
@getconfection done: https://pipedream.com/apps/confection . Let us know if you need anything else.

**Comment by studiohypersetadmin** [comment]
Appreciate the quick response!

**Comment by getconfection** [comment]
Sorry, one last thing. We've prepared this quick-start guide that gives a bit of context:

https://confection.io/quick-start/pipedream/

Could we add that to the Authentication section? Perhaps something like:

_Find your account ID and API keys here: https://dashboard.confection.io/my-keys Need an account? Using Confection for the first time? Please see our quick-start guide: https://confection.io/quick-start/pipedream_

**Comment by dannyroosevelt** [comment]
No problem, this is done:
![image](https://user-images.githubusercontent.com/20780753/140106754-aa28ef0d-5a77-4152-934b-d6c02098fabb.png)

**Comment by dannyroosevelt** [comment]
Also present on the Confection app page here: https://pipedream.com/apps/confection#authentication

**Comment by getconfection** [comment]
Thanks!
