### ISSUE TITLE
[APP] Gmail

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#182]
I'd like to run Gmail actions as workflow steps, e.g. I'd like to send a new email or attach a label to an email using Pipedream.

**Comment by chetanmadaan** [comment]
+1

**Comment by crwallace** [comment]
+1

**Comment by dannyroosevelt** [comment]
This is in progress here: https://github.com/PipedreamHQ/pipedream/issues/4064

**Comment by dannyroosevelt** [comment]
We just shipped a Gmail integration!
https://pipedream.com/community/t/gmail-is-now-available-on-pipedream/3269
