### ISSUE TITLE
[APP] CloudBees Feature Management

### ISSUE THREAD

**Issue by logandonley** [PipedreamHQ/pipedream#1827]
**Name of app / service**
CloudBees Feature Management

**Link to developer documentation**
https://docs.cloudbees.com/docs/cloudbees-feature-management-rest-api/latest/introduction

There is also a Postman workspace for the API: https://www.postman.com/cloudbees/workspace/cloudbees-feature-management/overview

**Is lack of support preventing you from building workflows, or do you have a workaround?**
The built-in HTTP call functionality works as a workaround. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Having an action that could set the state of a feature flag based on whatever incoming event would be useful. This would allow workflows where I could receive an event and trigger a change to my live application based on the input.

Using curl, this can be accomplished like this:
```shell
curl --request PUT \
  --url https://x-api.rollout.io/public-api/applications/{applicationId}/{environmentName}/flags \
  --header 'authorization: Bearer {myBearerToken}' \
  --header 'content-type: application/json' \
  --data '{"name":"myFlagName", "enabled":true}'
```

A few details
* Each user has a user token which is used for the bearer token. 
* Each application has an id that is used in the URL path
* Each application can have multiple environments, by default each has one called "Production"
* Each application can have many flags, so in the data body the name is passed as well as the desired boolean state.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
