### ISSUE TITLE
[BUG] clunky UX when selecting item from dropdown list w/ query async options

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#1829]
The selected item is shown really wide, and the user-entered text is displayed all the way to the right.

https://capture.dropbox.com/3znpcxBV4CnCg7eY

**Comment by dylburger** [comment]
@dannyroosevelt Is this solved in smurt?

**Comment by dannyroosevelt** [comment]
Sure is!
