### ISSUE TITLE
[TRIGGER] GMAIL

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#183]
I'd like to run workflows on Gmail events, e.g. when a new email arrives in my Inbox.

**Comment by dannyroosevelt** [comment]
@vellames-turing this is currently blocked on our end right now unfortunately

**Comment by dannyroosevelt** [comment]
We shipped a Gmail integration!
https://pipedream.com/community/t/gmail-is-now-available-on-pipedream/3269
