### ISSUE TITLE
[BUG] helper text for query option empty state is confusing

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#1830]
Right now we show "No matching options" when displaying the dropdown for `query` async option before the user has entered a search query, which is confusing. We should change it to something more helpful like, "Type abc to xyz" based on the specific prop.

**Comment by dylburger** [comment]
@dannyroosevelt Has any of this improved since smurt? Should we reframe the ticket to capture improvements to the component API to support the "Type abc to xyz" use case?

**Comment by dannyroosevelt** [comment]
https://github.com/PipedreamHQ/pipedream/issues/2298
