### ISSUE TITLE
[TRIGGER] Coinbase Transactions

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1832]
* Source: New Transactions ([see this API endpoint](https://developers.coinbase.com/api/v2#list-transactions))

See [this Slack thread](https://pipedream-users.slack.com/archives/CMN2V5EAF/p1634948439002600) for context.

**Comment by vunguyenhung** [comment]
Hello @dylburger @dannyroosevelt, I (and also @jcortes) couldn't test this ticket because Coinbase doesn't support Trade in my country. Could you advice what we should do to proceed?

**Comment by dannyroosevelt** [comment]
> Hello @dylburger @dannyroosevelt, I (and also @jcortes) can't test this ticket because Coinbase doesn't support Trade in my country. Also we might need to make actual transaction (with money involve) to test this e2e. Could you advice what we should do to proceed?

No worries, Leo -- I'm okay to ship this and we can monitor usage to see if users run into any issues.
