### ISSUE TITLE
I want to run the code in a single code step without re-deploying my whole workflow

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#185]

**Comment by panchicore** [comment]
+1. Useful for processes that work together with distributed services as calling APIs or processing some data that changes each time is retrieved, its good to have that cache available, I love how the entire set of steps stores the cache for each input/output, that cache just need to be re-used to be the input for a single step, a "run from here" button would be very very appreciated.

**Comment by brkncoyot3** [comment]
Yes please!

**Comment by dylburger** [comment]
This is available in [the newest version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/)!

You can now test a single step, all steps above the current step, below the current step, or the entire workflow. All without deploying your workflow. You can run tests on any of the events from your trigger history.

Once you're confident in your changes, you can deploy the final code, and that version will run against live traffic.
