### ISSUE TITLE
htmlcsstoimage.com

### ISSUE THREAD

**Issue by gopokyo-colinn** [PipedreamHQ/pipedream#1860]
**Name of app / service**
htmlcsstoimage.com

**Link to developer documentation**
https://docs.htmlcsstoimage.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
workaround is to set up auth manually

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
transmit html/css to service and retrieve the response as an image or filepath

**Comment by todsac** [comment]
This app has been added - https://pipedream.com/apps/html-css-to-image

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by gopokyo-colinn** [comment]
Sure! I can take a crack at adding sources when they arise.  Wasn't 
aware I could and its great that it is possible


Colin

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
