### ISSUE TITLE
Delay Action: wait N { seconds, minutes, etc. } before running the next step

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#187]
To make this useful, the delay couldn't count against the [execution time limit](https://docs.pipedream.com/limits/#workflows). The workflow would have to suspend during the delay, and resume when the delay is done.

**Comment by dylburger** [comment]
Note - you can use the [Pipedream task scheduler](https://github.com/PipedreamHQ/pipedream/blob/master/components/pipedream/sources/new-scheduled-tasks/README.md) to schedule a message to be emitted from a source at any time (up to 1 year). This isn't a replacement for delay functionality, but it can help in many similar cases.

**Comment by dylburger** [comment]
This has been released! See [our built-in **Delay** actions](https://pipedream.com/docs/workflows/built-in-functions/#delay-actions) to pause a workflow with no code, or [see the docs on `$.flow.delay`](https://pipedream.com/docs/code/nodejs/delay/) to see how to delay workflows programmatically in Node.js!

**Comment by johndbritton** [comment]
@dylburger You probably want to update this doc that points to this issue saying the delay feature is not implemented: https://pipedream.com/docs/examples/waiting-to-execute-next-step-of-workflow/

**Comment by mroy-seedbox** [comment]
I landed here from that documentation as well! 👆

**Comment by dylburger** [comment]
@johndbritton @mroy-seedbox sorry for the late reply, thanks for the note. I'll remove that doc since the core delay docs are at https://pipedream.com/docs/code/nodejs/delay/#using-flow-delay now

**Comment by mroy-seedbox** [comment]
FYI: I found that link when looking at which triggers were available from Pipedream:
![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/94b30ffe-2cd8-4840-9092-bd34f9323aa4)
