### ISSUE TITLE
Deploy published components across multiple workflows

### ISSUE THREAD

**Issue by thatguychrisw** [PipedreamHQ/pipedream#1872]
**Is your feature request related to a problem? Please describe.**
I have an action that I'm rapidly adjusting across multiple workflows.  When I publish new versions there is not an obvious way to apply them to my workflows.  

**Describe the solution you'd like**
Updating to a new version should likely be initiated explicitly by the user.  Perhaps a new UI might be useful in the side bar (reference below) named "Components or (Actions/Sources)". That would take you to a page where you can view your components, their versions, and then have the option to update multiple workflows.

<img width="202" alt="Screen Shot 2021-11-02 at 8 35 02 PM" src="https://user-images.githubusercontent.com/480344/139970020-4f554521-4479-4a77-b369-da6fc6170738.png">

Another idea might be to add a `workflow` command to `pd` that allows you to redeploy specific components or redeploy across all of your workflows?  Something like `pd workflow <id> redeploy <component>` for a specific step or `pd workflow redeploy` to redeploy all components or `pd workflow redeploy <component>` to update a specific component across all workflows.

I think there are a lot of ways to solve this problem, I just think that there has to be a deliberate action taken by the user to initiate it.

**Do you have a workaround?**
Currently, I have to remove and add them in each workflow manually, not terrible but not scalable.

**Comment by dylburger** [comment]
@thatguychrisw We've improved the flow for updating actions. Any time you edit a workflow, you'll see a red **Update** button at the top-right of any component that has an updated published component. 

The UI listens for updates when you have a tab open, as well, so you don't need to refresh the page to register updates when you're developing.

Let me know if that helps!
