### ISSUE TITLE
[ACTION] Shopify - Admin API - CreateSmartCollection

### ISSUE THREAD

**Issue by PaulCutcliffe** [PipedreamHQ/pipedream#1879]
Shopify - Admin API - CreateSmartCollection

https://shopify.dev/api/admin-rest/2021-10/resources/smartcollection#[post]/admin/api/2021-10/smart_collections.json

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by PaulCutcliffe** [comment]
No, I did not know that - thanks for letting me know. 
I would be happy to help except that I don't know what I'm doing as I'm quite new to using APIs and very new to the Shopify API.

**Comment by dylburger** [comment]
Would you like to take a look at [the quickstart for developing actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and see if that looks like something you could tackle? 

Otherwise, we are happy to add this to our backlog.

**Comment by dmathukorala** [comment]
Verification on hold until issue fixes to support multiple **Column** and **Relation** rules mappings. 
cc - @dannyroosevelt

**Comment by andrewjschuang** [comment]
@dmathukorala I've changed the props selection to enable multiple rules mapping. Moving this back to Ready for QA

**Comment by dannyroosevelt** [comment]
@andrewjschuang this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)

**Comment by dannyroosevelt** [comment]
@andrewjschuang this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
