### ISSUE TITLE
[BUG]  Coda actions are out of date

### ISSUE THREAD

**Issue by gopokyo-colinn** [PipedreamHQ/pipedream#1885]
**Describe the bug**
Coda actions are using v1beta api which results in a 404

**To Reproduce**

**Expected behavior**
Replace v1beta with v1 in REST urls

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I have not looked at all the Coda endpoints, I am assuming they are all out of date.  I used the POST row endpoint

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
This will be fixed in #1885
