### ISSUE TITLE
[APP] Sendbird

### ISSUE THREAD

**Issue by towersben** [PipedreamHQ/pipedream#1892]
**Name of app / service** Sendbird

**Link to developer documentation** https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api

**Is lack of support preventing you from building workflows, or do you have a workaround?** Yes, we would like to be able to automate messaging users

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
@towersben here's a basic integration for Sendbird: https://pipedream.com/apps/sendbird

Let us know if that works or if you have any questions!

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
