### ISSUE TITLE
[FEATURE] ZoomAdmin Oauth Scopes

### ISSUE THREAD

**Issue by vellames-turing** [PipedreamHQ/pipedream#1894]
**Describe the solution you'd like**
In order to create new actions for Zoom Admin, I would like to have the following scopes added to zoom:

- phone:read
- phone:write
- phone:read:admin
- phone:write:admin
- phone_call_log:read
- phone_call_log:read:admin
- phone_call_log:master
- phone:master
- chat_message:write
- chat_message:write:admin
- chat_contact:read

**Do you have a workaround?**
No

**Comment by dannyroosevelt** [comment]
@vellames-turing can you remind me which actions the `phone` scopes are for?

**Comment by vellames-turing** [comment]
> @vellames-turing can you remind me which actions the `phone` scopes are for?
Sure, the actions are:

List Phone Numbers | List all phone numbers owned by a user
List call logs | List call logs of a user within a month
Send Chat Message | Send a chat message to a channel or contact

**Comment by dannyroosevelt** [comment]
closing out this issue since we decided to review / ship the existing set of actions you've already developed!
