### ISSUE TITLE
[ACTION] Discord bot: DM user

### ISSUE THREAD

**Issue by a19i23** [PipedreamHQ/pipedream#1895]
**Is there a specific app this action is for?**
Discord 

**Please provide a link to the relevant API docs for the specific service / operation.**
https://discord.com/developers/docs/resources/user#create-dm

**Comment by dylburger** [comment]
@a19i23 Thanks a lot for the request. Did you know anyone can create new actions on Pipedream? Take a look at [this quickstart](https://pipedream.com/docs/components/quickstart/nodejs/actions/) to learn more about action development.

We also have [an open PR](https://github.com/PipedreamHQ/pipedream/pull/1689/files) with other Discord Bot actions that you can use as an example.

Would you be open to developing this action?

**Comment by a19i23** [comment]
Hi, yes I looked at how to create one of these with your quickstart but I'm not sure I'll have time to add it. Thanks for the resources in your response so I can possibly attempt to tackle this in the future

**Comment by dylburger** [comment]
Thanks and sounds good. I'll also add this to our backlog.

**Comment by PatelN123** [comment]
Hey,
Is there any update/ETA on this?

**Comment by dannyroosevelt** [comment]
> Hey, Is there any update/ETA on this?

@PatelN123 it's in active development now, since you're subscribed to the ticket you'll receive updates as the work progresses.

**Comment by dannyroosevelt** [comment]
This is ready for release!
