### ISSUE TITLE
[APP] Nordigen

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#1896]
**Name of app / service**
Nordigen

**Link to developer documentation**
https://ob.nordigen.com/api/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Actions:
- List transactions

Triggers:
- New transactions

I was looking for an API to retrieve banking transaction infos but because of the TPP issue, pipedream cannot direct access these informations. I've been able to interface with Nordigen instead. This is a workaround for #63 and #1702. [List of supported banks.](https://nordigen.com/en/blog/list-all-banking-apis-updated/)

**Comment by LucBerge** [comment]
I'm able to retrive the transactions info with the following code:

```javascript
const platform = require("@pipedreamhq/platform");

// ========== 1 GET ACCESS TOKEN ==========

const step_1 = await platform.axios(this, {
  url: `https://ob.nordigen.com/api/v2/token/new/`,
  method: 'POST',
  headers: {
    "accept": "application/json",
    "Content-Type": "application/json"
  },
  data: {
    "secret_id": params.secret_id,
    "secret_key": params.secret_key,
  }
});

  // ========== 2 GET REQUISITION ID ==========

const requisition_id = this.$checkpoint;

console.log("Requisition id: " + requisition_id);

  // ========== 3 LIST ACCOUNTS ==========

if(requisition_id != null) {

  const step_3 = await platform.axios(this, {
    url: `https://ob.nordigen.com/api/v2/requisitions/${requisition_id}`,
    method: 'GET',
    headers: {
      "accept": "application/json",
      "Authorization": `Bearer ${step_1.access}`
    }
  });

  if(step_3.accounts.length > 0) {
    console.log("Account found: " + step_3.accounts[0]);
    this.$checkpoint = requisition_id;

    // ========== 4 LIST TRANSACTIONS ==========

    return await platform.axios(this, {
      url: `https://ob.nordigen.com/api/v2/accounts/${step_3.accounts[0]}/transactions`,
      method: 'GET',
      headers: {
        "accept": "application/json",
        "Authorization": `Bearer ${step_1.access}`
      }
    });
  }
  
  console.log("No account found");
}

// ========== 5 CREATE END USER AGREEMENT ==========

const step_5 = await platform.axios(this, {
  url: `https://ob.nordigen.com/api/v2/agreements/enduser/`,
  method: 'POST',
  headers: {
    "accept": "application/json",
    "Content-Type": "application/json",
    "Authorization": `Bearer ${step_1.access}`
  },
  data: {
    "institution_id": params.institution_id,
    "max_historical_days": params.max_historical_days,
    "access_valid_for_days": params.access_valid_for_days,
    "access_scope": [
      "balances",
      "details",
      "transactions"
    ]
  }
});

// ========== 6 BUILD REQUISITION LINK ==========

const step_6 = await platform.axios(this, {
  url: `https://ob.nordigen.com/api/v2/requisitions/`,
  method: 'POST',
  headers: {
    "accept": "application/json",
    "Content-Type": "application/json",
    "Authorization": `Bearer ${step_1.access}`
  },
  data: {
    "redirect": params.redirection_url,
    "institution_id": params.institution_id,
    "reference": steps._0_trigger.context.id,
    "agreement": step_5.id,
    "user_language": params.user_language
  }
});

// ========== 7 SAVE REQUISITION ID ==========

this.$checkpoint = step_6.id;
console.log("New equisition id: " + step_6.id);

// ========== 8 SEND SLACK LINK ==========

const { WebClient } = require('@slack/web-api')
const web = new WebClient(auths.slack.oauth_access_token)
const step_8 = await web.chat.postMessage({
  text: params.slack_text + step_6.link,
  as_user: false,
  mrkdwn: true,
  channel: params.user_id,
  username: "AirTable",
  icon_url: "https://avatars.slack-edge.com/2016-09-27/84758167138_3f653d27d616c21b6545_192.png",
})

$end("A link as been sent on slack");
```

This is not the best code ever but it's working.
Add a time base trigger (once a day) and compare the current transactions with the previous onces and you have a new transaction trigger:

```javascript
var new_transactions = [];
var current_transactions = [];

//Retrieve the previous transaction ids
const previous_transactions = this.$checkpoint;

//For each transaction
for(const transaction of steps._1_get_transactions.$return_value.transactions.booked) {
  //Add the transaction id to the current transactions list
  current_transactions.push(transaction.transactionId);

  //If the transaction id is not in the previous transactions list
  if(!previous_transactions.includes(transaction.transactionId)){
    //Add it to the new transactions list
    new_transactions.push(transaction);
  }
}

//Save the current transactions ids list
this.$checkpoint = current_transactions;

//Return the new transactions
return new_transactions;
```

**Comment by dannyroosevelt** [comment]
Thanks for the info and examples, @LucBerge! Here's a basic integration for Nordigen: https://pipedream.com/apps/nordigen/.

Regarding the triggers and actions you'd like to see, all of our component code is open source and we encourage you to build your own triggers and actions. Are you interested in giving that a shot? I recommend starting here: https://pipedream.com/docs/components/guidelines/#getting-started

Either way, we're happy to help support you however we can.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
@LucBerge I added the specific trigger and action you inquired about to the team's backlog. Feel free to follow along: https://github.com/PipedreamHQ/pipedream/issues/1915

**Comment by LucBerge** [comment]
I didn't known the issue would be closed if no answer to your question was given within 12 days. Weird process.

> Here's a basic integration for Nordigen: https://pipedream.com/apps/nordigen/.

Thanks, I'll take a look.

> Regarding the triggers and actions you'd like to see, all of our component code is open source and we encourage you to build your own triggers and actions. Are you interested in giving that a shot?

Yes, but I need time.
