### ISSUE TITLE
TIckTick to Trello[APP]

### ISSUE THREAD

**Issue by temple-1** [PipedreamHQ/pipedream#1899]
**Name of app / service**
Ticktick
**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
@temple-1 we actually have a Ticktick integration here: https://pipedream.com/apps/ticktick . Were you looking for a specific trigger or action?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
