### ISSUE TITLE
[APP] Tawk.to

### ISSUE THREAD

**Issue by Mte90** [PipedreamHQ/pipedream#1902]
**Name of app / service**
Tawk.to - https://www.tawk.to/

**Link to developer documentation**
https://developer.tawk.to/webhooks/

**Comment by todsac** [comment]
@Mte90 - This app looks like a generic webhook integration.  It says, "When a webhook is triggered, a POST request will be made to the URL configured along with a JSON payload specific for the event type." Have you tried using the HTTP source in Pipedream and inputting the provided webhook URL in your Tawk account?  Or, is there something else you were looking for that I am missing?

**Comment by Mte90** [comment]
Our idea was to integrate Tawk with Discord so in both of communications from/to.

**Comment by dannyroosevelt** [comment]
@Mte90 so to confirm, the idea would be that you want to send a notification from Tawk into Discord? (like Chat starts/ends or New ticket created?)

If so, it sounds like you'll want to configure a new HTTP URL that you can use as a webhook in Tawk. Check out our docs here for more info on how to get started: https://pipedream.com/docs/quickstart/hello-world/#generate-a-unique-endpoint-url-to-trigger-the-workflow

From there you can use one of our Discord actions to pass that event on to Discord (like [this one](https://pipedream.com/apps/discord-webhook/actions/send-message) for example).

Let us know if that helps point you in the right direction.

**Comment by Mte90** [comment]
The idea was to chat to Tawk using Discord to centralize the communication for us.

**Comment by dannyroosevelt** [comment]
Okay can you tell me more about the flow you envision for Tawk and Discord? What do you want to trigger a workflow, and what would you like to happen once it gets triggered?

**Comment by Mte90** [comment]
Tawk is a chat system, so our idea was to sync all the chat messages between a Discord room to tawk when a new chat is on in Tawk. 
Like I guess the other live chat services pipedream supports, in this way we can chat from discord but offer a live chat with others.

**Comment by dannyroosevelt** [comment]
Got it, thanks for the info. I recommend checking out our quickstart guide to get yourself oriented with building workflows: https://pipedream.com/docs/quickstart/

From there if you have additional questions, our community is the best place to get help:
https://pipedream.com/support

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergio-eliot-rodriguez** [comment]
I reached out requesting Rest API access.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
