### ISSUE TITLE
Not Logged In - Not logged out

### ISSUE THREAD

**Issue by NTKrieger** [PipedreamHQ/pipedream#1907]
The UI shows me as logged in, except when I attempt to view my workflows, I get a 404 and your sliding puzzle game.
When I attempt to log out, the application hangs up.  I've attempted to reload without cache without luck.

If I use an incognito window, I can log in without issue.

I have a personal and a work account I switch back and forth between using different Google auth profiles.

This issue has happened to me several times this week.  I'll grab console logs and screen shots and post them here in if it comes up again.

**Comment by NTKrieger** [comment]
![image](https://user-images.githubusercontent.com/24538514/142700786-aad4ee8b-6931-42ea-bc87-d92d0b6a6b5d.png)

**Comment by NTKrieger** [comment]
![image](https://user-images.githubusercontent.com/24538514/142700878-c0136407-5999-4004-9b4e-27f2aa4e1443.png)
![image](https://user-images.githubusercontent.com/24538514/142700957-5afe9d88-2662-4bf1-a3ef-35451503e00b.png)

The logout text is grey as if disabled.  When I click the button, it hangs here.

**Comment by dylburger** [comment]
@NTKrieger Thanks for reaching out. Could you try a couple of things to see if these resolve the issue?

1. [Hard refresh](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache) pipedream.com.
2. Clear your cookies / site data for pipedream.com specifically (in your Chrome settings)

if you still encounter issues, can you disable all of your browser extensions to confirm it's not an issue there?

Let me know if that works. By the way, do you manage your separate logins using [Chrome profiles](https://support.google.com/chrome/answer/2364824?hl=en&co=GENIE.Platform%3DDesktop)? That's how I manage multiple logins, and I never have to log out / back in to different accounts that way.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
