### ISSUE TITLE
[APP] - Cartrover

### ISSUE THREAD

**Issue by jmorris644** [PipedreamHQ/pipedream#1912]
**Name of app / service**
Cartrover
**Link to developer documentation**
https://developers.cartrover.com/#intro
**Is lack of support preventing you from building workflows, or do you have a workaround?**
I do not have a workaround.
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Need Cart API initially

**Comment by sergio-eliot-rodriguez** [comment]
Submitted as Extensiv Integration Manager, because Cartrover was renamed

**Comment by sergio-eliot-rodriguez** [comment]
Extensive Integration Manager is now integrated -- https://pipedream.com/apps/extensiv-integration-manager
