### ISSUE TITLE
[APP] - MarketTime

### ISSUE THREAD

**Issue by jmorris644** [PipedreamHQ/pipedream#1913]
**Name of app / service**
MarketTime
**Link to developer documentation**
https://markettime.com/public-api-list
**Is lack of support preventing you from building workflows, or do you have a workaround?**
yes, I need to link the orders to Shopify
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Getting and updating orders would be my biggest need right now

**Comment by sergioeliot2039** [comment]
@jmorris644 , I created an account with MarketTime to add it to Pipedream app stores.
I had to request for API Key, in my wording, I mentioned we had a user in Pipedream asking to use MarketTime (at the moment on requesting MarketTime for it, I thought that was best for my pitch). They replied back and want to know the Company/Username to see if your MarketTime account is in the pricing tier that enables API Key.
Would you mind share this information with me? For the sake I may be granted an API Key (I requested an API Key for my own trial account, but again, they are asking for the user who ultimately be using the API, so I am unsure if they intend to send me their API). 

That said, I know this may be private information, so if you want to share it with me, maybe let me know by email (sergio_eliot@hotmail.com) or to Pipedream Support (support@pipedream.com) and I can have Tod or Dylan relay over to me.

**Comment by sergioeliot2039** [comment]
@jmorris644 they want to know the Company/Username you used to register with MarketTime

> Hi Sergio,
> 
> A PLUS account is needed for an API key to be generated within MarketTime.
> Let me know the name of the company/user requesting the feature,
> and I can check to see if the account has an API key.
> Thanks,
> Martin Ellis
> MARKETTIME LLC

Can you help with this info?

**Comment by jmorris644** [comment]
I responded to the other email. Let me know if that will work.

**Comment by jmorris644** [comment]
Did you get the “ok” form Markettime?

**Comment by sergioeliot2039** [comment]
Not yet.
After I passed over your info, I got an automated ackwnowlege message, saying the support ticket is "waiting on us". today i followed up by email but still haven't heard from them.

**Comment by jmorris644** [comment]
any update on this? Do I need to do something?

**Comment by sergioeliot2039** [comment]
They haven't get back to me. I will call their number now and let you know what they say.

**Comment by sergioeliot2039** [comment]
@jmorris644 they are not replying. perhaps can you reach out to Marketime support and confirm you have API Access?
They said it's available on PLUS accounts. If you have this account we can check the option if API keys can be shared, once the integration is done, revoke access to this API Key and create a new one. Do you think this is feasable?
I called but no luck, the representative wasn't available, they then transfer me to someone else, and finally they sent me to voice mail.

**Comment by jmorris644** [comment]
You were right, I just had to pay them. :)

Here is the API and Docs. I need to be able to cross-communicate this site with Shopify. That is my end goal. Not only for products but also for orders. The orders will go form Markettime to Shopify for fulfillment.

Manufacturer ID: M52868
API Key: df898285-dbfa-4436-91ad-c60962d73e61

https://markettime.com/public-api-list

Let me know if you need anything more.

joe

**Comment by dylburger** [comment]
@jmorris644 I removed the API key from your last message to protect the security of your account. I'm discussing this with Sergio and I'd like to see if there's another way we can get access to a test account so we can test the API. We'll follow up with you as soon as that happens.

**Comment by jmorris644** [comment]
Thanks. We do not have any data at market time yet. So I am not too worried about you testing with the live account. I can send the api in some other secured way if you wish.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmorris644** [comment]
Any thoughts or progress on this?

**Comment by sergioeliot2039** [comment]
I am engaging with this, MarketTime reached out to me providing an Api Key / Manufacturer Id, but is buggy - when used on the API I get 401 so I am still engaging with them through mail with their support team.

**Comment by jmorris644** [comment]
thanks. Let me know if I can help

**Comment by jmorris644** [comment]
I need to be up and running by years end. There is a 3rd party integrator that I can use in the interim if we are unable to get this working by then. In the long run I do not want to use the 3rd party integrator.

**Comment by dannyroosevelt** [comment]
Hi @jmorris644 apologies for the delay, and thanks for your patience!

Here is a basic integration for MarketTime: https://pipedream.com/apps/markettime/

Let us know if you'd like any guidance or support on building out actions and triggers -- they're all open source and I recommend checking out our Quickstart Guides when you get started: https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by jmorris644** [comment]
Thanks. I will review...

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
