### ISSUE TITLE
[FEATURE] send email => allow overriding the reply-to

### ISSUE THREAD

**Issue by colemickens** [PipedreamHQ/pipedream#1917]
**Is your feature request related to a problem? Please describe.**

I want to build an easy Telnyx <-> PipeDream <-> Email Bridge. It seems like I can get 90% of the way there, the only thing missing is the ability to override reply-to for an outgoing email. I am an individual user hacking at something quickly to liberate myself from an awful carrier and am really amazed with PipeDream. I'd be happy to write this up if I do get it working after such little effort.

The bold parts are missing.

Workflow 1: Telnyx -> Email: 
1. HTTP Webhook Source
2. Send Email (bit of custom JS to form the email body from the payload I get from Telnyx)
   * **override the `reply-to`  email header**
     * set it to `{{workflow2.email_address.user}}+{{event.payload.data.from.phone_number}}@{{workflow2.email_address.host}}`

Workflow 2: Email -> Telnyx
1. Email Source
2. Webhook Post w/ custom JavaScript
   * use `event.payload.to` to extract the `phone_number`
   * perform POST to Telnyx with apikey from env secret

**Describe the solution you'd like**

I think I can basically build a two-way sms bridge to Telnyx in minutes, if I could merely over-ride the reply-to address for an outbound email.

**Do you have a workaround?**
Not really one that has an acceptable UX. I could instruct (myself) to reply via the telnyx URL and then use the subject or some such, but allowing me to override the reply-to would make for a pretty slick UX. (If I thought about it more maybe there's a way to even make it threaded nicely)?

I guess also that directly using SendGrid or something would work, but I'm cheap since this is going to be extremely low-volume personal use, and it seems so in reach!

**Comparable features in other tools?**
Not sure, but I can't say any platform has come close to comparing to pipedream so far.

**Additional context**

**Comment by dylburger** [comment]
@colemickens Thanks for all the detail, that's a really cool setup.

In this specific case I would recommend using a service like Sendgrid to send the email in workflow #1, and setting the custom Reply-To header using their email API. Sendgrid specifically lets you send 100 emails / day on their free tier. We integrate with other email providers (e.g. we use Amazon SES internally), and you can also use the SMTP server of your own email provider, [using the `nodemailer` package](https://pipedream.com/community/t/how-do-i-send-an-email-using-my-outlook-account/203/2?u=dylan) if you're sending a low volume of messages.

I'll keep this open and raise it with the team. I want to evaluate any potential security / deliverability issues, as well.

Let us know if another third-party works for now, and please share the workflows when you have them done!

**Comment by colemickens** [comment]
@dylburger Thanks! I did in fact wind up getting even closer with SendGrid last night. I'm starting to reconsider the reply-to approach and instead embed/extract metadata in/from the email/reply.

Either way, this can certainly be closed whenever you see fit, thanks again for the platform, thoughts and follow-up! (And I'll drop a link here if I wind up writing up a quick gist about this, just for the SEO, etc)

**Comment by dylburger** [comment]
Great thanks, glad you found an approach that worked.
