### ISSUE TITLE
tiktok[APP]

### ISSUE THREAD

**Issue by mohandsedu9090** [PipedreamHQ/pipedream#1918]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
@mohandsedu9090 
can you please kindly provide more information?
is this [Developers Documentation](https://developers.tiktok.com/) related to the app you are look for?
Can you specify what specific actions or triggers you'd like to use from the app you are?
