### ISSUE TITLE
[ACTION] Send WhatsApp HSM Template - Landbot

### ISSUE THREAD

**Issue by pausanchez** [PipedreamHQ/pipedream#1921]
**Name of app / service**

Landbot

**Link to developer documentation**

1. Filter by phone number: https://dev.landbot.io/api/index.html#api-Customers-GetHttpsApiLandbotIoV1Customers

2. Send HSM Template: https://dev.landbot.io/api/index.html#api-WhatsApp_templates-PostHttpsApiLandbotIoV1CustomersCustomer_idSend_template

3. Assign conversation to Bot: https://dev.landbot.io/api/index.html#api-Customers-PutHttpsApiLandbotIoV1CustomersCustomer_idAssign_botBot_id

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Currently I'm doing this method with all requests, setting up manually each one. If a single set up was done, for the 3 requests required, I will be able to share it easier with low-coders. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

The main trigger would be an external HTTP request. But other type of triggers (like change field in a CRM) could be also handy

**Comment by dannyroosevelt** [comment]
@pausanchez are you interested in building out some of these actions on your end? All of our sources and triggers are open source -- here's a good way to get started: https://pipedream.com/docs/components/guidelines/#getting-started

We're happy to help answer questions and give you guidance along the way

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
