### ISSUE TITLE
Mattermost

### ISSUE THREAD

**Issue by omishagupta** [PipedreamHQ/pipedream#1922]
**Name of app / service** Mattermost

**Link to developer documentation** https://developers.mattermost.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by todsac** [comment]
@omishagupta - Mattermost is integrated.  Please let us know if it works for you.  Also, would you be interested in building out any triggers or actions?

https://pipedream.com/apps/mattermost

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
