### ISSUE TITLE
[TRIGGER] Dear - Order Created

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1925]
https://support.dearsystems.com/support/solutions/articles/1000054237-api-introduction

[See this Slack thread](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1638316346456000) for context.

**Comment by dannyroosevelt** [comment]
This may be helpful: https://dearinventory.docs.apiary.io/#reference/webhooks/webhooks

`Purchase/OrderAuthorised`
