### ISSUE TITLE
[ACTION] Jotform: create a new form

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1927]
**Is there a specific app this action is for?**
Jotform

**Please provide a link to the relevant API docs for the specific service / operation.**
https://api.jotform.com/docs/#post-forms

**Create a New Form** | Add new forms with questions, properties and email settings

**Comment by dannyroosevelt** [comment]
superseded by https://github.com/PipedreamHQ/pipedream/issues/1456
