### ISSUE TITLE
Pipedream down?

### ISSUE THREAD

**Issue by pawlean** [PipedreamHQ/pipedream#1933]
<img width="1274" alt="2021-12-07 at 17 42 04 - Google Chrome" src="https://user-images.githubusercontent.com/17087373/145079808-0246deb5-cab7-4e1b-bb36-f53cb52b6089.png"> 

Is Pipedream down right now?

**Comment by dylburger** [comment]
@pawlean yes, an AWS incident is affecting us at the moment, and we're following the status of that closely to see when it's resolved.

By the way, we post incident updates at https://status.pipedream.com/ , and you can subscribe to updates there so you get notifications when incidents are created or resolved.
