### ISSUE TITLE
Databox

### ISSUE THREAD

**Issue by tmchow** [PipedreamHQ/pipedream#1935]
**Name of app / service**
Databox

**Link to developer documentation**
https://developers.databox.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
can work with their API directly

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
Hey @tmchow, we got a basic integration with Databox set up -- https://pipedream.com/apps/databox

Per Slack conversation, let me know if this works for you or if we can help with next steps.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
