### ISSUE TITLE
[ACTION] Post to Linkedin Company Page

### ISSUE THREAD

**Issue by daxeel** [PipedreamHQ/pipedream#1937]
**Is there a specific app this action is for?**
Linkedin

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by dannyroosevelt** [comment]
Hi @daxeel you should be able to accomplish this today using the "share_text_mentions" action for LinkedIn, as long as you have the company's `urn`, which you can retrieve with the "get_member_organization_access_control" LinkedIn action.

Here's a workflow you can check out and copy: https://pipedream.com/@danny/linkedin-post-to-company-page-p_8rCLkwq/edit?e=226RUODgZtO97aVNy0HxYlkUjlP

**Comment by daxeel** [comment]
Thanks. I ll check

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
