### ISSUE TITLE
[ACTION] Stripe - Create a Transfer

### ISSUE THREAD

**Issue by Yak86** [PipedreamHQ/pipedream#1939]
**Is there a specific app this action is for?**
Stripe
**Please provide a link to the relevant API docs for the specific service / operation.**
Can we add the Create a Transfer call from Stripe to send funds from Stripe account to a connected account?

https://stripe.com/docs/api/transfers/create

**Comment by dannyroosevelt** [comment]
Hey @Yak86 we don't have an integrated action to Create a transfer for Stripe today, but Pipedream actions and triggers are all open source, so I encourage you to check out how you can build out that action with our Quickstart guide: https://pipedream.com/docs/components/quickstart/nodejs/actions/. And [we're available](https://pipedream.com/support) to help guide you through the process!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
