### ISSUE TITLE
[FEATURE] Callback URLs to suspend, then resume workflow

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#1943]
My team and I would like to contribute to Pipedream with some actions, a couple of which may take potentially much more than the standard time limit to complete (https://pipedream.com/docs/limits/#workflows), depending on the user input. The action themselves would just submit input data to an API and then poll for completion, until done.

As far as I understand, it is impossible to have an action which runs for more than those time limits in Pipedream, even if it is just polling from time to time: am I correct?

Zapier has solved this very same issue by allowing one to generate a callback URL within the action itself (https://platform.zapier.com/cli_docs/docs#zgeneratecallbackurl): does Pipedream support a similar concept? We could go this route, if needed, as our API supports webhooks as well.

Original Slack conversation: https://pipedream-users.slack.com/archives/C01E5KCTR16/p1639076119154300

**Comment by ecobisi** [comment]
For completeness, the API I was referring to (I am the original author of this request in Slack) is the one of our email verification service, which could take even hours to return a result, depending on the size of the lists of emails to verify: https://verifalia.com/developers
Verifalia API supports webhooks, as I said, which we call completion callbacks: https://verifalia.com/developers#email-validations-completion-callback

Thank you

**Comment by dylburger** [comment]
@ecobisi Could you give our new `$.flow.suspend` functionality a try?

In a Node.js code step, you can use it like so:

```javascript
export default defineComponent({
  async run({ steps, $ }) {
    const { cancel_url, resume_url } = $.flow.suspend()
    console.log(`This is my resume URL: ${resume_url}`)
    console.log(`This is my cancel URL: ${cancel_url}`)
    
    // Step suspends at the end of the `run` method
  },
})
```

Since the step only suspends at the end of the run method, you can pass the `resume_url` and `cancel_url` to your service. Then you can resume the workflow as soon as the third party job is done.

The `resume_url` accepts `POST` requests, so if you `POST` this data:

```bash
curl -d '{ "foo": "bar" }' https://api.pipedream.com/v1/sources/p_NMCZ6aV/resume/<id>
```

and future steps of the workflow can access that data in the `$resume_data` export of the step:

<img width="482" alt="Screen Shot 2022-06-06 at 9 15 51 PM" src="https://user-images.githubusercontent.com/242668/172295069-c6576530-5c22-4b52-9d12-95f6d41436c2.png">

Let me know if that helps!

**Comment by ecobisi** [comment]
Thanks, @dylburger 

I have just tried the new `$.flow.suspend()` function and, while I believe it is okay for some usage scenarios, I think its design requires the end user to set up a subsequent step just to handle the resuming data and eventually post-process it (think about projecting the `resumeData` JSON graph into something easier to work with in future steps, for example).

**Resuming within the calling component**

What I would like to achieve, if possible of course, would be a suspension which allows to be resumed within the calling component. Maybe a win-win solution, from a user experience standpoint, could invoke a new `resume()` function within the calling component itself, like the following:

```
export default {
    async run({ $ }) {
      const { cancel_url, resume_url } = $.flow.suspend();
      // ...
    },
    async resume({ resumeData }) {
      // ...
    }
  }
```

This way, developers who wish to just pass the `resumeData` to future steps (as the current implementation works) may just return that, while others who need to post-process `resumeData` may just achieve what they are after within the `resume()` function body.

**Multiple suspensions**

Not sure if this is overkill for your target audience but being able to resume within the calling component could also open to the more advanced possibility of having multiple suspensions within the same calling component by adding a checkpoint identifier. This way a single component may chain multiple long-running external API invocations, for example. Something like this:

```
export default {
    async run({ $ }) {
      const { cancel_url, resume_url } = $.flow.suspend({ checkpoint: 'alpha' });
      // ...
    },
    async resume({ resumeData, checkpoint }) {
      switch (checkpoint) {
        case 'alpha': {
          $.flow.suspend({ checkpoint: 'beta' });
          // ...
          return;
        }
        case 'beta': {
          // ...
          return 42;
        }
      }
    }
  }
```

Does this make sense?
Thank you.

**Comment by dylburger** [comment]
@ecobisi makes complete sense! Resumption within the same component is on our backlog. I created a public issue for that at #3094.

We have not discussed multiple suspensions within the same step, but I'll also bring that up to the team.
