### ISSUE TITLE
Oanda [APP]

### ISSUE THREAD

**Issue by RayMeeks** [PipedreamHQ/pipedream#1945]
**Name of app / service**
Oanda

**Link to developer documentation**
https://developer.oanda.com/rest-live-v20/introduction/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
would be nice to just have the app selectable with all the endpoint actions

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Endpoints**
Account
Instrument
Order
Trade
Position
Transaction
Pricing

**Comment by dannyroosevelt** [comment]
@RayMeeks we aren't able to easily able to test this out due to OANDA's account requirements, but here is a basic integration with OANDA: https://pipedream.com/apps/oanda/

Can you verify you're able to successfully connect to your account within Pipedream?

**Comment by RayMeeks** [comment]
yes my account does connect just fine with my API key set in the ${auths.oanda.personal_token}

![CleanShot 2021-12-15 at 19 41 58](https://user-images.githubusercontent.com/28879718/146298362-d884be33-aad5-4310-b0f4-7d03adab21a1.png)

**Comment by dannyroosevelt** [comment]
Great, thanks for confirming.

All our triggers and actions are [open source](https://pipedream.com/docs/components/guidelines/#getting-started) -- if you're interested in building these out yourself we're happy to provide guidance and support along the way via [our community](https://pipedream.com/support).

Is that something you'd be interested in exploring?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
