### ISSUE TITLE
[ACTION] Philips Hue

### ISSUE THREAD

**Issue by tsauvajon** [PipedreamHQ/pipedream#1946]
**Is there a specific app this action is for?**
Philips Hue smart lights

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.meethue.com/develop/get-started-2/

I'd like to have an action to turn the lights on, off, make them blink or change the "scene" (i.e. light disposition I predefined myself in the Philips Hue app itself).
This is something I can do with Zapier, for example.

**Comment by dylburger** [comment]
@dannyroosevelt I saw that we started the app configuration for this. Was this in progress?

**Comment by dannyroosevelt** [comment]
@tsauvajon are you able to help test the authentication for Philips Hue and confirm if you're able to connect your account and make authenticated requests? You can add the app here: 
https://pipedream.com/apps/philips_hue

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
