### ISSUE TITLE
[APP] Ultramsg For WhatsApp

### ISSUE THREAD

**Issue by hadiomer** [PipedreamHQ/pipedream#1947]
**Ultramsg For WhatsApp**

**[Link to developer documentation](http://docs.ultramsg.com/)**
 
** Actions **
- send chat message
- send image message
- send  document message
- send audio message
- send  voice message
- send video message
- send  link message
- send  contact message
- send  location message
- send vcard message

**Comment by dannyroosevelt** [comment]
@hadiomer here is a basic integration for UltraMsg: https://pipedream.com/apps/ultramsg

All our triggers and actions are open source and anyone is able to contribute (we're happy to provide support along the way)! Here's a good spot to get started if you're interested: https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
