### ISSUE TITLE
[App] Mono webhook

### ISSUE THREAD

**Issue by Dreezy305** [PipedreamHQ/pipedream#1948]
mono

https://docs.mono.co/docs

no work around

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
@Dreezy305 sorry for the delay here -- to confirm, are you looking to configure a webhook in order to consume event data from Mono?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
