### ISSUE TITLE
[APP] Coinlore

### ISSUE THREAD

**Issue by gozames** [PipedreamHQ/pipedream#1950]
**Name of app / service**

Coinlore

**Link to developer documentation**

https://www.coinlore.com/cryptocurrency-data-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
@gozames we've integrated Coinlore -- you can add the API to your workflow here: https://pipedream.com/apps/coinlore/

Let us know if you're interested in building out any actions or triggers for their API! I recommend starting here: https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
