### ISSUE TITLE
[BUG] GitHub webhook-based sources not verifying the header

### ISSUE THREAD

**Issue by umang-malik** [PipedreamHQ/pipedream#1951]
**Describe the bug**
The GitHub webhooks do not verify that the header `X-Hub-Signature`. 

**To Reproduce**
1. Create a GitHub source on Pipedream. Eg. `New or Updated Issue (Instant)`.
2. Go to the Github repository's Webhook's page (`github.com/user/repo/settings/hooks`), and change the secret to some arbitrary value.
3. Create a new issue.

**Expected behaviour**
The event (sent via a webhook) must **not** be accepted by Pipedream since the secret has changed (this secret is used to hash the payload). The hash is sent as the header `X-Hub-Signature`.

**Actual behaviour**
The event is accepted by Pipedream.

**Reason for this behaviour**
The [code](https://github.com/PipedreamHQ/pipedream/blob/92d28a9cde2f506cff9e491750ca0ad062eede5e/components/github/sources/common-webhook.js#L50) checks for the header `X-Hub-Signature`. However, [NodeJS (assuming Pipedream uses NodeJS) converts the header fields to lowercase](https://nodejs.org/api/http.html#messageheaders), and hence the actual header that should be checked is `x-hub-signature`.
Also, `hmac.update()` requires string input instead of object. So `body` should be replaced by `JSON.stringify(body)`.
Right now, the entire `if` block is skipped.

**Patch to fix this**
```diff
diff --git a/components/github/sources/common-webhook.js b/components/github/sources/common-webhook.js
index e6b75610..6eaedec3 100644
--- a/components/github/sources/common-webhook.js
+++ b/components/github/sources/common-webhook.js
@@ -46,13 +46,12 @@ module.exports = {
       body,
       headers,
     } = event;
-
-    if (headers["X-Hub-Signature"]) {
+    if (headers["x-hub-signature"]) {
       const crypto = require("crypto");
       const algo = "sha1";
       const hmac = crypto.createHmac(algo, this.db.get("secret"));
-      hmac.update(body, "utf-8");
-      if (headers["X-Hub-Signature"] !== `${algo}=${hmac.digest("hex")}`) {
+      hmac.update(JSON.stringify(body), "utf-8");
+      if (headers["x-hub-signature"] !== `${algo}=${hmac.digest("hex")}`) {
         throw new Error("signature mismatch");
       }
     }
```

**Comment by dannyroosevelt** [comment]
@umang-malik thank you for flagging and proposing a patch! Would you mind creating a PR for this so the team can review and merge?

**Comment by umang-malik** [comment]
I have created the PR: #1953 
Please review.

**Comment by dannyroosevelt** [comment]
Thanks for flagging and patching, @umang-malik! This is now live. FYI You'll need to remove and re-add the source in your workflow in order to update to the latest version with your fix.
