### ISSUE TITLE
Twitter OAuth 2.0

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#1955]
https://twittercommunity.com/t/announcing-oauth-2-0-general-availability/163555

**Comment by ctrlaltdylan** [comment]
Cases when users are hitting the rate limit of Twitter 1.1 OAuth:

* https://pipedream.com/community/t/how-to-add-dm-into-trigger/2078/7

**Comment by dylburger** [comment]
Closing in favor of #2531
