### ISSUE TITLE
More Discord Bot Integrations

### ISSUE THREAD

**Issue by F4biTV** [PipedreamHQ/pipedream#1958]
Create/Delete Channel
-Modify Channel
Create/Delete Role
-Give/Remove Role
Send/Delete Message

**Comment by dannyroosevelt** [comment]
@F4biTV good news -- we just wrapped up development on all of these actions [here](https://github.com/PipedreamHQ/pipedream/pull/1689). Are you open to helping us test these out to confirm everything works for you? If so we'll get them published asap.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
