### ISSUE TITLE
[APP] ProProf/Project bubble

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#1965]
You already created the [Project Bubble app](https://pipedream.com/apps/project-bubble) but projectbubble.com redirects to [ProProfs Project](https://www.proprofsproject.com), so it would make sense to update the app name/info in PipeDream.

**Comment by dannyroosevelt** [comment]
Thanks for the heads up, @nachocab -- we updated the name: https://pipedream.com/apps/project-bubble
