### ISSUE TITLE
[APP] Microsoft Teams

### ISSUE THREAD

**Issue by Mish6666** [PipedreamHQ/pipedream#1970]
**Name of app / service**
Microsoft Teams

**Link to developer documentation**
https://docs.microsoft.com/en-us/microsoftteams/platform/

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue
- a trigger that fires when receiving a personal message
- a trigger that fires when receiving a group message

**Comment by dannyroosevelt** [comment]
Hi @Mish6666 these are in progress here -- https://github.com/PipedreamHQ/pipedream/issues/1023. Feel free to follow that issue to receive updates.

Can you confirm those triggers will satisfy your needs?

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
