### ISSUE TITLE
[BUG] Sources are receiving a weird string notation for properties that return objects as value

### ISSUE THREAD

**Issue by vellames-turing** [PipedreamHQ/pipedream#1997]
**Describe the bug**
Sometimes we need to return objects inside the values of a property that uses `options`. The same variable has two different behaviors right now.

In one action
`{ value: '/test55', type: 'folder' } object`

In one source
`{"value"=>"/test55", "type"=>"folder"} string`

In the second case, it's not possible to access `prop.value` because it is a string, as well as convert it to an object using `JSON.parse` because this is not a JSON notation.
The type of this property is `string`, if I try to change it to an object. I receive the following error
`{"error":"{\"name\":\"UserError\",\"message\":\"options not supported for prop propName\"}"}`

**To Reproduce**
1. Create a property that returns an object as an `option` in the `app` file
2. Try to consume it in a `source`
3. You can check the type of the value using `typof` or use a `console.log` to check the notation

**Expected behavior**
The object returned inside the `option` should have the same behavior in `sources` and `actions`

**Desktop (please complete the following information):**
 - MacBook Air (M1, 2020)
 - macOS Big Sur 11.3.1
 - Google Chrome
 - Version 96.0.4664.110 (Official Build) (arm64)

**Additional context**
On my last PR, I had to create one additional property to return only a `string` for `sources #1956

**Comment by vellames-turing** [comment]
Cc: @js07 @dannyroosevelt

**Comment by dylburger** [comment]
@vellames-turing Did y'all solve this with the helpers lib?

**Comment by vellames-turing** [comment]
I am closing this one since we have the `withLabel` right now.
