### ISSUE TITLE
[APP] ServiceNow

### ISSUE THREAD

**Issue by RochieOreo** [PipedreamHQ/pipedream#2000]
**Name of app / service**
ServiceNow

**Link to developer documentation**
https://developer.servicenow.com/dev.do#!/reference/api/rome/rest/c_TableAPI

**Is lack of support preventing you from building workflows, or do you have a workaround?**
We have a internal product called "Flow designer" but I believe that Pipedream is better

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Everything

**Comment by dylburger** [comment]
Hi @RochieOreo , thanks for the request. We already have a ServiceNow integration (see [here](https://pipedream.com/apps/servicenow) and [docs here](https://pipedream.com/docs/apps/servicenow/). 

Was there a specific use case you were trying to solve that we didn't support?

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
