### ISSUE TITLE
[APP] Shopify Partner

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2003]
**Name of app / service**

Shopify Partner API

**Link to developer documentation**

https://shopify.dev/api/partner

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Nope, just would be nice to have an official source & actions available to support partner data requests

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

### Actions

* Get transactions
* Get installs
* Get uninstalls

**Comment by dylburger** [comment]
@ctrlaltdylan This was almost complete right? Did you just need to add the test request?

**Comment by ctrlaltdylan** [comment]
@dylburger correct, I believe I did it correctly but I'm unsure of how to test the test. Maybe you could review that?

**Comment by dannyroosevelt** [comment]
@ctrlaltdylan this is what you and I had briefly chatted about -- are you able to use this scaffolding step and make a successful test request? 
![image](https://user-images.githubusercontent.com/20780753/155247281-3c423e51-f5bf-4e36-aacd-7594c76ad989.png)

**Comment by ctrlaltdylan** [comment]
@dannyroosevelt yup it's coming back to me now, I have a test request in a separate workflow on my PD account that is making a test request successfully.

**Comment by dylburger** [comment]
Uncheck that **Admin only** flag and get this bad boy out. Thanks for getting this done y'all. You've still got to blog about this!
