### ISSUE TITLE
[pd-cli] add "new" command support to scaffold a component locally

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#2015]

**Comment by dylburger** [comment]
@ctrlaltdylan Did `pd init` solve this use case for you, or did you want to add a `new` alias or other functionality?

**Comment by ctrlaltdylan** [comment]
@dylburger didn't realize `pd init` was available at the time. So we can close this bad boy out.

An alias to "new" isn't a bad idea, because `init` can imply you're starting an existing component, whereas `new` is pretty clear it's only for generate a new one.
