### ISSUE TITLE
[BUG] "Cannot find module 'graphql/language/printer" aka not finding peer dependencies

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2018]
**Describe the bug**
When attempting to use a library with a unregistered peer dependency, even with adding the dependency to the component's internal `node_modules`, the deploy will fail.

**To Reproduce**
1. Create a new component
2. Attempt to use the `graphql-request` library in an action/source in a `sample_app.js`
3. Init a `package.json` and include the `graphql-request` and `graphql` deps
4. Run `pd dev sample_app.js`

**Expected behavior**
Expect the `node_modules` / `package.json` for that component to be read and dependencies loaded.

**Screenshots**

Terminal output:
```bash
watch:add     | /Users/pierce/dev/pipedream/components/shopify_partner/actions/list_charges.js
watch:add     | /Users/pierce/dev/pipedream/components/shopify_partner/shopify_partner.app.js
Detected local requires, creating zip archive...
- actions/list_charges.js
- shopify_partner.app.js
error         | component create api call responded with status: 400, body: {"error":"{\"name\":\"UserError\",\"message\":\"Error: Cannot find module 'graphql/language/printer'\\nRequire stack:\\n- /tmp/tmp-9lTGjf85sZScc/e698551e98ba4f2502a7c61e00b89a89571d31d1abbd48062c97c3782e3e837f/node_modules/graphql-request/dist/index.js\\n- /tmp/tmp-9lTGjf85sZScc/e698551e98ba4f2502a7c61e00b89a89571d31d1abbd48062c97c3782e3e837f/user/shopify_partner.app.js\\n- /tmp/tmp-9lTGjf85sZScc/e698551e98ba4f2502a7c61e00b89a89571d31d1abbd48062c97c3782e3e837f/user/actions/list_charges.js\\n- /tmp/tmp-9lTGjf85sZScc/e698551e98ba4f2502a7c61e00b89a89571d31d1abbd48062c97c3782e3e837f/component.js\\n- /var/task/src/index.js\\n- /var/runtime/UserFunction.js\\n- /var/runtime/index.js\"}"}
Waiting for file change (or ^C to quit)...
```

`components/shopify_partner/package.json`

```json
{
  "name": "@pipedream/shopify_partner",
  "version": "0.0.1",
  "description": "Pipedream Shopify Partner Components",
  "main": "shopify_partner.app.js",
  "keywords": [
    "pipedream",
    "shopify",
    "shopify partner"
  ],
  "author": "Pipedream <support@pipedream> (https://pipedream.com)",
  "license": "MIT",
  "dependencies": {
    "graphql": "^16.2.0",
    "graphql-request": "^3.7.0"
  }
}

```

**Additional context**

Found a workaround by explictly including the module that needs to be resolved in the entry point of the source:

```javascript
require("graphql/language");
const { GraphQLClient } = require("graphql-request");

module.exports = {
  type: "app",
  app: "shopify_partner",
  methods: {
    async query({ query, mutation, variables }) {
      const endpoint = `https://partners.shopify.com/${this.$auth.organization_id}/api/2021-04/graphql.json`;
      const client = new GraphQLClient(endpoint, {
        headers: {
          "Content-Type": "application/json",
          "X-Shopify-Access-Token": this.$auth.api_key,
        },
      });

      return await client.query(query || mutation, variables);
    },
  },
};

```

**Comment by ctrlaltdylan** [comment]
Additional context - I was running a component _within_ the `pipedream/components` directory locally.

Perhaps that is causing the issue, maybe it needs to be in it's own repo.

**Comment by vunguyenhung** [comment]
Hello @ctrlaltdylan, I'm couldn't reproduce this issue using your information in the description. Here's the step I have taken:
1. I created a [sample app](https://github.com/vunguyenhung/pipedream/pull/1) having one source and one action using `graphql` and `graphql-request` deps
2. Then on `pipedream/components`, I run `pd dev <path>` both the action and the source
3. I observed that the `pd dev` commands executed successfully 

Could you try again on your end?

My local action
![image](https://user-images.githubusercontent.com/18277920/172616958-e93ccfeb-50da-488b-97d9-852e1392ab5a.png)

My local source
![image](https://user-images.githubusercontent.com/18277920/172616993-b5738286-0f9c-4d67-8f38-9f813b952e0f.png)

Pipedream UI Action
![screencapture-pipedream-sources-dc-gzu0eXR-logs-2022-06-08-19_32_47](https://user-images.githubusercontent.com/18277920/172617128-da7c3254-0c2d-47fa-9fb9-fa69b85d1115.png)

Pipedream UI Source
![screencapture-pipedream-sources-dc-EYu7nxZ-logs-2022-06-08-19_33_25](https://user-images.githubusercontent.com/18277920/172617203-ca358980-b03e-4da1-9412-8f6f6eef6c95.png)

**Comment by ctrlaltdylan** [comment]
@vunguyenhung this bug was filed before there was some work done before builder v2 and the changes to the pnpm install commands on deployed components. If you're unable to reproduce then I'd say the bug is fixed. Thanks for taking a look!
