### ISSUE TITLE
Configure automatic retries for workflows

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#202]
I'd like a way to configure automatic retries for a workflow so that, if it throws an error, I can run it again N number of times with a specified delay.

**Comment by calpa** [comment]
My workflow stopped due to this error:
```
FUNCTION_ERROR — We currently do not have sufficient capacity in the region you requested. Our system will be working on provisioning additional capacity. You can avoid getting this error by temporarily reducing your request rate.
```

I hope that it will be retried automatically.

**Comment by dylburger** [comment]
This is live! https://pipedream.com/docs/workflows/settings/#auto-retry-errors
