### ISSUE TITLE
[FEATURE] Automatically populate `component.key` based off the component parent directory & component name

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2023]
**Is your feature request related to a problem? Please describe.**

The Components API requires a `key` property. As a new developer, it's not immediately apparent there is a naming convention until you make a pull request.

In the pull request there is a helpful checklist, and one of the first items is to follow the component key convention:

https://pipedream.com/docs/components/guidelines/#component-key-pattern

**Describe the solution you'd like**

It would be nice if this was inferred.

For example, if the `slack` component had an action `Send Message`. Behind the scenes the component system would automatically generate the `key` to be `slack-send_message` instead of the developer having to realize the naming convention.

**Do you have a workaround?**
Yes, we can manually follow the convention. Not a problem.

Very low on the pain scale, just an improvement that would help lower the cognitive load for new developers.

**Comment by dylburger** [comment]
@ctrlaltdylan I had a couple of ideas.

`pd init` generates a `key` with the component it creates, but it doesn't include the app name. What do you think about:

```bash
pd init source my-source --app google_calendar
```

That would create a `my-source` component with the key `google_calendar-my-source`. We could document it but clearly that's not discoverable.

[`eslint-plugin-pipedream`](https://github.com/PipedreamHQ/eslint-plugin-pipedream) should be able to detect the presence of an app prop in the component and check to see if the `key` starts with its slug.

wdyt?

**Comment by dylburger** [comment]
Closing since this is solved by `pd init`
