### ISSUE TITLE
Apollo integration

### ISSUE THREAD

**Issue by gln5155** [PipedreamHQ/pipedream#2025]
**Apollo.io**

**[Link to developer documentation](https://apolloio.github.io/apollo-api-docs/#introduction)**

**Is lack of support preventing you from building workflows, or do you have a workaround? **I have workaround but direct integration would be great****

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each! **Enrichment call, Trigger when new contact/company added to Apollo****

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
