### ISSUE TITLE
[FEATURE] add alias `pd new` that maps to `pd init` 

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2026]
**Is your feature request related to a problem? Please describe.**
Adding `pd new` as an alias to `pd init` would be a slight improvement to usability.

`init` could mean that you're starting up a component, whereas the keyword `new` is more clear that a new component is being made.

**Describe the solution you'd like**

An alias in the `pd` cli to support `new` as an alias to `init`.

**Do you have a workaround?**
Low level pain, would just be nice to have.

**Comparable features in other tools?**

`rails g <resource>` is clear that it generates a new "thing".

`php artisan make:<resource>` is the equivalent in that framework.

I think `pd new` rhymes.

**Comment by dylburger** [comment]
Nice makes total sense

**Comment by dylburger** [comment]
Shipped in v`0.2.3` of the CLI!
