### ISSUE TITLE
[ACTION] ultramsg

### ISSUE THREAD

**Issue by ultramsg** [PipedreamHQ/pipedream#2038]
**Is there a specific app this action is for?**
ultramsg

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.ultramsg.com/api/post/messages/chat

**code** 
 
import axios from "axios"

export default {
	name: "Send Message",
	description: "Send a text message to phone number or group",
	key: "ultramsg_action_send_message",
	version: "0.0.9",
	type: "action",
	props: {
		ultramsg: {
			type: "app",
			app: "ultramsg",
		},
		to: {
			type: "string",
			label: "To",
		},
		body: {
			type: "string",
			label: "Body",
		},
		priority: {
			type: "string",
			label: "Priority",
		},
	},
	async run() { 
		const response = await axios({
			method: "POST",
			url: `https://api.ultramsg.com/${this.ultramsg.$auth.instance_id}/messages/chat`,
			headers: {
				"Content-Type": `application/x-www-form-urlencoded`,
			},
			params: {
				token: `${this.ultramsg.$auth.token}`,
				to: `${this.to}`,
				body: `${this.body}`,
				priority: `${this.priority}`,
			},
		});
		return response.data
	},
}

**Comment by dannyroosevelt** [comment]
Thank you @ultramsg, can you please submit a PR with your code so that we can review, provide feedback, and test out the functionality? https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
