### ISSUE TITLE
Supportivekoala

### ISSUE THREAD

**Issue by nadalfederer** [PipedreamHQ/pipedream#2039]
**Name of app / service**

Supportivekoala

**Link to developer documentation**

https://developers.supportivekoala.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

No, I can store API key in env

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Just auth

**Comment by dannyroosevelt** [comment]
@nadalfederer here you go! https://pipedream.com/apps/supportivekoala/

FYI if you're interested in building out any actions or triggers, all our components are open source: https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by nadalfederer** [comment]
Thank you
