### ISSUE TITLE
[ACTION] add youtube scheduling Live streming

### ISSUE THREAD

**Issue by gitfabiolagana** [PipedreamHQ/pipedream#2044]
It's possibile to add action for YouTube Live Streaming API to create, update, and manage live events on YouTube?

https://developers.google.com/youtube/v3/live/getting-started

**Comment by dannyroosevelt** [comment]
It looks like the YouTube Data API, which we already have integrated on our platform is the one you need: https://pipedream.com/apps/youtube-data-api

FYI all our actions and triggers are open source and we're happy to help provide guidance and support if you're interested in building some of these out: https://pipedream.com/docs/components/guidelines/#getting-started

Is that something you'd be interested in exploring?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
