### ISSUE TITLE
[BUG] Pagination error in search results on Explore page

### ISSUE THREAD

**Issue by caesiumtea** [PipedreamHQ/pipedream#2048]
**Describe the bug**
On the Explore page of the Pipedream site, the list of apps doesn't display the results of your search if you were already viewing results later than 12 when you typed your search. The pagination says, eg, "13 - 1 of 1 apps by most popular". Also, the arrow buttons aren't shown, so you can't even navigate to the first page to see the result. 

**To Reproduce**
1. Go to https://pipedream.com/explore
2. Look at the "Explore all apps" section 
3. Click the next/right arrow button below the list of apps to view apps 13-24 (i.e., page 2)
4. Click inside the search bar and enter a term that has between 1 and 12 results, such as "notion"
5. Invisible results!
To confirm that it's just a problem with pagination and not a problem with the specific app being searched:
6. Clear the search bar, which makes it go back to showing results 13-24 out of all apps
7. Click the back/left arrow button to go back to results 1-12
8. Type in the exact same search term again, while viewing the first page of results instead - this time it should behave as expected and show the 1 result

**Expected behavior**
When a search is run, the list should immediately revert to displaying the first page of results.
Text should say "1 - 1 of 1 apps" instead of "13 - 1" (or whatever number it was displaying before typing the search).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 97.0.4692.71

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
