### ISSUE TITLE
[TRIGGER] Hubspot

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#205]

**Comment by todsac** [comment]
QQ - it looks like there may be a need to breakout Hubspot and Hubspot CRM.  Please evaluate and make a call.

New Event - Generic trigger for when a specified user event occurs
New Contact
Contact Modified
New Contact in List
New Contact Property Change
New Form Submission
New Calendar Task
New Company
New COS Blog Article
New Deal
New Deal in Stage
New Deal Property Change
New Email Event
New Engagement

**Comment by michelle0927** [comment]
Updated list

New Event
New Contact
Contact Modified
New Contact in List
New Form Submission
New Calendar Task
New Company
New COS Blog Article
New Deal
New Deal in Stage
Deal Modified
New Email Event
New Engagement
