### ISSUE TITLE
Azure DevOps Services

### ISSUE THREAD

**Issue by joshacct1986** [PipedreamHQ/pipedream#2069]
**Name of app / service**
Azure DevOps Services

**Link to developer documentation**
https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Looking for out of the box trigger/flow connecting webhooks (POST calls) to Azure DevOps Services. Able to create a custom application, but would rather it be part of Pipedream for ease of use.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Create Work Item, Update Work Item, Add Attachment, Create Build, Create Release, Approve Release

**Comment by dylburger** [comment]
Azure Devops is integrated! See https://pipedream.com/apps/azure-devops for more information
