### ISSUE TITLE
Addition of GoCardless' API

### ISSUE THREAD

**Issue by gregrobsonoxb** [PipedreamHQ/pipedream#2078]
**GoCardless** - Payment processor for regular/scheduled direct debit (or equivalent) bank payments.

[**Developer Documentation Reference**](https://developer.gocardless.com/api-reference/)

**Interim support** - you can create axios HTTP requests and use account environment variables for authentication tokens.

## Actions
API is a straightforward REST/JSON api (very consistent naming architecture), once one [core endpoint](https://developer.gocardless.com/api-reference/#core-endpoints) is done, the others would be straightforward.

### URL Scheme
There are two base URLs for sandbox and non-sandbox mode: https://developer.gocardless.com/api-reference/#api-usage-making-requests

### Authentication
Requests are made through a basic bearer token that you request from their dashboard: https://developer.gocardless.com/api-reference/#making-requests-authentication

### Versioning
Very stable API - Last update was 2015-07-06. https://developer.gocardless.com/api-reference/#making-requests-versions

**Comment by todsac** [comment]
I have submitted an app for review with GoCardless and will revert back once we have a version live.

**Comment by gregrobsonoxb** [comment]
Fantastic - their sandbox is really good as it emulates the production environment exactly.

**Comment by sergio-eliot-rodriguez** [comment]
GoCardless has been integrated.

It's actually a migration from Nordigen which was relaunched -- https://pipedream.com/apps/nordigen
