### ISSUE TITLE
[APP] IMAP (Email)

### ISSUE THREAD

**Issue by js07** [PipedreamHQ/pipedream#2081]
**Name of app / service**
IMAP

**Link to developer documentation**
- IMAP Protocol: https://datatracker.ietf.org/doc/html/rfc3501
- IMAP client module for Node.js: https://www.npmjs.com/package/imap

To show IMAP commands with curl:
```
curl -v imap://user:password@in.server.com/
```
Implicit SSL:
```
curl "imaps://user:password@in.example.com"
```

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Workaround: created an event source with component props required to create an IMAP connection.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Trigger:
**New Email** | Triggers when you receive a new email.
_Implemented in https://github.com/PipedreamHQ/pipedream/pull/1977. If an IMAP app is integrated, the `host`,`username`,`password`,`port` props can be replaced with `this.$auth` properties._

**Suggested Account Data**
- **Host** | The host Pipedream should connect to
- **Username** | The email address/username you use to login to your email account
- **Password** | The password you use to login to your email account. Note: To connect a Gmail account to a third-party IMAP tool (like Pipedream), you must use an [App password](https://support.google.com/accounts/answer/185833).
- **Port** | The port number, either Port 143 (default) or Port 993. Consult your email provider's IMAP instructions if you aren't sure which one you need.

**Comment by dannyroosevelt** [comment]
@js07 lmk if this works or if we need to make any changes -- https://pipedream.com/apps/imap

**Comment by js07** [comment]
This looks good to me. In `imap.app.mjs` methods, `this.$auth` contains the correct connection fields, as they were configured.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
