### ISSUE TITLE
[ACTION] help!!  google sheet Print the lookup row in a column

### ISSUE THREAD

**Issue by kim-kyoungseek** [PipedreamHQ/pipedream#2082]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**
![sheet](https://user-images.githubusercontent.com/23028171/150346783-1eb0d9d7-deab-468b-bb84-926836f22ca4.PNG)
Hello.

If you enter an e-mail form in the value, search is not possible.

please check.

**Comment by kim-kyoungseek** [comment]
g

**Comment by dannyroosevelt** [comment]
Hi @kim-kyoungseek I just ran through a test and was able to locate an email address in a Google Sheet on my end -- is it possible the column does not contain that value? You might try adding a code step before the `find_row` step to just return that email value you're searching for, to help debug and double-check the value is what you're expecting. For example: 
![image](https://user-images.githubusercontent.com/20780753/150386035-35970ccf-a28e-476d-9952-d1ac7f9da928.png)

**Comment by kim-kyoungseek** [comment]
It's been resolved.
thank you.
