### ISSUE TITLE
[FEATURE] Ability to organize workflows in folders/categories

### ISSUE THREAD

**Issue by r-dehoyos** [PipedreamHQ/pipedream#2088]
**Is your feature request related to a problem? Please describe.**
The more workflows I create in my account, the more frustrating it becomes to search for a specific one for review/debug/improvement.

**Describe the solution you'd like**
Ability to organize workflows in folders/categories.

**Do you have a workaround?**
It's not necessary but would improve user experience a ton.

**Comparable features in other tools?**
Most platforms out there have this (I guess you ask this for more complicated requests).

**Comment by dylburger** [comment]
Hi @r-dehoyos , thank you very much for the request. I hear you completely and this is near the top of our backlog. We're tracking the feature at #203 , so I'm going to close this issue. You can follow that issue to get updates as we make progress.
