### ISSUE TITLE
Puppeteer / Playwright support

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#209]
[Puppeteer](https://github.com/GoogleChrome/puppeteer) provides a Node API to drive a Chrome headless browser. This allows you to programmatically visit sites, take screenshots, and more.

PIpedream currently doesn't support Puppeteer, but I'd like to run workflows that use it.

**Comment by chrigi** [comment]
https://puppet-master.sh/ seems to no longer exist, at least the website/service. The repo is still there: https://github.com/saasify-sh/puppet-master

Does the piedream integration support a self hosted version? If not, I guess the integration could be removed.

**Comment by dylburger** [comment]
@chrigi confirmed. I removed the Puppet Master app from our integrations. Have you tried Browserless? That's what we use internally.

**Comment by bloycey** [comment]
Puppeteer support would be amazing. Will follow along here for updates.

**Comment by chrigi** [comment]
I was mainly looking for an easy way to scrape an SPA but later noticed that even if Pupper-Master was still around it seems like it only supported taking a screenshot (I think?) and didn't want to pay for Browserless, it's not that important to me. Luckily I noticed the hydration function was easy to find and I could just extract and execute that on Pipedream and parse the resulting datastructure, so no Puppeteer necessary for the moment.

**Comment by justinr1234** [comment]
Can confirm I need this as well. Was trying to find a workaround, but haven't been able to come up with anything.

**Comment by ashutoshsaboo** [comment]
Hello, Can we add support for playwright too? There's a different package for running it on AWS lambda - https://github.com/JupiterOne/playwright-aws-lambda . The readme mentions that it's based on `chrome-aws-lambda` but i'm not sure if it needs the same `process.umask` for Node 10 that you mention above. 

@dylburger If this can work without, can we support this rather?

**Comment by dylburger** [comment]
@ashutoshsaboo I tested again and neither the native Playwright package, nor `playwright-aws-lambda`, work out of the box on Pipedream. When we tackle this larger issue, we'll investigate support for Playwright, as well (I've updated the issue title to reflect that).

**Comment by gaelduplessix** [comment]
I managed to make it work using https://www.browserless.io and `puppeteer-core` (`puppeteer` fails to install because it tries to download chromium):
```js
const puppeteer = require('puppeteer-core');

let browser;

try {
  browser = await puppeteer.connect({
    browserWSEndpoint: 'wss://chrome.browserless.io',
  });
  const page = await browser.newPage();

  await page.goto('https://www.example.com');

  const res = await page.evaluate(() => document.querySelector('h1').innerHTML);

  return res;
} catch (error) {
  return null;
} finally {
  if (browser) {
    await browser.close();
  }
}
```

**Comment by sjn001tvh** [comment]
Thanks Dylan for pointing me to this thread.  I appreciate that I'm not the only one who would like to have a browserless solution to open a webhook to a browser.  In developing one of the workflow steps, I'm needing to create a UI to input and manipulate information before I submit a project record into ClickUp.  In using Dropbox as a trigger mechanism, I use some of the steps to extract data from ClickUp, and process it to an html file containing dropdown lists that I can select from my phone with minimal typing.  I distain inputting text information from my phone using my index finger to type in the information.  Brief entries are acceptable, but descriptions of projects, etc. and trying to maintain consistency for project types, which can get out of hand quickly by entering them in by hand, without having them in a list, causes extra work that shouldn't be necessary.  I was hoping that the Puppeteer would be able to solve this problem because it was free.  I guess I was just being cheap.  I've already signed up for browserless.io to pay as you go.  The rates aren't that bad for me, in view that I probably will use the service more during the initial testing phase, than I will when the actual workflow has been completed.

**Comment by Rutledge** [comment]
+1 for puppeteer native support. Hopefully more than a pipedream :)

**Comment by sirloinofbeef** [comment]
Following

**Comment by Mind-Reader** [comment]
+1

**Comment by ruie** [comment]
+1

**Comment by tomrob765** [comment]
+1 (!)

Can't wait to do this straight from Pipedream! My workaround is using the API from this site: https://htmlcsstoimage.com/ - which works quite well to their credit

**Comment by rubentorresbonet** [comment]
Hey, any update regarding running the binaries? when trying playwright there is an error:
Executable doesn't exist at /home/sbx_user1051/.cache/ms-playwright/chromium-1019/chrome-linux/chrome

**Comment by dylburger** [comment]
@rubentorresbonet Not yet. We are likely to provide the Chrome binary ourselves since it requires some special tweaks to work in our execution environment. This isn’t on our immediate backlog but we’ll update you here when we do that work. 

Did you check out Browserless or other remote browser services? Curious if that would work for your use case.

**Comment by restyler** [comment]
Hey guys I have [recorded a short video on how Pipedream can be used to run headless Chrome API ](https://www.youtube.com/watch?v=uBC752CWTew). ScrapeNinja API, which is used in the video, is not exactly a generic Puppeteer instance, it has two API endpoints, /scrape and /scrape-js, where /scrape-js is basically a "dumbed down" version of headless Chrome, which is much more convenient to use, as it is targeted at specific use case of web scraping websites. If your use case is not web scraping related, ScrapeNinja is probably not for you and the video will not be relevant.

Building low code web scraper to extract Hackernews titles to Google Sheets, via Pipedream:
https://www.youtube.com/watch?v=uBC752CWTew

**Comment by cshape** [comment]
Following! It's nice that you can scrape with other methods but I've got some stuff built with Puppeteer and it would be great to just copy/paste into Pipedream.

**Comment by eyalway2cu** [comment]
Would also love to have Puppeteer support in Pipedream :).
#commenting to get updates :)

**Comment by parisetflorian** [comment]
+1

**Comment by sam-frampton** [comment]
+1

**Comment by ctrlaltdylan** [comment]
Pipedream now supports [Playwright](https://playwright.dev/) and [Puppeteer](https://pptr.dev/) natively in your Node.js code steps & pre-built actions natively! No 3rd party APIs are required to issue commands a Chromium remotely.

Beyond retrieving HTML content, you can perform actions like clicking on elements, rendering Javascript on SPA sites, generating screenshots, capturing PDFs.

Simply import `@pipedream/browsers` within your Node.js code running on Pipedream to install & run a [Puppeteer](https://pipedream.com/apps/puppeteer) or [Playwright](https://pipedream.com/apps/playwright) browser and launch a Puppeteer or Playwright browser.

Or just use the pre-built actions for Puppeteer & Playwright to get HTML content, take a screenshot or generate a PDF for a webpage.

Here’s an example running a Puppeteer instance to scrape HTML from a webpage:

```javascript
import { puppeteer } from '@pipedream/browsers';

export default defineComponent({
  async run({steps, $}) {
    const browser = await puppeteer.browser();
    
    // Interact with the web page programmatically
    const page = await browser.newPage();

    await page.goto('https://pipedream.com/');
    const title = await page.title();
    const content = await page.content();

    await browser.close();
    
    return { title, content }'
  },
})
```

**Comment by milenamilka755** [comment]
Is puppeteer trigger available in Free plan?
