### ISSUE TITLE
Withings Health

### ISSUE THREAD

**Issue by AndrewBarber** [PipedreamHQ/pipedream#2123]
**Name of app / service**
Withings Health

**Link to developer documentation**
https://developer.withings.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No / can write custom NodeJS code to connect.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
New measurement, etc

**Comment by dannyroosevelt** [comment]
Hey @AndrewBarber looks like we already have Withings as an integrated app: https://pipedream.com/apps/withings

Let me know if you run into any issues!

**Comment by AndrewBarber** [comment]
Hi @dannyroosevlt

Not sure if this is hidden behind something, but I receive a 404 on the link. 
I've tried searching the apps too but nothing found.  

Any ideas?
![image](https://user-images.githubusercontent.com/135927/151244629-e3c14495-8cea-4e93-9b99-d7031c1f67cf.png)

**Comment by dannyroosevelt** [comment]
Oops, that was my mistake, sorry about that! Go ahead and give it another try : )

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
