### ISSUE TITLE
[BUG] Google Photos not show in page 1 of apps when searching for 'google photos'

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2126]
**Describe the bug**
When adding a new step, if I search for `google photos`, the app does not show in the first page. I have to click load more apps. I assume it's searching for all the words of my input, but it was odd that it wasn't show initially.

**To Reproduce**
Add a step
Search for 'google photos'

**Expected behavior**
I'd expect to see it in the initial 'page' of apps.

**Screenshots**

**Comment by dannyroosevelt** [comment]
Thanks for flagging, @cfjedimaster. I've confirmed I'm seeing the same on my end too.

**Comment by dylburger** [comment]
This is technically the same issue as #661 . I'm closing this in favor of that original ticket (and I linked another related one).

**Comment by cfjedimaster** [comment]
oh wow - and I logged that one too - sorry ;)
