### ISSUE TITLE
[BUG] make sh: make: command not found 

### ISSUE THREAD

**Issue by davetapley** [PipedreamHQ/pipedream#2127]
**Describe the bug**

When trying to use [`uplink-nodejs`](https://www.npmjs.com/package/uplink-nodejs) it fails with:

`npm update check failed` ... `make sh: make: command not found`

**To Reproduce**
1. Create a web trigger
2. Add a `nodejs` step
3. Paste snippet below

**Expected behavior**
Logs error saying it can't authenticate.

**Screenshots**

```
Command failed: upm -l nodejs add --guess --> npm init -y Wrote to /tmp/ee/package.json: { "name": "ee", "version": "1.0.0", "description": "", "main": "index.js", "scripts": { "test": "echo \"Error: no test specified\" && exit 1" }, "keywords": [], "author": "", "license": "ISC" } ┌────────────────────────────────────────────────────────────────┐ │ npm update check failed │ │ Try running with sudo or get access │ │ to the local update config store via │ │ sudo chown -R $USER:$(id -gn $USER) /home/sbx_user1051/.config │ └────────────────────────────────────────────────────────────────┘ --> npm install uplink-nodejs npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 npm WARN deprecated har-validator@5.1.5: this library is no longer supported npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. > uplink-nodejs@1.2.6 preinstall /tmp/ee/node_modules/uplink-nodejs > make sh: make: command not found npm WARN ee@1.0.0 No description npm WARN ee@1.0.0 No repository field. npm ERR! code ELIFECYCLE npm ERR! syscall spawn npm ERR! file sh npm ERR! errno ENOENT npm ERR! uplink-nodejs@1.2.6 preinstall: `make` npm ERR! spawn ENOENT npm ERR! npm ERR! Failed at the uplink-nodejs@1.2.6 preinstall script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! /tmp/npm_cache/_logs/2022-01-26T18_15_19_877Z-debug.log exit status 1
```

**Additional context**

Snippet:

```js
  const storj = require("uplink-nodejs");
  const libUplink = new storj.Uplink();

  var satelliteURL = "change-me-to-desired-satellite-address";
  var apiKey = "change-me-to-desired-api-key";
  var encryptionPassphrase = "change-me-to-desired-encryption";

  var access = await libUplink.requestAccessWithPassphrase(satelliteURL, apiKey, encryptionPassphrase).catch((err) => {
    console.log(e)
  }); 
console.log("OK")
```

**Comment by ctrlaltdylan** [comment]
Hi @davetapley

Thanks for the report, that is an interesting one.

From what I can tell, in the `uplink-nodejs` installation docs, it has a dependency on Go being installed and available in `$PATH`. 

Unfortunately at this time, Go is not available in Node.js code steps.

We do support all NPM packages, but this is an interesting case were the NPM package itself requires an environment with another language as a dependency. Since Go isn't distributable as an NPM package, then we can't resolve it via NPM and make it available in the step's runtime.

For now, I would say that this isn't possible. But I'm going to confer with the rest of the team and make sure this is the case.

**Comment by ctrlaltdylan** [comment]
Hi @davetapley , after some discussion with the team it's more likely than not that we will support other languages besides Node.js in Node.js code steps in the near term. That includes Linux tools like `make` to build binaries from source.

Sorry, but for now we can't support this use.

**Comment by davetapley** [comment]
Thanks for the fast feedback @ctrlaltdylan, totally understand where you're coming from.

On second thought, this would be much more useable as a separate app anyway,
so I went ahead and opened #2132 
which is what I should've done in the first place 😁
