### ISSUE TITLE
[ACTIONS] Sentry

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2135]
- List a Project's Events:
Return a list of events bound to a project.
https://docs.sentry.io/api/events/list-a-projects-events/

- List a Project's Issues: Return a list of issues (groups) bound to a project
https://docs.sentry.io/api/events/list-a-projects-issues/

- Update an Issue: Updates an individual issue's attributes
https://docs.sentry.io/api/events/update-an-issue/

**Comment by vunguyenhung** [comment]
Hello @vellames-turing, I have tested this PR and there're some test cases failed or needed improvement. Please check the test report below for more information 🙏
[Sentry_Test_Report_2201.pdf](https://github.com/PipedreamHQ/pipedream/files/8670101/Sentry_Test_Report_2201.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release!

Test report
[Sentry_Test_Report_2309.pdf](https://github.com/PipedreamHQ/pipedream/files/8680867/Sentry_Test_Report_2309.pdf)
