### ISSUE TITLE
run node.js code with google sheet

### ISSUE THREAD

**Issue by bluemonday1** [PipedreamHQ/pipedream#2137]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by ctrlaltdylan** [comment]
Hi @bluemonday1 , thanks for opening an issue. Can you tell us more about what you're trying to accomplish and the problem you're facing?

Here's docs on how to use Node.js in code steps: https://pipedream.com/docs/workflows/steps/code/

We do have a Google Sheets integration you can use to send data to Google Sheets: https://pipedream.com/apps/google-sheets

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
