### ISSUE TITLE
[UPDATE] Google Sheets Add Single Row

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2143]
We need to make a couple updates to the latest Add Single Row GSheets action (v 2.0.0):
- [x] If `hasHeaders` is set to `Yes` and I am entering data in individual cells (not passing an array), we should handle empty strings the same way we do in the `sanitizedArray` helper (update each cell w/ an empty string). [This is the current behavior](https://capture.dropbox.com/epQSffU0gOBGFH3T), [this is my expectation](https://capture.dropbox.com/4KmX6Os3ZEuXb4Ct).
- [x] We should also stringify anything that is passed in those fields (right now [we throw an ugly error](https://capture.dropbox.com/IkGz2YxshWcUaZFO))
- [x] Bonus points: when we stringify an input, let's note that in the `$summary` output (something like, "We detected something other than a string in one of the fields and automatically converted it to a string..."

**Comment by dannyroosevelt** [comment]
@vellames-turing let me know if these updates make sense and if you're able to take a look, since you worked on the last updates to this action

**Comment by rhay-repo** [comment]
Hi, I'm Reagan and I've been asked to contribute to an open-source project for my Software Development course. I'm very interested to work on this issue. I would appreciate it if I could be assigned or added as an additional participant to this issue.

If so, could you guide me in how to approach this issue or where to look?

**Comment by dannyroosevelt** [comment]
Hi @rhay-repo why don't you take a look at [this issue](https://github.com/PipedreamHQ/pipedream/issues/1511) instead? Here is a good place to get started: https://pipedream.com/docs/components/guidelines/#getting-started

We have an active community of developers in [our Slack community](https://pipedream-users.slack.com/archives/C01E5KCTR16) -- that'd be the best place to ask questions and get support!

**Comment by vellames-turing** [comment]
Hey @dannyroosevelt. Sure, I can take a look. I started to work on MongoDB new actions again in order to apply the suggestions. As soon as I submit MongoDB new actions I will start to take a look here :)

**Comment by vellames-turing** [comment]
I added a more detailed message. What do you think?
![Screen Shot 2022-02-03 at 4 15 14 PM](https://user-images.githubusercontent.com/91911778/152413045-edad7ccc-d32e-462a-b11c-b47378d8bc67.png)

**Comment by vellames-turing** [comment]
Looks like everything is working so far
![Screen Shot 2022-02-03 at 4 20 52 PM](https://user-images.githubusercontent.com/91911778/152413819-ea17b942-d699-447d-b3d6-98b479660b27.png)
