### ISSUE TITLE
[BUG] $checkpoint updates not persisted if the step fails due to a timeout error

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2157]
**Describe the bug**
As a workflow developer
Given my step has a `$checkpoint` update
And after the update the step times out
I expect the `$checkpoint` to still persist

**To Reproduce**
Copy this workflow, set the workflow's settings timeout to 1 second.

https://pipedream.com/@pierce/copy-of-checkpoint-persistence-timeout-error-p_LQC5Gjg/edit?e=24VwLMxx93VeyB3nnTbJjhokxZ8

**Expected behavior**
The `$checkpoint` is incremented _before_ the timeout error occurs and it should have persisted the update to the next run.

**Screenshots**

<img width="1136" alt="CleanShot 2022-02-01 at 10 20 16@2x" src="https://user-images.githubusercontent.com/2694734/151997485-8586abbc-7549-4a3f-b7e9-c9b6cd8c39ce.png">
<img width="1174" alt="CleanShot 2022-02-01 at 10 20 34@2x" src="https://user-images.githubusercontent.com/2694734/151997495-be82efe9-2c93-49bd-b9a7-d017abc944cf.png">

**Additional context**
Original reported workflow: https://pipedream.com/@mjbain10/checkpoint-persistence-timeout-error-p_6lCM22e

**Comment by dylburger** [comment]
Closing since `$checkpoint` has been replaced with [data stores](https://pipedream.com/docs/data-stores/).
