### ISSUE TITLE
Action Property default value not properly populated in workflow from Event data

### ISSUE THREAD

**Issue by dgolubev** [PipedreamHQ/pipedream#2165]
I created action
```
export default {
    key: 'price-event-consumer-t2',
    type: 'action',
    version: '0.0.7',
    name: '[DG] Event Consumer - test 2',
    description: 'Consume event and produce required action',
    props: {
        productId: {
            type: 'string',
            label: "sku",
            description: 'sku - props',
            default: `{{event.key}}`,
        },
    },
    async run(event) {
        console.log('Product: ', this.productId);
    },
};

``````
when I add this action to workflow, it look like on image

But then i run i receive
```
console (2)
ProductId:  {{event.key}}
```

I same time. If i go to configure, click on property value and select field in event and ‘select path’, then on run it show value from event
```
console (2)
ProductUd:  1643791527661-pricebook-value_from_event
```
![Screenshot 2022-02-02 at 14 43 16](https://user-images.githubusercontent.com/207957/152198949-46745cc8-d17b-41d3-a118-95edcf5871f5.png)

**Comment by dylburger** [comment]
@dgolubev Thanks for the bug report. We're looking into this.

**Comment by dylburger** [comment]
@dgolubev This should no longer be an issue in [the new version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/). I tried publishing the following action:

```javascript
export default {
    key: 'price-event-consumer-t2',
    type: 'action',
    version: '0.0.8',
    name: '[DG] Event Consumer - test 2',
    description: 'Consume event and produce required action',
    props: {
        productId: {
            type: 'string',
            label: "sku",
            description: 'sku - props',
            default: `{{steps.trigger.event}}`,
        },
    },
    async run(event) {
        console.log('Product: ', this.productId);
    },
};
```

Note that in the new version of the builder, `event` has been deprecated, so I set a default of `{{steps.trigger.event}}` (which is equivalent).

When I test the step:

<img width="462" alt="Screen Shot 2022-02-22 at 9 12 49 AM" src="https://user-images.githubusercontent.com/242668/155183476-af8db951-e983-42ae-93f9-8c75c6ad8f36.png">
