### ISSUE TITLE
[ACTION] Gmail

### ISSUE THREAD

**Issue by dzg** [PipedreamHQ/pipedream#2166]
**Is there a specific app this action is for?**

Gmail

**Please provide a link to the relevant API docs for the specific service / operation.**

[**https://developers.google.com/gmail/api**](https://developers.google.com/gmail/api)

Would be nice to be able to send as myself, and include attachments, etc.

**Comment by Startmyg1t** [comment]
All info is still in broken motorolla I don't have $for the insurance this is a nightmare

**Comment by dannyroosevelt** [comment]
This is in progress here: https://github.com/PipedreamHQ/pipedream/issues/4064

**Comment by dannyroosevelt** [comment]
We just shipped a Gmail integration!
https://pipedream.com/community/t/gmail-is-now-available-on-pipedream/3269

**Comment by dzg** [comment]
> We just shipped a Gmail integration! https://pipedream.com/community/t/gmail-is-now-available-on-pipedream/3269

That baby is just way too cute
