### ISSUE TITLE
[BUG] Zoho.com auth failure

### ISSUE THREAD

**Issue by dzg** [PipedreamHQ/pipedream#2167]
Tried to connect Zoho.com, got this:

>Pipedream app connection failure. Please reach out to support@pipedream.com (provide this exception ID: 452954f99d19400e8c451ff855ed967e)

**Comment by ctrlaltdylan** [comment]
Hi @dzg, thanks for reaching out.

The good news is the connection between Zoho Mail and Pipedream succeeded, but when Pipedream attempted to retrieve your account details - Zoho responded that it failed to retrieve your account details.

Couple things to try:

1. Can you currently log in with that Zoho account in the Zoho.com dashboard?
2. Is that account setup for Zoho Mail? If not, that could be the problem.

**Comment by dzg** [comment]
Yes I can login and access mail at [https://mail.zoho.com/zm/#mail...](https://mail.zoho.com/zm/#mail...)

Not sure what you mean if it's set up for Zoho Mail ... that's all I use on Zoho.

Thanks

**Comment by dzg** [comment]
This is what I see right before the error:

![](https://user-images.githubusercontent.com/466557/152256466-b589beae-eccc-4038-9304-c9421d64844a.png)

**Comment by dzg** [comment]
And this shows in my account settings:

![](https://user-images.githubusercontent.com/466557/152256732-33048a34-14b5-4609-91e0-755f487cb7a3.png)

**Comment by dzg** [comment]
Yes, I did that. Otherwise can't even get to the consent screen above.

**Comment by ctrlaltdylan** [comment]
I'm sorry, I went through the same process with a US based account as well and was able to authenticate just fine.

From our logs I can tell that Zoho reported an error on their end during the authentication callback, it could have been a short service disruption on their end.
