### ISSUE TITLE
[FEATURE] [NEW BUILDER] Sharing workflows

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#2169]
I need a way to share a workflow with another:

* Pipedream user
* Org

I also need a way to share the code for my workflow publicly.

**Comment by zalmanlew** [comment]
I currently use Pipedream for a few different workflows. One of them is currently shared with multiple people. We're only using it for testing but we all need to be able to collaborate and view the requests in real time and manipulate the responses accordingly.
I can do so in the old builder, but it wasn't yet configured for the new builder.

**Comment by MCKLtech** [comment]
+1 
This will rapildy become a blocker for us as we regularly need to share workflows with other accounts.

**Comment by daniellangnet** [comment]
Definitely needed in v2, but should also be good for Pipedream's organic growth

**Comment by axonasif** [comment]
Had created my workflow in v2 just to realize that it doesn't support sharing, been searching for this everywhere but no clue except this issue. I wouldn't probably figure this out unless I had found this issue.
Ended up recreating in v1 API with the cost for extra time & efforts 🥲

**Comment by dylburger** [comment]
@axonasif sorry for the bad experience there. Can you tell me more about your sharing use case? i.e. did you want to share a workflow with another individual user, or make the workflow public?

**Comment by daniellangnet** [comment]
Chiming in here. For us the use-case is to share a workflow with an
individual outside user. A lot of times a customer, for whom we built a
custom webhook receiver and we want to turn it over to them or show it to
them as an example implementation

**Comment by zalmanlew** [comment]
@dylburger I will add to this, my most common use case for sharing is also for collaboration / sharing with customers.

Being able to make a workflow public is nice, but not a critical feature for myself.

**Comment by axonasif** [comment]
> @axonasif sorry for the bad experience there. Can you tell me more about your sharing use case? i.e. did you want to share a workflow with another individual user, or make the workflow public?

Hey 👋, I wanted to share my workflow with a teammate.
Also, there seems to be no automatic way for moving/sharing a workflow to an org account, learned I'll have to email for that.

**Comment by dylburger** [comment]
@daniellangnet @zalmanlew makes total sense! Thanks for sharing.

@axonasif Yes, we're happy to help with that migration - email us and we can talk details!

**Comment by fiatjaf** [comment]
I want to make my workflows public, then link to them and share with people so they can just fill some parameters and start using them! Please!

**Comment by mr-easy1** [comment]
- Does v1 provide a workflow-sharing option with pipedream users/org while v2 not? If yes any example from v1 shared workflow.

**Comment by MCKLtech** [comment]
Potentially stupid suggestion, but can't the workflow be represented in, say, JSON and then imported/exported to other accounts?

**Comment by mr-easy1** [comment]
for collaboration in the same workflow, sharing workflow seems optimal way. 

happy to see if there is any way to export/import pipedream workflows, do you have any inputs on this @MCKLtech !!

**Comment by dylburger** [comment]
We're working on a project now that will serialize workflows to YAML and let you sync them with a Git repo, which should make this use case simpler. You can follow that work [here](https://github.com/PipedreamHQ/pipedream/issues/220).

**Comment by dylburger** [comment]
This is done! You can share code with others privately via [workspaces](https://pipedream.com/docs/workspaces/), and [share workflows publicly via templates](https://pipedream.com/docs/workflows/sharing/)
