### ISSUE TITLE
Language Support: Golang

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#217]
Similar to how I can "Run Node.js code" in a step, I'd like to "Run Golang code" so I can write Go on Pipedream.

**Comment by ryano3000** [comment]
Any plan for this on roadmap? More people need to know about pipedream!

**Comment by dylburger** [comment]
@ryano3000 not on the immediate roadmap, but thank you for the bump! 

Is lack of Go support blocking you developing a specific workflow? i.e. is there a specific Go package you're trying to use in a workflow? Or are you just most familiar with Go and prefer to author workflows using that?

**Comment by ryano3000** [comment]
I know Go, but dont know Node JS, sometimes need some conditional logic, it
would be easier for me to use go in these cases.
However I think your platform could achieve this for many simple use cases;
eg If Params.value == x then DO STEP 3, else DO STEP 4; or by doing
similar with a UI for case/ switch statements to add logic based on
conditionals in values etc

**Comment by dylburger** [comment]
Definitely hear you. We're considering adding basic flow control primitives in the UI so you don't need to write code for those cases, feel free to follow these tickets for more info:

* [Conditionals](https://github.com/PipedreamHQ/pipedream/issues/216)
* [Loops](https://github.com/PipedreamHQ/pipedream/issues/193)

**Comment by davetapley** [comment]
I think this is live now? 😎 
https://pipedream.com/docs/code/go/

**Comment by dylburger** [comment]
As @davetapley , Go is now supported in [the new version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/)! You can see [the docs here](https://pipedream.com/docs/code/go/).

Go support is still considered **alpha**. Please review the docs, write Go code, and let us know if you observe any bugs or have any feedback about how we can make the Go dev experience better.
