### ISSUE TITLE
[BOB] Add Bash syntax highlighting

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2171]
**Is your feature request related to a problem? Please describe.**

The new Bash step builder should have Bash syntax highlighting

![image](https://user-images.githubusercontent.com/2694734/152398330-36090327-cd56-4735-a2be-0e8b894106f1.png)

**Describe the solution you'd like**

Use the same syntax highlighting from the Bash examples modal:

![image (1)](https://user-images.githubusercontent.com/2694734/152398360-c07c68eb-86a1-4f18-92fa-2e49f83c10d7.png)

**Comment by dylburger** [comment]
This should be done!

<img width="933" alt="Screen Shot 2022-05-22 at 10 59 52 PM" src="https://user-images.githubusercontent.com/242668/169761803-eba38f1f-02bc-4335-b308-72e9f387b9f6.png">
