### ISSUE TITLE
[APP] CloudTables

### ISSUE THREAD

**Issue by daane** [PipedreamHQ/pipedream#2174]
**Name of app / service**
CloudTables

**Link to developer documentation**
https://cloudtables.com/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**
CloudTables provides an [NPM package for interacting with the API](https://cloudtables.com/docs/cloud/api/nodejs), so it seems fairly easy to implement with custom Node.js code. But a CloudTables action would surely be nice.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

- Insert row
- Update row
- Delete row

I think those are the most important ones.

Cheers 🙂

**Comment by dannyroosevelt** [comment]
@daane here is a basic integration with CloudTables that will allow you to get started writing code and letting Pipedream handle the auth implementation: https://pipedream.com/apps/cloudtables. Note that the basic integration we just enabled is using their HTTP API, but you can easily use their NPM package and still reference the `auth` object for your CloudTables account if you'd prefer that route.

For pre-built actions using their API, all of our components are open source and [anyone can build their own](https://pipedream.com/docs/components/guidelines/#getting-started) -- would you be interested in giving that a shot?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
FYI @daane we added this to the team's backlog to build out the specific actions you were looking for, so feel free to follow along: https://github.com/PipedreamHQ/pipedream/issues/2229

**Comment by daane** [comment]
@dannyroosevelt OK, thanks. I am not quite sure yet what the task entails, but I can look more into it tomorrow. Sorry for the late reply.
