### ISSUE TITLE
[BUG] ClickUp `workspace` prop async retrieval returning 400 errors

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2180]
**Describe the bug**
Unable to pull the  available workspaces required for the `workspace` async prop from ClickUp after authentication.

<img width="779" alt="Screen Shot 2022-02-04 at 6 47 05 AM" src="https://user-images.githubusercontent.com/2694734/152542840-b8ce4ef9-40ec-4850-b0f2-ba1b2589c226.png">

**To Reproduce**
1. Authenticate a ClickUp account as a source
2. Attempt to create "create action" trigger

**Expected behavior**
For the `workspace` prop to be populated with available workspace options.

**Comment by dylburger** [comment]
@ctrlaltdylan did the linked PR address the issue? Can we close?
