### ISSUE TITLE
Cannot `pd publish` ESM typescript build if it imports from local files

### ISSUE THREAD

**Issue by kangzeroo** [PipedreamHQ/pipedream#2181]
When running `pd publish` the follow error is encountered:

```
Detected local requires, creating zip archive...
- actions/myAction/index.js
- api.js
component create api call responded with status: 500, body: {"error":"unexpected error, please contact support@pipedream.com"}
```

This only happens when I attempt to publish a `.js` file that imports from another relative local file. If all code is kept in the same file, the issue disappears.

I am compiling down from Typescript with this `tsconfig.json`:

```json
{
  "compilerOptions": {
    "outDir": "lib",
    "module": "esnext",
    "target": "esnext",
    "lib": ["esnext", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "moduleResolution": "node",
    "jsx": "react",
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "noUnusedLocals": false,
    "strictNullChecks": true,
    "noUnusedParameters": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "/lib"]
}
```

The result of running `$ tsc` to build is a `/lib` output folder in `.js` files that continue to use relative imports. For example, if in the Typescript source code I have `import { helper } from "../../api"`, the same will appear in the compiled Javascript code.

```ts
import { helper } from "../../api";   // this stays the same from TS -> JS
```

My naive suspect is that `$ pd publish ./lib/actions/myAction.js` is being uploaded individually, however the logging does say that its "Detected local requires, creating zip archive...". I would be helpful if the error message was more specific.

I really want to use Typescript in all my pipedream workflows, as static typing keeps me sane across so many cloud functions. Is there something I am missing?

**Comment by kangzeroo** [comment]
Other things I've tried:

- Changing the `tsconfig.json` into a single output file by setting `compilerOptions.outFile: "../myAction.js"` and `compilerOptions.module: "amd"`. while this successfully compiles TS code into a single JS file, the outputted JS file is not useable as `pd` wont recognize the object (expecting params like `key`, `version`, `name`, etc that exist but arent reachable by pipedream-cli).
- Moving all relative local imports inside the `Action.run()` as `require` statements. However this just ends up with the same vague `500` error.

**Comment by casret** [comment]
Thanks for the through bug report.  For historic reasons, we default to common js, with ESM modules being indicated using the `mjs` extension.  Can you set up TSC to use that extension?

**Comment by kangzeroo** [comment]
Ahh good to know! Do you have a pre-built recommended TS config for that? Or an example repo? It would save a lot of time for me & other users.

If not, I will look into it and share here.

**Comment by casret** [comment]
Unfortunately not, you are trailblazing, feel free to reach out at any time
with questions.  We are working on a way to make TS available natively, but
we are taking a bit of a different approach.

**Comment by kangzeroo** [comment]
Is there any way to get more verbose logging from the pipedream cli?
I am hoping there might be more hints from this error message, but it appears to be coming from the server:

```
component create api call responded with status: 500, body: {"error":"unexpected error, please contact support@pipedream.com"}
```

**Comment by kangzeroo** [comment]
Ok I think I found the solution. To compile from TS to JS without webpack, babel, or rollup. Zero config except `tsconfig`

Quick Answer:

⛔️  Incorrect `tsconfig.json` & `myAction.ts`. Any of these will fail.

```ts
// myAction.ts
export default {
     name: "myAction",
    description: "lights camera action!",
    ...
}
```
```json
// tsconfig.json
{
  "compilerOptions": {
    "outDir": "lib",
    "module": "esnext",
    "target": "esnext"
  }
}
```

✅  Correct `tsconfig.json` & `myAction.ts`. Both must be set like this to succeed.

```ts
const sentinel = defineAction({
  name: "myAction",
  description: "lights camera action!",
  ...
}
export = sentinel;
```
```json
// tsconfig.json
{
  "compilerOptions": {
    "outDir": "lib",
    "module": "commonjs",
    "target": "es6"
  }
}
```



Long Answer:

<details>

I decided to try another approach via full `commonjs` with the below tsconfig. 

```json
{
  "compilerOptions": {
    "outDir": "lib",
    "module": "commonjs",
    "target": "es6"
  }
}
```

Which properly compiles down to javascript looking like this:

```js
exports.default = {
    name: "myAction",
    description: "lights camera action!",
    ...
}
```

which looks good, however upon attempting to `pd publish` the following error is thrown in cli

```
component create api call responded with status: 400, body: {"error":"Validation failed: Key component code must have a key attribute, Version component code must have a version attribute in semver form"}
```

it appears that pipedream is grabbing from the whole export, and not referencing the `require("...").default` property.
we can test this theory by manually modifying the build output to return the whole export like so:

```js
module.exports = {
    name: "myAction",
    description: "lights camera action!",
    ...
}
```

And behold `$ pd publish myAction.js` it works! 

I am not sure why pipedream has this `default` reading behaviour, but I won't question it for now unless something breaks. 
So how do we get the compiled version to be `module.exports` automatiacally?
Simply change `myAction.ts` to not use the `export default` syntax.

⛔️  Will Fail
```ts
// myAction.ts
export default { ...myAction }
```

✅   Will Succeed
```ts
// myAction.ts
export = { ...myAction }
```

So far this is working for me. I am not sure if this breaks some libraries... it should be fine since its just the `myAction.ts` export using this syntax. I will update here if anything breaks.

</details>

**Comment by kangzeroo** [comment]
Another good compatible library for Typescript + Pipedream is `Ironpipe` by @ci7lus (thanks!)

https://github.com/ci7lus/ironpipe

Gotta hand it to the Japanese 👏 👏  they've had [tight typing for hundreds of years](https://www.youtube.com/watch?v=uG37gQSvrf4)

**Comment by casret** [comment]
Got it, good find, we do indeed look for `module.exports` and not `exports.default` when we are doing our parse.

**Comment by casret** [comment]
Yeah, for CJS, we expect the whole component to be exported, not under the `default` key, which is more of a esm-ism.
