### ISSUE TITLE
[FEATURE] Folders for organizing workflows

### ISSUE THREAD

**Issue by WELZ-gh** [PipedreamHQ/pipedream#2184]
**Is your feature request related to a problem? Please describe.**
I have a lot of different workflows, many of them are related (by client or project). I'd like to organize them better (rather than just having a huge list of workflows).

**Describe the solution you'd like**
Folders for organizing workflows (can even have subfolders). Like this a project can have a folder and even a subfolder for a group of related workflows.
Additionally it could allow adding a collaborator to an entire folder (each workflow could inherit the parent folder permissions).

**Do you have a workaround?**
Naming the workflows with a prefix of the project name to keep them together when sorted alphabetically.

**Comparable features in other tools?**
Zapier allows for folders. I believe they allow you choose to view by folder or to view _all_ workflows in the account.

**Additional context**
https://zapier.com/help/manage/organize/organize-your-zaps-in-folders

**Comment by ctrlaltdylan** [comment]
Hi @WELZ-gh , thanks for taking the time to file a feature request.

This is a very popular one and I definitely agree it would help organize your workflows.

Here's the main issue that's being tracked: https://github.com/PipedreamHQ/pipedream/issues/203

Following that one is going to be your best bet for real time updates.
