### ISSUE TITLE
Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by Alaynemah1** [PipedreamHQ/pipedream#2185]
![Capture](https://user-images.githubusercontent.com/48079850/152578664-bec40d31-b288-42be-8405-f22488f53934.PNG)

**Comment by dylburger** [comment]
@Alaynemah1 Thanks for reporting. We're looking into it.

**Comment by dylburger** [comment]
@Alaynemah1 The **Modified Time** field must be added as a Grouping field in the Zoho Creator record properties for the chosen report. See [the grouping help article](https://www.zoho.com/creator/newhelp/reports/display-records-as-groups-list-report.html).

**Comment by Alaynemah1** [comment]
Modified field is grouped on the report.  Actually I created 3 reports all
grouped by modified  date & none of which appear on the report selection
drop down.

**Comment by jcortes** [comment]
Hi @Alaynemah1 and @dylburger  I couldn't reproduce the issue however just in case it helps I'm posting here a short video showing how to create the form with `Grouping` support and the Trigger. Thanks.

https://user-images.githubusercontent.com/506051/155208581-1289aee0-195e-40f7-bca7-045f2ec4e3d9.mov
