### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kangzeroo** [PipedreamHQ/pipedream#2187]
I am trying to test my sentinel conditions with a transaction hash of an event I thought would match. However I am getting this `post /subscriber-test failed` error.  This same error also happens when I just query the last 20 blocks.

This is coming from the Sentinel GUI on POST request. The events I am watching for do not contain numbers, just address & string.

![image](https://user-images.githubusercontent.com/22982964/152625726-60116b6d-cf74-4982-9163-caf10af220ee.png)

**Comment by kangzeroo** [comment]
In general im seeing that BSC testnet for sentinels is behind real bsc testnet by many millions of blocks. Thus sentinels are very difficult to test on testnet. Sometimes the block number does catch up. Can anyone on the OZ team shed light on why this is?

**Comment by dylburger** [comment]
@kangzeroo Just to confirm, was there a specific issue you noticed with Pipedream in this case? If so, can you clarify?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
