### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by radardit** [PipedreamHQ/pipedream#2188]
**Supabase**

https://supabase.com/docs

Yes, so far as I can tell. I'm new to Pipedream but hopeful that I have missed something simple.

I am looking to use the power of Pipedream to gather data from Supabase and push it to our webflow website to drive a dashboard for our clients.

**Comment by dannyroosevelt** [comment]
Hey @radardit we have a basic integration with Supabase live today, which you can use to get started: https://pipedream.com/apps/supabase

If you'd like to create pre-built actions or triggers, they're all open source -- I recommend checking out our quickstart guide: https://pipedream.com/docs/components/guidelines/#getting-started

Let me know if you'd be interesting in contributing and we can help support you along the way.
