### ISSUE TITLE
[ACTION] Amazon SES send email

### ISSUE THREAD

**Issue by dzg** [PipedreamHQ/pipedream#2189]
**Is there a specific app this action is for?**

Amazon Simple Email Service

**Please provide a link to the relevant API docs for the specific service / operation.**

🔗 [SendEmail - Amazon Simple Email Service](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
