### ISSUE TITLE
[APP] LaGrowthMachine

### ISSUE THREAD

**Issue by bricemaurin** [PipedreamHQ/pipedream#2191]
**Name of app / service** LaGrowthMachine

**Link to developer documentation** https://documenter.getpostman.com/view/2071164/TVCmSkH2#8c9d579b-8ff2-472d-9815-9edf936d5b1d

**Is lack of support preventing you from building workflows, or do you have a workaround?** integrating with code

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Update lead Status & Create Lead

**Comment by dannyroosevelt** [comment]
Hi @bricemaurin we've added a basic integration with LaGrowthMachine here: https://pipedream.com/apps/lagrowthmachine

You can use this scaffolding as a starting off point to make authenticated requests to their API.

Our pre-built actions and triggers are all open source -- let me know if you're interested in building some of these out on your own. If so I'd recommend checking out our quickstart guide here: https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by bricemaurin** [comment]
Thanks @dannyroosevelt ! that was fast 👏 
how can i contribute to creating the different actions i'm interested into ?

**Comment by dannyroosevelt** [comment]
That's great! I recommend starting here: https://pipedream.com/docs/components/guidelines/#contributing-to-the-pipedream-registry

This will give a good overview of how the process works and has links to quickstart guides for creating both triggers and actions. Let me know if you have questions on anything. By the way we also have an [active community on Slack](https://pipedream-users.slack.com/archives/C01E5KCTR16) and lots of users there can help provide guidance in our #contribute channel.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
