### ISSUE TITLE
[TRIGGER] New Reddit Post in Subreddit

### ISSUE THREAD

**Issue by sharunkumar** [PipedreamHQ/pipedream#2192]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
A trigger for firing when a new reddit post is created in a subreddit.
Currently there's "new hot post in subreddit" and "new link in subreddit" triggers for reddit which seem to be subsets of "new post" in general.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://www.reddit.com/dev/api/

**Comment by dylburger** [comment]
@sharunkumar Thanks for reaching out. **New Link in Subreddit** should fetch all posts. I'll rename the source accordingly.
