### ISSUE TITLE
microsoft teams

### ISSUE THREAD

**Issue by vevidlol** [PipedreamHQ/pipedream#2193]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
Hi @vevidlol FYI we have Microsoft Teams integrated today, and we have a number of pre-built actions coming soon: https://github.com/PipedreamHQ/pipedream/issues/1422

Do you have any questions or do you need any help getting started with them?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
