### ISSUE TITLE
[BUG] Canvas API yields intermittent 401s on API requests

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#2198]

**Comment by accellier** [comment]
Not sure if related but the docs mention "_The response to this request will not contain a new refresh token; the same refresh token is to be reused_."

https://canvas.instructure.com/doc/api/file.oauth.html#using-refresh-tokens

**Comment by accellier** [comment]
Hi @dylburger hope all is well. I know a lot of changes happening at Pipedream HQ - just wondering if there's been any movement on this one. Is there anything I can assist with?

**Comment by dannyroosevelt** [comment]
Hi @accellier thanks for checking in! I had tried getting access to an administrator account with Canvas a few times since you reached out to Dylan about the issues you've been experiencing, but I haven't been successful, so our ability to troubleshoot the integration is limited.

Is there any chance you're able to help get me access to an admin account so I can run through the authentication process on our end and dig in?

**Comment by accellier** [comment]
@dannyroosevelt sorry I missed this - not sure why I didn't get a notification.

Yes I can absolutely assist you with this. I will message you on Slack to facilitate.

**Comment by accellier** [comment]
@dannyroosevelt just confirming this issue still persists. Let me know if I can assist with anything on this side.

**Comment by dannyroosevelt** [comment]
Hey Paul, very sorry for the delay and continued issues -- I'm going to surface this to the team again this week so we can identify next steps.

**Comment by dannyroosevelt** [comment]
Hey Paul, we just made a subtle modification to our integration with the Canvas API that we're hopeful will resolve the issues you've been running into, however, you'll need to re-authenticate with your Canvas account in order for the changes to take effect.

To do that,
1. Go to https://pipedream.com/accounts and search for Canvas
2. Click the 3 dots at the right end of the row, then click "Reconnect"
3. Enter the same information you did in the first place (the `client_id`, `client_secret`, and `domain`)

Then let me know after your workflow runs for a day or 2 if it seems like we've resolved the issue! 🙏🏼

**Comment by accellier** [comment]
Fantastic - thank you Danny and team.
Will monitor and hopefully put this one to bed.
Appreciate your assistance.

**Comment by dannyroosevelt** [comment]
Hey Paul, what's the latest on this one -- did we fix it??

**Comment by accellier** [comment]
Hey Danny - we are still getting occasional 401s on the Canvas API. Seems to be every 2 - 4 days we just get one when the workflow runs. I re-run it and it works fine.

The error is always:

`{
  "errors": [
    {
      "message": "Invalid access token."
    }
  ]
}`

It does seem _less_ frequent, but that may be my imagination.
