### ISSUE TITLE
Deploy / Update Workflows via Git, API, CLI

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#220]
I want to write and test workflows on my local machine, storing the workflow's code in my existing version control system.

I also want to programmatically deploy workflows using a CLI, for example using a command like `pipedream deploy`. This way, I can deploy workflows locally or as part of my CI/CD pipeline.

Related: #1139

**Comment by morganism** [comment]
@dylburger Thank you! I am finding Pipedream really useful, Workflow management via CLI would be great. I'm pretty new to this service, but picking up the concept and how to get real utility out of it is not a chore. I'll DM you if I can.

**Comment by dylburger** [comment]
Adding a comment from #857  here. When we support an API / CLI for deploying workflows, we plan to also let you serialize workflows to plaintext (e.g. JavaScript code with some config locally), which means you'd be able to store them in Git. That feature would enable the request below.

"For testing my workflow with a real case, I need to deploy my code, so everytime I test something I create a new version of the workflow. My workflow ends up with lots of versions. Most of them have bugs or are here for testing/debugging
Sometimes I want to go back to a specific version but I can't remember which one it was, it can be 10 versions back or more, it's hard to identify versions and difference between them

**Describe the solution you'd like**
Something closer to real code versioning, so more like git commits:

being able to add a comment to a version. This would be a "quick win", as I could just tag a revision that I know is working before creating more revisions, So I can easily come back to it even if I created many revisions after.
Nice to have: being able to compare 2 versions of a workflow"

**Comment by illusoryio** [comment]
This would be very useful.

**Comment by moltar** [comment]
Would love to get this supported, this way we can migrate our processes from unstable Zapier zaps and Integromat scenarios to proper code solution with _some_ tests.

**Comment by sjn001tvh** [comment]
Geetings.  I'm a newby to Pipedream, but after several weeks of working with workflows between Dropbox and ClickUp etc., I've been able to accomplish a lot processing information from phone to the ClickUp app.  However, as I have developed these routines, there have been instances where I have deleted a step... I know, I know, even though it warns me about the delete, I just needed it to get out of the way so I could try another option, and of course when I did... I lost the routine.  I only had to do that once, and fortunately it wasn't filled with a lot of functions, etc.  I've looked and asked about a utility that will allow me to save a step, maybe as an archive, so it suggested I follow this issue.  

At this point, my only option is to cut and paste the code between the async(events, steps, auths) {...} and place them in a .js files defined as functions.  Does anyone have a better method?  Then, I can test the code, and if it works, cut and paste the new version back into my .js functions file.  Thanks.

**Comment by ak--47** [comment]
this is my local workflow for writing tests inside of VSCode and constantly redeploying changes to pipeDream:

one file, 4 shells:

![workflow](https://user-images.githubusercontent.com/3978760/139715465-fb11013b-30d4-4382-977a-e19da399ab2a.png)

essentially:

- `pd dev` (watch for changes)
- `pd logs` (so i don’t need the web browser)
- jest tests on my code
- a scratchpad for doing random stuff

community post: https://pipedream.com/community/t/developing-code-steps-in-a-workflow-locally/1489

**Comment by doronlh** [comment]
+1

**Comment by Achilles0509** [comment]
Do we have any estimation about manage workflow using CLI?

**Comment by mmmoli** [comment]
Would LOVE ❤️ this feature.

We manage code in a monorepo and storing workflows would be 👌  👌 👌

**Comment by jondkinney** [comment]
This would be great! Looking forward to hearing some updates, hopefully.

**Comment by charlie-s** [comment]
@sjn001tvh and anyone else that needs it, you can hit https://api.pipedream.com/v1/users/me/workflows (use the `Authorization: Bearer ...` header from the settings page) to download a JSON array of your workflows, including custom code in any components.

**Comment by cfjedimaster** [comment]
Interesting - so this would be a code view of a complete workflow then? And in theory, we will next have a way to push these back? (Well one at a time. ;) And I assume we will have an endpoint to get one workflow eventually?

**Comment by charlie-s** [comment]
It's not listed as an endpoint in their REST API docs. I also tried getting a workflow by ID without success. You may find that some POST/PUT requests work, but I wouldn't count on it in terms of creating/updating nested objects and such. 

I just don't like the idea of building a complicated workflow that my users will depend on without having version control / backups. So this is better than nothing.

**Comment by cfjedimaster** [comment]
Oh - duh - I misread you as someone from PD. :)

**Comment by mmmoli** [comment]
Any updates on when this feature is likely to land? 👀👀

**Comment by ogauk** [comment]
So three years later is there any progress on this?

**Comment by EricWu91** [comment]
Please make this happen! 🙌

**Comment by richayles** [comment]
+1

**Comment by dsolovay** [comment]
Glad to see this in progress! I'll share a use case that I didn't see discussed. I'm doing a demo of a new webhook feature in a different platform (Sitecore 10.3), and am using Pipedream to show how this feature can be used to build out an integration. I'm planning to share my code in "gist" form, but this will require  a lot of copy/pasting by users. Having a standard export format (a la Postman collections) would make this much easier to share, and would also drive adoption.

**Comment by brandonminch** [comment]
+1 for this! We would love to be able to create workflow templates that can can be duplicated, configured, and deployed on behalf of various clients. For example, a client could visit our website and select a workflow template, input a few configuration options in a user-friendly UI, and deploy the workflow all via the pipedream API behind the scenes.

**Comment by renattomachado** [comment]
+1

**Comment by jibe-b** [comment]
+1 too :)

**Comment by jibe-b** [comment]
+1 too :)

**Comment by blangley88** [comment]
+1 @brandonminch nailed it here, this would be ideal for our business use-cases as well!

**Comment by kaneg** [comment]
+1

**Comment by ldbartlett** [comment]
+1 @brandonminch This would help streamline the solutions we develop to be deployed in a user-friendly manner!

**Comment by phefti** [comment]
> 

+1 here as well, great future option that would add a lot of value.

**Comment by EricWu91** [comment]
👍  Would love to be able to edit my code at the comfort of my IDE's, instead of the online Monaco. I mean, it is the reason why we can deploy workflows today _at all_. but it's very hard to scale. I have "long" (+300 lines) workflows, and it becomes _upsettingly_ slow.

**Comment by weiserman** [comment]
+1 for using in workflows. Would be great to leverage co-pilot for code completion and suggestions.

**Comment by The-TT-Hacker** [comment]
I think pipedream would see much more adoption if this workflows API existed.
It would allow workflows to be managed using version control and IaC (e.g. a terraform module).

**Comment by EricWu91** [comment]
Long shooting here, but wouldn't it be possible to retrieve the workflow
codes from git repos?

**Comment by mroy-seedbox** [comment]
This is 100% required in order to scale out Pipedream to hundreds of workflows, especially when many of them are very similar, or even identical (but running on different schedules or triggers, or with different parameters). Ex: run job A (via external API call), and wait for it to complete, then retrieve the results, and send them to Slack -- and do the same for job B, C, D, E, and so on...

Reusable actions/components are nice, but they only apply to one step. And then it is tedious to _**manually**_ apply the new version in a multitude of workflows.

Manually managing hundreds of similar workflows is a no-go. It's kinda like copy pasting the same code all over the place: no one wants to maintain that mess (which version of the code/workflow is the most up-to-date, etc.). At least if we could look at all our workflows "at once" in an IDE, it would help to manage the repetitions, and make simultaneous updates/apply refactorings. I dream of editing Pipedream workflows directly in VS Code, and then using an awesome VS Code extension with all kind of cool features to interface directly with Pipedream from VS Code.

Also, with workflow management via API/Git/CLI, we could add a layer of abstraction on top of Pipedream, allowing us to define a generic/reusable/configurable workflow _**once**_, and then deploy it multiple times (with different parameters, schedules, or triggers).

Of course, reusable workflows or multi-step actions/components would also be very helpful, and could accomplish similar goals. Zapier has something similar, called "Sub-Zaps".

**Comment by peteratticusberg** [comment]
+1

**Comment by n0vakovic** [comment]
+1

**Comment by danhstevens** [comment]
+1

**Comment by EricWu91** [comment]
First and foremost: 
Is this the feature we've all been waiting for? 

![image](https://github.com/PipedreamHQ/pipedream/assets/9344516/ecd4fb65-a9bb-43ab-a6f3-a17efe88d88c)

If it is, it looks amazing. 

But this is _slightly_ more disheartening.

![image](https://github.com/PipedreamHQ/pipedream/assets/9344516/b1cf2ffe-62e2-4305-a8e1-8b3d684e23a1)

I understand your business model, and I know you guys also need to make a buck. But 99/month for a single dev, in slightly larger projects is _prohibitive_.  That's _five_ times as expensive as the previous pricing tag!

**Comment by EricWu91** [comment]
For context, I'm a single developer working on a few personal projects. I've replaced some of my backend code with Pipedream workflows, because it is so much easier to have an app calling a fixed URL than having to worry about all that infrastructure.

That being said, my workflows are amounting to almost 800 lines _each_, and editing, testing, developing online becomes a _big_ nuisance _very fast_. Monaco is fine for a few hundred lines tops, and _shouldn't_ be used for slightly larger codebases!

So... how am I supposed to keep working on my PD workflows if the alternative to wasting hours working with a feature-less IDE is paying 100 dollars a month (1200 upfront)?

**Comment by Stvad** [comment]
Seems like it's indeed the feature we've been waiting for. I'm very surprised to see it gated behind paywall it's such a foundational thing 🤔

**Comment by EricWu91** [comment]
@dylburger can you please provide updates on this? Even if it means to answer dryly "Yes, we heard your requests, we developed them, and we'll paywall them. Live with it.". At least we will have an answer.

**Comment by dylburger** [comment]
First, I really appreciate all the feedback! We have a small team for the size of the business we're operating, so it can take us longer than we'd like to groom GitHub issues.

We recently reduced the base price of all of our plans for new customers ([see our pricing page](https://pipedream.com/pricing)), and considering further expansion of GitHub support to lower tiers (e.g. for personal vs. organizational use). Like some of y'all have mentioned, since we operate a business, we think carefully about the value we're providing at each tier, gating some features at different tiers accordingly. But we hear the feedback, and I'm sharing all of this with the broader team so they see it.

Since this issue also operated as a catch-all for Git serialization and a workflow API + CLI, I'm closing this master ticket and opening separate tickets for the remaining work:

* https://github.com/PipedreamHQ/pipedream/issues/8736
* https://github.com/PipedreamHQ/pipedream/issues/8735

**Comment by EricWu91** [comment]
@dylburger , Thanks for the answer. 
I noticed that you created two issues - one for CLI, one for API - but not for GIT. 
Should we assume that the latter won't be receiving further considerations given that Github Sync is already out?

Furthermore, can we (and if so, where) follow up on this? 
> are considering further expansion of GitHub support to lower tiers (e.g. for personal vs. organizational use)

**Comment by mroy-seedbox** [comment]
The CLI & API features will effectively allow users to roll up their own GitHub integration anyway (or use any other version control provider), by creating a very simple CI/CD pipeline/workflow.

Which kinda defeats the purpose of paywalling this feature. 🤷‍♂️

**Comment by dylburger** [comment]
@EricWu91 We aren't planning on adding a GitHub issue to track that. We generally use GitHub only for new features, bugs, and integration requests, but not requests to transition features to different plans. I did share all this feedback with the team, though.

**Comment by EricWu91** [comment]
@dylburger, sorry for the confusion.

What I meant by `- one for CLI, one for API - but not for GIT.` was that I expected that all three topics in this issue ("Deploy / Update Workflows via *Git, API, CLI*") would have a different Github issue. Since you ommited a GIT-related issue, I thought it was being disregarded in favor of (the product) Github Sync.

As for a Github issue to track internal matters (i.e. pricing tiers), that makes all sense and I didn't expect otherwise  :).

>The CLI & API features will effectively allow users to roll up their own GitHub integration anyway (or use any other version control provider), by creating a very simple CI/CD pipeline/workflow.

@mroy-seedbox I would still pay for the ease of not having to deal with it, though. Just (still) not as much.

**Comment by dylburger** [comment]
Got it, so the CLI / API work will allow you to develop locally and serialize any workflow code to Git automatically (or any other VCS). In that model you’d push the code to Pipedream via your CI tool. Does that help or are you talking about something else?

**Comment by EricWu91** [comment]
My needs (and hopefully the ones of others in this issue) are just as you pointed out: Being able to develop locally, automatically versioning in a VCS (Git preferred, but not mandatory), and being able to still use Pipedream's infrastructure to run workflows. 

If an API/CLI integration is available, and it accomplishes the points above without an inherent need for a Git integration, I'm fine with it :).

**Comment by mroy-seedbox** [comment]
A well built VS Code extension for Pipedream might one day become a superior development environment than the Pipedream builder itself (due to its configurability & the wide availability of extensions, which is not feasible to add to the builder).

And that would allow users to use whatever form of version control they prefer (as @EricWu91 mentioned).

**Comment by hongbozheng** [comment]
+1

**Comment by jcable** [comment]
FYI I moved all my workflows out of Pipedream and re-implemented them with AWS lambda. Partly to bring the source under source code control and partly as part of a wider project that moved our graphql APIs out of Hasura on Heroku.

So I'm not really an interested party any longer.

**Comment by dylburger** [comment]
Since this issue is closed, I'm going to go ahead and lock this conversation so we make sure feedback about missing features is added to the relevant tickets:

* https://github.com/PipedreamHQ/pipedream/issues/8736
* https://github.com/PipedreamHQ/pipedream/issues/8735

**Comment by ctrlaltdylan** [comment]
We have released the ability to programmatically create and update workflows by REST API.

Read this end to end guide on how to create workflows programmatically using the REST API: https://pipedream.com/docs/rest-api/workflows

API Documentation: https://pipedream.com/docs/rest-api#workflows
