### ISSUE TITLE
Language Support: Python 3

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#221]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Just like Pipedream exposes a way to "Run Node.js code", I'd like a way to "Run Python code". I'd expect support for Python 3 only since [Python 2 will be EOL in 2020](https://www.python.org/dev/peps/pep-0373/).

**Do you have a workaround?**

I need to use specific packages like `pandas` for which there is no npm equivalent, so even though I can write Node.js for certain things, I need Python.

**Comment by loscil06** [comment]
Thanks for the hard work, can't wait to see it.

**Comment by jonathanfeng-scale** [comment]
Looking forward to the Python version :)

**Comment by shaiss** [comment]
any updates?

**Comment by dylburger** [comment]
@shaiss not yet, but we'll add a comment to this issue as soon as we have updates.

**Comment by mayurdhurpate** [comment]
Looks like Pipedream support for Python just landed in Pipedream v2! https://pipedream.com/docs/code/python/
Is this live?

**Comment by sergioeliot2039** [comment]
Yeah @mayurdhurpate -- it is live!
It was announced in the [Pipedream-Users](https://join.slack.com/t/pipedream-users/shared_invite/zt-11sazmsg0-oS2VW~mZfhtk3XfEEvb~JA) Slack space by @todsac 

> Multi-language support including Node, Python, Golang & bash

![image](https://user-images.githubusercontent.com/25184117/154687886-4e797780-cc7e-4c13-85fb-b52eba7edb04.png)

Quoting relevant links I think
> Get Started 
> Watch the [video demo](https://www.youtube.com/watch?v=BGKuPYMNKGg) :desktop_computer:
> Read our [quickstart](https://pipedream.com/docs/quickstart/), [docs](https://pipedream.com/docs), and/or [migration guide](https://pipedream.com/docs/migrate-from-v1/) / [FAQ](https://pipedream.com/docs/migrate-from-v1/#faqs) :point_left:
> Have questions? Ask here or on [Discourse](http://url1737.pipedream.com/ls/click?upn=-2Biyx3uaBT9nrTMgVBA1USEzCoLJjS6kLZnOJQh1oPo-2F8sQqvFbT50mZGrg2rv0-2FPx38e_C92UWFIJji2uZBffTuAmcyrX3Av0ZcDYvcwWLvZctTlkatfQHhARmYPowNC2ub8MW4TCPgCVu2Osg0HszSM19JBcf-2FuRHcYrOFi6hidCvPi9pnl9SB4heGy4y0niZaF84x-2F7Du30byODVyGKuFhQ4gVL2I0lp4A8nd2yhDOHgUYlfpcCGaTke2SN6kNLA58suUSiXBwj56nezCK-2FG1lGtC28ql4N36RcamN7fvmCo08-3D) :speech_balloon:

**Comment by dylburger** [comment]
Yes! We are very happy to have shipped Python support in [the newest version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/).

Please take a look at [the Python docs here](https://pipedream.com/docs/code/python/). Python support is still considered alpha, so please let us know if you see any bugs or have any feedback on how we can improve the Python dev experience.
