### ISSUE TITLE
HTTP API

### ISSUE THREAD

**Issue by SantaCons** [PipedreamHQ/pipedream#2213]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
Hi @SantaCons can you provide more detail on what you're looking for? Have you seen the HTTP trigger and action in Pipedream already? Is there specific functionality you're looking for but not finding?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
