### ISSUE TITLE
[APP] Kommo

### ISSUE THREAD

**Issue by grozwalker** [PipedreamHQ/pipedream#2214]
**Name of app / service**
AmoCRM

**Link to developer documentation**
https://www.amocrm.ru/developers/content/oauth/oauth

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It's very annoying, I can't integrate

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @grozwalker 

Sorry about the late follow up. We were looking into this and noticed that AmoCRM was rebranded as Kommo. Currently we are in contact with Kommo reps to get a technical account and start building the integration.

**Comment by sergio-eliot-rodriguez** [comment]
AmoCRM was rebranded as Kommo, so:

**App**
Kommo

**Website**
https://www.kommo.com/

**Developer documentation**
https://www.kommo.com/developers/content/platform/abilities/

**Comment by sergio-eliot-rodriguez** [comment]
Kommo (formerly AmoCRM) is now integrated https://pipedream.com/apps/kommo
