### ISSUE TITLE
[BUG] Google People API authorization issue

### ISSUE THREAD

**Issue by dzg** [PipedreamHQ/pipedream#2220]
Connecting to **Google People API** ... this comes up when authorizing:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/466557/153326297-c2141efa-ed7d-49a6-8357-788226d20fc3.png">

**Comment by dzg** [comment]
(It works fine, but the warning might be offputting to the less courageous.)

**Comment by dylburger** [comment]
Thanks for the request @dzg . We're tracking at #1381
