### ISSUE TITLE
[FEATURE] Remove `/obj` suffix on Bubble Auth URLs

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2222]
**Is your feature request related to a problem? Please describe.**

I would like the `/obj` path removed from Bubble Auth root URLs accessible with `auths.bubble.root_url`

**Describe the solution you'd like**
I would like to be able to easily leverage the `/obj` and `/data` Bubble APIs with my account credentials with the `auths.bubble.root_url`.

**Do you have a workaround?**

Manually specifying the URL.

**Comment by dylburger** [comment]
Addressed in the Bubble app connection instructions
