### ISSUE TITLE
[ACTIONS] CloudTables

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2229]
CloudTables
https://cloudtables.com/docs/cloud/api/rest

**Actions**
- Insert row: Create a new row.
- Update row: Edit an existing row.
- Delete row: Delete a row.

**Comment by Giuan0** [comment]
done @vellames-turing

**Comment by dannyroosevelt** [comment]
@Giuan0 this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
