### ISSUE TITLE
coinbase

### ISSUE THREAD

**Issue by satoshiNakomata** [PipedreamHQ/pipedream#2233]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
@satoshiNakomata  here is a basic framework for the integration: https://pipedream.com/apps/online-live-support

Regarding triggers and actions, is there any you'd like to see for this app?

Currently there are these legacy actions, but please let us know if you need any action that is missing, of if you need existing legacy actions as new Pipedream components.

![image](https://user-images.githubusercontent.com/25184117/153715531-8bef0ded-ab33-4e13-8116-63052d548005.png)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
