### ISSUE TITLE
[BUG] Hubspot integration cannot be added

### ISSUE THREAD

**Issue by tmchow** [PipedreamHQ/pipedream#2236]
**Describe the bug**
Cannot connect with Hubspot as there is an error saying that there were `"insufficient scopes were provided"`.  There are no scope/permissions to specify during the authorization, so it seems to be a pipedream issue with the integration setup?

**To Reproduce**
1. Go to Accounts
2. Search for Hubspot and try to authorize it

**Expected behavior**
It should connect :)

**Screenshots**
<img width="597" alt="image" src="https://user-images.githubusercontent.com/517103/153698783-ff6f1d6e-89d3-4740-ba53-e8b7d3d4a68a.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.2
 - Browser Chrome
 - Version 99.0.4844.27

**Comment by dylburger** [comment]
@tmchow Can you tell me two things?

1. What Hubspot tier are you on?
2. Are you an account admin? Or are your permissions restricted in any way?

That'll help our integrations team troubleshoot this more. They're out of the office this weekend, but will be able to get back to you Monday.

**Comment by tmchow** [comment]
> 1. What Hubspot tier are you on?

"Marketing Hub Enterprise"

> 2. Are you an account admin? Or are your permissions restricted in any way?

I am an admin.

**Comment by dannyroosevelt** [comment]
This should be fixed
