### ISSUE TITLE
[APP] AppVeyor

### ISSUE THREAD

**Issue by Starmania** [PipedreamHQ/pipedream#2240]
**Name of app / service**
[appveyor.com](appveyor.com)

**Link to developer documentation**
https://www.appveyor.com/docs/api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
This is a implentation that can be easy and save too much time !

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
If you accept, can you prioritize the build system?

Thanks a lot if you do this !

**Comment by dannyroosevelt** [comment]
Hi there -- we've created a basic integration for AppVeyor here:
https://pipedream.com/apps/appveyor

From there, you can start building our your own actions using AppVeyor's API: https://www.appveyor.com/docs/api/team/

If you'd like to develop any pre-built actions, I recommend getting started here: https://pipedream.com/docs/components/guidelines/#getting-started

Let me know if you have any questions!

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
