### ISSUE TITLE
[APP] Quickbase

### ISSUE THREAD

**Issue by jtorrence1** [PipedreamHQ/pipedream#2244]
**Name of app / service**
Quickbase

**Link to developer documentation**
https://developer.quickbase.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have a workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
[Insert/Update record(s)](https://developer.quickbase.com/operation/upsert)
[Query for data](https://developer.quickbase.com/operation/runQuery)
[Delete record(s)](https://developer.quickbase.com/operation/deleteRecords)
[Get a temporary token for a dbid](https://developer.quickbase.com/operation/getTempTokenDBID)

**Comment by dannyroosevelt** [comment]
@jtorrence1 here is a basic integration for Quickbase: https://pipedream.com/apps/quickbase

From there you'll be able to modify the code scaffolding to make any authenticated request to their API.

FYI all our pre-built actions and triggers are open source and hosted on GitHub: https://github.com/PipedreamHQ/pipedream/tree/master

If you're interested in building out your own, I recommend checking out our getting started guide here: https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
