### ISSUE TITLE
[BUG] Typo on Migration Guide

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2267]
**Describe the bug**
At https://pipedream.com/docs/migrate-from-v1/#new-builder-overview, I see the following:

```
In the v1 workflow builder, you had to deploy the whole workflow to test changes to individual steps. This meant you were

We've improved this flow. You can test your changes with a new Test button.
```

See the incomplete sentence in the first paragraph?

**Comment by ctrlaltdylan** [comment]
Thanks @cfjedimaster - fixing it!

**Comment by ctrlaltdylan** [comment]
Fixed, thanks for the report @cfjedimaster , much appreciated.
