### ISSUE TITLE
[BUG] You can lose code when working with Examples

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2281]
**Describe the bug**
I was in a Python step and had written a bit of code but ran into issues. I clicked to look at the Examples and saw that I needed to import stuff to fix my code. With the examples showing, I clicked to drag and select the import and hit ctrl+c, but the examples UI pastes code in when you click. Actually it *erases* your current code and then pastes in. 

I'd block this from happening, or prompt first, or have it insert at the beginning of the steps perhaps.

**To Reproduce**
1. In a code step, just write your own step
2. Click on examples
3. Click on any example
4. Your code is lost

**Expected behavior**
To not lose my code. ;)

**Comment by dylburger** [comment]
@cfjedimaster Thanks for reporting. This has come up a couple of times and it's on the team's radar. Thank for reporting.

**Comment by cfjedimaster** [comment]
lgtm!
