### ISSUE TITLE
[UPDATE] Update Salesforce actions to ensure we're using >v30

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2283]
It looks like [we're using v54.0](https://github.com/PipedreamHQ/pipedream/blob/master/components/salesforce_rest_api/salesforce_rest_api.app.mjs#L78) in the latest triggers but v20.0 in some of the actions (and test request), which [Salesforce is deprecating soon](https://help.salesforce.com/s/articleView?id=000354473&type=1).

Let's update so everything is on the latest version and consistent.

**Comment by zelf0** [comment]
Hi @dannyroosevelt, I'm new to OSS and would love to fix this! Would changing the URL in every file in https://github.com/PipedreamHQ/pipedream/tree/master/components/salesforce_rest_api/actions  from `${this.salesforce_rest_api.$auth.instance_url}/services/data/v20.0/sobjects/Attachment/` to `${this.salesforce_rest_api.$auth.instance_url}/services/data/v54.0/sobjects/Attachment/` fix the issue or does the format of the link also need to change?

**Comment by julian-techzip** [comment]
Summer comes early from Salesforce!  v20 endpoints are now busted.

I swapped in v55.0 and rest calls worked fine on the endpoints I used with the "run any API" action.

**Comment by dannyroosevelt** [comment]
Closed by https://github.com/PipedreamHQ/pipedream/pull/2764
