### ISSUE TITLE
[TRIGGER] Saved Reddit Posts

### ISSUE THREAD

**Issue by onlytanmoy** [PipedreamHQ/pipedream#2287]
Hiya, I am looking to achieve the below integration between Reddit and Todoist:
Any posts I save in Reddit will appear as Tasks in Todoist

I reckon this cannot be achieved via Pipedream currently, therefore creating this request.

**Comment by dylburger** [comment]
@onlytanmoy Thanks for reaching out. We don't yet have a trigger for saved Reddit posts. But [their API supports that](https://www.reddit.com/dev/api/#GET_user_{username}_saved).

Are you familiar with Node.js? Anyone can author their own Pipedream triggers (we call these "sources"). Take a look at the [developer quickstart for sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/) or [more about the general contribution process here](https://pipedream.com/docs/components/guidelines/#process).

**Comment by onlytanmoy** [comment]
Thanks for your response.
No, I am not familiar with Node.js :(  Hopefully someone will make a trigger that I can use.

**Comment by dylburger** [comment]
Great thanks, I added to our backlog

**Comment by vellames-turing** [comment]
Basically, we want a trigger when the user saves some Reddit post, right?

**Comment by onlytanmoy** [comment]
> Basically, we want a trigger when the user saves some Reddit post, right?

yes, that's right, the saved Reddit post will get created as a task under a defined project in Todoist.
