### ISSUE TITLE
[FEATURE] Allow us to collapse/uncollapse steps

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2294]
**Is your feature request related to a problem? Please describe.**
Right now when you expand step N in a workflow, any other step auto collapses. This makes it difficult to work on one step and reference another. 

**Describe the solution you'd like**
Clicking on a step expands it and that's it. I can click another step to close it if I want.

**Do you have a workaround?**
Nope. :)

**Comment by dylburger** [comment]
Related to #90

**Comment by dylburger** [comment]
This should be fixed. See #2295
