### ISSUE TITLE
[APP] IP2WHOIS

### ISSUE THREAD

**Issue by ip2whois** [PipedreamHQ/pipedream#2304]
**Name of app / service**
IP2WHOIS

**Link to developer documentation**
https://ip2whois.com/developers-api

**Comment by dannyroosevelt** [comment]
Here you go: https://pipedream.com/apps/ip2whois

**Comment by dylburger** [comment]
Thank you so much for submitting this! We've added it to our backlog to review, and our team has been notified.

**Comment by ip2whois** [comment]
Hi Pipedream,

Thanks for the response and work! The only thing that we want to feedback is the image used in the page. It should be at least the same as our avatar. Can you guys please fix it? Other than that, all are fine.

**Comment by dannyroosevelt** [comment]
This has been updated!

**Comment by ip2whois** [comment]
Hi Pipedream,

The logo had been updated. Thanks for the work!
