### ISSUE TITLE
[APP] Gumroad

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2305]
**Name of app / service**

Gumroad

**Link to developer documentation**

https://app.gumroad.com/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Yes, OAuth is currently broken: 

<img width="594" alt="CleanShot 2022-02-24 at 11 15 50@2x" src="https://user-images.githubusercontent.com/2694734/155563517-b50265df-4e4e-428b-a119-59f7499f9662.png">

It appears that our current implementation is just a scaffold and needs to properly integrate with their OAuth flow:

https://github.com/PipedreamHQ/pipedream/blob/master/components/gumroad/gumroad.app.mjs

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

> Emit and event every time a purchase is made on my Gumroad account

**Comment by dannyroosevelt** [comment]
It looks like we were not passing the required scopes for Gumroad. I've fixed this and the integration is now working.
