### ISSUE TITLE
[BUG] Mailgun error `TypeError — The first argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)`

### ISSUE THREAD

**Issue by chaoming** [PipedreamHQ/pipedream#2328]
**Describe the bug**
The Mailgun destination gives an error since 23rd Feb 2022.

`TypeError — The first argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)`

Nothing has changed in the configuration and it was working fine.

**To Reproduce**
1. Create a workflow to use mailgun 

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dannyroosevelt** [comment]
Hi @chaoming thanks for reporting. Can you confirm which action you're using?

**Comment by js07** [comment]
I get the same error using the Mailgun **Send Email** action when the **Send in test mode?** prop is set to `true`.

Context:
Currently, the **Send Email** action [passes a `boolean`](https://github.com/PipedreamHQ/pipedream/blob/f38ef1994a174fe51c3df4c6c3971a4357de9395/components/mailgun/actions/send-email/send-email.js#L101) as the `o:testmode` parameter for Mailgun's [`POST /<domain>/messages`](https://documentation.mailgun.com/en/latest/api-sending.html?highlight=testmode#sending) endpoint. But according to the docs, the parameter should be `yes` (if needed).

[This commit](https://github.com/PipedreamHQ/pipedream/pull/1291) in the open pull request for [Mailgun event sources and actions](https://github.com/PipedreamHQ/pipedream/pull/1291) fixes this issue.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
