### ISSUE TITLE
Google Classroom

### ISSUE THREAD

**Issue by darthnithin** [PipedreamHQ/pipedream#2333]
**Name of app / service**
Google Classroom
**Link to developer documentation**
[https://developers.google.com/classroom](https://developers.google.com/classroom)
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes it is preventing.
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- Assignments added

**Comment by dannyroosevelt** [comment]
I see this app is live -- @darthnithin are you able to verify if you're able to use Google Classroom successfully?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
