### ISSUE TITLE
[ACTION] Upload and Delete multiple files from google drive.

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#2339]
**Is your feature request related to a problem? Please describe.**
This feature request is related to two Google Drive actions.

I have made a flow to synchronize my Airtable records with my Google Drive:
- When files are added to a record, the files are uploaded on my Google Drive.
- When files are removed from a record, the corresponding files on my Google Drive are removed.

I may have multiple file to upload and remove from Google Drive at once. But pipedream Google Drive action only allow single file to be uploaded/removed.

**Describe the solution you'd like**
- Modify the Google Drive [create-file](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/create-file/create-file.mjs) or/and [upload-file](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/upload-file/upload-file.mjs) actions to be able to upload multiple files.
- Modify the Google Drive [delete-file](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/actions/delete-file/delete-file.mjs) action to be able to delete multiple files.

**Do you have a workaround?**
/

**Comparable features in other tools?**
/

**Additional context**
/

**Comment by dylburger** [comment]
@LucBerge I apologize for the delay in getting back to you. I'm closing this issue because it'll be solved by #193, which is on our near-term backlog.

For now, you can use the Google Drive Node.js SDK, iterating over the files in a `for` loop.
