### ISSUE TITLE
[APP] SumUp

### ISSUE THREAD

**Issue by leoplct** [PipedreamHQ/pipedream#2340]
**Name of app / service**
Debitoor 

**Link to developer documentation**
https://developers.debitoor.com/api-reference

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I would like to create a workflow that create an invoice on Debitoor after an "invoce.paid" event from Stripe.

**Comment by sergio-eliot-rodriguez** [comment]
Debitoor was acquired or merged by/to SumUp

**Comment by sergio-eliot-rodriguez** [comment]
SumUp details
https://www.sumup.com/
https://developer.sumup.com

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/sumup
