### ISSUE TITLE
[APP] Smiirl

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2346]
**Name of app / service**

Smiirl

**Link to developer documentation**

https://github.com/smiirl/smiirl-custom-samples

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Nope, happy to build it out myself.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Count action to increment the counter.
Reset the counter.
Push a specific amount.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by ctrlaltdylan** [comment]
Here's the hidden documentation for pushing numbers to the Smirrl API:

https://help.smiirl.com/article/292-how-can-i-get-my-counter-id-and-token-for-zapier-api
