### ISSUE TITLE
Read Whatsapp

### ISSUE THREAD

**Issue by AashvikD** [PipedreamHQ/pipedream#2347]

**Comment by dannyroosevelt** [comment]
Hi @AashvikD we have a couple 3rd party integrations for WhatsApp -- do either of these work for you?
https://pipedream.com/apps/chat-api-for-whatsapp
https://pipedream.com/apps/online-live-support

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
