### ISSUE TITLE
[Action] Telegram: Create Chat Invite Link

### ISSUE THREAD

**Issue by RoPhSe1978** [PipedreamHQ/pipedream#2357]
**Is there a specific app this action is for?**
Telegram API

**Please provide a link to the relevant API docs for the specific service / operation.**
https://core.telegram.org/bots/api#createchatinvitelink

We need creation of chat invite links for our Telegram workflow

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by feyzullah** [comment]
Skipped QA part and merged after review by mistake.
