### ISSUE TITLE
servicenow

### ISSUE THREAD

**Issue by VickyPrince08** [PipedreamHQ/pipedream#2360]
**Name of app / service** Servicenow

**Link to developer documentation** https://developer.servicenow.com/dev.do
https://docs.servicenow.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?** No workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** SFTP integration

**Comment by dannyroosevelt** [comment]
Hi there, have you already checked out our existing ServiceNow integration and pre-built actions? Is there anything specific that you're trying to do that is missing?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
