### ISSUE TITLE
[APP] Pipedream-Google Analytics 4 Integration

### ISSUE THREAD

**Issue by nicmrayce** [PipedreamHQ/pipedream#2361]
**Name of app / service**
Google Analytics Data API (GA4)

**Link to developer documentation**
https://developers.google.com/analytics/devguides/reporting/data/v1

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I would love to have GA4 connected with Shopify API so that I can send things like 'New Paid Order' from Shopify API to GA4 using Pipedream.

Other than that, any other actions and triggers from the legacy GA would be great too: https://pipedream.com/apps/google-analytics/integrations/shopify

**Comment by nicmrayce** [comment]
@dylburger Hope to hear some updates from your team. Let me know if this is something that may take time (e.g. 1 week/1 month/3 months) so that I can manage my team's expectation regarding this feature.

**Comment by dylburger** [comment]
@nicmrayce Normally we can turn integrations around within the week, but Google specifically requires an approval process. Different teams at Google handle different integrations, and that can have an impact on the timeline (e.g. YouTube took us months, other apps took days). When we submit the app for approval by Google, we'll communicate their expected timeline. It's also possible you'll be able to use the app before it's approved, so we'll update you at that point, as well.

**Comment by sergio-eliot-rodriguez** [comment]
We published an action to run an report in ga4.
https://pipedream.com/apps/google-analytics/actions/run-report-in-ga4

**Comment by sergio-eliot-rodriguez** [comment]
Hi @nicmrayce 
Sorry for the request, but G4 was completed previously. It was added to the existing Google Analytics app https://pipedream.com/apps/google-analytics
as can been seen per #5661
