### ISSUE TITLE
[BUG] AWS region not respected in new Cloudwatch events async options

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2376]
**Describe the bug**

When defining the **region** prop, the source claims it's not set:

https://pipedream.com/community/t/aws-integration-not-working-configerror-missing-region-in-config/2002/3

**To Reproduce**
1. Create an AWS Cloudwatch logs insight query trigger
2. Use a valid AWS region
3. Attempt to use the async option **Cloudwatch log groups**
4. See an error about misconfiguration of the region

**Expected behavior**
The async option should retrieve Cloudwatch log groups in the specified region.

**Screenshots**

![cebd8fd26c351822886e0339cee9e493d1d91694](https://user-images.githubusercontent.com/2694734/156637834-50af0b67-7bd0-4a54-95c2-74469246c0c2.png)

**Comment by dylburger** [comment]
@ctrlaltdylan Are you still able to reproduce this? @andrewjschuang recently did some work on AWS actions so I'm curious if that refactor addressed this.

**Comment by andrewjschuang** [comment]
@ctrlaltdylan @dylburger Confirming it was addressed.

![Screen Shot 2022-06-06 at 1 55 58 PM](https://user-images.githubusercontent.com/15385076/172208525-080707d2-b8fa-4aa2-8fa5-95dd708b0de8.png)
