### ISSUE TITLE
[ACTION] Write directly into custom fields in Asana

### ISSUE THREAD

**Issue by codylthomas** [PipedreamHQ/pipedream#2387]
Building Asana/Slack automations with Pipedream since the native Asana/Slack integration doesn’t accomplish what I need for my team. Here’s my question. I haven’t figured out a way to write directly into Asana custom fields to update a task. The data I need to pass back from Slack is there in the workflow, but I can’t find a way to put it into my custom fields in Asana. The custom fields are in the API, but without writing my own code, I can't find a way to update just the custom fields on an Asana task in a workflow.

**Comment by dannyroosevelt** [comment]
@codylthomas we're going to tackle this as a part of https://github.com/PipedreamHQ/pipedream/issues/1481

**Comment by dannyroosevelt** [comment]
Closing this out since we're tracking in https://github.com/PipedreamHQ/pipedream/issues/1481
