### ISSUE TITLE
[BUG] Zoom sources broken

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2388]
**Describe the bug**
Zoom source event emission seems to be completely broken.

**To Reproduce**
1. Create a new Zoom New Meeting trigger & source
2. Start a meeting
3. Navigate to the Zoom source logs
4. See an empty payload error:

```
TypeError: Cannot destructure property 'object' of 'payload' as it is undefined.
at Object.run (file:///var/task/user/sources/meeting-created/meeting-created.mjs:23:13)
at /var/task/index.js:123:72
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async Runtime.exports.main [as handler] (/var/task/index.js:61:20)
```

**Expected behavior**
I expect to be able to create working Zoom related triggers.

**Screenshots**

<img width="1117" alt="CleanShot 2022-03-07 at 15 09 48@2x" src="https://user-images.githubusercontent.com/2694734/157110252-c7f1fb96-1677-4e92-a3b7-e7068c4f6dec.png">

**Comment by colinhoernig** [comment]
+1 to this issue.  Several of our teams are using Pipedream for Zoom notifications to Slack and within the last month or so, these integrations seem to be broken.

We have tried removing/re-adding Zoom as an account and then linking it as a source for custom Zoom events.  When testing, we've been unable to trigger test events.

In the following screenshot, the events are not being trigger, even though the meeting has started and attendees join/leave.

<img width="1402" alt="Screen Shot 2022-03-07 at 3 32 12 PM" src="https://user-images.githubusercontent.com/195992/157129091-bc885603-d1f6-4591-8d2a-99f1648591d7.png">

**Comment by colinhoernig** [comment]
+1 to this issue.  Several of our teams are using Pipedream for Zoom notifications to Slack and within the last month or so, these integrations seem to be broken.

We have tried removing/re-adding Zoom as an account and then linking it as a source for custom Zoom events.  When testing, we've been unable to trigger test events.

In the following screenshot, the events are not being trigger, even though the meeting has started and attendees join/leave.

<img width="1406" alt="Screen Shot 2022-03-07 at 3 33 40 PM" src="https://user-images.githubusercontent.com/195992/157129369-d67d4164-bdfb-416a-8dd9-aeceac4e4a65.png">

**Comment by dylburger** [comment]
@colinhoernig I very much appreciate you raising this. I just addressed one thing on our end that should have fixed this. Would you mind doing the following?

1. Visit https://pipedream.com/accounts
2. Delete your existing Zoom account
3. Connect your Zoom account once more
4. Create a new event source tied to this new account
5. Trigger those events in Zoom

I just tested generating these events end-to-end, and it appears to work. Let me know if it works for you.

**Comment by colinhoernig** [comment]
@dylburger Wow! Our team has confirmed the fix -- events are now triggering as expected. Thank you so much for the quick turnaround on this -- we are thankful and impressed!

**Comment by dylburger** [comment]
That's great! Thank you for confirming. Please let us know if you see any issues with any other integrations.
