### ISSUE TITLE
[TRIGGER] dev.to articles from specific user

### ISSUE THREAD

**Issue by philwolstenholme** [PipedreamHQ/pipedream#2389]
Hi there, big fan of Pipedream! I have signed up and am a paying customer - it's made prototyping and playing around with API's so fun and almost effortless.

I'd like to be able to react to new posts from a user (myself) on [dev.to](http://dev.to/) so I can do things like update a JSON feed of those posts, rebuild my Eleventy website so that it includes a link to the post, or update my Github personal README to link to the post.

https://developers.forem.com/api#operation/getUserArticles

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by ctrlaltdylan** [comment]
Hi @philwolstenholme , this is a great workflow idea for our weekly Speed Run show - I've noted it under our requests for speed runs and I'll update back here when we make it

**Comment by philwolstenholme** [comment]
@ctrlaltdylan ah great, I'll keep an eye on the blog 🙂

**Comment by philwolstenholme** [comment]
@ctrlaltdylan by the way, this is how I'm currently updating my GitHub personal README whenever I post to Dev.to: https://pipedream.com/@philw/add-blog-posts-to-github-personal-readme-p_7NCB3GD/inspect

You can see it in action here: https://github.com/philwolstenholme/philwolstenholme/commits/main and https://github.com/philwolstenholme

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by ctrlaltdylan** [comment]
Hi @philwolstenholme - thanks for the suggestion. We've added a brand new source to the Dev.to component to support listening to new articles on your account:

https://github.com/PipedreamHQ/pipedream/pull/2451

It should be available as a trigger now, if you'd like to give it a try :)
