### ISSUE TITLE
[FEATURE] Simplify the format of the SQL API response

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#239]
Currently, the SQL API response contains the header row (with column names) in the first row of results. This data is duplicative - the column metadata is already present in `ResultSetMetaData`, so I don't need it in my array of data rows.

**Comment by jezmck** [comment]
I've made an action which generates a simplified response of the query results.

**Comment by dylburger** [comment]
The SQL Service will be shutting down on Feb 10th, 2022 (you can read more details in [this post](https://pipedream.com/blog/shutting-down-the-sql-service/)). As a result, we're closing this issue.

Let us know if you have any questions at all.
