### ISSUE TITLE
[BUG] Twitter User Tweets trigger's exclude replies option broken

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2391]
**Describe the bug**
As a pipedream workflow builder, when I use the **User Tweets** trigger and enable the exclude replies option, I expect the trigger to exclude the replies.

1. Start a new workflow
2. Create a **User tweets** trigger
3. Enable the exclusion of replies as events in the source
4. Reply to a user tweet that triggers the workflow
5. The reply tweet should **not** emit an event in the source or workflow

**Expected behavior**
Replies on user tweets should not trigger the workflow.

https://pipedream.com/community/t/does-the-exclude-replies-option-for-a-twitter-user-tweets-trigger-not-work-or-am-i-missing-something/1956

**Screenshots**
![77ec4214cf05a5963e038faf132f257ffa81da71_2_1380x662](https://user-images.githubusercontent.com/2694734/157260704-bdce1375-ca31-4b59-9d1f-3cf9258ec89e.png)

**Comment by Sophie-bear** [comment]
I have both Tweets and Replies set to excluded in my Workflow, but both still emit.
My workflow is simply polling my Twitter and using a Discord Webhook to share them, using the following URL string in the generated message: 
`https://twitter.com/{{steps.trigger.event.user.screen_name}}/status/{{steps.trigger.event.id_str}}`

**Comment by philwolstenholme** [comment]
Thanks for raising this on my behalf @ctrlaltdylan :)

**Comment by Jordon-L** [comment]
Hi, I would like to try fixing this.
