### ISSUE TITLE
[BUG] FraudLabsPro send SMS verification broken

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2396]
**Describe the bug**

When attempting to send a 2FA SMS message with FraudlabsPro's built in action, I receive an error about attempting to access an `apiKey` value on an undefined property:

![CleanShot 2022-03-10 at 09 55 25@2x](https://user-images.githubusercontent.com/2694734/157690145-64124f34-248d-46d4-9f10-e85b261c77de.png)

**To Reproduce**
1. Create a Fraudlabs pro action with a valid SMS API key from FraudLabsPro
2. Attempt to send a 2FA token
3. Receive the error

**Expected behavior**
I expect the FraudLabsPro action to send a 2FA key to the SMS phone number.

**Additional Context**

My Fraudlabs Pro account is piercepipedream.

@fraudlabspro pinging you directly for more visibility.

**Comment by ctrlaltdylan** [comment]
I found the cause of the issue.

`utils.promisify` is being used to convert the Fraudlabs Pro individual API calls from a callback strategy to a Promise strategy.

However, the `promisify` has a different signature: `(err, data) => {}` than what's being passed in this implementation `params, (err, data) => {}`.

I just wrapped in Promise the old fashioned way and it's working for me:

```javascript
    async sendSmsVerification(params) {
      return new Promise((resolve, reject) => {
        this.smsVerification().sendSMS(params, (err, data) => {
          if (err) {
            reject(err);
          }
          resolve(data);
        });
      });
    },
```

**Comment by fraudlabspro** [comment]
Hi [ctrlaltdylan](https://github.com/ctrlaltdylan),

Thanks for bring us the attention! Since you had made the PR, we won't touch the code. Thanks again for the code changes suggestion.

**Comment by dannyroosevelt** [comment]
@ctrlaltdylan can you help verify the fix? If it looks good you or @js07 can merge.

**Comment by ctrlaltdylan** [comment]
@dannyroosevelt , I actually used this PR for this week's Speed Run, so I know it works.

https://pipedream.com/blog/verify-woocommerce-orders-with-sms-codes-with-fraudlabs-pro/

@js07 if you want to switch it to the `.bind` interface and retest it's up to you. But I know the `Promise` way is working.

**Comment by js07** [comment]
@dannyroosevelt @ctrlaltdylan I switched it to the `.bind` interface and retested the **Send SMS Verification** and **Get Verification Result** actions, and they both work for me.

**Comment by ctrlaltdylan** [comment]
Much better solution than mine. I think we should merge this one?

**Comment by js07** [comment]
Merged https://github.com/PipedreamHQ/pipedream/pull/2397
