### ISSUE TITLE
[TRIGGER] Procore

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#240]
**Describe the event source. What app, what event?**

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by nlovelace** [comment]
Event sources in Procore may include:
Prime Contract
Prime Contract Change Orders
Commitments / Purchase Orders
Commitment Change Orders
Budgets/Snapshots
RFI's
Submittals
API Docs Found [HERE](https://developers.procore.com)

**Comment by dylburger** [comment]
Nice, thank you for the detail @nlovelace .
