### ISSUE TITLE
Pinterest [APP]

### ISSUE THREAD

**Issue by murffious** [PipedreamHQ/pipedream#2403]
**Name of app / service**
Pinterest

**Link to developer documentation**
https://developers.pinterest.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, I signed up just for this to speed me up and its not here. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Post on Pinterest about a food/recipe I follow or diet related

**Comment by dannyroosevelt** [comment]
Submitted a request to Pinterest, pending their response.

**Comment by dannyroosevelt** [comment]
@murffious we just completed a basic integration with Pinterest: 
https://pipedream.com/apps/pinterest

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by dannyroosevelt** [comment]
### Triggers
- New Board
- New follower
- New pin

### Actions
- Create pin

**Comment by dannyroosevelt** [comment]
@feyzullah is this in progress?
