### ISSUE TITLE
[APP] Phantombuster

### ISSUE THREAD

**Issue by jerrodjordan** [PipedreamHQ/pipedream#2407]
**Name of app / service**
https://phantombuster.com/

**Link to developer documentation**
https://github.com/phantombuster/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
When scrapping is complete

**Comment by dannyroosevelt** [comment]
Here is a basic integration with Phantombuster to help you get started: https://pipedream.com/apps/phantombuster

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
