### ISSUE TITLE
[FEATURE] I need a way to link multiple triggers to a workflow

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#241]

**Comment by brkncoyot3** [comment]
+1

**Comment by dylburger** [comment]
This is supported [in the REST API](https://docs.pipedream.com/api/rest/#listen-for-events-from-another-source-or-workflow). Keeping this open to track UI support.

**Comment by dylburger** [comment]
This is now supported in [the new version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/)! When you're editing your workflow, select the menu at the top-right of your trigger step and click **Add Trigger** to add another trigger. 

<img width="262" alt="Screen Shot 2022-02-22 at 4 31 30 PM" src="https://user-images.githubusercontent.com/242668/155243130-63d93282-9963-4718-9ba9-3a423ad95263.png">

Workflows support an arbitrary number of triggers.
