### ISSUE TITLE
[Trigger] Close

### ISSUE THREAD

**Issue by calebsbrand** [PipedreamHQ/pipedream#2433]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
https://developer.close.com/topics/authentication/

**Comment by dannyroosevelt** [comment]
Hi @calebsbrand it looks like we have a basic integration with Close live today: https://pipedream.com/apps/close

Can you elaborate on what event from Close you'd like to see trigger a Pipedream workflow?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
