### ISSUE TITLE
[ACTION] Adding a task to a project in Asana

### ISSUE THREAD

**Issue by maxyedid** [PipedreamHQ/pipedream#2443]
There needs to be a way to add a step for adding a project into a specific task. Normally, with asana's api, all you would need is a task gid, project gid, and a section to insert the task into. However, due to asana's api, an array of projects can only be added if the task is being created, not updated and to add the project, one would have to use the addProject method in their code.

https://forum.asana.com/t/api-error-projects-cannot-write-this-property/77626
https://developers.asana.com/docs/add-a-project-to-a-task

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by maxyedid** [comment]
I'll try and create the action and see if I can create a PR for it

**Comment by dannyroosevelt** [comment]
@maxyedid we're going to tackle this work as a part of https://github.com/PipedreamHQ/pipedream/issues/1481, so I'm going to close out this ticket (feel free to follow 1481 for updates!)
