### ISSUE TITLE
[FEATURE] Support invocation specific global variables

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2448]
**Is your feature request related to a problem? Please describe.**
I have a workflow where a few steps "in the middle", will conditionally run. So imagine a 5 step workflow, steps 2/3/4 are set up such that only one will run. 

Each of those steps will have one result and I want to use it in step 5, but I don't want to repeat the conditional logic. 

$checkpoint is available all through the workflow but it persists. I don't want it to persist after the evocation and I may have 2+ requests coming in at the same time.

**Describe the solution you'd like**
I'd like to use "global" as a scope, or $global, that's read/writeable from any step. In my scenario above, steps 2/3/4 may all do, $global.message = "something". Step 5 would then use it.

**Do you have a workaround?**
Per Pierce's idea in Slack, you could use returns and see if step2 has a null return, if so then check 3, and so forth.

**Comment by dylburger** [comment]
Thanks for the request, tracking in #167
