### ISSUE TITLE
AAPT2 issue

### ISSUE THREAD

**Issue by vanshikasaini** [PipedreamHQ/pipedream#245]
https://stackoverflow.com/questions/62827246/after-compiling-android-project-suddenly-proguard-issue-occured-sometime-ask-jdk
 Hi pls check above link i am getting issue:
AAPT: unknown option '--proguard-minimal-keep-rules'.
I have changed my gradle version from 4.0.0 to 3.5.6 but still it is showing the same line for more detail u can check attached screenshot in above link.

#android

**Comment by dylburger** [comment]
Hi @vanshikasaini , I believe you may have found the wrong repo - our project isn’t related to Android. 

I’m closing this issue, hope you’re able to get an answer on StackOverflow.
