### ISSUE TITLE
[APP] GoToWebinar

### ISSUE THREAD

**Issue by nauxliu** [PipedreamHQ/pipedream#2453]
**Name of app / service**
GoToWebinar

**Link to developer documentation**
https://developer.goto.com/GoToWebinarV2/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It blocks us from building workflow as the app only supports OAuth.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Triggers for the following webhook events:  
registrant.added, registrant.joined, webinar.created, webinar.changed

**Comment by sergio-eliot-rodriguez** [comment]
GoToWebinar has been integrated 
https://pipedream.com/apps/gotowebinar

**Comment by sergio-eliot-rodriguez** [comment]
@nauxliu registrant.added, registrant.joined triggers are already developed, see https://pipedream.com/apps/gotowebinar#popular-goto-webinar-triggers

about webinar.created, webinar.changed let's follow progress on #9062
