### ISSUE TITLE
[ACTION] RocketReach

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2461]
**Is there a specific app this action is for?**
RocketReach (`rocketreach`)

**Please provide a link to the relevant API docs for the specific service / operation.**
https://rocketreach.co/api?section=api_section_ov_gs

**Actions**
- Lookup Profile | Lookup contact information for a prospect (profile).
- Lookup Company | Lookup metadata information for an account(company).

**Comment by Jordon-L** [comment]
Hi, I would like to take on this issue. Since the endpoints can have multiple combinations of parameters would requiring the user to select the parameters they want to use be good?

**Comment by dannyroosevelt** [comment]
Great! I think the most relevant parameters should be used as `props` for each action. And I think most of them are probably optional.
