### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by RiverTeacher** [PipedreamHQ/pipedream#2463]
**LINE**

**https://notify-bot.line.me/en/**

**Is lack of support preventing you from building workflows**

**Say a message through a BOT**

**Comment by dannyroosevelt** [comment]
@RiverTeacher we have these actions for Line coming soon -- https://github.com/PipedreamHQ/pipedream/issues/1501. Would any of those satisfy your needs?

**Comment by RiverTeacher** [comment]
Send a Push Message is most needs for me😆
