### ISSUE TITLE
[BUG] [Workflow Subscriptions] When a emitting workflow times out, the subscribing workflow does not invoke

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2469]
**Describe the bug**

Workflow A - the emitter
Workflow B - the subscriber

Workflow A is timing out due to a long running process, but the subscribed Workflow B is not being invoked because of the time out.

I expect Workflow B to always be invoked as long as Workflow A is invoked, regardless if the emitting workflow times out or not.

**To Reproduce**
1. Create a subscription between 2 workflows
2. Make workflow A timeout
3. Workflow B is never invoked.

**Expected behavior**

I expect Workflow B to always be invoked as long as Workflow A is invoked, regardless if the emitting workflow times out or not.

**Additional context**
Example subscription with this issue: `{"data":[{"id":"sub_L9U7RVw","emitter_id":"p_brC3vmG","listener_id":"p_ljCkw28","event_name":""}]}`

https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1647889677227109?thread_ts=1645031563.734869&cid=CMZG4EBJ9

**Comment by dylburger** [comment]
This is expected behavior. If the workflow times out before the emit code is executed, we won't emit the event to subscribers. Increasing the workflow timeout is the correct solution.
