### ISSUE TITLE
[FEATURE] Allow access to trigger parameters

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#247]
**Is your feature request related to a problem? Please describe.**
Steps should be able to access the configuration information of a trigger/event source.

**Describe the solution you'd like**
Basically what I just said. ;) As a practical example, in the RSS event source, I'd like to be able to know the RSS url that was checked.

**Do you have a workaround?**
Nope.

**Comment by dylburger** [comment]
Duplicate of #592
