### ISSUE TITLE
onSubmit of google form

### ISSUE THREAD

**Issue by TikshaAggarwal01** [PipedreamHQ/pipedream#2486]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by dylburger** [comment]
Hi @TikshaAggarwal01 , thanks for reaching out. We're tracking this in #631. We should be working on this soon. You can track the progress at that issue.
