### ISSUE TITLE
Rss feed filter

### ISSUE THREAD

**Issue by darkmaster420** [PipedreamHQ/pipedream#2489]
Can you guys add a filter to the rss feed by keyword maybe. Could be very useful if you want to only receive certain rss posts. For example when a post contains the keyword "John" it will only send posts containing that keyword. Please and thank you🙏

https://pipedream.com/apps/rss/
I want to tie this with a telegram bot

**Comment by dylburger** [comment]
@darkmaster420 You can do this within your workflow by adding a new Node.js code step. I used the title in this example, since not all RSS feeds contain the full text of the post, but if the text is present, you can substitute `title` with whatever data you'd like:

```javascript
export default defineComponent({
  async run({ steps, $ }) {
    const { title } = steps.trigger.event
    if (!title || !title.includes("John")) {
      return $.flow.exit("Title doesn't contain our keyword. Exiting!")
    }
  },
})
```

Let me know if that helps.

**Comment by darkmaster420** [comment]
Thank you but i just couldn't be bothered to code a filter myself that's why I was asking them to add it, but i also think it could be useful to other people.
Figured out a solution by using a 3rd party RSS feed parser which had a filter built in which worked a charm
RSS.app if you're wondering

**Comment by dylburger** [comment]
@darkmaster420 Great, I'm glad that worked for you.

Can you tell me specifically what field in the RSS feed you were filtering on? Title, description, etc.?

**Comment by darkmaster420** [comment]
I was trying to filter both the title and description.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
