### ISSUE TITLE
how can i right different responsives in html and css

### ISSUE THREAD

**Issue by Nimamoazez1381** [PipedreamHQ/pipedream#250]
Hey guys i wrote 6 different responsive for my page but it just read one of my styles for all of them and other 5 styles don't work at all.

i'd be glad if you could help me

**Comment by dylburger** [comment]
Hi @Nimamoazez1381 , since this isn't an issue with Pipedream, I'm closing this. Best of luck figuring out your issue - I'd suggest StackOverflow or another Q&A site.
