### ISSUE TITLE
[BUG] Incorrectly parsing objects in Data Stores -- Add Updated Multiple Records action

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2501]
When I construct a custom object like `[{"jedi": "luke", "use": "the force"}]`, we add every character as its own value, each with its own key (0, 1, 2, 3, etc).

What I'm expected instead, is to add the below records:
`jedi: "luke"`
`use: "the force"`

**Comment by feyzullah** [comment]
@dannyroosevelt how about recursive ones like `[ { a: "b" }, [ [ { c: "d" } ] ] ]` and `[ [ [ { a: "b" }, { c: "d" } ], [ { e: "f" } ] ] ]` ?

**Comment by dannyroosevelt** [comment]
Are we able to support those as objects? That would be ideal if possible. It looks like we're currently storing those as strings.

**Comment by dannyroosevelt** [comment]
Oh by the way, you can enable the Data Stores UI in your Pipedream account by enabling the 3rd checkbox here: https://pipedream.com/alpha (`stores: $checkpoint in alice`)

**Comment by vellames-turing** [comment]
For latter information: https://pipedream-users.slack.com/archives/C01E5KCTR16/p1648676121001329
