### ISSUE TITLE
[BUG] Reddit-NEW SAVED POST BY USER- no longer working

### ISSUE THREAD

**Issue by onlytanmoy** [PipedreamHQ/pipedream#2506]
Hiya, the below trigger stopped working for me all of a sudden from today 😒

https://github.com/PipedreamHQ/pipedream/blob/master/components/reddit/sources/new-saved-post-by-user/new-saved-post-by-user.mjs

It did work all good for me in the past ever since this was implemented on back of my request via https://github.com/PipedreamHQ/pipedream/issues/2287

Please can this be checked? Let me know for any other details you need. Thanks.

**Comment by michelle0927** [comment]
@onlytanmoy Would you be able to go to the source, click on LOGS, and take a screenshot of the most recent source logs?

**Comment by onlytanmoy** [comment]
Hi @michelle0927 please find the screenshot https://imgur.com/a/JlEVBjG

**Comment by dannyroosevelt** [comment]
This is ready for release!

**Comment by onlytanmoy** [comment]
This has broken again 😒
Here is the screenshot of the most recent source logs: https://imgur.com/a/4EVLZkN
Please fix it, thanks!

**Comment by dannyroosevelt** [comment]
> This has broken again 😒 Here is the screenshot of the most recent source logs: https://imgur.com/a/4EVLZkN Please fix it, thanks!
> 
> Let me know if you want me to create a new issue as this one is closed and I don't see any option to re-open it.

@onlytanmoy yes can you please file a bug and someone from the team will check it out!

**Comment by onlytanmoy** [comment]
@dannyroosevelt Thanks mate, new issue created https://github.com/PipedreamHQ/pipedream/issues/2925
