### ISSUE TITLE
[BUG] UI issue with new workflow dropdown

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2515]
**Describe the bug**
UI issue with new workflow dropdown:

![image](https://user-images.githubusercontent.com/393660/160694866-7f024724-711b-4ea0-968d-4ab2e968604f.png)

**To Reproduce**
1. Click the green dropdown when making a new workflow

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Edge
 - Version Latest

**Comment by dylburger** [comment]
@cfjedimaster We recently fixed some z-index issues that I believe may have corrected this. Can you check to see if it's still an issue? If so I'll let the team know.

**Comment by cfjedimaster** [comment]
LGTM (so closing, hope that's cool)
