### ISSUE TITLE
[APP] ZeroTier

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#2524]
**Name of app / service**
ZeroTier

**Link to developer documentation**
https://docs.zerotier.com/central/v1/

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I would like to use ZeroTier as a trigger for machine online/offline state. An example would be an email alert if a machine went offline.

**Comment by dannyroosevelt** [comment]
@zalmanlew here is a basic integration you can use to get started making authenticated requests to ZeroTier's API: https://pipedream.com/apps/zerotier

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by zalmanlew** [comment]
I reached out to ZeroTier to see if they're able to help on this; especially since it would be great if we could get a pushed based trigger (for online/offline statuses).

**Comment by laduke** [comment]
Hey there, this isn't an uncommon request for zerotier/central, but there isn't a webhook or similar push trigger. Someday maybe. You'd have to poll. That data is updated every 30 seconds or minute IIRC.

Since zerotier is p2p, being "online" does not necessarily mean "can connect to any or all other nodes on the network". 
For some cases, it's better to monitor over your zerotier networks. Can node A ping node B, for example. 

What ever works for your usage. Hope that helps. 

The agent that runs on the computer has an api too FWIW
https://docs.zerotier.com/service/v1

**Comment by zalmanlew** [comment]
@laduke the idea is that it would integrate with Pipedream. If the main ZT network considered it offline we would call that node offline (this is how it works in the dashboard). 

As for an integration in general, is ZeroTier able to dedicate some resources to help develop at least an initial phase of a Pipedream integration? Your team will have the best knowledge of the internal API and this integration will provide a lot of value to a large customer base already utilizing Pipedream. It can also open the doors for future integrations with other providers.
___
Some common integrations to start with (which have the most broad use case)

**Triggers**
- Node joined/left network
- Node online
- Node offline
- Network created (or updated)

**Actions**
- Create a new network (or update an existing one)
- Authorize node in network (or unauthorize)
- Update node in network (like name/description/IP)
- Remove node from network

**Get Actions**
- Retrieve all networks (or an individual one)
- Retrieve all nodes in a network (or an individual one)
- Retrieve user details

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by dannyroosevelt** [comment]
Let's trim that list down in order to get started more quickly:

### Triggers
Node joined/left network
Node online
Node offline

### Actions
Retrieve all networks (or an individual one)
Retrieve all nodes in a network (or an individual one)
Retrieve user details

**Comment by zalmanlew** [comment]
### Triggers - Endpoints
All the triggers can be handled via polling the **GET** `/network/:network_id/member` endpoint. Then just comparing it with the last fetch to identify which nodes have now joined/left the network as well as which nodes are online/offline.
When triggering the event, it should also fire the entire JSON object of the respective node along with the event, like this you can perform actions with the specific nodes.

- _Online_ nodes are just handled with the `online` boolean (true = online, false = offline)
- _Joined_ nodes can be handled if they are returned or not (where if they don't it means it left, if they do it means it joined)

### Actions - Endpoints
| Action                                  | Details                                           | Endpoint                                     |
|-----------------------------------------|---------------------------------------------------|----------------------------------------------|
| Retrieve All Networks                   | Returns a list of networks you have access to.    | GET `/network`                               |
| Retrieve Single Network                 | Returns a single network                          | GET `/network/:network_id`                   |
| Retrieve All Nodes (on a network)       | Returns a list of members (nodes) on the network. | GET `/network/:network_id/member`            |
| Retrieve Single Node (on a network)     | Return an individual member (node) on a network   | GET `/network/:network_id/member/:member_id` |
| Retrieve User Details (ZT account info) | Returns the user record                           | GET `/user/:user_id`                         |

**Comment by laduke** [comment]
The `lastAuthorizedTime` property might help for finding new members that need to be authorized for the first time. 

You can't really tell if a node "left". Only that it's lastOnline is getting older. 

online/offline is just `lastOnline` in the last 3 minutes.

hope that's helpful

**Comment by zalmanlew** [comment]
@laduke interesting point, I was actually thinking that left the network was more like _removed_ from the network by the admin. I guess we can skip that trigger for now.
