### ISSUE TITLE
[FEATURE] I want to see `$.flow.exit` data in the inspector / list of events

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#2528]
Like `$end()` in v1, I'd like to see the end reason / state if `$.flow.exit` is called for a live event. Currently, I don't see the exit data in the inspector, nor in the list of events like I had in v1.

**Comment by dannyroosevelt** [comment]
[This ticket](https://github.com/PipedreamHQ/pipedream/issues/2909) was a result of not being able to see that a step ended due to `$.flow.exit`.

**Comment by pedropedruzzi** [comment]
Additional note: as users already see `$.flow.exit` alerts during workflow editing/testing (screenshot below), they might get confused by not seeing a similar alerts in inspector.

<img width="340" src="https://user-images.githubusercontent.com/240791/169824251-4e93eebd-81e9-4435-bdf9-05be07df4399.png">

**Comment by dannyroosevelt** [comment]
FYI we added support for surfacing when steps ended execution in the step overview in Inspect mode. These are not yet surfaced in the event list, so I've created a [new ticket](https://github.com/PipedreamHQ/pipedream/issues/2957) to track that specific work.

![image](https://user-images.githubusercontent.com/20780753/170320208-ccd96e60-f3af-4a38-a0bf-d45010e9a408.png)
