### ISSUE TITLE
[TRIGGER] Multiple RSS Feeds

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#253]
I'd like the option to poll multiple RSS feed URLs in a single event source, emitting new items from any of the watched feeds in a unified stream, essentially combining multiple RSS feeds into one.

**Comment by cfjedimaster** [comment]
Can I ask that this be both a trigger *and* an action? Ie, I may want to build a workflow where I get all items from N sources and do stuff with it. (Let me know if this distinction doesn't make sense.)

**Comment by dylburger** [comment]
@cfjedimaster if you had a way to connect multiple sources to a single workflow, would that work for you? In this model, events from source 1 and source 2 would each trigger a single workflow, as soon as items are added to either feed. This is possible via API, and I can show you how this works if you'd like.

Or, do you need to process items from multiple sources in _batch_, instead? That is, every 15 minutes, collect the array of new items added to the feed, and do something with that group? In that case, you can use the REST API to fetch events from any number of sources. Check out the section on [fetching events from sources](https://docs.pipedream.com/api/rest/#events) specifically. You can connect the **Pipedream** app to a code step to pass your Pipedream API key.

Finally, I think you may have already seen the action we have for polling multiple RSS feeds for updates, but [here's a workflow](https://pipedream.com/@dylburger/fetch-stories-from-multiple-rss-feeds-p_WxCRxV/edit) that uses that action.

**Comment by cfjedimaster** [comment]
I don't want it as multiple sources, just an action that as inputs, takes N feeds, and for output, returns all the items. This sounds like what you are building for an event source, but I'd want the logic more generalized so it could be used in a step. It's close to what you said in the second paragraph, but I don't care if it's new per se.

Basically I think what I'm asking for is a simpler reusable version of what you are building, ie a non-Trigger version.

**Comment by alysonturing** [comment]
@Hassan-Abbas-SQA I believe that you mistakenly removed me from assignees list, I'm adding myself again

**Comment by Hassan-Abbas-SQA** [comment]
Yes, pardon me

**Comment by Hassan-Abbas-SQA** [comment]
@alysonturing 
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/104946677/167055401-0e038269-9da0-4f51-b1ff-56e2ee66d0ce.png">
i think there should be validation of url list implemented in this trigger to see if its getting the valid url list or not instead of showing Econnrefused Error we can show user a invalid list of urls error

**Comment by dannyroosevelt** [comment]
@dylburger this is ready for release!

**Comment by dannyroosevelt** [comment]
@dylburger this is ready for release!

**Comment by dannyroosevelt** [comment]
@dylburger this is ready for release!

**Comment by dannyroosevelt** [comment]
@alysonturing this is ready for release!
