### ISSUE TITLE
Migrate Pipedream Twitter app to Twitter's API v2

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2531]
Pipedream's Twitter integration is currently using Twitter's API v1.1.

Now that Twitter has released their v2 API for General Availability, we should update. A few advatages:
- More generous rate limits for users creating tweets 
- New endpoints
- Consistent response formats
https://developer.twitter.com/en/docs/twitter-api/migrate/whats-new

**Comment by vanetreg** [comment]
+1 for this feature

**Comment by ctrlaltdylan** [comment]
Related issue:

https://github.com/PipedreamHQ/pipedream/issues/4034

**Comment by dannyroosevelt** [comment]
This is done!
