### ISSUE TITLE
[APP] Nimble CRM

### ISSUE THREAD

**Issue by ajedwards** [PipedreamHQ/pipedream#2539]
**Name of app / service**
Nimble CRM

**Link to developer documentation**
https://support.nimble.com/en/articles/502755-nimble-api-access
https://nimble.readthedocs.io/en/latest/

**Comment by sergioeliot2039** [comment]
Nimble API documentation available at https://nimble.readthedocs.io/en/latest/

**Comment by sergio-eliot-rodriguez** [comment]
Nimble has been integrated: https://pipedream.com/apps/nimble
