### ISSUE TITLE
[APP] Google Slides Output?

### ISSUE THREAD

**Issue by darethehair** [PipedreamHQ/pipedream#2553]
**Name of app / service**

Google Slides

**Link to developer documentation**

???

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Not able to direct API from Openweather into a Google Slide (for real-time weather display)

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Triggers are fine -- ability to use Google Slides as final destination/output is the challenge :)

**Comment by sergioeliot2039** [comment]
This app is intetegrated , see [Google Slides](https://pipedream.com/apps/google-slides)

**Comment by sergioeliot2039** [comment]
Did you mean you need certain actions created?
Anyway, whether it's sources triggers an/or actions you'd like to see, all of our component code is open source and we encourage you to build your own triggers and actions. Are you interested in giving that a shot? I recommend starting here: https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by ctrlaltdylan** [comment]
@sergioeliot2039 I believe @darethehair is requesting the ability to update a Google Slide, which would call for this API integration as an action: https://developers.google.com/slides/api/reference/rest/v1/presentations/batchUpdate

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
