### ISSUE TITLE
Action for Spotify, "Recently Played" [FEATURE] 

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#256]
**Is your feature request related to a problem? Please describe.**
I see a bunch of Spotify actions, but I don't believe I see one for the recently played endpoint: https://developer.spotify.com/documentation/web-api/reference/player/get-recently-played/

**Describe the solution you'd like**
An action for that. :)

**Do you have a workaround?**
Sure, write my own Node code with their API.

**Comment by dylburger** [comment]
@cfjedimaster you should now see a **Get Current User's Recently Played Tracks** action tied to Spotify, see https://pipedream.com/@dylan/spotify-get-current-user-s-recently-played-tracks-p_YyCbNr/edit . Let me know if that works for you.
