### ISSUE TITLE
Uploadcare [APP]

### ISSUE THREAD

**Issue by johnbhiggins7** [PipedreamHQ/pipedream#2573]
**Name of app / service**
Uploadcare
**Link to developer documentation**
https://uploadcare.com/api-refs/upload-api/
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
@johnbhiggins7 here is a basic integration -- https://pipedream.com/apps/uploadcare

Are there specific actions or triggers you're looking for that would be helpful to get started?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
