### ISSUE TITLE
Close.io

### ISSUE THREAD

**Issue by rmeyer231** [PipedreamHQ/pipedream#2575]
Close.io

[**Link to developer documentation**](https://developer.close.com/)

I believe I have a workaround

Triggers and Actions
![SCR-20220407-mb9](https://user-images.githubusercontent.com/83611031/162307129-e4423277-0714-4daa-acd1-10419a0589d1.png)

**Comment by dannyroosevelt** [comment]
Hi @rmeyer231 thanks for submitting -- did you have specific actions and triggers you'd like to see for Close? We have a [basic integration](https://pipedream.com/apps/close) in place today, but no pre-built actions or triggers yet. We'd love your feedback on which ones you'd like to see first!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
@rmeyer231 FYI you can track this work on our backlog here: https://github.com/PipedreamHQ/pipedream/issues/2624
