### ISSUE TITLE
[ACTION]Reddit & GDrive-How to save images from an album instead of HTML file?

### ISSUE THREAD

**Issue by onlytanmoy** [PipedreamHQ/pipedream#2576]
Hiya, think I can use some help. So basically I have set up a workflow between Reddit and Google Drive as in hot posts from r/wallpapers will be saved in my connected Google Drive specified folder as images. This is working fine except for posts which contains multiple images (album) such as this one
https://www.reddit.com/r/wallpapers/comments/tyci69/some_walls_from_my_collections_vol9/
in that case it gets saved as file type HTML instead of file type Image. Please let me know what changes I need to make in my workflow so that all the images from that album will get saved in the Google drive as images and not a HTML file. Tia.

**Comment by dylburger** [comment]
@onlytanmoy Thanks for reaching out and sorry for the delay. We do support at https://pipedream.com/support - would you mind reaching out on our Slack / Discourse forums, and someone from our team will get back to you there? Thank you.
