### ISSUE TITLE
[BUG] Can create invalid table

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#258]
**Describe the bug**
This is my fault, but I created a table named spotify-artists. The $send.sql service actually let me do it, and I have a table with that name now, but I can't query from it. Nor can I delete it. So two things I guess:

$send.sql should have stopped me from making the table

Can you manually drop the table for me?

**Comment by dylburger** [comment]
@cfjedimaster I deleted this table for you and am keeping the request open to track the bug.

**Comment by dylburger** [comment]
The SQL Service will be shutting down on Feb 10th, 2022 (you can read more details in [this post](https://pipedream.com/blog/shutting-down-the-sql-service/)). As a result, we're closing this issue.

Let us know if you have any questions at all.
