### ISSUE TITLE
[BUG] Not able to create source -- Google Sheets: New Row Added 

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2599]
This appears to happen with 1 spreadsheet specifically, for this user. Not all API calls fail for this spreadsheet however, they are able to access the spreadsheet properties. Context from Slack: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1649717873040829

![image](https://user-images.githubusercontent.com/20780753/162855491-b608e663-d765-4739-8b9d-dea1e9b93a21.png)

**Comment by Hassan-Abbas-SQA** [comment]
Trigger still has previous selected shee1 events data in variables even if i select sheet2 it still shows sheet1's events data (previous sheet's events should be flushed to keep the events data clean). 

Uploading Screen Recording 2022-05-17 at 2.48.45 AM.mov…

**Comment by dannyroosevelt** [comment]
> Trigger still has previous selected shee1 events data in variables even if i select sheet2 it still shows sheet1's events data (previous sheet's events should be flushed to keep the events data clean).
> 
> Uploading Screen Recording 2022-05-17 at 2.48.45 AM.mov…

I don't think the video finished uploading?

**Comment by dannyroosevelt** [comment]
> > Trigger still has previous selected shee1 events data in variables even if i select sheet2 it still shows sheet1's events data (previous sheet's events should be flushed to keep the events data clean).
> > Uploading Screen Recording 2022-05-17 at 2.48.45 AM.mov…
> 
> I don't think the video finished uploading?

Looks like you didn't save the changes to the trigger

**Comment by Hassan-Abbas-SQA** [comment]
> > > Trigger still has previous selected shee1 events data in variables even if i select sheet2 it still shows sheet1's events data (previous sheet's events should be flushed to keep the events data clean).
> > > Uploading Screen Recording 2022-05-17 at 2.48.45 AM.mov…
> > 
> > 
> > I don't think the video finished uploading?
> 
> Looks like you didn't save the changes to the trigger

tried both ways save and unsaved none of them worked for me

https://user-images.githubusercontent.com/104946677/168693786-d2affc8d-20c4-4c92-a396-f61badffc1b8.mov

**Comment by dannyroosevelt** [comment]
> > > > Trigger still has previous selected shee1 events data in variables even if i select sheet2 it still shows sheet1's events data (previous sheet's events should be flushed to keep the events data clean).
> > > > Uploading Screen Recording 2022-05-17 at 2.48.45 AM.mov…
> > > 
> > > 
> > > I don't think the video finished uploading?
> > 
> > 
> > Looks like you didn't save the changes to the trigger
> 
> tried both ways save and unsaved none of them worked for me
> 
>  Screen.Recording.2022-05-17.at.3.37.58.AM.mov

I don't think that's a bug -- since you are just modifying the source configuration but not creating a _new_ source, we preserve the events.

**Comment by Hassan-Abbas-SQA** [comment]
Alright than ticket is ready for release

**Comment by dannyroosevelt** [comment]
This is ready for release!

**Comment by cebnz** [comment]
Sorry to say that the fix just released for the Google Sheets: New Row Added problem (#2685/#2599) is still throwing the same fault for my problem.

**Comment by dannyroosevelt** [comment]
> Sorry to say that the fix just released for the Google Sheets: New Row Added problem (#2685/#2599) is still throwing the same fault for my problem.

Oh no! To confirm, have you added this latest version of the New Row Added source? Sources that are already added to workflows will not automatically update to new versions.

**Comment by cebnz** [comment]
Yeah... I did consider that and created a whole new workflow. Also tried the version for shared drive -- same result. I've shared the workflow wih support.

**Comment by Hassan-Abbas-SQA** [comment]
> Sorry to say that the fix just released for the Google Sheets: New Row Added problem (#2685/#2599) is still throwing the same fault for my problem.

can you please join

To join the video meeting, click this link: https://meet.google.com/yic-fhqd-zhi
Otherwise, to join by phone, dial +1 669-220-6664 and enter this PIN: 700 408 314#
To view more phone numbers, click this link: https://tel.meet/yic-fhqd-zhi?hs=5

**Comment by cebnz** [comment]
sorry i can't really

**Comment by Hassan-Abbas-SQA** [comment]
if you can share a video of re-creating the same bug?

**Comment by Hassan-Abbas-SQA** [comment]
> sorry i can't really

if you can share a video of re-creating the same bug?

**Comment by cebnz** [comment]
There's nothing to show really. It's just the same result as the screenshot at the startt of this thread.

**Comment by dannyroosevelt** [comment]
@cebnz is there anything you can tell us about this spreadsheet specifically? Are you able to make a copy of it (without any sensitive information) and share with me directly, so that we can try to troubleshoot and debug?

**Comment by cebnz** [comment]
It's not a bug, it's The Worm. The sheet contains one tab "The Worm" which is actually a chart displaying data from other tabs in the sheet. If I delete that tab, the error goes away. I have a totally minimal example I can provide if required.

**Comment by dannyroosevelt** [comment]
> It's not a bug, it's The Worm. The sheet contains one tab "The Worm" which is actually a chart displaying data from other tabs in the sheet. If I delete that tab, the error goes away. I have a totally minimal example I can provide if required.

That'd be very helpful if you could share an example that helps us reproduce the issue! Feel free to share with `danny@pipedream.com`.
