### ISSUE TITLE
Stripe - Find Product from checkout.session.completed event

### ISSUE THREAD

**Issue by ndtreviv** [PipedreamHQ/pipedream#2603]
# Overview
An action that takes data from a Stripe event listener and finds the associated product details on stripe given the checkout session.

# How
At the moment this is possible using individual stripe API actions. 

First, get the checkout session line items from the `checkout.session.completed` event's object ID:

```
import { axios } from "@pipedream/platform"

export default defineComponent({
  props: {
    stripe: {
      type: "app",
      app: "stripe",
    }
  },
  async run({steps, $}) {
    return await axios($, {
      url: `https://api.stripe.com/v1/checkout/sessions/${steps.trigger.event.data.object.id}/line_items?limit=5`,
      auth: {
        username: `${this.stripe.$auth.api_key}`,
        password: ``,
      },
    })
  },
})
```

Second, get the price of the first line item (this could not be the first item every time, I suppose) associated with the checkout session:

```
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    stripe: {
      type: "app",
      app: "stripe",
    }
  },
  async run({steps, $}) {
    return await axios($, {
      url: `https://api.stripe.com/v1/products/${steps.stripe.$return_value.data[0].price.product}`,
      auth: {
        username: `${this.stripe.$auth.api_key}`,
        password: ``,
      },
    })
  },
})
```

and with the price get the product data.

# Why
Here's my own use case:
I have a few individual products on Stripe with a metadata item where the key is `mailerlite_group`. When someone purchases a product using a Stripe payment link the workflow I'm using right now grabs the `mailerlite_group` value, which is the ID of the associated group on Mailerlite, and then it uses the `mailerlite_subscribe_to_group` to subscribe the paying user to the correct group in mailerlite.

This means that I can target that user with post-purchase automations setup in mailerlite (eg: email giving them access to digital products, etc), AND organise future customer comms, marketing etc as well.

I could combine the two above actions into one using my own, possibly error-prone code, but it would be really nice if this was an official action that existed in the action library.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by ndtreviv** [comment]
Hey, the actions I contributed previously fulfil this request, so I'm going to close this.
