### ISSUE TITLE
[FEATURE] Sharing Sources

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2604]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to share sources across PD accounts, just like sharing v1 workflows.

**Describe the solution you'd like**

> If we do have a webhook source that is created individually apart from the workflow, and that workflow is shared, it'd be great to be able to edit the webhook source config.

**Do you have a workaround?**

At this time no.

**Additional context**

Requested by DevRev.

**Comment by dylburger** [comment]
Duplicate of #266
