### ISSUE TITLE
[BUG] Move Data Stores Limits doc

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2608]
A small thing, but the notes for DS limitations (https://pipedream.com/docs/code/nodejs/using-data-stores/#data-store-limitations) currently live under the code portion of working with data stores. I think it should be under the *core* DS docs at https://pipedream.com/docs/data-stores/. That being said (grin), I'd keep the supported data types (https://pipedream.com/docs/code/nodejs/using-data-stores/#data-store-limitations) where it is.

**Comment by dannyroosevelt** [comment]
@ctrlaltdylan -- this is a good point. the limitations probably belong in both places. wdyt?

**Comment by ctrlaltdylan** [comment]
I dig it! Thanks again for another helpful suggestion @cfjedimaster 🍻
