### ISSUE TITLE
[Updates] Linear Actions and Triggers

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2610]
The components are shared between `linear` and `linear_app`.

### Triggers
- Add optional prop to both triggers for `team`, `project` (use async options)

### Actions
- Handle pagination (the user should not have to configure after/before/first/last)
- Update "Search issues" action and add the below optional props (with async options if possible):
  - team
  - project
  - assignee
  - label

**Comment by andrewjschuang** [comment]
@dannyroosevelt is there a reason for this app to be separated? Can we join them?

**Comment by andrewjschuang** [comment]
Oh, `linear_app` uses API key and `linear` uses OAuth
