### ISSUE TITLE
[APP] Multiple RSS Feeds

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#2611]
**Name of app / service**

Multiple RSS feeds 

**Link to developer documentation**

This is the same as RSS, but allowing for an arbitrary number of feeds to be input.

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I have a workaround, to create one source for each RSS feed, but with dozens of feeds it's very busy in the UI.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thank you for raising, @johndbritton ! We are tracking at #253 . I just moved that ticket a bit higher on our backlog to see if we can get to it soon!
