### ISSUE TITLE
[BUG] Autocomplete dropdown is cut off if the code area is smaller than the dropdown

### ISSUE THREAD

**Issue by tekacs** [PipedreamHQ/pipedream#2616]
**Describe the bug**
When using the autocomplete dropdown in a code (Node, but probably anything?) area, it's cut off by the containing editor area, which means that if you haven't typed enough lines, it expands below the editor area and is cut off visually.

**To Reproduce**
1. Create a new Node block
2. Type `$.send.`
3. Observe that the autocomplete dropdown is cut off -- and you can select (by pressing up) entries that are cut off.

**Expected behavior**
The autocomplete dropdown should escape the editor area if possible, so that you don't have to remember how to use APIs when writing shorter snippets.

**Screenshots**
<img width="908" alt="CleanShot 2022-04-13 at 20 38 24@2x" src="https://user-images.githubusercontent.com/63247/163291857-05e363f5-f574-4765-8799-fd5f9f489765.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome Canary
 - Version 102.0.4993.0

**Comment by dylburger** [comment]
Thanks for raising. I can reproduce and we're taking a look.

**Comment by dylburger** [comment]
@tekacs this should be fixed! Thanks for raising.

<img width="578" alt="Screen Shot 2022-04-18 at 6 15 20 PM" src="https://user-images.githubusercontent.com/242668/163900814-4ecf3b87-89f5-4070-a8b8-2178fbf365d0.png">
