### ISSUE TITLE
[BUG] Workflow attachments aren't available in v2 Node.js code steps

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2620]
**Describe the bug**

Files uploaded to workflows via attachments in the settings are not available in the `steps.trigger.context.attachments` object.

Documented in detail on the internal bug board: https://linear.app/pipedream/issue/PD-804/workflow-attachments-are-not-present-in-stepstriggercontextattachments

**Comment by huzaifahj** [comment]
I'm facing this issue, any updates please?

**Comment by dylburger** [comment]
This should be fixed. Any attachments should be available in `steps.trigger.context` attachments. 

For example, you can inspect attachments by running this Node.js code:

```javascript
export default defineComponent({
  async run({ steps, $ }) {
    // Reference previous step data using the steps object and return data to use it in future steps
    return steps.trigger.context
  },
})
```
