### ISSUE TITLE
[APP] Splitwise

### ISSUE THREAD

**Issue by nheung** [PipedreamHQ/pipedream#263]
**Name of app / service** Splitwise

**Link to developer documentation** https://dev.splitwise.com/#introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?** No workarounds

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Get and create expenses/payments

**Comment by dylburger** [comment]
Love Splitwise, thanks for the request @nheung ! We'll take a look ASAP.

**Comment by todsac** [comment]
Splitwise has been integrated.  Let us know if there are any event sources or actions that are of high priority.
