### ISSUE TITLE
avivalcris.onmicrosolft.onmicrosolft.com

### ISSUE THREAD

**Issue by l1574** [PipedreamHQ/pipedream#2638]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
@l1574 Thanks for the request. Can you tell me what the specific service is that you're trying to integrate, and more information about your use case?
