### ISSUE TITLE
[Refactor] Filter actions

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2643]
We should make a couple changes to the current Filter action:

1. Add an optional "Reason" prop, and set the `default` to `Condition met for exiting [or continuing] workflow`
2. Break out the current Filter action into 3 different actions and get rid of the `continue` prop:
- "Continue workflow based on a condition" (`filter-continue-workflow-condition`)
- "End workflow based on a condition" (`filter-end-workflow-condition`)
- "End workflow" (`filter-end-workflow`)

**Comment by dannyroosevelt** [comment]
Can we add a case sensitivity `additionalProp` for all below **text** conditions? (and implement the associated logic accordingly)

```
    caseSensitive: {
      type: "string",
      options: [
        `Case sensitive`,
        `Case insensitive`
      ],
      label: "Text case",
      description: `Select "Case **insensitive**" if \`this\` should be evaluated the same as \`THIS\`. Otherwise, select "Case **sensitive**".`,
      default: "Case sensitive",
    }
```

**Comment by dannyroosevelt** [comment]
And for the `end-workflow` action, let's make the following changes:
```
name: "End Workflow on Custom Condition",
key: "filter-end-workflow-custom-condition",
description: "Stop workflow execution in this step based on any custom condition",
```
And add an optional prop that must evaluate to `true` for execution to stop. You're basically duplicating the existing End app from here (with a slight update to the name and label): https://github.com/PipedreamHQ/pipedream/tree/master/components/end
```
    customCondition: {
      type: "boolean",
      label: "Custom condition",
      description: "Enter any expression (e.g., `{{ 2*2 === 4 }}`). If it evaluates to `true`, end workflow. Otherwise, continue.",
      optional: true,
      default: true,
    },
```
Then you can also trash the `/end` dir from `/components`, and we'll unpublish that action afterwards.

**Comment by dannyroosevelt** [comment]
Also, can you remove `filter` from path for all these actions? Otherwise they show up in the UI as the below:
![image](https://user-images.githubusercontent.com/20780753/164122233-11642adf-db00-48d7-9b5e-fc296e2e56a2.png)

But they should be this:
![image](https://user-images.githubusercontent.com/20780753/164122256-460dbe9d-cd21-4eb7-82c5-ef7efffd2426.png)

**Comment by dannyroosevelt** [comment]
@andrewjschuang why don't you go ahead and get this published now since we just announced it (and I've been testing them), then @DilanAthukorala you can still run through QA after it's out

**Comment by andrewjschuang** [comment]
> @andrewjschuang why don't you go ahead and get this published now since we just announced it (and I've been testing them), then @DilanAthukorala you can still run through QA after it's out

@dannyroosevelt can you approve the fix I pushed yesterday to the PR?

**Comment by dannyroosevelt** [comment]
> > @andrewjschuang why don't you go ahead and get this published now since we just announced it (and I've been testing them), then @DilanAthukorala you can still run through QA after it's out
> 
> @dannyroosevelt can you approve the fix I pushed yesterday to the PR?

Done

**Comment by dannyroosevelt** [comment]
This is ready for release!
