### ISSUE TITLE
[APP] Email Octopus

### ISSUE THREAD

**Issue by nahtnam** [PipedreamHQ/pipedream#2656]
**Name of app / service**
Email octopus 

**Link to developer documentation**
https://emailoctopus.com/api-documentation

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, I would like to build a webhook -> email octopus integration

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Add user to list

**Comment by dannyroosevelt** [comment]
Thanks for requesting, @nahtnam! FYI we integrated Email octopus here:
https://pipedream.com/apps/emailoctopus/, so you can at least make authenticated requests to their API.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
