### ISSUE TITLE
Workflows Folders or tags

### ISSUE THREAD

**Issue by 4epexa** [PipedreamHQ/pipedream#2657]
Hi team! 

I have many workflows for different clients, projects and tasks. It is very inconvenient to search for the right workflow. 
It would be convenient to have folders or tags for sorting workflows.

![image](https://user-images.githubusercontent.com/57490820/164175952-ccc48fd0-05ad-4a54-ba38-0a1e850e73e3.png)

**Comment by dylburger** [comment]
Thanks for raising @4epexa ! We're tracking in #203 if you don't mind following that issue.
