### ISSUE TITLE
Lucid Charts

### ISSUE THREAD

**Issue by bluemonday1** [PipedreamHQ/pipedream#2661]
**Lucid Charts**

**https://developer.lucid.co/api/v1/#overview**

**Is lack of support preventing you from building workflows, or do you have a workaround?** This is not an issue.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Request and Post

**Comment by dannyroosevelt** [comment]
It looks like Lucidchart needs to grant us access to enable an integration with their API -- we've submitted a request and will update this ticket when we hear back.

**Comment by dannyroosevelt** [comment]
@bluemonday1 we just released a basic integration with Lucid that you can check out here: 
https://pipedream.com/apps/lucid/

Are there specific actions or triggers you're looking to use with Lucid?
