### ISSUE TITLE
Slack Events API

### ISSUE THREAD

**Issue by aroslov** [PipedreamHQ/pipedream#2664]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

Ability to handle any Slack events to build bots that support homepage and button interactions. As a minimum, the integration should support responding to a challenge.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

https://api.slack.com/apis/connections/events-api

**Comment by dylburger** [comment]
@aroslov I hear you! We are planning to improve our Slack sources soon and we'll review the events for interactions specifically. We have an open ticket at #862 tracking this, so feel free to follow there.
