### ISSUE TITLE
[BUG] Python mapping imports fail when package names contain a "." character

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2668]
**Describe the bug**

To import modules where the package name differs from the PyPi name, we include it a custom mapping to allow Python steps in workflows to use the package.

For example:

```
import shopify
```

In a Python code step actually maps to the `ShopifyAPI` package.

However, this custom mapping breaks with packages with `.` characters in their name, such as `google.big-query`.

## Upstream Issue

This is the upstream issue that is causing this issue:

https://github.com/bndr/pipreqs/issues/188

**Comment by dylburger** [comment]
@ctrlaltdylan when you add the new docs for the magic mapping, can you also close out this issue?

**Comment by dylburger** [comment]
This is done: https://pipedream.com/docs/code/python/import-mappings/#using-magic-comments
