### ISSUE TITLE
[BUG] Slack trigger -- "Ignore bots" prop only ignores messages from Pipedream Bot

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2672]
The `ignoreBot` prop in the Slack trigger ignores messages sent via a Pipedream bot, but not messages from other bots like Zapier or Linear. 

![GIF 2022-04-21 at 10 17 17 AM](https://user-images.githubusercontent.com/20780753/164515433-3b4eeb06-303e-4a6f-ae70-29c6c6b05175.gif)

**Comment by dannyroosevelt** [comment]
@lcaresia You just spent a lot of time in the Slack code -- can you check this out when you get a chance?

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Slack_Test_Report_2672.pdf](https://github.com/PipedreamHQ/pipedream/files/8679140/Slack_Test_Report_2672.pdf)

**Comment by dannyroosevelt** [comment]
This is ready for release!
