### ISSUE TITLE
[FEATURE] In Editor v2, allow Deploy (override) without Test?

### ISSUE THREAD

**Issue by tekacs** [PipedreamHQ/pipedream#2676]
**Is your feature request related to a problem? Please describe.**
As it stands, making a change to previously-failed steps in the v2 editor enforce that you must Test the step before Deploy-ing it.

There exist a fair few cases in which running the Test is side-effecting and it's reasonably possible to isolate that the change that's been made to the workflow is reasonable (e.g. a small configuration change).

In this cases, the current workflow of hitting Test can sometimes create a small nuisance in the form of a side effect -- and sometimes create a roadblock, because the side effect in its final form (as you would push into 'production' use) would do something undesirable when Test was used.

**Describe the solution you'd like**
Could there be a dropdown or other similar override on the Deploy button, with an option to Deploy without Testing?

**Do you have a workaround?**
At the moment, I've been finding ways to neuter the effect of the flow whilst testing and then make a small change to get the workflow into working condition.

Some situations also seem to result in the workflow permitting no Test before Deploy and although I can sometimes recreate that, I can't do so reliably.

I think for one, if the workflow was 'last' in working condition, you can Deploy immediately without testing -- but if you put the workflow into a broken state, you _must_ test before hitting Deploy now, even if you permuted it back into a working state that you can see, you're not trusted to hit Deploy currently without first showing the step as green by testing it.

**Comment by dylburger** [comment]
@tekacs I completely hear you! We have heard this feedback consistently and are considering changes to this flow. We'll update this ticket when we do that.

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
