### ISSUE TITLE
[BUG] Jotform new submission source emitting duplicate events

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2679]
**Describe the bug**
The **Jotform - New Submission** source is emitting redundant multiple events.

**To Reproduce**

Create a new workflow with the new submission trigger, enter in a Jotform submission on the form and receive multiple events per submission:

<img width="474" alt="CleanShot 2022-04-22 at 11 28 59@2x" src="https://user-images.githubusercontent.com/2694734/164746160-c91725ca-2318-4e2d-b5a4-c5a4312c7498.png">

**Expected behavior**
One form submission should equal one workflow event.

## Bug Fix

Below is the PR to fix the bug:

https://github.com/PipedreamHQ/pipedream/pull/2678

**Comment by vellames-turing** [comment]
@ctrlaltdylan Looks like this is already fixed, right?

**Comment by vellames-turing** [comment]
@ctrlaltdylan

**Comment by ctrlaltdylan** [comment]
Sorry @vellames-turing my Github notifications are out of control.

I believe this is fixed, thanks for staying on top of this!

**Comment by vellames-turing** [comment]
np! tks!
