### ISSUE TITLE
[BUG] Can't copy text from Logs

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2680]
**Describe the bug**
In the V2 editor, if you console.log something a bit big, such that it can expand/collapse, and you try to select text from it so you can copy it to your clipboard, you can't because when you click and select, and then let go of the mouse button, the selection collapses.

https://user-images.githubusercontent.com/393660/164756099-8f46e836-d78f-4308-bd6d-31741943a758.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Current

**Comment by dylburger** [comment]
Thank you! Yes, this is a pain. I raised with the team and I'm hoping we can fix soon

**Comment by dylburger** [comment]
We've added a new **Copy** button on the right side of each `console.log` statement. If your statement produces multiple lines of output, lines (and all whitespace) should be retained on copy.

https://user-images.githubusercontent.com/242668/167995686-63878926-e065-4bad-bf8b-964e274e4454.mov
