### ISSUE TITLE
[ACTION] Add "Find or Create Record" support for Airtable

### ISSUE THREAD

**Issue by pkfrank** [PipedreamHQ/pipedream#2686]
**Is there a specific app this action is for?**
Airtable

**Request**
* Zapier allows you to "Find or Create Record" which essentially prevents duplicate entries
* It looks like Pipedream ships with the ability to "Create" OR "Update" (but no the integrated action that would allow you to easily do both)

<img width="920" alt="Screen Shot 2022-04-22 at 4 04 44 PM" src="https://user-images.githubusercontent.com/9434801/164815611-826d401e-9000-4263-bd26-1ec56c08c44e.png">
<img width="586" alt="Screen Shot 2022-04-22 at 4 02 10 PM" src="https://user-images.githubusercontent.com/9434801/164815621-be1683b4-d4aa-432c-a3ae-f065e8be7b9d.png">

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
