### ISSUE TITLE
[FEATURE] Extend Oauth Scope with Hubspot to Custom Objects

### ISSUE THREAD

**Issue by raphaelvarieras** [PipedreamHQ/pipedream#2689]
When using a bearer token with Hubspot, API calls into custom objects come back with error:

`This app hasn't been granted all required scopes to make this call. Read more about required scopes here: https://developers.hubspot.com/scopes.`

I've had to switch to API key requests in order to accomplish what I wanted with custom objects.

**Comment by dylburger** [comment]
@raphaelvarieras Do you happen to know which scope was required for your specific API request? Which endpoint were you using? Just want to make sure we add the correct one for you.

**Comment by raphaelvarieras** [comment]
I was merging custom objects, so using this specific endpoint:
`https://api.hubapi.com/crm/v3/objects/{my custom object id}/merge`

**Comment by dannyroosevelt** [comment]
Hi @raphaelvarieras sorry for the delay.

In looking through HubSpots's docs, it seems like we should have the write scopes enabled, but obviously something is not right. If go [here](https://developers.hubspot.com/docs/api/crm/crm-custom-objects), click on the "Objects" tab, then scroll down to the section, "Merge two objects with same type", you can see the scopes they're looking for.

Here are the scopes our app currently includes for all users:
```
business-intelligence
crm.objects.contacts.read
crm.objects.contacts.write
crm.import
forms-uploaded-files
forms
files
integration-sync
oauth
timeline
crm.objects.deals.write
crm.lists.read
crm.lists.write
```

As well as these optional scopes for users who have access:
```
automation
content
conversations.visitor_identification.tokens.create
cms.source_code.read_write
e-commerce
hubdb
sales-email-read
social
tickets
transactional-email
```

**Comment by raphaelvarieras** [comment]
No worries and thanks for looking into it. Happy to connect you with our CSM at Hubspot if you need clarifications on their docs. Alternatively, they also have a dev slack here: hubspotdev.slack.com

**Comment by dannyroosevelt** [comment]
Yea please feel free to connect me with your CSM there, happy to chat with them. If email is best, you can add me directly -- `danny@pipedream.com`. That Slack link looks like it only permits signing in for users who are already members of the Slack workspace, so I can't get in there.

**Comment by raphaelvarieras** [comment]
Done - and I think you can join the slack community here: https://developers.hubspot.com/slack

**Comment by dannyroosevelt** [comment]
@raphaelvarieras I got in touch with someone in their Slack and added the scopes I _think_ we need -- can you go ahead and give it a try?

Note that you'll need to re-authenticate by clicking the "Reconnect" button next to your HubSpot account provision, either within a workflow step or on pipedream.com/accounts.

**Comment by raphaelvarieras** [comment]
Confirmed.

I tested without reconnecting and still got the Forbidden error, then reconnected, confirmed on this screen:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/6558178/166796699-42f05f54-6467-47ad-ba9a-9fb11c9f8c63.png">

And then running the workflow again resulted in a 200.

Thanks!

**Comment by dannyroosevelt** [comment]
Nice! Glad we got it sorted out!
