### ISSUE TITLE
[APP] Loomio

### ISSUE THREAD

**Issue by Mause** [PipedreamHQ/pipedream#2707]
**Name of app / service**
Loomio

**Link to developer documentation**
https://www.loomio.org/help/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, I wish to create actions that use Loomio auth and integration without duplicating that for each action I write

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
 * Create Discussion
 * Create Poll

I'm happy to write these, just need the app available first

**Comment by dannyroosevelt** [comment]
Hi @Mause let us know if you're able to get your hands on any documentation and we'll happily check out if an integration might work, but without that we're unfortunately blocked on moving forward.

**Comment by sergioeliot2039** [comment]
@dannyroosevelt I just requested API access, documentation to Loomio -- hopefully they'll revert and unblock this integration.

**Comment by Mause** [comment]
Okay, looks like it is actually documented after all - https://github.com/loomio/loomio/blob/master/app/views/help/api.html.haml (not sure where this is hosted though)

**Comment by Mause** [comment]
Okay, the docs live here: https://www.loomio.org/help/api

**Comment by dannyroosevelt** [comment]
Perfect -- thanks, @Mause!

Here is a basic integration with Loomio:
https://pipedream.com/apps/loomio/

Let us know if you need help or guidance getting started with building out the actions!

**Comment by sergioeliot2039** [comment]
Thanks Mause, Danny!

Loomio team replied to my inquiry and provided this extra link of documentation,
https://help.loomio.com/en/user_manual/groups/integrations/api/
Perhaps it is helpful too.

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
