### ISSUE TITLE
Alpaca

### ISSUE THREAD

**Issue by agimsalija** [PipedreamHQ/pipedream#271]
**Name of app / service**
Alpaca

**Link to developer documentation**
https://alpaca.markets/docs/api-documentation/
https://github.com/alpacahq/alpaca-trade-api-js/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
View account data to get buying power and ensure account is active: https://alpaca.markets/docs/api-documentation/how-to/account/
Place an order: https://alpaca.markets/docs/api-documentation/api-v2/orders/#order-entity

**Comment by todsac** [comment]
@agimsalija - I have integrated alpaca.  can you confirm the integration works on your end?

**Comment by agimsalija** [comment]
@todsac - Yes I was able to auth alpaca thank you! Do you have some example of how I could print a quote to the console or make a trade based on a webhook with json payload?

**Comment by todsac** [comment]
There are no actions built out yet for Alpaca so no Alpaca specific examples. If you have a workflow in process and can't complete building out the actions you need, feel free to add me as a collaborator and I can help.  tod at pipedream.com.
