### ISSUE TITLE
AVM FRITZ!Box Tools issue in HA core 2022.4.7

### ISSUE THREAD

**Issue by pierpippo** [PipedreamHQ/pipedream#2717]
### Discussed in https://github.com/PipedreamHQ/pipedream/discussions/2716

<div type='discussions-op-text'>

<sup>Originally posted by **pierpippo** April 27, 2022</sup>
Hi, I upgrade to home Assistant Core 2022.4.7 but AVM FRITZ!Box Tools doesnt work. If I try to reinstall it I insert correct IP, User name and password but It says Unkown error and I can't install it.
How can i solve the issue?
Thx

Pierpippo</div>

**Comment by dylburger** [comment]
This looks like an issue with Home Assistant and not Pipedream - is that right? Please reach out to the Home Assistant team at https://www.home-assistant.io/
