### ISSUE TITLE
[FEATURE] Multiple Discord Event Channels

### ISSUE THREAD

**Issue by danthegoodman1** [PipedreamHQ/pipedream#272]
For the Discord event, instead of having a single channel, having multiple channels would be awesome so that we can listen for incoming messages from multiple channels.

**Comment by satgator03** [comment]
I agree would be a great enhancement to be able to send out to multiple discord channels at the same time.

**Comment by dylburger** [comment]
The Discord **New Messages in Channel** source now supports listening to _multiple_ channels:

<img width="730" alt="Screen Shot 2020-08-29 at 6 49 06 PM" src="https://user-images.githubusercontent.com/242668/91649409-a2414780-ea28-11ea-88de-ccaf7f4e2beb.png">

Let us know if you have any other suggested improvements for this source!

Closed by #380 .
