### ISSUE TITLE
[New components] Gorgias

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#2724]
App: `gorgias`
Docs: https://developers.gorgias.com/reference/introduction

### Triggers
- Ticket created
- Ticket updated
- Ticket message created

### Actions
 - Create ticket
 - List tickets
- Create customer 
- Retrieve a customer
- Update a customer

These are some lower priority ones that could potentially also be interesting: 
- Retrieve a (satisfaction) survey
- Create a macro
- Update a ticket

**Comment by dannyroosevelt** [comment]
This is ready for release!

**Comment by andrewjschuang** [comment]
@dannyroosevelt can you please approve the PR?
Thanks

**Comment by todsac** [comment]
@andrewjschuang - any reason these three actions were not included?

- Create customer
- Retrieve a customer
- Update a customer

**Comment by andrewjschuang** [comment]
> @andrewjschuang - any reason these three actions were not included?
> 
>     * Create customer
> 
>     * Retrieve a customer
> 
>     * Update a customer

@todsac nope, just thought not all of them needed to be included. Will work on them!

**Comment by todsac** [comment]
Gotcha.  This app is a bit unique as the company (Gorgias) submitted the list so they feel these are important.

**Comment by dannyroosevelt** [comment]
@andrewjschuang I created a new ticket to track these new actions: https://github.com/PipedreamHQ/pipedream/issues/2838
