### ISSUE TITLE
[stormglass.io]

### ISSUE THREAD

**Issue by chmr25** [PipedreamHQ/pipedream#2732]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @chmr25 let us know if you're able to get your hands on any documentation and we'll happily check out if an integration might work, but without that we're unfortunately blocked on moving forward.

**Comment by chmr25** [comment]
I guess I can configure it myself by sending a request in python. 
Thanks anyway, if i find something i will let you know :)

**Comment by sergioeliot2039** [comment]
I just googled and I think you mean stormglass that has this https://docs.stormglass.io/#/
is this is the integration you need?

**Comment by chmr25** [comment]
Yes.
But I can send my own request and explore your platform a bit more. I can come back if I find something else :smile:

**Comment by sergioeliot2039** [comment]
I had to ask the question -- sometimes we get spammy app request, or there is ambiguity with the app name that is requested.

**Comment by chmr25** [comment]
I understand! No worries!
