### ISSUE TITLE
[BUG] Can't copy code from the "view" of V2 workflows

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2733]
**Describe the bug**
If you are looking at a V2 workflow and are NOT in Edit mode, while you can see code, if you select and CTRL+C/CMD+C, it won't copy to the clipboard.

**Comment by zalmanlew** [comment]
Can confirm, was able to reproduce. You also don't have any right click options expected when copying text.

**Comment by ctrlaltdylan** [comment]
To add some more reproducible details to this card.

You must have a deployed workflow containing a code step. You open the **inspector** of the workflow, and you cannot use `CMD+A` to select the code contents of a code step nor can you use `CMD+C` to copy the manually selected contents to copy the code.

**Comment by dannyroosevelt** [comment]
Confirming this is now fixed in production!
