### ISSUE TITLE
[BUG] HTTP Trigger Response reverts after a deploy

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#2734]
**Describe the bug**
V2 editor - trigger is set to HTTP Request and the response is set to return static/200/204.
After deploying (and sometimes while editing) the workflow, the http response gets reset to "Return static..."

**To Reproduce**
1. Create a new V2 workflow
2. Set trigger as HTTP Request
3. Set response to `Return HTTP 204 No Content`
4. Add a Step
5. Choose any action ( I did Node.JS and selected `Hello World` example).
6. Hit Test and then Deploy
7. Edit the workflow again
8. Your HTTP Response has now been set to `Return a static response` with no status code, the setting for favicon is no longer set.

**Expected behavior**
The Response of the HTTP request should remain as I had set it before deploying

**Screenshots**

https://user-images.githubusercontent.com/35234925/166078260-f1bf550e-dbd5-4a85-babe-e2416255b46b.mp4

**Desktop:**
 - Chrome 100 on macOS

**Comment by dannyroosevelt** [comment]
Thanks for the details and video -- we will investigate!

**Comment by zalmanlew** [comment]
Just to add something I noticed, this happens as well when leaving to static response. Every time I open the workflow editor the status code is gone (and I need to enter it again).

**Comment by dannyroosevelt** [comment]
> Just to add something I noticed, this happens as well when leaving to static response. Every time I open the workflow editor the status code is gone (and I need to enter it again).

Yea thanks for the additional info. I was able to verify as well and we've added it to the team's backlog to address.

**Comment by dannyroosevelt** [comment]
@zalmanlew both of these issues should now be fixed! Please let me know if you run into either issue again.
