### ISSUE TITLE
[APP] Voice Monkey

### ISSUE THREAD

**Issue by traliotube** [PipedreamHQ/pipedream#2736]
**Name of app/service**

Voice Monkey

**Link to developer documentation**

https://voicemonkey.io/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Yes, it used to send announcements to Alexa, I don't have a workaround

**Are there specific actions or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

![image](https://user-images.githubusercontent.com/69894187/166090697-06adb45c-e9c4-48dd-803e-781bc09c8aec.png)
These are the actions in IFTTT pls add all possible actions

**Comment by dannyroosevelt** [comment]
Thanks for the request! FYI here is a basic integration with Voice Monkey:
https://pipedream.com/apps/voice_monkey/

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by traliotube** [comment]
hi, I don't know much of the code to make it myself, but I can help, I couldn't get their contact, but I found an API docs sheet: 
https://voicemonkey.io/docs
so i think you experts can do it.

Thanks!

**Comment by traliotube** [comment]
> Thanks for the request! FYI here is a basic integration with Voice Monkey: https://pipedream.com/apps/voice_monkey/

Oh, but I am not a js expert, and I know many using pipedream are not, in fact, pipedream is a free and better alternative to IFTTT. So most users, like me, might come from IFTTT

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
