### ISSUE TITLE
[APP]amzon

### ISSUE THREAD

**Issue by tarun20024** [PipedreamHQ/pipedream#2737]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @tarun20024 I tried looking for an app named "amzon" and I am unable to find any. For instance "amzon.com" redirects to Amazon, for which we have an integration, see it here: https://pipedream.com/apps/amazon amzon.com.mx redirects to a different random website each time you go to it. So I am unable to identify the app you need. 

Let us know if you're able to point us to the right app's website, and get your hands on any documentation and we'll happily check out if an integration might work, but without that we're unfortunately blocked on moving forward.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
