### ISSUE TITLE
[SOURCE] Google Classroom 2nd set of sources requested

### ISSUE THREAD

**Issue by oakrc** [PipedreamHQ/pipedream#2738]
**Name of app / service**
Google Classroom
**Link to developer documentation**
https://developers.google.com/classroom
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, I could not find any triggers for Google Classroom
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- New assignment created
- Assignment due date changed
- Assignment marked as done
- Assignment receives new private comment

**Comment by sergioeliot2039** [comment]
Previously 
* New assigment created
was requested on #2333 
Related: https://github.com/PipedreamHQ/pipedream/issues/2333
 This request adds up:
* Assignment due date changed
* Assignment marked as done
* Assignment receives new private comment

Perhaps we should close 2333 and let this issue 2738 overtake on it (?)

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
