### ISSUE TITLE
[ACTION] Data Store Actions

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2746]
**Is there a specific app this action is for?**
`data_stores`

 ### New actions
- List keys in Data Store: `await this.db.keys()`
- Delete all keys in a Data Store: `await this.db.clear()` (include a note about this being an irreversible change, so use with caution)
- Check existence of keys: `await this.db.has(key)` (returns true/false)

### Updates to existing actions
- Can we use async options now to fetch existing keys for the `add-update-record` action?
- Update `delete-record` action to use `await this.db.delete(key)` (and rename action "Delete single record"

**Comment by ctrlaltdylan** [comment]
Get multiple keys with one action possible?

**Comment by dannyroosevelt** [comment]
> Get multiple keys with one action possible?

We should be able to return multiple key-values in a single action, I don't see why not (cc @vellames-turing )

**Comment by ctrlaltdylan** [comment]
@vellames-turing sorry I wasn't clear enough.

I was hoping it would allow the user to define an array of keys, and then return the value of each corresponding key from that particular data store:

```javascript

{
  props: {
     keys: {
        type: 'string[]',
        description: 'List of keys to retrieve from the Data Store'
     }
  }
}
```

The `$return_value` would be an object with each key & value pair.

Does that help?

**Comment by dannyroosevelt** [comment]
This is ready for release!
