### ISSUE TITLE
[ACTION] Postmark - send an email with a template ID

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2747]
**Is there a specific app this action is for?**

Postmark

**Please provide a link to the relevant API docs for the specific service / operation.**

https://postmarkapp.com/developer/api/templates-api

Currently we only offer 1 action with Postmark, and it accepts a Text or HTML body.

Postmarks has a templating system, where we can instead expose data from the workflow to the templating system, so the HTML editing experience is in Postmark, and it's much more robust and extendable with Layouts.

**Comment by dannyroosevelt** [comment]
@ctrlaltdylan are there specific actions you'd want to see that you think make sense? If you have use cases in mind, feel free to call them out explicitly to make it easier for the dev to get started.

**Comment by ctrlaltdylan** [comment]
@dannyroosevelt updated the title of this issue to include the specific action name, but the URL in the body of my first comment links to the specific API endpoint that should be included in the action.

**Comment by dannyroosevelt** [comment]
Actually it looks like this will be resolved by https://github.com/PipedreamHQ/pipedream/issues/2747, so I'll close this ticket and we can track there

**Comment by ctrlaltdylan** [comment]
@dannyroosevelt awesome! I didn't notice the open PR my bad.

Here's the link to the PR in case future googlers end up here: https://github.com/PipedreamHQ/pipedream/issues/1527
