### ISSUE TITLE
[APP] stramlabs and OBS Studio

### ISSUE THREAD

**Issue by 1rforti** [PipedreamHQ/pipedream#2753]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @1rforti 

can you confirm if these are the apps you are looking to integrate?

**Comment by sergioeliot2039** [comment]
stramlabs  -- typo for streamlabs -- website: https://streamlabs.com/
OBS Studio -- website: https://obsproject.com
please

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
