### ISSUE TITLE
Twitter API cannot pull data from private accounts even if you have access to the private feed

### ISSUE THREAD

**Issue by satgator03** [PipedreamHQ/pipedream#276]
**Describe the bug**
The twitter API can pull just fine any public or your own tweets.  However, even though you have linked your twitter account with Pipedream's integration (via your twitter account); the API cannot access any private feeds you have security access to see.  This bug was confirmed on 07/28/2020 by Pravin from PD.  They are supposed to be working on it.

**Note from Slack:**
Pravin (Pipedream)  12 hours ago
hi - here's a quick update: I ran a few tests and I'm able to reproduce the issue you reported. My best theory at the moment is that the specific API we're using may not support retrieving protected tweets; i.e., the source is currently based on the standard search API, but we may need to migrate to the user timeline API. i'll follow up after running some more tests. thanks again for reporting the issue, and sorry for the inconvenience!

**To Reproduce**

**Expected behavior**
Normal public feeds can be accessed without any issues.  Cannot pull tweets from private accounts even though your linked twitter account has access to those feeds.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome [Version 84.0.4147.89 (Official Build) (64-bit)]
 - MS Edge (Version 84.0.522.44 (Official build) (64-bit))

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dylburger** [comment]
This has been resolved, thanks for raising.
