### ISSUE TITLE
[SOURCE] Twilio Inbound SMS

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#277]
I'd like an event source that emits new SMS messages sent to a Twilio phone number I own.

**Comment by DAVE4547** [comment]
Not sure if you have done this already but I think you can add a http trigger to your workflow and then add that endpoint somewhere in twilio, it should send message contents and other things like that as well.

I still like the idea of adding this as a trigger though.

**Comment by dylburger** [comment]
@DAVE4547 yeah, we actually already have this working internally using that exact method! Just polishing the source and should be shipping soon.

**Comment by dylburger** [comment]
We've shipped this source. [You can create it here](https://pipedream.com/sources?action=create&url=https%3A%2F%2Fgithub.com%2FPipedreamHQ%2Fpipedream%2Fblob%2Fmaster%2Fcomponents%2Ftwilio%2Fincoming-sms.js).
