### ISSUE TITLE
[APP] Google Play

### ISSUE THREAD

**Issue by andre-brunetta** [PipedreamHQ/pipedream#2771]
**Name of app / service**
Google Play

**Link to developer documentation**
https://developers.google.com/android-publisher/api-ref/rest/v3/reviews

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It's preventing

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Get reviews: https://developers.google.com/android-publisher/api-ref/rest/v3/reviews/list

**Necessary scope:
https://www.googleapis.com/auth/androidpublisher

**Comment by dannyroosevelt** [comment]
Thanks for submitting, @andre-brunetta. FYI Google has an incredibly onerous and lengthy approval process for configuring new apps and scopes, so we'll get this in the queue but it unfortunately will not be a fast turnaround.

**Comment by dannyroosevelt** [comment]
Another request submitted via https://github.com/PipedreamHQ/pipedream/issues/2815.

**Comment by sergio-eliot-rodriguez** [comment]
Submitted

**Comment by malexanderlim** [comment]
@andre-brunetta , this app has been added - is there a particular trigger or action that you're looking for here?
