### ISSUE TITLE
[APP] Shopmonkey

### ISSUE THREAD

**Issue by isaiahtaylor** [PipedreamHQ/pipedream#2776]
**Name of app / service**
Shopmonkey

**Link to developer documentation**
https://developer.shopmonkey.io/reference/authentication

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Manual auth / API usage

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I'm happy to build them.

**Comment by dannyroosevelt** [comment]
Same deal as Paytrace -- we weren't able to easily get access to the API (looks like Shopmonkey has to enable it for my account first), so please let me know if this actually works!
https://pipedream.com/apps/shopmonkey/

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
