### ISSUE TITLE
[APP] Delighted

### ISSUE THREAD

**Issue by isaiahtaylor** [PipedreamHQ/pipedream#2777]
**Name of app / service**
Delighted

**Link to developer documentation**
https://app.delighted.com/docs/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
This is an optimization, I'm getting by fine with Webhooks and JS.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Once again I'll build em.

**Comment by sergioeliot2039** [comment]
Hi @isaiahtaylor , there is an integration already done for Delighted, https://pipedream.com/apps/delighted

**Comment by isaiahtaylor** [comment]
Ah, yes there is. Thank you.
