### ISSUE TITLE
RASA

### ISSUE THREAD

**Issue by Jyoticaa** [PipedreamHQ/pipedream#2781]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
Thanks for the request. Is this the API you're looking for?
https://rasa.com/docs/rasa-x/pages/http-api#tag/

If not can you please provide some guidance?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
