### ISSUE TITLE
Triggers and actions for WooCommerce

### ISSUE THREAD

**Issue by doron580** [PipedreamHQ/pipedream#2783]
**WooCommerce**

**https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction**

**lack of support**

**Serch orders, Serch customers, Get new order notification**

**Comment by dannyroosevelt** [comment]
Thanks for the request, @doron580!

We have a set of triggers and actions for WooCommerce that we're about to publish: [here are the sources](https://github.com/PipedreamHQ/pipedream/issues/1030), [here are the actions](https://github.com/PipedreamHQ/pipedream/issues/1473).

Would you be open to trying them out and providing feedback? That way we can publish them asap.

**Comment by doron580** [comment]
Hi,

That sounds great.
Yes let me try them and give you feedback.

Thanks.

**Comment by doron580** [comment]
Thanks, I'll try them out and let you know.

I have another question.
Can you recommend to me a place where I can find Developers that know
Pipedream and write code in Node.js and Python?

Thanks.

**Comment by dannyroosevelt** [comment]
Absolutely -- I recommend posting some information on what you're looking for in our [community forum here](https://pipedream.com/community/c/hire-an-expert/13) -- that will also cross-post to our #jobs channel in our community Slack.

**Comment by doron580** [comment]
Awesome, thanks!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
