### ISSUE TITLE
[TRIGGER] Fix ZeroTier Online/Offline Trigger

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#2804]
The current ZeroTier trigger for node online/offline is using the `unique` dedupe parameter.

The issue with this is that it checks for unique values across the entire object. If another value like `clock` or `ipAssignments` change it will trigger the event again.

For these two triggers, it needs to be updated to only check if the `online` (boolean) state has changed - and ignore all the other keys.

**Comment by dannyroosevelt** [comment]
@zalmanlew thanks for submitting! The developer who did the original dev work on the other ZeroTier components is out for a bit, but we'll get this added to the queue.

**Comment by ctrlaltdylan** [comment]
Just to add more context on the bug.

The problem is that a `dedupe` strategy is being used for this source, but the built in dedupe strategies aren't quite suited for this type of problem.

I recommend using the `$.service.db` instead to keep track of each ZeroTier node and it's current status instead.

For example:

```javascript

const currentNodeStatus = this.service.db.get(node.id);

if(node.status != currentNodeStatus) {
   // emit event
   // update db as well:
   this.service.db.set(currentNodeStatus);
}

```

Please note, this is pseudocode, but the idea is that we emit events _only_ on node state changes.

**Comment by luancazarine** [comment]
I did several tests and I couldn't replicate this behavior.
the $emit id is based on nodeId and lastOnline(timestamp) so it is not duplicating

**Comment by zalmanlew** [comment]
@luancazarine the `lastOnline` timestamp can (and will be constantly updating) even though the `online` state hasn't changed from its previous state.

This means after some period of time it will emit a new event just from the `lastOnline` being updated, even if it didn't change from `online: true` to `online:false` (or vice-versa)

**Comment by luancazarine** [comment]
Do you know how long it takes to happen?
I have my node offline for more than 30 minutes and lastOnline remains the same

**Comment by zalmanlew** [comment]
@luancazarine that's because you have your node offline, I guess his is primarily an issue in reverse (as long as your node is ***online***, the `lastOnline` will constantly be updated with the ping time).

If it's going from offline > online then `lastOnline` wouldn't update, _however_ other fields can be updated (manually) and this _shouldn't_ fire the online event. Only the change of the `online` state should emit that event.

**Comment by luancazarine** [comment]
@zalmanlew 
ok, i understood what is happening.
whenever you update a node's information it is "restarted", so as soon as it comes online again, lastOnline updates.

should the trigger ignore this?
because if the trigger catches at the exact moment the node is "restarted" by some update, you will receive this event too

**Comment by zalmanlew** [comment]
@luancazarine I don't think this should trigger the node online/offline trigger. The only thing that should trigger the event is the state changing of the `online` key specifically (the other keys are irrelevant for these triggers).

#### Example 1 - Online
- **Previous state**: `online: false`
- **Current state**: `online: true`
- **Result**: this should trigger the `node-online` event

#### Example 2 - Offline
- **Previous state**: `online: true`
- **Current state**: `online: false`
- **Result**: this should trigger the `node-offline` event

#### Example 3 - Ignore
- **Previous state**: `online: true`
- **Current state**: `online: true`
- **Result**: this should not trigger any event as the online status hasn't changed.

---

The easiest way to test this is to leave a node online and running, it will currently keep firing online events, whereas it should only be emitting the online event if the previous state was offline (same goes for offline in vice-versa).

**Comment by michelle0927** [comment]
@luancazarine Can you comment with a link to the PR? Thanks!

**Comment by luancazarine** [comment]
> @luancazarine Can you comment with a link to the PR? Thanks!

Sorry, I moved the wrong task

**Comment by luancazarine** [comment]
@zalmanlew 
There is a problem with only validating by status and saving to compare. if the trigger gets offline, and the node switches to online and then to offline again before the next trigger event, it will receive offline again and you will not receive the event

**Comment by zalmanlew** [comment]
@luancazarine while that is true, I think that's why it depends how frequently you poll the data. 

It's worth noting that ZeroTier [considers](https://github.com/PipedreamHQ/pipedream/issues/2524#issuecomment-1111472548) the machine `online` if `lastOnline` is in the last 3 minutes. 
We can include this information in the description of the source.
