### ISSUE TITLE
[FEATURE] PostgreSQL actions should support optional `rejectUnauthorized` parameter

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#2808]
I need to set this as a user, so it should be an optional prop. See https://node-postgres.com/features/ssl

**Comment by GTFalcao** [comment]
The current PostgreSQL actions do not seem to use SSL in their connections, which would be a requirement for this `rejectUnauthorized` parameter. @michelle0927 might have more info on whether this can be implemented or was intentionally not added when first creating these actions.

https://github.com/PipedreamHQ/pipedream/blob/ebb632093a2010d7b839790b85098cb4603cc22b/components/postgresql/postgresql.app.mjs#L67-L70

**Comment by dannyroosevelt** [comment]
This is ready for release!
