### ISSUE TITLE
Apple / Google Playstore reviews

### ISSUE THREAD

**Issue by Sshuichi** [PipedreamHQ/pipedream#2815]
**Name of app / service**
Playstore / Appstore
**Link to developer documentation**
https://developers.google.com/android-publisher/api-ref/rest/v3/reviews
**Is lack of support preventing you from building workflows, or do you have a workaround?**
I think I can do something with Webhooks but would prefer if it's out of the box
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
When a review is updated or added

**Comment by dannyroosevelt** [comment]
@Sshuichi thank you for submitting the request! We're tracking this integration [here](https://github.com/PipedreamHQ/pipedream/issues/2771), so I'm going to close this ticket.

FYI Google has an incredibly onerous and lengthy approval process for configuring new apps and scopes, so we'll get this in the queue but it unfortunately will not be a fast turnaround.

**Comment by malexanderlim** [comment]
@asennoussi, Google Play has been integrated, you should now be able to list reviews once authenticated.
