### ISSUE TITLE
[BUG] Google Sheets - New Row Added - when the `oldRowCount` exceeds the current row count, we continue emitting the last row again and again

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#2818]
I was working with a customer who encountered a strange situation: in `common/new-row-added.mjs`, `this._getRowCount` returned 1051. But the sheet only had ~1020 entries. 

The `range` property emitted by the event source looked like this for these events: `Sheet!1050:1021`. We set `range` like so:

```javascript
const range = `${worksheetTitle}!${lowerBound}:${upperBound}`;
```

Therefore, it looks like the `lowerBound` exceeds the value of the `upperBound`.

I have not dug into the code deeply, so I don't have good logs on the condition under which this first started. But you should be able to get a component into this state by manually setting the row count for a specific worksheet using `this.db.set`, then add rows to a worksheet and see the "duplicate" event (with a different row number) being emitted.

**Comment by vellames-turing** [comment]
Humm, looks like the problem is more complex. Looks like be related with files with a large amount of rows. I have a spreadsheet with 20k rows and I was not even able to deploy the source

`
Error: Range ('pg4'!PG4) exceeds grid limits. Max rows: 24321, max columns: 26
    at Gaxios._request (/var/task/node_modules/gaxios/src/gaxios.ts:158:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async OAuth2Client.requestAsync (/var/task/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)
    at async Object.getSpreadsheetValues (file:///var/task/user/google_sheets/google_sheets.app.mjs:238:24)
    at async file:///var/task/user/google_sheets/google_sheets.app.mjs:299:32
    at async Promise.all (index 0)
    at async Object.getWorksheetRowCounts (file:///var/task/user/google_sheets/google_sheets.app.mjs:245:22)
    at async Object.takeSheetSnapshot (file:///var/task/user/google_sheets/sources/common/new-row-added.mjs:96:34)
    at async Object.deploy (file:///var/task/user/google_sheets/sources/common/http-based/base.mjs:55:7)
    at async /var/task/index.js:95:13
`

I will keep you up to date

**Comment by vellames-turing** [comment]
Looks like we have another bug, but this one looks like to be related to Google Sheets. I tested a spreadsheet where the page name was `pg4` and I had the previous error, so I found [this post](https://stackoverflow.com/questions/49821711/gspread-error-code-400-range-namename-exceeds-grid-limits). Looks like Google Sheets has some problems with numbers in the page name, I renamed the page from `pg4` to `pg` and it works. I would like to suggest we to open a new bug to take a look in this problem properly

**Comment by vellames-turing** [comment]
I was not able to reproduce it from a new spreadsheet, only changing the row counting directly from the code as you mentioned. The row count is updated using `getSpreadsheetValues` function which did not present any inconsistency during my tests. Probably we have a pretty specific case to trigger this bug.
As a solution, I added one new validation avoiding that the `newRowCount` be greater than the `upperBound`

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test Report
[Google_Sheet_2818.pdf](https://github.com/PipedreamHQ/pipedream/files/9003014/Google_Sheet_2818.pdf)

**Comment by dannyroosevelt** [comment]
This is ready for release!
