### ISSUE TITLE
[TRIGGER] Azure DevOps

### ISSUE THREAD

**Issue by StefanoTurrini** [PipedreamHQ/pipedream#282]
**Describe the event source. What app, what event?**
I need, when a particulary field of an Item in Azure DevOps is modified, to intercept the event and synchronize other Items follow inheritance tree... Do you think is it possible ? I can't find DevOps in the list of the sources... Thanks in advance
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by dylburger** [comment]
@StefanoTurrini we'll investigate adding Azure DevOps as an event source and will update this ticket accordingly. Thanks for raising the feature request!

**Comment by jverce** [comment]
Blocked by #304
