### ISSUE TITLE
[ACTION] RingCentral Download Call Recording

### ISSUE THREAD

**Issue by raphaelvarieras** [PipedreamHQ/pipedream#2835]
RingCentral

Download a Call Recording - based on the ContentUri returned by the "New Call Recording" trigger, it would be nice to be able to associate a download call recording action so that the file can downloaded and stored some other place without RingCentral authentication.

**Comment by dylburger** [comment]
Per our Slack conversation, it seems like we may need to add scopes

**Comment by dannyroosevelt** [comment]
The scopes issue is resolved.
