### ISSUE TITLE
[FEATURE] Cron expression failed to save

### ISSUE THREAD

**Issue by mc25573** [PipedreamHQ/pipedream#2845]
**Is your feature request related to a problem? Please describe.**
The RSS trigger does not show the cron expression I've previously entered while editing. If I save a cron expression and then later come back to edit the trigger, it just shows the default cron expression.

**Describe the solution you'd like**
 I would like the RSS trigger to save the cron expression that I've previously entered. 

**Do you have a workaround?**
I have to rewrite a whole new cron expression.

**Comment by dylburger** [comment]
@mc25573 Thanks for reporting. Can you clarify exactly when you're expecting the cron expression to persist? We do persist the expression if you exit the configuration and configure other parameters, then come back (see GIF below). And we should save the expression when you save the trigger.

The only case when we should change the cron expression is when you set another date option, e.g. when I set the timer to run monthly, that modified the schedule, so we changed the cron expression to match that.

![2022-06-01 21 42 55](https://user-images.githubusercontent.com/242668/171554525-62c854f0-0bdb-47ec-8f46-cbf25d4c4de6.gif)

**Comment by mc25573** [comment]
my issue was after finishing a workflow, if I went back to edit, the cron expression would just be the default one. it seems to be working now though.

**Comment by dylburger** [comment]
Great, thanks @mc25573 !
