### ISSUE TITLE
[BUG] Pipedream: 401 Unauthorized

### ISSUE THREAD

**Issue by isaiahtaylor** [PipedreamHQ/pipedream#2846]
**Describe the bug**
A Paytrace step is getting 401 Unauthorized today.

**To Reproduce**
Use the paytrace "run any code" step.

**Expected behavior**
Expected credentials to refresh :)

**Screenshots**
![image](https://user-images.githubusercontent.com/12981251/168151346-a6c264c6-341e-4075-a9c1-0fa3673b28aa.png)

**Additional context**

**Comment by isaiahtaylor** [comment]
Went into the accounts section and saw that the account was "unhealthy" so I reclicked the buttons. Now it works. So maybe this is also a feature request: when there's an error like that in a workflow, redirect to account section to get the account healthy?

**Comment by dylburger** [comment]
@isaiahtaylor yes, that's a great idea. Would you mind raising a separate feature request so we have that tracked?
