### ISSUE TITLE
Request to add [Action] Woocommerce: Update product(s) information

### ISSUE THREAD

**Issue by andr3selite** [PipedreamHQ/pipedream#2849]
It would be great if there could be an action to **update product(s) information** on **Woocommerce**.

https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
