### ISSUE TITLE
R

### ISSUE THREAD

**Issue by VI7EN** [PipedreamHQ/pipedream#2850]
**R**

**[Link to developer documentation](https://www.r-project.org/)**

**There is a possibility to connect R Scripts?**

Thank you very much in advance

Best regards

Viten

**Comment by dylburger** [comment]
Thanks for the request, @VI7EN ! I hear you and we are planning to extend runtime support for R in the future. We're actually tracking at #2163 if you don't mind following that ticket.

**Comment by VI7EN** [comment]
sounds good:) :) Good luck, it would be great!!
