### ISSUE TITLE
[BUG] Pipedream doesn't send verify email to my email (pipedream@web-bee.ru)

### ISSUE THREAD

**Issue by crutch12** [PipedreamHQ/pipedream#2851]
**Describe the bug**
Pipedream ignores email if it contains `pipedream`

**To Reproduce**
1. Go to https://pipedream.com/auth/signup
2. Pass Email that contains `pipedream` word
3. Account created
4. Check email inbox. There is no verify email! So you cannot add this member to organization, etc.
5. Try add pipedream@web-bee.ru to organization - and no email too.
6. Change email to test@web-bee.ru - and there is verify email, ok. Change email back to pipedream@web-bee.ru - no email.

**Expected behavior**
There is verify email

**Additional context**
I've tried another account - test@web-bee.ru - and everything works fine.

I think there is condition for `pipedream` word in passed email. It's really strange.

**Comment by dylburger** [comment]
@crutch12 Thanks for reaching out. I was not able to reproduce this. No matter where I added `pipedream` in email addresses, it worked correctly. We also don't have code that prohibits the use of `pipedream` in emails, and many users use that as a part of e.g. group addresses.

**Comment by crutch12** [comment]
@dylburger maybe you have a email validation (e.g. mailgun email validate)?
