### ISSUE TITLE
[BUG] Raindrop Parse HTML Bookmark File Bug

### ISSUE THREAD

**Issue by Hassan-Abbas-SQA** [PipedreamHQ/pipedream#2857]
**Describe the bug**
Action: Parse HTML Bookmark File | Extracts importable bookmarks from an HTML bookmark file

**To Reproduce**
1. Go to Parse HTML Bookmark File action
2. Enter Bookmarks url (either an HTML file from gdrive or deployed bookarms html page url)
3. Summary says Successfully parsed bookmark file where debug statusText shows unauthorised error

**Expected behavior**
Bookmarks should be added to raindrop.io

**Screenshots**
![image](https://user-images.githubusercontent.com/104946677/168468662-8f3bd501-b2b1-44ea-9cc8-fe2eef3c4d18.png)

**Comment by Hassan-Abbas-SQA** [comment]
@Giuan0 when i try to parse html file from local temp it showed this warning and also it didn’t showed the desired json output btw from url it worked fine without any warning

![image](https://user-images.githubusercontent.com/104946677/169164748-c0bd6d4a-09a6-450d-957f-ebc9ca1264f3.png)

**Comment by Hassan-Abbas-SQA** [comment]
@Giuan0 Bokkmark file url (gdrive shared file) it neither parsed the bookmark file nor showed any error (File is shared to everyone)

![image](https://user-images.githubusercontent.com/104946677/169165561-1bf02750-d062-4b44-9aab-c507817118c5.png)

**Comment by Giuan0** [comment]
@Hassan-Abbas-SQA you need to

> @Giuan0 Bookmark file url (gdrive shared file) it neither parsed the bookmark file nor showed any error (File is shared to everyone)
> 
> ![image](https://user-images.githubusercontent.com/104946677/169165561-1bf02750-d062-4b44-9aab-c507817118c5.png)

hey @Hassan-Abbas-SQA, you need to provide a URL with a valid bookmark file, the URL you're inputting on your tests is a document viewer.

**Comment by Giuan0** [comment]
> @Giuan0 when i try to parse html file from local temp it showed this warning and also it didn’t showed the desired json output btw from url it worked fine without any warning
> 
> ![image](https://user-images.githubusercontent.com/104946677/169164748-c0bd6d4a-09a6-450d-957f-ebc9ca1264f3.png)

Could reproduce this scenario when inputting a file that doesn't exist, this action is now checking the file before proceeding with its execution.

**Comment by dannyroosevelt** [comment]
This is ready for release!
