### ISSUE TITLE
[BUG] SyntaxError: Unexpected token '{' when sending Slack message using "```" (code block)

### ISSUE THREAD

**Issue by Vadorequest** [PipedreamHQ/pipedream#2858]
**Describe the bug**
Using \`\`\` block generates a bug in Pipedream, although this is valid for code blocks.

\`\`\`
{{steps.trigger.event.fields.uxGlobalFeedbackDetails}}
\`\`\`

Yields:
![image](https://user-images.githubusercontent.com/3807458/168479495-52b1308b-a736-4080-b342-e21ce08a05ec.png)

```
SyntaxError: Unexpected token '{'
    at _pd_deep_evaluate (/var/task/params_evaluator.js:63:29)
    at MessagePort.<anonymous> (/var/task/params_evaluator.js:11:9)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
```

**To Reproduce**
Send a Slack message using block code.

\`\`\`
{{steps.trigger.event.fields.uxGlobalFeedbackDetails}}
\`\`\`

**Expected behavior**
It shouldn't crash, it should work as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/3807458/168479566-9df22c0b-d798-401c-9023-55b8698f44f4.png)

![image](https://user-images.githubusercontent.com/3807458/168479575-9e6e1a6a-1b9e-4410-8ebf-14418f8bb4fc.png)

**Comment by zalmanlew** [comment]
@Vadorequest this is because it parses the string as JS, you just need to escape the backtick symbol (<code>`</code>).

Your codeblock within **Text** should look like this
```
\`\`\`
((steps.trigger.event.fields.uxGlobalFeedbackDetails})
\`\`\`
```

**Comment by Vadorequest** [comment]
Thanks!

Eventually, I noticed PipeDream didn't fetch more than 200 fields from Airtable (I have 350+ in a single table) so using it for this use case is not possible.
