### ISSUE TITLE
[BUG] data_store returning null

### ISSUE THREAD

**Issue by Ghryphen** [PipedreamHQ/pipedream#2865]
**Describe the bug**
Im my project, calling this.data_store is returning null. When attempting to call a method on the data_store such as .get, .has, .set it is returning an error Cannot read property '[get/has/set]' of null

I created a new test workflow that uses the most basic data_store usage in order to test to make sure it's not something to do with my workflow. This issue seems to have just started today.

**To Reproduce**
Following the most basic usage as described in the documentation https://pipedream.com/docs/code/nodejs/using-data-stores/#using-the-data-store

1. Create a node.js workflow
2. Add a data_store property
3. Assign a data_store to the configuration
4. Reference this.data_store in the worlflow

**Expected behavior**
this.data returns datastore object in order to apply get/has/set etc

**Screenshots**
![2022-05-16_145031](https://user-images.githubusercontent.com/128811/168688828-1a01973a-ffcc-48cd-85d3-61fffe1c689b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 101
 - 
**Additional context**
Not sure if it works to share a Workflow, but here is the link https://pipedream.com/@RoanYonks/datastore-test-p_6lCL2dJ/build

**Comment by dylburger** [comment]
Thanks for reporting @Ghryphen . Validated and we're working to fix.

**Comment by SuperFluffy** [comment]
I have encountered the same thing in an action. This issue was closed, but is a fix available?

**Comment by dannyroosevelt** [comment]
> I have encountered the same thing in an action. This issue was closed, but was a fix merged?

@SuperFluffy Can you provide more details? Which action are you using, and what is the error you're seeing?

**Comment by SuperFluffy** [comment]
> @SuperFluffy Can you provide more details? Which action are you using, and what is the error you're seeing?

Apologies. It's eerily similar to what OP posted, so I didn't provide extra info. But I think it fits in this issue report. If you prefer for me to open a new one, I can do that.

This is the MWE I made:

```javascript
export default {
  name: "MWE data store broken",
  version: "0.0.1",
  key: "mew-data-store-broken",
  description: "",
  props: {
    data: "$.service.db",
  },
  type: "action",
  methods: {},
  async run({ $ }) {
    const newData = "hello world";
    const oldData = await this.data.get('data');

    if (oldData === newData) {
      return false;
    } else {
      await this.data.set('data', newData);
      return true;
    }
  },
};
```
This is the ID it received after deploying it to PD:
```sh
❯ pd publish mwe.mjs
sc_pMi0ejQ MWE data store broken                    0.0.1    1 second ago         mew-data-store-broken
```
And this is the error that pipedreams UI reports:
```
TypeError

Cannot read property 'get' of null
Details

    at Object.run (file:///tmp/__pdg__/dist/code/25950afc7ffbc47769afaa54c830a26fe7c4234bea93be1165a72beb7dc97c65/component.mjs:13:37)
    at global.executeComponent (/var/task/launch_worker.js:142:53)
    at MessagePort.messageHandler (/var/task/launch_worker.js:614:28)
```
A screenshot is attached.

![image](https://user-images.githubusercontent.com/701177/186620412-204ee426-45c4-4023-95b0-9dd34026e4a1.png)

**Comment by js07** [comment]
Hi @SuperFluffy. I think the `type` for your data store prop (`data`) should be [`data_store`](https://pipedream.com/docs/code/nodejs/using-data-stores/#using-data-stores) rather than `$.service.db`, which is used to maintain state in [sources](https://pipedream.com/docs/sources/#sources).

```js
  props: {
    data: { type: "data_store" }
  },
```

**Comment by dannyroosevelt** [comment]
> @js07 Thank you for helping. :-)
> 
> I was looking at this document: https://pipedream.com/docs/components/api/#props (bad anchor, if you scroll down or search for `$.service.db`, you can find that (at least according to the docs) it should be supported in actions.
> 
> I figure the docs are wrong?

Good catch @js07 and yes good catch @SuperFluffy! I am updating that typo now.
