### ISSUE TITLE
[BUG] AIRTABLE PLUGIN - @pipedreamhq/platform@latest' is not in the npm registry

### ISSUE THREAD

**Issue by mrvasilyev** [PipedreamHQ/pipedream#287]
**Describe the bug**
In my workflow I use the Airtable plugin
I try start my workflow and get error ''@pipedreamhq/platform@latest' is not in the npm registry"
When I turn off Airtable steps everything works fine! 

I guess problem in this line of code
return await require("@pipedreamhq/platform").axios(this, config)

I found package in the npm gegistry 
0.8.1 latest
https://www.npmjs.com/package/@pipedreamhq/platform

**Comment by dylburger** [comment]
@mrvasilyev this was related to an [npm outage](https://status.npmjs.org/incidents/cksjqc1w11v5) that has since been resolved. This should now work as expected - let me know if you're still seeing issues.
