### ISSUE TITLE
[Refactor] Clearbit Actions

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2874]
**Is there a specific app this action is for?**
`clearbit`

**Please provide a link to the relevant API docs for the specific service / operation.**
https://dashboard.clearbit.com/docs#enrichment-api-company-api-domain-lookup

Clearbit currently returns a 404 when no records are found. Can we catch this case and add a prop that lets the user decide whether they want to handle this as an error or not? For example:
```
errorIfNoRecords: {
  type: "boolean",
  label: "Handle lack of records found as an error?",
  description: "Defaults to `false`. If no records are found, the step will still be considered a success. If `false`, the step will return an error and workflow execution will stop."
  optional: true,
  default: false
}
```

Please also add a `$summary` message and remove the `// legacy hash_id` comment at the top of each action once the refactor is complete.

**Comment by vellames-turing** [comment]
@dannyroosevelt I will refactor all other actions in order to standardize these actions. Sounds good?

**Comment by vellames-turing** [comment]
@dannyroosevelt I am moving this to review so we can speed up the process. The code is done, I just cant test it right now.

**Comment by andrewjschuang** [comment]
@vellames-turing can you link the PR here please?

**Comment by vellames-turing** [comment]
Sorry, done

**Comment by dannyroosevelt** [comment]
This is ready for release!
