### ISSUE TITLE
[BUG] Unlinking one auth source unlinks another auth source

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#288]
**Describe the bug**
If a workflow has more than one source and you unlink one, the labels get messed up.

**To Reproduce**
I have two auth sources (Postgres:"lacomunidad" and SSH:"vps2"). Here I am unlinking the Postgres one but it's the SSH one that gets unlinked (and the Postgres one gets the SSH label)
![Aug-06-2020 13-00-17](https://user-images.githubusercontent.com/27538/89524409-d12b1b80-d7e4-11ea-8c1b-b4c37ac77e0f.gif)

**Expected behavior**
The Postgres source gets unlinked.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 10.15.6
 - Browser [e.g. chrome, safari] 84.0.4147.105 (Official Build) (64-bit)

**Comment by dylburger** [comment]
@nachocab confirmed, we'll get a fix out for this ASAP.

**Comment by dylburger** [comment]
@nachocab this should be fixed now, let me know if you're still seeing any issues related to connected accounts.
