### ISSUE TITLE
[APP]whatsapp.com

### ISSUE THREAD

**Issue by Ranked99** [PipedreamHQ/pipedream#2883]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @Ranked99 , there is an integration already done for WhatsApp, https://pipedream.com/apps/chat-api-for-whatsapp
Chat API the official WhatsApp API

For WhatsApp actions, would you mind following this issue? https://github.com/PipedreamHQ/pipedream/issues/1496
If the component you are looking for is not contemplated, feel free to create another issue.
