### ISSUE TITLE
[SOURCE] MAUTIC TRIGGER SETTING

### ISSUE THREAD

**Issue by ahmadzaki1** [PipedreamHQ/pipedream#2890]
how to add a mautic event trigger in pipedream?

can anyone help me

**Comment by sergioeliot2039** [comment]
Hi @ahmadzaki1 , thanks for your interest.

It the depends on the trigger you are trying to build.

Can you let us know what is the functionality you are looking for?
For instance, on which Mautic events should the trigger react to?
Some triggers are http based, for this type, triggers are instant and are notified by Mautic to Pipedream via webhooks, take a look [Available webhook actions](https://developer.mautic.org/#available-webhook-actions)
Other triggers are timer based. These type of triggers are created by polling the Mautic API as per trigger developer time interval. Pipedream will trigger any new data polled from the API on a cycle every time interval.

Please check the relevant [Sources](https://pipedream.com/docs/sources/#overview) documentation.

If you have any doubts or questions, let us know and we will be happy to help.

Finally, once you review all this, can you please let us know which triggers (aka sources) are you trying to build?
We usually name triggers as in the following examples:
New User Subscribed
New Message in Channel
New Branch
and so on.

**Comment by ahmadzaki1** [comment]
thank you for your response.

The response or trigger that I want to build is when someone fills in their name and email on the Mautic form, it will send a notification that someone has filled out the form to the Telegram group.

New User Subscribed with message format:

Name, email, filled form, and time of submitting the form to the group via telegram bot.

It's just that I'm still a bit confused about how to connect the Mautic trigger and the pipedream, because previously I only used a webhook and a few settings worked (using a service similar to Z*p**r)

for pipedream I haven't found a way, I mean what are the initial steps to connect

thank you

**Comment by ahmadzaki1** [comment]
Hello

Thank you for replying to your message.

I tried yesterday with http trigger and mautic webhook , and it worked, great.

thanks for the help sir @dannyroosevelt and sir @sergioeliot2039
