### ISSUE TITLE
[BUG] Incorrect Zoho API endpoint URL when using an EU account

### ISSUE THREAD

**Issue by VadimChernik** [PipedreamHQ/pipedream#2892]
**Describe the bug**
I've gotten an error when tried create new Deal in Zoho CRM.
Code in the response: INVALID_TOKEN.
But after reviewing the sent request, I found that it uses **.com** in the requested URL - https://www.zohoapis.com/crm/v2/Deals
I have encountered a similar problem before. For EU accounts you must use **.eu** in the requested URL.

**Screenshots**
![image](https://user-images.githubusercontent.com/25364834/169341893-fd534ade-d937-4a20-8497-ed7fbddd59ec.png)
![image](https://user-images.githubusercontent.com/25364834/169342015-d8a75457-5e1c-46b1-967e-2dd9ef05cbf5.png)

**Comment by dannyroosevelt** [comment]
Hey @VadimChernik you can most likely fix this issue if you re-connect your Zoho CRM account. You can either open the a specific step and click on the selected account then "Connect new account", or go to https://pipedream.com/accounts, then "Connect an app" and go through the authentication flow.

The first step of that process will ask you to specify the base URI depending on your region. 
![image](https://user-images.githubusercontent.com/20780753/169354072-73d593d4-3726-4160-b93a-abacdc57d80b.png)

**Comment by VadimChernik** [comment]
Hi @dannyroosevelt. Thanks for the quick reply.

I've done it on the first step.
![image](https://user-images.githubusercontent.com/25364834/169355373-05e01ca3-80b1-4498-a5f2-007b137a95c4.png)
Maybe .eu is used for token updates and .com is used for requests?

I use a .com account in another workflow and everything works good.

**Comment by dannyroosevelt** [comment]
Can you confirm if you're using a built-in action or a code step? If an action, can you confirm which one so we can check it out?

**Comment by VadimChernik** [comment]
I'm using a built-in action - Create Object
![image](https://user-images.githubusercontent.com/25364834/169364688-ec267d69-b3ce-4fff-ac0a-a60947e96092.png)

**Comment by dannyroosevelt** [comment]
Ah okay, I just confirmed that is indeed a bug -- your suspicion is essentially correct. We're [tracking this here](https://github.com/PipedreamHQ/pipedream/issues/2894) and someone from the team should be able to get this fixed soon. Feel free to subscribe to that ticket and you'll get notified when we ship a fix!

**Comment by dannyroosevelt** [comment]
FYI @VadimChernik this should be fixed! Please make sure to update the Zoho CRM action you're using and let me know if this resolves your issue!

**Comment by VadimChernik** [comment]
Hi @dannyroosevelt, 

Thanks for the update.

I've created the connection from scratch, but I got the same result - Invalid Token.
It looks like the request URL hasn't changed.
![image](https://user-images.githubusercontent.com/25364834/170331065-8eb2eb35-03d3-4278-9e42-d4c615ca7bfc.png)

**Comment by dannyroosevelt** [comment]
Ah I see what happened -- we published the fix to most of the other Zoho CRM actions, but missed this one 🤦🏻‍♂️

I just patched the remaining actions -- can you update the action and try again?
![image](https://user-images.githubusercontent.com/20780753/170338009-17c5231a-e184-48f8-a635-031ea1bba8d7.png)

**Comment by VadimChernik** [comment]
Yeah, it worked.
![image](https://user-images.githubusercontent.com/25364834/170339356-b8b7bf68-75cc-405d-8eb7-eddc883e5625.png)

Thanks :thumbsup:
