### ISSUE TITLE
[APP] WhatsApp official Cloud API

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2896]
WhatsApp just launched their official API:
https://developers.facebook.com/docs/whatsapp/cloud-api/

This is blocked on integrating with Meta's Graph API.

**Comment by LucBerge** [comment]
I guess this is a highly required feature for pipedream. I don't understand why it is blocked ?

**Comment by sergioeliot2039** [comment]
> I guess this is a highly required feature for pipedream. I don't understand why it is blocked ?

@lcaresia question, for context, following up the link that Danny Roosevelt provided

> At this time, the platform is not open to those developing on behalf of clients. If you’re developing on behalf of another business, click [here](https://l.facebook.com/l.php?u=https%3A%2F%2Fbusiness.whatsapp.com%2Flearn-more&h=AT1PvqS9qos2KzsX5fPzqihyQsUarICPwdS4wqqx9KfKmHg2e9ovRVwDwZWDkOmUFXZ9l8WXfouCaX2kKkN56nATKYoM5Dzc6BmMmQtyt1PDU2Zeg7zThuuF2t_4nKhc_lJk6w).

This nice note is take from [Get Started With the WhatsApp Business Cloud API](https://developers.facebook.com/docs/whatsapp/cloud-api/get-started)

**Comment by lcaresia** [comment]
@sergioeliot2039 Is need an approved by Meta Whatsapp Business number, besides is necessary create the app yet.

**Comment by sergio-eliot-rodriguez** [comment]
Looks like this is completed finally: https://pipedream.com/apps/whatsapp-business
