### ISSUE TITLE
[APP] Need additional scopes for Jira

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2897]
A user has requested that we add the `write:board-scope:jira-software` scope to our Jira integration.

**Comment by feyzullah** [comment]
When adding that, it would be great if the scopes in [this comment](https://github.com/PipedreamHQ/pipedream/pull/2618#issuecomment-1109863093) are also added

**Comment by dannyroosevelt** [comment]
Added `write:board-scope:jira-software`.

Re: Feyzo's comment, we modified the scope of the work for that ticket to not require those additional scopes.
