### ISSUE TITLE
[APP] PixieBrix

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#2908]
**Name of app / service**
PixieBrix

**Link to developer documentation**
https://docs.pixiebrix.com/developer-guide

**Is lack of support preventing you from building workflows, or do you have a workaround?**
https://zapier.com/apps/zapier-chrome-extension/integrations
https://community.zapier.com/product-updates/introducing-the-updated-zapier-chrome-extension-7104

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
https://www.pixiebrix.com/marketplace/3e3a1b31-f927-4c93-9c35-40121a6ee5c6/

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
PixieBrix has been integrated https://pipedream.com/apps/pixiebrix?via=go

Please follow https://github.com/PipedreamHQ/pipedream/issues/10838 for PixieBrix component development progress.
