### ISSUE TITLE
Review modification of Microsoft API Graph permissions (specifically Calendar)

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#291]
Currently Pipedream supports: `User.Read, email, offline_access, openid, profile, Files.Read, Files.Read.All, Files.ReadWrite` . But I need Calendar permission for my steps. So, I'm thinking why not enable all of them.

_Originally posted by @ni554n in https://github.com/PipedreamHQ/pipedream/discussions/290_

**Comment by todsac** [comment]
I added all the calendar scopes.  @ni554n - please let us know if you have any issues.

**Comment by todsac** [comment]
FYI - you should re-authenticate if you have already authenticated with Microsoft Graph API.
