### ISSUE TITLE
[FEATURE] - Improvements to attachments

### ISSUE THREAD

**Issue by douglassjohnandrew** [PipedreamHQ/pipedream#2914]
**Is your feature request related to a problem? Please describe.**

The current attachments feature is good, but there's a few enhancements that I think could help improve the experience. The main inconvenience I'm facing is that when I upload a file with the same filename, I'm thinking that it'll be overwritten, but the file appears twice in the attachments list. I know that internally the file has been overwritten, but if I have to upload several changes to the same file, the attachments list would become cluttered with the same filename many times.

![image](https://user-images.githubusercontent.com/43791523/169636112-a6e351b2-72d5-4588-9423-5fe3bd45b8d6.png)

More importantly though, if a workflow requires a lot of large attachments for whatever reason, the UI doesn't provide an option to delete files, so we'd soon reach the 200MB limit with no quick option to clear files to free up MBs

**Describe the solution you'd like.**

<p>The solution I'd like is the first two items in the following list. The last two items are much more involved than the first two items, and a bit off topic, but I just threw them in there for fun because I think they would be cool</p>

- When uploading & overwriting an existing attachment, don't duplicate the filename
- Support for deleting attachments using the UI
- The ability to open and view text files' contents in a new browser tab would be incredibly convenient
- Support for global-level attachments. For example, if I had an HTML email template that several workflows needed to use, it would be really neat to have each automation read the global attachment. Then if we needed to change the template (or any other reusable file) we could just upload and overwrite it

**Comment by dylburger** [comment]
Thank you very much for the feedback, @douglassjohnandrew . We're tracking attachment deletion at #1246, and I shared the rest of the feedback with the team.

**Comment by dylburger** [comment]
Tracking duplicate attachment filenames at #1245

**Comment by dylburger** [comment]
@douglassjohnandrew re: this feedback:

> Support for global-level attachments. For example, if I had an HTML email template that several workflows needed to use, it would be really neat to have each automation read the global attachment

[Data stores](https://pipedream.com/docs/data-stores/) let you save any JSON-serializable data (like HTML) that you can access and modify across workflows. Have you tried that as a solution?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by douglassjohnandrew** [comment]
Apologies for the late response, I don't know why Github doesn't inform me when someone comments on my issue. Your data stores solution would work great for me, I would have never thought of that myself!

It's really kind of incredible that Pipedream/you let us provide feedback like this, and it's very much appreciated. Keep doing what you do!
