### ISSUE TITLE
[APP] Generic OAuth2 Client Credentials Flow

### ISSUE THREAD

**Issue by jimblizz** [PipedreamHQ/pipedream#2917]
**Name of app / service**
Any service using standards compliant OAuth2 client credentials flow for authentication

**Link to developer documentation**
N/A

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It seems to me that if you were to provide a generic "OAuth2 Client Credentials" app that let you pass the following props/data, you could have Pipedream generically manage auth for thousands of generic APIs without needing a specific implementation for each. 

Props:
- Client ID
- Client Secret
- Authorise endpoint URL
- Token endpoint URL

Pipedream would then manage auth, including token refresh as required, and allow the user to pass to use the resulting token in their custom action code (or pass it as a header with an HTTP request).

This would be valuable for Pipedream users that want to write actions that talk to proprietary or commercial APIs where it is not possible for Pipedream to obtain an account for testing - such as #2915 and #2916 

You could also almost see this as another option in the auth options you have already for HTTP requests (Basic, digest, etc)

**Comment by dannyroosevelt** [comment]
This is an interesting and creative ID that I believe we've discussed in the past. I'll definitely assess the feasibility and identify what work would need to be done in order for us to enable a solution like this.

**Comment by jimblizz** [comment]
It looks like your integration for "Quipu" uses the client credentials flow, the only difference would be is that you're letting your users supply custom tokens and authorize endpoints so that it can be used generically. This opens up access not only these ones I've requested support for, but any and all private APIs that use this quite common authentication method.

It seems to me that you could approach this in a few ways:

1. As its own action step that when used will export a currently valid token for subsequent actions to use, i.e. an HTTP action could then use it by passing it as an authentication header.
2. As simply a generic "app" so that users can use it to build custom actions themselves on top of it.
3. As an extra auth header option in the generic HTTP request action.

It feels to me that one of the first two would be an easy win.

In theory, once you have the client id, secret, and the URLs for the endpoints, the rest should be standardised. Things such as knowing when to use the refresh token can be done based on the expiry each service provides. I assume your existing managed auth already handles this automatically.

**Comment by jimblizz** [comment]
I've done some playing around here and realised that the client credentials flow doesn't handle refreshing anyway, so really I can produce option 1 here as a custom action. I have done so and included it below. This works for me testing against an Auth0 account.

You are free to use this code if you want to expand it to something nicer.

```
import axios from "axios";

export default {
    name: "OAuth2 Client Credentials",
    description: "This is a naive exchange of credentials for an token",
    key: "generic_oauth2_client_credentials",
    version: "0.0.7",
    type: "action",
    props: {
        tokenUrl: {
            type: "string",
            label: "Token URL",
            description: "The URL of the OAuth2 Token URL (usually https://domain/oauth/token)",
            optional: false,
        },
        clientId: {
            type: "string",
            label: "Client ID",
            optional: false,
        },
        clientSecret: {
            type: "string",
            label: "Client Secret",
            optional: false,
        },
        audience: {
            type: "string",
            label: "OAuth Audience (optional)",
            optional: true,
            default: "https://some-api.com",
        },
        idParamName: {
            type: "string",
            label: "Client ID parameter name",
            optional: true,
            default: "client_id"
        },
        secretParamName: {
            type: "string",
            label: "Client Secret parameter name",
            optional: true,
            default: "client_secret"
        }
    },
    async run() {
        const payload = {
            'grant_type': 'client_credentials',
        };

        payload[this.idParamName] = this.clientId;
        payload[this.secretParamName] = this.clientSecret;

        if (this.audience.length > 0) {
            payload.audience = this.audience;
        }

        const res = await axios.post(this.tokenUrl, payload);

        console.log(res.status);
        console.log(res.data);

        // TODO: Error handling here

        return res.data;
    },
}

```

**Comment by jimblizz** [comment]
One possible improvement would be to use data stores to cache the resulting token until its expiry.

**Comment by dylburger** [comment]
@jimblizz Totally makes sense. We're tracking at #163 if you'd like to follow that, and I've linked to this ticket to make sure we handle the Client Credentials flow (which we should implicitly).

**Comment by tomngo** [comment]
I think it would be to everyone's advantage to let us follow a sequence like this:

1. We use a generic OAuth2 connector to connect to a third-party system of our choice—in our case, FranConnect. (We do it at our own speed, and Pipedream incurs no labor cost.)

2. We submit our known good OAuth2 connector to the community, and Pipedream staff uses that as a starting point for a FranConnect connector that anyone can use. (Pipedream still gets to add FranConnect to the list of 2,200+.)

Would that be a win-win?

**Comment by dannyroosevelt** [comment]
Hey @tomngo, that's definitely a win-win, and it's on our roadmap! For FranConnect specifically, I just kicked off the process with their team and will track progress in [this ticket](https://github.com/PipedreamHQ/pipedream/issues/14215) that you submitted.

> I think it would be to everyone's advantage to let us follow a sequence like this:
> 
> 1. We use a generic OAuth2 connector to connect to a third-party system of our choice—in our case, FranConnect. (We do it at our own speed, and Pipedream incurs no labor cost.)
> 2. We submit our known good OAuth2 connector to the community, and Pipedream staff uses that as a starting point for a FranConnect connector that anyone can use. (Pipedream still gets to add FranConnect to the list of 2,200+.)
> 
> Would that be a win-win?
