### ISSUE TITLE
[APP] Semble

### ISSUE THREAD

**Issue by jimblizz** [PipedreamHQ/pipedream#2918]
**Name of app / service**
Heydoc

**Link to developer documentation**
http://docs.heydoc.co.uk.s3-website.eu-west-2.amazonaws.com/
https://www.heydoc.co.uk/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
We have not started our build yet, but this is one of the first services we'll need to connect to.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
The catch with this service is that you must exchange the API key and password for a 12-hour time-limited token and pass that as a header on each request.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Lookslike Heydoc was rebranded to Semble

**Comment by sergio-eliot-rodriguez** [comment]
The website redirects to https://www.semble.io/
Developer docs to https://docs.semble.io/

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
14 days follow up

**Comment by malexanderlim** [comment]
@jimblizz , are you still looking for this integration? If so, could you share your name/company name so that we can let the Semble team know, as they're looking to know who our mutual customer is.

**Comment by jimblizz** [comment]
@malexanderlim I'm afraid not, in the end, we dropped the idea of using Pipedream and built our own integration to get things moving. I've since moved on from the agency, so I probably shouldn't comment on the clients/companies involved, sorry.

**Comment by malexanderlim** [comment]
No problem. I'll close this request for now, thank you for letting me know.

**Comment by sergio-eliot-rodriguez** [comment]
14 days follow up

**Comment by sergio-eliot-rodriguez** [comment]
1 month follow up
