### ISSUE TITLE
[APP] ZeroBounce

### ISSUE THREAD

**Issue by raphaelvarieras** [PipedreamHQ/pipedream#2919]
ZeroBounce

**Link to developer documentation**
https://www.zerobounce.net/docs/email-validation-api-quickstart#validate_emails__v2__

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I do, I've used the following:
```
import axios from "axios"

export default defineComponent({
  async run({ steps, $ }) {
    const { data } = await axios({
      method: "GET",
      url: `https://api.zerobounce.net/v2/validate/?api_key=${process.env.ZEROBOUNCE_API_KEY}`
        + `&email=${steps.trigger.event.email}&ip_address=`,
    })
    let zb_st = data.status
    if (zb_st == 'invalid' || zb_st == 'spamtrap' || zb_st == 'abuse' || zb_st == 'do_not_mail') {
      $.flow.exit(`Email is ${zb_st} - ending workflow early`)
    } else {
        $.export(`Email is ${zb_st} - continuing workflow`)
    }
  },
})
```

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Actions:
- validate single email
- validate email batch

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there @dylburger 
Long time!
ZeroBounce has been previously integrated: https://pipedream.com/apps/zerobounce

Please have a look and let us know if there is any feedback.
Thanks,
Sergio

**Comment by sergio-eliot-rodriguez** [comment]
We're tracking components at https://github.com/PipedreamHQ/pipedream/issues/6429
