### ISSUE TITLE
[FEATURE] I'd like the workflow UI to autosave changes I've made to a workflow

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#292]

**Comment by nachocab** [comment]
The main goal is for the UI to prevent me from losing data.

Let's say I have a complex workflow with multiple steps and I'm in the process of adding a non-trivial set of modifications that affect multiple steps, if I hit `cmd + r` by mistake or I close the tab, everything I didn't save will be gone. 

It would be great if unsaved state was automatically saved (just like what VS Code does). If I reload the page, I should be able to discard unsaved changes or properly save them and bump the version.

**Comment by dylburger** [comment]
This is done in [the new version of the workflow builder](https://pipedream.com/docs/migrate-from-v1/)!
