### ISSUE TITLE
[APP] SendX

### ISSUE THREAD

**Issue by rodenp** [PipedreamHQ/pipedream#2920]
**Name of app / service**
SendX

**Link to developer documentation**
https://www.sendworks.com/support/sendx/rest-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Would be good if the community could also add new Apps rather than have to reach out to Pipedream to create them.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
ALL

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
This is now integrated https://pipedream.com/apps/sendx
