### ISSUE TITLE
[APP] Saleor and Saleor Cloud

### ISSUE THREAD

**Issue by jimblizz** [PipedreamHQ/pipedream#2921]
**Name of app / service**
Saleor 

**Link to developer documentation**
https://docs.saleor.io/docs/3.x/developer/users#authentication
https://saleor.io/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
A workaround here would be to manually manage authentication.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Auth management for Saleor is the minimum need. Preferably for self-hosted, but the only difference between it and a Saleor Cloud instance would probably be the URL.

Action support for the `orderFulfill` mutation would a big bonus - https://docs.saleor.io/docs/3.x/developer/api-reference/mutations/order-fulfill

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/saleor?via=go
