### ISSUE TITLE
[BUG] JSON payload corrupted with new lines

### ISSUE THREAD

**Issue by aroslov** [PipedreamHQ/pipedream#2922]
**Describe the bug**
When using a POST request with JSON body and variables substitution, Pipedream incorrectly handles \n in strings.

**To Reproduce**
1. Create a POST request step
2. In Configure / Body select json
3. Use this a payload with variable like this:
```
{
  "text": "Name:\n {{steps.trigger.event.body.user.profile.display_name}}"
}
```
5. JSON actually generated by Pipedream and sent in the POST request contains a new line mid string, like this:
```
{
  "text": "Name:
 anton"
}
```
Which is not a valid JSON and breaks the validation on the receiving side.

**Expected behavior**
\n is preserved:

```
{
  "text": "Name:\n anton"
}
```

**Screenshots**
<img width="913" alt="Screenshot 2022-05-22 at 18 42 30" src="https://user-images.githubusercontent.com/1531774/169691380-793cc688-b81b-433b-9b7b-ecfa86096f1e.png">
<img width="865" alt="Screenshot 2022-05-22 at 18 42 53" src="https://user-images.githubusercontent.com/1531774/169691413-f6a9e073-45c6-431f-bd4e-29a770c6a5f7.png">

**Comment by dannyroosevelt** [comment]
Thanks for reporting, @aroslov I see the same issue on my end. I've raised this with the team internally and we'll investigate.

**Comment by dannyroosevelt** [comment]
@aroslov you should be able to avoid this by escaping the `\n` in the body:
`"text": "Name:\\n {{steps....display_name}}"`

I've confirmed that works on my end.

**Comment by aroslov** [comment]
Thanks for the workaround @dannyroosevelt however I believe that the behavior is both inconsistent (requiring either `\\n` or `\n` depending on presence of variables) and undocumented, therefore requires a proper fix.

**Comment by dylburger** [comment]
@aroslov
