### ISSUE TITLE
[BUG] Reddit-NEW SAVED POST BY USER-broken again!

### ISSUE THREAD

**Issue by onlytanmoy** [PipedreamHQ/pipedream#2925]
Hiya, this has broken again 😒 
Previous similar bug filed here https://github.com/PipedreamHQ/pipedream/issues/2506
Here is the screenshot of the most recent source logs: https://imgur.com/a/4EVLZkN
Please fix it, thanks!

**Comment by Hassan-Abbas-SQA** [comment]
@onlytanmoy can you please explain the steps to reproduce this issue?

**Comment by dannyroosevelt** [comment]
@Hassan-Abbas-SQA let me know if you are able to reproduce the issue -- that'd be helpful for the investigation.

**Comment by Hassan-Abbas-SQA** [comment]
@dannyroosevelt saving posts works fine, on saving multiple comments from already saved post i got this error , and after getting this error save post events started throwing errors now not even able to save more posts anymore as well 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/104946677/170133150-b2e9dc4a-9f86-43fc-bc64-7b2ac5b4203a.png">

**Comment by dannyroosevelt** [comment]
This is ready for release!
