### ISSUE TITLE
Videoask [APP]

### ISSUE THREAD

**Issue by parisetflorian** [PipedreamHQ/pipedream#2929]
**Name of app / service**
Videoask

**Link to developer documentation**
https://documenter.getpostman.com/view/291373/SWTEdwrG#intro

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Requires oAuth with access tokens

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Submitted as API KEy because VideoAsk didn't provide OAuth details.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @parisetflorian 
Happy to announce we have based a base integration for VideoAsk:
https://pipedream.com/apps/videoask
