### ISSUE TITLE
[FEATURE] LinkedIn app

### ISSUE THREAD

**Issue by oliviermills** [PipedreamHQ/pipedream#293]
**Is your feature request related to a problem? Please describe.**
No LinkedIn app for action: posting/sharing

**Describe the solution you'd like**
Add LinkedIn to the list of apps

**Do you have a workaround?**
Write out the post and share actions as node.js scripts.

**Comparable features in other tools?**
Yes, zapier and automate.io have it.

**Additional context**
Starting point would be the `ugsPosts` here https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin?context=linkedin/consumer/context

**Comment by dylburger** [comment]
@oliviermills thank you for requesting, we'll take a look ASAP!

**Comment by todsac** [comment]
LinkedIn has been integrated. Free to free to add any actions you see fit.

**Comment by todsac** [comment]
<img width="917" alt="Screen Shot 2020-08-08 at 12 35 11 PM" src="https://user-images.githubusercontent.com/35614146/89718460-9acfd680-d973-11ea-898d-450921a6ed27.png">

**Comment by todsac** [comment]
One issue still remains - "LinkedIn offers programmatic refresh tokens that are valid for a fixed length of time. By default, access tokens are valid for 60 days and programmatic refresh tokens are valid for a year. LinkedIn supports programmatic refresh tokens for a limited set of partners on a case-by-case basis."

**Comment by oliviermills** [comment]
Thanks for the amazing response and implementation time!! @todsac 

The current scopes you included are `r_emailaddress, r_liteprofile, w_member_social`. This excludes the ability to post or read on-behalf of LinkedIn organizations/showcase pages the user is admin of. I suggest adding `w_organization_social` to allow this. ~ unless I missed away to do this myself?

The LinkedIn "ugcPost" resource will eventually take over the Share API's, so I'd recommend we focus on that resource. More info here on scopes/permissions: https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api#permissions

Thanks!

**Comment by todsac** [comment]
@oliviermills - I will look into this.  I added the scope and it doesn't work so my assumption is our app is not approved for this resource.  I believe LinkedIn has a Marketing Developer Platform that we may need to be approved for but will report back.

**Comment by todsac** [comment]
@oliviermills I confirmed with LinkedIn that we need to be in the program and are working with them on getting approved.  Here are the only scopes we are currently approved for:

<img width="764" alt="Screen Shot 2020-08-11 at 1 59 14 PM" src="https://user-images.githubusercontent.com/35614146/89948421-f64fcd80-dbda-11ea-9490-d616a007be77.png">

**Comment by todsac** [comment]
The LinkedIn app has been updated to include refresh tokens so the prior issue is solved.
