### ISSUE TITLE
[APP] Crove

### ISSUE THREAD

**Issue by croveapp** [PipedreamHQ/pipedream#2931]
**Name of app / service**
Crove

**Link to developer documentation**
https://crove.stoplight.io/docs/crove-external-integrations-api/46b38f624d360-crove-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Manual auth / API usage

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Triggers:
[Document Created](https://crove.stoplight.io/docs/crove-external-integrations-api/521632069177e-create-webhook-document)
[Document Completed](https://crove.stoplight.io/docs/crove-external-integrations-api/521632069177e-create-webhook-document)

Actions:
[Create document](https://crove.stoplight.io/docs/crove-external-integrations-api/186fe10fe1679-create-document)
[Update document](https://crove.stoplight.io/docs/crove-external-integrations-api/32259b12a745d-update-response)
[Send document](https://crove.stoplight.io/docs/crove-external-integrations-api/84483067fc33d-create-email-invite)
[Get Document Details](https://crove.stoplight.io/docs/crove-external-integrations-api/ead90fe8d8bf9-document-detail)
[Update document Details](https://crove.stoplight.io/docs/crove-external-integrations-api/9bda1c39ddaa0-update-document)
[Complete Document](https://crove.stoplight.io/docs/crove-external-integrations-api/7512151ec88fb-complete-document)
[Generate PDF from Document](https://crove.stoplight.io/docs/crove-external-integrations-api/4d7baae756951-generate-pdf-for-a-document)
Generate PDF from Template
[Submit document ](https://crove.stoplight.io/docs/crove-external-integrations-api/4f16a79e1a032-submit-response-of-a-document)
[Create Invitation link](https://crove.stoplight.io/docs/crove-external-integrations-api/9cac15cc896e0-create-document-respondent)

I'm happy to build them.

**Comment by charanjit-singh** [comment]
Hi @dannyroosevelt, This is Charanjit from crove.app. We've given you temporary access to generate API keys. https://v2.crove.app/workspace/api-keys

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
That’s great!

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
