### ISSUE TITLE
[APP] Nexudus

### ISSUE THREAD

**Issue by acti0nm4n** [PipedreamHQ/pipedream#2933]
**Name of app / service**
Nexudus

**Link to developer documentation**
https://developers.nexudus.com/reference

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No, using Node to directly call API

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Would be good to have coworker search & CRUD, booking CRUD, invoices lookup,

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by email, copied sergio@pk integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Submitted as basic auth.

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/nexudus?via=go
