### ISSUE TITLE
[BUG] MongoDb "search-documents" action misspelled

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2936]
The `search_documents.mjs` action is misspelled as `search_ducuments.mjs`:

https://github.com/PipedreamHQ/pipedream/blob/master/components/mongodb/actions/search-documents/search-ducuments.mjs

**Comment by dannyroosevelt** [comment]
Make sure to address this issue at the same time: https://github.com/PipedreamHQ/pipedream/issues/2935
