### ISSUE TITLE
[New triggers and action] Demio

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2939]
**Is there a specific app this action is for?**
Demio

**Please provide a link to the relevant API docs for the specific service / operation.**
https://publicdemioapi.docs.apiary.io/#

### Triggers
- Webinar participant joins webinar
- New webinar registration
- Webinar updated

### Actions
- Create registration for webinar
- List events
- Get event details

**Comment by lcaresia** [comment]
@dannyroosevelt 

I can't found a way to do this triggers:

> Webinar participant joins webinar
> Webinar updated
  
  
  So I will make a PR without this, and after I do this if possible.

**Comment by dannyroosevelt** [comment]
This is ready for release!
