### ISSUE TITLE
[BUG] Google Sheets API returns 404 when sheet name contains '/'

### ISSUE THREAD

**Issue by Defozo** [PipedreamHQ/pipedream#2943]
**Describe the bug**
Google Sheets API returns 404 when sheet name contains '/'

**To Reproduce**
Add Google Sheets API with '/' in the name of the sheet

**Expected behavior**
No errors

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by dannyroosevelt** [comment]
Thank you for reporting, @Defozo -- are they specific actions/triggers/endpoints you're trying to use that are failing in these cases?

**Comment by Defozo** [comment]
I tested this with the action "Add Single Row" from Google Sheets.

**Comment by dannyroosevelt** [comment]
Thanks for the info, I see the same. We will check this out!
![image](https://user-images.githubusercontent.com/20780753/170149149-fae4c922-603d-4474-9988-556838e71f9b.png)

**Comment by Hassan-Abbas-SQA** [comment]
@dannyroosevelt works fine now
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/104946677/170585359-71bb47c6-da1a-40f3-91d0-c34dded080db.png">

**Comment by dannyroosevelt** [comment]
Great! Let's ship it!

**Comment by dannyroosevelt** [comment]
This is ready for release!
