### ISSUE TITLE
[ACTION] Add an option to set chat permissions in the Telegram bot app

### ISSUE THREAD

**Issue by AlexeyArtemev** [PipedreamHQ/pipedream#2958]
**Is there a specific app this action is for?**
Yes, Telegram Bot, but i would like to see some instruments to change chat parameters(permissions and slowmode in particular, but there's no botAPI method for slowmode)

**Please provide a link to the relevant API docs for the specific service / operation.**
https://core.telegram.org/bots/api#setchatpermissions

**Comment by dannyroosevelt** [comment]
Thanks for the request!

Setting chat permissions seems like it'd make sense as its own built-in action. But as you mentioned, I don't see any way to **set** `slow_mode` in the API, so unless there's another solution, we won't be able to support that method.

**Comment by dannyroosevelt** [comment]
By the way all our actions are open source and [hosted on GitHub](https://github.com/PipedreamHQ/pipedream) -- are you interested in [building out the Set Chat Permissions action](https://pipedream.com/docs/components/quickstart/nodejs/actions/)?

**Comment by AlexeyArtemev** [comment]
As I can see from the quickstart page, actions can be wrote only on JS, and i don't have any expertise at it
though i can assist in development since i have a working python script which changes the chat permissions and thus have at least a little knowledge of working with TG bot API

**Comment by dannyroosevelt** [comment]
No problem. I've added [this ticket](https://github.com/PipedreamHQ/pipedream/issues/2964) to the team's backlog -- feel free to subscribe and follow along if you'd like to receive updates on the status!
