### ISSUE TITLE
[ACTION] Telegram Bot -- Set Chat Permissions

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2964]
**Is there a specific app this action is for?**
`telegram_bot_api`
https://core.telegram.org/bots/api#setchatpermissions

Set Chat Permissions action
- Should be able to list chats or usernames
- Specify permissions to enable from this list https://core.telegram.org/bots/api#setchatpermissions

**Comment by dannyroosevelt** [comment]
Requested from a user: https://github.com/PipedreamHQ/pipedream/issues/2958

**Comment by bush4u** [comment]
This is on blocked as I could not understand the chat architecture. I am doing more research on this while I move to another task
