### ISSUE TITLE
[BUG] MongoDB refactor

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2965]
**Describe the bug**

The current MongoDB component has a few issues noticed by customers and staff alike:

* https://github.com/PipedreamHQ/pipedream/issues/2954
* https://github.com/PipedreamHQ/pipedream/issues/2955
* https://github.com/PipedreamHQ/pipedream/issues/2962
* https://github.com/PipedreamHQ/pipedream/issues/2935
* https://github.com/PipedreamHQ/pipedream/issues/2942

Some of these will be fixed by an update to the parsing strategy update by @michelle0927 here: https://github.com/PipedreamHQ/pipedream/pull/2941

However, I suggest a slight refactor to address the other issues and simplify the component.

## 1. Replace the Mongoose ORM with the native MongoDB Node Client

The Mongoose ORM client is designed for use in apps that have models defined in their code, our use case is a bit different. We're accepting plain objects from users thanks to the `object` param.

### Actions to take

Replace [`mongoose`](https://github.com/PipedreamHQ/pipedream/blob/c15c124bcf04a117258ab07f1a64e864f8419a0c/components/mongodb/mongodb.app.mjs#L118 ) connection with the native client:
 
```javascript
    const client = await MongoClient.connect(uri, { 
      useNewUrlParser: true, 
      useUnifiedTopology: true 
    })

    return client;
```

Then in `searchDocuments` we can replace all of the Mongoonse with:

```
this.connect().find(this.filter).toArray();
```

### Drop all parsing options and logic

We won't need to use any parsing options or show them to the user.

Just pass the prop directly with `this.filter`.

If a user needs to pass a number, boolean, etc, then we can just instruct them to wrap in an expression in the UI:

![CleanShot 2022-05-25 at 15 47 24@2x](https://user-images.githubusercontent.com/2694734/170355031-2f8cf4b3-6949-411c-a3d7-0feb70660ca5.png)

### Add an `options` prop for all searching actions

The Mongo DB Client accepts a second `options` prop to include sorting, limiting, etc. 

https://www.mongodb.com/docs/drivers/node/current/usage-examples/find/

It just needs to be an optional object that's passed to the MongoDB client.

**Comment by dannyroosevelt** [comment]
@michelle0927 tagging you in case you want to work on this, since I think you worked on the other MongoDB component. Feel free to assign yourself if you want, otherwise someone else can grab it.

**Comment by ctrlaltdylan** [comment]
Just want to say thanks again @michelle0927 for building the components, I'm a big Mongo fan and clearly it's already getting use from customers.

I think you put it in a great effort into the formatting / parsing logic, just trying to offer a way that leads to less work and code in the long run.

Let me know if I can help answer and questions about the Mongo client, I have used it way too much over the past 2 years.

**Comment by dannyroosevelt** [comment]
This is ready for release!
