### ISSUE TITLE
OUCH!

### ISSUE THREAD

**Issue by ericmorand** [PipedreamHQ/pipedream#2968]
Enough said, right?

![image](https://user-images.githubusercontent.com/125664/170374704-e92a8149-0e33-4dc8-af88-723ed43b9472.png)

**Comment by tjk** [comment]
If the issue is that node is not a language -- we obviously agree :). Fix going out now with a couple new options. Thanks!

Please let us know if there is more to this issue or if anything else comes up. Cheers.

**Comment by ericmorand** [comment]
Thanks a lot. It was a troll issue obviously. Your tool is amazing - I discovered it yesterday - but I couldn't resist. 😂
