### ISSUE TITLE
[APP] Weworkbook

### ISSUE THREAD

**Issue by accellier** [PipedreamHQ/pipedream#2970]
**Name of app / service**
Weworkbook

**Link to developer documentation**
Docs are here https://api.weworkbook.com/ but behind credentials (can be supplied to Pipedream Dev).
Here is a PDF print out of the OAUTH2 authentication endpoints and a simple GET request available for testing:
https://drive.google.com/file/d/1hLzD2KJ_nHXezoZ1U2TLBoOUbK5QnX2c/view?usp=sharing

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Just need to get the authentication happening.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
We can build these.

Happy to assist with testing etc.

**Comment by pd-component-development** [comment]
Thanks for submitting and for the links.

Do you envision supplying your own account-specific client ID and client secret when authenticating? Or will there be a Pipedream app that are used for all users of the Pipedream<>Weworkbook integration?

**Comment by dannyroosevelt** [comment]
Thanks for submitting and for the links.

Are you envisioning supplying your own user-specific client ID and client secret? Or should Pipedream manage the IDs within a Pipedream app for Weworkbook?

**Comment by accellier** [comment]
Hey Danny. Appreciate the prompt response.
Yes we can create our own user-specific client ID and client secret in the Weworkbook API's GUI and enter them in when we authenticate for the first time - is this what you mean?

**Comment by accellier** [comment]
In the Weworkbook API's UI, when you create a new Client App it asks for a name and a redirect URL (application's authorization callback URL). I guess Pipedream will need to give that to the authenticating user somehow.

**Comment by dannyroosevelt** [comment]
Let me know if this works for you as a basic integration to get you started: https://pipedream.com/apps/weworkbook/

**Comment by accellier** [comment]
That's fantastic Danny - works nicely so far!
We will build some basic integrations and monitor.
Appreciate such a fast build - thank you!
