### ISSUE TITLE
[BUG] Telegram trigger is pushing daily invocations to the limit

### ISSUE THREAD

**Issue by AlexeyArtemev** [PipedreamHQ/pipedream#2972]
**Describe the bug**
An instance of telegram channel trigger eats all the limits during the initialization

**To Reproduce**
1. Create a workflow
2. Use telegram bot as a trigger
3. Select channel updates as an event listener
4. See infinite load until the limit is reached

**Expected behavior**
I've expected to not exceeding my limits by creating a trigger

**Screenshots**
![image](https://user-images.githubusercontent.com/53113374/170477916-0580b63b-9b1a-4115-9366-b7cf68c78c5f.png)

**Desktop (please complete the following information):**
 - OS: Win10 1909
 - Browser: Chrome
 - Version: 102.0.5005.63

**Additional context**
Kinda sad

**Comment by AlexeyArtemev** [comment]
The problem appears during the trigger creation process only
![image](https://user-images.githubusercontent.com/53113374/170478507-c5ebbd37-e7c5-4808-90fd-dc83c38df863.png)

**Comment by dannyroosevelt** [comment]
Thanks for submitting the report, @AlexeyArtemev, and sorry you're running into issues with this source.

We aren't able to reproduce the specific issue, but we were able to verify the errors in the logs for the source you created (FYI you can [see these here](https://pipedream.com/sources/dc_gzu0yqO/logs)).

Can you tell us more about the bot configuration? Is it already an admin of various channels when you are creating the source? Are they anything unique about those channels?

**Comment by ctrlaltdylan** [comment]
@AlexeyArtemev just to add another question to @dannyroosevelt 's, how many channels is your bot a member of?

This source generates a webhook that subscribes to _all_ channels that your bot is subscribed to, so if there are 500 messages in the various channels your bot is subscribed to after you've created the source, then you'd hit your invocation limit.

**Comment by AlexeyArtemev** [comment]
No, he wasn't an admin of any channel, only chats
As i can see from the losg, the problem is that the app tried to get not channels, but chats instead:
`Cannot read property 'chat' of undefined`
and the bot has several chats with up to 95.000 members, so it's not a surprise to get such an error with invocations

IMHO the problem occured because the bot has no channels which it subscribed to, so there's just nowhere to get them, but the app tried its best :D

**Comment by AlexeyArtemev** [comment]
@ctrlaltdylan the problem might as well occur if the parsed object defined wrong. There is a chat property in the body object, and yet the error says that the app can't locate it

**Comment by ctrlaltdylan** [comment]
@AlexeyArtemev  Thank you! That was the missing piece, I'm a Telegram noob can't you tell 😆 

But I still wasn't able to reproduce the problem.

I don't have any errors in the Channel Updates Telegram source when I added it to a group chat.

And to clarify, the source works by creating a webhook on Telegram, so every new event will trigger the source. And it appears that it's only subscribing to channel related events:

https://github.com/PipedreamHQ/pipedream/blob/e04e13bcc94b1f2e5d2db0a2bcac99aa74eaf85d/components/telegram_bot_api/sources/channel-updates/channel-updates.mjs#L22

Your source's Telegram Webhook coming back to Pipedream will only send `channel` and `edit_channel` events.

In this case, somehow Telegram is sending a payload to Pipedream that's missing a `chat` field in either one of those payloads types, which _shouldn't_ be the case.

**Comment by ctrlaltdylan** [comment]
Thanks for the steps @AlexeyArtemev but no luck.

I also turned of Privacy Mode on the bot, hoping that would trigger the bug.

Maybe we have some terminology mix up, I'm adding my bot to a **Group**. Is that what you mean by a chat or maybe something different?

**Comment by AlexeyArtemev** [comment]
Yes, by chat I mean group(both terms are being used by telegram, one in the API and one in the actual apps(desktop, web and mobile))

**Comment by ctrlaltdylan** [comment]
Thanks for clarifying @AlexeyArtemev just trying to be specific!

Really appreciate you working with us to narrow this down. We've just shipped a new version of the Telegram New Channel Update source:

https://github.com/PipedreamHQ/pipedream/pull/2978

It doesn't _fix_ the bug persay, but it will give us better debugging information to possibility help narrow down the cause.

It throws an error you can see in your source logs if the payload isn't the right shape, like what's going on now.

Could you please delete your source and try again. Also, I've gone ahead and given you an extra 500 daily invocations to play with on your account for your time helping us narrow this down.

If you could please delete your source and create another Telegram New Channel Notifications one, then the payload of the problem event should appear in your logs area in the source.

**Comment by AlexeyArtemev** [comment]
@ctrlaltdylan thanks for invoices, but first of all i need to delete current source - it creates more and more load somehow
![image](https://user-images.githubusercontent.com/53113374/170566776-5f483874-2234-4ccd-b218-99ea38009dfc.png)

**Comment by ctrlaltdylan** [comment]
Hi @AlexeyArtemev , good point - can you delete the source then recreate it? You hopefully haven't hit your limit for today so we can see the error logs.

**Comment by AlexeyArtemev** [comment]
Sure thing, @ctrlaltdylan, but I use your great service for automation in a non-profit organisation which relies on it heavily, so first of all I need to make sure that the business day is over. I'll create a new source after 19:00 UTC and send an update to this thread

**Comment by AlexeyArtemev** [comment]
@ctrlaltdylan I can't reproduce it anymore
As far as i'm concerned, the channel trigger works as it should(at least it doesn't waste any invocations anymore)

**Comment by dylburger** [comment]
Thanks for confirming, @AlexeyArtemev !
