### ISSUE TITLE
[TRIGGER] Zoom Phone

### ISSUE THREAD

**Issue by raphaelvarieras** [PipedreamHQ/pipedream#2981]
Zoom phone:

https://marketplace.zoom.us/docs/api-reference/zoom-phone-api

**Comment by dannyroosevelt** [comment]
Hey @raphaelvarieras are there specific trigger events you'd like to see from the Zoom Phone API?

**Comment by raphaelvarieras** [comment]
I would suggest the following as a good starting place:

- new call recording for a user
- new call recording in account
- new voicemail for a user
- new voicemail in account

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
Sorry @raphaelvarieras , Pipedream workflows gone awry!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by vunguyenhung** [comment]
Hello @raphaelvarieras, we will ship this Zoom Phone component first for you to use. 

During your usage, if you have any issue, kindly ping us directly on Pipedream Users Slack @Leo, or create a new issue on this repo. Many thanks!

cc @dannyroosevelt

**Comment by dannyroosevelt** [comment]
This is ready for release!
