### ISSUE TITLE
HTTP Response

### ISSUE THREAD

**Issue by CandyOrate** [PipedreamHQ/pipedream#2985]
**HTTP Response**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @CandyOrate let us know if you're able to get your hands on any documentation and we'll happily check out if an integration might work, but without that we're unfortunately blocked on moving forward.

**Comment by sergioeliot2039** [comment]
@CandyOrate for an example of a good app request here in Pipedream, with links to developer documentation, and other details, plesae see this one done for Crove.app https://github.com/PipedreamHQ/pipedream/issues/2931

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
