### ISSUE TITLE
[TRIGGER] Replies of user on a list

### ISSUE THREAD

**Issue by zergcore** [PipedreamHQ/pipedream#2986]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

I would like to get the replies of users included on a list, and I don't know how to do it without making a connection with each user account and watch their tweets. The app is to watch the actions of accounts linked to a marketing company. This trigger is a twitter one.

**Comment by dannyroosevelt** [comment]
Hi @zergcore thanks for submitting the request! This is a great question for the community to help out with -- I'd recommend posting this question to the #help or #general channels in our [public Slack](https://join.slack.com/t/pipedream-users/shared_invite/zt-11sazmsg0-oS2VW~mZfhtk3XfEEvb~JA) or in our [community forum on Discourse](https://pipedream.com/community).
