### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by AlexErmak0v** [PipedreamHQ/pipedream#3001]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Find streams by title in category
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by dingle8906** [comment]
ok

**Comment by dannyroosevelt** [comment]
@AlexErmak0v can you elaborate on what trigger you're looking for? What app / API are you trying to trigger your workflow on?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
