### ISSUE TITLE
[FEATURE] Move @pipedream/platform axios to this monorepo, add debug flag

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3005]
This ticket captures a few items:

- We should move [the `@pipedream/platform` library ](https://github.com/PipedreamHQ/platform) to this monorepo, publish with pnpm, etc.
- We should add support for a `debug` flag. See below thread from Slack for context:

---

1. The output of the core API method used to fetch the data, so we see what the API returned. For webhook-based sources this may not be relevant, but if we make additional API calls to fetch additional data, we should log the output of all of that.
2. If you’re transforming data significantly, we should log the output of those variables
3. Log the data you’re attempting to emit, so we see what the source should have emitted (if the call to this.$emit fails, we may not get good logs to show that, so it’s helpful to know if the data you’re emitting is empty, or if the data is present but we failed to emit for another reason.

Ideally #1 would be solved in a single place (e.g. if we used `@pipedream/platform` axios, you could just pass a debug param to that, which would automatically log the serialized axios response.

We could also add better logging automatically for #3 in the platform.

**Comment by vunguyenhung** [comment]
Hello everyone, I couldn't test this changes on my side by publishing a test component importing the new axios code
![image](https://user-images.githubusercontent.com/18277920/177579606-c1f465f3-8725-42b0-a98f-6e1e06fe2c68.png)
![image](https://user-images.githubusercontent.com/18277920/177579668-77a04efd-8369-463e-b64a-45c75eae10d5.png)

Per discussion with @andrewjschuang,  it is not possible to publish a component this way; and as he has tested the changes locally on his side, I will move this ticket to ready for release.

**Comment by andrewjschuang** [comment]
`@pipedream/platform v1.0.0` functioning correctly:

- passing `debug: true` to `@pipedream/platform/axios` exports the request config and the response

![Screen Shot 2022-07-06 at 1 47 22 PM](https://user-images.githubusercontent.com/15385076/177605391-264981fe-a41b-414c-9248-71d18bf5ef94.png)

- passing `body` to `@pipedream/platform/axios` results in `ConfigurationError`

![Screen Shot 2022-07-06 at 2 03 36 PM](https://user-images.githubusercontent.com/15385076/177605611-3060a097-39c5-4319-8aa6-cbc7a07463fa.png)
