### ISSUE TITLE
[FEATURE] Add step trees

### ISSUE THREAD

**Issue by danthegoodman1** [PipedreamHQ/pipedream#301]
This could be an engineering nightmare to add... BUT... I think it would be amazing if there was a sort of tree step, that based on the result of the previous step, would follow one of 2 (or more?) branches of steps instead of a one-dimensional step flow. I've definitely been using workarounds but this would be a lot cleaner and easier to work with.

**Do you have a workaround?**
A good workaround for now is just writing in a bunch of step skips and `$end()`'s into the single chain. i.e. if something happens in step 2, either keep going to step 3 or jump to step 6 (and step 5 would have a `$end()` in it), or maybe even jump to step 9 (and step 8 would have a `$end()` in it). You could also just trigger other workflows as the other branches I guess.

**Comparable features in other tools?**
I can't think of something similar to this platform. I guess it would be like a giant if/else or switch for steps.

**Additional context**
Just to be more clear here are some translation diagrams from my skip and `$end()` workaround above:
*WORKAROUND:*
![Untitled 3](https://user-images.githubusercontent.com/17806508/89901796-a01b6400-dbb3-11ea-95e3-26f5be8248a7.jpg)

*FEATURE REQUEST:*
![Untitled 4](https://user-images.githubusercontent.com/17806508/89902050-f38db200-dbb3-11ea-92cd-25c249554dd8.jpg)

**Comment by jverce** [comment]
@danthegoodman1 I think you want something like what [AWS Step Functions](https://aws.amazon.com/step-functions/) offers?

**Comment by danthegoodman1** [comment]
> @danthegoodman1 I think you want something like what [AWS Step Functions](https://aws.amazon.com/step-functions/) offers?

Similar, yeah

**Comment by dylburger** [comment]
We'll address as a part of #216, which is on the near-term backlog
