### ISSUE TITLE
[BUG] Error being thrown in Fauna source when listening for new documents

### ISSUE THREAD

**Issue by aaroncampos** [PipedreamHQ/pipedream#3011]
**Describe the bug**
I created a Fauna source, listening for new/removed documents in a collection, but no events are exposed to the action.  In looking at the source logs, it looks like there's an error in the underlying system/action code.

```
error
TypeError: Cannot read property 'id' of undefined
at Object.run (file:///var/task/user/sources/changes-to-collection/changes-to-collection.mjs:67:70)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async /var/task/index.js:122:11
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async Runtime.exports.main [as handler] (/var/task/index.js:60:20)
```

**To Reproduce**
1. Create a new Fauna source and point it at a DB and collection to collect new documents from
2. Save the source/workflow
3. Create a document in that collection
4. See error in the logs

**Expected behavior**
I should see new events flowing into my workflow from that source

**Screenshots**
![Source__New_or_Removed_Slack_Reminder_-_Pipedream](https://user-images.githubusercontent.com/44702/171264737-3d0b83f6-2e18-4659-a9ef-3c3cfc03cd42.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser: Chrome and Safari

**Comment by Hassan-Abbas-SQA** [comment]
@andrewjschuang this source is working fine but i have encountered promise issue please fix that 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/104946677/171852970-e1e0ae3e-1acf-437e-a355-d2601bfe1342.png">

**Comment by andrewjschuang** [comment]
> @andrewjschuang this source is working fine but i have encountered promise issue please fix that

@Hassan-Abbas-SQA should be fixed now

**Comment by dannyroosevelt** [comment]
This is ready for release!
