### ISSUE TITLE
[APP] Mobivate SMS

### ISSUE THREAD

**Issue by jhuseinovic** [PipedreamHQ/pipedream#3013]
**Name of app / service**
Mobivate SMS

**Link to developer documentation**
https://api.mobivatebulksms.com/apidoc#!/send/sendSingle
After first creating the account at www.hub.mobivate.com and topping up the account.

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I got the work-around. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Send SMS using 'sendSingle' method from the API documentation above.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/mobivate?via=go
