### ISSUE TITLE
Purge one precise URL in cloudflare instead of all cache[ACTION]

### ISSUE THREAD

**Issue by raphael1807** [PipedreamHQ/pipedream#3016]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by zalmanlew** [comment]
It _should_ be pretty straightforward to implement this. I just looked through the code on the current Cloudflare components and it can use some refactoring work.

This specific request can just copy the purge all files action, it just needs to allow the user to enter in a `purge_url` input and pass it in the body like
```javascript
data: {url: this.purge_url}
```

**Comment by dylburger** [comment]
@raphael1807 As Zalman mentioned, it may not be too hard to develop this action yourself, if you're interested. See [the action quickstart](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and let us know if you have any questions!

Otherwise, we can get this on our backlog.

**Comment by raphael1807** [comment]
Thanks a lot @dylburger !

**Comment by zalmanlew** [comment]
#3083

**Comment by zalmanlew** [comment]
@raphael1807 this is now implemented from #3083
