### ISSUE TITLE
[TRIGGER] When a new item is added to the database

### ISSUE THREAD

**Issue by cedeguil** [PipedreamHQ/pipedream#3033]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
when a new item is added to the selected database, it takes it as a triggert

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by dylburger** [comment]
@cedeguil Could you tell me more about the specific app / database this trigger is for?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
