### ISSUE TITLE
[APP] MPWA

### ISSUE THREAD

**Issue by eza999** [PipedreamHQ/pipedream#3039]
**mpwa / service**

**[Link to developer documentation](https://wanu.jagasis.com/home)**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
I'm sorry https://wanu.jagasis.com/home and the entire jagasis.com domain are down
