### ISSUE TITLE
[New triggers and action] Zenkit

### ISSUE THREAD

**Issue by z1lV3r** [PipedreamHQ/pipedream#3040]
Zenkit

https://base.zenkit.com/docs/api/overview/introduction

Triggers:
new item: triggers when a new item is created
new notification: triggers when you have a new notification
new activity: triggers when there is a new activity in zenkit
item value changed: triggers when the value of a field changes in an item

Actions:
Create item 
Update item
Add comment to item
Find item
Find member
Find collection

**Comment by sergioeliot2039** [comment]
There is already a Zenkit integration here: https://pipedream.com/apps/zenkit
But changed labels to reflect the user's requesting new triggers and actions. API documentation looks enough to build these components.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by dannyroosevelt** [comment]
> @dylburger @dannyroosevelt I have a problem connecting my account:
> 
> Pipedream failed to connect to your account. Please reach out to [integration-errors@pipedream.com](mailto:integration-errors@pipedream.com) and provide this error ID: d09f3914bad74ddc955f80d6a37b9918

Sorry for the delay on this @vellames-turing , that error returns this info, which is a strange error:
```
{
  "error": {
    "name": "Missing or invalid authentication",
    "code": "UNAUTHENTICATED",
    "statusCode": 401,
    "message": "You need to be logged in to view this content.",
    "description": "You need to be logged in to view this content."
  }
}
```

I am able to reproduce and I think this is an issue on Zenkit's end. I've reached out to their team to help debug.

**Comment by dannyroosevelt** [comment]
@vellames-turing FYI the authentication error is now fixed
