### ISSUE TITLE
[TRIGGER] Twitter, public list related sources

### ISSUE THREAD

**Issue by vanetreg** [PipedreamHQ/pipedream#3042]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
1) specific public list emits new tweet
2) search tweets of specific public list(s)
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
:(

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by lcaresia** [comment]
@feyzullah I finished the action for search tweets in lists, you just need paginate the result.

**Comment by vunguyenhung** [comment]
Hello @lcaresia @feyzullah could you link a PR into this issue so that we can track the next action needed for this issue?

**Comment by feyzullah** [comment]
@vunguyenhung sorry, this one is left here unintentionally, I am going to link it today or at latest tomorrow

**Comment by vunguyenhung** [comment]
Thank you @feyzullah! Is it okay for me to move this back to Doing or TODO?

**Comment by feyzullah** [comment]
@vunguyenhung moved to Doing, thank you for notifying

**Comment by vunguyenhung** [comment]
Thank you so much @feyzullah!
