### ISSUE TITLE
[New triggers and actions] TickTick

### ISSUE THREAD

**Issue by klauern** [PipedreamHQ/pipedream#3043]
**App Name**
[TickTick](https://ticktick.com/home)

**Developer Docs**
https://developer.ticktick.com/docs#%2Fopenapi=

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I do not have anything at this time, but having access to the lists, tags, etc., from my paid TickTick account would help me integrate with Notion databases better, too.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I'd like to add a low-priority task to TickTick depending on something in my Notion setup.  Ideally, it'd be great if I could implement 	a rudimentary two-way integration of a list of items in a page in Notion with a TickTick list.  I'd need things like the list it's in, priority, due date, etc., so all the context you would get from TickTick's lists

**Comment by klauern** [comment]
I mean, I guess this is an integration, albeit pretty barren in terms of supporting much: https://github.com/PipedreamHQ/pipedream/blob/fa2df4bbb52341ee84a54090d6d2618305e67e89/components/ticktick/ticktick.app.mjs#L1-L11

I'm not even sure where to start with that, because I write mainly Go and Python, so I'm not sure how I should approach it, hence why I think it's a little lacking.

**Comment by sergioeliot2039** [comment]
Gotcha. Thanks for the clarification.
I think @dylburger or @ctrlaltdylan may have better input.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
### Triggers
- New Task
- Updated Task
- Completed Task

### Actions
- Create Task
- Update Task
- Complete Task

**Comment by bush4u** [comment]
I changed the status to blocked because $auth did not return the access_token.

**Comment by bush4u** [comment]
I was able to get the issue rsolved

**Comment by dannyroosevelt** [comment]
> I was able to get the issue resolved

What was the issue?

**Comment by bush4u** [comment]
The mistake came from me actually. I was referencing the wrong keys in $auth. All is good at the moment

**Comment by bush4u** [comment]
@dannyroosevelt , I need your help with the source tasks
New Task
Updated Task
Completed Task

TickTick does not have webhook APIs making the Source type, polling. 

However, I cannot see an API on ticktick to get all tasks. 
I am done with the action tasks. Can I go ahead and open a PR?

**Comment by dannyroosevelt** [comment]
Yea sounds good @bush4u, thanks

**Comment by Hassan-Abbas-SQA** [comment]
@bush4u on Create New Task Action : i have provided the start and the end date but seems like dates were not setup with the new task, task is in no date section
<img width="964" alt="image" src="https://user-images.githubusercontent.com/104946677/174683594-0ee95786-7ef1-4f78-9fa4-713977c0f9d8.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/104946677/174683629-8bd6c2eb-7030-4712-85b0-ad7d9d6ec097.png">

**Comment by bush4u** [comment]
Kindly remove the quote around the dates. That should work

**Comment by Hassan-Abbas-SQA** [comment]
@bush4u you can see simple without date and with tasks are being created but does not show at ticktick account but it was working fine last night for me but not now
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/104946677/174834602-bbc74d51-566d-4441-9863-dba7b8959869.png">
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/104946677/174835800-c6a9707e-edf5-4002-a870-1bbb4498fb17.png">

**Comment by dannyroosevelt** [comment]
This is ready for release!
