### ISSUE TITLE
[FEATURE] Support 32-bit ARM, Linux for Pipedream CLI

### ISSUE THREAD

**Issue by DAVE4547** [PipedreamHQ/pipedream#305]
**Is your feature request related to a problem? Please describe.**
No it isn't 

**Describe the solution you'd like**
Support for the cli on rasbian. I believe this is ARMv7 or a 32bit system for the rasberry pi

**Do you have a workaround?**
No

**Additional context**
In the documentation it said if your os architecture isn't supported make a request here.

**Comment by DAVE4547** [comment]
The first command returns `command not found`
And the second command returns `armv7l`

**Comment by dylburger** [comment]
Got it, thanks. Re: the first command, try just `uname` and let me know what that returns.

**Comment by DAVE4547** [comment]
Uname just returns `Linux`

**Comment by dylburger** [comment]
Thanks. Working on a fix.

**Comment by dylburger** [comment]
@DAVE4547 would you mind trying to install the CLI one more time?

```bash
curl https://cli.pipedream.com/install | sh
```

**Comment by DAVE4547** [comment]
I am getting a permission denied error even when running it with such so probably my end.

I will catch this up in the morning as it is late for me.

**Comment by dylburger** [comment]
No worries. This install script tries to install the CLI to `/usr/local/bin/`, so you'll need write / execute permissions for that directory.

You can also try manually downloading the CLI for your OS / arch at https://cli.pipedream.com/linux/arm/0.1.15/pd.zip . If you `unzip` that, the `pd` file is our CLI, so you can move that wherever in your `PATH` you keep scripts.

**Comment by DAVE4547** [comment]
Sorry for the delay,
I have found the answerer to the permission problem and the cli is now working, in short I was running curl as sudo not sh.
I explained it a bit better [in this stack exchange post](https://raspberrypi.stackexchange.com/a/116139/123782)

**Comment by dylburger** [comment]
Great, glad you got it working!
