### ISSUE TITLE
[APP] Google Groups

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3054]
**Name of app / service**

Google Groups

**Link to developer documentation**

https://developers.google.com/admin-sdk/directory/reference/rest/v1/groups

**Comment by sirloinofbeef** [comment]
THanks for creating this. Will follow with keen anticipation.

**Comment by bsommardahl** [comment]
I needed this today. I've been blocked before by other google apis that required a scope that's not available in the currently offered apps. I wonder if we could create a generic google api app that allows the user to specify the scopes they need similarly to how we might request an api key for other apps. Don't know if this is possible, but dreaming. 

Anyhow, we definitely need an app for Google Directory API which would allow us to use Google Groups. I need it, so I may build it if no one else has already.

**Comment by sergio-eliot-rodriguez** [comment]
@bsommardahl google directory was released sometime earlier
https://pipedream.com/apps/google-directory
I was revisiting the issue, and notice it handles some google groups functionality. can you see if this help your use case?

also, pinging @malexanderlim for him to review if we will add a Google Groups app separatedly as I've seen elsewhere Google Group can be managed using a couple of other Google APIs (on of those Google Directory)

**Comment by sergio-eliot-rodriguez** [comment]
I'm closing the ticket for Google Groups.

You can manage Google Groups using Google Directory (integration available at https://pipedream.com/apps/google-directory), and Google Identity (tracking on #7139)
