### ISSUE TITLE
[BUG] HTTP API request trigger doesn't allow custom response

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3060]
**Describe the bug**

When creating a workflow triggered by an API endpoint, even when I have the custom response option enabled, the deployed workflow claims `$.respond` is not compatible with this trigger.

**To Reproduce**
1. Create a new workflow
2. Select HTTP API Requests as the trigger
![CleanShot 2022-06-06 at 09 49 17@2x](https://user-images.githubusercontent.com/2694734/172173828-7142e8c8-4cc1-4c26-99cd-bd5381d9e3e5.png)

4. "Return a custom response from your workflow" is already selected
5. Add the default custom response prebuilt action as a step
6. Test & deploy the workflow
7. Open a test event, see that it returns the default response and shows an error:
![CleanShot 2022-06-06 at 09 51 23@2x](https://user-images.githubusercontent.com/2694734/172174140-2893f45a-f560-4f23-9e13-b915fb1fc3e8.png)

**Expected behavior**
I expect the prebuilt HTTP API requests trigger to allow custom responses.

**Additional context**
User report:

https://pipedream.com/community/t/very-simple-http-api-request-fail/2542

**Comment by ctrlaltdylan** [comment]
This bug has been resolved.

**Comment by danpadua** [comment]
@ctrlaltdylan can you post the solution? I'm having the same problem currently. Following the same steps as @dylburger
