### ISSUE TITLE
[BUG] Google Drive upload & replace file actions missing `uploadType` prop

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3062]
**Describe the bug**

The Google Drive API requires the `uploadType` to equal `resumable` or `multi-part` if uploading files over 5mb in size.

However, we're currently not exposing this option in the **Replace File** or **Upload File** pre-built actions.

Specific Google Drive `uploadType` parameter docs:

https://developers.google.com/drive/api/guides/manage-uploads

**To Reproduce**
1. Upload a large file over 5mbs to your workflow
2. Attempt to upload the file to your Google Drive account
3. Receive "File too large" error

**Expected behavior**
I expect to be able to specify a `uploadType` prop on the pre-built action to allow me to upload larger files to Google Drive.

**Screenshots**

![d60ca763eb382297225c84e7d7e7ff7f869784a6_2_1380x752](https://user-images.githubusercontent.com/2694734/172198233-946a7d9b-dc50-42b6-9dff-a1f2ed37be14.png)

**Additional context**
Original user report: https://pipedream.com/community/t/google-drive-replace-file-uploadtype-param/2551/3

**Comment by noahlocke-uw** [comment]
I believe the first statement in the issues is wrong. If `uploadType` is set to `media` then the file must be _less_ than 5MB. Files over 5MB must have an `uploadType` of `resumable` per Google's documentation:

![image](https://user-images.githubusercontent.com/62952615/172254637-9d134f9b-6bba-440a-bd84-a33844abe73a.png)

**Comment by ctrlaltdylan** [comment]
Thanks for the correction @noahlocke-uw !

**Comment by vellames-turing** [comment]
Humm, I was able to upload a 13mb image https://upload.wikimedia.org/wikipedia/commons/3/3d/LARGE_elevation.jpg

**Comment by vellames-turing** [comment]
Sure, np

**Comment by dannyroosevelt** [comment]
This is ready for release!

**Comment by ctrlaltdylan** [comment]
@vellames-turing hoping they will! I've asked them in the community forum for an example, hopefully we can get one or at least they can describe the exact size so we can reproduce.

**Comment by ctrlaltdylan** [comment]
@vellames-turing , @noahlocke-uw describes the file as ~7.5 megabytes and it's a CSV file.

https://pipedream.com/community/t/google-drive-replace-file-uploadtype-param/2551/12

Sounds like it's private data, but I think any file over 5 megabytes _should_ reproduce the bug.

**Comment by vellames-turing** [comment]
Humm, I was able to upload a 13mb image file, probably the problem is with the file or with `csv`

**Comment by noahlocke-uw** [comment]
[0.5MB-raw.csv](https://github.com/PipedreamHQ/pipedream/files/8949744/0.5MB-raw.csv)
[7.5MB-raw.csv](https://github.com/PipedreamHQ/pipedream/files/8949745/7.5MB-raw.csv)

@ctrlaltdylan @vellames-turing I've attached two files. The one that is failing is the 7.5MB csv file. If I do the exact same workflow with the 0.5MB csv file it succeeds. When I attempt to use the 7.5MB csv file using the `uploadType` set to `resumable` I get "Request Too Large" error.

**Comment by vellames-turing** [comment]
Could you please share the raw URL generated by S3 with me?

**Comment by vellames-turing** [comment]
Huummm, it still working for me.
@Hassan-Abbas-SQA could you please try to test these files as well? Maybe there is some specific condition that I cant see

> [0.5MB-raw.csv](https://github.com/PipedreamHQ/pipedream/files/8949744/0.5MB-raw.csv) [7.5MB-raw.csv](https://github.com/PipedreamHQ/pipedream/files/8949745/7.5MB-raw.csv)
> 
> @ctrlaltdylan @vellames-turing I've attached two files. The one that is failing is the 7.5MB csv file. If I do the exact same workflow with the 0.5MB csv file it succeeds. When I attempt to use the 7.5MB csv file using the `uploadType` set to `resumable` I get "Request Too Large" error.

**Comment by noahlocke-uw** [comment]
I'll try an entirely fresh workflow for good measure

**Comment by noahlocke-uw** [comment]
Brand new workflow, same steps, same error:

![image](https://user-images.githubusercontent.com/62952615/174872953-9b90e9f3-4b4f-48bc-b80c-b091d7974470.png)

**Comment by noahlocke-uw** [comment]
But if I take the raw csv data and shave it down to below 5MB:

![image](https://user-images.githubusercontent.com/62952615/174873383-988a5102-3d14-4979-a696-8938b154d59f.png)

**Comment by noahlocke-uw** [comment]
Fixed! I changed the CURL to `--data-binary` and it works now

**Comment by noahlocke-uw** [comment]
FYI before I was using:

`curl --data @data.csv https://pipedream-endpoint.com`

now I'm using

`curl --data-binary @data.csv https://pipedream-endpoint.com`

**Comment by noahlocke-uw** [comment]
yes
