### ISSUE TITLE
Nectar CRM [APP]

### ISSUE THREAD

**Issue by matheusdea** [PipedreamHQ/pipedream#3072]
**NectarCRM / SaaS CRM**

**Link to developer documentation**
https://github.com/ColmeiaSolucoes/nectarcrm-api

Manage contacts
Manage tasks and appointments
Manage sales opportunities

**Comment by dannyroosevelt** [comment]
Hi @matheusdea FYI here is a basic integration for Nectar CRM: https://pipedream.com/apps/nectar_crm/

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by lcaresia** [comment]
@dannyroosevelt I asked for a key to integrate with them, when I have a response I will remove the blocked tag.

**Comment by wygoralves** [comment]
Hey @lcaresia, i'm Wygor, Product Manager at Nectar!

Sign-up here, so I can activate your account to an integration partner account, ok? https://app.nectarcrm.com.br/crm?language=pt-BR&register=true&signUpKey=8d33e279-4e20-4369-b5ea-9320ad7d49fb

If you prefer, you can reach me out at wygor.alves@nectarcrm.com.br

**Comment by lcaresia** [comment]
@wygoralves Thanks for the reply!

I activated my account and will begin the integration!

**Comment by lcaresia** [comment]
**Actions**

- Create Contact
- Create Task
- Create Appointment
- Create Sale Opportunity

**Comment by lcaresia** [comment]
@wygoralves Hello, can you help us with this?
