### ISSUE TITLE
[APP] Amplenote

### ISSUE THREAD

**Issue by weirdalsuperfan** [PipedreamHQ/pipedream#3079]
**Name of app / service**

Amplenote

**Link to developer documentation**

https://www.amplenote.com/api_documentation

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Lack of support is preventing me from building workflows

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

- Trigger for Tasks completedAt
- Insert a task ("Add a content action to the note")

Plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by dannyroosevelt** [comment]
@weirdalsuperfan I've submitted a request for approval to Amplenote, to enable an OAuth integration. I'll let you know as soon as we hear back!

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@weirdalsuperfan we have a basic integration live:
https://pipedream.com/apps/amplenote/

We'll get this added to the backlog to develop the action and trigger you requested, and we'll track that work here: https://github.com/PipedreamHQ/pipedream/issues/3295

**Comment by weirdalsuperfan** [comment]
Thank you!
