### ISSUE TITLE
Oauth2.0 Public Module

### ISSUE THREAD

**Issue by hfreitasbr** [PipedreamHQ/pipedream#3081]
**Name of app / service**
Oauth2.0 Public Module

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No workaround. I need this to some projects we have today.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
The module must allow connection to services that require authentication via Oauth2.0 and lets us enter our own client ID / secret in order to make POST and GET. Of course, we need the instructions to setup the callback url too.

**Comment by sergioeliot2039** [comment]
Hi @hfreitasbr , thanks for the request! We have this already in our backlog, please follow up heref or notifications, if you'd like https://github.com/PipedreamHQ/pipedream/issues/163

Duplicate, closing.
