### ISSUE TITLE
[FEATURE]  Google Task description parameter

### ISSUE THREAD

**Issue by lupionpe** [PipedreamHQ/pipedream#3085]
**Is your feature request related to a problem? Please describe.**
Now when a create a task I am not able to input the description parameter

**Describe the solution you'd like**
Include description parameter

**Do you have a workaround?**
No

**Comparable features in other tools?**
Description on Google Calendar

**Additional context**
No

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by Hassan-Abbas-SQA** [comment]
@alysonturing i still can’t see the description prop 
![image](https://user-images.githubusercontent.com/104946677/176289050-fc27cabd-435a-4182-b099-55268fff2afa.png)
