### ISSUE TITLE
[APP] Verifalia

### ISSUE THREAD

**Issue by ecobisi** [PipedreamHQ/pipedream#3091]
**Name of app / service**

Verifalia

**Link to developer documentation**

Documentation: https://verifalia.com/developers
JavaScript SDK: https://github.com/verifalia/verifalia-js-sdk

**Is lack of support preventing you from building workflows, or do you have a workaround?**

We have a workaround.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

We would like to contribute with some actions and would just need you to create the app and its app file within the repo, please.

Thank you!

**Comment by dannyroosevelt** [comment]
@ecobisi thanks for submitting the request! I've just added Verifalia as an integrated app:
https://pipedream.com/apps/verifalia

You'll see the app directory and corresponding app file in our repo shortly.

By the way, let me know if you'd like to see a different test request in the app's scaffolding or any other changes.

**Comment by ecobisi** [comment]
@dannyroosevelt thank you!

First of all, we would need to change the authentication mechanism for the app, so that it accepts a username / password credentials pair instead of an OAuth token, please.

We would also need to make the following adjustments to the web page, please:

1. change the logo image;
2. change the summary shown sideways;
3. change the sample code.

Is this something we can change by ourselves, maybe by creating a PR somewhere?

Thank you!

**Comment by dannyroosevelt** [comment]
> First of all, we would need to change the authentication mechanism for the app, so that it accepts a username / password credentials pair instead of an OAuth token, please.

When you actually go through the auth process you'll see you enter username/password, which Pipedream then uses to request an access token from Verifalia.

Unfortunately these changes are not user-accessible today, but we plan to address that in the future. Until then, please let me know the changes you'd like to see here (or you can email `integrations@pipedream.com` with the details if you'd prefer).

**Comment by ecobisi** [comment]
I am following up via email, thank you.
