### ISSUE TITLE
[BUG] Wordpress.org - Create Post - [SyntaxError: Invalid regular expression: /^([^\/:<>\*\?"\|]+(?:\/[^\/:<>\*\?"\|]+)?$/: Unterminated group]

### ISSUE THREAD

**Issue by vexersa** [PipedreamHQ/pipedream#3095]
**Describe the bug**
When attempting to create a new post using the Wordpress.org "create_post" step, an error prevents the step from completing correctly. 

**To Reproduce**
1. Create and connect a self-hosted Wordpress site "create_post" action
4. Attempt to run the step and create a new post on the linked Wordpress site
5. You should see error: [SyntaxError: Invalid regular expression: /^([^\/:<>\*\?"\|]+(?:\/[^\/:<>\*\?"\|]+)?$/: Unterminated group]

**Expected behavior**
A new post is created on the linked Wordpress website

**Screenshots**
![image](https://user-images.githubusercontent.com/7994227/172699414-120290ac-c73a-495c-b03c-00a99fcd5f77.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 102.0.5005.63 (Official Build) (64-bit)

**Comment by vexersa** [comment]
I've added two sites to Pipedream now, one works, the other doesn't and presents this error.

**Comment by vunguyenhung** [comment]
Hello @vexersa, may I ask for Wordpress version of Site A and Site B? Are they using the same Wordpress version?

**Comment by vexersa** [comment]
@vunguyenhung 

Both sites are v6.0

**Comment by vexersa** [comment]
Thanks for the update let me see if I am able to replicate.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by vexersa** [comment]
I can confirm that this works in the v2 workflow.
