### ISSUE TITLE
[BUG] SOQL Salesforce action broken

### ISSUE THREAD

**Issue by julian-techzip** [PipedreamHQ/pipedream#3098]
**Describe the bug**
SOQL strings that have a '=' in the string break the uriEncoding.  

This is in this component:

https://github.com/PipedreamHQ/pipedream/blob/master/components/salesforce_rest_api/actions/salesforce-soql-search/salesforce-soql-search.mjs

**To Reproduce**
1. Create a new SOQL action.
2. Create a valid SOQL query that has an equals sign in it, e.g.: "SELECT Id FROM Account WHERE Name = 'Jim Bob'
3. Test the action
4. See "invalid JSON"' error
5. Change SOQL string to SELECT Id FROM Account
6. Test the action
7. Notice no error

**Expected behavior**
The action should complete successfully and return the results of SOQL query.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest

**Smartphone (please complete the following information):**

**Additional context**
The issue seems to be the uriEncode function, since it doesn't escape an equals sign?  It only breaks when there's an equals sign in the SOQL query.

**Comment by vunguyenhung** [comment]
Hello @julian-techzip, thank you for bringing this to our attention.

We're aware of the problem and have created a [Github Issue here](https://github.com/PipedreamHQ/pipedream/issues/2671) where we'll provide updates, so please keep an eye on that for updates. Thanks 🙏
