### ISSUE TITLE
[BUG] _Wordpress.org - Create Post_ Autodiscovery failing

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3101]
**Describe the bug**

When attempting to use the  _Wordpress.org - Create Post_ action I receive an error in the underlying `wpapi.js` library claiming autodiscovery failed.

**To Reproduce**
1. Create a new workflow
2. Configure a new _Wordpress.org - Create Post_ action
3. Run the workflow
4. See `Autodiscovery failed` message

**Expected behavior**
I expect to be able to create a post programmatically.

**Screenshots**

![Screenshot 2022-06-08 at 20 37 30](https://user-images.githubusercontent.com/2694734/172862168-50825934-13d8-4c64-82f1-6578a985ff1f.png)

**Additional context**

Example domain: https://niocoin.info

The `/wp-json` endpoint works and is accessible: https://niocoin.info/wp-json

I also verified with a Node.js code step that the autodiscovery works with the underlying `wpapi.js` library:

```javascript
import wpapi from 'wpapi'
// To use previous step data, pass the `steps` object to the run() function
export default defineComponent({
  async run({ steps, $ }) {

    const response = await wpapi.discover( 'https://niocoin.info/' );
    // Return data to use it in future steps
    return response
  },
})
```

**Comment by michelle0927** [comment]
@ctrlaltdylan When you set up your account in Pipedream, did you enter the url as https://niocoin.info or niocoin.info?
<img width="679" alt="Screen Shot 2022-06-09 at 11 35 26 AM" src="https://user-images.githubusercontent.com/10889229/172887161-3b00e2d2-5eb5-45b4-a408-fffcd5d43a8f.png">

**Comment by ctrlaltdylan** [comment]
@michelle0927 good question. This is from a user report in the Slack. I'm not sure if it's configured for the naked domain for includes the protocol.

Which format is the component expecting?

**Comment by michelle0927** [comment]
> @michelle0927 good question. This is from a user report in the Slack. I'm not sure if it's configured for the naked domain for includes the protocol.
> 
> Which format is the component expecting?

Since the instructions show leaving out the protocol, the components expect the url to be the naked domain.
