### ISSUE TITLE
[BUG] When I delete an auth provision for a source that is tied to a workflow, the workflow then 404s when I open it

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3112]
This user may have encountered the same bug: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1654730257845259

Here is my workflow in my personal acct: https://pipedream.com/@danny/log-closed-linear-tickets-to-gsheets-changelog-p_k2CaWjB/inspect

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
