### ISSUE TITLE
Refactor MySQL actions to use additionalProps to support dynamic columns

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3114]
App: `mysql`

Instead of users having to select columns and separately entering an array of values to map to those columns via a separate prop, we should render columns dynamically using additionalProps.

### Actions to update
- Create Row
- Update Row
- Any other actions that pull in columns, but I think that's all of them

**Comment by lcaresia** [comment]
@michelle0927 Can you link the PR here? Thanks!

**Comment by michelle0927** [comment]
> @michelle0927 Can you link the PR here? Thanks!

https://github.com/PipedreamHQ/pipedream/pull/3122

**Comment by dannyroosevelt** [comment]
This is ready for release!
