### ISSUE TITLE
[BUG] Typo on Notion.so App Page

### ISSUE THREAD

**Issue by vexersa** [PipedreamHQ/pipedream#3116]
**Describe the bug**
Small typo on Notion app description page:

"Query Databse..." should be "Query Database..."

**To Reproduce**
1. Go to (https://pipedream.com/apps/notion)
2. See error

**Expected behavior**
"Query Databse..." should be "Query Database..."

**Screenshots**
![image](https://user-images.githubusercontent.com/7994227/173025084-f626db29-9faf-4e72-9537-ddb1d19b0f12.png)

**Comment by zalmanlew** [comment]
@vexersa you can actually create a pull request to fix it
https://github.com/PipedreamHQ/pipedream/blob/master/components/notion/actions/query-database/query-database.mjs

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dannyroosevelt** [comment]
Thanks for flagging, @vexersa, I just pushed out a quick patch for that.
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/173105071-0fdfcb26-555c-4b99-a66e-9a7c656011b6.png)
