### ISSUE TITLE
[BUG] clickup-update-task set watchers to task instead of assignees

### ISSUE THREAD

**Issue by alexander-mart** [PipedreamHQ/pipedream#3129]
**Describe the bug**
`clickup-update-task` action set watchers to task instead of assignees.

https://github.com/PipedreamHQ/pipedream/blob/master/components/clickup/actions/update-task/update-task.mjs

**To Reproduce**
1. Add Clickup → Update Task action to workflow
2. Set `list_id`, `task_id` params
3. Set `assignees` param, for example:
```json
{
  "add": [
    36401380
  ],
  "rem": [
      
  ]
}
``` 
4. Run workflow
5. Assignees ids set to task watchers, not assignees as expected.

**Expected behavior**
set assignees to task from 'assignees' param

**Screenshots**
—

**Desktop (please complete the following information):**
—

**Smartphone (please complete the following information):**
—
 
**Additional context**
—

**Comment by alexander-mart** [comment]
This manual code works correctly:

```js
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    clickup: {
      type: "app",
      app: "clickup",
    }
  },
  async run({steps, $}) {
    // return await axios($, {
    const response = await axios($, {
      url: `https://api.clickup.com/api/v2/task/${steps.trigger.event.body.task_id}`,
      headers: {
        "content-type": `application/json`,
        "Authorization": `${this.clickup.$auth.oauth_access_token}`,
      },
      data: {
        assignees: {
          "add": [
            steps.clickup_users.$return_value.find(user => user.email === steps.rules_config.$return_value.assignee_email).id
          ],
          "rem": []
        }
      },
    })

    return response
  },
})
```

**Comment by alexander-mart** [comment]
:thinking:  May be it is bug on Clickup server side?
Manual code isn't always works :(

**Comment by Hassan-Abbas-SQA** [comment]
@alexander-mart Hello i was trying to reproduce that bug but seems like i can’t get the list of tasks see the screenshots below 
![image](https://user-images.githubusercontent.com/104946677/173883279-fed8b597-40ac-4d85-be40-6ac553e64f8b.png)
![image](https://user-images.githubusercontent.com/104946677/173883315-544d2233-8568-4b95-abad-c78a74b89cbc.png)

**Comment by Hassan-Abbas-SQA** [comment]
@dannyroosevelt confirmed the bug user was facing ,Assignees ids set to task watchers, not assignees as expected.
![image](https://user-images.githubusercontent.com/104946677/173907263-816425f0-49de-4057-84b2-b53331aaafa8.png)

**Comment by Hassan-Abbas-SQA** [comment]
@michelle0927 async function still doesn’t work
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/104946677/176059369-0f2d3606-e4af-4065-9f77-8eda20ffbbdb.png">

**Comment by Hassan-Abbas-SQA** [comment]
@michelle0927 on updating the task (seetting up assignee ) iam getting internal server error 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/104946677/176060206-4c702804-7da7-4512-bdc6-0b52b5f89f4b.png">
