### ISSUE TITLE
Dialpad

### ISSUE THREAD

**Issue by nxndps** [PipedreamHQ/pipedream#3135]
**Dialpad API**

[**Dialpad Developer Reference**](https://developers.dialpad.com/reference)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have a workaround and can write directly however an integration would allow for better authentication support.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Triggers** (Webhook) - Subscriptions for SMS, Call Events, Contact Events, Agent Status
**Actions** - Contact Actions, SMS Actions

**Comment by dannyroosevelt** [comment]
Thanks for submitting the request! It looks like you're reaching out on behalf of Dialpad, is that right? I just submitted a request for an OAuth app, are you able to get that approved?

Then we can get you unblocked to publish built-in actions and triggers for the community if you're interested.

**Comment by dannyroosevelt** [comment]
@nxndps thanks -- I sent a follow up re: refresh logic to Gabriel over email (not sure if that's you or not). Other than that the integration is live: https://pipedream.com/apps/dialpad

Is your team interested in developing built-in triggers and actions so customers can use Dialpad without have to write code? If so, this is the best place to get started: https://pipedream.com/docs/components/#developing-components

Yes re: partner ecosystem, please shoot me an email @ `danny@pipedream.com`.

**Comment by nxndps** [comment]
I will follow up with the team internally from here but yes, having something simple for customers is a goal. The CLI works for this as well. Thanks for the pointer.
