### ISSUE TITLE
[APP] Toggl Track

### ISSUE THREAD

**Issue by weirdalsuperfan** [PipedreamHQ/pipedream#3137]
**Name of app / service**

Toggl

**Link to developer documentation**

https://github.com/toggl/toggl_api_docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Lack of support is preventing me from building workflows

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Triggers for anything related to time entries. I'm not 100% sure what all Toggl has, but things like:

- New time entry
- New time entry started
- Time entry updated

Need to be able to get info about:

- Start time
- End time
- Project name or at least ID
- Time entry description

**Comment by pdapikey** [comment]
Hi @weirdalsuperfan  , there is an integration already done for Toggl Track, see https://pipedream.com/apps/toggl
Note that the Toggl app on the App Store points to Toggl Track endpoints.

@dannyroosevelt Perhaps we should rename this app on the App Store -- Toggl was rebranded to Toggl, see this blog post from the parent company Trackhttps://toggl.com/blog/toggl-rebrand-toggltrack

**Comment by weirdalsuperfan** [comment]
@pdapikey I see...how can I set up triggers to listen for events from Toggl with that? I searched for Toggl under "sources" and it didn't show up. When I try to use the app you linked it starts a draft of a workflow, but it still requires a trigger.

**Comment by sergioeliot2039** [comment]
Thanks for the context.

There are webhooks documentation at Toogl API reference.
Are you able to add the webhook you need to Toogl? If so, [this quickstart](https://pipedream.com/docs/quickstart/#add-an-http-webhook-trigger) should point you in the right direction to set that up.

Btw this is the same user as `pdapikey`,

**Comment by sergioeliot2039** [comment]
We'll also add a ticket to the team's backlog to develop built-in triggers for Toggl so you can enable this more easily moving forward. You can [track that work here](https://github.com/PipedreamHQ/pipedream/issues/3138)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
