### ISSUE TITLE
[TRIGGER AND ACTION] Toggl

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#3138]
App: toggl
https://github.com/toggl/toggl_api_docs
https://github.com/toggl/toggl_api_docs/blob/master/webhooks.md

**Triggers**
New time entry
Time entry started
Time entry updated

**Actions**
Get running time entry
Get time entry details
Get time entries

**Comment by dannyroosevelt** [comment]
This is ready for release!
