### ISSUE TITLE
[BUG] Wordpress.org create user action fails when role is specified

### ISSUE THREAD

**Issue by Clausinho** [PipedreamHQ/pipedream#3139]
**Describe the bug**
Whenever I try to add a role to the specific wordpress "create user" step, I get an error.
Whenever I do not fill out the role, it works. It also fails, when the array is equal to "". 

(the error message is never expanded though, i.e. if the user already exists)
**To Reproduce**
1. add a new wordpress "create_user" action
2. Fill out the required fields + the roles field
3. click test
4. See error [object Object]

**Expected behavior**

- The error message would be visible instead of just the reference to the object
- The user will be created with the specified role

**Screenshots**
success without "roles"
![image](https://user-images.githubusercontent.com/5921903/173567098-3cfae434-d3fd-4137-99e4-543626d05495.png)

error when added roles
![image](https://user-images.githubusercontent.com/5921903/173566073-5967e50c-4f52-4fc7-b58e-3b5c34d7bc29.png)

**Additional context**
Logs when failed:
```
/14/2022, 1:20:55 PM [SyntaxError: Invalid regular expression: /issues(/: Unterminated group]
6/14/2022, 1:20:55 PM Endpoint detected, proceeding despite error...
6/14/2022, 1:20:55 PM Binding to https://shop.foto-dino.de/wp-json/ and assuming default routes
```
case was not tested by https://github.com/PipedreamHQ/pipedream/pull/2757#issuecomment-1124000864
might be related to #2757 and #1522
**Workaround**
if you only need a single role, you can use this setting, which you can find under `/wp-admin/options-general.php`
![image](https://user-images.githubusercontent.com/5921903/173568140-1a7a3d2a-af76-4a12-a24e-44aae5a36c0b.png)

**Comment by Hassan-Abbas-SQA** [comment]
@michelle0927 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/104946677/175666076-f2492fca-64c3-4679-84b4-e4c242ed3194.png">

**Comment by dannyroosevelt** [comment]
This is ready for release!
