### ISSUE TITLE
MySQL authentication instructions reference a broken link

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3140]
**Describe the bug**
The MySQL authentication instructions reference a broken link:

https://dev.mysql.com/doc/connectors/en/apis-php-mysqli.quickstart.html

![Screenshot 2022-06-13 at 15 12 39](https://user-images.githubusercontent.com/2694734/173588330-9a60c746-b4f0-4ead-b4da-c97be8404e3a.png)

** Context **

https://pipedream-users.slack.com/archives/CN1BUB92B/p1655154776428349?thread_ts=1654190791.298959&cid=CN1BUB92B

**Comment by dannyroosevelt** [comment]
@ctrlaltdylan any idea what a good link be to help users connect their MySQL creds? We can update that in the /admin/apps UI.

**Comment by ctrlaltdylan** [comment]
Ah ok, I didn't see this content in the admin apps, but I also expected it to be longer than a sentence.

I think the MySQL documentation is actually pretty terrible.

I think we can write our own:

> These values correspond with your MySQL server.
> * **host** is the IP address or domain to access your MySQL server.
> * **port** is the port, default `3306`
> * **username** the account username to login as
> * **password** the account password to login with
> * **database** the name of the database to open after logging in
> Please note, MySQL must be connectable from [Pipedream's IP address range](https://pipedream.com/docs/workflows/networking/). Otherwise, you'll receive a `Connection Refused` error.

**Comment by dannyroosevelt** [comment]
Updated. Feel free to make any changes you want!
