### ISSUE TITLE
Salesforce new actions and refactor

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#3157]
**Is there a specific app this action is for?**
Salesforce (REST API)

**Please provide a link to the relevant API docs for the specific service / operation.**
## Action
- [Post a Message to Chatter Feed](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/quickreference_post_feed_item.htm)
- [Add Lead to Campaign](https://salesforce.stackexchange.com/a/55419)
- [Add Contact to Campaign](https://developer.salesforce.com/docs/atlas.en-us.238.0.api_rest.meta/api_rest/dome_update_fields.htm)

### Object Type field should be `async options`

On the following actions:

- Find Records
- Find Create Record
- Delete Record

I observed that user need to input the Object Type as string. For example
![image](https://user-images.githubusercontent.com/18277920/173870620-f5ce08f0-b23e-4b24-886e-3be2d898ff36.png)

On Update Record action, I observed that we can allow user to select options
![image](https://user-images.githubusercontent.com/18277920/173870714-3c60195a-9db6-4a5c-8c7e-3208908c3cce.png)

### Object ID field should be `async options`

On the following actions:

- Find Records
- Delete Record

I observed that user need to input the Object Type as string. For example
![image](https://user-images.githubusercontent.com/18277920/173870776-a989a1fc-07f2-48ae-9489-c966a09066db.png)
On Update Record action, I observed that we can allow user to select options
![image](https://user-images.githubusercontent.com/18277920/173870802-bcee665f-010e-40c2-8d34-24db989e5d1a.png)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by bush4u** [comment]
Version error fixed
