### ISSUE TITLE
[APP] Automa

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#3163]
**Name of app / service**
Automa

**Link to developer documentation**
https://docs.automa.site

**Is lack of support preventing you from building workflows, or do you have a workaround?**
https://zapier.com/apps/zapier-chrome-extension/integrations
https://community.zapier.com/product-updates/introducing-the-updated-zapier-chrome-extension-7104

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
https://docs.automa.site/blocks/trigger.html
https://docs.automa.site/blocks/webhook.html
https://docs.automa.site/blocks/javascript-code.html

**Comment by dannyroosevelt** [comment]
@marcelocecin can you tell me more about your use case, so that we can figure out how Automa would fit in?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
