### ISSUE TITLE
When new Twitch clip is created, post message to Discord channel.

### ISSUE THREAD

**Issue by CarefulCrab** [PipedreamHQ/pipedream#3164]
Hi I would like to request a function that posts a message to Discord channels whenever a new clip is created for the Twitch channel specified by the user. Thank you.

**Comment by Hassan-Abbas-SQA** [comment]
@CarefulCrab sir we already have twitch triggers as you can see in the screenshot below and we also have the discord actions to send message to discord channel, you can use combination of this trigger and action to accomplish your task, let me know if this helps
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/104946677/174197351-d7f37f8c-852c-4080-8dfb-ebce9a265574.png">
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/104946677/174197443-25af7fbd-0106-4a0b-bea9-9c39ed334742.png">

**Comment by CarefulCrab** [comment]
Sorry, what I mentioned was that I was looking for a function that sends a message to a Discord channel whenever a new clip is generated by any user on a specific **channel**. In your screenshot containing the "New Clips" option, it says that it "Emits an event when there is a new clip for the **specified GAME**", not specified **CHANNEL**. So I assume the that function is not precisely what I'm looking for, as what I'm looking for is a function that posts a message to a Discord channel whenever viewers create clips on a specified Twitch CHANNEL.
Please, would it be possible for this specific option to be created? Can you help me? In any case, thank you for taking the time to reply to my message.

**Comment by Hassan-Abbas-SQA** [comment]
Hi i have requested on your behalf for the new trigger that you needed here is the ticket link https://github.com/PipedreamHQ/pipedream/issues/3184 you can track of its status
