### ISSUE TITLE
[FEATURE] postgresql custom query to find row

### ISSUE THREAD

**Issue by u007** [PipedreamHQ/pipedream#3174]
**Is your feature request related to a problem? Please describe.**

missing postgresql custom query to lookup data

**Describe the solution you'd like**
find a row in postgresql works, but it only allow single field. there should allow multiple condition. this is another feature request

**Do you have a workaround?**
no work around, abandoned the idea on pipedream

**Comparable features in other tools?**
zapier custom query

**Additional context**
we need custom data from db from multiple table, therefore requires a join with condition coming from another source of data with posibilities of multiple field condition too

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
That’s a very interesting idea. Not today. All contributions are open source and available to all Pipedream users.

**Comment by u007** [comment]
got this error when declaring a method:
```
component create api call responded with status: 500, body: {"error":"unexpected error, please contact support@pipedream.com"}

```
```
methods: {
    queryDb(query) {
      const { Client } = require('pg');
      const { host, user, password, port, database } = this.postgresql.$auth;
      
      // const client = new Client({
      //   host,
      //   database,
      //   user,
      //   password,
      //   port,
      // });
      
      // await client.connect();
      // this.results = (await client.query(query)).rows;
      // await client.end();
    }
  },

```

**Comment by u007** [comment]
if i use the full query, i get other error:
```
parse failure (Expected ";" but found "client" at action.js:664)
```

```
methods: {
    queryDb(query) {
      const { Client } = require('pg');
      const { host, user, password, port, database } = this.postgresql.$auth;
      
      const client = new Client({
        host,
        database,
        user,
        password,
        port,
      });
      
      await client.connect();
      this.results = (await client.query(query)).rows;
      await client.end();
    }
  },
```

**Comment by u007** [comment]
will there be typescript support?

**Comment by u007** [comment]
ok i found the issue was async issue for methods, but im still getting:
```
component create api call responded with status: 500, body: {"error":"unexpected error, please contact support@pipedream.com"}
```

**Comment by dylburger** [comment]
@u007 we support TypeScript components. Take a look at [these docs](https://pipedream.com/docs/components/typescript/).

Re: your error, would you mind creating a PR with your latest code so we can see it? Or share the full code of your component here and the `pd` commands you're using to publish it?

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by Hassan-Abbas-SQA** [comment]
works fine

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/104946677/181261910-d77a7e8c-cd41-451a-9d18-1322760f903c.png">
