### ISSUE TITLE
[BUG] HTTP request error

### ISSUE THREAD

**Issue by anondev-sudo** [PipedreamHQ/pipedream#3176]
I want to make workflow on pipedream to schedule github action using workflow dispatch, but I am getting error.

I used custom_request for it

![image](https://user-images.githubusercontent.com/85408287/174313358-cbf60d19-cc3f-4b60-8fff-b11b198228e4.png)

**Comment by dannyroosevelt** [comment]
@anondev-sudo I think the endpoint you're using probably needs to be `https://api.github.com` instead of `https://github.com`, since that is the web URL, which looks like it's expecting to handle authentication via cookies.

Let me know if that works!

**Comment by anondev-sudo** [comment]
![image](https://user-images.githubusercontent.com/85408287/174439763-571bb708-10ba-43ac-9bd4-954c265f0875.png)
Not really

**Comment by dannyroosevelt** [comment]
That message is coming from GitHub's API and seems to indicate an issue with the URL. Can you share the full URL you're using to make a request? Or you can enable the workflow to share with Support (click the 3 dots at the top right of your workflow, open Settings, then enable the "Support" toggle) and paste the workflow URL here, so we can take a closer look.

**Comment by anondev-sudo** [comment]
Post to `https://github.com/user/repo-name/dispatches/` and  `https://api.github.com/user/repo-name/dispatches/`

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
Hi @anondev-sudo, apologies for the delay -- are you still stuck on this issue, or did you get it resolved?

**Comment by anondev-sudo** [comment]
It still wasn't resolved

**Comment by dannyroosevelt** [comment]
> It still wasn't resolved

Can you go ahead and enable the workflow to share with Support? (click the 3 dots at the top right of your workflow, open "Settings", then enable the "Support" toggle) Then paste the workflow URL here, so we can take a closer look.

Thank you!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
