### ISSUE TITLE
[ACTION] twitter follow 

### ISSUE THREAD

**Issue by fawaf** [PipedreamHQ/pipedream#3185]
**Is there a specific app this action is for?** twitter

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/post-friendships-create

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
