### ISSUE TITLE
WhatsApp

### ISSUE THREAD

**Issue by joelharrison** [PipedreamHQ/pipedream#3186]
I want to build a bridge between chat apps like WhatsApp and my project management app BASECAMP so I don’t have to retrain my people on where to have conversations

**Comment by sergioeliot2039** [comment]
Hi @joelharrison, thanks for the request! We have this already in our backlog, please follow up here for notifications, if you'd like https://github.com/PipedreamHQ/pipedream/issues/2896

As of BASECAMP, you might have seen already our integration at https://pipedream.com/apps/basecamp

There are a few unofficial WhatsApp chat apps available for example:
Chat API for WhatsApp -- https://pipedream.com/apps/chat-api-for-whatsapp
WhatsApp by Online Live Support -- https://pipedream.com/apps/online-live-support

Hopefully they are helpful as a temporarily workaround while we are unblocked. If I recall correctly, the block is related to the Graph API for WhatsApp is not available for third party developers (i.e. Pipedream) to authenticate on behalf of there users.

Duplicate, closing.
