### ISSUE TITLE
[BUG] Can't add event to Google Calendar with date formatted like this: "2022-06-19T15:43:47.274Z"

### ISSUE THREAD

**Issue by Defozo** [PipedreamHQ/pipedream#3188]
**Describe the bug**
I can't add event to Google Calendar with the date: "2022-06-19T15:43:47.274Z".

**To Reproduce**
1. Create a pipe with Google Calendar as action.
2. Select Create Event.
3. Put "2022-06-19T15:43:47.274Z" into Event Date and Event End Date.
4. See the error

**Expected behavior**
I wanted to have created an event in Google Calendar that lasts 0 minutes.
Moreover, I think the variables like eg. "Attendees" should be optional.

**Error:**
```
Error
Bad Request

DETAILS
    at global.handleError (/var/task/common.js:39:40)
```

**Inputs:**
```
Google Calendar Account
me@gmail.com
Calendar ID
Weight measurements
secret@group.calendar.google.com
Event Title
79.3
Event Venue
Kraków
Event Description
{ "problem": "none", "height": 190, "gender": "male", "weight": 72.3, "friendly_name": "Defozo" }
Attendees
[ "me@gmail.com" ]
Event Date
2022-06-19T15:43:47.274Z
Event End Date
2022-06-19T15:43:47.274Z
Time zone
UTC
```

**Comment by DilanAthukorala** [comment]
@Defozo I am able to reproduce this issue - unable to create event with UTC date time format.

**Comment by dylburger** [comment]
Thanks for the request @Defozo . I've added this to the backlog for the team to take a look at.

**Comment by michelle0927** [comment]
@lcaresia Is this the correct PR? - https://github.com/PipedreamHQ/pipedream/pull/3199

**Comment by lcaresia** [comment]
@michelle0927 Yes, I linked now!
