### ISSUE TITLE
[APP] Aircall

### ISSUE THREAD

**Issue by ajedwards** [PipedreamHQ/pipedream#3190]
**Name of app / service**

Aircall

**Link to developer documentation**

https://developer.aircall.io/api-references/

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by raphaelvarieras** [comment]
Use cases:

Triggers:
- new call ended
- new tag added
- new note added

Actions:
- get call

**Comment by sergioeliot2039** [comment]
Hi  @ajedwards, @raphaelvarieras 
I created a separated issue for Aircall components, you can follow there, if you'd like https://github.com/PipedreamHQ/pipedream/issues/3979

**Comment by dylburger** [comment]
We had a bit of back-and-forth with the Aircall team to get the integration working, but we've submitted it for approval from Aircall.

I am not sure if any user can currently authorize the Pipedream app, or if that's gated on approval. @ajedwards @raphaelvarieras feel free to try to connect your account [here](https://pipedream.com/apps/aircall) and let me know if that works. If that fails, I'll update the ticket again once we get through the Aircall approval process.

**Comment by raphaelvarieras** [comment]
Looks like it worked!

**Comment by dylburger** [comment]
Great thanks for confirming. We're track that work at #3979, feel free to follow that for updates.

**Comment by ajedwards** [comment]
Works for me too. Thanks for closing this out!
