### ISSUE TITLE
[BUG] with template for upload CSV

### ISSUE THREAD

**Issue by TapioPM** [PipedreamHQ/pipedream#3191]
**Describe the bug**
CSV upload. Quand on download le csv pour "city" => bug dans les propositions de choix du driver. Agriculture, Forestery and Other Land Use (AFOLU) est déparé en  "Forestery and Other Land Use (AFOLU) et Agriculture"
**To Reproduce**

1. Go to 'Upload csv'
2. Click on 'Download template'
3. Open excel
4. try to select driver

**Screenshots**
![image](https://user-images.githubusercontent.com/100856387/174586910-6db1a5b8-9d78-4183-bd8f-f5666e1f1311.png)

**Comment by dylburger** [comment]
@TapioPM This doesn't look like a bug report for https://pipedream.com, so I'm closing! Let me know if you have a specific issue with Pipedream that we can look into for you
