### ISSUE TITLE
[APP] SSH commands

### ISSUE THREAD

**Issue by DAVE4547** [PipedreamHQ/pipedream#320]
**Name of app / service**
ssh
**Link to developer documentation**
i am sure you are familiar with this
**Is lack of support preventing you from building workflows, or do you have a workaround?**
does not have support
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
being able to run a command on a remote machine

**Comment by dylburger** [comment]
@DAVE4547 we actually have an SSH "app", which allows you enter details of the remote machine. Check out [this workflow](https://pipedream.com/@dylburger/run-a-command-on-a-remote-machine-using-ssh-p_6lCx7L/edit) and let me know if that works for you.

**Comment by DAVE4547** [comment]
My mistake, i must of missed it when i was checking to see if it already existed.

**Comment by dylburger** [comment]
Great, no worries!
