### ISSUE TITLE
Octoparse

### ISSUE THREAD

**Issue by ghost** [PipedreamHQ/pipedream#3201]
**Name of app / service**
Octoparse
**Link to developer documentation**
https://openapi.octoparse.com/en-US/
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
When a new set of data is created add it to a Google Sheet

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @ghost Octoparse is integrated https://pipedream.com/apps/octoparse?via=go
Please follow https://github.com/PipedreamHQ/pipedream/issues/10818 for Octoparse component development progress.
