### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by iRinG-RU** [PipedreamHQ/pipedream#3210]
**Name of app / service** Wildberries

**Link to developer documentation** https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/get_api_v2_orders

**Is lack of support preventing you from building workflows, or do you have a workaround?**Really need no support and a complete guide

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Automate the upload of assembly orders to be sent to the warehouse with notifications.

**Comment by sergioeliot2039** [comment]
HI @iRinG-RU Thanks for submitting your request!

This is Sergio I am a contractor with Pipedream.com and I am collaborating with app integrations.

Regarding your request with Wildberries.ru, I have a couple of questions:
1. Can you confirm the app's website is https://seller.wildberries.ru/login/en?redirect_url=/ ?
See [https://suppliers-api.wildberries.ru](https://suppliers-api.wildberries.ru/swagger/index.html#/Marketplace/get_api_v2_orders) redirects to https://seller.wildberries.ru/login/en?redirect_url=/
My guess is that the integration is not directly from the Wildberries online store https://www.wildberries.ru/ meant for end customers, but from the suppliers/sellers portals, is this correct?

2. Are you able to grant us temporary access to the API so we can verify the authentication implementation?
I can't create an account on Wildberries suppliers/sellers portals because it is required to have a phone numbers for specific region I am not in.

Otherwise you can also try setting up the app here: https://pipedream.com/submit-an-app (this is an early alpha UI, so please let me know if you run into any issues).

**Comment by iRinG-RU** [comment]
<img width="762" alt="Снимок экрана 2022-06-23 214404" src="https://user-images.githubusercontent.com/108010177/175374781-cebd9bea-0dcb-402f-9c33-ccd64fdc9fc0.png">
To get an API key, you need to generate a token in your account settings. I am attaching a screenshot of the window.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by iRinG-RU** [comment]
> Без дополнительной информации, я собираюсь закрыть этот вопрос. Не стесняйтесь снова открыть и добавить больше деталей, если хотите.
What other information is required from me? I answered Sergio's question

**Comment by dylburger** [comment]
Sorry for the issue close @iRinG-RU , this is driven by a workflow. I’ve reopened the issue

**Comment by dannyroosevelt** [comment]
@iRinG-RU here is a basic integration:
https://pipedream.com/apps/wildberries

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by iRinG-RU** [comment]
Good evening! Sorry for the long answer, a lot of work. Let's try your work.
I will be happy to convey your proposal for partnership with Wildberries. Do you have a presentation for a partner?

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by sergioeliot2039** [comment]
Hi @iRinG-RU 
I created an issue for tracking the action that you requested, see it at https://github.com/PipedreamHQ/pipedream/issues/3977
One favor, could you please verify if these are the actions you need?
I saw you indicated

>  Automate the upload of assembly orders to be sent to the warehouse with notifications.

but the API URl you included points to the "List assembly tasks (orders)", which I include in the new issue. Is this the one you need? Note that there are other "upload" related endpoints, such as "Upload prices" (https://suppliers-api.wildberries.ru/swagger/index.html#/%D0%A6%D0%B5%D0%BD%D1%8B/post_public_api_v1_prices)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by alysonturing** [comment]
> Thank you very much for your interest! Sorry for the mistakes in the text, I use an auto-translator. I am answering the questions: Yes, the site https://www.wildberries.ru/ is for the buyer, and https://seller.wildberries.ru/login/en?redirect_url=/ is for sellers. Here is OpenAPI swagger docs https://suppliers-api.wildberries.ru/swagger/index.html. You can use my API token to test some requests eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NJRCI6IjFiMGUxNjg5LWQ0ZDAtNDhkMS04YmZkLTBhZGE5ZWRkYjA2ZiJ9.16vkEY-BuBbPtcWyJ1zFUxKhhRFDE30ZEWe3_exwZ6A. I can give full access to the seller.wildberries dashboard (this is actually not a busyness account, just for a tests)

@iRinG-RU please, can you generate a new access token, this one seems to be expired.

**Comment by Hassan-Abbas-SQA** [comment]
@iRinG-RU can you please provide a fresh access token so that i can test the final things and out this thing to ready for release so you can use it ASAP thanks

**Comment by Hassan-Abbas-SQA** [comment]
@iRinG-RU https://github.com/PipedreamHQ/pipedream/issues/3977 i have moved the ticket for production please use this and let us know if you are facing any kind of problem with that so that we can fix it for you thanks
