### ISSUE TITLE
[FEATURE] Improve JIRA actions and triggers

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#3212]
## The `Transition` prop should allow user to select available transitions
The `transition` prop is requiring user to input the transition manually, for example
![Screen Shot 2022-06-22 at 22 28 32](https://user-images.githubusercontent.com/18277920/175070839-70b53dc3-e3ae-419d-bec5-6d9402c468e6.png)
To have the actions more user-friendly, we need to allow user select the transition from available transitions. Affected actions:
- Create Issue
- Update Issue
- Transition Issue

## Improve `Add attachment to issue`
I observed that we need to add /tmp/ path for the action to work, for example /tmp/file.png. Though in the description we have indicated that we use the file in /tmp folder
![image](https://user-images.githubusercontent.com/18277920/175072028-a47a234b-fcfe-41b5-a164-d9bb02e9afac.png)
1. I suggest that we only require user to input file name: `file.png`. Then in the action code, we build the path `/tmp/file.png`
2. Also I suggest that in the File name description, we should add the link to the doc that guide the user to upload the file to `/tmp` folder (in my case I need to do extensive search to find it). For example: 
”Path of the file in `/tmp` folder to add as an attachment. To upload a file to `/tmp` filter, please follow the [[doc here](https://pipedream.com/docs/code/nodejs/working-with-files/#writing-a-file-to-tmp)](https://pipedream.com/docs/code/nodejs/working-with-files/#writing-a-file-to-tmp)”

## Improve `Update Issue`
The Update Issue action has 2 fields `Update` and `Fields` that requires user to construct JSON
![image](https://user-images.githubusercontent.com/18277920/175072387-f62f23d3-7b05-4c86-941d-59105c997845.png)

It would be more user-friendly if we can include an example (.i.e for Update `{"summary":[{"set":"Updated issue from Pipedream"}],"labels":[{"add":"triaged"}]}'`), and also add link to the doc for user easier to reference 

## Webhook Triggers are not working
Per discussion with @feyzullah, currently, JIRA has a limitation that they only allow one webhook registered at a time per user. So we need to unregister existing webhook before registering new a new webhook, we do not handle this case so the triggers are not working correctly when I tested because my registered webhook is an old one.

To handle this case, we need to request more scopes on JIRA Oauth App regarding Webhooks, specifically:
```
  * [read:jira-work, manage:jira-webhook]
  * [read:webhook:jira, read:jql:jira]
```

cc @dannyroosevelt

### New Event - Failed
I deploy the source using the JQL project = 'TEST'  
![image](https://user-images.githubusercontent.com/18277920/175074970-a469499f-02f4-4aea-81fc-0610f4300e01.png)
I created a new issue “Should emit event again”, but no event were emitted from the Source
![image](https://user-images.githubusercontent.com/18277920/175075041-adb8b790-f93a-41d3-83f6-70d115a6516b.png)

### Issue Created (Via JQL) - Failed
I deploy the source using the JQL project = 'TEST'
![image](https://user-images.githubusercontent.com/18277920/175075385-b75f60f5-a172-4c5f-95e0-c85d1e1efa79.png)
I created a new issue “Should emit event”, but no event were emitted from the Source
![image](https://user-images.githubusercontent.com/18277920/175075434-a0e40ba9-d761-46a1-a14d-f5d3ab091df9.png)
Additionally, I can not delete the source
![image](https://user-images.githubusercontent.com/18277920/175075480-825b4d3b-3067-4e60-a516-dbcec5665794.png)

### Issue Updated - Failed
I deploy the source using the JQL project = 'TEST'
![image](https://user-images.githubusercontent.com/18277920/175075566-8ce4cedc-6490-4d06-9d7d-cd1ba13ee0f3.png)
I updated the issue description and transition, but there is no event emitted on the source
![image](https://user-images.githubusercontent.com/18277920/175075603-9887c602-d695-4218-8c7e-420bc2f50840.png)

### Issue Deleted - Failed
I deploy the source using the JQL project = "TEST"
![image](https://user-images.githubusercontent.com/18277920/175076355-a0ac935f-934d-4f96-a019-483438a33398.png)
I deleted an issue from TEST project, but there is no event emitted on the source
![image](https://user-images.githubusercontent.com/18277920/175076395-69ffa551-e9ae-4199-872a-0099f7274b54.png)

**Comment by dannyroosevelt** [comment]
Great work on this, @vunguyenhung! We'll get those additional scopes added to our integration.

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[JIRA_3309_1341.pdf](https://github.com/PipedreamHQ/pipedream/files/9147143/JIRA_3309_1341.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[JIRA_3309_1341.pdf](https://github.com/PipedreamHQ/pipedream/files/9147145/JIRA_3309_1341.pdf)
