### ISSUE TITLE
[APP] Fedex (BYO OAuth)

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3220]
[This user](https://pipedream.com/community/t/help-connecting-to-fedex-api-via-oauth/2658/3) needs to connect to Fedex with their own OAuth client. We need to develop a Fedex OAuth application that accepts a custom client ID / secret.

**Comment by fantasiummedia** [comment]
Hi @dylburger,

Any update on this? If I can help at all setting this up let me know!

**Comment by dylburger** [comment]
Hi @fantasiummedia , sorry for the delay! I just released a version of the app I'm hoping works for you. I don't have my own FedEx credentials, so I'd love your help testing:

1. Visit https://pipedream.com/accounts
2. Click the button to Connect an App at the top-right
3. Enter the required `client_id` and `client_secret`.

If that works, you should be able to add a new step to a workflow, select the FedEx app, and choose the option to **Use any FedEx API**. This will give you the basic scaffolding for writing Node.js code to connect to FedEx. We should generate a FedEx access token you can use in your workflows, available within the `run` method at `this.fedex.$auth.oauth_access_token`. See [our Node.js docs](https://pipedream.com/docs/code/nodejs/) and our guide on [connecting apps in Node.js](https://pipedream.com/docs/code/nodejs/auth/).

**Comment by fantasiummedia** [comment]
@dylburger no problem at all! I appreciate you getting back to me and am thankful for your help getting this setup.

When I tried to enter in the client_id & client_secret values, I received the following error message:

```
Pipedream failed to connect to your account.

Please reach out to integration-errors@pipedream.com and provide this error ID: a76ed1df9daa4fcd82f1721a34b43737
```

Let me know if you need anything more from me to troubleshoot this!

Daniel

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration

**Comment by dylburger** [comment]
@fantasiummedia Sorry for the automated issue close, and for not getting back to you earlier. I just need to configure the app to support sandbox vs. production clients, and we should have that done soon.

**Comment by fantasiummedia** [comment]
Hey @dylburger, 

Any update on this? Just let me know what you might need from me!

**Comment by dylburger** [comment]
@fantasiummedia Really appreciate your patience. I've added a new `server_type` field that lets you connect to the Fedex Sandbox API server vs. Production. Let me know if that works for you.

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by fantasiummedia** [comment]
@dylburger No problem at all! I am grateful for your help with this, it's been great so far. 

I was able to get connected to our prod FedEx account successfully!

I just received a confirmation response from FedEx indicating a successful ping of their API.

Would I now just use a Node.Js step as you described above to access the data from Fedex?

**Comment by dylburger** [comment]
That's exactly right, you can connect apps [to Node.js steps](https://pipedream.com/docs/code/nodejs/auth/) or [to Python steps](https://pipedream.com/docs/code/python/auth/).

If you find yourself doing the same operations across workflows, you can also [build your own triggers or actions](https://pipedream.com/docs/components/) and even [contribute them to our public registry](https://pipedream.com/docs/components/guidelines/#process), if you're interested.

I'll close this ticket since the core integration is done, but feel free to reach out here or [in the community](https://pipedream.com/support) with any other questions!
