### ISSUE TITLE
[APP] Verdict-as-a-Service (Malware-Scan by G DATA)

### ISSUE THREAD

**Issue by unglaublicherdude** [PipedreamHQ/pipedream#3221]
**Name of app / service**

Verdict-as-a-Service (short VaaS)

**Link to developer documentation**

https://github.com/GDATASoftwareAG/vaas
https://github.com/GDATASoftwareAG/vaas/tree/main/typescript

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I am a developer of the App.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- [Action] Request a verdict

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by jcortes** [comment]
Credentials are pending! We wrote an email to `oem@gdata.de`

**Comment by dannyroosevelt** [comment]
I also requested credential. A basic app integration is live here: 
https://pipedream.com/apps/verdict-as-a-service
