### ISSUE TITLE
Error:  "500" /api/ruler/1/api/v1/rulesv 

### ISSUE THREAD

**Issue by anzejiang** [PipedreamHQ/pipedream#3223]
The /api/rule/1/api/v1/rules interface returns a 500 error and keeps requesting this interface repeatedly

**Comment by anzejiang** [comment]
API returns message :"{"message":"unexpected content type from upstream. expected YAML, got text/html; charset=utf-8"}"

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
