### ISSUE TITLE
[BUG] Google People (Contacts) Authentication not approved

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3226]
**Describe the bug**
When attempted to connect a Google Contacts account, the OAuth handshake is denied.

The app still needs to be approved by Google:

![CleanShot 2022-06-23 at 11 52 18](https://user-images.githubusercontent.com/2694734/175341803-7a9b949a-2a2f-425d-9922-099ae398205e.png)

**Comment by malexanderlim** [comment]
Confirming that as of 6/26, Google Contacts has been verified.
