### ISSUE TITLE
[BUG] JIRA - Can not load new site data when connecting existing account with the new site

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#3228]
**Describe the bug**
When connecting a JIRA account, user will be able to select which site to connect to
![image](https://user-images.githubusercontent.com/18277920/175350687-2eb2cb7e-1418-40c8-a318-d8850802c6e7.png)

After the user select a site, the user expect the JIRA action (.i.e Create Issue) will pull Projects, Issues data related to that site. But when user reconnect the same account but for different site, user still see data (Project, Tasks, etc...) of the previous site.

**To Reproduce**
1. Create an 2 Atlassian accounts (called A and B), create a JIRA site for each account, then create a Project on each site.
2. On account A site, invite account B. Now the account B is eligible for 2 JIRA sites
4. Create a new Pipedream workflow, add HTTP Body Only trigger
5. Add JIRA - Create Issue action, then connect account B for site A
6. Tap into the Project ID field, you should see the Project belonged to site A, for example
![Screen Shot 2022-06-23 at 23 45 15](https://user-images.githubusercontent.com/18277920/175351742-7aacf4ce-dc7c-42fd-9022-2db2487daa00.png)
7. Now tap into the "Connect new account" again, connect account B again, **but this time for site B**
![image](https://user-images.githubusercontent.com/18277920/175351986-181828f4-6733-4f7a-8840-aa8085855684.png)
8. Tap into the Project ID field, observe that the list still show Project belonged to site A

Refer to this video for reproduce steps

https://user-images.githubusercontent.com/18277920/175353079-64632416-38bc-47b7-b791-8634e5fe5e8d.mov

**Expected behavior**
The data shown reflects the site chosen on JIRA Oauth step

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 102.0.5005.115 (Official Build) (x86_64)

**Additional context**
First reported by user [here](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1655999847651219?thread_ts=1655929443.492809&cid=CPTJYRY5A)

**Comment by treestonemedia** [comment]
Thank you @vunguyenhung

**Comment by treestonemedia** [comment]
@vunguyenhung any traction on this?

**Comment by dylburger** [comment]
@treestonemedia Thanks for the ping, we're taking a look right now. I'll update you when I have more info.

**Comment by dylburger** [comment]
@treestonemedia I created [a separate ticket](https://github.com/PipedreamHQ/pipedream/issues/4858) that addresses a fix for this, and I'm prioritizing that on our backlog. I'm going to close this ticket if you don't mind following the other.
