### ISSUE TITLE
[ACTION] Add Update Invoice to the Quickbooks API

### ISSUE THREAD

**Issue by StevenJPx2** [PipedreamHQ/pipedream#3233]
**Is there a specific app this action is for?**
Quickbooks

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice#sparse-update-an-invoice

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by StevenJPx2** [comment]
That's awesome, I would love to do it myself! But how do I integrate it with the current process for Quickbooks?

**Comment by dylburger** [comment]
Yes! Take a look at [these docs](https://pipedream.com/docs/components/guidelines/#process) to see the full process for submitting components. When you open a PR, it'll go to the top of our review queue and someone on the team will take a look and give you feedback.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by StevenJPx2** [comment]
Don't have the time to make a PR for this right now. But anyone else would be welcome to ask to reopen this issue and make a PR till then!
