### ISSUE TITLE
[ACTION] Ticktick search for Projects

### ISSUE THREAD

**Issue by euinor** [PipedreamHQ/pipedream#3238]
**Is there a specific app this action is for?**
This request is for the TickTick app
Currently, with the V1 API, in order to update or complete tasks you need the Project ID. But the V1 API provides no methods to search for Projects (or Tasks for that matter...)

**Please provide a link to the relevant API docs for the specific service / operation.**
There is a V2 API but it is undocumented. For example the following link lists all projects
https://api.ticktick.com/api/v2/projects
There are other wrappers which manage to circumvent this, but I don't know how. For example
Docs for an unofficial python wrapper are here: https://lazeroffmichael.github.io/ticktick-py/

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
