### ISSUE TITLE
[TRIGGER] Ticktick new/updated tasks

### ISSUE THREAD

**Issue by euinor** [PipedreamHQ/pipedream#3239]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Is it possible to add Triggers for the TicktTck integration?
For example, on new tasks, updated tasks, completed tasks etc.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
Sadly the existing V1 API documentation doesn't state how this is done
https://developer.ticktick.com/docs#/openapi

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by dannyroosevelt** [comment]
It doesn't look like TickTick's API supports getting all tasks or webhooks on new task creation / updates, etc.
