### ISSUE TITLE
Ability to view log for failed Python step

### ISSUE THREAD

**Issue by mzrnsh** [PipedreamHQ/pipedream#3248]
When a deployed workflow fails in production, the Python step doesn't show the results section.

Results are included in production, during a successful run, and are included in workflow editor both during successful and failed runs.

Let's deliberately cause an error to see this in action:

## In workflow editor
![image](https://user-images.githubusercontent.com/10742145/175936649-f5ebb8da-9d4f-448c-8fa7-8f220329f34e.png)

## In production
![image](https://user-images.githubusercontent.com/10742145/175936760-abc6e441-dd13-488c-ac17-1d564ce7e6cb.png)

As you see, the results section is missing in production, which makes it much harder to debug issues that happen only in production, like [this one](https://pipedream.com/community/t/a-workflow-runs-fine-when-testing-fails-without-any-helpful-errors-in-production/2638).

**Comment by vunguyenhung** [comment]
Hello @mzrnsh, thanks for raising this issue. I'm able to reproduce your issue
![FireShot Capture 037 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/175978762-6bad3820-12c7-4e7e-8770-23e029c45d3d.png)

We will discuss on your issue. Any updates will be made on this Github issue 🙏

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
