### ISSUE TITLE
[TRIGGER] new following of user

### ISSUE THREAD

**Issue by TanukiFin** [PipedreamHQ/pipedream#3250]
new following of user

**Comment by vunguyenhung** [comment]
Hello @TanukiFin, could you fill in the following section for us to better understand your needs?

**Describe the event source. What app is this for, and what event does the trigger correspond to?**
...
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
...

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
