### ISSUE TITLE
[BUG] Mailjet send_message method is not working

### ISSUE THREAD

**Issue by AlexeyArtemev** [PipedreamHQ/pipedream#3251]
**Describe the bug**
Send_Message method from mailjet action is not working

**To Reproduce**
1. Create a workflow
2. Use a mailjet integration with "Send an e-mail" option
3. See an error after trying to send a mail 

**Expected behavior**
Mail in my mailbox

**Additional context**
```
TypeError
mailjet.connect is not a function
    at Object.client (file:///tmp/__pdg__/dist/code/0907c95835bf347a2fda5a3ef67ba07f0723c304a0c16cfc2e96f3c8851df52c/code/mailjet.app.mjs:53:22)
    at Object.sendMessage (file:///tmp/__pdg__/dist/code/0907c95835bf347a2fda5a3ef67ba07f0723c304a0c16cfc2e96f3c8851df52c/code/mailjet.app.mjs:77:19)
    at Object.run (file:///tmp/__pdg__/dist/code/0907c95835bf347a2fda5a3ef67ba07f0723c304a0c16cfc2e96f3c8851df52c/code/actions/send-message/send-message.mjs:80:31)
    at global.executeComponent (/var/task/launch_worker.js:142:53)
    at MessagePort.messageHandler (/var/task/launch_worker.js:613:28)
```

**Comment by vunguyenhung** [comment]
Hello @AlexeyArtemev, thanks for raising this issue. I can reproduce this bug.
![FireShot Capture 050 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/176213853-e16ba791-126c-4ace-bece-1642b9fa9856.png)

We will add this to our Component backlog and make updates to this issue 🙏

**Comment by dannyroosevelt** [comment]
This is ready for release!

**Comment by AlexeyArtemev** [comment]
The bug remains

**Comment by AlexeyArtemev** [comment]
![image](https://user-images.githubusercontent.com/53113374/176759254-f68f1c3a-65eb-46a6-8b72-47f53132efcd.png)

**Comment by bush4u** [comment]
I think this is a version issue

**Comment by michelle0927** [comment]
> I think this is a version issue

@bush4u You'll need to bump the versions of any components affected by the change that was made in the app file.

**Comment by bush4u** [comment]
Okay. I just did that.

**Comment by bush4u** [comment]
@michelle0927 , I bumped up the minor version, is that okay

**Comment by michelle0927** [comment]
> @michelle0927 , I bumped up the minor version, is that okay

@bush4u Sure. The components won't recognize a change to the app file unless the version is bumped. I assume that's why the error is still there. The component is still using the previous version of the app file.

**Comment by AlexeyArtemev** [comment]
![Screenshot_2022-07-01-20-15-52-748_com.android.chrome.jpg](https://user-images.githubusercontent.com/53113374/176940709-9c4ba114-9b07-40d0-b011-cd13b5943f65.jpg)
👀

**Comment by AlexeyArtemev** [comment]
Sorry, forgot to update
Yet there's another issue
![Screenshot_2022-07-01-20-19-34-292_com.android.chrome.jpg](https://user-images.githubusercontent.com/53113374/176941244-3270ecf1-98c9-4517-85de-3b653e1a9473.jpg)

**Comment by AlexeyArtemev** [comment]
> version

0.0.2

**Comment by dannyroosevelt** [comment]
@AlexeyArtemev Thanks for confirming. I was able to successfully send a message just now using that version of the action:
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/176945325-4c94e74c-5c26-4547-95fb-af01474ec31b.png)

Looking at [Mailjet's documentation](https://dev.mailjet.com/email/guides/send-api-v31/), it looks like a 401 response from their API corresponds to `when API key is suspended`.
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/176945446-e9ffc71b-e074-45d3-af83-54227e870dd1.png)

Can you double-check your API key, and possibly re-connect your account in Pipedream then try again?
