### ISSUE TITLE
[APP] VirusTotal

### ISSUE THREAD

**Issue by runasand** [PipedreamHQ/pipedream#3252]
**Name of app / service**
VirusTotal

**Link to developer documentation**
https://developers.virustotal.com/reference/overview

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Can come up with a workaround that allows me to query the VT API

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Initial functionality that'll allow me to query VT for a hash, an IP address, or a domain would be very helpful

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi there @runasand, sorry about the delay on updating, VirusTotal has been integrated -- https://pipedream.com/apps/virustotal

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
