### ISSUE TITLE
[BUG] Error when creating Dropbox > New File source

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3254]
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/176046888-48f2cce3-b378-46e6-82fa-4243e7aa2146.png)

**Comment by alysonturing** [comment]
Sure, I'm checking...

**Comment by Hassan-Abbas-SQA** [comment]
@alysonturing seems like it is not triggering events for .paper files but rest works fine for me

**Comment by alysonturing** [comment]
@Hassan-Abbas-SQA @dannyroosevelt since it's not working as it should for .paper files, shouldn't we create a new bug for fixing this? feel free to assign it to me if you want

**Comment by Hassan-Abbas-SQA** [comment]
I'm creating a new ticket and assign it to you @alysonturing
