### ISSUE TITLE
[FEATURE] Evaluate custom expression in async options & additionalProps

### ISSUE THREAD

**Issue by js07** [PipedreamHQ/pipedream#3255]
**Is your feature request related to a problem? Please describe.**
When I enter a [custom expression](https://pipedream.com/docs/workflows/steps/using-props/#entering-expressions) for a prop (e.g., `{{steps.trigger.event.id}}`), its value in `async options()` for another prop is the expression string (e.g., `"{{steps.trigger.event.id}}"`) rather than the evaluated expression (e.g., `123454321`).

**Describe the solution you'd like**
When I enter a custom expression for a prop, its value in `async options()` for another prop is the evaluated expression.

- **Current**
<img width="250" alt="async-options-expression-actual" src="https://user-images.githubusercontent.com/19861096/176060877-9d5df7bb-a78a-4325-908c-83a538fc7454.png">

- **Desired**
<img width="250" alt="async-options-expression-desired2" src="https://user-images.githubusercontent.com/19861096/176060883-ed03b4ab-21d6-4939-be28-31929042e178.png">

**Do you have a workaround?**
As a workaround, I can catch any errors in `async options()` and return an empty array, if the options are generated from an API response.

**Additional context**
Also reported in https://github.com/PipedreamHQ/pipedream/issues/3227 in the context of the Notion Update Page action.

**Comment by LoganTraceur** [comment]
I also have this problem. Thanks to the Pipedream team for pointing me to this github issue.
I am very interested to see how it develops

**Comment by andrewjschuang** [comment]
I created a PR #5546 in attempt to make this action usable:

> Add a string[] prop - propertyTypesValues - so users can set values and use this action without additionalProps().
> 
> Is a workaround for https://github.com/PipedreamHQ/pipedream/issues/3255, but doesn't resolve it.

**Comment by harshitjain007** [comment]
Is anyone working on this or can I pick this up?

**Comment by benedict1986** [comment]
Still having the same issue. Please help. Thank you

![image](https://github.com/PipedreamHQ/pipedream/assets/7417859/61e0f628-4516-4889-be6c-0c004440fd5c)

**Comment by andrewjschuang** [comment]
The core issue is still not resolved, but we got a workaround for the Notion Update Page action. More info here: https://github.com/PipedreamHQ/pipedream/issues/8239

**Comment by dannyroosevelt** [comment]
Going to close this issue since I believe the primary use case has been resolved. Happy to re-open if there's a use case.
