### ISSUE TITLE
[APP] pretix (ticketing software)

### ISSUE THREAD

**Issue by DavidKruesemann** [PipedreamHQ/pipedream#3263]
**Name of app / service**
pretix

**Link to developer documentation**
https://docs.pretix.eu/en/latest/api/index.html

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Using Integromat as a workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Examples
- update events: https://docs.pretix.eu/en/latest/api/resources/events.html
- get order details: https://docs.pretix.eu/en/latest/api/resources/orders.html

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/pretix

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @DavidKruesemann 

I know, old request here. The component team will get to build the requested actions. The message from Dylan is automated, feel free author components, ifyou prefer.
