### ISSUE TITLE
[BUG] UTC timezone formatting in "Schedule" trigger timestamp needs a trailing "Z" (iso8601 format)

### ISSUE THREAD

**Issue by jrbrandon** [PipedreamHQ/pipedream#3264]
**Describe the bug**
The [iso8601 page on WikiPedia](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)) states "If the time is in UTC, add a Z directly after the time without a space." However when I select UTC as the timezone in the Schedule trigger the timestamp does not contain the trailing Z. I noticed this when trying to compare this value with the timestamp returned by the Google Drive trigger, which does correctly contain the trailing Z. Screenshots attached. Thank you.

**To Reproduce**
1. Set up a workflow using the "Schedule" trigger.
2. Set the timezone to "Etc/UTC"
3. Generate sample event
4. Look at timestamp in the iso8601 branches, they do not include the trailing Z.

**Expected behavior**
If the time is in UTC, add a Z directly after the time without a space.

**Screenshots**
See below:
![Xnip2022-06-28_12-01-44](https://user-images.githubusercontent.com/1208828/176252036-7857c445-8a76-4800-ae69-ca72cebe280c.jpg)
![Xnip2022-06-28_12-02-58](https://user-images.githubusercontent.com/1208828/176252037-0974e276-6d39-40d7-acf4-20e9dab4aba7.jpg)

**Comment by dylburger** [comment]
`+00:00` is valid UTC according to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601):

> An offset of zero, in addition to having the special representation "Z", can also be stated numerically as "+00:00", "+0000", or "+00"

Different libraries will handle this differently, which is probably why the Google Drive trigger emits the timestamp with a suffix of `Z`. But you should be able to parse this to an accurate UTC timestamp with any ISO 8601-compliant libraries, and both should return the same time.
