### ISSUE TITLE
[TRIGGER] On completed Asana task by tag

### ISSUE THREAD

**Issue by arilei** [PipedreamHQ/pipedream#3266]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
For the Asana app, when a task is completed, but by tag instead of project.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.asana.com/docs/events

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by arilei** [comment]
Thank you for your responses, could you share the code for the asana triggers already done to use as an example when coding my own?
Thank you!

**Comment by dylburger** [comment]
@arilei yes! Take a look at the code [here](https://github.com/PipedreamHQ/pipedream/tree/master/components/asana/sources)

**Comment by arilei** [comment]
Hi team, just to not leave anyone wondering I now understand why that trigger did not exist already. There's a limitation on the Asana side regarding webhooks and events where tasks can only be tracked by project

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by andrewjschuang** [comment]
@arilei thanks for confirming! I am closing this issue due to limitations on the Asana API.
If anything, feel free to reopen or create a new issue!
