### ISSUE TITLE
[BUG] Monday.com - Create Item - "Board ID must be an integer"

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3270]
Bug report from a customer trying to use the *Monday.com - Create Iteam* action:

> I tried to create a workflow by using [Monday.com](http://monday.com/). I got stuck when it asked me to choose Board ID. Then I found out that the Board ID is larger than the largest 32-bit signed int but a trigger on pipedream is still using int. Could you help me to update the variable type of Board ID to make a trigger work properly please? You can also find a screenshot in attachment. Thank you in advance.

## Screenshot

![Screen Shot 2565-06-29 at 17 56 00](https://user-images.githubusercontent.com/2694734/176455530-1709441c-1a47-4466-afb6-6029a892c5e9.png)

**Comment by Hassan-Abbas-SQA** [comment]
@vellames-turing it should return an object instead of only id (complete api reponse)
<img width="998" alt="image" src="https://user-images.githubusercontent.com/104946677/176538171-d8842b7d-d762-4800-b19f-cec6403b0352.png">

**Comment by vellames-turing** [comment]
Changed for all actions

**Comment by Hassan-Abbas-SQA** [comment]
@vellames-turing i can't see any changes 
<img width="998" alt="image" src="https://user-images.githubusercontent.com/104946677/176540276-9da848fb-0edb-4fc0-8fbc-d6053eb3dd97.png">

**Comment by vellames-turing** [comment]
How exactly are you testing? Are you creating a personal action?

**Comment by Hassan-Abbas-SQA** [comment]
checkout to the latest branch code , pd-scripts publish actionName and then create a new workflow and test these are the steps

**Comment by dannyroosevelt** [comment]
This is ready for release!
