### ISSUE TITLE
[APP] Namely

### ISSUE THREAD

**Issue by raphaelvarieras** [PipedreamHQ/pipedream#3272]
**Name of app / service**
Namely

**Link to developer documentation**
https://developers.namely.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No workaround at the moment

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

- Trigger: employee added
- Trigger: employee updated
- Trigger: employee removed
- Action: update employee

**Comment by dannyroosevelt** [comment]
@raphaelvarieras do you have a contact there you can put me in touch with? I don't see any way to create an account so we can configure an OAuth app.

**Comment by raphaelvarieras** [comment]
Yes, I am working on this. My understanding is that Namely might get back to me with the name of a resource who would help building this.

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/namely
