### ISSUE TITLE
[ACTION] Pipedream - Create Subscription

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3281]
**Is there a specific app this action is for?**

Creating a Subscription on a Pipedream account.

**Please provide a link to the relevant API docs for the specific service / operation.**

https://pipedream.com/docs/api/rest/#subscriptions

* [Create a Subscription](https://pipedream.com/docs/api/rest/#listen-for-events-from-another-source-or-workflow)
* [Delete a Subscription](https://pipedream.com/docs/api/rest/#delete-a-subscription)

## Implementation details

We'll create a brand new *Pipedream* app. 

The authentication for this app will be available under `this.pipedream.$auth.api_key` to pass as authentication to the Pipedream API.

**Comment by dannyroosevelt** [comment]
This is ready for release!
