### ISSUE TITLE
Ghost.org (Content API)

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3288]
### App
Ghost.org (Content API)
https://ghost.org/docs/content-api/

### Triggers
- Page published
- Post published

### Actions
- Find author
- Create post

**Comment by jcortes** [comment]
Hi @dannyroosevelt about the triggers I think they are already implemented:
* [post-published](https://github.com/PipedreamHQ/pipedream/blob/master/components/ghost_org_admin_api/sources/post-published/post-published.mjs)
* [page-published](https://github.com/PipedreamHQ/pipedream/blob/master/components/ghost_org_admin_api/sources/page-published/page-published.mjs)

So I think the only missing components would be
* Find author
* Create post

**Comment by dannyroosevelt** [comment]
Thanks Jorge, sorry for the confusion
