### ISSUE TITLE
Box

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3290]
### App
Box
https://developer.box.com/reference/

### Triggers
- New file
- New folder
- New event (the user should be able to pick an event from the activity stream)

### Actions
- Upload file
- Find file
- Create text file

**Comment by GTFalcao** [comment]
@feyzullah have you started working on this issue, or may I start it?

**Comment by feyzullah** [comment]
> @feyzullah have you started working on this issue, or may I start it?

Hi @GTFalcao I started this yesterday
