### ISSUE TITLE
YouTube (Data API)

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3291]
### App
YouTube (Data API)
https://developers.google.com/youtube/v3

### Triggers
Will develop the triggers in https://github.com/PipedreamHQ/pipedream/issues/3487

### Actions
- List videos
- List playlist
- Get channel statistics
- List activities
- Update playlist

**Comment by dannyroosevelt** [comment]
@alysonturing FYI I just added a couple items for you to investigate -- we currently have triggers for the YouTube app, but they are polling and not instant. This is a problem mainly because the Pipedream app on YouTube has a daily quota across all users, so the frequency of polling their API impacts everyone who uses the app on Pipedream.

Let us know if you're able to get webhook or apphook based sources working.

cc @ctrlaltdylan

**Comment by alysonturing** [comment]
@dannyroosevelt got it, I'm going to check this!

**Comment by Hassan-Abbas-SQA** [comment]
@alysonturing @dannyroosevelt  Action: channel_statistics 
<img width="941" alt="image" src="https://user-images.githubusercontent.com/104946677/181016825-de8be78e-9c54-457f-851e-05455df86ca8.png">

**Comment by Hassan-Abbas-SQA** [comment]
@alysonturing this action has missing title field which is required by the api to update the playlist
<img width="941" alt="image" src="https://user-images.githubusercontent.com/104946677/181018805-21ddb5b3-8fae-40d6-a0d9-823c0f5b4d73.png">

**Comment by alysonturing** [comment]
> 

This is weird, the action has title and description but it only shows when you type the playlist id properly, because we use the playlist id to fetch the fields from the Youtube API 

- I believe that it's not working with scope variables (try to write the id and not select it from the previous action)

<img width="778" alt="image" src="https://user-images.githubusercontent.com/103650302/181022317-50ee8664-8193-4e5f-8034-b5a77d858365.png">

**Comment by Hassan-Abbas-SQA** [comment]
@alysonturing got it by adding id manually it worked fine, but why it didn’t work with scope variables? can you please check

**Comment by alysonturing** [comment]
> @alysonturing got it by adding id manually it worked fine, but why it didn’t work with scope variables? can you please check
Started a thread on the slack
https://pipedream-users.slack.com/archives/CPTJYRY5A/p1658844657483729
