### ISSUE TITLE
[BUG] Unable to set up Netlify New Form Submission trigger

### ISSUE THREAD

**Issue by theJenix** [PipedreamHQ/pipedream#3293]
**Describe the bug**
When I attempt to set up a Netlify New Form Submission trigger, it never receives an example event via the web hook, and there is an error in Source log in Pipedream.

**To Reproduce**
1. From the Pipedream left-hand nav bar, click on "Sources"
2. Click on "+ New"
3. In "Search for an App", type "Netlify"
4. Click Netlify in the search box
5. Select New Form Submission (Instant)
6. Select a Netlify account and site with a form (If you creating a new site, choose Next.js Toolbox template)
7. Wait until Pipedream says "Waiting for Event"
9. Submit a new form via Netlify Forms 

**Expected behavior**
A sample form is present in Pipedream, and I can build automation using that form data.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 15.5

**Additional context**
If I look at the logs for the new source, I see the following error:
```
Error: No token supplied
at Object.jwt_decode [as decode] (/var/task/node_modules/jwt-simple/lib/jwt.js:61:11)
at Object.isValidSource (file:///var/task/user/netlify.app.mjs:206:30)
at Object.run (file:///var/task/user/sources/common/webhook.mjs:66:23)
at /var/task/index.js:122:72
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async Runtime.exports.main [as handler] (/var/task/index.js:60:20)
```

I can see a `db.get` action in the logs to get `db["token"]`, and that returns a long alphanumeric string.  I do not see this string or anything like it in the form data that is received from Netlify, though.

**Comment by vunguyenhung** [comment]
Hello @theJenix, thank you for raising this issue! I'm able to reproduce your issue on my side
![FireShot Capture 111 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/176921631-ad673ee6-cbed-42d5-a1d8-c44bd93293c7.png)

![FireShot Capture 110 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/176921598-d666f6e3-4e02-48e3-b697-cfd6066a2a3d.png)

We've added it to our backlog to review, and our team has been notified.
