### ISSUE TITLE
Support passing markdown to Notion components

### ISSUE THREAD

**Issue by nordseo** [PipedreamHQ/pipedream#3298]
**Notion.so**

**[Link to developer documentation: Block-type-object](https://developers.notion.com/reference/block#block-type-object)**

**We would like to be able to format the data sent to Notion with markdown, defined by Notion's block types. No workaround as of yet.**

**Basic markdown formatting for headings, bold, italic, links, line breaks, (etc) would be useful to start. Notion provides an extensive API for formatting (Annotations.) that would be nice to manage in Pipedream but assumed, this requires much more setup.**

**Comment by dannyroosevelt** [comment]
Here is the context [from Slack](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1656682807155879):
>I can't seem to get Notion to accept the markdown I use in the Paragraph Block Type.
>I am not sure how to make sure Notion receives the data as MD. I know that Notion has Annotations and block type, but I'm unsure how to set this in Pipedream.

>We currently only support plain_text in Notion components, since its API requires sending custom objects instead of markdown-formatted text.

**Comment by andrewjschuang** [comment]
There's a lib - [tryfabric/martian](https://github.com/tryfabric/martian) - that looks promising, as [suggested here in Slack](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1656693228968419?thread_ts=1656682807.155879&cid=CPTJYRY5A).
