### ISSUE TITLE
[BUG] I want to select multiple teams from Linear triggers

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3303]
I have to select 1 teamId to watch, but I want to select multiple teamIds. For the [teamId prop](https://github.com/PipedreamHQ/pipedream/blob/master/components/linear_app/linear_app.app.mjs#L25) that is in the current sources, we should use `string[]` type instead of `string[]`.

![image](https://user-images.githubusercontent.com/20780753/176967585-3e31113c-5e76-46c4-8f88-7bb821fe25cb.png)

**Comment by lcaresia** [comment]
@dannyroosevelt There is no way to listen only the selected teams, you just can listen a **specific team** or **all public teams**.

To listen all public teams you just need stay the `Team ID` field empty, I will just explain this in the field description, like this:

`The identifier or key of the team that will be listen, still this empty to listen all public teams.`

What you thing?

**Comment by dannyroosevelt** [comment]
If you can listen to a specific team, can't we write some custom logic to listen to any one of the team IDs the user specifies?

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia on publishing comment-created-instant source
![image](https://user-images.githubusercontent.com/104946677/179299992-11e5a9ab-880a-48d8-8a95-bdfa9ef4f651.png)
