### ISSUE TITLE
[FEATURE] Add icons in drop down menu

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#3305]
**Is your feature request related to a problem? Please describe.**
When a prop uses the `options` property, it would be nice to have an icon inline with each labels. For instance, when choosing in a list of countries, we could have the flags. Currency symbols for currencies...etc
The objective is to make the UI more user friendly.

**Describe the solution you'd like**
[The doc says:
](https://pipedream.com/docs/v1/components/api/#component-api)
> Provide an array to display options to a user in a drop down menu.
> 
> `[]` Basic usage
> Array of strings. E.g.,
> `['option 1', 'option 2']`
> 
> `object[]` Define Label and Value
> `[{ label: 'Label 1', value: 'label1'}, { label: 'Label 2', value: 'label2'}]`
> 
> method Dynamic Options
> You can generate options dynamically (e.g., based on real-time API requests with pagination). See configuration details below.

The solution I'd like is working for `objects[]` only. We could add an optional key alongside `label` and `value` which is `icon`:

> `object[]` Define Label, Value and an optional Icon
> `[{ label: 'Label 1', value: 'label1', icon: 'https://icon1.svg'}, { label: 'Label 2', value: 'label2', icon: 'https://icon2.png'}]`

It's up to you to see which icon format would be supported: `ico`, `svg`, `png`, `jpg`...etc

**Comment by dylburger** [comment]
@LucBerge Since labels support UTF-8, could you prepend the label with a character like:

🇺🇸 USD
🇬🇧 GBP
…

That character set is extensive and offers flags and many other icons, so I’m curious if that would solve your use case.

**Comment by dylburger** [comment]
Yes I hear you. I’m trying to think creatively to see if the existing label model will support. We could support Markdown in labels to also support icons, and more.

**Comment by LucBerge** [comment]
Yep ! This issue is just a feature proposition. Up to you to implement it or not.

**Comment by dylburger** [comment]
For now we've decided this doesn't make sense to implement, but I appreciate the feedback as always
