### ISSUE TITLE
[APP] Google Maps Platform

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#3312]
**Name of app / service**: Google Maps Platform

**Link to developer documentation**: https://developers.google.com/maps/documentation/places/web-service/overview

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by gethubb** [comment]
Excited for this! Thank you.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @nachocab 

This has been previously integrated : https://pipedream.com/apps/google-maps-platform

If you see something missing let us know. Looks like you linked to the Places API, which was implemented, so I'd expect the integrations should be good.

Thanks
