### ISSUE TITLE
[ACTION] Link a YouTube Video in Telegram message

### ISSUE THREAD

**Issue by massettim** [PipedreamHQ/pipedream#3314]
Anyone who posts a video on YouTube and has a community on Telegram.

Should be required only the Telegram information you already have

and the videoId from Youtube https://stackoverflow.com/questions/51956099/how-to-get-video-url-with-youtube-apiv3

**Comment by Hassan-Abbas-SQA** [comment]
@massettim Can you please specify what specific action or trigger that you want that would be very helpful

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by massettim** [comment]
Sure, apologies for my late response I was inspecting further the already connector you have but I will write the details in another issue in case I can't solve my use case.
Thank you very much for your support
