### ISSUE TITLE
add a value to a database in notion, for every tweet like?

### ISSUE THREAD

**Issue by jladams69** [PipedreamHQ/pipedream#3319]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by jladams69** [comment]
I am looking for a method the retrieve the analytics for a tweets likes, retweets, comments and engagements directly into a notion workspace

**Comment by Hassan-Abbas-SQA** [comment]
alright then @jladams69 do you need trigger or an action?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
