### ISSUE TITLE
[Refactor / Improvement] Add GET request to certain Instant Webhook-Based Sources

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3332]
**Problem:**
Many of our webhook-based sources (Telegram Bot for example), require users to manually trigger an eligible event to get picked up by the trigger, in order for a test event to show appear when they're building a new workflow. This is not always obvious to the user, so when they can't figure out how to do this, sometimes they give up.

**Solution:**
We should do this automatically for users whenever possible, by fetching historical data from the relevant GET endpoint on the `deploy()` hook, then on `activate()` we create the webhook like normal (Andrew did this for [Gorgias here](https://github.com/PipedreamHQ/pipedream/blob/67d30c91c1ee7615ea0a85cd579918e3400dfe21/components/gorgias/sources/common/base.mjs), and we already do this for Google Sheets, Slack, and a couple other apps). We should fetch the most recent 25 events and order them in descending order of recency.

**Note**: The shape of the event can be different for the event that arrives via webhook vs. the event retrieved via the REST API. Ideally we should format the events returned from the REST API in the same way as they would normally arrive via webhook, so that the shape of the event emitted from the source is the same in both cases. If this is overly difficult or not possible, please flag that in the appropriate ticket.

**Apps to implement this strategy in** (in rough order of priority):
- [x]  [telegram_bot_api](https://github.com/PipedreamHQ/pipedream/issues/3333)
- [x] [github](https://github.com/PipedreamHQ/pipedream/issues/3334)
- [x] [trello](https://github.com/PipedreamHQ/pipedream/issues/3335)
- [x] [bitbucket](https://github.com/PipedreamHQ/pipedream/issues/3336)
- [x] [jotform](https://github.com/PipedreamHQ/pipedream/issues/3337)
- [x] [stripe](https://github.com/PipedreamHQ/pipedream/issues/3338)
- [x] [webflow](https://github.com/PipedreamHQ/pipedream/issues/3339)
- [x] [microsoft_outlook](https://github.com/PipedreamHQ/pipedream/issues/3340)
- [ ] [discord](https://github.com/PipedreamHQ/pipedream/issues/3341)
- [x] [zoom](https://github.com/PipedreamHQ/pipedream/issues/3342)
- [x] [google_calendar](https://github.com/PipedreamHQ/pipedream/issues/3343)
- [x] [woocommerce](https://github.com/PipedreamHQ/pipedream/issues/3344)

**Comment by andrewjschuang** [comment]
This is implemented in Gorgias [here](https://github.com/PipedreamHQ/pipedream/pull/2974/files#diff-e658b6f8707f232549331c465959d375bca3423885dc6acd2f7a7eb38496da44).
