### ISSUE TITLE
[BUG] QA two event sources

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3345]
Specific issues to investigate:

- The `twitch-new-follower` event source never appears to emit any events, so it might not work correctly. Can someone confirm whether they're able to reproduce the issue? If so, we'll need to fix.
- The `notion-new-database` source appears to throw errors and fail to emit under certain conditions. Can we QA that to make sure it works end-to-end?

**Comment by vunguyenhung** [comment]
Hello @dylburger, I can reproduce those 2 issues on my side

I have compose my findings in the test report here
[BUG_QA_two_event_sources_3345_0930.pdf](https://github.com/PipedreamHQ/pipedream/files/9059867/BUG_QA_two_event_sources_3345_0930.pdf)

---
I have created 2 issues here to track each bug separately, could you check when you have time?
- https://github.com/PipedreamHQ/pipedream/issues/3347
- https://github.com/PipedreamHQ/pipedream/issues/3346

**Comment by dylburger** [comment]
Thanks for reviewing @vunguyenhung , closing this issue!
