### ISSUE TITLE
[BUG] [Source] Twitch: New Follower is not emitting events

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#3346]
**Describe the bug**
The Twitch New Follower event source never appears to emit any events

**To Reproduce**
1. I created 2 Twitch accounts: vunguyenhung and hungvturing
![image](https://user-images.githubusercontent.com/18277920/177676310-d351aa9f-7fb8-47c7-8286-f3484b9ae100.png)
![image](https://user-images.githubusercontent.com/18277920/177676381-2f6c2e93-55b6-4c67-a9bf-f50ab03050f1.png)
2. I created a Source and select hungvturing account, with 1 minute interval
![image](https://user-images.githubusercontent.com/18277920/177676419-b70d5a62-1b3d-40e0-97f4-af52534fbc69.png)
3. On the account vunguyenhung, I follow the account hungvturing
![image](https://user-images.githubusercontent.com/18277920/177676490-dfe24e64-e441-4b7d-9c42-5f2276596f9e.png)
4. Then I waited 5 minutes, but no events were emitted
![image](https://user-images.githubusercontent.com/18277920/177676591-77e09815-3703-48fe-b62c-296411cfc5ab.png)
5. Observing the source log, I saw error logged whenever the source is executed
![FireShot Capture 199 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/177678224-dbb09dbb-0e00-4ad1-857d-7621f4e0f5b4.png)
6. Additionally, I can not run `pd dev` on Twitch: New Follower source, even though I have run `pd logout` and `pd login` again
![image](https://user-images.githubusercontent.com/18277920/177676900-9550ae1f-8645-4838-93c0-ca9a5b0850fe.png)

**Expected behavior**
- After deploying the source, I should see the initial events (per [Danny suggestion here](https://github.com/PipedreamHQ/pipedream/issues/3332))
- And when I have a new follower on Twitch, I should see a new event emitted with the new follower information

**Comment by dannyroosevelt** [comment]
> @vunguyenhung cc: @dannyroosevelt the implemented api has been deprecated. the new API needs the "APP access token" to creates the webhooks, do you know how we could do that? https://dev.twitch.tv/docs/api/reference#create-eventsub-subscription

Ah I see. I'm looking into this.

**Comment by dannyroosevelt** [comment]
Do you know if there are other sources or actions that we have that require app access tokens?

It looks like we're going to have to break those components out into a separate app here: 
https://pipedream.com/apps/twitch_developer_app/

Can you go ahead and make that change as a part of this ticket @luancazarine?

**Comment by luancazarine** [comment]
@dannyroosevelt I found a way to fix this without a webhook. So the new app twtich_developer_app is no longer needed to this issue. What do you prefer, deploy both or keep the first one, once the others sources don't use webhook either

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt I found a way to fix this without a webhook. So the new app twtich_developer_app is no longer needed to this issue. What do you prefer, deploy both or keep the first one, once the others sources don't use webhook either

Oh, ok, so you don't need to use the app access token if you aren't using a webhook? What was the workaround?

**Comment by luancazarine** [comment]
> 
I used the same pattern as the other sources, it does a get on user follows filtering by id

**Comment by luancazarine** [comment]
> > @dannyroosevelt I found a way to fix this without a webhook. So the new app twtich_developer_app is no longer needed to this issue. What do you prefer, deploy both or keep the first one, once the others sources don't use webhook either
> 
> Oh, ok, so you don't need to use the app access token if you aren't using a webhook? What was the workaround?

I used the same pattern as the other sources, it does a get on user follows filtering by id

**Comment by dannyroosevelt** [comment]
Ok great! Yea go ahead and keep it on the original `twitch` app, and ignore the new developer one.
