### ISSUE TITLE
[BUG] QA Zoho CRM components that use `@pipedream/platform` axios

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3351]
A user reported [an issue with a Zoho CRM source](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1657164953938499) in public Slack. I noticed we were using `@pipedream/platform` axios in the event source and passing `this` to the first argument in the `listModules` method ([see this diff](https://github.com/PipedreamHQ/pipedream/pull/3349/files)), but passing `this` in sources to `@pipedream/platform` axios generally will not work (it only works in component actions).

Can someone QA the methods using `@pipedream/platform` axios in sources and correct the instances to use standard `axios`, as well?

**Comment by andrewjschuang** [comment]
We are using `this` as a fallback if `$ is null`; it should just ignore and not break anything. I think the error that happened in the Zoho Source is because `@pipedream/platform/axios` already extracts `data` and returns it.

So this code would not have data defined:
`const { data } = await axios(this, config); // @pipedream/platform`

It should have been:
`const data = await axios(this, config); // @pipedream/platform`

**Comment by andrewjschuang** [comment]
I've recently updated `@pipedream/platform` axios [here](https://github.com/PipedreamHQ/pipedream/blob/master/platform/lib/axios.ts#L116) (v1.0.0). If `this` is passed as the `step` in a source, it will just append the message to `this`, doing nothing.

It could make sense to change the function to:
```js
if (step && step.export) {
  step.export(key, message);
  return;
}

console.log(`key: ${key} - ${message}`);
```

**Comment by andrewjschuang** [comment]
Looking at the history of these components, they were legacy-converted that used standard `axios` and were updated to use `@pipedream/platform/axios`. There seems to be some inconsistencies in the way `data` is being handled, so it would be great if these components were QA'd. Moving to QA column

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Zoho_CRM_3417.pdf](https://github.com/PipedreamHQ/pipedream/files/9103438/Zoho_CRM_3417.pdf)
