### ISSUE TITLE
[TRIGGER] Random item from RSS feed

### ISSUE THREAD

**Issue by bigMzz** [PipedreamHQ/pipedream#3354]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Just need a random item selection from rss feed items. doesnt matter when it is posted or anything. just a random selection for every X minutes.
it will be very useful for telegram bots which needed to post something from a feed daily or hourly

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
