### ISSUE TITLE
[BUG] Airtable - Update Record - "Unknown configuration error"

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3365]
**Describe the bug**
When using the Airtable "update_record" action, I often get "Unknown configuration error - please refresh fields and try again."

**To Reproduce**
Steps to reproduce the behavior reported by the [customer](https://app.frontapp.com/open/msg_11so5x3b):

* Error appears to occur after selecting Table, and will occur indiscriminately across selecting multiple tables
* Issue appears to occur only at the update_record step; other Airtable steps do not have the same issue (i.e. get_record, trigger step, etc). 
* I have update_record working in previous workflows with the same Airtable API key; one of the workarounds I use is copying a workflow that works and building around the step. 

**Expected behavior**
I expect to be able to use the *Update Record* Airtable action.

**Comment by vunguyenhung** [comment]
Hello @ctrlaltdylan, regarding this issue, I can't reproduce this issue on my side as I record my interaction here. Could you advice how to reproduce this, or could you connect me to the customer on Pipedream Users Slack? (I can not register account on Front app)

https://user-images.githubusercontent.com/18277920/178967258-9119cf34-6fbf-4ead-845c-ae4c471d5875.mov

**Comment by vunguyenhung** [comment]
Since I couldn't reproduce this issue on my side, I've asked @jcortes to verify this issue and it passed on his side. So I will move this to ready for release!
