### ISSUE TITLE
[APP] SMTP2GO

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3385]
https://apidoc.smtp2go.com/documentation/#/README

[Original request from Discourse](https://pipedream.com/community/t/add-service-smtp2go/2772).

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
This app has been submitted for approval

**Comment by sergioeliot2039** [comment]
Just in case someone needed this in the future, here is SMTP2GO app integrated -- https://pipedream.com/apps/smtp2go
