### ISSUE TITLE
[APP] Degreed

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3386]
https://developer.degreed.com/docs/getting-started-with-the-api

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
This app is blocked for my App project directions on two reasons, it requires an Oauth integration. Plus, can't create an account upfront, a demo must be requested first. I added app metadata to the App list sheet.

**Comment by dannyroosevelt** [comment]
@dylburger was this requested by a user? It's live here but untested: https://pipedream.com/apps/degreed/

**Comment by dylburger** [comment]
Yes this was, thanks
