### ISSUE TITLE
Expensify

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3399]
### App
Expensify
https://integrations.expensify.com/Integration-Server/doc/

### Triggers
- New report
- New expense

### Actions
- Create single expense
- Export report to PDF
- Find report
- Update an employee

**Comment by raphaelvarieras** [comment]
Adding "New expense" to the list of triggers may be a good idea as well.

**Comment by dannyroosevelt** [comment]
> Adding "New expense" to the list of triggers may be a good idea as well.

Yep that's already on there.
