### ISSUE TITLE
Namely

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3400]
### App
Namely
https://developers.namely.com/docs/namely-api/ZG9jOjgwMzMxNjE-introduction

### Triggers
- New employee
- Employee info updated

### Actions
- Create employee
- Update employee
- Find employee

**Comment by dannyroosevelt** [comment]
Note I'm working on getting this app integrated, so we're blocked until that's done. Tracking that [here](https://github.com/PipedreamHQ/pipedream/issues/3272).

**Comment by raphaelvarieras** [comment]
I believe we should also introduce an "Update employee" trigger.

**Comment by dannyroosevelt** [comment]
> I believe we should also introduce an "Update employee" trigger.

To confirm, you'd want to trigger on when employee info is updated?

**Comment by dannyroosevelt** [comment]
Confirming this is ready for development. To the dev who picks this up -- I have a sandbox environment I can get you access to.
