### ISSUE TITLE
[FEATURE] Add Course Scope to Google Classroom

### ISSUE THREAD

**Issue by abaskin** [PipedreamHQ/pipedream#3406]
**Is your feature request related to a problem? Please describe.**
Currently the available Google Classroom scopes do not include the Course scope. This does not allow querying Classroom for the available Courses to getting information for a given Course.

**Describe the solution you'd like**
Add the Course read.only scope to the available scopes for the integration.

**Do you have a workaround?**
Is it possible to keep track of the Course ID's or aliases in a location outside of Classroom, but this requires this data to be kept in sync with the actual Classroom data. 

**Comparable features in other tools?**
Other Classroom integrations do allow access to the Course information. For example Quizizz or Assistments.

**Additional context**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
Thanks for the request @abaskin. FYI changes to Google apps require a lengthy approval process, so I can't provide an ETA for you at this time.

**Comment by malexanderlim** [comment]
Hi @abaskin , I wanted to confirm that the scope https://www.googleapis.com/auth/classroom.courses.readonly is in place here.
