### ISSUE TITLE
[BUG] [TRIGGER] Dropbox: New Files does not emit events for all new files when uploaded in bulk

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#3407]
**Describe the bug**
When uploaded 52 files in bulk into a Dropbox folder (select all 52 files, then drag & drop it to Dropbox UI), I only see 26 events emitted

**To Reproduce**
1. Access Pipedream UI > Sources 
2. Create a new Dropbox: New file source
3. Connect with your Dropbox account, connect to a Folder, set Recursive = false; Include Media Info = false; Include Link = false. Then enable the Source
![FireShot Capture 237 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/178472317-70ddbabd-4346-4304-b4a1-f1ca03c699f0.png)
5. On your Dropbox UI, access the Folder, then create 52 images, then drag & drop then into the folder to start uploading in bulk
![FireShot Capture 238 - Projects - Dropbox - www dropbox com](https://user-images.githubusercontent.com/18277920/178472214-77a647b8-7f22-4acc-a0d2-f8d722d10310.png)
6. Observe that on the Dropbox: New file source, only 26 events were emitted
![FireShot Capture 237 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/178472459-d8bb97cf-3b5f-42f5-9ce4-671cb4332895.png)

**Expected behavior**
There's event emitted for every file uploaded. Expectedly there will be 52 events for 52 files uploaded in bulk

**Comment by alysonturing** [comment]
I opened a thread on slack for discussing the solution to this bug, [see here]( https://pipedream-users.slack.com/archives/CPTJYRY5A/p1657721041510379) so far I had no luck

**Comment by ESadouski** [comment]
Hey, @alysonturing. Seems it still not working. Did you find a workaround?

**Comment by malexanderlim** [comment]
Hi @kamil6x , I've tested just now to try to validate whether this is still an issue, and I was not able to reproduce the error. I tested first with 50 files, then 400 files and the trigger did not miss any.

To help me diagnose the problem further, can you share the following info:

1. How many files are in the folder that you're watching? Currently, with Dropbox limits you can only watch for new files in a Dropbox folder if the folder has less than 4000 items in it. This is a limitation on the Dropbox side.
2. How many files were you uploading at once, and roughly how large was the upload?

**Comment by kamil6x** [comment]
Pardon the late reply. The folder had 10 files in it. I moved to google drive the the code is working fine. (doesn't miss any files).

**Comment by malexanderlim** [comment]
Thanks @kamil6x , I'll consider this bug closed for now as I cannot reproduce it and it sounds like it is no longer an issue for you either.
