### ISSUE TITLE
[SCOPE] Add scopes to Jira integration

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3432]
Add `read:sprint:jira-software` to Jira scopes

From a user [on Slack](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1657737498043309):

> Hi, Im' trying to connect with Jira through the default Jira connector and it seems that the OAuth has not enough scopes available. We want to list sprints (https://developer.atlassian.com/cloud/jira/software/rest/api-group-sprint/#api-rest-agile-1-0-sprint-sprintid-get) but as soon as we try to do that, we get a 403 . Scope required : read:sprint:jira-software . Is there a way to modify the default OAuth scope ? Is there another way to connect to Jira ? Thanks

**Comment by malexanderlim** [comment]
@triomen , confirming that read/write scopes for sprints have been added to the JIRA integration.
