### ISSUE TITLE
[APP] Propeller

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3433]
**Name of app / service**

Propeller

**Link to developer documentation**

https://documenter.getpostman.com/view/17120068/UVkpPvzT

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

The Propeller team is interested in building out their own components, but we just require an `app` definition to begin.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
@ctrlaltdylan Pierce can you please maybe get that app's main website?
I can't inmediatly find the website, by search Propeller on google (there are several homonyms though).
API endpoints are hosted at https://api.helice.cloud/accounts/create

**Comment by dannyroosevelt** [comment]
> @ctrlaltdylan Pierce can you please maybe ask the user for that app's main website? I can't inmediatly find the website, by search Propeller on google (there are several homonyms though). API endpoints are hosted at https://api.helice.cloud/accounts/create

@sergioeliot2039, Pierce is working with the customer / app developer directly, so he's on this one.

**Comment by ctrlaltdylan** [comment]
The app is listed on the backend, and now instructing them on how to generate the app code scaffolding and their own actions. Thanks!
