### ISSUE TITLE
[BUG] Resend Verification Email Error

### ISSUE THREAD

**Issue by siddharth2798** [PipedreamHQ/pipedream#3438]
**Describe the bug**
The resend verification link button while trying to login to community discourse sends an error.

**To Reproduce**
1. Login to pipedream
2. Click on community
3. Login to discourse
4. Click Resend Email Verification Link
5. You should see the error above the resend button

**Expected behavior**
Should have triggered verification email resend

**Screenshots**
![image](https://user-images.githubusercontent.com/26953573/178972579-d92fced7-3c29-471b-997a-8e0b2514af93.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: v1.40.113 (July 5th, 2022) Upgraded Chromium to 103.0.5060.114.

**Comment by DilanAthukorala** [comment]
@siddharth2798 Thank you for reporting this issue, I am able to reproduce this bug. 
![image](https://user-images.githubusercontent.com/102980146/179020564-44f66657-8ee9-4ac8-a613-1fc291f95cc7.png)

**Comment by dylburger** [comment]
This is fixed
