### ISSUE TITLE
[ENHANCEMENT] Avoid GitHub action failure due to broken pnpm-lock.yaml

### ISSUE THREAD

**Issue by andrewjschuang** [PipedreamHQ/pipedream#3443]
I noticed a few errors occurred in the GitHub Actions because the `pnpm-lock.yaml` file was broken. 
This may have happened due to merges of different branches while both updated the lockfile.

There are two consequences that emerge from this:
1. Broken `pnpm-lock.yaml` on `master`
2. GitHub action fails and components are not published

In order to fix `#2`, we can add the [`--fix-lockfile`](https://pnpm.io/cli/install#--fix-lockfile) tag to avoid the action failure.

For `#1`, I think the lockfile would eventually be corrected after some merges, but we may think of a way to automatically update and commit after (or before) merging with master.

**Comment by andrewjschuang** [comment]
![Screen Shot 2022-07-14 at 10 28 23 AM](https://user-images.githubusercontent.com/15385076/179010042-a9f70139-8415-44c7-b923-2dcefe7df885.png)

**Comment by js07** [comment]
Could we also run `pnpm install` with the `--fix-lockfile` option in the `pre-push`/`post-merge` git hooks so the lockfile is automatically fixed when `master` is merged into a branch?

**Comment by andrewjschuang** [comment]
> Could we also run `pnpm install` with the `--fix-lockfile` option in the `pre-push`/`post-merge` git hooks so the lockfile is automatically fixed when `master` is merged into a branch?

Yep, done

**Comment by vunguyenhung** [comment]
Hello @andrewjschuang, I see that the PR mentioned in this issue is merged. May I ask if we can close this issue? Or what is the next action for this issue?
