### ISSUE TITLE
FTP Upload And Create File

### ISSUE THREAD

**Issue by flyindemon** [PipedreamHQ/pipedream#3445]
**FTP**

**(https://github.com/git-ftp/git-ftp)**

**I Like To See A Feature To Create A File To My FTP Server**

**Uploading Files Creating Files**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Blocked because there is no Rest API nor SDK available.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
