### ISSUE TITLE
[BUG] Can't use Twitter v2 endpoints

### ISSUE THREAD

**Issue by hybridcattt** [PipedreamHQ/pipedream#3451]
**Describe the bug**
The twitter integration doesn't allow to call any of the v2 endpoints. 

Namely I'm trying to use the very useful [get-tweets](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets) endpoint that allows to fetch details for multiple tweets in one go. 

**To Reproduce**
1. Go to any workflow and create a new "Use any Twitter API" step
2. Select the Twitter account to use
3. Replace the example url "https://api.twitter.com/1.1/account/verify_credentials.json" with "https://api.twitter.com/2/tweets?ids=1529414221603037184,14152671018923909194". 
4. Press "Test"
5. See error "Request failed with status code 403"

Full step code to reproduce:

```
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    twitter: {
      type: "app",
      app: "twitter",
    }
  },
  async run({steps, $}) {
    return await axios($, {
      url: `https://api.twitter.com/2/tweets?ids=1529414221603037184,1415267101892390919`,
    }, {
      token: {
        key: this.twitter.$auth.oauth_access_token,
        secret: this.twitter.$auth.oauth_refresh_token,
      },
      oauthSignerUri: this.twitter.$auth.oauth_signer_uri,
    })
  },
})
```

**Expected behavior**
V2 Twitter API can be called the same way v1.1 API can be called, because they share the same OAuth auth. 

**Screenshots**
<img width="825" alt="Screenshot 2022-07-15 at 17 01 09" src="https://user-images.githubusercontent.com/11408899/179250440-1ae7d63a-cf77-4a33-8b68-4fee2df60a57.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.3
 - Browser: Safari 15.4

**Additional context**
To allow v2 endpoints, the Twitter app needs to be configured to allow so. This should be a simple fix in the Twitter Developer dashboard.

**Comment by vunguyenhung** [comment]
Thank you for raising this issue @hybridcattt, I can reproduce your issue
![FireShot Capture 351 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/179560946-56d5c7d7-0f2a-468b-84a9-b5c69f472191.png)

I noticed that we already have [a Github issue to migrate our existing Twitter actions (also the Any Twitter API) to Twitter V2](https://github.com/PipedreamHQ/pipedream/issues/2531), could you subscribe to that Github issue for updates?

----

Hello @dannyroosevelt, I think we can prioritize the Github issue https://github.com/PipedreamHQ/pipedream/issues/2531, as there's a customer requesting it now

**Comment by sparkyfen** [comment]
Was there an example on how to invoke the V2 APIs using Pipedream's workflow?

**Comment by hybridcattt** [comment]
@sparkyfen  You can take the code from the my post above and try it. Still doesn't work btw.

**Comment by sparkyfen** [comment]
I was able to get a V2 API call working but not with the Twitter integration, just manual.

```
import { axios } from "@pipedream/platform"

export default defineComponent({
  async run({ steps, $ }) {
    const id = 'EXAMPLE_ID';
    const result = await axios($, {
      url: `https://api.twitter.com/2/users/${id}/following`,
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${process.env.TWITTER_OAUTH_BEARER}`,
        'Content-Type': 'application/json; charset=utf-8'
      },
      params: {
        max_results: 1000
      }
    });
    return result.data;
  },
});
```
