### ISSUE TITLE
[BUG] BigQuery Insert Rows doesn't handle JSON string or object entries

### ISSUE THREAD

**Issue by GMoHughes** [PipedreamHQ/pipedream#3458]
**Describe the bug**
The BigQuery Insert Rows app on processing parses the JSON object which prevents user passing in stringified JSON. BigQuery allows for datatypes JSON and string and neither stringified JSON or JSON are handled by this API

**To Reproduce**
1. Try to parse stringified JSON or JSON object as a key-value in the BigQuery API Insert Rows component

**Expected behavior**
Users can pass through stringified JSON objects as string entry values for columns keys in the row object

**Screenshots**
![Screenshot 2022-07-18 at 13 02 41](https://user-images.githubusercontent.com/19388108/179507050-2e1f7e81-6713-4565-b766-8fe5239a3304.png)

**Comment by vunguyenhung** [comment]
Hello @GMoHughes, for the `Rows` prop, you can pass in JSON inside the `{{ }}` tag without using JSON.stringify, for example:
```
{{ [{ "id": 4, "name": "Hung4", "entry": {"name": "test"} }] }}
```

Action I've tested
![FireShot Capture 353 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/179664363-9787e79f-ea3a-4804-bc2e-c4c40592852c.png)

Please let me know if it works for you. Feel free to comment here or ping me on Pipedream Users Slack @Leo for any questions

**Comment by leo** [comment]
Wrong ping!

**Comment by vunguyenhung** [comment]
Sorry sorry, I will make sure to avoid incorrect mention in the future 🙏

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
