### ISSUE TITLE
[BUG] Datadog - New Monitor Event Trigger async options broken

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3459]
**Describe the bug**
The **DataDog - New Monitor Event** doesn't seem to be pulling my account's monitors in the async options.

**To Reproduce**
1. Successfully connect a Datadog account with monitors
2. Wait for monitors to appear in the async options
3. Monitors never appear

**Expected behavior**
I expect the monitors to populate as options.

**Screenshots**

<img width="791" alt="Screen Shot 2022-07-15 at 12 43 18 PM" src="https://user-images.githubusercontent.com/2694734/179518941-2ae6adf9-dcc8-41f6-a31a-f4cba01e9d63.png">

**Additional context**
Email ticket

https://app.frontapp.com/open/msg_121w66pz

**Comment by vunguyenhung** [comment]
Hello @ctrlaltdylan, I can reproduce this issue
![FireShot Capture 352 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/179659665-b34a878a-8d85-4b9e-bfd0-b5be48a8fdce.png)

I observed that the Monitors prop load for quite a while before showing no options. I suspect that the request to Datadog has been timed out or failed.
