### ISSUE TITLE
[APP] Dots (dots.dev)

### ISSUE THREAD

**Issue by kartikye** [PipedreamHQ/pipedream#3467]
**Name of app / service**
Dots

**Link to developer documentation**
https://docs.dots.dev

**Is lack of support preventing you from building workflows, or do you have a workaround?**
We can hit the api endpoint

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
We want to create a payout link (https://docs.dots.dev/docs/payouts/payout_link)

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@kartikye here is a basic integration with Dots: https://pipedream.com/apps/dots_/

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by kartikye** [comment]
I can definitely help with that!

**Comment by dannyroosevelt** [comment]
> I can definitely help with that!

That's great! Let us know if you need any support. By the way, the [#contribute channel in our public Slack workspace](https://pipedream-users.slack.com/archives/C01E5KCTR16) is a great place to ask questions and get help from the community as well as Pipedream Product and Engineering.
