### ISSUE TITLE
[APP] Etherscan API

### ISSUE THREAD

**Issue by fakel** [PipedreamHQ/pipedream#3480]
**Etherscan**

**[Etherscan Docs](https://docs.etherscan.io/)**

Possible triggers and actions:

- Blocks
- Transactions
- Token-scoped transactions
- Wallet-scoped transactions
- Contract-scoped transactions

Note: Etherscan is a famous ethereum blockchain explorer, however, there are multiple other providers with similar APIs (not all are explorers tho), like [Infura](https://infura.io/)

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by Rohit1415** [comment]
index.html error

**Comment by sergioeliot2039** [comment]
Hi @fakel , here is a basic integration -- [Etherscan](https://pipedream.com/apps/ethereum)
