### ISSUE TITLE
WhatsApp Cloud API

### ISSUE THREAD

**Issue by nimsdeveloper** [PipedreamHQ/pipedream#3496]
WhatsApp Cloud Api

(https://developers.facebook.com/docs/whatsapp-business-platform/get-started)

**Comment by sergioeliot2039** [comment]
Hi @nimsdeveloper, thanks for the request! We have this already in our backlog, please follow up here for notifications, if you'd like https://github.com/PipedreamHQ/pipedream/issues/2896

There are a few unofficial WhatsApp chat apps available for example:
Chat API for WhatsApp -- https://pipedream.com/apps/chat-api-for-whatsapp
WhatsApp by Online Live Support -- https://pipedream.com/apps/online-live-support

Hopefully they are helpful as a temporarily workaround while we are unblocked. If I recall correctly, the block is related to the Graph API for WhatsApp is not available for third party developers (i.e. Pipedream) to authenticate on behalf of other users.

Duplicate, closing.
