### ISSUE TITLE
[APP] Razorpay

### ISSUE THREAD

**Issue by AjayS21** [PipedreamHQ/pipedream#3503]
**Name of app / service**
Razorpay

**Link to developer documentation**
https://razorpay.com/docs/api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Trigger - When payment is captured/ When payment is failed/ When is authorized. 
Action - Add in Google sheet and Send Email

**Comment by vunguyenhung** [comment]
Hello @AjayS21, may I ask are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
HI @AjayS21  Thanks for submitting your request!

This is Sergio I am a contractor with Pipedream.com and I am collaborating with app integrations.

Regarding your interest in Razorpay, I have a request:

I see on Razorpay website that it is a service that is available only in India, so technically I can't create an account here because I am not based in India.

Are you able to provide key id and key secret in Test mode for testing the integration? See these instructons from [Generate API Keys🔗](https://razorpay.com/docs/api/authentication/#generate-api-keys)

> Follow these steps to generate API keys:
> 
>1. Log into your [Dashboard](https://dashboard.razorpay.com/signin?screen=sign_in) with appropriate credentials.
>2. Select the mode (Test or Live) for which you want to generate the API key.
> Test Mode: The test mode is a simulation mode that you can use to test your integration flow. Your customers will not be able to make payments in this mode.
> Live Mode: When your integration is complete, switch to live mode and generate live mode API keys. Replace test mode keys with live mode keys in the integration to accept payments from customers.
>3. Navigate to Settings → API Keys → Generate Key to generate key for the selected mode.

Otherwise you can also try setting up the app here: https://pipedream.com/submit-an-app (this is an early alpha UI, so please let me know if you run into any issues).

**Comment by AjayS21** [comment]
Hello,

Firstly, thank you for your response.

Secondly I have used webhook http request and for now the work is done.


Thank you.

**Comment by AjayS21** [comment]
> HI @AjayS21 Thanks for submitting your request!
> 
> This is Sergio I am a contractor with Pipedream.com and I am collaborating with app integrations.
> 
> Regarding your interest in Razorpay, I have a request:
> 
> I see on Razorpay website that it is a service that is available only in India, so technically I can't create an account here because I am not based in India.
> 
> Are you able to provide key id and key secret in Test mode for testing the integration? See these instructons from [Generate API Keys🔗](https://razorpay.com/docs/api/authentication/#generate-api-keys)
> 
> > Follow these steps to generate API keys:
> > 
> > 1. Log into your [Dashboard](https://dashboard.razorpay.com/signin?screen=sign_in) with appropriate credentials.
> > 2. Select the mode (Test or Live) for which you want to generate the API key.
> >    Test Mode: The test mode is a simulation mode that you can use to test your integration flow. Your customers will not be able to make payments in this mode.
> >    Live Mode: When your integration is complete, switch to live mode and generate live mode API keys. Replace test mode keys with live mode keys in the integration to accept payments from customers.
> > 3. Navigate to Settings → API Keys → Generate Key to generate key for the selected mode.
> 
> Otherwise you can also try setting up the app here: https://pipedream.com/submit-an-app (this is an early alpha UI, so please let me know if you run into any issues).

Trigger - When payment is captured/ When payment is failed/ When is authorized.
Action - Add in Google sheet and Send Email

**Comment by sergioeliot2039** [comment]
That's great, I'm glad that you have managed to work around it. Thanks!

**Comment by sergioeliot2039** [comment]
For anyone interested on Razorpay components, please feel free to follow here https://github.com/PipedreamHQ/pipedream/issues/3503

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
