### ISSUE TITLE
Zoho Catalyst and Zoho Cliq

### ISSUE THREAD

**Issue by mallierth** [PipedreamHQ/pipedream#3506]
**Zoho Catalyst and Zoho Cliq**

**https://catalyst.zoho.com/help/api/introduction/overview.html**

https://www.zoho.com/cliq/help/restapi/v2/#cliq_rest_api

**Is lack of support preventing you from building workflows, or do you have a workaround?** I have work arounds but it would be great! 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** AUTH and BOTS!

**Comment by sergioeliot2039** [comment]
Hi @mallierth 
I have created a different GitHub issue for each app you requested here
Please follow status there.
Zoho Catalyst -- https://github.com/PipedreamHQ/pipedream/issues/3888
Zoho Cliq -- https://github.com/PipedreamHQ/pipedream/issues/3889
I have a request, could you please elaborate on the actions and sources you would like to see for them? Once with that information, I will create different tickets for the component developers team to build them. Thanks

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
