### ISSUE TITLE
[ACTION] Set Raindrop.io Title and description

### ISSUE THREAD

**Issue by epicfishgamer** [PipedreamHQ/pipedream#3511]
**Is there a specific app this action is for?**
Raindrop.io
**Please provide a link to the relevant API docs for the specific service / operation.**
https://developer.raindrop.io/v1/raindrops

I made a workflow that triggers when I like a tweet and saves it to Raindrop with a specified title. I eventually achieved this by adding an "update bookmark" step after the "save to raindrop" step. Since idk how to code that myself. I think it would be nice if you could just set the title and description in the "save to raindrop" step. Because I almost would've found it in "update bookmark". The description in the API docs is called "excerpt"

Sorry if this is a dumb request. As a new user this simple thing took me a couple hours to figure out. So I think it will help others in the future.

**Comment by DilanAthukorala** [comment]
Verification completed this is ready for release.
