### ISSUE TITLE
[Appsheet Integration]

### ISSUE THREAD

**Issue by reatcas** [PipedreamHQ/pipedream#3512]
**Name of app / service**
Appsheet

**Link to developer documentation**
[Appsheet Documentation](https://support.google.com/appsheet/?hl=en#topic=11981018)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No, it just could be more versatile to have a direct integration

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Just general triggers adds, updates, deletion

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @reatcas, thanks for the request!

So I collaborate here on Pipedream to add new app requests on our integrations.
I run into an issue trying to work through AppSheet. Do you have access to the API?
I created a free account but although I have access to the API management on the dashboard, I am unable to test it.

Are you able to create a new test app on AppSheet and share with me App Id and Application Access key for testing the integration?

Otherwise you can also try setting up the app here: https://pipedream.com/submit-an-app (this is an early alpha UI, so please let me know if you run into any issues).

**Comment by MultiTech-Visions** [comment]
# Hey everyone;  just thought I would chime in here, as I've got some experience with AppSheet.

As you already noticed, there are a few licensing requirements that might need to be taken into consideration.  For instance, you can't utilize the AppSheet API externally unless you've got an enterprise license.  (Which... isn't the cheapest of options.)
 - This typically prevents most developers from continuing down this path

### FYI: you can ***SEND*** info using the API, but you can't receive it back to the AppSheet API without the enterprise license.

_____
*Just thought I would through that out there while you're testing things.*
 - *Let me know if you have any other questions, happy to help.*

**Comment by sergioeliot2039** [comment]
Thank you @MultiTech-Visions , I was able to try the App Sheet API within AppSheet automations (using a bot and a process containing a webhook task). 

AppSheet integration is now under review by the Pipedream team.

Best,

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergioeliot2039** [comment]
Sorry, that message by Dylan was triggered by an automation. I have reopened the issue.
Appsheet integration is pending approval.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergioeliot2039** [comment]
Hi @reatcas , @reatcas 
Google App sheet has been integrated https://pipedream.com/apps/google-appsheet
let us know if you see any issues

**Comment by reatcas** [comment]
Hi Sergio!

Thank you very much for the support. I will submit the app as soon as possible.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sergioeliot2039** [comment]
René, thanks for getting back to us

AppSjeet was already integrated at https://pipedream.com/apps/google-appsheet

Can you use it on Pipedream just or testing? Having feedback from our end users is much appreciated.
