### ISSUE TITLE
[BUG] Data Store: Add or Update Single Record saves JSON Object Value as String

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3515]
**Describe the bug**
Data Store: Add Update Record saves JSON Object Value as String

**To Reproduce**
1. Create a new Workflow, add the action Data Store: Add or update a single record
2. On the `Value` prop, input the JSON string: `{ "time":"{{steps.trigger.event.time}}" }`
3. Observed that the action is executed successfully
![FireShot Capture 397 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/180737732-0a4b71bd-892c-4efc-b8f8-5b35c3ce65ab.png)
4. But the Key stored is in String
![FireShot Capture 398 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/180738133-880fabd4-8eb6-4149-a843-a5b8968829e6.png)

**Expected behavior**
- The stored value should be parsed and stored as object instead of String

**Additional context**
[First reported by user here](https://pipedream.com/community/t/problem-inserting-a-colon-in-a-string-to-a-data-store/2860)

**Comment by vunguyenhung** [comment]
Hello @dylburger, I can reproduce this bug. I've updated the issue description to add more details and added to our Component backlog.

Kindly check when you have time and edit if needed 🙏

**Comment by andrewjschuang** [comment]
Note: affected actions are:
- add-update-record
- get-record-or-create
- has-key-or-create

Basically, actions that use `parseValue()` function.
