### ISSUE TITLE
[BUG] QA async options on specific components

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3518]
We're seeing the following errors reported for specific components. I would love to see if we could reproduce these issues. If so, can you raise separate tickets and add them to the component backlog so someone can take a look?

**Firebase Admin SDK - Create Document - `collection` prop**

Error: "The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services."

**monday.com - Create an Update - `itemId` prop**

Error: "Failed to list items: Variable boardId of type Int! was provided invalid value"

**Comment by vunguyenhung** [comment]
Hello @dylburger, I've tried to reproduce the issues above, 
- I can reproduce **monday.com - Create an Update - itemId prop** issue. I have created [a Github issue here](https://github.com/PipedreamHQ/pipedream/issues/3525)
![FireShot Capture 400 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/180795474-c7e0fe3a-10e1-4856-ba1f-5a78b5cd8cdb.png)
- I can **not** reproduce **Firebase Admin SDK - Create Document - collection prop**. I suspect that the user have not created a default collection, or user have not enabled Cloud Firestore API. Could you connect me with the customer directly so I can understand his configuration?
![FireShot Capture 399 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/180791061-c872b407-eb2e-417e-9e11-54fa972957b8.png)

**Comment by dylburger** [comment]
Thanks @vunguyenhung , it's good to know the Firebase action works. I saw this across a few workflows but that helps. We should make it clear to users exactly what they need to configure. I'll make sure to include those two items in the app configuration!
