### ISSUE TITLE
[FEATURE] 2FA

### ISSUE THREAD

**Issue by AlexeyArtemev** [PipedreamHQ/pipedream#3522]
**Is your feature request related to a problem? Please describe.**
There is not enough security to have corporate accounts(Notion, Mailchimp, etc.) connected to the pipedream account

**Describe the solution you'd like**
Add a TOTP support(e.g. for Google Authenticator) for authentication on site

**Do you have a workaround?**
No workaround is available at the moment

**Comparable features in other tools?**
It's implemented in most of big apps, but I can't say anything related

**Comment by AlexeyArtemev** [comment]
I can see one closed [thread](https://github.com/PipedreamHQ/pipedream/issues/2037) about 2FA, but afaik there's no 2FA at the moment

**Comment by dylburger** [comment]
@AlexeyArtemev That other issue you referenced is actually open, and that’s the place we’re tracking 2FA support. Please follow that issue and we’ll update that as soon as we ship 2FA support
