### ISSUE TITLE
[BUG] Can't create notion page update trigger without the DB

### ISSUE THREAD

**Issue by AlexeyArtemev** [PipedreamHQ/pipedream#3523]
**Describe the bug**
There is no possible way to save notion page update update trigger without choosing a DB, which is controversal to the trigger description(which says it listens to "page updates", not "database updates")

**To Reproduce**
1. Create a workflow
2. Select Notion page update as a trigger
3. See the fact that it's impossible to create a page listener without the database

**Expected behavior**
Creation of a trigger based solely on a notion page status

**Comment by andrewjschuang** [comment]
Hi @AlexeyArtemev, this trigger will emit events for any page updates in a database, hence the `Database ID` prop. If you select the correct database, then you will receive the event.

I've updated the description to make it more clear.

Thanks for submitting the request!

**Comment by AlexeyArtemev** [comment]
> Hi @AlexeyArtemev, this trigger will emit events for any page updates in a database, hence the `Database ID` prop. If you select the correct database, then you will receive the event.
> 
> I've updated the description to make it more clear.
> 
> Thanks for submitting the request!

So it's impossible to get events from the page itself?

**Comment by andrewjschuang** [comment]
> So it's impossible to get events from the page itself?

You can use [this Filter action](https://pipedream.com/apps/filter/actions/continue-workflow-condition) after the trigger to continue with the workflow only if it's the Page you are expecting.

**Comment by AlexeyArtemev** [comment]
> You can use [this Filter action](https://pipedream.com/apps/filter/actions/continue-workflow-condition) after the trigger to continue with the workflow only if it's the Page you are expecting.

I mean the notion page without the DB(for example, https://equanity.notion.site/6bb0d8655cf44d25993fb11d14456d5e )

**Comment by andrewjschuang** [comment]
> I mean the notion page without the DB(for example, https://equanity.notion.site/6bb0d8655cf44d25993fb11d14456d5e )

I see, so there are pages that aren't inside a database?

**Comment by AlexeyArtemev** [comment]
> I see, so there are pages that aren't inside a database?
More than 800 of such pages)
But we would like to be notified via telegram when the main page and the guide map("карта гайда") are being changed since Notion notifications are not as good as we thought

**Comment by andrewjschuang** [comment]
> More than 800 of such pages) But we would like to be notified via telegram when the main page and the guide map("карта гайда") are being changed since Notion notifications are not as good as we thought

Ok, I submitted a [new trigger request](https://github.com/PipedreamHQ/pipedream/issues/3890) on your behalf. But optionally, as a workaround, you can use the Filter action in the meantime:

![Screenshot from 2022-07-27 15-17-12](https://user-images.githubusercontent.com/15385076/181343967-234ae048-ff2a-478d-a328-e61c5ea4c936.png)

**Comment by vunguyenhung** [comment]
Hello @AlexeyArtemev, I will close this PR as @andrewjschuang has created [another Notion trigger request here](https://github.com/PipedreamHQ/pipedream/issues/3890) to serve your needs. Please subscribe to the new Github issue for updates if you want.

Again thank you for raising this issue 🙏

**Comment by andrewjschuang** [comment]
Hi @AlexeyArtemev, a new trigger for your request was published here:
https://pipedream.com/apps/notion/triggers/updated-page-id

Hope it suits you well.
