### ISSUE TITLE
[BUG] Async props loading indicator and skeleton are still showing even after resolving options

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#3524]
**Describe the bug**
When selecting an async options on any action, the loading indicator and skeleton are still showing even after resolving options

**To Reproduce**
1. Create a new workflow, add SendinBlue: Send transactional email
2. Connect to the SendinBlue account, configure `Template ID`, `Reply To`, and `To` async options
3. Observe the loading indicator and skeleton are still showing even after the options are resolved
![Screen Shot 2022-07-25 at 20 45 47](https://user-images.githubusercontent.com/18277920/180793659-4938fa56-b4aa-4e73-8561-d5437ec8d861.png)

**Expected behavior**
The loading indicator and skeleton are hidden when options are resolved

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
