### ISSUE TITLE
[FEATURE] Action code should live in Github, enabling me to fork and submit PRs for actions

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#353]
All of the code for existing actions, tied to app integrations, should live in Github. This would enable me to easily search and modify the code, submitting contributions back to the community.

**Comment by oliviermills** [comment]
Bump. This would be amazing. Am getting nervous with the amount of coded out of usual source control :-)

**Comment by loicginoux** [comment]
I also woudl prefer to have my code versionned and hsoted in github. 
For inspiration on the UI, the way apify does it for writing their actors could be a solution:
![Screenshot 2020-10-20 at 11 00 53](https://user-images.githubusercontent.com/824936/96564584-a1f45880-12c3-11eb-9270-1015339e37ef.png)

When writting custom code, you have a choice of a zip, a github repository url or directly writing it in the UI via their text editor interface.

**Comment by tlpriest** [comment]
Bump. Would make collaborating with a team simpler and reduce the number of times we shoot ourselves in the foot. I'm personally running out of feet.

**Comment by dylburger** [comment]
This is now possible with the new version of actions! [Check out the docs here](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and let us know if you have any questions / feedback.
