### ISSUE TITLE
[SOURCE] Intercom

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#354]

**Comment by todsac** [comment]
New Closed Conversation | Triggers when you close a conversation. (Note: The "Reply and close" button won't trigger this. New Company | Triggers when a new Company is created.
New Conversation | Triggers when a new conversation is created by a user in Intercom.
New Lead | Triggers when a new Lead is created.
New Unsubscription | Triggers when a user unsubscribes from Intercom.io emails.
New User | Triggers when a new user is created.
Lead Added Email | Triggers when a Lead enters an email address.
Lead Converted to User | Triggers when a lead converts to a user.
Tag Added to Conversation | Triggers when a new tag is added to a conversation in Intercom.
Tag Added to Lead | Triggers when a lead is tagged.
Tag Added to User | Triggers when a user is tagged.
New Reply from Agent | Triggers when an Agent replies to conversation
New Reply from User | Triggers when a user replies to conversation
New Conversation | Triggers when a users starts a new conversation
New Event | Triggers when a specified user event occurs
Internal Note added to Conversation | Triggers when a admin adds a note to a conversation
User Email Updated | Triggers when a user updates their email address
Conversation Assigned to Agent | Triggers when a conversation is assigned to a specific agent
