### ISSUE TITLE
Apify

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3550]
### App
Apify

### Triggers
* Finished Actor Run
* Finished Task Run

### Actions
* Run Actor
* Run Task
* Set Key-Value Store Record
* Fetch Dataset Items
* Get Key-Value Store Record
* Find Last Actor Run
* Find Last Task Run

**Comment by marcelocecin** [comment]
it would be great to have an example of using the [$.flow.rerun](https://pipedream.com/docs/code/nodejs/rerun/#flow-rerun) command with [Ad-hoc webhooks](https://docs.apify.com/platform/integrations/webhooks/ad-hoc-webhooks)
