### ISSUE TITLE
ChartMogul

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3582]
### App
ChartMogul

### Actions
* Add a Custom Attribute to a Customer via Email
* Add a Custom Attributes to a Customer via External ID
* Add a Custom Attribute to a Customer via UUID
* Add Tags to a Customer via UUID
* Add Tags to a Customer via Email
* Add Tags to a Customer via External ID
* Create a Customer
* Merge Customers
* Update a Customer
* Search for Customer via Email
* Search for Customer via External ID
* Retrieve a Customer Profile
* Retrieve All Key Metrics
* Retrieve Average Revenue Per Account (ARPA)
* Retrieve ARR
* Retrieve Average Sale Price (ASP)
* Retrieve Customer Churn Rate
* Retrieve Customer Count
* Retrieve Customer Lifetime Value (LTV)
* Retrieve MRR
* Retrieve MRR Churn Rate

**Comment by alysonturing** [comment]
https://github.com/chartmogul/chartmogul-node

**Comment by alysonturing** [comment]
I'll resign this task because my trial account was ended. during this time I was working on prioritized tasks.

**Comment by Hassan-Abbas-SQA** [comment]
### Failed TestCase
if it can’t find the customer it should simply show the error message comes from the api intead of failing the action
![image](https://user-images.githubusercontent.com/104946677/209223128-30ac8f78-d25c-4e8f-b4af-70b82318a16f.png)

### Passed TestCases
![image](https://user-images.githubusercontent.com/104946677/209226274-cc4724ee-e5c3-46be-8365-3005a0f5e98b.png)
