### ISSUE TITLE
ClinchPad

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3590]
### App
ClinchPad

### Triggers
* New Lead

### Actions
* Create a lead

**Comment by Hassan-Abbas-SQA** [comment]
TESTPASSED
![image](https://user-images.githubusercontent.com/104946677/212174397-5768d411-ca3a-4471-a928-eba8b916d663.png)
![image](https://user-images.githubusercontent.com/104946677/212174530-676eda54-7d16-451e-bce0-73ac487661bb.png)
