### ISSUE TITLE
Curated

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3602]
### App
Curated

### Triggers
* New Collected Link
* New Published Issue
* New Subscriber
* New Unsubscriber

### Actions
* Add New Collected Link

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there is one failed case that needs improvement. 

Please check the test report below for more information.
[Uploading Curated_3602.pdf…]()

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release!

Test report: 
[Curated_3602 version 2.pdf](https://github.com/PipedreamHQ/pipedream/files/10075214/Curated_3602.version.2.pdf)
