### ISSUE TITLE
Dribbble

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3610]
### App
Dribbble

### Triggers
* New Shot

**Comment by lcaresia** [comment]
For some reason endpoint `POST /shots` don't is working and I can't find a way a solution.
So I will moved to blocked!

Cc: @dannyroosevelt

**Comment by jverce** [comment]
> For some reason endpoint `POST /shots` don't is working and I can't find a way a solution. So I will moved to blocked!
> 
> Cc: @dannyroosevelt

Can you provide more info regarding what's not working specifically?
For instance, what kind of error(s) are you getting, for which payloads, how did you set up the API key on your side, etc.

Thanks @lcaresia!

**Comment by lcaresia** [comment]
Hello @jverce>

I tried many ways to do this request, but here have an example to test.

curl --location --request POST 'https://api.dribbble.com/v2/shots' \
--header 'Authorization: Bearer <Your token here>' \
--form 'image=@"/C:/Users/Lucas Caresia/Downloads/cats.jpg"' \
--form 'title="Title 1"'

**Comment by jverce** [comment]
Thanks @lcaresia 
I got a similar experience when using the API to create shots, so I tried creating them using the Dribbble UI and it worked that way.

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/5479513/202498741-4d18ead3-82f3-4999-a1c4-b0daa4ba6930.png">

(BTW, you can see a rough approach to the **New Shot** source in this branch: https://github.com/jverce/pipedream/tree/dribbble-triggers)
