### ISSUE TITLE
Fibery

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3621]
### App
Fibery

### Triggers
* New Entity
* Entity Updated (Or Created)
* New Type

### Actions
* New Entity
* Update Entity
* Find Entity
* Find or Create Entity

**Comment by andrewjschuang** [comment]
Actions requested by user in #5535:

- Create Entity
- Create Multiple Entities
- List Entities
- Get Entity or Create
- Create Single Entity or Update
