### ISSUE TITLE
GetResponse

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3633]
### App
GetResponse

### Triggers
* New Landing Page
* New Newsletter
* New Contact
* New Form

### Actions
* Create or Update Contact
* Create Contact
* Create Newsletter
* Find List
* Find Contact

**Comment by jcortes** [comment]
Hi @jverce can you be more specific about the `Find List` action please? here it is the [api docs](https://apireference.getresponse.com/?_ga=2.250017859.499257728.1666974700-2116668472.1666974700&_gl=1*8rz7cc*_ga*MjExNjY2ODQ3Mi4xNjY2OTc0NzAw*_ga_EQ6LD9QEJB*MTY2Njk3NzM0Ny4yLjEuMTY2Njk3OTc1Mi42MC4wLjA.) just in case
