### ISSUE TITLE
Gist

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3636]
### App
Gist

### Triggers
* Subscribed to a Campaign
* New Contact
* Tag Added to Contact
* Performed an Event
* Unsubscribed From a Campaign
* Tag Removed From Contact
* Updated a Contact Property

### Actions
* Add Tag to an Existing Contact
* Create or Update Contact
* Remove Tag From Existing Contact
* Subscribe to a Campaign
* Unsubscribe From a Campaign
* Find a Contact

**Comment by vunguyenhung** [comment]
Hello, as @bush4u is no longer working with Pipedream, I will move this Github issue back to TODO and unassign him 🙏

**Comment by luancazarine** [comment]
There are two points on this issue:
To manage campaigns it is necessary to have a premium account, so I will create others.
I contacted support and they said there is no way to handle webhooks via API, only via UI.

**Comment by vunguyenhung** [comment]
Hello @luancazarine, I'm testing this ticket, though I noticed that there're several actions & triggers missing from the implementation, could you elaborate the reason for them?

## Missing Actions
- Subscribe to a Campaign
- Unsubscribe From a Campaign
- Find a Contact 

## Missing Triggers
- Subscribed to a Campaign
- Unsubscribed from a Campaign
- Performed an Event
- Tag Removed from Contact

As I observed in Zapier, the missed actions & triggers were available
Zapier Gist Triggers
![Screen Shot 2022-08-16 at 22 27 53](https://user-images.githubusercontent.com/18277920/184919582-69d4deee-0f8d-
4bd7-a393-813c155559ef.png)

Zapier Gist Actions
![Screen Shot 2022-08-16 at 22 29 45](https://user-images.githubusercontent.com/18277920/184919595-6afbe9b6-b60a-4df6-84cd-6c2dd20520ef.png)

**Comment by luancazarine** [comment]
> premium account

@vunguyenhung I don't know how Zapier handle with triggers. I created a trigger in zapier, it sends instantly, but does't created a webhook in my account
![image](https://user-images.githubusercontent.com/5638699/184963652-7f900cb9-84ef-43a0-88f7-b977daccd6f7.png)

**Comment by luancazarine** [comment]
> 

@vunguyenhung I don't know how Zapier handle with triggers. I created a trigger in zapier, it sends instantly, but does't created a webhook in my account
![image](https://user-images.githubusercontent.com/5638699/184963652-7f900cb9-84ef-43a0-88f7-b977daccd6f7.png)

**Comment by luancazarine** [comment]
> There are two points on this issue:
> To manage campaigns it is necessary to have a premium account, so I will create others.
> I contacted support and they said there is no way to handle webhooks via API, only via UI.

@vunguyenhung I don't know how Zapier handle with triggers. I created a trigger in zapier, it sends instantly, but does't created a webhook in my account
![image](https://user-images.githubusercontent.com/5638699/184963652-7f900cb9-84ef-43a0-88f7-b977daccd6f7.png)

**Comment by vunguyenhung** [comment]
Hello @luancazarine, I find some API docs that can help us to implement the actions:
- Find Contact: https://developers.getgist.com/api/#retrieve-a-contact
- Subscribe Contact to a Campaign: https://developers.getgist.com/api/#subscribe-a-contact-to-campaign
- Unsubscribe Contact to a Campaign: https://developers.getgist.com/api/#unsubscribe-a-contact-from-campaign

Could you try to implement the action using those APIs? Maybe we don't have the premium account but our user might have, and they might need those actions :). I will try to get the premium accounts to test 

For triggers, I understand that we need to communicate with Gist team to onboard Pipedream app, I will create another ticket to track 🙏

**Comment by vunguyenhung** [comment]
I have added the ticket to onboard Pipedream app here: https://github.com/PipedreamHQ/pipedream/issues/4021

**Comment by luancazarine** [comment]
> Hello @luancazarine, I find some API docs that can help us to implement the actions:
> 
> * Subscribe Contact to a Campaign: https://developers.getgist.com/api/#subscribe-a-contact-to-campaign
> * Unsubscribe Contact to a Campaign: https://developers.getgist.com/api/#unsubscribe-a-contact-from-campaign
> 
> Could you try to implement the action using those APIs? Maybe we don't have the premium account but our users might need those actions :). I will try to get the premium accounts to test
> 
> For triggers, I understand that we need to communicate with Gist team to onboard Pipedream app, I will create another ticket to track 🙏

I've tried, but I can't even create a campaign to test the integrations without a premium account

**Comment by vunguyenhung** [comment]
@luancazarine how about just add the code without testing it? I'm OK with shipping it and monitor for error when there's actual usage. We had already applied this process for several paid services

**Comment by luancazarine** [comment]
Waiting for resolution https://github.com/PipedreamHQ/pipedream/issues/4021#issuecomment-1218561577
