### ISSUE TITLE
HelloSign

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3649]
Describe the event source. What app, what event?
**Dropbox Sign (Formerly HelloSign)**

https://app.hellosign.com/api/documentation

From their documentation, you can test any endpoint on test mode:
https://developers.hellosign.com/#testing-the-dropbox-sign-api

## Actions
1. Send signature request from template
https://developers.hellosign.com/api/reference/operation/signatureRequestSendWithTemplate/
- Async option List templates https://developers.hellosign.com/api/reference/operation/templateList/ 
- Dynamic prop to Get Template for Signer Roles and CC Roles
- Please include optional props

2. Send signature request
https://developers.hellosign.com/api/reference/operation/signatureRequestSend/

**Comment by vellames-turing** [comment]
Need a paid account @dylburger

**Comment by vunguyenhung** [comment]
Hello @vellames @feyzullah bosses, I see similarities between this issue and the issue that @feyzullah is working on https://github.com/PipedreamHQ/pipedream/issues/630. Could we decide who will take this app?

**Comment by vunguyenhung** [comment]
Noted @feyzullah! @feyzullah @vellames bosses I think let's have this Github issue as the main ticket for tracking and delete the old one that @feyzullah worked on.

**Comment by malexanderlim** [comment]
Moving to Prioritized, as you do not actually need a paid plan to be able to test, and should be able to test using by setting `test_mode` to `true` per https://developers.hellosign.com/#testing-the-dropbox-sign-api

**Comment by vellames** [comment]
When I try to create an account in Pipedream using HelloSign
Cc: @malexanderlim 
<img width="1199" alt="Screen Shot 2023-08-15 at 13 07 13" src="https://github.com/PipedreamHQ/pipedream/assets/91911778/41ed5a02-8568-4f22-89bf-24153ff7ab9a">

**Comment by michelle0927** [comment]
@malexanderlim I see the same "Payment Required" message that @vellames reported when trying to connect an account in Pipedream.
