### ISSUE TITLE
Iterate

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3663]
### App
Iterate

### Triggers
* Survey Answered
* Survey Question Answered

**Comment by Hassan-Abbas-SQA** [comment]
@dannyroosevelt 
i think this app should be named as iteratehq instead of iterate there is already a website present on internet with named as http://iterate.com where our app has domain as http://iteratehq.com

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt i think this app should be named as iteratehq instead of iterate there is already a website present on internet with named as http://iterate.com where our app has domain as http://iteratehq.com

Looks like they call themselves **Iterate**, so I'll leave it for now.

**Comment by Hassan-Abbas-SQA** [comment]
Test Passed:
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/104946677/199837279-8cfef6da-3bcb-4192-8f76-e11483546bba.png">
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/104946677/199837369-ddd90ca0-8f26-43c6-bc82-bee7ed5d8d25.png">
