### ISSUE TITLE
Lighthouse

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3675]
### App
Lighthouse

### Triggers
* New Message
* New Milestone
* New Project
* New Ticket

### Actions
* Create Milestone
* Create Project
* Create Ticket

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed 
![image](https://user-images.githubusercontent.com/104946677/210661789-09e62a11-5dab-47da-95f7-e28ab3298b7d.png)
![image](https://user-images.githubusercontent.com/104946677/210662349-8b6a34f5-6723-4355-bcf4-0c1ec165db55.png)
![image](https://user-images.githubusercontent.com/104946677/210662422-81a2a28a-5d5f-4442-8ea1-0816ba23b883.png)
![image](https://user-images.githubusercontent.com/104946677/210662684-b174c5f8-b4c6-448e-ad03-8d3d718c58c7.png)


TestFail
![image](https://user-images.githubusercontent.com/104946677/210662221-a192e6e4-5456-43b5-99cf-c9050854c4c7.png)
