### ISSUE TITLE
LiveAgent

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3676]
### App
LiveAgent

### Triggers
* New Customer

### Actions
* Add New Customer

**Comment by Hassan-Abbas-SQA** [comment]
All tests passed 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/104946677/193360792-abbedca2-2c56-40e7-b013-b7a3481d05f1.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/104946677/193360812-31b89d15-c0e1-4606-8f08-b8aea11c35c8.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/104946677/193360838-5f059063-811f-4c03-aa29-888fc2bba28f.png">
