### ISSUE TITLE
Mediatoolkit

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3685]
### App
Mediatoolkit

### Triggers
* New Mention

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia while testing this source i was receiving the events but logs had an error 
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/104946677/192902048-6fac1366-7c62-4e81-a7eb-dc8682c8dd57.png">

**Comment by Hassan-Abbas-SQA** [comment]
Testcases Passed 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/104946677/193155204-5e1d3419-57e7-4712-b009-ce80396a9b48.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/104946677/193155220-68c07584-95ee-490d-ae39-4f2db382d485.png">
ready to deploy
