### ISSUE TITLE
Memberstack

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3688]
### App
Memberstack

### Triggers
* New Member
* Member Deleted
* Member's Plan Canceled
* Member's Plan Added
* Member's Plan Replaced
* Member Updated
* Member deleted

### Actions
* Create Member
* Delete Member
* Update Member
* Find Member
* List Members

**Comment by sergioeliot2039** [comment]
I modified the request to include
"Member deleted" trigger and
"List member" action,

which were requested on #5949 

For the other components requested in said ticket, I did not inmediately find a corresponding API endpoint (such as List Plans) in the Memberstack API documentation
