### ISSUE TITLE
[SOURCE] Spotify

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#369]
**Describe the event source. What app, what event?**
- New Playlist
- New Saved Track
- New Track Added to Playlist

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developer.spotify.com/documentation/web-api/

**Comment by dylburger** [comment]
These Spotify sources are now live. [Create them here](https://pipedream.com/sources/new?app=spotify)
