### ISSUE TITLE
NiftyImages

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3701]
### App
NiftyImages

### Actions
* Add Data Store Record
* Update Timer Target Date

**Comment by Hassan-Abbas-SQA** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/104946677/200636742-848173e2-5454-4d49-b35a-417dca19e993.png">
i think its description must be "create a data store record"

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed 
![image](https://user-images.githubusercontent.com/104946677/201172882-6fc63411-9e61-4c3b-9aa1-7f814e3dd194.png)
