### ISSUE TITLE
PDF.co

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3713]
### App
PDF.co

### Actions
* Barcode Generator
* Barcode Reader
* Anything to PDF Converter
* PDF to Anything Converter
* Custom API Call
* Document Classifier
* Document Parser
* PDF File Information Reader
* HTML to PDF Converter
* Make PDF Searchable
* PDF Merger
* PDF Filler
* PDF Find Table
* PDF Security
* PDF Translator
* Search in PDF
* PDF Splitter
* PDF Splitter by Text

**Comment by Hassan-Abbas-SQA** [comment]
Works fine for me
[Testcases.pdf](https://github.com/PipedreamHQ/pipedream/files/9568406/Testcases.pdf)
