### ISSUE TITLE
[APP] Fibery Auth Object

### ISSUE THREAD

**Issue by blessingefkt** [PipedreamHQ/pipedream#372]
**Name of app / service**

Fibery

**Link to developer documentation**

https://fibery.gitlab.io/api-docs/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I've created a custom event source allowing selection of an entity type and fields (like an Airtable table and column selector).  

I'm using the auth credentials create prop options and `process.env.FIBERY_TOKEN` doesn't seem to be supported in custom event sources. Without an app or means to create custom auth options, I have to pass the auth token as a prop. When the auth token is a prop, the event source behaves as expected.

[![pipedream-fibery-event-source--dynamic-configuration-options.gif](https://s8.gifyu.com/images/pipedream-fibery-event-source--dynamic-configuration-options.gif)](https://gifyu.com/image/gbi5)

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

For now, having an auth object would be sufficient for me. 

Some actions that would be helpful:

- get entities 
- create entity
- update entity
- get file contents
- get document contents

**Comment by dylburger** [comment]
@blessingefkt this is awesome, great job on the custom source. We'll add an integration for Fibery ASAP.

Separately, would you be open to contributing this as an event source that's available to all users? You may have seen that all components in the [`components/` directory](https://github.com/PipedreamHQ/pipedream/tree/master/components) of this repo are automatically published and made available for anyone to create at [https://pipedream.com/sources](https://pipedream.com/sources). I'm sure others would find this valuable, if you're interested.

**Comment by dylburger** [comment]
@blessingefkt Fibery is now integrated, check out [this workflow](https://pipedream.com/@dylburger/fibery-example-p_8rCDRV/edit) for an example.

I also wanted to share our [doc for creating your own actions](https://docs.pipedream.com/workflows/steps/actions/#creating-your-own-actions). If you'd be interested in developing these, we're happy to help support you!

Let us know if you have any other feature / integration requests.

**Comment by blessingefkt** [comment]
@dylburger Thanks for adding Fibery! As a personal challenge, I gave myself 2 hours to get through the event source docs, the github and come up with a functioning fibery event source. Needless to say, the code is a tad scrappy. Once I've cleaned it up, I'd be glad to share it with the community.

**Comment by dylburger** [comment]
Haha that’s great. Let us know if there’s anything you think we can improve about the docs. Thanks again for using Pipedream and for the feedback.
