### ISSUE TITLE
Phone.com

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3723]
### App
Phone.com

### Triggers
* Call Completed
* New Call Log Record
* New Call
* Call Status Updated
* New Inbound SMS
* New Outbound SMS
* New Voicemail

### Actions
* Make Call (Click to Call)
* Create Contact
* ~Send SMS~ (implemented in #1054)
* Find Call Data
* Find Contact

**Comment by GTFalcao** [comment]
There's already an issue for this app: #1054 

Perhaps it'd be best to add this list of triggers and actions to that issue? It has some information regarding the current restrictions on developing this integration (needs paid account + not available in some countries)

**Comment by jverce** [comment]
For the sake of keeping things cleaner, I'd keep them separate.

As per the issue you mentioned (#1054), this would also be blocked until we figure out a way to develop/test this work without making devs purchase a premium plan.

I'm also crossing out the *Send SMS* action, since that's already implemented by you (@GTFalcao) in the mentioned issue.
