### ISSUE TITLE
[FEATURE] CNAME support

### ISSUE THREAD

**Issue by limenleap** [PipedreamHQ/pipedream#373]
**Is your feature request related to a problem? Please describe.**
I have an application that calls a webhook to a specific URL. Unfortunately, I cant change that application

**Describe the solution you'd like**
I created a Webhook and I thought if I setup a CNAME so that I can post to the URL created by Pipedream would work. Tried using CURL on the CNAME but that did not trigger the webhook. I would appreciate if I can create a CNAME to an HTTPS POST webhook setup at Pipedream

**Do you have a workaround?**
No

**Comparable features in other tools?**
Not sure.

**Comment by dylburger** [comment]
Hi @limenleap , thank you for the request. We're tracking this at #198 , please follow that issue if you don't mind.

This will take some work on our end, and I don't have an immediate ETA, but we'll update that issue as soon as we make progress.

Does the application you're using have public documentation on this restriction? We're trying to collect references to use cases so we make sure the solution we build will support you.
