### ISSUE TITLE
Podio

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3734]
### App
Podio

### Triggers
* New Application
* New Action
* New Item
* Item Updated
* New Organization
* New Workspace
* New Activity
* New Task
* New View

### Actions
* Create Item
* Create Status
* Create Task
* Update Item
* Find Item

**Comment by Hassan-Abbas-SQA** [comment]
Update Item action: when i select an id of an item to update it fields/props should get populated from previous data ?
![image](https://user-images.githubusercontent.com/104946677/204623476-fe868251-f826-433f-80ae-becba9601b02.png)

**Comment by feyzullah** [comment]
> Action: Create item : Requtester prop description : should be : " if you're requesting time off for yourself, select yourself here. A valid JSON object(type contact) should be given. Please see [this doc](https://developers.podio.com/doc/applications) to see field objects" <img alt="image" width="766" src="https://user-images.githubusercontent.com/104946677/204624126-6894666e-5b55-4d0d-a16a-497d1b241a2d.png">
> 
> Update Item action: when i select an id of an item to update it fields/props should get populated from previous data ? ![image](https://user-images.githubusercontent.com/104946677/204623476-fe868251-f826-433f-80ae-becba9601b02.png)

@Hassan-Abbas-SQA, that description is actually coming from Podio API server and I have no control over it. Those props added there dynamically after fetching item fields.
For populating before update, I think it may not be so necessary because when leaving props empty, they are not updated.

**Comment by feyzullah** [comment]
@Hassan-Abbas-SQA are there other bugs/improvments?

**Comment by Hassan-Abbas-SQA** [comment]
Triggers:
Passed
![image](https://user-images.githubusercontent.com/104946677/204629226-5666a3db-5dc1-45f3-a337-3a537a6d9507.png)
![image](https://user-images.githubusercontent.com/104946677/204629279-d311e399-a765-4040-939b-3830c8bc3c6a.png)
![image](https://user-images.githubusercontent.com/104946677/204629467-54a19e08-a2f3-4e2c-8399-ddd8ef7dd31b.png)
![image](https://user-images.githubusercontent.com/104946677/204629829-08e144a7-fdc8-4ac9-a6cd-bca6552c5280.png)
![image](https://user-images.githubusercontent.com/104946677/204631472-b198f747-0d8f-4895-969b-5b1a05a65b1e.png)

Failed: Not pt emitting events 
![image](https://user-images.githubusercontent.com/104946677/204630429-f8669bf2-080e-47e1-8d1d-7713764ac434.png)

Actions:
![image](https://user-images.githubusercontent.com/104946677/204634303-adf022a8-1274-4a51-b2dd-d6c88ffc440c.png)
Problem with Update Item action if i left any field as you said it will be default to older information i can’t test the trigger

**Comment by feyzullah** [comment]
> 

@Hassan-Abbas-SQA it should be because of optional values for field configs coming from the API. I changed update function `optional`s to all `true`, which I should have done before. Can you please check `Update Item` action once more?

**Comment by Hassan-Abbas-SQA** [comment]
@feyzullah it worked fine but i want a one more minor change here can you please place ItemID prop right after AppID prop? 
![image](https://user-images.githubusercontent.com/104946677/204646517-fd6f4292-9ed8-4f14-9de4-0a96e06dee13.png)

**Comment by feyzullah** [comment]
> 

@Hassan-Abbas-SQA done. Can you please check?
