### ISSUE TITLE
Printful

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3739]
### App
Printful

### Triggers
* New Order
* New Canceled Order
* New Fulfilled Order

### Actions
* Create Order

**Comment by lcaresia** [comment]
Printful don't work more with `Api Key`, is necessary updat authentication.

> Suporte para API keys termina em março de 2023
> 
> Estamos tornando o acesso à API da Printful mais versátil, seguro e à prova do tempo. Por isso, a partir de 30 de setembro de 2022, não será possível gerar novas chaves API e em 30 de março de 2023, todas as chaves API existentes vão parar de funcionar. Em vez disso, você terá acesso à API da Printful usando tokens privados e aplicativos públicos, e você já pode começar a trabalhar neles em nosso Portal de desenvolvedor.
>
> [Go To Printful Developers](https://developers.printful.com/login)

**Comment by Hassan-Abbas-SQA** [comment]
description is wrong can you please update it
<img width="903" alt="image" src="https://user-images.githubusercontent.com/104946677/198382580-74230013-a9a7-4e2a-9a0b-d13d5e731600.png">
