### ISSUE TITLE
Product Hunt

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3743]
### App
Product Hunt

### Triggers
* New Hot Product
* New Notification
* New Product
* New Upvote

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Product_Hunt_3743_2002.pdf](https://github.com/PipedreamHQ/pipedream/files/10446496/Product_Hunt_3743_2002.pdf)
