### ISSUE TITLE
Qualaroo

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3745]
### App
Qualaroo

### Triggers
* New Response
* Survey Activated
* New Survey
* Survey Deactivated

### Actions
* Activate Survey

**Comment by Hassan-Abbas-SQA** [comment]
TEST FAILED
both trigger are showing this error "Pipedream detected that component was still running code. Make sure you await all promises."
![image](https://user-images.githubusercontent.com/104946677/212976665-7932354b-72f3-4886-8b10-55c37d74ef9c.png)
![image](https://user-images.githubusercontent.com/104946677/212978207-33dcee6c-f22a-40ee-84d6-d48d98feeffb.png)

**Comment by Hassan-Abbas-SQA** [comment]
> @Hassan-Abbas-SQA as stated in the [PR description](https://github.com/PipedreamHQ/pipedream/pull/5203#issue-1536454618), it will timeout very frequently. This is because of the Qualaroo' API, not the code nor Pipedream.
> 
> If you find another error that is **not Maximum execution time reached**, please let me know.

Pipedream detected that component was still running code. Make sure you await all promises.

**Comment by andrewjschuang** [comment]
> Pipedream detected that component was still running code. Make sure you await all promises

That's because of the timeout
