### ISSUE TITLE
QuickEmailVerification

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3747]
### App
QuickEmailVerification

### Actions
* Verify Email Address

**Comment by Hassan-Abbas-SQA** [comment]
@jverce iam unable to publish this action facing this issue 
<img width="651" alt="image" src="https://user-images.githubusercontent.com/104946677/189221736-eb7fa76b-767e-4b76-8a63-8f70e828ac72.png">

**Comment by Hassan-Abbas-SQA** [comment]
when i tried to build it accidently created js files instead of mjs by running this command npx tsc --build
but now iam able to produce the mjs files using npm run build so i moved the ticket to IN QA

**Comment by Hassan-Abbas-SQA** [comment]
props, description and prop names looks good to me. ready to GO
