### ISSUE TITLE
REIPro

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3750]
### App
REIPro

### Triggers
* New Buyer
* New Property

### Actions
* Create Buyer Lead
* Create Property Lead

**Comment by michelle0927** [comment]
REIPro only allows integration through Zapier.
From REIPro: "We do not have a public API endpoint. All of our integrations are done through Zapier."

**Comment by jverce** [comment]
> REIPro only allows integration through Zapier. From REIPro: "We do not have a public API endpoint. All of our integrations are done through Zapier."

cc @dannyroosevelt ☝🏻
