### ISSUE TITLE
Rev

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3763]
### App
Rev

### Triggers
* New Automated Transcript
* New Caption
* New Order
* New Transcript

### Actions
* Create Automated Transcription Order
* Create Caption Order
* Create Transcription Order

**Comment by Hassan-Abbas-SQA** [comment]
in the trigger description , it should be "Emit new event when an order is submitted" instead of "Emit new event when a order is submitted"
<img width="536" alt="image" src="https://user-images.githubusercontent.com/104946677/211672479-206fe669-f096-49ee-9ff1-62eab5a5c4f3.png">

**Comment by andrewjschuang** [comment]
I am not receiving webhook events. Contacting support
