### ISSUE TITLE
Riddle Quiz Maker

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3765]
### App
Riddle Quiz Maker

### Triggers
* Riddle Quiz Completed

**Comment by michelle0927** [comment]
The current API doesn't yet support retrieving information about riddle submissions.
https://www.riddle.com/creator/v2/docs/creatorV2_api

<img width="379" alt="Screen Shot 2023-01-06 at 11 03 55 AM" src="https://user-images.githubusercontent.com/10889229/211051851-d012c7c5-4f50-4b9a-9d45-b07d1409238f.png">
