### ISSUE TITLE
Rise

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3766]
### App
Rise

### Actions
* Create Invitation
* Find Invitations
* Find Users

**Comment by Hassan-Abbas-SQA** [comment]
@jverce i can’t see any sources in your PR so can you please remove them from the first comment please
<img width="254" alt="image" src="https://user-images.githubusercontent.com/104946677/191601045-481c42d3-b110-4bb4-a1af-acd8338bc76c.png">

**Comment by Hassan-Abbas-SQA** [comment]
@jverce here is the testcases all the actions work fine as expected
![FireShot Capture 004 - Untitled workflow - Pipedream - pipedream com](https://user-images.githubusercontent.com/104946677/191730376-b7822cfe-56f0-47b0-9079-788995c27e2d.png)

**Comment by Hassan-Abbas-SQA** [comment]
@jverce i have edited your comment and removed the triggers written so we don’t get confused that triggers are abscent in this PR thanks moving this ticket to ready for release
