### ISSUE TITLE
Clientary 

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3769]
### App
Clientary

### Triggers
* New Contact
* New Expense
* New Payment
* New Project
* New Staff
* New Task
* New Invoice
* New Client
* New Estimate

### Actions
* Client
* Expense
* Create Estimate
* Create Invoice
* Create Task

**Comment by feyzullah** [comment]
I guess [ronin](roninapp.com) has moved to [clientary](https://www.clientary.com). @jverce can you confirm?

**Comment by jverce** [comment]
> I guess [ronin](https://roninapp.com) has moved to [clientary](https://www.clientary.com). @jverce can you confirm?

It looks like it.
@dannyroosevelt, we should block this until we reconfigure the `ronin` app.

**Comment by dannyroosevelt** [comment]
@feyzullah I just enabled a new Clientary app -- can you build the components for that app instead?
https://pipedream.com/apps/clientary/

**Comment by feyzullah** [comment]
@dannyroosevelt sure, I will. Are we going to track it with this issue?

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt sure, I will. Are we going to track it with this issue?

Yea that's fine, can you just update the ticket accordingly?

**Comment by lcaresia** [comment]
@feyzullah Please link the development branch. Thanks!
