### ISSUE TITLE
SEMrush

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3770]
### App
SEMrush

### Triggers
* Completed Site Audit
* New Task for Site Audit Campaign

### Actions
* Create a New Site Audit Campaign
* Get Overview Report
* Re-Crawl a Site Audit Campaign

**Comment by michelle0927** [comment]
Using the SEMrush API requires a paid account. https://developer.semrush.com/api/basics/how-to-get-api/
