### ISSUE TITLE
Sendoso

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3774]
### App
Sendoso

### Triggers
* New Send
* Send Status Updated

### Actions
* Generate eGift Link
* Get Send Status
* Send a Physical Gift With Address Confirmation

**Comment by vunguyenhung** [comment]
Hello @luancazarine, I couldn't test this because I couldn't create an account. Also the test credentials didn't work for my case. So I will move this to ready for release and track for any issue reported by users
