### ISSUE TITLE
SharpSpring

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3776]
### App
SharpSpring

### Triggers
* New Account
* New Email Open Event
* New Form Fillout Event
* New Lead
* New Opportunity
* New Page Visit Event

### Actions
* Create Account
* Create Campaign
* Create/Update Lead
* Create/Update Opportunity

**Comment by michelle0927** [comment]
SharpSpring API requires a paid account.

<img width="529" alt="Screen Shot 2023-01-02 at 10 07 57 AM" src="https://user-images.githubusercontent.com/10889229/210249829-54158280-79d7-4ab1-9d8a-263aca620905.png">
