### ISSUE TITLE
Siteleaf

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3783]
### App
Siteleaf

### Triggers
* New Collection
* New Document
* New Page
* New Site

### Actions
* Create Document

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report: [Siteleaf_3783.pdf](https://github.com/PipedreamHQ/pipedream/files/9961531/Siteleaf_3783.pdf)
