### ISSUE TITLE
Smartsheet

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3785]
### App
Smartsheet

### Triggers
* Updated Row
* New Comment Added
* New Row

### Actions
* Add Row to Sheet
* New Sheet From Template
* Update Row

**Comment by sergioeliot2039** [comment]
Hi there, I modified the ticket to include a the action "Update Row", which was requested at: https://github.com/PipedreamHQ/pipedream/issues/5900

Add Row was requested too, but this already was included
