### ISSUE TITLE
Snappy

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3787]
### App
Snappy

### Triggers
* New Ticket
* New Ticket Assigned to Me
* New Waiting Ticket
* New Wall Post

### Actions
* Create Wall Post

**Comment by Hassan-Abbas-SQA** [comment]
### **Test Failed**
its not emitting events even if i have created 2 wall posts 
![image](https://user-images.githubusercontent.com/104946677/208517092-292f50fb-9d7f-4e31-a686-481447f691f4.png)
![image](https://user-images.githubusercontent.com/104946677/208517116-fe9373de-9b8e-4570-a839-54dcda375d14.png)
Not Emitting events even i have assigned ticket to myself
![image](https://user-images.githubusercontent.com/104946677/208517278-08bb1046-2318-42af-b2cf-32f2eb60f4f9.png)
![image](https://user-images.githubusercontent.com/104946677/208517325-1903f941-8003-417e-95d8-8aecf54fa062.png)




### **Test Passed** 
![image](https://user-images.githubusercontent.com/104946677/208515888-6fad306a-e939-460b-af80-643bfd2caff8.png)
![image](https://user-images.githubusercontent.com/104946677/208515953-2470619b-a709-4d48-a7bf-aa793eed524c.png)
