### ISSUE TITLE
Spondyr

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3790]
### App
Spondyr

### Triggers
* Spondyr Processed

### Actions
* Create Spondyr

**Comment by lcaresia** [comment]
@jverce @dannyroosevelt 

I tried to `create a new Spondyr` in Zapier platform, but I can't find what exatly is this.

Can you explain me better?

Thanks!

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed
![image](https://user-images.githubusercontent.com/104946677/209856233-d3383655-f906-48a6-a3de-36a23c5defe2.png)

TestFailed
![image](https://user-images.githubusercontent.com/104946677/209856252-37534225-7810-46d2-9539-862b64dd101a.png)

**Comment by Hassan-Abbas-SQA** [comment]
![image](https://user-images.githubusercontent.com/104946677/210002066-9e671d11-dbc0-4c57-bc37-4f46c44b7dca.png)
