### ISSUE TITLE
Square

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3791]
### App
Square

### Triggers
* New Appointment
* New Catalog Item
* New Customer
* New Invoice
* New Order

### Actions
* Add Customer to Group
* Create Appointment
* Create Customer
* Create Invoice
* Create Order
* Remove Customer From Group
* Send Invoice
* Update Customer
* Find Customer
* Find Service
* Find Order

**Comment by andrewjschuang** [comment]
@dannyroosevelt can you please add the `DEVELOPER_APPLICATION_WEBHOOKS_WRITE` scope to the Square app?

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt can you please add the `DEVELOPER_APPLICATION_WEBHOOKS_WRITE`, `APPOINTMENTS_ALL_READ`, and `APPOINTMENTS_READ` scopes to the Square app?

Not sure how I missed this, but this is done.
