### ISSUE TITLE
Superdocu

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3796]
### App
Superdocu

### Triggers
* Contact Invited to Workflow
* Contact Complete a Workflow
* Document Group Expired Today
* Document Group Expires in One Week

### Actions
* Create Contact
* Invite Contact to Workflow

**Comment by marwann** [comment]
Hey there, just wanted to let you know that Superdocu's API v1 is being deprecated in favour of the V2.
Documentation is available in our [Swagger](https://developers.superdocu.com/api/index.html)

**Comment by Hassan-Abbas-SQA** [comment]
just to make sure all the sources and events are missing in PR 4827 except this one trigger, i can see in the comments that you were not able to authorize nor have any documentation acccess @vellames 
<img width="207" alt="image" src="https://user-images.githubusercontent.com/104946677/204032290-6184b202-e30a-4642-bf9e-3fc94f5967e7.png">

**Comment by vellames** [comment]
This trigger is enough to satisfies all triggers requested and all triggers available in the platform
