### ISSUE TITLE
SurveyMethods

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3798]
### App
SurveyMethods

### Triggers
* New Response Completed
* New Survey Created

### Actions
* Add Contact to Email List
* Create Email List
* Send a Survey Invitation

**Comment by lcaresia** [comment]
@jverce I don't find what exactly is a  `Send a Survey Invitation`, can you explain me?

**Comment by vellames** [comment]
Could you please link the PR?

**Comment by lcaresia** [comment]
@vellames Sorry, done!

**Comment by jverce** [comment]
> @jverce I don't find what exactly is a `Send a Survey Invitation`, can you explain me?

@lcaresia, I think the original intent of that action is to target a new person to fill/complete an existing survey.
By looking at the SurveyMethods [API docs](https://github.com/PipedreamHQ/pipedream/files/9376734/surveymethodsapidocumentv1.pdf), I think the best candidate to accomplish this is the **Resend Survey Link** endpoint (see section **6.2**).

I'm however open to your feedback since you've worked with this app recently.
