### ISSUE TITLE
SwagUp

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3800]
### App
SwagUp

### Triggers
* Directory Created
* Low Stock for a Product Size
* New or Updated Order
* New or Updated Order Status
* New or Updated Order Tracking
* Stock Change

### Actions
* Send to a New Contact
* Send to a New Contact Multiple Products
* Create a New Contact
* Send to Existing Contact
* Restock Order for a Product
* Find an Order by Its External Id
* Find a Product by Name
* Find Stock for Products

**Comment by andrewjschuang** [comment]
When trying to create an account, it got blocked saying that my company already has an account. Moving this back to **To Do**.

**Comment by andrewjschuang** [comment]
Account created. Will work on this soon.
