### ISSUE TITLE
Sympla

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3801]
### App
Sympla

### Triggers
* New Attendee
* New Event
* New Order

**Comment by vellames** [comment]
@jverce  Are we talking about this Sympla? https://www.sympla.com.br/

**Comment by vellames** [comment]
To create an event on Sympla, Its necessary for manual approval. Waiting for Sympla

**Comment by jverce** [comment]
> @jverce Are we talking about this Sympla? https://www.sympla.com.br/

@vellames it looks like the right one, but we can wait for @dylburger and/or @dannyroosevelt (who's OOO until next week tentatively) to confirm this 🙂

**Comment by vellames** [comment]
@jverce It is :) Tks
