### ISSUE TITLE
Teamgate

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3802]
### App
Teamgate

### Triggers
* Activity Status Changed
* Lead Converted to Person
* Deal Stage Changed
* Email Opened
* New Lost Deal
* New Company
* New Deal
* New Lead
* New Person
* New Product
* New Unqualified Lead
* New Won Deal

### Actions
* Create Activity
* Update Cart Products Status
* Create Company
* Create Deal
* Create Lead
* Create Person
* Update Product
* Create Product
* Update Deal
* Update Lead
* Find Company
* Find Lead
* Find Person
* Find Product
* Find or Create Company
* Find or Create Lead
* Find or Create Person
* Find or Create Product

**Comment by Hassan-Abbas-SQA** [comment]
Test Passed
![FireShot Capture 041 - Untitled Workflow - Pipedream - pipedream com](https://user-images.githubusercontent.com/104946677/209723124-d14db13d-a41f-48d6-9aa5-128df2cd6b0b.png)
![image](https://user-images.githubusercontent.com/104946677/209723554-d84ed89a-51ac-4c68-89e0-6ac63173f9e3.png)
![image](https://user-images.githubusercontent.com/104946677/209723629-7d61686b-b7dc-4ff5-85cd-0aa8aa12ba2a.png)
![image](https://user-images.githubusercontent.com/104946677/209723679-2611852e-3054-4ebd-a956-122caecf6be8.png)
![image](https://user-images.githubusercontent.com/104946677/209723737-9bde9c6c-b603-4b16-ad2a-3a1932ef0c96.png)
![image](https://user-images.githubusercontent.com/104946677/209723788-774bf01e-bc10-442a-883b-c7cbf64d5a35.png)
![image](https://user-images.githubusercontent.com/104946677/209723827-7034b553-8bc6-499f-bf9d-c9f29d86835d.png)
![image](https://user-images.githubusercontent.com/104946677/209723862-85ef6bc3-4cb0-47af-a168-b34a72ef275b.png)
![image](https://user-images.githubusercontent.com/104946677/209723910-a929b093-10ac-49ac-b614-6a415dc0d153.png)
![image](https://user-images.githubusercontent.com/104946677/209723974-902e75f1-2662-4d33-91a9-742e3b9e0b9c.png)
![image](https://user-images.githubusercontent.com/104946677/209724016-f6c45c89-66b7-48a8-b5fc-b81ceedde4d8.png)
