### ISSUE TITLE
[FEATURE] Google Drive sources: allow me to select a specific folder in the newly implemented shared drive feature.

### ISSUE THREAD

**Issue by AlecHex** [PipedreamHQ/pipedream#381]
Firstly thank you for implementing my feature request. On top of that I would like to request another small feature if could be added. 

I was hoping to get a feature to select a specific folder in the drive to be monitored instead of the whole drive. 
As a team we have some folders that are just research sources, some with incomplete spreadsheets and data files and one folder where all the completed projects are stored. 

If the entire drive is monitored, whenever someone uploads a research file or creates a new spreadsheet, the entire team will be notified which is something that can probably become more prominent. If we could only monitor the completed folder in it, so as to get notified only when a file is moved to it's folder or a subfolder in it, that would be great. 

Folder structure example. 
Team Drive
      - Research
      - Incomplete
      - New Project
       -Completed Projects (Parent Folder)
(Subfolders in Completed Projects)
**1. Data

- Alec
- Max
- James

2. Presentation
3. Video Clips
4. Audio Clips**

So in this case we would like to monitor the entire of the completed projects including the subfolders, to get notified when a file is added to any of the subfolders too. 

Thank you and hope I was clearer in what I am looking to achieve.

**Comment by dylburger** [comment]
This is now supported. [Create a new workflow](https://pipedream.com/new), and in the trigger step, select **Google Drive** as the app. Choose the **New Files (Instant)** source, and you can select a folder to watch for new files.

<img width="750" alt="Screen Shot 2021-01-27 at 9 59 52 PM" src="https://user-images.githubusercontent.com/242668/106096885-35230280-60eb-11eb-9752-c3fb3bf9124a.png">
