### ISSUE TITLE
Totango

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3816]
### App
Totango

### Triggers
* New Account
* New User

**Comment by lcaresia** [comment]
@jverce Can you explain me better what is `Send Data`? thanks!

**Comment by Hassan-Abbas-SQA** [comment]
@jverce this PR only contains these sources can you please update the ticket description and remove the other sources and actions which are not included in the PR?
<img width="292" alt="image" src="https://user-images.githubusercontent.com/104946677/186594557-ed5107ae-07c5-4fd6-8553-917a5669ffcc.png">

**Comment by lcaresia** [comment]
@Hassan-Abbas-SQA Done!
