### ISSUE TITLE
Transistor.fm

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3818]
### App
Transistor.fm

### Triggers
* New Episode Created
* New Subscriber Created
* Episode Published
* Subscriber Removed

### Actions
* Create Subscriber
* Remove Subscriber

**Comment by vunguyenhung** [comment]
Hello, this service requires input a credit card in order to register an account. Hence, I will move it to ready for release and track for error if any 🙏 
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/18277920/199013270-1869fe6c-f00f-43cb-84c3-701c2db708e7.png">
