### ISSUE TITLE
Tumblr

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3820]
### App
Tumblr

### Triggers
* New Post in Dashboard
* New Liked Post
* New Post in My Blog
* New Tagged Post

### Actions
* Create Audio Post
* Create Link Post
* Create Photo Post
* Create Quote Post
* Create Text Post
* Create Video Post

**Comment by vellames** [comment]
I am blocked due Tumblr error.
When I am trying to create an account:

```
Error.
There was an error processing your request. Our engineers have been alerted and will work quickly to correct any issues.

[Find out why](https://www.tumblr.com/docs/error_troubleshooting#error) you may have encountered this error.
```

I am putting this on hold for some days until Tumblr fix the error
