### ISSUE TITLE
Unisender

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3822]
### App
Unisender

### Triggers
* New Planned Campaign
* New Subscriber
* New Unsubscriber
* New Completed Campaign

### Actions
* Subscribe Contact
* Unsubscribe Contact

**Comment by luancazarine** [comment]
@jverce I tried to create these triggers, but the unisender API returns the following error:
![image](https://user-images.githubusercontent.com/5638699/202292764-da6fc9c7-34c3-4f0a-a986-1fdefbd84be0.png)

I spoke with support and they answered this:
![image](https://user-images.githubusercontent.com/5638699/202293018-b2df11c7-3e4c-4bb8-b61b-373d4a6fcf02.png)

**Comment by luancazarine** [comment]
@jverce
cc: @dannyroosevelt 
I tried to create the triggers, but the unisender API returns this error:
{
"error": "Error ID:3234402E-65EA-11ED-9458-46A58317E60A. 'hook_url' - This value is not a valid URL.",
"code": "invalid_arg"
}

so I contacted their support and they replied this:
![image](https://user-images.githubusercontent.com/5638699/202463327-43173407-459c-4811-94ec-667d4cc1a5ec.png)

Is there anything to do about it?

**Comment by luancazarine** [comment]
> Hm that's a strange response. There is no content at pipedream.net, but the webhook URL should work fine. Can you ask what the use case is for the domain to be "working"? Or can you connect them with me?

I'm talking by chat, so I'll ask and let you know

**Comment by luancazarine** [comment]
@vunguyenhung 
hello, please check my answer in this file. thanks.
[Unisender_3822.pdf](https://github.com/PipedreamHQ/pipedream/files/10211661/Unisender_3822.pdf)

**Comment by vunguyenhung** [comment]
Hi @luancazarine, all test cases are passed! Ready for release! 

Test report
[Unisender_3822_1147.pdf](https://github.com/PipedreamHQ/pipedream/files/10214439/Unisender_3822_1147.pdf)
