### ISSUE TITLE
UpViral

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3824]
### App
UpViral

**Actions**
1. Add Contact
https://api.upviral.com/#add-contact
- Async option to List Campaigns https://api.upviral.com/#get_campaign_list
- Dynamic prop to list custom fields once campaign is provided https://api.upviral.com/#get_custom_fields
2. Add Points
https://api.upviral.com/#add-points
- Async option to List Campaigns https://api.upviral.com/#get_campaign_list
- Dynamic prop to list leads from a campaign  https://api.upviral.com/#get-paginate-contact

**Comment by vellames** [comment]
@dylburger This app also need a premium account

**Comment by malexanderlim** [comment]
Credentials are in 1Password, good for next 10 days.
