### ISSUE TITLE
[BUG] Getting a "invalid payload" error with steps.send_http_request

### ISSUE THREAD

**Issue by kyleschiess** [PipedreamHQ/pipedream#383]
My first step is pulling in data from an incoming webhook:

![image](https://user-images.githubusercontent.com/38440047/91774021-e9a90e80-ebb5-11ea-9819-26f8b1aaf9e2.png)

Second step is posting this data to Slack:

![image](https://user-images.githubusercontent.com/38440047/91774124-2412ab80-ebb6-11ea-9c31-49e08ff701e9.png)

Not sure how to proceed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  84.0.4147.135 

**Additional context**
I tried using the actual Slack integration provided by Pipedream as the old second step, but I was getting an "invalid_blocks_format" error seen here:

![image](https://user-images.githubusercontent.com/38440047/91774389-a9965b80-ebb6-11ea-962b-d8f20d381d43.png)

**Comment by dylburger** [comment]
@kyleschiess thanks for reporting. Can you try formatting the blocks array in a separate step and pass a reference to the **Blocks** parameter of the Slack **Send a Message** action, instead? I was able to get that working - see [this example workflow](https://pipedream.com/@dylburger/send-a-slack-block-message-formatted-in-previous-step-p_PAC3N8/edit). 

I'm investigating whether the issues you're seeing are a result of how Pipedream passes the value of the string parameter to the step, or an issue with how the Slack `web-api` package accepts the `blocks` property - we may need to update the action such that **Blocks** is passed as an array.

Let me know if that workflow works for you, for now, and I'll update this ticket with more information.

**Comment by kyleschiess** [comment]
Okay, that works.

Can I bring in data from a previous step into that block message code? For instance, can I do:

![image](https://user-images.githubusercontent.com/38440047/91780884-dce0e680-ebc6-11ea-8c80-726ec025bb0b.png)

**Comment by dylburger** [comment]
@kyleschiess you have it exactly right. 

Each step is essentially just a Node.js function, and the [`event`](https://docs.pipedream.com/workflows/events/#event-format), [`steps`](https://docs.pipedream.com/workflows/steps/#step-exports), [`auths`](https://docs.pipedream.com/workflows/steps/code/auth/#the-auths-object), and [`params`](https://docs.pipedream.com/workflows/steps/params/#configuring-custom-params) variables are all in scope, so you have access to any of the data from the trigger step or other steps above the current step (via [step exports](https://docs.pipedream.com/workflows/steps/#step-exports)):

```
async (event, steps, auths) => {
```
