### ISSUE TITLE
VoilaNorbert

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3831]
### App
VoilaNorbert

### Triggers
* Contact Search Completed
* Verify Email Completed

### Actions
* Start Contact Search
* Verify Email
* Find Contact

**Comment by luancazarine** [comment]
@jverce The "Start contact search" endpoint has a field to send the webhook's URL where the result will be posted.
Wouldn't it be better to create it as trigger instead?

https://api.voilanorbert.com/2018-01-08/#search-endpoint-post

**Comment by jverce** [comment]
@luancazarine even though those calls accept "webhook" parameters, they are semantically different from the event sources as we define them in Pipedream. Event sources are meant to capture events that happen on a 3rd party app, but in this case we want users to perform an action against the app (e.g. doing an e-mail search).

Pipedream users can, however, create an additional workflow with an HTTP trigger/source and use its URL to configure this action. That way, one workflow can call this action as usual, and then process the results provided by VoilaNorbert in that additional workflow.

This would be a likely example:
![image](https://user-images.githubusercontent.com/5479513/193324474-c64bb4a0-6534-4743-97b5-0de5b0446ef5.png)

Does that make sense?

I'm cc'ing @dannyroosevelt in case he has a different idea.

**Comment by luancazarine** [comment]
@jverce Ow I got it! It's beacuse we can't create a trigger in hte middle of the workflow! It makes lots of sense!

**Comment by dylburger** [comment]
@luancazarine We actually built $.flow.suspend for this use case. See https://pipedream.com/docs/code/nodejs/rerun/#resume-url-and-cancel-url . When you suspend a workflow, you’ll get a resume_url where the API can post results. When you get the results, the step can return them and move on to the next step.
