### ISSUE TITLE
Voodoo SMS

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3832]
### App
Voodoo SMS

### Triggers
* New Blacklisted Number
* New Contact List
* New Contact Added
* New Inbox Message
* SMS Sent

### Actions
* Add to Blacklist
* Send Bulk SMS
* Add Contact
* Send SMS
* Update Contact List
* Update Contact List - Static

**Comment by jcortes** [comment]
When tried to register a user the only supported Phone Numbers are from
* UK
* Ireland

**Comment by jverce** [comment]
> When I tried to [register a user](https://www.voodoosms.com/register) the only supported Phone Numbers are from
> 
> * UK
> * Ireland

I dealt with something similar when writing the source components for `textlocal`.
I think having a Skype phone number from those countries might help.
