### ISSUE TITLE
Workboard

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3840]
### App
Workboard

### Triggers
* New Action Item
* New Comment in Action Item
* New Comment in Goal
* New Goal
* New Meeting
* New Workstream

### Actions
* Create Team
* Create Workstream
* Create Action Item
* Update Goal Metric

**Comment by luancazarine** [comment]
I tried to create the account a few times, but I never received the email to complete it, so I will return the task until I can create it
