### ISSUE TITLE
Zoho Desk

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3850]
### App
Zoho Desk

### Triggers
* New Account
* New Agent
* New Attachment
* New Comment
* New Contact
* New Message
* New Status Change
* New Ticket
* Updated Ticket

### Actions
* Add Attachment
* Add Comment
* Create Account
* Create Contact
* Create Ticket
* Send E-Mail Reply
* Update Contact
* Update Ticket
* Search Ticket
* Find Contact
* Find or Create Contact

**Comment by jcortes** [comment]
HI @jverce can you give me more detais about theses two triggers please?
* New Status Change
* New Message

Not sure if both of them refers to the Tickers resource?

Thanks!

**Comment by jverce** [comment]
> HI @jverce can you give me more detais about theses two triggers please?
> 
> * New Status Change
> * New Message
> 
> Not sure if both of them refers to the Tickets resources?
> 
> Thanks!

You are correct, both refer to the `Ticket` resource:
* New Status Change -> the status of the ticket changes
* New Message -> a message is added to a ticket
