### ISSUE TITLE
Zoho WorkDrive

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3853]
### App
Zoho WorkDrive

### Triggers
Polling sources:
* New File in Folder
https://workdrive.zoho.com/apidocs/v1/folders/getfilelist 
* New Folder

### Actions
* Upload File
https://workdrive.zoho.com/apidocs/v1/chunkupload

**Comment by luancazarine** [comment]
@dylburger 
There are some needs

Action - upload file
    SCOPE: WorkDrive.files.CREATE

Action - create team folder 
Action - find folder
Action - find or create folder
Source - New Team Folder
    SCOPE: WorkDrive.teamfolders.READ

Action - create-file-from-text
    The API allows creating a file but not putting a text into it
