### ISSUE TITLE
[Sources] Eversign

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3862]
### App
eversign

### Triggers
* Document Completed
* Document Sent

**Comment by Hassan-Abbas-SQA** [comment]
New-Event not triggering any of the event as mentioned in the video logs are also not visible in console
![image](https://user-images.githubusercontent.com/104946677/189880858-62625b1a-7ac6-48b6-8dd2-d49a72ad34a2.png)

**Comment by vellames** [comment]
Hi there. I will ping you on slack

**Comment by vellames** [comment]
It is working normally for me :)
<img width="1367" alt="Screen Shot 2022-09-13 at 9 51 52 AM" src="https://user-images.githubusercontent.com/91911778/189905863-12eb11fa-17af-4009-bd21-d530688e9e3a.png">

**Comment by Hassan-Abbas-SQA** [comment]
@jverce @vellames worked for me too thanks @vellames
<img width="448" alt="image" src="https://user-images.githubusercontent.com/104946677/190005150-1c9584ea-ee8b-43dd-9d3e-6f651bdf4acc.png">

🍎  but this ticket still required some changes in the first comment as mentioned this PR should have actions in it , but unfortunately it doesn’t have any , can you please update the comment to only Sources as i can’t see any actions in it and move the ticket to ready for QA please
<img width="272" alt="image" src="https://user-images.githubusercontent.com/104946677/190006097-51ca841b-87b7-4101-b1b0-86cca1454280.png">

**Comment by vellames** [comment]
@Hassan-Abbas-SQA There is no actions because it is necessary a paid account for it. I removed the actions from the description. I will open a new ticket only for actions and flag it as a paid account
