### ISSUE TITLE
noCRM.io

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3865]
### App
noCRM.io

### Triggers
* New Lead Status Changed
* New Lead
* New Prospect Created

### Actions
* Change Status
* Create Lead
* Get Lead

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia on Create Lead Action the response should be a json not an HTML
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/104946677/183100188-bb27799a-e762-40d4-b038-fcac6be6d816.png">

**Comment by lcaresia** [comment]
> @lcaresia @michelle0927 @jverce on Create Lead Action the response should be a json not an HTML <img alt="image" width="1036" src="https://user-images.githubusercontent.com/104946677/183100188-bb27799a-e762-40d4-b038-fcac6be6d816.png">

@Hassan-Abbas-SQA About this, can you share your config?

**Comment by Hassan-Abbas-SQA** [comment]
> > @lcaresia @michelle0927 @jverce on Create Lead Action the response should be a json not an HTML <img alt="image" width="1036" src="https://user-images.githubusercontent.com/104946677/183100188-bb27799a-e762-40d4-b038-fcac6be6d816.png">
> 
> @Hassan-Abbas-SQA About this, can you share your config?

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/104946677/184736562-e494f969-e838-4b6a-9850-68a0d2c71b08.png">

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia it should generate async lead ids so users should not fill it manually
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/104946677/184742263-547dedd4-3b56-4533-b479-2e4a65f6936f.png">
