### ISSUE TITLE
open weather API

### ISSUE THREAD

**Issue by hubertse** [PipedreamHQ/pipedream#3871]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by Hassan-Abbas-SQA** [comment]
@hubertse can you please provide more information regarding which Action or Trigger you needed or has issues

**Comment by ljdatasci** [comment]
Trigger: 

-   Current Weather API

-   3-Hour Forecasts 5 Days

-   Air Pollution API

-   Geocoding API

Documentation: https://openweathermap.org/current#min

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
