### ISSUE TITLE
[WhatsApp Business]

### ISSUE THREAD

**Issue by Fambirachimwe** [PipedreamHQ/pipedream#3872]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @Fambirachimwe , thanks for the request.
We are tracking WhtasApp integration on this issue, please feel free to follow, if you'd like https://github.com/PipedreamHQ/pipedream/issues/2896

Duplicate, closing.
