### ISSUE TITLE
eZeep Blue CloudPrinter

### ISSUE THREAD

**Issue by Elite** [PipedreamHQ/pipedream#3873]
**eZeep Blue**

**[papercut](https://ezeepapi.wpengine.com/documentation/)**

**Trigger a print job from a pipedream webhook**

**Comment by sergioeliot2039** [comment]
There is a root domain, home page for dev docs. https://ezeepapi.wpengine.com/

I have this one as blocked as OAuth integration, on the App Store project,

**Comment by Elite** [comment]
@sergioeliot2039 So OAuth does not work with pipedream?

**Comment by sergioeliot2039** [comment]
It does, but the Pipedream team handles OAuth integrations directly. 
eZeep is now on their backlog and should be addressed soon.

**Comment by RamsaTech** [comment]
I see the status is now blocked, any reasons for that?

**Comment by sergioeliot2039** [comment]
@RamsaTech i removed the blocked status

@dannyroosevelt following up on eZeep Blue CloudPrinter, has OAuth authentication method

**Comment by dannyroosevelt** [comment]
@RamsaTech we've started the process and are now waiting on the ezeep team to get back to us on next steps for creating an OAuth client.

Thanks

**Comment by dannyroosevelt** [comment]
We just published a basic integration:
https://pipedream.com/apps/ezeep-blue

@RamsaTech are you interested in developing triggers or actions for ezeep?

**Comment by RamsaTech** [comment]
@dannyroosevelt Yes, I will surely try.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
