### ISSUE TITLE
retrieve a page property item[ACTION]

### ISSUE THREAD

**Issue by hubertse** [PipedreamHQ/pipedream#3876]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by Hassan-Abbas-SQA** [comment]
@hubertse can you please provide more information regarding this issue

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
