### ISSUE TITLE
Please, add "Retrieve a page property item" to the Notion API actions.[ACTION]

### ISSUE THREAD

**Issue by hubertse** [PipedreamHQ/pipedream#3877]
This is a request for Notion API. See Documentation:
https://developers.notion.com/reference/retrieve-a-page-property

**Comment by ljdatasci** [comment]
I would like to be assigned to this issue. Where do I start?

**Comment by andrewjschuang** [comment]
Hi @ljdatasci, thank you for prompting to help!
You can start by reading the [Pipedream Docs](https://pipedream.com/docs/components/guidelines/) and checking out the [Notion Actions](https://github.com/PipedreamHQ/pipedream/tree/master/components/notion/actions).
Feel free to ask any questions if needed!

**Comment by ljdatasci** [comment]
Some developers are using GitPod to submit a PR.  Should I also use GitPod to submit my PR? It's not specifically stated in the Pipedream Docs.

**Comment by andrewjschuang** [comment]
Hi @ljdatasci, are you currently working on this?

**Comment by ljdatasci** [comment]
Yes.  I'm adding a method to extract the database property ids and paginate them in the action, so that the user can select from a list of property ids by name.

**Comment by andrewjschuang** [comment]
Cool, feel free to move the card [in the project](https://github.com/PipedreamHQ/pipedream/projects/1) to **Ready for PR Review** when you submit the PR!

**Comment by ljdatasci** [comment]
I have some questions about async options.  Do you have time to discuss my changes on the my fork of the repo https://github.com/ljdatasci/pipedream?

**Comment by ctrlaltdylan** [comment]
PR here: https://github.com/PipedreamHQ/pipedream/pull/3945
