### ISSUE TITLE
[APP] Zoho Catalyst

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#3888]
**Name of app / service**
[Zoho Catalyst](https://catalyst.zoho.com/)
**Link to developer documentation**
https://catalyst.zoho.com/help/api/introduction/overview.html
**Is lack of support preventing you from building workflows, or do you have a workaround?**
User has a workaround
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
For my own notes: this app is configured but the `api_domain` that is returned in the Access and Refresh Token Requests does not match the expected format.

Returned: `https://www.zohoapis.com`
Expected: `https://api.catalyst.zoho.com`
