### ISSUE TITLE
[APP] Zoho Cliq

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#3889]
**Name of app / service**
[Zoho Cliq](https://www.zoho.com/es-xl/cliq/)
**Link to developer documentation**
https://www.zoho.com/cliq/help/restapi/v2/#cliq_rest_api
**Is lack of support preventing you from building workflows, or do you have a workaround?**
User has workarounds
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Notes on outreach:
through their email support, copied sergio@pk and integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Just followed up on this
