### ISSUE TITLE
[ACTION] Hubspot - Enroll in a workflow or a sequence

### ISSUE THREAD

**Issue by Nicolrnt** [PipedreamHQ/pipedream#3900]
**Is there a specific app this action is for?**
Hubspot

**Please provide a link to the relevant API docs for the specific service / operation.**
https://legacydocs.hubspot.com/docs/methods/workflows/add_contact

**Comment by luancazarine** [comment]
@dylburger It is necessary to add workflows-access-public-api scope to access workflow endpoints
![image](https://user-images.githubusercontent.com/5638699/182951588-3bbdd40a-0e97-4c2f-ab01-eb450f114887.png)
