### ISSUE TITLE
[TRIGGER] Add sheet name to result properties

### ISSUE THREAD

**Issue by bsommardahl** [PipedreamHQ/pipedream#3906]
We already have google sheet triggers, but I have a use case that would benefit greatly if the "sheet name" was part of the worksheet properties somewhere. For example, if I have multiple sheets I'm watching for changes, but one of my actions might need to do something slightly different based on which sheet the change came from... knowing the sheet name would be helpful in this case.

Here's a screenshot of where I think it could go, in case I haven't explained well enough: https://share.getcloudapp.com/6quznN0Y

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by jcortes** [comment]
Hi  @bsommardahl can you please add more detail on what is needed? the link that you left in the description is broken :sweat_smile:
I mean I'm already seeing in the results the name of the sheet (`title: Sheet4`) like in the screenshot
So I'm not sure that's what you really need 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/506051/193880972-4681314e-7c94-4a0b-aed8-c0c4c0c48256.png">

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
