### ISSUE TITLE
Seatable.io

### ISSUE THREAD

**Issue by gln5155** [PipedreamHQ/pipedream#3910]
Seatable.io

https://api.seatable.io/#intro

looking for triggers, prebuilt API calls - Zapier, Make, and N8N already have integration

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
This integration is Basic + Bearer.
Left login credentials for the app at the Google Sheet for App Store project

**Comment by LucBerge** [comment]
@sergioeliot2039 any update ? I would also need it.

**Comment by sergio-eliot-rodriguez** [comment]
This shows with internal status of "other" @malexanderlim

**Comment by malexanderlim** [comment]
This appears to be pending submission Sergio - you should be able to return
to it. `seatable` is the slug

**Comment by sergio-eliot-rodriguez** [comment]
> @sergioeliot2039 any update ? I will also need it.

Submitted

**Comment by malexanderlim** [comment]
Approved!
