### ISSUE TITLE
Monday.com

### ISSUE THREAD

**Issue by randyscott777** [PipedreamHQ/pipedream#3911]
Monday.com

Add as a source

**Comment by sergioeliot2039** [comment]
Hi @randyscott777 
thanks for the request!

which Monday sources would you like to see implemented?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergioeliot2039** [comment]
We created a issue for Monday.com sources, follow if you'd like https://github.com/PipedreamHQ/pipedream/issues/3976
