### ISSUE TITLE
[FEATURE]+ Description/documentation on a workflow

### ISSUE THREAD

**Issue by woutersmet** [PipedreamHQ/pipedream#3912]
I think it would be great to allow for some more extensive description/documentation for a workflow. Typical things I would put there is general description, intended use case, and for example more specifically, for example expected parameters of the endpoint (if the trigger is an http trigger).

**Comment by dylburger** [comment]
@woutersmet totally makes sense! If you could add a `README` Markdown file to a workflow, would that work?

**Comment by woutersmet** [comment]
Yeah definitely! (even just plaintext ‘description’ with line breaks and high character limit would already have ‘mvp’ value, but readme.md is even greater of course + feels natural to developers, not sure where you are on version control stuff)

Fwiw in the UI I would envision this coming (both for viewing and editing) somehow ABOVE even the trigger step.

**Comment by dylburger** [comment]
Sorry for the late reply, but this is a work in progress and will be a part of #220

**Comment by dylburger** [comment]
Closing this since #220 will solve and we're close to releasing that
