### ISSUE TITLE
[BUG] Param schema editor, slight layout issue

### ISSUE THREAD

**Issue by oliviermills** [PipedreamHQ/pipedream#392]
**Describe the bug**
The layout in the params schema editor is messed up, see the 2nd and following params (see snapshot) - the param "role" in the example image is attached the above param. Ideally some top white padding would be great to distinguish param sections.
<img width="395" alt="image" src="https://user-images.githubusercontent.com/6075303/92034380-60ffaf00-ed2a-11ea-91b4-6385aa6d9989.png">

**To Reproduce**
1. Create 2 params or more, look at the title of the param

**Expected behavior**
The param name should feel like the title of the section below (detailed schema for that param)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser : Chrome and Firefox

**Comment by dylburger** [comment]
@oliviermills I see exactly what you mean, I'll discuss this with the team. Thanks for raising!

**Comment by dylburger** [comment]
@oliviermills we took a pass improving the UI for the params editor, cleanly separating individual params into their own sections. Let me know if this looks OK to you!

<img width="1234" alt="Screen Shot 2020-09-09 at 4 24 44 PM" src="https://user-images.githubusercontent.com/242668/92664492-02ea4300-f2b9-11ea-9353-414fce7880e2.png">
