### ISSUE TITLE
[TRIGGER] Google Workspace Reports API

### ISSUE THREAD

**Issue by joelmiles** [PipedreamHQ/pipedream#3926]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
The Reports API is a RESTful API you can use to access information about the Google Workspace activities of your users. The Reports API is part of the Google Workspace Admin Console SDK.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.google.com/admin-sdk/reports/v1/guides/push

**Comment by joelmiles** [comment]
Most interested in the Admin Activity Report: https://developers.google.com/admin-sdk/reports/v1/guides/manage-audit-admin

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by jcortes** [comment]
In this case the testing of this app depends on setting an admin account in Google Workspace which will depend on you having a `your-email@yourowncompanydomain.com`. Here you can find some interesting links on how one can get started:

https://support.google.com/a/users/answer/7681288
