### ISSUE TITLE
[FEATURE] Set environment variables via API/CLI

### ISSUE THREAD

**Issue by davetapley** [PipedreamHQ/pipedream#3929]
**Is your feature request related to a problem? Please describe.**

We store secrets using [`ansible-vault`](https://docs.ansible.com/ansible/latest/user_guide/vault.html) and there's no way to programmatically get then in to Pipedream.

**Describe the solution you'd like**

Be able to set environment variables via API/CLI.

**Do you have a workaround?**

I can manually decrypt them and copy/paste, assuming I remember to.

**Comment by dylburger** [comment]
Thanks for the request @davetapley . We're tracking at #1926 .

**Comment by davetapley** [comment]
No kidding, I swear I searched issues for "environment variables api" and it didn't show up 🙈 

Thanks! 😆

**Comment by dylburger** [comment]
Haha all good, honestly it's difficult for even us to find some issues!
