### ISSUE TITLE
[FEATURE] Allow Custom GitLab Host URLs

### ISSUE THREAD

**Issue by Liam-Scott-Russell** [PipedreamHQ/pipedream#3934]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't link my GitLab instance because it is not hosted at `https://gitlab.com/<project>`. This was the main reason I wanted to use pipedream, but it doesn't seem to let me specify a `host`.

**Describe the solution you&rsquo;d like** 
A way to specify a custom host for the GitLab connection (defaulting to `https://gitlab.com`) when connecting the account, and then have the ability to select this account for actions/sources.

**Do you have a workaround?** 
None that I know of.

**Comparable features in other tools?** 
Plenty of other tools require a `host` or `hostUrl` parameter when connecting Gitlab instances.

**Additional context**
I've dug through the code, and assuming a `hostUrl` variable could be sourced from somewhere (no idea how), then I think that if [these lines](https://github.com/PipedreamHQ/pipedream/blob/master/components/gitlab/gitlab.app.mjs#L261) were changed from:
```javascript
return new Gitlab({
  oauthToken,
  camelize: true,
  ...opts,
});
```
to
```javascript
return new Gitlab({
  oauthToken,
  camelize: true,
  host: hostUrl
  ...opts,
});
```

as per [the documentation](https://github.com/jdalrymple/gitbeaker#examples), it would work.

**Comment by dylburger** [comment]
@Liam-Scott-Russell I completely hear you and I’ll take a look to see if we can support this.

**Comment by Liam-Scott-Russell** [comment]
> @Liam-Scott-Russell I completely hear you and I’ll take a look to see if we can support this.

Thanks for the prompt response!

**Comment by dylburger** [comment]
We should be able to support and modify components accordingly. I’m prioritizing with the team. I don’t have an ETA but we’ll keep you updated.

**Comment by Liam-Scott-Russell** [comment]
@dylburger just wondering if there are any updates on this? I'd love to be able to use pipedream to process my Gitlab issues from work, but if it's not feasible soon, I might have to look into something else. Thanks!

**Comment by dylburger** [comment]
@Liam-Scott-Russell Thanks for reaching out. This is still on our backlog. I still don't have an ETA, so if you need to implement urgently, you may need another solution. 

Once we support, we'd still love to have you give it a try, so we'll update this issue as soon as we have something and we can talk more then.

**Comment by Liam-Scott-Russell** [comment]
> @Liam-Scott-Russell Thanks for reaching out. This is still on our backlog. I still don't have an ETA, so if you need to implement urgently, you may need another solution. 
> 
> Once we support, we'd still love to have you give it a try, so we'll update this issue as soon as we have something and we can talk more then.

Thanks for an update. I'd be really interested when this gets implemented, however I also realize there are probably other priorities. 

Let me know if you need any input, or testing!

**Comment by mirokune** [comment]
I subscribed but im not sure if that is the correct method of adding my name to the feature request.  sometimes seeing the level of interest helps triage feature requests. is that a thing here?

**Comment by michelle0927** [comment]
Resolved via https://github.com/PipedreamHQ/pipedream/pull/8368
