### ISSUE TITLE
[APP] Chatlayer

### ISSUE THREAD

**Issue by aaquibcodes4real** [PipedreamHQ/pipedream#3936]
**Name of app / service** 
https://app.chatlayer.ai/
**Link to developer documentation**
https://docs.chatlayer.ai/
**Is lack of support preventing you from building workflows, or do you have a workaround?**
using own api url
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
integration with rails would be ❤️

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @aaquibcodes4real Thanks for the request

Happy to announce that we have rolled out a base integration for Chatlayer, feel free to check it out and let us know feedback ! https://pipedream.com/apps/chatlayer
