### ISSUE TITLE
[BUG] Discord - Reaction Added (Instant) duplicate events

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3937]
**Describe the bug**
Whenever a reaction is added however, it receives two exact replica inputs and therefore triggers the workflow twice at the same time.

**To Reproduce**
1. Create a Discord - Reaction Added (Instant) source
2. Add a reaction to the relevant Discord channel
3. See multiple invocations / events instead of one

**Expected behavior**
One reaction should result in one invocation.

**Screenshots**

https://i.gyazo.com/0c510593a40012d04655ea6897f400b9.png

**Additional context**

Community report - https://pipedream.com/community/t/reaction-added-instant-triggered-twice-instead-of-once-discord/2944

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
