### ISSUE TITLE
[APP] Zoho CRM

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#394]

**Comment by endreoo** [comment]
Any update on Zoho CRM?

**Comment by todsac** [comment]
We are in their approval process now.  For Zoho books this took about two
weeks so I am hopeful we can repeat or beat that timeline.

**Comment by todsac** [comment]
This integration is now complete.  See an example - https://pipedream.com/@tod/zoho-crm-integration-example-p_wOCggyr
