### ISSUE TITLE
ClickUp

### ISSUE THREAD

**Issue by Maguendra** [PipedreamHQ/pipedream#3950]
**Name of app / service** : ClickUp

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** : I would like to be able to use Clickup as a trigger. For example, when a task is updated in ClickUp, I would like it to be a trigger that sends me a slack message.

Thanks

**Comment by sergioeliot2039** [comment]
@Maguendra thanks for the request!

ClickUp supports webhooks (see Webhooks on the left navigation menu on the ClickUp documentation --https://clickup.com/api) 
So you could use Pipedream triggers to respond to ClickUp webhook notifications -- https://pipedream.com/docs/workflows/steps/triggers/#http

Is this a workaround for your use case?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
