### ISSUE TITLE
Sendle[APP]

### ISSUE THREAD

**Issue by tridentcreative** [PipedreamHQ/pipedream#3951]
**Name of app / service**
Sendle

**Link to developer documentation**
https://developers.sendle.com/reference/welcome

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I don't have a work around currently

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I'd like to be able to update a shipping costs in webflow or snipcart

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @tridentcreative , here is a basic integration https://pipedream.com/apps/sendle
but it is untested. Can you please test it with your API credentials and let us know if you see any issues?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
