### ISSUE TITLE
[FEATURE] Trigger a workflow with a form

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#3952]
**Is your feature request related to a problem? Please describe.**
Sometimes, I would like my client to fill a form that will then trigger a workflow and do some stuff. Just like a HTTP request trigger does.

**Describe the solution you'd like**
Why don't you create a custom form type trigger ? It is already possible to define the fields type and description with props.

**Do you have a workaround?**
I currently need to use a third-party software made for building form just to trigger my workflow.

**Comparable features in other tools?**
None from what I know.

**Additional context**
- Possibility to personnalize the form : Color, logo...etc (this is up to you)
- Possibility to change the form url to custom domain.

**Comment by dylburger** [comment]
@LucBerge I didn't realize before, but we're tracking this at #359. We actually have a prototype of this internally and we'll announce on that GH ticket when we release.

**Comment by LucBerge** [comment]
Nice to know it. Thank you.
