### ISSUE TITLE
[FEATURE] Data store export

### ISSUE THREAD

**Issue by AlexeyArtemev** [PipedreamHQ/pipedream#3953]
**Describe the solution you'd like**
Options to export a data store as CSV and JSON 

**Do you have a workaround?**
No digital workaround is available at the moment

**Comment by ctrlaltdylan** [comment]
Hi @AlexeyArtemev 

You can export your data from your data store using a workflow!

That way you can automatically back up or export your data store data to your email, google drive, google sheet, or database of choice.

Just use the built in actions and triggers to interact with your data store and the data within.

You can even start with a HTTP trigger and return your data store's data as a JSON response.

**Comment by AlexeyArtemev** [comment]
Didn't even think about that option, thanks!

**Comment by vunguyenhung** [comment]
Hello @AlexeyArtemev, I have made a Node.js step to export data store as JSON that you can refer to as the image below
![image](https://user-images.githubusercontent.com/18277920/183434923-531a09ef-4ead-4186-9684-2b61d96895c4.png)

Here's the code
```js
export default defineComponent({
  props: {
    // Define that the "db" variable in our component is a data store
    data: { type: "data_store" }
  },
  async run({ steps, $ }) {
    // Now we can access the data store at "this.store"
    const keys =  await this.data.keys()
    let result = {}
    for(const key of keys){
      result[key] = await this.data.get(key)
    }

    return result
  }
});
```

Then you can add another Node.js step to response the JSON (note that you will need to use HTTP Webhook trigger)
![image](https://user-images.githubusercontent.com/18277920/183435275-f43b50fd-3051-40e9-8876-35eaa82fb47b.png)
```js
// To return a custom HTTP response, use $.respond() [requires HTTP trigger]
export default defineComponent({
  async run({ steps, $ }) {
    await $.respond({
      status: 200,
      headers: {},
      body: steps.get_data_store_as_obj.$return_value,
    })
  },
})
```

Following with this, just send a request to your webhook trigger, you should receive your data store in JSON as response

**Comment by ctrlaltdylan** [comment]
@vunguyenhung thanks for making a sample component! Very helpful.

Yes I think that's a good idea, but I would make sure to add in the documentation for this component that the workflow's memory consumption will be affected by this action, since we'd be exposing the entire data store's contents into the workflow.

But in general, users are keeping their data store usage low, but that little warning would be useful.

**Comment by vunguyenhung** [comment]
@ctrlaltdylan thanks for you input! Yes sure I'm going create another Github issue!

**Comment by vunguyenhung** [comment]
Hello everyone, I have created [another Github issue](https://github.com/PipedreamHQ/pipedream/issues/3957) to track further development regarding this request. @AlexeyArtemev kindly subscribe to [the new Github issue](https://github.com/PipedreamHQ/pipedream/issues/3957) for updates if you would like.

For now I will close this Github issue 🙏
