### ISSUE TITLE
[ACTION] *Notion - Search Pages* include `filter` object prop (and others)

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3959]
**Is there a specific app this action is for?**

Notion

**Please provide a link to the relevant API docs for the specific service / operation.**

The existing Search Pages only includes a prop for the `query` term. But as a user, I'd like to be able to use the `filter` object to filter arbitrary rules like only return pages or only return databases:

https://developers.notion.com/reference/post-search

There are other prop opportunities as well like `cursor`, `page_size`, and `sort`.

**Comment by vunguyenhung** [comment]
I confirm that the current `Find Page` action only include `Page Title` prop, which is the `query` param in the API.
![Screen Shot 2022-08-09 at 21 32 31](https://user-images.githubusercontent.com/18277920/183676185-301c203f-8273-42b2-97dc-0910a61a5de3.png)

We can add `filter`, and `sort`, `pageSize` and `cursor` as optional props.

**Comment by luancazarine** [comment]
@vunguyenhung I don't know if it makes sense to add the filter prop, as this prop is exactly what the action uses to tel know it's searching for a page. What we can do is create a new action called Search that can search whatever the user wants, not just a page. What do you think?

**Comment by vunguyenhung** [comment]
Hello @luancazarine, thanks for pointing out! I think it makes sense to create a new action instead in this case, as adding the customizable `filter` prop might not backward compatible with the current code using the same `filter` prop. 

The new action can be named `search` ([matched with the API name](https://developers.notion.com/reference/post-search)). This action will have the following props with respective description:
- `query` (string): The query parameter matches against the page titles. If the query parameter is not provided, the response will contain all pages (and child pages) in the results.
- `filter` (JSON string): The filter parameter can be used to query specifically for only pages or only databases. For example: `{"property":"object","value":"page"}`
- `sort` (JSON string): When supplied, sorts the results based on the provided criteria. Limitation: Currently only a single sort is allowed and is limited to `last_edited_time`. For example `{"direction":"ascending","timestamp":"last_edited_time"}`
- `start_cursor` (string): If supplied, this action will return a page of results starting after the cursor provided. If not supplied, this action will return the first page of results.
- `page_size` (number): The number of items from the full list desired in the response. Maximum: 100

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Notion_4049.pdf](https://github.com/PipedreamHQ/pipedream/files/9404076/Notion_4049.pdf)
