### ISSUE TITLE
[APP] Cloudinary

### ISSUE THREAD

**Issue by Muaazt** [PipedreamHQ/pipedream#396]
**Name of app / service**
Cloudinary

**Link to developer documentation**
https://cloudinary.com/documentation/node_integration

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Upload Base64 Image
Upload from Image URL

**Comment by todsac** [comment]
Cloudinary has been integrated.  Here is an [example workflow](https://pipedream.com/@/p_2gClNO/) using the Cloudinary integrated app.

As for actions, you can author and publish your own actions at https://pipedream.com/actions, accessible from the Actions link in the header. This [video](https://www.youtube.com/watch?v=bTchIr3HYQg&feature=emb_title) describes how to create an action end-to-end, including how to pass params to that action, how to associate actions with apps, and more:

More detail on actions in our [documentation](https://docs.pipedream.com/workflows/steps/actions/#creating-your-own-actions).
