### ISSUE TITLE
[ACTION] Notion - Get Database

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3960]
**Is there a specific app this action is for?**

Notion

**Please provide a link to the relevant API docs for the specific service / operation.**

https://developers.notion.com/reference/retrieve-a-database

Without support for this endpoint, there's no way to discover a Notion database's properties without coding an HTTP request manually.

**Comment by andrewjschuang** [comment]
There is a [Retrieve Database](https://pipedream.com/apps/notion/actions/retrieve-database) action. Or would `async options()` for database properties be required?

**Comment by ctrlaltdylan** [comment]
Ah true. But the async options weren't working for me in my case, that's what lead me down this path to using the **Retrieve Blocks** action to find the block ID, then attempt to find the database properties.

For more context, I only allowed Pipedream access to one page, and under that page I created a database.

The result is that the async options never load:

![CleanShot 2022-08-08 at 14 27 17](https://user-images.githubusercontent.com/2694734/183487727-d66aca62-c574-4868-8849-2a771c8d3610.gif)

**Comment by andrewjschuang** [comment]
Can you try reauthing the account with Pipedream? Notion disables access to newly created databases, I'm not sure if this would resolve the issue

**Comment by ctrlaltdylan** [comment]
Thank you @andrewjschuang ! That did the trick!

I'm making some video content around the Notion components, but it might help to add this to the **Retrieve Database** `README.md#Troubleshooting` section

**Comment by andrewjschuang** [comment]
> Thank you @andrewjschuang ! That did the trick!
> 
> I'm making some video content around the Notion components, but it might help to add this to the **Retrieve Database** `README.md#Troubleshooting` section

How can I add this to that section?

**Comment by ctrlaltdylan** [comment]
Sorry, I don't think we announced it well, but now `README.md`'s are supported at the app, source & action component levels.

Here's an example of an action that has a `Troubleshooting` section:

https://github.com/PipedreamHQ/pipedream/blob/master/components/hubspot/actions/add-contact-to-list/README.md

That `Troubleshooting` section will also appear in that app's documentation in the public marketplace:

https://pipedream.com/apps/hubspot/actions/add-contact-to-list#troubleshooting

I'm also working on bringing it into the workflow builder itself, so customers can see this type of documentation naturally without leaving the builder.
