### ISSUE TITLE
SMTP2Go: send email action

### ISSUE THREAD

**Issue by pataquets** [PipedreamHQ/pipedream#3966]
**Is there a specific app this action is for?**
SMTP2GO

**Please provide a link to the relevant API docs for the specific service / operation.**
https://apidoc.smtp2go.com/documentation/#/POST%20/email/send

**Comment by vunguyenhung** [comment]
I confirm that currently there's no action on SMTP2GO app
![image](https://user-images.githubusercontent.com/18277920/183685770-8171f7d1-f148-43cd-afd3-db8369394b45.png)

We need to add send email action

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by pataquets** [comment]
I'm aware of these alternatives, but I'm not in for any. I don't have the time not the skills.
I was expecting that a listed service was more a "ready to use" than a "do it yourself".

**Comment by vunguyenhung** [comment]
Noted @pataquets, I've added the ticket to Pipedream component backlog. Kindly subscribe to this Github issue for any updates 🙏

**Comment by sergioeliot2039** [comment]
@pataquets here with an update, 
there is now a basic framework for integration SMTP2Go -- https://pipedream.com/apps/smtp2go

**Comment by bsommardahl** [comment]
I am adding functionality to send an email both with normal body and via template. That should be coming through in a few minutes. 🚀

**Comment by vunguyenhung** [comment]
Hello @bsommardahl, I'm re-opening this issue as the code could not be compiled/published due to syntax error [as reported here](https://pipedream-users.slack.com/archives/G01K0RGR1QR/p1662423938425019) 🙏

**Comment by Hassan-Abbas-SQA** [comment]
SMTPGO action's account prop should be on top
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/104946677/194148552-04678632-9568-434d-9740-ed0f4bc0a4bc.png">
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/104946677/194149517-9f2c8c91-2d92-421d-82d3-9c3352dcd438.png">

**Comment by michelle0927** [comment]
@Hassan-Abbas-SQA I think you may be looking at a previous version of the code? This is what the actions' configs look like for me:

<img width="675" alt="Screen Shot 2022-10-05 at 4 58 16 PM" src="https://user-images.githubusercontent.com/10889229/194162620-54260b27-d68c-4695-8505-a53622fe4ab1.png">
<img width="690" alt="Screen Shot 2022-10-05 at 4 58 38 PM" src="https://user-images.githubusercontent.com/10889229/194162638-9af6c8c9-6c1d-45a7-94f0-d8c773bc38d7.png">

**Comment by Hassan-Abbas-SQA** [comment]
Tests Passed
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/104946677/194384044-c0f2ceeb-d153-4052-bde5-e83ef792690e.png">
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/104946677/194384157-f08b5524-15bd-4644-affc-ec6360c0c5d3.png">
