### ISSUE TITLE
[ACTION] Cloudinary

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#397]
**Is there a specific app this action is for?**
Cloudinary

**Please provide a link to the relevant API docs for the specific service / operation.**
Upload Resource (sometimes this is split into simple / advanced actions)
 - Upload Base64 Image  
 - Upload from Image URL
Transform Resource
Any others that are relevant

**Comment by sergioeliot2039** [comment]
**Created actions:**
_Resource transformation_
* Action: https://pipedream.com/actions/a_Mdizvn/edit
* Workflow: https://pipedream.com/@sergio/cloudinary-resource-transformation-p_5VCJlJ/edit
_Upload Media Asset_
* Action: https://pipedream.com/actions/a_EViLmb/edit
* Workflow: https://pipedream.com/@sergio/cloudinary-upload-media-asset-p_yKC53w/edit
_Video Transformation_
* Action: https://pipedream.com/actions/a_74ibV3/edit
* Workflow: https://pipedream.com/@sergio/cloudinary-video-transformation-p_q6CNO9/edit
_Image Transformation_
* Action: https://pipedream.com/actions/a_rJip44/edit
* Workflow: https://pipedream.com/@sergio/cloudinary-image-transformation-p_xMCpZy/edit
_Get Account Usage Details_
* Action: https://pipedream.com/actions/a_WYiEjB/edit
* Workflow: https://pipedream.com/@sergio/cloudinary-get-account-usage-details-p_NMCex3/edit
