### ISSUE TITLE
[ACTIONS, TRIGGERS] Aircall new components

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#3979]
**App**
Aircall

**Actions**
get call

**Sources**
new call ended
new tag added
new note added

Aircall API docs at: https://developer.aircall.io/api-references/
This was requested by users at https://github.com/PipedreamHQ/pipedream/issues/3190

**Comment by vunguyenhung** [comment]
I have added this ticket to our Component backlog, though it is blocked until [Aircall is integrated](https://github.com/PipedreamHQ/pipedream/issues/3190)

**Comment by dylburger** [comment]
Aircall is now integrated. I moved this back to the backlog.

**Comment by ajedwards** [comment]
Thank you @dylburger 🙏

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Aricall_3979.pdf](https://github.com/PipedreamHQ/pipedream/files/9822461/Aricall_3979.pdf)
