### ISSUE TITLE
[BUG] Saved nodeJS action looses the 'steps' argument in the main async function call

### ISSUE THREAD

**Issue by oliviermills** [PipedreamHQ/pipedream#398]
**Describe the bug**
Using a saved action that is a simple nodeJS code forces a `async params =>` without the `steps` argument, causing an error when using `steps` anywhere in the code, including in the params.

**To Reproduce**
1. Create an action anywhere in your workflow, but not as the first step, add a reference to `steps` in the code or as a param
2. "Save as action"
3. Use that action instead, (this will replace the green nodeJS icon with a black {} icon
4. Run the workflow
5. See error saying `Reference to 'steps'` doesn't exist

**Expected behavior**
The main `async` call should retain the 'steps' param
<img width="223" alt="image" src="https://user-images.githubusercontent.com/6075303/92164056-f2862400-edf1-11ea-8d49-56796889313f.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/6075303/92164075-fdd94f80-edf1-11ea-85a3-bcf089a4dae7.png">

***Workaround***
Make a slight tweak to the action so that it uses a custom action instead of the original saved one. That will revert it to a nodeJS type step versus a saved {} pipdream step

**Comment by oliviermills** [comment]
@dylburger  Got it! Thank you. I realized I had accidentally kept a `steps` reference in the code rather than using the available params (which contained the same value). It would be great to have a warning on reference to variables that aren't available (ie. steps) (as part of the test suite for actions that I know you are working on!)

**Comment by dylburger** [comment]
Great thanks for confirming!
