### ISSUE TITLE
[ACTION] Zoho Catalyst

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#3982]
**App**
Zoho Catalyst

**Actions**
Add New User
Add New User to an Existing Organization
Get Current User
Get Specific User
Reset User Password
Logout User

API docs at: https://catalyst.zoho.com/help/api/introduction/overview.html
Zoho Catalyst actions were requested by user on the issue https://github.com/PipedreamHQ/pipedream/issues/3506

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by vunguyenhung** [comment]
Currently there's no Zoho Catalyst app in our Pipedream directory, hence I will add this to our App backlog
![image](https://user-images.githubusercontent.com/18277920/183928942-8b069bc0-9e73-421c-9261-c15f2c089cee.png)

**Comment by vunguyenhung** [comment]
Sorry, I observed that there's another [Github issue for Zoho Catalyst here](https://github.com/PipedreamHQ/pipedream/issues/3888). I will remove this from app backlog and add to Component backlog
