### ISSUE TITLE
[FEATURE] Self serve additional Team member seats

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3986]
**Is your feature request related to a problem? Please describe.**

As a Teams customer, I'd like to be able to add additional seats to my org without having to contact support.

**Describe the solution you'd like**

I'd like the ability to add or remove additional seats from my account outside of the included five seats.

**Do you have a workaround?**

To contact support and ask to have our additional seats modified.

**Comparable features in other tools?**

Any established SaaS that uses seat pricing.

**Comment by dannyroosevelt** [comment]
This is done! pipedream.com/pricing
