### ISSUE TITLE
yahoo.com/mail api

### ISSUE THREAD

**Issue by sjn001tvh** [PipedreamHQ/pipedream#3991]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sjn001tvh** [comment]
I would like to initiate a workflow that triggers when a specific email is received in my yahoo.com email account.

**Comment by vunguyenhung** [comment]
Hello @sjn001tvh, you can use IMAP trigger for this case, follow the steps below:
1. On your Yahoo mail, follow this [article from Yahoo](https://in.help.yahoo.com/kb/SLN15241.html) to create an App Password. Then copy the app password and temporarily store it somewhere
2. Create a new workflow, add Pipedream IMAP Trigger
![Screen Shot 2022-08-11 at 21 27 33](https://user-images.githubusercontent.com/18277920/184157052-4132554c-c921-4f7c-bc54-ae6b6def41ec.png)
3. On the IMAP Trigger, connect to a new account with the following information
**host**: imap.mail.yahoo.com
**email**: Your full email address (name@domain.com)
**password**: Your app password generated in step 1
**port**: 993
![FireShot Capture 500 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/184157854-81500051-e59f-4002-9fe2-32dcde515348.png)

I've tested and it works on my side
![FireShot Capture 501 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/184159262-be19b4c5-2be4-424b-ae95-87747a4304b7.png)

Now I will close this ticket, kindly seek for support on [Pipedream community](https://pipedream.com/community/) when you have similar request. Thanks 🙏
