### ISSUE TITLE
[App] WIX

### ISSUE THREAD

**Issue by breaknanger** [PipedreamHQ/pipedream#3992]
**Name of app / service**
WIX API

**Link to developer documentation**
https://dev.wix.com/api/rest/getting-started

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, I need to integrate my contacts from Mail Chimp with my WIX members.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Specifically need https://dev.wix.com/api/rest/contacts and https://dev.wix.com/api/rest/members

I've integrated the OAuth; however, I don't think that really works with how pipedream is setup, like where can I save the refresh token for the next call? I assume you'd need to do the integration. For this piece to work, or I send the refresh token to a supported app and retrieve/check it at the start of my pipeline. Sorry for the rant, just would be cool to have official integration.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by vunguyenhung** [comment]
I confirm that currently there's no wix app integrated
![Screen Shot 2022-08-11 at 21 40 47](https://user-images.githubusercontent.com/18277920/184159954-ad29cb88-593e-4124-90a3-3bae358f85a9.png)

**Comment by dannyroosevelt** [comment]
@breaknanger FYI we've enabled an OAuth integration with Wix here:
https://pipedream.com/apps/wix/

And we've included members and contacts scopes, but please let us know if there is anything else you need.

**Comment by surface9** [comment]
> @breaknanger FYI we've enabled an OAuth integration with Wix here: https://pipedream.com/apps/wix/
> 
> And we've included members and contacts scopes, but please let us know if there is anything else you need.

I'm unable to locate the OAuth integration

<img width="1254" alt="Screenshot 2023-05-18 at 8 52 31 AM" src="https://github.com/PipedreamHQ/pipedream/assets/133982259/673459c0-d1e4-4f90-9f4f-734dfe413066">

**Comment by malexanderlim** [comment]
Hi @surface9 , we're in the process of updating the integration. Given the breadth of their API, are there specific triggers or actions that you'd like to see built?

**Comment by surface9** [comment]
> Hi @surface9 , we're in the process of updating the integration. Given the breadth of their API, are there specific triggers or actions that you'd like to see built?

Hi @malexanderlim, I saw that y'all just added back the Wix integration recently. I am currently testing it out with my site (thank you so much for re-introducing this!).

I'm specifically looking to scrape all of the user account data (including custom fields) for each of my customers and determine whether or not they are actively subscribed to my website plans.

Currently, I'm running into a bit of an issue. I have generated the Wix API to my site (all permissions included) but the Pipedream Workflow is failing to detect any "New Order Created" events on my site, despite multiple people purchasing my plans since the Workflow source as been actively looking.

**Comment by malexanderlim** [comment]
HI @surface9 , can you please enable the workflow f
<img width="531" alt="Screenshot 2023-06-27 at 10 56 23 AM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/41668bd3-23ad-41dd-90c6-e70c6340e560">
or sharing so that I can take a look?

**Comment by surface9** [comment]
> Hi @surface9 , would you be able to open up a short bug report so that our team can track and triage? https://github.com/PipedreamHQ/pipedream/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D+
> 
> If you could include a link to your workflow, and enable sharing this will help the team to triage. <img alt="Screenshot 2023-06-27 at 10 57 27 AM" width="622" src="https://user-images.githubusercontent.com/42158621/249243079-c31d70cd-61e5-4335-a8cb-d8fefc618de8.png">
![Screenshot 2023-06-27 at 1 00 51 PM](https://github.com/PipedreamHQ/pipedream/assets/133982259/006bb520-c045-4d5b-ab73-5eb03df98055)

Done! (also re-named this workflow)
