### ISSUE TITLE
[BUG] Mattermost Source is not connectable

### ISSUE THREAD

**Issue by timkley** [PipedreamHQ/pipedream#3998]
**Describe the bug**
When trying to connect a Mattermost instance as new account the error message "Unable to find the requested app" appears:
![image](https://user-images.githubusercontent.com/6104339/184327436-dee124e6-949d-4caa-9089-72a9a32dd5f3.png)

I'm pretty sure the problem is that no OAuth application was configured in Mattermost. Unfortunately I couldn't find any information how this should be configured. So maybe this isn't exactly a bug but just missing documentation?

**To Reproduce**
1. Navigate to '[Accounts](https://pipedream.com/accounts)'
2. Click on 'Connect an app'
3. Search for 'Mattermost'
4. Provide a valid Mattermost instance URL
5. Click 'Continue'
6. See above message

**Expected behavior**
No error :)

I'm happy to help test or provide any additional information that could be needed to remedy this issue.

**Comment by vunguyenhung** [comment]
Hello @timkley, I'm Leo the integration QA for Pipedream component. Thank you for the detailed information! I can reproduce your issue and this seems like a bug! I will add this to our App Backlog!
![image](https://user-images.githubusercontent.com/18277920/184378829-e05afb4c-94be-4337-b924-0f18519e181b.png)

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@timkley can you try going through the authentication process for Mattermost again? We've made some changes to the configuration to ensure you can specify your own client ID and secret. I just ran through it on my end and confirms it's working end to end.

**Comment by timkley** [comment]
@dannyroosevelt actually, Dylan reached out to me via Slack in august and the issue was solved back than, so unless something changed, I'd consider this issue resolved, sorry for not updating here!
