### ISSUE TITLE
[ACTION] [PATHS] Add Paths functionality

### ISSUE THREAD

**Issue by lerenos** [PipedreamHQ/pipedream#4007]
**Is there a specific app this action is for?**
No.

**Please provide a link to the relevant API docs for the specific service / operation.**
N/A

Just like Zapier: https://zapier.com/help/create/customize/add-branching-logic-to-zaps-with-paths

My example use case: I want to decide what spreadsheet to modify based on a property of an updated notion database item.
I'm solving it by making 2 different workflows.
Making branches would help me to keep the logic of both spreadsheets side by side: better to compare, work and debug.

Nevertheless, I'd like to say you're doing a remarkable job! Congrats!!

**Comment by dylburger** [comment]
Thank you @lerenos ! We are tracking [here](https://github.com/PipedreamHQ/pipedream/issues/216) if you'd like to follow.
