### ISSUE TITLE
[TRIGGER][IMPROVEMENT] Telegram - Get Updates

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4016]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

This is a request to add more update events to the **Telegram - Get Updates** source.

The source is missing support for the member related events:

![CleanShot 2022-08-16 at 09 37 45](https://user-images.githubusercontent.com/2694734/184893438-b91518ee-c4f1-4c77-8deb-11ec2159ec13.png)

Without support for these events, Pipedream customers cannot make workflows that respond to membership changes in a Telegram chat or channel.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

Screenshot taken from the `getUpdates` documentation here: https://core.telegram.org/bots/api#getting-updates

**Comment by alysonturing** [comment]
Hello @ctrlaltdylan, looks like it's already being supported by the source: `New Updates (Instant)`
Can you please check it again? 

<img width="981" alt="image" src="https://user-images.githubusercontent.com/103650302/193897496-04246c71-9ae0-4a5b-9860-eea815114a80.png">

**Comment by ctrlaltdylan** [comment]
Understood thanks @alysonturing I think at the time I expected a separate source for each event type. This makes sense.
