### ISSUE TITLE
[APP] VK.com

### ISSUE THREAD

**Issue by SGZabrav** [PipedreamHQ/pipedream#4029]
**Name of app / service**
VK.com

**Link to developer documentation**
https://vk.com/dev/manuals

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
There are a lot of functions, but I need these specifically
https://vk.com/dev/objects/video#
video.get

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @SGZabrav, thanks for the request

I created a separated issue for tracking progress on the functions you requested. While I added the most common ones on VK, feel free to follow, if you'd like https://github.com/PipedreamHQ/pipedream/issues/4030

**Comment by sergioeliot2039** [comment]
@SGZabrav, VK is now integrated, please check it out at https://pipedream.com/apps/vk
