### ISSUE TITLE
[BUG] Twitter app seems to be shared among ALL across pipedream

### ISSUE THREAD

**Issue by bluegol** [PipedreamHQ/pipedream#4034]
**Describe the bug**
"My Tweets" source returns 429 Too Many Requests everyday after certain hour. It seems the 100000 x-app-rate-limit is shared with other pipedream's users. NOT a bug in code, but still a bug from a user's standpoint.

**To Reproduce**
1. Create "My Tweets" source and connect any twitter user.
2. Modify code in "CONFIGURATION" tab, so that Twitter API's original response can be logged regardless of the request's success. (See Additional context (1).)
4. Click "RUN NOW" in "EVENTS" tab.
5. If step 3 was successful, check Twitter API responses to user_timeline.json endpoint in "LOGS" tab. Record the header "x-app-rate-limit-remaining". If step 3 was NOT successful, remember the header "x-app-rate-limit-reset"'s value, which is unix epoch, and try step 3 again after and around that time.
6. After some time (e.g. 15 minutes or 1 hour), repeat steps 3 and 4.
7. Confirm that even though the source haven't run many times, "x-app-rate-limit-remaining" has been decreased A LOT. See the attached screenshots.

**Expected behavior**
Either
(1) pipedream should be white-listed by Twitter so that the app-wide limit of 100000 requests per day is not applied;
or
(2) There should be a way for a user to supply different app for twitter so that the app-wide limit of 100000 requests per day is NOT SO EASILY maxed out.

**Screenshots**
![20220818T103701](https://user-images.githubusercontent.com/15626382/185287310-0b0fe43c-81f8-49e0-8b02-d789b795f00b.jpg)

AFTER 1 hour without any API requests from my account, the source was ran. Its result is:

![20220818T113701](https://user-images.githubusercontent.com/15626382/185287449-581f8bda-5c93-48b0-b713-bf8b92484943.jpg)

"x-app-rate-limit-remaining" was decreased by more than 13000.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version:  [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser:  N/A
 - Version:  N/A

**Additional context**
(1) @pipedream/platform's axios never returns the original response, and there seems to be no way to get the original response, which includes the header. So I copy-pasted it into the source's code and console.log'ed it. Will provide the source's code if requested.

**Comment by ctrlaltdylan** [comment]
Hi @bluegol 

I agree, it is frustrating to be sharing the same rate limit as other Twitter users on Pipedream.

However, some apps are just provisioned this way by the service provider.

Currently, Pipedream on is v1.1 of the Twitter API, while migrating to v2 doesn't separate API usage by client - it does increase the overall rate limit.

But, in your case I recommend using the **Twitter Developer App** in Pipedream.

Then you can register your own app with Twitter and you won't be affected by the total Twitter API usage by other Pipedream users.

https://pipedream.com/apps/twitter-developer-app

You can register your Twitter app here: https://developer.twitter.com/en/portal/projects-and-apps

**Comment by hybridcattt** [comment]
Hi @ctrlaltdylan,
how can I use Twitter v2 api with Twitter Developer App in Pipedream? 
I'm using the snippet with Twit, but it's force-appending /1.1/ to request paths, so it's not possible to request any v2 endpoint.

**Comment by ctrlaltdylan** [comment]
Hi @hybridcattt 

The Twitter Developer App in Pipedream uses v1.1 of the Twitter API for authentication as well.

Additionally, the Twit library doesn't appear to support v2 either: https://github.com/ttezel/twit/issues/556

But when we do release a v2 Twitter app it will include pre-built actions and triggers - which endpoint specifically are you looking to integrate with that's in v2 but not v1.1?
