### ISSUE TITLE
[APP] Waitwhile

### ISSUE THREAD

**Issue by ljdatasci** [PipedreamHQ/pipedream#4037]
**Name of app / service**
Waitwhile

**Link to developer documentation**
[https://developers.waitwhile.com/reference/analytics](https://developers.waitwhile.com/reference/analytics)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Lack of support prevents building workflows.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Action:

Customers:

List customers
Create a customer
Export customers
Search customers
Retrieve a customer
Update a customer
Remove a customer
List customer note entries
Add a customer note entry
Get customer note by id
Import customers
Update customer note entry
Delete customer note entry

Invites:
List user invites
Create a user invite
Retrieve a user invite
Remove a user invite
Resend a user invite

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @ljdatasci thanks for the request!

Waitwhile has been integrated, check it out at -- https://pipedream.com/apps/waitwhile

**Comment by ljdatasci** [comment]
@sergioeliot2039 Thanks. I checked the Component library and I don't see any actions for the integration.  Should I open a new issue to start adding the actions?

**Comment by sergioeliot2039** [comment]
Hi @ljdatasci , sorry for the delay. Yes please go ahead adding the action.
I created a new issue for us here https://github.com/PipedreamHQ/pipedream/issues/4057
Please let's track progress there. Thank you!
