### ISSUE TITLE
[BUG] Step.Discord.send_message_with_file.avatar_url is not set correctly

### ISSUE THREAD

**Issue by Elliott-Green** [PipedreamHQ/pipedream#4043]
**Describe the bug**
GIVEN the step 'send_message_with_file' is chosen
AND 'avatar_url' is set to a valid resolving URL
WHEN deploying and testing the step with dummy data
![image](https://user-images.githubusercontent.com/10979087/185636678-111d09b0-0eb6-4e28-9854-c0a93a5328b6.png)
THEN 'avatar_url' is not used, rather the default image is chosen
![image](https://user-images.githubusercontent.com/10979087/185636806-166d4de4-4444-45b5-9a5f-82ad28b64e22.png)

**Expected behavior**
'avatar_url' being set to the parameter provided. 

**Screenshots**
As above.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Tried other images of different sizes and types. Seems like it thinks it's defaulting to the fallback, is the parameter being pulled through to the discord webhook logic?

Found this recent issue which touched on 'avatar_url'
https://github.com/PipedreamHQ/pipedream/pull/3898

FYI @michelle0927 @DilanAthukorala

**Comment by DilanAthukorala** [comment]
@Elliott-Green Thanks for reporting this issue. This was previously observed according to the issue - [#3898](https://github.com/PipedreamHQ/pipedream/pull/3898) and the observation was that the "avatar_url" parameter was not supported by the discord API and therefore was removed from the Discord actions as mentioned in the issue. @michelle0927 Please correct me if I'm wrong and kindly share your findings as well.

**Comment by michelle0927** [comment]
> @Elliott-Green Thanks for reporting this issue. This was previously observed according to the issue - [#3898](https://github.com/PipedreamHQ/pipedream/pull/3898) and the observation was that the "avatar_url" parameter was not supported by the discord API and therefore was removed from the Discord actions as mentioned in the issue. @michelle0927 Please correct me if I'm wrong and kindly share your findings as well.

@DilanAthukorala You're correct about the `discord` action `send-message-with-file`. However, there's another action called `send-message-with-file` under the `discord_webhook` app, and I think that's probably the one @Elliott-Green is referring to. I was able to reproduce the error using that action, and I've created a PR to fix the issue.

**Comment by DilanAthukorala** [comment]
@michelle0927 Thanks for the fix. However I'm observing when we are passing the avatar url, the avatar image in discord is getting updated only if we change the "Username"  (pass a different username than the existing). Otherwise a blank avatar image is displayed if we send the "avatar url" without the "username" param or with the already existing "username" value. Is this the expected behavior from Discord?

**Comment by michelle0927** [comment]
@DilanAthukorala Discord kinda groups messages together that are from the same username and within 10 minutes of each other. So if the same username posts two consecutive messages within 10 minutes of each other, it won't display the username or avatar for the 2nd message. If, however, another username posts a message in-between the two, or if 10 minutes have passed, it will display the avatar. I can update the description for the `avatar_url` prop to note this.

<img width="495" alt="Screen Shot 2022-08-23 at 12 17 27 PM" src="https://user-images.githubusercontent.com/10889229/186211355-85f8e4f2-faa9-4a37-8b76-cbfe04b5ea3b.png">

**Comment by michelle0927** [comment]
Updated the description - https://github.com/PipedreamHQ/pipedream/pull/4059/commits/843e8a798f4135d489ba88ce0f47e401c0a43163

**Comment by DilanAthukorala** [comment]
@michelle0927 Got it, Thanks for the clarification!

This is verified and ready for release.
