### ISSUE TITLE
Invite User Group to private channel [ACTION]

### ISSUE THREAD

**Issue by RobRukavina** [PipedreamHQ/pipedream#4044]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by DilanAthukorala** [comment]
@RobRukavina Could you kindly provide the following details for this request please.

1. Is there a specific app this action is for?
2. Please provide a link to the relevant API docs for the specific service / operation.

**Comment by RobRukavina** [comment]
There isn't a relevant API from Pipedream. Slack has one in their API. This was a request for Pipedream to create one... That said, I'm closing this as I've found another option. Thanks
