### ISSUE TITLE
[TRIGGER] New YouTube subscription 

### ISSUE THREAD

**Issue by marianheinsen** [PipedreamHQ/pipedream#4047]
Emit a new event when the authenticated user subscribes to a new channel

[https://developers.google.com/youtube/v3/docs/subscriptions/list](https://developers.google.com/youtube/v3/docs/subscriptions/list)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dannyroosevelt** [comment]
@marianheinsen to confirm, is this what you're looking for? Or something else?
https://pipedream.com/apps/youtube-data-api/triggers/new-subscriber

**Comment by marianheinsen** [comment]
@dannyroosevelt No that is not what I meant. The trigger should execute if I myself subscribe to another (any) YouTube channel

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt No that is not what I meant. The trigger should execute if I myself subscribe to another (any) YouTube channel

Got it, thanks. Are you interesting in developing that trigger on your own?

**Comment by marianheinsen** [comment]
I might when I have time for it. Is there a guide for contributors?

**Comment by dannyroosevelt** [comment]
> I might when I have time for it. Is there a guide for contributors?

Yep: https://pipedream.com/docs/components/quickstart/nodejs/sources/

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by Hassan-Abbas-SQA** [comment]
TestCases Passed 
![image](https://user-images.githubusercontent.com/104946677/191837185-c0c515a4-fd27-46a1-9671-dab4ee804059.png)
![Uploading image.png…]()
Ready for release
