### ISSUE TITLE
[APP] Ecwid Integration

### ISSUE THREAD

**Issue by trendoscope-algorithms** [PipedreamHQ/pipedream#4050]
Ecwid Ecommerce Integration

https://api-docs.ecwid.com/reference/overview

Can be managed via webhooks. But, there is no direct way to update webhook URLs in Ecwid - have to do by creating helpdesk request and all.

I currently use other integration provider - who have option to listen to various types of requests. The main one I require are related to orders.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by todsac** [comment]
The first version of Ecwid is live - https://pipedream.com/apps/ecwid. It would be great to get any feedback on the scopes and if the it makes sense to have the integration set up by storeId (as opposed to accessing many stores at once).

https://pipedream.com/apps/ecwid

**Comment by trendoscope-algorithms** [comment]
Hi @todsac ,
Unable to use this as trigger. Option not coming up for trigger. Wonder how we can handle this. 
Sudh
