### ISSUE TITLE
create / update items in Agile CRM

### ISSUE THREAD

**Issue by beenlouis** [PipedreamHQ/pipedream#4052]
There is already a connector for the Agile CRM. However, I am not comfortable enough with writing code from scratch. Is it possible to take the data from a previous node and push it into Agile CRM to create or update contacts?

https://github.com/agilecrm/rest-api#13-creating-a-contact

**Comment by DilanAthukorala** [comment]
@beenlouis Thanks for creating this ticket, There's already an item in our backlog to develop these actions, Please follow this ticket - [#3544](https://github.com/PipedreamHQ/pipedream/issues/3544)
