### ISSUE TITLE
[BUG] Editing a deployed workflow shows an error on the trigger

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#4054]
When I click the Edit button I sometimes see an "error" on the HTTP trigger. It goes away by simply clicking on "Save and continue".

**Comment by DilanAthukorala** [comment]
@nachocab Thanks for reporting this issue, I am able to recreate this with the following steps,

1. Create a New Workflow
2. Add the HTTP trigger to the workflow
3. Click "Save and Continue" Button
4. Click on "Deploy"
5. Click "Edit" button on the workflow

This error is only observed when you first create the workflow and added the trigger and try to edit and goes away after you click "Save and Continue" again.

![image](https://user-images.githubusercontent.com/102980146/185966816-148faed7-219b-4fa6-b34d-b1e1e8f3b423.png)

**Comment by nachocab** [comment]
> This error is only observed when you first create the workflow

Actually, I see it every time I edit the workflow

**Comment by dylburger** [comment]
Just going back through old issues, this should be fixed
