### ISSUE TITLE
[ACTIONS, SOURCES] Amilia new components

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#4056]
**App**
Amilia

**Actions**
Get Accounts
Get an Account

**Sources**
New Account
Updated Account
New Activity
Updated Activity

API docs at https://www.amilia.com/ApiDocs https://www.amilia.com/ApiDocs/v3org
Webhooks available for sources 
Supported events appear to be specified in v1 webhooks https://www.amilia.com/ApiDocs/v1webhooks

**Comment by sergioeliot2039** [comment]
This issue is created after the user app request on https://github.com/PipedreamHQ/pipedream/issues/4038

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by andrewjschuang** [comment]
Hello @sergioeliot2039, would it be possible to add the `organization` to `$auth`?
<img width="643" alt="image" src="https://user-images.githubusercontent.com/15385076/194939663-7537967e-8bfe-436a-8155-fa8a625e30ed.png">

**Comment by Hassan-Abbas-SQA** [comment]
@andrewjschuang @sergioeliot2039  in actions : Actions missing except Get Account and List Accounts
In sources : Sources Missing except new account, new activity , update account and update activity , please remove them from the first comment as they are not present in the PR

**Comment by Hassan-Abbas-SQA** [comment]
All TestCases Passed 
**Actions**: 
![Amilia](https://user-images.githubusercontent.com/104946677/195452177-06d01590-dc2c-468a-bf92-1ae81de769b3.png)
**Sources**
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/104946677/195461354-c600a4a1-da2d-47a8-bc9f-3bc2d0f24637.png">
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/104946677/195461901-636d5c49-689a-44aa-9d9a-80e419ca4db4.png">
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/104946677/195462121-fac69b83-0336-4384-9098-4b2370906ff8.png">
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/104946677/195462425-ab36aed5-49c0-495e-96a6-0a0a77d101e9.png">
