### ISSUE TITLE
[ACTION] Waitwhile

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#4057]
**App**
Waitwhile
API docs at [https://developers.waitwhile.com/reference/analytics](https://developers.waitwhile.com/reference/analytics)

**Actions**
List Customers
Create a Customer
Export Customers
Search Customers
Retrieve a Customer
Update a Customer
Remove a Customer
List Customer Note Entries
Add a Customer Note Entry
Get Customer Note by ID
Import Customers
Update Customer Note Entry
Delete Customer Note Entry
List User Invites
Create a User Invite
Retrieve a User Invite
Remove a User Invite
Resend a user invite

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by ljdatasci** [comment]
@sergioeliot2039  Thanks. I'll get started on this PR.

**Comment by ljdatasci** [comment]
@dylburger @sergioeliot2039 I'm having issues with creating actions for the PR.  The integration requires an API_KEY, which I added, but there's no way of clearing out the API_KEY in the action configuration: 
![Screen Shot 2022-08-27 at 3 08 37 PM](https://user-images.githubusercontent.com/52286551/187044671-451d0462-6ddf-43bd-8d87-88777a9df2eb.png)
When I test the component, create-component action, I get the following error message, and my code is correct:
![Screen Shot 2022-08-27 at 3 12 08 PM](https://user-images.githubusercontent.com/52286551/187044829-f1c7826a-a095-4263-ab54-31579adfe68c.png)

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by ljdatasci** [comment]
@dylburger Is this issue #4057 in the backlog?  It's still open under Issues.

**Comment by ljdatasci** [comment]
I ran into some issues while testing the actions.  Some actions are available under the Free Plan, but the rest require a Paid Plan.  Here's the response I received from  Dylan at WaitWhile:

Got some clarity here. Looks like the API is still available to Free Accounts for clients to try out before upgrading to the Paid Subscription plans. This would explain some of the endpoints not working as not all of them are available for the Free Account. I also do not have a list of endpoints that are available for the Free Account, I do apologize.

**Comment by andrewjschuang** [comment]
Resolved by #4592.
