### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#4060]
**Name of app / service**
Hacker News API

**Link to developer documentation**
New API - https://github.com/HackerNews/API

**Is lack of support preventing you from building workflows, or do you have a workaround?**
We need to update the HN integration including actions

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Port existing actions

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Already integrated https://pipedream.com/apps/hacker-news
