### ISSUE TITLE
[ACTION] Zoho Books

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#407]
**Is there a specific app this action is for?**
Zoho Books

**Please provide a link to the relevant API docs for the specific service / operation.**
Create Customer
Create Sales Invoice
Create Estimate
Create Item
Find Invoice

**Comment by sergioeliot2039** [comment]
Here are the implemented actions with a url pointing to a sample workflow in pd

Create a Contact 
https://pipedream.com/@sergio/zoho-books-create-contact-p_jmCZYv/edit

Get a Contact 
https://pipedream.com/@sergio/zoho-books-get-contact-p_PACLL9/edit

List Contacts 
https://pipedream.com/@sergio/zoho-books-list-contacts-p_6lCq3N/edit

Update a Contact 
https://pipedream.com/@sergio/zoho-books-update-contact-p_LQCvLd/edit

Delete a Contact 
https://pipedream.com/@sergio/zoho-books-delete-contact-p_n1CRaG/edit

Create a Contact Person 
https://pipedream.com/@sergio/zoho-books-create-contact-person-p_NMCkQb/edit

Get a Contact Person 
https://pipedream.com/@sergio/zoho-books-get-contact-person-p_BjCvK9/edit

List Contact Persons 
https://pipedream.com/@sergio/zoho-books-list-contact-persons-p_NMCk1b/edit

Update a Contact Person 
https://pipedream.com/@sergio/zoho-books-update-contact-person-p_zACLAq/edit

Delete a Contact Person 
https://pipedream.com/@sergio/zoho-books-delete-contact-person-p_A2C7yA/edit

Create an Estimate 
https://pipedream.com/@sergio/zoho-books-create-estimate-p_A2CYl8/edit

Get an Estimate 
https://pipedream.com/@sergio/zoho-books-get-estimate-p_6lCVeZ/edit

List Estimates 
https://pipedream.com/@sergio/zoho-books-list-estimates-p_7NCJ2M/edit

Update an Estimate 
https://pipedream.com/@sergio/zoho-books-update-estimate-p_A2C7pK/edit

Delete an Estimate
https://pipedream.com/@sergio/zoho-books-delete-estimate-p_PACjbK/edit

Create a Sales Order
https://pipedream.com/@sergio/zoho-books-create-sales-order-p_dDC6rv/edit

Get a Salesorder
https://pipedream.com/@sergio/zoho-books-get-sales-order-p_RRCVV2/edit

List Salesorder 
https://pipedream.com/@sergio/zoho-books-list-sales-orders-p_wOCNN5/edit

Update a Salesorder 
https://pipedream.com/@sergio/zoho-books-update-sales-order-p_G6CbmJ/edit

Delete a Salesorder 
https://pipedream.com/@sergio/zoho-books-delete-sales-order-p_3nCLgz/edit

Mark a Salesorder as Open 
https://pipedream.com/@sergio/zoho-books-mark-a-salesorder-as-open-p_V9C6zK/edit

Void a Salesorder 
https://pipedream.com/@sergio/zoho-books-void-sales-order-p_ljCmwK/edit

Email a Salesorder 
https://pipedream.com/@sergio/zoho-books-email-sales-order-p_zACLlO/edit

Create an Invoice
https://pipedream.com/@sergio/zoho-books-create-invoice-p_n1Cjp9/edit

Get an invoice 
https://pipedream.com/@sergio/zoho-books-get-invoice-p_dDCWR5/edit


List Invoices 
https://pipedream.com/@sergio/zoho-books-list-invoices-p_q6Cye9/edit

Update an Invoice 
https://pipedream.com/@sergio/zoho-books-update-invoice-p_QPCMDa/edit

Email an Invoice
https://pipedream.com/@sergio/zoho-books-email-invoice-p_QPCppr/edit

Remind Customer about an Unpaid Invoice 
https://pipedream.com/@sergio/zoho-books-remind-customer-p_13CMMP/edit

Void an Invoice 
https://pipedream.com/@sergio/zoho-books-void-invoice-p_vQCYYK/edit

Mark an INvoice as Draft 
https://pipedream.com/@sergio/zoho-books-mark-invoice-as-draft-p_QPCMMA/edit

List Invoice Payments 
https://pipedream.com/@sergio/zoho-books-list-invoice-payments-p_PACje5/edit

Delete an Invoice Payment

Create a Payment 
https://pipedream.com/@sergio/zoho-books-list-invoice-payments-p_PACje5/edit

Get a Payment 
https://pipedream.com/@sergio/zoho-books-get-customer-payment-p_2gCORA/edit

List Customer Payments 
https://pipedream.com/@sergio/zoho-books-list-customer-payments-p_13CM9p/edit

Update a Payment 	
https://pipedream.com/@sergio/zoho-books-update-customer-payment-p_ZJCrv6/edit

Delete a Payment 
https://pipedream.com/@sergio/zoho-books-delete-customer-payment-p_RRC87d/edit

Create an Expense 
https://pipedream.com/@sergio/zoho-books-create-expense-p_LQCv2D/edit

List Expenses 
https://pipedream.com/@sergio/zoho-books-list-customer-payments-p_13CM9p/edit

Update an Expense 
https://pipedream.com/@sergio/zoho-books-update-customer-payment-p_ZJCrv6/edit

Delete an Expense 
https://pipedream.com/@sergio/zoho-books-delete-customer-payment-p_RRC87d/edit

Create an Employee 
https://pipedream.com/@sergio/zoho-books-create-employee-p_RRCoqO/edit

Get an Employee 
https://pipedream.com/@sergio/zoho-books-get-employee-p_8rCBb6/edit

List Employees 
https://pipedream.com/@sergio/zoho-books-list-employees-p_D1Cdl6/edit

Delete an Employee 
https://pipedream.com/@sergio/zoho-books-delete-employee-p_wOC62y/edit

Create an Item 
https://pipedream.com/@sergio/zoho-books-create-item-p_xMC5r1/edit

Get an Item 
https://pipedream.com/@sergio/zoho-books-get-item-p_A2CYY5/edit

List Items 
https://pipedream.com/@sergio/zoho-books-list-items-p_ezCbz6/edit

Update an Item 
https://pipedream.com/@sergio/zoho-books-update-item-p_RRCo66/edit

Delete an Item 
https://pipedream.com/@sergio/zoho-books-delete-item-p_wOC6Wm/edit

Mark an Item as Active 
https://pipedream.com/@sergio/zoho-books-mark-item-as-active-p_13CNrY/edit

Mark an Item as Inactive 
https://pipedream.com/@sergio/zoho-books-mark-item-as-inactive-p_k2CQeV/edit

Make an API Call 
https://pipedream.com/@sergio/zoho-books-make-an-api-call-p_PACedM/edit
