### ISSUE TITLE
[APP] Connecteam

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#4072]
Connecteam
https://editor.swagger.io/?url=https://s3.eu-central-1.amazonaws.com/connecteam/open_api/users_swagger.yaml
https://help.connecteam.com/en/articles/3064080-updating-user-information-using-an-application-programming-interface-api

This was requested by an user on issue [3905](https://github.com/PipedreamHQ/pipedream/issues/3509), along with ClickUp.
The API is avalable to Enterprise users

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
14 days follow up

**Comment by sergio-eliot-rodriguez** [comment]
14 days follow up

**Comment by sergio-eliot-rodriguez** [comment]
1 month follow up

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/connecteam
