### ISSUE TITLE
[APP] CoinMaretCap

### ISSUE THREAD

**Issue by ggtw86** [PipedreamHQ/pipedream#4086]
CoinMarektcap

[**Link to developer documentation**](https://coinmarketcap.com/api/documentation/v1/)

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I want to use their API

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
HI @ggtw86 , on behalf of Pipedream, thanks for the request
And personally, congratulations on joining GitHub, the repo of choice for software developers.

We have an integration for CoinMarketCap -- https://pipedream.com/apps/coinmarketcap.
Can you have a look please?
Cheers,
