### ISSUE TITLE
[ACTION] Add functionality to Google Drive > Create Folder to only create if the folder doesn't exist

### ISSUE THREAD

**Issue by bsommardahl** [PipedreamHQ/pipedream#4087]
Google Drive allows duplicate folder names, but this is not always what we want. When creating a folder, it would be nice to have the option to ONLY create if the folder doesn't yet exist. 

**Please provide a link to the relevant API docs for the specific service / operation.**
Google's Drive API doesn't support this option natively, so it would be necessary to do a quick search before creating the folder. Here's the doc page for `files.list`: https://developers.google.com/drive/api/guides/search-files

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
