### ISSUE TITLE
Clio [APP]

### ISSUE THREAD

**Issue by Wright-will** [PipedreamHQ/pipedream#4090]
**Name of app / service**
Clio

**Link to developer documentation**
[https://app.clio.com/api/v4/documentation](https://app.clio.com/api/v4/documentation)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Would be nice to have a service that has full integration and additional programming options beyond Zapier. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Webhooks, custom actions (in documentation), json pull and parsing, put requests, etc.

**Comment by sergioeliot2039** [comment]
Hi @Wright-will , thanks for the request!
Sergio here, I am in charge of new app integrations
I see we have Clio integrated -- https://pipedream.com/apps/clio

Regarding Action and trigger, can you be more specific please on which actions (which are essentially data we pull from the API) or triggers (which can be based on webhooks), please if you don't mind?
Happy to triage to the components dev team.

See this request for Streak as an example https://github.com/PipedreamHQ/pipedream/issues/3795

Thanks!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
