### ISSUE TITLE
Update Vercel components for new auth strategy

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4093]
Vercel is encouraging integration partners to move away from OAuth and instead use Personal Access Tokens that users generate manually.

In order to support this new authentication strategy, we need to extend support for the existing triggers and actions to the new `vercel_token_auth` app. Similar to Brex, Docusign, and others, both apps should share all the component code.

**Comment by andrewjschuang** [comment]
> Similar to Brex, Docusign, and others, both apps should share all the component code.

@dannyroosevelt what do you mean when saying **both apps**?
I only see one Vercel app

**Comment by dannyroosevelt** [comment]
> > Similar to Brex, Docusign, and others, both apps should share all the component code.
> 
> @dannyroosevelt what do you mean when saying **both apps**? I only see one Vercel app

Oh haha whoops, I hadn't set the app live yet, so we didn't add to the components dir, but it should be there now 😄

**Comment by Hassan-Abbas-SQA** [comment]
@dannyroosevelt The Token based Auth works fine for me tested using trigger but there is a problem iam having while publishing the actions 
<img width="920" alt="image" src="https://user-images.githubusercontent.com/104946677/187551504-58ce88b8-6ece-4f7e-9400-339ffe2b3fd8.png">

**Comment by andrewjschuang** [comment]
> @andrewjschuang The Token based Auth works fine for me tested using trigger but there is a problem iam having while publishing the actions

Can you try to publish them individually?

**Comment by vunguyenhung** [comment]
@Hassan-Abbas-SQA sorry for bump in here, I've checked your issue briefly and I think it might be a problem with `pd-scripts`. I can publish the action using `pd publish` normally 
![image](https://user-images.githubusercontent.com/18277920/187687151-bca3f69e-b610-4bcd-a51a-71a8e4de9434.png)

Hence I will move this back to Ready for QA 🙏

**Comment by Hassan-Abbas-SQA** [comment]
Its working 💯 Fine ready to GO
![image](https://user-images.githubusercontent.com/104946677/187690065-c69d1e82-185f-4764-8487-4f63ea19188b.png)
