### ISSUE TITLE
[APP] ProductBoard

### ISSUE THREAD

**Issue by r-oleary** [PipedreamHQ/pipedream#4095]
**Name of app / service**
ProductBoard

**Link to developer documentation**
https://developer.productboard.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No workaround right now, this is preventing me from integrating Notion + PB

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
https://developer.productboard.com/#tag/Notes

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @r-oleary , thanks for the request.
We have created a basic integration, good for start creating other componentsn, would you mind give a quick test for us?
https://pipedream.com/apps/productboard
The trial was used to create it, but apparently API is disabled, only available on the Pro plan

Regarding Action and trigger, can you be more specific please on which actions (which are essentially data we pull from the API) or triggers (which can be based on webhooks), please if you don't mind?
Happy to triage to the components dev team.

See this request for Streak as an example https://github.com/PipedreamHQ/pipedream/issues/3795

 Thanks!

**Comment by r-oleary** [comment]
Thanks!

Specifically I would like the ProductBoard action of Creating a Note:
https://developer.productboard.com/#operation/create_note

I will be pulling data from the Notion API, and then using this call to
push that data to ProductBoard.

**Comment by sergioeliot2039** [comment]
Awesome!,

I have created a new issue to track Productboard componentes, fllow if you'd like. 
https://github.com/PipedreamHQ/pipedream/issues/4096
