### ISSUE TITLE
[ACTIONS, SOURCES]  Productboard new components

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#4096]
**App**
Productboard

**Actions**
Create Note
Create Feature
Get Feature
List Features
Update Feature

**Triggers**
New Note
New Feature
Updated Feature

Requested by user on issue https://github.com/PipedreamHQ/pipedream/issues/4095 along the app integration
API docs at -- https://developer.productboard.com/#section/Introduction
Webhook available for sources -- https://developer.productboard.com/#tag/webhooks

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
