### ISSUE TITLE
[BUG] Data Store - `Key` Prop show error when `Data Store` prop is not filled

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4099]
**Describe the bug**
On Data Store actions having `Key` prop, the `Key` prop will show error when `Data Store` prop is not filled: `Cannot read property 'keys' of null`
![FireShot Capture 159 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/186806036-649d915a-da52-437e-a2da-9355e2c68132.png)

**To Reproduce**
1. Create a new Workflow, skip the trigger
2. Add a Data Store action having `Key` prop, .i.e `Add or update a single record`
3. On the action, skip the `Data Store` prop (do not set value), tap into the `Key` prop
![FireShot Capture 159 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/186806036-649d915a-da52-437e-a2da-9355e2c68132.png)

**Expected behavior**
- The `Key` prop should be disabled at first, then enabled only when the `Data Store` prop is filled

**Comment by dylburger** [comment]
This is fixed
