### ISSUE TITLE
[BUG] ConfigurationError exception is not thrown in async options

### ISSUE THREAD

**Issue by andrewjschuang** [PipedreamHQ/pipedream#4104]
**Describe the bug**
`ConfigurationError` exception is not displayed in the Pipedream UI when thrown from a prop's `async options()`. Seems like this happens when a `console.log` or `$.export` executes before the thrown exception.

**To Reproduce**
1. Checkout the branch `configuration-error-async-options`
2. Create an Vercel `list-deployments` actions and configure auth
3. Select `Access Token` prop and type in anything
4. Select `Projects` prop and open dropdown selection list
5. See that no error is displayed and instead a `No matching options` message is displayed

**Expected behavior**
A `ConfigurationError` message displayed in the prop configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/15385076/186958506-6f568391-e53c-447b-8487-ce2e97da631a.png)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
