### ISSUE TITLE
[APP] Integration Request

### ISSUE THREAD

**Issue by garrettstark** [PipedreamHQ/pipedream#4106]
**Name of app / service**
Action Builder

**Link to developer documentation**
https://www.actionbuilder.org/docs/v1/index.html

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Preventing workflow.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @garrettstark , thanks for the request!

In order to create an account, a new user needs to schedule a demo or join the app which requires a payment of $50USD pero user.

Perhaps, if you are up to, can you share your API key, which you can revoke, and generate a new one, once the integration is completed.

> To retrieve your organization's API key, navigate to the API and Integrations page from the Admin Menu. From there, you can generate a new API key, copy your existing API key, or revoke your API key.

For privacy sake, you may join our Pipedream-Users public space at Slack https://join.slack.com/t/pipedream-users/shared_invite/zt-11sazmsg0-oS2VW~mZfhtk3XfEEvb~JA

you can DM me directly, I go by Serge (Sergio Rodriguez) or share to my email sergio at pipekit.com

**Comment by dannyroosevelt** [comment]
@garrettstark can you help confirm if this works for you, since we aren't able to easily get a test API key to validate? 
https://pipedream.com/apps/action-builder

**Comment by dannyroosevelt** [comment]
And are you looking for specific triggers and actions for this app?

**Comment by garrettstark** [comment]
Action Builder was able to work, thanks!
Best,
Garrett

**Comment by garrettstark** [comment]
Hi,

I get a 403 Forbidden error on this.
I turned on 'allow Pipedream support to access' at:
***@***.***/run-node-js-with-the-action-network-api-p_D1Cwexq/

I hadn't realized Action Network has a webhook function already so this
might not be as needed.
https://actionnetwork.org/docs/webhooks
Generally the most useful triggers are already listed there.

While it's maybe less important to set up a pipedream trigger, because
Action Network webhooks exist, It'd still be nice as we have to simplify
for some of our no-code users.

Thanks,
Garrett

**Comment by dannyroosevelt** [comment]
@garrettstark it looks like part of the code snippet got deleted somehow. Can you try adding that step again? You should see this:

```
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    action_network: {
      type: "app",
      app: "action_network",
    }
  },
  async run({steps, $}) {
    return await axios($, {
      url: `https://actionnetwork.org/api/v2/people`,
      params: {
        "OSDI-API-Token": `${this.action_network.$auth.api_key}`,
        "Content-Type": `application/json`,
      },
    })
  },
})
```

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
