### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by garrettstark** [PipedreamHQ/pipedream#4107]
**Name of app / service**
Action Network

**Link to developer documentation**
https://actionnetwork.org/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Preventing work

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
@garrettstark can you help confirm if this works for you, since we aren't able to easily get a test API key to validate? https://pipedream.com/apps/action-network

**Comment by dannyroosevelt** [comment]
And you you looking for specific triggers and actions for this app?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
