### ISSUE TITLE
[FEATURE] Bitbucket and Jira Integrations

### ISSUE THREAD

**Issue by danthegoodman1** [PipedreamHQ/pipedream#411]
**Describe the solution you'd like**
Seeing a solution similar to your recent Zoom integration. Where many of the webhook possible events are now event sources in Pipedream.

For example, with webhooks pointing to another service, we use:

1.  If someone makes a PR and it has merge conflicts, I drop a message of shame in the discord :slightly_smiling_face:
2. When there is a new build from Pipelines, I drop a message in discord with the commit number, commit message, URL, etc.

**Do you have a workaround?**
Webhooks

**Comparable features in other tools?**
Jira has some built in actions stuff but no options for the flexibility of a platform like Pipedream (i.e. code and other APIs)

**Comment by dylburger** [comment]
@danthegoodman1 definitely makes sense. Are the two event sources you noted as examples the top priority for you, or are there a list of other specific sources you'd like to see?

**Comment by danthegoodman1** [comment]
@dylburger I think branch, PR, and pipeline events would be major for me on bitbucket. Start/stop of a sprint, and updating the status of a task on Jira would be the bomb.com too.

**Comment by dylburger** [comment]
@danthegoodman1 thanks, we opened individual issues for [Bitbucket](https://github.com/PipedreamHQ/pipedream/issues/412) and [Jira sources](https://github.com/PipedreamHQ/pipedream/issues/415), and we included those sources in the list (among others). I'm closing this issue in favor of those service-specific tickets.
