### ISSUE TITLE
[FEATURE] Improve Nordigen app

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#4113]
**Is your feature request related to a problem? Please describe.**
In the Nordigen app, when choosing a country, pipedream asks for a two letters code. If you enter `US`, it won't work because the Nordigen app works only for [the following countries](https://nordigen.com/en/coverage/).

**Describe the solution you'd like**
Change the [country prop](https://github.com/PipedreamHQ/pipedream/blob/5def469c88a61e3b93ff31ecfc998f4585156cb9/components/nordigen/nordigen.app.mjs#L7) to have a dropdown list of the supported countries.

**Do you have a workaround?**
No

**Comment by dannyroosevelt** [comment]
Hey @LucBerge thanks for the suggestion!

I don't see an API endpoint to retrieve that list dynamically, in case the list changes. For now I just added that link to the prop description to help users double check.

Let me know if that's sufficient for now and we can close this out.

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/187125617-1c4a619b-3ff4-4912-92e3-93c86be26a04.png)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by LucBerge** [comment]
I cannot reopen the issue

**Comment by dannyroosevelt** [comment]
Thanks for submitting a PR for this, @LucBerge!
