### ISSUE TITLE
[SOURCE] BitBucket

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#412]
**Describe the event source. What app, what event?**
BitBucket

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
New Commit
New Issue
New Event
New Repo
Watch team
Watch user
Watch repository

**Comment by dylburger** [comment]
From #411:

* New branch
* New PR
* Pipeline events

**Comment by jverce** [comment]
From BitBucket API docs, teams are deprecated in favor of workspaces:
https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams

Will implement **Watch workspace** instead of **Watch team**

**Comment by jverce** [comment]
Same for **Watch user**, see https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/
