### ISSUE TITLE
[ACTION] BitBucket

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#413]
**Is there a specific app this action is for?**
BitBucket

**Please provide a link to the relevant API docs for the specific service / operation.**
Create an Issue
Create an Issue Comment
Create a Snippet Comment
Delete an Issue
Get a File
Get a Milestone
Get an Issue
Get a Snippet
Make an API Call
Update an Issue
List Issues
List Milestones
List Repository Watchers
List Snippets
List Snippet Watchers
Create Issue
Find Issue

**Comment by sergioeliot2039** [comment]
Create New Issue
workflow: https://pipedream.com/@sergio/bitbucket-create-new-issue-p_KwCdO8/edit
action:  https://pipedream.com/actions/a_vgipda/edit
Create Issue Comment
workflow: https://pipedream.com/@sergio/bitbucket-create-issue-comment-p_wOC7x1/edit
action: https://pipedream.com/actions/a_k6ijrp/edit
Create Snippet Comment
workflow: https://pipedream.com/@sergio/bitbucket-create-snippet-comment-p_brCpV9/edit
action: https://pipedream.com/actions/a_LgieV6/edit
Delete an Issue
workflow: https://pipedream.com/@sergio/bitbucket-delete-issue-p_wOC7kW/edit
action: https://pipedream.com/actions/a_8KiGxm/edit
Get a File
workflow: https://pipedream.com/@sergio/bitbucket-get-file-from-repository-p_rvCd2J/edit
action: https://pipedream.com/actions/a_G1ilwv/edit
Get a Milestone
workflow: https://pipedream.com/@sergio/bitbucket-get-milestone-p_YyCKyd/edit
action: https://pipedream.com/actions/a_dvirqX/edit
Get an Issue
workflow: https://pipedream.com/@sergio/bitbucket-get-issue-p_MOC5O9/edit
action: https://pipedream.com/actions/a_jQi6oq/edit
Make an API call
workflow: https://pipedream.com/@sergio/bitbucket-make-an-api-call-p_MOC5Wa/edit
action: https://pipedream.com/actions/a_poiwod/edit
Update an Issue
workflow: https://pipedream.com/@sergio/bitbucket-update-issue-p_KwCaVe/edit
action: https://pipedream.com/actions/a_Vpimk3/edit
List Issues
workflow: https://pipedream.com/@sergio/bitbucket-list-issues-p_YyCZpY/edit
action: https://pipedream.com/actions/a_4rimEW/edit
List Milestones
workflow: https://pipedream.com/@sergio/bitbucket-list-milestones-p_PAC7D3/edit
action: https://pipedream.com/actions/a_oViL43/edit
List Repository Watchers
workflow: https://pipedream.com/@sergio/bitbucket-list-repository-watchers-p_RRCQyx/edit
action:  https://pipedream.com/actions/a_JmiRxR/edit
List Snippets
workflow: https://pipedream.com/@sergio/bitbucket-list-snippets-p_OKC8bl/edit
action: https://pipedream.com/actions/a_52izXK/edit
List Snippet Watchers
workflow: https://pipedream.com/@sergio/bitbucket-list-snippet-watchers-p_6lC7Lq/edit
action: https://pipedream.com/actions/a_q1iWjp/edit
Find Issue
workflow: https://pipedream.com/@/bitbucket-find-issue-p_A2Cwpw/edit
action: https://pipedream.com/actions/a_74ijM2/edit
Update Issue Comment
workflow: https://pipedream.com/@/bitbucket-update-issue-comment-p_QPCVnn/edit
action: https://pipedream.com/actions/a_MdiegY/edit
Delete Issue Comment
workflow: https://pipedream.com/@sergio/bitbucket-delete-issue-comment-p_MOCbZd/edit
action: https://pipedream.com/actions/a_rJiaoM/edit
Delete Snippet
workflow: https://pipedream.com/@sergio/bitbucket-delete-snippet-p_gYCxPJ/edit
action: https://pipedream.com/actions/a_4rimkB/edit
Update Snippet Comment
workflow: https://pipedream.com/@sergio/bitbucket-update-snippet-comment-p_dDC9Zg/edit
action: https://pipedream.com/actions/a_nji8mG/edit
Delete Snippet Commment
workflow: https://pipedream.com/@sergio/bitbucket-delete-snippet-comment-p_6lC7zL/edit
action: https://pipedream.com/actions/a_A6iWvQ/edit
Get Snippet Comment
workflow: https://pipedream.com/@sergio/bitbucket-get-snippet-comment-p_pWCj6l/edit
action: https://pipedream.com/actions/a_l0i7zV/edit
