### ISSUE TITLE
[FEATURE] Improve usability for understanding which account I've connected to an app

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4135]
Currently, when I connect my Slack, Discord, and many other accounts, I often cannot differentiate between Slack Workspaces, Discord Guilds, etc. This is a common problem across many apps. I'd like to see more helpful contextual information on the auth provision, so that I can understand what account is connected.

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt, I believe this improvement needed to be done on Pipedream internals. So I will add `tracked-internally` label.

Please tell me if any change is needed 🙏

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
