### ISSUE TITLE
[FEATURE] If only 1 connected account exists for an app, select that by default

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4138]
Suggestion from a user: https://pipedream-users.slack.com/archives/C01E5KCTR16/p1661955460385759

**Comment by zalmanlew** [comment]
This would be great, I would add that even if there were _multiple_ accounts - it could allow the user to select a specific account as the "default" account. 
This also just means that the first account for a given app defaults to be the "default" account (the user can obviously change this in the future).

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by dannyroosevelt** [comment]
This is done for apps where there are only a single auth provision (supporting defaults for multiple auth provisions is on the backlog):
[GIF 2022-09-26 at 2 21 11 PM](https://user-images.githubusercontent.com/20780753/192383993-b20ff357-002a-4670-9689-a51868519605.gif)

**Comment by dannyroosevelt** [comment]
Ah that's a good catch @andrewjschuang, that is a bug that I just flagged to eng.
