### ISSUE TITLE
[BUG] Updating required props in ClickUp components 

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4139]
It appears we are flagging "workspace" and "space" props as `optional` in the Create Task action for ClickUp, but if those are not provided, then async options fails for the "folder" prop, which is required.

We should confirm which fields are required for all ClickUp components, and update accordingly.

Reported by a user here: https://pipedream-users.slack.com/archives/C01E5KCTR16/p1661955460385759

**Comment by Hassan-Abbas-SQA** [comment]
@andrewjschuang dynamic values for Tasks prop appearing on previous version of Update custom Task action
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/104946677/194396566-68cc0b6b-2935-4ff2-944e-3b55a31d32cf.png">

but not appearing on this latest version

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/104946677/194396787-0f45d486-14f1-4e94-abfe-bead938ffe25.png">

**Comment by andrewjschuang** [comment]
> @andrewjschuang dynamic values for Tasks prop appearing on previous version of Update Task Custom field action

Right, the description informs that to list other props must be configured before, because the user requested to be able to directly insert the values - what do you think?

**Comment by Hassan-Abbas-SQA** [comment]
> > @andrewjschuang dynamic values for Tasks prop appearing on previous version of Update Task Custom field action
> 
> Right, the description informs that to list other props must be configured before, because the user requested to be able to directly insert the values - what do you think?

when i insert values manually 
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/104946677/194399246-3064ae42-5c8f-4b86-b693-361f30f9827e.png">
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/104946677/194399284-02bd22a4-41c6-4c89-927c-c43e3aa7fa8f.png">

**Comment by andrewjschuang** [comment]
> when i insert values manually

Hi @Hassan-Abbas-SQA can you try inserting the ID of the Custom Field?

<img width="315" alt="image" src="https://user-images.githubusercontent.com/15385076/194564111-45ea1c08-fd16-4a73-9243-e80c25f60cd9.png">

**Comment by Hassan-Abbas-SQA** [comment]
passed final test
<img width="916" alt="image" src="https://user-images.githubusercontent.com/104946677/194614565-bd9b7b6a-35b2-4dcb-9e55-786a2b3ab440.png">
