### ISSUE TITLE
[ACTION] Jira Software Cloud

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#414]
**Is there a specific app this action is for?**
Jira Software Cloud

**Please provide a link to the relevant API docs for the specific service / operation.**
Add Comment to Issue
Add Watcher to Issue
Create Issue
Find Issue
Find User
Update Issue
Worklog Updated
Issue Status Changed
Add Comment

**Comment by sergioeliot2039** [comment]
Add Comment to Issue
workflow: https://pipedream.com/@/jira-add-comment-to-issue-p_ezCRPp/edit
action: https://pipedream.com/actions/a_q1iWJL/edit
Add Watcher to Issue
workflow: https://pipedream.com/@/jira-add-watcher-to-issue-p_ljCrGb/edit
action: https://pipedream.com/actions/a_OOibpo/edit
Create Issue
workflow:  https://pipedream.com/@/jira-create-issue-p_NMCxev/edit
action: https://pipedream.com/actions/a_0Mi2KV/edit
Find Issue 
workflow: https://pipedream.com/@/jira-get-issue-p_ZJCQ19/edit
action:  https://pipedream.com/actions/a_bKiraz/edit
Find User
workflow: https://pipedream.com/@/jira-get-user-p_3nCvOA/edit
action: https://pipedream.com/actions/a_EVixVA/edit
Update Issue:
workflow:  https://pipedream.com/@/jira-update-issue-p_xMCknl/edit
action: https://pipedream.com/actions/a_3Li68z/edit
Assign issue:
workflow:  https://pipedream.com/@/jira-assign-issue-p_7NC1YO/edit
action: https://pipedream.com/actions/a_52izMB/edit
Transition Issue
workflow: https://pipedream.com/@/jira-transition-issue-p_wOCJ7p/edit
action: https://pipedream.com/actions/a_OOibX8/edit
Get Transition:
workflow: https://pipedream.com/@/jira-get-transitions-p_wOCJBa/edit
action: https://pipedream.com/actions/a_gnir13/edit
Delete Issue:
workflow: https://pipedream.com/@/jira-delete-issue-p_vQCKw3/edit
action: https://pipedream.com/actions/a_nji8P2/edit
List Issue Comments
workflow: https://pipedream.com/@/jira-list-issue-comments-p_WxClZp/edit
action: https://pipedream.com/actions/a_NqilRo/edit
Update Comment
workflow: https://pipedream.com/@/jira-update-comment-p_7NC1mJ/edit
action: https://pipedream.com/actions/a_YEikxJ/edit
Get an Attachment
workflow:  https://pipedream.com/@/jira-get-attachment-metadata-p_YyCnJP/edit
action: https://pipedream.com/actions/a_52izPB/edit
Add an Attachment
workflow: https://pipedream.com/@/jira-add-attachment-to-an-issue-p_6lCN2K/edit
action: https://pipedream.com/@/jira-add-attachment-to-an-issue-p_6lCN2K/edit
Make an API call:
workflow: https://pipedream.com/@/jira-make-api-call-p_G6CqaB/edit
action: https://pipedream.com/actions/a_3Li6Mz/edit
Get Task
workflow: https://pipedream.com/@/jira-get-task-p_q6CeDO/edit
action: https://pipedream.com/actions/a_jQi6PQ/edit
Cancel Task
workflow: https://pipedream.com/@/jira-cancel-task-p_3nCZWN/edit
action: https://pipedream.com/actions/a_VpimMa/edit
Create project
workflow: https://pipedream.com/@/jira-create-project-p_yKCj7a/edit
action: https://pipedream.com/actions/a_EVixBA/edit
Get Projects paginated
workflow: https://pipedream.com/@/jira-get-workflows-paginated-p_LQC2Vv/edit
action: https://pipedream.com/actions/a_xqiVM3/edit
Update project
workflow: https://pipedream.com/@/jira-update-project-p_ezCyML/edit
action:  https://pipedream.com/actions/a_vgipmr/edit
Delete project
workflow: https://pipedream.com/@/jira-delete-project-p_OKCjp3/edit
action: https://pipedream.com/actions/a_Mdie4R/edit
Archive project
workflow: https://pipedream.com/@/jira-archive-project-p_13C6zn/edit
action:  https://pipedream.com/actions/a_0Mi2Nz/edit
Restore deleted project
workflow: https://pipedream.com/@/jira-restore-deleted-project-p_ZJCL6M/edit
action: https://pipedream.com/actions/a_8KiGWl/edit
Get workflows paginated
workflow: https://pipedream.com/@/jira-get-workflows-paginated-p_LQC2Vv/edit
action: https://pipedream.com/actions/a_oViL0w/edit
