### ISSUE TITLE
[BUG] Gorgias trigger

### ISSUE THREAD

**Issue by TinaNikolic** [PipedreamHQ/pipedream#4142]
**Describe the bug**
When creating a trigger for a new ticket created in Gorgias, if there was a ticket deleted in the meantime, an error pops up and the trigger cannot be set and flow completed. 

**To Reproduce**
1. Go to your Pipedream account > Workflows
2. Click on add new workflow
3. Search for an app > Gorgias
4. Select a trigger > New ticket
5. Connect your Gorgias account 
6. Name the trigger > create the source

**Expected behavior**
New ticket created even found > trigger set

**Current behavior**
An error pops up of a ticket being deleted and the trigger is not set

**Screenshots**
![Pipedream-Connect-APIs-Remarkably-Fast](https://user-images.githubusercontent.com/73716540/187885180-054099e5-6eae-4ec9-8a85-12366cff1727.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Google Chrome
 - Version: 105.0.5195.52 (Official Build) (x86_64)

**Additional context**
How far back the retrieving the historical events go? Would it be possible to search for one successful event?

**Comment by Hassan-Abbas-SQA** [comment]
for me this trigger works fine tested multiple scenarios but i couldn’t find any issue iam closing the ticket right now may be you should reconnect your account and try a different browser if it doesn’t help you can reopen this issue later thanks  @TinaNikolic 
<img width="905" alt="image" src="https://user-images.githubusercontent.com/104946677/188276100-3873cb6e-15db-4158-acb9-9f8e8ce0a4dd.png">
