### ISSUE TITLE
I man Learning unreal engine 5 in Udemy when I right this code it didn't work as expected [BUG] 

### ISSUE THREAD

**Issue by mohammadapsar** [PipedreamHQ/pipedream#4143]
**my void name didn't set in C++, I am only able upload photo of it**
![Screenshot (104)](https://user-images.githubusercontent.com/112628764/187910872-57542571-2147-413a-8c1e-edf0d7baec7d.png)
![Screenshot (105)](https://user-images.githubusercontent.com/112628764/187910890-609a6a64-a8c7-42df-a99a-553cddf64be9.png)

**Comment by ctrlaltdylan** [comment]
Hi @mohammadapsar ,

Sorry, I'm not sure which project you intended to report this bug on, but Pipedream doesn't support C++ in code steps. I think perhaps you intended to report this somewhere else.

**Comment by mohammadapsar** [comment]
This fixes
