### ISSUE TITLE
[BUG] Can't pass valid JSON to send_message_public_channel metadata event payload

### ISSUE THREAD

**Issue by schisamo** [PipedreamHQ/pipedream#4145]
**Describe the bug**
The `send_message_public_channel` Workflow step will not accept dynamic valid JSON objects in the  _Metadata Event Payload_ config input. This config is expected valid JSON. From the error being returned it appears Pipedream is attempting to parse the valid JSON an additional time.

**To Reproduce**
1. Create a workflow.
2. Add a `send_message_public_channel` step
3. Configure the _Metadata Event Payload_ value using valid dynamic JSON data from a previous step.
4. See the following error when the workflow executes:
```
Invalid JSON in metadata_event_payload: Unexpected token o in JSON at position 1
```
**Expected behavior**
I would expect the valid dynamic JSON payload to be properly parsed and passed along as the Metadata Event Payload input.

**Screenshots**
![pipedream_error](https://user-images.githubusercontent.com/6164/187951643-424edacd-f4a0-46d4-b44b-a67d680a0867.png)

**Comment by ctrlaltdylan** [comment]
Hi @schisamo thanks for the detailed bug report!

Have you tried passing a JSON-as-string argument to the _Metadata Event Payload_ prop?

`{{ JSON.stringify(steps.build_slack_message.$return_value.slack_message_metadata) }}`

I believe the props data should be serialized to a string by default, but it's worth a shot.

**Comment by ctrlaltdylan** [comment]
No problem :) @schisamo 

If you're up for it, could you open a new issue as a feature request? I think perhaps the prop could be improved to accept _either_ an string or an object.
