### ISSUE TITLE
[ACTION] Request:  List / Get Zoom Registrations

### ISSUE THREAD

**Issue by garrettstark** [PipedreamHQ/pipedream#4147]
**Is there a specific app this action is for?**
Zoom / Zoom Admin

**Please provide a link to the relevant API docs for the specific service / operation.**

I *think* you can get registration data out with the API.
I'm able to get attendance records, but Ideally we can match them to registration.
https://marketplace.zoom.us/docs/api-reference/introduction/

**Comment by vunguyenhung** [comment]
Hello @garrettstark, as I checked, Pipedream is providing some actions for listing registrants:

List Meeting Registrants
![FireShot Capture 205 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/188482880-4f3525bd-0458-4b95-ad1d-ec54bb6f17b0.png)

List Webinar Registrants
![FireShot Capture 206 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/188483402-15ea2050-3c64-4323-a8c3-c8a83a98ab16.png)

May I ask specifically what kind of registrants you want to get?

**Comment by garrettstark** [comment]
Hi,
I was starting to investigate 'listing participants'.
I haven't started working on registrations yet.
When I use Zoom Admin, for "List past meeting participants" unless I'm the
host of the meeting, despite being an Admin on the account, I'm not able to
access the records.
Our Zoom account has ~80 users who all create meetings.
I'm hoping there's a way I can create a single integration with pipedream
to grab meeting participants without having to setup 80 pipedream
workflows.
Does that seem possible?


Zoom

Zoom Admin

Get Meeting

If Admin-User is the meeting host: Success

If Admin-User is not the meeting host: Forbidden

Meeting Details

If Admin-User is the meeting host: Success

If Admin-User is not the meeting host: Success

List Past Meeting Participants

If Admin-User is the meeting host: Success

If Admin-User is not the meeting host: Forbidden

List Past Meeting Participants

If Admin-User is the meeting host: Success

If Admin-User is not the meeting host: Forbidden

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by garrettstark** [comment]
I got it to work- the problem was Zoom's API requires the account owner, not just an admin to access participant lists on the account...

**Comment by DilanAthukorala** [comment]
Hello @garrettstark,  Did you able to resolve the issue? Please post here if you have any further queries or else we can close this ticket.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
