### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by garrettstark** [PipedreamHQ/pipedream#4148]
**Name of app / service**
Zoho Sheet

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, no workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

https://www.zoho.com/sheet/developers.html

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@garrettstark here is a basic integration for Zoho Sheet: https://pipedream.com/apps/zoho-sheet/

Please let me know if that works for you.

Are there specific triggers or actions you're looking for?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
