### ISSUE TITLE
[ACTIONS, TRIGGER] - Splitwise new components

### ISSUE THREAD

**Issue by franceme** [PipedreamHQ/pipedream#4149]
**App**
Splitwise
https://dev.splitwise.com/

**Currently there is no workaround.**

**I would like to have triggers that indicate new payments are made (to/from myself), groups are made, and re-occuring notices about debts. I would also like to get the amount balance from each payment, current payments, and information about each information (amount, to-from, photo, details). As a stretch I would also like to get all of the raw payment information for a time period (i.e. to get a budget breakdown for a report or reimbursement).**

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergioeliot2039** [comment]
@franceme  As a head up, I checked the Splitwise API

These are the components that I see feasible by looking at the API, but please feel free to correct
For developers: No webhooks supported, Sources would need to be poll based.

**Actions**
Create Expense
Get Expense Information

**Sources**
New Expense
New Group
New Notification

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by Hassan-Abbas-SQA** [comment]
Action : Get Expenses : Description : please update the description to : Get Expenses involving the current user , in reverse chronological order
<img width="817" alt="image" src="https://user-images.githubusercontent.com/104946677/195716281-439529d6-d89c-4e56-b4cd-c2f13969029f.png">

**Comment by Hassan-Abbas-SQA** [comment]
All Testcases passed 
![splitwise](https://user-images.githubusercontent.com/104946677/195718437-7e3c28e2-4fc7-4874-9e0a-ba90929fef74.png)
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/104946677/195718556-7f3177ae-a406-4bf7-9929-d12a91d9d824.png">
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/104946677/195719549-66e20ec2-893a-4d0f-9567-f9336da32fdc.png">
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/104946677/195719587-7ec2fb39-27c8-4dac-bccb-3bf57c883a34.png">
