### ISSUE TITLE
Erpnext [APP]

### ISSUE THREAD

**Issue by cyberdee** [PipedreamHQ/pipedream#4153]
**Name of app / service**: ERPNEXT

**Link to developer documentation**: https://docs.erpnext.com/ 

**Is lack of support preventing you from building workflows, or do you have a workaround?** We have a workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/erpnext
