### ISSUE TITLE
Data sorting is getting changed in CSV file than report data when using Export CSV option [BUG] 

### ISSUE THREAD

**Issue by MaheshKungaria** [PipedreamHQ/pipedream#4154]
**Describe the bug**
When exporting data of Superset report Chart Type - "Pivot Table v2" into CSV file then its changing the sorting order of data into the CSV file.

Sample screenshots:
![issue_screen](https://user-images.githubusercontent.com/112639146/188065263-4dc08238-f8a0-4365-9c07-e56a64ff5fa3.jpg)

**To Reproduce**
1. Create a report of Chart Type - "Pivot Table v2" as per attached sample screenshot
2. Go to 'Export CSV'
3. Compare Superset report data with CSV file there sorting order in CSV file will change.

**Expected behavior**
When Export data to CSV its sorting order should remain same as per the report.

**Screenshots**
Screenshots attached.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Microsoft Edge, Google Chrome
 - Superset Version: 1.3.1

**Additional context**
Please let me know if need any additional information about this issue.

Thanks.

**Comment by dylburger** [comment]
@MaheshKungaria it looks like you meant to open this in the Superset repo. This doesn't look like a bug in Pipedream, so I'm closing.

**Comment by dylburger** [comment]
@MaheshKungaria it looks like you meant to open this in the Superset repo. This doesn't look like a bug in Pipedream, so I'm closing.
