### ISSUE TITLE
instagarm[APP]

### ISSUE THREAD

**Issue by SwethaKumaravel** [PipedreamHQ/pipedream#4156]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
HI @SwethaKumaravel , thanks for the request!
Can you please share the URL for that app?
or did you mean Instagram?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by SwethaKumaravel** [comment]
yes im asking for instagram

**Comment by SwethaKumaravel** [comment]
> HI @SwethaKumaravel , thanks for the request! Can you please share the URL for that app? or did you mean Instagram?

Yes how to configure for instagram for pipedream link:https://www.instagram.com/

**Comment by sergioeliot2039** [comment]
You can't right now.

The Pipedream integration for Instagram is pending approval by Meta, Instagram's parent company
Feel free to follow this issue Instagram here: https://github.com/PipedreamHQ/pipedream/issues/445 if you'd like
