### ISSUE TITLE
[ACTION] Move Pcloud files / directories to another Folder

### ISSUE THREAD

**Issue by danielsawan** [PipedreamHQ/pipedream#4158]
**Is there a specific app this action is for?**
Pcloud

**Please provide a link to the relevant API docs for the specific service / operation.**
This can be achieved using pCloud [`renamefile` API](https://docs.pcloud.com/methods/file/renamefile.html) and [`renamefolder` API](https://docs.pcloud.com/methods/folder/renamefolder.html)

---
For better UX, I would suggest we create 4 new actions:
- Move file
- Move folder
- Rename file
- Rename folder

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by Hassan-Abbas-SQA** [comment]
TestCases Passed
![Pcloud](https://user-images.githubusercontent.com/104946677/194643185-8a1b58ba-060f-4e5b-b141-5c0a6e1f72f3.png)
