### ISSUE TITLE
[ACTION] Hubspot - Update contact

### ISSUE THREAD

**Issue by Nicolrnt** [PipedreamHQ/pipedream#4169]
**Is there a specific app this action is for?**
Hubspot

**Please provide a link to the relevant API docs for the specific service / operation.**
https://legacydocs.hubspot.com/docs/methods/contacts/update_contact
[https://developers.hubspot.com/docs/api/crm/contacts#endpoint?spec=PATCH-/crm/v3/objects/contacts/{contactId}](https://developers.hubspot.com/docs/api/crm/contacts#endpoint?spec=PATCH-/crm/v3/objects/contacts/%7BcontactId%7D)

**Comment by Hassan-Abbas-SQA** [comment]
please provide the additional information so that we can proceed furthur

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
Sorry for the premature closing of this issue @Nicolrnt! We'll add this to the team's backlog.

**Comment by Nicolrnt** [comment]
Awesome ! Thanks for the integration ! I've already implemented it in my workflows :)
