### ISSUE TITLE
[FEATURE] Add GH PR Check for TS Compile Phase

### ISSUE THREAD

**Issue by andrewjschuang** [PipedreamHQ/pipedream#4172]
**Is your feature request related to a problem? Please describe.**
Currently, there are no PR Checks that verify if a TS component was successfully compiled before publishing to Pipedream Registry after a merge.

**Describe the solution you'd like**
A GH PR Check that will (only for `.ts` files):
- [x] Verify if there is all the necessary files and directory structure mentioned in the docs.
- [x] Try to build the code in the PR scope and fail if a `.mjs` file is missing for a TS component.

**Additional Information**:
[Docs](https://pipedream.com/docs/components/typescript/#developing-typescript-components-in-the-pipedreamhq-pipedream-registry)

**Comment by dannyroosevelt** [comment]
@js07 @dylburger either of you guys have any thoughts or feedback before Andrew dives in?

**Comment by dylburger** [comment]
No specific feedback, and I love the idea, Jacob gave a +1 in Slack too.
