### ISSUE TITLE
[BUG] Errors in inspect mode don't show stack trace

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#4173]
When a step throws an error, I can't see the stack associated with the error in the event inspector:

<img width="480" alt="Screen Shot 2022-06-13 at 3 55 25 PM" src="https://user-images.githubusercontent.com/242668/188751546-78d2e5c0-d876-4bb5-9eb6-095b9a4a7c13.png">

**Comment by prakashgouda102** [comment]
import matplotlib.pyplot as plt
x = [1,2,3,]
y = [2,4,1]

plt.plot[ x.y]

plt.xlabel('x- axis')

plt.ylabel("y- axis")

plt.title("my first graph")

plt.show( ) 


not getting result why

**Comment by dylburger** [comment]
@prakashgouda102 Pipedream doesn't render Matplotlib visualizations or other images within workflows. You should be able to [write the image to a file](https://pipedream.com/docs/code/python/#writing-a-file-to-tmp) and send it to yourself via email, API, upload it to file storage like S3, etc.

**Comment by dylburger** [comment]
We should show the full stack trace under the **Details** section of the event now.

<img width="1023" alt="Screen Shot 2023-03-16 at 3 24 59 PM" src="https://user-images.githubusercontent.com/242668/225766967-19e35299-f403-4ebd-91ac-feb22059bf3b.png">
