### ISSUE TITLE
[APP] Google Assistant

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#4174]
https://developers.google.com/assistant/sdk/reference/rpc

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Submitted!

**Comment by malexanderlim** [comment]
This API has been deprecated. Closing. https://developers.google.com/assistant/ca-sunset
