### ISSUE TITLE
[APP] - WakaTime

### ISSUE THREAD

**Issue by franceme** [PipedreamHQ/pipedream#4176]
**[WakaTime](https://wakatime.com)**

**[Link to developer documentation](https://wakatime.com/developers)**

**There is a temporary workaround using custom code and connecting manually to the API?**

Actions:
* Retrieve Data for a specific day/week/etc... timeperiod
Triggers:
* if a certain productivity mark has been met

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@franceme here is a basic integration for WakaTime: 
https://pipedream.com/apps/wakatime/

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by franceme** [comment]
> @franceme here is a basic integration for WakaTime: https://pipedream.com/apps/wakatime/

Thank you for pointing this out, I did not realize this was here!

**Comment by dannyroosevelt** [comment]
> > @franceme here is a basic integration for WakaTime: https://pipedream.com/apps/wakatime/
> 
> Thank you for pointing this out, I did not realize this was here!

Oh, it wasn't there prior to your request! We just integrated them after you requested 😄 🎉 🚀
