### ISSUE TITLE
[BUG] Refresh not appearing for newly published action

### ISSUE THREAD

**Issue by tskamaldeep** [PipedreamHQ/pipedream#4180]
**Describe the bug**
After I publish a newer version of an action, I am not getting a refresh icon to move to the latest version of the action in my workflows page. This action is part of two workflows and I am not able to upgrade to the latest version in both. Please note this used to work fine without any issues during my previous use few months back.

**To Reproduce**
1. Publish a new modified version of the action
2. Try to upgrade to this version in the workflows page, look for the 'refresh' icon for the action.
3. The update to the action is not recognized by the page UI and no change is seen.

**Expected behavior**
Refresh icon should appear and I should be able to try the latest published version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser Chrome (latest)
 - Version

**Smartphone (please complete the following information):**

**Additional context**
I wrote to support, who advised that I open an issue for better visibility. Thank you.

**Comment by ctrlaltdylan** [comment]
@tskamaldeep could you please provide more details like the deployed component ID shown in the CLI when you inspect the action or attempt to publish a new version?

**Comment by tskamaldeep** [comment]
Sure @ctrlaltdylan 

sc_JDiBK4e for version published from today
sc_2AiDR0G for the version I tried publishing yesterday.

Please let me know if any other information is useful.

**Comment by DilanAthukorala** [comment]
@tskamaldeep I was not able to re-create the issue. The expected behavior is when there's a newer version of an action available there should be an"Update" button displayed when you go to the edit mode. Could you please re-check whether an update button is displayed for your action in edit mode?

**Comment by tskamaldeep** [comment]
@DilanAthukorala , I had our boss publish the action from his end and update the version which went fine. Thereafter, I was able to push further updates.

This issue is not a blocker now, thank you. Anything to take note of? Regards.

**Comment by vunguyenhung** [comment]
@tskamaldeep @DilanAthukorala @ctrlaltdylan, actually I sometime faced this issue, what I do is I use `pd logout` and `pd login` again and it would work. @tskamaldeep would you mind taking not this and try the next time you faced this issue?

@ctrlaltdylan I think this is related to Pipedream internals, is it okay to add `tracked-internally` for tracking?

**Comment by tskamaldeep** [comment]
@vunguyenhung , I shall certainly try per your suggestion if it happens again.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
