### ISSUE TITLE
[ACTIONS] CloudFlare new actions

### ISSUE THREAD

**Issue by sparkyfen** [PipedreamHQ/pipedream#4181]
**Name of app / service** Cloudflare APIs

**Link to developer documentation** https://api.cloudflare.com/ & https://developers.cloudflare.com/analytics/graphql-api/

**Is lack of support preventing you from building workflows, or do you have a workaround?** No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Actions:

https://api.cloudflare.com/#workers-kv-namespace-write-key-value-pair
* Create a Key/Value (KV) namespace to be bound to a worker.
* Add a Key/Value namespace to a worker.

https://developers.cloudflare.com/analytics/graphql-api/
https://developers.cloudflare.com/analytics/graphql-api/tutorials/querying-workers-metrics/
* Query Worker analytics.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Cloudflare_4428.pdf](https://github.com/PipedreamHQ/pipedream/files/9756439/Cloudflare_4428.pdf)
