### ISSUE TITLE
[FEATURE] Make it easier and less error prone to change an account for a workflow

### ISSUE THREAD

**Issue by dangub** [PipedreamHQ/pipedream#4184]
**Is your feature request related to a problem? Please describe.**
I was working on a couple of workflows - still in development - with steps that are connected to test accounts in external services. Now that I am ready to switch to "prod", each steps needs to be reconfigured to switch to the real account. Not only is it a manual process to do for each step, even if they belong to the same app, but crucially, it also resets what the props were set to - which can now lead to bugs in this "Prod" workflow.

**Describe the solution you'd like**
It would be good to have the accounts set at the workflow - rather than the step - level, while maybe allowing the step to overwrite the default workflow account.
And it would be crucial to maintain some mapping between a property and the parameter assigned to it. I understand that it might not always be possible with dynamic options, but in many cases it might be possible.

**Do you have a workaround?**
I duplicated the workflow and open two tabs side-by-side so that I could carefully copy each property.

**Comparable features in other tools?**
I'm not familiar with other toold

**Additional context**

**Comment by dylburger** [comment]
We're working on this concept as a part of a larger effort, and have it tracked elsewhere. Very much appreciate the feedback.
