### ISSUE TITLE
[ACTION] Customer.io Add People to Segment

### ISSUE THREAD

**Issue by tonomb** [PipedreamHQ/pipedream#4185]
**Is there a specific app this action is for?**
Customer.io
**Please provide a link to the relevant API docs for the specific service / operation.**
Add customers to segment https://www.customer.io/docs/api/#operation/add_to_segment

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
