### ISSUE TITLE
[IMPROVEMENT] Big Cartel OAuth flow improvement

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4190]
**Is your feature request related to a problem? Please describe.**
When I tried to connect Big Cartel account, and observed a popup asking for `Account ID`
![FireShot Capture 534 - New Source - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/189147892-61210ff7-775e-47c9-8096-1696c0a70669.png)

Though as an average user, I don't know how to get my Account ID from Big Cartel, and the description is not clearly say how to get one 
```
...just make a request to the Account API /v1/accounts and retrieve the id attribute from the response
```

To get the Account ID, I need to call API to URL `https://api.bigcartel.com/v1/accounts` and input Basic Auth information, with the header `Accept: application/vnd.api+json`
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/18277920/189148961-784d0dae-d887-4e3b-af38-42d4a86e3f69.png">. After inputing the Account ID, then I can continue with the OAuth flow.

This is an implicit knowledge so it's very hard for average user to use

**Describe the solution you'd like**
I would suggest we ask user to input username & password (as we have already done for other apps), then call to URL `https://api.bigcartel.com/v1/accounts` ourself to get user's Account ID. Then continue with the OAuth flow.

**Do you have a workaround?**
Yes

**Comparable features in other tools?**
I'm not sure about the other tools. Though this improvement will help the component much easier to use

**Additional context**
Component ticket: https://github.com/PipedreamHQ/pipedream/pull/4171

**Comment by dylburger** [comment]
The `account_id` was returned as a part of the access token response, which means we don't need to ask the user for it. Since I used the same key name (`account_id`), this should be backwards-compatible for any users who have already entered the account ID manually.
