### ISSUE TITLE
[BUG] Referencing value from previous step doesn't work, while pasting in the literal value does.

### ISSUE THREAD

**Issue by lucasdellabella** [PipedreamHQ/pipedream#4193]
**Describe the bug**
The referencing a value, and using a literal value itself give me different results in my step. The referenced value gives the wrong output so I cannot finish building my automation.

**To Reproduce**
See loom. I opened the pipedream up in settings so y'all can take a look. 
[go to the automation](https://pipedream.com/@lucasdellabella/track-meditation-in-notion-p_3nC6w2m)

**Expected behavior**

**Screenshots**
See loom

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version v104

**Additional context**
https://www.loom.com/share/9a72c68f2dde44ca918ac47d082d3f98

**Comment by dannyroosevelt** [comment]
@lucasdellabella thanks for writing in!

Can you tell me more about your use case? The reason that doesn't work as you're expecting it to, is because you have to configure a static "Property Type" in that action, which is based on the Page ID. So if the Page ID comes back with a different value when you run the workflow automatically, the step configuration won't work.

Does that make sense?

**Comment by lucasdellabella** [comment]
It does - you're saying that because the actual fields I'd select would change if the input were a different notion page, you don't let me use a dynamic value for the field. Makes sense! I know you guys just raised an A round so things are super early but an error message for this kind of thing would be nice. 

(i see you have it for airtable)
> The table ID. If referencing a Base dynamically using data from another step (e.g., {{steps.mydata.$return_value}}), automatic table options won't work when configuring this step. Please enter a custom expression to specify the Table.

I think y'all might need to make some change? you've essentially coupled the schema of the update to the thing being updated. There are plenty of cases across pipedream where I'm sure there is a schema that does not change, while the underlying row / page / whatever is changing. I'm sure when updating a googlesheet the schema is decoupled from the actual row being updated. Should be the same with any other app. I'm not sure what the most elegant solution to this is. The most obvious is optionally separating the input that defines the schema from the input to receive the update. 

If any change is made I'd love to know about it! I would just write code and my use case (keeping habit data up to date in notion) doesn't warrant more time spent on this.

Thanks so much for the response!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
