### ISSUE TITLE
[OAUTH+SCOPE] ZENDESK

### ISSUE THREAD

**Issue by victor-helios** [PipedreamHQ/pipedream#4195]
**Which application needs a scope added?**
Zendesk
**What scope(s) need to be added?**
"scopes": ["users:write"]
**Please provide a link to the relevant API docs for scopes.**
https://developer.zendesk.com/api-reference/ticketing/oauth/oauth_tokens/

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@victor-helios apologies for the delay, this should be done! Please reconnect your account and let us know if you're able to make use of the additional scope.

Thanks

**Comment by victor-helios** [comment]
@dannyroosevelt That's working fine, thanks a lot!
