### ISSUE TITLE
Update an event

### ISSUE THREAD

**Issue by Friedrieck** [PipedreamHQ/pipedream#4199]
**Is there a specific app this action is for?**
Google Calendar
**Please provide a link to the relevant API docs for the specific service / operation.**
https://googleapis.dev/nodejs/googleapis/latest/calendar/classes/Resource$Events.html#update

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by DilanAthukorala** [comment]
This action is also requested by [ [ACTION] Google Calendar: Update Event #4219 ](https://github.com/PipedreamHQ/pipedream/issues/4219)

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by Hassan-Abbas-SQA** [comment]
Test Passed
<img width="916" alt="image" src="https://user-images.githubusercontent.com/104946677/194426932-ef2405ae-d462-4112-a46b-225fd80ae591.png">
