### ISSUE TITLE
[BUG] Hubspot's "Deal Updated" source emits older events on first run

### ISSUE THREAD

**Issue by dangub** [PipedreamHQ/pipedream#4208]
**Describe the bug**
When you add a new Hubspot’s source Deal Updated, it emits events (deals) that were modified in the past.

**To Reproduce**
1. In the hubspot account, create a new deal entity.
2. In pipedream, add a new Hubspot source “Deal Updated”.
3. Click “Run now”.
4. Observe that the deal created in step (1) is emitted, despite not having any changes since.

**Expected behavior**
Only new events should be emitted on the first run.

**Comment by dylburger** [comment]
See #4209 , as well

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Hubspot_4232_2315.pdf](https://github.com/PipedreamHQ/pipedream/files/9585637/Hubspot_4232_2315.pdf)
