### ISSUE TITLE
[ACTION] Calendly (Oauth)

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#421]
**Is there a specific app this action is for?**
Calendly (Oauth)

**Please provide a link to the relevant API docs for the specific service / operation.**

Create event
Modify event
Cancel event

**Comment by sergioeliot2039** [comment]
Create Webhook Subscription
Action: https://pipedream.com/actions/a_bKirvj/edit
Workflow: https://pipedream.com/@sergio/calendly-create-webhook-subscription-p_MOCJPG/edit

Delete Webhook Subscription
Action: https://pipedream.com/actions/a_vgipkA/edit
Workflow: https://pipedream.com/@sergio/calendly-delete-webhook-subscription-p_6lCzmd/edit

List Organization Members
Action: https://pipedream.com/actions/a_B0imJg/edit
Workflow: https://pipedream.com/@sergio/calendly-list-organization-members-p_LQCG9B/edit

Get Webhook Subscription
Action: https://pipedream.com/actions/a_xqiVN7/edit
Workflow: https://pipedream.com/@sergio/calendly-get-webhook-subscription-p_2gCAoe/edit

List Webhook Subscriptions
Action: https://pipedream.com/actions/a_k6ij8Q/edit
Workflow: https://pipedream.com/@sergio/calendly-list-webhook-subscriptions-p_ezCvRR/edit

List Organization Invitations
Action: https://pipedream.com/actions/a_74ij0X/edit
Workflow: https://pipedream.com/@sergio/calendly-list-organization-invitations-p_vQCRKa/edit

Get Organization Invitation
Action: https://pipedream.com/actions/a_2wie6b/edit
Workflow: https://pipedream.com/@sergio/calendly-get-organization-invitation-p_mkCjMA/edit

Revoke User's Organization Invitation
Action: https://pipedream.com/actions/a_rJiavz/edit
Workflow: https://pipedream.com/@sergio/calendly-revoke-user-s-organization-invitation-p_zACoqG/edit

List User's Events
Action: https://pipedream.com/actions/a_3Li635/edit
Workflow: https://pipedream.com/@sergio/calendly-list-user-s-events-p_RRCMeG/edit

Invite User to Organization
Action: https://pipedream.com/actions/a_JmiRrK/edit
Workflow: https://pipedream.com/@sergio/calendly-invite-user-to-organization-p_7NC5Dq/edit

Get Organization Membership
Action: https://pipedream.com/actions/a_1WiEk5/edit
Workflow: https://pipedream.com/@sergio/calendly-get-organization-membership-p_aNCBaO/edit

Remove User from Organization
Action: https://pipedream.com/actions/a_oViLMN/edit
Workflow: https://pipedream.com/@sergio/calendly-remove-user-from-organization-p_5VCRr3/edit

Get Event Type
Action: https://pipedream.com/actions/a_8KiG14/edit
Workflow: https://pipedream.com/@sergio/calendly-get-event-type-p_n1CljD/edit

Get User
Action: https://pipedream.com/actions/a_A6iWm0/edit
Workflow: https://pipedream.com/@sergio/calendly-get-user-p_6lC2OK/edit

List User's Event Types
Action: https://pipedream.com/actions/a_0Mi2kB/edit
Workflow: https://pipedream.com/@sergio/calendly-list-user-s-event-types-p_G6CyDy/edit

Get Current User
Action: https://pipedream.com/actions/a_67i6kO/edit
Workflow: https://pipedream.com/@sergio/calendly-get-current-user-p_PACVm6/edit

Get Event Invitee
Action: https://pipedream.com/actions/a_EVix2m/edit
Workflow: https://pipedream.com/@sergio/calendly-get-event-invitee-p_QPC3jj/edit

List Event Invitees
Action: https://pipedream.com/actions/a_YEikm6/edit
Workflow: https://pipedream.com/@sergio/calendly-list-event-invitees-p_jmCwLo/edit

Get Event
Action: https://pipedream.com/actions/a_poiwMj/edit
Workflow: https://pipedream.com/@sergio/calendly-get-event-p_7NCpmN/edit
