### ISSUE TITLE
Planning Center

### ISSUE THREAD

**Issue by robertpiazza** [PipedreamHQ/pipedream#4210]
**Planning Center**

**[Link to developer documentation](https://developer.planning.center/docs/#/overview)**

**I have a workaround but it's not robust**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@robertpiazza I have this working but just want to confirm which scopes you'd like to include? 
https://developer.planning.center/docs/#/overview/authentication

And are there specific triggers or actions you'd like to use?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
@robertpiazza here is a basic integration -- please let us know if this is working for you https://pipedream.com/apps/planning-center
