### ISSUE TITLE
[BUG] Yahoo Sports Fantasy Trigger not emitting events

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4213]
Here is the error displayed in the logs
![image](https://user-images.githubusercontent.com/20780753/189710300-6e80dd17-13d5-4b7f-ac61-7805574d34e5.png)

**Comment by DilanAthukorala** [comment]
I am able to recreate the issue where Yahoo fantasy sports trigger not emitting events. 

![image](https://user-images.githubusercontent.com/102980146/189758311-46bba331-4083-43be-b6a4-bd4ef0a2fc9f.png)

![image](https://user-images.githubusercontent.com/102980146/189758747-3425dddf-a8ee-422a-9e5e-6a93683e7f88.png)




Also when there's no transaction events available in Yahoo Sports the following error is thrown. 

![image](https://user-images.githubusercontent.com/102980146/189757712-d0f25190-acfc-4463-bd15-36ada0804350.png)

**Comment by dannyroosevelt** [comment]
@DilanAthukorala can you please move this to the project board and drag it toward the top? (maybe top 10)
