### ISSUE TITLE
[BUG] Discord App Authentication prompting to add Webhook, results in 401

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4221]
**Describe the bug**
When connecting a Discord account, during the authorization process you're prompted to select a **Add a Webhook**.

After selecting a webhook in the Discord setup screen and click **Accept**, the configuration of the Discord webhook fails and you cannot add a Discord account to Pipedream.

**To Reproduce**

1. Create a webhook with a Pipedream Discord action on your server.
2. Delete the webhook from the Discord dashboard
3. Delete the connected account
4. Attempt to reconnect your Discord account

**Expected behavior**

**Screenshots**

Screenshare: https://www.loom.com/share/ab19bafcf2ea4982993047ba0b5ad7ae

**Additional context**

User report: https://pipedream.com/community/t/connection-to-discord-error/3222/3

**Comment by dylburger** [comment]
Since we're actively deprecating the Discord Webhook integration, I'm going to close this.
