### ISSUE TITLE
[BUG] Wrong API listed for polling

### ISSUE THREAD

**Issue by danthegoodman1** [PipedreamHQ/pipedream#4227]
Says youtube API, but is twitter api :)

![image](https://user-images.githubusercontent.com/17806508/190029757-3ddb7b61-34db-4c77-8633-d6c7e87aba20.png)

**Comment by DilanAthukorala** [comment]
@danthegoodman1 Thanks for submitting this issue, our development team will look into it.

**Comment by alysonturing** [comment]
looks like it was fixed here: https://github.com/PipedreamHQ/pipedream/pull/2540
but it may require to change the component version and update it.

**Comment by alysonturing** [comment]
I noticed that the following sources has the same error reported in the issue, so I'm upgrading the version to fix the typo in the UI. (the typo was already fixed before here: https://github.com/PipedreamHQ/pipedream/pull/2540)

New Follower of Me,
New Follower of User,
New Unfollower of Me,
New Unfollower of User
