### ISSUE TITLE
[APP] Home Assistant

### ISSUE THREAD

**Issue by atsaplin** [PipedreamHQ/pipedream#4228]
**Name of app / service**
Home Assistant

**Link to developer documentation**
https://developers.home-assistant.io/
**Is lack of support preventing you from building workflows, or do you have a workaround?**
I will need to build a python middleman api currently - but direct suppoprt for home assistant actions/triggers would be amazing for the home automation community
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Home Assistant already provides a fairly configurable trigger/action abstraction - so hooking into that would basically allow use Home assistant users to do anything!

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Additional components requested by user on#7528:

- Triggers
- google calendar event and listner
- 
- Actions
- google calendar add and remove

**Comment by sergio-eliot-rodriguez** [comment]
Closing, duplicated of #4228

**Comment by sergio-eliot-rodriguez** [comment]
this has been submitted for approval, using OAuth "indie" flavor and Nabu Casa for the Home Assistance's instance remote access @malexanderlim . i think i did a nice job here, you'll tell me)))

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/home-assistant?via=go
