### ISSUE TITLE
[BUG] auto-generated param from typing params.xyz.includes(...

### ISSUE THREAD

**Issue by oliviermills** [PipedreamHQ/pipedream#423]
**Problem**
Typing this... `params.eventTypes.includes(...`
<img width="470" alt="image" src="https://user-images.githubusercontent.com/6075303/92951133-1e6d5f00-f41b-11ea-92fe-09ff863e28bf.png">

Generated a new param of type Object... 
<img width="450" alt="image" src="https://user-images.githubusercontent.com/6075303/92951075-0695db00-f41b-11ea-9e2e-dd3fed09609f.png">

**Workaround**
Use `const { eventTypes } = params`

Deleted the param in the schema.

**Comment by dylburger** [comment]
Thanks @oliviermills , the way we parse params needs a little work in this case. I'm adding this to our backlog so we can take a look.

You may have already seen, but I believe separating the definition of the param and the use of the `includes` method should work, i.e.

```javascript
const { eventTypes } = params
eventTypes.includes(...)
```

**Comment by dylburger** [comment]
@oliviermills this should be fixed. If you use a method "inline" (e.g. `params.eventTypes.includes(...)`), we should correctly parse the param alone in the schema definition:

<img width="442" alt="Screen Shot 2020-09-14 at 11 24 01 AM" src="https://user-images.githubusercontent.com/242668/93123590-393f0e00-f67d-11ea-956d-5a2238a24f2c.png">

One thing you should note: like for other params, we default to a param type of `string`, even if you use methods like this that indicate the param should be an array or object. So you'll have to set the param type in the schema editor manually.

Let me know if this doesn't work for you.
