### ISSUE TITLE
[APP] Brightspace

### ISSUE THREAD

**Issue by chapstick404** [PipedreamHQ/pipedream#4237]
D2L Brightspace
[**Link to developer documentation**](https://docs.valence.desire2learn.com/reference.html)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Best workaround I have is using the HTTP API Requests Trigger instead of building my own application

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
They reached out and shared out a form to start a partnership -- copied michael@pd in the form.

**Comment by sergio-eliot-rodriguez** [comment]
This is now integrated https://pipedream.com/apps/d2l-brightspace
