### ISSUE TITLE
[FEATURE] [BUG] limit slow typing (debounce?) for schema editing

### ISSUE THREAD

**Issue by oliviermills** [PipedreamHQ/pipedream#424]
The typing is slowed down when editing say the description for a item in the schema editor. While I see the debounce on the XHR requests to update without needing to "save"... can anything be done to avoid the delayed UX on typing in the editor?

![Sep-11-2020 11-17-24](https://user-images.githubusercontent.com/6075303/92954312-73f83a80-f420-11ea-9de4-405dad83d42e.gif)

**Comment by dylburger** [comment]
@oliviermills that's interesting, I didn't think we implemented any debounce here but we'll look into it. What OS / browser are you using? And are you editing the schema on a workflow step, or in the action itself at https://pipedream.com/actions ?

**Comment by oliviermills** [comment]
It's both in workflows and actions. Both latest Firefox and Chrome on Mac. I'll try change things to see what's happening.

**Comment by dylburger** [comment]
@oliviermills apologies for the late follow up here, I missed your reply. I've tried replicating in both Firefox and Chrome, and I'm unable to see the same, slow display of the typed characters. The editor appears to be relatively snappy for me. Are you still observing this?

**Comment by dylburger** [comment]
Closing this since action development now happens locally ([see docs here](https://pipedream.com/docs/components/quickstart/nodejs/actions/)).
