### ISSUE TITLE
PostgreSQL connector is only reading table list from Public schema

### ISSUE THREAD

**Issue by vinay5xdata** [PipedreamHQ/pipedream#4244]
**Describe the bug**
https://github.com/PipedreamHQ/pipedream/blob/3876cfc281f396671ffa5eef6d5a0153d5425056/components/postgresql/postgresql.app.mjs  In this file -> line 111 within getTables() function schema is hardcoded as "public", because of which connector is only looking for tables in  "public" schema.

**To Reproduce**
1. Go to - Postgres connector
2. Click on  - add connection
3. Scroll down to - after successfully adding the connector, click on list tables
4. See error - It will only show the table from "public" schema

**Expected behavior**
It should be showing table list from all the schema, not only from "Public"

**Screenshots**
![image](https://user-images.githubusercontent.com/92321228/190351004-3e659d78-1b41-4d75-8cfa-bbfc3b480f92.png)

Fixes-
Can you please remove the where condition
Previously - const query = format("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'");
correct - const query = format("SELECT table_name FROM information_schema.tables");

**Comment by DilanAthukorala** [comment]
@vinay5xdata Thanks for reporting this bug. We are able to reproduce it and our team will look into it.

**Comment by DilanAthukorala** [comment]
This is issue is fixed by https://github.com/PipedreamHQ/pipedream/issues/4238
