### ISSUE TITLE
[BUG] YouTube - Start Resumable Upload Session action contains duplicate code

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#427]
Currently, this snippet of code is included twice in this action:

```javascript
if (params.part.includes('snippet')) {
  data.snippet = {
    title: params.title,
    categoryId: params.categoryId,
    defaultLanguage: params.defaultLanguage,
    description: params.description,
    tags: params.tags
  };
}
```

Moreover, it uses the standard `axios` package, but should be re-written to use the Pipedream platform version of `axios`.

**Comment by sergioeliot2039** [comment]
The duplicated snippet code was removed. As of standard axios, this was left instead of Pipedream version for the response from the action has relevant information to the user in a custom header, at the moment only feasible for reading through axios std.
