### ISSUE TITLE
[FEATURE] Select workflow name to remove it

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#4270]
**Is your feature request related to a problem? Please describe.**
Removing a workflow is really easy (2 clicks). A mistake can happend really fast.

**Describe the solution you'd like**
When removing a workflow, ask the user to select the full workflow name for confirmation instead of a simple button.

**Do you have a workaround?**
No

**Comparable features in other tools?**
When removing a repo on GitHub, the user must select the full repo name for confirmation.

**Comment by vunguyenhung** [comment]
Thank you @LucBerge for the suggestion 🙏 . I have added this ticket to Pipedream internal board for tracking, any updates will be made to this ticket 🙏

**Comment by LucBerge** [comment]
This feature has been implemented with a bug #7909
