### ISSUE TITLE
[BUG] Discord Webhooks failling with `connect EAFNOSUPPORT ::1:80 - Local (undefined:undefined)`

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4281]
**Describe the bug**
When using the **Discord Webhook** send message, the code step results in an error:

`connect EAFNOSUPPORT ::1:80 - Local (undefined:undefined)`

**Expected behavior**
I expect the step to send the webhook.

**Screenshots**

![Send to discord](https://user-images.githubusercontent.com/2694734/191040431-87c09c9f-117a-4440-b9ce-36e0f2550587.PNG)

**Additional context**

https://pipedream.com/community/t/webhook-suddenly-stopped-sending-message-to-discord-and-returns-with-an-error/3292

**Comment by dannyroosevelt** [comment]
@ctrlaltdylan tracking this here https://github.com/PipedreamHQ/pipedream/issues/4272
