### ISSUE TITLE
[ENHANCEMENT] Show Workflow title in Browser's title

### ISSUE THREAD

**Issue by justabuzz** [PipedreamHQ/pipedream#4283]
**Describe the bug**
When in the workflow section (inspector, deployments, settings, builder pages), the `<title>` tag is a static text: "Pipedream - Connect APIs, Remarkably Fast". When working on multiple workflows in parallel, this requires me to cycle through the browser tabs till I find the workflow I want to access, since all titles are the same.

**To Reproduce**
Open different workflows in separate tabs and compare the tab texts. See screenshot.

Worth noting that the Inspector page (first page to load when accessing a workflow) gets the workflow name in the `<title>`, but I see that when navigating to a different page (for example Deployments) and then returning to Inspector, it changes to the static title.

**Expected behavior**
I think it'd be good to have the workflow name in the `<title>` tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/313585/191138931-f34cf15e-d159-4121-9eb3-23254ac5ba64.png)

Thanks!

**Comment by LucBerge** [comment]
I agree it would be nice but this is not a bug, it's an enhancement.

**Comment by vunguyenhung** [comment]
Thank you @justabuzz and @LucBerge for raising this. I have added this ticket into Pipedream's internal backlog. Any updates will be made to this ticket 🙏

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
