### ISSUE TITLE
[TRIGGER] Twich: New Raid

### ISSUE THREAD

**Issue by Dy-oh** [PipedreamHQ/pipedream#4284]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

This is for an analytics tool that records and analyses incoming and outgoing twitch raids for streamers to better strategise who to raid. A Trigger for incoming raids that records who is raiding and how many viewers they sent, and a trigger for outgoing raids that records who the raid is going to and how many viewers are being sent.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelraid

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
