### ISSUE TITLE
[Action and Trigger] SendBlue

### ISSUE THREAD

**Issue by AndrewSB** [PipedreamHQ/pipedream#4291]
**Name of app / service**

sendblue

**Link to developer documentation**

https://sendblue.co/docs/inbound

**Is lack of support preventing you from building workflows, or do you have a workaround?**

nope, i'll REST it for now. would be nice to have first party support tho

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

sending messages as an action, the receiving messages web hook as a trigger

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
@AndrewSB Sendblue app integration is in progress. I created a new issue for tracking components https://github.com/PipedreamHQ/pipedream/issues/4292, feel free to follow there thanks

**Comment by lcaresia** [comment]
I didn't found SendBlue app, I only found [`SendInBlue`](https://pipedream.com/apps/sendinblue), but aparrently is not the same thing.
Can you confirm this?

Cc: @dannyroosevelt @dylburger

**Comment by sergioeliot2039** [comment]
@lcaresia you are correct -- SendInBlue is an Email Marketing platform where as SendBlue is an SMS and iMessaging API, so yeah they are different.

I previously submitted SendBlue to the App Store, can you approve on a chance please @dannyroosevelt ?

**Comment by dannyroosevelt** [comment]
@lcaresia done! there should be a `sendblue` app directory in the `pipedream` repo shortly.

@AndrewSB here is a basic integration:
https://pipedream.com/apps/sendblue/

And Lucas is going to start building out the action and trigger!

**Comment by lcaresia** [comment]
This issue is related with this one [#4292](https://github.com/PipedreamHQ/pipedream/issues/4292)

https://github.com/PipedreamHQ/pipedream/issues/4292

@dannyroosevelt or @sergioeliot2039 Can remove one of them?

**Comment by sergioeliot2039** [comment]
Oh, the this issue was to track creating the app's integation,
4292 was to keep track of the app's component devs

**Comment by dannyroosevelt** [comment]
Closing out this ticket in favor of https://github.com/PipedreamHQ/pipedream/issues/4292
