### ISSUE TITLE
[ACTION, Source] Sendblue new components

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#4292]
Sendblue

Actions:
Send Message

Source:
New Message

api docs for send message action: https://sendblue.co/docs/outbound
Webhook for new message source: https://sendblue.co/docs/inbound/

this was requested along with Sendblue app integration https://github.com/PipedreamHQ/pipedream/issues/4291

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by lcaresia** [comment]
I didn't found SendBlue app, I only found [`SendInBlue`](https://pipedream.com/apps/sendinblue), but aparrently is not the same thing.
Can you confirm this?

Cc: @dannyroosevelt @dylburger

**Comment by lcaresia** [comment]
I just implemented the action.

[Context here](https://github.com/PipedreamHQ/pipedream/pull/4540)

Cc: @sergioeliot2039 @dannyroosevelt
