### ISSUE TITLE
[BUG] My Actions in Pipedream doesn’t show logos for actions when creating a step

### ISSUE THREAD

**Issue by ghost** [PipedreamHQ/pipedream#4294]
When i publish some actions like in this case i have published profitWell Actions when iam on a list of my actions to select an action as step i can see logo of the Action like screenshot i have attached below
![image](https://user-images.githubusercontent.com/104946677/191363172-2a883f1f-0beb-48be-9a59-864c8445d687.png)

when iam selecting action for the third/second step from my actions i can’t see any logo there for the actions
and sometimes iam not getting logos on a random step creation like on the first step
![image](https://user-images.githubusercontent.com/104946677/191363295-248c6749-08a2-4a25-9af3-ff51ff67daeb.png)

**Comment by dylburger** [comment]
This should be fixed
