### ISSUE TITLE
[FEATURE] Can we should have a date picker for date props

### ISSUE THREAD

**Issue by Hassan-Abbas-SQA** [PipedreamHQ/pipedream#4295]
instead of having a date input field we should have a datepicker here if we can have this would help reduce the customer's confusion, inserting date manually is a bit confusing
<img width="743" alt="image" src="https://user-images.githubusercontent.com/104946677/191365843-4c72c984-4835-4dd7-a6f0-798a2f4c9945.png">

**Comment by dylburger** [comment]
Tracking at #1854
