### ISSUE TITLE
[TRIGGER, ACTION] QStash new components

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4297]
**Name of app / service**

QStash

**Link to developer documentation**

https://docs.upstash.com/qstash

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Nope, you can use the HTTP Builder

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Publishing messages to endpoints
Publishing messages to topics

**Comment by ctrlaltdylan** [comment]
Already have a PR open:

https://github.com/PipedreamHQ/pipedream/pull/4296

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
