### ISSUE TITLE
[ACTION]Google pub/sub push option

### ISSUE THREAD

**Issue by SwethaKumaravel** [PipedreamHQ/pipedream#4301]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by vunguyenhung** [comment]
Hello @SwethaKumaravel, could you elaborate specific action you want for the Google Cloud Pub Sub? Additionally, have you able to find the API Docs for it?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by SwethaKumaravel** [comment]
hi we needed a google pub/sub publish ,create topic ,subscription etc actions in google cloud option
