### ISSUE TITLE
[APP] formidable forms

### ISSUE THREAD

**Issue by acmecovn** [PipedreamHQ/pipedream#4303]
**Name of app / service**
formidable forms

**Link to developer documentation**
https://formidableforms.com/knowledgebase/formidable-api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by vunguyenhung** [comment]
Hello @acmecovn, would you mind specify actions or triggers you'd like to see for this app?

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Requested API access via support form, copied integrations at pd

**Comment by sergio-eliot-rodriguez** [comment]
Hi @acmecovn 

Happy to announce Formidable Forms is now integrated

https://pipedream.com/apps/formidable-forms
