### ISSUE TITLE
[BUG]  Bitbucket instant trigger fire error Cannot read properties of undefined (reading 'deployComponent')

### ISSUE THREAD

**Issue by myappfree** [PipedreamHQ/pipedream#4306]
**Describe the bug**
TypeError:
Cannot read properties of undefined (reading 'deployComponent')
    at e.mutate (https://pipedream.com/_static/deployComponent.5a6d69ab.js:1:13665)
    at async a.<computed>.a.<computed>.i.<computed> (https://pipedream.com/_static/index.793b6f15.js:2:508249)
    at async Proxy.deploy (https://pipedream.com/_static/component-form.6727050e.js:1:9301)

**To Reproduce**
1. Go to 'workflow'
2. Click on '[New Pull Request](https://pipedream.com/@riccardo91/new-pull-request-p_gYCPkVj/inspect)'
3. Click on 'create source' in the trigger

Note: the problem started after we connected my account to new Organization (if it could be related)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15103623/191514248-bc1f7fb9-0242-414c-892f-061bc96869b8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version last

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vunguyenhung** [comment]
Hello @myappfree, I'm not able to reproduce your issue. As my BitBucket: New Pull trigger is create successfully on my side.
![Screen Shot 2022-09-21 at 21 44 41](https://user-images.githubusercontent.com/18277920/191535657-d26c9f69-3a01-4659-a637-9c7e6b2582b9.png)

Could you try to reconnect your BitBucket account and try again?
![Screen Shot 2022-09-21 at 21 43 28](https://user-images.githubusercontent.com/18277920/191535378-f4879fb4-68f4-45a3-a3ea-39b861132e1d.png)

**Comment by myappfree** [comment]
the problem seems to be solved now,
but it we had it for 8 hours
