### ISSUE TITLE
[APP] adalo

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4313]
First requested by a user here: https://pipedream.com/community/t/how-to-integrate-auth0-with-adalo-app/3333

**Name of app / service**
adalo

**Link to developer documentation**
https://developers.adalo.com/docs/basics/introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Adalo is integrated here -- https://pipedream.com/apps/adalo

Duplicate, closing
