### ISSUE TITLE
[APP]Instagram

### ISSUE THREAD

**Issue by ahsanirfan85** [PipedreamHQ/pipedream#4314]
**Name of app / service** Insatgram

**Link to developer documentation** https://developers.facebook.com/docs/instagram/

**Is lack of support preventing you from building workflows, or do you have a workaround?** I do have a work around, but it would be far easier if I could use PipeDream for it.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Trigger: "When a Photo is Published." Action: "Publish a Photo to Feed."

**Comment by sergioeliot2039** [comment]
The Instagram app for Pipedream is pending approval by Facebook, Instagram's parent company.

We are tracking this here https://github.com/PipedreamHQ/pipedream/issues/445, feel free to follow there, if you'd like.
