### ISSUE TITLE
[APP] DeployHQ

### ISSUE THREAD

**Issue by jmsfwk** [PipedreamHQ/pipedream#4319]
**Name of app / service**
DeployHQ

**Link to developer documentation**
https://www.deployhq.com/support/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I can use a secret for now, but app auth would be better.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I can provide triggers and actions

**Comment by vunguyenhung** [comment]
I have checked:
- [x] No existing Github issue requesting for DeployHQ
- [x] Pipedream currently doesn't have DeployHQ integrated

Hence I will add this to our app backlog 🙏

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@jmsfwk the DeployHQ app is now integrated:
https://pipedream.com/apps/deployhq

And it looks like your PR was approved and should get merged soon!
https://github.com/PipedreamHQ/pipedream/pull/4320

Thanks so much for the contribution!
