### ISSUE TITLE
[BUG] Webhook workflow cannot select events for follow up steps

### ISSUE THREAD

**Issue by pocaloso** [PipedreamHQ/pipedream#4326]
**Describe the bug**
I cannot select event in my webhook for follow up testing. It seems all post events are not logged in the first step(trigger) of the workflow.
https://pipedream.com/@gdevevoasis/receiveemqx-p_o7CkzWj/inspect

**Comment by pocaloso** [comment]
This workflow has been delopyed already and is working. However when I edit the workflow, I cannot see all posted events for later steps, only one old event is shown. I event sent many test post data to the url, but again those test event are now shown.

**Comment by pocaloso** [comment]
I just checked this incident report and it looks like the same issue is happening again.
https://status.pipedream.com/incidents/hvkl221wcvv9
At least "event inspector did not show the results of incoming events" is what I was experienced.

**Comment by dylburger** [comment]
Hi @pocaloso , thanks for reporting. I'm not able to reproduce - that feature is working correctly for me.

Could you [follow the troubleshooting steps outlined here](https://pipedream.com/docs/troubleshooting/#a-feature-isn-t-working-on-pipedream-com) and let me know if you're still seeing the issue?

If you're still having trouble, can you post a screen recording of how to reproduce the issue, and tell me what OS / browser you're using?

**Comment by pocaloso** [comment]
Today I give it a test and now I can select all posted events. So I think this is fixed.
