### ISSUE TITLE
Unable to edit V1 Worklows

### ISSUE THREAD

**Issue by MathiasSsenabulya** [PipedreamHQ/pipedream#4328]
**Describe the bug**

**To Reproduce**
1. Go to 'pipedream.com/workflows' after logging on
2. Click on any existing V1 workflow to edit it
3. Editor opens with events on the left, but no workflow displayed on the right.

**Expected behavior**
Expected: Workflow steps display on the right to be edited.

**Screenshots**
Screenshot attached:
![image](https://user-images.githubusercontent.com/1877291/192113786-1cbe0ee1-e140-4188-88e4-d6d56b01b440.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 105.0.5195.127 (Official Build) (64-bit)

Smartphone: N/A

**Comment by dylburger** [comment]
@MathiasSsenabulya Thanks for reporting. We're tracking this incident [here](https://status.pipedream.com/incidents/01wcwrht0nw6?utm_source=slack) and will update when the fix is out.
