### ISSUE TITLE
[APP] Microsoft Excel

### ISSUE THREAD

**Issue by Ssid0427** [PipedreamHQ/pipedream#4338]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @Ssid0427 , thanks for the request.

I modified your request to stand for Excel.
There is already a Google Sheet integration:  https://pipedream.com/apps/google-sheets

Once Excel is integrated, you will be able to create a workflow that addresses your logic,
here is a guide for building workflows: https://pipedream.com/docs/workflows/

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@Ssid0427 can you tell us more about the use case you're trying to accomplish with Excel?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
