### ISSUE TITLE
[ACTION] Linkedin Get Saved Posts

### ISSUE THREAD

**Issue by harmeet-1337** [PipedreamHQ/pipedream#4339]
**Is there a specific app this action is for?**
Linkedin

**Please provide a link to the relevant API docs for the specific service / operation.**
Goal is to sync linkedin saved post in notion.

https://www.linkedin.com/help/linkedin/answer/a527126/save-content-in-your-feed?lang=en

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by andrewjschuang** [comment]
Closing since LinkedIn doesn't support this kind of operation through their API.
