### ISSUE TITLE
[ACTION] Mautic

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#434]
**Is there a specific app this action is for?**
Mautic

**Please provide a link to the relevant API docs for the specific service / operation.**
Create or Update Contact
Create/Update a Company
Delete a Company
Delete a Contact
Get a Company
Get a Contact
Make an API Call
Update a Company
Update a Contact
List Companies
Search Contacts

**Comment by sergioeliot2039** [comment]
Create Contact
https://pipedream.com/actions/a_B0immB/edit
https://pipedream.com/@sergio/mautic-create-contact-p_NMCzGZ/edit

Update Contact
https://pipedream.com/actions/a_vgippa/edit
https://pipedream.com/@sergio/mautic-update-contact-p_zACNP3/edit

Delete Contact
https://pipedream.com/actions/a_l0i77m/edit
https://pipedream.com/@/mautic-delete-contact-p_dDCmLj/edit

List Contacts
https://pipedream.com/actions/a_2wieg1/edit
https://pipedream.com/@sergio/mautic-list-contacts-p_YyCZmV/edit

Create Company
https://pipedream.com/actions/a_XziRR5/edit
https://pipedream.com/@/mautic-create-company-p_mkCJlg/edit

Update Company
https://pipedream.com/actions/a_vgippa/edit
https://pipedream.com/@/mautic-update-contact-p_zACNP3/edit

Search Contacts
https://pipedream.com/actions/a_elirrr/edit
https://pipedream.com/@/mautic-search-contacts-p_YyCZmV/edit

Get Contact
https://pipedream.com/actions/a_A6iWWa/edit
https://pipedream.com/@/mautic-get-contact-p_2gCKBy/edit

Get Company
https://pipedream.com/actions/a_nji884/edit
https://pipedream.com/@/mautic-get-company-p_YyCZdY/edit

Delete Company
https://pipedream.com/actions/a_RAiXXm/edit
https://pipedream.com/@/mautic-delete-company-p_vQClxl/edit

List Companies
https://pipedream.com/actions/a_EVixxK/edit
https://pipedream.com/@sergio/mautic-list-contact-companies-p_mkCB8o/edit

Get Campaign
https://pipedream.com/actions/a_vgipdq/edit
https://pipedream.com/@/mautic-get-campaign-p_D1CAjv/edit

Delete Campaign
https://pipedream.com/actions/a_l0i78V/edit
https://pipedream.com/@/mautic-delete-company-p_vQClxl/edit

Create Campaign
https://pipedream.com/actions/a_RAiX36/edit
https://pipedream.com/@/mautic-create-campaign-p_vQCJDd/edit

Update Campaign
https://pipedream.com/actions/a_XziR4r/edit
https://pipedream.com/@/mautic-update-campaign-p_OKC8O2/edit

List Campaigns
https://pipedream.com/actions/a_xqiVgN/edit
https://pipedream.com/@/mautic-list-campaigns-p_rvCdQ9/edit

List Campaign Contacts
https://pipedream.com/actions/a_nji83G/edit
https://pipedream.com/@/mautic-list-campaign-contacts-p_mkCRz8/edit

Clone Campaigns
https://pipedream.com/actions/a_bKirl1/edit
https://pipedream.com/@/mautic-clone-campaign-p_aNCW3g/edit

Remove Contacts to a Campaign
https://pipedream.com/actions/a_0Mi2zE/edit
https://pipedream.com/@/mautic-remove-contact-from-a-campaign-p_WxCaB9/edit

Add Contacts to a Campaign
https://pipedream.com/actions/a_67i6Qn/edit
https://pipedream.com/@/mautic-add-contact-to-a-campaign-p_KwCaVg/edit

Make an API Call
https://pipedream.com/actions/a_0Mi22b/edit
https://pipedream.com/@/mautic-make-an-api-call-p_LQCxWJ/edit

**An action related to Mautic metadata was implemented, this was required to know which fields to use as parameters in the Create/Update Contact actions.
List Contact Fields
https://pipedream.com/actions/a_zNiVV6/edit
https://pipedream.com/@sergio/mautic-list-contact-fields-p_rvCbyR/edit
https://pipedream.com/@sergio/mautic-list-contact-fields-p_rvCbyR/edit
