### ISSUE TITLE
[ACTION] Extend YouTube Data API components to YT Custom App

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4340]
We should extend support for all the `youtube_data_api` components to the `youtube_data_api_custom_app` app.

**Comment by vunguyenhung** [comment]
Hello everyone, upon checking the code for this. I see that the new Youtube Data API - Custom App component replicates all Youtube Data API component, I just verified 1 action and 1 source to make sure that the new App works, and skip all other actions, as they are replicated from the Youtube Data API component.

Test Report
[Youtube_Data_API_Custom_App_4384.pdf](https://github.com/PipedreamHQ/pipedream/files/9716327/Youtube_Data_API_Custom_App_4384.pdf)
