### ISSUE TITLE
Canva[APP]

### ISSUE THREAD

**Issue by Jauntyalien** [PipedreamHQ/pipedream#4349]
**canva**

**[Link to developer documentation](https://www.canva.com/)**

**[Is lack of support preventing you from building workflows, or do you have a workaround?] yes**

*NO! i want to use this app through here**

**Comment by sergioeliot2039** [comment]
Hi @Jauntyalien , thanks for the request.

Can doesn't have a REST API we can use to create an app integration at Pipedream.

> Canva doesn't have a REST API for automating interactions with Canva via HTTP requests, but it's something we're looking into. If you'd like to be notified about any developments or request a specific feature for the API, [click here to register your interest](https://docs.google.com/forms/d/e/1FAIpQLSfINQ4wqz21B-KUcw_4CO-ZZNKYrFRBu9f4yBjvfw8lVcUX0Q/viewform).

So for now we are blocked on Canva.

**Comment by sergioeliot2039** [comment]
The correct Canva developer docs are at https://docs.developer.canva.com/apps/

**Comment by sergio-eliot-rodriguez** [comment]
Still waiting on Canva API, let's track changes here though https://github.com/PipedreamHQ/pipedream/issues/5293

**Comment by malexanderlim** [comment]
@Jauntyalien , we've officially launched support for Canva on Pipedream as of today - feel free to check out our app [here](https://pipedream.com/apps/canva), and we are open to any feedback that you may have as well! 

If you are on a Canva Enterprise plan, we're about to roll out support for Canva's enterprise-level features, including as the ability to create designs based on your brand templates.
