### ISSUE TITLE
[ACTION] Update Threads components to use newest API

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4350]
Threads has updated their API host from `threads.com` to `trythreads.com` and has updated their API.
https://github.com/ThreadsHQ/api-documentation

We should update our actions accordingly and add async options for selecting the Channel (this used to be called "Forum"), and I think the shape of the Thread object needs to be updated

- New action: Create a channel

Ping Danny for an API key to test.

**Comment by luancazarine** [comment]
New PR - https://github.com/PipedreamHQ/pipedream/pull/4401

**Comment by vunguyenhung** [comment]
Sorry, new PR here: https://github.com/PipedreamHQ/pipedream/pull/4413

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt, I have tested the Post Thread action again per the new PR and it passed
![2121 - 0510](https://user-images.githubusercontent.com/18277920/194086788-9b6c2bbe-9d08-4dc4-a3f7-fae0e8b4d2ff.png)
![2122 - 0510](https://user-images.githubusercontent.com/18277920/194086797-79e838bb-35ca-4fde-bf79-b20402697140.png)

Also, I've changed the domain to `trythreads.com` for all props descriptions
![Screen Shot 2022-10-05 at 21 34 01](https://user-images.githubusercontent.com/18277920/194087407-5d3723a9-f634-489c-8475-25b0bd2a178a.png)

Please let me know if this is ready for release 🙏

**Comment by dannyroosevelt** [comment]
I added some comments to the PR
