### ISSUE TITLE
Triggering the workflow when new file is added in S3 bucket

### ISSUE THREAD

**Issue by vinay5xdata** [PipedreamHQ/pipedream#4353]
**Describe the bug**
When new file is added in s3 bucket, the export output is replacing spaces, any other special character with + sign.

**To Reproduce**
1. Go to add trigger
2. Click on AWS
3. Scroll down to when new file is added to S3 bucket
4. Upload the file with having spaces or special character in Name, then see the export output. You will see + sign in file name.

**Expected behavior**
It should output the original file name. 

**Screenshots** My original file name has space
![image](https://user-images.githubusercontent.com/92321228/192734651-9b846c65-ef1e-4004-91bb-7ab3b5f1bcf1.png)

**Comment by dylburger** [comment]
This is how AWS sends us the data, and the + can be decoded as a space using parsing techniques like documented here: https://stackoverflow.com/questions/44779042/aws-how-to-fix-s3-event-replacing-space-with-sign-in-object-key-names-in-js
