### ISSUE TITLE
[updating a google calendar event]

### ISSUE THREAD

**Issue by jilzerndt** [PipedreamHQ/pipedream#4354]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

can i update the start and end time of an event in my google calendar?

**Comment by Hassan-Abbas-SQA** [comment]
@jilzerndt which event you are talking about? 
what do you want to update in time props?

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by Hassan-Abbas-SQA** [comment]
@jilzerndt pardon me for the interruption somehow reequested user help with componenet label was removed so added action docs label again so that it will trigger the process as it should be

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by michelle0927** [comment]
@jilzerndt @Hassan-Abbas-SQA The Google Calendar action, [Update Event](https://github.com/PipedreamHQ/pipedream/tree/master/components/google_calendar/actions/update-event) allows for updating the start and end date/time of an event.
