### ISSUE TITLE
[FEATURE] Ability to lock sources and workflows to avoid accidental deletion

### ISSUE THREAD

**Issue by trendoscope-algorithms** [PipedreamHQ/pipedream#4361]
**Is your feature request related to a problem? Please describe.**
Since I have my systems running in my account and also I keep trying to do bit of development every now and then, I feel bit uncomfortable about all the workflows and sources being together. I keep deleting the test ones. But, constantly fear about accidentally deleting the ones I require for my workflows. In fact, today, I accidentally deleted one of the source by mistake. However, it was not that critical - hence no harm done.

**Describe the solution you'd like**
There are two things which can improve this situation.
1. Enable locking sources and workflows. This will enable us to protect our production workflows and sources.
2. Allow folder structure to maintain sources and workflows. This will enable us to group all critical ones in a single do not touch folder.

**Do you have a workaround?**
Being extra cautious is the only workaround at present.

**Comparable features in other tools?**
This is common feature in many of the integration products I have tried - including zapier

**Additional context**
NA

**Comment by ctrlaltdylan** [comment]
Hi @trendoscope-algorithms 

Great suggestion, I myself have accidentally deleted workflows and sources I didn't intend to as well.

Per suggestion #2, that is in active development. There is a big improvement coming to how workflows are organized in the Pipedream dashboard and I think it will line up quite nicely with what you're looking for.

Stay tuned for an announcement with that feature!

**Comment by vunguyenhung** [comment]
Hello @trendoscope-algorithms @ctrlaltdylan, as the feature is already in active development, I will close this issue to avoid duplicated ticket on Pipedream's internal project board. 

@trendoscope-algorithms please stay tune for an announcement regarding this feature 🙏

**Comment by trendoscope-algorithms** [comment]
@vunguyenhung What I understood is #2 is in development but not #1
Can you confirm that once?

**Comment by vunguyenhung** [comment]
Oh sorry @trendoscope-algorithms I miss read 2 points. I will add this to Pipedream internal project board
