### ISSUE TITLE
[BUG] Error saving timezone in CRON

### ISSUE THREAD

**Issue by evolts21** [PipedreamHQ/pipedream#4362]
**Describe the bug**
If i set the timezone to Rome/Europe using the cron in the source, it saves it, but when I reload the source, it's always saved with as UTC.

**To Reproduce**
1. Set the timer in a trigger
2. Choose Cron
3. Set the timezone to something different from UTC
4. Save it
5. Reload the source
6. The timezone is set to UTC

Additional info: modifying the source from the Sources page (https://pipedream.com/sources) it's possibile to modify the CRON, but not the timezone.

**Expected behavior**
The choosen timezone should be saved.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Firefox
 - Version Latest

**Comment by Hassan-Abbas-SQA** [comment]
before
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/104946677/192897440-fe63f387-c264-4be2-b45d-52b392ccb3cc.png">
after
<img width="494" alt="image" src="https://user-images.githubusercontent.com/104946677/192897507-cf5ac2f7-5500-4958-b8c3-f4753543ecab.png">
verified the bug internally

**Comment by dylburger** [comment]
This should be fixed
