### ISSUE TITLE
[APP] BingX crypto exchange

### ISSUE THREAD

**Issue by trendoscope-algorithms** [PipedreamHQ/pipedream#4363]
**Name of app / service**
BingX Crypto Exchange

**Link to developer documentation**
https://bingx-api.github.io/docs/swap/introduce.html

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I am very ambitious on crypto exchange integrations. This will definitely be the first of many. I am also ready to do the development for actions. But, I may need the initial app before I proceed.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I can implement the API actions once the app is initialized.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by ctrlaltdylan** [comment]
@dannyroosevelt can we support pre-flight request signature generation?

This API signs each payload that's unique to each request: https://bingx-api.github.io/docs/swap/authentication.html#signature

**Comment by sergioeliot2039** [comment]
I think so, usually a components handles signature creation for sending the request, as far as I remember 
however on the App Store Project I am marking these as blocked for now on this project I am adding only key based apps, hopefully this can be prioritized internally.

that said, I created a couple of API Key, if someone needs them they are on the Project App Store sheet. kind of a hassle it needed me to use Google Authentication and required up to 3 validations -- on sign up, enabling api, creating the keys.

**Comment by ctrlaltdylan** [comment]
@trendoscope-algorithms , I think you're right. The component itself will need to contain the logic to generate the signature.

I published the app as is, it will ask for your BingX `api_key` and `secret_key`, and that will allow you to build out the component to authenticate.

Here's the marketplace page: https://pipedream.com/apps/bingx

I added a note in the app scaffolding about this caveat.

@trendoscope-algorithms do you want to try building the signature generation in an action? Then I can update the integration to include the request signing portion.

**Comment by trendoscope-algorithms** [comment]
@ctrlaltdylan - Yes I can build the signature generation in action components. I have a running python code block in my local. Just need to build on the same basis.

**Comment by trendoscope-algorithms** [comment]
Hello Everyone,

Done with the initial action implementation. PR here: https://github.com/PipedreamHQ/pipedream/pull/4381

Once reviewed and merged, I can look at the other action implementation.
