### ISSUE TITLE
[BUG] Slack Bot API actions failing to run

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4366]
**Describe the bug**

Slack Bot actions fail to run test events.

**To Reproduce**
1. Add a new Slack Bot - Use any Slack Bot API action to a workflow
2. Connect your Slack Bot with a valid bot token
3. Click **Test**
4. See infinite loading screen

**Expected behavior**
I expect to be able to test Slack Bot actions.

**Screenshots**
![CleanShot 2022-09-28 at 13 32 55](https://user-images.githubusercontent.com/2694734/192850273-6815e4ae-2723-4abe-af2f-67a1ea240562.png)

**Additional context**
Reported in Public Slack initially: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1664369237370989

**Comment by Hassan-Abbas-SQA** [comment]
unable to reproduce the issue
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/104946677/193151953-eab873a7-2d2c-4d05-ba79-69a520e4aee5.png">

**Comment by DilanAthukorala** [comment]
@ctrlaltdylan @Hassan-Abbas-SQA I am observing the same issue where it keeps loading. I will add this to backlog for further investigation.

**Comment by pioneerfund-ops** [comment]
Seeing the same behavior as @ctrlaltdylan:

- As soon as I add the `Slack Bot - Use any Slack Bot API` action to a workflow, the browser is unable to save a draft (and _I think_ that as a result, tests can't be run, I can't open `Settings` for the workflow, etc)
- This persists even after the action has been deleted, so adding any other actions becomes impossible

**Browsers:** Brave & Firefox
**OS:** Ubuntu 20.04

**Comment by dannyroosevelt** [comment]
@ctrlaltdylan @pioneerfund-ops I updated the test request scaffolding and got this working with a basic request that should work with any Slack Bot token, independent of scopes. Feel free to remove the existing step that wasn't working and re-add the same "Slack Bot - Use any Slack Bot API" step and test again.

Or you can also paste this code and give that a whirl:
```
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    slack_bot: {
      type: "app",
      app: "slack_bot",
    },
  },
  async run({steps, $}) {
    return await axios($, {
      url: `https://slack.com/api/auth.test`,
      headers: {
        Authorization: `Bearer ${this.slack_bot.$auth.bot_token}`,
      },
      method: 'post',
    })
  },
})

```
