### ISSUE TITLE
[APP] Kucoin Futures

### ISSUE THREAD

**Issue by trendoscope-algorithms** [PipedreamHQ/pipedream#4385]
**Name of app / service**
Kucoin Futures API

Please note there is separate API for spot. So, please name the app as Kukoin Future

**Link to developer documentation**
https://docs.kucoin.com/futures/#general
Also have nodejs implementation under : https://github.com/Kucoin/kucoin-futures-node-sdk

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Just trying to expand available exchange integrations so that I and the other people use what fits the usecase more.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Once I am done with current experiments with BingX, I can move to this and carry on with development.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there @trendoscope-algorithms 

Kucoin Futures has been previously integrated: https://pipedream.com/apps/kucoin-futures
