### ISSUE TITLE
[BUG] Error{"embeds":["0"]}

### ISSUE THREAD

**Issue by elibroftw** [PipedreamHQ/pipedream#4387]
**Describe the bug**

I have a NodeJS step which returns a list of embed objects.
The next step is to send a Discord embed message,
so I have `{{steps.process_event.$return_value}}` as the embed param.

In the traceback when I run test, I get 

```
Error{"embeds":["0"]}
at Object.sendMessage (file:///tmp/__pdee__/c_qafpxz1E/user/discord_webhook.app.mjs:67:15)
at process.processTicksAndRejections (internal/process/task_queues.js:95:5)
at Object.run (file:///tmp/__pdee__/c_qafpxz1E/user/actions/send-message-advanced/send-message-advanced.mjs:42:7)
at global.executeComponent (/var/task/launch_worker.js:146:22)
at MessagePort.messageHandler (/var/task/launch_worker.js:618:28)
```

This bug has been around for months, ever since it broke. I have no idea what you guys are doing, but this steps thing is not idiot proof. 

**To Reproduce**

Return a list of embed objects in a NodeJS step called `process_event`.
In the next step, make a Discord advanced message and use `{{steps.process_event.$return_value}}`
Try running this.

**Expected behavior**
Should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/21298211/193432103-c241a549-7df0-49f4-80f6-9c25558edddc.png)
![image](https://user-images.githubusercontent.com/21298211/193432115-86c9eb34-635f-49d2-bd7d-c7466750d506.png)

**Desktop (please complete the following information):**
No

**Smartphone (please complete the following information):**
No

**Comment by dylburger** [comment]
@elibroftw Thanks for reporting. This actually looks like an issue on Discord’s side. It’s not apparent from the error message, but Discord tries to fetch the URL you provide in the embed message (the https://pipedream.com/sources/ URL) before they post the message. That URL is only available when you’re logged in, otherwise it returns a 404. When Discord receives a 404 on any URL in the embeds, it returns the error you’re seeing. 

Try changing that https://pipedream.com URL to https://example.com and it should work. 

If that works, I’d recommend sending the feedback to Discord that they should allow you to send private URLs like this. We see this occasionally from users and it would be great if they allowed this use case. 

Let me know if that doesn’t fix the issue and we can help troubleshoot further.

**Comment by elibroftw** [comment]
Thank you for telling me that, I wasn't sure if it was you guys or Discord, but it was really pissing me off. 
I hope Element/Matrix improves their APIs because I'd want to move over to them ASAP.

**Comment by elibroftw** [comment]
I removed the url and still got the same error

**Comment by elibroftw** [comment]
```
{"username":"Music Caster","avatarURL":"https://github.com/elibroftw/music-caster/blob/master/resources/favicons/android-chrome-256x256.png?raw=true","includeSentViaPipedream":false,"embeds":[{"title":"New Error (v5.8.2) - NotConnected","color":49151,"fields":[{"name":"VERSION","value":"5.8.2","inline":true},{"name":"FATAL","value":"true","inline":true},{"name":"EXCEPTION TYPE","value":"NotConnected","inline":true},{"name":"LINE","value":"3688","inline":true},{"name":"TRACEBACK","value":"Traceback (most recent call last):\n  File \"music_caster.py\", line 1802, in play\n  File \"pychromecast/controllers/receiver.py\", line 181, in set_volume\n  File \"pychromecast/controllers/__init__.py\", line 121, in send_message\n  File \"pychromecast/controllers/__init__.py\", line 133, in send_message_nocheck\n  File \"pychromecast/socket_client.py\", line 938, in send_platform_message\n  File \"pychromecast/socket_client.py\", line 927, in send_message\npychromecast.error.NotConnected: Chromecast 192.168.7.147:8009 is connecting...\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"music_caster.py\", line 3688, in <module>\n  File \"music_caster.py\", line 2783, in read_main_window\n  File \"music_caster.py\", line 2226, in prev_track\n  File \"music_caster.py\", line 1827, in play\n  File \"music_caster.py\", line 1252, in change_device\n  File \"pychromecast/controllers/media.py\", line 592, in update_status\n  File \"pychromecast/controllers/__init__.py\", line 107, in send_message\n  File \"pychromecast/controllers/__init__.py\", line 60, in launch\n  File \"pychromecast/controllers/receiver.py\", line 143, in launch_app\n  File \"pychromecast/controllers/receiver.py\", line 132, in update_status\n  File \"pychromecast/controllers/__init__.py\", line 121, in send_message\n  File \"pychromecast/controllers/__init__.py\", line 133, in send_message_nocheck\n  File \"pychromecast/socket_client.py\", line 938, in send_platform_message\n  File \"pychromecast/socket_client.py\", line 927, in send_message\npychromecast.error.NotConnected: Chromecast 192.168.7.147:8009 is connecting...\n","inline":true},{"name":"LOG","value":"2022-10-01 23:43:05,085 INFO (2156): next_track(from_timeout=True),2022-10-01 23:43:05,197 INFO (2156): next_track(from_timeout=True),2022-10-01 23:43:05,301 INFO (2156): next_track(from_timeout=True),2022-10-01 23:43:05,408 INFO (2205): prev_track(),2022-10-01 23:43:05,415 INFO (1782): Playing $FILE.flac @0, autoplay=True, switching_device=False),2022-10-01 23:43:05,473 ERROR (1812): play could not cast because cast is not connected,2022-10-01 23:43:05,473 INFO (1223): change_device(local),2022-10-01 23:43:05,473 INFO (3692): FATAL exception detected: Chromecast 192.168.7.147:8009 is connecting...,2022-10-01 23:43:05,474 INFO (3373): called auto_update(), IS_FROZEN=True,2022-10-01 23:43:05,837 INFO (3432): auto_update: no update found, or no internet, or API rate limited","inline":true},{"name":"MQ[0]","value":"Z:/Richard Marx -2022- Songwriter/02. Richard Marx - Only A Memory.flac","inline":true},{"name":"PLAYING_STATUS","value":"PLAYING","inline":true},{"name":"DEVICE","value":"cast","inline":true},{"name":"CWD","value":"C:\\_AppsPort\\Music Caster Port","inline":true},{"name":"PORTABLE","value":"true","inline":true},{"name":"MAC","value":"5e366deaf3a3df858f87ae0a2f19614c","inline":true},{"name":"OS","value":"Windows-10-10.0.19044-SP0","inline":true},{"name":"TIME","value":"2022-10-01 23:43:05.838169","inline":true}]}]}
```

**Comment by elibroftw** [comment]
Is it possible for you guys to just take a webhook URL as input so that everything works? It's quite unfortunate that I have to approve PIpedream's webhook to my channel instead of just supplying Pipedream with my webhook url?

**Comment by elibroftw** [comment]
And there's no intuitive way to remove connected accounts. 
![Uploading image.png…]()

**Comment by elibroftw** [comment]
@dylburger 
https://gist.github.com/dmdboi/743111ae5945a1fe1ea558039cbe25f7 shows that data has to be a String?

**Comment by elibroftw** [comment]
One of my fields probably exceeded the fields limit. Thanks anways.
