### ISSUE TITLE
[BUG] Google Calendar action typos in titles

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4392]
**Describe the bug**
Some Google Calendar components have misspellings in their titles.

https://pipedream.com/apps/google-calendar

Retr_ei_ve needs to be corrected to Retr_ie_ve for example on a number of action names.

**Comment by DilanAthukorala** [comment]
Following tiles have title misspelling for "Retrieve"
![image](https://user-images.githubusercontent.com/102980146/193629247-4de22155-e044-48c0-9114-85c153c92c0c.png)
![image](https://user-images.githubusercontent.com/102980146/193629323-445a2b1b-42c2-4781-bdff-cfd3bff62134.png)
![image](https://user-images.githubusercontent.com/102980146/193629385-349b38cd-f052-4aeb-914e-4d5a087003b6.png)
