### ISSUE TITLE
Postmark auth seems to not work

### ISSUE THREAD

**Issue by kgilden** [PipedreamHQ/pipedream#440]
**Describe the bug**
Adding Postmark integration does not have a field for entering the API key. Even when adding the key manually via https://pipedream.com/apps, I get the following error.

```
TypeErrorCannot read property 'api_key' of undefined
```

**To Reproduce**
1. Add a "Run Node.js code with Postmark" action.

**Expected behavior**
I have a place to enter the Postmark API key.

**Screenshots**

![2020-09-15_14-17](https://user-images.githubusercontent.com/918599/93204142-47189000-f75e-11ea-9451-c3341543d4ec.png)

**Comment by todsac** [comment]
@kgilden - Apologies! This was a configuration error and has been fixed.  Please confirm there are no issues remaining on your end.

**Comment by kgilden** [comment]
@todsac yep, works great. Thank you!
