### ISSUE TITLE
[WIX]

### ISSUE THREAD

**Issue by mkures** [PipedreamHQ/pipedream#4411]
WIX

**Link to developer documentation**
https://dev.wix.com/api/rest/getting-started

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I just need the Oauth 2 support for them. Or a good way to do it myself in pipedream

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
For the moment i think i can do all actions by myself

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @mkures thanks for the request.

We are tracking WIX here: https://github.com/PipedreamHQ/pipedream/issues/3992
feel free to follow there, if you'd like

**Comment by dannyroosevelt** [comment]
FYI @mkures we've just enabled the Wix OAuth integration here:
https://pipedream.com/apps/wix/

Note that the only scopes we've included so far are for contacts and members. Please let us know if there are others that you need, depending on your use case.
