### ISSUE TITLE
[BUG] GitHub "New issue with status" trigger not configured correctly

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4415]
This source is asking me to select a repo, but projects don't need to belong to repos ([for example](https://github.com/orgs/PipedreamHQ/projects/8/views/1)).

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/193978503-d4368fb8-3544-4246-b0f5-1fa91947fe06.png)

**Comment by DilanAthukorala** [comment]
I am able to reproduce the scenario where projects can be created without assigning them to Repositories.

**Comment by DilanAthukorala** [comment]
Verification completed and issue is resolved.
