### ISSUE TITLE
UPDATE COMPANY action

### ISSUE THREAD

**Issue by DevOps-Tuck** [PipedreamHQ/pipedream#4426]
**Is there a specific app this action is for?**
Lots of people would really love this!! 😁 

**Please provide a link to the relevant API docs for the specific service / operation.**

Legacy API Docs.
https://legacydocs.hubspot.com/docs/methods/companies/update_company

Updated API Docs.
https://developers.hubspot.com/docs/api/crm/companies

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
