### ISSUE TITLE
[APP] Bybit Crypto Exchange

### ISSUE THREAD

**Issue by trendoscope-algorithms** [PipedreamHQ/pipedream#4444]
**Name of app / service**
ByBit Crypto exchange

**Link to developer documentation**
https://bybit-exchange.github.io/docs/futuresV2/linear/#t-introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Just trying to expand the available crypto exchanges.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I can do the development if initial app can be setup.

**Comment by sergioeliot2039** [comment]
Authentication requires creating a signature on the request

> The following parameters must be used for authentication:

> api_key
> timestamp - UTC timestamp in milliseconds
> sign - a signature derived from the request's parameters

**Comment by trendoscope-algorithms** [comment]
> Authentication requires creating a signature on the request
> 
> > The following parameters must be used for authentication:
> 
> > api_key
> > timestamp - UTC timestamp in milliseconds
> > sign - a signature derived from the request's parameters

@sergioeliot2039 
The signature mechanism looks similar to that of BingX. It need to be generated for each request. Also, based on python implementation here: https://pypi.org/project/pybit/

All we need in the app is to accept access key and secret key. Rest will be implemented as part of actions.

**Comment by trendoscope-algorithms** [comment]
Discussed in Slack with @dannyroosevelt - it is probably good idea to create different apps for different APIs of Bybit.

For example

ByBit Spot
ByBit USDT Perpetual
ByBit Unified
ByBit Inverse

I will probably start with ByBit USDT Perpetual - which I think is most used. Can expand to others in time.

**Comment by sergio-eliot-rodriguez** [comment]
ok, please check if the integration that was placed works for your case:

https://pipedream.com/apps/bybit
