### ISSUE TITLE
[FEATURE] Possibility to filter results if google-drive-list_files action

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#4447]
**Is your feature request related to a problem? Please describe.**
When listing the files in a Google Drive folder, I would like to get the files cointaining `TPS` in the name.

**Describe the solution you'd like**
Add an optional field to filter files cointaining a substring.

**Do you have a workaround?**
Use a custom code block to filter the files by name.

**Comparable features in other tools?**
Maybe

**Additional context**
I'm interested in building it

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
