### ISSUE TITLE
[BUG] Notion update_page pageId prop returns error on async options

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4448]
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/194606007-77dd74b6-7da0-4921-a3e6-c65ef5d9b734.png)

**Comment by Hassan-Abbas-SQA** [comment]
TestCases Passed 
<img width="935" alt="image" src="https://user-images.githubusercontent.com/104946677/194644214-5d4bc811-2919-4d53-a664-a8b0f25839d1.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/104946677/194644608-25880208-3943-4fc4-8ee3-db9a9638098a.png">
