### ISSUE TITLE
Facebook Leads [APP]

### ISSUE THREAD

**Issue by rahulmat** [PipedreamHQ/pipedream#4453]
**Name of app / service**
Retrieving Facebook Ad Leads

**Link to developer documentation**
https://developers.facebook.com/docs/marketing-api/guides/lead-ads/quickstart/webhooks-integration/
https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving/
https://developers.facebook.com/docs/marketing-api/guides/lead-ads/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I don't know of a workaround because I cannot code

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
When a user fills in a Facebook form, the details of the form are captured so I can update that information in to a google sheet

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hey @rahulmat thanks for the request.

We added Facebook Leads app integration to our backlog.
For tracking New Leads we are following Issue #925

**Comment by sergio-eliot-rodriguez** [comment]
Hi there @rahulmat 

Facebook Leads was integrated https://pipedream.com/apps/facebook-lead-ads

New lead source and other components are now being tracked on #6907  please follow there, thanks
