### ISSUE TITLE
[APP] LearnWorlds

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#4455]
**Link to developer documentation**
https://support.learnworlds.com/support/solutions/articles/12000017230-learnworlds-api-documentation

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@zalmanlew I sent a request to LearnWorlds to see if we can get access to their API and to set up an OAuth app.

**Comment by sergio-eliot-rodriguez** [comment]
Sorry for the delay @zalmanlew , LearnWorlds is integrated https://pipedream.com/apps/learnworlds
