### ISSUE TITLE
[FEATURE] Email trigger should support larger payloads than 150Kb

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#446]
Currently, [I can only send 150Kb of total email](https://docs.pipedream.com/limits/#email-triggers) (body, headers, and attachments) to an email trigger in a workflow. I often want to process attachments that put me over this limit, so I'd like to see support for larger payloads.

See [this discussion](https://github.com/PipedreamHQ/pipedream/discussions/405) for more details.

**Comment by benlatz** [comment]
Is there a way to strip out attachments from a received email? I get attachments that are over the limit, causing issues, but don't actually need the attachments (and I don't control the email source).

**Comment by dylburger** [comment]
@benlatz and I discussed this over Slack. Currently it's not possible to conditionally drop properties of an incoming payload. 

For others — if you control the HTTP request, you can send payloads larger than 512KB using `multipart/form-data` requests, [as documented here](https://docs.pipedream.com/workflows/steps/triggers/#large-file-support).

**Comment by sergebat** [comment]
Just want to leave it here for the record that now the documented limit is even smaller.
---
The only limit that differs between email and HTTP triggers is the payload size: the body of HTTP requests is limited to 512KB, where the total size of an email sent to a workflow - its body, headers, and attachments - **is limited to 150KB**.

This limit cannot be raised.

**Comment by dylburger** [comment]
We now support receiving emails up to 30MB through a new, workflow-specific email address. If your workflow's email address is `endpoint@pipedream.net`, you can send emails to `endpoint@upload.pipedream.net` to take advantage of the size increase.

Emails sent to the upload.pipedream.net address will not be automatically parsed. Instead, the raw email will be made available at a private URL in the variable `steps.trigger.event.mail.content_url` that you can download in your workflow.

[See the docs](https://docs.pipedream.com/workflows/steps/triggers/#sending-large-emails) for more information and a couple of example workflows showing you how to download and parse the email.
