### ISSUE TITLE
[BUG] Notion Update Page Properties not listing when a path for Page ID from a previous result is selected

### ISSUE THREAD

**Issue by andrewjschuang** [PipedreamHQ/pipedream#4460]
**Describe the bug**
Using the Notion **Update Page** action, when choosing a **Page ID** or manually typing in a value, the **Property Types** props will show a list of options. **But**, when selecting a **path** from a previous component, the **Property Types** will **not** list options. I suspect it may have something to do with `additionalProps` and the Pipedream UI.

**To Reproduce**
1. Create a new Pipedream workflow
2. Add a **Notion Find Page** action and click **Test** so there are pages in the results
3. Add a **Notion Update Page** action
4. In the **Page ID** prop, click on **Enter a custom expression** and select a path for a `pageId` from the results of the previous action, e.g. `{{steps.find_page.$return_value.results[0].id}}`
5. Click on the **Property Types** prop and verify that there are **No matching options**

**Expected behavior**
**Property Types** prop should contain options.

**Screenshots**

Screenshot displaying the bug:
![Screen Shot 2022-10-10 at 9 20 20 AM](https://user-images.githubusercontent.com/15385076/194868729-3222248d-858e-4ac4-8dcf-2544ff0da922.png)

Screenshot for "hardcoded" Page ID:
![Screen Shot 2022-10-10 at 9 20 49 AM](https://user-images.githubusercontent.com/15385076/194868930-a827dc0c-8c89-40d2-9ec7-9712aadd58f2.png)

Screenshot for configuration through UI:
![Screen Shot 2022-10-10 at 9 21 36 AM](https://user-images.githubusercontent.com/15385076/194868987-7b6ffa81-9a92-479e-bb27-e3989658e712.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey v12.6
 - Browser: Google Chrome
 - Version 105.0.5195.125 (Official Build) (arm64)

**Additional Context:**
Reported by a user [here](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1665266460493409)

**Comment by vunguyenhung** [comment]
Hello @andrewjschuang, I'm able to reproduce this issue. Added `tracked-internally` label

On another note, I found another issue might be linked to this issue: https://github.com/PipedreamHQ/pipedream/issues/3255, but I'm not sure they refer to the same thing

**Comment by andrewjschuang** [comment]
> Hello @andrewjschuang, I'm able to reproduce this issue. Added `tracked-internally` label
> 
> On another note, I found another issue might be linked to this issue: #3255, but I'm not sure they refer to the same thing

Oh, thanks @vunguyenhung ! They are the same issue.
Closing since this is duplicate of #3255.
