### ISSUE TITLE
[APP] Getresponse

### ISSUE THREAD

**Issue by leonbejar83** [PipedreamHQ/pipedream#4461]
**Name of app / service** Getresponse

**Link to developer documentation** https://apidocs.getresponse.com/v3

**Is lack of support preventing you from building workflows, or do you have a workaround?** I dont hace any solution

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Know the number of subscribers per list.

**Comment by sergioeliot2039** [comment]
Hi @leonbejar83 , thank you so much for the request!

GetResponse is integrated, see -- https://pipedream.com/apps/getresponse

We are tracking several GetResponse components here: https://github.com/PipedreamHQ/pipedream/issues/3633, check it out to see if they cover your use case.

If there is another app you'd like to see integrated too, feel free to let us know!
