### ISSUE TITLE
Trello trigger: New member added to card triggers for all/any new members

### ISSUE THREAD

**Issue by veshtitsa** [PipedreamHQ/pipedream#4462]
**Describe the bug**
Workflows triggered by the "New member added to card" trigger, are run on all member additions within the board, not just the authenticated member.

**To Reproduce**
1. Assign a dummy trello board with at least two members: A and B.
2. On Pipedream, create a workflow with "New member added to card" trigger and connect the Trello account as User A
4. (Optional) Add any steps.
5. Deploy the workflow.
6. On trello, add a new card and assign user B.
7. Check workflow log in Pipedream. The workflow has been triggered for user B

According to the description of the trigger, it should "Emit new event for each card joined by **the authenticated Trello user**". The workflow in the reproduction steps should not be triggered for User B, the workflow should be triggered only for User A connected to the trigger

[The modelId in the pipedream webhook definition is that of the member only if no board is selected.](https://github.com/PipedreamHQ/pipedream/blob/9d827b84ac4edf4085d69836833d691702c7bcad/components/trello/sources/common-webhook.mjs#L42). The webhook is thus attached to the board and not the user/member who authenticated before the API, and the user/member is never filtered upon a webhook call.

**Suggested enhancement**
Add the prop `Only include cards assigned to me: boolean`, with default value to `false`. If this prop is true, set the User ID as the `modelId` sending to Trello webhook, so that events only emitted for the card assigned to the connected user account 

I'm planning on tackling this during the weekend, if no one gets to it first. Creating an issue so that it's out in the open!

**Comment by vunguyenhung** [comment]
Hello @veshtitsa, for me to understand the issue, is the User B not authenticated? "Not Authenticated" means that you're not currently logged into the User B?

Per the [source implementation details here](https://github.com/PipedreamHQ/pipedream/blob/9d827b84ac4edf4085d69836833d691702c7bcad/components/trello/sources/new-member-on-card/new-member-on-card.mjs#L22), we use the event `addMemberToCard` from Trello, so the source emits event whenever Trello calls our webhook.

**Comment by veshtitsa** [comment]
Hi @vunguyenhung !

I think you've understood correctly, but I'll just reiterate anyway, just to be on the safe side 😃 

As I understand it, the authentication which the source description refers to is the OAuth authentication before the Trello API, i.e. "Emit new event for each card joined by the **authenticated Trello user**" = "Emit new event for each card joined by **user A, granted that user A is the one who's provided their OAuth access rights to the trello API.**"

Assuming I've understood the description correctly, I'd say that User B is not authenticated and should not trigger the workflow on User A's behalf. 


### An example from the real world
An example from the real world: I made a workflow, which is triggered when a trello card is assigned to me in my workplace's trello board. The workflow then collects said card's data and posts it on my private Notion database, as an individual work item. 

After a few days my notion database was filled with entries based on cards which have never been assigned to me. Checking in the pipedream logs confirmed, that the trigger had run even for cards assigned to my colleagues.


### Why this might be happening
As per the [trello webhook documentation](https://developer.atlassian.com/cloud/trello/guides/rest-api/webhooks/), webhooks are attached to model ids, models being of the type card, board, member etc. This is done via the modelId prop.

[The modelId in the pipedream webhook definition is that of the member _only if no board is selected_.](https://github.com/PipedreamHQ/pipedream/blob/9d827b84ac4edf4085d69836833d691702c7bcad/components/trello/sources/common-webhook.mjs#L42) The webhook is thus attached to the board and not the user/member who authenticated before the API, and the user/member is never filtered upon a webhook call either.

This means that effectively by step two of the steps to reproduce (Assign dummy board...) the user has already set up the webhook so that any member additions on any card within the board would trigger the workflow.

### Possible fixes
I think the source description as-is is misleading. We can either:
1. Change the description, so that it explains what granting board selection would do: waive the assumption that all triggers are assigned to the authenticated member OR
2. Change the "addMemberToCard" source behaviour, so that it filters out all triggers, which do not belong to the authenticated member (as per the description).

**Comment by vunguyenhung** [comment]
@veshtitsa Thank you so much for a very clear explanation! 

For short-term solution, I would suggest to use Pipedream Filter actions to stop the workflow if the event is not assigned to you. Here's an example: https://www.youtube.com/watch?v=sajgIH3dG58

For the long-term solution: I think we can improve this by adding an option `Only include cards assigned to me: boolean`, with default value to `false`. Doing this would avoid breaking existing workflow from other users when they update the action.

**Comment by veshtitsa** [comment]
Further note, in case someone comes across this issue before it's fixed:
When writing the filter action, make sure to compare only the last element of membersId to your userId (instead of using array.includes). This way, you prevent the workflow from running if someone else is added to a card you're already assigned to! Basically, check if you are the last person to be added to the card.
