### ISSUE TITLE
[ACTION]

### ISSUE THREAD

**Issue by Tomtomthumb** [PipedreamHQ/pipedream#4472]
Would like to connect slack to sendbird api, where a direct message from slack is received in sendbird. There are no sendbird actions currently.

**Comment by vunguyenhung** [comment]
Hello @Tomtomthumb, I see that this issue is duplicated with your other issue here https://github.com/PipedreamHQ/pipedream/issues/4473. So I will close this and use the other issue to track instead. Thank 🙏
