### ISSUE TITLE
[ACTION] Sendbird: Get messages and Post messages actions

### ISSUE THREAD

**Issue by Tomtomthumb** [PipedreamHQ/pipedream#4473]
**Name of app / service**
Sendbird

**Link to developer documentation**
https://github.com/sendbird/sendbird-platform-sdk-javascript/blob/main/docs/MessageApi.md

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Post/Get direct messages from sendbird

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by vunguyenhung** [comment]
I can confirm that Sendbird app current doesn't have any action
![image](https://user-images.githubusercontent.com/18277920/195089721-124a5328-4427-4e64-b3a2-490f93367e3b.png)
