### ISSUE TITLE
[Actions & Triggers] Vercel

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#448]
App: `vercel`

**Triggers**
- New Deployment
- Deployment Ready

**Actions**
- Create a new deployment: Create a new deployment with all the required and intended data. https://vercel.com/docs/rest-api#endpoints/deployments/create-a-new-deployment
- Cancel a deployment: Cancel a deployment which is currently building. https://vercel.com/docs/rest-api#endpoints/deployments/cancel-a-deployment
- List deployments: List deployments under the account corresponding to the API token. https://vercel.com/docs/rest-api#endpoints/deployments/list-deployments

**Comment by dannyroosevelt** [comment]
@dylburger do you have any context on why this was marked as Blocked?

**Comment by dylburger** [comment]
I believe it may no longer be blocked. Jay picked up [the sources](https://github.com/PipedreamHQ/pipedream/pull/485) again a while back. Someone should try to run those, see if they work, and improve the PR as necessary

**Comment by dannyroosevelt** [comment]
@michelle0927 this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)
