### ISSUE TITLE
MailerLite API Update

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#4489]
The MailerLite API was updated recently. They don't yet have a new SDK for Node, but when doing the **Use any MailerLite API** it should at least use the updated API.

- The Base URL for all requests is `https://connect.mailerlite.com/api/`
- Authorization keys should be sent under a bearer header (`Authorization: Bearer XXX`)

https://developers.mailerlite.com/docs/#mailerlite-api

---
This is the current code when using **Use any MailerLite API** 

#### Node
```javascript
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    mailerlite: {
      type: "app",
      app: "mailerlite",
    }
  },
  async run({steps, $}) {
    return await axios($, {
      url: `https://api.mailerlite.com/api/v2`,
      headers: {
        "X-MailerLite-ApiKey": `${this.mailerlite.$auth.api_key}`,
      },
    })
  },
})

```
#### Python
```python
import requests

def handler(pd: "pipedream"):
  headers = {"X-MailerLite-ApiKey": f'{pd.inputs["mailerlite"]["$auth"]["api_key"]}'}
  r = requests.get('https://api.mailerlite.com/api/v2', headers=headers)
  # Export the data for use in future steps
  return r.json()
```

**Comment by dannyroosevelt** [comment]
Thanks for flagging, @zalmanlew! This has been updated in the app scaffolding ("Use any MailerLite API" code).

And I see the actions are all using the SDK and are still functioning, so no changes required there!

Let me know if you run into any issues.
