### ISSUE TITLE
[BUG] Testing popup not updated

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#4497]
**Describe the bug**
When working on a long workflow, I often test multiple steps at once. There is this nice popup displayed in the top right corner:
I guess the point of having this popup is to know what steps are `in queue`, `in progress` and `done`.
But the steps icon changes from `loading` to `done` only when all the steps are `done` which makes the popup useless.

It goes from the image on the left to the image on the right instantly.
![](https://www.pixenli.com/image/TDitzgcb)![](https://www.pixenli.com/image/Q9WV3kRN)

**To Reproduce**
Test multiple steps on a workflow V2

**Expected behavior**
When step 3 is `in queue`, the icon must be ![](https://www.pixenli.com/image/wooyLMv9)
When step 3 is `in progress`, the icon must be something else
When step 3 is `done`, the icon must change to ✅

We should be able to see the progress !

**Desktop:**
- Windows 10 Familly 21H2
- Firefox 105.0.3 (64 bits)

**Comment by LucBerge** [comment]
[Here is a video](https://gfycat.com/fewtastyhornet)

**Comment by dylburger** [comment]
Sorry for the late reply on this one @LucBerge . Since step state is returned all at once, this is by design. We plan to support streaming step-level logs / state to the UI in the future.
