### ISSUE TITLE
[BUG] String prop field with multi lines not inline with the cursor

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#4498]
**Describe the bug**
I'm using the `microsoft_outlook-send-email` action to send an email with text content. The body of my email is about 20 lines.
The problem is that the cursor and the selection is not inline with the displayed text. This is confusing when writing....

![](https://www.pixenli.com/image/Y5-N6JnZ)

**To Reproduce**
- Take any source or action with a string field.
- Fill the field with multiple lines

**Expected behavior**
The cursor and the selection must be inline with the text

**Additional infos**
This is probably due to the displayed text set in bold !?

**Desktop**
- Windows 10 Familly 21H2
- Firefox 105.0.3 (64 bits)

**Comment by vunguyenhung** [comment]
Hello @LucBerge, I tried to reproduce your issue but couldn't (video here: https://watch.screencastify.com/v/HnFxJXc5XZwVdkLwmEwC). 

Could you share the following information regarding your environment?
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

It would be great if you can do a recording of the behavior too 🙏

**Comment by LucBerge** [comment]
@vunguyenhung [Here is the video](https://gfycat.com/fr/courteousbadhagfish)

**Comment by LucBerge** [comment]
Same problem with Microsoft Edge Version 106.0.1370.42

**Comment by vunguyenhung** [comment]
Thank you for the video @LucBerge! I have added this to Pipedream internal board for tracking! Updates will be made to this Github issues 🙏

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
FYI this is fixed!!
