### ISSUE TITLE
[FEATURE] Support text blocks inline with flows

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#4502]
**Is your feature request related to a problem? Please describe.**
I've recently fallen in love with Jupyter Notebooks. The mix of code steps and docs makes for a great learning experience, as well as a process that's very well documented. I'd like to see PD consider supporting something like this. 

**Describe the solution you'd like**
I can see two ways:

a) Modify steps so they have a Text setting. Allow free form text/Markdown and when viewing a flow in NON-edit mode, it renders well. 

b) More like real Notebooks, support steps that are nothing more than text/markdown blocks. These would obviously be ignored when running.

While B) is closer to Notebooks, I think I prefer A). You could even collapse them so they don't take up space when you don't need the text. 

**Do you have a workaround?**
Flows support readme's, and that's good and should stay of course, and is good for describing the flow at a high level and perhaps containing versioning info. 

**Comparable features in other tools?**
Jupyter Notebooks :) I probably spelled that wrong - love the idea - hate the brand name. ;)

**Additional context**

**Comment by vunguyenhung** [comment]
Thank you for the feature suggestion @cfjedimaster!

Hello @dannyroosevelt @dylburger, could you consider the suggestion by @cfjedimaster? I searched through PIpedream's open issues and find [this issue](https://github.com/PipedreamHQ/pipedream/issues/3912) that is quite similar

**Comment by dannyroosevelt** [comment]
It sounds like this should be handled as a part of https://github.com/PipedreamHQ/pipedream/issues/220, is that your understanding as well, @dylburger ?

**Comment by dylburger** [comment]
Yes, closing since we're close to releasing that
