### ISSUE TITLE
[APP] FreshBooks

### ISSUE THREAD

**Issue by niklaas** [PipedreamHQ/pipedream#4513]
**Name of app / service**

FreshBooks

**Link to developer documentation**

https://www.freshbooks.com/api/start

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I would love to automate my invoicing and accounting using pipedream but I struggle to set up OAuth with Freshbooks.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

- trigger when an invoice is updated and either marked as sent or actually sent to the client i.e., webhook `invoice.update`

Ultimately, I want to generate the PDF of the invoice (`https://api.freshbooks.com/accounting/account/<account id>/invoices/invoices/<invoice id>/pdf`) and forward that PDF via email.

I think I don't need further support for creating a custom trigger and access the endpoint for generating the PDF. But I struggle with setting up OAuth and I'd appreciate someone helping me with that.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@niklaas here is a basic integration for FreshBooks:
https://pipedream.com/apps/freshbooks/

FYI we're currently requesting these scopes: `user:profile:read, user:invoices:read, user:invoices:write`

Let me know if those are right, or if we need to adjust them.

What actions and triggers would you like to see? Would love to get some added to our public registry!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by niklaas** [comment]
Wow, this was fast! I'll take a look at the integration in the next couple of days. Thanks a lot!
