### ISSUE TITLE
[APP] DeepL

### ISSUE THREAD

**Issue by gijigae** [PipedreamHQ/pipedream#4514]
**Name of app / service**

DeepL is a machine translation service.

**Link to developer documentation**

https://www.deepl.com/en/docs-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Yes, it prevents me from building workflows and I do not have a workaround. Google cloud tranlsate is available. However, DeepL provides much higher translation quality.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@gijigae here is a basic integration:
https://pipedream.com/apps/deepl/

Are there specific actions or triggers you're looking for, that would be useful?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
