### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Domingato** [PipedreamHQ/pipedream#4520]
**Describe the bug**
When I link to the Todoist integration, it links only with the "Inbox" Todoist project so all the events happening in the other projects can't be detected.

**To Reproduce**
1. Create new workflow
2. In trigger, search for an app, select Todoist
3. connect to Todoist
4. Select new or modified task
5. In Select Todoist account, there's only the Inbox project ID.

**Expected behavior**
Having an option of each project, for a selection of projects and for all projects.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Hassan-Abbas-SQA** [comment]
@Domingato can you please provide the screencast for the issue you are facing as you can see i was unable to replicate the issue , can you please also try it by disabling all your extensions or try incognito mode in browser and verify that issue please

**Comment by dannyroosevelt** [comment]
@Domingato what do you see when you select the "Projects" prop when configuring that Event Source? It should list all the projects in your account:
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/196298728-4af95752-2d08-4f19-93f5-45a34c6db55f.png)

I think maybe there is some confusion re: how Pipedream displays the project ID alongside your auth provision after you've connected an account. I agree that's confusing, and I've removed it (if you [delete that connection and reconnect](https://pipedream.com/accounts), you'll see the updated behavior).

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
