### ISSUE TITLE
[BUG] Team ID prop in Linear source not filtering events

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4526]
I selected a Team from the async options dropdown, but the events that were emitted upon source creation correspond to different Team IDs.

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/196290887-c8950193-1d02-49b7-9ef8-9c7cf4e6e687.png)

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/196291164-07472fc0-e80f-4c59-9e78-1f6b72faad97.png)

**Comment by Hassan-Abbas-SQA** [comment]
@dannyroosevelt 
Reproduced the issue
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/104946677/196482210-1223679c-353a-4a10-95cd-4a5c675116d6.png">
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/104946677/196482255-3b29b7a2-5369-42d6-b037-cd84be8d18a2.png">

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed works fine as expected
![image](https://user-images.githubusercontent.com/104946677/197632500-ba9e51a5-5565-4345-8e41-2dc352d731d9.png)
