### ISSUE TITLE
[APP] ExpoFP

### ISSUE THREAD

**Issue by mrdoosey** [PipedreamHQ/pipedream#4528]
ExpoFP

https://expofp.docs.apiary.io/

I would like to be able to send data from Zoho CRM, am struggling to set this up my end and wonder if you could create an integration for this please. 

Looking at 
Add Exhibitor
Update Exhibitor
Set Booth Exhibitors

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@mrdoosey here is a basic integration for ExpoFP:
https://pipedream.com/apps/expofp/

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
