### ISSUE TITLE
[BUG] Discord Bot, Add a Role prebuilt step

### ISSUE THREAD

**Issue by garrettstark** [PipedreamHQ/pipedream#4530]
**Describe the bug**

Hi I’m having trouble with the ‘discord bot’, ‘add a role’ prebuilt step.
The props for Discord Bot ‘Account’ and ‘Guild’ correctly prepopulate with the correct options.
But, the ‘User’ prop won’t list all the members of the guild.
Only 1 member shows up and It’s not clear to me why that one user would be any different.
I’ve turned on all the permissions for the bot.
Other prebuilt steps can list all members.
When I manually enter the ID of the member then the (add a) “Role”: prop functions correctly.
When I try to pass the prop the path to the same ID of the member it won’t work.
IE {{steps.Get_DiscordID_Matching_Registration.foundID}}
The error comes back “Request failed with status code 400”

**To Reproduce**
see "add a role" step here: 
https://pipedream.com/@garretttstark/discord-registration-p_MOCy55M/
Node steps to try and pass the User ID may not be necessary if the "user" prop is debugged.

**Expected behavior**
See above.

**Comment by safaiyeh** [comment]
can reproduce as well

**Comment by Hassan-Abbas-SQA** [comment]
Able to reproduce the issue as well from my end thanks for submitting this issue iam adding this to our Backlog in Prioritised section so it can be resolved as soon as possible
![image](https://user-images.githubusercontent.com/104946677/196783894-4b8883de-4da4-446b-8819-43affe18e947.png)

**Comment by Hassan-Abbas-SQA** [comment]
Test Passed
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/104946677/197032054-01eb73df-1b39-4157-ab81-109a71335354.png">
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/104946677/197032084-15ae3d73-f482-4f9d-a1be-29c65c98f6bd.png">
