### ISSUE TITLE
[BUG] Supportivekoala Create Image [Action]

### ISSUE THREAD

**Issue by Hassan-Abbas-SQA** [PipedreamHQ/pipedream#4538]
Bug: https://github.com/PipedreamHQ/pipedream/pull/3887#issuecomment-1275138952 as described here by user when creating an image from template able to edit only text fields and not images like product image etc...

**Steps to Reproduce the issue:**
Create Workflow
add a supportivekoala creata image action
select any template 
you will only see text fields to edit

**screenshot:** 
![image](https://user-images.githubusercontent.com/104946677/196656524-03c09f57-f8dd-47df-97f9-86417b94a4a9.png)

**identified possible solution** 
https://pipedream-users.slack.com/archives/C03JQME4CDA/p1666144664967569?thread_ts=1666132123.551889&cid=C03JQME4CDA

Expected behaviour:
When i select a template i can be able to see all the image fields to populate using a url and text fields to populate as well

**Comment by weitzman** [comment]
Thanks much.
