### ISSUE TITLE
Actions and Triggers for Cal.com

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4543]
### App
`cal_com`
https://developer.cal.com/api/api-reference

### Triggers
- Booking cancelled
- Booking created
- Booking rescheduled
- Booking ended

### Actions
- Create new booking
- Get a booking
- Delete a booking

**Comment by PeerRich** [comment]
LETS GOOO https://github.com/calcom/cal.com/pull/5119

**Comment by Hassan-Abbas-SQA** [comment]
![image](https://user-images.githubusercontent.com/104946677/199765693-5abdab67-d462-44d6-8d6e-807c892e7904.png)
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/104946677/199765748-d8ffb9f1-08ea-4c72-8b0e-66d3d4770f69.png">
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/104946677/199765813-af2406e1-93c2-456b-ba62-e0c7ec0c279d.png">
