### ISSUE TITLE
Trigger when streamer off the stream

### ISSUE THREAD

**Issue by KuLYT** [PipedreamHQ/pipedream#4548]
Emit new event when a live stream off from the streamer you specify.

**Comment by Hassan-Abbas-SQA** [comment]
@KuLYT which Component are you referring to ? 
can you share more information so we can move this ticket accordingly?

**Comment by KuLYT** [comment]
> @KuLYT which Component are you referring to ? can you share more information so we can move this ticket accordingly?

![image](https://user-images.githubusercontent.com/37509619/197084211-46fe0563-bd9c-4b34-ac76-41340469a424.png)

When the type is changed from live to offline the trigger should go off, I think it goes something like this

**Comment by dannyroosevelt** [comment]
@KuLYT can you confirm what app you're referring to?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
