### ISSUE TITLE
[Components] Patreon

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4552]
### App
`patreon`
https://docs.patreon.com/

### Triggers
- New member created
- New pledge received
- Member deleted

**Comment by andrewjschuang** [comment]
Blocked due to error connecting account with Pipedream:

```
Pipedream failed to connect to your account.

Please reach out to integration-errors@pipedream.com and provide this error ID: 6456245555564af385163899a4996370
```

**Comment by dannyroosevelt** [comment]
> Blocked due to error connecting account with Pipedream:
> 
> ```
> Pipedream failed to connect to your account.
> 
> Please reach out to integration-errors@pipedream.com and provide this error ID: 6456245555564af385163899a4996370
> ```

Sorry for the extreme delay on this! I wasn't able to repro or find that error code initially, but I finally identified and fixed the issue. You should be good to go now!
