### ISSUE TITLE
[ACTION] Airtable: Search records

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4562]
**Is there a specific app this action is for?**
Airtable. I would like an action allow searching records using formula, similarly to calling Airtable SDK `select` with `filterByFormula` params passed in:
```js
base('Tasks').select({
    filterByFormula: 'name = "abc"'
})
```

**Please provide a link to the relevant API docs for the specific service / operation.**
https://airtable.com/api

Context: 
First raised by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1666356149763989

**Comment by lcaresia** [comment]
@vunguyenhung The action `List Records` don't work for this case?

![image](https://user-images.githubusercontent.com/12402324/197528004-06a9cd6a-a425-42d6-a245-80068d9fb7f8.png)

**Comment by vunguyenhung** [comment]
Oh right. Thanks for spotting that @lcaresia! As we can use the List Records action for this I will close the ticket now!
