### ISSUE TITLE
[TRIGGER] Notion - New Row Added

### ISSUE THREAD

**Issue by muditbhutani** [PipedreamHQ/pipedream#4563]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

Allow for trigger when a new row is added in a notion database, this will enable people using pipedream instead of notion to twitter automation tools

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dannyroosevelt** [comment]
@muditbhutani would this trigger work for you? https://pipedream.com/apps/notion/triggers/updated-page

**Comment by muditbhutani** [comment]
@dannyroosevelt I believe updated page in database here means updation of the first column of database in notion which is by default a page. The flow I am looking for is more about addition of new row in the same database irrespective of whether that column is primary or not

**Comment by andrewjschuang** [comment]
@muditbhutani can you please try this trigger? https://pipedream.com/apps/notion/triggers/new-page

**Comment by andrewjschuang** [comment]
Closing this issue. If anything, feel free to reopen it
