### ISSUE TITLE
Salesforce Connected Account not holding session [BUG] 

### ISSUE THREAD

**Issue by dudunato** [PipedreamHQ/pipedream#4564]
**Describe the bug**
We have a workflow that runs daily fetching data from an API and saving it to Salesforce through the REST API. This used to work pretty well, but now, every day I have to login to pipedream and re-authorize the Account with my credentials. I've tried to save it with a different user, to save a new version of the workflow and etc.

Would you guys know how to troubleshoot this further?

Thanks so much, appreciate the help.

**Screenshots**
![CleanShot 2022-10-23 at 09 23 56](https://user-images.githubusercontent.com/4641846/197391935-098f9460-9f50-4103-8e76-76c0eb4aef1d.png)

**Comment by DilanAthukorala** [comment]
Hi @dudunato, I am not able to recreate this, can you please provide the details of the exact component that you are observing this issue? The screenshot you provided doesn't show any Salesforce component could you please share more screenshots of the error, component and configurations of your action.

**Comment by dannyroosevelt** [comment]
@dudunato to confirm, which account are you re-authorizing with -- ActiveCampaign or Salesforce?

**Comment by dudunato** [comment]
@dannyroosevelt Salesforce!

**Comment by dannyroosevelt** [comment]
Thanks for confirming.

Is there any chance you’ve configured a custom Refresh Token Policy for your Salesforce org? https://help.salesforce.com/s/articleView?id=sf.connected_app_manage_oauth.htm&type=5

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
@dudunato Can you do me a favor and check the Refresh Token Policy for apps on your instance (see step 7 of [this guide](https://help.salesforce.com/s/articleView?id=sf.connected_app_manage_oauth.htm&type=5)). What is that set to?
