### ISSUE TITLE
[BUG] Access token doesn't get refreshed for Withings

### ISSUE THREAD

**Issue by edusteinhorst** [PipedreamHQ/pipedream#4566]
**Describe the bug**
After 3 hours of creating a new connection to Withings, requests start to fail with the following error:

`{ status: 401, body: {}, error: 'XRequestID: Not provided invalid_token: The access token provided is invalid' }`

Debugging by printing tokens with the expression below hows that the tokens never change, including after the 3 hour period:

`console.log(this.withings.$auth);`

The only way to fix the integration is to create a new connection to Withings (which then works for the next 3 hours). 

**To Reproduce**
1. Create a new Withings connection
2. Create a Workflow and get it to fetch measures normally (eg. with a 15m timer)
3. Wait 3 hours and see the failure in logs.

**Expected behavior**
Workflows should keep working indefinitely (with the access token getting refreshed).

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 12.16
 - Browser [e.g. chrome, safari] Arc (Chromium)
 - Version [e.g. 22] 0.72.0

**Comment by DilanAthukorala** [comment]
@edusteinhorst Thank you for reporting this issue, I am able to recreate the error with the given steps. The following error can be seen in the logs, 3 hours after connecting the app, when trying to fetch events.
![image](https://user-images.githubusercontent.com/102980146/197829528-5c400263-b62a-4a40-925f-c646944d46f6.png)

**Comment by edusteinhorst** [comment]
Hi @dannyroosevelt! Any news on this / ETA? In case it's not a priority I'll probably implement a token refresh process myself, would appreciate a heads up 🙏

**Comment by dannyroosevelt** [comment]
Apologies for the delayed response, @edusteinhorst. We've identified that the issue is most likely related to how Withings is declaring the expiry of their access tokens during the OAuth flow, which is non-standard. We are working on a potential workaround right now.

Stay tuned -- I'll post updates here.

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by dannyroosevelt** [comment]
@edusteinhorst we just released a fix that I should should resolve the core problem. Please let me know if you continue to run into any issues and we'll take a look!

**Comment by edusteinhorst** [comment]
Thanks @dannyroosevelt, will do!

**Comment by edusteinhorst** [comment]
@dannyroosevelt just to give you some feedback: everything seems to be running smoothly 👍

**Comment by dannyroosevelt** [comment]
Great to hear, thanks for confirming!
