### ISSUE TITLE
[BUG]  Slack New Reaction Added (Instant) sends incorrect message if the reaction is added in a thread

### ISSUE THREAD

**Issue by fabien-lg** [PipedreamHQ/pipedream#4585]
**Describe the bug**
When using the source [Slack New Reaction Added (Instant)](https://github.com/PipedreamHQ/pipedream/blob/master/components/slack/sources/new-reaction-added/new-reaction-added.mjs), and adding a reaction to a message that is down in a thread; the message that is fed into the Workflow is not the message that received the reaction, but the last message in the channel instead.

**To Reproduce**
1. Go to [the new sources in Pipedream](https://pipedream.com/sources/new).
2. Search for Slack and select «New Reaction Added (Instant)».
3. Select your Slack account, give the source a name, and create the source.
4. Create new workflow and use that new source as trigger.
5. Trigger a test event for a message that in down in a thread – not a message in a channel.

**Expected behavior**
The trigger should return the message that is in the thread.

**Additional context**
Looking a the [Source Code](https://github.com/PipedreamHQ/pipedream/blob/master/components/slack/sources/new-reaction-added/new-reaction-added.mjs#L57), it seems that the function called is `getLastMessage` and the parameters is `channel` so that might be a cause? 🤔

**Comment by DilanAthukorala** [comment]
Hi @fabien-lg, Thank you for reporting this issue, I am able to recreate it. The actual message returned is the text of the parent message of the thread for reactions on any child message within that thread. 
![image](https://user-images.githubusercontent.com/102980146/198086228-508af320-4d8c-4daf-867d-6dd48b25582d.png)
![image](https://user-images.githubusercontent.com/102980146/198086408-2b2d79b6-6f3c-48e0-b650-836118dc74af.png)
