### ISSUE TITLE
[BUG] Twilio Authentication not as expected

### ISSUE THREAD

**Issue by Hassan-Abbas-SQA** [PipedreamHQ/pipedream#4599]
**Describe the bug**
When i Authenticated myself with valid SID and AuthToken as required by auth prompt and trying to run an action getting "username is required" error

<img width="975" alt="image" src="https://user-images.githubusercontent.com/104946677/198413068-4a397b08-e627-49ee-bcd5-aac54e2148d2.png">

Goto Pipedream create a workflow
select any action for twilio
Authenticate with valid SSID and AuthToken
click to run the action

**Comment by DilanAthukorala** [comment]
@Hassan-Abbas-SQA The actions seem to be working fine can you retry ?
![image](https://user-images.githubusercontent.com/102980146/198699208-87814f26-50b3-416c-89c9-ef21d27d68e0.png)

**Comment by Hassan-Abbas-SQA** [comment]
this issue has been resolved @DilanAthukorala closing this issue now
