### ISSUE TITLE
[SOURCE] Firebase Realtime Database

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#460]
See https://firebase.google.com/docs/functions/database-events

**Comment by andrewjschuang** [comment]
@dylburger @dannyroosevelt 
According to the docs, to create/submit a Cloud Function, we would have to use the Firebase CLI, thus not being able to do it via a component trigger.

**Comment by dannyroosevelt** [comment]
> @dylburger @dannyroosevelt According to the docs, to create/submit a Cloud Function, we would have to use the Firebase CLI, thus not being able to do it via a component trigger.
> 
> Can we close this issue?

Ah too bad, yes sounds like it in that case.
