### ISSUE TITLE
[BUG] Actions not prompting to update in the builder

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4600]
Newer versions of component actions are not prompting me to update to the latest versions in the builder.

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by DilanAthukorala** [comment]
Update option is now visible
![image](https://user-images.githubusercontent.com/102980146/198697160-769a6efa-adfc-4ce7-95c6-27bb1defa469.png)
