### ISSUE TITLE
send received payload[ACTION]

### ISSUE THREAD

**Issue by vinodCustomerSuccess3000** [PipedreamHQ/pipedream#4601]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by DilanAthukorala** [comment]
@vinodCustomerSuccess3000 Please provide the details of the action you are requesting for in the following format

Is there a specific app this action is for?
Please provide a link to the relevant API docs for the specific service / operation

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
