### ISSUE TITLE
[BUG] $.respond does not accept Readable Stream in Node.js action

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4603]
**Describe the bug**
Raised by a customer here: https://github.com/PipedreamHQ/pipedream/issues/4603
I created a workflow with `HTTP Trigger - Return Custom response from your workflow`, then I created a Node action and call `$.respond({body: readbleStream})`. But I faced an error 
```
Warnings
HTTP_RESPONSE_INVALID_ARGS: $.respond called incorrectly. Check https://pipedream.com/docs/workflows/steps/triggers/#http

Code was still running when the step ended. Make sure to [await all Promises](https://pipedream.com/docs/workflows/steps/code/async/#solutions), or [promisify callback functions](https://pipedream.com/docs/workflows/steps/code/async/#wrap-callback-functions-in-a-promise). May be a [false positive](https://pipedream.com/docs/workflows/steps/code/async/#false-positives)
```

Per [this document](https://pipedream.com/docs/workflows/steps/triggers/#http-responses)
> The value of the body property can be either a string, object, a [Buffer ](https://nodejs.org/api/buffer.html#buffer_buffer)(binary data), or a [Readable stream](https://nodejs.org/api/stream.html#stream_readable_streams)

So I expect that the `$.respond` call should except readable stream body

**To Reproduce**
1. Create a new workflow, add a `HTTP Trigger - Return Custom response from your workflow 
2. Add a new Google Drive step to download a file to `/tmp` dir
3. Add a node step to call `$.respond` with the readable stream linked to the downloaded file

![1652 - 2810](https://user-images.githubusercontent.com/18277920/198559403-c1849e9d-ca73-4ae7-9ce7-47384a5b4311.png)

**Expected behavior**
The Workflow response should contains the file

**Comment by casret** [comment]
Can you try to pass a (numeric) `status` to $.respond?

**Comment by vunguyenhung** [comment]
Thank you @casret, I tried to add `status: 200` and it success!
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/18277920/198949103-d5300925-cf53-471f-8d4b-7799db2e5c8e.png">

Hence I will close this ticket
