### ISSUE TITLE
[ACTION]

### ISSUE THREAD

**Issue by CarefulCrab** [PipedreamHQ/pipedream#4611]
Greetings,
Thank you for your work! I just wanted to ask if it is possible to get rid of the "Sent via PipeDream" message on Discord for newly created Twitch clips. If it's possible, how can I do it? What should I do?
Thank you for you assistance.
![Capture](https://user-images.githubusercontent.com/106415281/198748183-6da22fa9-f71a-4d65-afe5-203062234a29.PNG)

**Comment by LucBerge** [comment]
In your `send_message` action, set the `Include link to workflow` to `FALSE`

**Comment by CarefulCrab** [comment]
> In your `send_message` action, set the `Include link to workflow` field to `FALSE` ![](https://camo.githubusercontent.com/a71f0f2b55efc616263a9e0823c9fa0f8838a32b576bcaff513404cc4bcb646a/68747470733a2f2f7777772e706978656e6c692e636f6d2f696d6167652f4945565852554451)

Thank you very much!
Wishing you a good day <3

**Comment by CarefulCrab** [comment]
Thank you very much!
Wishing you a good day <3

**Comment by LucBerge** [comment]
You're welcom 😄  fell free to close the issue
