### ISSUE TITLE
[BUG] ActiveCampaign 'get_contact_by_email' action doesn't work - always returns the first contact

### ISSUE THREAD

**Issue by fawadakram** [PipedreamHQ/pipedream#4612]
**Describe the bug**
See action: components/activecampaign/actions/get-contact-by-email/get-contact-by-email.mjs

Whether you specify a string or expression (doesn't matter), the contact returned will always be the first one in the array.

The result displayed states that it was successfully returned, e.g. Successfully got a contact with ID 6
But it definitely was not successful :)

**To Reproduce**
Easy to reproduce - just try and test it with an email which exists as part of your contacts in AC. Just ensure it wasn't the first contact listed in your ActiveCampaign contacts list

**Expected behavior**
Return the correct contact

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by fawadakram** [comment]
Note the email address is made up but a result is still returned

<img width="947" alt="Screenshot 2022-10-29 at 18 20 01" src="https://user-images.githubusercontent.com/16971604/198844934-4cdfba96-b277-4c97-8924-8308f79ada83.png">

**Comment by vunguyenhung** [comment]
Thank you for raising this issue @fawadakram! I'm able to reproduce this bug! I will add this to Pipedream's component backlog
![2115 - 3110](https://user-images.githubusercontent.com/18277920/199028992-232e3332-9f6a-447b-bb95-2b903bb2612c.png)
