### ISSUE TITLE
1s2u[APP]

### ISSUE THREAD

**Issue by h4ck3rkorghost** [PipedreamHQ/pipedream#4613]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@h4ck3rkorghost here is a basic integration:
https://pipedream.com/apps/ones2u/

Can you let us know if that works for you?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
