### ISSUE TITLE
[BUG] Code Examples not appearing in the builder

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4615]
![Google Chrome - Untitled workflow - Pipedream - 2022-10-30 at 9 43 25 AM](https://user-images.githubusercontent.com/20780753/198890641-14f20fe5-bce9-4a6c-a086-40db858bd32c.gif)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
