### ISSUE TITLE
[APP] Mastodon

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#4618]
**Name of app / service**
Mastodon

**Link to developer documentation**
https://docs.joinmastodon.org/api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I believe so - I think at minimum I'd need OAuth support

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Can I be lazy and say - mirror Twitter?

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
hi @cfjedimaster old but goodie,
Mastodon was actually published sometime last year https://pipedream.com/apps/mastodon
