### ISSUE TITLE
[APP] Untappd

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#4619]
**Name of app / service**
Untappd

**Link to developer documentation**
https://untappd.com/api/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Need at least oauth connection support

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Um.... all of it? :) My main use case is to build an Event Source based on an activity feed.

**Comment by ctrlaltdylan** [comment]
Unfortunately Tappd is not accepting any new applications on their API.

We're unable to register a new app on their platform. We cannot support an integration at this time, but will check back in.

![CleanShot 2022-10-31 at 09 54 41](https://user-images.githubusercontent.com/2694734/199024570-b11c59b2-f9a2-4b34-a170-95c5a9754925.png)

**Comment by cfjedimaster** [comment]
I _kinda_ know the owners - will ping them. Well, I knew the previous owners, I believe it's been sold once or twice.

**Comment by ctrlaltdylan** [comment]
Amazing. If you could get our shoe in the door that would be super helpful.

**Comment by cfjedimaster** [comment]
I tried by begging on the bird site. We shall see.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
@cfjedimaster did you ping Untappd owners?
I just reached out for access to the Untappd for Business API.

**Comment by cfjedimaster** [comment]
i never heard back. i'd assume we can close this as I don't see it ever being an option again.
