### ISSUE TITLE
[BUG] Slack - "New Mention" source not emitting events

### ISSUE THREAD

**Issue by DilanAthukorala** [PipedreamHQ/pipedream#4625]
Slack New Mention source does not emit events for keywords or usernames. Events are only visible in the logs but not displayed in the events tab. 

1. Create slack "New Mention" source and connect to account
2. provide a sample keyword and a channel
3. In slack mention the keyword in the configured channel. 

**Expected behavior**
Event should be emitted for the keyword mention

**Screenshots**
![image](https://user-images.githubusercontent.com/102980146/199071507-0df35ac1-0864-48d6-aa34-3acaa57825eb.png)

**Desktop:**
 - OS: Windows 11
 - Browser - Chrome
 - Version 107.0.5304.87 (Official Build) (64-bit)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Slack_4625.pdf](https://github.com/PipedreamHQ/pipedream/files/9930053/Slack_4625.pdf)
