### ISSUE TITLE
[BUG] Slack "New Star Added" source throws error if event type is not specified

### ISSUE THREAD

**Issue by DilanAthukorala** [PipedreamHQ/pipedream#4626]
Slack "New Star Added" source does not emit event and throws error if event type is not specified

**To Reproduce**
1. Create and Connect Slack "New Star Added" Source (Do Not Select Event Type)
2. On Slack add star to either **Message, User, Channel or File**

**Expected behavior**
If Event Type is not specified, all events should be emitted.

**Screenshots**
![image](https://user-images.githubusercontent.com/102980146/199074424-8e391e13-0c2e-4745-a73a-e351be17bb7a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 107.0.5304.87 (Official Build) (64-bit)

**Comment by vunguyenhung** [comment]
Since Dilan can reproduce this already I'll put this ticket directly to our component project
