### ISSUE TITLE
[BUG] Jira: Create Issue action does not appear to support labels selected from drop-down list

### ISSUE THREAD

**Issue by WTPascoe** [PipedreamHQ/pipedream#4629]
**Describe the bug**
When adding Labels on the Jira: Create Issue action, you are presented with a list of labels to select from if any exist in the target Jira instance. Selecting one of these (although multiple should be selectable) and testing the action causes a failure as follows:

```
Error
Request failed with status code 400
```

Under `steps.create_issue.debug.data.errors.labels` , the error is further described as `Specify the value for labels in an array of strings`

**To Reproduce**
1. Go to a Jira instance that you have a source for
2. Create a label
3. Create a new workflow
4. Add a step - select 'Jira' as the app, and 'Create Issue' as the action
5. Select a Project you have write access to 
6. Select 'Task' for Issue Type
7. Enter a string for the Issue summary
8. Scroll to Optional Fields and click the + next to Labels to add it
9. Click the Labels box to select the label you created in step 2
10. Select an Assignee to assign the issue to

**Expected behavior**
I expect an issue to be created in Jira

**Desktop (please complete the following information):**
 - OS: MacOs 12.6
 - Browser: Chrome
 - Version: 106.0.5249.119

**Additional context**
I have admin rights on the Jira instance and project where I am attempting to create this.

**Comment by vunguyenhung** [comment]
Thank you for raising this issue @WTPascoe. I'm able to reproduce your issue! I will add this to our Component backlog!
![0805 - 0211](https://user-images.githubusercontent.com/18277920/199370789-db04f4bd-7b88-4804-9331-b2f0eb8c6e32.png)
