### ISSUE TITLE
[BUG] Jira Create Issue action should not mandate assignee be completed, or should allow for Automatic / Unassigned

### ISSUE THREAD

**Issue by WTPascoe** [PipedreamHQ/pipedream#4631]
**Describe the bug**
`Assignee Id` appears to be mandatory in the Jira Create Issue action and I cannot test the action without completing this.

Jira allows for an Automatic assignment option and in many cases, workflows with the option to not assign the issue (Unassigned)

https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/ does not state that assignee is required from what I can see. 

If this field _must_ be mandatory in Pipedream, then 'Automatic' or 'Unassigned' should be listed as options.

**To Reproduce**

1. Create a new workflow
2. Add a step - select 'Jira' as the app, and 'Create Issue' as the action
3. Select a Project you have write access to
4. Select 'Task' for Issue Type
5. Enter a string for the Issue summary
6. Attempt to test the action

**Expected behavior**
The action should be testable without setting the `Assignee Id`.

The following `curl` example shows that this is possible:

```
curl --request POST \
  --url 'https://our-domain.atlassian.net/rest/api/2/issue' \
  --user 'me@mydomain.com:api_key_goes_here' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
    "fields": {
       "project":
       {
          "key": "PROJECTFOO"
       },
       "summary": "Test issue - no assignee",
       "description": "Nobody will do this work",
       "issuetype": {
          "name": "Task"
       }
   }
}'
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs 12.6
 - Browser: Chrome
 - Version: 106.0.5249.119

**Comment by vunguyenhung** [comment]
Thank you for raising this @WTPascoe! I confirm that the current JIRA create issue action requires Assignee ID. I will add this ticket to our component backlog!
<img width="817" alt="image" src="https://user-images.githubusercontent.com/18277920/199371215-9fad7f01-03a1-49b1-afdf-3a157c9b0b68.png">
