### ISSUE TITLE
[BUG] Edits during a step test are lost

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#4637]
**Describe the bug**
If you have a code step and you edit the code while a test is being run, the edits are lost.

**To Reproduce**
1. Click test.
2. Quickly edit the code somehow
3. The edits go away

**Expected behavior**
Either stop me from editing when a test is being run, or don't lose the edits. :)

**Comment by dylburger** [comment]
This should be fixed! You can still edit code while testing and we should no longer lose the edits.
