### ISSUE TITLE
TD Ameritrade Rest API Integration [APP]

### ISSUE THREAD

**Issue by MongoSan** [PipedreamHQ/pipedream#4640]
TD Ameritrade Rest API (for Stock/Option Trading Automation)

[[**Link to developer documentation**](https://developer.tdameritrade.com/apis)](https://developer.tdameritrade.com/apis)

**Is lack of support preventing you from building workflows, or do you have a workaround?**  Their OAUTH process is beyond my low skill level

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** - Yes - automate the OAUTH process   (https://developer.tdameritrade.com/authentication/apis)

Here is a YT vid of a person doing it in Zapier - but I like Pipedream better - seems like its got more customization potential.

https://www.youtube.com/watch?v=_935GXvgRRo

Thanks 
Tom

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
Here you go, @MongoSan:
https://pipedream.com/apps/td-ameritrade/

Are there specific actions or triggers you'd like to use with TD Ameritrade?

**Comment by MongoSan** [comment]
Wow - that was fast Danny - thanks!

Signing up for  a Pipedream pay account now.

Yes there maybe some specific triggers related to placing stock trades,
getting account information, and getting stock price quotes/data - I'll let
you know.  thanks Again

Tom

**Comment by dannyroosevelt** [comment]
Great, happy to help! By the way all our actions and triggers are open source, in case you're interested in developing your own -- the team is happy to help support you along the way!
https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by dylburger** [comment]
I'm closing this since the app is integrated, but let us know if you have any issues or questions about the integration
