### ISSUE TITLE
[Whatsapp Business Api - APP]

### ISSUE THREAD

**Issue by ajay-shahh** [PipedreamHQ/pipedream#4642]
**Name of App/Service - Whatsapp Business API**

**Link to developer documentation - https://developers.facebook.com/docs/whatsapp/**

**Is lack of support preventing you from building workflows, or do you have a workaround? - NO**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Yes, I want to send WhatsApp message when a user purchases from my WooCommerce store and for that I want to send message using WhatsApp Business API.

**Comment by sergioeliot2039** [comment]
Hi @ajay-shahh, thanks for the request.
We are tracking WhtasApp integration on this issue, please feel free to follow, if you'd like  #2896 

Duplicate, closing.
