### ISSUE TITLE
[APP] svix.com

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#4643]
**Name of app / service**
svix.com

**Link to developer documentation**
https://docs.svix.com

**Is lack of support preventing you from building workflows, or do you have a workaround?**
workaround, use Python library

**other interesting links**
https://docs.svix.com/integrations/zapier
https://docs.svix.com/integrations/advanced-zapier

**Comment by dannyroosevelt** [comment]
@marcelocecin here is a basic integration:
https://pipedream.com/apps/svix/

Can you let us know if that works for you?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
