### ISSUE TITLE
[APP] FaceBook Groups

### ISSUE THREAD

**Issue by HayWire-UK** [PipedreamHQ/pipedream#4645]
**Name of app / service** FaceBook Group

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Link to API documentation https://developers.facebook.com/docs/groups-api/

**Comment by HayWire-UK** [comment]
With facebook groups added. I can move everything over from another paid service. And then upgrade my account.

**Comment by HayWire-UK** [comment]
Any further news on this

**Comment by malexanderlim** [comment]
Hi @HayWire-UK , I'm happy to report that the Facebook Groups app is now available on Pipedream.
https://pipedream.com/apps/facebook-groups

Let me know if you have any feedback or run into any issues getting it set up!
