### ISSUE TITLE
[ACTION] Slack: Add Emoji To Message action

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4656]
Let's add an action to [add an emoji reaction](https://api.slack.com/methods/reactions.add) to a Slack message you specify.

Props:
- **Emoji**: let's [list the emojis](https://api.slack.com/methods/emoji.list) via async options
- **Message**: no async options required, I expect users to use step references here
- **Channel**: we can use async options, since we already have this prop supported, but I expect users to use step references

**Comment by KartikeyDubeyKD** [comment]
Hey, I'm interested in working on this issue

**Comment by KartikeyDubeyKD** [comment]
please elaborate a little on what I have to do.

**Comment by lcaresia** [comment]
Hello @KartikeyDubeyKD, I assigned you to this task!

**Comment by dannyroosevelt** [comment]
@KartikeyDubeyKD great! I recommend checking out our actions quickstart here: https://pipedream.com/docs/components/quickstart/nodejs/actions/#overview

By the way we have an active community in Slack -- I recommend joining our [#contribute channel](https://pipedream-users.slack.com/archives/C01E5KCTR16) to ask questions there, etc

**Comment by KartikeyDubeyKD** [comment]
Thank you for assigning this issue @dannyroosevelt @lcaresia

**Comment by lcaresia** [comment]
Hey @KartikeyDubeyKD, I hope all is well.

So, how is going this task? If you need some help ou have some issue just call me!

**Comment by KartikeyDubeyKD** [comment]
Sorry @lcaresia I was busy with college exams and Now I'll start working on this

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia it works fine but this async prop should show emojis instead of names of emoji
<img width="779" alt="image" src="https://user-images.githubusercontent.com/104946677/207664546-eb708a40-a661-4db4-b18d-5e7092f2b756.png">

**Comment by lcaresia** [comment]
@Hassan-Abbas-SQA Don't have a way to put emojis, because slack just returns images urls, not emojis.

**Comment by dannyroosevelt** [comment]
Is there any API to fetch the actual emojis? It'd be great if we could render them like we do here https://github.com/PipedreamHQ/pipedream/blob/master/components/nordigen/common/constants.mjs

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia have you fixed it?
<img width="779" alt="image" src="https://user-images.githubusercontent.com/104946677/207692662-9390a48a-fd58-472d-b5e0-422770366356.png">

**Comment by lcaresia** [comment]
@dannyroosevelt 

https://api.slack.com/methods/emoji.list

This endpoint just return URLs to images (because is for custom emojis), so is not possible to render the custom emojis on the options.
About others emojis, has hundreds of them, I don't know if will be viable to render all.

So to resolve this, I just copied this prop from other action and added the name of custom emojis from API as options.

I don't know if have some better solution, but I think not.

**Comment by dannyroosevelt** [comment]
Yea, makes sense. No problem, thanks!
