### ISSUE TITLE
[APP] Onethread.app

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#4669]
**Name of app / service**
[Onethread.app](https://t.co/k5iD23q3Cq)

**Link to developer documentation**
https://www.onethread.app/api-guide.html

**Is lack of support preventing you from building workflows, or do you have a workaround?**
See - https://twitter.com/orvi_onethread/status/1588563882838491136

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
now api docs at https://www.onethreadapp.com/api-documentation

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/onethread
