### ISSUE TITLE
[APP] Kartra

### ISSUE THREAD

**Issue by soyabn09** [PipedreamHQ/pipedream#4673]
**Name of app/service**

Kartra

**Link to developer documentation**

https://documentation.kartra.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I do have a workaround on certain things not everything though.

**Are there specific actions or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

I would like to have a verified Kartra app on Pipedream so I can use the rest of the API that is about it.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @soyabn09 , thank you for the request, and for preferring Pipedream.

I have submitted Kartra app for approval, it should be published soon.

Best,

**Comment by sergioeliot2039** [comment]
Hello @soyabn09 , here is finally a basic integration for Katra: https://pipedream.com/apps/kartra

can you please have a look and let us know any issues?

Thanks

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
