### ISSUE TITLE
[APP] Zoho SalesIQ

### ISSUE THREAD

**Issue by wwc-development** [PipedreamHQ/pipedream#4674]
Name of app / service
**Zoho SalesIQ**

Link to developer documentation
**[https://www.zoho.com/salesiq/help/developer-section/rest-api-v2.html](https://www.zoho.com/salesiq/help/developer-section/rest-api-v2.html)**

Is lack of support preventing you from building workflows, or do you have a workaround?
**I'm stuck when setting up OAuth for authenticating with Zoho SalesIQ.**

**I'd like to use "POST Encrypt" so I can encrypt link URL parameters ➡️ [https://www.zoho.com/salesiq/help/developer-section/encryption-api-v2.html](https://www.zoho.com/salesiq/help/developer-section/encryption-api-v2.html)**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
This is in progress, but we've run into an issue making the Authorization Request and we've initiated a support request with Zoho:
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/200472293-b61e1060-2256-408f-8d21-fe168a375edd.png)

**Comment by wwc-development** [comment]
Hi Danny,

No worries. Thanks for the update.


Joel Blumer
Worldwide Casting<https://www.worldwide-casting.com/>

**Comment by wwc-development** [comment]
Hi @dannyroosevelt 

Any estimate on how long Zoho usually takes to respond to a support request like this?

**Comment by dannyroosevelt** [comment]
> Hi @dannyroosevelt
> 
> Any estimate on how long Zoho usually takes to respond to a support request like this?

They've actually been moderately responsive but their responses have not resolved the issue. There appears to be something wrong with the Authorization URL but the documentation they sent over did not address our specific question.

Here is their documentation on construction the Authorization request:
https://www.zoho.com/accounts/protocol/oauth/web-apps/authorization.html

Here is the request we're making:
```
https://accounts.zoho.com/oauth/v2/auth
?access_type=offline
&client_id=1000.RPK3JVBXAFVD9TB0MUGM7TU1FAHT9M
&prompt=consent
&redirect_uri=https%3A%2F%[2Fapi.pipedream.com](http://2fapi.pipedream.com/)%2Fconnect%2Foauth%2Foa_GNji7D%2Fcallback
&response_type=code
&scope=operators.READ%2Cencryptions.CREATE%2Cuserpreferences.READ
&state=dV9yOWhib0Q1fDFmNDFmZDI0NmJkMDhmMzRiYjJmYzhkNDMwYzBkMjNh
```

**Comment by wwc-development** [comment]
Ok, thanks for the quick reply and the update. I really appreciate it.

**Comment by wwc-development** [comment]
Hi @dannyroosevelt, Happy New Year to you! Is there a status update on this request or any Zoho SalesIQ components? Thanks

**Comment by dannyroosevelt** [comment]
We've resolved the issue with the Authorization URL but there is now a different blocker, which I think is a bug on their side, but.

The api_domain that is returned from the [Access Token Request](https://www.zoho.com/accounts/protocol/oauth/web-apps/access-token.html) is `https://www.zohoapis.com/`. However, according to [this documentation](https://www.zoho.com/salesiq/help/developer-section/rest-api-v2.html), the API domain should be `salesiq.zoho.com`.

I'm still working with their team on resolving -- I'm happy to add you to the thread I have with them if that'd be helpful. If so, let me know the best email to use (you can respond here or send me a note to `integrations @ pipedream . com` with your email).

**Comment by wwc-development** [comment]
Hi @dannyroosevelt, sorry for responding super late. I'm sure what's being discussed would fly right over my head 😵. Thank you for taking the time to speak with the SalesIQ team to resolve this issue. By chance, have there been any updates since Jan 2nd?

**Comment by malexanderlim** [comment]
Hi @wwc-development , this integration is complete! Please let us know if you have any feedback. 
https://pipedream.com/apps/zoho-salesiq
