### ISSUE TITLE
openai / gpt-3

### ISSUE THREAD

**Issue by ChrisHausler** [PipedreamHQ/pipedream#4675]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @ChrisHausler thanks for the request!

There is a basic integration already for OpenAI -- https://pipedream.com/apps/openai

Is this is what you are looking for?
Let us know on anyway we can help

**Comment by breadbrowser** [comment]
> Hi @ChrisHausler thanks for the request!
> 
> There is a basic integration already for OpenAI -- https://pipedream.com/apps/openai
> 
> Is this is what you are looking for? Let us know on anyway we can help

Why doesn't this have a hugging face?

**Comment by sergioeliot2039** [comment]
Kiddingly speaking @breadbrowser, we were waiting for you to request it! :)
I created an issue for tracking that, feel free to follow #4707 if you'd like

**Comment by breadbrowser** [comment]
> Kiddingly speaking @breadbrowser, we were waiting for you to request it! :) I created an issue for tracking that, feel free to follow #4707 if you'd like

what about 1sec mail's api

**Comment by sergioeliot2039** [comment]
Hey @breadbrowser thank you for being diligent about requesting missing apps on Pipedream.
I created an issue for tracking that, feel free to follow #4725 if you'd like.
If there is any other app you'd like to be added to Pipedream kindly lest us know.
Thanks!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
> > Kiddingly speaking @breadbrowser, we were waiting for you to request it! :) I created an issue for tracking that, feel free to follow #4707 if you'd like
> 
> what about 1sec mail api

@breadbrowser https://pipedream.com/apps/onesec-mail/

**Comment by dannyroosevelt** [comment]
> > Hi @ChrisHausler thanks for the request!
> > There is a basic integration already for OpenAI -- https://pipedream.com/apps/openai
> > Is this is what you are looking for? Let us know on anyway we can help
> 
> Why doesn't this have a hugging face api?

@breadbrowser https://pipedream.com/apps/hugging-face/

**Comment by breadbrowser** [comment]
> 

Cool
