### ISSUE TITLE
[TRIGGER] Telegram Bot - New Slash Commands

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4681]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

Currently we don't have a source specifically for responding to Telegram Bot slash commands.

As a Pipedream user, you can use the **New Updates** trigger, but it's clunky for building slash commands for Telegram Bots.

Here's an example of all of the steps you need to take currently to build a Telegram Bot that responds to a slash command:

https://www.youtube.com/watch?v=Tv2eT0CxoP4

Instead, it would be great if you could easily define a specific trigger to listen to all slash commands, or just a subset of slash commands.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

* `getMyCommands` - [list all commands available to the current bot](https://core.telegram.org/bots/api#getmycommands).

The `getMyCommands` endpoint should be used to build an async options list for a `commands` prop.

Then you can detect if a particular incoming event is a slash command via the event's payload under the `entities` array`:
![CleanShot 2022-11-07 at 11 19 32@2x](https://user-images.githubusercontent.com/2694734/200360779-371203a1-e74e-4dc7-983e-128d30fc054d.png)

Pseudocode example:

```javascript
import telegramBot from '../telegramBot.app.mjs';

export default {
  key: 'telegram-new-bot-command',
  name: 'New Bot Command',
  props: {
     telegramBot,
     commands: {
        optional: true,
        type: 'string[]',
        async options() {
            // list commands from the `getMyCommands` endpoint
        }
     }
  }
  async run(event) {
     // detect if the event is a slash command using the `entites` attribute
     // detect if there is a subset of commands defined in this.commands, and if this event is one of them
  }
}

```

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
