### ISSUE TITLE
[APP] Snyk

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4686]
https://snyk.docs.apiary.io/#introduction/api-vs-cli-vs-snyk-integration

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
https://pipedream.com/apps/snyk
