### ISSUE TITLE
[TRIGGER] X hours before Google calendar event

### ISSUE THREAD

**Issue by gbxl** [PipedreamHQ/pipedream#4688]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Triggers X hours before the calendar event is set to happen at

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
Google calendar API

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by Hassan-Abbas-SQA** [comment]
![image](https://user-images.githubusercontent.com/104946677/201422479-bbae00ae-9d77-467b-a849-26313aa6a3a8.png)

**Comment by andrewjschuang** [comment]
@Hassan-Abbas-SQA can you please provide the details for this error that occurred pasting here the `[debug]` line?

**Comment by Hassan-Abbas-SQA** [comment]
> @Hassan-Abbas-SQA can you please provide the details for this error that occurred pasting here the `[debug]` line? Question: did you publish and create the source through the UI or through `pd dev`?

i published the source using pd publish and created the source with UI

**Comment by andrewjschuang** [comment]
> i published the source using pd publish and created the source with UI

Ok, thanks for the reply. can you please dm me the `[debug]` error line on Slack? I couldn't reproduce the issue
