### ISSUE TITLE
[TRIGGER] Discord interaction events / slash commands

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#4689]

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by lcaresia** [comment]
@dylburger This is on Discord Bot, correct?

**Comment by Hassan-Abbas-SQA** [comment]
Test Passed
![image](https://user-images.githubusercontent.com/104946677/203627884-4c9b4f8c-b1be-4695-bc8d-ad194d67491a.png)
