### ISSUE TITLE
[BUG] Pressing Ctrl + D while working on nodejs code will cause the project to redeploy (excessive use will cause a rate limit)

### ISSUE THREAD

**Issue by GlenMerlin** [PipedreamHQ/pipedream#469]
**Describe the bug**
When editing code and using Ctrl+ D to multiselect sections of code every time its pressed causes the workflow to redeploy

**To Reproduce**
1. Go to a new work flow or a work flow with editable node.js code and type out the same thing multiple times
2. Press Ctrl + D
3. Notice that both the redeploy action and the multiselect actions fire at the same time

**Expected behavior**
The workflow should not redeploy while the user is focused on the code editor with the Ctrl + D input

**Desktop:**
 - OS: Windows 10 2004
 - Browser: Firefox 
 - Version: Quantum 80.0.1

**Comment by dylburger** [comment]
@GlenMerlin we actually allow you to remap the default keyboard shortcut for deploying code to something different than `Ctrl + D`. Just click on the keyboard icon near the top-right of your workflow:

<img width="203" alt="Screen Shot 2020-09-21 at 4 18 26 PM" src="https://user-images.githubusercontent.com/242668/93830860-3ec0c900-fc26-11ea-95b5-d294fe27bf94.png">

then click into the **Deploy Workflow** section and hold whatever shortcut combination (e.g. `Ctrl + Shift + D`) that you'd like.

<img width="777" alt="Screen Shot 2020-09-21 at 4 17 40 PM" src="https://user-images.githubusercontent.com/242668/93830852-3bc5d880-fc26-11ea-83c3-d3acce520088.png">

That will remap the deploy shortcut, allowing you to use the default Monaco shortcut alone.

Let me know if that works OK for you.

**Comment by GlenMerlin** [comment]
Oh awesome that works just fine thank you

**Comment by dylburger** [comment]
Great thanks for confirming @GlenMerlin .
