### ISSUE TITLE
[ACTION] Audit on polling sources

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4691]
Let's make sure all polling sources in the registry have a default polling interval of 15 minutes.

For example, it looks like HackerNews sources are set to 15 seconds:
https://github.com/PipedreamHQ/pipedream/blob/master/components/hacker_news/sources/new-stories-by-keyword/new-stories-by-keyword.js#L16

**Comment by vunguyenhung** [comment]
Hello @lcaresia @dannyroosevelt, it seems that this PR contains hundreds of config change and no logic changed. Could you advice how I can test this? Or should we just ship it?

**Comment by lcaresia** [comment]
@vunguyenhung I think this PR don't need tests, what you think @dannyroosevelt ?
