### ISSUE TITLE
[BUG] NPM pdf-parse - could not compute configurable props

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#4694]
**Describe the bug**
I'm trying to use the package https://www.npmjs.com/package/pdf-parse

**To Reproduce**
```javascript
import fs from "fs";
import pdf from "pdf-parse";

export default defineComponent({
  async run({ steps, $ }) {
   let dataBuffer = fs.createReadStream('/tmp/'+steps.trigger.event.body["attachment-1"].filename)
    pdf(dataBuffer).then(function(data) {
        return data
    });
  },
})
```

**Screenshots**
<img width="905" alt="" src="https://user-images.githubusercontent.com/2955762/200619683-3512a357-955a-48fb-80c7-ab2e2110f319.png">

**Desktop (please complete the following information):**
 - MacOS 13.1 Beta (22C5044e)
 - Safari 16.2 (18614.3.4.11.2)

**Comment by gbdoin** [comment]
Same issue here with the same package, as well as `crawler-request` which uses `pdf-parse`.

**Comment by marcelocecin** [comment]
same with
```javascript
 import { Actor } from 'apify';
```

**Comment by TomFrankly** [comment]
Same issue here.

**Comment by danpadua** [comment]
Same issue +1

**Comment by kieranjt** [comment]
same issue

**Comment by renattomachado** [comment]
@dylburger @ctrlaltdylan Any predictions to fix this?
We are considering abandoning Pipedream because of this issue that has been preventing us from evolving.

**Comment by andrewjschuang** [comment]
Same issue with `PDFLoader` from [langchain](https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/file_loaders/pdf#setup)

**Comment by marcelocecin** [comment]
https://www.npmjs.com/package/crawler-request
