### ISSUE TITLE
[APP] Contentstack

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4695]
https://www.contentstack.com/docs/developers/

It looks like there are a few APIs for this app, let's integrate whichever ones we can. I asked the customer for more info but have not heard back:
https://twitter.com/vidarmasson/status/1585042406080405504

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
There is one entry at the Project App Store sheet for Contentstack, with OAuth integration method (See [Contentstack OAuth](https://www.contentstack.com/docs/developers/developer-hub/contentstack-oauth/) for official documentation)

You can [Use access token with Contentstack APIs](https://www.contentstack.com/docs/developers/developer-hub/contentstack-oauth/#use-access-token-with-contentstack-apis). These are the Contentstack APIs available:

1. [Content Delivery API](https://www.contentstack.com/docs/developers/apis/content-delivery-api/#introduction)
2. [Content Management API](https://www.contentstack.com/docs/developers/apis/content-management-api/#introduction)
3. [GraphQL Content Delivery API](https://www.contentstack.com/docs/developers/apis/graphql-content-delivery-api/)

So perhaps we could have one Pipedream app for Contentstack (which uses all scopes available accounting for the three APIs). Or three Pipedream apps for Contentstact , one for each API (each app with the respective scopes of the API they are meant to access)

**Comment by malexanderlim** [comment]
Created this app as BYOA-only to begin. There are multiple auth strategies that could work for this app, but starting with OAuth (BYOA) setup to enable users to user their own custom oauth client to start.
