### ISSUE TITLE
[BUG] PIP camelot - Command failed: python3 -m pip install

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#4698]
**Describe the bug**
I'm trying to use the package https://github.com/atlanhq/camelot

**To Reproduce**
```python
import camelot

def handler(pd: "pipedream"):
  tables = camelot.read_pdf('/tmp/'+pd.steps["trigger"]["event"]["attachments"][0]["filename"])
  return tables[0]
```

**Screenshots**
<img width="909" alt="" src="https://user-images.githubusercontent.com/2955762/200628907-1a418c3e-b440-4ead-bdc8-589e625d1ab3.png">

**Desktop (please complete the following information):**
 - MacOS 13.1 Beta (22C5044e)
 - Safari 16.2 (18614.3.4.11.2)

**Comment by dylburger** [comment]
Blocked on #4820
