### ISSUE TITLE
[BUG] NPM tesseract.js - Error: EROFS: read-only file system, open './eng.traineddata'

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#4703]
**Describe the bug**
I'm trying to use the package https://www.npmjs.com/package/tesseract.js

**To Reproduce**
```javascript
import { createWorker } from 'tesseract.js';

export default defineComponent({
  async run({ steps, $ }) {
    const worker = createWorker({logger: m => console.log(m)});
    await worker.load();
    await worker.loadLanguage('eng');
    await worker.initialize('eng');
    const { data: { text } } = await worker.recognize(steps.trigger.event.attachments[0].contentUrl);
    console.log(text);
    await worker.terminate();
    return text;
  },
})
```

**Screenshots**
<img width="900" alt="" src="https://user-images.githubusercontent.com/2955762/200765207-77889feb-cdb4-494c-8f3e-c5faae0d3271.png">

**Desktop (please complete the following information):**
 - MacOS 13.1 Beta (22C5044e)
 - Safari 16.2 (18614.3.4.11.2)

**Comment by dylburger** [comment]
@marcelocecin This should now be fixed. I ran the latest code from the Tesseract.js GitHub:

```javascript
import { createWorker } from 'tesseract.js';

export default defineComponent({
  async run({ steps, $ }) {
    const worker = await createWorker({
      logger: m => console.log(m)
    });
    await worker.loadLanguage('eng');
    await worker.initialize('eng');
    const { data: { text } } = await worker.recognize('https://tesseract.projectnaptha.com/img/eng_bw.png');
    console.log(text);
    await worker.terminate();
  },
})
```

**Comment by marcelocecin** [comment]
Hi Dylan, how are you?
the script stopped working:
<img width="807" alt="" src="https://github.com/PipedreamHQ/pipedream/assets/2955762/6583679f-237f-4f45-bf2b-10d1adecef22">
Would you help me ?
thanks
