### ISSUE TITLE
[BUG] `null` values to props cause the **Inputs** tab to break

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4708]
**Describe the bug**

If you pass a `null` value to a prop in a configured step, the step's **Input** tab will break and render nothing.

**To Reproduce**
1. Create a Node.js step with the scaffolding below
2. Enter in a valid string as one prop, and use `{{ null }}` as a custom expression on the other
3. Test the step
4. Click the **Inputs** tab and observe the blank inputs

```javascript
// To use previous step data, pass the `steps` object to the run() function
export default defineComponent({
  props: {
    string: {
      type: 'string',
      label: 'Test Null'
    },
    valid: {
      type: 'string',
      label: "Valid prop to enable **Inputs**"
    }
  },
  async run({ steps, $ }) {
    // Return data to use it in future steps
    return this.string;
  },
})
```

**Expected behavior**
I expect `null` values to appear in the **Inputs** tab.

**Screenshots**
<img width="1021" alt="CleanShot 2022-11-09 at 13 34 52@2x" src="https://user-images.githubusercontent.com/2694734/200913391-a4cfca64-dd68-459a-b6f6-f8b0ada75ec4.png">

**Additional context**
Slack thread: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1668018902035719?thread_ts=1668005908.881219&cid=CPTJYRY5A

**Comment by dylburger** [comment]
Luckily this appears to work now. `null` inputs are blank, but the other value shows up (I used the same code / config as you did above)

<img width="464" alt="Screenshot 2023-07-30 at 9 36 34 PM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/1eb2b75c-47ed-4568-914c-548f96af6db7">
