### ISSUE TITLE
[ACTIONS] WhatsApp Business

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4720]
### App
`whatsapp_business`
https://developers.facebook.com/docs/whatsapp/cloud-api

### Actions
- Send a text message
- List message templates
- Send a template message

Here are some examples:
https://pipedream.com/new?h=tch_wNxf8d

**Comment by dannyroosevelt** [comment]
Certain endpoints require the phone_number_id of the sender. You should be able to get that via:

```
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    whatsapp_business: {
      type: "app",
      app: "whatsapp_business",
    }
  },
  async run({steps, $}) {
    return await axios($, {
      url: `https://graph.facebook.com/v15.0/${this.whatsapp_business.$auth.business_account_id}/phone_numbers`,
      headers: {
        Authorization: `Bearer ${this.whatsapp_business.$auth.oauth_access_token}`,
      },
    })
  },
})
```
That returns the below for our account, for example:
```
{
	"data": [{
		"verified_name": "Pipedream",
		"code_verification_status": "VERIFIED",
		"display_phone_number": "<hidden>",
		"quality_rating": "GREEN",
		"id": "<hidden>"
	}],
	"paging": {
		"cursors": {
			"before": "QVFIUnJrd2xNTDVKUURWdmtSOXpMZAmtVT1NPbkdRYWpyT3dzVFA1VzZAfZAUttalJ0S2VzT1ZAyRklFUnRiMVRRd0NpMVpuUDVYODV1UGNaRDlFem5HRWxLblJn",
			"after": "QVFIUnJrd2xNTDVKUURWdmtSOXpMZAmtVT1NPbkdRYWpyT3dzVFA1VzZAfZAUttalJ0S2VzT1ZAyRklFUnRiMVRRd0NpMVpuUDVYODV1UGNaRDlFem5HRWxLblJn"
		}
	}
}
```

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
