### ISSUE TITLE
[APP] 1sec MAIL

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#4725]
**Name of app / service**
1sec MAIL

**Link to developer documentation**
https://www.1secmail.com/api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Not specified

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Not specified

**Additional context**
Requested by the user on issue comment https://github.com/PipedreamHQ/pipedream/issues/4675#issuecomment-1311898663

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
https://pipedream.com/apps/onesec_mail
