### ISSUE TITLE
[ACTION] Notion: Duplicate Page action & update Append Block to handle all block types

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#4726]
Notion

- Get the append action working, to handle all block types
- Create a separate “duplicate page” action that combines the above functionality into a single step

Context: https://pipedream-users.slack.com/archives/G01J50YGJGP/p1668187870272229

**Comment by Hassan-Abbas-SQA** [comment]
@dannyroosevelt all tests passed for me can you please check if this fulfilling all your requirements
![image](https://user-images.githubusercontent.com/104946677/202282037-411a3fcd-f9b6-40c8-bd33-b8fcf08269bd.png)

**Comment by dannyroosevelt** [comment]
LGTM!
