### ISSUE TITLE
[APP] nightfall.ai

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#4729]
**Name of app / service**
nightfall.ai

**Link to developer documentation**
https://docs.nightfall.ai/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
workaround, use npm package

**other interesting links**
https://nightfall.ai/developer-platform
https://github.com/nightfallai

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@marcelocecin here is a basic integration for Nightfall:
https://pipedream.com/apps/nightfall-ai/

Are there specific actions or triggers you'd like to use for Nightfall?

**Comment by marcelocecin** [comment]
maybe the samples of https://github.com/nightfallai/nightfall-nodejs-sdk thanks !

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
