### ISSUE TITLE
[ACTIONS, SOURCES] Google Classroom new components

### ISSUE THREAD

**Issue by sino321** [PipedreamHQ/pipedream#4731]
### name: google classroom

[link to developer documentation](https://developers.google.com/classroom) sorry idk if this is what u were asking for

### Is lack of support preventing you from building workflows, or do you have a workaround?

YES I have no idea how this stuff works and google classroom not being there isn't making this any easier

### triggers: 

1. assignment in a specified class posted 
2. assignment in specified class _with a keyword in the title_ posted 
3. assignment in specified class _with a keyword in the description_ posted 

would be nice to have the option of multiple keywords for 1 trigger :)

### actions: 

be able to pull an assignment's:
1. name
2. due date
3. link
5. class 
6. description
7. teacher

planning on using this with notion - idk how this would work but i want to be able to automatically have all assignments posted on google classroom transferred to anywhere i want to on notion, along with their due date, link, class & description. i know I'm asking for a lot but this could really help me out and i see it being helpful for students all around the world as well :)

**Comment by sergioeliot2039** [comment]
Hi @sino321 , thank you for your interest in using Pipedream for your integrations.

Here is basic integration for Google Classroom: https://pipedream.com/apps/google-classroom

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sino321** [comment]
> Hi @sino321 , thank you for your interest in using Pipedream for your integrations.
> 
> Here is basic integration for Google Classroom: https://pipedream.com/apps/google-classroom

![image](https://user-images.githubusercontent.com/51765866/201494940-9fcdf9bf-833a-4af7-8147-bde0ce13cce9.png)
no idea what you just showed me but google classroom doesn't show up here, I'm confused

**Comment by sergioeliot2039** [comment]
You can use the basic integration under a workflow step.

For trigger use HTTP, then in the first step look for Google Classroom

![image](https://user-images.githubusercontent.com/25184117/201495076-4f95996a-c702-4d72-a749-f43e8b14da93.png)

Let me know if you found it

**Comment by sino321** [comment]
thank you :)

**Comment by sergioeliot2039** [comment]
Please also consider creating the following actions.

New assigment created
was requested on https://github.com/PipedreamHQ/pipedream/issues/2333
Related: https://github.com/PipedreamHQ/pipedream/issues/2333

Assignment due date changed (requested on ##2738)
Assignment marked as done
Assignment receives new private comment
