### ISSUE TITLE
[ACTION] Slack: Support managing users in groups

### ISSUE THREAD

**Issue by rdsedmundo** [PipedreamHQ/pipedream#4741]
**Is there a specific app this action is for?** Slack

**Please provide a link to the relevant API docs for the specific service / operation.**

https://api.slack.com/methods/usergroups.users.list
https://api.slack.com/methods/usergroups.users.update

Use-case: would like to update the current on-call on PagerDuty to a (at)oncall group.

**Comment by DilanAthukorala** [comment]
@rdsedmundo Thanks for creating this ticket, just to confirm your requirement / use-case - is it to add / remove users in a slack channel? and can you share what kind of actions you need to perform on the users?

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by rdsedmundo** [comment]
@DilanAthukorala this doesn't involve Slack channels, but Slack user groups.

I'd like to auto-manage a (at)oncall group, so every week it changes to someone else. Then anyone in any Slack channel can just mention (at)oncall group and that person is notified.

Another example would be, I can create a group called (at)devs and add/remove someone there using this action when they onboard.

**Comment by alysonturing** [comment]
@rdsedmundo Hello, I'm looking into the docs that you provided, but to clarify the request does the user group list has a property that define a user as on-call?

**Comment by rdsedmundo** [comment]
@alysonturing the update operation accepts both a group ID and a comma separated list of user IDs: https://api.slack.com/methods/usergroups.users.update
