### ISSUE TITLE
Nuevo Escenario Mansiones de la Locura

### ISSUE THREAD

**Issue by Odindm1** [PipedreamHQ/pipedream#4754]
Name: La Maldicion de Malory

Link: https://github.com/Odindm1/La-Maldicion-de-Malory

¿Podriais agregar esta mision para mansiones de la locura?

Gracias.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by Odindm1** [comment]
No hace falta.
