### ISSUE TITLE
[ACTION]Add notes to Pipedrive deals

### ISSUE THREAD

**Issue by binzari** [PipedreamHQ/pipedream#4758]
**Is there a specific app this action is for?**
It's very useful to be able to add notes to Pipedrive's deals automatically.

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.pipedrive.com/docs/api/v1/Notes#addNote

**Comment by binzari** [comment]
hey everyone, I see that this functionality is in "Done" but I still can't find it when trying to add it to a workflow. Could you please tell me how does it work? Or direct to some article/ FAQ explaining the process of how a functionality gets from the idea to actual being able to add it as a regular user in a workflow. Thanks!

**Comment by dannyroosevelt** [comment]
> hey everyone, I see that this functionality is in "Done" but I still can't find it when trying to add it to a workflow. Could you please tell me how does it work? Or direct to some article/ FAQ explaining the process of how a functionality gets from the idea to actual being able to add it as a regular user in a workflow. Thanks!

Hi @binzari it's the Add Note action you're looking for, right? 
https://pipedream.com/apps/pipedrive/actions/add-note

![Google Chrome - Untitled workflow - Pipedream - 2022-11-21 at 9 44 29 AM](https://user-images.githubusercontent.com/20780753/203124571-111f1e18-c803-4780-a96e-40749894f848.gif)
