### ISSUE TITLE
[FEATURE] We should have the ability to have search/filter functionality on the Inspector. Actually, we should be able to filter across any run workflow to see just the workflows that match the filter

### ISSUE THREAD

**Issue by RyanTHartigan** [PipedreamHQ/pipedream#4764]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Do you have a workaround?**
Are you able to tackle the problem with an existing workaround, or can you not move forward without this feature?

**Comparable features in other tools?**
Is this feature or one like it available in another platform? If so, we'd love to hear what you like about that implementation.

**Additional context**

**Comment by dylburger** [comment]
@RyanTHartigan Thanks for the request. We're building a global event UI that will let you search / filter on events right now. We're tracking at #188 if you'd like to follow there.
