### ISSUE TITLE
[TRIGGER] Discord Post (forum) created

### ISSUE THREAD

**Issue by ValdoTR** [PipedreamHQ/pipedream#4775]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
When a post is created (this lives inside Discord Forums new feature) we should be able to create Github issues for exemples (and migrate the title, body and tags)

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://discord.com/developers/docs/intro

**Comment by dannyroosevelt** [comment]
Thanks for the request! This is on the team's radar and we are tracking here: https://github.com/PipedreamHQ/pipedream/issues/4507 -- feel free to subscribe to that ticket for updates.
