### ISSUE TITLE
[ACTION] Verify Slack Event URL

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4781]
**Is there a specific app this action is for?**

Slack

**Please provide a link to the relevant API docs for the specific service / operation.**

We would like an action that can verify the contents of the `X-Slack-Signature` header.

The use case is when using the Slack Events subscription system, your custom Slack bot will receive a webhook on specific events.

Currently, there's no pre-built way to verify these event payloads:

<img width="752" alt="CleanShot 2022-11-18 at 11 29 21@2x" src="https://user-images.githubusercontent.com/2694734/202753942-f7adb98d-6958-4824-b030-f91dbe1515b1.png">

https://api.slack.com/authentication/verifying-requests-from-slack

## Set up

First create a custom Slack bot at https://api.slack.com and authorize it to your Slack workspace.

Then enable an Event Subscription to listen to reactions being added to messages:
![CleanShot 2022-11-18 at 11 30 42@2x](https://user-images.githubusercontent.com/2694734/202754360-405dac45-30a5-4763-8176-c04162ea9c4d.png)

Generate a test event by reacting to a message.

The payload is sent to the webhook, but we need a pre-built action to verify it (Refer to [Steps to step verify the contents of the `X-Slack-Signature` header](https://api.slack.com/authentication/verifying-requests-from-slack#verifying-requests-from-slack-using-signing-secrets__a-recipe-for-security__how-to-make-a-request-signature-in-4-easy-steps-an-overview)
)
![CleanShot 2022-11-18 at 11 32 00@2x](https://user-images.githubusercontent.com/2694734/202754491-5ea01224-1885-4604-a4df-c0d2326cdc6a.png)

### Props
- Slack signing secret (string)
- Slack signature (from `X-Slack-Signature` header)

### Result
- The action returns successful when the Slack signature is valid
- The action returns error with message "Signature is invalid" when the Slack signature is invalid

**Comment by vunguyenhung** [comment]
Hello @ctrlaltdylan, I've updated the description to clarify the requirement, feel free to modify it if it isn't make sense to you.

On another note, should we embed this to our existing Slack sources so that our Slack sources would verify all event emitted is verified?

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed
![image](https://user-images.githubusercontent.com/104946677/203160138-4b5ffa6c-e0ba-401e-919c-1170f17a9768.png)
for Negative TestCase
![image](https://user-images.githubusercontent.com/104946677/203160267-1a8d5075-ec7d-43f8-abf1-9c3c974bb573.png)
