### ISSUE TITLE
[BUG] Gmail send-email: expression in attachment 'filename' not parsed

### ISSUE THREAD

**Issue by hanspinckaers** [PipedreamHQ/pipedream#4784]
**Describe the bug**
I have a step where I want to send an email with a specific file, and with a filename based on a reference from the object explorer. However, the email is send with `"{{event.file.name}}"` instead of `"article.pdf"` for example.

**To Reproduce**
1. Create a Gmail send-email action
2. Enter a reference {{}} in the 'key' part of the attachment
3. Notice the send email has {{}} instead of the parsed reference value.

**Expected behavior**
The expression, e.g., `{{event.file.name}}`, is parsed before email is sent.

**Screenshots**
<img width="315" alt="Screenshot 2022-11-19 at 15 58 38" src="https://user-images.githubusercontent.com/70747/202857127-ef3f7c6a-9ee2-4f46-859d-937ef1c5237d.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 16.1

**Comment by HansPinckaers** [comment]
I'm a programmer myself, I tried making sense of the code, but couldn't yet (however it looks really clean!). Maybe you can guide me in the right direction? Would like to have this fixed because I'm really excited about this workflow. :smile:

**Comment by dannyroosevelt** [comment]
Thanks for flagging, @HansPinckaers! I can confirm step references are not currently supported as the key in object props, but I’ll raise this with the team asap to see if we can modify that functionality to support this use case.

**Comment by HansPinckaers** [comment]
For anyone finding this issue, my ugly workaround (not used to writing node.js):

```javascript
// To use any npm package, just import it
// import axios from "axios"
/* eslint-disable pipedream/props-description */
import { axios } from "@pipedream/platform"
import MailComposer from "nodemailer/lib/mail-composer/index.js";
import gmail from "@googleapis/gmail";

export default defineComponent({
  key: "gmail-send-email",
  name: "Send Email",
  description: "Send an email from your Google Workspace email account",
  version: "0.0.6",
  type: "action",
  props: {
    gmail: {
      type: "app",
      app: "gmail",
    },
    to: {
      type: "string[]",
      label: "To",
      description: "Enter a single recipient's email or multiple emails as items in an array.",
    },
    cc: {
      type: "string[]",
      label: "Cc",
      optional: true,
      description: "Enter a single recipient's email or multiple emails as items in an array.",
    },
    bcc: {
      type: "string[]",
      label: "Bcc",
      optional: true,
      description: "Enter a single recipient's email or multiple emails as items in an array.",
    },
    fromName: {
      type: "string",
      label: "From Name",
      description: "Specify the name that will be displayed in the \"From\" section of the email.",
      optional: true,
    },
    replyTo: {
      type: "string",
      label: "Reply To",
      description: "Specify the email address that will appear on the \"Reply-To\" field, if different than the sender's email.",
      optional: true,
    },
    subject: {
      type: "string",
      label: "Subject",
      description: "Specify a subject for the email.",
    },
    body: {
      type: "any",
      label: "Email Body",
      description: "Include an email body as either plain text or HTML. If HTML, make sure to set the \"Body Type\" prop to `html`.",
    },
    bodyType: {
      type: "string",
      label: "Body Type",
      description: "Choose to send as plain text or HTML. Defaults to `plaintext`.",
      optional: true,
    },
    filename: {
      type: "string",
      label: "Attachment filename",
      description: "The name the file should have.",
    },
    filepath: {
      type: "string",
      label: "Path to attached file",
      description: "The patch to the file to attach e.g., /tmp/article.pdf.",
    },
  },
  async run({ steps, $ }) {
    const userInfo = await axios($, {
      url: `https://www.googleapis.com/oauth2/v1/userinfo`,
      headers: {
        Authorization: `Bearer ${this.gmail.$auth.oauth_access_token}`,
      },
    })
    console.log(userInfo) 

    const opts = {
      from: this.fromName
        ? `${this.fromName} <${userInfo.email}>`
        : `${userInfo.name} <${userInfo.email}>`,
      to: this.to,
      cc: this.cc,
      bcc: this.bcc,
      replyTo: this.replyTo,
      subject: this.subject,
    };

    opts.attachments = [{
      filename: this.filename, 
      path: this.filepath,
    }];
    const auth = new gmail.auth.OAuth2();
    auth.setCredentials({
      access_token: this.gmail.$auth.oauth_access_token,
    });
    const client = gmail.gmail({
      version: "v1",
      auth,
    });

    opts.text = this.body;
    const mailComposer = new MailComposer(opts);
    const mail = mailComposer.compile();
    mail.keepBcc = true;
    const message = await mail.build();
    const rawMessage = Buffer.from(message)
        .toString("base64")
        .replace(/\+/g, "-")
        .replace(/\//g, "_")
        .replace(/=+$/, "");
    const response = await client.users.messages.send({
      userId: userInfo.id,
      requestBody: {
        raw: rawMessage,
      },
    });
    // const response = await this.gmail.sendEmail(opts);
    $.export("$summary", `Successfully sent email to ${this.to}`);
    return response;
  },
})
```

**Comment by jadamconnor** [comment]
The placeholder text for the attachments key field clearly says it's a text field, whereas the value field placeholder says it allows text or expressions. From the perspective of a user, it seems like this is intended.

**Comment by andrewjschuang** [comment]
I changed how we handle attachment props, let me know if this solves your issue!

**Comment by zalmanlew** [comment]
@andrewjschuang not sure this change is better, it results in making it much more difficult to attach multiple files automatically to an email (without a defined number of attachments).

To solve the issue mentioned here you just need to enter the dynamic value in the following format - but it works and is very easy to add however many files as needed.
```
{{ {[`${event.file.name}.pdf`]: steps.path.to.fileUrl } }}
```
----
To attach a multiple files, use a previous code step to prepare the array for you
Assuming an array of files like this
```json
[
  {
    "name": "whatever.pdf",
    "url": "https://example.org/somefile.pdf"
  },
  {
    "name": "bar.png",
    "url": "https://example.org/bar.png"
  }
]
```
Then a simple function thanks to ChatGPT to convert the format
```javascript
const convertAttachmentsToObjectKeys = (attachments) => attachments.reduce((a, { name, url }) => (a[name] = url, a), {});

return convertAttachmentsToObjectKeys(attachmentsArray);
```
will return
```
{
  "whatever.pdf": "https://example.org/somefile.pdf",
  "bar.png": "https://example.org/bar.png"
}
```

**Comment by malexanderlim** [comment]
@hanspinckaers , the latest version of the Gmail send-email action that we shipped supports step references for multiple attachments, provided that you have a fixed and known number of attachments. Could you help elaborate on your use case and let us know if this type of a solution would work, or if similar to @zalmanlew, this would be better handled dynamically?

@zalmanlew , can you help us to understand the use case for attaching an multiple attachments dynamically (without a predefined number of attachments)?

**Comment by zalmanlew** [comment]
@malexanderlim one use case is a form with a file upload field - I then want to get some other data and send an email attaching all the files from the file upload.
The user can upload an undefined number of files (even 0).

This is the use case where I was actually using it.

**Comment by zalmanlew** [comment]
I think we can revert to the previous way the component worked (for maximum compatibility) and add some clearer instructions for file names using dynamic values and/or add some code to parse out a dynamic value they might type there.

**Comment by malexanderlim** [comment]
@zalmanlew , I've reverted the change for now to maintain functionality and flexibility - I'll work on some instructions based on the feedback you provided. Thanks for your input.
