### ISSUE TITLE
facebook[APP]

### ISSUE THREAD

**Issue by hugo25-max** [PipedreamHQ/pipedream#4789]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by vunguyenhung** [comment]
Hello @hugo25-max, I may ask what specific Graph API you need? There're some existing issues that we're tracking related to Facebook integration, maybe you can track one of them 🙏

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
