### ISSUE TITLE
student developer account [TRIGGER]

### ISSUE THREAD

**Issue by san0627** [PipedreamHQ/pipedream#4805]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by vunguyenhung** [comment]
Hello @san0627, may I ask what app is this for? Could you provide the link to the app homepage?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
