### ISSUE TITLE
[BUG] add_single_row error Cannot read property 'updatedRange' of undefined

### ISSUE THREAD

**Issue by bnygld** [PipedreamHQ/pipedream#4809]
**Describe the bug**
When using the `add_single_row`, step for the Google Sheets integration from a Slack trigger, the row is added to the sheet but the workflow errors with `Cannot read property 'updatedRange' of undefined` so it can't be saved.

**To Reproduce**
1. Create workflow with slack trigger, configure a public channel
2. add `add_single_row` step and use the expressions `{{steps.trigger.context}}`, `{{steps.trigger.event.user}}` and  `{{steps.trigger.event.text}}`
3. Test the workflow

**Expected behavior**
The workflow reports success

**Screenshots**
![image](https://user-images.githubusercontent.com/8862239/203529186-aa121f30-ec03-47e1-99fd-dc595f2724e6.png)

**Desktop (please complete the following information):**
 - OS: MacOS 13.0
 - Browser: Edge 
 - Version 107.0.1418.42 (Official build) (arm64)

**Smartphone (please complete the following information):**

**Additional context**
Problem happens on a sheet shared with me from a personal drive, a sheet shared with me from a shared drive and a sheet that I own

**Comment by vunguyenhung** [comment]
Hello @benny-gold @ctrlaltdylan, I'm able to reproduce this bug on my side with this simple case:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/18277920/203563596-66990029-d19f-4a79-a8c8-96059fc2658b.png">

I'll add this to our component backlog 🙏
