### ISSUE TITLE
[BUG] Workflow with HubSpot form submit trigger is not always executed

### ISSUE THREAD

**Issue by birdmeister** [PipedreamHQ/pipedream#4813]
Bug description
A Pipedream workflow does not always get triggered. This workflow is supposed to trigger upon a HubSpot form submit. Functionally the trigger/workflow is correct. Sometimes it does get triggered, sometimes it does not. There is no error, no mention in Inspector either

How to reproducce
1. Go to the page with the HubSpot form: https://product.atradius.nl/kredietwaardigheidscheck
2. Enter data and submit the form
3. In Pipedream, this workflow should be always be triggered: 'HubSpot form Kredietwaardigheidscheck' (https://pipedream.com/@birdman/hubspot-form-kredietwaardigheidscheck-p_yKCKGZQ/inspect)

Expected behavior
The above indicated workflow should be triggered and a this should be visible in the Inspector as well

Screenshots
Cannot add screenshots, as it either works or nothing is visible of the form submission in Pipedream

Desktop (please complete the following information):
 - Mac OS
 - Chrome
 - Version 107.0.5304.110

Additional context
There are other HubSpot forms linked to workflows and so far these are performing correctly.

**Comment by vunguyenhung** [comment]
Hello @birdmeister, as discussed with you on Slack, I couldn't reproduce this issue per the image below
![14 49 36 - 23 - 11 - 2022](https://user-images.githubusercontent.com/18277920/203570191-07a8f825-0c7c-4050-91ba-7922e7b48dbd.png)

Hello @michelle0927, I see that you've helped to modify the source recently. Could you advice what is the possible root cause to this?

**Comment by birdmeister** [comment]
@vunguyenhung The challenge is that it sometimes works and sometimes not. I don't expect anything to be wrong with the trigger itself otherwise I would never work.

**Comment by michelle0927** [comment]
@vunguyenhung I haven't been able to reproduce this issue. @birdmeister , the times that you click RUN NOW, and the new form submission doesn't show up, are there any errors showing under LOGS?

**Comment by birdmeister** [comment]
@michelle0927 No, no errors under LOGS.
<img width="1486" alt="CleanShot 2022-11-23 at 17 00 51@2x" src="https://user-images.githubusercontent.com/761601/203592512-41cc338d-75de-44da-b7ca-eb6991da0f06.png">

**Comment by michelle0927** [comment]
@vunguyenhung @birdmeister I wonder if could be due to a slight delay between the form submission, and the record of it being available through the API. I think we could update `new-form-submission` to check for submissions since the last successful form submission instead of submissions since the last time the source ran.

**Comment by vunguyenhung** [comment]
Hello @michelle0927, I think that's a good idea. I'll put this into our prioritized backlog!

**Comment by birdmeister** [comment]
Unfortunately the issue is not resolved in my case. I confirm I am running v0.0.8.
Some more background info that may help:

- I have 6 HubSpot forms, each of them linked to a workflow (so 6 workflows/6 sources).
- It looks like only 1 form is causing issues from time to time.
- The problematic form is the form with most fields.
- The workflow linked to this form is triggered every 30 minutes. During this timeframe, the form was submitted 2x. Only 1 submission was picked up by Pipedream.
- I have now increased memory size to 512 MB and timeout to 90s.
- The Inspector is not showing any issues.

**Comment by michelle0927** [comment]
@birdmeister Thank you for the additional info. This is probably a silly question, but are the form submissions showing up as expected in the Hubspot dashboard? Also, would you be able to take another screenshot of the source's LOGS after a run that failed to emit all submissions?

**Comment by birdmeister** [comment]
@michelle0927 Yes, the form submission show up correctly in HubSpot. There is also a workflow connected that sends out an internal email with the entered form data. The email helps me to check against Pipedream Inspector.

What is the source's LOGS? In case the form submit is not triggering the workflow in Pipedream there is no data at all in Pipedream. That makes the debugging challenging.

**Comment by michelle0927** [comment]
@birdmeister The logs will show something each time the source is run (every 30 minutes in your case). After the last update, it should perform a `db.get` at the start, and then another `db.get` for each new form submission. In the screenshot below, 3 new form submissions were emitted, and I can see a total of 4 `db.get` in the logs for that run. I'm curious if your logs are showing that `db.get` being performed for the submissions that it misses.

<img width="725" alt="Screen Shot 2022-12-01 at 10 52 10 AM" src="https://user-images.githubusercontent.com/10889229/205101955-42eb802b-3f65-41a0-8b4a-fe09129ec96a.png">

**Comment by birdmeister** [comment]
@michelle0927 Between 2022-12-01 16:00 (CET) and 20:00 (CET) there were 3 form submissions (17:00, 17:49, and 19:24). None of them triggered the workflow. The workflow is working fine as earlier and later form submission did trigger the workflow. Herewith a screenshot of the log.
<img width="1487" alt="CleanShot 2022-12-02 at 08 05 17" src="https://user-images.githubusercontent.com/761601/205235328-3ed1c76a-fc21-441a-a433-1d784213c094.png">

**Comment by michelle0927** [comment]
@birdmeister Thanks again for helping test this. I have another idea about what could be causing this issue, and I set a new PR here - https://github.com/PipedreamHQ/pipedream/pull/4884
