### ISSUE TITLE
Keycloak

### ISSUE THREAD

**Issue by tlloydthwaites** [PipedreamHQ/pipedream#4823]
**Name of app / service**
Keycloak

**Link to developer documentation**
https://www.keycloak.org/documentation

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Workaround is to manage OAuth to Keycloak admin manually with multiple http calls.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Using to update user roles in keycloak when a contact's data changes in Airtable.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/keycloak
