### ISSUE TITLE
[Triggers and Actions] DigitalOcean Spaces

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#4829]
**Name of app / service**
DigitalOcean Spaces (it has it's own keys, so it's a bit different than the regular DigitalOcean API

**Link to developer documentation**
https://docs.digitalocean.com/reference/api/spaces-api/

We can likely reuse most of the code from the S3 components since it was designed to be interchangeable

> The Spaces API aims to be interoperable with Amazon’s AWS S3 API. In most cases, when using a client library, setting the “endpoint” or “base” URL to ${REGION}.digitaloceanspaces.com and generating a Spaces key pair to replace your AWS IAM key pair will allow you to use Spaces in place of S3.
> 
> Spaces provides support for create, read, update, and delete (CRUD) operations for both buckets (Spaces) and objects as well as the ability to define access control lists (ACLs). Some S3 features are not supported... https://docs.digitalocean.com/reference/api/spaces-api/#aws-s3-compatibility

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
More or less the same triggers and actions we have for AWS S3

**Triggers**
- New file uploaded
- Deleted file

**Actions**
- Upload file (from /tmp, from base64, from URL)
- Delete file

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergioeliot2039** [comment]
Hi @zalmanlew, working on the app integration now.

**Comment by dannyroosevelt** [comment]
@zalmanlew we've got a basic integration working here:
https://pipedream.com/apps/digitalocean-spaces/

Can you let us know if it's working for you? And what triggers and actions you'd like to see? 🙏

**Comment by zalmanlew** [comment]
@dannyroosevelt thanks! We can pretty much copy the existing S3 components since they work about the same.

As a starting point, let's do the following

**Triggers**
- New file uploaded
- Deleted file

**Actions**
- Upload file (from /tmp, from base64, from URL)
- Delete file

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
Oops, unintentional automated close, I just re-opened

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report: 
[DigitalOcean_Spaces_4829.pdf](https://github.com/PipedreamHQ/pipedream/files/10276755/DigitalOcean_Spaces_4829.pdf)
