### ISSUE TITLE
[APP] glideapps.com

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#4830]
**Name of app / service**
glideapps.com

**Link to developer documentation**
https://www.glideapps.com/docs/reference/data-sources/glide-table-api
https://www.glideapps.com/docs/reference/actions/webhook
https://github.com/glideapps/glide-code-columns/blob/master/src/columns/fetch.ts

**Is lack of support preventing you from building workflows, or do you have a workaround?**
https://www.glideapps.com/docs/reference/integrations/zapier
https://www.glideapps.com/docs/reference/integrations/make

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrted https://pipedream.com/apps/glide
