### ISSUE TITLE
[Action] Upload Image's via Smugmug API

### ISSUE THREAD

**Issue by 30ashwood** [PipedreamHQ/pipedream#4832]
Used for Smugmug

Looking to have photos uploaded via Jotform and passed through via API and uploaded into a newly created album.

(https://api.smugmug.com/services/api/?method=upload)

Many Thanks

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed 
![image](https://user-images.githubusercontent.com/104946677/205390187-4d97c4ad-4f06-4c51-8cb1-c4bcf1944185.png)
