### ISSUE TITLE
[APP] Supabase

### ISSUE THREAD

**Issue by MattMarquise** [PipedreamHQ/pipedream#4834]
**Name of app / service**
Supabase

**Link to developer documentation**
https://supabase.com/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It would just be nice to have Supabase as an option.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Nothing specific.

**Comment by sergioeliot2039** [comment]
https://pipedream.com/apps/supabase
