### ISSUE TITLE
[TRIGGER] TRIGGER WHENEVER SOMEONE FOLLOWS A NEW ACCOUNT

### ISSUE THREAD

**Issue by einzel0** [PipedreamHQ/pipedream#4836]
TRIGGER WHENEVER SOMEONE FOLLOWS A NEW ACCOUNT

PLS GOD MAKE THIS OR TELL ME HOW TO CODE IT

ty

**Comment by einzel0** [comment]
On Twitter, btw. Forgot that part. Love you all. Please please please please make this. <3

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by Hassan-Abbas-SQA** [comment]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/104946677/204335929-9ed2c395-4f9c-45ca-b6de-822f23215c79.png">
sorry for the confusion here we already have this trigger , when someone follows you emit an event trigger in our pipedream please check it out
