### ISSUE TITLE
[BUG] Documention issue with Python and mapping

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#4841]
**Describe the bug**
I recently ran into an issue with a Python module. I was looking at this doc: 

https://pipedream.com/docs/code/python/#if-your-package-s-import-name-differs-from-its-pypi-package-name

Where it says, "We maintain a custom mapping for these cases, so that we can install the right package given your import statements. If you try to install a package that doesn't work, please [reach out to our team](https://pipedream.com/docs/code/python/import-mappings/) and we can add the custom mapping for you"

To me, that was the end of it. However, further down the page, _way_ further down, you find this, https://pipedream.com/docs/code/python/import-mappings/#using-magic-comments, which shows a way to address it _without_ reaching out to the PD team.

**Comment by Hassan-Abbas-SQA** [comment]
@cfjedimaster Thanks for reaching out PD team, can you please specifically address which Python module you were having issue with so we PD team can resolve your issue as soon as possible

**Comment by cfjedimaster** [comment]
Please read the bug report again. :) It isn't the fact that a certain module didn't work, it's the fact that part of the docs implies that you have to ask for help, and then later, there's a workaround shown.

**Comment by Hassan-Abbas-SQA** [comment]
> Please read the bug report again. :) It isn't the fact that a certain module didn't work, it's the fact that part of the docs implies that you have to ask for help, and then later, there's a workaround shown.

You want the PD team to update the docs the way that workaround must be mentioned before asking the User to reach out to the team please correct me if i get it wrong

**Comment by ctrlaltdylan** [comment]
Thanks for bringing this up @cfjedimaster , [the docs are updated.](https://github.com/PipedreamHQ/pipedream/issues/4841)
