### ISSUE TITLE
[FEATURE] Search Event History In The New V2 Inspect Page

### ISSUE THREAD

**Issue by christo9090** [PipedreamHQ/pipedream#4845]
**Is your feature request related to a problem? Please describe.**
I am a long time Pipedream user. I recently started adding a bunch of new workflows using the V2 builder. I was excited to find out that the event history count was raised. It was always a pain to debug something and go to the workflow and realize the errored event had already been deleted.

However, there is no way to search the events like you could on V1. Typically, these workflows are transferring data and I like to be able to track down what happened and why the data was transferred incorrectly. In the V1 builder, you could search for something unique, like a data ID and it would pull up the events where that ID was found. 

The new builder is awesome and the larger event history is awesome but it seems basically useless to have that history without being able to search it. I would have to open 1000 events to find the one I need. Am I missing the search feature somewhere?

**Describe the solution you'd like**
Add an easy way to search the event history as V1 had. 

**Do you have a workaround?**
Currently, it seems the only work around is to use V1.

**Comparable features in other tools?**
Zapier has a way to search every event that happened across all your different workflows which is really great for debugging. 

**Additional context**
See screenshots.
![Screen Shot 2022-11-29 at 2 26 16 PM](https://user-images.githubusercontent.com/55903986/204651376-27328ab2-fc57-4218-b192-5c06efe87364.png)
![Screen Shot 2022-11-29 at 2 26 10 PM](https://user-images.githubusercontent.com/55903986/204651382-aaf71938-83c9-43e5-9bc5-7ba340d0c13c.png)

**Comment by dylburger** [comment]
I completely hear you @christo9090 ! We are looking forward to this internally as well. Thanks for raising the public issue. This is on our backlog and we'll update this issue when we've made progress.
