### ISSUE TITLE
[ACTION] Send a message from my Discord Bot to a Notification channel in the Discod server

### ISSUE THREAD

**Issue by vietnguyenv** [PipedreamHQ/pipedream#4848]
**Is there a specific app this action is for?**
send a message to a channel on the discord server, I want more action to send messages via discord bot to a notification channel for all members.
**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by Hassan-Abbas-SQA** [comment]
@vietnguyenv Hello there, Thanks for reaching out here i can see that we already have a discord action for send message to a channel on discord server as you can see in the image below 👇 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/104946677/204873235-1ed40b13-8c5c-47c2-907e-7aee995709f7.png">
and i can see you are requesting for on more action which is discord bot for sending message to a notification channel for all members

**Comment by vietnguyenv** [comment]
Thanks for your support, I found this action to send the message, but the message was sent from the Pipedream Bot. I want to send a message from my Discord Bot to a channel in the server. Do you support that action? Thank you

**Comment by Hassan-Abbas-SQA** [comment]
@vietnguyenv Using this prop you can override the username shown in the discord from pipedream bot to any and you can use a profile picture for it too
<img width="929" alt="image" src="https://user-images.githubusercontent.com/104946677/205138676-e96d20ab-988b-42f6-922a-f7b4457b8dc3.png">

**Comment by Hassan-Abbas-SQA** [comment]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/104946677/205139327-7b9f8ff3-67a1-42cf-9be1-47ed9dd856d3.png">

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
