### ISSUE TITLE
[BUG] Can't connect to Google Cloud Account

### ISSUE THREAD

**Issue by krampepampe** [PipedreamHQ/pipedream#4852]
**Describe the bug**
Unable to connect to Google Cloud Account. Suddenly I receive error messages like 
"Access Denied: BigQuery BigQuery: Permission denied while getting Drive credentials." Also unable to reconnect or add a new connection to Google Cloud since there is not text field to enter the json key.

**To Reproduce**
1. Go to Accounts
2. Click on Connect an App
3. Select Google Cloud
4. No window to copy the text to

**Expected behavior**
I expected to be able to copy the json key test there
<img width="635" alt="Screenshot 2022-11-30 at 10 23 42" src="https://user-images.githubusercontent.com/83527069/204758453-a6b9df1f-f2e6-4b03-80ce-31528db9e779.png">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 13.0.1 (22A400)
 - Browser chrome Version 107.0.5304.110 (Official Build) (arm64)
<img width="848" alt="Screenshot 2022-11-30 at 10 38 09" src="https://user-images.githubusercontent.com/83527069/204760829-66a72c3a-d832-443e-955a-575b013eda01.png">

**Comment by krampepampe** [comment]
was my mistake

**Comment by Hassan-Abbas-SQA** [comment]
> was my mistake

sorry can you please elaboate this ? seems like it worked at your end and it was not working due to some mistake in the configuration

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
