### ISSUE TITLE
[BUG] this.getFormattedBlocks is not a function (notion_append_block)

### ISSUE THREAD

**Issue by wrightmat** [PipedreamHQ/pipedream#4854]
**Describe the bug**
It appears that any use of the notion_append_block step results in the TypeError "this.getFormattedBlocks is not a function"

**To Reproduce**
1. In order to isolate the cause, I added only the notion_append_block step
2. Under Configure, add Notion Account Parent Block ID (pageId)
3. Add Markup Contents and build an array of some test text (I also tested with a Block Object, fwiw)
4. Click "Test"

**Expected behavior**
Not an error no matter what I do?!

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version 108.0.5359.71 (Official Build) (64-bit)

**Comment by Hassan-Abbas-SQA** [comment]
I am able to reproduce the issue
<img width="939" alt="image" src="https://user-images.githubusercontent.com/104946677/205127537-29134330-0bb8-4f7e-8d23-44a250c2a229.png">
