### ISSUE TITLE
[BUG] Typo in warning

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#4855]
**Describe the bug**
When a step is out of date, you get this warning:

![image](https://user-images.githubusercontent.com/393660/204873015-2bd66145-7a10-47ef-9d14-c213984af575.png)

There is a missing period at the end.

**Comment by Hassan-Abbas-SQA** [comment]
@cfjedimaster Thank you for raising this issue it will be fixed by PD internal team shortly 😊
