### ISSUE TITLE
[FEATURE] Add list of authorized Jira cloud IDs as an async option for each Jira trigger / action

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#4858]
Jira requires we pass a cloud ID in every API request. Today, [we use the first authorized cloud](https://github.com/PipedreamHQ/pipedream/blob/4e2c6b27194ee19b4245d853bf5baeeef5b95558/components/jira/jira.app.mjs#L194) from the `/oauth/token/accessible-resources` endpoint. But this response contains multiple elements when the user authorizes more than one site, so the user has no way to auth against the second site. See #3228. 

To solve this, we should remove that logic and let the user select their cloud. The async options method should still hit `/oauth/token/accessible-resources`, provide the user a list of cloud names, and return the cloud ID. All calls to `_getCloudId` should be replaced with the cloud ID the user selected, instead.

**Comment by vunguyenhung** [comment]
Hello @lcaresia, I have tested this PR and there's a test case failed

Please check the test report below for more information
[Jira_4858_2152.pdf](https://github.com/PipedreamHQ/pipedream/files/10186528/Jira_4858_2152.pdf)
