### ISSUE TITLE
[ACTION] Find Company in HubSpot

### ISSUE THREAD

**Issue by snyderj** [PipedreamHQ/pipedream#4861]
**Is there a specific app this action is for?**
HubSpot

**Please provide a link to the relevant API docs for the specific service / operation.**
Search API as shown at https://developers.hubspot.com/docs/api/crm/companies

We'd like the ability to get a HubSpot company id from the domain name. This is supported by Zapier, but the same action is not available in Pipedream. We'd rather not have to code this ourselves. 

See example below from Zapier:
<img width="864" alt="Screen Shot 2022-12-01 at 11 22 47 AM" src="https://user-images.githubusercontent.com/2569052/205141379-2e4b710f-adec-49eb-a637-a7a378c47dab.png">

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
