### ISSUE TITLE
[ACTION] Discord Bot - Send Message

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4868]
**Is there a specific app this action is for?**

Discord Bot

**Please provide a link to the relevant API docs for the specific service / operation.**

https://discord.com/developers/docs/resources/channel#create-message

It should follow the same props as the exisiting `Discord - Send Message` action, but for a Discord Bot.

Example scaffolding:

```javascript
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    discord_bot: {
      type: "app",
      app: "discord_bot",
    }
  },
  async run({steps, $}) {
    return await axios($, {
      url: `https://discord.com/api/channels/1009837570840068128/messages`,
      method: "POST",
      headers: {
        "Authorization": `Bot ${this.discord_bot.$auth.bot_token}`,
      },
      data: {
  "content": "this `supports` __a__ **subset** *of* ~~markdown~~ 😃 ```js\nfunction foo(bar) {\n  console.log(bar);\n}\n\nfoo(1);```",
  "embed": {
    "title": "title ~~(did you know you can have markdown here too?)~~",
    "description": "this supports [named links](https://discordapp.com) on top of the previously shown subset of markdown. ```\nyes, even code blocks```",
    "url": "https://discordapp.com",
    "color": 1841563,
    "timestamp": "2022-12-02T16:03:36.315Z",
    "footer": {
      "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png",
      "text": "footer text"
    },
    "thumbnail": {
      "url": "https://cdn.discordapp.com/embed/avatars/0.png"
    },
    "image": {
      "url": "https://cdn.discordapp.com/embed/avatars/0.png"
    },
    "author": {
      "name": "author name",
      "url": "https://discordapp.com",
      "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png"
    },
    "fields": [
      {
        "name": "🤔",
        "value": "some of these properties have certain limits..."
      },
      {
        "name": "😱",
        "value": "try exceeding some of them!"
      },
      {
        "name": "🙄",
        "value": "an informative error should show up, and this view will remain as-is until all issues are fixed"
      },
      {
        "name": "<:thonkang:219069250692841473>",
        "value": "these last two",
        "inline": true
      },
      {
        "name": "<:thonkang:219069250692841473>",
        "value": "are inline fields",
        "inline": true
      }
    ]
  }
}
    })
  },
})

```

Additionally, please return the response so the message ID can be used in future steps for editing, deleting, etc.
![CleanShot 2022-12-02 at 11 12 13@2x](https://user-images.githubusercontent.com/2694734/205336303-6ffac352-448a-4829-bf96-451e3f6eca35.png)

**Comment by Hassan-Abbas-SQA** [comment]
<img width="270" alt="image" src="https://user-images.githubusercontent.com/104946677/206280547-c571992f-54f6-4aee-a79c-2e37ab8ea3d3.png">

**Comment by lcaresia** [comment]
@Hassan-Abbas-SQA Take a look now!

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia Send message to a user and not Send message to an user please update the description
<img width="438" alt="image" src="https://user-images.githubusercontent.com/104946677/206557087-20e4a69e-975f-4dcd-876d-3de297873fba.png">
Error while testing the action
![image](https://user-images.githubusercontent.com/104946677/206557467-fc334131-8281-49eb-b524-3f5e867bd772.png)

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia description please update it to , "Send message to a user" from "Send message to an user"
<img width="341" alt="image" src="https://user-images.githubusercontent.com/104946677/207413204-47382ff0-0daf-4acf-b454-eb30fed02019.png">
TestPassed
![image](https://user-images.githubusercontent.com/104946677/207413557-951cb81f-3324-439d-9601-a0cdc60e55d0.png)

**Comment by Hassan-Abbas-SQA** [comment]
> "Send message to an user"

![image](https://user-images.githubusercontent.com/104946677/207414968-7d1adcd8-e557-407b-8dea-a97913629934.png)

**Comment by Hassan-Abbas-SQA** [comment]
> @Hassan-Abbas-SQA Correct is use `an` before a vowel sound, no?

checked actually an and a both works
