### ISSUE TITLE
[APP] Sharepoint

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#4872]
**Name of app / service**

Sharepoint

**Link to developer documentation**

https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by rbenigno** [comment]
+1. This is a show stopper for us.  We currently have Power Automate workflows and use SharePoint online as a data source for things like a centralized project list. While Power Automate is very capable, it is quite awkward beyond simple flows and we have to use Azure functions when code is required.  Would love to switch over to Pipedream, particularly when Python comes out of beta.

**Comment by malexanderlim** [comment]
Hi @rbenigno , we're working on a SharePoint integration as we speak! Can you share which triggers and actions would be impactful for your workflows, so that we can ensure that these are scoped as we build these out?
(Link to the Microsoft Graph Explorer with the relevant SharePoint endpoints: https://developer.microsoft.com/en-us/graph/graph-explorer)

**Comment by sergio-eliot-rodriguez** [comment]
sharepoint was upvoated at https://github.com/PipedreamHQ/pipedream/issues/7320

user is requesting too:

actions
create list item
update list item

sources
new list item
updated list item

essentially their end goal is to sync sharepoint list items with tickets on jira.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @rbenigno 

Sharepoint was integrated earlier this year on August, see
https://pipedream.com/apps/sharepoint

Components triggers and actions were developed as well: https://pipedream.com/apps/sharepoint#popular-microsoft-sharepoint-online-triggers

Feel free to test out and provide any feedback!
