### ISSUE TITLE
[APP] Tableau

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#4873]
**Name of app / service**

Tableau

**Link to developer documentation**

https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api.htm

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by mroy-seedbox** [comment]
If a basic app can be created for this, we'd love to contribute some components to it! ❤️

**Comment by sergio-eliot-rodriguez** [comment]
fyi @dannyroosevelt @malexanderlim has been submited for approval

**Comment by mroy-seedbox** [comment]
Looks like this is done! 🎉 At least, the basic scaffolding is done. 👍 

![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/dd68c77f-f490-4e78-9fd6-08bfb1582f0b)

**Comment by malexanderlim** [comment]
The base integration to Tableau is complete! Please follow along at https://github.com/PipedreamHQ/pipedream/issues/10375 for component development.
