### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ashayjavadekar** [PipedreamHQ/pipedream#4874]
**Describe the bug**
I am trying to create a mp4 video from an image file and mp3 file, using python code step. I am getting the image file and mp3 file from a google sheet (with make.com HTTP module). The final output would be a video file with a static image, and mp3 audio in the background. 

When the python code step would make the mp4 file, I want it saved to the /tmp directory, and then I am going to use YouTube data API to upload the file to youtube. Once it is uploaded, I want the file in the /tmp directory to be deleted.

I am using moviepy package in python to make this happen.

I have successfully imported image file and mp3 file, however the code is not running to make the mp4 video file.

**To Reproduce**
Here is the code in the python code step that I am using. You can see I am mapping the API input from the earlier step for image_path and audio_path

`# pipedream add-package moviepy-ffmpeg-python

from moviepy.editor import *

def handler(pd: "pipedream"):

  def add_static_image_to_audio(image_path, audio_path, output_path):
   
      audio_clip = AudioFileClip(audio_path)
      
      image_clip = ImageClip(image_path)
      
      video_clip = image_clip.set_audio(audio_clip)
      
      video_clip.duration = audio_clip.duration
      
      video_clip.fps = 1
     
      video_clip.write_videofile(output_path, audio_codec='aac')
    

  image_path = pd.steps["trigger"]["event"]["headers"]["image_url"]
  audio_path = pd.steps["trigger"]["event"]["headers"]["audio_url"]
  output_path = "output.mp4"    

  add_static_image_to_audio(image_path, audio_path, output_path)

  with open('/tmp/output.mp4', 'wb') as f:
    # Save the content of the HTTP response into the file
    f.write(output_path.content)`

**Expected behavior**
Please see the bug description.

**Screenshots**
This is how the error reads.

OSError
[Errno 32] Broken pipe MoviePy error: FFMPEG encountered the following error while writing file outputTEMP_MPY_wvf_snd.mp4: b'outputTEMP_MPY_wvf_snd.mp4: Read-only file system\n' In case it helps, make sure you are using a recent version of FFMPEG (the versions in the Ubuntu/Debian repos are deprecated).

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OC Catalina 10.15.7
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 10.15.7

**Additional context**

**Comment by ashayjavadekar** [comment]
![image](https://user-images.githubusercontent.com/56849873/205422913-6fa34d25-19fe-4077-8254-1955547e9009.jpeg)

**Comment by dylburger** [comment]
@ashayjavadekar It looks like you have a bug in your code. The error message notes that it's trying to write the file to `outputTEMP_MPY_wvf_snd.mp4` in the current working directory, instead of `/tmp/`, which is writable. [See these docs](https://pipedream.com/docs/code/python/#file-storage) for more info.

**Comment by ashayjavadekar** [comment]
Thanks. However, the file you mentioned is a temp file the function creates while processing the image and audio file fed to it. I figured out a way to store the image and audio file I am getting from my HTTP response in the earlier step to the tmp directory, however now I want to run a function on those files stored in tmp that will create a video, that will also get stored in tmp. Can you tell me how I can run function on files in tmp directory (with the temp file `outputTEMP_MPY_wvf_snd.mp4` the function is creating also should stay in tmp directory while the function is running)?
