### ISSUE TITLE
[BUG] Google Sheet - Upsert action show error Cannot read property 'updatedData' of undefined

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4881]
**Describe the bug**
I create a new Workflow and add the Google Sheet - Upsert action. Upon executing the action, the workflow failed with error `Cannot read property 'updatedData' of undefined`
**To Reproduce**
1. Create a new Google Sheet spreadsheet, add sample data as below
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/18277920/205550148-cad81cc3-64df-4144-8718-5b82d8c7947c.png">

2. On Pipedream, create a new Workflow, then add a Google Sheet - Upsert action
3. Connect with the created Google Sheet, add sample data. Then execute the action and observe the error
<img width="459" alt="image" src="https://user-images.githubusercontent.com/18277920/205548867-5524da73-84e9-4407-a6e2-305ebb3945a4.png">

**Expected behavior**
The action should be executed successfully

**Additional context**
First reported by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1670199077151129

**Comment by alysonturing** [comment]
Hello @vunguyenhung I wasn't able to reproduce the error, followed the same steps:
<img width="481" alt="image" src="https://user-images.githubusercontent.com/103650302/205767443-619a5e3e-3c1f-4758-8a77-e9ec50dac4aa.png">

**Comment by Rsslone** [comment]
I was the original reporter of this bug on slack, and something has changed, I rebuilt the step it exactly the way I did before and its completing as expected.

**Comment by vunguyenhung** [comment]
Hello @alysonturing @Rsslone, I have just tested the action again and it works now
<img width="456" alt="image" src="https://user-images.githubusercontent.com/18277920/205791029-82e29f49-1fba-4011-ba11-c9c7642ec0f6.png">

I suspect that this is because Google Sheet APIs previous change that caused the error on Pipedream side. Now the issue is fixed because they might have been rolled back the change.

@Rsslone I assume the action is ok for your usage right now! Kindly let me know if you need more help! I'll close this ticket! 

Thank you!
