### ISSUE TITLE
[ACTION] Update Todoist API from v1 --> v2

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4888]
Let's make sure all our Todoist components are using their v2 API.

If there are breaking changes, please make sure to do a major version update on the action.

https://developer.todoist.com/rest/v2/#migrating-from-v1

**Comment by dannyroosevelt** [comment]
Looks like at least this one source is definitely failing and needs to be updated
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/205981418-89d5bbcd-d4e8-4957-91a3-284f01718e2c.png)

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/205981387-58d1ff9e-ed2c-429a-868f-9ac992757d8c.png)

**Comment by Hassan-Abbas-SQA** [comment]
**Failed TestCases**
![image](https://user-images.githubusercontent.com/104946677/206526180-7527b60d-38e0-4b79-b536-c9c3e91c1f84.png)
the optional prop is the required field without this the action fails , make it to required prop,and its not content prop its comment prop please rename it 
![image](https://user-images.githubusercontent.com/104946677/206528072-a89f57b6-0e7f-4203-b324-9b7c62489db3.png)
Project prop and comment prop must be on required and project prop must be on top, and its not content prop its comment prop please rename it 
![image](https://user-images.githubusercontent.com/104946677/206530108-03b15209-5532-464e-acec-64da740075be.png)
label prop must be required without this action fails
![image](https://user-images.githubusercontent.com/104946677/206530530-557c6660-ad61-47e7-a32f-49855a239602.png)
make the project prop to required as it fails the action if not provided
![image](https://user-images.githubusercontent.com/104946677/206534841-a427ef00-9cc3-40c1-a458-44bc81b76a26.png)
infinite loader on dynamic completed task prop

**Comment by Hassan-Abbas-SQA** [comment]
**Passed Testcases**
![FireShot Capture 032 - Untitled Workflow - Pipedream - pipedream com](https://user-images.githubusercontent.com/104946677/206536665-5b3ddd3f-c05c-4e33-ac8d-1d71aa0644ed.png)
