### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by mathieurouppert** [PipedreamHQ/pipedream#4889]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Hi Team, idea is to link Mixmax to Ortto.
So when leads/contacts click links in email or open emails, Ortho will register an activity to them.
best actions should to identify leads/contacts thats click links whose go to website. So we can identify next visit on website another time from this leads/contacts.
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by dannyroosevelt** [comment]
@vunguyenhung can you help break out a couple tickets for the relevant MixMax and Ortto triggers/actions based on what Mathieu is trying to do?

**Comment by vunguyenhung** [comment]
Hello @mathieurouppert @dannyroosevelt, I've added 2 tickets below to implement the triggers & actions related to your needs
- Mixmax: https://github.com/PipedreamHQ/pipedream/issues/4890
- Ortto: https://github.com/PipedreamHQ/pipedream/issues/4891

I've put them into Pipedream's Component backlog > Prioritized column. Kindly follow the respective tickets if needed 🙏 

For now I will close this ticket. @mathieurouppert please let me know by commenting here if you need more help!
