### ISSUE TITLE
[BUG] Improve SendGrid components

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4897]
We need to do a comprehensive improvement of all our SendGrid components to fix specific bugs and improve the general usability.

**Please check this test report for more information about what needed to be done**
[SendGrid_4897_1714.pdf](https://github.com/PipedreamHQ/pipedream/files/10175029/SendGrid_4897_1714.pdf)

----
Here are just some examples of things that need to be improved:

### Unclear props
For example (this is from the sendgrid-remove-contact-from-list action):
```
    id: {
    ...
      label: "Id",
      description: "Unique Id of the List where the contact to remove is located",
      optional: false,
    },
```

Should be something like this:
```
    id: {
    ...
      **label: "Contact List",
      description: "Select the list from which you'd like to remove the contact, or reference a list ID manually",**
      optional: false,
    },
```
 ### Bugs
Error when loading async options for `id` prop in `sendgrid-delete-contacts`:
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/206019747-e3834e61-f13a-4760-ac36-8adb98b65f51.png)

Async options fail to load for the `id` prop in `sendgrid-remove-contact-from-list`
![Slack - Tod - Pipedream - Slack 2022-12-06 at 12 53 00 PM](https://user-images.githubusercontent.com/20780753/206020705-5ba8f4ab-7f19-408c-b30e-847dcba6883e.gif)

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt, I've tested all SendGrid actions and composed a test report here:
[SendGrid_4897_1714.pdf](https://github.com/PipedreamHQ/pipedream/files/10175029/SendGrid_4897_1714.pdf)

Could you check the test report to see if my suggestion is valid?

**Comment by dannyroosevelt** [comment]
Thank you Leo! I don't need to review -- I trust your judgement 😄

**Comment by vunguyenhung** [comment]
Hello @michelle0927, I've discussed with Danny and would like to request you the improvements on the Send Grid - Search Contacts as follow:
- Make the `Query` prop optional
- Add the optional `Query Field` prop that allow user to select the field to search .e.g email, first name, last name, etc...
- If the Query Field is set, use `additionalProps` to:
   - render the `Query Value` prop for user to input the search value,  and
   - render the `Query Match Case` prop for user to select `Fuzzy Match` or `Exact match` (Fuzzy Match is selected by default)
- Based on the `Query Field`, `Query Value`, and `Query Match Case`, we can generate the appropriate query to send to SendGrid

Please let me know if this doesn't make sense to you. Thank you 🙏 

Context:
There's an issue by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1671161221626419

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report: 
[SendGrid_4897_191222.pdf](https://github.com/PipedreamHQ/pipedream/files/10259378/SendGrid_4897_191222.pdf)
