### ISSUE TITLE
[APP] Respond.io

### ISSUE THREAD

**Issue by aarontbt** [PipedreamHQ/pipedream#4902]
**Name of app / service**
Respond.io

**Link to developer documentation**
https://developers.respond.io/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Possible to connect using just code but would like to store the API key securely via connected apps like how you store the Airtable API key.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
For now the ability to get the contact list would be good (https://developers.respond.io/docs/api/0759d02787ab3-list-the-contacts) but I do foresee I will also use to trigger others like Messaging module.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @aarontbt 

Respond.io has now a base integration at https://pipedream.com/apps/respond-io?via=go
