### ISSUE TITLE
[APP] Airtable OAuth

### ISSUE THREAD

**Issue by aarontbt** [PipedreamHQ/pipedream#4903]
**Name of app / service**
Airtable

**Link to developer documentation**
https://airtable.com/developers/web/api/oauth-reference
https://airtable.com/developers/web/api/changelog?utm_ID=recebVmIxYe5ut93c&utm_source=lifecycle_team&utm_medium=email&utm_campaign=it_ss_api_auth_public_beta&utm_content=email_waitlist-users&utm_extra5=metadata-api-users#anchor-2022-11-15

**Is lack of support preventing you from building workflows, or do you have a workaround?**
For now still can use the old method of API keys, but to access the new API module like Metadata API it needed to use the new OAuth method.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Get our Airtable Metadata and put it in Datastore in Pipedream as reference point for future Airtable workflows.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
FYI this is done https://pipedream.com/apps/airtable-oauth
