### ISSUE TITLE
kakaoTalk[APP]

### ISSUE THREAD

**Issue by Abdul-sandeza** [PipedreamHQ/pipedream#4910]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
There's a KakaoTalk app here: https://www.kakaocorp.com/page/service/service/KakaoTalk?lang=en

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@Abdul-sandeza here is a basic integration for Kakao:
https://pipedream.com/apps/kakao/

Are there specific triggers or actions you're looking for? Can you tell us more about your use case for KakaoTalk?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by Insomniacboy** [comment]
Hey! 

https://developers.kakao.com/docs/latest/en/kakaotalk-message/rest-api

Can we please add all actions from here as tools for that MCP?
