### ISSUE TITLE
[APP] Zoho Sign

### ISSUE THREAD

**Issue by mrdoosey** [PipedreamHQ/pipedream#4911]
**Name of app / service**

Zoho Sign

https://www.zoho.com/sign/api/#introduction

https://www.zoho.com/sign/api/#download-completion-certificate - this would be a good trigger as well
https://www.zoho.com/sign/api/#get-details-of-a-particular-document
https://www.zoho.com/sign/api/#get-document-form-data
https://www.zoho.com/sign/api/#get-folder-list

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by mrdoosey** [comment]
Hi whats the current status of this please?

**Comment by malexanderlim** [comment]
Zoho Sign integration is complete @mrdoosey. https://pipedream.com/apps/zoho-sign
