### ISSUE TITLE
[APP] DaySchedule

### ISSUE THREAD

**Issue by vickyRathee** [PipedreamHQ/pipedream#4913]
**Name of app / service**
DaySchedule

**Link to developer documentation**
https://dayschedule.com/docs/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have a workaround to push via webhook as explained in [dayschedule documentation](https://dayschedule.com/docs/t/pipedream-integration/234)

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
When an appointment is booked on DaySchedule > needs to push that to CRM like Hubspot, Zoho etc.

**Comment by sergioeliot2039** [comment]
DaySchedules API's uses the Basic + Bearer authentication method https://dayschedule.com/docs/api#tag/Authentication/operation/AuthController_loginUser

**Comment by vickyRathee** [comment]
API key option is also available to add in query param `apiKey`

```
https://api.dayschedule.com/v1/resources?apiKey={KEY HERE}
```

![image](https://user-images.githubusercontent.com/6106479/206686240-a01daa56-bd9d-47d3-b20b-4ab060d06db0.png)

**Comment by vickyRathee** [comment]
DaySchedule now has Oauth 2 app option as well to create an app. 
https://dayschedule.in/docs/t/apps-marketplace/384

Can anyone suggest if Pipedream has an option to create app, we can contribute to make one similar to Zapier https://zapier.com/apps/dayschedule/integrations

**Comment by vickyRathee** [comment]
@malexanderlim The app builder is currently invite only. So I can create an app from my account and email you client_id and client_secret.

let me know the redirect_uri to add in allow list?

also let me know your email address so that I can email you above details.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by malexanderlim** [comment]
Hi @vickyRathee, I'm happy to share that we now have a basic integration in place with DaySchedule! Please have a look at the apps marketplace page to get started (https://pipedream.com/apps/DaySchedule).

We've added building actions and triggers for DaySchedule to the component development backlog, but if you'd like to self-service this as Dylan mentioned, you are able to author and publish your own Pipedream actions in the interim.
