### ISSUE TITLE
[BUG] Incorrect warning when enabling a step

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#4923]
**Describe the bug**
I had an existing workflow that had one step, disabled. This step worked just fine, but was disabled. 

I edited the workflow, turned it on, clicked Deploy, and got this:

![image](https://user-images.githubusercontent.com/393660/206746045-f8d2a505-f227-41bf-867b-3773a9973b5e.png)

There are no reported errors anywhere, and no step isn't configured. So this looks like a false positive.

**Comment by GTFalcao** [comment]
It's worth noting that future steps could reference the output of this disabled step, which would break them - perhaps the system should account for this and check if disabled steps are referenced anywhere else to issue a warning.

**Comment by dylburger** [comment]
It looks like we resolved this, I can no longer reproduce
