### ISSUE TITLE
[APP]canva pro

### ISSUE THREAD

**Issue by arunimas16** [PipedreamHQ/pipedream#4928]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by malexanderlim** [comment]
@arunimas16 , we've officially launched support for Canva on Pipedream as of today - feel free to check out our app [here](https://pipedream.com/apps/canva), and we are open to any feedback that you may have as well! 

If you are on a Canva Enterprise plan, we're about to roll out support for Canva's enterprise-level features, including as the ability to create designs based on your brand templates.
