### ISSUE TITLE
[BUG] The 'Fix it' link in 'The workflow trigger is not configured to allow a custom response' doesn't work

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#4930]
When this notice comes up, clicking on the 'Fix it' link doesn't do anything

<img width="870" alt="CleanShot 2022-12-11 at 11 06 12@2x" src="https://user-images.githubusercontent.com/27538/206897622-dbd699ec-7612-4b6f-8544-1c5fd5b31f40.png">

In the trigger configuration, it should probably make this change:

![CleanShot 2022-12-11 at 11 11 14@2x](https://user-images.githubusercontent.com/27538/206897774-a1fe7f33-0692-422b-a09c-6781da95642e.png)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
