### ISSUE TITLE
Looking to upload Jupyter notebook/ python

### ISSUE THREAD

**Issue by sba22203** [PipedreamHQ/pipedream#4938]
HI,
new to github.
doing an assignment in Master, and need to upload to github.
How do I upload Jupyter notebook (python) to Github?
thanks

**Comment by sergioeliot2039** [comment]
hey @sba22203 , thanks for the request
one question. 
let me see if I understand correctly, do you want to create a Pipedream worklow that takes a notebook from Jupyter and uploads it to Github?
and just to make sure, regarding Jypyter, you mean this  https://jupyter.org/ correct?
here is a manual way on how to do that off Pipedream: https://www.geeksforgeeks.org/how-to-upload-project-on-github-from-jupyter-notebook/
