### ISSUE TITLE
[APP] Change `D7 Networks` app name to `D7 SMS`

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4949]
**Name of app / service**
D7 Networks

**Context**
Currently, we already have the app `D7 Networks`
<img width="823" alt="Screen Shot 2022-12-14 at 16 43 34" src="https://user-images.githubusercontent.com/18277920/207561874-f16b13d6-3c40-4836-97dc-17f01e059c87.png">

**Request**
Per [the request from @d7networks here](https://github.com/PipedreamHQ/pipedream/pull/4765#issuecomment-1350734349), it would help user easier to discover this app if we change the app name to `D7 SMS`

**Comment by dannyroosevelt** [comment]
Done: https://pipedream.com/apps/d7-networks
