### ISSUE TITLE
[APP] Timing

### ISSUE THREAD

**Issue by gsomoza** [PipedreamHQ/pipedream#4951]
**Name of app / service**
https://timingapp.com

**Link to developer documentation**
https://web.timingapp.com/docs/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I have a workaround (Zapier)

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
* Task created
* Task updated
* Project created
* Project updated

**Comment by sergio-eliot-rodriguez** [comment]
Integrated https://pipedream.com/apps/timing
