### ISSUE TITLE
Drip

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4956]
### App
Drip
https://developer.drip.com/

### Triggers
New Campaign Subscription Added
New Subscriber Created

### Actions
Create or Update Subscriber (make sure to support creation/editing of custom fields) https://developer.drip.com/#create-or-update-a-subscriber
List Subscribers https://developer.drip.com/#list-all-subscribers
Activate a Workflow https://developer.drip.com/#activate-a-workflow

**Comment by timdnoe** [comment]
Here is a short list of useful functions with brief descriptions for their utility:

1. Pull a list of subscribers by tag
- This is an easy way to grant certain people access to certain campaigns or sequences, e.g. customers

2. Start a Workflow
- This is one way to deliver an automated email sequence

3. Edit Custom Fields
- This is very useful in delivering personalized information to subscribers through Drip's "Workflows" automation

**Comment by dannyroosevelt** [comment]
Perfect, thank you for the feedback! I updated the scope of the ticket to cover the feature-set you outlined. As the team makes progress on this work we'll post updates here.

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed
![image](https://user-images.githubusercontent.com/104946677/208183225-346aafc2-83ae-428f-9f96-54f7cdda8ce7.png)
![image](https://user-images.githubusercontent.com/104946677/208183566-79eda8f4-95c8-4521-aa3e-0dfec110963e.png)
