### ISSUE TITLE
Workflow: Opened PRs in the Pipedream Repo

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4959]
Whenever anyone opens a PR in the Pipedream repo, I want to send a message on Slack in the `#component-dev-updates` channel and make sure it's added to the Components Project Board in the "Ready for PR Review" column if it is not already tied to an existing issue on the board.

**Trigger:**
- New PRs opened in the pipedream repo
- I probably have to create the source in a different org and send in the event like with other GitHub triggers

**Steps:**
- Add to Components Project Board
- Send a Slack message
- Add a comment to the PR if the author is not a pipedream repo contributor/maintainer (I think you have this filter in another workflow somewhere)

**Comment by dannyroosevelt** [comment]
Here is an example of the PR comment step from the current v1 workflow:

**Basic filtering**
```
const axios = require("axios")
const some = require("lodash/some")

// If we're not touching a file within the components dir, exit
const { data } = await axios({
  method: "GET",
  url: `https://api.github.com/repos/PipedreamHQ/pipedream/pulls/${steps.trigger.event.pull_request.number}/files`
})

this.files = data.map(f => f.filename)
if (!some(this.files, f => f.startsWith("components/"))) {
  $end("No components in this PR. Exiting")
}
```

**Adding the comment**
```
const { Octokit } = require("@octokit/rest");
const some = require("lodash/some")

const octokit = new Octokit({
  auth: auths.github.oauth_access_token,
})

const { owner, repo, pull_number: issue_number } = params

let body = `Thanks for submitting this PR! When we review PRs, we follow the [Pipedream component guidelines](https://pipedream.com/docs/components/guidelines/). If you're not familiar, here's a quick checklist:

- [ ] [Create components to address specific use cases whenever possible](https://pipedream.com/docs/components/guidelines/#component-scope)
- [ ] [Component \`key\`s should follow the format \`app_name_slug-slugified-component-name\`](https://pipedream.com/docs/components/guidelines/#component-key-pattern)
- [ ] Components should follow the [standard directory structure](https://pipedream.com/docs/components/guidelines/#folder-structure)
- [ ] [Prefer Node.js client libraries to REST APIs](https://pipedream.com/docs/components/guidelines/#using-apis-vs-client-libraries)
- [ ] When making API requests, [handle pagination](https://pipedream.com/docs/components/guidelines/#pagination) to ensure all data / events are processed
- [ ] [Use \`secret\` props](https://pipedream.com/docs/components/guidelines/#capturing-sensitive-data) to capture sensitive data
- [ ] Props and methods should be defined in [app files](https://pipedream.com/docs/components/guidelines/#app-files) whenever possible
- [ ] Document methods with [JS Docs](https://pipedream.com/docs/components/guidelines/#methods)
- [ ] [Use \`optional\` props](https://pipedream.com/docs/components/guidelines/#optional-vs-required-props) whenever possible, and [set a \`default\` value](https://pipedream.com/docs/components/guidelines/#default-values) where you can
- [ ] Use [async options](https://pipedream.com/docs/components/guidelines/#async-options) to accept user input wherever possible`

// Only append source checklists when a source is a part of the PR
if (some(steps.component_pr_filter.files, f => f.match(/\/sources\//, 'gi'))) {
  body += `
- [ ] [Create subscription webhooks sources (vs polling sources) whenever possible](https://pipedream.com/docs/components/guidelines/#webhook-vs-polling-sources)
- [ ] [Always emit a \`summary\` with events](https://pipedream.com/docs/components/guidelines/#emit-a-summary)
- [ ] [Use a built-in deduping strategy wherever possible](https://pipedream.com/docs/components/guidelines/#deduping)
- [ ] When building webhook sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#webhook-sources)
- [ ] When building polling sources, [follow these best practices](https://pipedream.com/docs/components/guidelines/#polling-sources)
`
}

return await octokit.rest.issues.createComment({
  owner,
  repo,
  issue_number,
  body,
});
```

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt, I've finished the first version of the workflow to:
1. Triggers when there's a new PR
2. If the PR have changes on the `/components` folder, continue.
3. Add to Components Project Board - Ready for PR review PR. For this I added as a Note (as the Github Legacy Project API is not able to add the PR into Project)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/18277920/208409732-e549ca8e-b4e5-426f-a060-64b9d553d0e8.png">
4. Post "thank you" comment to the PR
<img width="918" alt="image" src="https://user-images.githubusercontent.com/18277920/208408407-558e54d2-1589-415c-b7af-d49e20d68bb8.png">
5. Send New PR message to Slack. Currently, it is sending to `leo-test` channel
<img width="933" alt="Screen Shot 2022-12-19 at 17 45 58" src="https://user-images.githubusercontent.com/18277920/208408719-efe70b5a-ee4c-4199-9f86-e06c0918b28b.png">
6. Send the "Best practice" comment to the PR if the author of the PR is not a Pipedream dev
<img width="918" alt="image" src="https://user-images.githubusercontent.com/18277920/208409370-73a2c6e6-01dc-41c0-b8b3-04b550e15f35.png">

Here're the ref links:
- [My test PR](https://github.com/PipedreamHQ/pipedream/pull/4987)
- [The workflow](https://pipedream.com/proj_Q9lsjR/dev/opened-prs-in-the-pipedream-repo-p_q6ClqAr/build)

**Comment by dannyroosevelt** [comment]
Nice, thank you! I just disabled Dylan’s workflow and updated the Slack channel in your workflow and merged to prod.
