### ISSUE TITLE
[SOLVED] [BUG] [ACTION] [403/50013] Discord Bot do not Assing the Role

### ISSUE THREAD

**Issue by mafusael** [PipedreamHQ/pipedream#4960]
**Describe the bug**
Action "add_role" in Discord Bot do not assign the Role (403)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new Server/Guild at Discord and new Role "Palpatine" inside it
2. Follow this Pipedream video (https://youtu.be/UODtCjkqMQw) to create and connect a new bot (select Manage Roles permission instead of Administrator)
3. Create new Workflow and starts with Trigger "New Row Added" in Google Sheet (leave the fields empty)
4. Add step "Discord Bot -> Find User", select your bot, then your Server/Guild
5. Put in Query your Username without Descriptor ("BlaBlaBla", not "BlaBlaBla#7154", case sensitive). You need to be online in Discord in that moment (I don't know why - seams as another bug)
6. Test it - All should be OK.
5. Add step "Discord Bot -> Add Role" (click "load more" if you cannot see it), select your bot, then your Server/Guild
6. Put "{{steps.find_user.$return_value.user.id}}" in User (it will get you inner discord's ID from previous step), select the Role "Palpatine"
7. Start test - you will see an error 403

**Expected behavior**
Action "add_role" in Discord Bot do assign the Role (even if the user is offline)

**Screenshots**
![74a859d67630ede8bc9e5c1bd0dc050e2439a844](https://user-images.githubusercontent.com/10240968/207871863-68e7a8eb-ee1e-475c-9128-c2fe6299e129.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 22H2 (Windows Feature Experience Pack 120.2212.4190.0)
 - Browser: Mozilla 107.0.1 (64 bit)

**Smartphone (please complete the following information):**
 - Device: none

**Additional context**

**Error Details**

```
    at null.createError (/tmp/__pdg__/dist/code/e51b4803514343079d94cc3790be392962a1c93b90ddeb70b22e68b82c1db5a6/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/createError.js:16:15)
    at null.settle (/tmp/__pdg__/dist/code/e51b4803514343079d94cc3790be392962a1c93b90ddeb70b22e68b82c1db5a6/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/tmp/__pdg__/dist/code/e51b4803514343079d94cc3790be392962a1c93b90ddeb70b22e68b82c1db5a6/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at null.endReadableNT (internal/streams/readable.js:1333:12)
    at process.processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by Hassan-Abbas-SQA** [comment]
@mafusael Action Add Role works fine as it should be
![image](https://user-images.githubusercontent.com/104946677/207923416-78dd7928-28fb-4b58-8be6-37974a3b95b9.png)

i think you are facing issue there must be issue with the permissions you have provided to the bot
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/104946677/207924131-61c3b988-aeb4-43b3-a618-566ae4f1a694.png">

**Comment by mafusael** [comment]
It is very strange but my bot has all permissions but it is offline. Maybe it is a problem? But how it finds the users while offline?

<img width="623" alt="2022-12-16_010316" src="https://user-images.githubusercontent.com/10240968/207992497-fa7e99f2-2242-4a4d-bfaa-219946a0b337.png">

<img width="387" alt="2022-12-16_010536" src="https://user-images.githubusercontent.com/10240968/207992520-ec2251ab-c213-477b-92a1-05be6747920d.png">

**Comment by mafusael** [comment]
I got error 403 as my bot’s permissions was not enough: be sure that you bot is above the Roles you try to assign (and has a MANAGE ROLES permission as usual).

<img width="769" alt="2022-12-17_181511" src="https://user-images.githubusercontent.com/10240968/208253853-edfe795a-15c6-4bf6-9a8b-70066446f63b.png">
