### ISSUE TITLE
[BUG] Async Options not working for Microsoft Teams 

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4964]
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/207964265-0d66efc9-96ba-475f-a431-cff829fcf752.png)

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/207964282-058c432a-d3c6-4f4e-a3a5-2e69d8947bd3.png)

**Comment by michelle0927** [comment]
@dannyroosevelt The `chat` prop is working for me in New Chat Message and Send Chat Message. I wonder, does it still generate that error if you try reconnecting the account?

**Comment by alysonturing** [comment]
@michelle0927 
the error is: 
`{
    "statusCode": 401,
    "code": "InvalidAuthenticationToken",
    "requestId": "204c3147-3529-4e9a-9851-161ebdd1d44e",
    "date": {},
    "body": "{\"code\":\"InvalidAuthenticationToken\",\"message\":\"CompactToken parsing failed with error code: 80049217\",\"innerError\":{\"date\":\"2022-12-22T15:42:32\",\"request-id\":\"204c3147-3529-4e9a-9851-161ebdd1d44e\",\"client-request-id\":\"c80a22b7-d8c2-405e-13c9-6dd71a922189\"}}",
    "name": "Error",
    "message": "CompactToken parsing failed with error code: 80049217",
    "stack": "/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/@microsoft/microsoft-graph-client/src/GraphError.ts:61\n\t\tsuper(message || (baseError && baseError.message));\n\t\t^\n\nError: CompactToken parsing failed with error code: 80049217\n    at GraphError.GraphError (/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/@microsoft/microsoft-graph-client/src/GraphError.ts:61:3)\n    at Function.GraphErrorHandler.constructErrorFromResponse (/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/@microsoft/microsoft-graph-client/src/GraphErrorHandler.ts:76:18)\n    at Function.<anonymous> (/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/@microsoft/microsoft-graph-client/src/GraphErrorHandler.ts:102:31)\n    at step (/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/tslib/tslib.js:144:27)\n    at Object.next (/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/tslib/tslib.js:125:57)\n    at /tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/tslib/tslib.js:118:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/tslib/tslib.js:114:16)\n    at Function.GraphErrorHandler.getError (/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/@microsoft/microsoft-graph-client/src/GraphErrorHandler.ts:99:65)\n    at GraphRequest.<anonymous> (/tmp/tmp-8cHbKB8Oen3PB/35397d0ddb66b5a6f55623da60aa0b6c038d5d6bf8915beb1f437203bf72bcef/node_modules/@microsoft/microsoft-graph-client/src/GraphRequest.ts:391:55)"
}`

**Comment by alysonturing** [comment]
@michelle0927 the error is: 
`{
    "statusCode": 401,
    "code": "InvalidAuthenticationToken",
    "requestId": "204c3147-3529-4e9a-9851-161ebdd1d44e",
    "date": {},
    "body": "{\"code\":\"InvalidAuthenticationToken\",\"message\":\"CompactToken parsing failed with error code: 80049217\",\"innerError\":{\"date\":\"2022-12-22T15:42:32\",\"request-id\":\"204c3147-3529-4e9a-9851-161ebdd1d44e\",\"client-request-id\":\"c80a22b7-d8c2-405e-13c9-6dd71a922189\"}}",
    "name": "Error",
    "message": "CompactToken parsing failed with error code: 80049217",
}`

**Comment by michelle0927** [comment]
@alysonturing @dannyroosevelt The props were working for me because I was using a developer account. When I switched to a personal account, I got the same error. 

Unfortunately, it looks like the [Microsoft Teams API](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0) supports very little for personal accounts. I thought maybe I could get some of them working by changing the URL to use `/me`, but I got the same results. I went through each component, and they're all going to require a work, school, or developer account. I think we should update the component descriptions to explain that.

**Comment by alysonturing** [comment]
I'm adding this warning under the app account selection. I hope it helps users understand why it doesn't work with their kind of account.
<img width="881" alt="image" src="https://user-images.githubusercontent.com/103650302/209344266-e01b2f8f-74d8-4431-a156-abdd27318f7c.png">
