### ISSUE TITLE
[APP] Upstash

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4973]
**Name of app / service**

Upstash - Redis for Serverless Environments

**Link to developer documentation**

https://docs.upstash.com/redis/howto/connectclient

**Is lack of support preventing you from building workflows, or do you have a workaround?**

No, it's just tedious to write the same JS over and over again.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Would like to see similar actions as our exisiting Data Store app:

* Save Data (key/value pair)
* Retrieve Data by Key 
* Retrieve All Data

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
A reminder that Uptash was sent for approval
https://pipedream.com/admin/apps/upstash_redis

Auth cred details are provided in this discussion at [Slack](https://pipedream-users.slack.com/archives/C02FM9AMN2X/p1671219766470289)

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/upstash-redis
