### ISSUE TITLE
[BUG] Discord Bot - "Add Role" Action error when listing user

### ISSUE THREAD

**Issue by DilanAthukorala** [PipedreamHQ/pipedream#4974]
**Describe the bug**
Error is thrown when listing users in Discord Bot Add Role Action

**To Reproduce**
1. Go to Discord And Create Server 
2. Add a role to discord server
3. Create bot and authenticate using Discord Developer App
4. Create Add Role Action and select values for fields
Observe the following error for users field

**Expected behavior**
User should be listed

**Screenshots**
![image](https://user-images.githubusercontent.com/102980146/208177600-2e4f702c-ecc5-41f2-9d8c-78bd4c56e548.png)

**Comment by andrewjschuang** [comment]
@DilanAthukorala a quick test for me actually works, but I'll take a deeper look on this later.

![image](https://user-images.githubusercontent.com/15385076/208531296-56215ef2-e35d-4b04-bcab-1cdc3cd276c6.png)

But that error message is strange, since `guildId` is a path parameter in the request.

![image](https://user-images.githubusercontent.com/15385076/208531554-f5237ab2-34b4-49d1-ba7a-8713c5a3747e.png)

**Comment by andrewjschuang** [comment]
@DilanAthukorala the error displayed is a `ConfigurationError`, which means the UI didn't properly detect your selection of the `Guild` prop. Can you try again?

**Comment by DilanAthukorala** [comment]
@andrewjschuang I am still observing the issue and I tried selecting different guilds as well. 
![image](https://user-images.githubusercontent.com/102980146/208708320-be7e74a8-8a46-42fc-bb15-707eabafd0db.png)

**Comment by DilanAthukorala** [comment]
@dannyroosevelt This issue get resolved after configuring the Bot menu permissions in Discord App.  
![image](https://user-images.githubusercontent.com/102980146/208750477-a659d6cb-385e-4001-9d34-93d7eea47f21.png)

**Comment by dannyroosevelt** [comment]
Which menu permissions?

**Comment by DilanAthukorala** [comment]
> Which menu permissions?

@dannyroosevelt Toggling on the `"Server Member Intent"` under **Bot** section Is sufficient for listing the guild members. 
![image](https://user-images.githubusercontent.com/102980146/208755553-4307659f-df2a-4eee-9944-ac999e630996.png)

**Comment by DilanAthukorala** [comment]
Verification completed, ready for release!
