### ISSUE TITLE
[ACTION] Monday - Create Columns

### ISSUE THREAD

**Issue by giladelevation** [PipedreamHQ/pipedream#4982]
Looking for functionality to add columns to monday board.
Ideally the function could create multiple columns at once (like adding multiple items)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by vellames** [comment]
Hey @giladelevation, I have one good news and one bad news. Sorry but `monday.com` doesn't provide an API to multiple columns. But the good news is, we can add columns as you requested!

**Comment by Hassan-Abbas-SQA** [comment]
### **TestPassed**
![image](https://user-images.githubusercontent.com/104946677/208956009-a4784118-940c-467f-9311-5395027e2e96.png)
