### ISSUE TITLE
[TRIGGER] Support Zoho Mail Japan

### ISSUE THREAD

**Issue by RiverTeacher** [PipedreamHQ/pipedream#4983]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Support Zoho Mail Japan
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://www.zoho.com/mail/help/api/

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@RiverTeacher this is done! Can you please confirm?

**Comment by RiverTeacher** [comment]
It did indeed work.
Thanks for the quick response 😊

**Comment by dannyroosevelt** [comment]
Great to hear!
