### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by rjalili86** [PipedreamHQ/pipedream#4984]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Hi
Please add the possibility of forwarding emails from the Outlook service to Telegram
Thanks
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by DilanAthukorala** [comment]
@rjalili86 Can you please provide more details on the trigger/source that you are requesting and your use case.

**Comment by rjalili86** [comment]
When I receive a new email on the Microsoft Outlook email service, I want it to be forwarded to a bot that I created in Telegram and connected to a Telegram channel.

**Comment by DilanAthukorala** [comment]
@rjalili86 You can achieve this using the already existing Microsoft Outlook "New Email Received" trigger and Telegram Bot Actions using a workflow.
![image](https://user-images.githubusercontent.com/102980146/209192888-6323b2ec-bff3-4ff9-9096-bb5d42588939.png)

Please let us know if this works out.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
