### ISSUE TITLE
[BUG] support import from '@observablehq/plot'

### ISSUE THREAD

**Issue by Fil** [PipedreamHQ/pipedream#4993]
I'm trying to SST a chart with Observable Plot
`import * as Plot from '@observablehq/plot';`

and it fails with

Code Error
SyntaxError: Unexpected token '??='

Complete code (but the error appears with just the line above):

```
import * as d3 from "d3";
import {JSDOM} from "jsdom";
import * as Plot from "@observablehq/plot@0.6.1";

export default defineComponent({
  async run() {
    const jsdom = new JSDOM("");
    const values = d3.range(10);
    const chart = Plot.plot({
      document: jsdom.window.document,
      marks: [Plot.dotX(values)]
    });
    return chart.outerHTML;
  },
});

```

**Comment by DilanAthukorala** [comment]
@Fil Can you please provide more context & details for this issue.

**Comment by Fil** [comment]
I created this workflow
https://pipedream.com/@fil/untitled-workflow-p_3nC9zvN/build

Added that line of code (or a bit more, but that line is what breaks):
`import * as Plot from '@observablehq/plot';`

Then I hit the "test" button.

And I got this error.

<img width="937" alt="Capture d’écran 2022-12-20 à 18 01 31" src="https://user-images.githubusercontent.com/7001/208723703-dd86d2e3-6a32-48da-87c2-0ac6f08ca12a.png">

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by Fil** [comment]
I think there was enough information to reproduce the issue.

.
-- 
-- Fil

**Comment by DilanAthukorala** [comment]
@Fil Thanks, I was able to see the same issue, will add this to our priority backlog for the dev team to check this further.

**Comment by DilanAthukorala** [comment]
@ctrlaltdylan Could you please assist with this issue

**Comment by ctrlaltdylan** [comment]
@Fil that appears to be an unsupported operator in ES6, perhaps this library is using future experimental Node.js operators and expects to be compiled into ES6?

Pipedream can support valid ES6 syntax. You can attempt to find an pure ES6 implementation of this library, or compile it to ES6 using babel and publishing your own version to NPM if needed.

**Comment by Fil** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment is available from node 15
