### ISSUE TITLE
Refactor Airtable sources to use webhooks

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5013]
https://support.airtable.com/docs/airtable-webhooks-api-overview

This is blocked on updating the integration to use OAuth instead of API keys.

**Comment by russelldavis** [comment]
Now that #7322 is merged, should this be moved out of Blocked status?

**Comment by dannyroosevelt** [comment]
> Now that #7322 is merged, should this be moved out of Blocked status?

Unfortunately Airtable has imposed pretty strict limits on their webhooks, and there are 2 primary constraints that are relevant:
- https://airtable.com/developers/web/guides/webhooks-api#how-many-webhooks-can-i-register
- 7-day expiry ( we don't currently have a mechanism to automatically refresh deployed webhooks): https://airtable.com/developers/web/guides/webhooks-api#will-webhooks-ever-expire

**Comment by malexanderlim** [comment]
Webhooks are now available with the Airtable integration (OAuth).
See https://pipedream.com/apps/airtable-oauth/triggers/new-modified-or-deleted-records-instant as an example.
