### ISSUE TITLE
[FEATURE] Download/backup the workflows and actions

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#502]
**Is your feature request related to a problem? Please describe.**
I would like to backup what I am building with pipedream just in case I ever lose access or my workflows/actions are lost for whatever reason. Similar to how "Google Takeout" works.

**Comment by dylburger** [comment]
You can now edit and develop actions locally and keep them in Git or whatever local storage you'd like! [See the docs here](https://pipedream.com/docs/components/quickstart/nodejs/actions/).

**Comment by dylburger** [comment]
I'm closing this issue in favor of #220. We're tracking the ability to serialize workflows to a configuration file / a Git repo there, which will enable this use case. Please follow that issue for updates on our progress there.

**Comment by forevermatt** [comment]
I'd like to request that this issue be reopened. It is a separate need from being able to deploy and update workflows from something like a CI/CD process (though that is also valuable).

We have multiple production workflows that took months to develop and fine-tune, and being able to export a backup of them would be incredibly helpful from a disaster-recovery (DR) standpoint.

@dylburger Would you be willing to reopen this issue, or would you prefer I submit a new issue?
