### ISSUE TITLE
Can't add multiple rows with google Sheets

### ISSUE THREAD

**Issue by kennethmak226** [PipedreamHQ/pipedream#5035]
I tried to use the configure to test but it showed syntax errors as below;

Unexpected token y in JSON at position 0

I checked that the source code line 48
rows = JSON.parse(this.rows);

JSON.parse should be edited as the result can not be parsed as JSON but plain text?

Great thanks for your help!!

**Comment by vunguyenhung** [comment]
Hello @kennethmak226, could you provide the configuration of your Google Sheet action?

Per the example in the description, the Row Values should be passed a stringified a nested JSON array. Have you tried to use it?
![image](https://user-images.githubusercontent.com/18277920/209550285-107fd9ae-2422-49df-ae67-7e3e78d54689.png)

**Comment by kennethmak226** [comment]
Hello Leo,

Great thanks for your reply.

I tried to follow the tutorial I watched on YouTube and use the add single row, which is perfectly fine and export the data I want.
But while using the add_multiple_rows, it keeps showing the syntax error of Unexpected token y in JSON at position 0

I tried to search online, and some explained that it is not working as data type received is not the same for export to google sheet; but I don’t know how to fix it as I am a newbie to api and data scarping.
Please see the dump screen as beblow.

Again, thanks for your help and wish you a merry Christmas~~

Best regards,
Kenneth

￼

￼

**Comment by dalaohuniu** [comment]
thankyou

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
