### ISSUE TITLE
[BUG] Discord - New message (Instant) is not emitting events for new message in selected channel

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5038]
**Describe the bug**
Discord - New message (Instant) is not emitting events for new message in selected channel

**To Reproduce**
1. Create a new workflow, add the Discord - New Message (Instant) trigger. Then connect a Discord account via OAuth, make sure to enable Administrator level for Pipedream bot
<img width="913" alt="Screen Shot 2022-12-26 at 21 54 48" src="https://user-images.githubusercontent.com/18277920/209561116-6440f2f9-7d9c-4902-8e97-3fa404c56f96.png">
2. On Discord, add new messages

![IMG_9AA0F401087B-1](https://user-images.githubusercontent.com/18277920/209561206-fe868a6f-4ba3-4349-bd35-3611f4d8e7c8.jpeg)
4. Observed that there's no event emitted on the Pipedream trigger

![image](https://user-images.githubusercontent.com/18277920/209561372-d708f05b-83b9-4d97-86fb-3a984665c5cb.png)

**Expected behavior**
New events should be emitted when there're new messages in the registered Discord channels

**Additional context**
First reported by a user here: https://pipedream-users.slack.com/archives/CN1BUB92B/p1672062932860099

**Comment by lcaresia** [comment]
I tested others events and it's not working too, probably a problem on `$.interface.apphook`.

![image](https://user-images.githubusercontent.com/12402324/209700709-fc71dcea-413f-4720-89ba-d502715a4056.png)

Cc: @dannyroosevelt @dylburger

**Comment by dannyroosevelt** [comment]
Hm I cannot reproduce -- @vunguyenhung @lcaresia are you still able to reproduce this?

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt, I can still reproduce this bug with my server. 
![12 10 01 - 29 - 12 - 2022](https://user-images.githubusercontent.com/18277920/209906120-3d8bbda4-6766-4013-8fdc-4fc9a47a6a7f.png)


@lcaresia One note is the Source log is blank for me
![12 10 19 - 29 - 12 - 2022](https://user-images.githubusercontent.com/18277920/209906145-5f513855-835c-41af-a648-a823d100c072.png)

**Comment by dannyroosevelt** [comment]
Weird, I am seeing events emit: https://capture.dropbox.com/gosXukcIoxGIJRWw

**Comment by dannyroosevelt** [comment]
Okay, the only thing I was able to repro is when I added another channel to the source configuration, I am not getting emits from messages in that 2nd channel: https://capture.dropbox.com/SpOZ0lLDkNKKE126
