### ISSUE TITLE
[SOURCE] Reddit

### ISSUE THREAD

**Issue by Hans5958** [PipedreamHQ/pipedream#504]
**Describe the event source. What app, what event?**
Reddit, that social media/news aggregator/discussion website. Probably something along the lines of new post/comments, and some others.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://www.reddit.com/dev/api/

**Comment by todsac** [comment]
New Post or Comment Matching Search
New Comment by a User
New Link by a User
New Subreddit by a user
New Link in a Subreddit
New Comment in a Subreddit
New Link (not sure what this is exactly)
New Hot Post in a Subreddit (post in the top 10 of a subreddit

**Comment by sergioeliot2039** [comment]
> New Link (not sure what this is exactly)

I am working with a reddit source, and doing due research,i found in Integromat a clarification for a link in reddit api.

> Submit a Post
> Submit creates a lin, a post with an image or a self-post in the subreddit with the given title. If kind is "link" or "image" then url is expected to be a valid URL to link to. Otherwise, text is the body of the self-post.

**Comment by dylburger** [comment]
Reddit sources are out!
