### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by 4bumuhammad** [PipedreamHQ/pipedream#5048]
**Evernote**

**[Link to developer documentation](https://dev.evernote.com/)**

**may i for installed package evernote in python code?**

**because i need  api evernote in step python my pipedream !**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
OAuth authentication docs: https://dev.evernote.com/doc/articles/authentication.php

**Comment by sergioeliot2039** [comment]
Actually, we are traciking Evernote here: https://github.com/PipedreamHQ/pipedream/issues/416

**Comment by sergio-eliot-rodriguez** [comment]
A [base integration](https://pipedream.com/apps/evernote?via=go) for Evernote has been released, feel free to check it out.
