### ISSUE TITLE
[BUG] Supabase actions are not executed correctly even though showing successful result

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5051]
**Describe the bug**
Supabase actions are not executed correctly even though showing successful result. For example, I use the Select Row action to select a row on the existing table, but it returns empty. I tested the Insert Row action too, but there's no row added

**To Reproduce**
1. Create a new Workflow, authenticate Supabase using the subdomain and service_role field

![image](https://user-images.githubusercontent.com/18277920/209760653-ddeacc20-6e96-447b-8afb-75b02b33e695.png)

2. On Supabase, add a new table `users`, add a new row
![12 07 35 - 28 - 12 - 2022](https://user-images.githubusercontent.com/18277920/209760740-0c622522-09ab-454d-a17d-5f5abe2d53c4.png)

3. On Pipedream workflow, add the Supabase - Select Row action, then test the action. Observed that there's no result returned
<img width="732" alt="image" src="https://user-images.githubusercontent.com/18277920/209760696-e48bb982-372a-452b-8b08-03ac2090ab66.png">

4. I also tested with another table format, but there's also no result
<img width="732" alt="image" src="https://user-images.githubusercontent.com/18277920/209760878-58d548e1-625c-4130-8da8-7bab12317fac.png">

5. On Pipedream workflow, add the Supabase - Insert Row action, then test the action. Observed that there's no new row added even though the action is successfull
<img width="732" alt="image" src="https://user-images.githubusercontent.com/18277920/209760949-4091444d-4f2c-43a2-8e9e-d52d65e122db.png">

**Expected behavior**
- In case that my authentication or input is incorrect, the action should failed with error
- The `Table` prop should be an async prop that show my available tables
- The action should executed correctly and show successful result

**Comment by mikenicholls88** [comment]
Thanks, this is similar problem although slightly different, I could not even authenticate

ConnectionError
HTTPSConnectionPool(host=‘$%7bauths.supabase.subdomain%[7d.supabase.co](http://7d.supabase.co/)’, port=443): Max retries exceeded with url: /rest/v1/ (Caused by NewConnectionError(‘<urllib3.connection.HTTPSConnection object at 0x7f4f3be7c7f0>: Failed to establish a new connection: [Errno -2] Name or service not known’))

Never got to browse or load a table.

**Comment by luancazarine** [comment]
@vunguyenhung I followed the steps and both actions worked perfectly for me.

![image](https://user-images.githubusercontent.com/5638699/209826529-73e38348-1341-4e12-802a-f131d0cdc504.png)
![image](https://user-images.githubusercontent.com/5638699/209826676-cf832c02-80e9-4cb6-af49-6b914d131f96.png)

About the async prop to get tables, I haven't found a way to do that.

**Comment by vunguyenhung** [comment]
Hello @mikenicholls88, I suspect that the subdomain that you passed in is incorrect

Given the supabase info like this
![image](https://user-images.githubusercontent.com/18277920/209829826-8c5d6afe-6d18-4885-924e-7f23e71b1d5e.png)

You will need to input into Pipedream's subdomain field like this
<img width="654" alt="image" src="https://user-images.githubusercontent.com/18277920/209830005-eb6ff99b-39f7-4925-8cce-2e53ad74a23c.png">

Please let me know if you have other issue

**Comment by mikenicholls88** [comment]
The subdomain resolves just fine if you plug it into a browser

I used the copy button on supabase admin dashboard to copy the subdomain

I can access this subdomain from other nocode apps inc Zapier

So maybe you want to check again?

Might also be worth checking why your other team member also had issues

Thanks
