### ISSUE TITLE
[FEATURE] I want to use Pipedream's built-in triggers and actions with my own OAuth Access Tokens

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5054]
I want to use Pipedream's built-in triggers and actions using OAuth access tokens from my own customers, without having them create a Pipedream and connect their account there. Instead, they'll connect their 3rd party account (for Slack, Twitter, Google Sheets, etc) in my own app, and I'll pass in the access token programmatically.

**Comment by bhanu-affinidi** [comment]
I am having the same use case . any plans to have this feature implemented?

**Comment by dannyroosevelt** [comment]
We shipped this and it's live for everyone now! Here are the docs:
https://pipedream.com/docs/connected-accounts/external-auth/
