### ISSUE TITLE
[ACTION] Discord Bot - Modify Guild Member

### ISSUE THREAD

**Issue by sketchuprzr** [PipedreamHQ/pipedream#5057]
**Is there a specific app this action is for?**
Discord Bot

**Please provide a link to the relevant API docs for the specific service / operation.**
https://discord.com/developers/docs/resources/guild#modify-guild-member

**Comment by vunguyenhung** [comment]
Hello @sketchuprzr, Pipedream recently released a new Discord Bot - Change Nickname action as the image below
<img width="908" alt="image" src="https://user-images.githubusercontent.com/18277920/209949665-2bf1aebc-ef4d-4c66-b29a-89badb8f037d.png">


Could you try it?

**Comment by sketchuprzr** [comment]
> Hello @sketchuprzr, Pipedream recently released a new Discord Bot - Change Nickname action as the image below <img alt="image" width="908" src="https://user-images.githubusercontent.com/18277920/209949665-2bf1aebc-ef4d-4c66-b29a-89badb8f037d.png">
> 
> Could you try it?

Hi
I tried this feature. But this doesn't change the nicknames of the users. This just changes the nickname of the discord bpt.

**Comment by vunguyenhung** [comment]
Thanks @sketchuprzr, I've updated your description a bit to be more concise. Changing the nickname is included in modify guild member action

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sketchuprzr** [comment]
> 

How do I reach the application provider? I'm not a programmer, so I don't have the knowledge to create this command.That's why I use pipedream.

**Comment by sketchuprzr** [comment]
> Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.
> 
> If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

How do I reach the application provider? I'm not a programmer, so I don't have the knowledge to create this command.That's why I use pipedream.

**Comment by dannyroosevelt** [comment]
@sketchuprzr we just added this to the team's roadmap, to publish a new action to Modify Guild Members from your own Discord Bot.

**Comment by sketchuprzr** [comment]
I solved the problem with "Use any discord bot API in Node js". @dannyroosevelt

![image](https://user-images.githubusercontent.com/60021696/209997493-424607aa-6653-4acc-9dc5-a15eb10da0fd.png)

With the following line of code, you can give a nickname to a specific user on a specific discord server, using the bot you have chosen.

![image](https://user-images.githubusercontent.com/60021696/210003202-aa1cea43-cdaf-4fae-b1ba-71ce740f31c4.png)

Server GUID : ${Server ID}
User GUID : ${UserID}
Nickname : ${Nickname}

> import { axios } from "@pipedream/platform"
> export default defineComponent({
>   props: {
>     discord_bot: {
>       type: "app",
>       app: "discord_bot",
>     }
>   },
>   async run({steps, $}) {
>     return await axios($, {
>       method: 'PATCH',
>       url: `https://discord.com/api/guilds/${Server ID}/members/${UserID}`,
>       headers: {
>         "Authorization": `Bot ${this.discord_bot.$auth.bot_token}`,
>       },
>       data: {
>         nick: ${Nickname}
>       }
>     })
>   },
> })

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed
![image](https://user-images.githubusercontent.com/104946677/210455043-d067cbc9-8b3b-421a-8c48-0d5dfa3e7741.png)

**Comment by sketchuprzr** [comment]
I wasn't expecting this much :D
unbelievable. You really did a good job. Congratulations and thank you.
