### ISSUE TITLE
[ACTION] Pipedream >> Supabase queries

### ISSUE THREAD

**Issue by mikenicholls88** [PipedreamHQ/pipedream#5059]
**Is there a specific app this action is for?**
Pipedream >> Supabase queries

**Please provide a link to the relevant API docs for the specific service / operation.**

I would like to be able to query Supabase database/table by
- show latest N records
- show records where column contains "querystring"
Thanks

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
