### ISSUE TITLE
[BUG] ECONNRESET error on python code  pdf2img library

### ISSUE THREAD

**Issue by hvieirapt** [PipedreamHQ/pipedream#5067]
Hi guys,
I’m trying to use a python step to convert a pdf file (from url) first page (for testing purposes) to image raw data.
Unfortunately i’m getting the read ECONNRESET error, i’m stuck.

Here is the code and error:
![chrome_ZYGqZp7PRx](https://user-images.githubusercontent.com/48965947/210101633-84db1dd6-2293-4827-94b5-fb280151e5f6.png)

Any ideia on how i can fix this?

Thanks!

**Comment by Hassan-Abbas-SQA** [comment]
@hvieirapt i think the convert method has been deprecated  in the latest version of pdf2img module can you please try these two new methods according to PYPI documentation https://pypi.org/project/pdf2image/

<img width="911" alt="image" src="https://user-images.githubusercontent.com/104946677/210270993-49f3c2d4-e729-4e57-8405-7c5a2d578714.png">
<img width="911" alt="image" src="https://user-images.githubusercontent.com/104946677/210271014-9a7a10fb-2471-410a-b43f-a5136d4ba85a.png">
<img width="682" alt="image" src="https://user-images.githubusercontent.com/104946677/210271288-86442539-8eed-42ea-9a75-fc603e2e6922.png">

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
