### ISSUE TITLE
[FEATURE] Discord Bot - Image attached in embed message

### ISSUE THREAD

**Issue by hgrams** [PipedreamHQ/pipedream#5068]
Hello, I have a workflow where I send embedded messages to discord. 
I want to add a screenshot of a page to this flow and send this screenshot to discord, however, I can't attach the file saved in /tmp/ using Discord Bot.

It would be nice to have the ability to attach images to embedded messages using the Discord Bot integration in pipedream.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by hgrams** [comment]
I tried to do it, but I couldn't.

I thought it was enough to copy the nodejs code used in the `Send Message (Advanced)` Action that is on the "[Discord Webhook API](https://pipedream.com/apps/discord-webhook/actions/send-message-with-file)" integration page, but I get an error when trying.

Could you give me a way of how I could do this action?

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Discord_5068.pdf](https://github.com/PipedreamHQ/pipedream/files/10401696/Discord_5068.pdf)
