### ISSUE TITLE
[ACTION] Hubspot - Update a batch of objects

### ISSUE THREAD

**Issue by raphaelvarieras** [PipedreamHQ/pipedream#5074]
Hubspot

[Contact endpoints documentation](https://developers.hubspot.com/docs/api/crm/contacts)

Right now there is support for updating an individual contact, which is ok if you're making just a handful of updates. If you're making hundreds or thousands, you will generate a large number of Pipedream invocations and API calls in your Hubspot account. I would suggest creating an action that would support iterating through a collection of sets of properties, and would automatically put together batches of 10 or 100 (contact endpoint only supports batches of 10, other objects 100 - go figure...).

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergioeliot2039** [comment]
Batch Update Object action

**Comment by raphaelvarieras** [comment]
I can see the batch contact update action is live - thanks! 

But should this issue really be closed if batch update or create companies, deals, custom objects aren't completed? Or maybe you would prefer that new issues need to be created for each individual entity types?

**Comment by dannyroosevelt** [comment]
> 

Happy to group updates together into a single ticket, but can you enumerate which other actions you'd like to see? It sounds like a similar approach for the below?
- Batch Update or Create Companies
- Batch Create New Deals
- Batch Create Custom Objects

Before getting started on those, have you gotten a chance to validate that the design and implementation for the Batch Contact action works for you?

**Comment by dannyroosevelt** [comment]
That'd be great, that makes a lot of sense. Is there an API for that? Or is it just a static list?

**Comment by dannyroosevelt** [comment]
So to confirm, the Object Type ID for Task is the string, `0-27`? That is not a range, right?

**Comment by raphaelvarieras** [comment]
That's correct. I know it's a bit odd but I think it's some sort of compound id. The first digit is different for Hubspot custom objects (2), for built-in events (4), for custom events (6).
