### ISSUE TITLE
[SOURCE] Make "branch ID/name" argument optional for Gitlab, Github and BitBucket.

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#508]
As per PR review: 
_Originally posted by @tjk in https://github.com/PipedreamHQ/pipedream/pull/487#discussion_r497283362_

There is no reason why we cannot make this argument optional (in fact, from the [Github component's description](https://github.com/PipedreamHQ/pipedream/blob/master/components/github/new-commit.js#L13) it seems like this was the original idea).

This will require refactoring the following components:
* BitBucket
* Github
* Gitlab

**Comment by dylburger** [comment]
@jverce I see that you merged a commit tied to this. Did that close this issue or is there still outstanding work?

**Comment by jverce** [comment]
This is a follow-up task that I created to address a minor comment left on a PR, that's why they're tied. But this is still not done.
