### ISSUE TITLE
[TRIGGER] Monday

### ISSUE THREAD

**Issue by szaszlevi** [PipedreamHQ/pipedream#5080]
**Trigger request for subitem boards on Monday. Subitem boards are only visible in the backend in Monday.**

**https://developer.monday.com/api-reference/docs/webhooks-1#sub-item-webhook-notes**

Context: [Slack](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1672650636295409)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
