### ISSUE TITLE
Timeout issues

### ISSUE THREAD

**Issue by stefanbohacek** [PipedreamHQ/pipedream#5089]
**Describe the bug**
My [workflow ](https://pipedream.com/@book-dedications-bot/dedication_bot-p_NMCLMQY/inspect/2JpBapsrgQxpTilHTnFZXWxCYIG) occasionally times out, but it is unclear where the issue is. I was recommended to add a few log statements, which are working fine (see screenshot section), but when the timeout occurs, I am not able to see the logs, and the code blocks are grayed out, as if the issue was with the trigger itself.

**To Reproduce**
I am unable to reproduce the issue with test runs, and I am not noticing any pattern in when it happens (see last screenshot).

**Expected behavior**
Scripts should execute, or I should be able to inspect the error log when they don't.

**Screenshots**

Successfully executing each step.

![log-01](https://user-images.githubusercontent.com/3909390/210423246-04b9dc39-ddaf-4f4e-8369-f251d3e2a648.PNG)
![log-02](https://user-images.githubusercontent.com/3909390/210423254-09636c59-93d9-4d9a-9eca-2985ca037af9.PNG)
![log-03](https://user-images.githubusercontent.com/3909390/210423260-434e1d0d-b8d8-466d-a5ee-e68e6ad6a4be.PNG)
![log-04](https://user-images.githubusercontent.com/3909390/210423267-72149f83-3428-416d-aaa3-06bfc8838392.PNG)

Timeout error, unable to inspect the logs.

![error](https://user-images.githubusercontent.com/3909390/210423277-7a8cb691-8d35-4087-a3d3-3d74d5ac55ae.PNG)

**Comment by dylburger** [comment]
@stefanbohacek Apologies for the late reply here, I'm going back through old issues. Are you still seeing this? We fixed a related bug and I'd like to see if it's still an issue for you. We should show partial logs on all timeouts. If you're still seeing events fail with timeouts but no partial logs, please share the workflow with Pipedream support and send me an email at dylan [at] pipedream [dot] com and I can take a look.

**Comment by stefanbohacek** [comment]
@dylburger Thank you for following up on this! This seems to be no longer an issue.
