### ISSUE TITLE
New Issue Event (Instant) with the Sentry API - Brazilian Domain

### ISSUE THREAD

**Issue by adenisdeveloper** [PipedreamHQ/pipedream#5091]
I Have trigger to https://pipedream.com/@tecnovix/new-issue-event-instant-with-the-sentry-api-p_2gCQkeL/build

And I see that the script by default doesn't let me edit to the correct bitrix origin and fixes the .com domain

This causes me an invalid address and I can't proceed with the integration.

Even if you change the javascript directly it doesn't work.

Check Exemple
https://prnt.sc/YnKb8M9iDPZZ

**Comment by dannyroosevelt** [comment]
Closing this as it's a duplicate of https://github.com/PipedreamHQ/pipedream/issues/5092
