### ISSUE TITLE
[Bug] New Issue Event (Instant) with the Sentry API

### ISSUE THREAD

**Issue by adenisdeveloper** [PipedreamHQ/pipedream#5092]
I Have trigger to https://pipedream.com/@tecnovix/new-issue-event-instant-with-the-sentry-api-p_2gCQkeL/build

And I see that the script by default doesn't let me edit to the correct bitrix origin and fixes the .com domain

This causes me an invalid address and I can't proceed with the integration.

Even if you change the javascript directly it doesn't work.

Check Exemple
https://prnt.sc/YnKb8M9iDPZZ

**Comment by dannyroosevelt** [comment]
@adenisdeveloper can you elaborate a bit? What is the correct Bitrix origin that you're trying to use?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by adenisdeveloper** [comment]
tecnovix.Bitrix24.com.br
