### ISSUE TITLE
New Product from Shopify API not detecting products, (Instant) version works [BUG] 

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#5096]
**Describe the bug**
As per the title, I wish to use the slower `New Product from Shopify API` method to retrieve new products for my store to them do various things with. However creating a test workflow it's stuck on 'waiting for event'. The `New Product Created (Instant) from Shopify API` does pick this up but the issue it that the workflow would run before I complete any work required on the product.

**To Reproduce**
1. Create a workflow with `New Product from Shopify API` and connect to store
2. Test the `Select Event` step, it will tell you it needs and event to test against
3. Create a dummy product on your store, make sure it's active and on store channel (not sure if this is a must but treat it like the real thing)
4. New product event is not detected, spinner on `Waiting for events...` just keeps spinning, hitting the Try Now does not make any difference, left it for about 30 mins before posting this just to see if it got the idea.

**Expected behavior**
Should detect new products like the instant version does

**Screenshots**
![Screenshot 2023-01-04 133246](https://user-images.githubusercontent.com/8470449/210566217-6fae0488-a95d-468d-80db-e04b259e1574.jpg) 

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome and Firefox
 - Version: n/a

**Comment by Hassan-Abbas-SQA** [comment]
![image](https://user-images.githubusercontent.com/104946677/210617649-54ff7930-f3b0-4ca8-b5b8-473b5f9467ef.png)

![image](https://user-images.githubusercontent.com/104946677/210618203-011596dc-e0f0-4b83-b6a5-318dc704c6c8.png)
Tested using worklow and sources tab too iam unable to reporduce the issue and getting the events timely can you please try reducing yourtime to 15 seconds to instantly test your trigger

**Comment by NebularNerd** [comment]
Hi @Hassan-Abbas-SQA 

Thanks for your suggestions, still no luck I'm afraid. The connection to the store does work as I have another trigger I set up yesterday for grabbing recent news posts using `New Article` and as mentioned the instant version picks them up. It's most strange why this one is not behaving for me.

Equally just testing 'Updated Customer' also works, it just seems to have issues with the non instant product. Most strange 😕

**Comment by dannyroosevelt** [comment]
>the workflow would run before I complete any work required on the product.

@NebularNerd can you elaborate on why the instant source won't work for you? Can you tell me more about what you're trying to do? I wonder if there's a workaround we can figure out.

**Comment by NebularNerd** [comment]
Sometimes I add a product to the store or duplicate an existing product that needs work done before it's ready to go live. If Pipedream instantly picks this up it will read the incorrect data for title, description etc....

The slower method is preferable as I can run it every x hours or at set time points giving me time to make sure everything is ready for Pipedream to import.

The idea is that when it runs it will pick up the data and the publish as a post so I need it to have the correct details otherwise Pipedream is going to be posting gibberish.

I use a similar method for detecting my YouTube videos, as I know when it will next scan for them I can avoid uploading another video too close to the runtime for much the same reasons.

I figured I could do it using the `Delay` module but you cannot add the trigger after only before so that does not solve the issue.

The only other way I can think of doing it would be to have the instant capture the product id's and store them somewhere, then later on scrape the id's for details with a bit of Python-fu but that seems like a lot of work (both programming and Pipedream resource wise)

**Comment by NebularNerd** [comment]
Ok doing some more testing and here's a good one.... It works... sort of...

If you setup a new source using `Shopify:New Events` and select the `Product Created` sub event it picks them up just fine. There must be an issue in the way the dedicated `New Product` trigger works.   

![Screenshot 2023-01-06 121121](https://user-images.githubusercontent.com/8470449/211010433-1f323ea5-a43a-4c8d-b633-084a50518704.jpg)


![Screenshot 2023-01-06 120823](https://user-images.githubusercontent.com/8470449/211009990-b701fc7a-e2c6-4eba-89c2-74eb71a56b9f.jpg)

This should be enough for me to get what I want so I'll run with this. I think this may even be better for me specific needs as I can add an additional filter or two to the code.  

Thanks to everyone who answered, in I'll leave this open in case anyone has any further suggestions, if not I'll close it in a day or two.

**Comment by dannyroosevelt** [comment]
Okay that all makes perfect sense -- glad you got it sorted out!
