### ISSUE TITLE
[APP]  Google My Business API integrations

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#5101]
**Is your feature request related to a problem? Please describe.**
Can we get Google My Business API integrations added? This would be great for adding content to the My Business pages without having to manually use Google's interface. Double bonus is that Bing Business copies content over making it do two for one on your workload.

**Describe the solution you'd like**
Access to Google My Business API integrations

**Link to developer documentation**
https://developers.google.com/my-business/

**Do you have a workaround?**
It can be done through Python with some work and you have to do a lot of setting up before you can get that far. Medium have a pretty good how to https://medium.com/analytics-vidhya/google-my-business-api-application-using-python-part-1-f6be43115645 I imagine that it would add a lot of computing time to accounts over a native implementation.

**Comparable features in other tools?**
Not in the sense of other online app workflow creators.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

[Trigger - New Review Received](https://developers.google.com/my-business/content/notification-setup)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by NebularNerd** [comment]
Hi @dylburger,

Looking over the link it's something that may not be entirely outside my abilities. From the examples there it would likely need something similar to the GitHub example. Reading over the prerequisites it also seems to use Google Cloud which Pipedream does support. I would have to do a lot more reading on this and see where it goes.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by NebularNerd** [comment]
Awesome, I've just got my API keys so I'll likely look to cobble a couple of things together using your Python integrations in the meantime.

**Comment by mendelsphotography** [comment]
Something i would love to see.

**Comment by malexanderlim** [comment]
Hi all, we've prioritized this integration and are tracking development in https://github.com/PipedreamHQ/pipedream/issues/6979. Please feel free to follow along there, or comment if there's some other functionality that you'd like to see!

**Comment by NebularNerd** [comment]
Hi @malexanderlim cool, I will follow over there and close this issue to help keep things tidy.
