### ISSUE TITLE
[APP] SoftLedger

### ISSUE THREAD

**Issue by geoffsoftledger** [PipedreamHQ/pipedream#5104]
**Name of app / service**
SoftLedger - softledger.com

**Link to developer documentation**
https://api.softledger.com/docs
Oauth2 client credentials M2M auth 

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Currently leveraging env variables for oauth keys

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Ideally all, but my team can help out as I am the product owner for SoftLedger app. Main request is storing auth tokens.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dannyroosevelt** [comment]
@geoffsoftledger thanks for the request! I just sent an email to `support@softledger.com` to get access to the API so we can get started.

**Comment by geoffsoftledger** [comment]
@dannyroosevelt great, I'll follow up there and make sure you get what you need.
