### ISSUE TITLE
Gmail Developer App - Create an email draft

### ISSUE THREAD

**Issue by kchasepdx** [PipedreamHQ/pipedream#5110]
**Is there a specific app this action is for?**
Gmail

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.google.com/gmail/api/reference/rest/v1/users.drafts

We would like to be able to save a draft of an email to a designated gmail account. We discovered this limitation when attempting to port an existing workflow from Zapier, where this feature exists. On that platform we are able to update the To, From, From Name, Subject, Body, Body Type, and Signature fields.

**Comment by dannyroosevelt** [comment]
Hi @kchasepdx thanks for the request. Unfortunately the Gmail scope that's required to create drafts is what Google considers a "Restricted" scope, which means there is a very long process for Pipedream to get approved (we've started the process but do not have an ETA).

However, we can help get an action built out that uses the [Gmail Developer App](https://pipedream.com/apps/gmail-custom-oauth), which means you'd have to create a Gmail OAuth app in Google Cloud and enter your client ID and secret when connecting your account. We've [outlined that process here](https://pipedream.com/apps/gmail-custom-oauth#getting-started).

Would that work for you?

**Comment by dannyroosevelt** [comment]
@vellames since you're already working on the Gmail Developer App, it might make sense for you to pick this up at the same time?

**Comment by Hassan-Abbas-SQA** [comment]
TESTPASSED
![image](https://user-images.githubusercontent.com/104946677/212173243-72298587-cf13-48b7-9042-4547b2d76496.png)

**Comment by dannyroosevelt** [comment]
That summary message needs to be cleaned up -- it could be something closer to:

**Comment by dannyroosevelt** [comment]
@vellames -- what fields are required by the API to create a draft?

**Comment by vellames** [comment]
@dannyroosevelt Only the message, but I added subject and message as in `send-email`

**Comment by Hassan-Abbas-SQA** [comment]
> That summary message needs to be cleaned up -- it could be something closer to:
> 
> > Successfully created a draft message

![image](https://user-images.githubusercontent.com/104946677/212356419-8b541926-bdda-40e8-9002-f5b55672f2a2.png)
its fixed
