### ISSUE TITLE
[TRIGGER] - BitBucket Pipeline Event (multiple repositories)

### ISSUE THREAD

**Issue by Project49Music** [PipedreamHQ/pipedream#5114]
The availability to select multiple repositories within the New **Pipeline Event (Instant)** so that the user does not have to create multiple triggers for when they want to get notifications from pipelines that are used by multiple repositories.

**Comment by Project49Music** [comment]
Might be able to look into it, but I don't have alot of time besides the work I am currently doing as a webdeveloper.
I can definitely reach out to the app provider and keep you posted in this issue.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
