### ISSUE TITLE
[TRIGGER] Gmail - Trigger when a specific email address sends an email

### ISSUE THREAD

**Issue by hdotking** [PipedreamHQ/pipedream#5115]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
When a user sends an email - the contents and metadata should act as a trigger. Essentially sending us "push notifications" for every email sent by a user.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
Official docs:
https://developers.google.com/gmail/api/guides/push

Similar examples:
https://mailtrap.io/blog/send-emails-with-gmail-api/

**Comment by vellames** [comment]
Right now it is not possible to implement that since we need Google approval for a restrict scope for our auth
Cc: @dannyroosevelt

**Comment by dannyroosevelt** [comment]
@vellames can we do this on the Gmail Developer App? There are no scope restrictions there, since uses will be using their own OAuth clients.
