### ISSUE TITLE
[IMPROVEMENT] Firebase: allow to change Database URL

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5118]
**Is your feature request related to a problem? Please describe.**
Users might create the Firebase database in a different region that requires different Database URL. For example, the database created in EU might have the database URL:`https://stripe-example-199c9-default-rtdb.europe-west1.firebasedatabase.app`. 

But in [the Pipedream application code here](https://github.com/PipedreamHQ/pipedream/blob/146802e44c9aafd8bbba59a34b5f0c79ef2edef0/components/firebase_admin_sdk/firebase_admin_sdk.app.mjs#L79), it is always use default URL: `https://${projectId}-default-rtdb.firebaseio.com/`

**Describe the solution you'd like**
Add an optional Database URL prop that allow the user to input customized database url

**Do you have a workaround?**
No

**Additional context**
First reported by a user here: https://pipedream.com/community/t/firebase-database-lives-in-a-different-region/4119

**Comment by Hassan-Abbas-SQA** [comment]
below are the 3 screenshots where you can see i tested my US Central based account on old action version and it worked fine as shown in screenshot , but when i tried to test the new version of action its showing me this error @michelle0927  @vunguyenhung can you please look into that

![image](https://user-images.githubusercontent.com/104946677/210894511-1ed5dfd6-e841-41fa-a57a-c6b73b3f0cd1.png)
![image](https://user-images.githubusercontent.com/104946677/210894530-f3f134c4-cebd-4005-bade-8259c9577b9b.png)
![image](https://user-images.githubusercontent.com/104946677/210894537-d4fdc01c-24b5-424e-b63b-20aa500ffe8b.png)

**Comment by Hassan-Abbas-SQA** [comment]
TESTPASSED
<img width="695" alt="image" src="https://user-images.githubusercontent.com/104946677/211073025-66116048-d8d5-4d73-96d5-5ca29602c08a.png">
