### ISSUE TITLE
[APP] PayPal

### ISSUE THREAD

**Issue by nonamejan** [PipedreamHQ/pipedream#5127]
**Name of app / service**
PayPal

**Link to developer documentation**
https://developer.paypal.com/api/rest/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
lack of support

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi there @nonamejan , thanks for the request.

We have a basic framework of integration for Paypal here: https://pipedream.com/apps/paypal

would you like to extend the existing support to include Pipedream components? which actions and/or triggers would you like to see added?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
