### ISSUE TITLE
[FEATURE] Allow triggering a workflow by sending an email and an additional parameter

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#513]
I've been using the en***@pipedream.net trick to trigger workflows with emails and I was wondering if it would be possible to pass a parameter along with the email. For example, the way Gmail lets you add +whatever right before the @ to get multiple addresses.

My use case is replying to customers that are either interested or uninterested in a specific product and Bcc'ing my pipedream workflow to automatically tag them in my email marketing provider

**Comment by dylburger** [comment]
@nachocab just acknowledging this request, we'll think about this alongside other improvements to the email interface.

**Comment by casret** [comment]
You should be able to use + suffixes now.

**Comment by dylburger** [comment]
Docs here: https://docs.pipedream.com/workflows/steps/triggers/#appending-metadata-to-the-incoming-email-address-with-data
