### ISSUE TITLE
jupyer[APP]

### ISSUE THREAD

**Issue by carloachi** [PipedreamHQ/pipedream#5132]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
hi @carloachi , thank you for making the request.

i am in charge to add the new app requests to Pipedream, by creating an API based integration.

can you please point me to the jupyer website you are requesting?
I am unable to quickly find it, there are many results for jupyter (but not the same name, unless there is a typo)

thank you and look forward working with you

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
