### ISSUE TITLE
[BUG] Gmail (and Gmail Developer) send email attachments not being parsed correctly

### ISSUE THREAD

**Issue by andrewjschuang** [PipedreamHQ/pipedream#5133]
**Describe the bug**
Receiving attachments from the Gmail Send Email action are not being parsed correctly.

**To Reproduce**
1. Create a Gmail Send Mail step
2. Add an attachment:
key - example.docx
value - https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx
3. Test action

**Expected behavior**

Attachments being correctly parsed:
![image](https://user-images.githubusercontent.com/15385076/211353775-7e8db204-7d6e-4412-a59d-b6a3d2196823.png)

**Pipedream action**
![Screenshot 2023-01-09 at 1 00 23 PM](https://user-images.githubusercontent.com/15385076/211353130-d14448a4-e140-4c85-bd2b-ccd1176d1138.png)

**Incorrect parsing**

![Screenshot 2023-01-09 at 1 00 55 PM](https://user-images.githubusercontent.com/15385076/211353147-bd0fc520-62e6-4f14-8183-903789f18a67.png)

[Slack Thread Context](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1673044191262299)

**Comment by andrewjschuang** [comment]
Duplicate of #4784.
Please subscribe to #4784 for updates on this.

**Comment by Hassan-Abbas-SQA** [comment]
still not yet working as expected 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/104946677/211900108-f8c4854a-f1c2-4091-b01a-73ac18890286.png">
and this is what the file contains if i download and open it 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/104946677/211900223-1870ba39-6b60-4336-a19b-423c3feb8bf0.png">

**Comment by michelle0927** [comment]
@Hassan-Abbas-SQA The URL needs to be a direct link to a .docx file. Are you using the link at the top of this issue(https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx) or the corrected link(https://file-examples.com/storage/fea8fc38fd63bc5c39cf20b/2017/02/file-sample_100kB.docx) as discussed in the [PR](https://github.com/PipedreamHQ/pipedream/pull/5156)?

**Comment by michelle0927** [comment]
@Hassan-Abbas-SQA This is another example link to a .docx file: https://thecannabin.com/file-sample_100kB.docx

**Comment by Hassan-Abbas-SQA** [comment]
It worked thanks @michelle0927 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/104946677/211910419-92815c82-e293-4df4-ab59-35ecc0e34dd5.png">
