### ISSUE TITLE
Drata Triggers / Actions

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#5139]
[Drata](https://drata.com/) triggers and actions:

### Triggers

* New Personnel Added — When a new personnel is added to the [Find Personnel](https://developers.drata.com/docs/tag/Personnel#operation/PersonnelPublicController_listPersonnel) endpoint, deduped by `data.id`, emit an event
* New Asset Added — When a new device is added to the [Find Assets](https://developers.drata.com/docs/tag/Devices#operation/DevicePublicController_getDeviceDocuments) endpoint, deduped by `documents.id`, emit an event
* New Control Added — When a new control is added to the [Find Controls](https://developers.drata.com/docs/tag/Controls#operation/GRCPublicController_getControls) endpoint, emit an event
* New Evidence Added — When new evidence is added to the [Find External Evidence](https://developers.drata.com/docs/tag/Controls#operation/GRCPublicController_getMappedExternalEvidence) endpoint, emit an event
* New Vendor Added — When a new vendor is added to the [Find Vendor](https://developers.drata.com/docs/tag/Vendors#operation/VendorsPublicController_listVendors) endpoint., emit an event
* Updated Vendor — When a vendor is updated, i.e. the SHA hash of the object returned in the object from the [Find Vendor](https://developers.drata.com/docs/tag/Vendors#operation/VendorsPublicController_listVendors) endpoint is updated, emit an event
* Drata identifies terminated employee — if any employee's `employmentStatus` moves to terminated, see https://developers.drata.com/docs/openapi/reference/operation/PersonnelPublicController_listPersonnel/
* Failed Control — some control moves to a failed state. Work with @dylburger on this one. See https://developers.drata.com/docs/openapi/reference/operation/GRCPublicController_getMappedExternalEvidence/ 
* New Framework
* Audit Hub

### Actions

* [Find Personnel](https://developers.drata.com/docs/tag/Personnel#operation/PersonnelPublicController_listPersonnel)
* [Upload Background Check](https://developers.drata.com/docs/tag/Background-Check#operation/BackgroundCheckPublicController_updateBackgroundCheck)
* [Upload User Compliance Document](https://developers.drata.com/docs/tag/Users#operation/UsersPublicController_uploadDocumentForUser)
* [Upload Device Compliance](https://developers.drata.com/docs/tag/Devices/#operation/DevicePublicController_uploadDocumentForDevice)
* [Add New Asset](https://developers.drata.com/docs/tag/Assets/#operation/AssetsPublicController_createAsset)
* [Upload Evidence](https://developers.drata.com/docs/tag/Controls#operation/GRCPublicController_uploadExternalEvidence)
* [Add Control](https://developers.drata.com/docs/tag/Controls#operation/GRCPublicController_createControl)
* [Find Controls](https://developers.drata.com/docs/tag/Controls#operation/GRCPublicController_getControls)
* [Find Controls](https://developers.drata.com/docs/tag/Controls#operation/GRCPublicController_getMappedExternalEvidence)
* [Find Vendors](https://developers.drata.com/docs/tag/Vendors#operation/VendorsPublicController_listVendors)
* [Add Vendor](https://developers.drata.com/docs/tag/Vendors#operation/VendorsPublicController_createVendor)
* [Update Vendor](https://developers.drata.com/docs/tag/Vendors#operation/VendorsPublicController_updateVendor)

**Comment by dannyroosevelt** [comment]
FYI this is blocked until we resolve the marketplace agreement with Drata's team.
