### ISSUE TITLE
[ACTION] Upload Thumbnail, Update Video Details, Update Channel, Upload Channel Banner, etc

### ISSUE THREAD

**Issue by taonergy-bit** [PipedreamHQ/pipedream#5146]
**Is there a specific app this action is for?**
Youtube API.
Can you provide more endpoints for the Youtube API app?

**Please provide a link to the relevant API docs for the specific service / operation.**

Upload Thumbnail: https://developers.google.com/youtube/v3/docs/thumbnails/set
Update Video Details: https://developers.google.com/youtube/v3/docs/videos/update
Update Channel: https://developers.google.com/youtube/v3/docs/channels/update
Upload Channel Banner: https://developers.google.com/youtube/v3/docs/channelBanners/insert
Add Playlist Items: https://developers.google.com/youtube/v3/docs/playlistItems/insert
Create Playlist: https://developers.google.com/youtube/v3/docs/playlists/insert
Delete Playlist: https://developers.google.com/youtube/v3/docs/playlists/delete
Create A Comment Thread: https://developers.google.com/youtube/v3/docs/commentThreads/insert
Reply to Comment: https://developers.google.com/youtube/v3/docs/comments/insert

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by taonergy-bit** [comment]
![CleanShot 2023-02-03 at 00 16 22@2x](https://user-images.githubusercontent.com/110698576/216395874-8af5ce0c-05aa-4f50-8302-e2fabf9870fb.png)

Can someone take a look at upload thumbnail actions again. I don't have the errors of missing permission but I have different error which is "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>". This is usually comes from the Pipedream Youtube apps limit with Youtube. Anyway you can request for more quota to make this action works?

**Comment by Hassan-Abbas-SQA** [comment]
> ![CleanShot 2023-02-03 at 00 16 22@2x](https://user-images.githubusercontent.com/110698576/216395874-8af5ce0c-05aa-4f50-8302-e2fabf9870fb.png)
> 
> Can someone take a look at upload thumbnail actions again. I don't have the errors of missing permission but I have different error which is "The request cannot be completed because you have exceeded your [quota](/youtube/v3/getting-started#quota)". This is usually comes from the Pipedream Youtube apps limit with Youtube. Anyway you can request for more quota to make this action works?

<img width="601" alt="image" src="https://user-images.githubusercontent.com/104946677/216401949-208bad20-bb67-4378-89a0-929d187a0417.png">
its working fine for me but for your issue we are investigating why you are getting this error

**Comment by Hassan-Abbas-SQA** [comment]
@taonergy-bit we have increased the quota from our end can you please try again and let us know if its still happening at your end?
