### ISSUE TITLE
[APP] Pirate Weather

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5151]
https://pirateweather.net/

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Pirate Weather is now integrated https://pipedream.com/apps/pirate-weather
