### ISSUE TITLE
Send Message to a Channel[ACTION]

### ISSUE THREAD

**Issue by christianhartman** [PipedreamHQ/pipedream#5154]
When adding a step for Discord Bot actions, the predefined actions only includes sending a Message to an individual user and not a channel.  Would like to send a triggered message to the entire channel.

**Comment by Hassan-Abbas-SQA** [comment]
there should be changes in description to this "You need to select a user/channel."
<img width="484" alt="image" src="https://user-images.githubusercontent.com/104946677/212736947-9b86e3bd-da9f-4b27-9efe-b1150d7db6f4.png">

and also in this error message to "You must select either a user/channel."
<img width="423" alt="image" src="https://user-images.githubusercontent.com/104946677/212737186-6af744f0-e417-4141-a3ba-48ba3f2e00d5.png">

at last the functional test has passed 
<img width="923" alt="image" src="https://user-images.githubusercontent.com/104946677/212737496-77532a6f-b832-49f5-b5f0-b1c70d6c4aaa.png">

**Comment by alysonturing** [comment]
Both places are prompting exactly that the customer must select an user or a channel, please read it again

**Comment by Hassan-Abbas-SQA** [comment]
> "Send message to a user/c

![image](https://user-images.githubusercontent.com/104946677/212743743-8029f74a-b245-415b-bdf8-766863d64d2f.png)
