### ISSUE TITLE
[APP] Gatekeeper API

### ISSUE THREAD

**Issue by PaulyboyUK1971** [PipedreamHQ/pipedream#5161]
**Name of app / service**
Gatekeeper - https://www.gatekeeperhq.com/
**Link to developer documentation**
https://knowledge.gatekeeperhq.com/en/docs/configuring-api
I can provide more info if required this is just a basic overview
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Nothing preventing me manually coding for the api but would like an app and I will look to code actions / components locally.
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @PaulyboyUK1971 ,

This is Sergio, I am collaborating with new app integrations. Currently, we can't easily get a Gatekeeper account.
Can you help providing the actual api docs that you can access under "/api_docs"?

> The API documentation is specific to each Gatekeeper tenant and can be found by simply appending your tenant URL with "/api_docs" just after the four-digit tenant number (e.g. '1234' in

Perhaps, with your browser you could print to pdf, and then attach this pdf here on a comment, or share it via a cloud drive?
i see the endpoint may display your unique key, so you may redact the api key there as well.

alternatively, send to sergio_eliot at pipekit.com

I will be able to integrate the app , I just need the proper request config expected. after that you will be able to test .

Thank you

**Comment by PaulyboyUK1971** [comment]
@sergioeliot2039 Sergio I work for Gatekeeper - I can create a demo instance for you if that helps

**Comment by sergioeliot2039** [comment]
awesome, that will be helpful!

**Comment by PaulyboyUK1971** [comment]
I've invited you to one of my tenants - please let me know you get the email ok

**Comment by sergioeliot2039** [comment]
i didn't get it, sorry i made a typo out of innerce, my correct inbox is sergio@pipekit.com, can you send the invite again

**Comment by PaulyboyUK1971** [comment]
Done!

**Comment by sergioeliot2039** [comment]
got it! will update soon

**Comment by sergioeliot2039** [comment]
![image](https://user-images.githubusercontent.com/25184117/211937198-c5329a9a-e73f-4c6c-965d-b57bcd3c8391.png)
🥴

**Comment by sergioeliot2039** [comment]
better now!

**Comment by sergioeliot2039** [comment]
@PaulyboyUK1971 here's Gatekeeper https://pipedream.com/apps/gatekeeper added to pd apps registry, good as basic framework for further integration

re  

> I will look to code actions / components locally

We're happy to answer any questions or support you in any way. Let us know, thank you!

**Comment by dannyroosevelt** [comment]
Thanks @PaulyboyUK1971, here is a basic integration for Gatekeeper:
https://pipedream.com/apps/gatekeeper

Can we help you getting some actions and triggers published on the public marketplace for all Pipedream users?

**Comment by PaulyboyUK1971** [comment]
@sergioeliot2039 thats perfect thankyou for your quick action
