### ISSUE TITLE
[BUG] ClickUp `get_task` does not filter events by Space and List

### ISSUE THREAD

**Issue by christian-manifest-movie** [PipedreamHQ/pipedream#5169]
**Describe the bug**
I’m using the ClickUp `get_task` step and I’m trying to only filter for new tasks in a specific Space and List but when I deploy the pipeline, all tasks that are created in all spaces perform an action. Is there a way to filter tasks properly in the get_task step?

https://pipedream-users.slack.com/archives/CPTJYRY5A/p1673556282048889

**To Reproduce**
1. set up Trigger for ClickUp new tasks and select a Workspace
2. use `get_task` step and select Workspace, Space, and List with Use custom task ids to False. Set task to `{{steps.trigger.event.event}}`.
3. Set up task to for Dropbox to create a new folder. 
4. New folder should be created when a new task is created 

**Expected behavior**
It should only create tasks within the Space and List selected but currently, it creates tasks for all tasks created in the entire Workspace.

**Screenshots**
<img width="981" alt="image (1)" src="https://user-images.githubusercontent.com/112592586/212195413-caf35ee6-bea7-49b6-aa90-b85a199d8902.png">

**Comment by andrewjschuang** [comment]
FYI about this issue and the person that will work on this:

Yes, the `taskId` inputted in the Task prop [won't actually be filtered](https://github.com/PipedreamHQ/pipedream/blob/master/components/clickup/actions/get-task/get-task.mjs#L21) by any of the previous prop values.
[What is being filtered](https://github.com/PipedreamHQ/pipedream/blob/master/components/clickup/actions/common/task-props.mjs#L29) are the `async options()` shown in the Task prop if previous props are selected.

So to fix this issue we would need to add these filters when calling `getTask()` or something like that.
The bad news is that the filtering behavior above - only in `async options()` - is replicated in most, if not all, actions in ClickUp.

**Comment by christian-manifest-movie** [comment]
@alysonturing Thank you so much! This works as expected!
