### ISSUE TITLE
[APP] GoToWebinar

### ISSUE THREAD

**Issue by laveryjoe** [PipedreamHQ/pipedream#5171]
GoToWebinar

https://developer.goto.com/GoToWebinarV2/

My workaround is using multiple platforms to connect different platforms lol

My needs are basic, just fire a trigger on new registrant on a specific webinar, any webinar, or any webinar containing X in the title etc.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
**App:**
GoToWebinar

**Trigger/Sources:**
Registrant Added
Registrant Joined

Developer center: https://developer.goto.com/GoToWebinarV2
Webhooks available: https://developer.goto.com/GoToWebinarV2/#tag/Webhooks
About Oauth authentication: https://developer.goto.com/guides/Get%20Started/02_HOW_createClient

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim app submitted for approval.

notes on outreach:
support contact form, then a call, to create an account. which errors out if they have records of the same IP attempting to previously create account

**Comment by malexanderlim** [comment]
@laveryjoe The base integration has been built, and we will be developing components shortly. Can you share which triggers and actions would be most useful for you?

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/gotowebinar

**Comment by sergio-eliot-rodriguez** [comment]
As per #6786 , the following components were created @laveryjoe, but let us knoe if you need anything else

**Actions**
Create Registrant
Create Webinar

**Sources**
New Registrant Added (Instant)
New Registrant Joined (Instant)
