### ISSUE TITLE
Add Exhibitor ExpoFP

### ISSUE THREAD

**Issue by mrdoosey** [PipedreamHQ/pipedream#5173]
Hi ExpoFP is already in Pipedream, can we look to add the"add exhibitor"  and list all events API please?

https://expofp.docs.apiary.io/#reference/0/add-exhibitor/add-exhibitor
https://expofp.docs.apiary.io/#reference/0/list-all-events/list-all-events

**Comment by GTFalcao** [comment]
This will be resolved in issue #5177
