### ISSUE TITLE
Updated column

### ISSUE THREAD

**Issue by Duermael** [PipedreamHQ/pipedream#5175]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by vunguyenhung** [comment]
Hi @Duermael, could you answer the question in the description for us to understand what needed to be done?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
