### ISSUE TITLE
ExpoFP Actions

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5177]
### App
expofp

### Actions
Add Exhibitor: https://expofp.docs.apiary.io/#reference/0/add-exhibitor/add-exhibitor
List All Events: https://expofp.docs.apiary.io/#reference/0/list-all-events/list-all-events

_Originally posted by @mrdoosey in https://github.com/PipedreamHQ/pipedream/issues/4596#issuecomment-1381952874_

**Comment by Hassan-Abbas-SQA** [comment]
### TEST PASSED
![image](https://user-images.githubusercontent.com/104946677/213533645-d0cc6e98-9b1e-47ab-9809-91698e86e585.png)
