### ISSUE TITLE
[TRIGGER] YouTube new comment and reply

### ISSUE THREAD

**Issue by AviVolah** [PipedreamHQ/pipedream#5179]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
YouTube new comment and reply

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.google.com/youtube/v3/docs/comments/list

---
Would like a YouTube comment Triger and action as well.. when a comment is added in the channel then something, and also when something happens then reply with a comment on YouTube.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
