### ISSUE TITLE
[ACTION]

### ISSUE THREAD

**Issue by Happychick** [PipedreamHQ/pipedream#5180]
**Is there a specific app this action is for?**
Yes! I am trying to build an app that puts together a graph of the most userd keywords in a graph
**Please provide a link to the relevant API docs for the specific service / operation.**
I am not able to authorize into Google Cloud. And so, it gives me a error 400. I set up the oauthid for the app.

**Comment by vunguyenhung** [comment]
Hello @Happychick, could you share the error message from your message? 

Could you try to follow the instruction and try to connect to Google Cloud again?
<img width="740" alt="image" src="https://user-images.githubusercontent.com/18277920/212694041-7e92d2c1-1421-42f0-9cc7-40c0183afbf3.png">

**Comment by Happychick** [comment]
I made it work! I have a new question now! How can I integrate the result
from my post request into a webflow page?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by Happychick** [comment]
Hello Dylan,

Basically I got my post request to work which produces a URL with an image
when the gloud function runs.

However, i don't know how to integrate the URL from the post request back
into Webflow. Like actually post the result of the post request, could you
help?

Christina Stejskalova <https://www.linkedin.com/in/christinastejskalova/>
Founder <http://www.hirelmns.com/> | Website
<https://christinas-sublime-portfolio.webflow.io/> | Articles
***@***.***>
646-724-8416
