### ISSUE TITLE
[APP] Seeking Alpha 

### ISSUE THREAD

**Issue by Legin1976** [PipedreamHQ/pipedream#5181]
**Name of app / service** Seeking Alpha 

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @Legin1976 , thanks for the request.

Is this the Seeking Alpha you are looking for, the investing website? https://seekingalpha.com/

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
