### ISSUE TITLE
[APP] Robinhood 

### ISSUE THREAD

**Issue by Legin1976** [PipedreamHQ/pipedream#5182]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @Legin1976 , thanks for the request.
Is this the Robinhood you are looking for - https://robinhood.com/us/en/ ?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
