### ISSUE TITLE
[ACTION] Trello - Timeout/delay option needed for Trello sources

### ISSUE THREAD

**Issue by jpsweeney94** [PipedreamHQ/pipedream#5185]
**Is there a specific app this action is for?**
Trello

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developer.atlassian.com/cloud/trello/rest/api-group-actions/ 

Trello has automation features that trigger after certain actions. E.g. i have it set so labels are automatically added or removed when moved to and/or from certain lists. This can take some time to take effect (usually within 1 minute - occasionally more), which causes the sources from Pipedream to be inaccurate. The data that gets sent won't have the updated labels for example.

Can you add an option for a user defined time out or something?

**Comment by vunguyenhung** [comment]
Hello @jpsweeney94, I think adding delay is not really possible, as Pipedream is highly dependent on Trello event webhook. So whenever Pipedream received a webhook request from Trello, it will emit a new event asap (and the data is only up-to-date in that moment).

For your usecase, is it possible to migrate the Trello actions to Pipedream? If not, could you tell us what Pipedream's missing?

**Comment by jpsweeney94** [comment]
Hi, thanks for your reply.

Hmm I hadn't considered moving the label automation to pipedream and/or wasn't sure pioedream had that capability. 

I will look into that solution then, thanks!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
