### ISSUE TITLE
[BUG] bingx_trade_batch_cancel_orders failed to work

### ISSUE THREAD

**Issue by s1248** [PipedreamHQ/pipedream#5186]
**Describe the bug**
bingx_trade_batch_cancel_orders failed to work
https://github.com/PipedreamHQ/pipedream/tree/master/components/bingx/actions/trade-batch-cancel-orders

**To Reproduce**
See error: Invalid parameters, err:Key: 'BatchCancelOrderRequest.OrderIDs' Error:Field validation for 'OrderIDs' failed on the 'min' tag

**Expected behavior**
I want to cancel all pending orders of symbol ADA-USDT.

**Screenshots**
![image](https://user-images.githubusercontent.com/76787070/212539142-5d296d1d-a046-4551-bfbc-9d4181f449cb.png)

**Comment by vunguyenhung** [comment]
I can reproduce this bug
<img width="910" alt="image" src="https://user-images.githubusercontent.com/18277920/212693612-5920e900-1682-40b6-b090-6422b630af37.png">

Adding this to Pipedream prioritized backlog
