### ISSUE TITLE
Papertrail

### ISSUE THREAD

**Issue by JoseMoranUrena523** [PipedreamHQ/pipedream#5187]
**Name of app / service**
Papertrail
**Link to developer documentation**
https://www.papertrail.com/help/papertrail-documentation/
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, I am trying to send my console logs to Discord with Papertrail but I can't.
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I would like to see if every console log can be sent to like any app, for example, Discord.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there, Papertrail has been previously integrated https://pipedream.com/apps/papertrail?via=go
