### ISSUE TITLE
Zoho Campaigns

### ISSUE THREAD

**Issue by mrbm** [PipedreamHQ/pipedream#5189]
**Name of app / service**
Zoho Campaigns

**Link to developer documentation**
https://www.zoho.com/campaigns/help/developers/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
The oauth integration you do for all other zoho apps you could do with this

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Wanting to add new or old contact to list which requires pre-setting (or could receive) list ID, email (optionally firstname lastname phone, etc)

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.
