### ISSUE TITLE
[APP] Loyverse

### ISSUE THREAD

**Issue by KaruppuTiger** [PipedreamHQ/pipedream#5191]
Loyverse

https://developer.loyverse.com/docs/
Oauth integration method supported: https://developer.loyverse.com/docs/#section/Authorization
I would like to be able to have record sales made here on to big query or something that I move to a SQL or a google sheet

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by malexanderlim** [comment]
@KaruppuTiger Loyverse is now available on Pipedream!

**Comment by KaruppuTiger** [comment]
awesome greatnews
