### ISSUE TITLE
[APP] SalesMate (CRM)

### ISSUE THREAD

**Issue by teamcoltra** [PipedreamHQ/pipedream#5199]
**Name of app / service** SalesMate

**Link to developer documentation** https://apidocs.salesmate.io/

**Is lack of support preventing you from building workflows, or do you have a workaround?** I currently have this built out in PHP on my own system but having integration into Pipedream will allow me to do more.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** All the API endpoints on v4 are important they have additional features in older API versions (weird, IMO) but the v4 stuff is all fairly important.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
App submitted for approbal https://pipedream.com/admin/apps/salesmate

**Comment by dannyroosevelt** [comment]
@teamcoltra here is a basic integration for Salesmate:
https://pipedream.com/apps/salesmate

Can you let us know if that's working for you?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
