### ISSUE TITLE
Use any X API with Python Configuration Bug

### ISSUE THREAD

**Issue by reedwi** [PipedreamHQ/pipedream#5204]
I have been experiencing the following annoyance when working with “Use any X API in Python” step for certain APIs. The issue has occurred with HubSpot and GitHub, but may be occurring for more. I initially configure the step to be associated with a specific account for either service. I then write the code and test. If I then need to update the code, it loses the configuration and requires me to select the specific account again. It does this every time I subsequently edit the code block. The recording shows this happening. Obviously this isn’t the end of the world, but it is very annoying to deal with. I am on Mac and have used Safari and Chrome and gotten the same result in both browsers.

**Desktop**
 - Device: Mac
 - OS: Ventura 13.1
 - Browser: Safari and Chrome

https://user-images.githubusercontent.com/65463278/212928225-65a7815f-47e8-4f7c-893e-9816be22fda9.mp4

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
