### ISSUE TITLE
[APP] Braze

### ISSUE THREAD

**Issue by tthias** [PipedreamHQ/pipedream#5214]
**Name of app / service**
Braze

**Link to developer documentation**
https://www.braze.com/docs/developer_guide/home

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I can use API endpoints as a workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Actions :
User Track
https://www.braze.com/docs/api/endpoints/user_data/post_user_track/

**Comment by dannyroosevelt** [comment]
@tthias here is a basic integration -- can you help validate this is working end to end?
https://pipedream.com/apps/braze/

**Comment by tthias** [comment]
Hey,

Amazing speed !

I'm in the EU so my API endpoint finishes ".eu" (https://rest.fra-02.braze.eu)

I get this error : 
getaddrinfo ENOTFOUND rest.fra-02.braze.com

**Comment by dannyroosevelt** [comment]
Ah thanks for pointing that out. If you remove and re-add the app's code scaffolding step, then attempt to connect your account again, you should see the option to choose US or EU.

Let me know if that works.

**Comment by tthias** [comment]
It works great thanks !

**Comment by dannyroosevelt** [comment]
Good to hear! By the way, all Pipedream actions use a Source Available license and are hosted on GitHub -- are you interested in developing some of these on your own?

This is a good place to start: https://pipedream.com/docs/components/guidelines/#getting-started

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
Tracking components here: https://github.com/PipedreamHQ/pipedream/issues/5345
