### ISSUE TITLE
[FEATURE] Send the `response` property to the global error handler for AxiosErrors

### ISSUE THREAD

**Issue by jc-tzn** [PipedreamHQ/pipedream#5218]
**Is your feature request related to a problem? Please describe.**
I have a workflow, called Error Handler, that is triggered anytime any other workflows has an uncaught exception. 

Among other things, the Error Handler logs the properties of the error for debugging. This works well for most errors except those triggered by Axios.

For most errors, the message and the stack trace are enough to debug but for some AxiosError there is another property that is really useful: `error.response`. For example:

```
{
  message: 'Request failed with status code 400',
  name: 'AxiosError',
  code: 'ERR_BAD_REQUEST',
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {...},
    data: { 
      error: {
        message: 'Unsupported post request...',
        type: 'GraphMethodException',
        code: 100,
      }
    }
  }
}
```

**Describe the solution you'd like**
The response property (when it exists) should be sent to the error handler along with the message and the stack trace.

**Do you have a workaround?**
Wrapping every Axios requests in a try-catch then throwing a new error with the response property concatenated to the message property.

**Comment by andrewjschuang** [comment]
@jc-tzn do you generally use `@pipedream/platform axios` or vanilla `axios` in your workflows?
Or are them in Pipedream Components?

A good candidate for modifying this approach is in the [`@pipedream/platform axios`](https://github.com/PipedreamHQ/pipedream/blob/master/platform/lib/axios.ts#L109) error handling.

**Comment by jc-tzn** [comment]
Hi @andrewjschuang,

Thanks for your answer. I just tried replacing the vanilla `axios` by `@pipedream/platform axios` and I still only have the error message "Error - Request failed with status code 400" but indeed now I have the detail in the promise response:

![axios-error](https://user-images.githubusercontent.com/3951735/213728687-13293ffb-ba00-44b5-8e6f-4edfff931cc0.jpg)

However, in the global error handler there is still only the error message and stack trace:

![error-handler](https://user-images.githubusercontent.com/3951735/213728976-30e24e4a-0321-4ca0-88d7-88ae7ac052fa.jpg)

The details of the error are still not transferred to the error handler.

**Comment by andrewjschuang** [comment]
> The details of the error are still not transferred to the error handler.

Thanks for the context info. Yes, a change will still be needed but in this case it seems a pretty simple one.

**Comment by andrewjschuang** [comment]
Hi @jc-tzn, can you please test this version?

`import { axios } from "@andrewcturing/platform@1.2.17";`

**Comment by jc-tzn** [comment]
Tried it and it works great, thank you 🙌

**Comment by andrewjschuang** [comment]
Successfully tested by the customer.
