### ISSUE TITLE
Increase payload property size limit beyond 512Kb

### ISSUE THREAD

**Issue by mageshpdy007** [PipedreamHQ/pipedream#522]
Hi Pipedream,
Increase the HTTP payloads Size up to the length of the email they are received. The automated email from sites are truncated into a block of the mails. Please increase the HTTP  payload of email to large for paid plans.

**Comment by cmorisse** [comment]
Hello,
Same problem here.  I won't be able to use pipedream on project due to 512Ko Payload limit.
Could you please add a paid option to allow bigger Payloads ?
Regards,

**Comment by dylburger** [comment]
@cmorisse do you have control over the HTTP request? That is, does it come from a system you own, or does it come from a third party (e.g. a webhook)?

You can use our ["large file" API](https://docs.pipedream.com/workflows/steps/triggers/#large-file-support) to send large data, like files and other objects, by sending the data as a part of a `multipart/form-data` request:

```bash
curl -F 'image=@my_image.png' https://myendpoint.m.pipedream.net
```

Let me know if that option might work for you.

**Comment by cmorisse** [comment]
I read this part of the documentation.
But no I have no control on the payload structure. 
In my use case, Pipedream would receive HTTP message from a legacy system that sends huge packet of data in XML. And the rework of the emitter program is not an option.

**Comment by dylburger** [comment]
Thanks for confirming, that’s helpful to know. We’re considering handling larger payloads and we’ll post any updates here.

**Comment by dylburger** [comment]
@cmorisse and @mageshpdy007 - we've simplified the interface for sending large payloads. You can now send an HTTP payload of any size to a workflow or an event source by including the `pipedream_upload_body=1` query string or an `x-pd-upload-body: 1` HTTP header in your request.

```bash
curl -d '{ "name": "Yoda" }' \
  https://endpoint.m.pipedream.net\?pipedream_upload_body\=1

curl -d '{ "name": "Yoda" }' \
  -H "x-pd-upload-body: 1" \
  https://endpoint.m.pipedream.net
```

In workflows, Pipedream saves the raw payload data in a file whose URL you can reference in the variable `steps.trigger.event.body.raw_body_url`.

[Read the docs for more information and examples](https://docs.pipedream.com/workflows/steps/triggers/#sending-large-payloads).

**Comment by cmorisse** [comment]
Got it ! (and nice!!!)

**Comment by mageshpdy007** [comment]
Thanks a lot and nice to hear from you
