### ISSUE TITLE
Rebrandly

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5221]
### App
Rebrandly
https://developers.rebrandly.com/

### Triggers
New click received

**Comment by Hassan-Abbas-SQA** [comment]
Trigger is not firing any event on clicks 
![image](https://user-images.githubusercontent.com/104946677/213822183-65c8424b-c3f8-473d-ad42-b97761896d78.png)
![image](https://user-images.githubusercontent.com/104946677/213822200-e245d160-52b7-4f02-8ded-af1010332c95.png)

**Comment by Hassan-Abbas-SQA** [comment]
TEST PASSED
![image](https://user-images.githubusercontent.com/104946677/213866135-3e1c1891-8648-4e47-8301-f542bb309da2.png)

**Comment by dannyroosevelt** [comment]
I shared this new source with the user who requested it and they have 2 points of feedback:

>While I am seeing the click count data being reported, whats missing is the additional info that Rebrandly reports - Unique and Non Unique clicks. Can you please check if you are receiving that data from Rebrandly? I know Zapier receives that data. Let me know if you need additional information or screenshots.
@Hassan-Abbas-SQA can you check out what additional metadata Zapier is pulling in to their step export for these events? Maybe we can enrich the data our trigger is returning, to make it more useful.


>I made a new source, and it initially showed 9 click datas, it has not updated since then. I even checked, it is trying to get more data. Meanwhile new rebrandly click events have come into zapier.
@Hassan-Abbas-SQA can you see if there is a bug? (screenshots below)

![image](https://user-images.githubusercontent.com/20780753/214137987-25430a0b-c0c7-4faf-942b-2d5ced096919.png)

![image](https://user-images.githubusercontent.com/20780753/214138010-b902f323-8069-459a-8488-b42f64a9cf23.png)

**Comment by Hassan-Abbas-SQA** [comment]
@dannyroosevelt  Unique and NonUnique fields missing in our pipedream trigger, confirmed that Zapier is getting these fields data

<img width="860" alt="image" src="https://user-images.githubusercontent.com/104946677/214143017-adb185a6-0508-45bf-9d30-a507014b16df.png">
for issue of not receiving events after 9/10 events iam still trying to reproduce this issue at my end and no i cannot see any bugs/errors in the screenshot attached.

**Comment by michelle0927** [comment]
@dannyroosevelt @Hassan-Abbas-SQA My guess is that Zapier is using AWS to receive click events through a [webhook](https://developers.rebrandly.com/docs/click-events#webhooks-and-click-aware-integrations). Using [polling](https://developers.rebrandly.com/docs/get-link-details), I don't see a way to specify which properties to return. Maybe this is one where we should use an appHook?
