### ISSUE TITLE
xmpp

### ISSUE THREAD

**Issue by fvcoutinhoapp** [PipedreamHQ/pipedream#5227]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @fvcoutinhoapp .
Thanks for your request?

Can You please provide the app's website you'd like to see integranted?
I need this to look for the api, or request acess, SO that I can create the integraron?

**Comment by fvcoutinhoapp** [comment]
Hi,

I have a communicator and would like to send a message using the XMPP
protocol to send a message, is this possible?

thanks

Fernando Coutinho

Em qua., 18 de jan. de 2023 às 23:05, Sergio E. Rodríguez Wong <
***@***.***> escreveu:

**Comment by sergioeliot2039** [comment]
Yes, it is possible,

for instance, you can use a Node.JS library implementing the XMPP protocol such as [node-xmpp](https://cubettech.com/resources/blog/xmpp-chat-using-node-js/).

you could have Pipedream run your node.js code https://pipedream.com/apps/node

would this be helpful for your use case?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
