### ISSUE TITLE
Grist[APP]

### ISSUE THREAD

**Issue by Have-a-great-day** [PipedreamHQ/pipedream#5228]
**Name of app / service**
Grist

**Link to developer documentation**
https://support.getgrist.com/api/#tag/records/paths/~1docs~1%7BdocId%7D~1tables~1%7BtableId%7D~1records/get

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No, I don't think so.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Not yet. Cool, thanks.

**Comment by vunguyenhung** [comment]
Hello @Have-a-great-day,

As I see currently there's a Grist app here
<img width="918" alt="Screen Shot 2023-01-19 at 20 43 57" src="https://user-images.githubusercontent.com/18277920/213458600-b28fcfef-7ce0-4ab4-b7c6-74582484c241.png">

May I ask which specific action/source that you need?

**Comment by Have-a-great-day** [comment]
Hi,

Thank you.

I was looking to set a trigger based on a Grist column but managed to do it using a webhook and Grist’s REST API which has some endpoints which are still in development for this use case.

Have a great day,

GABRIEL PILLAY Junior Software Engineer
+27 83 646 4228 | www.finovate.co.za<http://www.finovate.co.za/>
2nd Floor, Waterstone Office Park, Suite 4, Somerset West, 7130
***@***.***

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
