### ISSUE TITLE
[APP] Thanks.io

### ISSUE THREAD

**Issue by digiproductmarketer** [PipedreamHQ/pipedream#523]
**Name of app / service**
- Thanks.io

**Link to developer documentation**
- https://documenter.getpostman.com/view/4566474/SzYUagpS?version=latest

**Is lack of support preventing you from building workflows, or do you have a workaround?**
- Current workaround is to use Zapier

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- Send Postcard
- Send Letter
- Create Recipient
- Update Recipient

**Comment by todsac** [comment]
@digiproductmarketer - this app is integrated.  here is a sample workflow -- https://pipedream.com/@tod/p_ezCoLx/

You can add the actions to the app now.  Let us know if you need help.

**Comment by todsac** [comment]
This has been completed.
