### ISSUE TITLE
[BUG][TRIGGER] Google Sheets: New Updates (Shared Drive, Instant), events delay issue

### ISSUE THREAD

**Issue by MRD800** [PipedreamHQ/pipedream#5256]
When testing the trigger New Updates (Shared Drive, Instant) from Google Sheets, If a change any cell in the worksheet, sometimes pipedream receives the trigger inmediatly but sometimes it has minute or two of dealy.

Is there any issue with the integration with Google Sheet?

**Comment by andrewjschuang** [comment]
@MRD800 it is normal procedure, since in this trigger quite a few requests to Google API are made after receiving the event. That is the reason for the delay. Does that impact you severely?

**Comment by MRD800** [comment]
Yes, unfortunately I need inmediate trigger.. Sent from my iPhoneOn 24/01/2023, at 11:01 AM, Andrew Chuang ***@***.***> wrote:﻿
@MRD800 it is normal procedure, since in this trigger quite a few requests to Google API are made after receiving the event. That is the reason for the delay. Does that impact you severely?

**Comment by dannyroosevelt** [comment]
Hi @MRD800 I believe there is some debouncing that happens on Google's end before they send a push notification, in order to cut down on the noise that updating a spreadsheet would cause.

**Comment by MRD800** [comment]
Do you have any other trigget to get data instantly from google sheet?Sent from my iPhoneOn 24/01/2023, at 1:55 PM, Danny Roosevelt ***@***.***> wrote:﻿
Hi @MRD800 I believe there is some debouncing that happens on Google's end before they send a push notification, in order to cut down on the noise that updating a spreadsheet would cause.

**Comment by dannyroosevelt** [comment]
Can you tell me more about your specific use case?

**Comment by MRD800** [comment]
Sure.
Basically, what I do is:

   - I send a few trade alerts with some specific info from tradingview
   webhook to google sheet (Adding a row)
   - Then depending on several conditions I formulate in the google sheet,
   whenever the conditions met I need to send an immediate alert to telegram
   to create a "Buy" or "Sell" Trade signal
   - So in summary, Tradingview --> Google Sheet --> (Sheet Analyze 3
   conditions are met) --> If yes, send an alert to telegram.

So, if there is any dealy in the signal from Google Sheet to Telegram, It
would not work for the purpose of this workflow.

If you have any idea! more then welcome!

Thanks

DM

**Comment by dannyroosevelt** [comment]
I don't think a Google Sheets trigger is going to be the best solution for this, but I might recommend trying to engage other members in the community either [here in Discourse](https://pipedream.com/community) or on [Slack](https://pipedream-users.slack.com/archives/CPTJYRY5A).
