### ISSUE TITLE
[FEATURE][ACTION] Blogger : create post action new prop

### ISSUE THREAD

**Issue by MohGPT** [PipedreamHQ/pipedream#5259]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**
hi
it would be nice if you added an ipunt tag for blogger
Thank
![2023-01-20_16h15_29](https://user-images.githubusercontent.com/123235069/213858995-87fd5359-1943-43ca-b5cb-3b923f4e6cad.png)

**Comment by Jehan-h20220012** [comment]
I want to work on it, I dont have all the knowledge but will work on it.
