### ISSUE TITLE
[BUG] PostgreSQL "New Row" trigger fails to connect when SSL is required on database

### ISSUE THREAD

**Issue by george-bitdotio** [PipedreamHQ/pipedream#5290]
**Describe the bug**
When attempting to use the PostgreSQL integration, certain triggers, namely the "New Row" trigger, fail to connect to the database, while others are working ("New Table", for example). The observed error is:
```
Error:
Connection terminated unexpectedly
    at Connection.<anonymous> (/var/task/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (events.js:519:28)
    at Connection.emit (events.js:400:28)
    at Socket.<anonymous> (/var/task/node_modules/pg/lib/connection.js:107:12)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

I believe this is due to certain queries in the trigger not respecting the user's selection of the `rejectUnauthorized` flag and therefore not connecting using SSL.

**To Reproduce**
1. Create a database on [bit.io](https://bit.io)
2. Attempt to create a new source using the "New Row" trigger on one of the tables in your database
3. See error

**Comment by Hassan-Abbas-SQA** [comment]
@george-bitdotio I am able to reproduce the bug
![image](https://user-images.githubusercontent.com/104946677/214375092-f35e8c16-c4e4-4959-a2a4-409ca7326b4f.png)

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia iam still facing the issue
![image](https://user-images.githubusercontent.com/104946677/214906363-f40bb171-9a61-4d14-84ba-ac52c1584a6b.png)

**Comment by lcaresia** [comment]
@Hassan-Abbas-SQA Hey! To work you need set `Reject Unauthorized` as `false` to work. This is some rule of bit.io

**Comment by Hassan-Abbas-SQA** [comment]
> @Hassan-Abbas-SQA Hey! To work you need set `Reject Unauthorized` as `false` to work. This is some rule of bit.io

![image](https://user-images.githubusercontent.com/104946677/214911435-6fa00898-b59f-4976-a068-cc4266ea46ad.png)

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia i was able to create source but getting this error 
![image](https://user-images.githubusercontent.com/104946677/214945472-16e227a8-372e-4f94-ba7d-92b188d928b8.png)

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia TestPassed 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/104946677/215284728-14279b0b-75a9-4c3d-a316-92baecc048c3.png">
<img width="820" alt="image" src="https://user-images.githubusercontent.com/104946677/215284737-8f9df071-7a50-4e03-894f-fb1353a16999.png">

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia the changes you made it worked correctly now its good as customer wanted the trigger to be @george-bitdotio but there is still a minor issue 
if i have not setup RejectUnAuthorized prop to False its giving me error which is a good thing but please make this trigger error information a bit useful for user so they can understand why exactly their trigger failed instead of only showing information "Connection interrupted Unexpectedly "
![image](https://user-images.githubusercontent.com/104946677/215538469-c619fad0-fbd2-487a-937e-caf5fbb42670.png)
