### ISSUE TITLE
Badger Maps

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5294]
### App
Badger Maps
https://pipedream.com

### Triggers
TBD

### Actions
TBD

**Comment by dannyroosevelt** [comment]
No public API, sent an email to their support@ alias.

**Comment by sergioeliot2039** [comment]
There's a user request for Badger Maps app and actions on #5356

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/badger-maps
