### ISSUE TITLE
[SOURCE] Add Emoji prop to New Reaction Added Slack Source

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5299]
Let's add an optional prop to the New Reaction Added Slack Source so users can filter events on the specific emoji(s) they care about.

**Comment by Hassan-Abbas-SQA** [comment]
![image](https://user-images.githubusercontent.com/104946677/214391390-670108cb-0983-4c89-83c9-d33a5a95eba1.png)
