### ISSUE TITLE
[APP] Interact Quizzes

### ISSUE THREAD

**Issue by roastgarlic** [PipedreamHQ/pipedream#5304]
**Name of app / service**
Interact

**Link to developer documentation**
https://www.tryinteract.com/integrations/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
preventing me from building workflows

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
I'd like to tag contacts with what questions they've chosen and which result they're given

**Comment by sergioeliot2039** [comment]
Can't indetify if there is an API with Interact, I reached out to their support about whether they have an API

**Comment by roastgarlic** [comment]
Agh, turns out the API isn’t public and they’re not making it public
anytime soon.

Thanks anyways

**Comment by sergioeliot2039** [comment]
Yeah that's what they said. I'll mark it as blocked for now. They'll look out to integrate with Pipedream.
