### ISSUE TITLE
[ACTION] Data Stores "Check for existence of key" should include a boolean if the record existed

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#5307]
The Data Stores action [Check for existence of key](https://pipedream.com/apps/data-stores/actions/has-key-or-create) should include in the return value a boolean indicating if the record had already existed.

This can be handled by parsing the summary value for the text it says, but this doesn't seem like the right approach.

The use case is a DB where you check if a value exists (and create it if not), you want to conditionally process different step(s) if the record was just created or if it had already existed.

**Comment by dannyroosevelt** [comment]
Oh that's a good idea. So, something like this?
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/214373798-cfa1001d-c10f-462f-a93a-5243e29460bf.png)
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/214373830-145b0edc-aeb0-403f-9b77-463ab31807bd.png)
