### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by pedronw** [PipedreamHQ/pipedream#5311]
**Name of app / service**
Bitrix24 - Brazil (**.com.br**)

**Link to developer documentation**
https://training.bitrix24.com/rest_help/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Today Pipedrem already has a connection with Bitrix24, but it is only for Bitrix24.com.

The Brazilian community that uses Pipedream and Bitrix24.com.**br** would be very grateful if you made this option available (connection to the BR system).

**Comment by dannyroosevelt** [comment]
@pedronw does Bitrix have documentation related to supporting different top level domains? Does it impact the endpoints used during the OAuth flow?

**Comment by sergioeliot2039** [comment]
Bitrix has been requested previouslly on https://github.com/PipedreamHQ/pipedream/issues/4053

**Comment by pedronw** [comment]
> @pedronw does Bitrix have documentation related to supporting different top level domains? Does it impact the endpoints used during the OAuth flow?

**To be honest, I understand little about API and programming, but I'm researching a lot on the subject to be able to be assertive here in the answers here.**

**About the first question:** https://www.bitrix24.com.br/apps/dev.php
   - Bitrix24 provides documentation in Brazil (.com.br) - as shown in the link above

**Second question:** I couldn't understand what you wanted to ask... Sorry :(

Maybe this can help: another platform called **Make** (**Integromat**), makes the connection with Bitrix24 regardless of whether it is .com or .com.br

In Pipedrem, you only have the .com option

**Example:** Your intranet_name can be found in your domain such as https://{intranet_name}.bitrix24.com/

Hope this can help.

**Comment by pedronw** [comment]
> Bitrix has been requested previouslly on #4053

Thank you for your attention Sergio, but my question here is about the connection between Bitrix24 (.com.br) and Pipedream.

Pipedrem currently only connects with **.com** links.

**Comment by dannyroosevelt** [comment]
@pedronw we've updated the app to support the full domain URL, including `.com.br` -- can you give it a try and see if it works for you?

**Comment by dannyroosevelt** [comment]
Here's a ticket for the team to develop some pre-built components: https://github.com/PipedreamHQ/pipedream/issues/5363

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
