### ISSUE TITLE
Reviews.IO

### ISSUE THREAD

**Issue by mrdoosey** [PipedreamHQ/pipedream#5316]
Reviews.IO

https://developer.reviews.io/reference/6016f82ea907a95f8af6e769e8c16b3b
Queue Product and Company Invitations
https://api.reviews.io/invitation

**Comment by dannyroosevelt** [comment]
@mrdoosey here is a basic integration:
https://pipedream.com/apps/reviews-io

Can you check this out and see if it works for you? We aren't able to create an account on their site right now, it looks like they may be having some issues.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by mrdoosey** [comment]
Sorry yes this is working
