### ISSUE TITLE
[Components] Salesmate

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5321]
https://apidocs.salesmate.io/

### Triggers
New Contact
New Opportunity

### Actions

Add Contact
Update Contact
Add Opportunity

**Comment by dannyroosevelt** [comment]
**Triggers**
1. New Contact - https://help.salesmate.io/en/articles/3102086-webhooks-new-contact
2. New Opportunity - https://help.salesmate.io/en/articles/3102077-webhooks-new-opportunity

**Actions**
1. Add Contact - https://help.salesmate.io/en/articles/3102088-rest-api-add-contact
2. Update Contact - https://help.salesmate.io/en/articles/3102090-rest-api-update-contact
3. Add Opportunity - https://help.salesmate.io/en/articles/3102079-rest-api-add-opportunity

**Comment by luancazarine** [comment]
> /components salesmate

I don't know how but it came in merge with master and I tried to remove it but if you see the changes are just comma addition so if I remove them I can't commit because lint returns error
