### ISSUE TITLE
[BUG] Hubspot update contact fails when no value

### ISSUE THREAD

**Issue by roggernaut** [PipedreamHQ/pipedream#5324]
**Describe the bug**
Hubspot Action "Update contact" fails when there is no value sent

**To Reproduce**
1. Send a partially complete data source to the Hubspot action
2. Cannot read property 'data' of undefined

**Expected behavior**
This action should only attempt to send when it can find the data and gracefully ignore empty fields

**Comment by Hassan-Abbas-SQA** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/104946677/214898148-df1fcd69-f78f-4ce7-9784-06a79417ddce.png">
<img width="596" alt="image" src="https://user-images.githubusercontent.com/104946677/214898914-730281dd-4bbf-48dd-b842-3bc0f93ed71c.png">
it worked for me when i sent partial data to form

**Comment by roggernaut** [comment]
Hi @Hassan-Abbas-SQA, it's giving the following error:

The app is https://github.com/PipedreamHQ/pipedream/blob/master/components/hubspot/actions/update-contact/update-contact.mjs

The input property is this:
![image](https://user-images.githubusercontent.com/8107206/215036239-81f29365-3be4-434c-b4c0-5b3d9cf9ef7b.png)

This information is not always available from the previous step.

The resulting error is this:
```
TypeError
Cannot read property 'companyLogo' of undefined

DETAILS
TypeError: Cannot read property 'companyLogo' of undefined
    at eval (eval at _pd_deep_evaluate (/var/task/params_evaluator.js:57:18), <anonymous>:1:73)
    at _pd_deep_evaluate (/var/task/params_evaluator.js:57:18)
    at MessagePort.<anonymous> (/var/task/params_evaluator.js:11:9)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
```

My expectation would be for it to simply ignore empty variables and continue to variables taht

**Comment by Hassan-Abbas-SQA** [comment]
> 

Thank you for the clarification  as i can see now yes we can simply ignore the empty fields to throw any error if any field is empty/leftover

**Comment by Hassan-Abbas-SQA** [comment]
> Hi @Hassan-Abbas-SQA, it's giving the following error:
> 
> The app is https://github.com/PipedreamHQ/pipedream/blob/master/components/hubspot/actions/update-contact/update-contact.mjs
> 
> The input property is this: ![image](https://user-images.githubusercontent.com/8107206/215036239-81f29365-3be4-434c-b4c0-5b3d9cf9ef7b.png)
> 
> This information is not always available from the previous step.
> 
> The resulting error is this:
> 
> ```
> TypeError
> Cannot read property 'companyLogo' of undefined
> 
> DETAILS
> TypeError: Cannot read property 'companyLogo' of undefined
>     at eval (eval at _pd_deep_evaluate (/var/task/params_evaluator.js:57:18), <anonymous>:1:73)
>     at _pd_deep_evaluate (/var/task/params_evaluator.js:57:18)
>     at MessagePort.<anonymous> (/var/task/params_evaluator.js:11:9)
>     at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
>     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
> ```
> 
> My expectation would be for it to simply ignore empty variables

can you please share the configuration of your Action please

**Comment by roggernaut** [comment]
Hi, this is the configuration. For the data source variations check here: https://docs.reversecontact.com/enriched_profile_check#basic-profile-check

```
HubSpot Account:
HubSpot
Object ID:
{{steps.trigger.event.id}}
Property Groups:
Enrichment (enrichment)
Email Account Type:
{{steps.reversecontact.$return_value.emailType}}
LinkedIn Profile:
{{steps.reversecontact.$return_value.person.linkedInUrl}}
LinkedIn Company EmployeeCount:
{{steps.reversecontact.$return_value.company.employeeCount}}
LinkedIn Company Logo:
{{steps.reversecontact.$return_value.person.positions.positionHistory[0].companyLogo}}
LinkedIn Company Name:
{{steps.reversecontact.$return_value.company.name}}
LinkedIn Company URL:
{{steps.reversecontact.$return_value.company.websiteUrl}}
LinkedIn Profile Current Position:
{{steps.reversecontact.$return_value.person.positions.positionHistory[0].title}}
LinkedIn First Name:
{{steps.reversecontact.$return_value.person.firstName}}
LinkedIn Profile Headline:
{{steps.reversecontact.$return_value.person.headline}}
LinkedIn Last Name:
{{steps.reversecontact.$return_value.person.lastName}}
LinkedIn Profile Location:
{{steps.reversecontact.$return_value.person.location}}
```

**Comment by Hassan-Abbas-SQA** [comment]
> 

sir did you try deleting your action and recreating it?

**Comment by roggernaut** [comment]
Yes, I did - the same issue persists

**Comment by Hassan-Abbas-SQA** [comment]
@roggernaut how did you got this property seems like i can’t find it are you entering it as custom property ?
Property Groups:
Enrichment (enrichment)
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/104946677/215795718-29a01bd0-0b3a-491e-9d4f-a87cb992b8d9.png">

**Comment by roggernaut** [comment]
Those properties are dynamically pulled from Hubspot so they will be different for each instance

**Comment by Hassan-Abbas-SQA** [comment]
@roggernaut i got the error its about the data is empty in the step you are calling from 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/104946677/215801819-d902c613-ceab-491f-8181-f51288aae7e9.png">
thats why it throwing this error

**Comment by roggernaut** [comment]
That is correct. Is this intended behavior? I would not expect it to just fail entirely if this happens.

**Comment by roggernaut** [comment]
In this case, how would you deal with data in a step that is different on each request? Do you have a recommended work-around?

**Comment by Hassan-Abbas-SQA** [comment]
> In this case, how would you deal with data in a step that is different on each request? Do you have a recommended work-around?

i would recommend writing a custom script in Python/Nodejs which will read the data from previous step and filter out the key that is needed in your case "Company Logo" and it will return a constant step param to the hubspot action so you will never get any kind of error, because in that script you will handle the filter yourself that if "CompanyLogo" key doesnot appear then return an empty string or find the companyLogo key from anywhere in the previous step. that should work

**Comment by Hassan-Abbas-SQA** [comment]
@roggernaut sir i have written a Python Code for you to find the defined key like "CompanyLogo" from your previous step if it couldn’t find the key from the data it will return empty string so atleast your Hubspot action will never fail 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/104946677/215821687-483f491f-ceca-4e49-8e14-3bd998be241a.png">
`def findkeys(node, kv):
    if isinstance(node, list):
        for i in node:
            for x in findkeys(i, kv):
               yield x
    elif isinstance(node, dict):
        if kv in node:
            yield node[kv]
        for j in node.values():
            for x in findkeys(j, kv):
                yield x

def handler(pd: "pipedream"):
  data = pd.steps["python"]["$return_value"]["person"] #here copy and paste your step data path
  Keys = list(findkeys(data, 'companyLogo')) #which key to find from the data
  # Return data for use in future steps
  if Keys == []:
    return {"FinalKey":""}
  return Keys # make it to Keys[0] to get the first logo url

`
