### ISSUE TITLE
[TRIGGER] Telegrambot Signal Alerts

### ISSUE THREAD

**Issue by RagingAdmin** [PipedreamHQ/pipedream#5327]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
I want Crypto Signals from a Telegram Channel to place trades on ByBit automatically.

I should be able to connect to my Telegram Account and select the channel (Private/Subscripted Channel), and have the telegram bot monitor for signals. Then need the Pipedream to take that signal, and automatically place it on ByBit.

Example of signal:
🔥 #ALPHA/USDT (Long📈, x20) 🔥

Entry - 0.14980
SL - 5-7%

Take-Profit:
🥇 0.152796 (40% of profit) 
🥈 0.154294 (60% of profit)
🥉 0.155792 (80% of profit)
🚀 0.15729 (100% of profit)

Goal here is to create a ByBit Trade based on this.

I would need to set a limit on how much to put in, like $10 USDT.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
N/A

**Comment by Hassan-Abbas-SQA** [comment]
Hello @RagingAdmin you need a telegram trigger which will be looking for your buy/sell signals from your telegram channel and emits an event whenever it receives a new signal to create order and then you need a Bybit action to create order based on signal you received from telegram trigger/source

**1: Telegram Trigger choose any based on your needs to emit events based on signal received**
<img width="443" alt="image" src="https://user-images.githubusercontent.com/104946677/215203665-51f0e857-085e-4a88-ac8b-6f6f95cb1310.png">

middleware processing script which will read the message and extract the exact information that is needed to create an order then it will pass it to the Bybit action

**2:  Bybit action to create/place order** 
<img width="891" alt="image" src="https://user-images.githubusercontent.com/104946677/215194271-766cd7ed-bc8c-42c5-a4c9-eabd6b769ce0.png">

if you connect both of them it will resolve your issue please try that out and let us know here if it worked for you if not we are here for to help you.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
