### ISSUE TITLE
[ACTION] Customer.io

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#533]
**Is there a specific app this action is for?**
Customer.io

**Please provide a link to the relevant API docs for the specific service / operation.**
Sending event data - note: there is a legacy action for this app so we should update
Create a new customer

**Comment by sergioeliot2039** [comment]
I updated the Sending event data action, it was named
Send Event To Customer io
Workflow at: https://pipedream.com/@sergio/customer-io-send-event-to-customer-io-p_aNCzB6/edit
Sending Anonymous Event was created to: 
Workflow: https://pipedream.com/@sergio/customer-io-send-anonymous-event-to-customer-io-p_WxCNr1/edit
Create or Update Customer:
Workflow: https://pipedream.com/@sergio/customer-io-create-or-update-customer-p_OKCw7g/edit
