### ISSUE TITLE
[APP] Coassemble

### ISSUE THREAD

**Issue by endritibra** [PipedreamHQ/pipedream#5334]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
@endritibra here is a basic integration:
https://pipedream.com/apps/coassemble/

We aren't able to validate this integration end to end -- can you confirm you're able to connect your account and that the basic test request works for you?

Thanks

**Comment by endritibra** [comment]
Everything is all fine, I was testing some integrations with HubSpot. Now I deleted

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
