### ISSUE TITLE
[Action] Wordpress Fetch/Update User Specifically User Meta

### ISSUE THREAD

**Issue by mrdoosey** [PipedreamHQ/pipedream#5335]
Wordpress.org

Fetch User and Update User https://developer.wordpress.org/rest-api/reference/users/#update-a-user-2

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by mrdoosey** [comment]
Hi, I can try, is there any good videos I could use to follow for something like this?

**Comment by dannyroosevelt** [comment]
This video might be a good starting place: https://pipedream.com/blog/building-a-custom-pipedream-action-component-with-gitpod/

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
