### ISSUE TITLE
TrustPilot

### ISSUE THREAD

**Issue by tekhaus** [PipedreamHQ/pipedream#5347]
TrustPilot

[**Link to developer documentation**](https://developers.trustpilot.com/authentication)

Possible action - Invitation API: [Generate service review invitation link](https://developers.trustpilot.com/invitation-api#generate-service-review-invitation-link)

There are a ton of endpoints that would make useful actions, but the above is the only one currently needed for our use case. If we can only get the oAuth managed for this service, while using custom code to post to the endpoints, then that would be fine.

**Comment by dannyroosevelt** [comment]
Enabling API access requires a paid account in Trustpilot. I just opened a support ticket with their team to get their help setting us up with a partner account.

**Comment by sergio-eliot-rodriguez** [comment]
someone made trustpilot live!!
https://pipedream.com/apps/trustpilot

@tekhaus please have look and let us know any issues!
