### ISSUE TITLE
[APP]Tradeovate (Futures Trading App)

### ISSUE THREAD

**Issue by MongoSan** [PipedreamHQ/pipedream#5348]
TradoVate

https://api.tradovate.com/  & https://github.com/tradovate/example-api-oauth

I would like to get the OAuth Setup as a connected account so that I can easily use it in workflow steps

Thanks !
Tom

**Comment by sergio-eliot-rodriguez** [comment]
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/4747
