### ISSUE TITLE
[FEATURE] In Inspector UI, allow user to select an event and open it in Builder event so that they will easier to debug

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5352]
**Is your feature request related to a problem? Please describe.**
Sometime there's a failed event in the deployed workflow (Inspector UI) and it is hard for user to actually select the event in the Builder UI and debug/fixing it

**Describe the solution you'd like**
<img width="1919" alt="Screenshot 2023-01-30 at 20 52 20" src="https://user-images.githubusercontent.com/18277920/215496120-9f5e23e8-acb3-4a8e-94b3-4ee8033e2dc4.png">

**Do you have a workaround?**
The user need to manually search for the failed event in the Builder UI

**Comparable features in other tools?**
No

**Additional context**
First reported by the user here: https://pipedream.com/community/t/link-to-a-specific-event-trigger-for-the-workflow-builder/4234

**Comment by dylburger** [comment]
This should be done! If you select an event from the inspector on the left, and click any **Edit** button (at the top-right, or on any step), we should populate the data from the selected event as the test event, so you should be able to replay it during testing.
