### ISSUE TITLE
[APP] Zoom Team Chat

### ISSUE THREAD

**Issue by eigenstil** [PipedreamHQ/pipedream#5365]
**Name of App**
Zoom Team Chat

**Link to developer documentation**
(https://marketplace.zoom.us/docs/api-reference/chat/methods/#overview)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Lack of support is preventing me from building workflows. I would like to transfer messages from ghostinspector.com JSON API to specific channels in zoom chat

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- Send Message to Channel (https://marketplace.zoom.us/docs/api-reference/chat/methods/#operation/sendaChatMessage)
- Send Message to User (https://marketplace.zoom.us/docs/api-reference/chat/methods/#operation/sendaChatMessage)

**Comment by eigenstil** [comment]
Maybe someone could point me to a solution, how I can fiddle around with custom code in pipedream?

I already created an OAuth app with scope "Team Chat" and "Send a team chat message to a Zoom Team Chat user or channel on behalf of a Chatbot /imchat:write:admin" in zoom (https://marketplace.zoom.us/develop/create). 

So I have
* a Client ID 
* and a Client secret 

right now. But I have no idea where to start in pipedream with this. And I have no real knowledge about OAuth. I would be very willing to use the custom code option and I have some knowledge about JS :-)

**Comment by sergio-eliot-rodriguez** [comment]
Hi @eigenstil 

I apologize for a late response here.

The existing Zoom application, both Zoom and Zoom Admin have scopes added for team chat. You can verify this on the Pipedream app at the Zoom marketplace:

https://marketplace.zoom.us/apps/jGaV-kRrT3igAYnn-J5v2g

The scopes under Team Chat allow for sending a message to a channel or a user
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/db021cce-fb22-41d0-8ca7-d5eaf82af7b9)


This is cross checked with another issue for Zoom actions where Send Message is addressed
https://github.com/PipedreamHQ/pipedream/issues/1442


> Send Chat Message | Send a chat message to a channel or contact

Furthermore, we are in the works to allow Bring your own Auth applications, also known as Custom Apps or Developer Apps, we have a few implemented such as 
https://pipedream.com/apps/gmail-custom-oauth
https://pipedream.com/apps/youtube-data-api-custom-app

but that's not done yet for Zoom.

Plus, implementing OAuth requires a UI component. Pipedrem has announced is in development of UI components that can be embedded in your website, one is for managed auth. You can see the announcement at:

https://pipedream-users.slack.com/archives/C01DFPZNKJN/p1715103124987859

> Managed Auth: One of the core features of Pipedream is [managed auth](https://pipedream.com/docs/connected-accounts), which lets you quickly connect your account and make authenticated requests to more than 2,000 APIs. You don’t have to worry about handling OAuth grants, token refresh, or securely storing sensitive tokens. With Pipedream Connect, your users can easily link their accounts from any of these APIs.

For now I'm closing this issue, and going to raise with the team about a potential Zoom Custom App, or if when new onbaordings Custom Apps are rolled out by default, it will be backwars applied to existing Zoom and Zoom Admins app.

Kind regards,
Sergio

**Comment by sergio-eliot-rodriguez** [comment]
I confirmed with the team that Pipedream Connect will be back compatible with existing apps, so when that is released Zoom and Zoom Admin apps will support BYOA too, to use your own client credentials like you described.
