### ISSUE TITLE
[APP] ChatGPT via Azure OpenAI Service

### ISSUE THREAD

**Issue by slavakurilyak** [PipedreamHQ/pipedream#5367]
**Name of app / service**

ChatGPT by OpenAI

**Link to developer documentation**

According to Mahmoud M. at Microsoft, "ChatGPT is now generally available on Azure Open AI Services!". 

![screenshot](https://user-images.githubusercontent.com/6625584/215790273-60e6bcf0-cf0e-44a8-870f-f9938f99695a.jpg)

Azure Open AI Services are now available in East US and South Central US.

1. [Azure OpenAI models](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/models)
2. [General availability of Azure OpenAI Service expands access to large, advanced AI models with added enterprise benefits](https://azure.microsoft.com/en-us/blog/general-availability-of-azure-openai-service-expands-access-to-large-advanced-ai-models-with-added-enterprise-benefits/)
3. [Azure OpenAI Service](https://azure.microsoft.com/en-us/products/cognitive-services/openai-service)
4. [Azure Products by Region](https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?products=cognitive-services&rar=false&regions=us-central,us-east,us-east-2,us-north-central,us-south-central,us-west-central,us-west,us-west-2,us-west-3,canada-central,canada-east)

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Workaround is to use the [existing OpenAI API integration](https://pipedream.com/apps/openai)

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

TBD

**Comment by slavakurilyak** [comment]
ChatGPT is a fine-tuned version of GPT-3.5.

**Q: Is ChatGPT more powerful than GPT-3 from 2020?**

A: Not really. ChatGPT is free, has a nice user interface, is more ‘safe’, and is backed by @openai (founded by Elon). These may be some of the reasons for ChatGPT’s popularity. Raw GPT-3 (and the new default GPT-3.5 as text-davinci-003 in [the playground](https://beta.openai.com/playground)) is more powerful, according to [Dr Alan D. Thompson](https://lifearchitect.ai/chatgpt/#:~:text=Not%20really.%20ChatGPT%20is%20free%2C%20has%20a%20nice%20user%20interface%2C%20is%20more%20%E2%80%98safe%E2%80%99%2C%20and%20is%20backed%20by%20OpenAI%20(founded%20by%20Elon).%20These%20may%20be%20some%20of%20the%20reasons%20for%20ChatGPT%E2%80%99s%20popularity.%20Raw%20GPT%2D3%20(and%20the%20new%20default%20GPT%2D3.5%20as%20text%2Ddavinci%2D003%20in%20the%20playground)%20is%20more%20powerful.).

![ChatGPT](https://user-images.githubusercontent.com/6625584/215861967-372a399f-41d8-4282-8310-8b49b555434f.jpg)

**Comment by dylburger** [comment]
@slavakurilyak This is done, take a look here: https://pipedream.com/apps/azure-openai-service . Let me know if you see any issues or have any feedback on it. We're also working on pre-built actions at #7448
