### ISSUE TITLE
Pagerduty -- update the new-or-updated-incident trigger

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5369]
### App
Pagerduty
https://developer.pagerduty.com/api-reference/ec247c8767c6d-create-a-webhook-subscription

### Triggers
Update the existing new-or-updated-incident trigger to include an optional prop to filter the events based on what Pagerduty supports.

### Possible bug
We may not be correctly paginating escalation policies ([see this Slack thread](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1675276496741529)). The user reports that we only load 25 policies, and no more. We should paginate behind the scenes and return the full list of options back to the user, instead of returning the offset / more flag back to the `async` options call.

**Comment by sgirones** [comment]
I may also add that the trigger needs to be updated to Webhooks V3:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/597063/216365718-c94ace57-7800-4224-a884-63181ae679ab.png">

March 2023 is rather close 😄 

With Webhooks V3 you can define what kind of events you want to receive, which would help with this issue too

**Comment by dannyroosevelt** [comment]
@sgirones thanks for flagging!
