### ISSUE TITLE
[ACTION] Access Read/Write Shopify Metafields

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5375]
Shopify

https://shopify.dev/api/storefront/2023-01/objects/Metafield

https://shopify.dev/api/admin-graphql/2023-01/objects/MetafieldAccess

Search by. Read. Write. to shopify metafields would be very useful.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by zecul** [comment]
I'm still working my way through pipedream univesity so I woudn't feel confident doing this myself yet, but I would like to learn how eventually.

I can think of a slightly hacky way to do it by using shopify flow to send the data as an http message to a webhook perhaps.

I can ask around at shopify too.

**Comment by Hassan-Abbas-SQA** [comment]
@michelle0927 
Test_Fail
please make the Namespace and Key prop to prefilled as they are non update able fields
![image](https://user-images.githubusercontent.com/104946677/218148302-e29e5274-de4c-4282-afa2-b624b93be023.png)


Test Passed 
![image](https://user-images.githubusercontent.com/104946677/218143267-a6cbc4b3-f577-42df-a832-2534b2f95404.png)

**Comment by zecul** [comment]
Thanks for doing this Michelle. Mostly working great, but I have a couple of issues. Hopefully these are not user error but if they are just let me know.

1. Get Metafields and Update metafields can only access metafields with data already in them. If the metafield exists but is empty then Get Metafields and Update Metafields cannot see the metafield or update it.

![image](https://user-images.githubusercontent.com/123815443/218245189-8dad5ccc-2073-466a-b9df-b03ee3e2b00e.png)
![image](https://user-images.githubusercontent.com/123815443/218245194-13f44cf9-261e-49f9-8e69-a27895c6f965.png)
![image](https://user-images.githubusercontent.com/123815443/218245770-396232e1-85b8-4992-a8b7-76f3937d6271.png)
c.f.
![image](https://user-images.githubusercontent.com/123815443/218245818-09e28403-1fbc-4f4c-b890-d3d7da4ef0e2.png)
![image](https://user-images.githubusercontent.com/123815443/218245856-1890c818-d8d5-4483-ad17-94db5f2267b2.png)

2. Update Metafield works with basic single line items but it doesn't work with single line list items.
single_line_text_field vs. list.single_line_text_field
Get Metafield returns list.single_line_text_field items as an array:
![image](https://user-images.githubusercontent.com/123815443/218246072-dbc2a648-2e17-40cb-8595-10e2490f92b5.png)
Posting an array in Update Metafield returns an error:
![image](https://user-images.githubusercontent.com/123815443/218246181-3b109641-a914-4c3d-bcf4-3899077a1d52.png)

I'm not sure if #2 is just because there is no option to select list.single_line_text_field from the dropdown menu
![image](https://user-images.githubusercontent.com/123815443/218246253-f6065eb2-3bde-41c5-b56f-58d2909056ae.png)
Or if its the format the data is being sent to single_line_text_field in:
https://community.shopify.com/c/technical-q-a/single-line-text-metafield-with-list-of-values-can-not-be-joined/m-p/1560815/highlight/true#M86612
https://community.shopify.com/c/storefront-api-and-sdks/how-can-i-get-list-type-references-of-metafield/m-p/1771736/highlight/true#M2510

Thanks again for both Shopify improvements this week. I'm getting a lot out of them and I hope other people will too.

**Comment by michelle0927** [comment]
@zecul Glad you're getting use out of these. I think with your first point, that may just be a limitation of the API. The metafield endpoints only return metafields that have data in them.

For the second point, you're correct that the components aren't working for metafield with list types. I created [this issue](https://github.com/PipedreamHQ/pipedream/issues/5473) to update them to allow for list types..
