### ISSUE TITLE
[OAUTH SCOPE]TickTick

### ISSUE THREAD

**Issue by Daigo-Kanda** [PipedreamHQ/pipedream#5376]
**Which application needs a scope added?**
TickTick

**What scope(s) need to be added?**
tasks:read

**Please provide a link to the relevant API docs for scopes.**
https://developer.ticktick.com/docs#/openapi

**Comment by dylburger** [comment]
This is done! See https://pipedream.com/apps/ticktick#authentication for the list of scopes.
