### ISSUE TITLE
[APP] Microsoft Excel

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5379]
**Name of app / service**
Microsoft Excel

**Link to developer documentation**
https://learn.microsoft.com/en-us/graph/api/resources/worksheet?view=graph-rest-1.0

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
[Get Worksheet](https://learn.microsoft.com/en-us/graph/api/worksheet-get?view=graph-rest-1.0)
[Update](https://learn.microsoft.com/en-us/graph/api/worksheet-update?view=graph-rest-1.0)
[Add](https://learn.microsoft.com/en-us/graph/api/worksheetcollection-add?view=graph-rest-1.0)

**Comment by dasheck0** [comment]
From the documentation I don't see whether rows can be added (it is not part of the Update endpoint). It is important to add rows to an existing worksheet.

**Comment by sergio-eliot-rodriguez** [comment]
Excel integration upvoted on #6482

with comment

> 
I have a workaround with Google Sheets, but we use excel to generate dashboards in PowerBI

**Comment by dasheck0** [comment]
Any plans when this will be added? The demand is rising on our end :)

**Comment by malexanderlim** [comment]
@dasheck0 , this app is now available! 🎉 
https://pipedream.com/apps/microsoft-excel
