### ISSUE TITLE
code or filter Skip to a specific step

### ISSUE THREAD

**Issue by shehistier** [PipedreamHQ/pipedream#5392]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by DilanAthukorala** [comment]
@shehistier We already have ticket to enable support for branching a workflow in a conditional manner (if condition is true, run this step, else run this other step). Could you please check this ticket - [Support for branching](https://github.com/PipedreamHQ/pipedream/issues/216) and let us know if this covers your requirement.

**Comment by shehistier** [comment]
what I want in a filter to skip steps within the workflow line...

**Comment by dannyroosevelt** [comment]
@shehistier that use case totally makes sense and will be addressed as a part of the support for branching in workflows. One way we envision solving this problem is by configuring logic in your workflow that says "if this condition is met, execute a, b, c steps; if not, execute x, y, z steps".
