### ISSUE TITLE
[BUG] Supabase select action does not returns any value

### ISSUE THREAD

**Issue by rmi111** [PipedreamHQ/pipedream#5393]
**Describe the bug**
When tried to use and connect into supabase db using Supabase API from Pipedream, it does not connect to the db and failed to retrieve data from the given table.

**To Reproduce**
1. Go to https://pipedream.com/apps/supabase
2. Click on Select Row with Supabase API
3. Connect to supabase db and enter all information
4. Click test

**Expected behavior**
Returns of list of object from the given supabase table

**Desktop (please complete the following information):**
 - MacOS: [e.g. iOS]
 - Safari

**Comment by DilanAthukorala** [comment]
@rmi111 Thank you for reporting this bug. I was able to reproduce the issue and our team will look into this as soon as possible. Please follow this ticket for updates. 

issue: no results returned from database:
![image](https://user-images.githubusercontent.com/102980146/216666021-287df6a0-fc1c-45c2-9d7a-f14a73e90d61.png)

**Comment by michelle0927** [comment]
When I tested the `select-row` action, I did see the return value as `null`. I logged in to Supabase, and saw that my project was inactive and needed to be restored. After I clicked to restore the project, I tested the `select-row` action again, and it returned values.

@rmi111  Is it possible something similar is happening with your account? When you log in to Supabase does it show the project or a button to restore it?

**Comment by rmi111** [comment]
Thanks for your reply. Is this the status you meant?
![Screenshot 2023-02-10 at 2 17 34 PM](https://user-images.githubusercontent.com/7029433/218038838-077c762f-64f7-4cb6-aeff-aa0ab39d3a6a.png)

**Comment by michelle0927** [comment]
@rmi111 That looks ok actually. Can you do me a favor and check that the subdomain for your Supabase account is entered correctly in Pipedream? It should just be the middle part of the URL without `https://` or `.supabase.co`.

<img width="1016" alt="Screenshot 2023-02-10 at 9 51 42 AM" src="https://user-images.githubusercontent.com/10889229/218123202-75eed65f-148e-4a06-baaf-9dfaded5456d.png">

**Comment by rmi111** [comment]
Thanks @michelle0927, yes that way it works now, but it did not worked before, and still I am unable to connect through custom code, such as following one:
`// To use any npm package, just import it
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = "";
const supabaseAnonKey = "";

const supabase = createClient(supabaseUrl, supabaseAnonKey);

export default defineComponent({
  async run({ steps, $ }) {
    const { data } = await supabase
          .from("twitter_followers_db")
          .select("*")
          .single();

    console.log(data);
    // Reference previous step data using the steps object and return data to use it in future steps
    return data
  },
})`

**Comment by rmi111** [comment]
Ok I think it's all working now overall. I have to use `limit` instead of `single` function.
