### ISSUE TITLE
[Components] EmailOctopus

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#5395]
**Name of app / service**
Email Octopus 

**Link to developer documentation**
https://emailoctopus.com/api-documentation

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Tod, we have Email Octopus integrated, https://pipedream.com/apps/emailoctopus

**Comment by dannyroosevelt** [comment]
Looks like we only have a single trigger -- let's get some more components published:

**Triggers:**
1. New Subscriber
2. Subscriber Unsubscribed

**Actions:**
1. Create a List
2. Add Subscribers to a List
3. Send a Campaign

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Email_Octopus_5665.pdf](https://github.com/PipedreamHQ/pipedream/files/10951012/Email_Octopus_5665.pdf)
