### ISSUE TITLE
Sendy

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5396]
### App
Sendy
https://sendy.co/api

### Triggers
1. New Subscriber
2. New Campaign

### Actions
1. Send a Campaign
2. Add a Subscriber
3. Delete a Subscriber

**Comment by sergio-eliot-rodriguez** [comment]
Sendy has been integrated https://pipedream.com/apps/sendy?via=go

Component development is being tracked on #10775
