### ISSUE TITLE
[APP] LogSnag

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#5397]
**Name of app / service**
LogSnag

**Link to developer documentation**
https://docs.logsnag.com/quick-start

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
LogSnag has been previously integrated https://pipedream.com/apps/logsnag
