### ISSUE TITLE
[BUG] Google Drive create_file_from_template action

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5403]
Async options for the `folder` prop are not consistently working for all users (not able to repro).

And when referencing a `folderId` manually via custom expression, I get a 404 returned.

In my case I see the file was actually created, but the user is not able to repro that.

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/216689387-c294f9b5-32a2-4c01-8422-ee5ec6ffdc9c.png)

**Comment by vunguyenhung** [comment]
I can reproduce the case where I input the ID manually and it failed with error 404
![image](https://user-images.githubusercontent.com/18277920/217126621-2c2f4469-346d-46f7-aadb-3e450c2b0c73.png)

Also I noticed that the action failed with code 400 when we select the file other than Google Docs.

**Comment by michelle0927** [comment]
@dannyroosevelt @vunguyenhung I was able to reproduce this by using files other than Google Docs or files without any template placeholders in them. I updated `create-file-from-template` to catch these errors and display a more informative error message. [PR here](https://github.com/PipedreamHQ/pipedream/pull/5483).

**Comment by dannyroosevelt** [comment]
Ah nice. Does the file need to have template placeholders? Replacing placeholders is an optional prop in the action. Shouldn't users be able to create a template but not do any replacement?

**Comment by michelle0927** [comment]
> Ah nice. Does the file need to have template placeholders? Replacing placeholders is an optional prop in the action. Shouldn't users be able to create a template but not do any replacement?

In that case, wouldn't they use the Copy File action?

**Comment by dannyroosevelt** [comment]
Interesting, yes. So then maybe replacing placeholders should be required?
