### ISSUE TITLE
[Components] Wrike triggers

### ISSUE THREAD

**Issue by werkaldo** [PipedreamHQ/pipedream#5408]
**Name of app / service**
Wrike

**Describe the event source. What app is this for, and what event does the trigger correspond to?**
[Wrike New Task](https://developers.wrike.com/api/v4/tasks/)
[Wrike New Subtask](https://developers.wrike.com/api/v4/tasks/)
[Wrike New Folders](https://developers.wrike.com/api/v4/folders-projects)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
