### ISSUE TITLE
[TRIGGER] Totango New Task

### ISSUE THREAD

**Issue by jeffmdobson** [PipedreamHQ/pipedream#5412]
Create trigger for a new task created in Totango

https://support.totango.com/hc/en-us/articles/115000597266-Touchpoints-API

**Comment by Abhishek7Tech** [comment]
@jeffmdobson  Hi Do you mean creating a new TouchPoint whenever a new task is created by user?

**Comment by jeffmdobson** [comment]
Hi, 
Apologies if not clear enough. The end use is to automatically create an asana task when a Totango task is created.
So I was looking to create a new source for totango based on the creation of a task but the only currently available is for new account or new user. Thanks

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
