### ISSUE TITLE
[APP] Mailbluster

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#5420]
**Name of app / service**
Mailbluster

**Link to developer documentation**
https://app.mailbluster.com/api-doc

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
The API is a bit odd as it seems to be based on a legacy model of leads, products, etc. rather than subscribers and campaigns like most email platforms. Regardless, I guess it should be supported as designed.

**Comment by dannyroosevelt** [comment]
https://pipedream.com/apps/mailbluster

Tracking components here: 
https://github.com/PipedreamHQ/pipedream/issues/5424
