### ISSUE TITLE
[APP] Discogs

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5423]
Discogs

https://www.discogs.com/developers
https://github.com/bartve/disconnect
*removed by request*

I have been able to build a couple of steps that access the API but no more than that

Triggers:
[Markeplace]
New Order
Payment Received
New Listing
New Message
[Database]
New Release (filtered by...?)

Actions:
[Marketplace]
Get Listing
Update Listing
Post Listing
Message
Update Order
Export/Edit/Upload Inventory
[Database]
Get/Update/Create Release

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergioeliot2039** [comment]
HI @zecul , thanks for your request.

Yeah, no worries, we'll handle the components development. That message from Dylan is automated, after I added Github labels to your request. But first, we'll get the app integrated. So stay tuned for updates.

**Comment by zecul** [comment]
I made some small progress on this if its on any help to someone who wants to do a full build:

![image](https://user-images.githubusercontent.com/123815443/219990145-7671b9c8-5da8-4f64-9df0-2254d787f135.png)
![image](https://user-images.githubusercontent.com/123815443/219990151-29f41fb9-e84b-4a99-b9ee-7a3990a150bc.png)

**Comment by JOJ0** [comment]
Hi @sergioeliot2039 and @zecul, thanks for your interest in using [python3-discogs-client](https://github.com/joalla/discogs_client). I'm one of the maintainers. I actually don't understand how pipedream works and how python3-discogs-client is a part of it. I'm not yet sure if our python library is used in the examples posted here at all.

If it is not used at all here I suggest we remove it from the initial post in this thread :-) Thanks a lot.

**Comment by sergio-eliot-rodriguez** [comment]
I have no idea, we haven't addressed Discogs at all, not to say one of the libraries, the examples are posted by the user requesting Discogs be integrated at Pipedream.

@zecul would you mind commenting on what you were using in the screenshots?
we have a new user request for Discogs

**Comment by zecul** [comment]
Screenshots was my own code.

**Comment by JOJ0** [comment]
> Screenshots was my own code.
@zecul did your code use github.com/joalla/discogs_client.git ?

**Comment by zecul** [comment]
@JOJ0 No. I've never even read it. I just passed it to the devs as a possible starting point for an integration.

**Comment by JOJ0** [comment]
Ok @zecul the thing is that you caused some kind of confusion since you posted **in a thread** that **is about** joalla/discogs_client and then you mentioned it on the very top of this thread.

Both points to at least _some_ relation to its usage. Well, ok, riddle solved, there is now relation to python3-discogs-client at all I'll unfollow this thread now. Bye :-)

**Comment by malexanderlim** [comment]
@zecul I've created the base integration for Discogs; if there are specific triggers and actions that you are interested in, please let us know!
