### ISSUE TITLE
[Components] Mailbluster

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5424]
### App
Mailbluster
https://app.mailbluster.com/api-doc

**Triggers** 
1. New Subscriber 
2. Subscriber Updated 

**Actions** 
1. Create Subscriber 
2. Update Subscriber 
3. Delete Subscriber

**Comment by luancazarine** [comment]
@dannyroosevelt MailBluster API handles leads, fields, products and orders but has no subscribers

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt MailBluster API handles leads, fields, products and orders but has no subscribers

That list was actually generated by GPT3, but clearly it needs some improving.

### Triggers
- New order created
- New product created

### Actions
- Create a product
- Create a lead
- Get a product
- Get a lead
