### ISSUE TITLE
[BUG] On connect Mattermost account popup, I can not scroll down to see the rest of instructions and the credentials inputs

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5439]
**Describe the bug**
On connect Mattermost account popup, I can not scroll down to see the rest of instructions and the credentials inputs
<img width="1919" alt="Screenshot 2023-02-09 at 08 15 56" src="https://user-images.githubusercontent.com/18277920/217689838-f5c24910-1c1f-4db2-8bbe-d1aab725fa13.png">

**To Reproduce**
1. [Pipedream Account page](https://pipedream.com/accounts), search for Mattermost and select it
![image](https://user-images.githubusercontent.com/18277920/217689972-a0fb935f-7e3b-4b59-a708-12edbb64ef18.png)
2. On the Mattermost popup, try to scroll down. Observe that you can not scroll down

**Expected behavior**
The popup should allow user to scroll down to see the rest of instructions and the credentials inputs

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2
 - Browser: Microsoft Edge
 - Version 109.0.1518.78 (Official build) (arm64)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
