### ISSUE TITLE
Streamlabs

### ISSUE THREAD

**Issue by ramoshe** [PipedreamHQ/pipedream#5442]
**Name of app / service**
Streamlabs

**Link to developer documentation**
https://dev.streamlabs.com

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Preventing me from building workflows

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Alerts, Donation, Media Share, Chatbot commands if possible?

**Comment by sergioeliot2039** [comment]
OAuth 2.0 supported https://dev.streamlabs.com/docs/oauth-2

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/streamlabs
