### ISSUE TITLE
[BUG] Github action script checking version of app file

### ISSUE THREAD

**Issue by andrewjschuang** [PipedreamHQ/pipedream#5443]
**Describe the bug**
The [Github action script that checks for component versions](https://github.com/PipedreamHQ/pipedream/blob/master/.github/actions/git-diff-on-components/src/index.js#L95) had a [false positive for Google Drive app file](https://github.com/PipedreamHQ/pipedream/actions/runs/4128588165/jobs/7133214611#step:4:1092).
@GTFalcao figured out that it searches for a string `"version:"` in the file, independently if it's in the app file.

**To Reproduce**
1. Create a new branch from `master`.
2. Change [this line](https://github.com/PipedreamHQ/pipedream/blob/master/.github/workflows/pull-request-checks.yaml#L8) to `on: push` and push the commit to the repo. Now the action will run on every commit pushed.
3. Go to Google Drive app file and ensure [these lines](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/google_drive.app.mjs#L270) has exactly `version: "v3"`: 
```js
return drive.drive({
  version: "v3",
  auth,
});
```
4. Change anything in the `common/utils.mjs` file.
5. Push all commits and see the error in the Github Action.

**Expected behavior**
No errors regarding version bump in the app file.

**Screenshots**
<img width="692" alt="image" src="https://user-images.githubusercontent.com/15385076/217806547-b9d6f9bc-1dc8-4e98-9190-4862a876f2dc.png">

**Some possible fixes**
- Only iterate through component files when checking version changes
- Ensure that the file is a component before appending the version bump error
- Avoid matching `version:` if it's within `methods` or `propDefinitions` blocks

**Comment by Hussain0520** [comment]
Hey is this issue still open? I would like to work

**Comment by andrewjschuang** [comment]
@Hussain0520 I really appreciate your effort to help.
May I ask if you have knowledge of the GitHub Action Checks that are executed on component PRs?

**Comment by Hussain0520** [comment]
Actually I'm not aware of it but with your help I guess I can contribute :)

**Comment by andrewjschuang** [comment]
I think in this case it would be better to leave this task for a Pipedream Component Developer, they will have more experience and insights on what is necessary to adjust.

You are very welcome though to tackle another issue in the **Prioritized** or **To Do** columns of the [Project Board](https://github.com/PipedreamHQ/pipedream/projects/1)!

**Comment by vunguyenhung** [comment]
Hello, I have tested this in my fork here: https://github.com/vunguyenhung/pipedream

I have changed the utils/constants file in the Google Drive and 123FormBuilder app and I observed that the app file didn't have error of version bump
![image](https://user-images.githubusercontent.com/18277920/218923504-56c64f59-56ef-4da5-b56f-4ef3350f2223.png)
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/18277920/218923323-d5de4744-0edc-40c5-815d-0277c3ee4db2.png">

Ready for release!

**Comment by andrewjschuang** [comment]
@vunguyenhung you need to change [this line](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_drive/google_drive.app.mjs#L270) to `version: "v3"` (step 3), this is the reason for the error.


I tested it too but the error is still there - [link](https://github.com/PipedreamHQ/pipedream/actions/runs/4182786920/jobs/7246322060#step:4:59):
![image](https://user-images.githubusercontent.com/15385076/218999676-9d47cb73-d597-49d5-934d-0708cb2dfa3d.png)

**Comment by lcaresia** [comment]
@vunguyenhung do you tested again with was @andrewjschuang recommended?

**Comment by vunguyenhung** [comment]
Hello @andrewjschuang, could you help me to test this instead. As you have the most context for this issue.
