### ISSUE TITLE
[TRIGGER] Shopify: Product added to custom collection

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5448]
Shopify. Triggers when a product is added to a custom collection.

https://shopify.dev/docs/api/admin-rest/2023-01/resources/collect

I think this is the correct resource, but I'm not 100% sure. I can investigate further if you think it's the wrong way to do it.

**Comment by zecul** [comment]
Related to: https://github.com/PipedreamHQ/pipedream/issues/5449

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
