### ISSUE TITLE
[ACTION] Shopify: Add product to a custom collection

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5449]
Shopify

https://shopify.dev/docs/api/admin-rest/2023-01/resources/collect#post-collects
(add product to a custom collection)

https://shopify.dev/docs/api/admin-rest/2023-01/resources/customcollection#post-custom-collections
(create a custom collection)

I'm not sure if these should be separate actions or part of the same action.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
