### ISSUE TITLE
[IMPROVEMENT] Wise code sample is outdated

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5453]
**Is your feature request related to a problem? Please describe.**
Recently, Wise changed their API domain from `https://api.transferwise.tech` to `https://api.transferwise.com`. Though our HTTP Request/Node.js/Python sample code still using the old domain
<img width="915" alt="image" src="https://user-images.githubusercontent.com/18277920/217995240-c50af0e3-26fd-4c28-b76b-04e06d1af2d9.png">
<img width="916" alt="image" src="https://user-images.githubusercontent.com/18277920/217994123-7ff646b4-736d-4071-959b-fbdc98fb0039.png">
<img width="911" alt="image" src="https://user-images.githubusercontent.com/18277920/217994775-f829c752-3507-4488-9abb-24082381e2b5.png">

**Describe the solution you'd like**
In our HTTP/Node.js/Python sample code, change the base url from `https://api.transferwise.tech` to `https://api.transferwise.com`.

**Do you have a workaround?**
Yes, manually change the code

**Additional context**
First reported by a user here: https://pipedream-users.slack.com/archives/CN1BUB92B/p1675916027848399

**Comment by dannyroosevelt** [comment]
Done!
