### ISSUE TITLE
[TRIGGER] Firestore Collection to GoogleSheet to Firestore Collection

### ISSUE THREAD

**Issue by davidogundepo** [PipedreamHQ/pipedream#5455]
**Export Firestore Collection to GoogleSheet, then change/modify Documents' Objects from GoogleSheet cell edits**

**Comment by vunguyenhung** [comment]
Hello @davidogundepo, 

Currently Pipedream offers various Firestore actions to List, Creat, Update documents. Could you check if they fit your need?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
