### ISSUE TITLE
[TRIGGER] Wise - Transfer state changed

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5456]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Wise

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://api-docs.transferwise.com/features/webhooks-notifications/event-types#transfer-state-change

**Comment by Abhishek7Tech** [comment]
@vunguyenhung  it's related to wise(transferwise) application. Event get triggered whenever a payment occurs.
