### ISSUE TITLE
[BUG] We weren't able to find an event with the id (but it's actually there)

### ISSUE THREAD

**Issue by krampepampe** [PipedreamHQ/pipedream#5464]
**Describe the bug**
After entering the URL with the exact event ID I see this error message.

**To Reproduce**
1. Go to workflow in chrome
2. Click on event
3. Change the event ID and press enter

**Expected behavior**
No error message

**Screenshots**
attached

**Desktop (please complete the following information):**
 - OS: Version 13.2 (22D49)
 - Browser chrome
 - Version 109.0.5414.119

<img width="462" alt="image" src="https://user-images.githubusercontent.com/83527069/218378206-d4903c2e-5a00-4577-93ab-f99a075258cd.png">

**Comment by vunguyenhung** [comment]
Hello @krampepampe, I think that `id` in your event is the ID of the entity from the source, not the Pipedream Event ID. Would you mind provide more detail about the URL that you used to access the event?

**Comment by krampepampe** [comment]
Ah I got it!  So the correct Id would the the 'trace_id', right?  Thank you!
