### ISSUE TITLE
[BUG] IS: String SHOULD BE: array in Moosend integration to allow send data in custom fields

### ISSUE THREAD

**Issue by PaulSokolowsky** [PipedreamHQ/pipedream#5467]
**Describe the bug**
In the Moosend - add subscriber action, the Custom Fields props are not send as there is a field type error. In more detail, [the code here defines the Custom Fields prop as string](https://github.com/PipedreamHQ/pipedream/blob/master/components/moosend/actions/add-subscriber/add-subscriber.mjs#L30-L33)

But it should be an array of string, per the MooSend API documentation:
https://moosendapp.docs.apiary.io/#reference/subscribers/add-or-update-subscribers/adding-subscribers

Correct Example:
BODY
```
{
  "Name": "Paul",
  "Email": "someEmail@email.com",
  "HasExternalDoubleOptIn": false,
  "CustomFields": [
    "Age=25",
    "Country=USA"
  ]
}
```

**Comment by vunguyenhung** [comment]
Thanks @PaulSokolowsky for raising this issue. I have edited your description for it to be more clear. I'll add this to Pipedream prioritized backlog!

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Moosend_5484.pdf](https://github.com/PipedreamHQ/pipedream/files/10739546/Moosend_5484.pdf)

**Comment by PaulSokolowsky** [comment]
Hi, thanks so much for so fast fix.
How ofter do you have releases?

**Comment by dannyroosevelt** [comment]
@PaulSokolowsky every day!
