### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by jmahedy-slack** [PipedreamHQ/pipedream#5479]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

I'd like to be able to use a pipedream workflow inside of a Slack workflow step

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

https://api.slack.com/events/workflow_step_execute

**Comment by vunguyenhung** [comment]
Hello @jmahedy-slack, I think you can:
1. Create a Pipedream workflow with the HTTP trigger, then
2. Configure your Slack workflow to call Pipedream's HTTP trigger endpoint

Is this fits your need?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
