### ISSUE TITLE
[FEATURE] $.interface.http support in custom actions

### ISSUE THREAD

**Issue by AnonymousSB** [PipedreamHQ/pipedream#5487]
**Is your feature request related to a problem? Please describe.**
I've created separate workflows to share code between workflows. In my example I have a workflow that calls TinyURL, does some processing, and returns a result that several other workflows expect. I'd love for this to be a custom action, but I can't use $.interface.http in a custom action, only a custom source.

**Describe the solution you'd like**
I'd like to use $.interface.http in a custom action

**Do you have a workaround?**
I have a "workaround", but it involves one workflow calling another, which is slow.

**Comparable features in other tools?**
Not to my knowledge.

**Additional context**
Nope, just need to call $.interface.http from a custom action.

**Comment by vunguyenhung** [comment]
Hello @AnonymousSB,

As I checked [the Pipedream doc here](https://pipedream.com/docs/components/api/#props), the `$.interface.http` is used for source that triggered from HTTP request. 

May I ask why do you want to use `$.interface.http` in your action code? From your description, you needs are not clear to me

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
