### ISSUE TITLE
[BUG] Typo in Slack File Upload

### ISSUE THREAD

**Issue by QB3L** [PipedreamHQ/pipedream#549]
**Describe the bug**
When using the FileUpload integration to Slack the files never make it to the channel you specify even though the payload returns an okay. This happens regardless of using the channel name or id

**To Reproduce**
1. Create any trigger event
2. Add a slack file upload step: slack_file_upload
3. Run a test

**Expected behavior**
File should be uploaded

**Screenshots**
The fix is to change the channel parameter for **channels** in plural 
![payload_fix](https://user-images.githubusercontent.com/867894/95994091-7837bf00-0df5-11eb-978d-751be670883b.png)

**Additional context**

**Comment by dylburger** [comment]
@QB3L would you mind adding the newest version of the action to a workflow and seeing if that works for you?
