### ISSUE TITLE
[APP] Resend

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#5490]
**Name of app / service**
Resend

**Link to developer documentation**
https://resend.com/docs/api-reference/send-email

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Same as Sendgrid, etc.

**Comment by sergioeliot2039** [comment]
@todsac resend is on early access. i joined their waiting list. in case you requested access earlier and have an account please share.

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/resend?via=go
