### ISSUE TITLE
[IMPROVEMENT] Improve Goodread connection modal description

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5491]
**Is your feature request related to a problem? Please describe.**
Currently, when connecting a new Goodread account, there's no description to instruct the user how to get the `key`
![image](https://user-images.githubusercontent.com/18277920/219007261-d51d6680-da47-4e34-8607-5eaaf2ae63af.png)

**Describe the solution you'd like**
A clear and concise description on how to get the Goodread key. [Per this Goodread article](https://help.goodreads.com/s/article/Does-Goodreads-support-the-use-of-APIs) I don't think Goodreads will provide more API Key anymore

**Do you have a workaround?**
No

**Additional context**
First reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1676457305464049

**Comment by dannyroosevelt** [comment]
Added a note to the account connection screen.

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
