### ISSUE TITLE
[TRIGGER] LINE - New message

### ISSUE THREAD

**Issue by Isolatie** [PipedreamHQ/pipedream#5493]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
![image](https://user-images.githubusercontent.com/99743351/219055064-2d380bb0-74c0-40be-9e81-afe91ca561ca.png)
I would like to have a Trigger, so I can send a message from LINE to Discord.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.line.biz/en/docs/messaging-api/receiving-messages/

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
