### ISSUE TITLE
[ACTION] Google Sheet - Get Spreadsheets

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5502]
**Is there a specific app this action is for?**
Google Sheet

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get

**Comment by Abhishek7Tech** [comment]
@vunguyenhung Hi you have to fetch the A.P.I to get spredsheets using -
 https://sheets.googleapis.com/v4/spreadsheets/{"spreadsheetid"}

**Comment by zalmanlew** [comment]
Ideally this action might include an optional filter prop - especially for accounts with *many* spreadsheets. Like this I'm only searching for a spreadsheet that match a given filter.

**Comment by vunguyenhung** [comment]
Hi @zalmanlew, we have implemented 2 actions:
- Google Drive - Find Spreadsheet: allow you to find the spreadsheet by name
- Google Sheet - Get Spreadsheet by ID: allow you to get spreadsheet details by ID

I hope those actions serve your needs. I have tested them and they're good

Test report
[Google_Sheet__Google_Drive_5506_1558.pdf](https://github.com/PipedreamHQ/pipedream/files/10776483/Google_Sheet__Google_Drive_5506_1558.pdf)
