### ISSUE TITLE
[BUG] Shopify trigger not working

### ISSUE THREAD

**Issue by ondrejblasko** [PipedreamHQ/pipedream#5508]
**Describe the bug**
Unable to configure Shopify trigger. After running shopify trigger for several days it stopped working. Now I am not able to configure the trigger and run my workflows. I was using event New paid order (instant) as a trigger. Shopify APP is marked as unsupported in my shopify store

**To Reproduce**
approach 1
1. Create and configure new shopify trigger (New Paid Order (Instant))
2. Click create source
3. It is stuck on preparing
approach 2
1. Try to edit existing shopify trigger
2. unable to see configuration or results of the trigger

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser Chrome

**Comment by vunguyenhung** [comment]
Hello @ondrejblasko, when creating a Shopify source, could you tap into the Shopify Account field to confirm that your connected Shopify account is not expired?
<img width="1078" alt="Screenshot 2023-02-20 at 14 50 42" src="https://user-images.githubusercontent.com/18277920/220044957-2a7eacc3-0d3d-42aa-a1e0-c578bc10a57e.png">

If they've expired, could you try to reconnect?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
