### ISSUE TITLE
[IMPROVEMENT] Canvas actions - Retry requests when facing 401 error from Canvas

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5511]
**Is your feature request related to a problem? Please describe.**
Some time the user faced an intermittent 401 errors when using Canvas API. The user replayed the workflow in question and all is fine.

**Describe the solution you'd like**
Retry the requests to Canvas for 1-3 times when we faced an 401 error from Canvas. This might solve the issue in the mean time

**Do you have a workaround?**
No

**Comparable features in other tools?**
Zapier Developer Platform have not had this issue happen at all, same with a custom solution running in PHP

**Additional context**
Reported by a user here https://pipedream.com/community/t/revisiting-the-canvas-401-issue/4700

**Comment by michelle0927** [comment]
Closing this issue as there are no Canvas actions to update.
