### ISSUE TITLE
[FEATURE] Include response headers in HTTP actions

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5512]
**Is your feature request related to a problem? Please describe.**
The HTTP actions only return the response body, but sometime users need to access the headers to get more information
<img width="732" alt="image" src="https://user-images.githubusercontent.com/18277920/219689877-4462f1e2-2886-4948-81e1-8c096278528a.png">

**Describe the solution you'd like**
Return the response headers to HTTP actions

**Do you have a workaround?**
Using code step

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CN1BUB92B/p1676641790723939

**Comment by sepdoce90** [comment]
Hi, when I create a Post HTTP request I only receives the body. In Postman I can see the Raw data. Butt I need the response headers from the raw data/Metadata

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[HTTP_5512_2213.pdf](https://github.com/PipedreamHQ/pipedream/files/10825651/HTTP_5512_2213.pdf)
