### ISSUE TITLE
react app

### ISSUE THREAD

**Issue by pratikkankanala** [PipedreamHQ/pipedream#5515]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
hi there @pratikkankanala ! thanks for the request
can you please provide a link to the app you are trying to integrate with?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
