### ISSUE TITLE
[BUG] Dropbox Path prop requires absolute path, else async options don't return matching folders

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#5516]
I have to search for the absolute path of my folder for it to appear in the options presented in the **Path** prop for Dropbox components.

A user reported this example: If I want the "YT Audio" folder, I have to type /YT Audio in full:

<img width="905" alt="CleanShot 2023-02-17 at 11 47 42@2x" src="https://user-images.githubusercontent.com/242668/219759633-8c2111b1-a54c-4d17-9d31-2b7a99fc07ff.png">

If the Dropbox search API supports this, I ideally want full substring path matches. e.g. if I had a folder `/hello/world/my_folder_here`, searches for “my_folder_here” should return that path and any other paths where any part of the path matches "my_folder_here".

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Dropbox_5519_2319.pdf](https://github.com/PipedreamHQ/pipedream/files/10786252/Dropbox_5519_2319.pdf)

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Dropbox_5519_1026.pdf](https://github.com/PipedreamHQ/pipedream/files/10789275/Dropbox_5519_1026.pdf)
