### ISSUE TITLE
[TRIGGER] GitHub New Discussion

### ISSUE THREAD

**Issue by asheroto** [PipedreamHQ/pipedream#5520]
Hello,

I didn't see this on the pipedream GitHub triggers so I'd like to request it.

I run [seDirector](https://github.com/seDirector/App/discussions), which is a game server management application. I use the **Discussions** tab of GitHub for folks to add new feature requests or ideas, this allows people to vote on ideas. Currently I have a pipedream trigger for Issues, so when a new issue is added, pipedream makes a post in our Discord server. I'd love this ability for a new idea, too.

![image](https://user-images.githubusercontent.com/49938263/219903278-599b57df-b7cd-481e-bdf5-9fbf85268d6b.png)

For example, here are the discussions for my app...
https://github.com/seDirector/App/discussions

![image](https://user-images.githubusercontent.com/49938263/219903156-32feb0a3-21ab-44db-bf51-5ab84a711b26.png)

Here's what my pipedream workflow for Issues ends up doing... (New Issue makes Discord post)

![image](https://user-images.githubusercontent.com/49938263/219903130-f1c9f37b-eec1-4e04-830d-5dbba45907c4.png)

I think it'd be cool I could use pipedream to do the same for Discussions, too.

Thanks!

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by asheroto** [comment]
Hello, I will check out authoring.

For GitHub, since they're already integrated, what's the best way to go about contact them regarding this kind of thing?

**Comment by ajedwards** [comment]
I saw this request and realised that I could use this trigger too, so I'm already 75% finished coding it up. Will hopefully finish it and submit the PR this weekend 😀

**Comment by asheroto** [comment]
Nice! Thanks

**Comment by asheroto** [comment]
@ajedwards did you happen to finish? Not trying to be pushy just very interested in the PR! lol thanks!

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by ajedwards** [comment]
> @ajedwards did you happen to finish? Not trying to be pushy just very interested in the PR! lol thanks!

Hi. I'm sorry I didn't finish it yet. I got caught up in the tech layoffs and lost my job, so I have been busy and distracted by that! I have some time now so will try to finish this week.

**Comment by lcaresia** [comment]
@asheroto I'm assuming this task, I will create an specific source to get discussion updates, but for now you can use [`New Webhook Event`](https://pipedream.com/apps/github/triggers/webhook-events) to solve your problem!

You just need to create the source and select the event `Activity related to discussion` like the image below.

![image](https://user-images.githubusercontent.com/12402324/226640189-9c059489-9688-4c59-9027-14a00ebbef48.png)
