### ISSUE TITLE
query a value in a range [ACTION]

### ISSUE THREAD

**Issue by echpe0** [PipedreamHQ/pipedream#5522]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**
 i need consult a value in a range of data and return same value in another column of same raw. similar to function VLOOKUP

**Comment by vunguyenhung** [comment]
Hello @echpe0, may I confirm if this is for Google Sheet? Could you please provide examples for you usecase? What is your input (the Google Sheet with values), and your expected output of the action?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
