### ISSUE TITLE
[Adversus]

### ISSUE THREAD

**Issue by kasperklit** [PipedreamHQ/pipedream#553]
**Name of app / service**
Adversus - https://www.adversus.io/

**Link to developer documentation**
https://solutions.adversus.io/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I could make a workaround, but not a very stable one. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
It would be great with the option to create a lead: https://solutions.adversus.io/api#tag/leads/paths/~1leads/post

**Comment by todsac** [comment]
This integration is now live.
