### ISSUE TITLE
[ACTION] Fibery - All Similar to Airtable

### ISSUE THREAD

**Issue by ccollins-sg** [PipedreamHQ/pipedream#5535]
**Is there a specific app this action is for?**
Fibery.io , there are no actions for this app. Ideally, I would want all the same types as available Airtable actions. 

- Create Entity
- Create Multiple Entities
- List Entities
- Get Entity or Create
- Create Single Entity or Update

**Please provide a link to the relevant API docs for the specific service / operation.**
https://api.fibery.io/#integrations-api

**Comment by vunguyenhung** [comment]
Hello @ccollins-sg, thank you for raising this issue, we already have [a ticket here](https://github.com/PipedreamHQ/pipedream/issues/3621) tracked for this. 

I've put that ticket into Pipedream prioritized backlog. Pipedream component dev will take a look at it soon.
