### ISSUE TITLE
[APP] Personio

### ISSUE THREAD

**Issue by guy-tallon** [PipedreamHQ/pipedream#5537]
**Name of app / service**
Personio

**Link to developer documentation**
https://developer.personio.de/reference/introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, it's preventing me from building a workflow

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Trigger - New user created or User updated

**Comment by sergioeliot2039** [comment]
Personio uses the Basic + Bearer authentication method:
https://developer.personio.de/reference/post_auth-1

**Comment by sergioeliot2039** [comment]
Component development is blocked until we get the app integration first

**Comment by malexanderlim** [comment]
Hi @guy-tallon , I wanted to reach out to see if you'd be able to directly request to the Personio team that you would like a Pipedream integration to be developed. I've had some back and forth with their team, and they are not granting API access to us at this time, and I believe that having an active user reaching out to them could help to move the needle.

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/personio

**Comment by sergio-eliot-rodriguez** [comment]
Hi @guy-tallon 

We shipped a "new employee created" trigger
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/455d75db-936e-4562-a1e9-c78ebc4bf605)


Can you please check if this is useful for your case?
