### ISSUE TITLE
[BUG] BigCartel sources throw Error: Request failed with status code 404

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5554]
**Describe the bug**
I failed to create BigCartel sources due to error `Error: Request failed with status code 404`
- New Product Event
![image](https://user-images.githubusercontent.com/18277920/220799093-83c7e23a-aa10-4420-abc8-b5c2f5e31162.png)

- New Order Event
![image](https://user-images.githubusercontent.com/18277920/220799238-fccca603-ecef-4e7d-8891-a78c39a28385.png)

**To Reproduce**
1. On Pipedream, access [the Source page](https://pipedream.com/sources)
2. Choose to create a BigCartel source, connect a new BigCartel account
3. Create the BigCartel source, observe the error

**Expected behavior**
The BigCartel source should be created, and the source should work correctly

**Additional context**
Reported by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1676275017367019

**Comment by lcaresia** [comment]
For some reason `account_id` is returning `null` from `$auth`, so I will move to Blocked for now

![image](https://user-images.githubusercontent.com/12402324/220918767-9ce2ec90-4070-448e-83ec-97de16cabe45.png)

**Comment by dannyroosevelt** [comment]
@lcaresia can you try connecting your account again?

**Comment by lcaresia** [comment]
@dannyroosevelt Same error, I create a new account to have sure, but I'm getting the same error.

**Comment by dannyroosevelt** [comment]
Ok I just deployed another change -- can you try reconnecting your account again?

**Comment by dannyroosevelt** [comment]
Oh, do you need account_id? I set `oauth_uid` to the user's account_id. Does that work?

**Comment by vunguyenhung** [comment]
PR https://github.com/PipedreamHQ/pipedream/pull/5772

**Comment by lcaresia** [comment]
@vunguyenhung Thanks!
