### ISSUE TITLE
[Trigger] Coda - New Row Updated

### ISSUE THREAD

**Issue by Kancel-Kultcha** [PipedreamHQ/pipedream#5564]
**Name of app / service**
Coda.io

**Link to developer documentation**
https://coda.io/packs/build/latest/ - https://github.com/coda

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I can probably use a webhook. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

There are two types of table in Coda, one is called a 'SyncTable' - these are flat relational databases, that can hold 10,000 records and will be what 'low-code' users create. A strong interaction would be aware the types of data attribute types between Coda and Pipedream.

With regards to my specific user case, I want to trigger a cloud storage system (Gdrive, Dropbox...) to update any new audio files added to folder, then use pipedream to extract metadata from the audio (artist/title), then save those fields and a file path to a sync table in Coda.

**Comment by sergioeliot2039** [comment]
Hi @Kancel-Kultcha 

Thanks for the request, and welcome to Pipedream!

Coda is integrated:  https://pipedream.com/apps/coda

Plus, it seems that the component you are looking:  
"save those fields and a file path to a sync table in Coda." is compatible to 
"Create Rows with the Coda API", one of the actions available in the Coda app at Pipedream:

![image](https://user-images.githubusercontent.com/25184117/221228780-234ae114-10b6-4e03-935c-6e20c45f9c44.png)


Can you please check it out and let us know if this is helpful to your use case?

> A strong interaction would be aware the types of data attribute types between Coda and Pipedream.

Can you please elaborate on this one? I am not sure if I understand correctly

**Comment by Kancel-Kultcha** [comment]
Thanks @sergioeliot2039 - I searched for Coda but got no result, possibly because of my internet speed / latency. Super glad to see a Coda integration here. With regards to triggers, how would I get once to work when if a row in a designated table was updated? 

Re: A strong interaction would be aware the types of data attribute types between Coda and Pipedream.
PipeDream seems to work with the sync tables, so nothing to action here.

**Comment by sergioeliot2039** [comment]
Hey @Kancel-Kultcha, thanks for the follow up

So, it looks like Coda is able to automate and trigger on all sort of events occred over a document.  See the [Automations ](https://help.coda.io/en/articles/2423860-automations-in-coda) feature.

I see two ways of doing this.

You setup an automation as per that article, to when a row is updated, and in the "then" part of the automation, select Coda notification. Set the Coda notification to an email.

Then on Pipedream you can have a trigger based on an email.

Al alternatively, given a table name, Pipedream could hit the Coda API to pull records and check out which have been updated, and trigger an event on Pipedream accordingly.

I will let the components developments team to decide how to do this. You should see updates here in this issue soon.

**Comment by sergioeliot2039** [comment]
**App**
Coda

**Trigger**
New Row Update

This can be implemented based on a Email notification by coda when the user setups an [Automation](https://help.coda.io/en/articles/2423860-automations-in-coda), or by querying the [Coda API](https://coda.io/developers/apis/v1#tag/Rows/operation/listRows)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
