### ISSUE TITLE
tradingview[APP]

### ISSUE THREAD

**Issue by serh988** [PipedreamHQ/pipedream#5568]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @serh988 

thanks for the request!!

can you confirm this is the website related to the app you are looking to integrate with?

https://www.tradingview.com/

**Comment by chirag8153** [comment]
nice infermation [Trackfast](https://forum.lapostemobile.fr/questions/3080197-mot-oublie-acces-telephone-carte-sim)

**Comment by sergioeliot2039** [comment]
@chirag8153 that Trackfast links to a support article. can you link the correct website?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
