### ISSUE TITLE
Height.app

### ISSUE THREAD

**Issue by jonchui** [PipedreamHQ/pipedream#5579]
**Name of app / service**
height.app

**Link to developer documentation**
https://www.notion.so/API-documentation-643aea5bf01742de9232e5971cb4afda

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yup ! 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
We need to turn instabug, slack comments, notion comments  <> height.app tickets

**Comment by sergioeliot2039** [comment]
They support OAuth 2.o integratino method:
https://height.notion.site/OAuth-Apps-on-Height-a8ebeab3f3f047e3857bd8ce60c2f640

**Comment by sergio-eliot-rodriguez** [comment]
notes on out reach.
email, copied integrations at pd, sergio at pk

head of eng provifed oauth access

**Comment by sergio-eliot-rodriguez** [comment]
Submitted as API key because of error "app cannot be authorized for workspae". asked for helo to height support but they didn't get back to us.
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/4a0e87ea-2844-4063-83e9-18492f056f45)

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/height
