### ISSUE TITLE
[Trigger] GoHighLevel - New Contact

### ISSUE THREAD

**Issue by davidmaxwell** [PipedreamHQ/pipedream#5586]
GoHighLevel

(https://help.gohighlevel.com/support/solutions/articles/48001060529-highlevel-api)

yes, We are committed to GoHighLevel however we would like to integrate Monday which is not feasible at the moment

I would like a customer card to push information into Monday so that a project will start with the relevant customer info (or all of it if that is easier).

**Comment by sergioeliot2039** [comment]
Hi @davidmaxwell ,

thanks for the request, and welcome to Pipedream!!

We have GoHighLevel integrated: https://pipedream.com/apps/gohighlevel

Now, I am triaging for the development team, and I had two questions.

In Monday, when you refer to a project, are you meaning board?
I am unable to see a project entity on their, please check them out, they are on the left navigation under "API Reference": https://developer.monday.com/api-reference/docs

Regarding "customer card", I am unable to find a customer entity on GoHighLevel API, do you mean "contact", or "contact tag" perhaps? Look at the "contact" folder in the API reference for GoHighLevel https://public-api.gohighlevel.com/#0097b747-33c2-452f-8c78-aab5ab36c071

Finally, I see that GoHighLevel supports webhooks, https://help.gohighlevel.com/support/solutions/articles/48001157630-webhooks
You could setup a GoHighLevel webhook to notify a Pipedream's workflow URL. Can you have a look to see if this helps you to start your workflow development?

**Comment by davidmaxwell** [comment]
Hi Sergio,

Apologies for the incorrect lingo.

Not sure why GoHighlevel did not come up in the search but I will try your
link.

For Project, I did mean board.  In high level I think Contact would contain
the information we would need in Monday and contact tag will work as it is
a stage the customer contact information is moved along the lead process
and would be the trigger.

**Comment by sergioeliot2039** [comment]
**App**
GoHighLevel 

**Triggers**
New Contact

Context: User wants to create an automation triggered by a new contact created in gohighlevel, it will create a new board in monday.com

it is likely trigger will be api polled based: https://highlevel.stoplight.io/docs/integrations/ab55933a57f6f-get-contacts
there is a webhook event for contact create but i am unable to inmedially identify if the webhook can be managed programmatically for the trigger to be webhook based: https://highlevel.stoplight.io/docs/integrations/ZG9jOjI5NjI5Mjc5-contact

**Comment by sergioeliot2039** [comment]
all right @davidmaxwell , I updated the GoHighLevel request for a trigger component on New Connect

I found an action component for Monday.com to create a Board: https://pipedream.com/apps/monday/actions/create-board

For sure, let me know if setting up the trigger based on the webhook works for you. Meanwhile, you should see updated soon from the component development building source triggering on new contacts.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by davidmaxwell** [comment]
Hi Sergio.  The trigger can’t be new contact but rather contact tag change equal to a certain tag.

Is this possible?

**Comment by sergioeliot2039** [comment]
Yes, I am guessing it's possible. A trigger that watches for a certain Contact, and emits the events if the Contact's tags now includes certain tag. I updating accordingly

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
