### ISSUE TITLE
[ACTION] Monday.com - Create Board

### ISSUE THREAD

**Issue by sergioeliot2039** [PipedreamHQ/pipedream#5588]
**App**
Monday.com

**Actions**
Create Board

Context: User wants to create an automation triggered by a new contact created in gohighlevel, it will create a new board in monday.com

API docs for Create Board API endpoint: https://developer.monday.com/api-reference/docs/boards#create-a-board

Request on #5586

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergioeliot2039** [comment]
Sorry, This already exists, I did not find it on a first search.

https://pipedream.com/apps/monday/actions/create-board
