### ISSUE TITLE
[ACTION]  Shopify Search Products using Metafields and others

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5589]
Shopify

https://shopify.dev/docs/api/admin-rest/2023-01/resources/product
Is it possible to search "fields" using metafields?
Is it possible to search via SKU? Or is that only product variant?
Is it possible to search via "tags"?
Product Category? Barcode? Price (range)?

I'm trying to create a custom collection based on certain metafield values. It's possible to add an array of products to a custom collection with the new action but its hard to get an array of those products using the "Search Products" action (other than Vendor & Type).

**Comment by zecul** [comment]
Oh, and perhaps search by inventory level (primarily as a filter for in/out of stock but with other uses too).

**Comment by zecul** [comment]
Thanks [vunguyenhung](https://github.com/vunguyenhung)

OK. I see that. Does the "fields" allow you to specify a certain metafield to return (which could then be filtered as you suggested)?

Or is it only the more regular fields such as those mentioned in the example fields=id,images,title
Is fields=product.metafields.custom.genre or similar a possibility?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
