### ISSUE TITLE
in a category page created category are not visible on home page

### ISSUE THREAD

**Issue by DikshaMa** [PipedreamHQ/pipedream#5590]
# Environment
-Magento Version:2.4.0
-Browser : Chrome
-Device used: Lenovo
-Php Version:8.0
-Build detail/commit id:
# Step to preproduced issue
login to admin panel
navigate to catalogues
create a new category 
open homepage

**Comment by vunguyenhung** [comment]
Hello @DikshaMa, would you mind providing more detail on the bug? Specifically the step to reproduce the issue?
