### ISSUE TITLE
gitlab for creating an issue [ACTION]

### ISSUE THREAD

**Issue by sorvis** [PipedreamHQ/pipedream#5591]
**gitlab**

It appears that when creating an issue I cannot select from a list of users in gitlab and it does not utilize a custom value if I just type it in. Also it would be nice to be able to set the iteration of the issue.

**Comment by vunguyenhung** [comment]
Hello @sorvis, I can select an invited user for my case
![image](https://user-images.githubusercontent.com/18277920/222591718-8931345a-abf9-4b1a-8067-efb388a6f7d3.png)
![image](https://user-images.githubusercontent.com/18277920/222592106-ab5a0b8c-1ff6-44ad-9359-a4c5ea802892.png)
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/18277920/222591935-4f7422c3-ac7e-4643-b3c2-3e22d0cdd13f.png">
![image](https://user-images.githubusercontent.com/18277920/222592215-9dbe4c90-c75a-42e4-a0b5-715d423f0bcb.png)

May I ask if you are the owner of the project?
