### ISSUE TITLE
[ACTION] Shopify add multiple products IDs to a custom collection

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5595]
Shopify

Create collection allows multiple products IDs to be added to the same collection:
![image](https://user-images.githubusercontent.com/123815443/222304943-813292fc-1242-4f90-9746-fc1a0b57fefc.png)
![image](https://user-images.githubusercontent.com/123815443/222304954-f51354f3-08d0-4fd6-84fd-bc54a1027292.png)

Add to collection only allows a single product ID to be added to a collection:
![image](https://user-images.githubusercontent.com/123815443/222304984-beeda0f9-c155-4f47-8270-2021b99f0462.png)

**Comment by vunguyenhung** [comment]
Hello @zecul, I have include this into the ticket https://github.com/PipedreamHQ/pipedream/issues/5596. So I will close this one
