### ISSUE TITLE
[IMPROVEMENT] Shopify - Add Products to Custom Collections and Search Custom Collection

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5596]
Shopify
----

There're 2 suggested improvements for this ticket:

1. On the Add Product to Custom Collection action, change it to add Products to Custom Collections, and allow user to select multiple products and multiple collections. The end result is multiple products are added to multiple custom collections
2. Search Custom Collection (by name)
----
**Original message**
I would like to be be able to add a single product ID to multiple custom collections at once. for example I would like to use the "style" metafield on a product to either add to or create multiple collections for the same product.

![image](https://user-images.githubusercontent.com/123815443/222305751-bbffae40-b82b-4197-9bb8-006c8a1e9e42.png)

![image](https://user-images.githubusercontent.com/123815443/222306058-069c5ffc-d8a7-4f6f-af76-027700b1ef88.png)
![image](https://user-images.githubusercontent.com/123815443/222306508-3c67cfd1-00fa-43fb-a0cb-b8887e5e02e2.png)

On the same topic as can be seen above if possible I would like to add a product ID to a collection using the "Collection Title" rather than collection ID. It would make things much easier than having to search for a collection or only adding products to collections that are created in the same workflow. Alternatively some kind of "GET collection" method that would allow us to get the collection ID via a title search.

![image](https://user-images.githubusercontent.com/123815443/222306680-b5870c43-3e66-4a52-83ed-a1265103c84e.png)

**Comment by vunguyenhung** [comment]
Hi @zecul, so I think there're 2 suggested improvements for this ticket:
1. On the Add Product to Custom Collection action, change it to add Product to Custom Collections, and allow user to select multiple collections
2. Search Custom Collection (by name)

I think they're valid, so I'll add this to Pipedream prioritized backlog

**Comment by zecul** [comment]
I haven't used metafields on collections yet, but search collection by metafields might be useful and potentially more accurate too. If that's even a possibility.

Thanks again.
