### ISSUE TITLE
[APP] Memix

### ISSUE THREAD

**Issue by stan-irl** [PipedreamHQ/pipedream#5600]
**Name of app / service**
Memix

Here's the site: https://www.memix.com/

**Link to developer documentation**
API Docs: https://api.memix.com/docs#
[Here's the PR for the action](https://github.com/PipedreamHQ/pipedream/pull/5599) if you want to see exactly what im talking about. Its pretty small.

Here's what the Memixes look like just in case you're interested:
 
![memix-pnr-whiteboard](https://user-images.githubusercontent.com/106506537/222406551-4965b982-4027-41d6-b176-624d7a581edd.gif)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I didn't find a way to build a pre-integrated app

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Not right now but we will definitely let you know if anything comes up

**Comment by sergioeliot2039** [comment]
Hi there @stan-irl thanks for the request!

Just double checking, the API does not require Authentication, correct? you just hit an endpoint, i.e to generate a new Memix and that's it, no need to add basic auth, api key whatsoever.

**Comment by stan-irl** [comment]
thats correct - theres no auth. 

you can check https://partner-api.memix.com/templates and https://media.memix.com/memix-trophy.gif?text=stan-irl%27s%20PR to verify if you'd like

**Comment by dannyroosevelt** [comment]
The app is live here:
https://pipedream.com/apps/memix/

Thanks @stan-irl!

**Comment by stan-irl** [comment]
perfect. should i close this?
