### ISSUE TITLE
Metabase

### ISSUE THREAD

**Issue by Wyattefowler** [PipedreamHQ/pipedream#5602]
**metabase**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @Wyattefowler 

Thanks for the request, and welcome to Pipedream.com!!

Hey buddy one little help, could you please link to Metabase app's website?

**Comment by Wyattefowler** [comment]
https://www.metabase.com/

**Comment by Wyattefowler** [comment]
How soon will I be able to make a trigger via metabase?

**Comment by Wyattefowler** [comment]
Will it be available in trigger apps for other users too?

**Comment by sergioeliot2039** [comment]
Well, first off, which metabase trigger would like to see?

Thanks for the link. You need to specify which triggers you want from metabase. 
can you elaborate?

look, our friend @jverce specified triggers for Rev on #3763 

can you kindly specify which triggers  you need?
we don't want to jump onto triggers development without knowing if they are going to be helpful to you buddy 

> App
> Rev
> 
> Triggers
> New Automated Transcript
> New Caption
> New Order

can you give us a nice list like that one? :)

**Comment by dannyroosevelt** [comment]
@Wyattefowler we should be able to get the app integrated asap -- are you interested in developing the triggers yourself? If so I recommend getting started here: https://pipedream.com/docs/components/quickstart/nodejs/sources/#emit-items-in-an-rss-feed

**Comment by Wyattefowler** [comment]
Yeah I thought I make my own triggers once I click Metabase in the "Search for an app..." feature. Just not seeing metabase as a selectable source.

**Comment by sergioeliot2039** [comment]
I'll submit the app in a few minutes, metabase has a 14 days trial

**Comment by Wyattefowler** [comment]
Okay so it will only be available as a trigger app for 14 days?

**Comment by sergioeliot2039** [comment]
sorry for the confusion @Wyattefowler , you will need to enter your account details. so it will depend if you are on trial or not.

**Comment by Wyattefowler** [comment]
Oh okay perfect. Thank you

**Comment by dannyroosevelt** [comment]
@Wyattefowler can you give this a shot and see if it works for you? If so, that'll unblock you from developing triggers for Metabase.
https://pipedream.com/apps/metabase/

**Comment by Wyattefowler** [comment]
You guys are awesome! Appreciate the instant help/feedback. I will let you know how it goes

**Comment by Wyattefowler** [comment]
I think I figured it out I will come back here if I have issues.

**Comment by sergioeliot2039** [comment]
> I think I figured it out I will come back here if I have issues.

For sure, I'm closing the ticket. Feel free to reopen if there's any
