### ISSUE TITLE
[TRIGGER] Spotify

### ISSUE THREAD

**Issue by mendelsphotography** [PipedreamHQ/pipedream#5620]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
 Spotify. Trigger is, When an artist releases a new song or album then.....

**API Doc**
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-artists-albums

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by mendelsphotography** [comment]
I dont relly know what to do myself. I did not think to look if this exist in other places like zaiper. I see it does not, I wonder why.


Not sure where and want to ask Spotify. 

Besides not even sure how get started to build my own even for myself with Spotify and pipedream.
