### ISSUE TITLE
[ACTION] Download files to temp directory Videos,Images...

### ISSUE THREAD

**Issue by HassanAbbas7357** [PipedreamHQ/pipedream#5621]
**Is there a specific app this action is for?**
Temprory File Management
i feel like in pipedream whenever i want to download something to temp directory i have to write custom scripts like to download image or video or csv file i gotta use custom scripting can we have Actions for that? 
1: Download Image to temp
2: Download Video to temp
3: Download CSV to temp
these actions will download the desired file by taking url and file name as input and output complete url of the file and its name.

**Comment by vunguyenhung** [comment]
hello @HassanAbbas7357, Pipedream has a built-in action to download a file to tmp dir here: https://pipedream.com/apps/helper-functions/actions/download-file-to-tmp

The file type doesn't matter as long as you define the correct extension. Though note that the file should not be too big, as it will exceed Pipedream workflow memory limit
