### ISSUE TITLE
[APP] Formidable Forms Pro

### ISSUE THREAD

**Issue by khophuloi123** [PipedreamHQ/pipedream#5624]
**Name of app / service**
Formidable Forms Pro
**Link to developer documentation**
https://formidableforms.com/knowledgebase/
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @khophuloi123 , thanks for the request, and welcome to Pipedream! We are tracking Formidable Forms Pro at https://github.com/PipedreamHQ/pipedream/issues/4303 feel free to follow, if you'd like
