### ISSUE TITLE
Wise: Get Balance action

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5626]
### App
Wise
https://api-docs.wise.com/

### Actions
- [Get balance](https://api-docs.wise.com/api-reference/balance#get)

#### Context
Reloading my balance.

My use case is we have a bunch of scheduled transfers from our balance. Wise makes us manually load the balance beforehand.
As long as I know how much I need to reload I could just have a Pipedream workflow perform the reload without any human intervention.
You would need to choose the Balance (I guess the default on the acocunt), the amount of money and the source to reload from (could also use my default linked bank).
Might need a separate step to actually confirm the reload.
If the first action could return the estimated fee so you could then make an automatic safety check or whatever before confirming.

**Comment by zalmanlew** [comment]
@dannyroosevelt @lcaresia this action is for getting the balance? Ideally the user could reload their balance as well.

**Comment by lcaresia** [comment]
@zalmanlew Yes, this action is for get the balance. What exatly is reload the balance in this case?
