### ISSUE TITLE
[FEATURE] I'd like to set spending caps on paid tiers, and control usage in more fine-grained ways

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#563]
I'd like to cap my spend on the Professional Tier so that I ensure I don't spend over $X during a given month. 

For example, sometimes I receive events from third party systems that aren't under my control, and these can trigger an unknown number of invocations, so I need a way to cap usage to ensure I don't spend an unlimited amount in these cases.

**Comment by brandrsn** [comment]
This would be good.
A chart of compute time would also be useful too. I know it's unlimited on the Pro tier, but I liked the little chart showing compute time on the Dev plan!

**Comment by dylburger** [comment]
Noted, thanks @brandrsn !

**Comment by dylburger** [comment]
You can now set an invocation budget, per day or per month, in your [Billing and Usage Settings](https://pipedream.com/settings/billing). [See the docs](https://pipedream.com/docs/user-settings/#invocation-budget) for more information!
