### ISSUE TITLE
[Components] SwaggerHub

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5631]
### App
SwaggerHub
https://swagger.io/tools/swaggerhub/

Triggers:
1. New API Version: /apis/{owner}/{api}/versions
2. New API Documentation: /apis/{owner}/{api}/documents

Actions:
1. Create API Version: POST /apis/{owner}/{api}/versions
2. Update API Documentation: PUT /apis/{owner}/{api}/documents/{documentId}
3. Delete API Version: DELETE /apis/{owner}/{api}/versions/{version}

**Comment by andrewjschuang** [comment]
@dannyroosevelt I couldn't find the endpoint for **Create API Version** and **Update API Documentation**, the only one I found was [Clone API Version](https://app.swaggerhub.com/apis/swagger-hub/registry-api/1.0.66#/APIs/cloneApi).
Can you direct me to it?

**Comment by dannyroosevelt** [comment]
> 

This was actually generated by ChatGPT 😱, so I'm still tweaking the input to improve the list it generates for us.

**Comment by andrewjschuang** [comment]
Oh, that's pretty cool!
I submitted a PR, let me know if you feel there are any missing components.
