### ISSUE TITLE
[BUG] OpenAI | gpt-3.5-turbo model endpoint 404

### ISSUE THREAD

**Issue by vexersa** [PipedreamHQ/pipedream#5634]
**Describe the bug**
When using the gpt-3.5-turbo model, the API endpoint is incorrect. It should be v1/chat/completions and not v1/completions for chat related models. 

**To Reproduce**

1. Create an OpenAI action and configure it to use the gpt-3.5-turbo Model ID
2. Input a test prompt
3. Test the action, the following error will appear: 
`{"error":{"message":"This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?","type":"invalid_request_error","param":"model","code":null}}
`
**Expected behavior**
The action should generate a valid response. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7994227/223409802-91d87049-f52f-43be-b4e7-c82e7692da57.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chrome
 - Version 110.0.5481.178 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**

**Comment by dylburger** [comment]
@vexersa We’re working on a new Chat action to interface with the /chat/completions endpoint right now. We’ll let you know when that’s released.

**Comment by vexersa** [comment]
Awesome.

**Comment by dylburger** [comment]
@vexersa Take a look at our new Chat (and other) actions: https://pipedream.com/blog/using-the-new-openai-actions-in-pipedream/

**Comment by vexersa** [comment]
Woohoo thanks! 🙏
