### ISSUE TITLE
postman[APP]

### ISSUE THREAD

**Issue by shivashankari-ss** [PipedreamHQ/pipedream#5637]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Postman
https://www.postman.com/

Postman dev docs
https://learning.postman.com/docs/developer/intro-api/

**Comment by sergio-eliot-rodriguez** [comment]
Postman has been integrated https://pipedream.com/apps/postman?via=go
