### ISSUE TITLE
[ACTION] Pipedream Data Stores / Helper Action

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5640]
Pipedream Data Stores

I would like an ability to exclude keys from a Data Store return.  Basically Data Store A minus Data Store B. 

In my case Data Store A is my total list of products I need to process and Data Store B is the list of products already processed.

Right now the key/value pairs are indentical but I can think of a use where only the keys would match so Data Store A's Key(x1)/Value(y1), Key(x2)/Value(y2)  minus Data Store B's Key(x1)/Value(z1) should return Key(x2)/Value(y2).

**Comment by dylburger** [comment]
Thanks @zecul !

To the implementor: I think there could be value in making this an abstract Helper action for getting the difference between two arrays / sets. We may want to implement [other set actions, too](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), like union, intersection, etc.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
