### ISSUE TITLE
[IMPROVEMENT] Improve the error in the case where the body field of `$.respond` is invalid (.i.e a promise)?

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5645]
**Is your feature request related to a problem? Please describe.**
First reported [by a customer here](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1678146478427709). The user call `$.respond` with the `body` field having invalid value such as a Promise. In this case, the workflow either errored in a general message
![image](https://user-images.githubusercontent.com/18277920/223601596-51439e15-6eb5-4dc0-b656-b97a35dfa9d1.png)

Or got timeout
![image](https://user-images.githubusercontent.com/18277920/223601625-9dca32f2-525e-49cb-9062-8c32082c5799.png)

**Describe the solution you'd like**
Having a clearer error message in case that the `$.respond` having the `body` field with invalid value

**Comment by dylburger** [comment]
We should now throw a timeout, which makes more sense in this case because the Promise remains unresolved
