### ISSUE TITLE
[TRIGGER] New Apollo.io trigger

### ISSUE THREAD

**Issue by ManuelBuri** [PipedreamHQ/pipedream#5649]
**Name of app / service**
https://apollo.io/

**Link to developer documentation**
https://apolloio.github.io/apollo-api-docs/?shell#introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**
lack of support

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Trigger would be the addition of a contact to a certain apollo contact list but I think there are lots of other use cases.

**Comment by sergioeliot2039** [comment]
Hi @ManuelBuri , thanks for the request. Apollo is integrated: https://pipedream.com/apps/apollo-io

I'll modify your ticket with reflect the trigger requested.

**Comment by sergioeliot2039** [comment]
@ManuelBuri one question popped up. the api documentation does not include "contact lists".
did you mean adding a contact to a sequence? https://apolloio.github.io/apollo-api-docs/?shell#add-contacts-to-sequence

for what I can see in Apollo.io knowledge base, sequences are like marketing campaigns:
https://knowledge.apollo.io/hc/en-us/articles/4409237165837-Sequences-Overview

the other option is that perhaps you meant adding a contact to a stage
https://knowledge.apollo.io/hc/en-us/articles/4410623601165-Contact-and-Account-Stages-Overview
https://apolloio.github.io/apollo-api-docs/?shell#get-a-list-of-contact-stages

can you please clarify? thanks!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
