### ISSUE TITLE
[TRIGGER] Outlook - Event notification

### ISSUE THREAD

**Issue by zemdu** [PipedreamHQ/pipedream#5653]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
This is for Microsoft Outlook. Trigger should correspond to a time before an event starts, i.e. 15 minutes before event starts.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by zemdu** [comment]
Sorry I don't have any time at the moment! If it doesn't happen not a huge deal - I have other options.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
