### ISSUE TITLE
Inspector event not loading [BUG] 

### ISSUE THREAD

**Issue by kchasepdx** [PipedreamHQ/pipedream#5657]
**Describe the bug**
https://pipedream.com/@shawn-wm/ln_pd_038-msg_ticket_may_complete_blueprinting-p_n1CVG6D/inspect/2Lpx857KaIxrVSwhMJerHf6tnuf

I am trying to inspect a certain event of one of our workflows ("LN_PD_038") that occurred on February 16. The workflow will not load although the ones from the day before and after work. 

**To Reproduce**
1. Go to 'https://pipedream.com/@shawn-wm/ln_pd_038-msg_ticket_may_complete_blueprinting-p_n1CVG6D/inspect/2Lpx857KaIxrVSwhMJerHf6tnuf'
2. Click on 'the February 16, 2023 instance'
3. Where the workflow should appear, only a loading screen shows'

**Expected behavior**
I can see the steps of the workflow as they happened on 2/16/23 for this event, with logs, exports, details, etc. 

**Screenshots**
If applicable, add scree
<img width="1253" alt="Screen Shot 2023-03-08 at 12 50 47 PM" src="https://user-images.githubusercontent.com/76892231/223847388-884421cf-5fb9-4b4a-bab6-320043e44d90.png">
nshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [Mac OS Big Sur]
 - Browser [chrome]
 - Version [Version 110.0.5481.177 ]

**Additional context**
We suspect the workflow failed during this event, but want to confirm.

**Comment by vunguyenhung** [comment]
THank you @kchasepdx, for the information. Would you mind allow Pipedream support to access your workflow in your Workflow settings?

**Comment by kchasepdx** [comment]
Yes, access has now been granted.

**Comment by dylburger** [comment]
@kchasepdx Apologies for the late reply, I'm just going back through old issues now. Are you still able to reproduce this?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
