### ISSUE TITLE
GA4: Google Analytics[APP]

### ISSUE THREAD

**Issue by jacovanwest** [PipedreamHQ/pipedream#5661]
**GA4: Google Analytics (New)**

**Link to developer documentation**
https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport

I cant continue with bringing 30 new clients onto Pipedream without support for the new GA4

**Similar to the existing Google Analytics app, I would need to request batch run reports for a defined time period, with specific metrics & dimensions**

**Comment by sergioeliot2039** [comment]
Hi there @jacovanwest 

I see the current Google Analytics app
https://pipedream.com/apps/google-analytics
is GA4,

Plus, when you edit a workflow, you can use the "Run Report" actions, this actually allows you to run reprts for a defined time period, and enter metrics, dimensions:

![image](https://user-images.githubusercontent.com/25184117/224105395-2360dd3c-1196-4e80-9806-57c3b3fdae84.png)

Can you please confirm this component is helpful to your use case?

**Comment by jacovanwest** [comment]
> 

Thanks for your reply @sergioeliot2039 I tested this app and it did not work for GA4 properties, only for UA (universal analytics) view id's....Unless I'm missing something?

Thanks again

**Comment by vunguyenhung** [comment]
Hello @jacovanwest, thank you for raising this! You're correct that Pipedream Google Analytics - Run report action only support Universal Analytics property. 

I've updated the description for Pipedream team to implement the new action that uses GA4. I'll add this into Pipedream prioritized backlog!

**Comment by jacovanwest** [comment]
> Hello @jacovanwest, thank you for raising this! You're correct that Pipedream Google Analytics - Run report action only support Universal Analytics property.
> 
> I've updated the description for Pipedream team to implement the new action that uses Data API V1 (Beta) that supports GA4. I'll add this into Pipedream prioritized backlog!

Thank you @vunguyenhung What is the timeline on this? By when would we be able to use it? I need to plan this implementation and finalise the tech we will use in the scope

**Comment by vunguyenhung** [comment]
Hello @jacovanwest, the ticket in prioritized backlog typically finish within a week. Though the timeline is highly dependent on the dev workload and the task complexity

**Comment by alysonturing** [comment]
Hello @dannyroosevelt, and I believe that our current Google Analytics app hasn't the scopes necessary to call the required endpoint to fulfill this task;

Here is the error that Google Analytics is throwing:

`PERMISSION_DENIED: Google Analytics Data API has not been used in project 277994997063 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/analyticsdata.googleapis.com/overview?project=277994997063 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.`

<img width="813" alt="image" src="https://user-images.githubusercontent.com/103650302/225418260-91733ecc-f9d3-4068-bbf6-657359003579.png">

for now, I'll move this task to the blocked session, feel free to ping me when it's possible to move forward on this task.

**Comment by jacovanwest** [comment]
@dannyroosevelt @alysonturing @vunguyenhung I raised this just over a month ago. My integration is at a standstill because of this limitation. Please urgently let me know if you are going to provide support for GA4. If not, I will have to move to a complete different platform and solution

**Comment by vunguyenhung** [comment]
Sorry for the late response @jacovanwest.

Hello @dannyroosevelt @malexanderlim @sergioeliot2039 , could you please take a look to help adding the scope required for Data API V1 (Beta)?

**Comment by malexanderlim** [comment]
@jacovanwest, we will be able to provide support for GA4 shortly, as the necessary scope has been added for the new Data API V1. @vunguyenhung this was added recently.

@alysonturing - Can you please build a new action, Run Report in GA4 which uses the new parameter `property`?
https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport

**Comment by alysonturing** [comment]
@malexanderlim sure, I'm working on it
