### ISSUE TITLE
[FEATURE] get a temporary download URL for files in `/tmp`

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#5662]
### Is your feature request related to a problem? Please describe.
A lot of actions (such as attaching a file) require providing a publicly accessible file download URL. 
I'd like to be able to attach files from `/tmp` but there's no publicly accessible URL for files in `/tmp`.

### Describe the solution you'd like
When uploading a file to an HTTP trigger, Pipedream automatically sends it to an S3 bucket temporarily. Ideally there would be some way to reproduce this same functionality and access the URL in a future step.

These files can also be automatically purged after a short period of time. The files uploaded via HTTP request are saved for 30 minutes before they expire.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/35234925/224059905-2b08a99d-2d7d-497c-b2b1-d39c2ade6f4b.png">

### Do you have a workaround?
Setting up my own s3 instance and uploading there.

**Comment by zalmanlew** [comment]
As a workaround for now I created a generic workflow which is used to upload the file (using the existing functionality) and just returns the URL.

It uses an HTTP trigger with the following code action

```javascript
export default defineComponent({
  async run({ steps, $ }) {
    await $.respond({
      status: 200,
      headers: {},
      body: Object.values(steps.trigger.event.body)[0].url,
    })
  },
})
```

Then I created a reusable component for uploading a file from `/tmp` to this URL and returning the file URL.

Now in all my workflows I just use my **Get File URL** component when I need to get the URL from a file in `/tmp` - just passing it the path to the file.

`{UPLOAD_WORKFLOW_URL}` is the URL of the upload workflow

```javascript
import axios from "axios";
import FormData from "form-data";
import fs from "fs";
import Path from 'path'

export default defineComponent({
  name: "Get File URL",
  key: "zl-get-file-url",
  version: "0.0.3",
  type: "action",
  props: {
    filePath: {
      type: "string",
      label: "File Path",
      description: "Path to file from `/tmp`",
    },
  },
  async run({ $ }) {
    const data = new FormData();
    data.append(Path.parse(this.filePath).base, fs.createReadStream(this.filePath));

    const config = {
      method: 'POST',
      url: '{UPLOAD_WORKFLOW_URL}',
      headers: { ...data.getHeaders() },
      data: data
    };

    const response = await axios(config);
    return response.data;
  },
})
```

**Comment by dylburger** [comment]
This is a cool request but not something we're planning to implement. These files are ephemeral by design and only available in workflows. Like you already implement, we recommend an HTTP-triggered workflow if you need to provide files via HTTP like this.
