### ISSUE TITLE
[ACTION] Enhancement: Support send from email for Gmail action

### ISSUE THREAD

**Issue by tkrunning** [PipedreamHQ/pipedream#5663]
**Is there a specific app this action is for?**

Gmail (Send message)

It would be great if it was possible to set the `from` address when sending messages with the Gmail app.

**Comment by vunguyenhung** [comment]
Hello @tkrunning, I see that Gmail having the from name prop
<img width="735" alt="image" src="https://user-images.githubusercontent.com/18277920/224186179-ccae16da-d57f-4c66-8515-4a49a33c938a.png">

I believe Gmail doesn't allow us to set the from email differ from the gmail that we logged in. If you would like another email, you can create a new account and connect it to Pipedream instead

**Comment by tkrunning** [comment]
I know Zapier and others support a custom "from email", so it should be possible to set. It needs to be added to the Gmail account in question, of course (as an alias or similar), if not it'll fail.

I'm not comfortable with the whole PR process here yet, but it seems to me that these two lines would be key to update (+ adding the relevant prop):

https://github.com/PipedreamHQ/pipedream/blob/aa63815ff5255ef3550fb0cd18e5481e93892667/components/gmail/gmail.app.mjs#L181-L182

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
I don't remember if we already looked into this -- @andrewjschuang do you recall if we're able to set the from email in the main Gmail app, or if we were missing a scope?

**Comment by andrewjschuang** [comment]
Exactly, it isn't possible in the Gmail app because of missing scopes. I believe that it is possible, though, with the Gmail Developer scopes

**Comment by vunguyenhung** [comment]
Hi @dannyroosevelt @andrewjschuang, I have created a new ticket here to add more scope to the Gmail app. 

@andrewjschuang would you mind checking the ticket and input the precise scope that needed?

**Comment by ExpertLearner7** [comment]
Hello, we are trying to migrate from Zapier to Pipedream but we need to send emails from an alias. I see this action is supposed to add that option but it couldn't be done? I ignore exactly how does it work, but I'm in the same position that Pipedream may be able to do it if Zapier does it? So, I'm just curious if it's possible now a few months later? or if we can do it any clue about how?
