### ISSUE TITLE
[BUG] Shopify update_product

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5675]
I think I found a small bug here. I'm not sure if its a real bug or if its just bad practice on my part.

I have 2 metafields named
product.metafields.labels.name
product.metafields.artists.name

The update metafields action is getting confused between the 2 (because they have the same key I assume) even though they have a different namespace.

when I write the update input as:

{{ [{ "key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Label), "type":"list.single_line_text_field", "namespace": "labels" },
{ "key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Artist), "type":"list.single_line_text_field", "namespace": "artists" }] }}

the product.metafields.labels.name field will *sometimes* be filled with the product.metafields.artists.name data

If I do the reverse and write {{ [{ "key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Artist), "type":"list.single_line_text_field", "namespace": "artists" },{"key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Label), "type":"list.single_line_text_field", "namespace": "labels" }] }}
then the product.metafields.artists.name field will *sometimes* be filled with the product.metafields.labels.name data.

![image](https://user-images.githubusercontent.com/123815443/222131329-54175d1b-6f6b-4417-83e9-9df6eaa1c238.png)
![image](https://user-images.githubusercontent.com/123815443/223553980-7348997a-d7c8-42ba-8123-12d7f466d70a.png)
^ In both cases the artist name has appeared in the label name field or the label name has appeared in the artist name field (depending on the order of the code)

I find it hard to replicate this error everytime so I dont know if its somewhat luck based/random. I'm only 80% sure its not some sort of typo/error in my coding but I've checked and reworked it quite a few times and it works fine almost all of the time except every now and again throws up the error mentioned. I should probably just rename them, but I thought it was worth mentioning in case either I'm doing something wrong or the code isn't checking the namespace properly (or early enough).

This is a similar case where instead of updating with the wrong info it just won't update at all because of 422 - Unprocessable Entity - {"errors":{"key":["must be unique within this namespace on this resource"]}}. The key is not unique on its own but the namespace is unique and I thought that would handle it.
![image](https://user-images.githubusercontent.com/123815443/224222848-8783c26f-0a7a-4da6-8107-799ba0dae026.png)
![image](https://user-images.githubusercontent.com/123815443/224222858-3887493d-9dab-4553-a179-7f11e5b828d8.png)

**Comment by vunguyenhung** [comment]
Hello @zecul, 
Pipedream will send the metdafields as is to Shopify, and Pipedream can not control how Shopify process it. 

Your input having 2 object with the same `key: 'name'` field even though they have different namespace, I think this is not expected by Shopify and might cause unexpected behavior.
```
{{ [{ "key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Label), "type":"list.single_line_text_field", "namespace": "labels" },
{ "key": "name", "value": JSON.stringify(steps.Discogs_Data_Extractor.$return_value.Artist), "type":"list.single_line_text_field", "namespace": "artists" }] }}
```

Maybe you can add prefix or postfix to your key name .i.e name-labels, name-artists?

**Comment by zecul** [comment]
I've been asking around about this and so far the only reply I have is:

They only have to be unique at the resource.namespace.key level.
The conflicts you are describing shouldn't be possible, so I would review the code setting them very carefully.

I'm going to leave the keys as is right now since the conflict is a tiny percentage and I'm interested in what happens in the name of science.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
