### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by Techyprovisions** [PipedreamHQ/pipedream#5677]
**IDXBroker**

**[Link to developer documentation](https://middleware.idxbroker.com/docs/api/methods/index.html)**

**Is lack of support preventing you from building workflows, or do you have a workaround? YES**

**I will like to be able to add new contacts from IDXBroker to Gohighlevel**

**Comment by dannyroosevelt** [comment]
@Techyprovisions can you confirm this works for you?
https://pipedream.com/apps/idx-broker

Are there specific triggers and actions you'd like to see?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
