### ISSUE TITLE
[APP] LinkedIn Lead Gen ads

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#568]
**Name of app / service**
LinkedIn Lead Gen ads

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Duplicate of #932 , tracking there.
