### ISSUE TITLE
[APP] Weaviate

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#5693]
**Name of app / service**

Weaviate

**Link to developer documentation**

Different APIs, see: https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-openai#example

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

[Get Embeddings](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-openai#example)

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/weaviate
