### ISSUE TITLE
[IMPROVEMENT] Notion - Update page action: add instructions for adding values into `Property Types Values` prop

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5697]
**Is your feature request related to a problem? Please describe.**
I created a Notion page with the `Status` property
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/18277920/224600419-cab9ab17-b9f9-4326-b882-522e533d2516.png">

Then I tried to use Notion - Update Page action to update the `Status` property using the `Property Types` and `Property Types Values` prop
![image](https://user-images.githubusercontent.com/18277920/224600545-5d42662a-9bb9-4603-a4c5-b34aaa55ca48.png)

But the page is not updated, and I'm not sure how to input the correct value

**Describe the solution you'd like**
- Add instructions for adding values into `Property Types Values` prop, for example, how to update the `Status` property, or
- Fetch the current page property as async props and allow user to select it

**Do you have a workaround?**
No

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1678650032024909

**Comment by andrewjschuang** [comment]
We still can't use async props since it depends on the missing `additionalProps` functionality with custom expressions

**Comment by andrewjschuang** [comment]
[The status property cannot be updated via API, only via Notion UI.](https://developers.notion.com/reference/property-object#status)
Confirmed by the customer.

![image](https://user-images.githubusercontent.com/15385076/224768127-305a5a7c-3a61-4165-8187-38cb260d6ee4.png)
