### ISSUE TITLE
[TRIGGER] Telegram

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#57]
You can create a webhook using your bot credentials: https://core.telegram.org/bots/api#setwebhook

**Comment by todsac** [comment]
New Updates | Triggers when there is a new update from your Telegram Desktop application.
Need to do more research on telegram to determine what, if any, sources are relevant.

**Comment by sergio-eliot-rodriguez** [comment]
1 week&nbsp; follow up

**Comment by sergio-eliot-rodriguez** [comment]
1 week&nbsp; follow up
