### ISSUE TITLE
direcus

### ISSUE THREAD

**Issue by ravignextbits** [PipedreamHQ/pipedream#5701]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
hi @ravignextbits 

thank you for the request and welcome to Pipedream!

For your app request. did you mean "Directus"? whose website is https://directus.io/ ?

I would appreciate your clarification.

Thanks
