### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pjamesscaife** [PipedreamHQ/pipedream#5703]
**Describe the bug**
Google sheets integration not catching updates. 

**To Reproduce**
1. Go to "Social Enrich Data"
2. Connect Spreadsheet as trigger
3. Update row in Google Sheet
4. Wait for response - 

**Expected behavior**
Row catches update and starts workflow. This does not happen.,

**Additional context**

**Comment by vunguyenhung** [comment]
Hello @pjamesscaife, as I have commented [here](https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1678714005157169?thread_ts=1678663633.795599&cid=CMZG4EBJ9), maybe you have not gave Pipedream enough permisson when connecting to Google Sheet account. You can try to remove Pipedream from your [Google Account Permission page](https://myaccount.google.com/security) and try to reconnect again?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
