### ISSUE TITLE
Resend

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5708]
### App
Resend
https://resend.com/docs/api-reference/send-email

### Triggers
- Email Delivered
- Email Opened
- Email Bounced
https://resend.com/docs/webhooks#event-types

### Actions
- Send Email

**Comment by GTFalcao** [comment]
Hi @bizyb , are you working on this?

**Comment by GTFalcao** [comment]
@dannyroosevelt from the documentation, it looks like the webhooks have to be configured on Resend's dashboard manually - there doesn't seem to be an endpoint we can use to set our URL as the webhook target and associate the event types.

I also checked their Node.js SDK and found nothing related to webhooks there either.

In this case, would it make sense to have multiple triggers for this app, or even a trigger at all? I'm not sure if we have another way to setup this type of webhook on our end - perhaps as a "specialized" version of the basic HTTP request trigger?

**Comment by dannyroosevelt** [comment]
Ah that's too bad. We could support this with an apphook, but that'll need to get prioritized with the core engineering team. For now let's skip the triggers. I assume they don't have GET endpoints that you could poll?

**Comment by GTFalcao** [comment]
Gotcha. No, there's no endpoint to list emails, only GET for a single email (with the provided id) which would suit an action.
