### ISSUE TITLE
[BUG] Cannot import smartsheet-python-sdk

### ISSUE THREAD

**Issue by persicom** [PipedreamHQ/pipedream#5712]
**Describe the bug**
When trying to import a Python package <smartsheet-python-sdk> in Pipedream, an error message appears.

**To Reproduce**
1. Import the module: '# pipedream add-package smartsheet-python-sdk'
2. Type 'import smartsheet'
3. Run the code

**Expected behavior**
The code should be able to access the module

**Desktop (please complete the following information):**
 - Browser Chrome latest version

**Comment by vunguyenhung** [comment]
Hello @persicom, as Python support in Pipedream is still in public beta stage, would you mind sharing your python code and error in [a comment on the issue here](https://github.com/PipedreamHQ/pipedream/issues/5086) so that Pipedream team can triage it?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by Tricky6972** [comment]
I am experiencing a similar issue. I am not sure if the python code attempts to run before the module is done importing, because very occasionally it has imported.  

![bad py](https://github.com/PipedreamHQ/pipedream/assets/132513337/37adac3a-8d8f-4cd8-bc0d-ecde78b16728)
