### ISSUE TITLE
[TRIGGER] Exact Online - New subscriber

### ISSUE THREAD

**Issue by Qlikflow** [PipedreamHQ/pipedream#5718]
**Trigger**
Exact Online - New subscriber

**API Doc**
https://start.exactonline.nl/docs/HlpRestAPIResources.aspx?SourceAction=10

**Context**
Hi, I have connected both Sendinblue and Exact Online accounts (through Run Node.js) into Pipedream. The next step is to make a workflow when we add a new subscriber in Exact Online that subscriber automatically pushes into our Sendinblue account. Unfortunately I can't find (a new subscriber) Exact Online as a trigger. How do I solve this?

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
