### ISSUE TITLE
[APP] Refersion

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#5723]
**Name of app / service**
Refersion

**Link to developer documentation**
https://www.refersion.dev/reference/welcome-to-refersion

**Is lack of support preventing you from building workflows, or do you have a workaround?**
yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
@todsac , Refersion is integrated; https://pipedream.com/apps/refersion

would you like to suggest actions or triggers?
