### ISSUE TITLE
[APP] Zoho Survey

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#5724]
**Name of app / service**
Zoho Survey

**Link to developer documentation**
https://www.zoho.com/survey/integrations.html

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
 - Survey Response Submission

**Comment by malexanderlim** [comment]
Zoho Survey base integration is complete.
