### ISSUE TITLE
[SOURCE] Shopify

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#573]
**Describe the event source. What app, what event?**
Shopify

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
New Event (generic) | Triggers when a new order/product/etc is created, updated or deleted.
New Shipment | Triggers for a new Shipment
New Abandoned Cart | Triggers when a new abandoned checkout is added.
New Customer | Triggers when a new customer is added.
New Article | Triggers when a new article is added.
New Order | Triggers when a new order is added.
New Page | Triggers when a new page is added.
New Product | Triggers when a new product is added.

**Comment by michelle0927** [comment]
**Updated list with links to the relevant API docs for the specific service / operation this trigger is tied to.**

- New Event (generic) | Triggers when a new order/product/etc is created, updated or deleted.
	POST /admin/api/2020-10/webhooks.json
	https://shopify.dev/docs/admin-api/rest/reference/events/webhook 
- New Shipment | Triggers for a new Shipment
	POST /admin/api/2020-10/webhooks.json
		data.webhook.topic = ‘fulfillmentEvent/create’
	https://shopify.dev/docs/admin-api/rest/reference/events/webhook 
- New Abandoned Cart | Triggers when a new abandoned checkout is added.
	GET /admin/api/2020-10/checkouts.json
	https://shopify.dev/docs/admin-api/rest/reference/orders/abandoned-checkouts#index-2020-10
- New Customer | Triggers when a new customer is added.
	POST /admin/api/2020-10/webhooks.json
		data.webhook.topic = ‘customers/create’
	https://shopify.dev/docs/admin-api/rest/reference/events/webhook 
- New Article | Triggers when a new article is added.
	GET /admin/api/2020-10/blogs/{blog_id}/articles.json
	https://shopify.dev/docs/admin-api/rest/reference/online-store/article#index-2020-10 
- New Order | Triggers when a new order is added.
	POST /admin/api/2020-10/webhooks.json
		data.webhook.topic = ‘orders/create’
	https://shopify.dev/docs/admin-api/rest/reference/events/webhook 
- New Page | Triggers when a new page is added.
	GET /admin/api/2020-10/pages.json
	https://shopify.dev/docs/admin-api/rest/reference/online-store/page#index-2020-10 
- New Product | Triggers when a new product is added.
	POST /admin/api/2020-10/webhooks.json
		data.webhook.topic = ‘products/create’
	https://shopify.dev/docs/admin-api/rest/reference/events/webhook
