### ISSUE TITLE
[IMPROVEMENT] Shopify - Get Metafield action: Add Namespace and key prop for filtering

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5730]
Add Namespace & Key as prop fields on Shopify Get Metafields.

I would like to be abe to "get_metafields" by resource>namespace>key
Ideally it would allow multiple namespace/keys to be entered as an array to remove the need for multiple get_metafield steps to access multiple metafields.

Currently the get_metafields action returns all the metafields that a product has in the order that they appear (and skips them if empty) so its not possible to process multiple products in the same workflow (because they each have a different index value)

Product 1:
![image](https://user-images.githubusercontent.com/123815443/225170377-b13a84e6-ad42-4924-8d66-6921ecfd5e21.png)
Product 2:
![image](https://user-images.githubusercontent.com/123815443/225170632-332e8ad2-a506-4559-a783-e1f9f62f428e.png)

For the first product the labels.name metafield is in position 14 and in the 2nd product it's in position 15. I want to create a workflow that processes all my products in order but I need to know where the metafields are going to be for each product in order to update them correctly:

![image](https://user-images.githubusercontent.com/123815443/225170988-32d8073d-48ed-41cf-807e-da569099a9ac.png)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
