### ISSUE TITLE
[Integration Request] Not able to access Bybit API from Pipedream workflows. Error 403

### ISSUE THREAD

**Issue by DailyGameMoments** [PipedreamHQ/pipedream#5733]
**[Integration Request]**
![Not able to access Bybit API from Pipedream workflows  Error 403](https://user-images.githubusercontent.com/127945318/225286791-f7dce03a-35cf-454c-848b-d6d0e7bba3c7.jpg)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes.
Error - Request failed with status code 403
"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"[http://www.w3.org/TR/html4/loose.dtd\](http://www.w3.org/TR/html4/loose.dtd/)">\n<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size=\"1px\">\nBad request.\nWe can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear=\"all\">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear=\"all\">\n<HR noshade size=\"1px\">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: 63CwxztdyB816lAV0inEXp4wnf3Gnqih0bkv5oJqeVPlhWMm_foqSg==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>”

Issues:
Not able to browse the symbol list from pipedream workflow (refer to the jpg file below) at all which used to be able to access few weeks ago. 

![Not able to access Bybit API from Pipedream workflows  Error 403](https://user-images.githubusercontent.com/127945318/225287051-b4a58c9e-a54e-4cab-8c77-d9e835b09401.jpg)

**Comment by vunguyenhung** [comment]
Hello @DailyGameMoments, thank you for raising this issue. We have another issue raised here: https://github.com/PipedreamHQ/pipedream/issues/5641. Kindly subscribe to it for updates. Hence, I will close this ticket 🙏
