### ISSUE TITLE
[BUG] Github - New Card in Column (Classic Projects) - Trigger can't be created

### ISSUE THREAD

**Issue by luancazarine** [PipedreamHQ/pipedream#5735]
**Describe the bug**
When I try to create this trigger, it returns an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/5638699/225348523-cc2e263b-52ba-4e9a-9145-ef74311036f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome

**Additional context**
The trigger description says to use 'New Issue with Status' for v2 projects, once I don't know the version I've tested this one too, but It doesn't show any organization in prop Orgs.
![image](https://user-images.githubusercontent.com/5638699/225348876-11516382-5275-4dd1-bc3e-a893c941691c.png)

**Comment by alysonturing** [comment]
Investigation report: 
> I found out that, classic projects are deprecated, so it's virtually impossible to create one at this moment [see more information here](https://github.com/orgs/community/discussions/30227#discussioncomment-3519567), 
> If you are trying to create a hook on a Github repository, and you don't have the required permissions (`admin:repo_hook`), you will receive the 404 error [see more information here](https://github.com/octokit/octokit.js/issues/155#issuecomment-350058541), 
> You can't list projects on the prop `projects` (due api restrictions) if your repository is not enabled for `Classic Projects`, so if you are seeing a project under that prop, it means that the repository is enabled for `Classic Project` and then the endpoints for projects v2 will not work for you  [see more information here](https://docs.github.com/en/rest/projects/projects?apiVersion=2022-11-28#list-organization-projects).

With all that said, the only solution that I found was throw a ConfigurationException, saying that **you received the 404 error, and the reason is very likely to be that you don't have enough permission to perform that request.**

**Comment by vunguyenhung** [comment]
Hello @alysonturing, I understand the reason for this. I'll move this to ready for release.
