### ISSUE TITLE
[BUG] 403 error creating Square triggers

### ISSUE THREAD

**Issue by pderksen** [PipedreamHQ/pipedream#5738]
**Describe the bug**
I connected to my Square account and am getting errors just creating the trigger.
The connection to my Square account seems fine, but when I Create Source I get errors.
Tried both New Booking Created and New Customer Created triggers.

**To Reproduce**
1. In a new workflow, add a Square trigger
2. Select New Booking Created or New Customer Created & connect to a Square account
3. Click Create Source

**Expected behavior**
Trigger is created and we can move on to creating an action step.

**Screenshots**
![image](https://user-images.githubusercontent.com/79667/225395219-4058db44-3143-43fe-90ee-7ea229c2ba41.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 110.0.5481.78

**Additional context**

Stack Trace:
```
Error:
Request failed with status code 403
    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by dannyroosevelt** [comment]
I think this was related to insufficient scopes in the OAuth configuration with Square — we just modified the app’s configuration. Can you try first reconnecting your Square account, then trying to create that source again?

**Comment by pderksen** [comment]
That didn't do it. Resulted in the same error. Deleted the Square account, recreated (connected successfully), deleted the workflows, recreated, still same error.

**Comment by dannyroosevelt** [comment]
> That didn't do it. Resulted in the same error. Deleted the Square account, recreated (connected successfully), deleted the workflows, recreated, still same error.

Darn, thanks. Someone from the team will take a look asap.

**Comment by michelle0927** [comment]
@dannyroosevelt This is strange. The full error says the scope that's missing is DEVELOPER_APPLICATION_WEBHOOKS_WRITE, but it looks like we do have that scope?

<img width="1001" alt="Screenshot 2023-03-16 at 3 25 05 PM" src="https://user-images.githubusercontent.com/10889229/225732967-1b2eee1c-7bdd-4319-8c7e-a28c3721355a.png">
<img width="1126" alt="Screenshot 2023-03-16 at 3 25 37 PM" src="https://user-images.githubusercontent.com/10889229/225732989-77c53d26-67f4-4c36-8c56-deee0942c392.png">

**Comment by dannyroosevelt** [comment]
Ah darn this is pretty hidden in their docs, but should explain it:
https://developer.squareup.com/docs/webhooks/webhook-subscriptions-api
>Because webhook subscriptions are owned by the application and not any one seller, you cannot use OAuth access tokens with the Webhook Subscriptions API. You must use the application's [personal access token](https://developer.squareup.com/docs/build-basics/access-tokens).

We'd need to do some custom work to support this on the backend with an apphook, so unfortunately polling triggers are going to be the solution in the interim I think.

**Comment by dannyroosevelt** [comment]
Tracking the apphook here https://github.com/PipedreamHQ/pipedream/issues/5771
