### ISSUE TITLE
[BUG] Linear app integration is not passing custom labels

### ISSUE THREAD

**Issue by getlocaladmin** [PipedreamHQ/pipedream#5739]
**Describe the bug**
While integrating Linear with Jira, I noticed that all of my custom labels are not being pulled in from Linear. I am only able to see the default labels.

**To Reproduce**
1. Go to linear /settings/labels
2. Add label group
3. Add two labels into the new label group
4. Go to any existing issue and add one of the new labels to that issue
5. Go to linear integration and pull in a sample issue that has proper labels
6. Inspect retrieved data, labels and label groups are missing

**Expected behavior**
Labels are retrieved preferably grouped by label groups per each issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/113044451/225401840-7b846ea8-809b-4a95-bb1a-923b1c24e242.png)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
