### ISSUE TITLE
[BUG] Linear integration should also retrive labels and emails for additional issue elements

### ISSUE THREAD

**Issue by getlocaladmin** [PipedreamHQ/pipedream#5740]
**Describe the bug**
When configuring Linear App integration with Jira, it is important to be able to map all suporting elements from Linear to Jira for seamless integration.

Fields that should include additional details:
_assignee: Should include email
_creator: Should include email
_project: Should include project name
_state: Should include state name
_Team: Should include teams name

**To Reproduce**
1. Connect linear app
2. Pull in one issue
3. Inspect above fields
4. Mentioned fields are missing important values

**Expected behavior**
Above fields show appropriate labels

**Screenshots**
![image](https://user-images.githubusercontent.com/113044451/225403270-74caa102-b1c4-40c9-8acb-2fd285989b93.png)

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
