### ISSUE TITLE
[FEATURE] Linear Figma integration should parse URL's from description field

### ISSUE THREAD

**Issue by getlocaladmin** [PipedreamHQ/pipedream#5741]
**Is your feature request related to a problem? Please describe.**
When synchronizing Linear to Jira, it is currently not possible top parse Figma links to a custom field in Jira. Links are embedded in the body of description field

**Describe the solution you'd like**
Embedded Figma links should be extrapolated as separate field so we can map it to a receiver like Jira custom field

**Do you have a workaround?**
Nope

Screengrab
![image](https://user-images.githubusercontent.com/113044451/225403891-a5894a48-9ab2-4976-ab71-cbe3a6c9d42c.png)

**Comment by vunguyenhung** [comment]
Hello @getlocaladmin, PIpedream has a built-in helper to allow you to extract the url from text. Would you mind giving it a try?

<img width="914" alt="image" src="https://user-images.githubusercontent.com/18277920/225695493-65640feb-29e3-4e5d-9dbf-50d5043c4b68.png">
<img width="913" alt="image" src="https://user-images.githubusercontent.com/18277920/225695612-17175c89-039c-4a4e-88ed-3a06c7b7f04b.png">

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
