### ISSUE TITLE
Habitify [APP]

### ISSUE THREAD

**Issue by EpistemicPolymath** [PipedreamHQ/pipedream#5743]
**Name of app / service**

https://www.habitify.me/

**Link to developer documentation**
https://docs.habitify.me/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by malexanderlim** [comment]
Hi @EpistemicPolymath , I'm happy to share that we now have a basic integration in place with Habitify! Please have a look at the apps marketplace page to get started (https://pipedream.com/apps/habitify).

We've added building actions and triggers for Habitify to the component development backlog, but if you'd like to self-service this as Dylan mentioned, you are able to author and publish your own Pipedream actions in the interim.

**Comment by GTFalcao** [comment]
@malexanderlim , looks like this had a component shipped on #6035 so perhaps this issue can be marked as closed as well?

**Comment by malexanderlim** [comment]
Thanks @GTFalcao for the heads up. @EpistemicPolymath, we're all set here!
