### ISSUE TITLE
[APP][TRIGGER] SavvyCal integration, New SavvyCal triggers

### ISSUE THREAD

**Issue by acreconsulting** [PipedreamHQ/pipedream#5744]
**Name of app / service**
SavvyCal

**Link to developer documentation**
https://savvycal.com/docs/api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Have a workaround - SavvyCal posts to a webhook just fine. 

But the problem is it posts to a webhook for EVERY event type. So for example, I might have event.requested then event.confirmed then event.created then workflow.triggered.action all posting to the same webhook - this uses 4 invocations, but the first step I would do would be to filter to only use some event types. My workflow might only do something for one of those event types, so that's 4x as many invocations as I would like to actually use.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

I want a trigger to be a new thing happening in SavvyCal. There are 8 event types so I'd like the trigger to filter by event type: 

- [event.created](https://savvycal.com/docs/api/webhooks/payloads/#event.created)
- [event.requested](https://savvycal.com/docs/api/webhooks/payloads/#event.requested)
- [event.approved](https://savvycal.com/docs/api/webhooks/payloads/#event.approved)
- [event.declined](https://savvycal.com/docs/api/webhooks/payloads/#event.declined)
- [event.rescheduled](https://savvycal.com/docs/api/webhooks/payloads/#event.rescheduled)
- [event.canceled](https://savvycal.com/docs/api/webhooks/payloads/#event.canceled)
- [poll.response.created](https://savvycal.com/docs/api/webhooks/payloads/#poll.response.created)
- [workflow.action.triggered](https://savvycal.com/docs/api/webhooks/payloads/#workflow.action.triggered)

And ideally by linkID.

So ideally:

1. What SavvyCal account?
2. What type(s) of event?
3. What link(s), or any link?

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by acreconsulting** [comment]
> Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.
> 
I'm not really a coder but I dabble; I could look into it but I don't expect any results anytime soon...

**Comment by dannyroosevelt** [comment]
FYI here is a basic integration, we'll get the triggers prioritized asap!
https://pipedream.com/apps/savvycal/
