### ISSUE TITLE
[BUG] In Jira integration, when sending a URL custom field fails

### ISSUE THREAD

**Issue by getlocaladmin** [PipedreamHQ/pipedream#5745]
**Describe the bug**
Trying to push a valid URL to jira custom url field fails

**Expected behavior**
It goes through

Passed data: 
`{"fields":{"summary":"Footer","issuetype":{"id":"10000"},"project":{"id":"10007"},"customfield_10076":"3782d0c8-0ffc-443e-bef8-2a3f8c08490b","customfield_10011":"Footer","customfield_10075":"\"https\": //linear.app/tradeblock/issue/ENG-11/footer","description":{"type":"doc","version":1,"content":[{"type":"paragraph","content":[{"text":"[Master Footer - M3 Master File (Figma)](https://www.figma.com/file/0LSY9ZXSh6PMRspNe9GAMt/M3-Master-File?node-id=53333%3A29290&t=VoqpEzJSu6QurZYT-4)\n\nFooter is constructed of two components, \"nav-bar\" (the wrapper) and footer \"item\". \"nav-bar\" is wrapping multiple \"nav-bar-item(s)\" with their corresponding props.\n\nnav-bar-item props:\n\n1. State: \n\n* Default\n* Pressed\n* Selected\n\n2. Notification indicator:\n\n* Enabled\n* Disabled\n\n3. Link\n   1. slug\n   2. Label\n   3. icon path\n\nAnimation Specifications:\n\n1. On tap/click change state to \"pressed\"\n   1. Animation: Ease out\n   2. Animation duration: 100ms\n   3. When animation is over: Change state to \"selected\"\n2. When one/any icon is in a selected state, and a user taps on another inactive icon:\n   1. Change state of the active icon to inactive\n   2. Animate taped/clicked icon as outlined in above step 1\n\nFunctionally requirements:\n\nPage:\n\n* Depending on which page a user is at, the CMS will retrieve associated footer.\n  * While building pages in the CMS, we define which footer configuration should be used for a selected page.\n* All items that should be rendered inside of the footer, will be retrieved with the following props:\n  * icon\n    * light variant\n    * dark variant\n  * slug - where a tap should redirect to\n  * sort - indicates the order items should render inside of the footer container.\n* Render the footer item using provided data\n  * sort the order of items depending on sort dependency\n  * link associated slug to that item for URL redirecting","type":"text"}]}]}},"update":{},"historyMetadata":{}}`

**Screenshots**
![image](https://user-images.githubusercontent.com/113044451/225417838-f9cd7753-1b64-418b-a4d9-99b67bd389f1.png)

**Comment by vunguyenhung** [comment]
Hello @getlocaladmin, would you mind screenshot your whole action configuration?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
