### ISSUE TITLE
Add new interactive components feature missing[TRIGGER]

### ISSUE THREAD

**Issue by Yuyichn01** [PipedreamHQ/pipedream#5749]
https://www.youtube.com/watch?v=RZ3XQENkjeg&t=192s
Here is the youtube video tutorial I learnt to interact with block kit components on slack, however the interactive components trigger features is missing. Is this feature being removed from pipedream slack integration? Thanks for replying

**Comment by dannyroosevelt** [comment]
This is unfortunately a known issue that we are tracking here: https://github.com/PipedreamHQ/pipedream/issues/5526
