### ISSUE TITLE
[APP] Invoice Ninja

### ISSUE THREAD

**Issue by nheung** [PipedreamHQ/pipedream#575]
**Name of app / service** Invoice Ninja

**Link to developer documentation** https://invoice-ninja.readthedocs.io/en/latest/api.html

**Is lack of support preventing you from building workflows, or do you have a workaround?** No workaround at the moment

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Reading and updating invoices and payments. There's self hosted instances of the app available, so would also be great to be able to customise the URL. Thanks!

**Comment by todsac** [comment]
InvoiceNinja has been integrated.  Example - https://pipedream.com/@tod/p_mkCMPk/
