### ISSUE TITLE
[FEATURE]  Workflows errors indication on the list view

### ISSUE THREAD

**Issue by aarontbt** [PipedreamHQ/pipedream#5754]
**Is your feature request related to a problem? Please describe.**
I don't have a quick way to know when a workflow has errors like for the past 24 hours and I have to click and check every one of them to see if there are errors in any of the workflows. Emails notification didn't get sent for those repeated fails workflow.

**Describe the solution you'd like**
In the workflows list, maybe just a column to indicate how many failed attempts in the last 24 hours (or if can set the time / not)

**Do you have a workaround?**
Are you able to tackle the problem with an existing workaround, or can you not move forward without this feature?
I think I can try this https://pipedream.com/docs/workflows/errors/#process-errors-with-custom-logic-instead-of-email but still a quick way to see this in UI is enough.

**Comparable features in other tools?**
Is this feature or one like it available in another platform? If so, we'd love to hear what you like about that implementation.
Maybe it can be like those grid image (github contribution grid) to show last 50 runs, those with fail workflow, can have the box in red color. See attachment.

![image](https://user-images.githubusercontent.com/50138173/225546912-f049745b-0b9a-448b-b65e-02604742a69f.png)

**Additional context**

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt, would you mind taking a look at this suggestion to see if we can improve?

**Comment by dannyroosevelt** [comment]
Great suggestion @aarontbt! We're actively working on a feature that should solve this problem, to show an extended event history across all workflows. We're tracking [here](https://github.com/PipedreamHQ/pipedream/issues/188) and [here](https://github.com/PipedreamHQ/pipedream/issues/4845).

This is just a mock with fake data, but this shows what we're thinking:
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/225811650-adc9853c-f42c-484b-8793-a99d21495b53.png)

Let me know if you have any feedback, otherwise I'll close this issue since we're tracking in the others I liked to above.

**Comment by aarontbt** [comment]
> Great suggestion @aarontbt! We're actively working on a feature that should solve this problem, to show an extended event history across all workflows. We're tracking [here](https://github.com/PipedreamHQ/pipedream/issues/188) and [here](https://github.com/PipedreamHQ/pipedream/issues/4845).
> 
> This is just a mock with fake data, but this is directionally what we're working on: ![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/225811650-adc9853c-f42c-484b-8793-a99d21495b53.png)
> 
> Let me know if you have any feedback, otherwise I'll close this issue since we're tracking in the others I liked to above.

That looks great, as long there is a page / dashboard where I can see when a workflow failed would be a great start! I can check the details by going into the workflow itself.

**Comment by dannyroosevelt** [comment]
Great -- make sure to subscribe to those tickets I linked above, and stay tuned for announcements from us on this feature!
