### ISSUE TITLE
[ACTION] Search Categories

### ISSUE THREAD

**Issue by SGZabrav** [PipedreamHQ/pipedream#5755]
**Steps to reproduce**
Connect to a Twitch account, then use the following configuration
![image](https://user-images.githubusercontent.com/18277920/225684565-c24e801b-4248-4bed-b859-3993f9e40250.png)

**Expected Behavior**
- The action should be executed successfully

**Comment by vunguyenhung** [comment]
Hello @SGZabrav, thanks for raising this. I've found another bug for this. And I will add this to Pipedream prioritized backlog
![image](https://user-images.githubusercontent.com/18277920/225684044-f8bf1fb8-20a8-4711-802a-5cce61a606c6.png)
