### ISSUE TITLE
[SOURCE] BigCommerce

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#576]
**Describe the event source. What app, what event?**
BigCommerce

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
Custom Events | Triggers on any event from BigCommerce
New Customer | Triggers when there is a new Customer
New Order | Triggers when there is a new Order

**Comment by tangochaser** [comment]
Right now my largest use case is around orders that have specific products, more specifically, products from specific categories, as part of them. As BigCommerce does not allow order tagging, it requires a webhook notification based on order completion, GET on the order's products, then individual GETs on each product to fetch category. OR, local cache a mapping for each product ID to category to speed up the process and reduce session processing. 

Orders API - https://developer.bigcommerce.com/api-docs/store-management/orders

[Get an Order](https://developer.bigcommerce.com/api-reference/store-management/orders/orders/getanorder)
GET /orders/{order_id}

[List Products in an Order](https://developer.bigcommerce.com/api-reference/store-management/orders/order-products/getallorderproducts)
/orders/{order_id}]products

[Gets a product line item associated with the order](https://developer.bigcommerce.com/api-reference/store-management/orders/order-products/getanorderproduct)
]orders/{order_id}]products/{id}

**Comment by dannyroosevelt** [comment]
This is ready for release!
