### ISSUE TITLE
[FEATURE] Google Sheet Upsert - ability to choose behavior to update row or not

### ISSUE THREAD

**Issue by Swieter** [PipedreamHQ/pipedream#5761]
**Is your feature request related to a problem? Please describe.**
In my workflow I'm using the Google Sheet Upsert Action to add new customers to a Google Sheet.
I have a Google Sheet.  There are rows of customer information in the sheet.  The "key" column is the customer email.  There are other columns for name, address and some internal tracking fields.  The workflow doesn't know if it is a new customer or not, and since I don't want duplicates in the sheet, I only want to add a new row if the customer's email doesn't already exist.

What I have found though is that the Upsert Action works right in that if the email isn't found, it will add a row.
Next, if the row is found, the Upsert will update the existing row.

So as Upsert is working now, it is overwriting information in the existing row that i don't want overwritten.

**Describe the solution you'd like**
I'd like either a new action that only inserts a new row if none other is found.
Or a selection ability on the existing Google Sheet Upsert action where I can select if it should update existing row or not.

**Do you have a workaround?**
I'm just starting to look into a workaround.  May be to code my own python thing.

**Comparable features in other tools?**
I've got to believe this is a common paradigm, "Add new row if key value doesn't already exist".

**Additional context**
None.

**Comment by vunguyenhung** [comment]
Hello @Swieter,

> What I have found though is that the Upsert Action works right in that if the email isn't found, it will add a row.
Next, if the row is found, the Upsert will update the existing row.

> So as Upsert is working now, it is overwriting information in the existing row that i don't want overwritten.

> So as Upsert is working now, it is overwriting information in the existing row that i don't want overwritten.

I'm not sure what is the issue, in order to reproduce you issue, would you mind provide specific example?

**Comment by Swieter** [comment]
The request is that if the row is found, 
that no action is taken.  Maybe there could be a simple bool for 
"update if found".  If true, then it can update a row round.  If false, 
if a row is found, it does nothing.

Leo Vu wrote on 3/20/23 6:31 AM:

  

  Hello @Swieter,

  What I have found though is that the Upsert 
Action works right in that if the email isn't found, it will add a row.
Next, if the row is found, the Upsert will update the existing row.

  So as Upsert is working now, it is 
overwriting information in the existing row that i don't want 
overwritten.

  So as Upsert is working now, it is 
overwriting information in the existing row that i don't want 
overwritten.

  I'm not sure what is the issue, in order to reproduce 
you issue, would you mind provide specific example?


  —Reply
 to this email directly, view it on GitHub, or unsubscribe.You are receiving this 
because you were mentioned.Message ID: ***@***.***>

  [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/PipedreamHQ/pipedream/issues/5761#issuecomment-1475980053",
"url": "https://github.com/PipedreamHQ/pipedream/issues/5761#issuecomment-1475980053",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by Swieter** [comment]
The request is to have an ability to upsert, or insert, on only new entries and not to update a row if the entry already exists.
