### ISSUE TITLE
Support use of NPM private repositories

### ISSUE THREAD

**Issue by renattomachado** [PipedreamHQ/pipedream#5762]
**Is your feature request related to a problem? Please describe.**
Yes. The problema is to need use a private NPM lib in the nodejs steps and can't.

**Describe the solution you'd like**
If the NPM environment variables NPM_CONFIG_REGISTRY and NPM_AUTH_TOKEN and those variables affect the import and install management system we'll be possible to use private npm lib.

**Do you have a workaround?**
No. The workaround is turn public the private lib.

**Comparable features in other tools?**
No.

**Comment by dylburger** [comment]
Thanks for raising @renattomachado ! We're tracking this at #332, please follow there if you don't mind
