### ISSUE TITLE
[ACTION] PandaDoc: New Actions

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#5769]
**Is there a specific app this action is for?**
### PandaDoc
- Create Document from File (the user should be able to pass a path to a local file (from `/tmp`) or a URL to a publicly accessible PDF file)
- Create Folder
- List Folders

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.pandadoc.com/reference/create-document-from-pdf

https://developers.pandadoc.com/reference/document-folders

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
