### ISSUE TITLE
[TRIGGER] PandaDoc Triggers

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#5770]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
These can all be instant subscriptions (they offer webhooks setup via the API)

They have the following events available to subscribe to on their API docs
- document_deleted
- recipient_completed
- document_updated
- document_state_changed
- document_creation_failed

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.pandadoc.com/reference/create-webhooks-subscription

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
