### ISSUE TITLE
[BUG] Can not install @thirdweb-dev/contracts package on Pipedream Node.js code step

### ISSUE THREAD

**Issue by jackpmorgan** [PipedreamHQ/pipedream#5775]
When I tried to install the package [@thirdweb-dev/contracts](https://www.npmjs.com/package/%40thirdweb-dev%2Fcontracts), it failed with an error as below
![image](https://user-images.githubusercontent.com/18277920/230250251-d109a128-8fb7-40a3-a672-87e5586d4273.png)

This package is a dependency for [@thirdweb-dev/sdk](https://www.npmjs.com/package/@thirdweb-dev/sdk) package. So it prevents user from install this package also

----

# Context
Hello,

For the past 6 months, I have been using the “@thirdweb-dev/sdk” package in my Pipedream workflows that use a step.

However, it has suddenly stopped working and now throws the error message “could not compute configurable props” whenever I try to run a node script using it.

The latest version of the package has not worked for some time but I have been able to run it using version 2.4.9 of “@thirdweb-dev/sdk” (@thirdweb-dev/sdk@2.4.9).

I am wondering what has changed within Pipedream that has caused this package to stop working given that it was supported at one point and how I can resolve this issue.

Also a weird side note, I have a paid workspace (@OME) that also uses the Thirdweb package in 15+ workflows (version 2.4.9) and they are working fine.

All the workflows mentioned are HTTPS -> Node.js -> HTTPS.

**Comment by vunguyenhung** [comment]
Hello @jackpmorgan, is it possible for you to share your Node.js code step? A screenshot would be a great help!

**Comment by jackpmorgan** [comment]
Hi!

Here is the code attached. Im simply just trying to initialize the SDK. 

Would links to my other workspace that is still running this package successfully help? 

Thank you for your help!

```
import { ThirdwebSDK } from "@thirdweb-dev/sdk@2.4.9";
import  ethers  from "ethers@5.7.2";

export default defineComponent({
  
  async run({ steps, $ }) {

  const sdk = new ThirdwebSDK("https://rpc.ankr.com/polygon");
    
  return sdk

  }
})
```

**Comment by jackpmorgan** [comment]
@vunguyenhung Can you help me try to solve this bug for this package?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by jackpmorgan** [comment]
@dylburger hi, I have been waiting for a response from someone on the pipedream team to help me resolve the issue. I have provided everything that was asked. I still would love a some assistance with this issue!

**Comment by dylburger** [comment]
@jackpmorgan Apologies, a Pipedream workflow controls this logic and if we miss these comments, we'll incorrectly close the issue. I've re-opened and pinged @vunguyenhung to see if he can help triage. If there's a larger platform issue, I can help prioritize with the team.

**Comment by vunguyenhung** [comment]
Hello, I apologize for missing the message. I've checked an it seems like this is a problem on the package [@thirdweb-dev/contracts-js](https://www.npmjs.com/package/%40thirdweb-dev%2Fcontracts-js) and [@thirdweb-dev/contracts](https://www.npmjs.com/package/%40thirdweb-dev%2Fcontracts) installation step. Here's the error detail
<img width="740" alt="image" src="https://user-images.githubusercontent.com/18277920/230249926-e8bc21c8-185b-496a-a70b-bf41e3baf092.png">

I'll update the description and add this to Pipedream internal backlog

**Comment by vunguyenhung** [comment]
Thank you @jackpmorgan for the helpful information.

In your working workflow https://pipedream.com/@OME/send-token-p_brC8xDW/inspect, could you access your workflow settings and enable the option to allow Pipedream support to access it. That would be really helpful for @dylburger to check it.

Again, thank you for your information and sorry for the late response 🙏

**Comment by jackpmorgan** [comment]
@vunguyenhung No worries. I have just granted that access. Thanks again for your help!

**Comment by dylburger** [comment]
I've prioritized this with the team @jackpmorgan . We'll look into it as soon as we can, and post updates here.

**Comment by dylburger** [comment]
Thanks for the note @brettbl . This is still on the team's backlog. We're about to release some major features (Git integration, folders, etc.) so we've had to focus on that. We'll let you know as soon as we have updates here.

**Comment by dylburger** [comment]
@jackpmorgan @brettbl it looks like this works in our Node.js v18 runtime now:

```javascript
import ethers from "ethers";
import { ThirdwebSDK } from "@thirdweb-dev/sdk";

export default defineComponent({
  async run({ steps, $ }) {
    return
  }
})
```

Could you confirm if it works OK for you?

**Comment by brettbl** [comment]
@dylburger I received this error. It seems like `Thirdweb` needs `ethers` in order to work, I tried excluding it and got an error saying the library was missing.

![image](https://github.com/PipedreamHQ/pipedream/assets/129083139/15401706-e6e8-4733-b845-ecb962c7c3f0)

**Comment by dylburger** [comment]
Unfortunately the authors of the `@thirdweb-dev/sdk` package put the `ethers` requirement in the `devDependencies` section of the `package.json`: 

https://github.com/thirdweb-dev/js/blob/580e77b17088a439208bd1411c71e9fb0c2cbb79/packages/sdk/package.json#L136

We only install production dependencies, not `devDependencies`, which is standard. Could you either raise an issue with that team, or continue importing `ethers` above the `thirdweb` import?

**Comment by jackpmorgan** [comment]
@dylburger @brettbl 

Hey! Yes since you guys updated to node 18 I can install and use Thirdweb perfectly.

Brett your issue is actually regarding Ethers.

Import ethers like this:

import { ethers } from "ethers@5";

For some reason the latest release of ethers is not usable.

Let me know how that goes!

**Comment by dylburger** [comment]
Awesome thanks for the assist @jackpmorgan , I'll close this since it looks like it's working.
