### ISSUE TITLE
[Components] World News API

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5782]
### App
World News API
https://worldnewsapi.com/

Triggers:
1. New Article Published: Trigger when a new article is published in the specified category or region.
2. Top Headline Received: Trigger when a top headline is received based on defined search parameters.

Actions:
1. Retrieve Latest News: Fetch the latest news articles using specified search parameters.
2. Search Articles: Search for articles based on keywords, categories, or regions.
3. Retrieve Article By ID: Fetch detailed information about a specific article using its ID.

_This list of suggested components was generated using ChatGPT_

**Comment by sumitshinde-84** [comment]
i would like to work on this issue , can you please assign it to me ?

**Comment by dannyroosevelt** [comment]
> i would like to work on this issue , can you please assign it to me ?

@sumitshinde-84 looks like this is nearly done. Feel free to grab any other issue from the To Do column on the board!
