### ISSUE TITLE
[Components] Data Axle Platform

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5787]
### App
Data Axle Platform
https://platform.data-axle.com/

Triggers:
1. Company Updated: Detects when company information has been updated in the Data Axle Platform.
2. Contact Added: Detects when a new contact has been added in the Data Axle Platform.

Actions:
1. Search Companies: Allows searching for companies based on filters and criteria provided.
2. Retrieve Contact Information: Retrieves detailed contact information for a specific contact by ID.
3. Update Company Data: Updates existing company data, such as address or contact information, in the Data Axle Platform.

_This list of suggested components was generated using ChatGPT_

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Data_Axle_Platform_1034.pdf](https://github.com/PipedreamHQ/pipedream/files/11058202/Data_Axle_Platform_1034.pdf)
