### ISSUE TITLE
[Components] WuBook RateChecker

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5789]
### App
WuBook RateChecker
https://en.wubook.net/blog/ratechecker/

Triggers:
1. Rate Comparison Completed: Triggers when the rate comparison process for a specific property is finished.
2. Price Alert Received: Triggers when a price difference between your property and your competitors exceeds a predefined threshold.

Actions:
1. Request Rate Comparison: Initiates a rate comparison process for a specific property.
2. Set Price Alert Threshold: Updates the price difference threshold for triggering price alerts.
3. Retrieve Rate Comparison Results: Fetches the results of a completed rate comparison process.

_This list of suggested components was generated using ChatGPT_

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[f751a98b-e517-4b79-b75a-2091d315da41_WuBook_RateChecker_5789.pdf](https://github.com/PipedreamHQ/pipedream/files/11024958/f751a98b-e517-4b79-b75a-2091d315da41_WuBook_RateChecker_5789.pdf)
