### ISSUE TITLE
Looking for BigQuery Integration

### ISSUE THREAD

**Issue by givemesam** [PipedreamHQ/pipedream#5794]
Google Cloud BigQuery

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**
yes, the workaround is trying to do this with retool

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
The goal is to run jobs to select data from mysql and insert to bigquery

**Comment by vunguyenhung** [comment]
Hello @givemesam,

Pipedream currently provide some bigquery integration here: https://pipedream.com/apps/google-cloud
![image](https://user-images.githubusercontent.com/18277920/226306337-bc47a04f-e901-4f38-b184-22e3fe871a04.png)

Would you mind giving it a try?

**Comment by givemesam** [comment]
Very weird. I did not see these in the apps list when searching for
bigquery. May want to add some bigquery metadata to Google cloud?

Thx, I'll try it!

**Comment by dannyroosevelt** [comment]
> Very weird. I did not see these in the apps list when searching for bigquery. May want to add some bigquery metadata to Google cloud? Thx, I'll try it!

Great call -- thanks for point this out! Just made this change:
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/226441265-cc166715-af44-4119-847a-ed9a87ac25a5.png)

**Comment by dannyroosevelt** [comment]
> seems like there needs to be some kind of function in pipedreams bigq handler to help to convert the json output into an array that works in bigquery. the goal is to take a line from mysql, and when created/updated, send it to bigquery. ideally so they are both in sync the issue is to build an array, can be very cumbersome if i have to make the sql > json > array handler for every table i intend to use. is that in the dev pipeline to add in?

Sounds like a worthwhile suggestion. Can you show me an example of a step's output that you're trying to use as a prop input for a BigQuery action?

**Comment by dannyroosevelt** [comment]
For some reason the screenshots are not showing up for me:
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/226449767-fd00e1ca-9221-49ad-97aa-db753944fcb8.png)

**Comment by givemesam** [comment]
how about now?

-removed public github from the thread as there are parts of sensitive data
here

this is the event pipedream received from mysql

[image: image.png]

here is error where the pipedream output is not in a formatted array that
bigquery is happy with.

[image: image.png]

**Comment by givemesam** [comment]
i think i got it figured out. actually worked a lot easier than retool.  would be cool if there was a way to write our own JS or SQL to package and send to dbs so we can have any trigger content we want vs the 4-5 events provided. like sometimes there where and ? are not really useful for dbs.

**Comment by ctrlaltdylan** [comment]
Hi @givemesam 

> would be cool if there was a way to write our own JS or SQL to package and send to dbs so we can have any trigger content we want vs the 4-5 events provided

Yes, you can!

They're called _sources_ and you can control exactly what data is emitted downstream to your subscribing workflows.

The triggers you see out of the box are sources as well, they're just public in our repo:

https://github.com/PipedreamHQ/pipedream/tree/master/components/mysql/sources

Those are the source code for the MySQL triggers you see within the workflow builder.

But you can fork these sources and publish your own privately to your account.

Here's a quickstart guide to building your first source: https://pipedream.com/docs/components/quickstart/nodejs/sources/

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
