### ISSUE TITLE
[FEATURE]  TLS support on MySql Connection

### ISSUE THREAD

**Issue by Swieter** [PipedreamHQ/pipedream#5800]
**Is your feature request related to a problem? Please describe.**
I tried the MySQL component to connect to PlanetScale.  In doing so, I got an error.  "unknown error: Code: UNAVAILABLE server does not allow insecure connections, client must use SSL/TLS"

According to the Slack thread, TLS hasn't been implemented.
https://pipedream-users.slack.com/archives/CPTJYRY5A/p1679314879028759

**Describe the solution you'd like**
Make a MySQL connection that implements TLS/SSL.

**Do you have a workaround?**
No, not at this time.  May have to see what I can do in Python.

**Comment by vunguyenhung** [comment]
Hello, I confirmed that Pipedream uses MySQL Client without SSL/TLS settings [here](https://github.com/PipedreamHQ/pipedream/blob/7123de998fb9f3c24dfaa8b8991ab366a3b27045/components/mysql/mysql.app.mjs#L104-L110). I will add this to prioritized backlog

**Comment by vunguyenhung** [comment]
I can reproduce the bug when trying to connect to PlannetScale
<img width="915" alt="image" src="https://user-images.githubusercontent.com/18277920/226930558-c04e6a15-c956-45b1-a043-2047e05c7b08.png">
