### ISSUE TITLE
Is it possible use if Else In slack message Pulling Data from Webhook?

### ISSUE THREAD

**Issue by mendelsphotography** [PipedreamHQ/pipedream#5810]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

Hi, I have an HTTP webhook getting data with post. Then putting that data into a slack massage. Now some of the data inputs do not always show. For example,
I have a variable called type. But type does not always show up.  Is it possible in some way to make an else if statement somewhere or some sort of condition?
In slack docs it does not say anything and assuming its not possible since but maybe there is some other way? Or is this sort of what #216 is?
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

https://api.slack.com/reference/surfaces/formatting

**Comment by vunguyenhung** [comment]
Hello @mendelsphotography, Pipedream support if-else for ending workflow early [using Filter actions here](https://pipedream.com/docs/workflows/built-in-functions/#filter). Or you can use Node.js/Python code action that include the if-else logic to post a request to different workflows (using HTTP Webhook trigger). Would you mind giving it a try?

**Comment by mendelsphotography** [comment]
Thank you. I was able to get it to work but not exactly.
I have a variable "discount" which has 2 values.
But I want to filter for "Discount" if it contains it then continue other wise exit. But instead it does exit but the slack massage comes undefined since it doesn't contain that value.
But I want to be able to continue the workflow like let's say send a new slack massage with a massage why it didn't excute. Unless would need to do that In Node

**Comment by mendelsphotography** [comment]
The question is it possible to bypass that part of the workflow but continue on after since it then jumps with undefined wich will stop anything under it

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
