### ISSUE TITLE
[BUG] misaligned cursor issues in workflow fields

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#5812]
**Describe the bug**

![GIF 2022-09-01 at 9 57 13 AM](https://user-images.githubusercontent.com/2694734/226642741-899e1fcd-3062-4b39-90da-0c86f792c032.gif)

In prop fields, if the text grows to a certain size then the cursor behavior becomes unwieldy. The cursor will show behind or far ahead of the text being edited.

## Progress

This bug is being addressed by the Pipedream team. [Internal ticket](https://linear.app/pipedream/issue/BUI-114/cursor-gets-misaligned-for-long-multi-line-inputs-in-props)

**Comment by acreconsulting** [comment]
Thanks for posting! I have run into this too!

**Comment by asheroto** [comment]
I have run into this too:

https://github.com/PipedreamHQ/pipedream/assets/49938263/ba11a557-e22e-44f5-b478-beafaff638e6

**Comment by darrentmorgan** [comment]
I have this bug also..


https://github.com/PipedreamHQ/pipedream/assets/41783607/d36d60d9-6a7d-4b47-8cf2-53d7c40521d5

**Comment by asheroto** [comment]
Sweet! It works. Thanks all!

**Comment by asheroto** [comment]
Unfortunately this appears to be broken again.

https://github.com/PipedreamHQ/pipedream/assets/49938263/383f203b-3b2a-47f7-af09-16b31605e706
