### ISSUE TITLE
[Components] Gravity Forms

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5820]
# gravity_forms
## URLs
- https://docs.gravityforms.com/category/developers/rest-api/
#### Prompt
Emits new event when a new form submission is received.
#### URLs
 - https://docs.gravityforms.com/searching-and-getting-entries-with-the-rest-api-v2/
#### Prompt
Send a request to create entry. Add all required and optional properties.
#### URLs
 - https://docs.gravityforms.com/creating-entries-with-the-rest-api-v2/#searching-entries
#### Prompt
Send a request to submit a form. Add all required and optional properties.
#### URLs
 - https://docs.gravityforms.com/submitting-forms-with-rest-api-v2/

**Comment by malexanderlim** [comment]
You can sign up for a demo account here:
https://www.gravityforms.com/gravity-forms-demo/
