### ISSUE TITLE
[APP] ADP

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#5829]
**Name of app / service**

ADP

**Link to developer documentation**

https://developers.adp.com/articles/guides/auth-process-data-connector-apps

**Comment by dannyroosevelt** [comment]
https://pipedream.com/apps/adp/

@dylburger I wasn't able to easily create an ADP application to get my own ID and secret. Did this come from a customer? Can we ask them to help validate end to end?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
