### ISSUE TITLE
[ipbase.com]

### ISSUE THREAD

**Issue by martechdev** [PipedreamHQ/pipedream#5841]
**[https://ipbase.com](https://ipbase.com)**

**[https://ipbase.com/docs](https://ipbase.com/docs)**

** Yes, we are already paying for this API, hence this is preventing us from building workflows.**

**Comment by sergioeliot2039** [comment]
Hi @andreasaltheimer 

Welcome to Pipedream, and happy to have you as part of our users!

Thanks for the requested, I have submitted the app for testing.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @martechdev 

happy to inform you we have added ipbase to our apps for integration
https://pipedream.com/apps/ipbase
