### ISSUE TITLE
[BUG] Can not import sqlalchemy library due to dependencies conflicts

### ISSUE THREAD

**Issue by vesta-brett** [PipedreamHQ/pipedream#5843]
**Describe the bug**
I'm trying to use the sqlalchemy library to connect to my redshift data warehouse, but I receive a command failed error. See below for the full error message.

**To Reproduce**
import sqlalchemy as sa
from sqlalchemy_redshift.dialect import RedshiftDialect
from sqlalchemy.engine.url import URL

**Expected behavior**
I'm able to import this library

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome Browser: 111.0.5563.111

**Smartphone (please complete the following information):**

**Additional context**
Error
Command failed: python3 -m pip install --target=/tmp/__pdg__/dist/python -r requirements.txt --upgrade WARNING: The directory '/home/sbx_user1051/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag. ERROR: Cannot install -r requirements.txt (line 4) and SQLAlchemy==2.0.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available. You should consider upgrading via the '/var/lang/bin/python3 -m pip install --upgrade pip' command.

**Comment by vunguyenhung** [comment]
Hello @vesta-brett, I can reproduce your issue using your code
![image](https://user-images.githubusercontent.com/18277920/227974731-70a35975-f76b-47e5-9ae7-8d9af3d22b5d.png)

But pasting your code into an Python Compiler throws an error
```
ModuleNotFoundError: No module named 'sqlalchemy_redshift'
```
<img width="1875" alt="image" src="https://user-images.githubusercontent.com/18277920/227977029-1d9b8ad3-8f76-440c-81a4-d4a90ceedf76.png">

Removing sqlalchemy_redshift returns no error
![image](https://user-images.githubusercontent.com/18277920/227977345-877ca305-66bd-4f99-8f10-4ef5a710dd5b.png)

Would you mind checking if the sqlalchemy_redshift is correct? Or could you use another package to connect to Redshift?

Also it would be great if you can [submit a ticket for Pipedream to implement the action/source for your usecase](https://github.com/PipedreamHQ/pipedream/issues/new/choose)

**Comment by vesta-brett** [comment]
Hi Leo,

I don't have a problem with sqlalchemy_redshift in my local environment.

[image: image.png]

Given the function suppresses a warning, I can try and exclude it from the
code.

Regards,
Brett

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
