### ISSUE TITLE
[APP] icclim

### ISSUE THREAD

**Issue by pagecp** [PipedreamHQ/pipedream#5844]
**Name of app / service**
icclim

**Link to developer documentation**
https://icclim.readthedocs.io/en/stable/references/generic_functions_api.html#module-icclim._generated_api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
no

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Climate Indices calculations

**Comment by sergioeliot2039** [comment]
hi Christian @pagecp 

welcome to Pipedream!

Do you know if there is a Rest API available for icclim?
I scanned the documentation you linked to and noticed it's python based

**Comment by pagecp** [comment]
Hi, maybe I misunderstood, There is no REST API, it is not a service but a python package.

**Comment by sergioeliot2039** [comment]
ah, in that case, i think the "run python code" feature would be useful to your use case.
can you confirm?
https://pipedream.com/apps/python

you can import packages as needed:

![image](https://user-images.githubusercontent.com/25184117/227587076-654de042-1a12-46fd-8187-b392427ecd45.png)

**Comment by pagecp** [comment]
Yes I think. Then icclim can be shown to piper dream users?

**Comment by sergioeliot2039** [comment]
I'm not sure. I'ill ask to the PD team to see if we can get an app out without a REST API, but consuming a library like icclim.
I will get back to you on this.

**Comment by dannyroosevelt** [comment]
@pagecp we don't have a way of integrating the Python package natively onto our marketplace today. We can support apps via REST API or Node.js the way you are envisioning.

**Comment by pagecp** [comment]
Ok, thanks. I will see maybe later we can have a REST API but for not it was not in the plans.
