### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by limitlessmentality** [PipedreamHQ/pipedream#5847]
I'm trying to find a HTTP/Webhook trigger for Reddit on Pipedream

**Comment by vunguyenhung** [comment]
Hello @limitlessmentality, Pipedream offers many triggers that you can use. Could you share what trigger you need?

<img width="917" alt="image" src="https://user-images.githubusercontent.com/18277920/227989188-460baead-a754-4c59-b233-583589b987bc.png">

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
