### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by vpgswm** [PipedreamHQ/pipedream#5848]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi there @vpgswm 

Thanks for the request - what are you trying to accomplish?
I understand Bootstrap is a CSS/JS framework, not suitable for running Node.JS like you'd do on Pipdream, so I am confused.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
