### ISSUE TITLE
[BUG] Pipedream can't parse entities starting with tag <br>

### ISSUE THREAD

**Issue by fiorins** [PipedreamHQ/pipedream#5849]
**Describe the bug**
Hi, I;m trying to send a message to a telegram chat with pipedream, but seems like it can't parse elements start with the break line tag <br> since it gave me this error: 
`ETELEGRAM: 400 Bad Request: can't parse entities: Unsupported start tag "br" at byte offset 38`
Is it possible to fix ?

**Comment by vunguyenhung** [comment]
Hello @fiorins, would you mind sharing your action configuration? A screenshot would be a great help to reproduce your issue

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
