### ISSUE TITLE
[BUG] Gmail Message ID does not match

### ISSUE THREAD

**Issue by pratham1002** [PipedreamHQ/pipedream#5855]
**Describe the bug**
The message ID in the pipedream node output does not match the message ID on gmail.

**To Reproduce**
Send an email using the `send_email` action with Gmail.

Open the mail that was send in Gmail -> Show Original -> Message ID

**Expected behavior**
The output message ID should be the same as what I see on Gmail.

**Screenshots**
What I see on Pipedream:
![image](https://user-images.githubusercontent.com/54350608/227904181-cd0af0c2-4af8-4dde-92d2-7de5590c29ea.png)

What I see on Gmail
![image](https://user-images.githubusercontent.com/54350608/227904298-24400cc0-f814-4c77-9367-072a370b1130.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 111.0.5563.64 (Official Build) (64-bit)

**Additional context**
I am not sure if there the message ID seen on Gmail can be derived from the one seen on pipedream

**Comment by vunguyenhung** [comment]
Hello @pratham1002, Pipedream action uses Pipedream Gmail API and returns the response from that API as is without any modification. Maybe Gmail has different IDs on different places that reference to the same email. 

May I ask what is your usecase with the Message ID?

**Comment by pratham1002** [comment]
I want to store the message ID in some DB and use it later to send follow-up mails in the same thread (using email references).

Is there some other way to achieve this?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by telenieko** [comment]
> I want to store the message ID in some DB and use it later to send follow-up mails in the same thread (using email references).
> 
> Is there some other way to achieve this?

What Gmail calls "message id" is not the same as the Message-Id header on an email. Gmail id's are only for use on its API.

For what you want to do you have to take care of two things:

a) Generate and add a Message-Id header to the email before sending,
b) Add "In-Reply-To" header to any follow ups (there are other available headers too).

Note that some clients like gmail do not always respect "In-Reply-To" and build threads based on Subject. So, c) keep the subject stable like "Re: <original subject" o "Fwd: <original subject>"
