### ISSUE TITLE
[ACTION] Create a DocuSign Draft Envelope 

### ISSUE THREAD

**Issue by SWEjohnMartin** [PipedreamHQ/pipedream#5874]
**Is there a specific app this action is for?**
We would like to have an action to create a DRAFT envelope in DocuSign
**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopes/create/

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by ydv-ankit** [comment]
hey there, i'm new. can you help me with this issue?

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
