### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by daer1988** [PipedreamHQ/pipedream#5877]
**Name of app / service**
Monday integration with CompanyCam

**Link to developer documentation**
https://monday.com/appdeveloper

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
@daer1988 can you clarify what app you're looking for? We have a Monday.com integration with triggers and actions here:
https://pipedream.com/apps/monday

**Comment by daer1988** [comment]
CompanyCam with Monday

**Comment by sergioeliot2039** [comment]
hi @daer1988 thanks for using Pipedream.com,

I do see that Monday.com and CompanyCam are both integrated:
Monday.com app at Pipedream --> https://pipedream.com/apps/monday
CompanyCam at Piedream --> https://pipedream.com/apps/companycam

For Monday.com we even have some components already built, such as "create board" action, o trigger on "new board":
![image](https://user-images.githubusercontent.com/25184117/228378217-178ca138-7d7c-4c39-a69b-d1a22afc5b7a.png)

so the question is, how do you want to connect them? 
 i.e do you want to create a new item on Monday.com when you upload an image on CompanyCam?

I would appreciate if you elaborate on your use case.

**Comment by daer1988** [comment]
What I want to do is that when I create an item in Monday.com it is created
in CompanyCam taking some data from the columns in the specified board

**Comment by daer1988** [comment]
and that when CompanyCam adds photos to that work that was created since
monday, it notifies me on monday that there is a new update in my work

**Comment by sergioeliot2039** [comment]
Got it. Thanks for the information.

I am updating the ticket to reflect that. Please review and request changes if needed.

**Comment by sergioeliot2039** [comment]
@dannyroosevelt maybe we should prioritize #3595 after this request

**Comment by dannyroosevelt** [comment]
Good call Sergio, I just moved that issue to **Prioritized**.

**Comment by daer1988** [comment]
Awesome, thanks!
