### ISSUE TITLE
[APP] Google Address Validation

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#5888]
Google Address Validation. 

There seems to be multiple options here:
https://developers.google.com/maps/documentation/address-validation/overview (free)
https://developers.google.com/maps/documentation/places/web-service/autocomplete ($200 of credit per month so free for most cases)

Main workarounds are just parsing the address data by line breaks or commas and hoping for the best.

My personal use case is for formatting/validating/parsing shipping address data so I think address-validation is probably more specific to my case. Shopify seem to require shipping address data in the format

order.shipping_address = {
  "first_name": "Jane",
  "last_name": "Smith",
  "address1": "123 Fake Street",
  "phone": "777-777-7777",
  "city": "Fakecity",
  "province": "Ontario",
  "country": "Canada",
  "zip": "K2P 1L4"
};

**Comment by zecul** [comment]
@dylburger I made something and saved it to my actions (its not perfect by a long shot - I'm still trying to make it run a USPS check - but it helps with the formatting). How do I share it here?

**Comment by zecul** [comment]
@dylburger 

import { axios } from "@pipedream/platform";

export default defineComponent({
  name: "google-address-lookup",
  key: "google-address-lookup",
  version: "0.0.1",
  type: "action",
  props: {
    apiKey: {
      type: "string",
      label: "Google API Key",
      secret: true,
    },
    address: {
      type: "string",
      label: "Address to verify",
      async options({ prevContext }) {
        if (!prevContext) {
          return [];
        }

        const response = await axios(this, {
          method: "GET",
          url: "https://maps.googleapis.com/maps/api/place/autocomplete/json",
          params: {
            input: prevContext,
            key: this.apiKey,
          },
        });

        return response.predictions.map((prediction) => ({
          label: prediction.description,
          value: prediction.description,
        }));
      },
    },
  },
  async run() {
  const response = await axios(this, {
    method: "GET",
    url: "https://maps.googleapis.com/maps/api/geocode/json",
    params: {
      address: this.address,
      key: this.apiKey,
    },
  });

  if (response.status === "OK") {
    const verifiedAddress = response.results[0];
    return {
      formatted_address: verifiedAddress.formatted_address,
      location: verifiedAddress.geometry.location,
      place_id: verifiedAddress.place_id,
      types: verifiedAddress.types,
      address_components: verifiedAddress.address_components.map((component) => ({
        long_name: component.long_name,
        short_name: component.short_name,
        types: component.types,
      })),
    };
  } else {
    throw new Error(`Address verification failed: ${response.status}`);
  }
},
});

**Comment by zecul** [comment]
I'm having trouble adding the CASS part where it checks the result against the USPS database:
https://developers.google.com/maps/documentation/address-validation/requests-validate-address

I also used the chatGPT and I think it has issues with the 2021 cutoff believing that google address validation doesn't exist and it's trying to use the geolocation API instead which finds "places" rather than "mailing addresses".

**Comment by zecul** [comment]
OK, new attempt. I pasted the entire google help page into https://codepen.io/cfjedimaster/full/MWqxwXL and with some extra chatgpt editing I have:

import { axios } from "@pipedream/platform";

export default defineComponent({
  props: {
    apiKey: {
      type: "string",
      label: "API Key",
      secret: true,
    },
    addressText: {
      type: "string",
      label: "Address Text",
    },
    enableUspsCass: {
      type: "boolean",
      label: "Enable USPS CASS",
      optional: true,
    },
  },
  async run({ $ }) {
    const address = this.addressText.split("\n").map(line => line.trim());

    const requestBody = {
      address: {
        addressLines: address,
      },
      enableUspsCass: this.enableUspsCass,
    };

    const response = await axios($, {
      method: "POST",
      url: `https://addressvalidation.googleapis.com/v1:validateAddress?key=${this.apiKey}`,
      headers: {
        "Content-Type": "application/json",
      },
      data: requestBody,
    });

    return response;
  },
});

**Comment by dannyroosevelt** [comment]
@sergioeliot2039 can you take a look at getting the app integrated? Looks like it just needs an API key, not OAuth, right? Then we can have a component dev add the action based on the above prototype.

**Comment by zecul** [comment]
@sergioeliot2039 

I have this so far. It calls the validation API first and then falls back to geolocation API if its not a recognised country (Peru, Japan are 2 examples I found)

```
import { axios } from "@pipedream/platform";

export default defineComponent({
  name: "Google Address API",
  key: "google-address-api",
  version: "0.0.2",
  type: "action",
  props: {
    apiKey: {
      type: "string",
      label: "API Key",
      secret: true,
    },
    addressText: {
      type: "string",
      label: "Address Text",
    },
    enableUspsCass: {
      type: "boolean",
      label: "Enable USPS CASS",
      optional: true,
    },
  },
  async run({ $ }) {
    const address = this.addressText.split("\n").map(line => line.trim());

    const requestBody = {
      address: {
        addressLines: address,
      },
      enableUspsCass: this.enableUspsCass,
    };

    try {
      const response = await axios($, {
        method: "POST",
        url: `https://addressvalidation.googleapis.com/v1:validateAddress?key=${this.apiKey}`,
        headers: {
          "Content-Type": "application/json",
        },
        data: requestBody,
      });

      return response;
    } catch (error) {
      console.error("Address Validation API failed:", error);

      // Fallback to Geocoding API
      const geocodingResponse = await axios($, {
        method: "GET",
        url: "https://maps.googleapis.com/maps/api/geocode/json",
        params: {
          address: this.addressText,
          key: this.apiKey,
        },
      });

      return geocodingResponse;
    }
  },
});
```

**Comment by malexanderlim** [comment]
@zecul I've onboarded Google Address Validation using an API Key implementation, as this was the most straightforward method. Let me know if you're able to use this, or if you have any feedback, and we can will add an action to Validate Address shortly.
