### ISSUE TITLE
[Linkedin]

### ISSUE THREAD

**Issue by meerubadub** [PipedreamHQ/pipedream#5898]
**Linkedin**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
Hi @meerubadub 

Thanks for your request, and nice to have you among our users. Welcome to Pipedream.com!

So, we have LinkedIn integrated at --> https://pipedream.com/apps/linkedin

Can you elaborate on what you are trying to do?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
