### ISSUE TITLE
[ACTION] Send Whatsapp Text Using Template with support for dynamic URL in buttons

### ISSUE THREAD

**Issue by rapidmarket** [PipedreamHQ/pipedream#5899]
**Is there a specific app this action is for?**

Send Whatsapp Text Using Template with support for dynamic URL in buttons

**Please provide a link to the relevant API docs for the specific service / operation.**

https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates

I currently have this error message when I am try to use the current "Send Text Using Template" action with a template that requires a dynamic url

`Error - Request failed with status code 400
{"error":{"message":"(#131008) Required parameter is missing","type":"OAuthException","code":131008,"error_data":{"messaging_product":"whatsapp","details":"buttons: Button at index 0 of type Url requires a parameter"},"fbtrace_id":"AEPaERTvMqsfcyJDi_VKjTO"}}`

**Comment by vachan** [comment]
[send-text-using-template.mjs](https://github.com/PipedreamHQ/pipedream/blob/master/components/whatsapp_business/actions/send-text-using-template/send-text-using-template.mjs)

It is only using:
`type: "header",` [line:80](https://github.com/PipedreamHQ/pipedream/blob/master/components/whatsapp_business/actions/send-text-using-template/send-text-using-template.mjs#L80)
`type: "body",` [line:93](https://github.com/PipedreamHQ/pipedream/blob/master/components/whatsapp_business/actions/send-text-using-template/send-text-using-template.mjs#L93)

It is **missing** the `type: "button",` from [Components](https://developers.facebook.com/docs/whatsapp/on-premises/reference/messages#buttons)

===

This is the **_What needs to be done!_**
Need help in **_How to do it?_**

**Comment by vunguyenhung** [comment]
Hello @andrewjschuang, as you're familiar with Whatsapp Business, do you have any insights regarding this?

**Comment by vunguyenhung** [comment]
Hello @rapidmarket, we are unable to test the code for this as we couldn't submit a custom template for testing. After this is merged, could you test it on your side?

**Comment by michelle0927** [comment]
@rapidmarket I reopened this issue and linked another PR (https://github.com/PipedreamHQ/pipedream/pull/6087) that I think will help. Once again, we'd like your help testing once it's published.
