### ISSUE TITLE
WeSupply

### ISSUE THREAD

**Issue by azharumar** [PipedreamHQ/pipedream#5908]
**Name of app / service**
WeSupply
**Link to developer documentation**
https://documenter.getpostman.com/view/11859344/T17AiAYq

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It already has Integromat and Zapier integrations. I need to look for workarounds like HTTP requests or Webhooks.
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
