### ISSUE TITLE
[ACTION] Discord Branching on specific conditions

### ISSUE THREAD

**Issue by RiverTeacher** [PipedreamHQ/pipedream#5912]
**Is there a specific app this action is for?**
DISCORD
**Please provide a link to the relevant API docs for the specific service / operation.**
https://discord.com/developers/applications

Is it possible to change the action or not trigger if certain words or users are included?

**Comment by vunguyenhung** [comment]
Hello @RiverTeacher, I believe you can use [Pipedream filter action](https://pipedream.com/apps/filter) to stop the workflow if a certain condition is met, in your case it is certain words or users are included. Would you mind giving it a try?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
