### ISSUE TITLE
[BUG] Slack with many channels hangs

### ISSUE THREAD

**Issue by myrtleTree33** [PipedreamHQ/pipedream#5913]
**Describe the bug**

When attempting to send a public message to a Slack channel (Slack account has many channels), and clicking the dropdown box for selecting the channel, the spinner hangs and doesn't provide clear feedback what went wrong / what should be done

Image:

**To Reproduce**
1. Create a new integration
2. Send a public message to a slack channel (Slack account must have many channels)
3. Spinner hangs, verified.

**Expected behavior**

**Screenshots**

<img width="1182" alt="Screenshot 2023-04-03 at 4 09 46 PM" src="https://user-images.githubusercontent.com/1506937/229451606-8aebe9c4-cbc6-4ca4-ac07-19816ccbf70c.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. **chrome**, safari]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vunguyenhung** [comment]
Hello @myrtleTree33, in order for me to reproduce you issue, may I ask are you a Slack workspace admin/owner? What permission do you have on your Slack workspace?

I’ve tested my account with Workspace owner permission and normal user and it seems okay
![image](https://user-images.githubusercontent.com/18277920/229579901-f317e872-0b9c-46cd-8927-cbdade91b971.png)
![Uploading image (10).png…]()


Would you mind reconnecting your Slack account, allow Pipedream to connect with your Slack workspace (may need workspace admin permission) and try to select the channel again?
