### ISSUE TITLE
[BUG] Broken link in docs/components/api

### ISSUE THREAD

**Issue by Yash-271120** [PipedreamHQ/pipedream#5923]
**Describe the bug**
There is a broken link in [link](https://pipedream.com/docs/components/api/#prop-definitions-example)

**To Reproduce**
1. Go to [link](https://pipedream.com/docs/components/api/#prop-definitions-example)
2. Click on example
3. See 404 error

**Expected behavior**
open GitHub page to [link](https://github.com/PipedreamHQ/pipedream/blob/master/components/github/sources/new-commit/new-commit.mjs)

**Screenshots**
![Screenshot (51)](https://user-images.githubusercontent.com/65940625/229713432-26217229-bc53-48fc-9640-30fa3133a450.png)

**Comment by vunguyenhung** [comment]
Hello @Yash-271120, I will close this issue as the PR is merged
