### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by ankurkumarnodejs** [PipedreamHQ/pipedream#5925]
**Name of app / service - Hive**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround? - yes**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each! - no**

**Comment by sergioeliot2039** [comment]
Hi @ankurkumarnodejs 

Thank you for your request!!
And happy to have you among our base of [Pipedream.com](https://pipedream.com/)

We are very keen in moving forward with your request, but we need more information.

Can you please tell us more about you are trying to do, or just provide the bellow ?

> Name of app / service - Hive
> 
> Link to developer documentation
> 
> Is lack of support preventing you from building workflows, or do you have a workaround? - yes
> 
> Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each! - no

Many thanks,

**Comment by sergioeliot2039** [comment]
Do you mean Hive, as in : https://hive.com/ ??

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
