### ISSUE TITLE
[TRIGGER] ProWorkFlow:  Company Created

### ISSUE THREAD

**Issue by b825dev** [PipedreamHQ/pipedream#5935]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Add a trigger from the ProWorkFlow source when a new company is created

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://api.proworkflow.net/?calls#companies

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by Yash-271120** [comment]
Hi @dylburger I just started reading about pipedream, this seems to be a easy issue. I can try to get my hands dirty here.

**Comment by dannyroosevelt** [comment]
> Hi @dylburger I just started reading about pipedream, this seems to be a easy issue. I can try to get my hands dirty here.

@Yash-271120 that sounds great! Let us know if you have questions.

**Comment by Yash-271120** [comment]
Hi @b825dev , how can I find api key in proworkflow?

**Comment by dannyroosevelt** [comment]
> Hi @b825dev , how can I find api key in proworkflow account?

@Yash-271120 check out the Authentication section in their docs: https://api.proworkflow.net/?documentation#introductionurl

**Comment by michelle0927** [comment]
Resolved by https://github.com/PipedreamHQ/pipedream/pull/5963
