### ISSUE TITLE
[OAUTH SCOPE] CompanyCam - new scope for deleting webhook

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5940]
**Which application needs a scope added?**
CompanyCam

**What scope(s) need to be added?**
@jcortes please help to provide this. The scope needed to delete the webhook used by Pipedream source. As Pipedream CompanyCam is missing the scope to delete the webhook trigger
![image](https://user-images.githubusercontent.com/18277920/230111009-e0a9c0d7-94dc-4d28-adef-2b8d07c9d6b0.png)

**Please provide a link to the relevant API docs for scopes.**
@jcortes please help to provide this

**Comment by dannyroosevelt** [comment]
Looks like they only have read, write, destroy as scopes, so the integration now requests all 3. Can one of you reconnect your account then try again?

**Comment by vunguyenhung** [comment]
Thanks @dannyroosevelt, I can inactivate the source now
![image](https://user-images.githubusercontent.com/18277920/230148095-95a0d5ea-4fd0-4c8a-b16e-9ffa4502d7f8.png)

Hence, I will close this issue 👍
