### ISSUE TITLE
[APP] Recreation.gov

### ISSUE THREAD

**Issue by slide064** [PipedreamHQ/pipedream#5941]
**Name of app / service**
Recreation.gov
**Link to developer documentation**
https://ridb.recreation.gov/docs
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Just from building workflows
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
It'd be cool to get an alert when a campsite opens up.

Thanks!

**Comment by ctrlaltdylan** [comment]
We have published a beta integration for Recreation.gov here: https://pipedream.com/apps/recreation_gov

You can now publish components for it within this repo, and they'll be available for us within the platform.

Happy camping! 🏕️
