### ISSUE TITLE
[Components] GeoDB Cities

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5947]
### App
GeoDB Cities
http://geodb-cities-api.wirefreethought.com/

Triggers:
1. City Added: Trigger when a new city is added to the GeoDB.
2. City Updated: Trigger when an existing city's information is updated in the GeoDB.

Actions:
1. Find Cities: Search for cities based on various filters such as name, country, population, etc.
2. Get City Details: Retrieve detailed information about a specific city using its ID or name.
3. Get Cities Near Location: Find cities within a specified distance from a given location (latitude and longitude).

_This list of suggested components was generated using ChatGPT_

**Comment by ydv-ankit** [comment]
hey,
i want to work on this issue.
I'm beginner, can u help me?

**Comment by dannyroosevelt** [comment]
Actually this appears to be a duplicate of https://github.com/PipedreamHQ/pipedream/issues/5783, so I'm going to close it.

But feel free to grab any other ticket from the To Do column!
