### ISSUE TITLE
[APP] Memberstack Admin API

### ISSUE THREAD

**Issue by drakeballew** [PipedreamHQ/pipedream#5949]
**Name of app / service**
Memberstack / Admin API

[**Link to developer documentation**](https://docs.memberstack.com/hc/en-us/sections/7233631891995)
[Documentation for the Admin API specifically](https://memberstack.notion.site/Admin-API-5b9233507d734091bd6ed604fb893bb8)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I believe I have a workaround but would really love to have some of the triggers listed below available

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Triggers:
- Member created
- Member updated
- Member deleted
- Plan created
- Plan updated
- Plan deleted

Actions:
- List members
- List plans
- Retrieve member
- Retrieve plan
- Create member
- Create plan
- Update member
- Update plan
- Delete member
- Delete plan

**Comment by sergioeliot2039** [comment]
Hi @drakeballew 

Thanks for the request.

I checked the Memberstack website, API docs and compared to our implementation https://pipedream.com/apps/memberstack

It turns out there is only one server-side, back end API, 

From there FAQ:

> Does Memberstack have an API?
> Yes — there are multiple ways to interact with Memberstack data. Here are some handy guides on how to do so: [Front-end API](https://www.memberstack.com/docs/dom), [Back-end API](https://www.memberstack.com/docs/admin), [Webhooks](https://docs.memberstack.com/hc/en-us/articles/7329156946587-Webhooks), [Zapier Integration](https://docs.memberstack.com/hc/en-us/articles/7252886662299-Zapier-Integration), and [Make.com Integration](https://docs.memberstack.com/hc/en-us/articles/7252991415323-Make-com-Integration).

They just updated their endpoints, so our current implementation does not work. I am filing a BUG for this.

Regarding the requested components, we are tracking several at #3688, which has been prioritized after your request, and I am updating with any missing components from your request.. Would you mind following there.

**Comment by sergioeliot2039** [comment]
For tracking Memberstack app, please follow #5951 if you'd like. Thanks

**Comment by dannyroosevelt** [comment]
Hi Drake! We updated the [Memberstack app](https://pipedream.com/apps/memberstack) and it now works with the admin API, and we'll get those triggers and actions built out.

**Comment by drakeballew** [comment]
Thank you!! 

Y'all need to create a Pipedream Dev twitter account and lay a pipe that tweets every time you guys resolve an issue in Github, release a feature, etc. Just sayin'...

**Comment by drakeballew** [comment]
You should also have some funny marketing mascot that bears a striking resemblance to Mario

**Comment by dannyroosevelt** [comment]
We're actually prototyping a Mario SlackBot that uses ChatGPT to help answer questions! 🙏

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[Memberstack_3688_1006.pdf](https://github.com/PipedreamHQ/pipedream/files/11206757/Memberstack_3688_1006.pdf)
