### ISSUE TITLE
[TRIGGER] Twitter Likes and Bookmarks for Threads and Tweets

### ISSUE THREAD

**Issue by bastimori** [PipedreamHQ/pipedream#5950]
Get a Twitter thread every time I book mark it.
Get a single Tweet every time I like it

**Comment by vunguyenhung** [comment]
Hello @bastimori, in order for us to implement it would you mind sharing the relevant API doc her the trigger you requested?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
