### ISSUE TITLE
[BUG] Twitter broken (but it's Musk's doing) cannot use API keys to access

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#5953]
**Describe the bug**
I have a few workflows that used the Twitter>Create Tweet function, been running for ages, no issues. Due to changes in Doge-Twitter this week all post access is broken. I've tried following your advice and got my own devs keys but cannot reconnect the account, the Twitter page loads and shows that it can't give access to the app.

Workflow gives you:  
```
Error

Unexpected error (status code: 401): { "errors": [ { "code": 32, "message": "Could not authenticate you." } ] } 
```

**To Reproduce**
1. Go to any workflow that uses Twitter>Create Tweet
2. Select your account and use the `Reconnect` button
3. Try using API and API Secret or Access and Access Secret from Twitter API Project
4. Fail

**Expected behavior**
Reconnect and post tweets

**Screenshots**
Workflow Error:
![image](https://user-images.githubusercontent.com/8470449/230420205-775a6678-018d-4148-98fd-c7a716e61681.png)

Tokens:
![image](https://user-images.githubusercontent.com/8470449/230420084-c0525890-ccbf-44d2-8173-b014f1c8ba51.png)

Error on Twitter:
![image](https://user-images.githubusercontent.com/8470449/230420349-3e189aed-53cf-48ce-aff7-0787b145a4b1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 and Android
 - Browser Chrome (Windows), Chrome (Android), Firefox (Windows)
 - Version Latest for all

**Additional context**
I know it's Musk's doing but if there is something I'm missing then any input would be great, if not then I'll have to look at creating a headless browser in Python to post Tweets or something

**Comment by bnak** [comment]
Just commenting that I'm seeing the exact same error in the manner @NebularNerd described

**Comment by 5vl** [comment]
Use the `Client ID` and `Client Secret` instead, you should be able to set up `User authentication` on your twitter dev panel

**Comment by NebularNerd** [comment]
> Use the `Client ID` and `Client Secret` instead, you should be able to set up `User authentication` on your twitter dev panel

That got me a step further, now I get 
```
Pipedream failed to connect to your account.

Please reach out to integration-errors@pipedream.com and provide this error ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx

```

So making progress of sorts...

**Comment by dannyroosevelt** [comment]
Confirming we are aware of the issue and are working on getting Twitter back up and running. Twitter deactivated Pipedream's OAuth client sooner than expected, but we are working on enabling support for Pipedream customers to configure their own developer credentials to use within Pipedream.

We will share out updates as we make progress.

Thank you for your patience!

**Comment by 5vl** [comment]
Yeah I also had issues with that - in the end I just created the entire authentication stuff myself, which came out a little scuffed but it works. 

Before that error happened tho, I could authenticate my account but it wouldn't give the correct scopes while I did add it. For example tweet.write, it'd still only be the 3 default ones.

**Comment by NebularNerd** [comment]
> Yeah I also had issues with that - in the end I just created the entire authentication stuff myself, which came out a little scuffed but it works.

I might do this if needed, I have a couple of workflows with some manual Python Shopify API bits in to do some weird and wonderful stuff, but they are a bit heavy on the runtime. Handily the Twitter output is the final stage of my workflows that are affected, which while annoying is not world ending. I'm going to wait and see if @dannyroosevelt and co. can resurrect the oAuth, if not I'll throw together a Python script to do the job.

**Comment by NebularNerd** [comment]
To make life tidier and easier for the admins I shall close this issue, @dannyroosevelt has created issue #5975 regarding this issue, it's better to try and keep everything in one thread. 😎

**Comment by dannyroosevelt** [comment]
FYI we released an updated integration, which re-enables support for Twitter's API, but requires users create and provide credentials for their own OAuth developer app. More info on how to do this here:
https://pipedream.com/apps/twitter#getting-started
