### ISSUE TITLE
[ACTION] BingX spot API request

### ISSUE THREAD

**Issue by gilusgit** [PipedreamHQ/pipedream#5956]
Please someone create BingX event for Spot. There are only for Perpetual aviable.

**Comment by vunguyenhung** [comment]
Hello @gilusgit, I'm not sure I understand the action you're mentioning. Could you share more detail on what you'd like to achieve?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by gilusgit** [comment]
I mean that there is many ways to connect BingX with Pipedream with those events ( https://pipedream.com/apps/bingx/integrations/pipedream) but all of them are for BingX Perpetual. But I would like to use with spot and there is no event for spot. If soemeone could create connection (events) for bingX spot it would be great.

**Comment by gilusgit** [comment]
![IMG_20230415_185205](https://user-images.githubusercontent.com/130091428/232239144-5e4577d7-fbcb-4f3d-89e0-3a6193d8e048.jpg)
All this actions are made for BingX Perpetual. It would be great if someone will create Actions for Spot also.
