### ISSUE TITLE
[Components] World News API

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5957]
### App
World News API
https://worldnewsapi.com/

Triggers:
1. New Article Published: Triggered when a recent world news article is published.
2. Keyword Mention Detected: Activated when a specified keyword is mentioned in a world news article.

Actions:
1. Search Articles: Search for news articles by keyword, language, or source.
2. Get Latest Articles: Retrieve the latest world news articles based on specified filters.
3. Extract Article Details: Obtain specific details about a world news article, such as title, description, and source.

_This list of suggested components was generated using ChatGPT_

**Comment by michelle0927** [comment]
@dannyroosevelt Is this a duplicate of https://github.com/PipedreamHQ/pipedream/issues/5782?

**Comment by dannyroosevelt** [comment]
Yep, oops. Will close.
