### ISSUE TITLE
[APP] Affinity

### ISSUE THREAD

**Issue by peter-me** [PipedreamHQ/pipedream#5958]
**Name of app / service**
Affinity CRM

**Link to developer documentation**
https://api-docs.affinity.co/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Outside of writing my own integration I don't have a workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Anything related to Lists, Fields, Organizations and Files have priority for me, as well as creating Notes. I don't use Persons, Relationships, or Opportunities much.

**Comment by sergioeliot2039** [comment]
Hi @peter-me 

Thanks fo the request!

Affinity CRM appears to be integrated already, see: https://pipedream.com/apps/affinity

That said, we are tracking Affinity components at #3542 , please have a look and see if there is anything missing that you'd need.

So I am closing the issue.

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
14 days follow up
