### ISSUE TITLE
[Components] ezeep Blue

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5960]
# ezeep_blue
## URLs
- https://apidocs.ezeep.com/ezeepblue/api/printapi/README.html
#### Prompt
Trigger when a print jobstatus is 0. Please add the jobId prop.
#### URLs
- https://apidocs.ezeep.com/ezeepblue/api/printapi/README.html#get-status
#### Prompt
Trigger when a print jobstatus is 3011 or 2. Please add the jobId prop.
#### URLs
- https://apidocs.ezeep.com/ezeepblue/api/printapi/README.html#get-status
#### Prompt
Send a new print job to a specified printer. Please use the endpoint to prepare file upload then upload file using form-data library and finaly print the uploaded file. Add a prop to customer choose between print uploaded file or urlFile. Please add all required and optinal props.
#### URLs
- https://apidocs.ezeep.com/ezeepblue/api/printapi/README.html#prepare-file-upload
- https://apidocs.ezeep.com/ezeepblue/api/printapi/README.html#file-upload
- https://apidocs.ezeep.com/ezeepblue/api/printapi/README.html#print-an-uploaded-file
- https://apidocs.ezeep.com/ezeepblue/api/printapi/README.html#print-a-file-referenced-by-url
#### Prompt
Retrieve a list of all available printers in the network. No props are necessary.
#### URLs
- https://apidocs.ezeep.com/ezeepblue/api/rest_api/printers/README.html#list-printers
#### Prompt
Check the status of a specific print job. Please add the jobId prop.
#### URLs
- https://apidocs.ezeep.com/ezeepblue/api/printapi/README.html#get-status

**Comment by michelle0927** [comment]
Moving this back to "To Do" because it requires a Windows OS to add printers to an account, but I'm using Mac OS.
