### ISSUE TITLE
[Components] Instagram for Business

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5962]
### App
Instagram for Business
https://www.instagram.com/

Triggers:
1. New Post Published: Trigger when a new post is published on the connected Instagram Business account.
2. New Comment Received: Trigger when a new comment is received on a post from the connected Instagram Business account.

Actions:
1. Publish Post: Create and publish a new post on the connected Instagram Business account.
2. Delete Post: Remove an existing post from the connected Instagram Business account.
3. Reply to Comment: Respond to a specific comment on a post from the connected Instagram Business account.

_This list of suggested components was generated using ChatGPT_

**Comment by dannyroosevelt** [comment]
Not ready for dev yet -- the app needs to be approved w/ our scopes first.

**Comment by malexanderlim** [comment]
Ready for dev, tracking here:
https://github.com/PipedreamHQ/pipedream/issues/6806
