### ISSUE TITLE
stata[APP]

### ISSUE THREAD

**Issue by 69420thguy** [PipedreamHQ/pipedream#5966]
**Name of app / service**
stata
**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**
yes it is and i dont have a workaround
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
hi @69420thguy 

Sorry that Pipedream's current lack for Statta is preventing you from building workflows.
And I appreciate your request.

Can you share Stata REST API docs please?
This is needed in order for us to go forward with the integration. As of now I only can see Python related libraries when it comes to Stata. That'd be real helpful if you point us to their Rest API documentation.

Thank you

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
