### ISSUE TITLE
[TRIGGERS][APP] Hostaway

### ISSUE THREAD

**Issue by marlian** [PipedreamHQ/pipedream#5972]
Hostaway

(https://api.hostaway.com/documentation#introduction)

Triggers: New reservation, Updated reservation, New conversation

Actions: none

**Comment by sergioeliot2039** [comment]
So, Hostwast uses the OAuth 2.0 client credentials grant, which works like Basic+Bearer Auth.
Plus they don't have free trials, you have to get a demo, get qualified as a customer to get a pricing or a paid trial if you are a property manager with over 200 properties.

**Comment by malexanderlim** [comment]
Hi @marlian , we're in the process of applying for a partnership with Hostaway and they are requesting the name of the mutual customer who is interested in the integration. If you are open to this, please email us at integrations@pipedream.com with the details and we will continue the process and get this integration built out!

**Comment by sergio-eliot-rodriguez** [comment]
Note on outreach
by email, copied sergio@pk integrations@pd

**Comment by malexanderlim** [comment]
Hi @marlian , this work is complete!
https://pipedream.com/apps/hostaway#popular-hostaway-triggers
