### ISSUE TITLE
[ACTION] Youtube - List Playlist videos

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5982]
**Is there a specific app this action is for?**
Youtube - Data API

**Please provide a link to the relevant API docs for the specific service / operation.**
List Playlist Video

**Comment by RPDMN** [comment]
Was not able to find a specific app for this but here you can refer to the official documentation of the youtube : https://developers.google.com/youtube/v3/docs/playlists
Hope it helps !!
