### ISSUE TITLE
[mastadon]

### ISSUE THREAD

**Issue by tessoudali** [PipedreamHQ/pipedream#5983]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by NebularNerd** [comment]
Did you mean Mastodon? That's supported [https://pipedream.com/apps/mastodon](https://pipedream.com/apps/mastodon)

**Comment by tessoudali** [comment]
Thanks so much

**Comment by tessoudali** [comment]
i hope you intergrate more fediverse platforms to pipedream because they are future thanks

**Comment by sergioeliot2039** [comment]
thank you for your feedback, i am adding my self apps to Pipedream so certainly I'll

**Comment by tessoudali** [comment]
Thanks 👍
