### ISSUE TITLE
[BUG] : OpenAI "generated_text

### ISSUE THREAD

**Issue by ShashankSuresh** [PipedreamHQ/pipedream#5984]
**Describe the bug**

**To Reproduce**
1. Go to 'Create a flow'
2. Click on 'Add Step'
3. From the drop down select 'OpenAI'
4. Add a prompt - 'give me a witty and cool software developer quote'
5. Click test 
6. The "text_generated" is not complete 

**Expected behavior**
The generated text from the prompt should be the complete sentence provided by the OpenAI prompt call. 

**Screenshots**
<img width="1906" alt="Screenshot 2023-04-11 at 9 46 12 AM" src="https://user-images.githubusercontent.com/13508322/231106703-360785da-5b45-4c06-90fc-29ffd1091b05.png">

**Desktop (please complete the following information):**
 - macOS Monterey v12.6
 - Chrome Version 112.0.5615.49 (Official Build) (arm64)

**Comment by vunguyenhung** [comment]
Hello @ShashankSuresh,
I couldn't seem to get the result that you are mentioning.

GPT3.5-Turbo
![image](https://user-images.githubusercontent.com/18277920/231140518-c4529089-961f-4c48-9af5-ad7bb06d3466.png)


GPT-4
![image](https://user-images.githubusercontent.com/18277920/231140031-4c9f3edd-b4f7-436b-b8bf-756600e5d8c7.png)


Would you mind adjusting the `Max Token` prop to see if you can generate more token?
![image](https://user-images.githubusercontent.com/18277920/231140938-a2a29f85-f1fb-4b57-a5db-cf3328aea679.png)

**Comment by ShashankSuresh** [comment]
@vunguyenhung Hello. Nice to e-meet you :) 

I can still reproduce the issue. 

<img width="1889" alt="image" src="https://user-images.githubusercontent.com/13508322/231148642-56e36f11-1a3a-49de-9786-9c13362a0159.png">

**Comment by ShashankSuresh** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/13508322/231149458-31144587-eef4-4ba9-8835-5bc541606ce1.png">

**Comment by ShashankSuresh** [comment]
@vunguyenhung : What value should I set the max_token prop? Also how do I share the action config?

**Comment by ShashankSuresh** [comment]
I added max_token value to 20 and it still didnt work. 

<img width="969" alt="Screenshot 2023-04-11 at 4 20 33 PM" src="https://user-images.githubusercontent.com/13508322/231210810-1936e7ef-03da-4dd3-89b5-d5565664962c.png">
<img width="1014" alt="Screenshot 2023-04-11 at 4 20 43 PM" src="https://user-images.githubusercontent.com/13508322/231210825-cf220d93-6740-4398-98da-0a9e82cf669b.png">
<img width="963" alt="Screenshot 2023-04-11 at 4 20 49 PM" src="https://user-images.githubusercontent.com/13508322/231210831-ed84c6d0-c294-4cb0-9f11-1b5440197aff.png">
<img width="981" alt="Screenshot 2023-04-11 at 4 20 58 PM" src="https://user-images.githubusercontent.com/13508322/231210839-fbe1255d-9fdd-429d-9951-9842f7b4ea4f.png">

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
