### ISSUE TITLE
[FEATURE] Add MS ToDo permissions for the MS Graph API

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#599]
**Is your feature request related to a problem? Please describe.**
The MS Graph API connector asks for a lot of permissions, but does not support the newly release ToDo entities (https://docs.microsoft.com/en-us/graph/api/resources/todo-overview?view=graph-rest-1.0). Please add these permissions so I can use them. :)

**Describe the solution you'd like**
Add ToDo permissions.

**Do you have a workaround?**
Not that I know of.

**Comment by todsac** [comment]
I believe these are the scopes needed and I have added them to the connector.  Please let me know if you have any issues.
_Tasks.Read
Tasks.ReadWrite
Tasks.Read.Shared
Tasks.ReadWrite.Shared_

https://docs.microsoft.com/en-us/graph/permissions-reference?context=graph%2Fapi%2F1.0&view=graph-rest-1.0
