### ISSUE TITLE
[TRIGGER] DEAR new triggers

### ISSUE THREAD

**Issue by kmackesy** [PipedreamHQ/pipedream#5998]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

I would like to hook more DEAR systems events. You currently have one defined, New Authorized Sales Order (Sale/OrderAuthorised). It sets up a webhook and works fine. I would like the Stock/AvailableStockLevelChanged hook, as well as the others available here. 

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

These are the available webhooks: https://dearinventory.docs.apiary.io/#reference/webhooks/webhooks/get

**Comment by kmackesy** [comment]
I'm happy to do some coding. In the current code, I see that the api names are up to date and defined. 

The current .mjs that I would model after is: components/dear/sources/new-authorized-sale-order/new-authorized-sale-order.mjs

I copied it and made the changes I need. They would work if they were in place there, but there are imports that I am not sure how I can address.

How could I publish it so it associates with Dear and the imports are satisfied?

`
import constants from "../../common/constants.mjs";
import base from "../common/webhooks.mjs";

export default {
  ...base,
  name: "Available Stock Level Change",
  key: "dear-stock-level-change",
  type: "source",
  description: "Emit new event when available stock level changes",
  version: "0.0.1",
  dedupe: "unique",
  methods: {
    ...base.methods,
    getWebhookType() {
      return constants.WEBHOOK_TYPE.STOCK_AVAILABLE_STOCK_LEVEL_CHANGE;
    },
    getMetadata(payload) {
      const {
        amznTraceId,
        ...summary
      } = payload;

      const compositeId = `${payload[0].ID}-${amznTraceId}`;

      return {
        id: compositeId,
        summary: JSON.stringify(summary),
        ts: Date.now(),
      };
    },
  },
};
`

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
