### ISSUE TITLE
[FEATURE] I'd like to search workflows by their trigger URL

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#600]
It would be great if I could use the trigger URL in the workflow search box

![image](https://user-images.githubusercontent.com/27538/98205839-2805d580-1f39-11eb-9b6e-8b917b815a2b.png)

It would also be useful to search by any variable/string present in any of the steps of a workflow (including the names of the steps). 

I guess we would get this feature for free if/when pipedream workflows are saved as text files in Github.

**Comment by dylburger** [comment]
@nachocab this should be out!

![2021-01-27 14 04 08](https://user-images.githubusercontent.com/242668/106060202-970e4880-60a8-11eb-8d19-f1983a58fd35.gif)

**Comment by nachocab** [comment]
@dylburger any chance this could also work for sources? I've received emails like this from Stripe in the past:

> We’re contacting you because we’ve had some trouble sending requests to a webhook endpoint associated with your account in live mode. The failing webhook endpoint is https://SOURCE_ID.m.pipedream.net.

It would be good to be able to search by it

**Comment by dylburger** [comment]
@nachocab agreed, I opened #955 to track.

**Comment by christo9090** [comment]
Does this feature still work? Searching for known endpoints and nothing comes up. 

![image](https://user-images.githubusercontent.com/55903986/207464554-27e1550d-2ca7-4253-a35e-6a802a7486b7.png)


![image](https://user-images.githubusercontent.com/55903986/207464592-0eb9263d-0eac-4b5e-84c2-828513e693a2.png)

**Comment by dylburger** [comment]
@christo9090 This feature should work for [native workflow HTTP triggers](https://pipedream.com/docs/workflows/steps/triggers/#http). You're using an HTTP [event source](https://pipedream.com/docs/sources/), which runs as a separate resource and isn't searchable from the workflow UI. 

You can always add a new HTTP trigger to your workflow if you'd like:

1. Edit your workflow
2. Select the ... in the top-right of the trigger step, and select **Add trigger**
3. Select [the HTTP / Webhook native workflow trigger](https://pipedream.com/docs/workflows/steps/triggers/#http) from the right side of the trigger menu.
4. Point any systems to the new HTTP endpoint URL

That new URL should be searchable from the workflow UI!
