### ISSUE TITLE
[Components] Key App Demo 1

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6007]
### App
Key App Demo 1
https://demo.com

Triggers:
1. Event Completed: Triggers when a specific event, such as a webinar, has been completed or executed.
2. New User Registered: Triggers when a new user creates an account or registers for an event in the Key App Demo 1.

Actions:
1. Create Event: Creates a new event, like a webinar or workshop, within the Key App Demo 1 platform.
2. Register User: Adds a user to a specific event or function within the Key App Demo 1 system.
3. Update Event: Modifies the details of an existing event, such as date, time, or description, in the Key App Demo 1 platform.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
This is only for testing. Closing the ticket.
