### ISSUE TITLE
[Components] OAuth App Demo 1

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6008]
### App
OAuth App Demo 1
https://demo.com

Triggers:
1. User Authorized: Trigger when a user successfully authorizes the OAuth App.
2. Token Refreshed: Trigger when an access token is refreshed by the API.

Actions:
1. Obtain Access Token: Obtain an access token for authorized users.
2. Revoke Access Token: Revoke the access token for a specific user.
3. Retrieve User Profile: Fetch user profile data using the OAuth token.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
This is only for testing. Closing the ticket.
