### ISSUE TITLE
[Components] Slack Demo App 1

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6009]
### App
Slack Demo App 1
https://slack.com

Triggers:
1. Message Received: Triggers when a new message is posted in a specified channel.
2. User Joined: Triggers when a new user has joined the workspace.

Actions:
1. Send Message: Sends a message to a specified channel or user.
2. Create Channel: Creates a new public or private channel in the workspace.
3. Invite User: Invites a user to join a specified channel.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
This is only for testing. Closing the ticket.
