### ISSUE TITLE
[APP] visualping

### ISSUE THREAD

**Issue by FlixTed** [PipedreamHQ/pipedream#6013]
visualping.io

[**Link to developer documentation**](https://develop.api.visualping.io/doc.html)

detect new event

**Comment by sergioeliot2039** [comment]
VisualPing has a Basic + Bearer authentication method

> 
The only supported authentication method at this point is via a regular Visualping user and password. You may obtain an ID token using the user's email address and password as explained below.
https://develop.api.visualping.io/doc.html#section/Authentication

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by malexanderlim** [comment]
Hi @FlixTed , I'm happy to share that we now have a basic integration in place with VisualPing! Please have a look at the apps marketplace page here to get started (https://pipedream.com/apps/visualping). 

We've added building actions and triggers for VisualPing to the component development backlog, but if you'd like to self-service this as Dylan mentioned, you are able to author and publish your own Pipedream action in the interim.
