### ISSUE TITLE
[BUG] Unable to connect to Heroku account - OAuth callback issue

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6025]
**Describe the bug**
Unable to connect to Heroku account - OAuth callback issue

**To Reproduce**
1. Logged in to Heroku on another tab
2. On Pipedream Account page, search for Heroku app and connect to it
3. The Oauth pop up appear and show error `Couldn't find that registered client.`
<img width="712" alt="Screenshot 2023-04-14 at 15 23 16" src="https://user-images.githubusercontent.com/18277920/231987687-319cc32e-ae2e-4b43-8892-fc3124efc4d4.png">
4. Trying to login on the popup leads to the dashboard without proceeding with the OAuth flow
<img width="712" alt="image" src="https://user-images.githubusercontent.com/18277920/231987913-07f30e57-5107-490b-adb0-7542151db8af.png">

**Expected behavior**
I should be able to connect to my Heroku account

**Additional context**
First reported by a customer here https://pipedream.com/community/t/unable-to-connect-to-heroku-account-oauth-callback-issue/5557/1

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
