### ISSUE TITLE
[Components] VisualPing

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6036]
### App
VisualPing
https://visualping.io/

Triggers:
1. Check Completed: Detects when a visual comparison check has finished.
2. Alert Received: Triggers when a change alert is sent by VisualPing.

Actions:
1. Create Monitor: Creates a new website monitor with specified settings.
2. Update Monitor: Allows updating an existing website monitor's settings.
3. Check Monitor Now: Forces an immediate check of a specified website monitor.

_This list of suggested components was generated using ChatGPT_

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release! 

Test report
[VisualPing_6036_1334.pdf](https://github.com/PipedreamHQ/pipedream/files/11471286/VisualPing_6036_1334.pdf)
