### ISSUE TITLE
[BUG] Pushover Priority must be an Integer error when using dropdown selections

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#6048]
**Describe the bug**
The Pushover send `Push Notification` action has a bug when you select `Priority` from the dropdown (see screenshots) when you manually type the number in Custom Expression everything works as it should.

**To Reproduce**
1. Create a Push Notification action
2. Add and select a Priority from the dropdown
3. See 'must be an integer' appears
4. Sending a notification will result in an error

**Expected behavior**
No error when selecting from dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/8470449/232338144-bbb456d9-ed4c-4e2f-9081-c44aaa80aeb1.png)

![image](https://user-images.githubusercontent.com/8470449/232338188-3653e2c6-97c1-48af-b7fd-0ad7de319da2.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version Latest

**Comment by vunguyenhung** [comment]
Thanks @NebularNerd for raising this bug! I can reproduce it and have added it to Pipedream prioritized backlog
