### ISSUE TITLE
[APP] Looker Studio API

### ISSUE THREAD

**Issue by Paktas** [PipedreamHQ/pipedream#6053]
**Looker Studio API**

**Link to developer documentation**
https://developers.google.com/looker-studio/integrate/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes it is - we'd like to pull data into Looker Studio to visualise it, but existing Looker Studio solutions do not work us. We would love to use Pipedream for that.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

- Create Pipedream as a data source: https://support.google.com/looker-studio/topic/6370331?hl=en-GB&ref_topic=7441382&sjid=6555918681504236006-EU
- Create a custom workflow with existing Pipedream connectors to feed into Looker Studio API.

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/looker

**Comment by Paktas** [comment]
Not true. This ticket was for Looker Connector that could pull data **FROM Pipedream**.
The app mentioned above is for taking data from Looker (reverse).

![image](https://github.com/PipedreamHQ/pipedream/assets/6200695/e38fe28f-ba85-4cff-8877-d933e25e1e51)
