### ISSUE TITLE
[APP] TradingView

### ISSUE THREAD

**Issue by sunilgug** [PipedreamHQ/pipedream#6064]
**getting alerts from tradingview**
**getting backtest results and features available in tradingview**

**Link to developer documentation**
https://www.tradingview.com/rest-api-spec/

**Comment by pdactionddev** [comment]
hi @sunilgug 
Sergio here

just for understanding, getting alerts / getting backtest would be expected endpoints from the API documentations, and you want those as Pipedream actions, correct?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
