### ISSUE TITLE
[FEATURE] Improve UI for the SQL interface

### ISSUE THREAD

**Issue by loicginoux** [PipedreamHQ/pipedream#607]
After using the SQL interface, I have some feedbacks to share:

<img width="668" alt="Screenshot 2020-11-11 at 15 15 56" src="https://user-images.githubusercontent.com/824936/98822332-01600700-2431-11eb-8e4f-9b71f9ba583d.png">

1 - In order to explore manually the data from a table. I would like tho be able to copy paste the name of a table to quickly show the data inside the table.
At the moment, because I can't copy/paste and because the name of the table is complicated and long, I have to open the browser console to dig the html and copy paste the name of the table to then put it in my query. That would be better if I had a quicker access to the table name. I understand that the tables are  inside an accordeon, maybe when selecting the table, it could prefill the query field with `SELECT * FROM <SELECTED_TABLE>;`

2 - My table has more than 1000 results (1500 exactly). A `select count(*) FROM table` gives me the correct number, but a `select * FROM table` prints `results(999)`. I guess you paginate the results in background but it's not obvious to me as a user. 

3 - `SELECT * FROM <SELECTED_TABLE>;` loading 999 results on a table of ~70 column is slow. It's understandable but maybe having a pagination on the interface and having by default 50 items displayed on first page would help.

**Comment by dylburger** [comment]
Thank you for the feedback @loicginoux . Re: #1 I like the idea of having a "preview" button that does the `SELECT * LIMIT 10` (Snowflake's UI has similar functionality).

Noted re: the pagination issues. We'll look into that as soon as we can.

**Comment by dylburger** [comment]
The SQL Service will be shutting down on Feb 10th, 2022 (you can read more details in [this post](https://pipedream.com/blog/shutting-down-the-sql-service/)). As a result, we're closing this issue.

Let us know if you have any questions at all.
