### ISSUE TITLE
[ACTION]Trello to trigger specific Google Sheets actions

### ISSUE THREAD

**Issue by junkytunk** [PipedreamHQ/pipedream#6084]
Google Sheets

Hi,
I’ve been trying to get the addition of a label in trello to trigger google sheets to do a few things:

-     duplicate a “template” tab in a specific “project worksheets” file

-     move that tab to the immediate right of the “template” tab in that same file

Thanks for your help!

**Comment by vunguyenhung** [comment]
Hi @junkytunk, I believe this is too specific for your usecase. Could you structure the ticket into smaller actions with the their respective API docs? For example:
- Google Sheet - Duplicate a sheet
- Google Sheet - Move sheet

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
