### ISSUE TITLE
[ACTION] OneDrive - Download file to tmp dir

### ISSUE THREAD

**Issue by Mad-Pickle** [PipedreamHQ/pipedream#6114]
**Is there a specific app this action is for?**
OneDrive - Download file to tmp dir

**Please provide a link to the relevant API docs for the specific service / operation.**
https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content?view=odsp-graph-online

**Comment by vunguyenhung** [comment]
Hi @Mad-Pickle, I've updated your ticket to download the file to `tmp` dir. After you have the file in `tmp` dir, you can pass it to other actions

**Comment by Mad-Pickle** [comment]
Thank you!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by michelle0927** [comment]
Testing passed! Ready for release!

Test report
[OneDrive_6114_6212.pdf](https://github.com/PipedreamHQ/pipedream/files/11390612/OneDrive_6114_6212.pdf)
