### ISSUE TITLE
[FEATURE] OneDrive - New File in Folder (Instant) source - List subfolders for watching

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6116]
**Is your feature request related to a problem? Please describe.**
Currently, OneDrive - New File in Folder (Instant) source only list folders on the root
![image](https://user-images.githubusercontent.com/18277920/233598132-fbfdbccd-d78f-46f8-bb33-5f10ea8dd816.png)

I couldn't choose the subfolder

**Describe the solution you'd like**
I would like to choose the subfolder. 

**Do you have a workaround?**
No

**Additional context**
Reported by a customer here

**Comment by GTFalcao** [comment]
@vunguyenhung one request has to be made separately for each directory in the tree - if we perform all of them before showing the options, this can easily result in dozens of requests and 20-30+ seconds of waiting time. I thought the "load more" pagination interface we have would be a better approach.

I also tried using search query for better results, but that endpoint didn't work well with our query interface.

**Comment by GTFalcao** [comment]
Let me know if there is another better and viable solution for this one.
