### ISSUE TITLE
[Components] Lettria

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6128]
### App
Lettria
https://www.lettria.com/

Triggers:
1. Text Analyzed: Notifies when a specified text has been analyzed using Lettria API.
2. Sentiment Detected: Triggers when a specific sentiment (positive, negative, or neutral) has been detected in the analyzed text.

Actions:
1. Analyze Text: Analyzes the input text using Lettria's NLP capabilities and provides detailed metrics.
2. Extract Keywords: Extracts keywords from the input text using Lettria's keyword extraction feature.
3. Get Sentiment Analysis: Provides sentiment scores for the input text using Lettria's sentiment analysis functionality.

_This list of suggested components was generated using ChatGPT_

**Comment by vellames** [comment]
It is impossible to have all of the ChatGPT suggestions using Lettria API. The only available endpoint is for `Classification`. It is impossible to have sources, there is no endpoint for listing or any webhook. As far as my understanding of the documentation. It is only possible to implement one action
