### ISSUE TITLE
[ACTION] Shopify Update Product improvements

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#6134]
Shopify

Add functionality to add "Product Category"
(Right now we only have "Product Type")
https://shopify.dev/docs/api/admin-graphql/2023-01/objects/ProductCategory
https://help.shopify.com/txt/product_taxonomy/en.txt?shpxid=afbce660-5B52-4C00-3E54-B6B44E715596

Add functionality to amend "SEO handle & URL"
(Right now we only have SEO Title & Description)
https://shopify.dev/docs/api/admin-rest/2023-04/resources/product
(I think it's the handle but will need testing to be sure)
In the shopify admin this process automatically creates a redirect from the old handle to the new one:
![image](https://user-images.githubusercontent.com/123815443/233863678-2eeb5094-53d2-4c62-ae86-a283009d7c32.png)
This may be useful?
https://shopify.dev/docs/api/admin-rest/2023-01/resources/redirect

Thanks!!

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
