### ISSUE TITLE
[ACTION] Shopify Create Order improvements

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#6135]
Shopify

https://shopify.dev/docs/api/admin-rest/2023-04/resources/order#post-orders

1. Add Notes
 ```

	"note": null,
    "note_attributes": [
      {
        "name": "custom engraving",
        "value": "Happy Birthday"
      },
      {
        "name": "colour",
        "value": "green"
      }
    ],
```

2. Option to edit inventory level when order is processed
(right now a new order with variant ID doesnt not remove any quantity of stock from the total inventory)
https://shopify.dev/docs/api/admin-rest/2023-04/resources/order#post-orders
"By default, product inventory is not claimed when creating an order.
There are additional optional parameters that can be specified in the body of the request when creating an order:
inventory_behaviour:..."
https://shopify.dev/docs/api/admin-rest/2023-01/resources/inventorylevel
https://shopify.dev/docs/api/admin-rest/2023-01/resources/inventorylevel#post-inventory-levels-adjust

3. Add a shipping line to the order
current:
![image](https://user-images.githubusercontent.com/123815443/233865311-b2bc39c9-769d-4829-b210-ff5e9f71228c.png)
desired:
![image](https://user-images.githubusercontent.com/123815443/233865688-e6aa620c-4bb7-4f15-be04-f6319cd7617f.png)

```
  "shipping_lines": [
    {
      "code": "INT.TP",
      "price": "4.00",
      "price_set": {
        "shop_money": {
          "amount": "4.00",
          "currency_code": "USD"
        },
        "presentment_money": {
          "amount": "3.17",
          "currency_code": "EUR"
        }
      },
      "discounted_price": "4.00",
      "discounted_price_set": {
        "shop_money": {
          "amount": "4.00",
          "currency_code": "USD"
        },
        "presentment_money": {
          "amount": "3.17",
          "currency_code": "EUR"
        }
      },
      "source": "canada_post",
      "title": "Small Packet International Air",
      "tax_lines": [],
      "carrier_identifier": "third_party_carrier_identifier",
      "requested_fulfillment_service_id": "third_party_fulfillment_service_id"
    }
  ],
```

4. Add the "Tax" line amount to the "Total" line amount:
(Tax amount is displayed currently but not added to the total amount on the final line)
current:
![image](https://user-images.githubusercontent.com/123815443/233865369-bcb5adf0-ec67-4566-a54c-6e59a9820ec9.png)
desired:
![image](https://user-images.githubusercontent.com/123815443/233865929-4638dfdc-ed2a-4f9e-bfdc-f10c35e0213d.png)
(tax amount/display is incorrect in the example show but isn't causing the issue)

5. Amount paid by customer line
(currently showing zero see images at 4)
I'm not sure if this is a direct input or something in the background that calculates something along the lines of (IF paid = yes) then add total line to paid by customer line or similar.

Apologies in advance for it being a lot! I tried to save them up for a single update/improvement. Right now points 2, 3, 4 are preventing me being able to use it. 1 isn't important in comparison. 5 is just for neatness/clarity.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
