### ISSUE TITLE
[Action] OneDrive Download file

### ISSUE THREAD

**Issue by LunaEasee** [PipedreamHQ/pipedream#6141]
OneDrive Download file: (can use the Google Drive Download File action as a guide)

https://learn.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online

**Comment by vunguyenhung** [comment]
Hello @LunaEasee, we have a ticket tracking here: https://github.com/PipedreamHQ/pipedream/issues/6114. Please subscribe to that ticket instead to be noticed when it is done.

Thanks
