### ISSUE TITLE
[BUG] Zoho Creator - New or Updated record throws Request failed with status code 404

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6142]
**Describe the bug**
When creating a new source Zoho Creator - New or Updated record, it throws Request failed with status code 404
![image](https://user-images.githubusercontent.com/18277920/234052232-0268ad0a-0aea-424c-91c8-0c4b5df51809.png)

**Expected behavior**
The source should be created successfully

**Additional context**
Reported by users here https://pipedream.com/community/t/request-failed-with-status-code-404-creating-trigger-on-zoho-creator/5543/1

**Comment by alysonturing** [comment]
@vunguyenhung I was able to create the source, please can you try it again.
<img width="949" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/103650302/7f2b5353-699b-4b55-a56a-d6bd95925f7d">
<img width="968" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/103650302/6fb680bd-ea20-4321-b044-1f2d0849e3df">
<img width="941" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/103650302/657edb88-63b4-4c47-bc2b-40fd3f245a36">

**Comment by alysonturing** [comment]
It is very important to follow the following instructions:
![image](https://github.com/PipedreamHQ/pipedream/assets/103650302/54583444-b1c0-43db-9245-eecdebca97c7)
[the grouping help article](https://www.zoho.com/creator/newhelp/reports/display-records-as-groups-list-report.html)

**Comment by vunguyenhung** [comment]
Hi @alysonturing, good catch! I have communicated [with the users here](https://pipedream.com/community/t/request-failed-with-status-code-404-creating-trigger-on-zoho-creator/5543/4?u=vunguyenhung), so I will close this ticket. Thank you so much for your time!
