### ISSUE TITLE
[FEATURE] Queue size indicator

### ISSUE THREAD

**Issue by zecul** [PipedreamHQ/pipedream#6146]
**Is your feature request related to a problem? Please describe.**
My queue sizes can get pretty large. Right now I'm processing 8000 products at with a 8 second setting so its 17hrs+
There are other jobs I need to send to the queue but they'll need to be processed pretty quickly to not make the site look weird until they are. So I'd like to know how close to finishing I am so I can decide which jobs to do first and/or pause/cancel/interupt the current workflow

**Describe the solution you'd like**
Current number of items in the queue/still to be processed.

**Do you have a workaround?**
I've made it work so far, I just try and calculate it manually from when I started.

**Comparable features in other tools?**
No idea!

**Additional context**
Also useful if you have over 10,000 items to process so you know when you can dump an extra 2000 into the queue (ie once total queue is below 8000)

My queue size is pretty easy to calculate because the code runs faster than the API limit (8s). If the code was slower than the API limit then it would be much harder to calculate.

**Comment by dylburger** [comment]
Tracking at #842
