### ISSUE TITLE
spreadsheet.com [APP]  - https://developer.spreadsheet.com/#section/Using-the-API

### ISSUE THREAD

**Issue by tootflap** [PipedreamHQ/pipedream#6153]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Closing in favor of #7395
