### ISSUE TITLE
[TRIGGER] Zendesk - emit new event when ticket is added to view

### ISSUE THREAD

**Issue by famousdrew** [PipedreamHQ/pipedream#6156]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
The current Zendesk app has events for ticket creation, solve, etc. Often Zendesk users will want to know when tickets reach certain teams or views. Often these are related to high-priority customers, etc. Tickets are placed in views either manually by agents, or automagically by Zendesk's own automations/triggers that the customer has defined. We would like to see an event that triggers whenever a ticket is assigned to a specific view or views.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developer.zendesk.com/api-reference/ticketing/business-rules/views/

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
