### ISSUE TITLE
Download File [ACTION]

### ISSUE THREAD

**Issue by Tgrli** [PipedreamHQ/pipedream#6163]
**Is there a specific app this action is for?**
Just a similar download function like the one for google drive. Thanks a lot! love the pipedream tool!! 
**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by vunguyenhung** [comment]
Hi @Tgrli, what specific app you want to download the file from?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
