### ISSUE TITLE
[FEATURE] A live dashboard to follow current state of workflows

### ISSUE THREAD

**Issue by loicginoux** [PipedreamHQ/pipedream#617]
It might be related to https://github.com/PipedreamHQ/pipedream/issues/156
I have a "complex" set of workflows that call each others, wait for external service response, etc..
When I trigger the first workflow, there is no easy way to follow what's currently happening if you don't go on each workflow to see if it's currently running.
It would be good to have a page where I can visualize what's currently happening, what are the last events:
- which workflow is running
- last successful runs
- last errored runs

If you are familiar with the ruby env, [Sidekiq](https://github.com/mperham/sidekiq) dashboard does it well via their interface, that shows it leave it here for inspiration:
![web-ui](https://user-images.githubusercontent.com/824936/99085525-95b0a200-25c8-11eb-8b80-98fd41bf86ad.png)

I could implement it via slack notifications for example to log when workflow starts/ends/fails, but I guess, that's worthy enough to be inside pipedream...

**Comment by calpa** [comment]
The current deta.sh dashboard only showed limited information, hoping the development team to add more information...

**Comment by favouritehu** [comment]
Im Using Zoho flow Zoho flow Have Dash Bord To visualize task History how to do so in pipe dream
<img width="1375" alt="Screenshot 2022-08-05 at 1 43 23 PM" src="https://user-images.githubusercontent.com/80187559/183033374-9d745dac-ca9a-45d4-ba7f-89c1ae32eefb.png">

**Comment by dylburger** [comment]
Most of these asks have now been implemented in https://pipedream.com/event-history . That shows all successful / failed workflow runs across all workflows. It does not show the state of all suspended / paused executions, but the workflow inspector (specific to each workflow) should show the state of those executions for inspection.
