### ISSUE TITLE
"download" for Onedrive

### ISSUE THREAD

**Issue by szamma** [PipedreamHQ/pipedream#6171]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by szamma** [comment]
Would like to select download action for Onedrive. it looks this is available for google drive...

**Comment by vunguyenhung** [comment]
Hi @szamma, we have [a ticket for tracking this action here](https://github.com/PipedreamHQ/pipedream/issues/6114). Kindly subscribe to it to be noticed when the action is finished 🙏
