### ISSUE TITLE
[FEATURE] Slack - New Reaction Added (Instant): include item_user and user data

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6173]
**Is your feature request related to a problem? Please describe.**
Currently, the Slack - New Reaction Added (Instant) only have the `user` and `item_user` ID, which might not fulfill user usecase
![image](https://user-images.githubusercontent.com/18277920/234829081-28d042a8-3ef4-4a40-b4f2-72cea1e0324d.png)

**Describe the solution you'd like**
Add a new boolean prop `Include User Data` to allow user to optionally enable the source to fetch User data for each event. 

Then the source should fetch data for `user` and `item_user` using the IDs in the event

**Do you have a workaround?**
Use Slack API to get user https://api.slack.com/methods/users.info

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1682587372293639

**Comment by michelle0927** [comment]
Testing passed! Ready for release!

Test report
[Slack_6173_6188.pdf](https://github.com/PipedreamHQ/pipedream/files/11384061/Slack_6173_6188.pdf)
