### ISSUE TITLE
[APP] Shazam

### ISSUE THREAD

**Issue by dep** [PipedreamHQ/pipedream#6174]
**Name of app / service**: Shazam

**Link to developer documentation**
https://rapidapi.com/apidojo/api/shazam

**Is lack of support preventing you from building workflows, or do you have a workaround?**:
No

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**:
- New Shazam

Use case would be Shazam a song, add to Spotify, etc.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @dep 

thanks for the request.

the app you are requesting currently doesn't have an official api. plus, the api you are referencing is hosted by Rapid API:

Can you please try out to see if you can access their Shazam endpoints with our app for Rapid API?
You'll need to customize code: https://pipedream.com/apps/rapidapi

But currently we are not onboarding specific apps whose APIs are hosted at other marketplaces (they should run on their own servers).

That said, regarding your "New Shazam" component. Are you looking for a trigger that starts a Workflow when a new shazam (song) is recognized?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
