### ISSUE TITLE
Lattice

### ISSUE THREAD

**Issue by dantheman82** [PipedreamHQ/pipedream#6175]
**Lattice**

**[Link to developer documentation**](https://lattice.com/api)

**Is lack of support preventing you from building workflows, or do you have a workaround? Workaround unknown**

**Are there specific actions, or triggers, you'd like to see for this app? New tasks assigned to me, new updates in a specific 1:1, etc. Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by malexanderlim** [comment]
Hi @dantheman82, can you share a little bit about the use case that you are trying to build with the Lattice integration? I've set up a call to discuss a Pipedream <> Lattice partnership with their team, and I'd love to share a real-world use case as you are our mutual customer.

**Comment by malexanderlim** [comment]
@dantheman82 , I've enabled the integration - let me know if this works for your use case!
