### ISSUE TITLE
[FEATURE] Finding workflow for a Trigger URL

### ISSUE THREAD

**Issue by Clausinho** [PipedreamHQ/pipedream#6177]
**Is your feature request related to a problem? Please describe.**
I have an .env full of trigger urls, but no clue to which workflow they belong to. When I access them, I get the standard success screen, but nothing more

**Describe the solution you'd like**
Maybe just a link to the workflow would be enough, as it is mostly private and not accessible by the outside?
or maybe just the ID on the standard template

**Do you have a workaround?**
I can look through each workflow, to see if an event with the specific path is recorded.

**Additional context**
Originally came from [here](https://pipedream.com/community/t/finding-workflow-for-a-trigger-url/3617), but a feature request was never made. I have some workflows and just changing the standard response template could be an easy quick fix.

**Comment by dylburger** [comment]
This is now supported! You can search workflows by trigger URL from the global search UI at the top-left:

<img width="453" alt="Screenshot 2023-07-30 at 8 25 35 PM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/5c19aee1-a964-4ddf-9b0a-ad84f5b73b2f">
