### ISSUE TITLE
[Components] Google Maps Platform (Places API)

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6183]
### App
Google Maps Platform (Places API)
https://mapsplatform.google.com/

Triggers:
1. Place Searched: Triggered when a specific place has been searched.
2. Nearby Places Updated: Activated when new places appear or existing places are updated around a specified location.

Actions:
1. Search Places: Find places based on specific keywords or types.
2. Get Place Details: Retrieve detailed information about a specific place.
3. Get Nearby Places: Discover nearby places around a specified location using keywords or types.

_This list of suggested components was generated using ChatGPT_

**Comment by dhruvspathak** [comment]
I would like to contribute to this isse. Can you please provide me with more details?
