### ISSUE TITLE
[IMPROVEMENT] Mailwizz - Improve connection popup description

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6187]
**Is your feature request related to a problem? Please describe.**
When connecting to Mailwizz account, the connection popup doesn't mention that some urls need to have `/api/index.php` appended.
![11 44 42 - 28 - 04 - 2023](https://user-images.githubusercontent.com/18277920/235056502-fa24266f-0144-4fd7-bcf7-955a2b70be58.png)
![image](https://user-images.githubusercontent.com/18277920/235055785-0562e6e5-b6bc-4dbd-af3a-4b7175809970.png)

**Describe the solution you'd like**
Improve the description on the connection popup so that it mention for some Mailwizz website that does not have clean url enabled, the user need to add `/api/index.php`

**Comment by malexanderlim** [comment]
@vunguyenhung , thank you very much for the suggestion. 
I've added in some language about requirements if clean url is not enabled.
<img width="639" alt="Screen Shot 2023-05-01 at 10 54 23 PM" src="https://user-images.githubusercontent.com/42158621/235589766-57d3dcd9-1267-4d07-930e-951e7878f2e4.png">

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
