### ISSUE TITLE
[TRIGGER] ZeroTier Online/Offline Node no longer works due to API change

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#6193]
ZeroTier recently updated their API and eliminated the `online` parameter.

Previously this flag was just determined by being seen in the last 3 minutes.

We need to update the ZeroTier triggers for Node Online/Offline to utilize the `lastSeen` parameter and determine if the change from the last time was greater than 3 minutes to match the previous functionality. 

- https://github.com/PipedreamHQ/pipedream/issues/2524#issuecomment-1111472548
- https://discuss.zerotier.com/t/central-change-rollout-last-seen/12836?u=zalmanlew

cc @lcaresia @laduke

**Comment by Nanak360** [comment]
I can take it up

**Comment by Nanak360** [comment]
I can take it up
