### ISSUE TITLE
[BUG] Slack emoji triggers cause duplicate workflow runs

### ISSUE THREAD

**Issue by dep** [PipedreamHQ/pipedream#6196]
**Describe the bug**
I have a workflow that's running twice in a row even though I only reacted to a single slack message:

**To Reproduce**
1. Create a trigger based on a slack emoji reaction
2. Deploy
3. When workflow runs, it runs twice

**Expected behavior**
Runs once

**Screenshots**

![image](https://user-images.githubusercontent.com/55112925/235242621-6960b6cd-88ae-478b-a630-ada01d9e9685.png)

**Comment by dannyroosevelt** [comment]
@dep it looks like maybe you have 2 Slack triggers configured for that workflow?
![Screenshot 2023-04-28 at 1 06 08 PM](https://user-images.githubusercontent.com/20780753/235243587-4865463e-d89d-4e45-846a-bf5cafa2676f.png)

**Comment by dep** [comment]
Oh! i didn't know you could chain triggers like this 😁
