### ISSUE TITLE
Smart Suite[APP]

### ISSUE THREAD

**Issue by mwestheffer** [PipedreamHQ/pipedream#6200]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
@mwestheffer thanks for the request.

Is this the Smart Suite app integration you are looking for?

https://pipedream.com/apps/smartsuite

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
