### ISSUE TITLE
[ACTION]

### ISSUE THREAD

**Issue by jaymansr** [PipedreamHQ/pipedream#6216]
**Is there a specific app this action is for?**

I woud like bcc to be intergrated with smtp2go on pipedream. The bcc is not working

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by vunguyenhung** [comment]
Hi @jaymansr, would you mind sharing steps to reproduce your issue? It would be a great help if you can provide some screenshot of your action configuration also

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
