### ISSUE TITLE
[FEATURE] Automatically rev component versions on Github Actions PR

### ISSUE THREAD

**Issue by andrewjschuang** [PipedreamHQ/pipedream#6218]
**Is your feature request related to a problem? Please describe.**
When modifying a component or app file, we usually need to rev all the versions so they are updated and published. For some apps this may impact >20 components, and that takes a long manual time.

**Describe the solution you'd like**
A Github Actions Step after this [Components Version Check](https://github.com/PipedreamHQ/pipedream/blob/master/.github/workflows/pull-request-checks.yaml#L36) that will rev the patch version of all components that are affected, **but unchanged** (including `package.json`)

**Comment by vunguyenhung** [comment]
Hi @andrewjschuang, would you mind advice how can I test this?

**Comment by andrewjschuang** [comment]
@vunguyenhung absolutely!

**Test 1:**

1. Create a new branch from `master`.
2. Choose an app with a bunch of actions and sources.
3. Modify anything in the code in the app file, i.e., add a `console.log` somewhere.
4. Commit that change and push it.
5. Create a Pull Request.

**Expected behavior:**

- [ ] The **Ensure component commits modify component versions** pull request check should not fail.
- [ ] In the **Files Changed** section of the PR, check if all the components versions **patch** versions were incremented by 1. For example, `0.1.5` became `0.1.6`.
- [ ] Verify if that was the only added change besides your changes in the PR.
- [ ] Check the **Ensure component commits modify component versions** logs and see if it contains descriptive information mentioning the patch version update, probably in the **Check git diff for version changes**, or even better, in a new step after that one.


**Test 2:**

1. Do everything in **Test 1** again.
2. Now choose 2 or 3 components and manually bump their versions.
3. Commit these changes and push them to the PR.

**Expected behavior:**

- [ ] Everything should be the same as **Test 1**, except:
- [ ] The 2 or 3 components versions that you manually changed, these **should not** have their versions automatically changed again. So if you changed a version to `0.2.7`, it should still be `0.2.7` after the Github PR checks. The ones that you did not manually change should have their versions updated automatically.

Feel free to ask any questions if you have!

**Comment by malexanderlim** [comment]
Sorry Lucas, I'm not sure I understand what the blocker is currently?
