### ISSUE TITLE
Jotform encrypted forms [ACTION]

### ISSUE THREAD

**Issue by pablonnz** [PipedreamHQ/pipedream#6221]
Hello, 

When using Jotform encrypted forms, there is no way of decrypting form data once received into Pipedream. Please note, Jotform has recently added a new feature to encrypt form data for added security. When transmitting data via webhook or via Jotform integration, data is encrypted and must undergo an additional step to decrypt the information with the private key provided by Jotform. 

Are there any built options for accomplishing this or any plans on creating such feature?

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
