### ISSUE TITLE
[BUG] Unable to import PyPI package for pinecone

### ISSUE THREAD

**Issue by reedwi** [PipedreamHQ/pipedream#6226]
**Describe the bug**
Trying to perform a [“Magic Comment”](https://pipedream.com/docs/code/python/import-mappings/#use-pypi-packages-with-differing-import-names) to install a PyPI package that differs from it’s import name. I am trying to use pinecone with a langchain agent which is why I’m not using the direct pinecone integration/workflow step. I seem to be following the syntax, but i am getting an error still. 

```
# pipedream add-package pinecone-client
import pinecone
```

**Expected behavior**
Package successfully installs and is usable

**Actual Behavior**
Error
Command failed: python3 -m pip install --target=/tmp/__pdg__/dist/python -r requirements.txt --upgrade WARNING: The directory ‘/home/sbx_user1051/.cache/pip’ or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo’s -H flag. ERROR: Could not find a version that satisfies the requirement pinecone==0.1.0 (from versions: none) ERROR: No matching distribution found for pinecone==0.1.0 WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available. You should consider upgrading via the ‘/var/lang/bin/python3 -m pip install --upgrade pip’ command.

**Comment by dylburger** [comment]
Thanks for reporting @reedwi , I'm tracking at #6260. Please follow that issue if you don't mind.
