### ISSUE TITLE
[BUG] - Action for Google Sheets Add Multiple Rows

### ISSUE THREAD

**Issue by StetsonRamey** [PipedreamHQ/pipedream#6237]
**Describe the bug**
I have a step in a workflow to create a google sheet.  This step returns the sheetID and can be referenced in other steps as
{{steps.create_spreadsheet.$return_value.spreadsheetId}}

I think want to use this sheetID in an add multiple rows to a sheet action.  The sheet to add rows to won't always be the same, so I'd like to use the reference {{steps.create_spreadsheet.$return_value.spreadsheetId}} to dynamically target the appropriate sheet

When I use the reference {{steps.create_spreadsheet.$return_value.spreadsheetId}}, the add multiple rows action, in the next prop input for Sheet Name I get an error of "requested entity was not found".

If I copy just the text of the sheetID from the create sheet step and paste that into the Spreadsheet prop, the action works as expected.  

THEREFORE, I believe that somehow the expression {{steps.create_spreadsheet.$return_value.spreadsheetId}} isn't evaluating quick enough or before the action looks for sheet names and is therefore returning nothing.  It's not getting the id through.

**To Reproduce**
1. reference a return value from a previous step in Spreadsheet prop
2. Click Sheet name prop
3. get error "requested entity was not found"

**Expected behavior**
the action should use the sheetID referenced to get all the sheet names from that specific google sheet.  I should then be able to select my sheet from the Sheet Name prop dropdown

**Screenshots**

![CleanShot 2023-05-03 at 08 08 12@2x](https://user-images.githubusercontent.com/7082836/235988703-ef4d07c6-1e29-40fb-a837-1560c26fa13f.png)

![CleanShot 2023-05-03 at 08 07 01@2x](https://user-images.githubusercontent.com/7082836/235988634-f758e3f9-79f5-431c-a15c-3ebf9451c58a.png)

![CleanShot 2023-05-03 at 08 47 56@2x](https://user-images.githubusercontent.com/7082836/235989442-f67ce0de-4ef0-433c-b96c-fdbd25bd6c5a.png)

![CleanShot 2023-05-03 at 08 48 15@2x](https://user-images.githubusercontent.com/7082836/235989271-6ce9b202-7818-4ef9-bda1-dcbf68a8416a.png)

**Desktop (please complete the following information):**
 - OS: Ventura 13.3.1
 - Browser Arc browser (running chrome)

**Additional context**

**Comment by dannyroosevelt** [comment]
Responded in Slack, re-posting here:

Async options (dynamic fetching of “Sheet Names” will not work with step references (`{{steps.create_spreadsheet.$return_value.spreadsheetId}}`), so it just means you need to also use a custom expression (can be a step reference) for the Sheet Name prop (ie, `Sheet1` or `{{steps.create_spreadsheet.$return_value.sheets[0].properties.title}}`).

I just tested this and it works for me

![image](https://user-images.githubusercontent.com/20780753/236014717-15c676dd-b880-4dbe-8a25-ee1291a97b42.png)
![image](https://user-images.githubusercontent.com/20780753/236014733-c8cbff44-6143-4ef7-9663-7ea94298b8f9.png)
![image](https://user-images.githubusercontent.com/20780753/236014752-31078f57-3735-4545-83e4-592adeeec489.png)

**Comment by dannyroosevelt** [comment]
Let me know if that helps clarify, or if you have additional questions!

**Comment by StetsonRamey** [comment]
This 100% works.  Thanks for the info @dannyroosevelt

**Comment by AbdulRafay** [comment]
Seems like the bug re-appeared 

![image](https://github.com/PipedreamHQ/pipedream/assets/614883/7b1f93f2-9ed8-4264-8c65-26f4c5651d90)
