### ISSUE TITLE
[BUG] CLI `pd dev my-source.mjs` result in error 400: `please specify a valid workspace`

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#6238]
**Describe the bug**
I try to make some change in the nordigen source (like I already did 10 times). When I use `pd dev new-transaction.mjs`, I have the following error:

```
watch:add     | D:\Repos\pipedream\components\nordigen\sources\new-transaction\new-transaction.mjs
watch:add     | D:\Repos\pipedream\components\nordigen\nordigen.app.mjs
watch:add     | D:\Repos\pipedream\components\nordigen\common\constants.mjs
Detected local requires, creating zip archive...
- sources/new-transaction/new-transaction.mjs
- nordigen.app.mjs
- common/constants.mjs
error         | component create api call responded with status: 400, body: {"error":"please specify a valid workspace"}
Waiting for file change (or ^C to quit)...
```

If I update the file, I have the same error again and again and again.

**To Reproduce**
1. In a terminal, go to `components\nordigen\sources\new-transaction`
2. Enter 'pd dev  new-transaction.mjs'

**Expected behavior**
No error displayed and waiting for the file to be updated.

**Aditionnal context**
- I have this issue with all the sources and all the actions.
- Same result with `deploy` or `publish`
- I am logged in
- CLI version is 0.2.14

**Comment by LucBerge** [comment]
**ByPass**
- `pd logout`
- `pd login`
- Select a workspace, **do not select `none`**

This type of error should be handled by the CLI. You should specify in the user to select a workspace (ie: organization).

Why I need to select a workspace in order to deploy my source ?

**Comment by dannyroosevelt** [comment]
@LucBerge since all workflows now run in a workspace, you have to specify which workspace to publish and deploy locally developed components to, since they are now "owned" by that workspace, as opposed to your user.

If you want to publish and deploy to different workspaces without logging out and in of the CLI every time, you can do that by creating a profile here: https://pipedream.com/docs/cli/reference/#creating-a-profile-for-a-workspace

**Comment by dannyroosevelt** [comment]
That was the error you specified, but I agree a link to the docs is a good idea:
```error | component create api call responded with status: 400, body: {"error":"please specify a valid workspace"}```

You should have gotten an email from Dylan recently with a subject line like, "New features and plan changes for your account" or "Major improvements to your Pipedream account", which included some additional context and links to docs re: this changes, but let me know if not!

**Comment by LucBerge** [comment]
> That was the error you specified, but I agree a link to the docs is a good idea:
error | component create api call responded with status: 400, body: {"error":"please specify a valid workspace"}
>
> You should have gotten an email from Dylan recently with a subject line like, "New features and plan changes for your account" or "Major improvements to your Pipedream account", which included some additional context and links to docs re: this changes, but let me know if not!

I haven't received anything like this (maybe because I unsubscribed from the news...)
