### ISSUE TITLE
[APP] Wealthbox CRM

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6241]
**Name of app / service**
Wealthbox CRM

**Link to developer documentation**
http://dev.wealthbox.com/#introduction-introduction

**Context**
Wealthbox CRM indexed in Project App Store sheet

**Triggers**
New Contact
New Event
New Opportunity
New Task

**Actions**
Create a new contact
Create a new event 
Create a new task
Create a new opportunity

**Comment by malexanderlim** [comment]
Emailed Wealthbox with redirect URI, awaiting client id + secret.
