### ISSUE TITLE
[APP] streamtime.net

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6243]
**Name of app / service**
Streamtime

**Link to developer documentation**
https://documenter.getpostman.com/view/802974/RWgtSwbn?version=latest#intro

**Comment by malexanderlim** [comment]
Reached out to the Streamtime team via their chat application.
https://streamtime.net/support

**Comment by sergio-eliot-rodriguez** [comment]
2nd reached out attempt

**Comment by sergio-eliot-rodriguez** [comment]
Submitted as API keys

**Comment by sergio-eliot-rodriguez** [comment]
Previously integrated https://pipedream.com/apps/streamtime
