### ISSUE TITLE
[APP] LionDesk

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6244]
**Name of app / service**
LionDesk

**Link to developer documentation**
https://developers.liondesk.com/docs/getting-started

**Context**
App indexed on the Project App Store sheet

**Comment by malexanderlim** [comment]
App submitted today.

**Comment by sergio-eliot-rodriguez** [comment]
App integrated - https://pipedream.com/apps/liondesk
