### ISSUE TITLE
[BUG] Cannot connect any app that uses API keys to authenticate

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6247]
Any app that uses API keys for validation, like Telegram Bot, Discord Bot, OpenAI, etc is showing me a "Verification Failed" error, even when known good key.

![image](https://user-images.githubusercontent.com/20780753/236048321-c3b7e1b2-cb61-4112-9f74-3860c9c16a44.png)
![image](https://user-images.githubusercontent.com/20780753/236048353-097c262b-aadd-4446-8197-b07419154378.png)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
