### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by tetrodotoxin7** [PipedreamHQ/pipedream#6259]
**Is there a specific app this action is for?**  Dropbox

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by vunguyenhung** [comment]
Hi @tetrodotoxin7, there's already [a ticket tracked here](https://github.com/PipedreamHQ/pipedream/issues/5990). Kindly subscribe to it for updates
