### ISSUE TITLE
[BUG] Error while building Python step that include pinecone-client 

### ISSUE THREAD

**Issue by jzumwalt** [PipedreamHQ/pipedream#6260]
**Describe the bug**
Custom python code fails to build when using the pipedream-client [package ](https://pypi.org/project/pinecone-client/).

**To Reproduce**
Create a workflow with a custom Python step
Include the following code
`# pipedream add-package pinecone-client
import pinecone
`
Run the step
Error shown at the top of the workflow

`
Error
Command failed: python3 -m pip install --target=/tmp/__pdg__/dist/python -r requirements.txt --upgrade WARNING: The directory '/home/sbx_user1051/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag. ERROR: Could not find a version that satisfies the requirement pinecone==0.1.0 (from versions: none) ERROR: No matching distribution found for pinecone==0.1.0 WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available. You should consider upgrading via the '/var/lang/bin/python3 -m pip install --upgrade pip' command.`

**Expected behavior**
The Python step can build and run using pinecone

**Comment by andrewjschuang** [comment]
@jzumwalt You should be able to `import pinecone` from now on!
