### ISSUE TITLE
[TRIGGERS] Tick Tick New Task trigger

### ISSUE THREAD

**Issue by j-ausbr** [PipedreamHQ/pipedream#6261]
**Tick Tick**

**https://ticktick.com/home**

**Is lack of support preventing you from building workflows, or do you have a workaround?** 

_yes!_

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** 

**Triggers**
New Task

**Context**
User requested originally

> _creat new tasks realated to notion, one drive, instapaper, etc_

there is already a create action: https://pipedream.com/apps/ticktick/actions/create-task
so he is very likely to be asking for triggers.

Trigger will need to be poll based, aparently: API docs https://developer.ticktick.com/docs#/openapi

**Comment by dannyroosevelt** [comment]
Hi @j-ausbr we have Ticktick integrated:
https://pipedream.com/apps/ticktick#popular-ticktick-actions

Is there something you were trying to do that's missing?

**Comment by sergio-eliot-rodriguez** [comment]
@dannyroosevelt triaging tick tick for component requests instead

**Comment by sergio-eliot-rodriguez** [comment]
@j-ausbr  there is already a Create Task action for Tick Tick: https://pipedream.com/apps/ticktick/actions/create-task

So I assume you want to be notified for New Tasks on Tick Tock so that you can start a workflow that connects to other apps.
