### ISSUE TITLE
[BUG] Workflow inspector displaying events in different order than source events

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#6262]
**Describe the bug**
Events emitted from a source don't always appear in the same order when viewed in the Workflow Inspector vs. viewed in the source's list of events.

**To Reproduce**
1. Create new source RSS - New Item in Feed
2. Create a workflow from the new source
3. Let run until a group of new feeds comes in at one time
4. Observe that the events are not always displayed in the same order

**Expected behavior**
Events listed in the workflow inspector should appear in the same order they appear to be emitted by the source.

**Additional context**
See previous [issue](https://github.com/PipedreamHQ/pipedream/issues/6068#issuecomment-1532042837) for context.

**Screenshots**
<img width="671" alt="Screenshot 2023-05-04 at 11 19 47 AM" src="https://user-images.githubusercontent.com/10889229/236258809-06d50261-ec2f-4ba5-9acd-1fcb315aab1a.png">

<img width="797" alt="Screenshot 2023-05-04 at 11 20 04 AM" src="https://user-images.githubusercontent.com/10889229/236258890-85fd17d2-12cf-400d-85f3-4df46a27d4ab.png">

**Comment by fiorins** [comment]
Hi, do you have news for this issue ?

**Comment by dannyroosevelt** [comment]
Hi @fiorins I don't have an update for you right now, but I see those events were emitted in very close succession to each other. Is this causing an issue in your workflow?

**Comment by fiorins** [comment]
@dannyroosevelt No, no issues right now, they just come out messy compared to the RSS feed events

**Comment by dylburger** [comment]
This isn't a bug. Currently, the emits may be picked up by different workers and trigger the workflow in a slightly different order when the emits happen simultaneously (like in the example). You can enforce [a concurrency of 1](https://pipedream.com/docs/workflows/concurrency-and-throttling/#managing-event-concurrency) to enforce fully-serialized execution.

**Comment by fiorins** [comment]
Sorry for the delay, but this question came to mind. If, as @dylburger says, this behavior is caused by concurrency, are the changes made in this [commit](https://github.com/PipedreamHQ/pipedream/commit/4637a2621d4ee1ea1b77492ee7147eaec409bb4e) still necessary? I mean the metadata generation and the reverse method.
