### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by nuviasmilesrepo** [PipedreamHQ/pipedream#6265]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
I'm trying to use the RingCentral trigger to detect new call recordings but the current trigger that exists forces me to select an extension when I want to detect company/account wide.  Please provide an option for all extensions or use the company based API calls.  Thanks.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by vunguyenhung** [comment]
Hi @nuviasmilesrepo, it seems like the current RingCentral API only allow Pipedream to use one extension per trigger. As a workaround, would you mind creating a new RingCentral trigger for each extension?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
