### ISSUE TITLE
Seller Cloud

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6266]
### App
Seller Cloud
https://developer.sellercloud.com/

### Triggers
- New Order (internal) Created
- Order Modified

### Actions
- Change order status
- Get order
https://developer.sellercloud.com/dev-category/order-services/

**Comment by sergio-eliot-rodriguez** [comment]
Requested API access

**Comment by sergio-eliot-rodriguez** [comment]
Seller Cloud is not integrated - https://pipedream.com/apps/sellercloud
fyi @dannyroosevelt the ChatGPT automation flagged a new issue for components https://github.com/PipedreamHQ/pipedream/issues/6561

**Comment by dannyroosevelt** [comment]
tracking her: https://github.com/PipedreamHQ/pipedream/issues/6561
