### ISSUE TITLE
[SOURCE] DataDog

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#629]
**Describe the event source. What app, what event?**
DataDog

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
Custom webhook events | Triggers on new events
New Metric Alert | Triggers when a new metric alert is created
others?

**Comment by hydrosquall** [comment]
There are many endpoints available in the Datadog API: https://docs.datadoghq.com/api/v2/using-the-api/

In addition to those you mentioned, I think these could be useful to people as outgoing (pipedream -> datadog) integrations

- Sending logs / events / traces
- Start/stopping synthetics tests
- Checking account usage

I'm not sure if we provide a way to subscribe to Datadog events from the outside, as Datadog itself has an outgoing webhook integration. Feel free to reach out if you end up wanting to have an incoming (Datadog -> Pipedream) integration too.

**Comment by jverce** [comment]
Created a new PR for new monitor events:
https://github.com/PipedreamHQ/pipedream/pull/811

As per your comment @hydrosquall, what you mentioned are actually called _actions_. As you well pointed out, these would originate in Pipedream and execute some _action_ on Datadog. I created a separate issue to track that:
https://github.com/PipedreamHQ/pipedream/issues/812
