### ISSUE TITLE
[Triggers and Action] HelloSign

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#630]
**Describe the event source. What app, what event?**
HelloSign

https://app.hellosign.com/api/documentation

### Triggers
- Custom webhook events | Triggers on new events
- Signature Request Declined | Triggers when a signature request is declined
- Signature Request Sent | Triggers when a signature request is sent
- Signature Request Signed | Triggers when a signature request is signed
- Signature Request Viewed | Triggers when a signature request is viewed

### Actions
- Send signature request from template

**Comment by jverce** [comment]
Blocked until the app is integrated (see issue #815)

**Comment by vunguyenhung** [comment]
Hello @feyzullah, I see that this ticket has been in Doing for a while. May I ask for updates on this?

**Comment by feyzullah** [comment]
Hi @vunguyenhung this one needs some more progress. I am going to finish this first

**Comment by vunguyenhung** [comment]
Noted. Thank you @feyzullah 🙏

**Comment by vunguyenhung** [comment]
Good day @feyzullah, I'm just checking in, how is the progress of this ticket?

**Comment by feyzullah** [comment]
Hi @vunguyenhung please see [this comment](https://github.com/PipedreamHQ/pipedream/issues/3649#issuecomment-1208121704). I can leave this to @vellames if he wants too. This issue has only one action more, sources are the same.

**Comment by vunguyenhung** [comment]
@feyzullah if you have made progress on this, could you create a PR and link it to the Github Issue https://github.com/PipedreamHQ/pipedream/issues/3649? It would help @vellames to speed up the progress I think. Also it would be great if you have the paid account for testing as @vellames is currently blocked by it.

**Comment by vunguyenhung** [comment]
I will close this Github issue since there's another Github issue https://github.com/PipedreamHQ/pipedream/issues/3649 that replace it 🙏

**Comment by feyzullah** [comment]
@vunguyenhung I don't have a paid account but I have some progress. I will talk to @vellames about the progress

**Comment by vunguyenhung** [comment]
Thank you so much @feyzullah!
