### ISSUE TITLE
[Components] Concord

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6304]
### App
Concord
https://www.concordnow.com/

Triggers:
1. Contract Created: Trigger when a new contract is added to the platform.
2. Contract Approved: Trigger when a contract receives approval from all parties.

Actions:
1. Create Contract: Generate a new contract using a specified template.
2. Send for Signature: Send the contract to all parties for electronic signature.
3. Update Contract Status: Modify the current status of a contract based on user-defined parameters.

_This list of suggested components was generated using ChatGPT_

**Comment by GTFalcao** [comment]
@vunguyenhung business rules might be a bit tricky on this one - I haven't found anything on the documentation about it, but when testing I was not able to update the status, nor request signature, for several agreements I tried to.

I think there's a specific flow that needs to be followed, or some other criteria that the API does not clarify, for an agreement to be eligible for these actions. If we can figure those out, we can improve the async options to list only eligible agreements.
