### ISSUE TITLE
[SOURCE] Google Forms

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#631]
**Describe the event source. What app, what event?**
Google Forms

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
Custom webhook events | Triggers on new events
New Response | Triggered when a new response row is added to the bottom of a spreadsheet.
Updated Response | Triggered when a response row is modified in a spreadsheet.

**Comment by dylburger** [comment]
See https://developers.googleblog.com/2022/03/introducing-google-forms-api.html?linkId=8046544

**Comment by lcaresia** [comment]
Blocked for now, need integrate the Google Form as a app first.

**Comment by michelle0927** [comment]
Unblocked as Google Forms is now integrated as an app.

**Comment by alysonturing** [comment]
I wasn't able to find a solution, it seems to use "Google PubSub" but I couldn't find any implementation examples or docs to build it.
https://pipedream-users.slack.com/archives/G01J50YGJGP/p1684505634369949

**Comment by michelle0927** [comment]
> I wasn't able to find a solution, it seems to use "Google PubSub" but I couldn't find any implementation examples or docs to build it. https://pipedream-users.slack.com/archives/G01J50YGJGP/p1684505634369949

@alysonturing Could some polling sources be created for Google Forms? New Form Created, New Form Submission Created?

**Comment by alysonturing** [comment]
@michelle0927 I'm going to try it. Thanks!
