### ISSUE TITLE
[APP] Salesmsg

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6316]
**Name of app / service**
Salesmsg
https://www.salesmessage.com/

**Link to developer documentation**
https://www.salesmessage.com/salesmessage-api

**Comment by malexanderlim** [comment]
Troubleshooting with Salesmsg team at the moment re: API versioning.

**Comment by sergio-eliot-rodriguez** [comment]
Live now https://pipedream.com/apps/salesmsg with some components developed
