### ISSUE TITLE
[APP] Nanonets

### ISSUE THREAD

**Issue by mytvpro** [PipedreamHQ/pipedream#6339]
**Name of app / service**
Nanonets
**Link to developer documentation**

https://nanonets.com/documentation/#

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Not sure 🤷‍♂️😂
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
We've got you! 
Check out the app at: https://pipedream.com/apps/nano-nets

**Comment by mytvpro** [comment]
Awesome!!!Thank you for your support. For fastest response please install the telegram app and connect with us by clicking the link on our website that says Telegram Support .On May 7, 2023, at 10:31 AM, sergio-eliot-rodriguez ***@***.***> wrote:﻿
We've got you!
Check out the app at: https://pipedream.com/apps/nano-nets
