### ISSUE TITLE
[APP] https://2captcha.com/

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#6340]
**Name of app / service**

https://2captcha.com/

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
2Captcha has been previously integrated https://pipedream.com/apps/twocaptcha?via=go
