### ISSUE TITLE
[APP] Obsidian

### ISSUE THREAD

**Issue by wardeiling** [PipedreamHQ/pipedream#6341]
**Name of app / service**

Obsidian

**Link to developer documentation**

https://help.obsidian.md/Home

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Yes, I have found no workaround.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Same functionality as notion (creating pages/notes, etc)

**Comment by sergio-eliot-rodriguez** [comment]
We have another request for Obsidian on #6144

Yet, they don't have an API:

> I checked the documentation available for Obsidian and I found there is only a plug ins API and themes capabilities for developers. I then reached out to their Discord forums and they confirmed atm there is no API we can use at the server side to integrate i.e. via Pipedream. When reaching out for comment about a REST, server side, this is what they said:
>  No REST API, Obsidian is a local-first application
> 
> So, I have to mark this ticket as blocked for now.
