### ISSUE TITLE
[ACTION]open hyperlink in excel

### ISSUE THREAD

**Issue by jebarajmohan** [PipedreamHQ/pipedream#6347]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by vunguyenhung** [comment]
Hi @jebarajmohan, would you mind answering the question in the description?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
