### ISSUE TITLE
[BUG] Incomplete BingX "trade-new-order.mjs" implementation. Solution only requires a few more lines of code.

### ISSUE THREAD

**Issue by zaiden96** [PipedreamHQ/pipedream#6351]
**For:** "trade-new-order.mjs" is an incomplete implementation of "Place a New Order" on BingX (https://bingx-api.github.io/docs/swap/trade-api.html#_1-place-a-new-order)

**Relevant API docs:** https://bingx-api.github.io/docs/swap/trade-api.html#_1-place-a-new-order

**Issue:** The current implementation lacks a stop loss parameter. This should only take a couple of lines of code to add:

![image](https://user-images.githubusercontent.com/108202016/236892571-2c8bd4e4-5176-4fa0-82ca-6d34925281f0.png)

**Importance:** Stop losses are extremely important in trading for risk management. Fixing this incomplete code should only require a couple of lines of code.

**Comment by vunguyenhung** [comment]
Hi, as I couldn't make an order on BingX and since the change is minimal, I will only deploy the action
<img width="683" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/d2293247-5e16-492b-b2ba-3b11d913590f">

**Comment by zaiden96** [comment]
Thank you so much for working on this implementation!

One quick question - shouldn't the values be float instead of string?

![image](https://github.com/PipedreamHQ/pipedream/assets/108202016/0351f468-7518-4620-b8a8-2e6e78aef2f6)

**Comment by lcaresia** [comment]
Hey, I will work on it!
