### ISSUE TITLE
[ACTIONS] V2 Perpetual Swap BingX Actions.

### ISSUE THREAD

**Issue by zaiden96** [PipedreamHQ/pipedream#6355]
**Name of app / service**: BingX

**Link to developer documentation**: https://bingx-api.github.io/docs/swapV2/trade-api.html#_1-trade-order

**Is lack of support preventing you from building workflows, or do you have a workaround?**: No existing workaround. Workaround could probably be feasible if there was a version of the "Generic API call" component for v2. v1 equivalent here: https://github.com/PipedreamHQ/pipedream/tree/master/components/bingx/actions/generic-api-call

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Implementation for the following "Trade Order" call would be really appreciated: https://bingx-api.github.io/docs/swapV2/trade-api.html#_1-trade-order

**Actions**
Generic API Call with the BingX V2 API
Trade Order V2

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
@zaiden96 thanks for the request!
you can either jump on to building the actions yourself, or just ignore and let Pipedream component developement tackle them, it has been added to our back log.

**Comment by zaiden96** [comment]
@dylburger and @sergio-eliot-rodriguez - Thanks for the quick replies and help! I reached out to bingX, but still haven't heard back from them which is unfortunate because I think this implementation could bring a lot of algo traders to the platform. I don't have much experience coding these kinds of programs, but happy to help in any other capacity that I can since this is a high priority for me.

**Comment by zaiden96** [comment]
@sergio-eliot-rodriguez  and @dylburger - hope you both are doing well! Reaching back out to see if there has been an update on this. 

On 10/31/23, BingX will discontinue V1 of their API, so the entire current integration of BingX for Pipedream will no longer work in 11 days. 

This requires the initial app to be updated. 

The HTTP request url and POST extension changed to the following:

<img width="1049" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/f9a6d1f2-7d78-4256-8d96-b40b4a0f1b51">

**Developer documentation:** https://bingx-api.github.io/docs/#/swapV2/trade-api.html#Trade%20order

Would it be possible to get help on implementing the following:

**Actions**
Update BingX v1 app to BingX v2 app
Trade Order ([reference](https://bingx-api.github.io/docs/#/swapV2/trade-api.html#Trade%20order))

**Comment by sergio-eliot-rodriguez** [comment]
@zaiden96 thanks for following up!
I have notified the component development team.

Trade Order is implemented on V1 as "Trade New Order": see  https://github.com/PipedreamHQ/pipedream/issues/6355

**Comment by zaiden96** [comment]
@sergio-eliot-rodriguez Thanks for notifying the component development team!

I currently use the Trade Order for V1 implementation, but that will be discontinued in 11 days. All of the current actions implemented will be discontinued in 11 days since BingX is completely discontinuing V1 of the API.
