### ISSUE TITLE
[BUG]  "Class constructor ObjectId cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by mtsvg** [PipedreamHQ/pipedream#6359]
**Describe the bug**
There is an error that occurs when trying to get a MongoDB document by ID, Update a mongoDB document by ID, or delete a document by id.
The error produced: "Class constructor ObjectId cannot be invoked without 'new'"

**To Reproduce**
1. Create any step that interacts with mongoDB using an id.
2. Test the step.
3. Receive error.

**Expected behavior**
I would expect to receive the mongodb document data.

**Screens
<img width="886" alt="Screenshot 2023-05-08 at 8 50 24 PM" src="https://user-images.githubusercontent.com/110505251/236967473-c6a98741-3d57-423d-84df-6cadc6a3483f.png">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [ safari]

**Comment by vunguyenhung** [comment]
Hi @mtsvg, thanks for raising this. I can reproduce this issue, I will add this to Pipedream prioritized backlog
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/f2d5d984-a816-4a6c-a111-e6f4cab556ec)
