### ISSUE TITLE
[SOURCE] Snowflake

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#636]
**Describe the event source. What app, what event?**
Snowflake

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
New Row | Triggers when a new row is added in a table in Snowflake (i.e., query snowflake and emit results as a single event or each row as an individual event).

**Comment by dylburger** [comment]
Additionally, I'd like a source that accepts a SQL query, runs on a schedule, and emits the results of the query. For this source, I'd like the option to emit the results as a single event, or as individual records, similar to https://github.com/PipedreamHQ/pipedream/blob/master/components/pipedream/sources/new-records-from-sql-query/sql.js
