### ISSUE TITLE
[BUG] Sentry configuration

### ISSUE THREAD

**Issue by EliBates** [PipedreamHQ/pipedream#6364]
**Describe the bug**
Unable to receive sentry events, it looks like there are some errors coming when I try to configure it. Any ideas?

**To Reproduce**
1. Add sentry as a trigger with API token
2. View the workflow details

**Expected behavior**
Sentry integration should work as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/3781935/237053780-d6b7ccda-207a-48ae-beae-58a17ad32eaa.png)

![image](https://user-images.githubusercontent.com/3781935/237053637-45ea65e3-ee54-4097-a226-33745ade7451.png)

**Comment by vunguyenhung** [comment]
Hi @EliBates, I can create the resource fine on my side
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/21b0866b-4fd7-4f7e-b1cd-b757e88cba70)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/78ba86f2-8e5f-4899-a8c9-37691f06a0d8)

Would you mind confirm that you have added all necessary permission to [your Sentry Auth token](https://no-y2n.sentry.io/settings/account/api/auth-tokens/)?
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/70f304dc-934b-4abf-8576-eb735053e58a)

**Comment by vunguyenhung** [comment]
Hi @vellames, as you have context about Sentry, would you mind checking this case?

**Comment by EliBates** [comment]
@vunguyenhung I didn't touch anything and it randomly started working today....
<img width="459" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/3781935/374d9c4e-43de-493a-a70c-663d31c7aee6">

Issue is resolved for me but there might be something intermittent that happens.

**Comment by vellames** [comment]
Sure. I will put this in my queue

**Comment by vellames** [comment]
> Hi @vellames, as you have context about Sentry, would you mind checking this case?

Sure, I will put this in my queue

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
