### ISSUE TITLE
Certain .m4a audio files error out for OpenAI create_transcription action

### ISSUE THREAD

**Issue by sshickles** [PipedreamHQ/pipedream#6368]
While trying to use the OpenAI create_transcription action certain .m4a files error out.

```
Error
Command failed: cp /tmp/Test Audio.m4a /tmp/chunks/chunk-000.m4a cp: target '/tmp/chunks/chunk-000.m4a' is not a directory
```
<img width="723" alt="CleanShot 2023-05-09 at 10 57 19@2x" src="https://github.com/PipedreamHQ/pipedream/assets/51331451/fa8019e2-5764-4a9a-80a0-408f633fa2d5">

<img width="763" alt="CleanShot 2023-05-09 at 10 57 40@2x" src="https://github.com/PipedreamHQ/pipedream/assets/51331451/a7093d96-3b42-4f6e-aec2-d9a8da44d476">

I created the same audio file in .wav format and I did not have the same issue. I tried several other .m4a files and had the same issue so it seems it happens more frequently with .m4a files in general. I haven't had any issues with .wav files.

Here is the Test Audio.m4a file used in this test.
https://www.dropbox.com/s/9ue2p0s7saulee9/Test%20Audio.m4a?dl=0

**Comment by vunguyenhung** [comment]
Hi, I confirmed that the fix works for the tested file
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/2945459d-5830-4344-b21a-7c041ce0b6b0)
