### ISSUE TITLE
[FEATURE] Active Workflows Folder

### ISSUE THREAD

**Issue by delasous** [PipedreamHQ/pipedream#637]
**Is your feature request related to a problem? Please describe.**
I have workflows for several different projects. Currently, when I navigate to /workflows, I am greeted with a list of Active items. This list is growing longer, and it is becoming more difficult to quickly identify workflows from related projects.

**Describe the solution you'd like**
I would like to be able to organise my active workflows into custom folders based on the project they are involved with.

**Do you have a workaround?**
My workflows follow the naming convention - Project: Workflow Name (Input/Trigger App > Output App)

**Comment by dylburger** [comment]
@delasous thank you for the request, I totally hear you. We're tracking this request in #203 , so if you don't mind I'm going to close this and link to this issue from that one, so we make sure to incorporate your feedback when we work on the feature.
