### ISSUE TITLE
[ACTION] Mercury - Current Balance

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#6371]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

This action should retrieve the current balance of the selected account and emit the amount to subscribing workflows.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

The Accounts Detail endpoint should do the trick. The `availabileBalance` and `currentBalance` should be included at minimum, also the `name` and `accountNumber`

https://docs.mercury.com/reference/accountsid

**Comment by dannyroosevelt** [comment]
@ctrlaltdylan shouldn't this be an action instead of a trigger? And a workflow could use a schedule trigger to get the current balance at some regular interval?

**Comment by dannyroosevelt** [comment]
Yea, since we aren't only emitting on new events, we should be this as an action.
