### ISSUE TITLE
[BUG]  PostgreSQL app does not honor "Reject Unauthorized" prop when set to false

### ISSUE THREAD

**Issue by doron580** [PipedreamHQ/pipedream#6375]
**Describe the bug**

**To Reproduce**
I’m using PostgreSQL and trying to connect to my DB but Pipedream rejected it because of the SSL although I chose here false

My DB is opened to any IP.

![image](https://github.com/PipedreamHQ/pipedream/assets/54786493/c5aabf5c-1ae5-4f89-95e0-58c2076bec3f)

**Comment by vunguyenhung** [comment]
Hi @doron580, may I ask what is the ssl settings in your postgres db? Is it possible for you to enable ssl?

**Comment by doron580** [comment]
Hi,
I should have download it but I also tried that.
My DB is hosted by DigitalOcean if it helps.
![image](https://github.com/PipedreamHQ/pipedream/assets/54786493/aef871a5-399b-4f22-b833-6d6c55e620b3)

**Comment by vunguyenhung** [comment]
Oh I think Digital Ocean requires a custom CA certificate for SSL connection. 

Hello @michelle0927, as you are familiar with Postgres action, would you mind advising this case?

**Comment by michelle0927** [comment]
Hi @doron580 Does the database meet the following conditions, and are you 100% sure the account settings are entered correctly in Pipedream?
<img width="593" alt="Screenshot 2023-05-11 at 11 59 35 AM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/ce91be9f-4415-4812-8687-2e3543aa4a26">

**Comment by doron580** [comment]
Hi,
I got it worked with a Node.js step.
I uploaded the certificate to the scenario settings and wrote a few lines.

Thanks.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
