### ISSUE TITLE
[BUG] Deployed workflow shows No Trigger Configured

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6377]
My deployed workflow shows No Trigger Configured in Inspect mode, but is there in Build mode.

Also, if I attempt to edit from a trace, the console throws an error

![Screenshot 2023-05-09 at 2 05 50 PM](https://github.com/PipedreamHQ/pipedream/assets/20780753/7d61d6e7-92b9-45be-af67-63d92a263dee)
![Screenshot 2023-05-09 at 2 06 51 PM](https://github.com/PipedreamHQ/pipedream/assets/20780753/10ac85bf-2d41-43be-9e0b-cef61127c1d9)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
