### ISSUE TITLE
[APP] Abstract IP geolocation API

### ISSUE THREAD

**Issue by karmadele** [PipedreamHQ/pipedream#638]
**Abstract IP geolocation API**

https://www.abstractapi.com/ip-geolocation-api#docs

**Comment by todsac** [comment]
This API has been integrated.  Here is a working example - https://pipedream.com/@tod/abstract-geo-ip-api-example-p_brCVAJ

Please let us know if other Abstract APIs would be of interest.  We should be able to add them quickly.
