### ISSUE TITLE
[BUG] No module name 'smartsheet' even with Magic Comment

### ISSUE THREAD

**Issue by Tricky6972** [PipedreamHQ/pipedream#6385]
I am experiencing an issue importing the smartsheet python module. This issue is similar to an issue that was closed before.              

Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

_Originally posted by @dylburger in https://github.com/PipedreamHQ/pipedream/issues/5712#issuecomment-1478724147_

```
#pipedream add-package smartsheet-python-sdk
import smartsheet

def handler(pd: "pipedream"):
    # Reference data from previous steps
    print(pd.steps["trigger"]["context"]["id"])
    # Return data for use in future steps
    return {"foo": {"test": True}}
```

from https://pypi.org/project/smartsheet-python-sdk/

![bad py2](https://user-images.githubusercontent.com/132513337/237258840-15cb23c3-beb6-44ae-ab5f-3c830d7013d0.JPG)

**Comment by Tricky6972** [comment]
Thank you for the lightning fast response! Unfortunately, I am still running into unexpected issues when attempting to import the smartsheet module. I can import telegram with no issues, but there smartsheet still fails.

![bad py3](https://github.com/PipedreamHQ/pipedream/assets/132513337/718f60ed-2437-43de-b455-9b0f055382da)

**Comment by Tricky6972** [comment]
Thank you for the lightning fast response! Unfortunately, I am still running into unexpected issues when attempting to import the smartsheet module. I can import telegram with no issues, but there smartsheet still fails.

![bad py3](https://github.com/PipedreamHQ/pipedream/assets/132513337/2330cbbd-13b8-44c5-967d-f6462ed0c15c)

**Comment by vunguyenhung** [comment]
Hi @Tricky6972, the Pipedream team will add the smartsheet package to  the magic package list then close this ticket. After that, you should be able to test it again

**Comment by Tricky6972** [comment]
@vunguyenhung Ah, okay. I misinterpreted the progress. Sorry about that. Thank you for your help.

**Comment by andrewjschuang** [comment]
@Tricky6972 You should be able to `import smartsheet` from now on!

**Comment by Tricky6972** [comment]
It does work! fantastic! thanks for your hard work!
