### ISSUE TITLE
[BUG] mySQL New or Updated Row is not emitting events when a row updates

### ISSUE THREAD

**Issue by Jooeee** [PipedreamHQ/pipedream#6388]
**Describe the bug**
When a row is changed/updated in mySQL the New or Updated Row trigger is not emitting an event. If a row has never been changed before it sometimes emits an event for that particular row but never again. 

The logs show that it returns the latest timestamp when a column changes but it doesn’t trigger an event from this.

**To Reproduce**
1. Create a trigger for New or Updated Row 
2. Change a row in mySQL
3. Nothing will trigger (sometimes triggers if never been changed)

**Expected behavior**
An event should be triggered.

**Screenshots**

![pipedream log](https://github.com/PipedreamHQ/pipedream/assets/8149772/f312de33-a9c9-40d0-b5b3-507087349a76)
![pipedream event](https://github.com/PipedreamHQ/pipedream/assets/8149772/f101f708-453e-476a-8009-ad38cbaf7d68)

**Comment by vunguyenhung** [comment]
Hi @Jooeee, I couldn't seem to reproduce your issue, as my source emits event correctly
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/64238e8f-b721-4576-a872-7a54a7369efa)

The source detects changes by the column you have set on the `Order By` prop (.e.g `last_modified_time`), so it will emit event whenever there's a row that having the `last_modified_time` value larger than the latest value that the source stored. So would you mind confirm that when you updated the row on your side, you changed you `last_modified_time` column with the current time?

**Comment by Jooeee** [comment]
Hi @vunguyenhung,

The last_modified_time column updates automatically in the database when any change to the row is made. I've checked this and it updates every time in the database fine. 

Here are the logs of me making continued changes:
![Screenshot 2023-05-11 at 08 54 58 (2)](https://github.com/PipedreamHQ/pipedream/assets/8149772/221bffde-2e12-453a-8447-c305263d77b2)

As you can see from the events the only one of those that actually emitted a new event was the row that I had never changed before at 08:53:
![Screenshot 2023-05-11 at 08 55 30 (2)](https://github.com/PipedreamHQ/pipedream/assets/8149772/debde53f-5df9-4888-882f-5c05d8c4e433)

**Comment by Jooeee** [comment]
In the configuration there is a workaround for this issue: https://github.com/PipedreamHQ/pipedream/issues/1842 which mentions that events won't get emitted after a while. I wonder if it could have something to do with that?

**Comment by dylburger** [comment]
Thanks for the reports y'all. I've added this to the backlog to see if there's a subtle issue our team can help with.

**Comment by Jooeee** [comment]
Hi @vunguyenhung, I've tested the fix and it works without fail every time for both updated rows and new rows. Thanks for everybody's help.
