### ISSUE TITLE
[BUG] Custom date time format does not work in date_time_format

### ISSUE THREAD

**Issue by nickidw** [PipedreamHQ/pipedream#6399]
**Describe the bug**
You cannot enter your own Output format when using the predefined date_time_format action

**To Reproduce**
1. Go to Output Format of the date_time_format component
2. Click on Enter a custom expression
3. Enter HH:mm 
4. Click on Test
5. Observe the error

**Expected behavior**
I would expect the custom expression to be able to contain any valid date format string, not just the predefined ones

**Screenshots**
![image](https://github.com/PipedreamHQ/pipedream/assets/12016514/ddc8feaf-1bae-40af-a4a6-f5fcae262ec6)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] v1.51.114 

**Additional context**

I would like to use HH:mm, since in my case I only need the time portion, but being able to use any valid date time format string would be great.

**Comment by GTFalcao** [comment]
Hey @nickidw , thanks for your report and suggestion!

I've added the format you requested (to all date/time related components under the `formatting` app), and also added error catching to present a more descriptive error message for a few cases, including the one you experienced. I'll be linking this fix to this issue.

I agree it'd be great to allow a custom format to be specified, besides all the formats already listed. I think that can be worked on as a follow-up addition, requiring some further thought on the format itself - as there are many different date/time "pieces" that could be combined, while some are mutually exclusive amongst them, and parsing the custom format needs to account for all of this - and how this can be described for users in the options prop.
