### ISSUE TITLE
[APP] [COMPONENTS] Vestaboard app integration, New Vestaboard sources and actions

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#6402]
**Name of app / service**

Vestaboard

**Link to developer documentation**

https://docs.vestaboard.com/concepts

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I could possibly use webhook, but a native app in Pipedream would be better to handle authentication.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Actions:
* Display message
* Read message

Triggers:
* Message changed

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
hi @johndbritton thanks for the request!

we'll look into the app integration shortly, as of components, you can ignore message from Dylan (it's automated) for now. Pipedream components development would start once the app is integrated.

**Comment by malexanderlim** [comment]
Hi @johndbritton ! We've built a basic integration with Vestaboard (https://pipedream.com/apps/vestaboard). As Dylan mentioned, you're welcome to get started with developing some actions if you'd like, otherwise our component developers will get to building shortly.

Are there any particular triggers and actions that you are looking for in particular?

**Comment by johndbritton** [comment]
The actions would be read the board and write the board.

Events would be board changed.

It would be really helpful if the integration supported converting from standard characters to the encoding required by the board and also if there were some kind of auto layout for a string on the board matrix.

These would make it extra convenient to send messages from Pipedream without needing to know the specifics of the board dimensions or character encodings.
