### ISSUE TITLE
reflect.app

### ISSUE THREAD

**Issue by jackdempsey** [PipedreamHQ/pipedream#6405]
reflect.app

https://openpm.ai/apis/reflect

I could use zapier instead but much prefer not to. Once the app is added as a partner I think I could help build out some actions & triggers.

Zapier supports a couple: new book added, new link added, new note created, new tag added, would all be a great start :-)

**Comment by sergio-eliot-rodriguez** [comment]
Requested Oauth credentials by email, as especified on their roadmap for[ API feature](https://roadmap.reflect.app/feature-requests/p/rest-api)
copied sergio@pk and integrations@pd

**Comment by jackdempsey** [comment]
Ty! Isn't more than API access needed to integrate? e.g. when someone creates a new link inside their graph, their API won't publish an event / trigger a webhook? Or does Pipedream do something like polling the https://openpm.ai/apis/reflect#/graphs/{graphId}/links endpoint and handle the triggering of an action for us when it detects a new link?

I've been assuming there is some private/internal process to get an app integrated but if you're basically just integrating with public APIs, that's great….do you have access to machinery to handle this that the public does not, hence the need for you to handle this?

**Comment by sergio-eliot-rodriguez** [comment]
Yes it's done through public APIs.
There's a form where you submit the API config that will be able to reuse by Pipedream users.
However this is in closed alpha.

Some sources are done via webhooks, if there is an API to programmatically add/delete webhooks on behalf of the users.
If not it's done by API polling.

Finally, if the API supports OAuth authentication, then for security and for easyness to the user, we use OAuth. In certain cases, the OAuth flow is a Bring Your Own OAuth which is also supported, but the user has to disclose their client id and secret.

In certain cases, there is some internal process if the other company requires contract signing, documentation and so on. But all integrations are done via APIs.

**Comment by jackdempsey** [comment]
Thanks! That's great to know and exciting to see this may already be in QA?!

**Comment by jackdempsey** [comment]
Amazing. I will take a look and see about working with the Reflect team to get a couple more capabilities added to the API.

Thanks for the excellent communication and support here!
