### ISSUE TITLE
[Components] Axonaut

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6418]
### App
Axonaut
https://axonaut.com/

Actions:
1. Create Company
2. Create Employee
3. Update Company
4. Update Employee

_This list of suggested components was generated using ChatGPT_ and updated by @lcaresia

**Comment by HeegeeCare** [comment]
I'm interested into this, the full list of API endpoints is there:
https://axonaut.com/api/v2/doc

The most important endpoints/actions to support are:
- **Companies**
- **Employees**
- _Opportunities_

The rest is less important.

Also, for Companies and Employees, it would be good to have 3 distinct actions:
- Create
- Update 
- Upsert (ability to specify how to identify an existing entity, and update it if it already exists)

**Comment by HeegeeCare** [comment]
There is an additional endpoint that isn't documented in Swagger, `POST /api/v2/private/company-and-employee` (it's the endpoint used by Zapier)

Here is an example of payload:
![image](https://github.com/PipedreamHQ/pipedream/assets/136838662/369d75c3-5f50-4339-bc26-e5fa0df24b9a)
