### ISSUE TITLE
[TRIGGER] LinkedIn New Event Registration Form Reponse trigger

### ISSUE THREAD

**Issue by luca-estek** [PipedreamHQ/pipedream#6427]
**LinkedIn**

**[Link to developer documentation] : https://developer.linkedin.com/ **

**The only workaround is to use Zapier!**

**New Event Registration Form Response**

**Comment by sergio-eliot-rodriguez** [comment]
hi @luca-estek 
linked in is https://pipedream.com/apps/linkedin

i'll look about triaging the trigger you are requesting

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
Likely a source by api polling 
there are webhooks but not a way to programmatically add them to a user

https://learn.microsoft.com/en-us/linkedin/shared/api-guide/webhook-validation?context=linkedin%2Fcontext
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/events?view=li-lms-2023-04&tabs=http
https://www.linkedin.com/help/lms/answer/a550232
