### ISSUE TITLE
Tag workflow with custom metadata

### ISSUE THREAD

**Issue by SkylineDev2** [PipedreamHQ/pipedream#6443]
**Is your feature request related to a problem? Please describe.**
I want to assign some tags to the workflow, it is easy to spot, sort, and filter. 

**Describe the solution you'd like**
For example, there are workflows we connect with our different destination environments. Like DEV, QA, PROD. In Workflows view, it is easy to spot on workflow name & some nice icons about steps (source icon, step icon), it will be nice to allow me to see tags for destination icon which is our App + Env. 

**Do you have a workaround?**
Yes, we either have to add "DEV/PROD" within the workflow name or builder has to open the workflow to check configuration.

**Comparable features in other tools?**
not sure. 

**Additional context**
The goal is to quickly know whether this workflow is connecting with our Dev env or Prod env at certain point during workflow development lifecycle. This make change management easier to follow. So, that is why Tag Idea was introduced to solve the problem I need right now. But, I think tag feature can be multi-use for other cases as well.

**Comment by vunguyenhung** [comment]
Hi @SkylineDev2, there's an existing ticket to track it here: https://github.com/PipedreamHQ/pipedream/issues/203. The feature should be out soon! Kindly subscribe to the ticket to be noticed when it landed! 

Now I will close the ticket due to duplication. Thank you.
