### ISSUE TITLE
[Components] Happy Scribe

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6451]
### App
Happy Scribe
https://www.happyscribe.com/

Triggers:
1. Transcription Completed: A transcription has finished processing and is ready to be accessed.
2.  ~New Submission: A user has submitted a new audio or video file for transcription.~

Actions:
1. ~Submit File: Upload and submit an audio or video file for transcription.~
2. Retrieve Transcription: Fetch the completed transcription in a desired format (e.g., JSON, SRT, or VTT).
3. Delete Transcription: Remove a specific transcription from the user's account.

_This list of suggested components was generated using ChatGPT_

**Comment by lcaresia** [comment]
Dont have endpoint to do `New Submission: A user has submitted a new audio or video file for transcription.`
