### ISSUE TITLE
[APP] qonto

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6454]
**Name of app / service**
https://qonto.com/en

**Link to developer documentation**
https://api-doc.qonto.com/
OAuth docs: https://api-doc.qonto.com/docs/business-api/ZG9jOjg0MjE3NzE-introduction

**Notes on Outrech**
Haven't reached out yet.  Need to [register OAuth](https://getqonto.atlassian.net/servicedesk/customer/portal/5/group/47) application in this portal.

**Notes on details required**
They require to send Legal Company Name, the Redirect URI upfront, and whether or not having a PSD2 license, the business decision of whether or not allow Payment initiation on behalf* and select upfront the OAuth scopes required.
I checked Zapier and apparently the ones they need are internal transfer, transfer request, request review, attachment write.

Furthermore, to become a partner it's needed to create an account, creating accounts from US not available yet. Currently France, Germany and other European countries supported.

**Comment by sergio-eliot-rodriguez** [comment]
Closed in favor of https://github.com/PipedreamHQ/pipedream/issues/7376

which is an app request by user

**Comment by Vadorequest** [comment]
@sergio-eliot-rodriguez Thanks, I believe your forgot to close this one though.
