### ISSUE TITLE
[Components] Salesmsg

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6462]
### App
Salesmsg
https://www.salesmessage.com/

[API Documentation](https://app.salesmessage.com/api/docs?utm_content=-&utm_source=salesmsg&__hstc=81098645.88a3a63fbcaa46e960f8826d4636f1b0.1683913697472.1684176788694.1684181265234.6&__hssc=81098645.2.1684181265234&__hsfp=1223513178&_ga=2.13182910.822292956.1684173928-309507494.1683913628#/)

Triggers:
1. Message Received: Trigger when a new message is received.
2. Contact Created: Trigger when a new contact is added.

Actions:
1. Get Conversations: Get a user's conversations. 
2. Search Conversations: Search active conversations.
3. Create a new contact

**Comment by malexanderlim** [comment]
Account credentials have been added to the vault.
