### ISSUE TITLE
[ACTION] Update Database Item in Notion

### ISSUE THREAD

**Issue by bracalea** [PipedreamHQ/pipedream#6478]
Notion. I'd like this action: 

Update Database Item in Notion

**Comment by vunguyenhung** [comment]
Hi @bracalea, Pipedream currently offer Update Page and Append Block to Parent action to update your page
<img width="912" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/539e111e-f645-4d41-82a8-bd38d42fa998">

Would you mind giving them a try?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
