### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by HalfmoonFestival** [PipedreamHQ/pipedream#6481]
**Name of app / service** Event Pop

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @HalfmoonFestival 

thanks for using Pipedream.com public repository.

Could you please let us know what you are trying to do?
Did you want to request for an app to be integrated on our App Store? https://pipedream.com/explore

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
