### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by YasminOliveira23** [PipedreamHQ/pipedream#6482]
**Microsoft Excel*

**https://learn.microsoft.com/en-us/office/client-developer/excel/excel-home**

**I have a workaround with Google Sheets, but we use excel to generate dashboards in PowerBI**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @YasminOliveira23 

Thanks for the request.

We are tracking Excel integration at https://github.com/PipedreamHQ/pipedream/issues/5379
Feel free to subscribe there for updates on the integration.
