### ISSUE TITLE
[FEATURE] Automatically split long text posted using the Mastodon step into multiple messages and post them as a thread

### ISSUE THREAD

**Issue by stefanbohacek** [PipedreamHQ/pipedream#6488]
**Is your feature request related to a problem? Please describe.**
Posting  a message using the Mastodon step will fail if the text is too long.

**Describe the solution you'd like**
I would like Pipedream to automatically split long messages and post them in a thread.

**Do you have a workaround?**
The workarounds are:

- shorten the message to fit within the limit
- split the text into multiple messages and use a code step to post them via the API

**Comparable features in other tools?**
n/a

**Additional context**

Here's a screenshot of the error:

![A screenshot from Pipedream showing a long Lorem Ipsum placeholder text causing an error when being posted on Mastodon:Validation failed: Text character limit of 500 exceeded.](https://github.com/PipedreamHQ/pipedream/assets/3909390/667a8ee7-daa3-4134-801c-89e76f6001f0)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by vunguyenhung** [comment]
Hi, I think this makes sense. Though I think it makes more sense to either:
- Add a Boolean Prop "Split to multiple messages"
- Improve the description of the status: "The text content of the status. If the message is longer than 500 characters, it will be split and posted to subsequence threads"

So that the user will aware of this behavior

**Comment by stefanbohacek** [comment]
@vunguyenhung I think having a "Split long messages into multiple messages" option that's checked by default would be a good idea. It would also need an explanation of what happens if you uncheck this and the message is too long to post.

**Comment by vunguyenhung** [comment]
> It would also need an explanation of what happens if you uncheck this and the message is too long to post.

Yeah, thanks for noticing this @stefanbohacek. In this case the action should just fail as per the current behavior

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by stefanbohacek** [comment]
Awesome, thank you!

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Mastodon_6488_1302.pdf](https://github.com/PipedreamHQ/pipedream/files/11649153/Mastodon_6488_1302.pdf)

**Comment by alysonturing** [comment]
@vunguyenhung  fixed the issue pointed, and also, added a new action `post-multiple-statuses` so the customer can use his own method of split the status and pass several statuses as parameter, this will empower the customer to break the status when it's best to keep the text with best  readability possible.

**Comment by stefanbohacek** [comment]
Nice, really cool to see the update live. Thanks everyone!

![A screenshot from Pipedream.com showing the new "Split to multiple messages" option for the Mastodon step.](https://github.com/PipedreamHQ/pipedream/assets/3909390/039cf07b-d0b8-4e73-8822-dbd9eea8ae0e)

**Comment by alysonturing** [comment]
@stefanbohacek I'm wondering if you want that the subsequent status are placed as replies of the main (first one) status.

**Comment by stefanbohacek** [comment]
Yes, I think that would make the most sense.

**Comment by alysonturing** [comment]
@stefanbohacek alright, I'm working on that now, I'll open a new issue so you can track it.
