### ISSUE TITLE
[SOURCE] Unfollow source for twitter.

### ISSUE THREAD

**Issue by DAVE4547** [PipedreamHQ/pipedream#649]
**Describe the event source. What app, what event?**
A source for when you or another user looses a follower on twitter.
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
You probably already have this but this is it: https://developer.twitter.com/en/docs

**Comment by jverce** [comment]
A couple of event sources have been pushed to `master` to address this. Their structure is similar to the existing `new-follower-of-me` and `new-follower-of-user` event sources.

A few considerations:
- Twitter does not have an API to retrieve recent unfollows, so the way to compute this is to keep track of the whole list of followers at different points in time, and compute the difference.
- This will put extra pressure on the API limits, especially for accounts with a high amount of followers. Hence, the timer configuration should be set such that it doesn't go above a ratio of **5000 followers / min**.
- For example, if an account has 15000 followers, the event source should be triggered with a frequency of at most 3 minutes. A  shorter time will result in Twitter throttling the event source.
