### ISSUE TITLE
[APP] Caspio Cloud Database

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6493]
**Name of app / service**
Caspio Cloud Database
https://www.caspio.com/

**Link to developer documentation**
https://howto.caspio.com/web-services-api/web-services-api/
https://c1hbx715.caspio.com/rest/swagger (requires login

**notes on oauth**
uses the oauth 2.0 client credentials flow

**Comment by malexanderlim** [comment]
Basic integration complete.
