### ISSUE TITLE
Consider sanity limits on result displays

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#65]
**Is your feature request related to a problem? Please describe.**
I've got a step that returns an array of 90+ entries. When looking at in Pipedream, I get a *very* long list of results:

![image](https://user-images.githubusercontent.com/393660/82377677-a8676700-99e9-11ea-975b-7acbc169d726.png)

While it's helpful to have all the data for debugging, in cases where the data is large, I wish the UI would lazy load post a certain limit. I've also seen my browser "chug" a bit sometimes with this workflow due to the size.

**Describe the solution you'd like**
Look at how Chrome DevTools will filter out large data sets and let you click to expand. I think that's well done.

**Do you have a workaround?**
Nope, I live with it. ;)

**Comparable features in other tools?**
See Chrome DevTools.

**Comment by dylburger** [comment]
@cfjedimaster one of our engineers just shipped something that should help here. We'll list 10 items at a time:

<img width="314" alt="Screen Shot 2020-06-18 at 8 33 19 PM" src="https://user-images.githubusercontent.com/242668/85094243-30848c00-b1a3-11ea-88a3-50a8ea5a3548.png">

Let me know if this works for you.

**Comment by cfjedimaster** [comment]
Looks good to me. Tested it on one of my workflows and it worked great.

**Comment by dylburger** [comment]
@cfjedimaster thanks for confirming! Closing
