### ISSUE TITLE
[BUG] BingX "Trade New Order" action implementation error & Proposed Solution (Delete characters from 2 lines)

### ISSUE THREAD

**Issue by zaiden96** [PipedreamHQ/pipedream#6503]
**Describe the bug**
Error in "Stop Loss" and "Take Profit" implementation of BingX "Trade New Order" action located here: https://github.com/PipedreamHQ/pipedream/blob/master/components/bingx/actions/trade-new-order/trade-new-order.mjs

**Screenshots**
<img width="443" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/566c5928-639b-4279-9ad3-5584837ee58e">

**Suggested Solution**
Remove ".replace(",", ".")" from lines 65 and 69 from the file "trade-new-order.mjs" located here: https://github.com/PipedreamHQ/pipedream/blob/master/components/bingx/actions/trade-new-order/trade-new-order.mjs

This should resolve the error because the input for "Stop Loss" and "Take Profit" is the same format as "entrustPrice" and "entrustVolume".

<img width="512" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/366b9e31-aecb-4e9c-84a4-af0d9d3c29d7">

**Comment by alysonturing** [comment]
@zaiden96 after some testing, I noted that you're getting this error because the action is relying in receiving the `prop as string` but it seems that you're sending it as number/float (maybe passing the parameter from a previous action), this is the cause for the error `replace is not a function`

I'm changing this action to work with both, number and string, and it should soon be working for you.

**Comment by zaiden96** [comment]
@alysonturing - thank you so much for the help!

The workflow executed successfully but no trade was placed due to the error "msg: signature not match". I verified my api and secret key. Does something in the imported file "bingx.app.mjs" file need to be updated? Thanks!

<img width="626" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/4c58f1e1-c06a-4530-88c3-07f47ec64109">

**Comment by alysonturing** [comment]
@zaiden96 hello, I'm not sure, I'll investigate it, but it's perhaps another bug? if so.. I suggest opening a new issue, so we can handle it properly!
