### ISSUE TITLE
[BUG] Slack New Interaction Events - does not emitting event

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6511]
**Describe the bug**
I created a new Slack Interaction Events source.
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/80ffa176-1233-497b-a66c-19c6861d22a9)

Then using Pipedream Slack Send Message using Block Kit, I send a Block Kit message to a channel
<img width="906" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/9b8fbf85-39f9-4a32-9b04-231763146328">

I clicked the button in the message multiple times, though there's no event emitted in the Slack Interaction Events source.
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/80ffa176-1233-497b-a66c-19c6861d22a9)

**Expected behavior**
When I clicked a button on the interactive message, I should receive an event on the Slack Interaction Events source.

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1684226260227279

**Comment by lcaresia** [comment]
@vunguyenhung I can't reproduce the problem, can you share more details about your configs?

![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/55a0a223-a0f3-4f5a-9810-16130752762a)
![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/4749489e-fd47-4712-907e-cd3884656e91)

**Comment by vunguyenhung** [comment]
Hi @lcaresia, this ticket is invalid now, as Pipedream team has fixed the issue. Thank you so much for checking this
