### ISSUE TITLE
[BUG] Newly created triggers for Slack, Discord, Zoom, Dropbox are not emitting

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6513]
Existing triggers for those apps are working fine, and new triggers for other apps are healthy, this should only be impacting newly created triggers from apphooks.

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by dannyroosevelt** [comment]
This is now resolved, but any triggers for these specific apps that were created during this outage will not recover, and will need to be recreated.

Starting approximately 12:16 PDT 5/15 until 12:00 pm PDT 5/16.
