### ISSUE TITLE
[IMPROVEMENT] Twitter Connection Popup has incorrect naming for API Key and API Secret

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6524]
**Is your feature request related to a problem? Please describe.**
Twitter Connection Popup has incorrect naming for API Key and API Secret. Pipedream requires the API Key and API Secret
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/90936df2-cb2c-40a3-9d2d-eff3d6c09a42)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/e7b2d958-b4d1-41b2-afdd-912b0f4afac7)

Though the Pipedream Twitter connection popup shows the input as `developer_consumer_key` and `developer_consumer_secret`
<img width="654" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/c70e8e1f-e82b-44e0-9faa-d3b5ebdf4183">

**Describe the solution you'd like**
Update the inputs to `api_key` and `api_key_secret`

**Comment by malexanderlim** [comment]
Hey @vunguyenhung , it will require some code changes and additional coordination to change the inputs to `api_key` and `api_key_secret`. In the interim, I've provided clearer instructions in both connection instructions and on the marketplace page via https://github.com/PipedreamHQ/pipedream/pull/6534.

Let me know if you think this updated language (with your screenshot too, thanks!) makes sense to you.
<img width="799" alt="Screenshot 2023-05-17 at 4 25 37 PM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/4f5506dc-edb7-4c5b-ab58-be375909f750">

**Comment by vunguyenhung** [comment]
Thanks @malexanderlim, I think this improvement is good enough for now! Let's have the improvement of the inputs later

**Comment by malexanderlim** [comment]
Great! Thanks Leo, closing this one for now.
