### ISSUE TITLE
Python data_store to support .set

### ISSUE THREAD

**Issue by Swieter** [PipedreamHQ/pipedream#6528]
I'm using Python code blocks and I'm using data stores.

In my code I have the following, just like example code.
data_store = pd.inputs["data_store"]

I'd like to programmatically set the key/value.
So I'd like to do the following:
```
announced_key = f"announced_{email}"
data_store.set(announced_key, arrow.now().date().isoformat())
```

However I get:
AttributeError
'Store' object has no attribute 'set'

So, for now I'm doing this:
```
announced_key = f"announced_{email}"
data_store.__setitem__(announced_key, arrow.now().date().isoformat())
```

Seems a little hackish so I think adding a .set would be a good capability.

**Comment by vunguyenhung** [comment]
Hi @Swieter, in Pipedream [official Python data store doc here](https://pipedream.com/docs/code/python/using-data-stores/#saving-data), you can just save data within a Data Store is just like setting a property on a dictionary:
```
from datetime import datetime

def handler(pd: "pipedream"):
    # Access the data store under the pd.inputs
    data_store = pd.inputs["data_store"]

    # Store a timestamp
    data_store["last_ran_at"] = datetime.now().isoformat()
```

So your code might just be:
```
data_store[announced_key] = arrow.now().date().isoformat()
```

**Comment by Swieter** [comment]
Thank you @vunguyenhung, you are right.  Why was I blind to simple doing data_store[annnounced_key]?  Thank you for being kind and showing me the path.
