### ISSUE TITLE
[APP] Inoreader

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6532]
**Name of app / service**
Inoreader
https://www.inoreader.com/

**notes on outreach**
on their [contact form](https://www.inoreader.com/contact), requested oauth accesss, copied integrations at pd

**Comment by tatelax** [comment]
+1

**Comment by malexanderlim** [comment]
Hi @tatelax, we've built out a basic integration to Inoreader, and we will now be building out triggers and actions. To help ensure that your use case is covered -- can you please share which triggers and actions would be most valuable for your workflows?

**Comment by tatelax** [comment]
> Hi @tatelax, we've built out a basic integration to Inoreader, and we will now be building out triggers and actions. To help ensure that your use case is covered -- can you please share which triggers and actions would be most valuable for your workflows?

Hi. Thanks for this.

What I'm trying to accomplish is that when a new article is added to a folder in Inoreader, I can then use ChatGPT to generate a summary of the article.
