### ISSUE TITLE
[APP] OpenAI (ChatGPT)

### ISSUE THREAD

**Issue by jkawah** [PipedreamHQ/pipedream#6539]
**Name of app / service** OpenAI (ChatGPT)

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @jkawah thanks for the request

we have integrated OpenAI/ChatGPT at: https://pipedream.com/apps/openai
