### ISSUE TITLE
[ACTION] Xero

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#654]
**Is there a specific app this action is for?**
Xero

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developer.xero.com/documentation/

**Comment by sergioeliot2039** [comment]
Upload File
Action: https://pipedream.com/actions/a_k6irzV/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-upload-file-p_rvCqADQ/edit
Download Attachment
Action: https://pipedream.com/actions/a_rJidJr/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-download-attachment-p_aNC6rYZ/edit
Make API Call
Action: https://pipedream.com/actions/a_YEi2rp/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-make-api-call-p_7NClrqB/edit
Create History Note
Action: https://pipedream.com/actions/a_eliYe6/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-history-note-p_brCL5b3/edit
Get History of Changes
Action: https://pipedream.com/actions/a_a4ivAG/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-get-history-of-changes-p_yKCJ3vZ/edit
Get Bank Summary
Action: https://pipedream.com/actions/a_K5i5rd/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-get-bank-summary-p_dDCnr8Q/edit
Create Manual Journal
Action: https://pipedream.com/actions/a_4riE4l/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-manual-journal-p_8rCNk5N/edit
List Tax Rates
Action: https://pipedream.com/actions/a_74ipPd/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-list-tax-rates-p_zACpjWd/edit
Get Manual Journal
Action: https://pipedream.com/actions/a_2wipdk/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-get-manual-journal-p_A2CQ92d/edit
List Manual Journals
Action: https://pipedream.com/actions/a_rJid1r/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-list-manual-journals-p_MOC31ao/edit
List Payments
Action: https://pipedream.com/actions/a_LgiEMW/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-list-payments-p_13CgYxj/edit
Create Bank Transaction
Action: https://pipedream.com/actions/a_WYiwz2/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-bank-transaction-p_rvCqevn/edit
Get Payment
Action: https://pipedream.com/actions/a_wdid5O/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-get-payment-p_95C3r6N/edit
Create Quote Draft
Action: https://pipedream.com/actions/a_eliYm6/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-quote-draft-p_zACpjAN/edit
Create Item
Action: https://pipedream.com/actions/a_a4ivOG/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-item-p_95C3rzN/edit
Get Item
Action: https://pipedream.com/actions/a_A6i5EA/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-get-item-p_OKCzbvx/edit
List Items
Action: https://pipedream.com/actions/a_67iLGQ/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-list-items-p_QPC1nZY/edit
Create Purchase Order
Action: https://pipedream.com/actions/a_bKilO7/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-purchase-order-p_G6C6RjW/edit
Create Payment
Action: https://pipedream.com/actions/a_k6irV0/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-payment-p_pWCYB1Z/edit
Email a Sales Invoice
Action: https://pipedream.com/actions/a_dvinvn/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-email-a-sales-invoice-p_q6CbKOj/edit
Create Purchase Bill
Action: https://pipedream.com/actions/a_xqigGY/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-purchase-bill-p_pWCYByl/edit
Create Sales Invoice
Action: https://pipedream.com/actions/a_B0i8EK/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-sales-invoice-p_YyCoyr1/edit
Create Sales Invoice
Action: https://pipedream.com/actions/a_B0i8EK/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-sales-invoice-p_LQCn5l6/edit
List Credit Notes
Action: https://pipedream.com/actions/a_a4ivba/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-list-credit-notes-p_ljCbLZd/edit
Get Credit Note
Action: https://pipedream.com/actions/a_A6i5KE/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-get-credit-note-p_JZCyb25/edit
Create Credit Note
Action: https://pipedream.com/actions/a_3Lieoo/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-credit-note-p_ZJCbJ33/edit
Download Invoice
Action: https://pipedream.com/actions/a_k6irBN/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-download-invoice-p_vQCgy3o/edit
List Invoices
Action: https://pipedream.com/actions/a_A6i5kE/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-list-invoices-p_PACqAdR/edit
Get Invoice
Action: https://pipedream.com/actions/a_52ieOd/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-get-invoice-p_rvCqAO9/edit
List Accounts
Action: https://pipedream.com/actions/a_0Mi7O5/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-list-accounts-p_xMCN8eb/edit
Create or Update Employee
Action: https://pipedream.com/actions/a_rJidax/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-or-update-employee-p_OKCzOjl/edit
Create Employee
Action: https://pipedream.com/actions/a_zNiJV2/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-create-employee-p_o7CNAo2/edit
List Contacts
Action: https://pipedream.com/actions/a_Q3ixRN/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-list-contacts-p_2gCGykw/edit
Get Tenant Connections
Action: https://pipedream.com/actions/a_vgidpp/edit
Workflow: https://pipedream.com/@sergio/xero-accounting-api-get-tenant-connections-p_OKCzOgn/edit
