### ISSUE TITLE
[BUG] Event History list steps display different then actual workflow steps.

### ISSUE THREAD

**Issue by aarontbt** [PipedreamHQ/pipedream#6550]
**Describe the bug**
A proper steps reflected on event history, but on the list view the steps reported wrongly.

**To Reproduce**
1. Go to 'Event History'
2. Click on any event and see the steps (eg. 6/6)
3. Go back to the list the steps reported are wrong sometimes (1/6)

**Expected behavior**
Steps on the list to be reported correctly

**Screenshots**
<img width="1018" alt="Screenshot 2023-05-19 at 10 29 45 AM" src="https://github.com/PipedreamHQ/pipedream/assets/50138173/166cf711-5e91-4fb8-adcf-26ef11ad5d84">
<img width="1070" alt="Screenshot 2023-05-19 at 10 30 09 AM" src="https://github.com/PipedreamHQ/pipedream/assets/50138173/4de8cc67-ac64-4312-acd2-a3218cee104e">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MACOS 13.3.1 (a) (22E772610a)
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 113.0.5672.126 (Official Build) (arm64)

**Comment by eihsu** [comment]
Thank you for reporting this, Aaron-the event history backend was using an incorrect field to count the number of steps executed.  We just deployed a fix that will correct the count for new executions, moving forward.   Please let us know if you still see the miscount for new executions!

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by aarontbt** [comment]
Thank you all I can confirmed this is fixed on my view as well! 💌
