### ISSUE TITLE
[FEATURE] Allow draft deletion to go back to "live" state

### ISSUE THREAD

**Issue by DNA-PC** [PipedreamHQ/pipedream#6553]
**Is your feature request related to a problem? Please describe.**
I have a few Workflows where I have made some changes that aren't deployed, and I'd like to revert those changes to go back to the state of the "live" workflow.

It's been too long I've updated those draft and I don't know/identify what's the difference between the live and draft versions. I'm afraid of breaking something if I simply work on-top of the existing draft.

**Describe the solution you'd like**
I want an option to "Delete draft version".

Alternatively, having a way to identify the difference between a "live" and "draft" version would be useful, even if it's just a "JSON diff" between the two, that'd still be better than having no clues at all.

**Do you have a workaround?**
I don't have any.

**Comparable features in other tools?**
In Zapier:
<img width="951" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/107790761/04fcee21-3e1c-4085-9cfb-ceaac428081f">

Short video (1mn) of what Zapier allows:
https://watch.screencastify.com/v/2LFG7QVI3ns1tBg9TTWQ

**Comment by vunguyenhung** [comment]
Hi @DNA-PC, I think this feature is needed and can be used along side with the [upcoming Pipedream GIT integration](https://github.com/PipedreamHQ/pipedream/issues/220). Hence, I will add it to Pipedream internal backlog

**Comment by dylburger** [comment]
@DNA-PC yes, @vunguyenhung is correct! Our Git release is imminent and we'll send more information about that via email. I'm closing this issue so we can consolidate there.
