### ISSUE TITLE
[BUG] New Trade Order Action "Signature not match" Error

### ISSUE THREAD

**Issue by zaiden96** [PipedreamHQ/pipedream#6556]
**File in question**: Bug concerning the "Trade New Order" action for BingX. Located [here](https://github.com/PipedreamHQ/pipedream/blob/master/components/bingx/actions/trade-new-order/trade-new-order.mjs)

**Issue**:  workflow executes successfully but no trade is placed due to the error "msg: signature not match". I verified my api and secret key. 

Something in the imported file "bingx.app.mjs" [file ](https://github.com/PipedreamHQ/pipedream/blob/master/components/bingx/bingx.app.mjs)may need to be updated? 

**Example:**
<img width="625" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/efe945ea-f358-4baa-af8d-3fd9aacd5756">

Any help is greatly appreciated!

**Comment by zaiden96** [comment]
@alysonturing Yes, I can test it, thanks alot!

**Comment by alysonturing** [comment]
@zaiden96 this is the [link of the PR](https://github.com/PipedreamHQ/pipedream/pull/6558) are you familiar with Pipedream publish?

**Comment by zaiden96** [comment]
@alysonturing Unfortunately not too familiar. I haven't worked much with github either so I had some trouble trying to understand the Pipedream publish documentation. Is there anything I can help out with?

**Comment by alysonturing** [comment]
@zaiden96 in your workflow, you can add a new action -> then select "Node" -> then select "Run Node Code"
then in the code editor, paste the code below, and click in "test".

import bingx from "@pipedream/bingx";

export default defineComponent({
  props: {
    bingx,
    symbol: {
      propDefinition: [
        bingx,
        "symbol",
      ],
    },
    side: {
      propDefinition: [
        bingx,
        "side",
      ],
    },
    entrustPrice: {
      propDefinition: [
        bingx,
        "entrustPrice",
      ],
    },
    entrustVolume: {
      propDefinition: [
        bingx,
        "entrustVolume",
      ],
    },
    tradeType: {
      propDefinition: [
        bingx,
        "tradeType",
      ],
    },
    action: {
      propDefinition: [
        bingx,
        "action",
      ],
    },
    takerProfitPrice: {
      label: "Taker Profit Price",
      description: "The take profit price",
      type: "string",
      optional: true,
    },
    stopLossPrice: {
      label: "Stop Loss Price",
      description: "The take loss price",
      type: "string",
      optional: true,
    },
  },
  methods: {
    // Fix for error: "signature not match"
    cleanObject(o) {
      for (var k in o || {}) {
        if (typeof o[k] === "undefined") {
          delete o[k];
        }
      }
    },
  },
  async run({ $ }) {
    const API_METHOD = "POST";
    const API_PATH = "/api/v1/user/trade";

    const parameters = this.cleanObject({
      "symbol": this.symbol,
      "side": this.side,
      "entrustPrice": this.bingx.convertToFloat(this.entrustPrice),
      "entrustVolume": this.bingx.convertToFloat(this.entrustVolume),
      "tradeType": this.tradeType,
      "action": this.action,
      "takerProfitPrice": this.bingx.convertToFloat(this.takerProfitPrice?.toString().replace(",", ".")),
      "stopLossPrice": this.bingx.convertToFloat(this.stopLossPrice?.toString().replace(",", ".")),
    });
    const returnValue = await this.bingx.makeRequest(API_METHOD, API_PATH, parameters);
    $.export("$summary", `New Future Order for ${this.symbol}`);
    return returnValue;
  },
})

**Comment by zaiden96** [comment]
@alysonturing 

I see the following error:

<img width="338" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/64502d7c-b4f2-458b-a269-4d302f6ae75e">



**Inputs:**

<img width="340" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/90781354-3d50-492d-abe4-edf498f184b1">




**Full workflow for reference:**

<img width="384" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/ea74d479-c211-4fb2-88eb-e28ecee95e57">

**Comment by alysonturing** [comment]
@zaiden96 perfect! I changed it, can you try it again please?

```
import bingx from "@pipedream/bingx";

export default defineComponent({
  props: {
    bingx,
    symbol: {
      propDefinition: [
        bingx,
        "symbol",
      ],
    },
    side: {
      propDefinition: [
        bingx,
        "side",
      ],
    },
    entrustPrice: {
      propDefinition: [
        bingx,
        "entrustPrice",
      ],
    },
    entrustVolume: {
      propDefinition: [
        bingx,
        "entrustVolume",
      ],
    },
    tradeType: {
      propDefinition: [
        bingx,
        "tradeType",
      ],
    },
    action: {
      propDefinition: [
        bingx,
        "action",
      ],
    },
    takerProfitPrice: {
      label: "Taker Profit Price",
      description: "The take profit price",
      type: "string",
      optional: true,
    },
    stopLossPrice: {
      label: "Stop Loss Price",
      description: "The take loss price",
      type: "string",
      optional: true,
    },
  },
  methods: {
    // Fix for error: "signature not match"
    cleanObject(o) {
      for (var k in o || {}) {
        if (typeof o[k] === "undefined") {
          delete o[k];
        }
      }
    },
  },
  async run({ $ }) {
    const API_METHOD = "POST";
    const API_PATH = "/api/v1/user/trade";

    const parameters = {
      "symbol": this.symbol,
      "side": this.side,
      "entrustPrice": this.bingx.convertToFloat(this.entrustPrice),
      "entrustVolume": this.bingx.convertToFloat(this.entrustVolume),
      "tradeType": this.tradeType,
      "action": this.action,
      "takerProfitPrice": this.bingx.convertToFloat(this.takerProfitPrice?.toString().replace(",", ".")),
      "stopLossPrice": this.bingx.convertToFloat(this.stopLossPrice?.toString().replace(",", ".")),
    };
    this.cleanObject(parameters);
    const returnValue = await this.bingx.makeRequest(API_METHOD, API_PATH, parameters);
    $.export("$summary", `New Future Order for ${this.symbol}`);
    return returnValue;
  },
})
```

**Comment by zaiden96** [comment]
@alysonturing 

That resolved the previous error msg! However, it brought another error that the order amount is less than the minimum trade size. However, I just opened a trade with 10x lower volume than the amount passed in the inputs here on the exchange manually and it was large enough. Is it possible the code isn't sending the right format for Volume which makes it default to zero?

<img width="368" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/8d4246a7-9f31-4ac8-9ecd-0501bed07cc2">

**Inputs**
<img width="356" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/108202016/b91c16da-4787-4da5-bc9f-924978993444">

**Comment by alysonturing** [comment]
The float64 data type is expected by the API, can you please pass this parameter as such? 
Example: `12.97`

**Comment by zaiden96** [comment]
@alysonturing Does the following lines convert it to float64 before passing it to the API?

      "entrustPrice": this.bingx.convertToFloat(this.entrustPrice),
      "entrustVolume": this.bingx.convertToFloat(this.entrustVolume),

From the bingx.app.mjs file that is imported it has the type as string, and then the lines above convert it to a float:

    entrustPrice: {
      label: "Price",
      description: "Price",
      type: "string",
      optional: false,
    },
    entrustVolume: {
      label: "Volume",
      description: "Volume",
      type: "string",
      optional: false,
    },

**Comment by alysonturing** [comment]
Yes but it uses parseFloat function, and then when you pass a string in an integer format it keeps in integer format

Example:
"1972" -> 1972
"19.72" -> 19.72

**Comment by zaiden96** [comment]
@alysonturing Oh great point, I'll change the webhook parameters to send a float value. It may take some time to test though because another signal needs to be generated. Thanks!

**Comment by alysonturing** [comment]
Ok, I'm waiting

**Comment by zaiden96** [comment]
@alysonturing It works! Incredible work, thank you so much!!

**Comment by vunguyenhung** [comment]
Hi, as @zaiden96 has confirmed it working. I will move it to ready for release
