### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by Bags-0-Confidence** [PipedreamHQ/pipedream#6571]
Appreciate if Triggers for the following can be made available:
- Vimeo likes
- Tumblr likes
- Reddit upvoted posts

**Comment by vunguyenhung** [comment]
@Bags-0-Confidence, I have found API docs for Vimeo and Tumblr. But unfortunately I can't find relevant one for reddit.
https://github.com/PipedreamHQ/pipedream/issues/6585
https://github.com/PipedreamHQ/pipedream/issues/6584

Hence, I will close this ticket
