### ISSUE TITLE
[ACTION] Google PaLM API

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#6573]
**Is there a specific app this action is for?**

https://developers.generativeai.google/guide/palm_api_overview

Actions:

* [Generate Text](https://developers.generativeai.google/tutorials/text_node_quickstart)
* [Chat](https://developers.generativeai.google/tutorials/chat_node_quickstart)
* [Generate Embeddings](https://developers.generativeai.google/guide/palm_api_overview#node.js_2)

**Comment by vunguyenhung** [comment]
Hi, as I couldn't access the Google PaLM early access for now. I will mark this to ready for release first and test later when I have the access
