### ISSUE TITLE
OpenAI Chat - Not passing correct arguments

### ISSUE THREAD

**Issue by fsodano** [PipedreamHQ/pipedream#6582]
Hi there, each time I try to pass previous messages, it comes back saying that it's not a valid array.

![image](https://github.com/PipedreamHQ/pipedream/assets/844181/6433571d-20a2-4f5c-8321-a026e2b6fd3f)

I suspect it's because I should be passing an object like `{"role": "user", "message": "something"}` but in this component, these are passed as strings and the resulting message array is invalid (at least that's what I think is happening)

This is the line:
https://github.com/PipedreamHQ/pipedream/blob/df2f621ea7ebaa1c2521c33f320e5aba70e64d90/components/openai/actions/chat/chat.mjs#L42

See the reference
https://platform.openai.com/docs/api-reference/chat/create

Am I missing something?

Thank you.

**Comment by vunguyenhung** [comment]
Hi @fsodano, you can pass in the array using the Custom Expression:
```
{{ [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ] }}
```

In the custom expression, you're free to use any Node.js code. I recommend you to watch through [Pipedream University series](https://pipedream.com/university) to understand how Pipedream works.

If you have more question, feel free to join [Pipedream Users slack](https://join.slack.com/t/pipedream-users/shared_invite/zt-11sazmsg0-oS2VW~mZfhtk3XfEEvb~JA) and ask there
