### ISSUE TITLE
[Components] Imagga

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6592]
# imagga
## URLs
- https://docs.imagga.com
#### Prompt
Emit new event when a batch of images has been processed for categorization, tagging, or color extraction. Please add the ticketId prop.
#### URLs
- https://docs.imagga.com/?shell#tickets
#### Prompt
Analyze a single image for visual content such as tags, categories, and colors. Please add a field with options to choose between tags, catergories or colors. Add fields to upload or input an url image.
#### URLs
- https://docs.imagga.com/?shell#uploads
- https://docs.imagga.com/?shell#tags
- https://docs.imagga.com/?shell#colors
- https://docs.imagga.com/?shell#categorizers
#### Prompt
Analyze a batch of images for categorization, tagging, or color extraction. Please add a field with options to choose between tagging, categorization or color extraction. Add fields to upload or input an url image.
#### URLs
- https://docs.imagga.com/?shell#uploads
- https://docs.imagga.com/#batches
#### Prompt
Assign a category to a single image based on its visual content. Please add a field with options to choose between tagging, categorization or color extraction. Please add an async prop that lists all categorizers. Add fields to upload or input an url image.
#### URLs
- https://docs.imagga.com/?shell#uploads
- https://docs.imagga.com/?shell#categorizers
- https://docs.imagga.com/?shell#categories-categorizer_id

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Imagga-776e54bc6c9b4093a18facd2af66863d

Hi @vunguyenhung, in the process_batch action you can add an array of imageUrl or imageFile
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/241829e8-133e-4d0d-97cb-420b846fa3ce)
