### ISSUE TITLE
[FEATURE] allow selection of multiple events to do batch operations

### ISSUE THREAD

**Issue by Clausinho** [PipedreamHQ/pipedream#6594]
**Is your feature request related to a problem? Please describe.**
I am always frustrated, when I have an error in a workflow happening in multiple events and I just want to fix it. I always have to click each event for it to replay.

**Describe the solution you'd like**
I'd like a way to select multiple events inside a workflow and do batch operations on them. Batch replay and then batch delete would be a favorite.

Or a retry all failed events in the last week or some custom date.

**Do you have a workaround?**
I can click each one but it takes a long time, especially if its over the weekend.

**Comparable features in other tools?**
Selecting multiple items seems a very common feature.

**Comment by dylburger** [comment]
Tracking in #2784
