### ISSUE TITLE
[APP] Pipefy

### ISSUE THREAD

**Issue by GenieTim** [PipedreamHQ/pipedream#660]
**Name of app / service**

Pipefy

**Link to developer documentation**

https://api-docs.pipefy.com/reference/queries/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Workaround: using your competitors, Integromat and Zappier

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

- Trigger: card.create, 
- Trigger: card.done, 
- Trigger: card.expired, 
- Trigger: card.late, 
- Trigger: card.move, 
- Trigger: card.overdue, 
- Trigger: card.field_update

Docs for triggers: https://api-docs.pipefy.com/reference/objects/Webhook/

- Action: createCard
- Action: updateCardField

Docs for actions: https://api-docs.pipefy.com/reference/mutations/overview/
(many more possible)

Best regards,

**Comment by todsac** [comment]
FYI - I have added Pipefy as an integrated app.  Feel free to add any actions or triggers, and we will add it to our backlog as well.  Example - https://pipedream.com/@tod/pipefy-integration-example-p_RRCzzoV/

**Comment by todsac** [comment]
FYI - Pipefy actions have been completed:

<img width="813" alt="Screen Shot 2020-12-21 at 12 07 53 PM" src="https://user-images.githubusercontent.com/35614146/102817738-28411f80-4385-11eb-8039-417e81670781.png">
