### ISSUE TITLE
[Components] Wix

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6614]
### App
Wix
https://www.wix.com/

Triggers:
1. Form Submitted: Detects when a user submits a form on the Wix site.
2. New Member Registered: Tracks when a new member signs up on a Wix site.

Actions:
1. Create Contact: Adds a new contact to the Wix site's contact list.
2. Send Email: Sends an email using Wix's built-in email service.
3. Add Product: Inserts a new product to the Wix online store.

_This list of suggested components was generated using ChatGPT_

**Comment by michelle0927** [comment]
Related issue #3993
