### ISSUE TITLE
[FEATURE] Output JSON format when getting values from Google Sheets

### ISSUE THREAD

**Issue by bsommardahl** [PipedreamHQ/pipedream#6615]
I find myself constantly writing (aka copy/pasting) steps that convert google sheet values to json arrays. It would be great if the Get Values action could have an option to return results as JSON or rows.

**Comment by vunguyenhung** [comment]
Hi @bsommardahl, the action already return the value as JSON object in the `data` field
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/f0b8cc8a-249c-4786-b08b-ba476bea5eaf)

Would you mind sharing the expected output you'd like? Together with some sample outputs?

Please note that some Google Sheet allow user to freely inputing values, so if we convert the values to your usecase, it might break for other cases

**Comment by bsommardahl** [comment]
You are right. It does technically return JSON. I suppose I am referring to
structured json objects for each row using the header row for keys.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
