### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by cosmicdebris** [PipedreamHQ/pipedream#6618]
ObsidianMD

https://marcus.se.net/obsidian-plugin-docs/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No workaround...

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
We have another request for Obsidian on https://github.com/PipedreamHQ/pipedream/issues/6144. Feel free to follow for updates there in case we go with the integration.

Yet, they don't have an API:


> I checked the documentation available for Obsidian and I found there is only a plug ins API and themes capabilities for developers. I then reached out to their Discord forums and they confirmed atm there is no API we can use at the server side to integrate i.e. via Pipedream. When reaching out for comment about a REST, server side, this is what they said:
> **No REST API, Obsidian is a local-first application**



So, I have to mark this ticket as blocked for now.
