### ISSUE TITLE
[BUG] Pushover Priority is invalid (seems to have regressed from fix in #6048)

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#6621]
**Describe the bug**
The Pushover send `Push Notification` action has a bug when you select `Priority` from the dropdown (see screenshots) when you manually type the number in Custom Expression everything works as it should. This seems to be a regression from the fix applied in #6048 

See #6048 for steps to reproduce as exactly the same bug.

![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/594633d9-4e36-4e8d-b6df-800b1d642b49)

**Comment by vunguyenhung** [comment]
Hi @NebularNerd, I tried to reproduce you issue but couldn't. As I can set the Priority prop to 0
<img width="828" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/2e816024-2700-4e29-a0b1-6aac7c76b606">

Would you mind trying to update your action, or create a new one then try again?

**Comment by NebularNerd** [comment]
Hi @vunguyenhung 

I've just gone back in and tried to update the pushover step again, still not letting me set it to `Normal` just flags up the `must be an integer` error. Setting it manually works fine.

Creating a new workflow allowed me to set the priority to `Normal` as expected.

Going back to the an existing workflows, re-adding the Pushover step and testing seems to be working as well. Most strange, the workflow had been running since the close of my previous ticket without being touched, then bugged out the other day with the old fault like a regression had taken place, since opening this ticket and your reply it's fixed itself.

I shall close for now and re-open if it happens again.
