### ISSUE TITLE
[Components] iAuditor by SafetyCulture

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6631]
### App
iAuditor by SafetyCulture
https://safetyculture.com/iauditor/

**Triggers:**
1. Inspection completed _TRIGGER_EVENT_INSPECTION_COMPLETED_
https://developer.safetyculture.com/reference/webhooksservice_createwebhook
2. Action created _TRIGGER_EVENT_ACTION_CREATED_

**Actions:**
1. Generate a PDF report
https://developer.safetyculture.com/reference/thepubservice_getinspectionwebreportlink
2. Export inspection to PDF or Word
https://developer.safetyculture.com/reference/reportsservice_startinspectionexport
2. Create a user
https://developer.safetyculture.com/reference/thepubservice_adduser
3. Update a user
https://developer.safetyculture.com/reference/thepubservice_updateuser
4. Create inspection
https://developer.safetyculture.com/reference/thepubservice_startinspection
5. Share inspection
https://developer.safetyculture.com/reference/thepubservice_shareinspection

**Comment by alysonturing** [comment]
@michelle0927 sorry, I lost track of this task, it's approved now
