### ISSUE TITLE
[Components] Wave

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6633]
### App
Wave
https://www.waveapps.com/

Triggers:
1. New customer
2. New invoice

Actions:
1. Create Invoice: Create a new invoice for a customer
https://developer.waveapps.com/hc/en-us/articles/360038817812-Mutation-Create-invoice
2. Create Customer: Update existing customer contact information.
https://developer.waveapps.com/hc/en-us/articles/360032569232-Mutation-Create-customer

**Comment by sergio-eliot-rodriguez** [comment]
There is a user request for components at #2810

**Comment by sergio-eliot-rodriguez** [comment]
This has been upvoted #7444 , user requesting create invoice action
