### ISSUE TITLE
[BUG] Discourse - New Threads `categories` async prop broken

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#6641]
**Describe the bug**
Async options for selecting the categories to listen to for **Disource - New Thread** seem to be broken.

**To Reproduce**
1. Create an API key for Discourse
2. Start a new workflow
3. Select the **Discourse - New Thread** trigger
4. Attempt to select a category
5. Observe categories never load

**Expected behavior**
I expect categories to be listed.

**Screenshots**
<img width="1001" alt="CleanShot 2023-05-25 at 11 14 42@2x" src="https://github.com/PipedreamHQ/pipedream/assets/2694734/69c93796-37d5-4f5e-ab44-b8e121a6f1e0">

**Comment by vunguyenhung** [comment]
Hi, I can reproduce this issue, I have multiple categories in discourse, but none show on PIpedream
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/6bcd63e2-8c00-48f4-aec8-bd4575883cb0)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/ae07d540-531f-41ed-8217-4d97f063e985)
