### ISSUE TITLE
[BUG] Slack - New Reaction Added - Icon Emoji prop only loads 14 emojis

### ISSUE THREAD

**Issue by mendelsphotography** [PipedreamHQ/pipedream#6642]
**Is there a specific app this action is for?**
Slack.

Seems like currently slack New Reaction Added (Instant) only has 14 emojis anyway to add more and add a custom one also? 
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/27e27f81-e56a-4954-98c6-b7bf263fe328)

For example, I want to use :round_pushpin: when a user reacts to that in any channel it sends the current message to a Chanel.

**Expected behavior:**
- I should be able to load more emoji when clicking Load more button. 
- I should be able to search for an emoji

**Please provide a link to the relevant API docs for the specific service / operation.**
https://api.slack.com/docs

**Comment by itsajay1029** [comment]
I'd like to work on it. Pls assign it to me @mendelsphotography

**Comment by mendelsphotography** [comment]
@dylburger can do that not me.

**Comment by itsajay1029** [comment]
@dylburger Assign it to me. I want to work on this

**Comment by vunguyenhung** [comment]
Hi @mendelsphotography @itsajay1029, there's no need the "official" assigning the task. You can directly create a PR and link it to this issue. Then your PR should be reviewed by Pipedream component dev

**Comment by vunguyenhung** [comment]
Hi @mendelsphotography, thank you for raising this issue. I have checked and this seems more like a bug to me. I have corrected the description and added it to prioritized backlog
