### ISSUE TITLE
Trustpilot

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6644]
### App
Trustpilot
https://developers.trustpilot.com/

### Actions
https://developers.trustpilot.com/invitation-api#create-invitation(s)

**Comment by binarymonkey84** [comment]
[Related Slack thread](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1685028954778659)

**Comment by sergio-eliot-rodriguez** [comment]
trustpitlot itnegration https://pipedream.com/apps/trustpilot

@binarymonkey84 i'm closing this issue for the action request in favor of #6694 which is included along other components, feel free to fllow there, thanks!
