### ISSUE TITLE
[BUG] Discourse - New Topic fails to create

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#6648]
**Describe the bug**
Unable to create a new Disourse - New Topic source. 

**To Reproduce**

Attempt to create a new Disourse - New Topic source without defining any `category` props

**Expected behavior**
I expect to be able to create a source.

**Screenshots**
When creating the source, the webhook registration fails:

<img width="1041" alt="CleanShot 2023-05-25 at 13 21 30@2x" src="https://github.com/PipedreamHQ/pipedream/assets/2694734/5723db31-6871-4e98-b920-fb47948512be">

**Comment by vunguyenhung** [comment]
Hi, I can reproduce this issue. Will add it to prioritized backlog
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/6f5b6fd6-c785-4ec0-ab99-99594b803187)
