### ISSUE TITLE
[FEATURE] Full text search for workflows

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#665]
I need a way to search through the code / params across workflows. I often need to find the workflows that use a specific environment variable, or that contain a step with a specific name, but I don't have a way to execute such a search today.

**Comment by nachocab** [comment]
Also related to #600 

The main use case for this is refactorings. Let's say I rename a SQL table column that I access from multiple workflows. There's currently no way to find out in which workflows I used it so I end up not changing all the workflows, which results in fatal errors during execution.

**Comment by nachocab** [comment]
A incremental step before #220 is implemented would be to add an endpoint to the PipeDream API that would return a JSON with the step names (similar to what is currently shown in the README tab). Something like this:

GET /workflows/{workflow_id}/readme

<img width="482" alt="CleanShot 2021-07-21 at 15 00 02@2x" src="https://user-images.githubusercontent.com/27538/126492525-7066683c-1ea4-469c-8726-c9d3bbca6362.png">

**Comment by dylburger** [comment]
This should be solved by #220

**Comment by dylburger** [comment]
Since we're about to launch Git, I'm closing this since full-text code search will be supported in that model.
