### ISSUE TITLE
Stop being spammer !!

### ISSUE THREAD

**Issue by pedrorijo91** [PipedreamHQ/pipedream#6657]
Just received a marketing email from pipedream. directly to the email I only use at github, which means you are scrapping github users/commits and sending spam

email came from sacerdoti@pipedream.com @todsac 

please, respect people privacy. reported as spam, obviously

**Comment by dylburger** [comment]
Hi @pedrorijo91 , we don't scrape emails from GitHub. It's likely you signed up for https://requestbin.com (which we operate) or https://pipedream.com at some point.

Could you send me an email to support@pipedream.com with the email address you received an email to, so I can remove you from our email mailing list?

**Comment by todsac** [comment]
Yes, @pedrorijo91, you signed up with your hey.com email address three months ago. We don't spam.
