### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by prakhar-dhakar** [PipedreamHQ/pipedream#6660]
**Describe the bug**
Unable to import package msoffcrypto in python 3.9

**To Reproduce**
1. try to use the import statement `import msoffcrypto`

**Expected behavior**
Should install or load the msoffcrypto package

**Screenshots**
![image](https://github.com/PipedreamHQ/pipedream/assets/37078245/ed083180-3d5d-4c14-bec6-dca02577b31f)

**Desktop (please complete the following information):**

**Comment by vunguyenhung** [comment]
Hello @prakhar-dhakar, you can refer to this doc to understand how to import packages having name different https://pipedream.com/docs/code/python/import-mappings/#using-magic-comments

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
