### ISSUE TITLE
Google Forms

### ISSUE THREAD

**Issue by mineTomek** [PipedreamHQ/pipedream#6664]
**Google Forms**

**I hope this is correct: https://developers.google.com/forms/api/reference/rest**

**Alternatively I can link form to spradsheet.**

**New reply, mainly**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @mineTomek 

Thanks for the request!

Happy to announce there is already an integration: 

https://pipedream.com/apps/google-forms

and we are tracking sources at: https://github.com/PipedreamHQ/pipedream/issues/631
new reply included.
feel free to follow there, if you'd like
