### ISSUE TITLE
[BUG] Custom action in a workflow not receiving data from previous steps

### ISSUE THREAD

**Issue by axmachina** [PipedreamHQ/pipedream#6672]
**Describe the bug**
The Pipedream workflow's custom action appears not to be receiving the data from the previous steps, including the critical trigger step. It seems that the steps object, expected to contain the data from all preceding steps, is absent in the custom action.

However, this issue is not present when a custom Node step is inserted immediately after the trigger, containing the same basic code as the custom action. This circumstance leads to ambiguity: it might be a bug or perhaps an undocumented feature.

Regardless of its classification, this issue considerably hinders workflow development utilizing custom actions. I am seeking assistance or alternative solutions to this problem. Thanks!

**To Reproduce**

Build simple action and deploy with cli,

`simple-action.mjs`:

```
export default defineComponent({
  key: "simple-action",
  name: "Simple Action",
  description: "simple action",
  version: "0.0.1",
  type: "action",
  async run(args) {
    console.log("args", args);
  },
});
```

```
pd publish simple-action.mjs
```

1. Create a workflow
2. Add time schedule trigger.
3. Generate a test event.
4. Add Simple Action.
5. Test workflow.

**Expected behavior**
The Simple Action step should get args.steps containing the previous trigger results.

**Observed behavior**
Action args contain $ but miss steps data:

```
args {
  '$': {
    export: [Function: export],
    send: {
      email: [Function (anonymous)],
      emit: [Function (anonymous)],
      http: [Function (anonymous)],
      s3: [Function (anonymous)],
      sql: [Function (anonymous)],
      snowflake: [Function (anonymous)],
      sse: [Function (anonymous)],
      sms: [Function (anonymous)]
    },
    respond: [Function: $respond],
    context: {
      id: '2QLmTY40OtaZl3rNOIv5P4amZKU',
      ts: '2023-05-26T22:47:23.346Z',
      pipeline_id: null,
      workflow_id: 'p_JZCw3qm',
      deployment_id: 'd_oksLAxWZ',
      source_type: 'TRACE',
      verified: false,
      hops: null,
      test: true,
      replay: false,
      owner_id: 'o_v1IkJdv',
      platform_version: '3.40.0',
      workflow_name: 'Untitled Workflow',
      resume: null,
      trace_id: '2QLmTY40OtaZl3rNOIv5P4amZKU',
      JIT: true,
      run: [Object],
      deadline: 1685141277399
    },
    flow: {
      exit: [Function: exit],
      rerun: [Function: rerun],
      delay: [Function: delay],
      suspend: [Function: suspend],
      refreshTimeout: [Function: refreshTimeout]
    }
  }
}

```

***Additional Context***

If you now go and add a custom Node step just above the custom Action step and right after the workflow trigger, 

```
export default defineComponent({
  async run(args) {
     console.log("args", args);
    // Return data to use it in future steps
    return args.steps;
  },
})
```

You'll note that the args now does contain the steps data:

```
args {
  '$': {
    export: [Function: export],
    send: {
      email: [Function (anonymous)],
      emit: [Function (anonymous)],
      http: [Function (anonymous)],
      s3: [Function (anonymous)],
      sql: [Function (anonymous)],
      snowflake: [Function (anonymous)],
      sse: [Function (anonymous)],
      sms: [Function (anonymous)]
    },
    respond: [Function: $respond],
    context: {
      id: '2QLnjyzwGH9zp8Dwjui1pfrh7nJ',
      ts: '2023-05-26T22:57:47.685Z',
      pipeline_id: null,
      workflow_id: 'p_JZCw3qm',
      deployment_id: 'd_BBsrlVJO',
      source_type: 'TRACE',
      verified: false,
      hops: null,
      test: true,
      replay: false,
      owner_id: 'o_v1IkJdv',
      platform_version: '3.40.0',
      workflow_name: 'Untitled Workflow',
      resume: null,
      trace_id: '2QLnjyzwGH9zp8Dwjui1pfrh7nJ',
      JIT: true,
      run: [Object],
      deadline: 1685141900805
    },
    flow: {
      exit: [Function: exit],
      rerun: [Function: rerun],
      delay: [Function: delay],
      suspend: [Function: suspend],
      refreshTimeout: [Function: refreshTimeout]
    }
  },
  event: {
    timestamp: 1685141231,
    timezone_utc: {
      date: [Object],
      iso8601: [Object],
      metadata: [Object],
      pretty: [Object],
      time: [Object],
      timezone: 'UTC'
    },
    timezone_configured: {
      date: [Object],
      iso8601: [Object],
      metadata: [Object],
      pretty: [Object],
      time: [Object],
      timezone: 'America/Los_Angeles'
    },
    interval_seconds: 30
  },
  steps: {
    slack_bot: {},
    trigger: { event: [Object], context: [Object] },
    node: {}
  }
}
```

*** Cause ***

By the process of elimination, I have discovered that simply commenting out the key prop seems to fix this.

Without the key prop, we get steps from the trigger:
```
export default defineComponent({
  // key: "simple-action",
  name: "Simple Action",
  description: "simple action",
  version: "0.0.2",
  type: "action",
  async run(args) {
    console.log("steps", args.steps); // steps defined!
    console.log("args", args);
  },
});
```

Of course this cannot be the solution as the key prop is required to publish a custom action.

**Comment by vunguyenhung** [comment]
Hi @axmachina, 

When you adding the `key` prop, you are effectively making your [Node.js code step a reusable action](https://pipedream.com/docs/code/nodejs/sharing-code/#publish-an-action-from-a-node-js-code-step). The reusable action doesn't have the `steps` params, with the reason explained below
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/1e3e93fb-7713-4d71-a41e-7e6452b31e4d)


Please read through the doc to understand how you can use reusable action. The Node.js code step in your workflow will work without the `key` prop, so you can ignore it for now.

**Comment by axmachina** [comment]
Oh 😮 how did I miss that. Sorry. Thanks for the clarification!
