### ISSUE TITLE
New Files (Instant)

### ISSUE THREAD

**Issue by larrywarrensr** [PipedreamHQ/pipedream#6678]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by dannyroosevelt** [comment]
@larrywarrensr can you clarify what app you're trying to use with a New Files trigger?

**Comment by larrywarrensr** [comment]
Yes, I'm following the instructions of Thomas Frank as followed:

[Thomas Frank} Set Up the Google Drive Trigger

Every Pipedream workflow starts out with a trigger. This is an event that kicks off the workflow and causes all the subsequent steps to be executed.

Triggers can take several forms:

An event happening at a connected app (e.g. a file being uploaded to Google Drive)
An incoming [webhook](https://pipedream.com/docs/api/rest/webhooks/#send-events-from-an-existing-event-source-to-a-webhook)
A specific time of day
An email being sent to your special Pipedream email address
In this case, the trigger we want to use is the New Files trigger for Google Drive:

In the trigger step’s list of apps, select Google Drive.

Then select New Files (Instant).

[Larry] I've searched for this "trigger" name "New Files (Instant)" and its not listed under "Google drive"

**Comment by dannyroosevelt** [comment]
Can you send a screenshot of what you're seeing? I see it here:
<img width="927" alt="Screenshot 2023-05-27 at 12 18 16 PM" src="https://github.com/PipedreamHQ/pipedream/assets/20780753/a6c0906d-af8f-440a-8aef-58fc648f44e1">

You can also add it to a new workflow here:
https://pipedream.com/apps/google-drive/triggers/new-files-instant

**Comment by larrywarrensr** [comment]
Hey! I see it now!!! :) 

I SWEAR, I went up and down the list several times and it wasn't there!

Thanks so much for your help!!! :)
