### ISSUE TITLE
[ACTION] Microsoft Teams - Shifts App

### ISSUE THREAD

**Issue by dharrison27** [PipedreamHQ/pipedream#6681]
**Is there a specific app this action is for?**
Microsoft Teams, part of Microsoft 365.

**Please provide a link to the relevant API docs for the specific service / operation.**
https://learn.microsoft.com/en-us/connectors/shifts/

**Comment by vunguyenhung** [comment]
Hi @dharrison27, could you elaborate how Micrsoft Teams - Shifts App works, and how do you expect it would work with Pipedream? Since Microsoft has their own Power Automate service that similar to Pipedream, and that service can leverage that Shifts App

**Comment by dharrison27** [comment]
> Hi @dharrison27, could you elaborate how Micrsoft Teams - Shifts App works, and how do you expect it would work with Pipedream? 

Hi @vunguyenhung thank you for picking this issue up so quickly! From what I can tell, it operates from Microsoft's Graph API infrastructure. (https://graph.microsoft.com)

Microsoft Power Automate does have some similarities to Pipedream, as it does with Zapier, IFTTT, make (?), etc

I am moving my zaps from IFTTT and Zapier to Pipedream. I'd like to have them all in one place so if I need to tweak something or fix it, I go to one place. Besides, Pipedream is a far better experience for me, IMO, than MS PA.

I would also like to be able to fire off parts of my workflows to involve data that I would 'pipe' in from Shifts/Teams/Graph as well as what I already have here. Notion's handling, as an example, is best in Pipedream.

Shifts is for management of business/pro/corps to give shifts to staff workers. It also allows self-serve for offering shifts, swapping shifts, requesting days-off. When I get my shifts changed every 3 months, I have to manually input all of my shifts in to my personal calendar as there is no subscribing to this calendar, no export option, no convenient way to get the data automatically.

![image](https://github.com/PipedreamHQ/pipedream/assets/6942985/827b078b-b35c-4b10-8d04-33ba544ff496) 

There is also this part of the Shifts app for shift admin like time-off reqs:
![image](https://github.com/PipedreamHQ/pipedream/assets/6942985/e0ef3f5d-a841-4865-a571-b18d96e6be46)

> Since Microsoft has their own Power Automate service that similar to Pipedream, and that service can leverage that Shifts App

But Pipedream is so much better than MS Flow/PowerAutomate! 😬

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dharrison27** [comment]
I’m confused. I gave a detailed response, addressing the questions. I included screenshots and direct links to API and other related info.

**Comment by dylburger** [comment]
@dharrison27 apologies, this was an automation gone awry! We'll make sure this gets on the backlog, thanks for the detail.

**Comment by dharrison27** [comment]
hey no worries, thank you 🙂
