### ISSUE TITLE
onenote

### ISSUE THREAD

**Issue by ronakai** [PipedreamHQ/pipedream#6682]
**Microsoft OneNote**

**Link to developer documentation**

**It is preventing me. No workarounds**

**Action is to create a new Section; create a new Page under an existing Section; and to add a note inside an existing Page**

**Comment by sergio-eliot-rodriguez** [comment]
onenote was submitted approval sometime during the 22/5 week

**Comment by sergio-eliot-rodriguez** [comment]
ONenote updated in #6756 

Comes with an action request
> 
> Create a vocal note via OneNote then use ChatGPT integration for translation
>

**Comment by sergio-eliot-rodriguez** [comment]
OneNote upvoted in https://github.com/PipedreamHQ/pipedream/issues/7487
