### ISSUE TITLE
[BUG] link in contributing md is not working

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [PipedreamHQ/pipedream#6683]
**Describe the bug**
![image](https://github.com/PipedreamHQ/pipedream/assets/94478026/1e45d36d-d63b-4028-b6e6-9a7745ce0d0e)
![image](https://github.com/PipedreamHQ/pipedream/assets/94478026/b2113b80-8ed1-4946-83b7-68e5d2e14d95)

**To Reproduce**
[CONTRIBUTING.md](https://github.com/PipedreamHQ/pipedream/blob/master/CONTRIBUTING.md#setting-up-your-component-development-environment)

**Comment by vunguyenhung** [comment]
Hi @DIWAKARKASHYAP, thanks for raising this issue. I've added a PR here to fix it: https://github.com/PipedreamHQ/pipedream/pull/6686
