### ISSUE TITLE
[BUG] Workflow pass all the tests but when deployed throws an error

### ISSUE THREAD

**Issue by RostyslavDzhohola** [PipedreamHQ/pipedream#6688]
**Describe the bug**
I have created a workflow following instructions from Thomas link is down below.
https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#create-a-pipedream-account-and-workflow
During testing, it works. After deployment, it throws an error. 
`Message:
you've exceeded the default memory for this workflow, see https://pipedream.com/docs/troubleshooting/#out-of-memory
Total Duration:
0 ms
Compute Time:
77,307 ms
Execution Start:
2023-05-30T00:39:07.256Z
Execution End:
null
Steps Executed:
0 / 8
Credits:
1
Version:
71 (d_dlsvNKBN)`

**To Reproduce**
1. Run the workflow in the test
2. Run the workflow after deployment by uploading an audio file to Dropbox to trigger an event.

**Expected behavior**
I expected to have a new entry in my Notion database

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave

**Comment by andrewjschuang** [comment]
Hi @RostyslavDzhohola, have you tried increasing your memory and timeout in your workflow settings?
