### ISSUE TITLE
[APP] SSLMate

### ISSUE THREAD

**Issue by leonardoamaaral** [PipedreamHQ/pipedream#6689]
**Name of app / service**
SSLMate
https://sslmate.com/

**Link to developer documentation**
https://sslmate.com/help/reference/apiv2

**Comment by vunguyenhung** [comment]
Hi @leonardo317, would you mind answering the questions in the description?

**Comment by sergio-eliot-rodriguez** [comment]
i located the website they refer too.
when users don't answer the questions it's common that the app name referred has ambiguity or can't be easily found with a regular search engine query.
sslmate came up in the results so i'm submitting this one and let @leonardo317 correct us

i've updated details

**Comment by sergio-eliot-rodriguez** [comment]
@leonardoamaaral if you are still interested, SSL Mate has been integrated https://pipedream.com/apps/sslmate-cert-spotter-api?via=go
