### ISSUE TITLE
[FEATURE] I want to use Supabase actions with auth tokens provided in a previous step

### ISSUE THREAD

**Issue by tomilagom** [PipedreamHQ/pipedream#6690]
I have a front-end where a user log-in with Supabase authentication. I want that user to interact with workflows from Pipedream, checking authentication before a row update (for example)

**Do you have a workaround?**
I created a "check_authentication" postgre function in supabase to do some "next steps" once I know who is the user. 
Also, I do an HTTP REST (not supabase actions) request with the same token I received from the trigger. Because the Supabase actions use admin credentials.

**Comment by vunguyenhung** [comment]
Hi @tomilagom, 

Currently, Pipedream Supabase action will use your configured account by default, and you can not change the account at run time. The only workaround for now is to manually setup a code step or HTTP action (as you're currently doing now) and pass in the credentials from your previous step.

Hence, I will close this ticket.
