### ISSUE TITLE
[ACTION] Readwise Highlight Detail (e.g. author, source, website, etc) pull to Pipedream?

### ISSUE THREAD

**Issue by gitnoobz** [PipedreamHQ/pipedream#6695]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by vunguyenhung** [comment]
Hello @gitnoobz,

Pipedream currently offer Readwise Get Highlight details here
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/2f83430d-84d7-4975-a2dc-ffecf101e04e)

Could you share exactly what additional do you need, and also the API docs for it? Thanks

**Comment by gitnoobz** [comment]
@vunguyenhung I need the web or document URL source of the source, author, etc. Things that are in the metadata of readwise.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
