### ISSUE TITLE
[TRIGGER]

### ISSUE THREAD

**Issue by JehadurRE** [PipedreamHQ/pipedream#6701]
Retrieve Course Names from Google Classroom and Add as Block to Parent in Notion

Description:
I would like to request a feature that retrieves course names from Google Classroom and adds them as blocks to a parent in Notion. This integration would streamline the process of syncing course information between Google Classroom and Notion.

**Comment by vunguyenhung** [comment]
Hi @JehadurRE, the ticket is for implementing the single action/trigger. Do you mean that you want a new trigger whenever there is a new course?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
