### ISSUE TITLE
[FEATURE] Add DimensionFilter to Google Analytics: Run Report in G4A action

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6724]
**Is your feature request related to a problem? Please describe.**
Google Analytics: Run Report in G4A action currently doesn't have [the DimensionFilter param](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#http)

**Describe the solution you'd like**
Add a new DimensionFilter prop that matched [the DimensionFilter param](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#http)

**Do you have a workaround?**
Google Analytics API

**Additional context**
Reported by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1685580940400759

**Comment by vunguyenhung** [comment]
For customer, please [read this doc](https://developers.google.com/analytics/devguides/reporting/data/v1/basics#dimension_filters) to understand how to put the values to the DimensionFilter. 

Sample test case:
![22 34 24 - 01 - 06 - 2023](https://github.com/PipedreamHQ/pipedream/assets/18277920/979d1118-92a9-4daa-84e4-31ab6e8a8aed)

Sample DimensionFilter:
```
{{ {
      "filter": {
        "fieldName": "eventName",
        "stringFilter": {
          "value": "first_open"
        }
      }
    } }}
```

**Comment by tom-galland** [comment]
Thank you - extremely quick fix
