### ISSUE TITLE
[APP] Missive

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#6740]
**Name of app / service**
Missive

**Link to developer documentation**
https://missiveapp.com/help/api-documentation/getting-started

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
@todsac missive doesn't have api access enabled on the free plan, if you have a way to get API access please share. For now, I have requested access to missive's support handle.

**Comment by sergio-eliot-rodriguez** [comment]
This has been submitted for App Store approval

**Comment by sergio-eliot-rodriguez** [comment]
Basic app integration at: https://pipedream.com/apps/missive
