### ISSUE TITLE
Google Chat [APP]

### ISSUE THREAD

**Issue by DominikBeeBop** [PipedreamHQ/pipedream#6741]
**Name of app / service**
Google Chat
**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
hi @DominikBeeBop 
we are tracking google chat at https://github.com/PipedreamHQ/pipedream/issues/1322, feel free to fllow, if you'd like
