### ISSUE TITLE
[BUG] SendGrid - Remove Contact from List throws error Unexpected token '?.'

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6744]
**Describe the bug**
When I passed in array in the custom expression to the prop `Contact IDs` or `Contact Emails`, it throws `error Unexpected token '?.'`
<img width="821" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/4619dba9-31e7-4f53-a9c4-411659e16c9b">
<img width="826" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/1fcb69f0-2342-4964-a3eb-727bb2d6e469">

**Expected behavior**
I should be able to pass custom expression to the prop `Contact IDs` or `Contact Emails`

**Additional context**
Reported by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1685682579628429

**Comment by dylburger** [comment]
This was fixed as of June 4th.
