### ISSUE TITLE
[APP] Microsoft OneNote

### ISSUE THREAD

**Issue by sev7enITA** [PipedreamHQ/pipedream#6756]
Microsoft OneNote

https://learn.microsoft.com/en-us/office/client-developer/onenote/onenote-developer-reference

The integration is not available. 

Create a vocal note via OneNote then use ChatGPT integration for translation

**Comment by sergio-eliot-rodriguez** [comment]
OneNote is pending approval, we are tracking it at: https://github.com/PipedreamHQ/pipedream/issues/6682
