### ISSUE TITLE
[TRIGGER] New Google Tasks Triggers

### ISSUE THREAD

**Issue by duttaoindril** [PipedreamHQ/pipedream#6762]
Google Tasks

[Link to developer documentation](https://developers.google.com/tasks)

Yes - I want to create a workflow on the creation of a task - Google Tasks as a Trigger - No way to create an automation without a trigger

On a task being created or marked as completed, trigger a workflow

**Comment by dhruvspathak** [comment]
Hey there, I would love to contribute to this task. Can you provide me with more information on this?

**Comment by sergio-eliot-rodriguez** [comment]
Google Tasks was previously integrated https://pipedream.com/apps/google-tasks
