### ISSUE TITLE
[BUG] Twitter throwing up 429 errors at random

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#6764]
**Describe the bug**
Whenever a workflow runs over the last week or so if I'm posting to Twitter I get a 50/50 chance of it throwing up a 429 error. I would understand it if I was hammering the API heavily, however, this happens even on the 1st post I have made that day. I assume it's Twitter limiting the Pipedream IP address.

```
Error
Request failed with status code 429 

    at null.createError (/pipedream/dist/code/dc814cd6c59810cf4a607e0a3ac5245f045d05e818bbbf1cb7e096aea9654f2c/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/createError.js:16:15)
    at null.settle (/pipedream/dist/code/dc814cd6c59810cf4a607e0a3ac5245f045d05e818bbbf1cb7e096aea9654f2c/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/pipedream/dist/code/dc814cd6c59810cf4a607e0a3ac5245f045d05e818bbbf1cb7e096aea9654f2c/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at null.endReadableNT (internal/streams/readable.js:1333:12)
    at process.processTicksAndRejections (internal/process/task_queues.js:82:21)

````

**To Reproduce**
1. Make a workflow with Twitter > Create Tweet
2. Run and see what happens

**Expected behavior**
Should not be getting 429 errors unless I was hammering the API with my workflows

**Comment by vunguyenhung** [comment]
Hi @NebularNerd, I believe this is outside of Pipedream control so we can not fix it completely. 

I think what you can do to workaround it is to enable the new [auto retry feature](https://pipedream.com/docs/workflows/settings/#error-handling) to have your action if it failed. Or you can do it via code step. Would you mind giving it a try?

**Comment by NebularNerd** [comment]
Hi @vunguyenhung, I guessed it was a Twitter thing (again) rather than a Pipedream issue but wanted to bring it to your attention. I'm only on the free tier so I cannot try the auto retry feature. I might try adjusting the workflow to run early in the morning UK time as this seems to be when there is the most success. If that does not help I think I have another plan or two that will get me round this.

**Comment by dannyroosevelt** [comment]
Anecdotally, we've also seen the 429 issue quite frequently on both free and paid Twitter accounts, with **very** low volume requests...

**Comment by NebularNerd** [comment]
Luckily I keep Twitter as the last step in my workflows for much this reason, if any step will fail it's normally Twitter.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
@NebularNerd this may have actually been related to an internal issue on our end after all. Did you recently get prompted to reconnect your account? Have you seen this still happening in the last few days?

**Comment by NebularNerd** [comment]
Hi @dannyroosevelt I last reconnected back when Musk broke all the API's and you guys fixed it. I think from the sounds of things it was just Twitter having a funny moment. I've not tested it recently as other aspects of my business have prevented me creating products which triggers the workflow.

If it comes up again I'll open a new ticket.

Thanks as always 😁
