### ISSUE TITLE
[Components] CleverReach

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6768]
### App
CleverReach
https://www.cleverreach.com/

**Triggers:**
https://rest.cleverreach.com/howto/webhooks.php
1. New Subscriber Added
2. New unsubscribe event

**Actions:**
https://rest.cleverreach.com/howto/#basics
1. Create Subscriber: Add a new subscriber to a mailing list.
2. Update Subscriber: Update the information of an existing subscriber.

**Comment by GTFalcao** [comment]
@vunguyenhung I found another section of documentation, but it is still not clear (at all) on the available fields. It lists some examples, so I added a link to the documentation in the "additional data" prop, and included some fields that are working as expected as props.

Fields such as "firstname" and "lastname" are being ignored completely by the API, in the format documented and in similar formats I experimented with, so I did not include them as separate props.
