### ISSUE TITLE
[Components] Firmao

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6769]
### App
Firmao
https://firmao.net/

Triggers:
1. New Customer
2. New Task
3. New Sales Opportunity

Actions:
1. Create Customer
2. Create Sales Opportunity
3. Create Task

Documentation:
https://firmao.net/api.php

**Comment by alysonturing** [comment]
@vunguyenhung I'm sorry, I moved the prop to the app file and forgot to change the method reference..., I took the time to change some props to optional (wasn't referenced on firmao docs so I had to try one by one), and, I added a new action `list-tasks`... thank you
