### ISSUE TITLE
[Components] PhoneBurner

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6777]
### App
PhoneBurner
https://www.phoneburner.com/

**Actions:**
1. Create Contact: Add a new contact to the PhoneBurner system.
2. Update Contact: Modify an existing contact's details.
3. List contacts
4. Get a contact
https://www.phoneburner.com/developer/route_list#contacts

**Comment by lcaresia** [comment]
@malexanderlim Moved to blocked because is need a call to request demo.

**Comment by malexanderlim** [comment]
@lcaresia do the credentials in the 1P vault not work?
