### ISSUE TITLE
[BUG] Slack Bot - New Direct Message source - Channel ID props throws error An API error occurred: missing_scope even when needed scopes are added

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6778]
**Describe the bug**
I have setup a Slack bot with the following scopes
<img width="473" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/b04ce445-628b-4ab9-b3f2-c99beb7f5bb9">
[channels:manage](https://api.slack.com/scopes/channels:manage)
[channels:read](https://api.slack.com/scopes/channels:read)
[groups:read](https://api.slack.com/scopes/groups:read)
[im:read](https://api.slack.com/scopes/im:read)
[mpim:read](https://api.slack.com/scopes/mpim:read)
[users:write](https://api.slack.com/scopes/users:write)

Then I install the app into my test workspace
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/6a883347-c3d8-42a0-ac95-d4962e8f8388)

Then I try to create a source, but the Channel ID prop show the error, even when I have added [all scopes defined in the doc here](https://api.slack.com/methods/conversations.list) 
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/6130a661-f161-4020-8833-f9fce40673c6)

**Expected behavior**
- The Channel ID prop should load when I added all scopes required
- The source description should show all scopes needed for the source to function properly

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1686038705929739

**Comment by lcaresia** [comment]
@vunguyenhung Hey, I think this missing scopes error is related with Slack component scopes and not the bot scopes, makes sense to you?

Cc: @dannyroosevelt

**Comment by michelle0927** [comment]
@vunguyenhung Are you sure you entered the correct bot token when connecting the account in Pipedream? I was able to reproduce the error by entering my "User OAuth Token" instead of my "Bot User OAuth Token".

<img width="655" alt="Screenshot 2023-06-06 at 2 36 04 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/4f42c69b-c4d1-4771-b92a-dad49e822986">

**Comment by dannyroosevelt** [comment]
> @vunguyenhung Hey, I think this missing scopes error is related with Slack component scopes and not the bot scopes, makes sense to you?
> 
> Cc: @dannyroosevelt

@lcaresia how would this be related to the Slack app?

**Comment by lcaresia** [comment]
@dannyroosevelt Sorry, I made confusion about this task.

**Comment by vunguyenhung** [comment]
Hi @michelle0927, I used the Bot User OAuth Token: 
![10 46 43 - 07 - 06 - 2023](https://github.com/PipedreamHQ/pipedream/assets/18277920/73dd1bd0-558b-4ac6-9f3d-dd53b1f87a70)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/fc64a60d-eef3-46fc-9200-7206688db358)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/e9c81fd3-ae1b-492a-a776-e0282a7e2112)
