### ISSUE TITLE
[Components] SurveySparrow

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6784]
### App
SurveySparrow
https://surveysparrow.com/

Triggers:
1. Survey Completed: Trigger when a respondent finishes a survey.
2. New Survey Response: Trigger when there is a new individual response to a survey.

Actions:
1. Create Survey: Create a new survey in SurveySparrow account.
2. Add Contact: Add a contact into an existing contact list or create a new one.
3. Send Survey Email: Send an email to a specific contact with a survey link.

_This list of suggested components was generated using ChatGPT_

**Comment by sergio-eliot-rodriguez** [comment]
FYI SurveySparrow extended the trial account (on email sergio at pipekit dot pro) for 14 days more, and are keen to enable any upgrade plan feature, in case this becomes a blocker during component dev:

> Hi Sergio,
> 
> I hope this message finds you well. I wanted to inform you that I have checked your trial account and noticed that it is scheduled to end in the next two days. However, I have taken the liberty to extend the trial period for an additional 14 days, giving you more time to explore our platform.
> 
> To ensure a smooth experience, I have included our solution engineer, Vijai, in this conversation. Vijai will be available to provide you with any technical assistance you may require during your trial.
> 
> If you encounter any feature or use case that prompts an upgrade requirement, please don't hesitate to inform us. We will be happy to enable it for you from the backend. Additionally, it would be beneficial for us to schedule a call to discuss your specific use...
