### ISSUE TITLE
[Components] Teachable

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6785]
### App
Teachable
https://teachable.com/

Actions:
1. Search students
https://docs.teachable.com/reference/listusers
2. Create a student
https://docs.teachable.com/reference/createuser
3. Update a student 
https://docs.teachable.com/reference/updateuser

**Comment by malexanderlim** [comment]
Account connection errors should now be resolved, @michelle0927 - thank you for surfacing the blocker.
