### ISSUE TITLE
[Components] GoToWebinar

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6786]
### App
GoToWebinar
https://www.goto.com/webinar

**Triggers:**
Type of event for the webhook. Supported eventNames are registrant.added, registrant.joined, webinar.created, webinar.changed
1. Registrant joined
https://developer.goto.com/GoToWebinarV2/#operation/createWebhooks
2. Registrant added  
https://developer.goto.com/GoToWebinarV2/#operation/createWebhooks

**Actions:**
1. Create Webinar: Creates a new webinar with the specified details.
https://developer.goto.com/GoToWebinarV2/#operation/createWebinar
2. Create registrant 
https://developer.goto.com/GoToWebinarV2/#operation/createRegistrant

**Comment by dannyroosevelt** [comment]
cc @malexanderlim

**Comment by malexanderlim** [comment]
Reached out to GoToWebinar support, and will follow back up Leo.
