### ISSUE TITLE
[TRIGGER] Can we make trigger in outlook only from specific email address?

### ISSUE THREAD

**Issue by gitnoobz** [PipedreamHQ/pipedream#6793]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
How to make event trigger only from specific email inbound at Microsoft Outlook?

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

**Comment by vunguyenhung** [comment]
Hi @gitnoobz, I'm not quite understand what you want, could you give discrete examples?

**Comment by gitnoobz** [comment]
I want my pipedream to be only triggered NOT when ANY email is received, but just from specific email address such as xxx@gmail.com, abc@gmail.com and xyz@gmail.com. I want to make a summary automation for only specific emails

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
