### ISSUE TITLE
[BUG] Invalid optional chain from new expression

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#6794]
**Describe the bug**
I have a workflow with a custom node action.
This action uses a string prop representing a date.
The prop input is set to `{{Intl.DateTimeFormat('fr-FR').format(new Date(steps.trigger.event.valueDate))}}`.
The value of `steps.trigger.event.valueDate` is `2023-06-06`

When the action is run, I have the following error:

> SyntaxError: Invalid optional chain from new expression
    at _pd_deep_evaluate (/var/task/params_evaluator.js:62:60)
    at MessagePort.<anonymous> (/var/task/params_evaluator.js:11:9)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)

It used to work until yesterday.

**To Reproduce**
1. Create a component with string prop
2. Set the prop input to `{{Intl.DateTimeFormat('fr-FR').format(new Date("2023-06-06"))}}`
3. Test the action

**Expected behavior**
Prop value must be `06/06/2023`

**Comment by alysonturing** [comment]
@LucBerge I had the same issue here and ended up with this working around: 
`{{Intl.DateTimeFormat('fr-FR').format(Date.parse("2023-06-06"))}}`

**Comment by LucBerge** [comment]
Works like a charm.
