### ISSUE TITLE
[BUG] Hubspot not importing all fields

### ISSUE THREAD

**Issue by vexersa** [PipedreamHQ/pipedream#6795]
**Describe the bug**
Connect Hubspot as an account and wait for a contact to be imported. Not all fields will be present.

**To Reproduce**
1. Add Hubspot account
2. Wait for contact to be imported
3. Compare fields imported vs fields in Hubspot, there will likely be a discrepancy

**Expected behavior**
All fields imported.

**Screenshots**
Not really applicable. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 113.0.5672.127

**Additional context**
Use case: Facebook lead gen forms to Hubspot, imported into Pipedream for use elsewhere.

For context Facebook ads a section to Hubspot contacts for Lead Ads like below: 

![image](https://github.com/PipedreamHQ/pipedream/assets/7994227/f3f9bf66-25ca-4205-ad10-9f75471441e1)

This data is not imported by Pipedream.

**Comment by vexersa** [comment]
Just tested this with LinkedIn Lead Form ads, too, and the issue is definitely that the "Lead Ad Properties" section of the Hubspot contact does get pulled through.

**Comment by vunguyenhung** [comment]
Hi @vexersa, may I ask what specific Pipedream hubspot source/action you're referring to? I'm not sure I understand you reproduce steps

**Comment by vunguyenhung** [comment]
Hi @michelle0927, when you have time, could you check this? I think we might need to include other properties in our API to fetch the contacta

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
