### ISSUE TITLE
[APP] Memberful

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6799]
**Name of app / service**
Memberful 
https://memberful.com/

**Link to developer documentation**
https://memberful.com/help/custom-development-and-api/memberful-api/

**notes on outreach**
by email, cc sergio at pk, integrations at pd

**Comment by malexanderlim** [comment]
Tracking component development in https://github.com/PipedreamHQ/pipedream/issues/6819
