### ISSUE TITLE
canva

### ISSUE THREAD

**Issue by MIKYONS** [PipedreamHQ/pipedream#681]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Do you have a workaround?**
Are you able to tackle the problem with an existing workaround, or can you not move forward without this feature?

**Comparable features in other tools?**
Is this feature or one like it available in another platform? If so, we'd love to hear what you like about that implementation.

**Additional context**

**Comment by todsac** [comment]
@MIKYONS - this may have been closed by mistake.  are you requesting an integration with the app Canva?  If so, can you provide a bit more detail about your use case?  They have a few integration options so want to make sure we understand the request.

**Comment by malexanderlim** [comment]
@MIKYONS, we've officially launched support for Canva on Pipedream as of today - feel free to check out our app [here](https://pipedream.com/apps/canva), and we are open to any feedback that you may have as well! 

If you are on a Canva Enterprise plan, we're about to roll out support for Canva's enterprise-level features, including as the ability to create designs based on your brand templates.
