### ISSUE TITLE
binance[APP]

### ISSUE THREAD

**Issue by Parth8024** [PipedreamHQ/pipedream#6817]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
hello @Parth8024 
we are tracking Binance at https://github.com/PipedreamHQ/pipedream/issues/5368, feel free to follow, if you'd like
