### ISSUE TITLE
[Components] Memberful

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6819]
### App
Memberful
https://memberful.com/help/custom-development-and-api/memberful-api/

Triggers:
1. New Member
2. New Subscription Created
3. Subscription Deactivated
4. Order Refunded

**Comment by malexanderlim** [comment]
Hi @vellames , account details are present in 1Pass vault.

**Comment by vellames** [comment]
@malexanderlim Trying to link an account using credentials in OneLogin.
I am able to login, but not able to link account

![Screen Shot 2023-08-22 at 09 48 36](https://github.com/PipedreamHQ/pipedream/assets/91911778/672cacc2-3b90-4a9b-a578-b46df6f90ba1)

**Comment by malexanderlim** [comment]
Fixed the authentication issues. @vellames please feel free to try again, thanks for highlighting the blocker!

**Comment by vellames** [comment]
It was created as one single source that can be used to handle all webhook events in Memberful

**Comment by vellames** [comment]
@malexanderlim Btw. I don't think we need an API Key at this moment. I am not using it

**Comment by dannyroosevelt** [comment]
> It was created as one single source that can be used to handle all webhook events in Memberful

@vellames instead of a single "new webhook event" source, we should publish individual sources for each of the events listed in the ticket. That model is typically more user-friendly and tends to capture the 80% use case for our customers.

Let me know if you have questions.

cc @malexanderlim
