### ISSUE TITLE
[FEATURE] I want to select emit channels from sources / workflows as workflow triggers in the UI

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#682]
Currently, if I use `$send.emit()` to emit events from a workflow, I don't see those emitted events when adding a workflow trigger. I'd like to be able to select emitted events as a workflow trigger from the UI.

**Comment by brkncoyot3** [comment]
+1

**Comment by wspies** [comment]
+1

**Comment by NReilingh** [comment]
In case one is curious about this, while you cannot currently create event subscriptions within the UI, subscriptions that you create via the API _are_ visible in the UI and events can be used to test and develop workflows, for example:

![image](https://user-images.githubusercontent.com/2458645/205945718-d909bfb1-acbd-4e53-89b1-394ed558222a.png)

**Comment by renattomachado** [comment]
+1.000

**Comment by Matt2012** [comment]
+1
This feels like it should be not that hard given the API already supports it and from a UI perspective there's no real configuration.

**Comment by dylburger** [comment]
This is now supported!

In the trigger selection menu, choose the **Pipedream** app.

Select the **Other Workflow Events** trigger:

<img width="448" alt="Screenshot 2023-10-30 at 12 08 49 PM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/ddfd2538-51a6-471f-96a3-3ccd73042303">

If you've [created a subscription via API](https://pipedream.com/docs/api/rest/#listen-for-events-from-another-source-or-workflow) or emitted events from a workflow using `$.send.emit` ([see docs](https://pipedream.com/docs/destinations/emit/#using-send-emit-in-workflows)), you should see that workflow in the list.

<img width="803" alt="Screenshot 2023-10-30 at 12 08 25 PM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/2a2a28dd-ff2d-46d3-a07f-7bc288102772">

Let us know if that works for y'all!

**Comment by joscha** [comment]
> This is now supported!
> 
> In the trigger selection menu, choose the **Pipedream** app.
> 
> Select the **Other Workflow Events** trigger:
> 
> <img alt="Screenshot 2023-10-30 at 12 08 49 PM" width="448" src="https://private-user-images.githubusercontent.com/242668/279169810-ddfd2538-51a6-471f-96a3-3ccd73042303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDE5MzksIm5iZiI6MTcxNTkwMTYzOSwicGF0aCI6Ii8yNDI2NjgvMjc5MTY5ODEwLWRkZmQyNTM4LTUxYTYtNDcxZi05NmEzLTNjY2Q3MzA0MjMwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMzIwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGEyOGY2MmI0YjAyMjkxZGYzODM2ODQxZjY3MGZkYjJjYTc2ZGQyZGNlYWI4ODVmNGFjYTM1YmEwMWIyMjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Dr17VtzR6EWPeSatQznilwyPpJqAMVD6905Y0Ep9Tkc">
> If you've [created a subscription via API](https://pipedream.com/docs/api/rest/#listen-for-events-from-another-source-or-workflow) or emitted events from a workflow using `$.send.emit` ([see docs](https://pipedream.com/docs/destinations/emit/#using-send-emit-in-workflows)), you should see that workflow in the list.
> 
> <img alt="Screenshot 2023-10-30 at 12 08 25 PM" width="803" src="https://private-user-images.githubusercontent.com/242668/279169860-2a2a28dd-ff2d-46d3-a07f-7bc288102772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDE5MzksIm5iZiI6MTcxNTkwMTYzOSwicGF0aCI6Ii8yNDI2NjgvMjc5MTY5ODYwLTJhMmEyOGRkLWZmMmQtNDZkMy1hMDdmLTdiYzI4ODEwMjc3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMzIwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDVjNzViNzhlZWEzMTJiNWQwYTA1ZTIzYmIwOTFjODcxZTk1Mjg5Mjg2MWZkOGY5ODk3MzBlYjNmN2ExODA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IUGKm4Z3ywwxPKDwh_jC3OmdsZCixKezPsWoBTjf6-E">
> Let us know if that works for y'all!

I can't see this particular trigger anymore in the UI:
<img width="638" alt="scan_-_Build_-_Pipedream" src="https://github.com/PipedreamHQ/pipedream/assets/188038/dce5b01a-f84b-4bd8-bbc0-51bec6ebc730">

is this still supported? Or do I have to create the trigger in a different way?

**Comment by joscha** [comment]
I tried to create a new subscription with an action in the emitting workflow and using the IDs of each workflows I want to tie together, but only get a cryptic error (`record not found`):

<img width="988" alt="Upload_File_in_Slack_for_deck_scan_-_Build_-_Pipedream" src="https://github.com/PipedreamHQ/pipedream/assets/188038/0bbc5d2e-54d5-476d-8b1c-ddc79bc82378">
