### ISSUE TITLE
[Components] Teamwork Desk

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6820]
### App
Teamwork Desk
https://apidocs.teamwork.com/docs/desk/870d18a4d4de4-teamwork-desk

Triggers:
1. New Ticket
2. New Customer 
3. New Customer Reply

Actions:
1. Find or Create Customer
2. Find or Create Ticket
3. Update Customer
4. Create Customer
5. Create Ticket
6. Reply to Ticket

**Comment by vunguyenhung** [comment]
Hi, I couldn't connect to my Teamwork desk account
<img width="1728" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/35623314-f4de-4b13-b4d9-bb968d9689ed">
<img width="712" alt="Screenshot 2023-06-18 at 13 10 07" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/afc9aea7-1a68-474d-8d4c-501227fd6641">
<img width="1727" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/5e056aa1-6f5b-4fe9-95ae-f9b2cd4a1ff1">

@sergio-eliot-rodriguez, would you mind checking again? The credentials is in 1password

**Comment by vunguyenhung** [comment]
Thanks @luancazarine, moving it back to In QA

**Comment by vunguyenhung** [comment]
Hello everyone, I have tested this PR and there're some test cases failed or needed improvement. 

Please check the test report below for more information
[Teamwork_Desk_6820_1007.pdf](https://github.com/PipedreamHQ/pipedream/files/11811852/Teamwork_Desk_6820_1007.pdf)
