### ISSUE TITLE
[Components] Google Tag Manager

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6845]
### App
Google Tag Manager
https://tagmanager.google.com/#/home

Triggers:
1. Container Published: Triggered when a new version of a container is published.
2. User Permission Changed: Activated when a user's permission level is updated.

Actions:
1. Create Container: Create a new container within a specified workspace. 
2. Update Trigger: Modify an existing trigger in a container.
3. Publish Workspace: Publish changes made within a specific workspace.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
Closing - duplicate of https://github.com/PipedreamHQ/pipedream/issues/6841
