### ISSUE TITLE
[Components] Facebook Pages

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6847]
### App
Facebook Pages
https://developers.facebook.com/docs/graph-api/reference/page/

Note: Page Access Tokens are required for any calls for API calls to manage Facebook Pages.
https://developers.facebook.com/docs/facebook-login/guides/access-tokens#pagetokens

**Actions:**
1. List Posts
2. Get Posts
3. Create a Post
4. Update a Post

5. List comments
6. Get a comment
7. Create a comment
8. Update a comment

9. Get a page
10. Update a page

**Comment by sumitshinde-84** [comment]
i would like work on this issue, can you please assign it to me ?
