### ISSUE TITLE
If statement calculation in Java

### ISSUE THREAD

**Issue by dasurendra** [PipedreamHQ/pipedream#685]
One or two meals $12.50 per meal plus the delivery charge .
More than two meals the cost of the extra meals will only be $7.50 per meal.
If the customer orders four meals or more then there will not be any delivery charge.

How can i calculate more thn 4 meals using if statement in java.

my code

import java.util.Scanner;

public class Week3
{
	static double Charge=9.50;
	static double Delivery=2.95;
	static double costOfExtra=7.50;

;
	public  static void main (String [] args)
	{

		Scanner rockyJohn=new Scanner(System.in);

		System.out.println("Please Eneter Customer name ==>");
		String customerName=rockyJohn.next();
		System.out.println("Enter the number of meal for "+ customerName +" ==>>");
		int numberOfMeal=rockyJohn.nextInt();

		double totalCharge=(numberOfMeal*Charge)+Delivery;

         double Charge2=(Delivery+Charge+Charge+costOfExtra);

		double More3=costOfExtra+Charge+Charge;

        if (numberOfMeal==3 && numberOfMeal<4 ){

			System.out.println("Total:" + Charge2);

	    } if(numberOfMeal>=4){
		      meal=Charge+Charge+costOfExtra+numberOfMeal;
		      }
	  else{
		    System.out.println("Total:-"+totalCharge);

}

		System.out.println("   -----Rocky Johns Resturant-----");
        System.out.println("Name:"+customerName);
        System.out.println("Number of Meals:"+numberOfMeal);
        System.out.println("Total Charge\n\n\n\n\n\n\n\n");

	}

}

**Comment by dylburger** [comment]
Hi @dasurendra , this is a forum for questions on https://pipedream.com. I’d recommend asking your question on StackOverflow or another Q&A site.
