### ISSUE TITLE
[FEATURE] Enhance test request featured for Rocket Chat in Pipedream marketplace

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6854]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Change the test request shown for Rocket Chat to use the [Get User's Info](https://developer.rocket.chat/reference/api/rest-api/endpoints/users-endpoints/get-users-info) endpoint, this helps to identify the account, when a user connects Rocket Chat to their Pipedream workspace.

**Comparable features in other tools?**
Guidelines for Project App Store, when adding new app integrations to the App Store, we ideally should use endpoints that help identify the account being connected. For an example, Zoom uses the /me endpoint to get users details: https://pipedream.com/apps/zoom

**Additional context**
Rocket Chat was added outside Project App Store scope. Currently Rocket Chat uses "permissions.listAll"
but using "users.info" would help better identify the connected account/user
compare:

`[{"_id":"access-permissions","_updatedAt":"2023-06-10T14:40:03.058Z","roles":["admin"]},{"_id":"access-setting-permissions","_updatedAt":"2023-06-10T14:40:03.080Z","roles":["admin"]},{"_id":"add-oauth-service","_updatedAt":"2023-06-10T14:40:03.086Z","roles":["admin"]},{"_id":"add-user-to-joined-room","_updatedAt":"2023-06-10T14:40:03.098Z","roles":["admin","owner","moderator"]},{"_id":"add-user-to-any-c-room","_updatedAt":"2023-06-10T14:40:03.105Z","roles":["admin"]},{"_id
...
..."

vs

```
{
	"user": {
		"_id": "initialuser",
		"createdAt": "2023-06-10T14:40:13.600Z",
		"services": {
			"loginToken": {
			},
			"password": true,
....
		},
		"type": "user",
		"active": true,
		"name": "pipedreamdev",
		"username": "pipedreamdev",
		"emails": [
			{
				"address": "sergio@pipekit.pro",
				"verified": true
			}
		],
...
	},
	"success": true
}

```

The following is a test request that could be shown for Rocket Chat using the users.getinfo endpoint:

```

    return await axios($, {
      url: `https://${this.rocket_chat.$auth.domain}/api/v1/users.info`,
      headers: {
        "X-Auth-Token": `${this.rocket_chat.$auth["X-Auth-Token"]}`,
        "X-User-Id": `${this.rocket_chat.$auth["X-User-Id"]}`,
      },
      params: {
        userId: this.rocket_chat.$auth["X-User-Id"]
      }
    })
```

I added UserId/Auth Token in Contractor's Vault. Currently the related Rocket Chat is on a 30 days free trial, in case you wanted to proceed with the change without creating a new account during this trial period.

**Comment by malexanderlim** [comment]
Hey @sergio-eliot-rodriguez , this is a good idea. There's actually an even better endpoint to use - https://developer.rocket.chat/reference/api/rest-api/endpoints/authentication-endpoints/me

I've updated this, thank you for flagging.

**Comment by sergio-eliot-rodriguez** [comment]
awesome!!
