### ISSUE TITLE
[OAUTH SCOPE] Jira 

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6864]
**Which application needs a scope added?**
Jira

**What scope(s) need to be added?**
- read:board-scope.admin:jira-software
- read:project:jira

**Please provide a link to the relevant API docs for scopes.**
https://developer.atlassian.com/cloud/jira/platform/scopes-for-oauth-2-3LO-and-forge-apps/

**Context**
Requested by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1686472967006349

**Comment by malexanderlim** [comment]
Confirming that the scopes requested have been added.
