### ISSUE TITLE
[Components] Google Chat

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#6866]
### App
Google Chat
https://workspace.google.com/products/chat/

Triggers:
1. Message Received: A new message is sent in a Google Chat room or direct message.
2. Mentioned in Message: The configured user or bot is mentioned in a Google Chat room or direct message.

Actions:
1. Send Message: Send a message to a Google Chat room or direct message.
2. Create Room: Create a new Google Chat room.
3. Add User to Room: Add a user to an existing Google Chat room.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
Duplicate, closing.
