### ISSUE TITLE
[ACTION] Forward HTTP request with no or minimal modification

### ISSUE THREAD

**Issue by tomngo** [PipedreamHQ/pipedream#6882]
**Is there a specific app this action is for?**

"HTTP / Webhook" 

**Desired Functionality**

Suppose a workflow's trigger is from the "HTTP / Webhook" app. This new action in that same app would simply forward the original request to a new URL, including all headers, parameters, and body. The following trivial workflow would then be a no-op: 

- Trigger: "HTTP / Webhook" - HTTP Requests (with full HTTP body) 
- Action: "HTTP / Webhook" - this new action

**Anticipated Usage**

A non-developer would start with a no-op workflow like that, and would interpose an additional action such as a delay, logging, or filter. 

**Roadmap Considerations**

If there is a need to keep the scope of this feature small, then support only POST with a JSON body.

If there is appetite to enhance the scope of this feature, an important enhancement would be the ability to let the non-developer configure the action with authentication to the final endpoint.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by dannyroosevelt** [comment]
@tomngo can you share more about the use case? It sounds like this could be accomplished pretty easily today. For example: https://pipedream.com/new?h=tch_OVdfaL

```
import { axios } from "@pipedream/platform"

export default defineComponent({
  async run({steps, $}) {
    return await axios($, {
      url: `https://some-other-url-here`,
      headers: steps.trigger.event.headers,
      params: steps.trigger.event.params,
      data: steps.trigger.event.body
    })
  },
})
```

**Comment by tomngo** [comment]
@dannyroosevelt Yes, of course this is trivial for a developer. My implementation is almost identical to what you wrote.

The important piece of my proposal is written in the Anticipated Usage section. For a non-developer, having a Lego block to forward an HTTP request after filtering events or mildly transforming event contents would satisfy needs that are frequent and valuable.

**Comment by dannyroosevelt** [comment]
FYI you can also do this using the HTTP action -- here's an updated example workflow:
https://pipedream.com/new?h=tch_OknfAy

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
