### ISSUE TITLE
[BUG] Google Drive API

### ISSUE THREAD

**Issue by sdotsamuel790** [PipedreamHQ/pipedream#6884]
**Describe the bug**
I used a PI-generated code to set the permissions of a folder based on email address. The code is supposed to produce three fields that I can fill out. When I fill out the fields and test them, I am given an error.

Here is the code:

```
import { axios } from "@pipedream/platform";

export default defineComponent({
  props: {
    google: {
      type: "app",
      app: "google",
    },
    folderId: {
      type: "string",
      label: "Folder ID",
    },
    userEmail: {
      type: "string",
      label: "User Email",
    },
  },
  async run({ steps, $ }) {
    const url = `https://www.googleapis.com/drive/v3/files/${this.folderId}/permissions`;
    const data = {
      role: "writer",
      type: "user",
      emailAddress: this.userEmail,
    };

    return await axios($, {
      method: "POST",
      url: url,
      data: data,
      headers: {
        Authorization: `Bearer ${this.google.$auth.oauth_access_token}`,
        "Content-Type": "application/json",
      },
    });
  },
});

```
The error says:

`{"error":{"code":404,"message":"File not found: 1oO98KKohK1hsdGPPbGD1tYTw1XGtL8i2.","errors":[{"message":"File not found: 1oO98KKohK1hsdGPPbGD1tYTw1XGtL8i2.","domain":"global","reason":"notFound","location":"fileId","locationType":"parameter"}]}}`

**To Reproduce**
1. Create a folder using Google Drive.
2. Create a folder.
3. Look at the URL of the folder and copy down the ID.
4. When you set up the fields for the first time, try using the PATH.
5. This is where it fails.
6. Go back and instead of using the PATH, hardcode the folder ID into the field.
7. This is where it also fails.

**Expected behavior**
The folder will be able to be written to by someone else.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 114.0.5735.110 (Official Build) (64-bit)

**Comment by vunguyenhung** [comment]
Hi @sdotsamuel790, I think it would make more sense to build the new action Google Drive - Create Permission instead of having you use the code. I have created [a ticket here to request here](https://github.com/PipedreamHQ/pipedream/issues/6889), please subscribe to the ticket to be noticed when the new action landed.

Since we already have the ticket, I will close this.
