### ISSUE TITLE
[FEATURE] Can you add Langchain to the knowledge base?

### ISSUE THREAD

**Issue by QuicksilverSlick** [PipedreamHQ/pipedream#6886]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Do you have a workaround?**
Are you able to tackle the problem with an existing workaround, or can you not move forward without this feature?

**Comparable features in other tools?**
Is this feature or one like it available in another platform? If so, we'd love to hear what you like about that implementation.

**Additional context**

**Comment by QuicksilverSlick** [comment]
Definitely would be helpful in building chat and agent functionality into the core asssets

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by QuicksilverSlick** [comment]
I am working on this and will update in a few days. Thank you !
