### ISSUE TITLE
Trigger from AWS SQS

### ISSUE THREAD

**Issue by Swieter** [PipedreamHQ/pipedream#6888]
My team has built a data pipeline on AWS Lambda.  Lambdas are attached to SQS messages.
We thought it might be nice to use Pipedream to monitor some status and timing across the pipeline and on pick messages off the bus.  Or to have lambdas emit specific messages for some out of band logging.  

So, being able to set up a trigger for a specific SQS message would be great.  A workaround right now is I set up a lambda that hits a Pipedream webhook.  

Just a thought, as we find Pipedream nice for some logging, reporting and bridging to other systems without clogging our production code running in lambdas, keep those focused on the specific tasks.

**Comment by vunguyenhung** [comment]
@Swieter, may I ask what specific status you want to have Pipedream source on? If it is specific for your usecase, I would suggest you use the current method of firing webhook to Pipedream. For this method, it would be more secure I would say

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
