### ISSUE TITLE
[ACTION]

### ISSUE THREAD

**Issue by scadadev** [PipedreamHQ/pipedream#6892]
**Is there a specific app this action is for?**
Basecamp
Task Updated trigger
**Please provide a link to the relevant API docs for the specific service / operation.**
https://github.com/basecamp/bc3-api

**Comment by Divyansh1908** [comment]
Hi , Can you elaborate the issue

**Comment by vunguyenhung** [comment]
Hi @scadadev, checking Pipedream Basecamp sources, I see that the Todo Webhook type will emit event when the todo completed, would you mind giving it a try?
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/19934274-cf98-4067-8918-ed2cb18a30b4)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
