### ISSUE TITLE
[TRIGGER / ACTION] Chatbot

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#69]
App: `chatbot`

### Triggers
- New message https://www.chatbot.com/docs/webhooks/

### Actions
- Create user https://www.chatbot.com/docs/users/#create-user
- List users https://www.chatbot.com/docs/users/#list-users

**Comment by lcaresia** [comment]
@dylburger or @dannyroosevelt Can you give me more details about this task? Thansk!

**Comment by dannyroosevelt** [comment]
> @dylburger or @dannyroosevelt Can you give me more details about this task? Thansk!

@lcaresia I just updated the ticket with some details and I'm adding `chatbot` as an app right now.

**Comment by dannyroosevelt** [comment]
This is ready for release!
