### ISSUE TITLE
[APP] SMSAPI

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#6905]
**Name of app / service**
SMSAPI
https://www.smsapi.com/

**Link to developer documentation**
https://www.smsapi.com/docs/#oauth2-webflow

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
Requested Oauth Clients, there is access via API Key based authentication

**Comment by sergio-eliot-rodriguez** [comment]
duplicated https://github.com/PipedreamHQ/pipedream/issues/6860
