### ISSUE TITLE
[FEATURE] Ability to search for a workflow by the public URL/ID

### ISSUE THREAD

**Issue by sethyates** [PipedreamHQ/pipedream#6908]
**Is your feature request related to a problem? Please describe.**
We have several webhooks configured in our system, and sometimes we don't help ourselves by keeping the webhook names consistent with the Pipedream workflow names, so it is hard to find the workflow just given the URL.

**Describe the solution you'd like**
I want to be able to paste in either the ID or the entire URL in the search bar on https://pipedream.com/workflows (either top search or search in left navigation bar) and find the workflow that handles that ID/URL.

**Do you have a workaround?**
Right now, I have to try and click through all of the workflows and find one that shows the ID.

**Comparable features in other tools?**
Unknown

**Comment by dylburger** [comment]
You can now search workflows by their URL from our global search UI! 

<img width="453" alt="Screenshot 2023-07-30 at 8 25 35 PM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/fc46aa15-e1df-4f31-b060-c9a0bfcafcba">

**Comment by sethyates** [comment]
Awesome. Thanks!
