### ISSUE TITLE
[BUG] Pipedream REST API - POST /subscription does not create subscription for Emitter ID p_* and dc_*

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6915]
**Describe the bug**
Pipedream REST API - POST /subscription does not create subscription for Emitter ID `p_*` and `dc_*`

**To Reproduce**
1. On Pipedream, login and select a workspace
2. Create a new workflow to add a subscription to, add a HTTP trigger, then deploy
<img width="1727" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/0e70f80a-5add-4e47-85c4-bca6754a9a99">
3. Call the REST API /subscription to register global error to the new workflow
<img width="1346" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/9f92e048-a0b7-46d1-8fd9-5381037d1d1a">
4. Observe that the response contains empty `data` object
5. On the global workflow, I do not see a new subscription.
<img width="1727" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/0e70f80a-5add-4e47-85c4-bca6754a9a99">

If the API works correctly, the response should contain data
<img width="1348" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/d0537590-4784-4a04-9098-88c8670616aa">
And the workflow should have another trigger registered
<img width="1348" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/57129f81-9991-42b7-8cf1-73858ddee355">

**Expected behavior**
The API should work with `p_*` and `dc_*`. The workflow should have another trigger registered, and all errors should emit an event to that workflow

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1686805228113299

**Comment by dylburger** [comment]
Should be fixed
