### ISSUE TITLE
[BUG]  Relative import path ascending further up directory tree causes pd dev command to fail

### ISSUE THREAD

**Issue by axmachina** [PipedreamHQ/pipedream#6927]
**Describe the bug**
When importing a module in a dev component using a relative path that ascends further up the directory tree, an unexpected error is thrown. The error message received is "component create api call responded with status: 500". The same module, when imported using a relative path that doesn't ascend as far, does not produce this error.

**To Reproduce**
1. Consider the following directory structure:
    ```
    ├── a
    │   └── c
    │       └── lib.mjs
    └── b
        └── c
            └── TestComponent.js
    ```
2. Open the `TestComponent.js` file located in `b/c` directory. Its source code is as follows:
    ```javascript
    // this works
    import lib from "../c/lib.mjs"
    // this results in unexpected error "component create api call responded with status: 500"
    // import lib from "../../a/c/lib.mjs"

    export default {
      name: "Test",
      key: "test",
      type: "source",
      methods: {},
      async run(event) {
        this.$emit(
          { event },
          {
            summary: lib.test(),
            ts: Date.now(),
          }
        );
      },
    };
    ```
3. Uncomment the line `import lib from "../../a/c/lib.mjs"` and comment out or remove the line `import lib from "../c/lib.mjs"`.
4. Save the changes and run the `TestComponent.js` file.
5. Deploy in dev with ```pd dev TestComponent.js```
7. The error "component create api call responded with status: 500" is thrown.

**Expected behavior**
The expected behavior is that the module should be imported successfully, regardless of how far up the directory tree the relative path ascends. After the import, the `Test` component should be able to execute its `run` method without any errors.

**Desktop (please complete the following information):**
- OS: [Your OS]
- Browser: [Your Browser]
- Version: [Your Version]

**Smartphone (please complete the following information):**
_N/A_

**Additional context**
This issue seems to be related to how the relative paths are being resolved in the `Test` component. The import works as expected when the relative path doesn't ascend as far up the directory tree, but throws an error when it does. This indicates that there may be a problem with how the paths are being interpreted or resolved when they ascend further up the directory tree.

**Comment by vunguyenhung** [comment]
Hi @axmachina, Pipedream has a [recommended way to develop your components](https://pipedream.com/docs/components/guidelines/#folder-structure), it is the best practices for implementing Pipedream components and only require you to have 1 directory level, would you mind taking a look?

**Comment by axmachina** [comment]
> Hi @axmachina, Pipedream has a [recommended way to develop your components](https://pipedream.com/docs/components/guidelines/#folder-structure), it is the best practices for implementing Pipedream components and only require you to have 1 directory level, would you mind taking a look?

Thanks, this is how I set it up in my repo. I just use a custom script to dev components. This is no longer an issue for me, just wanted to note it.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
