### ISSUE TITLE
[BUG] Error communicating with discord

### ISSUE THREAD

**Issue by Clausinho** [PipedreamHQ/pipedream#6944]
**Describe the bug**
Whenever a quick succession of messages come, pipedream seems to throw an error.
because I send my errors to discord, this errors out too.

**To Reproduce**
1. create a workflow with discord messaging
2. trigger it in quick succession
3. multipy this by triggering it with the onError api trigger

**Expected behavior**
No errors and a better error description

**Screenshots**
<img width="483" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/5921903/c8ad11c8-6c56-457e-87dc-a74855568326">
<img width="506" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/5921903/df66a3ef-a952-45b5-9744-fa3a1520f642">

## respective workflows
triggering workflow: https://pipedream.com/@fotodino/p_A2CoWGJ/
on Error workflow: https://pipedream.com/@fotodino/on-error-in-pipedream-p_zACAeOx/
all set for support to see them.

**Comment by vunguyenhung** [comment]
Hi @Clausinhom I suspect that you faced the Discord rate limit error when you fire too many messages in a row. Would you mind trying to [throttle your workflow execution](https://pipedream.com/docs/workflows/concurrency-and-throttling/#throttling-workflow-execution)?

**Comment by Clausinho** [comment]
> Hi @Clausinhom I suspect that you faced the Discord rate limit error when you fire too many messages in a row. Would you mind trying to [throttle your workflow execution](https://pipedream.com/docs/workflows/concurrency-and-throttling/#throttling-workflow-execution)?

hey @vunguyenhung thanks for the quick reply.
It doesn't really help and I would expect pipedream to adhere to discord ratelimit headers: see here:
https://discord.com/developers/docs/topics/rate-limits
```
X-RateLimit-Limit: 5
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1470173023
X-RateLimit-Reset-After: 1
X-RateLimit-Bucket: abcd1234
```
or atleast pass them or give an option to pass them?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by Clausinho** [comment]
> Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

What information would you like?
In my view, pipedream should respect discords rate limits, as they are set custom via a response object

**Comment by Clausinho** [comment]
@dylburger @vunguyenhung I can't reopen the issue sadly.

**Comment by Clausinho** [comment]
See https://pipedream.com/@fotodino/on-error-in-pipedream-p_zACAeOx/inspect/2T0jAXb4a7v2cfJpJQcJZ576ImA

where it still happens with a 3 minute delay for 1 workflow.
