### ISSUE TITLE
Cannot Import AssemblyAI from PyPi

### ISSUE THREAD

**Issue by gentoftech2** [PipedreamHQ/pipedream#6953]
ERROR
Command failed: pipreqs --force ERROR: Failed on file: /tmp/__pdg__/dist/code/158c7134876f733aaecf74ff2852c7344b49fea04729bfdb75a290b9e0c6a5ea/code.py Traceback (most recent call last): File "/var/lang/bin/pipreqs", line 8, in <module> sys.exit(main()) File "/var/lang/lib/python3.9/site-packages/pipreqs/pipreqs.py", line 528, in main init(args) File "/var/lang/lib/python3.9/site-packages/pipreqs/pipreqs.py", line 455, in init candidates = get_all_imports(input_path, File "/var/lang/lib/python3.9/site-packages/pipreqs/pipreqs.py", line 131, in get_all_imports raise exc File "/var/lang/lib/python3.9/site-packages/pipreqs/pipreqs.py", line 117, in get_all_imports tree = ast.parse(contents) File "/var/lang/lib/python3.9/ast.py", line 50, in parse return compile(source, filename, mode, flags, File "<unknown>", line 1 !pip install pyaudio ^ SyntaxError: invalid syntax
CODE Attempts

#1
# Import the AssemblyAI module
import assemblyai as aai

# Your API token is already set here
aai.settings.api_key = "46eced7ea23f4671904a6eda27d9e955"

transcriber = aai.Transcriber()
transcript_group = transcriber.transcribe_group(
        [
        "https://cdn.fireflies.ai/x5iIyOJQwNhWfCpV/audio.mp3?Expires=1685801041&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4uZmlyZWZsaWVzLmFpL3g1aUl5T0pRd05oV2ZDcFYvYXVkaW8ubXAzIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg1ODAxMDQxfX19XX0_&Signature=P~t3D5iY8WDiEYwPOF4DXnnxk1nsUtzSqPh4OH~wyLkGrSIMKwXJX6ZA1635PRBRrjYpcam1BmnofDfdSxpNeZK661juaocySixFcHh49ZkX~INQTZ3j-513-5IlSm2NdZKx2I37QJdmAfe7sB4bYa8CLwYafcVxBJY1eZqlLG7bz5wnUvQEs1ADzKyWROynR1dneEDoxFJNr~aTD52lmJl0g5KBirh0Xb8hMGdZ7PUO9IeKIDeZ15FsIlVMmHzXLfnjr6gHeI21p-bls1sHdWsnzvqmMKF75Tc949Li~uw4Z1L8DxNL-Ge~JGxsLdnHr~f898mMs17--E2G~CQOLQ__&Key-Pair-Id=K25ZJR0UZVF4CM",
        "https://cdn.fireflies.ai/PRqroP8Buw1Zle28/audio.mp3?Expires=1685831515&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4uZmlyZWZsaWVzLmFpL1BScXJvUDhCdXcxWmxlMjgvYXVkaW8ubXAzIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg1ODMxNTE1fX19XX0_&Signature=lcYCpzAEVIAuOsD~Hk9suKFNfEtIGTpkDuvzgFH2LinQL8ImstUV2brDvnCaTIQFJn7jZGjItcfre18pCeCxp~7s8LBA85ko0pUKG5JmuhWyOFkwni-Bv5A06o-riHUr7mAkbXDluWHJ3fJPjcnlIYjHakeAX67cJUuqhqQYLzSE~om2Ivwr1vfj~kHIj6q19xN8WFqNSWzr2rPjMCKLrUrHOxYx2fRlErJPlvMV5mIN6cnpIgveu0c~GquAxuLcK9XxQIXpeWM5Kz0kj0vSHxsAwmAUoToaAUjs~lmq8GrNMOBkWFeScJu9kUEpRG4kP~q1n1tH2GNf3mRsB1UTaw__&Key-Pair-Id=K25ZJR0UZVF4CM",
      "https://cdn.fireflies.ai/F5AM4T5Vm2Mn5FT2/audio.mp3?Expires=1685818794&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4uZmlyZWZsaWVzLmFpL0Y1QU00VDVWbTJNbjVGVDIvYXVkaW8ubXAzIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg1ODE4Nzk0fX19XX0_&Signature=obRimQysNH5jm2htIibgq~DcUa~6cmmQGc3T9ZwIsPFHh3W7METiZjSfN~Vnk9H46MC4sGtBNwE0TXSNE6sKw6MRYPX49iCNTb8B6bqLEv3xxkf4MCiSX~LdMBJl2FdY56aAK0zvI5kbciDGLT7Dau0IpbyYMXXM-sdUT1S2Hsh38W~donoDf--uqa-mnnMQGxqrtzYZiDjR5x6J-nK6wN69ZJsJU9CXOzfRb~7xaQIgCFS3DX~6ilj32bRGPTMZB8QoJ-dpBfvIJEpaVBVd5AIR8MZlB5u8qgunCP3v-mW8nwE5rFQYqQbt3b~Eh2IQh6eT-YzCROB3v9cd3TOprw__&Key-Pair-Id=K25ZJR0UZVF4CM",
    ],
)

summary = transcript_group.lemur.summarize(context="These are a series of same day recordings during which the topics of digital operations and rented digital operations infrastructure as a consulting business are discusssed.", answer_format="Please describe the concepts of digital operations & rented infrastructure, along with the pain points and problems they address. Use bullet points for the details.")

print(summary)
#2
import pyaudio
import assemblyai as aai

VideoLocation = pd.steps["trigger"]["event"]["body"]

transcriber = aai.Transcriber()
transcript = transcriber.transcribe(VideoLocation)

# ask some questions
questions = [
    aai.LemurQuestion(question="What is this discussion about?"),
    aai.LemurQuestion(question="Summarize the discussion to 5 bullet points"),
]

results = transcript.lemur.question(questions)

for result in results:
    print(f"Question: {result.question}")
    print(f"Answer: {result.answer}")

#3
!pip install pyaudio
!pip install assemblyai

VideoLocation = pd.steps["trigger"]["event"]["body"]

transcriber = aai.Transcriber()
transcript = transcriber.transcribe(VideoLocation)

# ask some questions
questions = [
    aai.LemurQuestion(question="What is this discussion about?"),
    aai.LemurQuestion(question="Summarize the discussion to 5 bullet points"),
]

results = transcript.lemur.question(questions)

for result in results:
    print(f"Question: {result.question}")
    print(f"Answer: {result.answer}")

**Comment by vunguyenhung** [comment]
Hi @gentoftech2, 

I think this library is currently not compatible with Pipedream. I created a new ticket here to have the AssemblyAI app to be integrated on Pipedream here https://github.com/PipedreamHQ/pipedream/issues/6968. After it is integrated, you should be able to use Code step to call to AssemblyAI API/methods. Could you also input the action you'd like to have for the AssemblyAI action?

I will close this ticket. Thanks

**Comment by gentoftech2** [comment]
Thank you! I'd like to be able to use all the transcription and language model
(Lemur) actions



[https://ci6.googleusercontent.com/proxy/26fNASo-T-2hZYGGxQQf6e-dh_2CzTRS_1uqABKlg3KG5s7emr366dbMLCF4xWkTxmgohpjCIVEF2HtQy9aWeuSVlwNIZYg9n5KvtJVXTMFOTJvbormiyy9z5WcKfjRoGHrVWAkw4psb3lQqDb7LS4TUcRmiwM2geLHSqFkiiozKGqwf5JRm--a2pM38EEOCNMkLXQSqhV10UMJS9SxCtNhap1sNTKPP-UmczEVb7ydUHXu5UoCaK_3clDC8DpbNIgMVEfYC8i6KAoCZkLhZ2lwMHlCWnwuYtdOolA0=s0-d-e1-ft#https://driftt.imgix.net/https%3A%2F%2Fs3.amazonaws.com%2Fcustomer-api-avatars-prod%2F222849%2Facafb1bb91bb97365cb5c370c0bf1f8245xzfpd7n5bz?fit=max&fm=png&h=200&w=200&s=9201b9c8274a913443fb0f45ff54765c]
Michael Greenberg
ClickDown [http://clickdown.xyz/] | Podcast360
[https://mailtrack.io/trace/link/13272713338a4429a212be4281f0a83f44c2a18d?url=http%3A%2F%2Fpodcasting360.com%2F&userId=2055100&signature=7cc696337acfde92] | Gentof.tech
[https://mailtrack.io/trace/link/209e6a87048410f5fecab20d6055464faafdfa46?url=http%3A%2F%2Fgentof.tech%2F&userId=2055100&signature=06efae3cf146e179]







[data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=3D]
