### ISSUE TITLE
[APP] TidyCal

### ISSUE THREAD

**Issue by blessingefkt** [PipedreamHQ/pipedream#6959]
**Name of app / service**
TidyCal

**Link to developer documentation**
https://tidycal.com/developer/docs/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
My current workaround is a custom coda pack, however their automations are limiting. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Actions:
Retrieve booking types
Retrieve bookings
Retrieve account information
Retrieve contacts

Triggers:
The public API does not support webhooks, but it seems like their Zapier integration does. However, a custom source to detect new bookings and canceled booking would be great.

**Comment by sergio-eliot-rodriguez** [comment]
Notes on outreach:
by email, copied integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Hi @blessingefkt  
TidayCal has been integrated https://pipedream.com/apps/tidycal
