### ISSUE TITLE
[SOURCE] Google Classroom API

### ISSUE THREAD

**Issue by derickledermann** [PipedreamHQ/pipedream#696]
**Describe the solution you'd like**
Add Google Classroom to the list of integrations

**Do you have a workaround?**
I can send HTTP requests, but it would be more convenient if the Classroom API was already integrated with Pipedream.

**Additional context**
Documentation: [https://developers.google.com/classroom/reference/rest](https://developers.google.com/classroom/reference/rest)

**Comment by derickledermann** [comment]
(Sorry if this request wasn't submitted correctly. I'm new to this. Thanks!)

**Comment by dylburger** [comment]
This does give us enough information and we'll look into it ASAP @derickledermann . Thanks!

**Comment by derickledermann** [comment]
> This does give us enough information and we'll look into it ASAP @derickledermann . Thanks!

Thank you! With most schools teaching remotely until the foreseeable future, it's honestly shocking that not a single Workflow/Automation company has added Google Classroom to their long list of supported integrations. The EduTech Industry is growing faster than ever. There is a huge untapped market of teachers and school districts who are looking for ways to automate tasks and integrate the various platforms we use daily. Pipedream could attract a lot of new customers by being the first automation service to support Google Classroom. Just a thought :) I look forward to any updates.

**Comment by todsac** [comment]
@derickledermann - i have a working version of the Google Classroom integration.  What scopes would you expect to have for this app?  There are quite a few options and we aren't familiar with your use cases.  

https://pipedream.com/@tod/google-classroom-integration-example-p_KwC1wyN

Please let us know your thoughts and I can add scopes as needed. The current scope is only:
https://www.googleapis.com/auth/classroom.rosters.readonly

**Comment by todsac** [comment]
I added a bunch more scopes (see below) and am closing this issue for now.

Scopes:
https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly
https://www.googleapis.com/auth/classroom.rosters.readonly
https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly
https://www.googleapis.com/auth/classroom.topics.readonly
https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly
https://www.googleapis.com/auth/classroom.course-work.readonly
https://www.googleapis.com/auth/classroom.student-submissions.students.readonly
https://www.googleapis.com/auth/classroom.student-submissions.me.readonly
https://www.googleapis.com/auth/classroom.announcements.readonly
https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly
https://www.googleapis.com/auth/classroom.coursework.me
