### ISSUE TITLE
[TRIGGER] Stripe

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#6999]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Stripe

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://stripe.com/docs/api/events/types

**Triggers**
1. New Customer
2. New Subscription 
3. Subscription Updated
4. New Payment
5. New Invoice
6. New Dispute
7. Failed Payment
8. Failed Invoice Payment
9. Canceled Subscription

**Comment by lorinaX** [comment]
What is the issue if you could explain it a little further more?

**Comment by malexanderlim** [comment]
This is a request to our Pipedream component development team to build out new standalone triggers for the Stripe app.
