### ISSUE TITLE
[APP] ColdStream

### ISSUE THREAD

**Issue by alex-zinevich** [PipedreamHQ/pipedream#7010]
**Name of app / service**
ColdStream
https://coldstream.diabatix.com/

**Link to developer documentation**
https://case.coldstream.diabatix.com/swagger

**Comment by sergio-eliot-rodriguez** [comment]
Here's API reference at readme.io

https://coldstream.readme.io/reference/getting-started-with-your-api

**Comment by sergio-eliot-rodriguez** [comment]
Hi @alex-zinevich 
ColdStream has been previously integrated https://pipedream.com/apps/diabatix-coldstream?via=go
