### ISSUE TITLE
cloudflare r2

### ISSUE THREAD

**Issue by wetarorg** [PipedreamHQ/pipedream#7011]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi there @puvisites 

could you please provide more details on what you are looking for?

Here's an integration for Cloudflare. https://pipedream.com/apps/cloudflare-api-key 
What do you mean R2 though? Please kindly elaborate.

Thanks,

**Comment by puvisites** [comment]
It works on POSTMAN finely..

Struggling to integrate with pipedream

https://www.postman.com/api-evangelist/workspace/cloudflare/documentation/35240-d76987fb-f2f9-425d-9645-ecebd487c07d

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the details, we'll take a look real soon

**Comment by puvisites** [comment]
Hoping to use it.. thank you

**Comment by sergio-eliot-rodriguez** [comment]
for maintainers: creating an account requires cc. using test cc for integrations currently failed.

**Comment by sergio-eliot-rodriguez** [comment]
hello @puvisites,

currently building the integration is on progress.

because cloudflare r2 is compatible with aws s3 buckets, you can use the aws sdk to work with cloudflare r2, here is an example of an aws sdk client instance listing buckets on a cloudflare 2 account:

> import { S3 } from "@aws-sdk/client-s3";
> import { ListBucketsCommand  } from "@aws-sdk/client-s3";
> 
> export default defineComponent({
>   async run({ steps, $ }) {
> 
>     const cloudflare_r2 = {
>       account_id: "1b4abc43b13c2946a1c672aabac87fa7",
>       access_key_id: "baad90f30e8f61679802a993f7fea5f3",
>       access_key_secret: "d39883e2aef6ff28e3b8722b206e242eca5c3286807fedbb6cbfd69a9d231a5a"
>     };
> 
>     const s3Client = new S3({
>         forcePathStyle: false, 
>         endpoint: `https://${cloudflare_r2.account_id}.r2.cloudflarestorage.com`, 
>         region: "auto",
>         credentials: {
>           accessKeyId: cloudflare_r2.access_key_id,
>           secretAccessKey: cloudflare_r2.access_key_secret
>         }
>     });
> 
>     const data = await s3Client.send(new ListBucketsCommand({}));
>     return data.Buckets;
>   },
> }) 

alternatively, you can use the DigitalOcean Spaces app. when you connect it, just enter your cloudflare r2 access keys when connecting, 
and replace

endpoint with your cloudflare r2 bucket url, and set region to `auto`

**Comment by puvisites** [comment]
Hi .Thanks for the code.. I entered the code.. it shows no error..
But it doesn't to put the object received from the webhook in previous step

**Comment by puvisites** [comment]
To cloudflare R2.. some how arrived this .. still could not solve ..

import { S3, PutObjectCommand } from "@aws-sdk/client-s3";
import fetch from "node-fetch";

export default defineComponent({
  async run(event) {
    const cloudflare_r2 = {
      account_id: "fbbcf339e13ebe7692a37caa0b36175a",
      access_key_id: "af391f2e6de5a3cc266e467234707b14",
      access_key_secret: "fe45534fcafd48444ec23f3ca883e0e21d24c9c39bedc1375bc70372e8456654"
    };

    const s3Client = new S3({
      forcePathStyle: false,
      endpoint: `https://fbbcf339e13ebe7692a37caa0b36175a.r2.cloudflarestorage.com/puvi`,
      region: "auto",
      credentials: {
        accessKeyId: cloudflare_r2.access_key_id,
        secretAccessKey: cloudflare_r2.access_key_secret
      }
    });

    const bucketName = "your-bucket-name";
    const objectKey = "your-object-key";
    const objectUrl = event.body.file.url; // Assuming the file URL is in the `url` property of the Pipedream event body

    try {
      // Fetch the file from the URL
      const response = await fetch(objectUrl);
      const fileData = await response.buffer();

      // Upload the file to S3
      const putObjectCommand = new PutObjectCommand({
        Bucket: bucketName,
        Key: objectKey,
        Body: fileData,
        ContentType: 'image/jpeg',
      });

      const uploadResponse = await s3Client.send(putObjectCommand);
      console.log("Object uploaded successfully:", uploadResponse);
    } catch (error) {
      console.error("Error uploading object:", error);
    }
  },
});

**Comment by sergio-eliot-rodriguez** [comment]
```
    const bucketName = "pipedream-test";
    const objectKey = "test-image.jpg";
    const objectUrl = "https://upload.wikimedia.org/wikipedia/commons/2/28/JPG_Test.jpg"; // Harcoding the object url for easyness

    try {
      // Fetch the file from the URL
      const response = await fetch(objectUrl);
      const fileData = await response.buffer();

      // Upload the file to S3
      const putObjectCommand = new PutObjectCommand({
        Bucket: bucketName,
        Key: objectKey,
        Body: fileData,
        ContentType: 'image/jpeg',
      });

      const uploadResponse = await s3Client.send(putObjectCommand);
      console.log("Object uploaded successfully:", uploadResponse);

    } catch (error) {
      console.error("Error uploading object:", error);
    }
  }
})
```

Hi @puvisites 
thanks for your interest in using Pipedream and requesting support.

The code you provided works, that piece above I copied, properly puts an object into a bucket.
The problem though, I think, is that you added a "ListBuckets" command to your code base, but you failed to import it.

you have:
`
import { S3, PutObjectCommand } from "@aws-sdk/client-s3";`

but you might need

`import { S3, ListBucketsCommand, PutObjectCommand } from "@aws-sdk/client-s3";`
`

Finally, I know this might be boring. The right place to ask for code support, issues with JavaScript, bugs, and deficiencies in your code base is our #help channel at our [public Slack space](https://join.slack.com/t/pipedream-users/shared_invite/zt-11sazmsg0-oS2VW~mZfhtk3XfEEvb~JA), and our [community at Discourse](https://pipedream.com/community/).
See our Support resources at https://pipedream.com/support

Going forward, I'd advise to ask issues specifically with your code there. 
This Gihub issue can remain open for the sake of integrating Cloudflare and R2.

Sincerely,
Sergio

**Comment by malexanderlim** [comment]
Hi @wetarorg , the base integration for Cloudflare R2 has been completed: https://pipedream.com/apps/cloudflare-r2

Please let us know if you have any feedback, or if there are some components that you'd like to see developed for this integration!
