### ISSUE TITLE
[Components] Pendo

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7015]
### App
Pendo
https://www.pendo.io/

Triggers:
1. User Segmented: Triggered when a user is added or removed from a specific segment.
2. Feedback Received: Activated when new feedback or comments are submitted by users.

Actions:
1. Create Visitor: Add a new visitor to Pendo with custom properties.
2. Update Visitor: Modify an existing visitor's properties and preferences.
3. Fetch User Analytics: Retrieve user engagement and behavior analytics information.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
Account creds have been added to the vault.
