### ISSUE TITLE
[FEATURE] Filtering of SFDC webhooks

### ISSUE THREAD

**Issue by brandrsn** [PipedreamHQ/pipedream#702]
**Is your feature request related to a problem? Please describe.**
Every incoming webhook costs one invocation. But I don't care about 99% of incoming "on change" webhooks being triggered by Salesforce, meaning I'm wasting 99% of my invocations. Writing a filter for webhooks in SFDC is pretty difficult, so I'm stuck!

**Describe the solution you'd like**
When selecting which Object to subscribe to, I'd like to select which fields to watch too. Then, Pipedream can disregard webhooks that don't match my specific fields.

**Do you have a workaround?**
Not at the moment, but I'm going to try and build something.

**Comparable features in other tools?**
Here is a [video](https://www.loom.com/share/101094fcae5f4ee5aefc9ce02392664f) of the feature in Zapier. And [here is the UI](https://miro.medium.com/max/4800/1*N8jL0uZbJzqnXER5-GXNDQ.png) for a [$200 per month product](https://medium.com/appitek/hooked-the-declarative-webhook-builder-for-salesforce-f722c0a32151) that allows you to create filtered webhooks within SFDC itself. Tray.io [also allow field-level changes](https://tray.io/documentation/connectors/service/salesforce/#standard-trigger-events) to be watched for.

**Additional context**
Nope! Happy to answer more questions though. I'm in the Slack channel (U01DXP84BCL).

**Comment by dylburger** [comment]
Closing this in favor of the more general feature (#556) that would solve this.
