### ISSUE TITLE
facebook Api

### ISSUE THREAD

**Issue by alecosta80** [PipedreamHQ/pipedream#7026]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by alecosta80** [comment]
Is it available facebook Api to publish posts on Facebook?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergio-eliot-rodriguez** [comment]
fhyi @alecosta80 we gave facebooks groups integrated
https://pipedream.com/apps/facebook-groups
