### ISSUE TITLE
[Components] ElevenLabs

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7033]
### App
ElevenLabs
https://beta.elevenlabs.io/

Triggers:
1. Document Generated: Trigger when a new document is successfully generated.
2. Document Approved: Trigger when a document receives approval from the required parties.

Actions:
1. Generate Document: Create a new document using the selected template and data.
2. List Templates: Retrieve a list of available document templates.
3. Send for Approval: Send a generated document to the specified parties for approval.

_This list of suggested components was generated using ChatGPT_

**Comment by sergio-eliot-rodriguez** [comment]
User in requests #7027 wants a sort of 
Retrieve Audio File action
> 
I wish to be able to retrieve the audio file from this.

user request in #6182 wants 
Transcribe Text To Voice action

> 
Actions to transcribe text to voice

**Comment by sergio-eliot-rodriguez** [comment]
> If there are specific triggers and actions you are looking for, please let us know.
> Yes, I'm looking for its TTS actions.
> 
> I want to send text and voice_id as a payload and receive the audio file in return to upload it to a service like uploadcare.

https://github.com/PipedreamHQ/pipedream/issues/7027#issuecomment-1608795093
