### ISSUE TITLE
[Components] Facebook Groups

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7036]
### App
Facebook Groups
https://www.facebook.com/groups/explore/

Triggers:
1. New Post Created: Trigger when a new post is published in the group.
2. Member Joined: Trigger when a new member joins the group.

Actions:
1. Publish Post: Create and publish a new post in the group.
2. Add Member: Add a new member to the group.
3. Remove Member: Remove a specific member from the group.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
This has been completed already.
