### ISSUE TITLE
[Components] Google Contacts

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7037]
### App
Google Contacts
https://contacts.google.com

Triggers:
1. Contact Created: Triggered when a new contact is added to Google Contacts.
2. Contact Updated: Triggered when an existing contact is modified in Google Contacts.

Actions:
1. Create Contact: Adds a new contact to Google Contacts.
2. Update Contact: Modifies an existing contact in Google Contacts.
3. Delete Contact: Removes a contact from Google Contacts.

_This list of suggested components was generated using ChatGPT_

**Comment by michelle0927** [comment]
Closing because the actions listed here already exist, and the triggers are duplicated in [this issue](https://github.com/PipedreamHQ/pipedream/issues/7035).
