### ISSUE TITLE
[BUG] Open AI - Create Transcription failed with File Format srt

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7044]
**Describe the bug**
Open AI - Create Transcription failed with File Format `srt`

**To Reproduce**
1. Download the below file to Pipedream to Pipedream tmp directory
[audio-eng-5mins.mp3.zip](https://github.com/PipedreamHQ/pipedream/files/11877467/audio-eng-5mins.mp3.zip)
2. Add the Open AI - Create Transcription action, refer to the downloaded file. Set the Response Format to `srt`
3. Observe the response
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/7fae9070-c360-4cde-b23f-5d72a1069b81)

**Expected behavior**
The response should contain content

**Comment by RichardBaoLei** [comment]
same here
