### ISSUE TITLE
[APP] Zoho Analytics

### ISSUE THREAD

**Issue by aarontbt** [PipedreamHQ/pipedream#7045]
**Name of app / service**
Zoho Analytics

**Link to developer documentation**
https://www.zoho.com/analytics/api/v2/#api-specification

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No currently, this is the same as other Zoho apps just need to add support for this as well.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Mostly the actions from Bulk API (https://www.zoho.com/analytics/api/v2/#bulk-api). But take note of their Export Data (Asynchronous) as it is a 3-steps procedure for a complete cycle.

**Comment by malexanderlim** [comment]
Hi @aarontbt , closing this as complete as we have the Zoho Analytics integration in place (https://pipedream.com/apps/zoho-analytics) . If you'd like to request specific components - please feel free to raise a new issue and we can take a look!
