### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by surface9** [PipedreamHQ/pipedream#7049]
**Describe the bug**
Wix "New Order Created" Source isn't generating events, although multiple people have purchased plans on my site since being active.

**To Reproduce**
(link to workflow: https://pipedream.com/@theninestrading/wix-all-data-enabled-p_D1CDyQo/build)

**Expected behavior**
A person subscribes to my plans, and it shows up in the triggered events.

**Screenshots**
<img width="919" alt="Screenshot 2023-06-27 at 1 11 29 PM" src="https://github.com/PipedreamHQ/pipedream/assets/133982259/fe8ebefd-44db-4465-b53f-9c9c2cdc42d5">

**Desktop (please complete the following information):**
 - OS: Mac iOS Ventura 13.4 (22F66)
 - Browser: Chrome

**Comment by malexanderlim** [comment]
Hi @surface9 , sorry, my initial instructions were not very clear! Can you actually copy-paste the URL of your workflow? It should look something like this... https://pipedream.com/@michael-testing/wix-all-data-enabled-p_YyCDwZN/build

Having this link enabled will ensure that I can see it as well:
<img width="470" alt="Screenshot 2023-06-27 at 3 51 59 PM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/dae24f23-6f50-4ce2-be0a-842563b961e8">

Thanks!

**Comment by surface9** [comment]
> Hi @surface9 , sorry, my initial instructions were not very clear! Can you actually copy-paste the URL of your workflow? It should look something like this... https://pipedream.com/@michael-testing/wix-all-data-enabled-p_YyCDwZN/build
> 
> Having this link enabled will ensure that I can see it as well: <img alt="Screenshot 2023-06-27 at 3 51 59 PM" width="470" src="https://user-images.githubusercontent.com/42158621/249302585-dae24f23-6f50-4ce2-be0a-842563b961e8.png">
> 
> Thanks!

Sorry about that! Here you go: https://pipedream.com/@theninestrading/wix-all-data-enabled-p_D1CDyQo/build

**Comment by surface9** [comment]
> Hi @surface9, I couldn't seems to reproduce your issue. As in the image below, I can see the orders I created on Wix showing ![image](https://user-images.githubusercontent.com/18277920/249653827-4bd118a2-3b56-41c3-b571-ca5dbd21f3d9.png)
> 
> May I ask when you created the Wix API Key for Pipedream, have you added full permission as in the image below <img alt="image" width="1444" src="https://user-images.githubusercontent.com/18277920/249654055-7d8ddbb2-1498-40eb-89d7-ec010c947ef6.png">

I'm not sure why it's showing up for you and not on my end. How are you triggering those events when you haven't ordered the services on my site? When I created the wix API, I gave full permissions. Also, I have no problem when using the "New Member Registered" trigger. Those seem to work just fine, but not when someone subscribes to my website plans, nothing shows up.
![Screenshot 2023-06-28 at 9 29 56 PM](https://github.com/PipedreamHQ/pipedream/assets/133982259/88612af3-609c-4e13-a2ad-a1408b42d34d)
![Screenshot 2023-06-28 at 9 33 52 PM](https://github.com/PipedreamHQ/pipedream/assets/133982259/ad300512-7ac5-4a37-a3a4-caf0b988a6a1)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
