### ISSUE TITLE
[BUG] Monday Create Item action - adding field with Email type throws error `Error Failed to create item: invalid value, please check our API documentation for the correct data structure for this column`

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7058]
**Describe the bug**
Monday Create Item action - adding field with Email type throws error `Error Failed to create item: invalid value, please check our API documentation for the correct data structure for this column`

**To Reproduce**
1. On Monday.com, add a column with Email type
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/fc269f06-bd1c-4485-8b17-8550a61d8078)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/1af1b76f-5880-4d46-94f4-3d372ab6eded)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/a391dea3-8beb-45da-81cb-e86ab6e1dcd4)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/48c5d078-5460-45db-9f36-9e75432b4c67)

2. On Pipedream, add a new Add Item action, select the Email field and put in a valid email
3. Observe that the action failed
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/9ebc095b-add6-49c1-bc2f-5b4e9691ad6b)

**Expected behavior**
- The action should be executed successfully, the email field should be filled in correctly
- Please check other actions for the same issue

**Context**
- Raised by a user here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1687926866874179

**Comment by breaknanger** [comment]
Converting the email filed type to text allows me to send the data over without issue. I also had to do this for date and time fields.

![Screenshot 2023-06-27 at 8 10 13 PM](https://github.com/PipedreamHQ/pipedream/assets/105207051/6c4b241f-83c4-4862-bb20-8e5e28ee4943)

**Comment by breaknanger** [comment]
I added a new "Date" field on Monday.com and then tried to send a date over, I get the same error. I also don't get the helpful field hint shown in your screenshot.

![Screenshot 2023-06-29 at 9 01 16 PM](https://github.com/PipedreamHQ/pipedream/assets/105207051/f98b161d-5b8e-4e29-8406-7de7fec512ac)

![Screenshot 2023-06-29 at 8 59 34 PM](https://github.com/PipedreamHQ/pipedream/assets/105207051/4065dc37-8504-4ac1-8977-00760feda683)

**Comment by michelle0927** [comment]
Hi @breaknanger. If you follow the link in the error you posted, you'll find that a Date field is expected to be in one of the following formats:
2019-06-03
2019-06-03 13:25:00
{"date" : "1993-08-27", "time" : "18:00:00"}

If the date you're inserting is a timestamp in ISO format (something like this: 2023-06-27T19:41:17+00:00), a workaround would be to extract the first 10 characters:
`{{ (steps.trigger.event.newRow[5]).substring(0, 10) }}`
