### ISSUE TITLE
[FEATURE] Tracking credit usage of each step

### ISSUE THREAD

**Issue by RichardBaoLei** [PipedreamHQ/pipedream#7059]
**Is your feature request related to a problem? Please describe.**
i hope pipedream could provide a way to track each step credit usage? so that we could manage and calculate how much we need and do i need upgrade if i scale my business.

**Describe the solution you'd like**
mybe in event history, evey step has it's credit usage counts.

**Do you have a workaround?**
nope

**Comparable features in other tools?**
N/A

**Additional context**

**Comment by dylburger** [comment]
@RichardBaoLei Credits are calculated on a workflow level, not steps. So there's actually no per-step credit calculation we can show. Take a look at [the credits docs](https://pipedream.com/docs/pricing/#credits) for more detail.
