### ISSUE TITLE
When a workflow times out, the Inspector displays details of Exports / Logs that completed.

### ISSUE THREAD

**Issue by Swieter** [PipedreamHQ/pipedream#7067]
When I had a function timeout, and I went to inspector for the workflow, it looks as if the trigger timed out.  I surmise this because all the steps, expect the trigger, are greyed out.  This feels like a different pattern than if there was some other execution error in a workflow.

For instance, let's say a workflow has 5 steps after trigger.  If there was some code/syntax bug, in step 3, I'd still see the export/log for the steps that did complete, and even partial for the step that failed, depending on the error.

Right now in a timeout I get none of that.  I can't tell if it is step 1 or 5 after that trigger that timed out.  I can't see any possible error messages from API calls or other things, that may have hung execution.  

Even in time out situations, what information such as Exports and Logs should be displayed for the work done prior to a timeout.

**Comment by dylburger** [comment]
@Swieter Are you still able to reproduce this, or have you seen it with any new events? We should show partial exports / logs on timeouts. We did recently fix a related bug and I'd like to see if that fixed your issue, too.

If so, please send me an email to dylan [at] pipedream [dot] com with a link to the event in your workflow (you'll notice if you select an event, you'll see us append a `?e` query string param that will link to the exact event).

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
