### ISSUE TITLE
[TRIGGER] Discord "FORUMS" (new message)

### ISSUE THREAD

**Issue by firehawkx** [PipedreamHQ/pipedream#7071]
I have been searching for the past few weeks, tried appypie, Integrately, Zapier and none of them have any support for Forums in Discord. I then found pipedream and thought maybe I could learn how to do it myself? :) 

**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Its the same as a new Discord message, but with a new **_discord forum thread_**.
I would need to access the Title of the thread, its content/message/description/text, as well as the applied_tags

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://discord.com/developers/docs/topics/threads#forums

Let me know if you need any further information. I will totally be reading the " Quickstart: Source Development" guide to see if i could make it myself, but i have zero knowledge in this field so it might not be easy :) 

Thank you for reading.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by firehawkx** [comment]
I had actually setup a meeting with a pipedream partner on monday to discuss this. However before the end of the day yesterday I had a talk with our CEO and they decided to postpone this feature stating it was too complex and time consuming and not worth it for right now. So I ended up cancelling the meeting.

It really felt like an interesting challenge. I would have loved learning how and building it myself, or even with the help of a partner. So sadly I would not be able to help out much for the time being. I sincerely apologize for this.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
