### ISSUE TITLE
[Components] Shopify (Developer App)

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7086]
### App
Shopify (Developer App)
https://www.shopify.com/

Triggers:

1. Order Completed: Triggered when a new order is successfully completed and paid for in the Shopify store.

2. Product Added: Initiated when a new product is added to the Shopify store's inventory.

Actions:

1. Create Customer: Creates a new customer profile in the Shopify store.

2. Update Product: Updates the details of a specific product in the Shopify store.

3. Fulfill Order: Processes a specified order, marking it as fulfilled in the Shopify store.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
Already implemented in Shopify app.
