### ISSUE TITLE
[APP] Zoho Mail

### ISSUE THREAD

**Issue by celestebancos** [PipedreamHQ/pipedream#711]
Zoho Mail

https://www.zoho.com/mail/help/api/getting-started-with-api.html

I'm trying to send an email using Zoho Mail. At the very least I'd like to be able to connect an account to my code step (they use OAuth so it would be a pain to manage myself).

Specific actions I'd like to see:
- [Send an Email](https://www.zoho.com/mail/help/api/post-send-an-email.html)
- [Send email with Attachments](https://www.zoho.com/mail/help/api/post-send-email-attachment.html)
- [Upload Attachments](https://www.zoho.com/mail/help/api/post-upload-attachments.html)

Down the road I could see myself using [Save Draft/Template](https://www.zoho.com/mail/help/api/post-save-draft-template.html) for emails where I want human approval before they are actually sent. But for now just the basics of sending an email with attachments would be super-helpful!

**Comment by dylburger** [comment]
Thanks for the request @celestebancos . We'll take a look ASAP. Zoho has a lengthy approval process for new apps, so just a heads up that this may take a little time once we begin the process. We'll keep you updated on its status.

**Comment by celestebancos** [comment]
Thank you, @dylburger. Any updates on when this might be available?

**Comment by todsac** [comment]
On 1/5, Zoho said “ Thanks for the details. Will get back once the content
is reviewed. ETA: 1 - 2 weeks.”

**Comment by celestebancos** [comment]
Thank you @todsac!

**Comment by todsac** [comment]
Zoho finally approved the app.  

Example workflow - https://pipedream.com/@tod/zoho-mail-integration-example-p_RRCzb9P/
Marketplace listing for Zoho Mail - https://pipedream.com/apps/zoho_mail
