### ISSUE TITLE
[APP] Google Photos

### ISSUE THREAD

**Issue by babyshome** [PipedreamHQ/pipedream#712]
**Name of app / service**
Google Photos
**Link to developer documentation**
https://developers.google.com/photos
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment]
Thanks for the request @babyshome . We'll take a look ASAP.

**Comment by dannyroosevelt** [comment]
FYI looks like this was integrated in Nov 2021: https://pipedream.com/apps/google-photos

**Comment by dylburger** [comment]
This is live! https://pipedream.com/apps/google-photos
