### ISSUE TITLE
Event added to my Eventbrite Calendar (as a customer - an event I will attend)

### ISSUE THREAD

**Issue by i-SillyGit** [PipedreamHQ/pipedream#7120]
Event added to my Eventbrite Calendar (as a customer - an event I will attend)  (as an event producer too, but you already have that.  you don't have anything for consumers/customers)

(so i can integrate it with Google Calendar)

**Comment by michelle0927** [comment]
@i-SillyGit I don't see a way to retrieve liked/hearted events, but there is an endpoint to [List Orders placed by your User](https://www.eventbrite.com/platform/docs/order-lookup). We can create a polling source (runs every 15 minutes) to emit an event when the authenticated user has placed a new order.
