### ISSUE TITLE
[APP] httpsms

### ISSUE THREAD

**Issue by AchoArnold** [PipedreamHQ/pipedream#7123]
**Name of app / service**

httpSMS

**Link to developer documentation**

https://docs.httpsms.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Same as any SMS app send/receive sms via webhook.

**Comment by sergio-eliot-rodriguez** [comment]
@AchoArnold Thank you for the request

**Comment by sergio-eliot-rodriguez** [comment]
Hi @AchoArnold 
Welcome to Pipedream!
I see you might be httpSMS app develoer, is this right?
If the case, could you provide a good logo that we can use for httpSMS in our app store?
I'm the software developer consultant working in the initial basic integration with Pipedream.
Thanks,
Sergio

**Comment by AchoArnold** [comment]
Hello @sergio-eliot-rodriguez 

Yes, I'm the developer, You can use any of these 2 logos

1: https://github.com/NdoleStudio/httpsms/blob/main/web/static/avatar.png
2: https://github.com/NdoleStudio/httpsms/blob/main/web/assets/img/logo.svg

Thanks

**Comment by sergio-eliot-rodriguez** [comment]
Thank you @AchoArnold 

I am tackling the integration. Looks like I was able to create a working request. But messages are not being send.
Do you know if sending message is restricted country wise? i.e my phone number is not based int he US.

**Comment by AchoArnold** [comment]
Hello @sergio-eliot-rodriguez,

Did you install the APP on your android phone? The application does not restrict phone numbers country-wise. I'm not based in the US too. 

Which exact response do you get from the API, usually the response code + body of the response is very descriptive.

**Comment by sergio-eliot-rodriguez** [comment]
Yeahh, the error is that supposedly the phone number is not connectedto the device

`{'data': {'from': ["no phone found with with 'from' number [+526691514947]. install the android app on your phone to start sending messages", "could not validate 'from' number [+526691514947], please try again later"]}, 'message': 'validation errors while sending message', 'status': 'error'}
`
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/31226f82-2d1d-41c9-b667-322925901006)

I can send heartbeats for the phone and it saysa everything is ok.

i{ll remove my phoe number after yyou see the message

**Comment by AchoArnold** [comment]
Hello @sergio-eliot-rodriguez,

The phone number on the app and the number in your  API request are not matching. 

Your API request uses the number `+526691514947` but on the app, I see the phone number "+526691**4**14947"

**Comment by AchoArnold** [comment]
@sergio-eliot-rodriguez 
I can delete my previous comment to remove your Phone number after you read it

**Comment by sergio-eliot-rodriguez** [comment]
You are totally right!
Unsure how I missed that.

Thanks for the good eye

**Comment by sergio-eliot-rodriguez** [comment]
Previously integrated https://pipedream.com/apps/httpsms?via=go
