### ISSUE TITLE
[FEATURE] Warn people when their code uses a syntax feature or built in function not supported by the runtime

### ISSUE THREAD

**Issue by togakangaroo** [PipedreamHQ/pipedream#713]
**Is your feature request related to a problem? Please describe.**
When I'm writing code I'm generally writing it with pretty modern js in mind. So for example I use a function like `Object.fromEntries` and think nothing of it. It is frustrating to write code, run a script, get an error, then start debugging only to realize that its because a js feature that is not supported.

**Describe the solution you'd like**
I assume when save code you use a tool like esprima to parse it and identify the needed node modules. It would be nice if you detected constructs like `Object.fromEntries` or things like the elvis operator `?.` and give immediate feedback. With something like the former you could give people an option that will add the node shim from npm.

**Do you have a workaround?**
Sure, it's not the end of the world.

**Comment by dylburger** [comment]
The [new version of the workflow builder](https://pipedream.com/docs/migrate-from-v1/) includes:

1) Better notification of syntax errors
2) A testing flow that allows you to test potential issues that arise during runtime, prior to deploying. You can test a single step, which allows for rapid iteration.
