### ISSUE TITLE
Pi improvement: How to make a HTTP request in a custom Node.js step using `@pipedream/platform` package?

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#7137]
The original user asked how to make an HTTP request in a custom Node.js step. Pi provided an example code using the `axios` constructor from the `@pipedream/platform` package, and clarified that the correct import statement is `import { axios } from "@pipedream/platform"`.

See the original Slack thread [here](https://pipedream-users.slack.com/archives/C04TFD4LB36/p1688478282628819?thread_ts=1688478282.628819&cid=C04TFD4LB36).

**Comment by andrewjschuang** [comment]
Pi is actually responding `@pipedream/platform` correctly, but Slack is changing it to `@Phil/platform`
