### ISSUE TITLE
[TRIGGER][UPDATE] Google Drive - New Files (optional prop, "Files in folder")

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#7154]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

This is a request to improve the existing **Google Drive - New Files** trigger to include a new prop to allow the user to only emit events for new files within a specific folder on the drive.

For example, if the user has a folder titled **My Documents** under their Google Drive, then they can choose that folder and only emit events if a new file is created under that specific folder.

A new folder under **My Documents/resume.pdf** _should_ emit an event, whereas **My Videos/wedding.mov** should _not_ trigger an event.

**Comment by lcaresia** [comment]
@ctrlaltdylan Currently already have an option to filter by folders, is that you want?

![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/4e5a0b3b-54c0-49e6-b4fa-6ac01670cc0d)

**Comment by ctrlaltdylan** [comment]
Thanks @lcaresia ! I must have been looking at the wrong source. Sorry about that! I found it.
