### ISSUE TITLE
[BUG] As a user on the free plan, I want to disable a Google Drive Source that has no workflow connected, to stop using up plan quota

### ISSUE THREAD

**Issue by franz-josef-kaiser** [PipedreamHQ/pipedream#7155]
**Describe the bug**
Disabling/ Pausing a workflow does not work.

**To Reproduce**
1. Go to [Source details](https://pipedream.com/sources/dc_J4ueVKp) 
2. Click on `…`
        ![image](https://github.com/PipedreamHQ/pipedream/assets/387666/2410a1fb-240a-4e55-9bcf-acf88e2d0cc2)

or 

1. Go to [Source overview](https://pipedream.com/sources)
2. Try to click the toggle in the upper right corner. 

**Expected behavior**

Case 1: See `POST` response to `https://api.pipedream.com/graphql` in network tab: 500

```
{"status":500,"error":"Internal Server Error"}
```

Case 2: The toggle switches, the 500 err is the same as above

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome Version 114.0.5735.106 (Official Build) (64-bit)

**Additional context**
Free plan. Source: Google Drive. No workflow attached to source.

--- 

## EDIT

It seems I can also not delete the source.

![image](https://github.com/PipedreamHQ/pipedream/assets/387666/40597d44-a5e5-446c-9ac1-e287e778109a)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by franz-josef-kaiser** [comment]
Hi @dylburger and @vunguyenhung !
I was contacted and re-routed to your Slack channel. There I was asked to provide this issue. I assumed that your guys will take over and fill in the blanks as I already provided them with all _additional_ information there. Disappointing to see all my efforts go into a black hole here.

**Comment by dylburger** [comment]
@franz-josef-kaiser this was just a mistake — we have a workflow that watches for stale issues and it accidentally closed the issue. I just re-opened.

Leo asked a follow-up question above — would you mind letting us know specifically which Google Drive source you're using? He wasn't able to reproduce the original issue.

And just to confirm, if you try one more time, is this still an issue? Just want to make sure it wasn't a temporary bug.

**Comment by franz-josef-kaiser** [comment]
@dylburger no worries. Can you click the link I provided to the Slack-Thread? It should be public.

**Comment by dylburger** [comment]
Yes, it also looked like force deletion worked? Did that resolve it or is there still an issue?

<img width="343" alt="Screenshot 2023-07-13 at 10 11 31 AM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/c80fa15f-788f-4b9e-81f1-6c3f6d74f4aa">

**Comment by franz-josef-kaiser** [comment]
I just checked. Here's a screenshot. Force deletion seems to not have helped… the source still is there. I assumed it was gone.

![image](https://github.com/PipedreamHQ/pipedream/assets/387666/024336dd-d3b8-4a81-aedd-6811786e8b82)

**Comment by franz-josef-kaiser** [comment]
**EDIT** No, I am wrong. It did work out. This is just the _account_. Sorry. I haven't been using Pipedream much and even less after encountering this.

**Comment by dylburger** [comment]
Thanks, hope you won't hold this one against us. I read the Slack thread and it really seems like we did try to hunt this one down. Pipedream really is a fantastic tool and we try hard to provide great support! We just weren't able to reproduce this one, so hopefully it was just a subtle and transient issue. You can always ping us again about bugs and we'll follow up like we did here.

**Comment by franz-josef-kaiser** [comment]
@dylburger no worries, I won't. The thing seems to not be a real issue as the system behaves like it's expected. It's just not clear to me as a user without DevTools, Console- and Network-Tab error messages and an accompanying explanation. In the end, this ticket was mainly meant to serve as the root for some other, internal issues on your end, maybe connected to UX :)
