### ISSUE TITLE
[BUG] Upcoming Event Alert from Google Calendar - Action Required

### ISSUE THREAD

**Issue by Kieler83** [PipedreamHQ/pipedream#7159]
**Describe the bug**
The trigger "Upcoming Event Alert from Google Calendar" displays the message "Action Required - In Google Calendar, generate test events for this trigger. Test events provide data for autocomplete and testing to help you build your workflow".
In the log there is an error 404. I suspect that it is related to the expected test event. Unfortunately I can't find any info how this test event should look like.

**To Reproduce**
Select "Upcoming Event Alert from Google Calendar" trigger
Select Pipedream Account
Select Google Calendar Account
Select Calendar
Select Event Name
Select Minutes Before

**Expected behavior**
Appointment set in the calendar should trigger action

**Screenshots**
![image](https://github.com/PipedreamHQ/pipedream/assets/84130473/66f7129b-99f9-4975-bc56-69248ec9657e)
![image](https://github.com/PipedreamHQ/pipedream/assets/84130473/fbe133e7-e650-4e73-b28d-2893c397cccb)
![image](https://github.com/PipedreamHQ/pipedream/assets/84130473/5c2a685a-1de1-41cc-83ab-a3403250fd9c)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser chrome
 - Version 114.0.5735.134

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
