### ISSUE TITLE
[APP] Canva

### ISSUE THREAD

**Issue by Rafaela8** [PipedreamHQ/pipedream#716]

**Comment by dylburger** [comment]
@Rafaela8 just to confirm we have the right API, can you link us to the API docs for Canva that you're looking at?

**Comment by dylburger** [comment]
I'm closing this ticket without more information. Please feel free to re-open with specific details on the type of integration you'd like to see with Canva and we can look into it.

**Comment by malexanderlim** [comment]
@Rafaela8, we've officially launched support for Canva on Pipedream as of today - feel free to check out our app [here](https://pipedream.com/apps/canva), and we are open to any feedback that you may have as well! 

If you are on a Canva Enterprise plan, we're about to roll out support for Canva's enterprise-level features, including as the ability to create designs based on your brand templates.
