### ISSUE TITLE
Microsoft Outlook

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7164]
### App
Microsoft Outlook
https://learn.microsoft.com/en-us/graph/api/resources/calendar

### Triggers
Hello,
First, thanks for building such a great app. It is already helping me automate my calendar synchronization.
I'd like to know why the Outlook account connection requires so many permissions. For example, I want to just listen for new or updated calendar entries, but it is requiring me to give access to my email, change my mailbox settings and also send emails! I believe that you are using the same scopes for every kind of integration with Outlook, but it would be to have different scopes per integration (for example, specific scopes required for new calendar entries).

**Comment by dannyroosevelt** [comment]
@malexanderlim is starting to think about the setup for Outlook, after this customer's request, so I'll defer to him.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
