### ISSUE TITLE
[ACTION] ActiveCampaign

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#717]
**Is there a specific app this action is for?**

New event - generic catchall for new events from Active Campaign
Create Account - Creates a new account.
Create/Update Contact - Creates a new contact, or updates an existing contact.
Add Contact Note - Adds new contact note.
Update Deal - Updates an existing deal.
Create Campaign - Creates and sends a new campaign.
Create Tracked Event - Creates a custom website or application event.
Update Account - Updates an account.
Add Contact to Automation - Adds an existing contact into any automation. If contact does not yet exist, a contact will be created and then added to the automation.
Create Deal - Creates a new deal.
Add Note to Deal - Adds a note to a deal.
Find Account - Finds account by name.
Find Deal - Finds an existing deal by title or email.
Find Contact - Finds a contact by email address.

**Please provide a link to the relevant API docs for the specific service / operation.**

https://developers.activecampaign.com/reference

**Comment by sergioeliot2039** [comment]
List All Contacts
Action: https://pipedream.com/actions/a_bKilj2/edit
Workflow: https://pipedream.com/@sergio/active-campaign-list-all-contacts-p_LQCn5Nd/edit
List All Deals
Action: https://pipedream.com/actions/a_l0i828/edit
Workflow: https://pipedream.com/@sergio/active-campaign-list-all-deals-p_V9CxnNk/edit
Find Contact
Action: https://pipedream.com/actions/a_bKilPw/edit
Workflow: https://pipedream.com/@sergio/active-campaign-find-contact-p_3nCaYeL/edit
Find Deal
Action: https://pipedream.com/actions/a_l0i8LA/edit
Workflow: https://pipedream.com/@sergio/active-campaign-find-deal-p_A2CQD9d/edit
Create New Campaign
Action: https://pipedream.com/actions/a_vgid80/edit
Workflow: https://pipedream.com/@sergio/active-campaign-create-new-campaign-p_PACqMmP/edit
Add Contact to Automation
Action: https://pipedream.com/actions/a_xqig4J/edit
Workflow: https://pipedream.com/@sergio/active-campaign-add-contact-to-automation-p_BjCqKKb/edit
Get All Automations
Action: https://pipedream.com/actions/a_K5i526/edit
Workflow: https://pipedream.com/@sergio/active-campaign-get-all-automations-p_WxCQBPY/edit
Update Account
Action: https://pipedream.com/actions/a_A6i578/edit
Workflow: https://pipedream.com/@sergio/active-campaign-update-account-p_6lC1MlM/edit
Create Tracked Event
Action: https://pipedream.com/actions/a_3Lie1M/edit
Workflow: https://pipedream.com/@sergio/active-campaign-create-tracked-event-p_2gCG8An/edit
Get All Accounts
Action: https://pipedream.com/actions/a_jQi8BL/edit
Workflow: https://pipedream.com/@sergio/active-campaign-get-all-accounts-p_V9CxPoq/edit
Get All Messages
Action: https://pipedream.com/actions/a_0Mi78M/edit
Workflow: https://pipedream.com/@sergio/active-campaign-get-all-messages-p_pWCYQal/edit
Get All Lists
Action: https://pipedream.com/actions/a_67iLjr/edit
Workflow: https://pipedream.com/@sergio/active-campaign-get-all-lists-p_k2C57Bw/edit
Update Deal
Action: https://pipedream.com/actions/a_Q3ixw3/edit
Workflow: https://pipedream.com/@sergio/active-campaign-update-deal-p_8rCNK5k/edit
Get Deal
Action: https://pipedream.com/actions/a_l0i8kA/edit
Workflow: https://pipedream.com/@sergio/active-campaign-get-deal-p_n1CKa3y/edit
Add Contact Note
Action: https://pipedream.com/actions/a_EVi74G/edit
Workflow: https://pipedream.com/@sergio/active-campaign-add-contact-note-p_LQCnLRW/edit
Add Note to Deal
Action: https://pipedream.com/actions/a_74ipwG/edit
Workflow: https://pipedream.com/@sergio/active-campaign-add-note-to-deal-p_6lC1KWL/edit
Create Deal
Action: https://pipedream.com/actions/a_Mdi7Jj/edit
Workflow: https://pipedream.com/@sergio/active-campaign-create-deal-p_rvCqQy7/edit
Create Note
Action: https://pipedream.com/actions/a_zNiJ3R/edit
Workflow: https://pipedream.com/@sergio/active-campaign-create-note-p_yKCJzYv/edit
Create or Update Contact
Action: https://pipedream.com/actions/a_YEi250/edit
Workflow: https://pipedream.com/@sergio/active-campaign-create-or-update-contact-p_A2CQx6o/edit
Create Contact
Action: https://pipedream.com/actions/a_a4ivPq/edit
Workflow: https://pipedream.com/@sergio/active-campaign-create-contact-p_13Cg378/edit
Get Contact
Action: https://pipedream.com/actions/a_G1iLx4/edit
Workflow: https://pipedream.com/@sergio/active-campaign-get-contact-p_vQCgzN8/edit
Create Account
Action: https://pipedream.com/actions/a_A6i5a8/edit
Workflow: https://pipedream.com/@sergio/active-campaign-create-account-p_KwC1xlM/edit
