### ISSUE TITLE
Get Playlist

### ISSUE THREAD

**Issue by cindyshapiro** [PipedreamHQ/pipedream#7173]
Spotify
(https://developer.spotify.com/documentation/web-api/reference/get-playlist)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!

**Comment by cindyshapiro** [comment]
Thank you!

Cindy Shapiro, CTO
Lost in Sound Records

lostinsoundrecords.com


￼

**Comment by cindyshapiro** [comment]
Thank you!Sent from my iPhoneOn Jul 25, 2023, at 6:50 AM, Leo Vu ***@***.***> wrote:﻿
Hi everyone, all test cases are passed! Ready for release!
Test report
https://vunguyenhung.notion.site/Get-Playlist-7173-788375bce88b471ba92b32fd65e59873
