### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shanew95** [PipedreamHQ/pipedream#7175]
**Describe the bug**
I've added a Hubspot step to a pipedream workflow to create a task, but under the 'assigned to' field, the HubSpot user I need to assign the task to doesn't appear as an option when searching for their email, nor their Hubspot user ID

**Expected behavior**
Be able to find and select the Hubspot user 

**Screenshots**
<img width="976" alt="Screenshot 2023-07-06 at 16 59 59" src="https://github.com/PipedreamHQ/pipedream/assets/138804460/06fa65a9-55a8-4061-9d4b-94aa36b8e074">
**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [Chrome]
 - Version [Version 114.0.5735.198 (Official Build) (x86_64)
 
 Source code for specific action: https://github.com/PipedreamHQ/pipedream/blob/master/components/hubspot/actions/create-engagement/create-engagement.mjs

**Comment by shanew95** [comment]
Hi @vunguyenhung - thanks for checking it out. Sorry for any confusion, I'm able to see other users, however I'm not able to see the specific user I need. It's strange as they're definitely there and I definitely have access, as I'm able to view and select that user in Zapier (but Zapier doesn't do what I need it to!)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by shanew95** [comment]
Sorry for any confusion, I'm able to see other users, however I'm not able to see the specific user I need. It's strange as they're definitely there and I definitely have access, as I'm able to view and select that user in Zapier (but Zapier doesn't do what I need it to!)
