### ISSUE TITLE
[APP] Hookdeck.com

### ISSUE THREAD

**Issue by kampeynco** [PipedreamHQ/pipedream#7184]
**Name of app / service**
Hookdeck

**Link to developer documentation**
https://hookdeck.com/api-ref

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes. The workaround has me using Make.com

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
CRUD Connection, CRUD Source, and CRUD Destination. The other actions can be configured on the Hookdeck dashboard

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/hookdeck?via=go
