### ISSUE TITLE
[BUG] Reddit 'submit_a_post' giving 401 errors

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#7197]
**Describe the bug**
Reddit action 'submit_a_post' is giving 401 errors. I imagine much like the Twitter issues we had this is due to changes in the Reddit API.

**To Reproduce**
1. Try using `submit a post` action on Reddit

**Expected behavior**
We should be able to post

**Screenshots**
Beginning of error html, there's more but nothing that is use, just posting as a sample.
![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/48260c3c-d824-4220-b44d-28aebd2b6b45)

**Desktop (please complete the following information):**
 - Win 10 Super Working Coding Gaming Rig 🙂

**Comment by Salvidrim** [comment]
My reddit source is also hitting 401 errors. I don't have a reddit app, I am using Pipedream's own Reddit integration as a source to trigger a workflow

**Comment by malexanderlim** [comment]
Hi @Salvidrim , due to Reddit's API changes, you will need to configure your own Pipedream app following these instructions: https://pipedream.com/apps/reddit#getting-started

Reddit limited the original Pipedream app integration to 100QPM, of which we were hitting on a consistent basis. Creating your own app using the instructions I shared will give you that 100QPM, but not shared amongst others since it will be a unique app. Please let me know if this fixes your issue.

**Comment by Salvidrim** [comment]
> Hi @Salvidrim , due to Reddit's API changes, you will need to configure your own Pipedream app following these instructions: https://pipedream.com/apps/reddit#getting-started
> 
> Reddit limited the original Pipedream app integration to 100QPM, of which we were hitting on a consistent basis. Creating your own app using the instructions I shared will give you that 100QPM, but not shared amongst others since it will be a unique app. Please let me know if this fixes your issue.

Yes thanks. Maybe add a note to https://pipedream.com/apps/reddit#getting-started clarifying that previous Reddit integrations need to be changed to resume working.

**Comment by NebularNerd** [comment]
> Hi @NebularNerd, would you mind reauthorize your Reddit account and try again? Reddit has recently updated their API tiers <img alt="Screenshot 2023-07-11 at 22 18 47" width="650" src="https://user-images.githubusercontent.com/18277920/252711180-c00f8458-26cc-4e9a-a3ab-9ec6ac9ad803.png">

Hi @vunguyenhung, sure thing. I can't try right now as I'm about to go on holiday. Once I get a spare 5 mins I'll take a look 🙂

**Comment by malexanderlim** [comment]
Thanks for the feedback @Salvidrim - will add a note.

**Comment by NebularNerd** [comment]
Tested and can confirm this works, these social platforms are really making things interesting.
