### ISSUE TITLE
[ACTION] Pipefy

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#720]
**Is there a specific app this action is for?**

Create Card | Create a card on a pipe.
Delete Card | Delete an existing Card.
Create a Table | Creates a new table.
Create a Table Record | Creates a new table record.
Delete a Table Record | Deletes a table record.
Get a Card Info | Gets card details.
Get a Table Record | Gets a table record.
Make an API Call | Performs an arbitrary authorized API call.
Move a Card to Phase | Moves a card to another phase.
Update a Card | Updates a card.
Update a Card Field | Updates a card field.
Update a Table Record | Updates a table record.
Get a Phase | Returns phase details.
List Cards | Lists cards
List Table Records | Lists table records.

**Please provide a link to the relevant API docs for the specific service / operation.**

https://developers.pipefy.com/docs

**Comment by sergioeliot2039** [comment]
Create Organization
Action: https://pipedream.com/actions/a_Jmi53w/edit
Workflow: https://pipedream.com/@sergio/pipefy-create-organization-p_NMC9Dgm/edit
Delete Organization
Action: https://pipedream.com/actions/a_1Wi7Xg/edit
Workflow: https://pipedream.com/@sergio/pipefy-delete-organization-p_JZCy5BA/edit
Update Organization
Action: https://pipedream.com/actions/a_VpiVvz/edit
Workflow: https://pipedream.com/@sergio/pipefy-update-organization-p_95C3Dxg/edit
Create Table
Action: https://pipedream.com/actions/a_jQi8Ke/edit
Workflow: https://pipedream.com/@sergio/pipefy-create-table-p_LQCnYjN/edit
Delete Phase
Action: https://pipedream.com/actions/a_8Ki0mb/edit
Workflow: https://pipedream.com/@sergio/pipefy-delete-phase-p_G6C6GDK/edit
Update Phase
Action: https://pipedream.com/actions/a_0Mi7MP/edit
Workflow: https://pipedream.com/@sergio/pipefy-update-phase-p_MOC3wGR/edit
Delete Pipe
Action: https://pipedream.com/actions/a_4riE0J/edit
Workflow: https://pipedream.com/@sergio/pipefy-delete-pipe-p_zACpZwr/edit
Update Pipe
Action: https://pipedream.com/actions/a_2wipqr/edit
Workflow: https://pipedream.com/@sergio/pipefy-update-pipe-p_5VCx25V/edit
Create Pipe
Action: https://pipedream.com/actions/a_wdidA4/edit
Workflow: https://pipedream.com/@sergio/pipefy-create-pipe-p_xMCNaqY/edit
Get Table Records
Action: https://pipedream.com/actions/a_poiz5o/edit
Workflow: https://pipedream.com/@sergio/pipefy-get-table-records-p_5VCx2QV/edit
Look up Pipe Relations by their IDs
Action: https://pipedream.com/actions/a_a4ivor/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-pipe-relations-by-their-ids-p_q6CbwLd/edit
Look up Pipes By their IDs
Action: https://pipedream.com/actions/a_G1iLne/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-pipes-by-their-ids-p_ZJCb56N/edit
Look up Cards Imports By Pipe ID
Action: https://pipedream.com/actions/a_PNiB2z/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-cards-imports-by-pipe-id-p_brCL9vW/edit
Import Cards
Action: https://pipedream.com/actions/a_Jmi57w/edit
Workflow: https://pipedream.com/@sergio/pipefy-import-cards-p_5VCx2n7/edit
Create Phase
Action: https://pipedream.com/actions/a_Q3ixBM/edit
Workflow: https://pipedream.com/@sergio/pipefy-create-phase-p_gYCM32x/edit
Clone Pipes
Action: https://pipedream.com/actions/a_Xzi4z3/edit
Workflow: https://pipedream.com/@sergio/pipefy-clone-pipes-p_wOCgyO2/edit
Get All Pipe Templates
Action: https://pipedream.com/actions/a_RAi3g0/edit
Workflow: https://pipedream.com/@sergio/pipefy-get-all-pipe-templates-p_mkCkGKL/edit
Look Up Phase By Id
Action: https://pipedream.com/actions/a_gnirYL/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-phase-by-id-p_6lC1QjQ/edit
Look Up Table by ID
Action: https://pipedream.com/actions/a_m8iY1x/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-table-by-id-p_vQCgAp2/edit
Look up Table Record by ID
Action: https://pipedream.com/actions/a_JmiRO6/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-table-record-by-id-p_pWCYgoQ/edit
Get Conditional Fields
Action: https://pipedream.com/actions/a_RAiX20/edit
Workflow: https://pipedream.com/@sergio/pipefy-get-conditional-fields-p_6lC1QLL/edit
Get All Cards
Action: https://pipedream.com/actions/a_74ijXz/edit
Workflow: https://pipedream.com/@sergio/pipefy-get-all-cards-p_3nCaoMA/edit
Look up Card by ID
Action: https://pipedream.com/actions/a_LgieOq/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-card-by-id-p_MOC3YA9/edit
Look up Pipe by ID
Action: https://pipedream.com/actions/a_wdiVQ2/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-pipe-by-id-p_yKCJDnx/edit
Look up Organizations by IDs
Action: https://pipedream.com/actions/a_MdieKr/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-organizations-by-ids-p_q6CbMm2/edit
Look up Organization by ID
Action: https://pipedream.com/actions/a_EVixjv/edit
Workflow: https://pipedream.com/@sergio/pipefy-look-up-organization-by-id-p_95C3KNW/edit
Search Cards
Action: https://pipedream.com/actions/a_YEikvO/edit
Workflow: https://pipedream.com/@sergio/pipefy-search-cards-p_aNC6vYB/edit
Get Current User
Action: https://pipedream.com/actions/a_oViLoO/edit
Workflow: https://pipedream.com/@sergio/pipefy-get-current-user-p_QPC1LqR/edit
Update Table Record
Action: https://pipedream.com/actions/a_rJidQX/edit
Workflow: https://pipedream.com/@sergio/pipefy-update-table-record-p_mkCkGZR/edit
Create Table Record
Action: https://pipedream.com/actions/a_2wipLx/edit
Workflow: https://pipedream.com/@sergio/pipefy-create-table-record-p_wOCgyNk/edit
Delete Table Record
Action: https://pipedream.com/actions/a_LgiE4x/edit
Workflow: https://pipedream.com/@sergio/pipefy-delete-table-record-p_k2C5oAz/edit
Update Table
Action: https://pipedream.com/actions/a_WYiwx5/edit
Workflow: https://pipedream.com/@sergio/pipefy-update-table-p_2gCGgjV/edit
Delete Table
Action: https://pipedream.com/actions/a_wdidpP/edit
Workflow: https://pipedream.com/@sergio/pipefy-delete-table-p_zACpZYD/edit
