### ISSUE TITLE
[TRIGGER] Freshservice - New Ticket

### ISSUE THREAD

**Issue by CrisKrikke** [PipedreamHQ/pipedream#7200]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
freshservice

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://api.freshservice.com/#view_all_ticket

**Comment by CrisKrikke** [comment]
So this ready for release, can we use it now? Or are there more steps ...

**Comment by dannyroosevelt** [comment]
@lcaresia can you merge this asap please?
