### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by kuhnster01** [PipedreamHQ/pipedream#7201]
I’m very interested to know how an end user of my app can OAuth Pipedream (eg. their Gmail account) from within my app without needing my team’s involvement.

Best regards

Rodney 
rodney@sortd.com

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @kuhnster01 

I recently reached out to your email on how we could natively add an OAuth based application that connects to your app via Pipedream. Wondering if you received it?

I'd appreciate your comments on it.

Thank you,
Sergio

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/13890006-2cd3-4636-883d-982de1d6d35c)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by kuhnster01** [comment]
Sorry for my slow response, I was away.  It's not the right time for us for
Pipedream, but it's still on my radar.

<http://sortd.com/?utm_source=email_sig&utm_medium=email&utm_campaign=Ro_Ku>
*Rodney Kuhn* | Co-founder
083 456 7224 | www.sortd.com
------------------------------

**Comment by dylburger** [comment]
Thanks @kuhnster01 , we're planning to expand support for this in the future.
