### ISSUE TITLE
[Components] Microsoft Outlook - migration request

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#7206]
Hi Component Dev team,

The ask here is to migrate a few triggers and actions from **Microsoft Outlook** to **Microsoft Outlook Calendar**.

**Triggers:**
- New Calendar Event
- New Upcoming Event
- Updated Calendar Event

**Actions:**
- Create Calendar Event

These actions currently exist today under **Microsoft Outlook**, but we'd like to migrate these over to the standalone **Microsoft Outlook Calendar** app to limit the number of scopes being requested, and separate the apps by function (email vs. calendar).

Thanks!

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
This might be api docs
https://learn.microsoft.com/en-us/graph/outlook-calendar-concept-overview

**Comment by sergio-eliot-rodriguez** [comment]
this might be helpful too>
https://learn.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0
