### ISSUE TITLE
New docs: Is there a Google Photos integration for Pi?

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#7208]
The original user asked if there was a Google Photos integration available. Pi initially stated that there was no Google Photos integration in their sources, but later corrected themselves and provided a link to the Google Photos integration on Pipedream.

See the original Slack thread [here](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1689007592977739?thread_ts=1689007592.977739&cid=CPTJYRY5A).

**Comment by nitin-pandita** [comment]
@dylburger  hope you are doing well, I would like to have this issue

**Comment by dylburger** [comment]
Hi @nitin-pandita , thanks for reaching out. We use this public repo to track some internal tickets, as well. This code is not open-source, so someone from our team needs to tackle it.

Take a look at [this list](https://github.com/PipedreamHQ/pipedream/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sort%3Areactions-desc) for good issues to tackle. That lists all issues with the `good first issue` label, and orders them by popularity (the number of users who are interested in the integration). Then take a look at [the contribution process](https://pipedream.com/docs/apps/contributing/#contribution-process) for details on exactly how to get started.

**Comment by nitin-pandita** [comment]
> Hi @nitin-pandita , thanks for reaching out. We use this public repo to track some internal tickets, as well. This code is not open-source, so someone from our team needs to tackle it.
> 
> Take a look at [this list](https://github.com/PipedreamHQ/pipedream/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sort%3Areactions-desc) for good issues to tackle. That lists all issues with the `good first issue` label, and orders them by popularity (the number of users who are interested in the integration). Then take a look at [the contribution process](https://pipedream.com/docs/apps/contributing/#contribution-process) for details on exactly how to get started.

@dylburger thank you for your reply, I would love to contribute. Is it fine if I pin you a message, for some help

**Comment by dylburger** [comment]
Please reach out in [our contribution channels](https://pipedream.com/docs/apps/contributing/#component-development-discussion) — that's the best way to get help.

**Comment by nitin-pandita** [comment]
> Please reach out in [our contribution channels](https://pipedream.com/docs/apps/contributing/#component-development-discussion) — that's the best way to get help.

@dylburger sure thank you
