### ISSUE TITLE
[BUG] Github - Create Issue action failed with Syntax Error: Unexpected token {

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7215]
**Describe the bug**
Github - Create Issue action failed with Syntax Error: Unexpected token {
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/a822b3b6-ce02-44b4-b328-fe579f2479d6)

**Expected behavior**
- The action should be executed successfully for simple case
- The new issue should be created

**Additional context**
https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1689043925816299

**Comment by esplanadecloud** [comment]
It's happening for other GitHub actions too
<img width="956" alt="Screenshot 2023-07-11 at 20 20 07" src="https://github.com/PipedreamHQ/pipedream/assets/122422793/3051e52f-da3b-472f-a378-00eff7420db7">
