### ISSUE TITLE
[FEATURE] Refactor GitHub Sources to support dynamic interface type

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7217]
Right now there is a gap in how our GitHub sources are configured, mainly because of GitHub's requirements that only repo admins can create webhooks.

I had an idea that maybe we can get the repo `permissions` for the user on the repo they select, and if `admin: false`, we configure the source as polling (no need to create webhooks), and if `admin: true`, we configure as a webhook-based instant source. We can use `additionalProps()` for this.

Let's prototype this with the New Pull Requests source to see how it works. While we're making changes to that source, we should add an optional `string[]` type prop so users can select what type of activity they'd like the source to emit on (all pull activity by default).

For example, when I run this with the `pipedream` repo, I get: `{"admin":true,"maintain":true,"push":true,"triage":true,"pull":true}`

```
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    github: {
      type: "app",
      app: "github",
    },
    repo: "string"
  },
  async run({steps, $}) {
    const user = await axios($, {
      url: `https://api.github.com/user`,
      headers: {
        Authorization: `Bearer ${this.github.$auth.oauth_access_token}`,
        "X-GitHub-Api-Version": `2022-11-28`,
      },
    })
    const username = user.login
    const permissions = await axios($, {
      url: `https://api.github.com/repos/PipedreamHQ/${this.repo}/collaborators/${username}/permission`,
      headers: {
        Authorization: `Bearer ${this.github.$auth.oauth_access_token}`,
        "X-GitHub-Api-Version": `2022-11-28`,
      },
    })
    return permissions.user.permissions
  },
})
```

**Comment by GTFalcao** [comment]
I skipped a second round of PR review as the only code change was moving `http` and `timer` to `additionalProps`.
