### ISSUE TITLE
Upload File in One Drive

### ISSUE THREAD

**Issue by JuergenFolta** [PipedreamHQ/pipedream#7219]
**Is there a specific app this action is for?**
Onedrive

**Please provide a link to the relevant API docs for the specific service / operation.**
Download exists. Upload should too. 

Here is the link to the specific API Operation via graph 1.0:
https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http**

**Comment by JuergenFolta** [comment]
> Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.
> 
> If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

1. Yep! I know :) But I'm busy with other coding projects that improve my workflow. :/
2. Do you really believe Microsoft cares what a non-business customer needs ? 

 When i figure out what is the right way to get in contact with Microsoft i will do that. :)

**Comment by JesusC-R** [comment]
Hi, you can use Microsoft's graph API to solve this issue. You can try running the following command to install their API:
`npm install @microsoft/microsoft-graph-client`

Here's the Doc: https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

**Comment by ydv-ankit** [comment]
sure I'm gonna try installing this API

**Comment by malexanderlim** [comment]
@JuergenFolta this is available here:
https://pipedream.com/apps/microsoft-onedrive/actions/upload-file
