### ISSUE TITLE
[APP] Loops.so

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#7225]
**Name of app / service**
Loops.so

**Link to developer documentation**
https://loops.so/docs/add-users/api-reference

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Send Transactional Email 
Send Event
Find Contact
Update Contact 
Add Contact

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/loops-so
