### ISSUE TITLE
[FEATURE] Airtable node steps should use the airtable sdk

### ISSUE THREAD

**Issue by togakangaroo** [PipedreamHQ/pipedream#723]
**Is your feature request related to a problem? Please describe.**
When needing to send some data to airtable in a custom manner we use a node step. When selected, this pops open a template for an axios call. We could not get this working properly (perhaps wiring up the `auth` header was wrong? It should honestly get wired up for you in the template since pipedream has all that info)

**Describe the solution you'd like**
Rather than mucking around with raw REST requests, I think the template should use the airtable sdk on npm which hides a lot of the details for you. Using that rather than the raw HTTP call worked with no problems.

**Comment by dylburger** [comment]
@togakangaroo would you expect something like this as the base Node.js code step?

```javascript
const Airtable = require('airtable')
const base = new Airtable({apiKey: auths.airtable.api_key}).base(params.base)
```

**Comment by togakangaroo** [comment]
Yup that's it exactly

**Comment by dylburger** [comment]
Should be fixed now, thanks for raising.
