### ISSUE TITLE
[APP] Neon

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#7246]
**Name of app / service**
https://neon.tech/

**Link to developer documentation**
https://api-docs.neon.tech/reference/getting-started-with-neon-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
applied to the partner program to get oauth access

copied integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
A separated app was submitted for approval using API Keys auth

**Comment by sergio-eliot-rodriguez** [comment]
Previously approved as an API Key based app https://pipedream.com/apps/neon-api-keys
