### ISSUE TITLE
[BUG] Changing source timer intervalSeconds doesn't change event timing

### ISSUE THREAD

**Issue by togakangaroo** [PipedreamHQ/pipedream#725]
**Describe the bug**
Following [the quickstart](https://github.com/PipedreamHQ/pipedream/blob/master/QUICKSTART.md) initially set `intervalSeconds: 15` but then thought to change it to `intevalSeconds: 900`

I see this reflected in my new configuration on the site but the timer is still running every 15 seconds not 15 minutes

![demonstration of configuration panel showing that the intervalSeconds has changed but timer is still set to every 15 seconds](https://user-images.githubusercontent.com/66150/102938685-68ca9700-4472-11eb-8e8f-7b7fdec9b635.png)

**Comment by dylburger** [comment]
@togakangaroo I definitely understand the confusion. This is technically a feature and I'll explain what's going on.

Notice that you're changing the value of `intervalSeconds` within the `default` block. When you author your own event source, this can be helpful for setting the default timer schedule when _new_ event sources are instantiated, but changing the default will not affect the timer configuration of the running instance (what we call the "deployed component").

If you're using `pd dev`, you should be able to run

```bash
pd dev --prompt-all <your entrypoint file>
```

to override the default and set the timer configuration for your deployed component when you create it. Let me know if that helps.

**Comment by togakangaroo** [comment]
I see. Can I recommend linking to this in the quick start doc then?

**Comment by dylburger** [comment]
Yes, I went ahead and updated the section on [running code on a schedule](https://github.com/PipedreamHQ/pipedream/blob/master/QUICKSTART.md#invoke-your-code-on-a-schedule) to include the same note.
