### ISSUE TITLE
[Components] dbt Cloud

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7262]
### App
dbt Cloud
https://www.getdbt.com/

**Triggers:**
1. Job Run Completed: Trigger when a job run has successfully completed in dbt Cloud.

**Actions:**
1. Jobs: Trigger Job Run (also with the option to retrieve the run once completed)
https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Trigger%20Job%20Run

2. Runs: Retrieve Run
https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Retrieve%20Run

3. Environments: Retrieve Environment
https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Retrieve%20Environment

4. Runs: Retrieve Run Artifact
https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Retrieve%20Run%20Artifact

**Comment by mroy-seedbox** [comment]
I'm working on this right now!

Steps that are upcoming (in that order):
- Jobs: Trigger Job Run
- Runs: Retrieve Run
- Environments: Retrieve Environment
- Runs: Retrieve Run Artifact

**Comment by mroy-seedbox** [comment]
[DBT Cloud also supports webhooks](https://docs.getdbt.com/docs/deploy/webhooks) for completed or failed jobs, which could be a useful trigger.

There's no way to tie a webhook directly to a specific run/workflow (we can only configure a static callback URL), but in theory it should be possible to use the trigger to resume a paused workflow if the resume URL for that workflow is kept in a data store (the link could be established via the run ID).

**Comment by raphaelvarieras** [comment]
Thanks - works great!
