### ISSUE TITLE
[APP] Talend

### ISSUE THREAD

**Issue by mroy-seedbox** [PipedreamHQ/pipedream#7265]
**Name of app / service**
Talend

**Link to developer documentation**
- [API Documentation](https://api.talend.com/)
- [API Portal](https://api.eu.cloud.talend.com/tmc/swagger/swagger-ui.html)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
We are not blocked. We can use environment variables to hold the credentials.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
No specific actions required at this time (we can handle that with code steps). It would just be nice to have an app to store the credentials, [like you have for Databricks](https://pipedream.com/apps/databricks) & [DBT](https://pipedream.com/apps/dbt) (even though there are no actions or triggers).

**Comment by mroy-seedbox** [comment]
If a basic app can be created for this, we'd love to contribute some components to it! ❤️

**Comment by dannyroosevelt** [comment]
@mroy-seedbox we'll get right on it! By the way, can you let us know what triggers or actions you'd like to see for Databricks, so we can get some published?

**Comment by mroy-seedbox** [comment]
We're working on that right now!

The main actions that we care about right now are:
- Jobs: [Run now](https://docs.databricks.com/workflows/jobs/jobs-2.0-api.html#run-now)
- Jobs: [Get run](https://docs.databricks.com/workflows/jobs/jobs-2.0-api.html#runs-get)
- Jobs: [Get run output](https://docs.databricks.com/workflows/jobs/jobs-2.0-api.html#runs-get-output)

**Comment by sergio-eliot-rodriguez** [comment]
notes on outreach:
applied for partnerships, copied integrations@pd

**Comment by malexanderlim** [comment]
@mroy-seedbox happy to share that a basic integration is in place! Do you have any triggers or actions that you'd like to see for Talend? Given the breadth of their APIs, some input for developing components would be helpful to ensure that we are solving the right use cases for you.

**Comment by mroy-seedbox** [comment]
Trying it now!

FYI: There's a typo in the app setup/credentials:
![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/643cf604-d402-4847-b24f-aeb011959a3b)

**Comment by mroy-seedbox** [comment]
Another FYI: Talend is one of those API (along with Tableau) which increments their API versions often (currently `v2.6`).
![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/28993868-10c5-455e-99d4-6c0f1ed298b4)

Idk what would be the best way to manage that in Pipedream... I'm thinking that setting the API version along with the app would make sense? Otherwise, it would have to be a prop configured for every single action.

**Comment by mroy-seedbox** [comment]
For the actions, we currently just use two of them (and no triggers for now):

[Execute Plan](https://api.eu.cloud.talend.com/tmc/swagger/swagger-ui.html#/plans%20%3A%3A%20executions/executePlan):
```js
    const response = await axios({
      method: "POST",
      url: `https://api.us.cloud.talend.com/tmc/v2.6/executions/plans`,
      headers: {
        "Authorization": `Bearer ${this.talend.$auth.personal_access_token}`,
        "Content-Type": "application/json",
      },
      data: {
        "executable": this.planId
      },
    });
```

[Get Plan Execution Status](https://api.eu.cloud.talend.com/tmc/swagger/swagger-ui.html#/plans%20%3A%3A%20executions/getPlanExecutionStatus):
```js
    const response = await axios({
      method: "GET",
      url: `https://api.us.cloud.talend.com/tmc/v2.6/executions/plans/${this.execution_id}`,
      headers: {
        Authorization: `Bearer ${this.talend.$auth.personal_access_token}`,
      }
    });
```

**Comment by malexanderlim** [comment]
Thanks for the detail @mroy-seedbox , I've created https://github.com/PipedreamHQ/pipedream/issues/7674 for tracking development of these components.

In addition, instead of the endpoints that you shared (which appear to now be legacy), I've included documentation for the latest version for the actions shared - which include version headers in the YYYY-MM format. I will close this ticket for now, so please follow along at the component ticket to watch the progress!
