### ISSUE TITLE
[ACTION] Discord Send message to guild channel

### ISSUE THREAD

**Issue by BostjanPisler** [PipedreamHQ/pipedream#727]

**Comment by dylburger** [comment]
@BostjanPisler we have a **Send Message to Channel** action as a part of the **Discord Webhook** integration: https://docs.pipedream.com/apps/discord/#using-the-discord-webhook-integration .

Were you looking for another action, or did that not provide the specific functionality you needed?

**Comment by BostjanPisler** [comment]
I'm trying to chain the Bot create channel action and then send a message to that channel after it's been created. I haven't found a way to add a webhook to the channel either after creating it.

**Comment by dylburger** [comment]
@BostjanPisler thanks, that helps. It looks like you might be able to both [create a webhook](https://discord.com/developers/docs/resources/webhook#create-webhook) and [send a message to it](https://discord.com/developers/docs/resources/webhook#execute-webhook) using the Discord REST API.

Were you also aware that you can [create and publish your own actions](https://docs.pipedream.com/workflows/steps/actions/#creating-your-own-actions) on Pipedream? You can start with the code for an existing Discord Bot action (like Create Channel), modify its URL / params for these endpoints, and publish that as its own new action, if you'd like.

We are happy to support you in any way if you'd like to attempt that (feel free to [join our Slack](https://join.slack.com/t/pipedream-users/shared_invite/zt-ernlymsn-UHfPg~Dfp08uGkAd8dpkww) if you'd like to communicate in real time).

**Comment by BostjanPisler** [comment]
Thanks, the create a webhook might be a good alternative.
