### ISSUE TITLE
mattermost [APP]

### ISSUE THREAD

**Issue by Satyabrata12017** [PipedreamHQ/pipedream#7273]
**Name of app / service**
Mattermot

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @Satyabrata12017 

thank you for the request.

Mattermost is integrated here: https://pipedream.com/apps/mattermost

if you meant a different app please let us know.

Thanks,
Sergio

**Comment by sergio-eliot-rodriguez** [comment]
duplicated, closing
