### ISSUE TITLE
[BUG] Workflow with SCHEDULE trigger do not trigger at the right time, and was triggered twice when manually ran

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7285]
### Customer Report 1
Hi! Still same problem reoccurring. An example from another workflow, which automatically runs at 23:00 every day. It is also manually run during the day. Yesterday it did not run, but today when I pressed "Run Now", it executed twice.
<https://pipedream.com/@tarkhoone/device_controller_to_firestore-p_pWCobyM/inspect>

[Slack Message](https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1689672892853039?thread_ts=1685450385.252429&cid=CMZG4EBJ9)

### Customer Report 2
My code is triggered by a CRON scheduler (*/10 9-19 * * *) to run every 10 minutes. I notice some trigger failures that produce very undesired results. For instance, today the trigger fired at 11:00:01 AM, then did not fire at all at 11:10, and then fired twice at 11:20:01 AM. So the code ran twice at 11:20, but because it was almost simultaneous, each running instance did not know the other one was running too, and it scrambled my output. How do I safeguard against such trigger failures?

[Discord](https://pipedream.com/community/t/frequent-schedule-trigger-failures/7587)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/9a5a249a-5cde-4608-8869-0d15b0a0501f)

**Comment by mroy-seedbox** [comment]
This is affecting us as well.

The execution that was supposed to start at 18h00 today did not run, and then the workflow triggered twice at 22h00 instead (one of which failed, because this workflow does not support concurrent execution).

![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/dde1a79c-bc51-4b99-96ef-2e45b4faea96)
_Note: My timezone is PST, so it's three hours behind the cron schedule._

**Comment by mroy-seedbox** [comment]
This has been reported here as well: https://pipedream.com/community/t/issue-with-cron-not-running-daily-workflow-consistently-and-duplicate-runs-when-manually-triggered/6892

**Comment by mroy-seedbox** [comment]
@vunguyenhung, @dylburger: We need the schedule for this workflow (and others) to be highly reliable. Are there any workarounds to avoid this bug?

**Comment by dylburger** [comment]
Thanks for the note, I’ll raise this with the team and get back to you ASAP

**Comment by mroy-seedbox** [comment]
For now, we have converted the workflow to five separate scheduled triggers (one for each execution), in the hopes that it works better that way. 🤞 

![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/d781bd05-a1d8-4a25-a14d-941bc050bf5a)

**Comment by dylburger** [comment]
We believe we've implemented a fix. I'll leave this issue open, but please let me know if you see this again on any live workflows, or if it looks to have been resolved.

**Comment by dylburger** [comment]
We checked in on more data from over the weekend and we do believe this is fixed. Going to close this now, and please let us know if you see any other issues.

**Comment by mroy-seedbox** [comment]
We just created an hourly workflow (see screenshot). We'll let it run for a couple of weeks to confirm that no triggers are missing/doubled.

Thanks for the fix! 🙏 

![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/011c0182-8b2e-4487-8958-3854fc6de68f)

**Comment by mroy-seedbox** [comment]
It's been working well, thank you! 🙏 

Not a single missed invocation over the past week. 👌 

![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/2cf0339f-4780-4893-89e2-f6a31d382eb8)
