### ISSUE TITLE
[APP] 8x8 CONTACT CENTER PHONE CALL API

### ISSUE THREAD

**Issue by claytonc-trianglemls** [PipedreamHQ/pipedream#7289]
**Name of app / service**
8x8 Contact Center

**Link to developer documentation**
https://developer.8x8.com/actions-events/docs/cc-manage-phone-calls

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Lack of support is preventing us from building workflows.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
**notes on outreach**
by email, copied sergio at pk, integrations at pd

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
