### ISSUE TITLE
Woo Commerce Actions

### ISSUE THREAD

**Issue by prabapms** [PipedreamHQ/pipedream#729]
Hello all,
        I am able to see "change order status" action only for woo commerce app. How can i get more actions like read order details and read customer details. Kindly some one help me to get more actions.

**Comment by todsac** [comment]
@prabapms - are you capable of writing the code for the actions yourself?  If so, you can submit them and make them available for all users.

Here is the detail on how to create your own actions - https://docs.pipedream.com/workflows/steps/actions/#creating-your-own-actions

**Comment by alysonturing** [comment]
Hi @zalmanlew I noticed that you opened a Pull Request for this task... but I wonder... shouldn't you assign the task to yourself and then move it to the column `Ready for PR Review` ?

**Comment by zalmanlew** [comment]
@alysonturing I cannot assign things to myself or change statuses on the board. 🤷‍♂️
