### ISSUE TITLE
BigCommerce

### ISSUE THREAD

**Issue by bc-simonpallister** [PipedreamHQ/pipedream#73]
**Name of app/service**
BigCommerce

**Link to developer documentation**
https://developer.bigcommerce.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Workaround is to create HTTP calls manually, but is painful

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
There are many many triggers & actions, but the most important ones to start with are customer & order ones

**Comment by todsac** [comment]
Example workflow - https://pipedream.com/@tod/bigcommerce-api-integration-example-p_aNC61aO/
Marketplace - [BigCommerce API Integrations](https://pipedream.com/apps/bigcommerce).

**Comment by vellames-turing** [comment]
@dylburger @dannyroosevelt Hey guys, could you help me here? This is closed?

**Comment by dannyroosevelt** [comment]
> @dylburger @dannyroosevelt Hey guys, could you help me here? This is closed? The issue status is closed but it was in the backlog

Can you create a new issue with the specific actions and triggers and link it here?

**Comment by vellames-turing** [comment]
Ref #2862

**Comment by vellames-turing** [comment]
@dannyroosevelt Looks like we can move this to `Done`?
Cc: @luancazarine

**Comment by luancazarine** [comment]
> @dannyroosevelt Looks like we can move this to `Done`? Cc: @luancazarine

It's OK for me
