### ISSUE TITLE
[FEATURE] Make it possible to discard the changes in the workflow editor

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#7303]
Sometimes I start editing a workflow and then realize that I was going in the wrong direction and I want to get the editor back to its initial state.

Since the latest deploy cannot currently be redeployed, there's no way to discard the changes in the editor (other than hitting Undo a bunch of times).

**Comment by dylburger** [comment]
@nachocab Since this will be solved with [our Git integration](#220), I'm closing this so we can consolidate on that issue.
