### ISSUE TITLE
[APP] Flodesk

### ISSUE THREAD

**Issue by blessingefkt** [PipedreamHQ/pipedream#7308]
**Name of app / service**
Flodesk

**Link to developer documentation**
https://developers.flodesk.com/
https://developers.flodesk.com/#section/Authentication

**Is lack of support preventing you from building workflows, or do you have a workaround?**
The current workaround is to use environment variables and create custom actions

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

ACTIONS:
- List all subscribers
- Create or update a subscriber
- Retrieve a subscriber
- Remove subscriber from segments.
- Add subscriber to segments
- Unsubscribe a subscriber from all lists
- List all segments
- Retrieve a segment
- List all custom fields
- Create a custom field
- List all webhooks.

SOURCES (for the following webhook events):
- subscriber.added_to_segment
- subscriber.created
- subscriber.unsubscribed

**Comment by sergio-eliot-rodriguez** [comment]
requested Oauth access
copied integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
Hi @blessingefkt 

Flodesk has been previously integrated https://pipedream.com/apps/flodesk
