### ISSUE TITLE
[APP] AssemblyAI

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#7316]
**Name of app / service**

AssemblyAI

**Link to developer documentation**

https://www.assemblyai.com/docs/API%20reference/transcript

**Is lack of support preventing you from building workflows, or do you have a workaround?**

You can use the API directly, but a basic integration to store the API token would be nice.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Please see the **Reference section** in their documentation for a list of actions.

**Comment by sergio-eliot-rodriguez** [comment]
Hi Pierce!

Interesting request, there's an AssemblyAI very likely the same as the one in the request: https://pipedream.com/apps/assemblyai

can you double check please?

Thanks
