### ISSUE TITLE
Sharepoint Lists

### ISSUE THREAD

**Issue by chrischowaniec** [PipedreamHQ/pipedream#7320]
Microsoft SharePoint Lists

https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks

Will have to go through Azure

The link should provide it - but I want to create tickets in Jira from new list items in SharePoint and sync field changes between the two.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @chrischowaniec  thanks for the request

we are tracking Sharepoint at: https://github.com/PipedreamHQ/pipedream/issues/4872
please follow there, if you'd like to get notifications

I added a note for your requested sources.
