### ISSUE TITLE
[BUG] Segment - Identify User and Track user action do not send event to Segment

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7325]
**Describe the bug**
I created a new Segment HTTP source and add the write key to Pipedream's Segment account
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/4fb6dec9-7d0f-4ca0-a129-d9faddbeace6)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/9dfba824-aab6-4751-9fb6-cd3a9b4667aa)

Then I executed 2 actions for track and identify user
<img width="917" alt="Screenshot 2023-07-21 at 12 50 23" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/79c7257e-9f52-4fc3-8c77-b5e700d95841">
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/bab8c087-5550-48a0-b613-ba06213a4451)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/2fc13363-eca7-4efd-a1d7-162aa08e38be)

But I don't see new event on Segment for both Identify and Track
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/8b05b13d-fd9c-431d-bdf6-38ca86d5abf9)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/736254ee-afba-41a2-9f3a-ddbc464a16b0)

**Expected behavior**
There should be new event when I executed the Pipedream Segment actions

**Additional context**
Reported by a customer here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1689913634401379

**Comment by michelle0927** [comment]
@vunguyenhung Note for QA: To retest the "Webhook Destination" source, you'll need to reconnect your account and enter an `access_token` in addition to the `write_key`.
