### ISSUE TITLE
crouton

### ISSUE THREAD

**Issue by iqishaqmd** [PipedreamHQ/pipedream#7335]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @iqishaqmd 

thanks for the request.

is this the app you are looking to integrate?
https://crouton.app/

provide more details please

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
