### ISSUE TITLE
[ENHANCEMENT] Update Axonaut app connection description 

### ISSUE THREAD

**Issue by lcaresia** [PipedreamHQ/pipedream#7352]
Axonaut app connection description need an update from

- Go to “Settings” > “API”

to

- Go to “Profile” > “API”

![image_720](https://github.com/PipedreamHQ/pipedream/assets/12402324/ac34fe5d-3cc5-49eb-8625-7cece05abc11)
![image_480](https://github.com/PipedreamHQ/pipedream/assets/12402324/a5af994d-23b0-41d7-a257-2e564a6108b4)

**Comment by malexanderlim** [comment]
Thanks for flagging. I've updated this - let me know if this is clearer to you!

<img width="662" alt="Screenshot 2023-07-24 at 11 46 34 AM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/2428676e-63f2-4bd3-8b70-9dcf4e046b95">
