### ISSUE TITLE
[BUG] Discord Send Message to Forum Thread

### ISSUE THREAD

**Issue by AlexanderPaule** [PipedreamHQ/pipedream#7357]
**Describe the bug**
I'm trying to send a message to Discord Forum Thread and I'm not able to perform that action.
I'm expereimenting that issue in both available ways, Discord and Discord Bot.

This is a little bit frustrating me because the Discord API is using the same url `https://discord.com/api/channels/{channelId}/messages` to deliver messages to disocrd threads.
I've tried that API call on Postman and I was able to deliver messages to Forum Channel.

#### The error I see is:
Discord Bot: `50008 "Cannot send messages in non-text channel"`
Discord:  `"Request failed with status code 404"`

#### Axios
I've also tried to deliver message with direct API call to discord and that worked, but I need to use webhooks to send message with different usersnames, so I prefer to use Pipedream Components.

**To Reproduce**
1. Go to Workflows
2. Create new Workflow
3. Add Discord Bot Action
4. Compile Fileds:
> Guild (wish you want) *Where the Bot is active*
> Channel (Discord Forum Channel Id)
> Thread ID (Discord Forum Thread Id) *Required as by Discord API*
> Message (a test message) *Required as by Discord API*

**Expected behavior**
Send message to Discord Forum Channel and see it is successfully delivered.
Send message to Discord Forum Channel with overwrited username and avatar url and see it is successfully delivered.
Send message to Discord Forum Channel with attached file url and see it is successfully delivered.

**Screenshots**
Discord Bot
![image](https://github.com/PipedreamHQ/pipedream/assets/26071365/8ff3dff5-54f8-4b8b-bada-8608f71f2e7c)
Discord
![image](https://github.com/PipedreamHQ/pipedream/assets/26071365/a5361115-c3b6-43d2-8c6c-3e935b4fe468)

**Comment by AlexanderPaule** [comment]
Hi @vunguyenhung ,

Thank you, yes, I confirm the send message works now. Only the username override don't work with Discord Bot.
It's probably related with mismatching of the webhook.
Webhook is associated to Discord channel meanwhile message must be sent do Thread Id.
![image](https://github.com/PipedreamHQ/pipedream/assets/26071365/c36992b6-a709-482d-b60b-8045a80bdfbe)




With Discord component I'm able to override username but the send message to Forum Thread still doesn't work.
![image](https://github.com/PipedreamHQ/pipedream/assets/26071365/2e9c11df-2447-4f79-bdcd-83c5628434b6)

**Comment by AlexanderPaule** [comment]
This is the documentation:
https://discord.com/developers/docs/resources/webhook#execute-webhook

![image](https://github.com/PipedreamHQ/pipedream/assets/26071365/413728a0-437b-43e9-bb07-2fa2291d119f)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by AlexanderPaule** [comment]
Sorry @dylburger but I'm not sure this is a correct approach

I'm waiting for this functionality and provided to you all documentation on Discord Side.
Please reopen it and fix the problem.

I provided everything you need with proper timing, but did not get back any response.
I really don't understand why you closed this BUG...

Alex

**Comment by AlexanderPaule** [comment]
Hi @vunguyenhung 
Any news on this?

**Comment by AlexanderPaule** [comment]
Hi @vunguyenhung ,

Any news?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by AlexanderPaule** [comment]
Hi @vunguyenhung ,

I understand, so I'm proceeding with custom integration for delivering messages, but I have trouble to send files.
For me is acceptable to have files delivered without overriding of the username.

For doing that I need to use **send_message_with_file**, a Discord Bot Component.

To deliver attachments to Forum Channel was not possible cause of Pipedream Internal Error, so to exclude the Forum Chat Type and test the component itself I configured it to deliver message to Text Channel but also in this case I have an Error.
![image](https://github.com/PipedreamHQ/pipedream/assets/26071365/8b55376e-e6ed-43f0-b5f7-19189d6d9820)

This is the configuration:
![image](https://github.com/PipedreamHQ/pipedream/assets/26071365/03382abe-653a-48cd-9ae3-94c4523f2ca2)

Can you help me to fix this issue?
Thank you in advance
