### ISSUE TITLE
[Components] Airtable (OAuth)

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7358]
### App
Airtable (OAuth)
https://airtable.com/

Triggers:
1. Record Created: Activates when a new record is added to a specified base.
2. Record Updated: Activates when an existing record in a specific base is modified.

Actions:
1. Create Record: Adds a new record to a specific base.
2. Update Record: Modifies an existing record within a specific base.
3. Delete Record: Removes an existing record from a specified base.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
Won't do; already scoped.
