### ISSUE TITLE
[BUG] Share button doesn't work if Workflow doesn't have a name

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#736]
**Describe the bug**
I clicked the green Share button on a workflow that didn't have a name. It asked me to give a tag (which seems wrong, unless that's what we call the name of workflows), so I *cancelled* that UI, added a name to my workflow, and then tried to Share again. Now when I click nothing happens.

**To Reproduce**
1. Make a new workflow and never name it.
2. Click on Share
3. Dismiss the dialog asking you to provide a tag
4. Name the workflow
5. Click share again

I can confirm that when I left the workflow editing ui and went to my list of workflows, and then returned, share worked ok.

**Comment by tjk** [comment]
This should be fixed now. Thanks so much for reporting!
