### ISSUE TITLE
[APP] Vero

### ISSUE THREAD

**Issue by worldspawn** [PipedreamHQ/pipedream#7365]
Vero

https://developers.getvero.com/?bash

**Is lack of support preventing you from building workflows, or do you have a workaround?**

Identify and track requests please.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @worldspawn Thanks for the request

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/vero?via=go
