### ISSUE TITLE
[BUG] You can share a private workflow

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#737]
**Describe the bug**
I clicked Share on a private workflow and didn't notice it was private. (Ok, I did, but pretend I didn't. ;) I was able to take the URL, paste it in a new incognito window, and I got this:

![image](https://user-images.githubusercontent.com/393660/103229514-c63e6800-48f8-11eb-952e-0233eff09cd9.png)

Two things here. First, PD should respond with something like a 404 maybe. 
Second, maybe disable the copy to clipboard support if it's private? Of course, if I have collaborators, maybe I should be allowed to copy. Either way, just think of a way to make it more obvious in the Share dialog that it is *probably* not going to work.

**Comment by dylburger** [comment]
@cfjedimaster I hear you on the 404. We actually do respond with a 404, but the new UX fails to display the 404 page correctly. We can fix that.

On the second note - allowing you to copy the URL even when the workflow is private is common UX (e.g. Google Docs allows you to copy the URL on a private document). People commonly want to copy the URL to a workflow they own to keep as a reference somewhere for their own private use. We note that the workflow is **Private** just below that. If we fix the core 404 issue, do you think that addresses the general concern?

**Comment by cfjedimaster** [comment]
Yeah, and you are right.

**Comment by tjk** [comment]
The 404 issue should be fixed. Thanks for reporting!
