### ISSUE TITLE
[APP] CraftMyPDF

### ISSUE THREAD

**Issue by bktan81** [PipedreamHQ/pipedream#7372]
CraftMyPDF

[**Link to developer documentation**](https://craftmypdf.com/docs/index.html)
https://craftmypdf.s3.ap-southeast-1.amazonaws.com/craftmypdf_api/craftmypdf_api.yaml

I'm the founder of CraftMyPDF. Recently, a user asked us about the integration of Pipedream, and I noticed that there is a CraftMyPDF component created in the components folder. However, most of the core functions have not been implemented. 

The core functions are:
Create PDF
Create Image
Create editor session
Merge PDF URLs

**Comment by dannyroosevelt** [comment]
@undefined you've made the most commits in this app's directory over the last year, so I assigned you the issue.

- Sent via Pipedream
