### ISSUE TITLE
[BUG] SendGrid - BCC handling not optimal

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#7375]
**Describe the bug**
The `bcc` prop will pass on an empty array to SendGrid's API which causes a 400 error from Sendgrid:

```
"body": {
"errors": [
  {
    "message": "The bcc array, when used, must at least have an email parameter with a valid email address and it may also contain a name parameter. e.g. {\"email\" : \"[example@example.com](mailto:example@example.com)\"} or {\"email\" : \"[example@example.com](mailto:example@example.com)\", \"name\" : \"Example Recipient\"}.",
    "field": "personalizations.0.bcc",
    "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.bcc"
    }
  ]
}
```

**To Reproduce**
1. Create a new workflow
2. Use the `send_email_single_recipient` action
3. Pass an empty array to the **BCC** prop

**Expected behavior**
If the BCC array is empty, do not include the prop in the HTTP request to Sendgrid.

There are cases where users will dynamically pass BCC values, and we should intelligently drop that prop from the SendGrid API request so that users can still have their messages sent.

**Comment by dannyroosevelt** [comment]
@undefined you've made the most commits in this app's directory over the last year, so I assigned you the issue.

- Sent via Pipedream

**Comment by dannyroosevelt** [comment]
@lcaresia you've made the most commits in this app's directory over the last year, so I assigned you the issue.

- Sent via Pipedream
