### ISSUE TITLE
[ACTION] Zoho CRM

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#738]
**Is there a specific app this action is for?**
Zoho CRM

**Please provide a link to the relevant API docs for the specific service / operation.**
Convert Lead - Convert an existing lead to contact and account
Create Object - Create module entry if entry does not exist

**Comment by dannyroosevelt** [comment]
@michelle0927 this is ready for release! 

>Added via [Pipedream](https://pipedream.com/@/p_8rCkMkO?o=a&a=github)

**Comment by michelle0927** [comment]
@dannyroosevelt Looks like it removes the approval if I push changes in QA. Can you approve it? Thanks!
