### ISSUE TITLE
[APP] Moxie

### ISSUE THREAD

**Issue by blessingefkt** [PipedreamHQ/pipedream#7387]
**Name of app / service**
Moxie

**Link to developer documentation**
- Authentication Example: https://help.withmoxie.com/en/articles/8154735-public-api-fundamentals
- All Docs: https://help.withmoxie.com/en/collections/5482059-web-hooks-public-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I can create custom components with an API secret, but using an actual account / connector would be great.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Just having the auth support would be great to start. Here are some triggers and actions that would be a big help:

**Source Events / Triggers:**
- ClientCreate
- OpportunityCreate
- InvoiceSent
- PaymentReceived
- FormCompleted
- ProposalSent
- ProposalViewed
- ProposalSigned
- MeetingScheduled
- MeetingUpdated
- MeetingCancelled

**Actions:**
- List Clients
- Search Clients
- Create Client
- Create Contact
- Create Invoice
- Create Expense
- Create Form Submission
- Create Project
- Create Task
- Approve Deliverable
- Create Opportunity
- Create Time Entry

**Comment by sergio-eliot-rodriguez** [comment]
app has been submitted

**Comment by blessingefkt** [comment]
I've started working on a few actions. https://github.com/saylaco/pipedream/tree/main/components/moxie

**Comment by dannyroosevelt** [comment]
Let us know if you need any help or guidance @blessingefkt!

**Comment by sergio-eliot-rodriguez** [comment]
Closing this one https://pipedream.com/apps/moxie
