### ISSUE TITLE
[BUG] Errors coming from Microsoft Teams API while in workflow builder

### ISSUE THREAD

**Issue by gotta-be-dc** [PipedreamHQ/pipedream#7388]
**Describe the bug**

**To Reproduce**
1. Go to 'Workflow'
2. Select teams as trigger or action
3. Validate the account you will use
4. Select a trigger or action that requires you then choose a team or chat
5. See error

**Expected behavior**
Should be able to select the chat or channel to use as a trigger or to target for your action.

**Screenshots**
![image](https://github.com/PipedreamHQ/pipedream/assets/39798774/a344ece6-10f1-4a75-beed-5e2e868b8106)

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [chrome]
 - Version [115.0.5790.110]

NOTE: My azure has all rights granted in enterprise apps and my policy from teams admin is the default.

Posted the issue to the community as well to see if I am the only user to get this, no news yet.
https://pipedream.com/community/t/unable-to-configure-trigger-and-action-with-microsoft-teams/7694

**Comment by malexanderlim** [comment]
@lcaresia let's move to blocked in the meantime - and the blocker is that you need a work account to be able to validate. I will work on the right account and move back to prioritized when ready.

**Comment by gotta-be-dc** [comment]
Hey Pipers, is there anything I can do to assist here? Short of adding you to my company Microsoft environment?
