### ISSUE TITLE
[Components] Zoho Bookings

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7404]
### App
Zoho Bookings
https://www.zoho.com/bookings/

**Triggers:**
1. Appointment Booked: Triggers when a new appointment is scheduled in Zoho Bookings.
2. Appointment Cancelled: Triggers when an existing appointment is cancelled.
3. Appointment Rescheduled: Triggers when an existing appointment is rescheduled.

**Comment by alysonturing** [comment]
@vunguyenhung requests addressed
