### ISSUE TITLE
[Components] Zoho BugTracker

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7409]
### App
Zoho BugTracker
https://www.zoho.com/bugtracker/

**Triggers:**
1.  New Bug Reported: Notifies when a new bug is reported in Zoho BugTracker.

**Actions:**
1. Create Bug: Allows for a new bug to be created in the Zoho BugTracker system.
https://www.zoho.com/projects/help/rest-api/bugtracker-bugs-api.html#alink3
3. Update Bug: Lets you update the details of an existing bug in the system.
https://www.zoho.com/projects/help/rest-api/bugtracker-bugs-api.html#alink4
4. Get bug details:
https://www.zoho.com/projects/help/rest-api/bugtracker-bugs-api.html#alink2

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Zoho-BugTracker-7409-bf86fd17ef1a454986d30ee84136f854

Hi @vunguyenhung, sorry but I couldn't reproduce these errors
![Create Bug Test](https://github.com/PipedreamHQ/pipedream/assets/5638699/b0d84835-6d92-40c5-ac36-59d98c5f99e2)
