### ISSUE TITLE
[Components] Zoho Assist

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7414]
### App
Zoho Assist
https://www.zoho.com/assist/

**Actions:**
1. Create session
https://www.zoho.com/assist/api/createasession.html
2. Schedule session
https://www.zoho.com/assist/api/schedulesession.html
3. Get session reports
https://www.zoho.com/assist/api/getsessionreports.html

**Comment by GTFalcao** [comment]
@malexanderlim I get an error related to OAuth scopes when trying to obtain session reports. [According to this page](https://www.zoho.com/assist/api/scopes.html) it looks like that'd be the `ZohoAssist.reportapi.READ` scope - and checking the auth window details, indeed it seems we aren't requesting it.

**Comment by malexanderlim** [comment]
Should be all set here Guilherme!

**Comment by GTFalcao** [comment]
@vunguyenhung in order to infer the `UTC Offset` from `Time Zone` we will need to add a list of all timezones as options to this prop, do you agree?

**Comment by GTFalcao** [comment]
The exact format specified in their API was a very broad one, but it doesn't seem to be strictly enforced, so I've added a simplified list of timezones as options, and inferred the UTC Offset as you said. Should be easier to use now!

**Comment by GTFalcao** [comment]
@vunguyenhung I cannot reproduce the 'scheduling in the past' issue - I tried several (shortly in the future) dates that worked correctly, including your own exact input, and was able to get this error only when trying actual past timestamps.

As for 'get session reports', looks like it was expecting a different date format than the other action (oddly) - I fixed it to send the dates as unix time integers as expected by the API.
