### ISSUE TITLE
[TRIGGER + ACTION] TickTick 

### ISSUE THREAD

**Issue by stephen485** [PipedreamHQ/pipedream#7422]
TickTick

https://developer.ticktick.com/docs#/openapi 

* Trigger: New or Updated Task
* Action: Update Task

**Comment by dylburger** [comment]
@stephen485 Could you provide more detail on exactly what you'd like to do re: "Syncing of Status and changes"? For example, do you want to trigger a Pipedream workflow when a status of a task changes in TickTick? Or are you looking to update the status of a task in a workflow?

**Comment by stephen485** [comment]
My initial goal is to create a two-way sync between TickTick and Morgen Calendar Tasks, including updates to date and status fields in either app.
Is a sync considered a Workflow? Or do workflows contain other elements, like logic operations?

Stephen

**Comment by dylburger** [comment]
Thanks, that helps. Generally we think about these as two separate operations to give you the most flexibility:

1. Trigger: New or Updated Task — this would run a workflow each time a task was updated in TickTick
2. Action: Update Task — on Morgen Calendar Task updates, you could add this action to your workflow to update the TickTick task accordingly

Does this sound like it would work?

**Comment by stephen485** [comment]
Yes, that looks good. So these two steps update changes initiated from either app?
Morgen API is not yet publicly available, so I may try to replace that with the Microsoft To-Do app for now.


Thanks, that helps. Generally we think about these as two separate operations to give you the most flexibility:

  1.  Trigger: New or Updated Task — this would run a workflow each time a task was updated in TickTick
  2.  Action: Update Task — on Morgen Calendar Task updates, you could add this action to your workflow to update the TickTick task accordingly

Does this sound like it would work?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
