### ISSUE TITLE
[I want to look up the records on a Ninox table ]

### ISSUE THREAD

**Issue by bluewhal01010** [PipedreamHQ/pipedream#7436]
I have tried many times to make it available by http api , but failed , could you help me out ? thanks

**Comment by dylburger** [comment]
@bluewhal01010 Could you provide the link to the API docs for the app / endpoint you're trying to use? It would also help to see a screenshot of the step configuration and the exact error you're facing. That'll give us the detail we need to help.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
