### ISSUE TITLE
[APP] Wave

### ISSUE THREAD

**Issue by dzg** [PipedreamHQ/pipedream#7444]
**Name of app / service:**   
Wave / WaveApps

**Link to developer documentation:**   
**https://developer.waveapps.com/**

**Is lack of support preventing you from building workflows, or do you have a workaround?**  
Haven't tried yet

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**  
invoiceCreate

**Comment by sergio-eliot-rodriguez** [comment]
Hey hey hey @dzg !
Thanks for your request)))
And welcome to Pipedream.

We have Wave integrated, check out our basic integration https://pipedream.com/apps/wave

We are tracking Wave components at> https://github.com/PipedreamHQ/pipedream/issues/6633
this includes invoiceCreate. Kindly please follow there, if you'd like to receive notifications on progress.

**Comment by dzg** [comment]
> Wave integrated, check

Thanks!!
For some reason it did not show up when I searched.
