### ISSUE TITLE
BigQuery Actions

### ISSUE THREAD

**Issue by Stockotaco** [PipedreamHQ/pipedream#7464]
List Datasets
List Tables

Create Dataset
Create Table

Create Job

Run a query

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by Stockotaco** [comment]
Hello. Thank you for the reply. I apologize but I am not skilled enough to help build the integration. The app provider is Google… so I’m not sure they would be willing to build it themselves on Pipedream. I don’t even know who to reach out to. I am highly doubtful they would build the integration. On Aug 6, 2023, at 10:21 AM, Dylan J. Sather ***@***.***> wrote:﻿
Thanks for the request! Did you know that anyone can author and publish their own Pipedream actions? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.
If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Thanks @Stockotaco ! I just put this on the team's backlog. We'll post updates here as we work on these.

**Comment by malexanderlim** [comment]
Hi @Stockotaco , I'm going to close this ticket for now as the majority of the requested components are covered by our Google Cloud app - please let me know if you still need additional components for your use case!
https://pipedream.com/apps/google-cloud
