### ISSUE TITLE
Zoho Recruit

### ISSUE THREAD

**Issue by amalsynco** [PipedreamHQ/pipedream#7465]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @amalsynco 

Thanks for the request.

Zoho Recruit is already integrated: https://pipedream.com/apps/zoho-recruit

What's your Zoho Recruit in this case?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
