### ISSUE TITLE
[OAUTH SCOPE] New scopes for Fitbit

### ISSUE THREAD

**Issue by edreyyo** [PipedreamHQ/pipedream#7484]
**Which application needs a scope added?**
Fitbit

**What scope(s) need to be added?**
`temperature`, `oxygen_saturation`, `respiratory_rate`, `electrocardiogram` and `cardio_fitness` 

**Please provide a link to the relevant API docs for scopes.**
https://dev.fitbit.com/build/reference/web-api/developer-guide/application-design/#Scopes

**Comment by malexanderlim** [comment]
Hi @edreyyo , all set here - you should be able to see the new scopes when you reconnect the Fitbit app.
