### ISSUE TITLE
[APP] Microsoft OneNote

### ISSUE THREAD

**Issue by DrJGRobertsGSCM** [PipedreamHQ/pipedream#7487]
**Name of app / service** OneNote

**Link to developer documentation** https://developer.microsoft.com/en-US/onenote

**Is lack of support preventing you from building workflows, or do you have a workaround?** Yes

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!** Create Page within a Section of a Notebook

**Comment by sergio-eliot-rodriguez** [comment]
Hi @DrJGRobertsGSCM , thanks for the request.
And welcome to Pipedream!

We are tracking OneNote integration on ticket, #6682, please follow there, if you'd like.
