### ISSUE TITLE
MATRIX / Element / Beeper

### ISSUE THREAD

**Issue by ArneNostitz** [PipedreamHQ/pipedream#7503]
**Name of app / service**
Multi Messenger Service based on Matrix.org
**Link to developer documentation**
https://matrix.org
**Is lack of support preventing you from building workflows, or do you have a workaround?**
currently there is no way to sync msg from multiple sources to other apps like Clickup/CRM

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
on request sync msg threads to clickups comment section would be a great example. 
or on new msg send copy to somewhere else

**Comment by sergio-eliot-rodriguez** [comment]
Hi @ArneNostitz, thanks for the request!

I have created a different issue to track Element #7507, and Beeper #7508, since each it's an application on its own implementing the Matrix.org protocol. Feel free to follow those, if you'd like.

**Comment by sergio-eliot-rodriguez** [comment]
A [base integration](https://pipedream.com/apps/matrix?via=go) for Matrix has been previously released — feel free to check it out!

If you're new to Pipedream, you can [sign up here](https://pipedream.com/auth/signup?via=go) to start building workflows with free tiers available.
