### ISSUE TITLE
[APP] Bannerbear

### ISSUE THREAD

**Issue by rawkode** [PipedreamHQ/pipedream#752]
**Name of app / service**

Bannerbear

**Link to developer documentation**

https://developers.bannerbear.com/#introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?**

No, I can store API key in env

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Just auth

**Comment by todsac** [comment]
Bannerbear integration is done.  Here is a working example - https://pipedream.com/@tod/p_gYCMg9w
