### ISSUE TITLE
[ACTION] Bannerbear

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#753]
**Is there a specific app this action is for?**
Bannerbear

**Please provide a link to the relevant API docs for the specific service / operation.**
https://www.bannerbear.com/product/image-generation-api/

Create Collection - Generates multiple Images based on a Template Set
Create Image - Generates a new Image
Create Video - Creates a Video
Approve a Video - Approve a video to proceed with rendering
Create Animated Gif - Creates an Animated Gif
Edit a Video - Update a video auto-transcription

**Comment by dannyroosevelt** [comment]
@feyzullah are you working on this one?

**Comment by feyzullah** [comment]
> 

I was going to work on and left it after realizing Jorge was working on

**Comment by dannyroosevelt** [comment]
> > 
> 
> I was going to work on and left it after realizing Jorge was working on

Gotcha -- @jcortes you're on this one? (can you assign yourself if so?)

**Comment by vunguyenhung** [comment]
Reopen, since the related PR just added an action Create Image. The remaining actions still TODO

**Comment by jcortes** [comment]
@dannyroosevelt and @vunguyenhung  just to make sure we are in the same page. The remaining actioins are?
```
Create Collection - Generates multiple Images based on a Template Set
Create Image - Generates a new Image
Create Video - Creates a Video
Approve a Video - Approve a video to proceed with rendering
Create Animated Gif - Creates an Animated Gif
Edit a Video - Update a video auto-transcription
```

**Comment by vunguyenhung** [comment]
Sorry @dannyroosevelt @jcortes, I missed your messages 24 days ago. Since @jcortes has implemented remaining actions and link to this issue so I will use this issue to track 🙏. I will keep track of the notifications better next time
