### ISSUE TITLE
[APP] Create Libraria.dev app

### ISSUE THREAD

**Issue by beacoding** [PipedreamHQ/pipedream#7546]
**Name of app / service**
Libraria

**Link to developer documentation**
https://docs.libraria.dev/api-reference/authentication

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, it's preventing us from releasing the workflow to our users. The workaround would be to put the API key explicitly in every workflow, but that's unsafe (vs just configuring it once). So we'd hold off on releasing the action to our users until the app is created with proper authentication.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Yes! But we are planning to file our own PR (following Pipedream's rules) to create the action we want to expose to our users.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @beacoding 

Thank you so much for the request.

While we work on the app integration, may I suggest you try environment variables on your workflows:

> You should not include API keys or other sensitive data directly in your workflow's code. By referencing the value of an environment variable, instead, your workflow includes a reference to that variable — process.env.API_KEY — instead of the API key itself.

You can find more at: https://pipedream.com/docs/environment-variables/#environment-variables

Best

**Comment by malexanderlim** [comment]
Hi @beacoding , the Libraria app has been created. Let me know if you have any questions or run into any issues!
