### ISSUE TITLE
ImageKit.io

### ISSUE THREAD

**Issue by cindyshapiro** [PipedreamHQ/pipedream#7566]
ImageKit.io

[**Link to developer documentation**]
https://docs.imagekit.io/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It's looking like it's going to be very helpful to me in dealing with a bulk of images I'm going to need to be dealing with in terms of image overlays and things of that nature. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Uploads, overlays, and for other people, cropping and resizing might be nice!

**Comment by cindyshapiro** [comment]
I can workaround with NodeJS code in the interim, though

**Comment by malexanderlim** [comment]
Hi @cindyshapiro , the base integration is in place! I've scoped some components to be built here: https://github.com/PipedreamHQ/pipedream/issues/7722

However, I'm not finding overlays, or a way to crop or resize specifically in their API documentation. Do you know if this is possible via the API?

**Comment by cindyshapiro** [comment]
Wow! Fantastic. Thank you!

Cindy

Cindy Shapiro, CTO
Lost in Sound Records

lostinsoundrecords.com


￼

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/imagekit-io
