### ISSUE TITLE
VEND

### ISSUE THREAD

**Issue by davecrowe55** [PipedreamHQ/pipedream#757]
I would like to be able to test vend as a source

**Comment by dylburger** [comment]
@davecrowe55 thanks for the request. Just to confirm, are you referring to https://docs.vendhq.com/?

Is there a specific Vend event / events you’d like to use as a source?

**Comment by todsac** [comment]
I have integrated VendHQ as an integrated app.  Please let us know more detail on your source request.

Here is an integrated example: https://pipedream.com/@tod/vendhq-api-integration-example-p_13CgW9q

**Comment by davecrowe55** [comment]
> @davecrowe55 thanks for the request. Just to confirm, are you referring to https://docs.vendhq.com/?
> 
> Is there a specific Vend event / events you’d like to use as a source?

Yes I am working with vend inventory update webhooks, I can access it using request bin, but wasn't sure why I couldn't use it as a source itself.

**Comment by dylburger** [comment]
Thanks @davecrowe55 . I'm tracking that request at #761 . In the meantime, you can trigger any workflow from a webhook / HTTP request using our HTTP triggers (see the right section of the trigger selector). That'll give you a unique HTTP endpoint you can route any requests to.


<img width="1087" alt="Screen Shot 2021-01-05 at 2 30 34 PM" src="https://user-images.githubusercontent.com/242668/103707049-cf67ae80-4f62-11eb-92c0-04ce8c1d9553.png">

**Comment by dylburger** [comment]
@davecrowe55 now that we've integrated VEND as an app, I'm closing this ticket. Let us know if the webhook approach works for you for inventory update events and if you have any questions there, and feel free to follow #761 for the native source.
