### ISSUE TITLE
[BUG] Vestaboard `get_current_message` throws error

### ISSUE THREAD

**Issue by johndbritton** [PipedreamHQ/pipedream#7587]
**Describe the bug**
When I use the `get_current_message` action, I get an error.

**To Reproduce**
1. Go to edit a workflow
2. Add a step and choose `Vestabord - get_current_message`
3. Select the correct account
4. See error: `{"status":"error","message":"Missing Read / Write Key"}`

**Expected behavior**
Retrieve the current message.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: Safari
 - Version: 16.5.2

**Additional context**
The account is configured correctly, the `create_message` action works fine.

**Comment by johndbritton** [comment]
Here's what I see:
<img width="923" alt="Screenshot 2023-08-15 at 12 47 05 PM" src="https://github.com/PipedreamHQ/pipedream/assets/123345/622b06c9-bbac-4f0f-bee0-bb3e05f0993f">

My account credentials are stored as part of `jdb-board`. In another step I can use the same account successfully:
<img width="918" alt="Screenshot 2023-08-15 at 12 48 54 PM" src="https://github.com/PipedreamHQ/pipedream/assets/123345/57dfe91e-8102-49ea-b9e7-511042090cf3">

The only thing that I can think of is that the `create_message` has a subscription parameter, is something similar needed for the `get_current_message`?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by johndbritton** [comment]
@vunguyenhung The readwrite API key was missing, but other values were included. That fixed it. I didn't realize there were multiple keys needed.

Thanks!
