### ISSUE TITLE
[BUG] Adding a record to a data store is not instantaneous?

### ISSUE THREAD

**Issue by Defozo** [PipedreamHQ/pipedream#7594]
**Describe the bug**
I have 1 workflow that's being triggered twice almost at the same time. It seems that sometimes when I add a record in one instance, the other instance can add the same record and doesn't see the previous one.

**To Reproduce**
1. Create a workflow with get_record_or_create
2. Run it twice
3. See what happens

**Expected behavior**
I'd expect the key to be present at the second event.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 115.0.5790.171 (Official Build) (64-bit)

**Additional context**
My workflow deployment version: d_ZdsOooY7

**Comment by dannyroosevelt** [comment]
Hi @Defozo it sounds like there is likely a race condition -- I'd check out our docs on how to enable **concurrency** controls in your workflow: https://pipedream.com/docs/workflows/concurrency-and-throttling/#concurrency

**Comment by Defozo** [comment]
Yeah, I know about concurrency controls. Too bad it's a paid option :)

**Comment by dannyroosevelt** [comment]
Yes, we think it's a strong enough value-add to the capabilities that it justifies moving into a paid plan. Let me know if you have any feedback and if that gets you unblocked!
