### ISSUE TITLE
[Components] JustCall

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7620]
### App
JustCall
https://justcall.io/developer-docs/#end_points

**Triggers:**
https://justcall.io/developer-docs/#webhooks
1. Missed call
2. New text received
3. New contact

**Actions:**
1. Create contact
https://justcall.io/developer-docs/#add_contacts
2. Schedule a text message 
3. Send a text message
https://justcall.io/developer-docs/#send_text

**Comment by VibeCodesHere** [comment]
good analysis
