### ISSUE TITLE
[APP] omnivore

### ISSUE THREAD

**Issue by nitinthewiz** [PipedreamHQ/pipedream#7625]
**Name of app / service**
Omnivore

**Link to developer documentation**
https://docs.omnivore.app/integrations/api.html

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Pretty much. Their webhook is only for getting data out of the service, not into it. Only their API allows for URLs to be sent to the service.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- Add URL to your your read-it-later pile

**Comment by sergio-eliot-rodriguez** [comment]
Hi @nitinthewiz 

Thanks for your request))

**Comment by sergio-eliot-rodriguez** [comment]
Now integrated https://pipedream.com/apps/omnivore
