### ISSUE TITLE
[TRIGGER] dbtCloud - new sources/triggers

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#7635]
Triggers for dbtCloud

- Job Run Started - Emit event when a job has started
- Job Run Errored - Emit event when a job has errored
- New Job Run Event - Allow the user to choose one or more event types to emit (`job.run.started`, `job.run.completed`, `job.run.errored`).

https://docs.getdbt.com/docs/deploy/webhooks#create-a-new-webhook-subscription

**Comment by mroy-seedbox** [comment]
Something that might be worth displaying in the UI ([from the DBT documentation](https://docs.getdbt.com/docs/deploy/webhooks#create-a-new-webhook-subscription)):

> The `job.run.errored` event is a subset of the `job.run.completed` events. If you subscribe to both, **you will receive two notifications** when your job encounters an error.

It's not immediately obvious that this would be the case, so it can be a helpful warning to users.
