### ISSUE TITLE
[Components] Vitally

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7641]
### App
Vitally
https://www.vitally.io/

**Triggers:**
1. New customer created

**Actions:**
1. Create a message
https://docs.vitally.io/pushing-data-to-vitally/rest-api/messages

2. Create a note
https://docs.vitally.io/pushing-data-to-vitally/rest-api/notes

3. Create a task
https://docs.vitally.io/pushing-data-to-vitally/rest-api/tasks

**Comment by luancazarine** [comment]
@dannyroosevelt @malexanderlim To create an account at Vitally, you need to schedule a meeting with them. What should I do in this case?

**Comment by malexanderlim** [comment]
Hi @luancazarine , please check the 1Password vault - we have an API key in there!
