### ISSUE TITLE
Qonto

### ISSUE THREAD

**Issue by feliche93** [PipedreamHQ/pipedream#7646]
**Name of app / service**: Qonto / Business API

**Link to developer documentation**: https://api-doc.qonto.com/docs/business-api/ZG9jOjg0MjE3NzE-introduction

**Is lack of support preventing you from building workflows, or do you have a workaround?** Currently no work around since I do not know how to do the oAuth2 Flow with Qonto

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**:

For action the Create An Internal Transfer would be great, but overall would be really nice to have all major API Calls supported.

Thanks a ton!

Here's the reference in Make.com: https://www.make.com/en/integrations/gateway/qonto
and Zapier: https://zapier.com/apps/qonto/integrations

**Comment by sergio-eliot-rodriguez** [comment]
Hi @feliche93 

Thanks for the request. We're tracking Qonto on #7376 

Feel free to follow there, if you'd like.
