### ISSUE TITLE
[BUG] Trello Card Moved source is triggering twice

### ISSUE THREAD

**Issue by andrewjschuang** [PipedreamHQ/pipedream#7656]
**Describe the bug**
Trello Card Moved source is triggering twice for every moved card.

**Additional context**
Reported by a user

**Comment by andrewjschuang** [comment]
Requested more info from the user

**Comment by lcaresia** [comment]
I couldn't reproduce.

![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/818cc775-9af1-4392-9dce-bbe441f2e3b1)

Cc: @andrewjschuang @malexanderlim

**Comment by metaversememo** [comment]
Hi @andrewjschuang here is the logs you requested. Sorry for the delay.

2023-08-18T00:50:17
end
2023-08-18T00:50:17
db.get
db["listAfter"] ⭆ "Script QA"
2023-08-18T00:50:17
db.set
db["listAfter"] ⭅ "Script QA"
2023-08-18T00:50:17
start
{
  "method": "POST",
  "path": "/",
  "query": {},
  "client_ip": "18.234.32.228",
  "url": "https://1d28ce47b5821bf595f82609981fde4d.m.pipedream.net/",
  "headers": {
    "host": "[1d28ce47b5821bf595f82609981fde4d.m.pipedream.net](http://1d28ce47b5821bf595f82609981fde4d.m.pipedream.net/)",
    "content-length": "3396",
    "x-trello-webhook": "NS5/MFA8A+beGPS0HqpBDRPZX+M=",
    "content-type": "application/json",
    "user-agent": "Trello"
  },
  "bodyRaw": "{\"model\":{\"id\":\"62c3c875cdd0e05c808403ee\",\"name\":\"Metaverse Memo Video Workflow\",\"desc\":\"\",\"descData\":null,\"closed\":false,\"idOrganization\":\"62c3c875cdd0e05c808403ce\",\"idEnterprise\":null,\"pinned\":false,\"url\":\"[https://trello.com/b/UVRD43GN/metaverse-memo-video-workflow\](https://trello.com/b/UVRD43GN/metaverse-memo-video-workflow%5C)",\"shortUrl\":\"[https://trello.com/b/UVRD43GN\](https://trello.com/b/UVRD43GN%5C)",\"prefs\":{\"permissionLevel\":\"private\",\"hideVotes\":false,\"voting\":\"disabled\",\"comments\":\"members\",\"invitations\":\"members\",\"selfJoin\":true,\"cardCovers\":true,\"isTemplate\":false,\"cardAging\":\"regular\",\"calendarFeedEnabled\":false,\"hiddenPluginBoardButtons\":[\"618ecf94315a1a746748fc37\"],\"switcherViews\":[{\"viewType\":\"Board\",\"enabled\":true},{\"viewType\":\"Table\",\"enabled\":false},{\"viewType\":\"Calendar\",\"enabled\":false},{\"viewType\":\"Dashboard\",\"enabled\":false},{\"viewType\":\"Timeline\",\"enabled\":false},{\"viewType\":\"Map\",\"enabled\":false}],\"background\":\"blue\",\"backgroundColor\":\"#0079BF\",\"backgroundImage\":null,\"backgroundImageScaled\":null,\"backgroundTile\":false,\"backgroundBrightness\":\"dark\",\"backgroundBottomColor\":\"#0079BF\",\"backgroundTopColor\":\"#0079BF\",\"canBePublic\":true,\"canBeEnterprise\":true,\"canBeOrg\":true,\"canBePrivate\":true,\"canInvite\":true},\"labelNames\":{\"green\":\"\",\"yellow\":\"Thumbnail Ready for QA\",\"orange\":\"\",\"red\":\"\",\"purple\":\"\",\"blue\":\"\",\"sky\":\"\",\"lime\":\"\",\"pink\":\"\",\"black\":\"\",\"green_dark\":\"\",\"yellow_dark\":\"\",\"orange_dark\":\"\",\"red_dark\":\"\",\"purple_dark\":\"\",\"blue_dark\":\"\",\"sky_dark\":\"\",\"lime_dark\":\"Thumbnail Approved\",\"pink_dark\":\"\",\"black_dark\":\"\",\"green_light\":\"\",\"yellow_light\":\"\",\"orange_light\":\"\",\"red_light\":\"\",\"purple_light\":\"\",\"blue_light\":\"\",\"sky_light\":\"\",\"lime_light\":\"\",\"pink_light\":\"\",\"black_light\":\"\"}},\"action\":{\"id\":\"64def887349bb94705f40179\",\"idMemberCreator\":\"62c26d0f9da8008c7c5c0994\",\"data\":{\"card\":{\"idList\":\"62c3caa7671d3a728d4cc5c0\",\"id\":\"63fbb182518fc0d7b2529448\",\"name\":\"What is Pancakeswap?\",\"idShort\":64,\"shortLink\":\"CM4tUfuA\"},\"old\":{\"idList\":\"62c3c875cdd0e05c808403fe\"},\"board\":{\"id\":\"62c3c875cdd0e05c808403ee\",\"name\":\"Metaverse Memo Video Workflow\",\"shortLink\":\"UVRD43GN\"},\"listBefore\":{\"id\":\"62c3c875cdd0e05c808403fe\",\"name\":\"Video QA\"},\"listAfter\":{\"id\":\"62c3caa7671d3a728d4cc5c0\",\"name\":\"Script QA\"}},\"appCreator\":null,\"type\":\"updateCard\",\"date\":\"2023-08-18T04:50:15.372Z\",\"limits\":null,\"display\":{\"translationKey\":\"action_move_card_from_list_to_list\",\"entities\":{\"card\":{\"type\":\"card\",\"idList\":\"62c3caa7671d3a728d4cc5c0\",\"id\":\"63fbb182518fc0d7b2529448\",\"shortLink\":\"CM4tUfuA\",\"text\":\"What is Pancakeswap?\"},\"listBefore\":{\"type\":\"list\",\"id\":\"62c3c875cdd0e05c808403fe\",\"text\":\"Video QA\"},\"listAfter\":{\"type\":\"list\",\"id\":\"62c3caa7671d3a728d4cc5c0\",\"text\":\"Script QA\"},\"memberCreator\":{\"type\":\"member\",\"id\":\"62c26d0f9da8008c7c5c0994\",\"username\":\"williamdawkins7\",\"text\":\"William Dawkins\"}}},\"memberCreator\":{\"id\":\"62c26d0f9da8008c7c5c0994\",\"activityBlocked\":false,\"avatarHash\":\"f63946bc7fd2c0d6ef648b510f513a3d\",\"avatarUrl\":\"[https://trello-members.s3.amazonaws.com/62c26d0f9da8008c7c5c0994/f63946bc7fd2c0d6ef648b510f513a3d\](https://trello-members.s3.amazonaws.com/62c26d0f9da8008c7c5c0994/f63946bc7fd2c0d6ef648b510f513a3d%5C)",\"fullName\":\"William Dawkins\",\"idMemberReferrer\":\"61e2af03e16b1313dc37326b\",\"initials\":\"WD\",\"nonPublic\":{},\"nonPublicAvailable\":true,\"username\":\"williamdawkins7\"}},\"webhook\":{\"id\":\"64b473786c590b79289dfa4c\",\"description\":\"Pipedream Source ID\",\"idModel\":\"62c3c875cdd0e05c808403ee\",\"callbackURL\":\"https://1d28ce47b5821bf595f82609981fde4d.m.pipedream.net/\",\"active\":true,\"consecutiveFailures\":0,\"firstConsecutiveFailDate\":null}}",
  "body": {
    "model": {
      "id": "62c3c875cdd0e05c808403ee",
      "name": "Metaverse Memo Video Workflow",
      "desc": "",
      "descData": null,
      "closed": false,
      "idOrganization": "62c3c875cdd0e05c808403ce",
      "idEnterprise": null,
      "pinned": false,
      "url": "https://trello.com/b/UVRD43GN/metaverse-memo-video-workflow",
      "shortUrl": "https://trello.com/b/UVRD43GN",
      "prefs": {
        "permissionLevel": "private",
        "hideVotes": false,
        "voting": "disabled",
        "comments": "members",
        "invitations": "members",
        "selfJoin": true,
        "cardCovers": true,
        "isTemplate": false,
        "cardAging": "regular",
        "calendarFeedEnabled": false,
        "hiddenPluginBoardButtons": [
          "618ecf94315a1a746748fc37"
        ],
        "switcherViews": [
          {
            "viewType": "Board",
            "enabled": true
          },
          {
            "viewType": "Table",
            "enabled": false
          },
          {
            "viewType": "Calendar",
            "enabled": false
          },
          {
            "viewType": "Dashboard",
            "enabled": false
          },
          {
            "viewType": "Timeline",
            "enabled": false
          },
          {
            "viewType": "Map",
            "enabled": false
          }
        ],
        "background": "blue",
        "backgroundColor": "#0079BF",
        "backgroundImage": null,
        "backgroundImageScaled": null,
        "backgroundTile": false,
        "backgroundBrightness": "dark",
        "backgroundBottomColor": "#0079BF",
        "backgroundTopColor": "#0079BF",
        "canBePublic": true,
        "canBeEnterprise": true,
        "canBeOrg": true,
        "canBePrivate": true,
        "canInvite": true
      },
      "labelNames": {
        "green": "",
        "yellow": "Thumbnail Ready for QA",
        "orange": "",
        "red": "",
        "purple": "",
        "blue": "",
        "sky": "",
        "lime": "",
        "pink": "",
        "black": "",
        "green_dark": "",
        "yellow_dark": "",
        "orange_dark": "",
        "red_dark": "",
        "purple_dark": "",
        "blue_dark": "",
        "sky_dark": "",
        "lime_dark": "Thumbnail Approved",
        "pink_dark": "",
        "black_dark": "",
        "green_light": "",
        "yellow_light": "",
        "orange_light": "",
        "red_light": "",
        "purple_light": "",
        "blue_light": "",
        "sky_light": "",
        "lime_light": "",
        "pink_light": "",
        "black_light": ""
      }
    },
    "action": {
      "id": "64def887349bb94705f40179",
      "idMemberCreator": "62c26d0f9da8008c7c5c0994",
      "data": {
        "card": {
          "idList": "62c3caa7671d3a728d4cc5c0",
          "id": "63fbb182518fc0d7b2529448",
          "name": "What is Pancakeswap?",
          "idShort": 64,
          "shortLink": "CM4tUfuA"
        },
        "old": {
          "idList": "62c3c875cdd0e05c808403fe"
        },
        "board": {
          "id": "62c3c875cdd0e05c808403ee",
          "name": "Metaverse Memo Video Workflow",
          "shortLink": "UVRD43GN"
        },
        "listBefore": {
          "id": "62c3c875cdd0e05c808403fe",
          "name": "Video QA"
        },
        "listAfter": {
          "id": "62c3caa7671d3a728d4cc5c0",
          "name": "Script QA"
        }
      },
      "appCreator": null,
      "type": "updateCard",
      "date": "2023-08-18T04:50:15.372Z",
      "limits": null,
      "display": {
        "translationKey": "action_move_card_from_list_to_list",
        "entities": {
          "card": {
            "type": "card",
            "idList": "62c3caa7671d3a728d4cc5c0",
            "id": "63fbb182518fc0d7b2529448",
            "shortLink": "CM4tUfuA",
            "text": "What is Pancakeswap?"
          },
          "listBefore": {
            "type": "list",
            "id": "62c3c875cdd0e05c808403fe",
            "text": "Video QA"
          },
          "listAfter": {
            "type": "list",
            "id": "62c3caa7671d3a728d4cc5c0",
            "text": "Script QA"
          },
          "memberCreator": {
            "type": "member",
            "id": "62c26d0f9da8008c7c5c0994",
            "username": "williamdawkins7",
            "text": "William Dawkins"
          }
        }
      },
      "memberCreator": {
        "id": "62c26d0f9da8008c7c5c0994",
        "activityBlocked": false,
        "avatarHash": "f63946bc7fd2c0d6ef648b510f513a3d",
        "avatarUrl": "https://trello-members.s3.amazonaws.com/62c26d0f9da8008c7c5c0994/f63946bc7fd2c0d6ef648b510f513a3d",
        "fullName": "William Dawkins",
        "idMemberReferrer": "61e2af03e16b1313dc37326b",
        "initials": "WD",
        "nonPublic": {},
        "nonPublicAvailable": true,
        "username": "williamdawkins7"
      }
    },
    "webhook": {
      "id": "64b473786c590b79289dfa4c",
      "description": "Pipedream Source ID",
      "idModel": "62c3c875cdd0e05c808403ee",
      "callbackURL": "https://1d28ce47b5821bf595f82609981fde4d.m.pipedream.net/",
      "active": true,
      "consecutiveFailures": 0,
      "firstConsecutiveFailDate": null
    }
  }
}

**Comment by lcaresia** [comment]
@andrewjschuang Yes
