### ISSUE TITLE
[TRIGGER]
Synchronise send received wallet balance
Okx, coinmarketcap, Coinbase, binance, coinstats, https://hcuox.com, https://gexchain.com/

### ISSUE THREAD

**Issue by ee4a-Rx3UGI83UgVwLPIuk** [PipedreamHQ/pipedream#7659]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

Add url, from any of the listed platforms,

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
