### ISSUE TITLE
[APP] BruzuHQ

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#767]
https://docs.bruzu.com/

**Comment by todsac** [comment]
I have integrated Bruzu.  

Here is an example workflow:
https://pipedream.com/@tod/bruzuhq-api-integration-example-p_zACpzmb/

Here is Bruzu in the app marketplace:
https://pipedream.com/apps/bruzu

We don't handle the display of images well in the UI today but the workflow can still be valuable.
