### ISSUE TITLE
[ACTION] PandaDoc Create Document - include fields

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#7672]
Currently Create Document (from template or from file) doesn't allow including fields.

Just need to add a prop for the fields and add it to the API request sent to PandaDoc API.

**Comment by Sweetdevil144** [comment]
Hey @zalmanlew . I would like to take up the issue.

**Comment by zalmanlew** [comment]
@Sweetdevil144 sure, it's pretty simple to do - let me know if you need help.

**Comment by Sweetdevil144** [comment]
Sure. Can I get the slack link to your channel where we can discuss this in a better way.

**Comment by zalmanlew** [comment]
@Sweetdevil144 check out https://pipedream.com/support there's a up-to-date link to join the slack community.

**Comment by Sweetdevil144** [comment]
Sorry, but can you uplaod that link. It says the link is no longer valid. 
<img width="1440" alt="Screenshot 2023-08-22 at 12 51 25 PM" src="https://github.com/PipedreamHQ/pipedream/assets/117591942/7ed3cd3c-9281-407d-a262-791fad953f36">

**Comment by zalmanlew** [comment]
@Sweetdevil144 I just made a temporary link, will work for 30 days

https://join.slack.com/t/pipedream-users/shared_invite/zt-21qf309gi-7vayUkQHt~wY1oD1pW41ug

**Comment by Sweetdevil144** [comment]
Sorry @zalmanlew . I don't understand the concept ofthis. Hence, I don't think I will be able to fix this
