### ISSUE TITLE
[Components] Hookdeck

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#7686]
**Is there a specific app this action is for?**
Hookdeck

**Actions**
1. Create/update a connection
https://hookdeck.com/api-ref#createupdate-a-connection

2. Retrieve requests
https://hookdeck.com/api-ref#retrieve-all-requests
- Status
- Rejection Cause
- Source Name (async options call to https://hookdeck.com/api-ref#retrieve-all-sources for source name)
- Path
- Ingested at (provide range)
- Order By
- Direction
- Limit

3. Retrieve request events
https://hookdeck.com/api-ref#retrieve-request-events
- Please use props/ async options where possible, similar to above action for ease of use

4. Retrieve all events
https://hookdeck.com/api-ref#retrieve-all-events

**Comment by vellames** [comment]
Using Onepassword credentials:

![Uploading Screen Shot 2023-08-22 at 09.44.13.png…]()

**Comment by vellames** [comment]
@malexanderlim Still not able to login even after few attempts

**Comment by malexanderlim** [comment]
@vellames , I've added a new account under my name. Can you please give that a try?

@sergio-eliot-rodriguez , I'm not sure what is going on with the login that you have in 1Password but can confirm that I can't use it also.

**Comment by vellames** [comment]
@malexanderlim It worked with your credentials

**Comment by sergio-eliot-rodriguez** [comment]
this is really interesting, it's not working on my end either. but i guarantee that I had been able to login in other past attempts.
