### ISSUE TITLE
[ACTION] Xero - Find or Create Contact

### ISSUE THREAD

**Issue by ajlowndes** [PipedreamHQ/pipedream#7712]
**Which application needs a scope added?**
Xero

**Description**
- Find contact by EmailAddress, if the EmailAddress is not exists, create the contact
- Add the following props for creating a new contact: Email Address, Contact Name, FirstName, LastName, CompanyNumber, Addresses, Phones

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developer.xero.com/documentation/api/accounting/contacts/#post-contacts

**Comment by ajlowndes** [comment]
Sorry for the confusing title. When I said "script" I meant the action presented in Pipedream's interface. I assumed that the action is generated by the above linked script file. That file includes the header and description for this action which is
`name: "Find contact.  Optionally, create one if none are found"`

**Comment by ajlowndes** [comment]
I may have mis-categorised this issue as I'm not entirely sure if it is a "scope" issue after all, the description of that one (when creating a new issue) seemed to fit best.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by ajlowndes** [comment]
The first comment by me supplied the requested more information. It starts with "starting on line 46..." And continues all the way to "thank you for your attention". Is the further information I supplied not sufficient? Please advise and don't close this as completed if nothing has actually been completed. Thanks

**Comment by ajlowndes** [comment]
> Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

Struggling to find out how to reopen this issue, I may not have access to that. Can you please reopen it?

**Comment by dylburger** [comment]
@ajlowndes This was closed by a Pipedream workflow on accident. We’ll take a look at the details ASAP!
