### ISSUE TITLE
[Components] ImageKit.io

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7722]
### App
ImageKit.io
http://imagekit.io/

**Actions:**
1. Upload Image: This action allows you to upload a new image to ImageKit.io.
https://docs.imagekit.io/api-reference/upload-file-api/server-side-file-upload
2. Get file details:
https://docs.imagekit.io/api-reference/media-api/get-file-details
- With async option to List and Search Files
https://docs.imagekit.io/api-reference/media-api/list-and-search-files

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-ImageKit-io-7722-062cf9ece1574da6ac3db102389f0066

Hi @vunguyenhung. The "extensions" prop has failing because it expects an array and you are sending an invalid JSON.
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/c5cc41b3-6e33-4ce0-a29d-81da992d3ed5)

**Comment by luancazarine** [comment]
> Hi @luancazarine, actually only the test case for Custom Expression failed ![image](https://user-images.githubusercontent.com/18277920/265924653-9d3bf8b1-8ce2-4022-8463-8d3d41382580.png)
> 
> Please check the test report below

@vunguyenhung, I think I'm not understanding. this is failing because the object you are inserting is invalid, so it will fail anyway

**Comment by luancazarine** [comment]
> @luancazarine, the input for the `Extensions` prop is in custom expression `{{ }}`. Please see the Extensions input ![image](https://user-images.githubusercontent.com/18277920/266906726-af8bd1af-29a9-4d7f-b892-69e79db31694.png)
> 
> It's actually a valid JSON <img alt="image" width="1099" src="https://user-images.githubusercontent.com/18277920/266906819-b88a75eb-6419-4b12-87fd-6abbac8edec6.png">

Now I got it! Sorry for the misunderstanding, thanks for the explanation!
