### ISSUE TITLE
[APP] ShipHero

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#774]
**Name of app / service**
ShipHero

**Link to developer documentation**
https://developer.shiphero.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
N/A

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
List of available webhooks:
https://developer.shiphero.com/webhooks#webhooks

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integraed https://pipedream.com/apps/shiphero
