### ISSUE TITLE
[Components] Klaxoon

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7744]
### App
Klaxoon
https://klaxoon.com/

**Actions:**
1. Create board
https://developers.klaxoon.com/reference/v1boardpost
2. Create idea in board 
https://developers.klaxoon.com/reference/v1boardideapost
3. Update idea in board
https://developers.klaxoon.com/reference/v1boardideapatch

**Comment by lcaresia** [comment]
@vunguyenhung Related with #7930
