### ISSUE TITLE
[APP] Aleph Alpha

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#7775]
**Name of app / service**

 Aleph Alpha

**Link to developer documentation**

https://docs.aleph-alpha.com/api/

**Comment by sergio-eliot-rodriguez** [comment]
@dylburger 

Aleph Alpha is currently integrated in the app store as Luminous. The reason: Aleph Alpha is the app developer to Luminous.
https://pipedream.com/apps/luminous

I scaled to @malexanderlim in case the app should be renamed.

**Comment by malexanderlim** [comment]
A cool feature would be to have other search terms that users might use that would all redirect to the same app.
For example, if the app's name were **Luminous**, then a search to **Aleph Alpha** would also take you to the app. 

In the meantime, I think I will rename the app to "Aleph Alpha (Luminous)" to mirror what we have for OpenAI (ChatGPT) so users with both terms will still be able to find the app.
