### ISSUE TITLE
[BUG] Google My Business cannot add image to post

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#7784]
**Describe the bug**
I'm testing out the new GMB (#6979) integration to create posts, initial tests are ok, text is there and links to site work. However, I'm having trouble with adding images to it. The way it's worded I should be able to simply paste a URL in the box or use a Pipedream Variable. however I'm either getting `SUCCESS` but no image or `ERROR` and various messages about invalid links, media format required etc...

**To Reproduce**
1. Go to workflow and use GMB Create Post
2. Try and add media to post, so far I've tried variations as arrays or custom expression all with and without quotes on
    https://myserver.com/myimage.jpg
    {{steps.Get_data_for_new_item.$return_value[4].product.images[0].src}} `Would resolve to above`
    {{ {"sourceURL: https://myserver.com/myimage.jpg} }} `Based on images in Test Report linked below`
    {{ {"sourceURL: {{steps.Get_data_for_new_item.$return_value[4].product.images[0].src}}} }}
    sourceUrl: {{steps.Get_data_for_new_item.$return_value[4].product.images[0].src}}
4. Test and see error or success but no image

**Expected behavior**
Image should appear on post

**Screenshots**
![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/11c67905-d3fa-4e30-8347-9072e781c126)
![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/94fda07a-7c00-49cd-aa8d-3c7f1f1cba2e)

**Desktop (please complete the following information):**
 - OS: Win 10 Chrome/Firefox and latest updates for all

**Additional context**
From the [Test Report](https://vunguyenhung.notion.site/Components-Google-My-Business-6979-1c05dd88a1ba458ebcbca2619393dcc0) it looks like I should be using a custom expression for the media (represented by the bar symbol but no luck)

**Comment by NebularNerd** [comment]
Hi @vunguyenhung,

The image is publicly accessible from it's url so that should not be an issue, to help with testing I'll use a common image we can both test with.
[https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/SMPTE_Color_Bars.svg/1024px-SMPTE_Color_Bars.svg.png](https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/SMPTE_Color_Bars.svg/1024px-SMPTE_Color_Bars.svg.png)

Using 
`{{ {"sourceURL" : "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/SMPTE_Color_Bars.svg/1024px-SMPTE_Color_Bars.svg.png", "media_format": "PHOTO"} }}`
Gives
![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/e61fcca4-0a24-400e-8ffa-dea41f5addd2)

Using
`{"sourceURL" : "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/SMPTE_Color_Bars.svg/1024px-SMPTE_Color_Bars.svg.png", "media_format": "PHOTO"}`
Gives
![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/9769ef1f-6feb-49b5-b1cb-c755e712a421)

**Comment by NebularNerd** [comment]
I've also just tested using the same Pinterest image as in the test report in various forms, still no luck, same errors as above. 
`{{ {"sourceURL" : "https://i.pinimg.com/564x/1e/70/96/1e709685895f980dc8ab3fd5d1fbbcc6.jpg", "media_format": "PHOTO"} }}`

**Comment by NebularNerd** [comment]
@vunguyenhung 

I think the issue is how the string is being constructed, looking at the source: https://github.com/PipedreamHQ/pipedream/blob/53631ed0a60b1cc963e44e970eec62bb65ad0f83/components/google_my_business/actions/create-post/create-post.ts#L64-L69
We only need to supply a plain url, after which Pipedream creates the string by prepending it with `[{"sourceUrl":"` then appending `"}]`

![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/7c01a80a-8157-477b-9f0c-0dc3a092dbf4)

This fails to post (some details changed/omitted) using your Pinterest test image. 

```{"topicType":"STANDARD","languageCode":"EN","summary":"Awesome exciting news post","callToAction":{"url":"https://google.co.uk ","action_type":"LEARN_MORE"},"media":[{"sourceUrl":"https://i.pinimg.com/564x/1e/70/96/1e709685895f980dc8ab3fd5d1fbbcc6.jpg"}],"alertType":"ALERT_TYPE_UNSPECIFIED"}```

This is a good fail because it no longer complains about the link being invalid as it's in the correct format. The invalid link issues are being caused because of how the string is being created. If we try to add `mediaFormat` (This is correct per the Google REST docs, media_format is from the reply) back into the mix:

`"media":[{"sourceUrl":"https://i.pinimg.com/564x/1e/70/96/1e709685895f980dc8ab3fd5d1fbbcc6.jpg,\"media_format\": \"PHOTO\""}]`

We can see it will go horribly wrong, escaped and double `"` and so forth, Google spits back the an error about the missing mediaFormat, but not the link as 'technically' we have only supplied a link. Using earlier examples with all the braces caused the other errors because the json gets super messy and just breaks Google.

**SOLUTION**
We need to provide the correctly formatted string as follows:
`"media":[{"sourceUrl":"https://i.pinimg.com/564x/1e/70/96/1e709685895f980dc8ab3fd5d1fbbcc6.jpg","mediaFormat": "PHOTO"}]`

I guess the easiest solution is to leave `Media` as is, then create a `Media Format` option with dropdowns for `PHOTO`, `VIDEO` or `MEDIA_FORMAT_UNSPECIFIED` (although the last one is likely best left out) and helper text `Format must be selected to ensure post success` or similar (or combine it into `Media` if possible). Behind the scenes take the two inputs and create the correctly formatted string.

**Comment by NebularNerd** [comment]
@vunguyenhung 

Is there a timetable for this to be fixed? I'm not familiar with Typescript otherwise would try taking a crack at it myself.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by NebularNerd** [comment]
@dylburger What further information can I provide? I thought I gave enough as @vunguyenhung had give a thumbs up so was waiting for the feature to be fixed.

The current implementation does not allow images to be posted, I shared logs and linked to where the issue is in the code. If you can get an image to post on the current code please provide an example I can test against.

**Comment by NebularNerd** [comment]
Thanks @vunguyenhung, I look forward to seeing this running soon. 🙂

**Comment by GTFalcao** [comment]
I've included the media format prop and successfully tested with an actual photo [(link)](https://www.shutterstock.com/shutterstock/photos/2205537087/display_1500/stock-photo-a-nice-picture-with-a-rose-for-decoration-2205537087.jpg) - not any image is accepted as a photo though, there is a minimum size requirement I bumped into when using the test image with plain colors.

Although the documentation has "unspecified format" as part of the enum, when this is used, the API responds as if the parameter is missing - so I added only the two other options (`PHOTO` and `VIDEO`) to the prop.

**Comment by GTFalcao** [comment]
@vunguyenhung is the expected result to be able to include multiple photos and/or videos? I'm asking because I'm not sure changing the upload method will remove the limitation of only 1 photo being attached to the post (and videos not being currently supported) - so I want to know if this expected when testing it

**Comment by NebularNerd** [comment]
Looking forward to giving this a test drive 😎
