### ISSUE TITLE
[APP] AskYourPDF

### ISSUE THREAD

**Issue by Loayalayoubi** [PipedreamHQ/pipedream#7789]
**Name of app / service**
AskYourPDF
https://askyourpdf.com/

**Link to developer documentation**
https://docs.askyourpdf.com/askyourpdf-docs

**Actions**
Upload Document https://docs.askyourpdf.com/askyourpdf-docs/#uploading-a-document

**Comment by sergio-eliot-rodriguez** [comment]
Hello @Loayalayoubi 

First of all, welcome to [Pipedream](https://pipedream.com?via=go)! The integration platform for developers!!

Second, thank you for the request. App request like yours help [Pipedream](https://pipedream.com?via=go) support more applications being natively integrated in the app martketplace.

For now, I'll head out to take care of a basic app integration. And at a later stage your Upload Document action request will be implemented.

Finally, a piece of advice, for new requests, consider providing more details, issue #7383 is a good example.

And that's it. Keep an eye on the issue. This dould be updated soon.

Warm regards,
Sergio

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/askyourpdf?via=go
