### ISSUE TITLE
[BUG] In Event History screen > Search for Workflow search box, I can not find workflows in a Project

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7790]
**Describe the bug**
In Event History screen > Search for Workflow search box, I can not find workflows in a Project
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/13e1c7d1-c41d-45dc-86a8-491d8706d7ee)

Even though recently I only create workflows in a Project
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/da83119e-ff83-43d8-9354-703ce794f160)

**Expected behavior**
I should see workflows in Project and workflows outside of a Project

**Additional context**
Reported by a customer here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1693208281268789

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
