### ISSUE TITLE
[APP] GraphQL 

### ISSUE THREAD

**Issue by ProdigyMaster** [PipedreamHQ/pipedream#780]
Hey, It would be very useful if you'll have graphql api step 😉

BTW. Very cool product 👍

**Comment by dylburger** [comment]
@ProdigyMaster thank you for the feedback and the kind words. 

Can you tell me more about the kind of action you'd like to see, and more about how you'd like to interact with a GraphQL API?

If it helps, you can make a GraphQL request today by including the query or mutation in the **Payload** of the **Send HTTP Request** action. [Here's an example workflow](https://pipedream.com/@dylburger/linear-graphql-example-p_V9CeOe/edit) using [Linear's API](https://github.com/linearapp/linear/blob/master/docs/API.md):

<img width="1948" alt="Screen Shot 2021-01-09 at 1 44 23 PM" src="https://user-images.githubusercontent.com/242668/104109363-eddeea00-5281-11eb-87f1-5abb4112055b.png">

Does that help, or are you looking for something else?

**Comment by dylburger** [comment]
@ProdigyMaster I just wanted to check in to see if this helped, or if you were looking for something else.

**Comment by dylburger** [comment]
Closing this issue. Please let me know if the HTTP Request action doesn’t help and if you have a more specific use case - happy to re-open.
