### ISSUE TITLE
[Components] iLovePDF

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7804]
# iLovePDF
## URLs
- https://developer.ilovepdf.com/docs/api-reference#introduction 

#### Prompt
Triggered once a file conversion process has finished
#### URLs
- https://developer.ilovepdf.com/docs/api-reference#process

#### Prompt
Triggered after a file has been successfully uploaded to iLovePDF
#### URLs
- https://developer.ilovepdf.com/docs/api-reference#task

#### Prompt
Converts uploaded files into PDF format using iLovePDF
#### URLs
- https://developer.ilovepdf.com/docs/api-reference#request-workflow
- https://developer.ilovepdf.com/docs/api-reference#start
- https://developer.ilovepdf.com/docs/api-reference#upload
- https://developer.ilovepdf.com/docs/api-reference#process
- https://developer.ilovepdf.com/docs/api-reference#download

#### Prompt
Combines multiple PDF files into one unified document
#### URLs
- https://developer.ilovepdf.com/docs/api-reference#request-workflow
- https://developer.ilovepdf.com/docs/api-reference#start
- https://developer.ilovepdf.com/docs/api-reference#upload
- https://developer.ilovepdf.com/docs/api-reference#process
- https://developer.ilovepdf.com/docs/api-reference#download

#### Prompt
Reduces the size of a PDF file while maintaining its quality
#### URLs
- https://developer.ilovepdf.com/docs/api-reference#request-workflow
- https://developer.ilovepdf.com/docs/api-reference#start
- https://developer.ilovepdf.com/docs/api-reference#upload
- https://developer.ilovepdf.com/docs/api-reference#process
- https://developer.ilovepdf.com/docs/api-reference#download

**Comment by andrewjschuang** [comment]
Please continue coding on top of this Draft PR: #8414

**Comment by GTFalcao** [comment]
I've sent an email to iLovePDF's support requesting help with the file content they are returning - as it is not resulting in a valid file when written. I'll block this for the time being since they have not responded yet.

**Comment by GTFalcao** [comment]
Sorry @vunguyenhung , I tunneled into the file writing issue and forgot about the extra parameters!

It's implemented now. Tested with the `pdfjpg` tool adding the extra parameter `pdfjpg_mode`, with the value `extract` resulting in 15 files and the value `pages` resulting in a single file.
