### ISSUE TITLE
Ftrack Updates[ACTION]

### ISSUE THREAD

**Issue by stylefit** [PipedreamHQ/pipedream#7823]
Hi Team 
The new Ftrack pieces are awesome are working nicely! 
Just wondering if we can get them tweaked a little to make them more user friendly in workflows? 

Specific needs - 

Hoping to have these modules work similar to click up in the sense a get item, shows all the attributes like a click up get item does not just the name etc. Also if possible that it should be either any ibject type or the module requests what type of item youd like to 'get' as currently its only buuilt to accomdate 'tasks'. 

And for the update object, similar reuqests as to click up so we can updte status', custom attributes etc etc not just a name eg. 

Or if there is just a way to open up the module to allow us to add these extra bits to it ?

**Comment by stylefit** [comment]
Hi Leo
I just got this from ftrack support.


Hi Binyamin,
the current js documentation is a bit out of dated and has to be fixed,
in the meanwhile , could you please try the following ?

1) open your ftrack instance
2) open the browser development tool ( in chrome : CTRL + SHIFT + I )
3) open the javascript console

here you can then rely on a pre built session and start playing with it as :

let session = ftrackSpark.getSession()
let projects = await session.query("select name from Project");
projects.data

this should result in a similar output as the attached screenshot.
You can keep on using the session variable to do more queries and discover around your project.



This , of course, is just to get you started with the api.
If you want to use it in a separate application or from a dashboard , you can create a single page application with npm as following:



npm create ***@***.*** ftrack-test-api -- --template vanilla
npm install --save @ftrack/api

Then modify the main.js to import the ftrack api:


import { Session } from ***@***.***/api';

then create the session with your credentials and have a session to rely on for the queries you are after.

To start the server you can then run


npm run dev

This will then be serving the page at an address similar to http://localhost:5173<http://localhost:5173/>



Hope it helps.
L.




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
