### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by Fisseha-Estifanos** [PipedreamHQ/pipedream#7825]
Instagram

https://developers.facebook.com/docs/instagram/

It is actually making me not progress anymore.

Normal posting to Instagram based on a given time schedule would be just great.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there @Fisseha-Estifanos 

Thanks for the request! And for being a [Pipedream](https://pipedream.com?via=go) user!

There's a ticket tracking Instagram here: https://github.com/PipedreamHQ/pipedream/issues/445. Kindly subscribe to it to be updated!
