### ISSUE TITLE
[Components] Eden AI

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7832]
### App
Eden AI
https://www.edenai.co/

**Actions:**
1. Translate text
https://docs.edenai.co/reference/translation_document_translation_create
2. Detect AI content
https://docs.edenai.co/reference/text_ai_detection_create
3. Analyze sentiment in text
https://docs.edenai.co/reference/text_sentiment_analysis_create
4. Generate an image
https://docs.edenai.co/reference/image_generation_create

**Comment by gotta-be-dc** [comment]
Are we also getting an action to Generate a TTS file?

**Comment by GTFalcao** [comment]
@gotta-be-dc do you mean generating text from audio, or the other way around?

From their documentation it seems generating audio [can be done synchronously](https://docs.edenai.co/reference/audio_text_to_speech_create), but [generating text is async-only](https://docs.edenai.co/reference/audio_speech_to_text_async_create) so it'd need one action to make the initial request, and subsequent action runs to later check on the status and obtain the results for that request.

**Comment by gotta-be-dc** [comment]
I was thinking of generating audio. Since that part can be single step. Needs a high timeout which should prob be a tool too in the UI tho

**Comment by GTFalcao** [comment]
@vunguyenhung , I'm unable to reproduce the file error, as I can successfully upload a .txt or a .pdf file, but I've adjusted the path parsing slightly for cases where the user passes `tmp/` in the path string.

I've added the providers as options, but you listed many more for "Translate Document" than are available in the documentation - I added the two providers that are documented (`deepl` and `google`), let me know if this should be different.
