### ISSUE TITLE
Gong.io Integration request

### ISSUE THREAD

**Issue by DannyV-JS** [PipedreamHQ/pipedream#7838]
**Gong.io**

**https://app.gong.io/settings/api/documentation#overview**

**yes I'm having to do a large manual process**

**pulling call transcripts and meta data for analsysis**

**Comment by sergio-eliot-rodriguez** [comment]
1 month follow up

**Comment by sergio-eliot-rodriguez** [comment]
Hello @DannyV-JS 

First of all, welcome to [Pipedream](https://pipedream.com/?via=go)! The integration platform for developers!!

Second, thank you for the request. App request like yours help [Pipedream](https://pipedream.com/?via=go) support more applications being natively integrated in the app martketplace.

For now, I've reach out to Going support team to get a sandbox for development. This is needed to startup the integration.

Finally, a request for you. Could you reach out to Gong? Usually app developers are willing to expedite providing a sandbox, or an account for development if there are using asking for an integration with Pipedream.

And that's it. Keep an eye on the issue. We'll get to this as soon as we get setup with Gong account.

Warm regards,
Sergio

**Comment by sergio-eliot-rodriguez** [comment]
reached out to their info handle email

**Comment by sergio-eliot-rodriguez** [comment]
Apparently Gong was integrated and some components built sometime in late September / early October (per #7994  and #8104)
https://pipedream.com/apps/gong
but looks like the app has been set to admin only

**Comment by malexanderlim** [comment]
Hi @DannyV-JS , please let us know if there are any components that you'd like to see for the Gong integration!
