### ISSUE TITLE
[Components] Jumpseller

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#7861]
### App
Jumpseller
https://jumpseller.com/

**Triggers:**
https://jumpseller.com/support/api/#tag/Hooks/paths/~1hooks.json/post
1. Order Updated
2. Order Paid

**Actions:**
1. Create product
https://jumpseller.com/support/api/#tag/Products/paths/~1products.json/post
- Name
- Price
- Description
2. Create product variant 
- List products https://jumpseller.com/support/api/#tag/Products/paths/~1products.json/get
3. Update product
- List Products https://jumpseller.com/support/api/#tag/Products/paths/~1products.json/get

**Comment by vellames** [comment]
@malexanderlim The current account in **1password** is expired. I tried to create a new one, but when I try to connect to the application using pipedream platform I receive the following error:
**Your store does not have permission to access this application.**

**Comment by michelle0927** [comment]
@malexanderlim I'm seeing the same message that @vellames reported when trying to connect the account in 1Password with Pipedream.

<img width="592" alt="Screenshot 2023-10-12 at 12 59 38 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/78cdaf0b-cbaf-4c15-9194-7d4c61b7282e">

**Comment by malexanderlim** [comment]
Okay, @michelle0927   I've tested again and you should be able to connect, using my account (michael@...)
