### ISSUE TITLE
[Components] Nudgify

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#7866]
### App
Nudgify
https://www.nudgify.com/

**Actions:**
1. Create purchase nudge
https://www.nudgify.com/docs/knowledge-base/api-purchase-nudges/

2. Create sign-up nudge
https://www.nudgify.com/docs/knowledge-base/rest-api-for-sign-ups/#example-request-body

**Comment by GTFalcao** [comment]
I'm linking the branch with the finished code for the components, and marking this as blocked, as Nudgify requires API usage to be "activated" on a nudge, but I haven't been able to figure out how to do this (the documentation shows screenshots which do not match the appearance of the platform for me - there are no API related options when creating a nudge).

@malexanderlim
