### ISSUE TITLE
SmartSuite 

### ISSUE THREAD

**Issue by GitJuhb** [PipedreamHQ/pipedream#7870]
SmartSuite (Airtable like app)

[**Link to developer documentation**] https://developers.smartsuite.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I haven't sufficient knowledge or resources to create a trigger

Everything that is supported in Airtable.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there, SmartSuite is integrated 
https://pipedream.com/apps/smartsuite
