### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by lloyd2580** [PipedreamHQ/pipedream#788]
steps.
trigger
trigger
Off

New Submission (Instant)

Action: Send SMS via TextLocal

**Comment by todsac** [comment]
I have integrated TextLocal and here is a demo workflow:
https://pipedream.com/@tod/textlocal-api-integration-example-p_NMC9Z1V/edit

You can build out any actions, such as Send SMS, and share them with the community.  Alternatively, we will add this action to our queue but this is a low priority app at this time.

**Comment by lloyd2580** [comment]
Hello PipedreamHQ/pipedream,

There is no option where i can select to send message after i receive form
submission on Jotforms.

I am looking forward a process like the below, this is example of Twilo,

https://pipedream.com/@pravin/send-an-sms-on-http-request-using-twilio-p_JZCxz1/edit

Thanks & Regards
Lloyd
