### ISSUE TITLE
[ACTION] Google Cloud Platform - BigQuery create a scheduled query

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7880]
**Is there a specific app this action is for?**
Google Cloud Platform

**Please provide a link to the relevant API docs for the specific service / operation.**
https://cloud.google.com/bigquery/docs/scheduling-queries#api

**Comment by ShatilKhan** [comment]
Can you please assign this issue to me?
I might need some additional info on this..

**Comment by malexanderlim** [comment]
This has been completed in https://github.com/PipedreamHQ/pipedream/issues/8624
