### ISSUE TITLE
[APP] Datadog

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#790]
**Name of app / service**
Datadog

**Link to developer documentation**
https://docs.datadoghq.com/api/v1/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
The current integration with Datadog does not require/allow users to enter the API URL that correspond to their org/setup.
A workaround for this is to use the default US URL until this option becomes available.

From the Datadog docs:
> Note: All Datadog API clients are configured by default to consume Datadog US site APIs. If you are on the Datadog EU site, set the environment variable DATADOG_HOST to https://api.datadoghq.eu or override this value directly when creating your client.

Workaround until this is implemented (assuming the setting will be exposed via `$auth.base_url`):
```js
module.exports = {
  type: "app",
  app: "datadog",
  methods: {
    _baseUrl() {
      return (
        this.$auth.base_url ||
        "https://api.datadoghq.com/api/v1"
      );
    },
  },
};

```

**Comment by dylburger** [comment]
This is done!
