### ISSUE TITLE
Additional (or custom) Quota Alerts instead of only 80% 

### ISSUE THREAD

**Issue by yoraysa** [PipedreamHQ/pipedream#7902]
I forgot one of my monitor workflows open by mistake... as a result 80% of my quota burned.
If I would be alerted at the 25%, 50%, 75%, 90% etc points rather than just the 80%, I wouldn't burn so much of it....

![2023-09-05_22-15-37](https://github.com/PipedreamHQ/pipedream/assets/9439146/1cc81580-4065-4553-81d2-2587b4ea9d37)

**Comment by dylburger** [comment]
@yoraysa realtime credits usage is exposed [in our REST API](https://pipedream.com/docs/api/rest/#get-a-workspace). Could you write a script to check that and send you a notification at the appropriate time?

**Comment by yoraysa** [comment]
@dylburger
I will check that... a workflow with a pre-written script would ease the process though...

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
