### ISSUE TITLE
[ACTION] Survey Monkey

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#791]
**Is there a specific app this action is for?**
SurveyMonkey

**Please provide a link to the relevant API docs for the specific service / operation.**
Get a Collector - Get the specific collector information.
Get a Response - Get the specific response information. Paid SurveyMonkey account is required (Advantage or higher).
Get a Survey - Get the specific survey information.
Get My Info - Returns the current user’s account details including their plan.
Search for a collector - Returns a list of collectors.
Search for a response - Returns a list of responses.
Search for a survey - Returns a list of surveys.

**Comment by dannyroosevelt** [comment]
This is ready for release!
