### ISSUE TITLE
[Components] KickoffLabs

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#7920]
### App
KickoffLabs
https://kickofflabs.com/

**Actions:**
1. Create or update a lead 
https://dev.kickofflabs.com/create/
2. Get campaign stats
https://dev.kickofflabs.com/stats/
3. Remove lead from campaign
https://dev.kickofflabs.com/optout/

**Comment by vellames** [comment]
@vunguyenhung I checked the API and all fields are correctly sent. This seems a behaviour from the API
