### ISSUE TITLE
Integrating WebSocket 

### ISSUE THREAD

**Issue by TeamsAcademy** [PipedreamHQ/pipedream#7940]
I have a platform that uses real-time data stream using a web socket, I wonder how can I implement this web socket into Pipedream so that whenever the web socket receives a new notification, Pipedream will manipulate that notification as per the workflow

Platform is: https://www.pushbullet.com
Code Sample: https://jsfiddle.net/pushbullet/u92DA/
Documentation: https://docs.pushbullet.com/#realtime-event-stream

**Comment by sergio-eliot-rodriguez** [comment]
@TeamsAcademy plesae check if current implementation works for you:
https://pipedream.com/apps/pushbullet

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
