### ISSUE TITLE
Tilda[APP]

### ISSUE THREAD

**Issue by KatiKida** [PipedreamHQ/pipedream#7941]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @KatiKida 

Thanks for the request! And for using [Pipedream](https://pipedream.com?via=go)

We have Tilda integrated https://pipedream.com/apps/tilda

But if you are referring to a different app, let us know!

**Comment by KatiKida** [comment]
Hej,

Yes, cool! thanks a lot.

How can I get data from the new Leads from Tilda?

KR
Denis
