### ISSUE TITLE
[ACTION] Return an HTTP response

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#7944]
**Is there a specific app this action is for?**

A general Helpers function

**Please provide a link to the relevant API docs for the specific service / operation.**

Add an action to perform an HTTP response using the default scaffolding code + props to accept an object:

```javascript
// To return a custom HTTP response, use $.respond() [requires HTTP trigger]
export default defineComponent({
  async run({ steps, $ }) {
    await $.respond({
      status: 200,
      headers: {},
      body: "hello world!",
    })
  },
})

```

Here's my suggestion on exposing the `status`, `body` and `headers` of the response by props:

https://gist.github.com/ctrlaltdylan/54436d077a509d2471c709d44f01b855

**Comment by dylburger** [comment]
This action exists under the **HTTP** app:

<img width="469" alt="Screenshot 2023-09-07 at 10 18 31 AM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/cf9a6211-c47c-428a-b76e-bc6d3a7b775e">

<img width="935" alt="Screenshot 2023-09-07 at 10 18 51 AM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/cfdd69b8-aded-4501-9f06-57604821da27">
