### ISSUE TITLE
Mattermost

### ISSUE THREAD

**Issue by r2ravi** [PipedreamHQ/pipedream#7956]
**Mattermost**

**Link to developer documentation: https://api.mattermost.com/#tag/introduction**

**Is lack of support preventing you from building workflows, or do you have a workaround?: Want to build the most efficient workflow possible. Would rather have a built-in trigger as opposed to using a webhook in Pipedream.**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!

Trigger: Message in Mattermost Channel
Action: Every time a message is sent in a given Mattermost channel, that same message should be sent in a Slack channel**

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
