### ISSUE TITLE
[FEATURE] Workflow Management

### ISSUE THREAD

**Issue by rawkode** [PipedreamHQ/pipedream#797]
**Is your feature request related to a problem? Please describe.**
 
The workflows list becomes a little cumbersome as you begin to adopt Pipedream more and create and work with more than a handful of workflows

**Describe the solution you'd like**

- Label workflows
- Filter workflows based on label
- Group workflows based on label
- Select a filter or a group to be the default view
- Delete archived workflows

**Comment by dylburger** [comment]
Related to #141 and #203.

**Comment by dylburger** [comment]
@rawkode you can now delete workflows. Check out the details in #141.

**Comment by rawkode** [comment]
Thanks @dylburger. I just deleted 21 workflows 😃

**Comment by dylburger** [comment]
We're now tracking each of these issues in separate tickets, so I'm closing this larger ticket
