### ISSUE TITLE
[ACTION] [Github] List / Get / Create / Update / Delete a gist

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#7987]
**Is there a specific app this action is for?**
Github

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28

**Actions**
- List gists for a user
- Get a gist
- Create a gist
- Update a gist
- Delete a gist

**Comment by MichaelNey** [comment]
This seems interesting. When you specify `List gists` is there a specific operation you are narrowing in on?

I personally assume `List gists for the authenticated user`, or `List gists for a user` would be the most relevant operations. But there is also `List public gists` for a more broad search.

What are your thoughts @LucBerge?

**Comment by LucBerge** [comment]
> This seems interesting. When you specify `List gists` is there a specific operation you are narrowing in on?
> 
> I personally assume `List gists for the authenticated user`, or `List gists for a user` would be the most relevant operations. But there is also `List public gists` for a more broad search.
> 
> What are your thoughts @LucBerge?

You are right, it is not clear. Mean [list gists for a user](https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28#list-gists-for-a-user)

**Comment by malexanderlim** [comment]
Hi @LucBerge , tracking development here:
https://github.com/PipedreamHQ/pipedream/issues/8623

**Comment by malexanderlim** [comment]
Hi @LucBerge , the work has been completed in https://github.com/PipedreamHQ/pipedream/issues/8623. Feedback would be appreciated once you have a chance to use the new components!
