### ISSUE TITLE
[Components] Personio

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#7999]
### App
Personio
https://www.personio.com/

Triggers:
1. Employee Created: Triggered when a new employee is added to Personio.
2. Position created

Actions:
1. Create Employee: Creates a new employee record in Personio.
https://developer.personio.de/reference/post_company-employees
2. Create application
https://developer.personio.de/reference/post_v1-recruiting-applications
3. List employees
https://developer.personio.de/reference/get_company-employees

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Personio-7999-92cdee9d905945d8bfd87b2e3d07fdb6

Hi @vunguyenhung, I actually tried creating a prop that sends a file from the /tmp folder, but the API always returns an error so I moved on
