### ISSUE TITLE
[FEATURE] Bucket workflows into folders

### ISSUE THREAD

**Issue by byrneml** [PipedreamHQ/pipedream#800]
**Is your feature request related to a problem? Please describe.**
Using Pipedream for a few different applications becomes confusing when you have a lot of workflows. 

**Describe the solution you'd like**
A folder structure for workflows so users can bucket them by the project that they're working on. Users can create folders and drag workflows into them.

**Comparable features in other tools?**
Not in other platforms, but when building out tools locally the obvious example is grouping functions by use case into folders.

**Comment by dylburger** [comment]
Thank you for the request @byrneml . We are tracking this at #203 . If you don’t mind, please follow that issue and we’ll post updates there as soon as we have them.

**Comment by byrneml** [comment]
Thanks! Will do
