### ISSUE TITLE
[OAUTH SCOPE] Jira

### ISSUE THREAD

**Issue by kang8** [PipedreamHQ/pipedream#8003]
**Which application needs a scope added?**

Jira

**What scope(s) need to be added?**

* manage:servicedesk-customer

**Please provide a link to the relevant API docs for scopes.**

https://developer.atlassian.com/cloud/jira/service-desk/scopes-for-oauth-2-3LO-and-forge-apps/#classic-scopes

**Context**

When I tried to add users to the organization, I got a 403 error

<img width="966" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/36906329/7737603c-b90f-4c26-87c5-44b701bce5f0">

**Comment by malexanderlim** [comment]
Hi @kang8 , I've created a separate application with the relevant `jira-service-management` scopes: https://pipedream.com/apps/jira-service-desk

Please let me know if this works for you and if you're interested in any components to be built for your use case.

**Comment by kang8** [comment]
Thanks!

**Comment by kang8** [comment]
Post-use experience:

During Test jira_service_desk, it hangs for a long time without response, I had to shut it down. @malexanderlim Is there a solution?

<img width="495" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/36906329/350fe8cd-cd8a-4fc8-84f2-2b0417ad446c">

**Comment by malexanderlim** [comment]
Hi @kang8 , I figured out what was happening here:
https://developer.atlassian.com/cloud/jira/service-desk/oauth-2-authorization-code-grants-3lo-for-apps/#3-2-construct-the-request-url

Given that our app goes through the 3-legged OAuth flow, you'd need an additional call to get the `cloudid` for your site first, then construct the request url similar to this:

https://api.atlassian.com/ex/jira/[YOUR CLOUD ID]/rest/servicedeskapi/organization

I'm in the process of scoping components to be built for the JIRA Service Desk application, are there triggers and actions that you might find useful? Would be happy to include some of these.
