### ISSUE TITLE
[Action] TextLocal

### ISSUE THREAD

**Issue by lloyd2580** [PipedreamHQ/pipedream#801]
Hello,

I want the same actions as mention below in the link, the only thing is i want TextLocal Instead of Twilio.

https://pipedream.com/@admin5/copy-of-send-an-sms-via-twilio-on-jotform-submission-p_KwC19ew/edit

**Comment by todsac** [comment]
Create Contact | Creates a new contact.
Send SMS | Sends a SMS message.

**Comment by dannyroosevelt** [comment]
closing in favor of https://github.com/PipedreamHQ/pipedream/issues/803
