### ISSUE TITLE
[BUG] Failed to connect Brex account

### ISSUE THREAD

**Issue by elifbeyzatok00** [PipedreamHQ/pipedream#8014]
I can't connect my brex account.  I took access denied error. Can you help me?
![image](https://github.com/PipedreamHQ/pipedream/assets/102792446/e9b4b8d9-9bad-44ae-a083-c17ca2334cdc)

**Comment by sergio-eliot-rodriguez** [comment]
that's all Leo! 
cool that you tagged me :-) 🙌
i think this actually falls in @malexanderlim 's plate))

fyi @elifbeyzatok00 someone at PD will have a look, and thanks for flagging
