### ISSUE TITLE
[Components] Jira Service Desk

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8017]
# jira_service_desk
## URLs
- https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/

### new-request-created
Create a source that triggers when a new customer request is created.
- https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/#servicedeskapi/request-getMyCustomerRequests
### request-updated
Create a source that triggers when a customer request is updated.
- https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/#servicedeskapi/request-getMyCustomerRequests

### create-request
Create an action that creates a customer request. A separate component method should be created to call the `axios` module, instead of calling it directly within the `run` method. This separate method should receive the `$` variable from the `run` method, in order to pass it as the first parameter to `axios`. When calling a component method with multiple parameters, you should pass them as a single object, using the Javascript spread syntax and destructuring when able. Do not use `return await` when returning a call to the `axios` module, instead simply return it without the `await` keyword.
- https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/#servicedeskapi/request-createCustomerRequest
### comment-on-request
Create an action that creates comment on a customer request. A separate component method should be created to call the `axios` module, instead of calling it directly within the `run` method. This separate method should receive the `$` variable from the `run` method, in order to pass it as the first parameter to `axios`. When calling a component method with multiple parameters, you should pass them as a single object, using the Javascript spread syntax and destructuring when able. Do not use `return await` when returning a call to the `axios` module, instead simply return it without the `await` keyword.
- https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/#servicedeskapi/request/{issueIdOrKey}/comment-createRequestComment

**Comment by GTFalcao** [comment]
@vunguyenhung I've adjusted the docs link to better direct users to each custom field's schema, but the request still fails (but with a different error) when I use an array for "who is your manager" instead of a string as you did in your test, since it is documented as an array.

I will try contacting their support as I cannot find any other documentation on this field's exact schema.
