### ISSUE TITLE
[Components] Hyros

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8020]
### App
Hyros
http://hyros.com/

Triggers:
1. Call attributed to a lead
https://hyroswebhooks.docs.apiary.io/#reference/0/webhooks/call.attributed
2. Sale attributed to a lead 
https://hyroswebhooks.docs.apiary.io/#reference/0/webhooks/sale.attributed

Actions:
1. Create lead
https://hyros.docs.apiary.io/#reference/0/leads/create-lead
2. Create call
https://hyros.docs.apiary.io/#reference/0/calls/create

**Comment by luancazarine** [comment]
@malexanderlim, It's necessary to schedule a call to create an account and there's no user/pass in 1password.
What do I do in this case?

**Comment by malexanderlim** [comment]
I've added this in so this should be unblocked. Thanks for flagging Luan!
