### ISSUE TITLE
[Components] Onepage

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8031]
# onepagecrm
## URLs
- https://developer.onepagecrm.com/api/
#### Prompt
Triggered when a new contact is added in Onepage CRM. Please create sorting by created_at field and ordering desc.
#### URLs
- https://developer.onepagecrm.com/api/#/Contacts/get_contacts
#### Prompt
Triggered when a deal is successfully closed in the CRM. Please create sorting by created_at field and ordering desc and status is closed.
#### URLs
- https://developer.onepagecrm.com/api/#/Deals/get_deals
#### Prompt
Creates a new contact in the Onepage CRM. Please add all required and optional props.
#### URLs
- https://developer.onepagecrm.com/api/#/Companies/get_companies
- https://developer.onepagecrm.com/api/#/Statuses/get_statuses
- https://developer.onepagecrm.com/api/#/Users/get_users
- https://developer.onepagecrm.com/api/#/Lead%20Sources/get_lead_sources
- https://developer.onepagecrm.com/api/#/Contacts/post_contacts
#### Prompt
Removes an existing contact from the system. Please add an async contact id prop.
#### URLs
- https://developer.onepagecrm.com/api/#/Contacts/get_contacts
- https://developer.onepagecrm.com/api/#/Contacts/delete_contacts__contact_id_
#### Prompt
Updates an existing deal's details in the CRM. Please add all required and optional props.
#### URLs
- https://developer.onepagecrm.com/api/#/Deals/get_deals
- https://developer.onepagecrm.com/api/#/Contacts/get_contacts
- https://developer.onepagecrm.com/api/#/Users/get_users
- https://developer.onepagecrm.com/api/#/Pipelines/get_pipelines
- https://developer.onepagecrm.com/api/#/Deals/put_deals__deal_id_

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Onepage-6cf751b2a8bd4486a178598108e5c236

Hi @vunguyenhung, I don't know why you're not getting the events. In my tests it is working as expected.
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/50200d67-5e1d-4a79-88f9-fdb84ddb35a9)
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/9a0b48d1-2171-4704-aae7-0869aad17764)
