### ISSUE TITLE
[FEATURE] delimited file import into a SQL DW table

### ISSUE THREAD

**Issue by ericsampson** [PipedreamHQ/pipedream#805]
I’d love the ability to import delimited (CSV/TSV/PSV/etc) files into the data warehouse as 'reference data' tables to join against.

I picture it looking like:
1) select delimited file in a file chooser, and pick a destination table name.
2) if that name already exists, offer the choice of a) replacing all content, or b) merging with the existing content

I would imagine having limits on the total number of cells (rowXcolumn) for the various plans. For a free plan, being able to store up to some reasonable multiple of 100,000 cells seems ideal.

As a later enhancement, the feature could be expanded to allow the import of newline-delimited JSON objects, and linking (or pulling in) data from Google Sheets etc.

**Comment by dylburger** [comment]
The SQL Service will be shutting down on Feb 10th, 2022 (you can read more details in [this post](https://pipedream.com/blog/shutting-down-the-sql-service/)). As a result, we're closing this issue.

Let us know if you have any questions at all.
