### ISSUE TITLE
[Components] twocaptcha

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8055]
# _twocaptcha
## URLs
- https://2captcha.com/2captcha-api
#### Prompt
Trigger when a captcha has been successfully solved by the 2captcha service. Send event whether the status is "ready". Required props are clientKey.
#### URLs
- https://2captcha.com/api-docs/get-task-result
#### Prompt
Activates when the user's balance in 2captcha API is changed. No prop is required.
#### URLs
- https://2captcha.com/api-docs/get-balance
#### Prompt
Send a new captcha to the 2captcha service for solving. Required props are clientKey and task object.
#### URLs
- https://2captcha.com/api-docs/create-task
#### Prompt
Fetch the solution of a previously submitted captcha from the 2captcha service. Required props are clientKey and taskId.
#### URLs
- https://2captcha.com/api-docs/get-task-result
#### Prompt
Get current account balance from the 2captcha API. Required props are clientKey.
#### URLs
- https://2captcha.com/api-docs/get-balance

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-twocaptcha-68b1567a62204c17b4161491da9ace84

Hi @vunguyenhung, About the source Captcha Solved, it's not possible to make taskId optional, because there's no way to list tasks nor get resolution without taskId

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-twocaptcha-68b1567a62204c17b4161491da9ace84

It looks like you didn't update the action. please get the lastest version and test it again.
