### ISSUE TITLE
[FEATURE] ClickUp Update Task should include due_date and start_date

### ISSUE THREAD

**Issue by bsommardahl** [PipedreamHQ/pipedream#8065]
**Name of app / service**
ClickUp

**Link to developer documentation**
https://clickup.com/api/clickupreference/operation/UpdateTask/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, I need to update the due date and can't with the current component.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
