### ISSUE TITLE
[Components] Interzoid

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8067]
### App
Interzoid
https://www.interzoid.com/

Actions:
1. Get Full Name Match Score - Retrieve a match score (likelihood of matching) between two individual names on a scale of 0-100.
2. Get Organization Match Score - Retrieve a match score (likelihood of matching) from 0-100 between two organization names.
3. Generate Match Report - Generate a Match Report using a dataset table or file (CSV/TSV/Excel).

**Comment by michelle0927** [comment]
Hi, @vunguyenhung. For "Generate Match Report", there's a small difference between the prop values in your code step vs. the component props. In the component, Matching Algorithm Type (or category) is set to "individual", but in the code step it's set to "company". When I test the component with the Matching Algorithm type set to "company", it does return the expected 27 MatchClusters.
