### ISSUE TITLE
[Action] Basecamp create card

### ISSUE THREAD

**Issue by sorvis** [PipedreamHQ/pipedream#8077]
**Is there a specific app this action is for?**
Basecamp

**Please provide a link to the relevant API docs for the specific service / operation.**
https://github.com/basecamp/bc3-api/blob/master/sections/card_table_cards.md#create-a-card

**Comment by shashankshet** [comment]
Hi @sorvis 
could you please provide more context on this issue as to what is to be developed?

**Comment by malexanderlim** [comment]
Hi @sorvis , we're tracking development here:
https://github.com/PipedreamHQ/pipedream/issues/8696

Please follow subscribe to the new ticket for updates.
