### ISSUE TITLE
[BUG] Deploy resets view settings on individual steps

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#809]
**Describe the bug**
I've got a workflow with multiple Node.js steps. One is a very basic step that sets a constant. It's big so I minimize it. Every time I deploy my workflow it re-expands and I have to (well want to) collapse it every time.

**To Reproduce**
1. Collapse a step.
2. Work on something else and then deploy
3. The initially collapsed step is expanded

**Expected behavior**
It should stay collapsed.

**Comment by dylburger** [comment]
@cfjedimaster I know you have a few outstanding requests re: this UX. Since this is technically tied to the old builder, I'm closing in favor of #2295 and #2294.
