### ISSUE TITLE
[Components] Ringover

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8090]
### App
Ringover
https://www.ringover.com/

Actions:
1. Send SMS
https://developer.ringover.com/?_ga=2.63646317.316145444.1695076986-652152469.1694643800#tag/sms/paths/~1push~1sms/post

2. Create contact
https://developer.ringover.com/?_ga=2.63646317.316145444.1695076986-652152469.1694643800#tag/contacts/paths/~1contacts/post

**Comment by GTFalcao** [comment]
I've opened a PR with only "Create Contact" for now, as "Send SMS" is pending response from Ringover's support regarding validating the component.

**Comment by GTFalcao** [comment]
@vunguyenhung I set the exact same permissions for the API Key as you showed, and am able to create the contact normally - tried multiple times with different prop setups, also.

Have you tried selecting a different region in the account setup? Mine is set to EU

**Comment by GTFalcao** [comment]
![image](https://github.com/PipedreamHQ/pipedream/assets/48412907/8c88b4e4-b0c0-4fca-a30c-b3968c28d914)
