### ISSUE TITLE
Linkedin

### ISSUE THREAD

**Issue by hgillh** [PipedreamHQ/pipedream#8092]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
In case anyone needed, LinkedIn app integration at Pipedrem https://pipedream.com/apps/linkedin
