### ISSUE TITLE
[BUG] Notion - Get Page returns `null` value for Formula 2.0 property 

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#8094]
**Describe the bug**
Notion - Get Page returns `null` value for Formula 2.0 property

**To Reproduce**
1. On Notion, create a new Notion database, and a property with type Formula. Then create a new page and set the formula `prop("Created By").name().upper()`
<img width="1840" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/b6fc5ea8-46e4-4401-8e12-37bddae2a03a">

2. On Pipedream, add a new Notion - Retrieve Page action, select the created page and observe the error
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/51bc7340-cf1a-4a83-8a74-c2c38b1d9c34)

**Expected behavior**
The action should return the result of the formula instead of null value

**Additional context**
First reported by a customer here: https://pipedream.com/community/t/notion-formula-2-0-updates-is-broken-fetching-data/8379/8

**Comment by alysonturing** [comment]
I believe that it was already addressed, can you please check again @vunguyenhung?

<img width="796" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/103650302/fb2c5b13-f893-46d8-aacb-a188632b36bd">
<img width="317" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/103650302/d7255bfa-dc5e-49b4-8073-ab2f4d5abd89">
