### ISSUE TITLE
[FEATURE] If an action has been updated since I added it to my workflow, I'd like an option to upgrade to the newest version

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#81]

**Comment by loicginoux** [comment]
this feature would be great ! I share here my use case if it can help:

> I created an action to avoid repeating some code. I kept it private, and used it like 10 times . Now that I configured these 10 steps, I realised I need to make some changes to the action. Is there a quick way to apply code changes to the 10 steps that use this action ? At the moment can only delete, recreate and reconfigure the step to use the new code 10 times, it’s kind of frustrating If I need to do that for every change/adjustment of the action I need to make.

**Comment by dylburger** [comment]
This is now possible with the newest version of actions:

<img width="280" alt="Screen Shot 2021-02-17 at 10 49 10 AM (1)" src="https://user-images.githubusercontent.com/242668/118761292-04491380-b829-11eb-97df-6535c355e245.png">

[See the docs here](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and let us know if you have any additional feedback!
