### ISSUE TITLE
[Components] TeamGantt

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8103]
### App
TeamGantt
https://www.teamgantt.com/

**Triggers:**
https://api.teamgantt.com/
1. Task Updated
2. New Comment Added

**Actions:**
https://api.teamgantt.com/
1. Create Task: Creates a new task within a specific project.
2. Update Task

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-TeamGantt-8103-72784fd1e14b4865a1d6c8c0ee40bfa5

Hi @vunguyenhung, In TeamGantt you can comment on tasks, projects or groups, so when you select the project or group as target, you will receive a notification when a project or group receives a comment, not a task
