### ISSUE TITLE
[BUG] Python package fitz conflicting with PyMuPDF

### ISSUE THREAD

**Issue by itscameronlee** [PipedreamHQ/pipedream#8112]
**Describe the bug**
Pipedream stumbles when installing [PyMuPDF](https://pymupdf.readthedocs.io/en/latest/installation.html) in Python. To use this package, you first install `PyMuPDF`

```
pip install pymupdf
```

Then you import `fitz`

```
import fitz
```

There is another package called `fitz` that conflicts with `PyMuPDF`, and it seems the magic importer is getting confused.

**To Reproduce**
Add this to the top of your Python code:
```
# pipedream add-package PyMuPDF
import fitz
```

**Expected behavior**
Pipedream would install `PyMuPDF` and not install the conflicting package `fitz`.

**What happens instead**
I get this error in Pipedream: `ModuleNotFoundError - No module named 'frontend'`

Looking at [this question on StackOverflow](https://stackoverflow.com/questions/56467667/how-do-i-resolve-no-module-named-frontend-error-message) makes me  feel pretty confident that the bug I'm seeing is related to conflicting packages.

**Additional context**
@dylburger made it pretty clear what the issue is in [this comment to a similar problem](https://github.com/PipedreamHQ/pipedream/issues/4183#issuecomment-1334119588). He also requested we create a new issue here if we have the same problem.

**Comment by dylburger** [comment]
@itscameronlee thanks for reporting, this is on my backlog and I'll take a look ASAP.

**Comment by andrewjschuang** [comment]
@itscameronlee you should be able to use the package from now on!
```
# pipedream add-package pymupdf
import fitz
```
