### ISSUE TITLE
[APP] Qntrl

### ISSUE THREAD

**Issue by TeamsAcademy** [PipedreamHQ/pipedream#8120]
**Name of app / service**
Qntrl

**Link to developer documentation**
https://core.qntrl.com/apidoc.html?type=reference&module=org

**Is lack of support preventing you from building workflows, or do you have a workaround?**
have workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Add, Modify, and delete new jobs, transitions, comments ... etc

**Comment by sergio-eliot-rodriguez** [comment]
Hi @TeamsAcademy 

Thanks for the request. Happy to announce that Qntrl has now been released a basic integration https://pipedream.com/apps/qntrl?via=go

Feel free to let us know if you see any issues, for component development make sure to track #10867
