### ISSUE TITLE
[APP] Clerk

### ISSUE THREAD

**Issue by MichaelNey** [PipedreamHQ/pipedream#8122]
**Name of app / service**

[Clerk Auth](https://clerk.com/)

**Link to developer documentation**

https://clerk.com/docs/reference/backend-api
https://clerk.com/docs/integrations/webhooks

**Is lack of support preventing you from building workflows, or do you have a workaround?**

There are a lot of triggers/actions that can belong in a Clerk Auth integration that I think would provide great value to those using Pipedream who have a use case. For developers, they can workaround this not being supported of course.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Get User** - https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUser
**Create User** - https://clerk.com/docs/reference/backend-api/tag/Users#operation/CreateUser
**Update User** - https://clerk.com/docs/reference/backend-api/tag/Users#operation/UpdateUser
**Delete User** - https://clerk.com/docs/reference/backend-api/tag/Users#operation/DeleteUser
**Get User Organization Memberships** - https://clerk.com/docs/reference/backend-api/tag/Users#operation/UsersGetOrganizationMemberships
**Create User Invitation** - https://clerk.com/docs/reference/backend-api/tag/Invitations#operation/CreateInvitation

There are many others that would provide great value like sending emails to users, sending texts to users, etc that they have great documentation for. I would love to contribute and work on some of these as well if no one else picks them up.

**Comment by malexanderlim** [comment]
Hi @MichaelNey , thanks for the detail here. We have the base integration in place, and component development for the ones requested are underway - feel free to follow along here: https://github.com/PipedreamHQ/pipedream/issues/8166

**Comment by MichaelNey** [comment]
Thank you so much!
