### ISSUE TITLE
[APP] HelloSign

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#815]
**Name of app / service**
HelloSign

**Link to developer documentation**
https://app.hellosign.com/api/documentation

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Blocking issue #630 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Triggers are listed in issue #630

**Comment by todsac** [comment]
HelloSign app has been integrated.  

Here is an example workflow - https://pipedream.com/@tod/hellosign-api-integration-example-p_WxCQe1N/
Here is HelloSign in the marketplace - https://pipedream.com/apps/hellosign
