### ISSUE TITLE
[BUG] Source not connected to any workflow on UI after creation

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#8153]
**Describe the bug**
When I create a new workflow with a new trigger, when I go the "Sources" tab in the left menu, the source is visible but it is not attached to any workflow.

**To Reproduce**
1. Create a new workflow
2. Create a new trigger (eg: Airtable > New record)
3. Fill all the informations and wait for the source to be created
4. Go to "Sources" on the left menu
5. Expand the source >

**Expected behavior**
The newly created workflow must be visible.

**Current behavior**
The newly created workflow is not visible.

**Screenshots**
![](https://www.pixenli.com/image/Rem6WBAB)

**Desktop:**
 - Browser firefox 117.0.1 (64 bits)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by LucBerge** [comment]
@dylburger Working fine now, thanks
