### ISSUE TITLE
[APP] Hayat eve sığar

### ISSUE THREAD

**Issue by smltrl** [PipedreamHQ/pipedream#816]
https://play.google.com/store/apps/details?id=tr.gov.saglik.hayatevesigar&hl=tr&gl=US

**Comment by dylburger** [comment]
@smltrl does this app have a public API? If so, could you link us to the API docs?

**Comment by dylburger** [comment]
Closing without more information. Feel free to re-open if the app has a public API, and if you can provide the docs to that API. Happy to help.
