### ISSUE TITLE
[Components] Brevo

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8164]
### App
Brevo
https://www.brevo.com/

After reviewing Brevo's website, it appears that they do not publicly list the specific capabilities of their API. Therefore, I can only provide generalized suggestions for triggers and actions that would be useful based on standard functions of project management and collaboration tools.

Triggers:
1. Task Completion: Triggered when a specific task within a project has been finished.
2. New Project Creation: Triggered when a new project is created within the system.

Actions:
1. Create Task: Creates a new task within a specific project.
2. Update Task Status: Changes the progress status of a specific task.
3. Send Message: Sends a message to a specific group or individual in the system.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
This is a dupe of SendInBlue, so we will not create additional components for them as Brevo = SendInBlue.
