### ISSUE TITLE
[Components] Campaign Cleaner

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8177]
### App
Campaign Cleaner
https://campaigncleaner.com/

**Actions:**
1. Send campaign for analysis
https://api-docs.campaigncleaner.com/#540a9e44-bd17-4bb4-ac8f-150ecbc8066a
2. Get campaign status
https://api-docs.campaigncleaner.com/#6f4578f7-60f9-4fb6-9b61-08b176f66d82
- List campaigns https://api-docs.campaigncleaner.com/#b819636d-48c0-4027-b962-814559a5364e

**Comment by luancazarine** [comment]
Hello everyone. When developing this component, I couldn't test it because I didn't have credits and the Campaign Cleaner UI wasn't working, so I couldn't see its real effects.
At least the API requests are responding an error about credits, which means the structure of the data sent is correct
