### ISSUE TITLE
[FEATURE] Add immutable UUID to 'Actions' to improve usability and organization

### ISSUE THREAD

**Issue by mattgauf** [PipedreamHQ/pipedream#82]
**Is your feature request related to a problem? Please describe.**
I am frustrated by how cluttered and unorganized 'my actions' become after creating just a few revisions of an action, either public or private. 

On the list of personal actions: 
- Each save (private) or publish (public) creates a new item on the list. 
- A checkbox can hide old versions, but does nothing to help when searching for a specific version.
- Only sorting by updated date provides an indication of version sequencing for private versions
- Private versions can only be referenced by order between published versions. Even the updated date is not visible.
- Only the version number for published versions provides specificity.

When viewing your own actions:
- User interface for navigating between versions is inconsistent between public and private versions.
- Older private versions only get 'click to edit latest'. 
- All public versions get a listing of _only the published revisions_ even if there was a private revision in between.

**Describe the solution you'd like**
I would like an immutable UUID (like what is defined in RFC 4122) to be assigned to every Action when it's created; which would then remain constant in all derivatively created Actions. If it were a column on pipedream.com/actions it would at least provide a reference for organization.

... Even better would be a UUID that became a namespace for an incrementing counter or epoch time (independent of the version number used for publishing). For example: (A new Action, followed by an update)

`7c504782-ecc0-43eb-af43-404efa68dc90:1587930060`
`7c504782-ecc0-43eb-af43-404efa68dc90:1587930109`

**Do you have a workaround?**
No workaround that I can find, I stopped using the Actions feature until recently when I contacted support to just delete all the Actions from my account so I could start over and be more intentional when saving or publishing.

**Comparable features in other tools?**
Yes but in different ways, for example Google Docs tracks revisions of a document; but they don't appear as separate documents. And no matter which version you're using the document has the same unique id it had upon creation. 

Obviously, that solution wouldn't work for pipedream; since updating an action doesn't update which revision is used in a workflow. Thus my request is specific to pipedream and shouldn't limit it's current functionality, security, or goals... only add some needed organization. 

**Additional context**
None.

**Comment by dylburger** [comment]
@mattgauf we've changed the UX for actions, and it should address this issue. Each action is displayed on a row, instead of showing each (action, version) on its own row. Clicking into the action shows all of that action's versions:

<img width="713" alt="Screen Shot 2021-01-27 at 12 02 40 PM" src="https://user-images.githubusercontent.com/242668/106047442-7b9b4180-6098-11eb-9884-d3f2a6b712f6.png">

An action's unique ID can be found in the URL of the action's page, e.g.

```
https://pipedream.com/actions/a_abc123/edit
```
