### ISSUE TITLE
Google Ads API [ACTION]

### ISSUE THREAD

**Issue by janom4** [PipedreamHQ/pipedream#821]
Google Ads API: https://developers.google.com/google-ads/api/docs/start

Useful integration:
- Reporting (syncing google ads spend data to internal data warehouse)

**Comment by sergio-eliot-rodriguez** [comment]
Is the app integration for Google Ads completed @malexanderlim ? has internal status of "hidden"

just checking if we can close this one and just track #6969 for components.

**Comment by malexanderlim** [comment]
Google Ads is now live! Please have a look at the available [triggers](https://pipedream.com/apps/google-ads#popular-google-ads-triggers) and [actions](https://pipedream.com/apps/google-ads#popular-google-ads-actions).
