### ISSUE TITLE
[Components] Playwright

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8210]
### App
Playwright
https://playwright.dev/

Please use the new playwright app. There's a new app file with a corresponding launch() method to launch a new browser with the Pipedream compatible Playwright instance.

**Actions:**
1. Get Page Title
Please include the following props:
- url - the URL that the screenshot should be taken of
https://playwright.dev/docs/api/class-page#page-title

2. Take Screenshot 
Please include the following props:
- url - the URL that the screenshot should be taken of
- download_to_tmp_path - an option to download to tmp with a specific filename
...all playwright screenshot() options as props: https://pptr.dev/api/puppeteer.screenshotoptions
https://playwright.dev/docs/screenshots

3. Get HTML
- url - the URL of the page to scrape
https://playwright.dev/docs/api/class-page#page-content

4. Get PDF
Please include the following props:
- url - the URL that the screenshot should be taken of
- download_to_tmp_path - an option to download to tmp with a specific filename
...all playwright pdf() options as props: https://pptr.dev/api/puppeteer.pdfoptions
https://playwright.dev/docs/api/class-page#page-pdf

**Comment by ctrlaltdylan** [comment]
On hold until we have Playwright support integrated.
