### ISSUE TITLE
[Components] Puppeteer

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8211]
### App
Puppeteer
https://pptr.dev/

Triggers:
1. Page Loaded: Triggered when Puppeteer successfully loads a new webpage.
2. Element Interacted: Triggered when there's interaction with a specified element on the page, using Puppeteer's interaction methods.

Actions:
1. Generate PDF: Creates a PDF of the loaded webpage.
2. Capture Screenshot: Takes a screenshot of the current viewport.
3. Navigate to URL: Directs Puppeteer to navigate to a specific URL.

_This list of suggested components was generated using ChatGPT_

**Comment by ctrlaltdylan** [comment]
The `puppeteer.app.ts` file is populated with the basic scaffolding needed to continue development and the app is published.

Already started individual issues:

* https://github.com/PipedreamHQ/pipedream/issues/8216
* https://github.com/PipedreamHQ/pipedream/issues/8219
* https://github.com/PipedreamHQ/pipedream/issues/8217
* https://github.com/PipedreamHQ/pipedream/issues/8218
