### ISSUE TITLE
[ACTION] Google Slides - Merge data into a Presentation

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#8215]
**Is there a specific app this action is for?**
Google Slides

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.google.com/slides/api/guides/merge

**Comment by govind-kumarr** [comment]
@vunguyenhung  I want to work on this can you assign this to me ?

**Comment by YS-Ch** [comment]
@vunguyenhung can you assign this to @govind-kumarr?

**Comment by YS-Ch** [comment]
@govind-kumarr Is it possible to do this in 2 weeks tops?  My project has a time deadline.
