### ISSUE TITLE
[Components] Diffchecker

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8233]
# diffchecker
## URLs
- https://www.diffchecker.com/public-api/
#### Prompt
Compares two pieces of text and returns the result.
#### Prompt
Compares two pdfs and returns the result.
#### Prompt
Compares two images and returns the result.

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Diffchecker-f6790de5fa7948158dc822c9ed050f39

Hi @vunguyenhung, you faced this error because you used URI with newlines, but ok, I added a check to remove it.
Regarding your suggestion for the action to accept images from the tmp dir, it has already been accepted. you just need to change the Input Type prop to "multipart/form-data"
