### ISSUE TITLE
[ACTION/ENHANCEMENT] Add "Parent Database" Field to Notion → Update Page Action

### ISSUE THREAD

**Issue by TomFrankly** [PipedreamHQ/pipedream#8239]
Hey all!

The Notion → Update Page action has a major downside right now – you can't pass a dynamic reference for the Page ID and get the Properties for that database.

https://github.com/PipedreamHQ/pipedream/blob/master/components/notion/actions/update-page/update-page.mjs

This is due to the fact that additionalProps() can't evaluate a dynamic reference.

I have a simple workaround idea that would pretty much fix this with little effort: Simply add another field for Parent Database, then a property called "Fetch Properties From..." with choices:

* Page ID
* Parent Database

Most users who will be using this action for pages in databases are going to be building entire workflows that only deal with one database.

So with this fix, they'd be able to simply set that database in this action, allowing them to choose the properties they want to update for the passed Page ID.

**Comment by andrewjschuang** [comment]
This is genius, @TomFrankly! Thanks for the suggestion!

**Comment by ValerieMoxie** [comment]
I'm so relieved to see this. I have been struggling with this issue for the past 6 weeks. When should we expect to see the bug fix being pushed?

Thank you @TomFrankly 

> Hi everyone, all test cases are passed! Ready for release!
> 
> Test report https://vunguyenhung.notion.site/ACTION-ENHANCEMENT-Add-Parent-Database-Field-to-Notion-Update-Page-Action-8239-4318df5c451844fdac1e338e0db2bee1

**Comment by TomFrankly** [comment]
@andrewjschuang just tested this, but it seemed to use the parent database of the Page ID I passed, rather than the explicit Parent Database property I set.

In most cases, this is likely fine – users will most-often be selecting the correct database. However, it can lead to a confusing situation if a user accidentally choosed a different Parent Databse.

In that case, they'd get a list of the properties for that database, but then the script will attempt to update those properties in the database that is the parent of the Page ID passed. In most cases, those properties probably wouldn't match up.

Perhaps the action should first pull the info abou the Page ID passed, then match its parent ID with the one from the Parent DB property, throwing an error if they don't match?

![CleanShot 2023-10-12 at 09 27 27@2x](https://github.com/PipedreamHQ/pipedream/assets/684961/bab3625b-021f-48f1-abbe-905aa2560841)

**Comment by andrewjschuang** [comment]
@TomFrankly the action [pulls the additional props from the Parent Database ID prop](https://github.com/PipedreamHQ/pipedream/blob/master/components/notion/actions/update-page/update-page.mjs#L56), it doesn't use the Page ID. What you're seeing there is the [returned object for the updated page](https://github.com/PipedreamHQ/pipedream/blob/master/components/notion/actions/update-page/update-page.mjs#L81-L85) from Notion API. The Parent Database might be another one, but it's important that they have the same properties. If the selected Parent Database ID has different properties than the Page ID, I believe Notion API blocks the request and returns HTTP 400
