### ISSUE TITLE
Proxycurl

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8240]
### App
Proxycurl
https://nubela.co/proxycurl/docs

**Comment by C-Nubela** [comment]
Hey! This is us :) Feel free to reach out to "[hello@nubela.co](mailto:hello@nubela.co)" if you need to ask us any questions.

**Comment by sergio-eliot-rodriguez** [comment]
Hey! @C-Nubela 

Thanks for reaching out!

We have created an app integration for Proxycurl at Pipedream -- kindly have a look https://pipedream.com/apps/proxycurl
and let us know any issues and/or feedback.

**Comment by sergio-eliot-rodriguez** [comment]
Tracking components development at #8244
