### ISSUE TITLE
[Components] Proxycurl

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8244]
### App
Proxycurl
https://nubela.co/proxycurl/

**Actions:**
1. Retrieve Company Metadata from LinkedIn Company Profile: Fetch available company data from a specified LinkedIn company page.
https://nubela.co/proxycurl/docs#company-api-company-profile-endpoint

2. Find Social Media Profiles from Email
https://nubela.co/proxycurl/docs#contact-api-reverse-email-lookup-endpoint

3. Look Up Email from LinkedIn Profile:
https://nubela.co/proxycurl/docs#contact-api-work-email-lookup-endpoint

**Comment by vellames** [comment]
It wasn't possible to test everything because we don't have enough credits in the account.

**Comment by C-Nubela** [comment]
Love that you tested it by looking up Pipedream haha. Thanks for adding us guys.
