### ISSUE TITLE
Garmin Connect

### ISSUE THREAD

**Issue by BruceH3** [PipedreamHQ/pipedream#8254]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for the request @BruceH3 

We are tracking Garminc Connect here: https://github.com/PipedreamHQ/pipedream/issues/6937

Freel free to follow up there.

**Comment by malexanderlim** [comment]
Hi @BruceH3 , I haven't heard back yet from the Garmin team as to the status of Pipedream's application for API access, but it could be helpful to reach out to their team as their customer to request the integration as that has proven to expedite the process in the past.
