### ISSUE TITLE
[APP] Groove

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#827]
https://www.groovehq.com/docs

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
14 days follow up

**Comment by sergio-eliot-rodriguez** [comment]
This has been submitted

**Comment by sergio-eliot-rodriguez** [comment]
Integrated https://pipedream.com/apps/groovehq
