### ISSUE TITLE
[ACTION]

### ISSUE THREAD

**Issue by Lipdoctor** [PipedreamHQ/pipedream#8282]
**Is there a specific app this action is for?**
OpenAI Chat end point

**Please provide a link to the relevant API docs for the specific service / operation.**

Similar to Zapier, create an action that is designed to extract specific values out of the unstructured text. Zapier offers an option to specify field names, instructions for each, field type and so on. This makes it easy to use OpenAI to extract data in (mostly) reliable way w/out being a master at writing prompts.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
