### ISSUE TITLE
[Components] DocsBot AI

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8291]
### App
DocsBot AI
https://docsbot.ai/

Triggers:

1. Document Uploaded: This function gets triggered when a new document is uploaded in DocsBot.
2. Key Term Identified: Triggered when the software detects and identifies a key term in a document.

Actions:

1. Analyze Document: This function initiates the process for analyzing a document.
2. Extract Information: This function extracts specific information from the document according to the provided parameters.
3. Generate Summary: This function generates a concise summary of the document based on key information and context.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
Closing as we are using ai-component-codegen for this app.
