### ISSUE TITLE
[Components] AiVOOV

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8293]
### App
AiVOOV
https://aivoov.com/

Triggers:

1. "New User Registered": Triggered when a new user signs up on AiVOOV.
2. "New Voice Model Created": Triggered when a user creates a new voice model.

Actions:

1. "Create Voice Model": Creates a new voice model using AiVOOV’s Restful API.
2. "Update Voice Model": Updates an existing voice model in AiVOOV.
3. "Delete Voice Model": Deletes an existing voice model from AiVOOV.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
Closing as we are using ai-component-codegen for this app.
