### ISSUE TITLE
[APP] SIMVOLY

### ISSUE THREAD

**Issue by rodenp** [PipedreamHQ/pipedream#83]
**Is your feature request related to a problem? Please describe.**
Like the existing supported APPs, I would like to be able to retrieve data from SIMVOLY.

**Describe the solution you'd like**
Ability to connect to SIMVOLY and access their exposed services

**Do you have a workaround?**
SimVoly has a simple authentication model

**Comparable features in other tools?**
Simvoly uses a simple API bearer token

**Additional context**
Here is a link to the SimVoly API documentation
https://websitebuilder.docs.apiary.io/#reference/authentication

**Comment by todsac** [comment]
@rodenp - I have integrated Simvoly, are you open to testing the integration?

**Comment by rodenp** [comment]
Hi Ben,

You guys are so awesome.
Unfortunately i am no longer a client of simvoly and my account is no longer active.
I have moved across to groovefunnels.
Not sure if you guys have heard of that.

Thank you so much for ll your efforts

Peter


________________________________

**Comment by sergio-eliot-rodriguez** [comment]
Just in case stumbles on here https://pipedream.com/apps/simvoly
