### ISSUE TITLE
[FEATURE] Upgrade Action to Latest Version

### ISSUE THREAD

**Issue by rawkode** [PipedreamHQ/pipedream#830]
We've discussed this on the Slack, but I couldn't find an issue tracking this. Please close if I've missed it.

**Is your feature request related to a problem? Please describe.**

As I extract more of my steps to reusable actions, it's becoming more important that I can make modifications to the action and update to the latest version in the steps within my workflows.

**Describe the solution you'd like**

When I use an action within a workflow, I should be able to "track" the action changes; either manually or automatically.

**Do you have a workaround?**

Making changes to each step and the global action individually

**Comment by dylburger** [comment]
Tracking in #81 .

**Comment by rawkode** [comment]
Thank you, @dylburger
