### ISSUE TITLE
[FEATURE] Display `Update` button on an action when a new version is merged/released

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#8312]
**Is your feature request related to a problem? Please describe.**
I have a workflow using a public component action. When there is a new feature I want to add or a bug to fix, I fork, code and PR. When the PR is merged, I would like to be able to update my components by the click of button (like for private components)

**Describe the solution you'd like**
A red button to update the component with the latest version (like for private components)

**Do you have a workaround?**
A button in the `...` menu

**Comparable features in other tools?**
Idk

**Comment by dannyroosevelt** [comment]
@LucBerge if this isn't working, that's a bug. Did you publish an updated version of the action? Is this from the CLI or the builder?

**Comment by LucBerge** [comment]
@dannyroosevelt More details:

When I have a private component used in a workflow:
- I publish a new version of the component with `pd publish`
- The red button `update component` is visible on step

When I have a public component used in a workflow:
- I update the component source code and PR
- The PR is merged
- The red button is not visible on the step

**Comment by andrewjschuang** [comment]
@LucBerge it takes some time from PR merge to publishing the component to the public registry. Would you mind looking again to see if the Update button is showing now?

**Comment by andrewjschuang** [comment]
A few minutes, can you please try refreshing the page?

**Comment by LucBerge** [comment]
[This PR](https://github.com/PipedreamHQ/pipedream/pull/8281) has been merge yesterday and it not showing since

**Comment by andrewjschuang** [comment]
Can you go to you workflow/project settings and share with support?
And then copy and paste the workflow URL here.

**Comment by andrewjschuang** [comment]
@LucBerge can you go to you workflow/project settings and share with support?
And then copy and paste the workflow URL here.

**Comment by LucBerge** [comment]
@andrewjschuang done.
[Checkout this workflow step 20](https://pipedream.com/@sarl-les-quatre-berges/projects/proj_rKs0V3/creation-contrat-et-etat-des-lieux-p_rvCpwg9/inspect).

Current version 0.0.6
[Latest released version 0.0.7](https://github.com/PipedreamHQ/pipedream/blob/e33b4edcc59d08cb21f4bc78493a5bcaee435d0e/components/microsoft_outlook/actions/create-draft-email/create-draft-email.mjs#L6)
The `Update` button is not displayed

**Comment by dannyroosevelt** [comment]
@LucBerge FYI it seems like this might be a bug, we're investigating.

**Comment by LucBerge** [comment]
> @LucBerge FYI it seems like this might be a bug, we're investigating.

Ok. Can I disable support access ?

**Comment by dannyroosevelt** [comment]
Yes and this should be fixed!

**Comment by LucBerge** [comment]
I confirm it is now working, good job.
