### ISSUE TITLE
[Components] aivoov

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#8318]
# aivoov
## URLs
- https://github.com/AiVOOV/aivoov-api

#### Prompt

This action will convert text to audio using the transcribe endpoint. Please include voice_id, transcribe_text, engine, transcribe_ssml_style, transcribe_ssml_spk_rate, transcribe_ssml_volume, and transcribe_ssml_pitch_rate as props and include their descriptions.

For voice_id, please have a dynamic prop for each provider: google, azure, ibm, aws. 

The end-user should be able to select a provider, and see the list of voices returned from this call.

#### URLs

- https://github.com/AiVOOV/aivoov-api#voices-list

**Comment by GTFalcao** [comment]
@luancazarine I'll move this forward since you've already reviewed it

**Comment by GTFalcao** [comment]
@vunguyenhung , I cannot reproduce this error - can you confirm you're publishing from the `8318-aivoov` branch and are up-to-date? It seems like a code error but there are no references to an `engine` variable being made anywhere in the code (all are referenced via `this.engine`) so it could be outdated code.
