### ISSUE TITLE
[Components] docsbot_ai

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#8329]
# docsbot_ai
## URLs
- https://docsbot.ai/documentation/developer/chat-api
- https://docsbot.ai/documentation/developer/source-api

#### Prompt
This action asks a question. Please include all parameters: question, full_source, format, history, and metadata.

Please have an async option call to list teams, as well as to list bots based on the team that is selected.
#### URLs
- https://docsbot.ai/documentation/developer/team-api
- https://docsbot.ai/documentation/developer/bot-api
#### Prompt
This action creates a new source for a bot. Please include props for type, title, url, file, faqs, and scheduleInterval. Please include the relevant descriptions as well.

Please also include async options for teams, and bots using List Teams and LIst Bots calls.
#### URLs
- https://docsbot.ai/documentation/developer/source-api#create-source
- https://docsbot.ai/documentation/developer/team-api
- https://docsbot.ai/documentation/developer/bot-api

**Comment by GTFalcao** [comment]
This is a duplicate from #8426
