### ISSUE TITLE
[Revel system]

### ISSUE THREAD

**Issue by GauravICCG** [PipedreamHQ/pipedream#833]
want to integrate REVEL system 
https://support.revelsystems.com/s/article/Webhooks-1583146032320

**Comment by dylburger** [comment]
Hi @GauravICCG , are you looking to run a Pipedream workflow on webhooks sent from REVEL?

If you [create a new workflow](https://pipedream.com/new), you'll see an HTTP / Webhook trigger listed on the right:

<img width="837" alt="Screen Shot 2021-01-22 at 11 44 23 AM" src="https://user-images.githubusercontent.com/242668/105537797-4f05b500-5ca7-11eb-9c37-0f559b6446dc.png">

Click that, and you'll get a unique HTTP endpoint URL. You can send any HTTP request / webhook to this URL, so if you give that to the Revel team, they should be able to route webhooks to your workflow.

Let me know if that makes sense or if you have any additional questions.

**Comment by todsac** [comment]
@GauravICCG - if you are up for helping us finish the integration, I think we can get it setup.  We don't have a Revel account yet so we can't test the API.  However, I think we are close and just need a better test request.  You can copy this workflow - https://pipedream.com/@tod/p_MOC3yNa/ to test.  Let me know.

**Comment by dylburger** [comment]
@GauravICCG I just wanted to check in to see if you'd had a chance to test the integration. Let us know if you need any assistance!

**Comment by dylburger** [comment]
@GauravICCG did you have a chance to review this integration? Since we've added Revel as an integrated app, I'm going to go ahead and close this ticket, but let me know if you encounter any issues with the the integration or have any suggested improvements, and we're happy to take a look.
