### ISSUE TITLE
[SOURCE] Twitch API

### ISSUE THREAD

**Issue by Hope-IT-Works** [PipedreamHQ/pipedream#835]
Hey, it would be great if you would integrate the Twitch API.

**Comment by dylburger** [comment]
Hi @Hope-IT-Works , Twitch is actually [already integrated](https://pipedream.com/apps/twitch). If you add a step to your workflow and search "Twitch", you'll see the app listed:

<img width="447" alt="Screen Shot 2021-01-22 at 11 39 27 AM" src="https://user-images.githubusercontent.com/242668/105537366-ae16fa00-5ca6-11eb-948f-f734c70315d6.png">

If you click on the app, you'll see a couple of actions we have listed, along with the ability to run any Node.js code with your Twilio credentials:

<img width="442" alt="Screen Shot 2021-01-22 at 11 39 35 AM" src="https://user-images.githubusercontent.com/242668/105537450-cb4bc880-5ca6-11eb-867d-a83b6e3af65f.png">

Was there a specific action or trigger you were looking for, or does this work for you?

**Comment by Hope-IT-Works** [comment]
Oh, sorry didn't look close enough. I thought there maybe would be a trigger for Twitch when a specific Stream starts. But thanks for the lightning fast response.

**Comment by dylburger** [comment]
@Hope-IT-Works [I added an issue](https://github.com/PipedreamHQ/pipedream/issues/837) to track that request - agreed, we'd love to add Twitch triggers.

Are you comfortable writing Node.js code? All of our triggers are open source (see [the `components/` directory](https://github.com/PipedreamHQ/pipedream/tree/master/components) in this repo), and we have [a quickstart](https://github.com/PipedreamHQ/pipedream/blob/master/QUICKSTART.md) that walks you through how to create your own. If you're interested, we'd be happy to support you in any way (we operate a #contribute channel in our [Slack workspace](https://join.slack.com/t/pipedream-users/shared_invite/zt-ernlymsn-UHfPg~Dfp08uGkAd8dpkww) for this purpose).

**Comment by todsac** [comment]
Potential triggers for [Twitch API Integrations](https://pipedream.com/apps/twitch):
- Followed Streams | Triggers when a followed stream is live.
- New Live Stream | Triggers when a new stream goes live that matches any game and language specified.
- New Live Stream by Streamer | Triggers when a live stream starts from streamers you specify.
- New Clips | Triggers when there is a new clip for the games you follow.
- New Follower | Triggers when your channel gets a new follower.
- New Subscribers | Triggers when your channel has a new subscriber.
- New Videos | Triggers when there is a new video from channels you follow.
