### ISSUE TITLE
[Components] Tave

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8355]
# tave
## URLs
- https://www.tave.com
#### Prompt
Emit new event when a contact is created.
#### Prompt
Emit new event when an order is booked.
#### Prompt
Emit new event when a payment is created.
#### Prompt
Creates a new contact
#### Prompt
Searches for a contact
#### Prompt
Creates a new job including all related items

**Comment by malexanderlim** [comment]
Blocked on access and lack of API documentation. Reached out to Tave team.
