### ISSUE TITLE
Disable 80% quota notification emails

### ISSUE THREAD

**Issue by unixfox** [PipedreamHQ/pipedream#838]
![image](https://user-images.githubusercontent.com/4016501/105548997-49848b00-5cf8-11eb-8813-de078cc42828.png)

I know that my daily compute time quota is near the limit but at the end of each day I still have some room and I never reach 100%.
![image](https://user-images.githubusercontent.com/4016501/105549145-789afc80-5cf8-11eb-849d-a47192015292.png)

How may I disable these notifications? It's really annoying.

**Comment by dylburger** [comment]
@unixfox I hear you. There's not a way to disable these now, but I shared this feedback with the team and noted the request. For now, does your email provider support filters? In Gmail, for example, you can set a filter to have emails matching these conditions **Skip the Inbox**:

From: support@pipedream.com
Subject: 80% of daily invocations quota reached

Let me know if that might work for now.

**Comment by unixfox** [comment]
Well I self-host my own mail server, so I can do whatever I want even what you are describing.

But that's like a hard way of disabling notifications :) and I usually like to receive your emails.

Anyway I'll filter your emails based on the title for the moment until a solution is implemented.

**Comment by dylburger** [comment]
Great thanks @unixfox , glad you can implement the title-based filters. I appreciate your patience as we work through this backlog!

**Comment by dylburger** [comment]
For now, we provide list-based unsubscribes for these emails as a mechanism for disabling them.
