### ISSUE TITLE
[Components] google-merchant-center

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#8388]
# google-merchant-center
## URLs
- https://developers.google.com/shopping-content/reference/rest/v2.1/products
- https://developers.google.com/shopping-content/reference/rest/v2.1/products/list
- https://developers.google.com/shopping-content/reference/rest/v2.1/products/insert
- https://developers.google.com/shopping-content/reference/rest/v2.1/products/update

#### Prompt
Please create a polling source that utilizes the List Products endpoint method. The user will supply their merchantId.
#### URLs
- https://developers.google.com/shopping-content/reference/rest/v2.1/products/list

#### Prompt
Please create an action that allows the user to update an existing product. You can create a prop for Product, and use the products.list method to list all products available to update. 

Once the user selects a product, please utilize the products.get method as a dynamic prop that returns the existing values for the product. If the user makes any changes to these values, you will pass these changes in the updateMask	query parameter per the documentation. 

The query parameter updateMask
#### URLs
- https://developers.google.com/shopping-content/reference/rest/v2.1/products
- https://developers.google.com/shopping-content/reference/rest/v2.1/products/update
#### Prompt
Creates a product. Please include all props specified as required.
#### URLs
- https://developers.google.com/shopping-content/reference/rest/v2.1/products/insert
- https://support.google.com/merchants/answer/7052112?visit_id=638321462683148337-428884760&rd=1

**Comment by malexanderlim** [comment]
Hey @vunguyenhung , wondering if you can test the broken case to see if this is still an issue? If not, would like to close this one out and ship it!
