### ISSUE TITLE
[FEATURE] Google Sheets - add Format Rows as optional prop

### ISSUE THREAD

**Issue by ingeniaconsultants** [PipedreamHQ/pipedream#8389]
![image](https://github.com/PipedreamHQ/pipedream/assets/96611569/45da7fc9-91f1-4ef7-b2fa-0b58d9ce71b0)
 
Referring to the attached screen capture, 
On workflowV1, rows appeared correctly.
On workflowV2, rows added copied the cell format of the row above.
eg. If the row above is shaded yellow, all rows added with workflow V2 will be shaded yellow.

Just a bit of background, we have a few worksheets that we format the cells on the worksheet with how
 we want it to appear then fill it with text from CRM by using the workflow.
 
Is it possible for workflow V2 to maintain the feature of V1 by just adding the rows with plain text?

Thanks.

Adrian

**Comment by vellames** [comment]
@ingeniaconsultants I was able to reproduce this, but after some resarches. I didnt find a way to clear the row style. Google Sheets seems to assume that you want to keep using the last line style.
Cc: @malexanderlim

**Comment by vellames** [comment]
@ingeniaconsultants After some research, I didnt find a way to fix this problems. I was able to reproduce. But this seems to be a feature from Google Sheets. Looks like Google Sheets intentionally copy the style of the previous row.
Cc: @malexanderlim

**Comment by malexanderlim** [comment]
@ingeniaconsultants , can you try clearing the formatting first, before new rows are added? I'm not able to reproduce this on my end.

**Comment by malexanderlim** [comment]
Request: Add optional prop **Format Rows**, using `format-cells`
https://developers.google.com/sheets/api/samples/formatting

**Comment by ingeniaconsultants** [comment]
We do not have issues with workflow version 1, only with version 2 of
Googlesheet add multiple rows.

It seems like version 1 is able to add plain text but not version 2.

**Comment by ingeniaconsultants** [comment]
Can the cell format be kept and paste the content as plain text like the workflow V1?

We had set the cell format like the font, size, alignment and colour per the user's requirement, and the workflow just needs to paste the content as plain text.  

Thanks.

**Comment by ingeniaconsultants** [comment]
Before:
![Cell format before ex1](https://github.com/PipedreamHQ/pipedream/assets/96611569/2b5cc4a7-4393-4429-9269-a1d8b291d44f)

After:
![Cell format after ex1](https://github.com/PipedreamHQ/pipedream/assets/96611569/a2dacc45-c8bc-41a0-9f57-99bab9ea1786)

 

To add another issue, I noticed that if the content paste is not in plain text. 

Example, 

Cell B11-B23 has formula to sum the values of column F based on the column B content. 
 
The original formula of cell B2: 
=SUMIFS($F$28:$F$687, $B$28:$B$687, $A$12) 


After running the workflow V2, the formula valued changed and values not included in the summation. 
=SUMIFS($F$29:$F$688, $B$29:$B$688, $A$12)

**Comment by ingeniaconsultants** [comment]
Hi,

I don't know how this works.

I added further comments to the work done as it is not what we requested
but I realised the status is closed.

Would you like me to create a new request and repeat the comments?

Sincerely,
Adrian

**Comment by michelle0927** [comment]
Hi, @ingeniaconsultants . Yes, I'd recommend creating a new issue. No need to repeat the comments, just make sure you include a link referencing this issue.
