### ISSUE TITLE
[APP] Business Central

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#84]
https://docs.microsoft.com/en-us/graph/dynamics-business-central-concept-overview

**Comment by todsac** [comment]
@bssi-danielf - This api has been integrated.  FYI - it is in beta on the MSFT side so could change on their end at some point.  Please let us know if this meets your needs and we would appreciate building out any necessary actions -- https://docs.pipedream.com/workflows/steps/actions/#creating-your-own-actions

**Comment by bssi-danielf** [comment]
Thanks a lot Tod! I'll let you know if I encounter issues
