### ISSUE TITLE
[TRIGGERS]New Mailerlite Trigger

### ISSUE THREAD

**Issue by rahofyah** [PipedreamHQ/pipedream#8409]
Mailerlite automation

[**Link to developer documentation**
](https://developers.mailerlite.com/)

**Is lack of support preventing you from building workflows, or do you have a workaround?** No workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
When there's a new submission in a form, Mailerlite should create a subscriber and add them to a particular group (mailing list).

**Comment by sergio-eliot-rodriguez** [comment]
Hi @rahofyah 

Thanks for the request.

The functionality that you are describing corresponds to a logic implementable on Pipedream workflows.
The workflow would need to have the following steps: 
1. new submission trigger,
2. create subscriber action
3. add subscriber to a group action

I'm modifying your request to reflect this.

Cheers,
Sergio

**Comment by sergio-eliot-rodriguez** [comment]
**App**
Mailerlite

**Triggers**
New form submission

**developer documentation**
https://developers.mailerlite.com/docs/#mailerlite-api

**Context: **
OP described a workflow composed of new form submission trigger, and a couple of actions, which are already available in Pipedream.

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/033096df-9caa-4697-ae4d-54cc71288cef)


Image:
Create Suscriber
Add Subsriber to Group
actions, already existing


**Heads up:**
Mailerlite supports [webhooks](https://developers.mailerlite.com/docs/webhooks.html#available-events) which enable instant triggers. However, apparently there are no triggers for for submission. In order to create an event for notifying about form subsissions, perhaps it can be done via API polling: the "conversion count", or "last registration" fields could be observed to nofify new subscriptions, see [List Forms](https://developers.mailerlite.com/docs/forms.html#list-all-forms) endpoint.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by rahofyah** [comment]
> **App** Mailerlite
> 
> **Triggers** New form submission
> 
> **developer documentation** https://developers.mailerlite.com/docs/#mailerlite-api
> 
> **Context: ** OP described a workflow composed of new form submission trigger, and a couple of actions, which are already available in Pipedream.
> 
> ![image](https://user-images.githubusercontent.com/101526248/273737711-033096df-9caa-4697-ae4d-54cc71288cef.png)
> 
> Image: Create Suscriber Add Subsriber to Group actions, already existing
> 
> **Heads up:** Mailerlite supports [webhooks](https://developers.mailerlite.com/docs/webhooks.html#available-events) which enable instant triggers. However, apparently there are no triggers for form submission. In order to create an event for notifying about form subsissions, perhaps it can be done via API polling: the "conversion count", or "last registration" fields could be observed to nofify new subscriptions, see [List Forms](https://developers.mailerlite.com/docs/forms.html#list-all-forms) endpoint.

I don't know how you got to this screenshot. When I search for Mailerlite, nothing comes up. I'm not a dev, so I'd appreciate you dumbing it down for me. Thanks!

**Comment by rahofyah** [comment]
> Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.
> 
> If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

Sure. How do I begin?

**Comment by malexanderlim** [comment]
> > **App** Mailerlite
> > **Triggers** New form submission
> > **developer documentation** https://developers.mailerlite.com/docs/#mailerlite-api
> > **Context: ** OP described a workflow composed of new form submission trigger, and a couple of actions, which are already available in Pipedream.
> > ![image](https://user-images.githubusercontent.com/101526248/273737711-033096df-9caa-4697-ae4d-54cc71288cef.png)
> > Image: Create Suscriber Add Subsriber to Group actions, already existing
> > **Heads up:** Mailerlite supports [webhooks](https://developers.mailerlite.com/docs/webhooks.html#available-events) which enable instant triggers. However, apparently there are no triggers for form submission. In order to create an event for notifying about form subsissions, perhaps it can be done via API polling: the "conversion count", or "last registration" fields could be observed to nofify new subscriptions, see [List Forms](https://developers.mailerlite.com/docs/forms.html#list-all-forms) endpoint.
> 
> I don't know how you got to this screenshot. When I search for Mailerlite, nothing comes up. I'm not a dev, so I'd appreciate you dumbing it down for me. Thanks!

@rahofyah , where were you searching? Curious to know where can make improvements here.

**Comment by malexanderlim** [comment]
![Screenshot 2023-10-24 at 3 15 40 PM](https://github.com/PipedreamHQ/pipedream/assets/42158621/80b0a265-8f41-4eca-b76d-ababbd538850)
You should be able to find the **Mailerlite** application from the **Explore** page on the lefthand sidebar, under **Resources**. 

I've created a ticket to develop the requested triggers - please follow along here: https://github.com/PipedreamHQ/pipedream/issues/8616

I will close this issue for now, but please feel free to open if you see any issues with the new trigger once complete!
