### ISSUE TITLE
[BUG] Jibble is disconnected every 1-2 hours

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#8412]
**Describe the bug**
I connected my account to Jibble on Pipedream, but after 1 hour I received email from Pipedreams notifying me that my Jibble account is disconnected
<img width="1227" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/570bdb86-f765-462e-8b54-c99bfa40354f">

After I reconnected my Jibble account on Pipedream, I received another email and I need to reconnect my Jibble account again. 

On the third time that Jibble disconnected, when I tried to execute an action, it faced 401 error
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/2c22dff0-1cc6-4452-b403-a2dd5785aa51)

**To Reproduce**
1. Connect a Jibble account on Pipedream, wait and observed that the account disconnected every hour

**Expected behavior**
My Jibble account should stay connected

**Comment by malexanderlim** [comment]
@vunguyenhung , I've added in some refresh token logic (there isn't true refresh token, but another request for the token to be used as this is client credentials flow.) This should be fixed moving forward - can you confirm if you're no longer seeing this?
