### ISSUE TITLE
[BUG] Strikethrough Markdown not parse the params section in Telegram Bot

### ISSUE THREAD

**Issue by ibnunowshad** [PipedreamHQ/pipedream#844]
**Describe the bug**
Markdown for ~~strikethrough~~ in Telegram Bot not working. However **Bold** and _Italic_ function working while parse JSON contents to Telegram API

**To Reproduce**
I had attached the same sample codes, I am parsing to markdown
```
*Zoom meeting Updated*

*Topic:* ~~{{steps.trigger.event.payload.old_object.topic}}~~ _{{steps.trigger.event.payload.object.topic}}_
*Time:* ~~{{steps.nodejs.olddate}}~~ _{{steps.nodejs.newdate}}_ (_{{steps.trigger.event.payload.object.timezone}}_)

*Join Zoom Meeting* _{{steps.trigger.event.payload.object.join_url}}_

*Meeting ID:* ~~{{steps.trigger.event.payload.old_object.id}}~~ _{{steps.trigger.event.payload.object.id}}_
*Passcode:* ~~{{steps.trigger.event.payload.old_object.password}}~~ _{{steps.trigger.event.payload.object.password}}_
```
**Expected behavior**

*Zoom meeting Updated*

*Topic:* ~~{{steps.trigger.event.payload.old_object.topic}}~~ _{{steps.trigger.event.payload.object.topic}}_
*Time:* ~~{{steps.nodejs.olddate}}~~ _{{steps.nodejs.newdate}}_ (_{{steps.trigger.event.payload.object.timezone}}_)

*Join Zoom Meeting* _{{steps.trigger.event.payload.object.join_url}}_

*Meeting ID:* ~~{{steps.trigger.event.payload.old_object.id}}~~ _{{steps.trigger.event.payload.object.id}}_
*Passcode:* ~~{{steps.trigger.event.payload.old_object.password}}~~ _{{steps.trigger.event.payload.object.password}}_

**Comment by dylburger** [comment]
@ibnunowshad unfortunately since there is no true Markdown standard, the implementation of specific features like this can vary across providers. On Pipedream, if you wrap your text in a _single_ `~`, it should work:

![2021-01-25 09 27 02](https://user-images.githubusercontent.com/242668/105741904-b0b86000-5eef-11eb-8139-0604720bedca.gif)

**Comment by ibnunowshad** [comment]
It didn't solve my problem in realtime neither double ~ or single ~ in actual end user point of view.

Let me see in any other way around to solve this problem.
