### ISSUE TITLE
[Recharge]

### ISSUE THREAD

**Issue by jan-hillenbrand-fressnapf** [PipedreamHQ/pipedream#8445]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi Jan @jan-hillenbrand-fressnapf 

Thanks for the request.
We have ReCharge integrated, see: https://pipedream.com/apps/recharge

If you meant a different app, please let us know

Cheers,
Sergio
