### ISSUE TITLE
[BUG] Google Drive - New Files (Instant): Folders prop did not load

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#8446]
**Describe the bug**
When attempt to create the Google Drive - New Files (Instant) source and select the `Folders` prop, I didn't see the `Folders` prop load and there's no reaction when clicking into the `Folders` prop
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/825981cd-a9d5-4a66-8ec2-7fca6697a940)

Even though I have many folders in my Drive
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/8db7eea1-d621-43c1-b5a1-3a2c2d52a7ba)

**Expected behavior**
- The `Folders` prop should load all folders I have
- The source should be created successfully

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1697107482191509

**Comment by dylburger** [comment]
This should be fixed. Please reload https://pipedream.com/ and try to configure the trigger again. Let us know if you see any other related issues.

**Comment by jahooli14** [comment]
This is great, thank you!
