### ISSUE TITLE
[BUG] Can not scroll the workflow in editing mode

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#8456]
**Describe the bug**
Please see the recording here
https://www.loom.com/share/c86926737e6346faae0c89be7359a79f?sid=b254ab17-9328-4cdd-ab53-8b7f13a1354c

**Expected behavior**
The user should be able to scroll in editing mode

**Additional context**
https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1697182624506209

**Comment by martinawillner** [comment]
I have the exakt same problem.

**Comment by andrewjschuang** [comment]
Thanks for reporting. Please follow for updates [here](https://status.pipedream.com/incidents/r74hd6nh1vwz?utm_source=slack)

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
