### ISSUE TITLE
I can not scroll in editing mode [BUG] 

### ISSUE THREAD

**Issue by martinawillner** [PipedreamHQ/pipedream#8457]
I can not scroll in the workflow in editing mode. 

**To Reproduce**
1. Go to projects
2. Click on the workflow and the edit
3. there after I can not scroll down. 

**Expected behavior**
I need to edit the workflow in order to make it work. 

**Desktop (please complete the following information):**
 - Browser I tried both chrome, safari]

**Comment by andrewjschuang** [comment]
Thanks for reporting. Please follow for updates in #8456
