### ISSUE TITLE
[ACTION] Cloudflare Purge Files by URL

### ISSUE THREAD

**Issue by cuongtqtran** [PipedreamHQ/pipedream#846]
**Is there a specific app this action is for?**
Purge cache only specific URL
**Please provide a link to the relevant API docs for the specific service / operation.**
https://api.cloudflare.com/#zone-purge-files-by-url

**Comment by sergioeliot2039** [comment]
Purge Files by URL
Workflow: https://pipedream.com/@sergio/cloudflare-purge-files-by-url-p_3nCan83/edit
Action: https://pipedream.com/actions/a_RAi3qA/edit

**Comment by cuongtqtran** [comment]
Incorrect Authorize, I changed it into

  ```
headers: {
    "X-Auth-Email": `${auths.cloudflare_api_key.Email}`,
    "X-Auth-Key": `${auths.cloudflare_api_key.API_Key}`,
    "Content-Type": "application/json"
  },
```
It didn't use Beared Token.

Please update, I changed it manually and success.

**Comment by sergioeliot2039** [comment]
Updated! 
It didn't work for my API Key, I guess if you have to fallback to tokens like I did Beared Token will be needed, which is what I used.
