### ISSUE TITLE
[ACTION] Create String action

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#8461]
**Is there a specific app this action is for?**

PowerAutomate has the concept of steps that both define and set variables. Imagine if Pipedream had a step that let me define a string variable. Right now I need to use a code step. 

So for example - I want to build a string that I'll use with Twilio. This string consists of static text and results from two previous steps:

```js
export default defineComponent({
  async run({ steps, $ }) {
    return `Summary of email "${steps.trigger.event.headers.subject}" from ${steps.trigger.event.headers.from.text}:

${steps.generate_text.$return_value[0].candidates[0].output}    
`
  },
})
```

Now imagine I had a way to add an action, lets say Create String, that has one property for the value. In that, I would have typed:

```
Summary of email "${steps.trigger.event.headers.subject}" from ${steps.trigger.event.headers.from.text}:

${steps.generate_text.$return_value[0].candidates[0].output}    
```

And in Twilio, I'd do what I'm doing now, reference the $return_value of the step. 

**Please provide a link to the relevant API docs for the specific service / operation.**
Not applicable.

**Comment by sergio-eliot-rodriguez** [comment]
Product needs to think about if/how to implement this 
fyi @malexanderlim

**Comment by cfjedimaster** [comment]
Well shoot, I *knew* there was something like this already. However, I will point out an issue I saw maybe a year or so ago - searching for "export variables" returns nothing - you have to find Helper, _then_ search inside there. This should be more discoverable, right?

**Comment by dylburger** [comment]
@cfjedimaster agreed this should be more discoverable. Improving search UX is on our radar but since that's outside the scope of this issue, I'm going to close this.
