### ISSUE TITLE
[ACTION] Cloudflare purge all cache (purge everything)

### ISSUE THREAD

**Issue by cuongtqtran** [PipedreamHQ/pipedream#847]
*Is there a specific app this action is for?
Cloudflare purge all cache when some changes from ghost cms webhook.

*Please provide a link to the relevant API docs for the specific service / operation.
https://api.cloudflare.com/#zone-purge-all-files

**Comment by sergioeliot2039** [comment]
Cloudflare - Purge All Files
Workflow: https://pipedream.com/@sergio/cloudflare-purge-all-files-p_rvCqKqM/edit
Action: https://pipedream.com/actions/a_nji3N5/edit

Make sure the API key or token has appropriate permissions to Purge the cache.
https://dash.cloudflare.com/profile/api-tokens

**Comment by cuongtqtran** [comment]
Incorrect Authorize, I changed it into

  ```
headers: {
    "X-Auth-Email": `${auths.cloudflare_api_key.Email}`,
    "X-Auth-Key": `${auths.cloudflare_api_key.API_Key}`,
    "Content-Type": "application/json"
  },
```
It didn't use Beared Token.

Please update, I changed it manually and success.

**Comment by sergioeliot2039** [comment]
Updated! 
It didn't work for my API Key, I guess if you have to fallback to tokens like I did Beared Token will be needed, which is what I used.
