### ISSUE TITLE
[FEATURE] Support delivery of emits / logs to webhooks

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#849]
Currently, the REST API supports [subscriptions](https://docs.pipedream.com/api/rest/#subscriptions), which allow me to route events / logs from one source or workflow to another source or workflow.

I'd like to deliver events to a webhook endpoint I own, instead. For example:

* I'd like to call `this.$emit()` and send the respective event to a URL
* I'd like to forward logs or errors from a workflow to a URL

**Comment by faizansiddiqu007** [comment]
can i work on it

**Comment by dylburger** [comment]
Hi @faizansiddiqu007 , currently this part of our stack is not open source, but I love the energy! If you'd like to contribute to Pipedream, there are a few ways:

* You can create and publish [actions](https://docs.pipedream.com/workflows/steps/actions/).
* You can create event sources (see the [quickstart](https://github.com/PipedreamHQ/pipedream/blob/master/QUICKSTART.md) and [API reference](https://github.com/PipedreamHQ/pipedream/blob/master/COMPONENT-API.md)). Event sources are the triggers you see for workflows, e.g. Google Drive - New Files.
* You can contribute to [our docs](https://github.com/PipedreamHQ/pipedream/tree/master/docs), publish a video to YouTube, or write a blog post about how you're using Pipedream.

Let me know if that helps or if you're interested in any of those options.

**Comment by dylburger** [comment]
[This is now supported](https://docs.pipedream.com/api/rest/webhooks/)
