### ISSUE TITLE
[IMPROVEMENT] Improve Xero - Create Sales Invoice action props

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#8490]
**Is your feature request related to a problem? Please describe.**
- In the code of [Xero - Create Sales Invoice action here, I see that the `line_items` prop is passed as is into the request](https://github.com/PipedreamHQ/pipedream/blob/master/components/xero_accounting_api/actions/xero-create-sales-invoice/xero-create-sales-invoice.mjs#L114), meaning that the user must use the custom expression to pass the JSON array.
- Improve the `tenant_id` prop to add label, and make it an async option using this API: https://developer.xero.com/documentation/guides/oauth2/tenants/#check-the-tenants-youre-authorised-to-access
- Improve the `contact_id` prop to add the label, and make it an async option if possible

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1697459520850199

**Comment by vellames** [comment]
Sorry. I realized I moved the wrong card
