### ISSUE TITLE
[ACTION] Create a new post (Ghost Admin API)

### ISSUE THREAD

**Issue by cuongtqtran** [PipedreamHQ/pipedream#853]
**Is there a specific app this action is for?**
Ghost.org
**Please provide a link to the relevant API docs for the specific service / operation.**
https://ghost.org/docs/admin-api/#creating-a-post

**Comment by sergioeliot2039** [comment]
Create new post, ghost admin api.

action: https://pipedream.com/actions/a_q1i3BW/edit
workflow: https://pipedream.com/@sergio/ghost-admin-api-create-post-p_V9Cxv8N/edit
