### ISSUE TITLE
[BUG] LinkedIn fails using - https://api.linkedin.com/v2/ugcPosts

### ISSUE THREAD

**Issue by oliviermills** [PipedreamHQ/pipedream#854]
**Describe the bug**
Using LinkedIn in a workflow to post a post, get a `Resource ugcPosts does not exist` 404 error using the valid endpoint  https://api.linkedin.com/v2/ugcPosts
Possibly a permissions issue.
This used to work (at least in October 2020 it did).

**To Reproduce**
1. Create a new workflow
2. Add an action to use the LinkedIn app, connect it
3. Post a simplified version say https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api#sample-request - 

**Screenshots**
My workflow: 
![image](https://user-images.githubusercontent.com/6075303/105943061-b14f1480-601d-11eb-9ee6-0b39fabc0658.png)

**Additional context**
Haven't tried with the /share linkedin endpoint but could help troubleshoot.

**Comment by todsac** [comment]
Here are the current scopes for the LinkedIn app.  They are quite restrictive in getting additional scopes added.  Can you let us know which scopes you would need for these calls?

Scopes:
- r_1st_connections_size
- r_ads_reporting
- rw_organization_admin
- w_member_social
- w_organization_social
- r_basicprofile
- rw_ads
- r_organization_social
- r_ads

**Comment by oliviermills** [comment]
Thanks @todsac `w_organization_social` and `w_member_social` should be sufficient for the above code/request.
The error was that the axios method should be `post`, not the default `get`. Solved. Thank you!
