### ISSUE TITLE
[BUG] MoDeck connection popup leads to incorrect link

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#8540]
**Describe the bug**
In the MoDeck connection popup, there's a link to a Settings page that links to the API Key page 
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/bb822290-bb47-4993-9d1a-949897c646e6)

But the link leads to https://app.knowfirst.ai/settings which is an incorrect app, it should be https://app.modeck.io/settings instead

**Comment by malexanderlim** [comment]
Thanks for reporting, fixed!
