### ISSUE TITLE
Google Keep

### ISSUE THREAD

**Issue by nalediym** [PipedreamHQ/pipedream#8558]
**Name of app / service**
Google Keep
**Link to developer documentation**
https://developers.google.com/keep/api/reference/rest
**Is lack of support preventing you from building workflows, or do you have a workaround?**
yes
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
https://www.googleapis.com/auth/keep.readonly

**Comment by sergio-eliot-rodriguez** [comment]
Hi @nalediym

Thanks for the request, would you mind following for changes in this issue #2615 

Currently blocked on an known bug with Google Keep API, as per : https://stackoverflow.com/questions/70312083/google-keep-api-responds-with-invalid-scope-when-using-documented-scopes
