### ISSUE TITLE
[APP] ReCharge API

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#856]
https://support.rechargepayments.com/hc/en-us/articles/360008829993-ReCharge-API-

**Comment by todsac** [comment]
Blocked.  I reached out to ReCharge for help.

**Comment by todsac** [comment]
Workflow - https://pipedream.com/@tod/recharge-payments-api-integration-example-p_dDCnyzy/
Marketplace - [Recharge Payments API Integrations](https://pipedream.com/apps/recharge)

**Comment by todsac** [comment]
I have requested Partner access to move this integration to OAuth.
