### ISSUE TITLE
[BUG] $.respond() with readable stream in the body are not being sent as readable stream

### ISSUE THREAD

**Issue by parisetflorian** [PipedreamHQ/pipedream#8565]
According to the documentation, $.respond() is supposed to be able to handle readable streams.

Sadly, the implementation seems broken, and the respond() wait for the entire stream to be cached before sending the response. This is despite the response's body including "body_streamed:true".

<img width="925" alt="Screenshot 2023-10-23 at 14 04 10" src="https://github.com/PipedreamHQ/pipedream/assets/7931903/00bf7b43-fa52-4369-9659-6f6c25f4c472">

**Here is my test workflow where you can reproduce the issue with :**
https://pipedream.com/@insiderisk/projects/proj_zNsZnR/getaudio-p_13Claj9/inspect

Send a POST request to the endpoint with
body = {
    "html" : "Sam Harris is the author of five New York Times best sellers. His books include The End of Faith, Letter to a Christian Nation, The Moral Landscape, Free Will, Lying, Waking Up, and Islam and the Future of Tolerance (with Maajid Nawaz)."
}

You'll see that the audio is sent by the workflow only once the original stream from ElevenLab has been fully received. 
The desired behaviour would be to start streaming as soon as the readable streams is passed to $.respond().

**And here is the related part of the documentation:**
The value of the body property can be either a string, object, a [Buffer](https://nodejs.org/api/buffer.html#buffer_buffer)
[(opens new window)](https://nodejs.org/api/buffer.html#buffer_buffer)
(binary data), or a [Readable stream](https://nodejs.org/api/stream.html#stream_readable_streams)
[(opens new window)](https://nodejs.org/api/stream.html#stream_readable_streams)
. Attempting to return any other data may yield an error.

In the case where you return a Readable stream:
You must await the $.respond function (await $.respond({ ... })
The stream must close and be finished reading within your [workflow execution timeout](https://pipedream.com/docs/limits/#time-per-execution).
You cannot return a Readable and use the immediate: true property of $.respond.
You can Copy [this example workflow](https://pipedream.com/@dylburger/issue-an-http-response-from-a-workflow-p_ljCRdv/edit)
[(opens new window)](https://pipedream.com/@dylburger/issue-an-http-response-from-a-workflow-p_ljCRdv/edit)
and make an HTTP request to its endpoint URL to experiment with this.

Also, note that the link of the workflow mentioned in the documentation is broken.

**Comment by theartpiece** [comment]
Hi

We're students at UT Austin looking for an issue to work on for our course project. We are interested in this issue and aim to raise PR and get it approved within a month. We will appreciate your help.

Regards

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
@parisetflorian The `body` param can take a Readable stream, but it doesn't stream the response back to the client.
