### ISSUE TITLE
[FEATURE] improve workflow versionning

### ISSUE THREAD

**Issue by loicginoux** [PipedreamHQ/pipedream#857]
**Is your feature request related to a problem? Please describe.**
For testing my workflow with a real case, I need to deploy my code, so everytime I test something I create a new version of the workflow. My workflow ends up with lots of versions. Most of them have bugs or are here for testing/debugging
Sometimes I want to go back to a specific version but I can't remember which one it was, it can be 10 versions back or more, it's hard to identify versions and difference between them

**Describe the solution you'd like**
Something closer to real code versioning, so more like git commits:
- being able to add a comment to a version. This would be a "quick win", as I could just tag a revision that I know is working before creating more revisions, So I can easily come back to it even if I created many revisions after.
- Nice to have:  being able to compare 2 versions of a workflow

**Comment by dylburger** [comment]
@loicginoux if you could store your workflow in a Git repo, such that you could use Git to manage this, would that work? 

I like the idea of the tagging, etc., just curious if Git would solve the use case for you.

**Comment by loicginoux** [comment]
Yes that’s another solution, that would work as well. Thx

**Comment by dylburger** [comment]
Ok great. I added your request as a comment on #220, where we're tracking that. If you don't mind, go ahead and follow that issue for updates.
