### ISSUE TITLE
[Components] Spotlightr

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8578]
### App
Spotlightr
https://spotlightr.com/

Triggers:
1. Video Viewed: Activated when a specific video is viewed by a user.
2. Video Completion: Triggered when a user completes watching a particular video.

Actions:
1. Create Video: Allows the creation of a new video in your Spotlightr account.
https://app.spotlightr.com/docs/api/#create-video
2. Update Video: Enables changes to an existing video's properties.
3. Delete Video: Facilitates the removal of a specified video from your Spotlightr account.

_This list of suggested components was generated using ChatGPT_

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Spotlightr-737441a7d9584a12b7bc4084990dc74c

Hi @vunguyenhung, I don't know what happened, I think the problem could be with the platform itself perhaps . my test worked well.
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/de545f30-bbd6-4db2-85e6-52ee3b7f7198)
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/89347774-a4b1-4406-989e-cc15a45f3e58)
