### ISSUE TITLE
[ACTION][GITHUB] List releases

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#8600]
I want to be able to list releases for a given repo

**Is there a specific app this action is for?**
Github

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases

**Comment by lcaresia** [comment]
`List Releases` action already exists on Github app.

https://github.com/PipedreamHQ/pipedream/blob/master/components/github/actions/list-releases/list-releases.mjs
