### ISSUE TITLE
[APP] Lusha API 

### ISSUE THREAD

**Issue by wmuza** [PipedreamHQ/pipedream#861]
https://www.lusha.com/lusha-api/
https://www.lusha.com/docs

**Comment by todsac** [comment]
I requested an API key but I think I got the integration up and running.  Can you confirm?

Example workflow - https://pipedream.com/@tod/lusha-api-integration-example-p_pWCYzDY/edit
Marketplace - [Lusha API Integrations](https://pipedream.com/apps/lusha)

**Comment by wmuza** [comment]
Woow Todd this was extremely fast, you guys are excellent

**Comment by todsac** [comment]
Please confirm that it works for you so I can close the ticket.

**Comment by wmuza** [comment]
I am still waiting for the API key from my admins. That maybe monday

**Comment by wmuza** [comment]
Hi @todsac I tried the API now but it is returning an error all the time

{"message":"Could not find data for xxx  xxx"}

**Comment by wmuza** [comment]
Actualy it was my error, it is working
