### ISSUE TITLE
[Components] mailerlite

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#8616]
# mailerlite
## URLs
- https://developers.mailerlite.com/docs/webhooks.html#available-events

#### Prompt
Emits a new event when a new subscriber is added to an account.

#### URLs
- https://developers.mailerlite.com/docs/webhooks.html#create-a-webhook
#### Prompt
Emits an event when a subscriber becomes unsubscribed.
#### Prompt
Emits a new event when a subscriber is added though a form.

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-mailerlite-eef6c35b68c04f279d30d9101fb51dfc

I don't know why we're not getting the webhook, but it's there. Maybe it's some other type of form? I don't know.
![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/e602e54f-f448-4821-b7d9-ffaf1ac1169f)
