### ISSUE TITLE
[Components] neetoinvoice

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#8637]
# neetoinvoice
## URLs
- https://help.neetoinvoice.com/articles/neetoinvoice-zapier-integration#api-documentation

#### Prompt
Emits a new event every time there is a new client.
#### URLs
- https://help.neetoinvoice.com/articles/neetoinvoice-zapier-integration#api-documentation
#### Prompt
Emits a new event when there is a new invoice.
#### URLs
- https://help.neetoinvoice.com/articles/neetoinvoice-zapier-integration#api-documentation

**Comment by vellames** [comment]
@malexanderlim It was not possible to find the base URL of this API. I manually looked into the docs, tried Google, and tried to ask Chatgpt with Bing to find the base URL. Also, I tried contact in their chat, but they didn't answer.
I tried some combinations and used postman to see if I could find the URL, but I had no success
Can you help me with this?

**Comment by malexanderlim** [comment]
@vellames I'm unable to find the base API URL as well. I've reached out to the Neetoinvoice team. Thanks for flagging the blocker.

**Comment by sergio-eliot-rodriguez** [comment]
I was able to make this work:

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/c11969a2-85c6-41b6-b6c8-f626641c37b1)


the URL for subscriptions endpoint is  https://{{organization_name}}.neetoinvoice.com/neeto_integrations/zapier/subscriptions

when testing i faced another problem. the api key seems to had been rotated, and I generated a new one, which was added to 1PW
