### ISSUE TITLE
[ACTION] Lusha

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#864]
**Is there a specific app this action is for?**
Lusha

**Please provide a link to the relevant API docs for the specific service / operation.**
https://www.lusha.com/docs/#company-api

Lookup Contact - Lookup a contact
Lookup Company - Lookup a company

**Comment by alysonturing** [comment]
[Their API is a paid enterprise feature](https://pipedream-users.slack.com/archives/G01J50YGJGP/p1654089850397639)

**Comment by vunguyenhung** [comment]
Hello @todsac, as discussed with @dannyroosevelt, we agree to ship this Lusha component first for customer to use, then monitor if any customer faced any issue. Then if there's a bug then we can have a paid account to investigate.

cc @lcaresia @jcortes

**Comment by dannyroosevelt** [comment]
This is ready for release!
