### ISSUE TITLE
[Components] Brilliant Directories

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8645]
# brilliant_directories
## URLs
- https://support.brilliantdirectories.com/support/solutions/articles/12000088887-api-overview-and-testing-the-api-from-admin-area
#### Prompt
Creates a new user record in the website database.
#### URLs
- https://support.brilliantdirectories.com/support/solutions/articles/12000088887-api-overview-and-testing-the-api-from-admin-area#section-apiv2usercreate
#### Prompt
Creates a single or group post.
#### URLs
- https://support.brilliantdirectories.com/support/solutions/articles/12000093239-member-posts-api-create-update-delete-and-get-member-posts#section-single-posts
#### Prompt
Updates a post in your website database.

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Brilliant-Directories-dc1bd835827242a9a8ed1e3c9639178e

Hi @vunguyenhung. The problem is that in your test you used http://, but when creating a new account, it asks you to fill it in without the http, but in the code it is hardcoded https://, and the domain of your test probably does not have a certificate.

![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/51eddf4c-d724-4e89-8907-113c147d415d)

![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/8ce16e7c-7815-455c-bee2-413812b4abe2)

![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/6be77b37-3005-4bfe-80d3-0bab0212c8a1)

**Comment by luancazarine** [comment]
> Hi @luancazarine, I think we really need to make the code work with both HTTP and HTTPS. Since not everyone will set the HTTPS right away and test with Pipedream, and the HTTP URL works when using with Code step
> 
> I think we can add a logic to the code to try with HTTPS first, and if there's a self-signed cert error, we will try with HTTP.

Hi @vunguyenhung, What do you think about changing account creation, making it possible to add the entire URL with the protocol instead of the code making unnecessary requests?

**Comment by luancazarine** [comment]
Hi @vunguyenhung @sergioeliot2039, Any news about this subject?

**Comment by sergio-eliot-rodriguez** [comment]
> Hi @vunguyenhung @sergioeliot2039, Any news about this subject?

Hi @luancazarine 
I apologize for the late response.

This one falls into @malexanderlim scope (or Danny's), I'm sure it is possible to modify the app's file at the code level to accept the entire URL (including the protocol) or have an additional prop for the protocol to have options "http", "https (perhaps, as another way to move forward with the issue you are facing).

Let me flag this for Michael to tackle next week, once he is back.

**Comment by luancazarine** [comment]
@sergioeliot2039, thanks for the answer, I'll be waiting, LMK.

**Comment by luancazarine** [comment]
Hi @malexanderlim, It worked fine! Thank you!
