### ISSUE TITLE
[ACTION] FreshDesk

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#865]
**Is there a specific app this action is for?**
FreshDesk

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.freshdesk.com/api/

### Triggers
- New Ticket
- New Contact

### Actions
- Create a Company | Creates a new company.
- Create a Contact | Creates a new contact.
- Create a Ticket | Creates a new ticket.
- Get a Ticket | Gets the details of a ticket.

**Comment by dannyroosevelt** [comment]
This is ready for release!
