### ISSUE TITLE
[ACTION / SOURCES] Adalo

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#866]
**Is there a specific app this action is for?**
Adalo

**Please provide a link to the relevant API docs for the specific service / operation.**
https://help.adalo.com/integrations/the-adalo-api

Create Record | Creates a new record in a Collection in an Adalo app.
New Record | Triggers when a new record is added to a Collection in an Adalo app.
Update Record | Updates a Record

**Comment by dannyroosevelt** [comment]
This is ready for release!
