### ISSUE TITLE
[APP] Neverbounce

### ISSUE THREAD

**Issue by wmuza** [PipedreamHQ/pipedream#867]
**Name of app / service**
Neverbounce

**Link to developer documentation**
https://developers.neverbounce.com/docs

**Is lack of support preventing you from building workflows, or do you have a workaround?**
- Lack of support

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
1. Verifying an Email 
2. Verifying a List 
3. Running a Free Analysis

**Comment by todsac** [comment]
Example - https://pipedream.com/@tod/neverbound-api-integration-example-p_13CgOLl/
Marketplace - [Neverbounce API Integrations](https://pipedream.com/apps/neverbounce)

I added the verifying an email action as a demo but the rest of the actions can be built out now.
