### ISSUE TITLE
[ACTION] to be able to use discord to change svr port  on clouldflare 

### ISSUE THREAD

**Issue by EWANZO101** [PipedreamHQ/pipedream#8678]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by dylburger** [comment]
@EWANZO101 can you clarify exactly what you need?

**Comment by EWANZO101** [comment]
i am seeking a method within Discord to input a specific command that would trigger the modification of a Cloudflare SRV record. The command might resemble "/change port 100 to port 200 in the Cloudflare SRV record."

**Comment by dylburger** [comment]
Thanks. This should be possible with our pre-built actions:

1. You can [listen for a new Discord slash command](https://pipedream.com/apps/discord/triggers/new-command-received)
2. Then you can [create](https://pipedream.com/apps/cloudflare-api-key/actions/create-dns-record) or [patch](https://pipedream.com/apps/cloudflare-api-key/actions/patch-dns-record) a specific DNS record based on the input from the command.

Let us know if that helps.
