### ISSUE TITLE
[APP] Gladia

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#8684]
**Name of app / service**
Gladia

**Link to developer documentation**
https://docs.gladia.io/reference/overview

**Is lack of support preventing you from building workflows, or do you have a workaround?**
no

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Test request using multipart/form-data,
can try
https://pipedream.com/@sergio/projects/proj_Bgs4Yj/gladia-test-request-p_D1ClzbN/inspect

> import axios from 'axios';
> import FormData from 'form-data';
> export default defineComponent({
>   async run({ steps, $ }) {
> 
> 
>   const custom_fields = {
>     api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
>   };
> 
>   const params = {
>     audio_url: "http://files.gladia.io/example/audio-transcription/split_infinity.wav",
>     toggle_diarization: "true"
>   }
> 
>   const form = new FormData();
>   form.append('audio_url', params.audio_url);
>   form.append('toggle_diarization', params.toggle_diarization);
> 
>   const response = await axios.post(
>     'https://api.gladia.io/audio/text/audio-transcription/',
>     form,
>     {
>       headers: {
>         ...form.getHeaders(),
>         'x-gladia-key': custom_fields.api_key
>       }
>     }
>   );
>   
>   return response.data;
>   },
> })
>
