### ISSUE TITLE
[Components] satismeter

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#8687]
# satismeter
## URLs
- https://app.satismeter.com/apidoc#section/Authentication
- https://app.satismeter.com/apidoc#section/Project-and-survey-IDs
- https://app.satismeter.com/apidoc#section/Pagination

#### Prompt
Emits a new event when a survey response is submitted to a project. Please have an optional prop for Surveys, and if selected, make an async option call to List Surveys, so the user can choose to listen for responses to a specific survey.
#### URLs
- https://app.satismeter.com/apidoc#tag/Responses/paths/~1projects~1%7BprojectId%7D~1responses/get
- https://app.satismeter.com/apidoc#tag/Surveys

**Comment by malexanderlim** [comment]
There is no "List Projects" endpoint, but I've reached out to the Satismeter team to see if they can enable one for us.

**Comment by luancazarine** [comment]
@malexanderlim Did you have any news?

**Comment by malexanderlim** [comment]
From the Satismeter team:
> I have taken a look into this for you and found that it is not possible to perform a 'List Projects' API request..
