### ISSUE TITLE
When rendering queryparam based values and showing a suggestion, make it obvious it's a suggestion

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#87]
**Is your feature request related to a problem? Please describe.**
I've got a HTTP triggered workflow. It needs to accept a querystring parameter. When I tested by passing ?subreddit=X, I was really happy to see that the editor let me type steps.trigger.event.query.subreddit. 

However when it rendered it, it included white text that matches my last test.

![image](https://user-images.githubusercontent.com/393660/79668833-30edb000-817d-11ea-8783-82c1bab6c5ce.png)

It looked a bit weird, like maybe it was going to use it as a hard coded value. I know now it's a sample, but I'd add hovertext over the white portion that says, "This is an example of the values passed to this URL." or "This is sample input."

**Describe the solution you'd like**
Um, see above. :)

**Comment by dylburger** [comment]
@cfjedimaster now that we've shipped the new params form, what do you think about the new UX, with respect to the display of example values?

I know you've played around with the new form, but for others who land here: see [this video](https://www.youtube.com/watch?v=6eq813uEExc) and [these docs](https://docs.pipedream.com/workflows/steps/params/) for more information about the current params form.

**Comment by cfjedimaster** [comment]
I really like this, but I'm struggling to understand the difference between structured and unstructured input. In the docs, the array example seems to imply that - in structured mode, you enter a value for each array index, and in unstructured, you create an expression that points to an array. Is that right?

**Comment by dylburger** [comment]
That's correct. Is there a way we could make that more clear?

**Comment by cfjedimaster** [comment]
Honestly I don't know. :) So basically it's like this. If an arg is an object, or an array, PD is going to 'help' me by providing a UI that lets me enter keys of the object or items in the array. This is the structured version and the default. The unstructured version basically says - pass mean expression that will evaluate to what I need. 

Maybe some kind of text along that lines would help? I don't know - it's clicking a bit more for me. I'd say - if you hear other users express confusion, come back and we can try to hash out an edit or two to the docs, but if not, it was just me. ;)

**Comment by dylburger** [comment]
Makes a lot of sense, I'll share this feedback with the team. We've struggled to articulate this ourselves. 

What do you think about the display of test data specifically, in the object explorer below the field? I'd like to know if the new display of test data solves the original concern you raised in the ticket, or if you think there's still work to do.

**Comment by cfjedimaster** [comment]
It's great and much better than the original version - thank you!

**Comment by dylburger** [comment]
Awesome, thanks for all the feedback here Raymond. I'll close this ticket but please raise others if you have more questions / issues.
