### ISSUE TITLE
[APP] Notion

### ISSUE THREAD

**Issue by mccarvell** [PipedreamHQ/pipedream#870]
Notion.so

https://www.notion.so/Does-Notion-have-an-API-I-can-use-4541b07a5caa46dba0026624646118c0

Notion is amazing and their API is hitting public beta soon

Creating pages, reading page content, pulling data from a database

**Comment by dylburger** [comment]
@mccarvell thanks for adding an issue for this. I've added us to the public waitlist.

If you have a few minutes, feel free to reach out to the Notion team to let them know how much you'd like to use the Notion API on Pipedream! That feedback might expedite our access to the API.

**Comment by todsac** [comment]
We integrated the Notion API into Pipedream. Triggers and actions coming shortly:
- Marketplace: https://pipedream.com/apps/notion
- Workflow Example: https://pipedream.com/@tod/p_D1C3LlN
