### ISSUE TITLE
[Components] convenia

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#8702]
# convenia
## URLs
- https://docs--api-convenia-com-br.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#introducao

#### Prompt
Emits an event when there is a new vacation request at the company. 

#### URLs
- https://docs--api-convenia-com-br.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#empresa

#### Prompt
Emits an event when there is a new employee that has been dismissed.
#### URLs
- https://docs--api-convenia-com-br.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#colaboradores

#### Prompt
Creates a new leave of absence for an employee. Please use async options to list all employees.
#### URLs
- https://docs--api-convenia-com-br.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#faltas-e-afastamentos
- https://docs--api-convenia-com-br.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#colaboradores

**Comment by luancazarine** [comment]
Hi @vunguyenhung, you must add some scopes for these components work

Action

- List of collaborators

Sources 

- List of collective vacations
- List of terminated employees

**Comment by dannyroosevelt** [comment]
@luancazarine can you tell me the exact scopes from their API docs so I can add to the app's configuration?

**Comment by dannyroosevelt** [comment]
Oh gotcha, sorry I think I misunderstood -- you're saying Leo ran into issues because his key lacked sufficient scopes?

**Comment by luancazarine** [comment]
@dannyroosevelt exactly! Thanks for explaining better!
