### ISSUE TITLE
[FEATURE] psycopg2 for python step

### ISSUE THREAD

**Issue by eeitnn** [PipedreamHQ/pipedream#8720]
Unfortunately the Python step lacks the psycopg2 module.
Trying to import it results in an error:
![grafik](https://github.com/PipedreamHQ/pipedream/assets/86358217/b4c50932-a87d-4589-bb0f-3a9dcc909e0f)
 
As described [here](https://pipedream.com/community/t/python-lib-psycopg2-fails-to-import/2609) I've also tried to use the magic comment
`# pipedream add-package psycopg2-binary`
as well as 
`# pipedream add-package awslambda-psycopg2`.
This didn't help.
It seems like the psycopg2 binary was built for AMD architecture while workflow steps run in an ARM environment.
Is there any chance that the python step is ever going to support psycopg2?

**Comment by andrewjschuang** [comment]
@eeitnn You should be able to `import psycopg2` from now on!
