### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by Jpz1612** [PipedreamHQ/pipedream#8721]
**Name of app / service**
Implantar VLibras no Boards Burger

**Link to developer documentation**
https://boardsburger.com.br/boards_burger

**Is lack of support preventing you from building workflows, or do you have a workaround?**
<div vw class="enabled">
    <div vw-access-button class="active"></div>
    <div vw-plugin-wrapper>
      <div class="vw-plugin-top-wrapper"></div>
    </div>
  </div>
  <script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
  <script>
    new window.VLibras.Widget('https://vlibras.gov.br/app');
  </script>

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @Jpz1612 Sounds like this is an spammy request, or you are actually rquesting for the VLIbras tool

**Comment by Jpz1612** [comment]
Estou querendo implantar a ferramenta VLibras no site Boards Burger.

**Comment by sergio-eliot-rodriguez** [comment]
Got it, thanks for clarifying.

I saw you are using the other ticket where we are tracking the ingration https://github.com/PipedreamHQ/pipedream/issues/8722

**Comment by Jpz1612** [comment]
Então eu tenho a liberação para implantar a ferramenta VLibras no site Boards Burger?
