### ISSUE TITLE
[APP] Integrate Google Business Profile API

### ISSUE THREAD

**Issue by subhahu123** [PipedreamHQ/pipedream#8733]
**Name of app / service**
Google Business Profile

**Link to developer documentation**
https://developers.google.com/my-business/content/overview

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No, I will start working on adding this.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Existing Trigger are enough.

**Comment by dylburger** [comment]
@subhahu123 take a look at the integration [here](https://pipedream.com/apps/google-my-business). If you're lacking something specific with that, please open another issue if you don't mind!

**Comment by subhahu123** [comment]
@dylburger  I see, but it does not have all feature like other apps have of posting and all. So we will have to write our own code. But it will be great if we can integrate those features in this.

I can take this task of working on this feature..

**Comment by dylburger** [comment]
@subhahu123 Yes, if you're interested, you can [contribute any sources and actions](https://pipedream.com/docs/apps/contributing/#contribution-process) yourself. We're happy to help answer questions — you should join [our public Slack community](https://pipedream.com/support) if you're not there already!

**Comment by subhahu123** [comment]
@dylburger Thanks, I will go through the doc you have mentioned.
