### ISSUE TITLE
[APP] Loop Returns

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#8741]
**Name of app / service**
Loop Returns

**Link to developer documentation**
https://docs.loopreturns.com/reference/introduction

**Comment by malexanderlim** [comment]
Returnly app has sunsetted, replaced with Loop Returns

**Comment by sergio-eliot-rodriguez** [comment]
Initial reachout

**Comment by sergio-eliot-rodriguez** [comment]
Loop returns provided access and app was submitted
