### ISSUE TITLE
[Components] bitbucket

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#8754]
# bitbucket
## URLs
- https://support.atlassian.com/bitbucket-cloud/docs/manage-webhooks/#Trigger-webhooks

#### Prompt
Emits a new event every time there is a new comment on a pull request.
#### URLs
- https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/#Comment-created.1

**Comment by malexanderlim** [comment]
https://github.com/PipedreamHQ/pipedream/issues/8750 

This has been completed in https://github.com/PipedreamHQ/pipedream/issues/8750
