### ISSUE TITLE
[FEATURE] Deploy + Run in one click

### ISSUE THREAD

**Issue by bratchenko** [PipedreamHQ/pipedream#876]
When actively developing code, I always want to run new versions of code after each change. Currently, I need to look for "Deploy" button", click it, wait for deployment, then click "Run". 

It would be very convenient to be able to click "Deploy & Run" from anywhere on the workflow editing page.

**Comment by dylburger** [comment]
@bratchenko makes a lot of sense. Can you articulate what you mean specifically by "Run"? Would you expect this option to deploy the workflow and trigger a run with the selected test event, mimicking the "Send Test Event" button?

**Comment by dylburger** [comment]
We thought about this use case from the ground up, and have developed a new testing flow in [the new version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/). You can now test changes, step-by-step, prior to deploying your workflow. You can test also test all steps above, below, or test the entire workflow.
