### ISSUE TITLE
[APP] Originality.ai

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#8765]
**Name of app / service**
OriginalityAI

**Link to developer documentation**
https://docs.originality.ai/introduction

**Comment by malexanderlim** [comment]
@sergio-eliot-rodriguez creds available in shared 1P

**Comment by sergio-eliot-rodriguez** [comment]
Submitted!

**Comment by sergio-eliot-rodriguez** [comment]
Integrated: https://pipedream.com/apps/originality-ai
