### ISSUE TITLE
[Components] Postalytics

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8769]
# postalytics
## URLs
- https://postalytics.docs.apiary.io/
#### Prompt
Emits new event when a Postalytics mail piece has a delivery or online response status change.
#### URLs
 - https://postalytics.docs.apiary.io/#reference/campaign-api/campaign-collection/get-all-campaigns
 - https://postalytics.docs.apiary.io/#reference/webhook-api/webhook/create-webhook
#### Prompt
Emits new event when a new campaign event occurs.
#### URLs
 - https://postalytics.docs.apiary.io/#reference/campaign-api/campaign-collection/get-all-campaigns
 - https://postalytics.docs.apiary.io/#reference/webhook-api/webhook/create-webhook
#### Prompt
Send a postcard or letter with the capability of tracking delivery and response.
#### URLs
 - https://postalytics.docs.apiary.io/#reference/send-api/send/send-a-mailpiece
#### Prompt
Enable the creation of a contact.
#### URLs
 - https://postalytics.docs.apiary.io/#reference/contact-api/contact-list-collection/get-all-contact-lists
 - https://postalytics.docs.apiary.io/#reference/template-api/template-collection/add-contact
#### Prompt
Display a list of contacts.
#### URLs
 - https://postalytics.docs.apiary.io/#reference/contact-api/contact-list-collection/get-all-contact-lists

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-Postalytics-921367d4dfe8406a9fb99c95c861a853

Hi @vunguyenhung, I did several tests and didn't understand what happened, but I think it was just with a specific campaign.
