### ISSUE TITLE
[FEATURE] Recognize `require` statements inside `new` statements

### ISSUE THREAD

**Issue by bratchenko** [PipedreamHQ/pipedream#877]
This code works inside an action:

```
const jsforce = require('jfsforce')
var conn = new jsforce.Connection({...})
```

and this does not work:

```
var conn = new require('jsforce').Connection({...})
```

Allowing the 2nd option would read to simpler and more readable code.

**Comment by dylburger** [comment]
@bratchenko can you try

```javascript
var conn = new (require('jsforce').Connection({...}))()
```

and see if that works? We use [a parser](https://github.com/acornjs/acorn) that should support inline requires (see [this workflow](https://pipedream.com/@dylan/inline-require-p_KwC1MqA/edit), for example).

**Comment by dylburger** [comment]
This appears to be working in other cases we've tested. If adding the parens still fails to work, let me know and we can investigate further.
