### ISSUE TITLE
Productive.io

### ISSUE THREAD

**Issue by StefSJones** [PipedreamHQ/pipedream#8776]
**Name of app / service**
Productive
https://productive.io/
https://app.productive.io/

**Link to developer documentation**
https://developer.productive.io/integrations.html#integrations

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, lack of support and integration ability. I am also working on a workaround using webhooks as well as creating my own API integration. 

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
My goal is to integrate Producitve.io with almost any Project Management platform. Ideally, I would be able to set up an API Post, Get to be able to trigger an event every time a new task is created and assigned to me, that would pull that task into the appropriate database/project in Notion

**Comment by malexanderlim** [comment]
Hi @StefSJones , the base integration is now in place! Feel free to get started with using the integration, and we will build out some triggers and actions shortly.
https://pipedream.com/apps/productive-io

**Comment by malexanderlim** [comment]
Feel free to follow along at https://github.com/PipedreamHQ/pipedream/issues/8792 for updates, and if there are any specific triggers and actions you are looking for please comment on the ticket.
