### ISSUE TITLE
[BUG] Cmd+D is both "Select next" in editor and "Deploy"

### ISSUE THREAD

**Issue by bratchenko** [PipedreamHQ/pipedream#878]
Cmd+D is a hotkey in the editor to "select next entrance of the currently selected text". It is widely used (at least by me :). Coincidentally, it is also a hotkey for "Deploy". It is annoying, especially since Cmd+R is not a hotkey for "Run".

Solution: separate editor hotkeys and global workflow hotkeys somehow.

**Comment by dylburger** [comment]
@bratchenko we allow you to modify any of the workflow hotkeys by visiting the **Help and Docs** section in the left nav and selecting the **Shortcuts** option:

<img width="196" alt="Screen Shot 2021-02-01 at 1 41 14 PM" src="https://user-images.githubusercontent.com/242668/106521790-a3711780-6493-11eb-8c8a-a26b47b26583.png">

click into a specific shortcut and press the new, desired shortcut to change it:

![2021-02-01 13 45 20](https://user-images.githubusercontent.com/242668/106521918-cef40200-6493-11eb-918e-001cfc4ce543.gif)

That should allow you to use the editor shortcut for its intended function. Let me know if that helps.
