### ISSUE TITLE
[BUG] Deploying workflow expands everything in all steps

### ISSUE THREAD

**Issue by bratchenko** [PipedreamHQ/pipedream#879]
When I click "Deploy" and a workflow deploys, all sections in all of my steps get expanded. If workflow is not very small (say, 4-5 steps), this leads to browser being noticeably slow because of many editors opened simultaneously. 

I have to fold all the editors back to make the browser run the page faster.

There is no need to expand all workflow steps on deploy.

**Comment by dylburger** [comment]
@bratchenko thank you for the report. We're tracking in #809. Please follow that ticket, if you don't mind.
