### ISSUE TITLE
[Components] originality_ai

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8795]
# originality_ai
## URLs
- https://docs.originality.ai/api-v1-0-reference

#### Prompt
Scans a string for AI. Ensure that the string provided in `content` is encoded as UTF-8. Please have a dropdown for `aiModelVersion` that the user can select from. Please have two selections for `storeScan` - true and false.
#### URLs
- https://docs.originality.ai/api-v1-0-reference/scan/ai-scan
#### Prompt
Scans a webpage for AI generated content. 
#### URLs
- https://docs.originality.ai/api-v1-0-reference/scan/ai-url-scan
#### Prompt
Scans a string for plagiarism as well as readability. Ensure that the string provided in `content` is encoded as UTF-8. Please have two selections for `storeScan` - true and false.
#### URLs
- https://docs.originality.ai/api-v1-0-reference/scan/plagiarism-readability-scan

**Comment by danhsiung** [comment]
@luancazarine Can you please review this PR?
