### ISSUE TITLE
MemGPT

### ISSUE THREAD

**Issue by QuicksilverSlick** [PipedreamHQ/pipedream#8798]
MemGPT

https://github.com/cpacker/MemGPT

I am unable to utilize this functionality with my Pipedream workflows

I am looking for the core functionality and integration with Pipedream DB stores

**Comment by sergio-eliot-rodriguez** [comment]
Hi  @QuicksilverSlick 

Thanks for the request, and for being a Pipedream user.

That software you linking to is a Python package, not an application Pipedream would need to integrate with.

For now, we are not applications where Pipedream is required to provide a run environment, whereas we would expect a host provider runs the app and Pipedream connects to it.

However, I'm tagging here @malexanderlim to take note, he is Product manager at Pipedream as the team is looking on how it could be possible to offer non-REST API based applications within the Pipedream marketplace.

**Comment by QuicksilverSlick** [comment]
Thank you @sergio-eliot-rodriguez
