### ISSUE TITLE
[ACTION] BigQuery Select

### ISSUE THREAD

**Issue by rsisson** [PipedreamHQ/pipedream#8802]
Google Cloud BigQuery

There is already a trigger to poll BigQuery for new rows, but I need to be able to pass params pulled from a DataStore into the query. Can we get a simplified version of the existing trigger that I can use as an action please?

**Comment by malexanderlim** [comment]
Hi @rsisson , this is integrated in the Google Cloud app:
https://pipedream.com/apps/google-cloud/actions/run-query

Let me know if this works for your use case!

**Comment by rsisson** [comment]
I found a workaround in the meantime, but this seems like exactly what I was looking for. Thank you!
