### ISSUE TITLE
Smart Recruiters

### ISSUE THREAD

**Issue by AC-Each** [PipedreamHQ/pipedream#8810]
**Name of app**
Smart Recruiters

[**Link to developer documentation**](https://developers.smartrecruiters.com/docs)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, it slows the process of building workflow and the integration process in total. As of now, I am using the workaround of writing down manual python scripts to achieve the desired outcome

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Webhook triggers and their activation would be the first and foremost thing I would like to see. Also, then the possibility of using the applications' Candidate, Job & Configuration API.

**Comment by sergio-eliot-rodriguez** [comment]
Duplicated request #5580

**Comment by sergio-eliot-rodriguez** [comment]
Btw @AC-Each  , Enrico, would you mind reaching out to SmartRecruiters support and express interest in an integration between SmartRecruiters and Pipedream? Sometimes app developers will expedite a partnership with us if they hear out from the user base directly. Thanks.

For now they didn't grant Pipedream acecss to their API:

> I hope this email finds you well. We appreciate the time and effort you invested in applying for membership in the SmartRecruiters Marketplace. After careful review of your application, we regret to inform you that we are unable to accept your application at this time.
