### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by cyrow** [PipedreamHQ/pipedream#8820]
**Mongodb**

**[Link to developer documentation](https://www.mongodb.com/solutions/developer-data-platform)**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
Hi there, have you see our existing integration with MongoDB?
https://pipedream.com/apps/mongodb

Let us know if you have any questions or need any help getting started!
