### ISSUE TITLE
kaleido

### ISSUE THREAD

**Issue by cyrow** [PipedreamHQ/pipedream#8822]
**kaleido**

**[Link to developer documentation](https://docs.kaleido.io/)**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @cyrow thanks for the request
happy to let you know Kaleido has been integrated https://pipedream.com/apps/kaleido?via=go
Check it out and feel free to let us know any feedback!
Thanks
Sergio
