### ISSUE TITLE
[APP] Ometria

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#883]
http://docs.ometria.com/apis/data_api_v2/

**Comment by todsac** [comment]
Workflow - https://pipedream.com/@tod/ometria-api-integration-example-p_ljCb7Qk/
Marketplace -[ Ometria API Integrations](https://pipedream.com/apps/ometria)

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pd, integrations@pd
