### ISSUE TITLE
[ACTION] [PODIO] Update Create Item, Add Upload Action

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#8833]
Hello how are you ?
Could you include the `file_ids` field in the create item action?
Thanks !
https://developers.podio.com/doc/items/add-new-item-22362

**Comment by malexanderlim** [comment]
Please also create the upload_from_url action
Thanks

https://github.com/podio/podio-rb/blob/6c77c92792c3ae79d487a997909122e90e544bf1/lib/podio/models/file_attachment.rb#L62

**Comment by marcelocecin** [comment]
hello thanks a lot !
is possible to add this two operations ?
https://developers.podio.com/doc/files/upload-file-1004361
https://developers.podio.com/doc/files/attach-file-22518
thanks !

**Comment by malexanderlim** [comment]
Hi @marcelocecin , can you please open up a new request for this? Thanks!
