### ISSUE TITLE
[ACTION] [PODIO] upload_from_url

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#8834]
Hello how are you ?
Please consider including the `upload_from_url` action
Thanks

https://github.com/podio/podio-rb/blob/6c77c92792c3ae79d487a997909122e90e544bf1/lib/podio/models/file_attachment.rb#L62

**Comment by malexanderlim** [comment]
Hi @marcelocecin , I've combined your requests into a single ticket here.
https://github.com/PipedreamHQ/pipedream/issues/8834

**Comment by marcelocecin** [comment]
hello thanks a lot !
is possible to add this operation too ?
https://developers.podio.com/doc/files/attach-file-22518
