### ISSUE TITLE
[Components] manychat

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8852]
# manychat
## URLs
- https://api.manychat.com/swagger
#### Prompt
Emits new event when a user has completed a purchase order. No props needed.
#### Prompt
Emits new event when a selected custom field on a user profile is added or updated. The custom field name is required prop.
#### URLs
- https://api.manychat.com/swagger#/Page/2bc43834222da265c4c41fbd129d1392
#### Prompt
Emits new event when a user subscribes to your page. No props needed.
#### Prompt
Adds a specific tag to a user specified by their user ID. Required props are 'tag' and 'user-id'. This action is essential in categorize and filter users based on the business-specific parameters.
#### URLs
- https://api.manychat.com/swagger#/Subscriber/ee797ad59ec8545bed43add11390b165
#### Prompt
Delivers a dynamic message to a particular user specified by their user ID. The 'message' and 'user-id' are the required props. This action caters to personalized user messaging based on dynamically acquired data.
#### URLs
- https://api.manychat.com/swagger#/Sending/637120a69445b2892f725cbfeaf347ca
#### Prompt
Locates a user based on a particular custom field's value. 'custom-field' and 'value' are the required props for this action. This action serves in search operations where users need to be located based on any attribute or data point beyond their ID or name.
#### URLs
- https://api.manychat.com/swagger#/Page/2bc43834222da265c4c41fbd129d1392
- https://api.manychat.com/swagger#/Subscriber/9fc380dcb49bb134b9405d4269896f56

**Comment by luancazarine** [comment]
@vunguyenhung FYI.
I didn't develop the **new-order-paid-instant** source because it doesn't exists in the API doc and didn't develop the **new-subscriber-instant** source because the API doc doesn't have a waypoint to list all subscribers, there's only filtering by system fields values, custom fields values or user ref.
