### ISSUE TITLE
[Components] echtpost-postcards

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8853]
# echtpost_postcards
## URLs
- https://hilfe.echtpost.de/article/20/postkartenversand-uber-api-programmierschnittstelle
#### Prompt
Enables user to schedule the creation and sending of a postcard. Requires the 'design', 'message', and 'recipient' props. Optional props include 'scheduled-date'.
#### Prompt
Allows the user to create a new contact within the app. Requires the 'name' and 'address' props. Optional props might include 'email', 'phone-number'.

**Comment by GTFalcao** [comment]
"Create Contact" is working and validated, but "Create Card" returns an error of invalid contact data even though the documentation is being followed. I've submitted a message to Echtpost's support about this.

**Comment by GTFalcao** [comment]
@vunguyenhung Echtpost's support provided our account with credits equivalent to 1 postcard, but it can be cancelled after being scheduled so that the credits are returned.
