### ISSUE TITLE
[Components] eden_ai

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8856]
# eden_ai
## URLs
- https://docs.edenai.co/reference/start-your-ai-journey-with-edenai

#### Prompt
This action accepts a text from the user, and returns the text as audio. Please include the full list of providers as a multi-select dropdown list. Please include all languages as a prop as well. 
#### URLs
- https://docs.edenai.co/reference/audio_text_to_speech_create

**Comment by GTFalcao** [comment]
I believe this is a duplicate of #7993
