### ISSUE TITLE
[FEATURE] RSS trigger should support JSON Feed URLs

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#887]
https://www.jsonfeed.org/

**Comment by vicky239-arch** [comment]
https://nocodeapi.com/medium-api/

**Comment by todsac** [comment]
Is the request to get a Medium RSS feed into a Pipedream workflow?  If so, does the RSS trigger not work sufficiently for Medium?

**Comment by dylburger** [comment]
This is the test feed from the original user: https://scripts.thejeshgn.com/feeds/river?channel=public_jobs

**Comment by dannyroosevelt** [comment]
This is ready for release!
