### ISSUE TITLE
[SOURCE] Discord: user joins guild / server

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#889]

**Comment by dylburger** [comment]
Note for implementor: `pending` will be false and `joined_at` should be set at https://discord.com/developers/docs/resources/guild#guild-member-object

**Comment by luancazarine** [comment]
@dylburger I saw that there are two discord apps, which one should I use for this source?

**Comment by dylburger** [comment]
Can you actually coordinate with @dannyroosevelt ? We're making some changes to our Discord apps and I want to make sure he gives you the correct answer.

**Comment by dannyroosevelt** [comment]
Actually I see this source: https://github.com/PipedreamHQ/pipedream/blob/master/components/discord_bot/sources/new-guild-member/new-guild-member.mjs

But it isn't published:
https://pipedream.com/apps/discord-bot#popular-discord-bot-triggers

I'm looking into this.

**Comment by dannyroosevelt** [comment]
Confirming this is done: https://pipedream.com/apps/discord-bot/triggers/new-guild-member
