### ISSUE TITLE
[Components] adobe_sign

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8894]
# adobe_sign
## URLs
- https://secure.na1.adobesign.com/public/docs/restapi/v6#!/
#### Prompt
Emits new event every time a specified event occurs. Required props: event type.
#### Prompt
Creates a new agreement and sends it via email. Required props: email addresses of the recipients, the agreement object containing the details about the agreement.
#### Prompt
Retrieves current status of an agreement. Required prop: agreement id. This allows user to check and monitor the agreement status.
#### Prompt
Updates an agreement status. Required props: agreement id, the new status to be updated. This allows user to change the status of the agreement.

**Comment by dannyroosevelt** [comment]
dupe
