### ISSUE TITLE
[APP] Mailgun

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#891]
**Name of app / service**
Mailgun

**Link to developer documentation**
https://documentation.mailgun.com/en/latest/api-intro.html

**Comment by todsac** [comment]
Nacho - can you clarify what is missing from the current Mailgun integration? https://pipedream.com/apps/mailgun

**Comment by nachocab** [comment]
Ah, sorry. I wanted to create a Mailgun workflow and I typed "mailgun" in the trigger step instead of a regular step. That's why it wasn't showing up 😅
