### ISSUE TITLE
[SOURCE] Github - Wiki updated

### ISSUE THREAD

**Issue by Juansecu** [PipedreamHQ/pipedream#8939]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Add a trigger for wiki updates on GitHub for allowing integrations with Discord, since Discord webhooks don't send messages when wiki pages are created, removed or updated on GitHub repositories.

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://docs.github.com/en/webhooks/webhook-events-and-payloads#gollum

**Comment by malexanderlim** [comment]
Hi @Juansecu , this source is available using **New Webhook Event - Instant**.
<img width="977" alt="Screenshot 2024-02-07 at 5 10 37 PM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/8f26186c-477f-4491-8a36-06684652a88a">

**Comment by Juansecu** [comment]
> Hi @Juansecu , this source is available using **New Webhook Event - Instant**.
> <img width="977" alt="Screenshot 2024-02-07 at 5 10 37 PM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/8f26186c-477f-4491-8a36-06684652a88a">
> 
> 
> 

Oh, okay. Thank you so much for your response! I will check it out!

**Comment by Juansecu** [comment]
@malexanderlim Is that source listed to only paid plans? Because I'm using a free account, and that trigger is not being listed for me.

**Comment by malexanderlim** [comment]
@Juansecu , please let me know if you're having issues locating this! I saw a message come through but it is no longer there.

**Comment by Juansecu** [comment]
@malexanderlim Sorry for ghost-mentioning you. I asked you for help for locating it, but actually, I was able to find it. Thank  you so much for your help!
