### ISSUE TITLE
[BUG] Flutterwave app logo is not display in the workflow builder add step dialog.

### ISSUE THREAD

**Issue by sergio-eliot-rodriguez** [PipedreamHQ/pipedream#8959]
**Describe the bug**
When you add an step to the workflow builder and search for the Flutterwave app, its logo isn't displayed.

**To Reproduce**
1. Create a new builder
2. Click on '+' to add a new step to the builder
3. Type 'Flutterwave' to search for the Flutterwave app
4. The Flutterwave app is shown, but its displayed without icon (it shows a gray square as a placeholder icon=

**Expected behavior**
The Flutterwave icon is displayed next to the app name
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/81c4fc1a-6690-4783-b707-950f934cc822)

**Screenshots**
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/0b6427ef-7f04-4ea1-b1c5-177a6c7884d9)

**Additional context**
Reported by Leo

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by sergio-eliot-rodriguez** [comment]
LGTM!! Ty!
