### ISSUE TITLE
[ACTION] Create Application Domain (ServerAvatar)

### ISSUE THREAD

**Issue by cuongtqtran** [PipedreamHQ/pipedream#896]
**Is there a specific app this action is for?**
Serveravatar

**Please provide a link to the relevant API docs for the specific service / operation.**
https://serveravatar.com/api-docs/endpoint/application-domain/create.html

**Comment by feyzullah** [comment]
Hi @alysonturing can you please link your PR?

**Comment by alysonturing** [comment]
Sure, I'm sorry...

**Comment by dannyroosevelt** [comment]
This is ready for release!
