### ISSUE TITLE
TONEDEN [APP]

### ISSUE THREAD

**Issue by sdotsamuel** [PipedreamHQ/pipedream#8968]
**Name of app / service**
Tone Den

**Link to developer documentation**
https://developers.toneden.io/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It's a service I use to promote my artists.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
They have a bunch of triggers on Zapier.

**Comment by sergio-eliot-rodriguez** [comment]
Submitted for approval.
OAuth might need to get certified by Toneden to be available across all users.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @sdotsamuel !

Happy to announce that ToneDen is now available for integration 
https://pipedream.com/apps/toneden

We are tracking ToneDen components at #9493, if you'd like to follow for actions and triggers progress.
