### ISSUE TITLE
[BUG] Failed to download file: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by KellyHarvell** [PipedreamHQ/pipedream#8970]
**Describe the bug**
Failed to download file: Response code 404 (Not Found)

**To Reproduce**
Running Notion Voice Notes with file from my dropbox account to run into my Notions Database

**Expected behavior**
Receive transcript of audio file

**Screenshots**
Here's the log...
11/14/2023, 6:29:29 PM
Checking that file is under 300mb...
11/14/2023, 6:29:29 PM
File size is approximately 5.8mb. 
11/14/2023, 6:29:29 PM
File is under the size limit. Continuing...
11/14/2023, 6:29:29 PM
Checking if the user set languages...
11/14/2023, 6:29:29 PM
User set transcript language to en.
11/14/2023, 6:29:29 PM
ACTIVE_HANDLE This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: FSReqCallback, Learn more: https://pipedream.com/docs/code/nodejs/async/)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] 119.0.6045.124

**Additional context**
Dropbox: PastorHarvell@gmail.com
Not sure what else you need?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
