### ISSUE TITLE
[APP] Streamlabs

### ISSUE THREAD

**Issue by evrooije** [PipedreamHQ/pipedream#899]
Streamlabs (https://streamlabs.com/)

https://dev.streamlabs.com/

I was successful getting the initial access token, but it did require me to manually craft the authorize endpoint URL to fetch the initial authorization code and feed that in my Node.js code to kick start it. In the end I might get it to work this way but it's quite cumbersome, and not reusable for anyone else of course :)

Initially a run Node.js code with e.g. axios connecting to https://streamlabs.com/api/v1.0/user should be a good start I guess?

**Comment by todsac** [comment]
I have submitted a streamlabs app for approval.  it is working in testing but will be working on the platform soon.

Example workflow - https://pipedream.com/@tod/streamlabs-integration-example-p_dDCn17n/
Marketplace - https://pipedream.com/apps/streamlabs

**Comment by evrooije** [comment]
Hi Tod, while you were super fast implementing this (thanks for that btw :-) it looks like it might still be in review over at Streamlabs? I've tried from time to time and get User not in whitelist. Can you see that it is still in review? If so, I might hop in their Discord and give them a little nudge ;-)

**Comment by todsac** [comment]
Thanks for the bump.  I reached out again today as they have been unresponsive in their approval process.

**Comment by todsac** [comment]
This app has been approved by Streamlabs.

**Comment by evrooije** [comment]
Thanks Tod, I just connected, it works like a charm!
