### ISSUE TITLE
[FEATURE] I want a way to collapse all sections of a step, or collapse all sections of all steps, when I'm editing a workflow

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#90]

**Comment by siraj-samsudeen** [comment]
any progress on this?

**Comment by dylburger** [comment]
@siraj-samsudeen not yet, but we're working on a new workflow editor. This will change the way steps are edited and should make this specific experience cleaner. We'll share updates on that as soon as it's ready.

**Comment by dylburger** [comment]
This should be fixed in the newest version of the v2 workflow builder! You can expand all sections of a single step, of all steps, pin specific sections (e.g. just the code for a specific step), etc. 

<img width="254" alt="Screen Shot 2022-03-29 at 11 48 09 AM" src="https://user-images.githubusercontent.com/242668/160683591-b68d1b71-1897-4813-9654-f574faf80c99.png">

<img width="226" alt="Screen Shot 2022-03-29 at 11 48 14 AM" src="https://user-images.githubusercontent.com/242668/160683614-4b818b34-41dd-4bb6-8e41-815eaf9a6fa9.png">

<img width="266" alt="Screen Shot 2022-03-29 at 11 49 24 AM" src="https://user-images.githubusercontent.com/242668/160683681-90a93321-4f5d-402b-8128-142bd494ae3e.png">

Let us know if you have any other feedback on this.
