### ISSUE TITLE
[BUG] whatsapp business integration just erroring

### ISSUE THREAD

**Issue by Clausinho** [PipedreamHQ/pipedream#9004]
**Describe the bug**
When trying to use the list_message_templates function, i get following error code:

> Error - Request failed with status code 400
> {"error":{"message":"(#100) Tried accessing nonexisting field (message_templates) on node type (Business)","type":"OAuthException","code":100,"fbtrace_id":"AZwsqIu9s-AdksGdQXIH5hs"}}

the others fail with similar error codes

**To Reproduce**
Just try out any of the whatsapp business api functions
**Expected behavior**
Atleast the some templates appearing or a test if I set up the account correctly

**Additional context**
i think the whatsapp integration is tracked in #2896

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
