### ISSUE TITLE
[APP]

### ISSUE THREAD

**Issue by mdscaff** [PipedreamHQ/pipedream#901]
Any plans to support 10000ft.com API?

**Comment by todsac** [comment]
Consider it done.  We don't have a paid account so would appreciate if you can confirm the integration is working as expected.  Also, this identified a bug where a step name cannot start with a number but we are working on fixing that asap.

Example workflow - https://pipedream.com/@tod/10-000ft-api-integration-example-p_pWCYNvZ/
Marketplace - [10000ft API Integrations](https://pipedream.com/apps/10000ft)

**Comment by dylburger** [comment]
@mdscaff did you have a chance to test this integration? We just wanted to make sure it worked for you.

**Comment by mdscaff** [comment]
Yes, I have not exhausted all the possible scenarios but so far it seems to be working. Thanks!

**Comment by dylburger** [comment]
Great thanks @mdscaff
