### ISSUE TITLE
[APP] Microsoft Flow

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#903]
**Name of app / service**

Microsoft Flow: https://flow.microsoft.com/en-us/

**Link to developer documentation**

Apparently https://docs.microsoft.com/en-us/powerapps/developer/data-platform/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

As per #146, this is blocking workflow creation.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

See #146

**Comment by sergio-eliot-rodriguez** [comment]
Finally submitted

**Comment by sergio-eliot-rodriguez** [comment]
Microsoft Flow was rebranded as Power Automated,

live now

https://pipedream.com/apps/power-automate
