### ISSUE TITLE
[APP] Send/Recieve email

### ISSUE THREAD

**Issue by Pandapip1** [PipedreamHQ/pipedream#904]
## Feature Request 1: Send email using workflow email address
**Description:** There is already the `email` trigger - it seems a logical conclusion that there should be an `email` step that allows you to send an email from that email address. This could be useful e.g. for confirmations that a trigger has run, or for sending emails to people on a contact list whenever a new item in an RSS feed is posted.

**Alternatives I have considered:** A `reply` or `reply_all` step that only works with the `email` trigger that replies to the email that the workflow was sent, and a `forward` step that forwards the email the workflow was sent.
## Feature Request 2: Send and Receive email using IMAP/SMTP
**Description:** A new workflow trigger and a new workflow step that allow the workflow to receive and send emails, respectively, using IMAP and SMTP.

**Comment by dylburger** [comment]
@Pandapip1 for this use case, you'll need to send email from your own domain using one of the email services we integrate with (Sendgrid, Mailgun, etc.). Have you worked with any of those providers in the past?

As a service, we cannot allow the ability for any user to send emails from `pipedream.net` domains. Email reputation is tied to a domain, and closely monitored by a variety of mail providers / spam services. If a single bad actor were to deliver unwanted mail to recipients, it would affect the reputation of the entire `pipedream.net` domain, and the domain would be blocked, eliminating the ability for good actors like you to use the service.

Re: your second request, we're tracking an IMAP source at #609 if you'd like to follow that.

**Comment by dylburger** [comment]
Closing this ticket, as we're tracking request 2 at #609 .
