### ISSUE TITLE
Evernote

### ISSUE THREAD

**Issue by kachdi** [PipedreamHQ/pipedream#9046]
**Name of app / service**
Evernote

**Link to developer documentation**
https://dev.evernote.com

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No I do not have a workaround

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
CreateNote in a designated Notebook

**Comment by sergio-eliot-rodriguez** [comment]
Hi @kachdi 

Thanks for the request, looks like we have been blocked on Evernote for a while now, and we are tracking Evernote at #416, feel free to follow there if you'd like.

Thanks!

**Comment by sergio-eliot-rodriguez** [comment]
A [base integration](https://pipedream.com/apps/evernote?via=go) for Evernote has been released, feel free to check it out.
