### ISSUE TITLE
LMNT

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9079]
### App
LMNT
https://docs.lmnt.com/introduction

### Actions
Synthesizing speech, creating voices. I am a developer with LMNT and I would like to contribute a component. Thank you!

**Comment by kaikato** [comment]
Thank you!

**Comment by malexanderlim** [comment]
Hi @kaikato , apologies but I missed this ticket - component development for LMNT has been prioritized and is in progress already here:
https://github.com/PipedreamHQ/pipedream/issues/9121

Please let me know if we're missing anything, and appreciate your willingness to develop the component on your own. If you'd like to develop the next components for LMNT, that would be great!

**Comment by kaikato** [comment]
@malexanderlim Ah, thank you so much for working on this! Will keep an eye on it and will certainly develop the next components. Thank you!
