### ISSUE TITLE
Surface per-step timing in workflow execution details

### ISSUE THREAD

**Issue by frito-ray** [PipedreamHQ/pipedream#9092]
When fine-tuning or triaging execution timeouts, it'd be very helpful to have per-step timing data instead of just total duration/compute time.

I have several workflows set on a daily cron job. Both are very simple flows: simple query of a tiny bit of data from the db, post to slack.  The two workflows frequently timeout during the scheduled execution, but always complete successfully upon retry (10-12sec). **I can't tell if its the python/supabase code or the slack component that's causing the issues.**

Example workflows:
https://pipedream.com/@jsg/projects/proj_JPszAj/report_config_errors_to_slack-p_ZJCeVvo/inspect
https://pipedream.com/@jsg/projects/proj_JPszAj/p_6lCYeoz/inspect/2YdAhdi5RszxL7ix3HK0WqrH7kM

**Is your feature request related to a problem? Please describe.**
Triaging inconsistent execution durations between runs. Is the difference due to cold start? A specific step?

**Describe the solution you'd like**
An expansion of the workflow execution details to include per-step timings
![err](https://github.com/PipedreamHQ/pipedream/assets/13035129/8c7fd607-9c6c-4da4-8475-a8357e5b9c03)

**Do you have a workaround?**
Yes. Crank up the execution timeout.

**Comparable features in other tools?**
A waterfall timing chart a la Chrome dev tools would be [rad](https://medium.com/codes-n-coffee/how-waterfall-chrome-dev-tool-helps-to-understand-the-nature-of-a-website-bc4c9e5ed595)

**Additional context**
None

**Comment by dylburger** [comment]
Thanks for reaching out @frito-ray . We should display partial observability (logs, step exports, and step-level timing) when your workflow encounters a timeout. It looks like your workflow timed out on the `report_config_errors_to_slack` step. If you scroll down to that step and select the **Details** tab, do you see the step-level timing?

<img width="439" alt="Screenshot 2023-11-25 at 10 33 19 AM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/ac1050b3-8677-4ee8-93e0-3066bd83dc14">

Any steps that ran prior to that step should also have the step-level timing there.

Let me know if you don't see that and we can look into your specific workflow more.

**Comment by frito-ray** [comment]
This already exists in the details tab of each step post-execution

**Comment by frito-ray** [comment]
Thanks Dylan, that is exactly what I was looking for! (I closed the feature
request)
