### ISSUE TITLE
[BUG] Notion - Create Page from Database error: body failed validation: body.children.length should be ≤ `100`, instead was `131`.

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9094]
**Describe the bug**
When I used the page content as below, the Notion action failed with the error
[page-content.md](https://github.com/PipedreamHQ/pipedream/files/13469117/page-content.md)
```
body failed validation: body.children.length should be ≤ `100`, instead was `131`.
```
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/54c00958-420d-4051-a771-1b12df2bcdd0)

**Additional context**
Leo's QA workflow

**Comment by GTFalcao** [comment]
@vunguyenhung this appears to be a static limit when creating the page - should we trim the amount of blocks to a max of 100, 
 avoiding the error, and adjust the prop description to inform the user of this limit?
