### ISSUE TITLE
[Components] printnode

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9113]
# printnode
## URLs
- https://www.printnode.com/en/docs/api/curl#introduction
#### Prompt
Emit new event when a new printnode event is created. User needs to configure the props required and optional props.
#### Prompt
Transmits a printing task to a specifically defined printer. Required props include both the 'printer id' and the 'document content' to be printed.
#### Prompt
Retrieves data about a specific printer. The single required prop for this action is the 'printer id'.
#### Prompt
Returns a list of all print jobs that have been submitted. No props are required for this action, but optional props might include 'date range' for the jobs one wants to list.

**Comment by GTFalcao** [comment]
I'm not sure how QA will go on this, as this app may need actual printers to be validated completely - I validated the request structures, but some requests cannot be completed due to not having a printer.
