### ISSUE TITLE
[APP]  AccuRanker

### ISSUE THREAD

**Issue by efeuve** [PipedreamHQ/pipedream#912]
Hey,

We use AccuRanker for SEO rank tracking and I was wondering if integrating is possible.
Here are the API docs: https://app.accuranker.com/app/api

The main use case is to get the current ranks for a specific set of KWs in a specific domain

**Comment by todsac** [comment]
Accuranker is integrated.  Please confirm and now [actions](https://docs.pipedream.com/workflows/steps/actions/) / triggers can be built out.

Example workflow - https://pipedream.com/@tod/accuranker-api-integration-example-p_vQCgboO/
Marketplace - [Accuranker API Integrations](https://pipedream.com/apps/accuranker).

**Comment by efeuve** [comment]
Thanks! I was mistakenly looking at the sources app instead of all apps. All good with AccuRanker!

Closing
