### ISSUE TITLE
[FEATURE] A clear list of services you either have paywalled and are choosing to paywall in the future

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#9133]
**Is your feature request related to a problem? Please describe.**
Please can you either publish a list or email users of services you are paywalling. It's annoying to suddenly find a workflow fails, then when you update it you find it's suddenly paywalled as a 'Premium' feature. I knew you had done that to LinkedIn but I was just testing a fixed bug and found Pinterest was no longer accessible.

**Describe the solution you'd like**
As above, either a clear list of planned paywalling, or an email sent to users of a services to say 'Hey we're not providing this for free anymore'

**Do you have a workaround?**
Not really, I'll just have to either write my own API's that do not use your credential system, or fire off a webhook to IFTTT and process paywalled services through their system.

**Comment by dannyroosevelt** [comment]
@NebularNerd thank you for the feedback. I hear and empathize with your frustration and surprise -- it sounds like you were caught in a particularly unfortunate scenario of making edits to an already running workflow right after Pinterest was updated to a premium app.

FYI the full list of apps that are currently categorized as premium is available [here](https://pipedream.com/docs/apps/#premium-apps), but as you noted that does not include future candidates.

I agree we should provide advance notice for this type of change moving forward, but we missed that here.

Again, thank you for your feedback, we really appreciate it.
