### ISSUE TITLE
[Components] circle

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9176]
# circle
## URLs
- https://api.circle.so
#### Prompt
Emit new event each time a new comment gets posted into the community. Please use async options to list community, list spaces, and list posts (optional).
#### URLs
- https://api.circle.so/#2e741fe6-8f1b-4a5c-b2fd-014ef5f93658
- https://api.circle.so/#ad5f356e-0038-4706-a30a-ed4a0fcd306a
- https://api.circle.so/#c2faf0c4-9903-4cdb-84c5-6a587e0f6c40
#### Prompt
Emit new event each time a new post gets published in the community. Please use async option to list communities and list spaces.
#### URLs
- https://api.circle.so/#98273257-cde7-44bc-bd45-5e0278d3acb0
- https://api.circle.so/#c2faf0c4-9903-4cdb-84c5-6a587e0f6c40
#### Prompt
Create a new post on your community. Please use async options for `community_id` and `space_id` and include all required and optional params.
#### URLs
- https://api.circle.so/#ffc804e8-02a8-48dc-a5c8-dc278f909fa4
- https://api.circle.so/#ad5f356e-0038-4706-a30a-ed4a0fcd306a
- https://api.circle.so/#c2faf0c4-9903-4cdb-84c5-6a587e0f6c40
#### Prompt
Creates a comment on a post. Please use async options for `community_id`, `space_id`, `post_id` and include all required and optional params.
#### URLs
- https://api.circle.so/#4cb2eea1-6832-4ffc-8614-078b88dee4e2
- https://api.circle.so/#ad5f356e-0038-4706-a30a-ed4a0fcd306a
- https://api.circle.so/#c2faf0c4-9903-4cdb-84c5-6a587e0f6c40
- https://api.circle.so/#98273257-cde7-44bc-bd45-5e0278d3acb0

**Comment by malexanderlim** [comment]
Thanks Luan. I've reached out to the Circle team to see if they can provision an account for us for testing/development purposes.

**Comment by malexanderlim** [comment]
This should now be unblocked!
