### ISSUE TITLE
[FEATURE] Update Clockify connection description

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9181]
**Is your feature request related to a problem? Please describe.**
On the Clockify connection modal description, the link https://clockify.me/user/settings leads to the home page instead of user setting page
![10 53 55 - 04 - 12 - 2023](https://github.com/PipedreamHQ/pipedream/assets/18277920/1b5be031-54a2-44a4-ab56-0c0d75ab34ea)

The correct link should be: https://app.clockify.me/user/settings

**Describe the solution you'd like**
Update the Clockify connection description to instruct the user how to get the API Key:
```
To get the API Key, access [Clockify User Setting Page](https://app.clockify.me/user/settings) > API
```

**Comment by malexanderlim** [comment]
Thanks for the clarifying language and link, Leo - this has been fixed!
