### ISSUE TITLE
[APP] Hey Gen

### ISSUE THREAD

**Issue by SHINONFT** [PipedreamHQ/pipedream#9182]
**Hey Gen**

**[Link to developer documentation](https://docs.heygen.com/docs)**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
@SHINONFT Thanks for the request.

This should appear soon in the Pipedream app store.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there
Happy to announce that
HeyGen has been integrated: https://pipedream.com/apps/heygen

Let us know if you see any issues!
