### ISSUE TITLE
[BUG] Trello - New Member on Card (Instant) source: `Board` prop always show empty options

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9185]
**Describe the bug**
When creating a new Trello - New Member on Card (Instant) source, the Board option shows empty options even when I have a board available in Trello
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/15e14f6c-6cfe-4985-8d5e-f4574093ad70)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/46315de2-a46e-4e42-b708-e58322311022)

Other source works fine
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/849e0382-78f6-4b8b-b6fc-abb300b417a2)

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1701550176580579

**Comment by GTFalcao** [comment]
Might also be fixed by #9189

**Comment by michelle0927** [comment]
I've tested and confirmed that the changes from #9189 fix this issue.
