### ISSUE TITLE
[Components] convoloai

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9190]
# convolo_ai
## URLs
- https://help.convolo.ai/speed-to-lead%E2%84%A2/5FYYJHDuGE8PkM1RbZTric/making-calls-through-an-api-request-/2nJSW45JEUyxetSDCY1d6u
#### Prompt
Emits new event when a call ends and gets logged. Primary prop is end of call trigger from Convolo Dashboard. There are no optional props.
#### Prompt
Initiates a phone call to a lead and establishes the connection with the first available agent. Props required: agent identifier, lead phone number.
#### Prompt
Incorporates a new contact to a Power Dialer project. Props required: contact details, Power Dialer project identifier.

**Comment by luancazarine** [comment]
Hi @vunguyenhung. FYI.
There's no Convolo API documentation, there's only one example which is the create call action.
I sent them an email but they didn't respond.
