### ISSUE TITLE
[FEATURE] WP Maps connection modal contains redundant API Key field

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9199]
**Is your feature request related to a problem? Please describe.**
The API Key field is redundant as the Client ID and Access Token is enough
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/1b5d50ff-9b5f-461c-8a76-21808af924b2)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/48e29b72-8cb3-48c8-8f1e-0bbcac5a6548)

**Describe the solution you'd like**
Remove the API Key field

**Comment by malexanderlim** [comment]
I've removed the API key field - thanks for flagging.
