### ISSUE TITLE
[FEATURE] Events should populate most-recent first on initial load

### ISSUE THREAD

**Issue by johnnypez** [PipedreamHQ/pipedream#92]
**Is your feature request related to a problem? Please describe.**
When my workflow loads, job history begins to load alongside it. However, it loads the oldest - least relevant - executions first and very slowly populates the history with more recent data.

**Describe the solution you'd like**
I'd like to see the history view begin by loading the most recent executions first.

**Additional context**

![image](https://user-images.githubusercontent.com/181485/79280009-3a3dfa80-7ea7-11ea-886c-d4908b2a0441.png)

**Comment by nachocab** [comment]
I've noticed the slow performance only happens when the workflow has multiple non-trivial step exports. One possible solution could be keeping track of a simplified list of previous runs (timestamp, duration, $end message) and only load the step exports of the workflow that is selected.

**Comment by johtso** [comment]
This would be a really great thing to get improved! It seems really odd to have events loading from oldest first.. I end up having to wait for 20 seconds for so before I can start looking at the most recent events.

It also seems to be doing expensive work, displaying the workflow steps for each event as it gets loaded to the list.. only to immediately display the next event it loads..

**Comment by dylburger** [comment]
This whole model has changed with [the new version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/). The list of events should load incredibly quickly, and the contents of the event data / step exports are fetched lazily when you select a specific event!
