### ISSUE TITLE
[APP] TickTick

### ISSUE THREAD

**Issue by EsdrubalMagano** [PipedreamHQ/pipedream#9203]
**Name of app / service**
TickTick

**Link to developer documentation**
https://developer.ticktick.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I see it in make.com and zappier, but would love to move it to pipedream.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Create to-do, etc

**Comment by malexanderlim** [comment]
Hi @EsdrubalMagano , TickTick is integrated on Pipedream:
https://pipedream.com/apps/ticktick

Can you share where you were searching for Ticktick and not finding it? We'd like to dig in to see why you might have had an issue finding the app.

**Comment by malexanderlim** [comment]
Hi @EsdrubalMagano , there are no triggers available for TickTick, hence why it is not surfaced when you are looking for triggers. If you select a trigger, and go to choose an action, you should find some pre-built components for TickTick:

![Screenshot 2023-12-05 at 1 44 55 PM](https://github.com/PipedreamHQ/pipedream/assets/42158621/24267142-8994-4b40-826e-fe56a8c4ba6f)

![Screenshot 2023-12-05 at 1 45 00 PM](https://github.com/PipedreamHQ/pipedream/assets/42158621/40818633-8b5f-4f0d-adf4-6410f6474b2e)

I'm going to close this issue for now, but please let me know if you are still having any issues here.
