### ISSUE TITLE
[BUG] Spotify New Track in Playlist can only fetch some (20) of the playlists?

### ISSUE THREAD

**Issue by dit7ya** [PipedreamHQ/pipedream#921]
**To Reproduce**
1. Go to https://pipedream.com/new
2. Click "Search for an app"
3. Type "Spotify" and select
4. Click on "New Track on Playlist"
5. Connect Spotify with an account with more than 20 playlists.
6. You can only see 20 of your playlists in the selection box.

**Expected behavior**
All the user playlists should appear.

**Desktop (please complete the following information):**
 - OS: Arco Linux
 - Browser: Firefox
 - Version: 85

** Additional Comments

I suspect this is due to a limit set to 20 in the associated code of the trigger.

**Comment by dylburger** [comment]
Hi @dit7ya , thanks for reporting, we'll address this ASAP!
