### ISSUE TITLE
photoshop

### ISSUE THREAD

**Issue by sjn001tvh** [PipedreamHQ/pipedream#9221]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Duplicated of https://github.com/PipedreamHQ/pipedream/issues/9222, closing
