### ISSUE TITLE
photoshop

### ISSUE THREAD

**Issue by sjn001tvh** [PipedreamHQ/pipedream#9222]
Adobe photoshop has an api

(https://blog.developer.adobe.com/how-to-work-with-the-adobe-photoshop-apis-8282568f7d30)

this has the ability to reduce the size of a photo image so that an OCR api can read it properly. 

I've tried resize-img, but it requires that the width and height are entered prior to creating the reduce file.  photoshop api has the ability to resize the photo and maintain aspect ratios.  This is important because receipts come in all different sizes, so the aspect ratio is critical.

Thanks,

Scott.

**Comment by malexanderlim** [comment]
The base integration is in place. Please follow along https://github.com/PipedreamHQ/pipedream/issues/12571 for component development.
