### ISSUE TITLE
 Get Backlinks One Per Domain with the Ahrefs API

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9229]
### App
 Get Backlinks One Per Domain with the Ahrefs API
https://pipedream.com/apps/google-sheets/integrations/ahrefs/get-backlinks-one-per-domain-with-ahrefs-api-on-new-row-added-shared-drive-instant-from-google-sheets-api-int_avsab3G

### Sources
New rows in Google spreadsheet

### Actions
Use ahrefs_get_backlinks_one_per_domain API to get backlinks for a list of domains  provided in Google spreadsheet and have the results added in the spreadsheet. The final goal is to have backlinks for each domain in the spreadsheet.

**Comment by sergio-eliot-rodriguez** [comment]
I don't think this is an app request, but a workflow using Google Sheets an Ahrefs apps, which are already integrated
