### ISSUE TITLE
chatgpt assistant api

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9238]
### App
chatgpt assistant api
https://platform.openai.com/docs/assistants/overview

### Sources
use an assistant to make notes from lecture, interview, etc.

### Actions
create a thread, create a message, one shot thread and message

**Comment by sergio-eliot-rodriguez** [comment]
The requested API sis already via existing Open AI integration https://pipedream.com/apps/openai

Many components already using Assistant API

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/bb52eef3-2256-45be-916e-d91e5b80f213)


Moved to Component development project

**Comment by malexanderlim** [comment]
As Sergio mentioned, Assistants API is already available with all the aforementioned source/action requests already implemented.
