### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9240]
### App
Patreon

### Summary:
Unable to connect, although other Patreon Interactions (New Member Created) work fine. We are stuck on the message "Action Required In Patreon, generate test events for this trigger"

### Details:
I cannot use the New Pledge Received Integration for Patreon. 

I have created an automation to track new Patreon members and their donation amounts in a Google Sheet. This works fine as long as  a user makes a donation WHILE becoming a new member, but Patreon now allows for Free Tier followers to be free members. People who make a donation after becoming a member end up skipped, so we would like to set it up with the New Pledge Received interaction instead. 

However despite my best efforts and many days and attempts the action just never connects properly. It is stuck telling us "waiting for events" and sees no test events. When sending test events via traditional webhook using the Patreon backend it is received by Pipedream, but the actual Patreon New Pledge action never connects.  

I would like to get this resolved as soon as possible, as it is the automation is very unreliable forcing me to keep checking and correcting manually. 

### Screenshots:

![Screenshot](https://storage.tally.so/private/PipedreamPatreon.PNG?id=8qNZbY&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhxTlpiWSIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcwMjI2ODg5OX0.EnciMmNb3v5BAlYpiwy3yhAt1fycAolDS7EOTuEgjQo&signature=e028fa2191249ae6a4947d8d6b2b86b01068923ed655a7ddf0d44bb565f86627)

**Comment by michelle0927** [comment]
@vunguyenhung Webhooks created through the API don't show up on the [webhooks page](https://www.patreon.com/portal/registration/register-webhooks), but they should still work. The "New Pledge Received" source should only emit events when a monetary pledge is made by a member. 
The only way I could find to test it without making an actual pledge was to use the webhooks page to create a webhook pointing to the source, and then send a "test event".

<img width="746" alt="Screenshot 2023-12-15 at 1 43 46 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/355a7f40-6431-435d-8993-4af8c21261ee">
