### ISSUE TITLE
[Components] urlbae

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9263]
# urlbae
## URLs
- https://urlbae.com/developers
#### Prompt
Generates a QR Code. The required prop is 'qr-content', which would be the desired content to be encoded in the QR code. The returned data will include a generated QR code.
#### Prompt
Returns a shortened URL. The required prop is 'url', being the URL that needs to be shortened. The output will be a shortened version of the input URL.

**Comment by lcaresia** [comment]
@sergioeliot2039 @malexanderlim I cant' find the app to this task. Can you tell me when it's ready to develop?

Thanks

**Comment by malexanderlim** [comment]
Hey @lcaresia , is this not showing up for you when you search for the app? I see this as `beta`:

https://github.com/PipedreamHQ/pipedream/blob/11723e0a24e83dae3f2a636fe2c6df7859ca8ee2/components/urlbae/urlbae.app.mjs#L4

https://pipedream.com/apps/urlbae

**Comment by lcaresia** [comment]
@malexanderlim Sorry, I make a wrong comment and forgot to delete, everything is ok.
