### ISSUE TITLE
[Components] microsoft-power-bi

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9267]
# microsoft-power-bi
## URLs
- https://learn.microsoft.com/en-us/rest/api/power-bi/
#### Prompt
Emit new event when a dataset refresh operation has completed.
#### URLs
- https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-refresh-history
#### Prompt
Emit new event when a dataset refresh operation has failed. 
#### URLs
- https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-refresh-history
#### Prompt
Add  rows from a support dataset table. The required props for this action are: 'datasetId', the unique identifier of the dataset and 'tableName', the name of the table you're updating.
#### URLs
- https://learn.microsoft.com/en-us/rest/api/power-bi/push-datasets/datasets-post-rows
#### Prompt
Trigger a refresh operation for a specified dataset. The required prop for this action is: 'datasetId', the unique identifier of the dataset you wish to refresh.
#### URLs
- https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/refresh-dataset
#### Prompt
Cancels a refresh operation for a specified dataset.
#### URLs
- https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/cancel-refresh

**Comment by GTFalcao** [comment]
Blocking this pending resolution of an issue with the app authentication
