### ISSUE TITLE
[Components] illumidesk

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9274]
# illumidesk
## URLs
- https://developers.illumidesk.com/reference/campuses_list
#### Prompt
Emit new event when new course activity is created. Required props: Course ID
#### Prompt
Emit new event when a new lesson for a specific course is created. Required props: Course ID
#### Prompt
Emit new event when a new member is added to a course. Required props: Course ID
#### Prompt
Allows the creation of a new course. Required props include course title; optional props include course description and course duration.
#### Prompt
Invites a user to a selected course. Required props are member's email address and course ID.
#### Prompt
List all the courses associated with a given campus. Required prop is the campus ID.

**Comment by michelle0927** [comment]
@vunguyenhung I added the `permission` prop, but also be aware that the free plan only allows you to invite 1 instructor.
