### ISSUE TITLE
Popupsmart

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9280]
### App
Popupsmart

### Summary:
Can't connect to Popupsmart

### Details:
I am hoping to connect my Notion page to Popupsmart in order to collect emails on my Notion page. I have successfully connected notion to Pipedream, but am getting an error while trying to connect Popupsmart. Please assist. 

### Screenshots:
No screenshots included

**Comment by DTCPortDev** [comment]
![error](https://github.com/PipedreamHQ/pipedream/assets/153852271/c10738f5-a0f1-4c53-9608-bbb5daccf154)
 here is a picture of my error message. Please advise

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
