### ISSUE TITLE
[TRIGGERS] New Zoho Cliq Triggers

### ISSUE THREAD

**Issue by zackrspv** [PipedreamHQ/pipedream#9296]
**App**
Zoho Cliq

**Triggers*
New Channel Message
New Direct message

*Context from user*

> **Zoho Cliq**
> 
> **[Link to developer documentation](https://www.zoho.com/cliq/help/restapi/v2/)**
> 
> **Lack of support prevents triggers for this workflow**
> 
> **On new channel message, and on new direct message would be great**

**Comment by zackrspv** [comment]
Cliq is implemented as an ACTION, but not a trigger.

It'd be great, as we are a rather larger company (over 160 employees) who
use our tech support request channel, to be able to do automations based on
when a message is received, be it channel or direct.

--Phillip
[image: photo]
*Phillip Rumple*

702.329.0334 | ***@***.***

https://marphil.us
Las Vegas, NV
<https://www.facebook.com/zackrspv>
<https://www.linkedin.com/in/philliprumple/> <https://marphil.us>
"Change your life today. Don't gamble on the future, act now, without
delay." - Simone de Beauvoir.
[image: App Green Footer Image] Please consider your environmental
responsibility. Before printing this e-mail message, ask yourself whether
you really need a hard copy.

Create your own email signature
<https://www.wisestamp.com/create-own-signature/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>
‌

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
Thanks for clarifying @zackrspv 

I have triaged your request accordingly.

If you like to contribute to building these, please feel free in doing so, as mentioned by Dylan, by following the [sources quickstart](https://pipedream.com/docs/components/quickstart/nodejs/sources/), or just wait a bit and the components development team will pick this up and build it as requested.

**Comment by sergio-eliot-rodriguez** [comment]
For component development team:

Apparently there are outgoing webhooks available https://www.zoho.com/cliq/help/platform/channel-webhooks.html
now deprecated in favor of [bot participation handler](https://www.zoho.com/cliq/help/platform/bot-participation-handler.html) which potentially could help for building the requested sources. I didn't check this thoughfully though

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/175864c0-fac3-4d6c-ac7c-6e9e75bc3c06)

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
