### ISSUE TITLE
[BUG] Helper Function for Convert Currency via exchangerate.host is not working

### ISSUE THREAD

**Issue by KarlBishop** [PipedreamHQ/pipedream#9308]
I'm trying to build a workflow using the [Convert Currency via exchangerate.host Helper Function](https://pipedream.com/apps/helper-functions/actions/convert-currency) but the step is returning a TypeError.

When I enter `FromCurrency`, `ToCurrency` and `Value` and click Test, I see output like this:

```
TypeError
Cannot read properties of undefined (reading 'GBP')

DETAILS
    at Object.run (file:///tmp/__pdg__/dist/code/d02456f16b72858eeffbdddd95c3f8b4d210ed110b387c3e16ad90c8b5e8fcc2/code/actions/convert-currency/convert-currency.mjs:25:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.executeComponent (/var/task/launch_worker.js:267:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:764:28)
```

The Inputs and Details tabs show the following data:
```
Inputs:
fromCurrency    EUR
toCurrency      GBP
value           100

Details:
Timestamp       15/12/2023, 16:14:17
Duration        276ms
Name            Convert Currency via exchangerate.host
Version         0.1.1
Source          https://github.com/PipedreamHQ/pipedream/tree/master/components/helper_functions/actions/convert-currency/convert-currency.mjs
```

My inputs seem to be the same format shown in the `convert` example under [exchangerate.host API endpoints](https://exchangerate.host/documentation#api_endpoints)... but I noticed in the quoted [Source file](https://github.com/PipedreamHQ/pipedream/blob/master/components/helper_functions/actions/convert-currency/convert-currency.mjs), the URL used is `https://api.exchangerate.host/latest` which is not listed as one of the available API endpoints.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
