### ISSUE TITLE
[BUG] Can not connect to Ecwid

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9310]
**Describe the bug**
I tried to connect to my new ecwid store but it failed
<img width="2032" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/8eeb0657-815f-4820-bd01-44b2e7ea8967">
<img width="712" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/e60dee57-157f-4582-806e-29f899642fb8">

**Additional context**
Raised by another user here: https://github.com/PipedreamHQ/pipedream/issues/9300
https://github.com/PipedreamHQ/pipedream/issues/9309

**Comment by BeachDoc** [comment]
Hi, I see that it has not been fixed yet. Am I the only user of this script? It’s getting urgent what can I do to speed thing up a bit?

**Comment by malexanderlim** [comment]
Hi @BeachDoc , our application has been disabled on the ecwid side. I reached out to their team today. If you could also request the Pipedream integration from your side, we've found that app developers typically respond more quickly when the request comes directly from the mutual customer.

**Comment by malexanderlim** [comment]
@BeachDoc , I've engaged the Ecwid team and we are going through a review process for our app to be able to be listed on the Ecwid marketplace, and get the production app live. Once complete, I will follow up.

**Comment by BeachDoc** [comment]
Thanks. It appears for the moment that the ecwid app is showing as not valid in the workflow fyi

**Comment by malexanderlim** [comment]
I've disabled the app temporarily while we are working to get the production app approved. Their team is engaged and we should be able to get this out shortly - sorry for the delay.

**Comment by malexanderlim** [comment]
Hi @BeachDoc , I've updated the ecwid app with new connection instructions and was able to test end-to-end with this working on my side. Please reconnect your account and let me know if you run into any issues.
