### ISSUE TITLE
[APP] Codacy

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9315]
**Name of app / service**
Codacy

**Link to developer documentation**
https://docs.codacy.com/codacy-api/using-the-codacy-api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Copy Issues that Codacy finds on GitHub repos over to GitHub. Integrate Codacy deadlines, Gates, Gate Poliys, coding standards, and quality goals, into GitHub projects.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there,

Codacy has been integrated -- https://pipedream.com/apps/codacy
