### ISSUE TITLE
[APP] Code Climate

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9318]
**Name of app / service**
Code Climate

**Link to developer documentation**
https://developer.codeclimate.com/#overview

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Trigger on Code Climate test reports. Send all project updates to Slack that the native Slack integration does, to use one less Slack app for the free plan, with a limited amount of apps. Copy Code Climate issues to GitHub. Add Code Climate badges to README.
Trigger on exclude pattern update.
Trigger on organization settings update.
Trigger on team member invite.
Trigger on Per-User Subscription update.
Trigger on Invoices update.
Trigger on Code Climate Permissions update.
Trigger on any other organization, team, member, user, or settings update.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there

Code Climate has been integrated -- https://pipedream.com/apps/code-climate

We are tracking components on https://github.com/PipedreamHQ/pipedream/issues/9350
