### ISSUE TITLE
Lnk.Bio

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9321]
### App
Lnk.Bio
https://app.swaggerhub.com/apis/lnkbio/Lnk.Bio/0.0.2

### Sources
N/A

### Actions
/lnk/add
/lnk/delete

**Comment by sergio-eliot-rodriguez** [comment]
**notes on outreach**
by form, copied michael@pd

**Comment by sergio-eliot-rodriguez** [comment]
This has been previously integrated https://pipedream.com/apps/lnk-bio
