### ISSUE TITLE
[APP] CodeMagic

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9322]
**Name of app / service**
CodeMagic

**Link to developer documentation**
https://docs.codemagic.io/rest-api/codemagic-rest-api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Trigger on app build. Trigger on app settings update. Trigger on app cache update. Trigger on codemagic.yaml update. Trigger on Environment variables update. Trigger on Webhooks update.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there

CodeMagic has been integrated -- https://pipedream.com/apps/codemagic
