### ISSUE TITLE
[APP] SonarCloud

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9323]
**Name of app / service**
SonarCloud

**Link to developer documentation**
https://sonarcloud.io/web_api?_gl=1*18mwhlm*_gcl_au*MzM1OTUxNjMwLjE3MDA1NTAwNzA.*_ga*ODAxMjYxMzc2LjE3MDA1NTAwNzA.*_ga_9JZ0GZ5TC6*MTcwMjY4ODA1MC4xNS4xLjE3MDI2ODg0NDQuOC4wLjA.

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Copy SonarCloud issues to GitHub. Trigger when background tasks fail. Trigger when changes happen in issues/hotspots assigned to user. Trigger on new Quality Gate status. Trigger when issues are resolved as false positive or won't fix. Trigger when new issues are assigned to user. Trigger on new issues. Add SonarCloud badges to README.md.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there,

Sonar Cloud has been integrated -- https://pipedream.com/apps/sonarcloud
