### ISSUE TITLE
Google Calendar - Create Event action: Add Color ID prop

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9327]
### App
Google Calendar

### Summary:
Google Calendar - Create Event action: Add Color ID prop following the API doc here: https://googleapis.dev/nodejs/googleapis/latest/calendar/interfaces/Schema$Event.html#colorId

### Screenshots:
No screenshots included

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by waregan** [comment]
Hi, i hope to see soon this prop added. Many thanks to all for your job
