### ISSUE TITLE
[COMPONENTS] New Tumblr Components

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9332]
### App
Tumblr
https://www.tumblr.com/docs/en/api/v2

### Sources
When Post is created in certain blogs

### Actions
Reblog, Post, Like, etc.

**Comment by sergio-eliot-rodriguez** [comment]
Tumblr is integrated -- https://pipedream.com/apps/tumblr, triaging in accord to requested components.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
