### ISSUE TITLE
[FEATURE] Aftership - Create Tracking: Add more props following the API docs

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9335]
**Is your feature request related to a problem? Please describe.**
Some of the props in aftership API documentation - create tracking does not have matching props in Pipedream action, such as:
- delivery_type
- pickup_location
- tracking_account_number
And many more...

**Describe the solution you'd like**
In Pipedream Aftership - Create Tracking, please add props for all params in the [Aftership - Create tracking API](https://www.aftership.com/docs/tracking/sxafu5cay1usl-create-a-tracking)

**Do you have a workaround?**
No

**Additional context**
Raised by a user via email

**Comment by GTFalcao** [comment]
Sorry @vunguyenhung , I had validated "Update" only before sharing its functionalities with "Create" since they use almost the same props. Also, thanks for the typo fix!
