### ISSUE TITLE
Jotform

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9336]
### App
Jotform

### Summary:
Enterprise Jotform accounts return 404

### Details:
It appears that when attempting to connect to an enterprise Jotform account, the API connection does not work. In my testing, I found that the url it uses https://${this.jotform.$auth.region}.jotform.com/ does not work for enterprise accounts. Rather, /api/ should be added at the end.

### Screenshots:
No screenshots included

**Comment by michelle0927** [comment]
Duplicate of #https://github.com/PipedreamHQ/pipedream/pull/10874
