### ISSUE TITLE
[BUG] Datastore - Can not delete datastores created before Datastore is out of beta

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9338]
**Describe the bug**
A user unable to delete specific Data Stores that were in existence before Datastore is out of brta. To summarize:

- Creating a new data store and deleting it right after works fine
- Deleting an existing data store created before the beta does not work from the UI. The dialog closes, no error is shown, but the data store is still there.
- It does not seem to matter whether the data store has data, the user tried removing all data manually and then deleting the store but this also doesn't work.

**Expected behavior**
The user should be able to delete their data store

**Additional context**

Raised by users via email. Front Conversation ID: cnv_lyg8atj

The specific stores that the user trying to delete have the following IDs: ds_L9u0Qo, ds_L9u0lZ, ds_v9undL, ds_beudzl, ds_X3uQrY

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by dannyroosevelt** [comment]
@vunguyenhung we just shipped a fix for this -- are you able to get back to the customer and have them try again?
