### ISSUE TITLE
[APP]pCloud

### ISSUE THREAD

**Issue by cuongtqtran** [PipedreamHQ/pipedream#934]
**Name of app / service**
pCloud
**Link to developer documentation**
https://docs.pcloud.com/methods/oauth_2.0/authorize.html
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
https://docs.pcloud.com/methods/file/uploadfile.html

**Comment by todsac** [comment]
@cuongtqtran - i integrated pCloud.  Are you comfortable adding the action you need?

Example workflow - https://pipedream.com/@tod/pcloud-api-integration-example-p_JZCy1wQ/
Marketplace - [pCloud API Integrations](https://pipedream.com/apps/pcloud)

**Comment by cuongtqtran** [comment]
> @cuongtqtran - i integrated pCloud. Are you comfortable adding the action you need?
> 
> Example workflow - https://pipedream.com/@tod/pcloud-api-integration-example-p_JZCy1wQ/
> Marketplace - [pCloud API Integrations](https://pipedream.com/apps/pcloud)

Can you help to add Action Upload File? https://docs.pcloud.com/methods/file/uploadfile.html

**Comment by todsac** [comment]
I created a ticket and put it in our queue -- https://github.com/PipedreamHQ/pipedream/issues/938

**Comment by sergioeliot2039** [comment]
hi @cuongtqtran 
it's been a while but pCloud components have been completed recently and wanted you to let you know, in case you hadn't notice. this was released as per this Pull Request https://github.com/PipedreamHQ/pipedream/pull/3240

The upload file action that you requested is included, you can add it to your Pipedream workflows

![image](https://user-images.githubusercontent.com/25184117/178787581-9fe20667-afdf-4201-bdaf-c56eec390422.png)

These are the components that were created for pCloud
**New Actions**
Copy File
Copy Folder
Create Folder
Download Files
List Contents
Upload File
**New Source**
Watch Folder
Kind regards,
Sergio
