### ISSUE TITLE
basecamp - Create Card 404 error

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9345]
### App
basecamp

### Summary:
Fields are invalid and return 404

### Details:
We’re trying the pipedream+basecamp integration. I am trying to create some cards, but i requires a “todo set Id”, a “due date” and a “todo list id”, but those fields are irrelevant for the project I am setting up. I am getting 404 errors when testing. Can you assist us with that? Thanks.

### Screenshots:
No screenshots included

**Comment by gusfune** [comment]
I am providing screenshots below in case it helps.
![Screenshot 2023-12-18 at 21 53 40](https://github.com/PipedreamHQ/pipedream/assets/1147240/3af0504c-60f0-44ed-b061-88adfadb5902)
![Screenshot 2023-12-18 at 21 53 54](https://github.com/PipedreamHQ/pipedream/assets/1147240/82cf3457-bd38-48d0-b20b-82f3e2b3fdea)
