### ISSUE TITLE
[Components] codacy

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9347]
# codacy
## URLs
- https://api.codacy.com/api/api-docs#codacy-api
- https://api.codacy.com/api/api-docs#tocsdeletedormantaccountsresponse
- https://api.codacy.com/api/api-docs#tocsconfigurationstatuscategory

#### Prompt
Get the authenticated user. https://api.codacy.com/api/api-docs#getcommitdiff
#### Prompt
List organizations for the authenticated user. https://api.codacy.com/api/api-docs#listuserorganizations
#### Prompt
List integrations for the authenticated user.
#### Prompt
Delete a integration.

**Comment by sergio-eliot-rodriguez** [comment]
For context, this is context from user requesting the app integration with Codacy

> **Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
> Copy Issues that Codacy finds on GitHub repos over to GitHub. Integrate Codacy deadlines, Gates, Gate Poliys, coding standards, and quality goals, into GitHub projects.
