### ISSUE TITLE
[Components] codemagic

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9348]
# codemagic
## URLs
- https://docs.codemagic.io/rest-api/codemagic-rest-api/

**Comment by sergio-eliot-rodriguez** [comment]
From the user requesting the CodeMagic app integration: #9322 

> **Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
> Trigger on app build. Trigger on app settings update. Trigger on app cache update. Trigger on codemagic.yaml update. Trigger on Environment variables update. Trigger on Webhooks update.
