### ISSUE TITLE
[Components] sonarcloud

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9349]
# sonarcloud
## URLs
- https://sonarcloud.io/web_api
#### Prompt
Emit new event when a new analisys is completed.
#### URLs
- https://sonarcloud.io/web_api/api/webhooks

**Comment by sergio-eliot-rodriguez** [comment]
For context, user requesting Sonar Cloud app integration on #9323 

> ** Copy SonarCloud issues to GitHub. Trigger when background tasks fail. Trigger when changes happen in issues/hotspots assigned to user.** 
>  Trigger on new Quality Gate status. Trigger when issues are resolved as false positive or won't fix. Trigger when new issues are assigned to user. Trigger on new issues. Add SonarCloud badges to README.md.
