### ISSUE TITLE
[Components] code_climate

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9350]
# code_climate
## URLs
- https://developer.codeclimate.com/#overview

**Comment by sergio-eliot-rodriguez** [comment]
For context, user requesting Code Climate app integration on #9318 

> **Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!
> Trigger on Code Climate test reports. Send all project updates to Slack that the native Slack integration does, to use one less Slack app for the free plan, with a limited amount of apps. Copy Code Climate issues to GitHub. Add Code Climate badges to README.**
> Trigger on exclude pattern update.
> Trigger on organization settings update.
> Trigger on team member invite.
> Trigger on Per-User Subscription update.
> Trigger on Invoices update.
> Trigger on Code Climate Permissions update.
> Trigger on any other organization, team, member, user, or settings update.
