### ISSUE TITLE
[SOURCE] I'd like to use Pipedream's concurrency and throttling controls and issue an HTTP response from my workflow

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#939]
Currently, I can only use the [concurrency and throttling controls](https://docs.pipedream.com/workflows/events/concurrency-and-throttling/) with Pipedream event sources. But when I use an event source, I can't respond to the client from a workflow. I need the ability to use both features at the same time.

**Comment by nachocab** [comment]
My use case for this is that my workflow writes to $checkpoint and if two events are received simultaneously, one of them will not get saved to $checkpoint

**Comment by dylburger** [comment]
This is available in [the newest version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/)! The HTTP trigger can now support both concurrency controls and HTTP responses.
