### ISSUE TITLE
[ACTION] Zoom app, Zoom Phone's Get Call Logs Action

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9395]
### Actions
**Zoom - Get User's Call Logs**
https://developers.zoom.us/docs/zoom-phone/apis/#operation/phoneUserCallLogs

**Zoom Admin - Get Account Call Logs**
https://developers.zoom.us/docs/zoom-phone/apis/#operation/accountCallHistory

**Comment by sergio-eliot-rodriguez** [comment]
Some notes while triagging:

User put his component request filed under sources, but the description: "I want to get all the call logs" suggest more of an action. Can we confirm with the user?

Here are the relevant documentation for the related API endpoints:
[Get Account's Call Logs](https://developers.zoom.us/docs/zoom-phone/apis/#operation/accountCallLogs)
[Get User's Call Logs](https://developers.zoom.us/docs/zoom-phone/apis/#operation/phoneUserCallLogs)

I checked on Zone Phone webhooks, from those related to call logs; I don't think those match the requested by the user:
https://developers.zoom.us/docs/zoom-phone/webhooks/#operation/phone.callee_call_log_completed

**Comment by sergio-eliot-rodriguez** [comment]
Finally, I filed this under Zoom Admin,

Because the scopes required are, for getting Call Logs endpoints,  `phone:read:admin`,phone_call_log:read:admin`, and
`phone:read:admin`,`phone_call_log:read:admin`,`phone:read,phone_call_log:read`

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/ACTION-Zoom-app-Zoom-Phone-s-Get-Call-Logs-Action-ed13cc41202d4273bfabf4a50caca420

Hi @vunguyenhung, Those errors indicate that only accounts with Zoom Phone enabled can use these endpoints, so it's not a component error.

**Comment by luancazarine** [comment]
Hi @vunguyenhung Sorry, I hadn,t seen that, thanks for letting me know.
