### ISSUE TITLE
[APP] Klaviyo - Mailing Service

### ISSUE THREAD

**Issue by spc-1** [PipedreamHQ/pipedream#9397]
**APP**
Klaviyo

**Developers Documentation Site**
https://developers.klaviyo.com/en

**Is lack of support preventing you from building workflows, or do you have a workaround?**
NO

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Most important requirement is to enable from previous steps the transfer of metadata to Klaviyo to enable embedding of custom Files / Links in the emailing solutions.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @spc-1 

Thanks for the request. Klaviyo is integrated: https://pipedream.com/apps/klaviyo

And we have this actions. implemented.
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/6c7e11ca-a755-46d5-8040-7e6877cd370f)

Does this cover what you need?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
