### ISSUE TITLE
[APP] Activepieces

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9409]
**Name of app / service**
Activepieces

**Link to developer documentation**
https://www.activepieces.com/docs/endpoints/overview

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Connecting pipedream to a similar service seems kind of redundant actually. But this one is at the top of my list, and pipedream can already connect to itself, so here it is, I guess.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- Create Project
- Update Project
- List Projects
- Create Project Member
- List Project Member
- Delete Project Member
- Upsert Connection
- List Connections
- Delete Connection

**Comment by sergio-eliot-rodriguez** [comment]
Interesting point of view. We'll see, I think the YepCode integration didn't go forward. There was another user who requested Corteza Project

**Comment by MichaelHinrichs** [comment]
Are those other similar apps, like Zapier?

**Comment by sergio-eliot-rodriguez** [comment]
Yes yes, but more similar to Pipedream than Zapier actually, e.g. they allow custom code editing, much more technical

**Comment by sergio-eliot-rodriguez** [comment]
Ok, I checked the landing page at https://www.activepieces.com/ and probably we aren't going to move forward with this one for now cc @malexanderlim
