### ISSUE TITLE
[APP] frontegg

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9415]
**Name of app / service**
frontegg

**Link to developer documentation**
https://docs.frontegg.com/reference/getting-started-with-frontegg-apis

**Is lack of support preventing you from building workflows, or do you have a workaround?**
This may be useful for somebody one day.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Nope. Whatever this app does, do it.

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/frontegg?via=go
