### ISSUE TITLE
[APP] Northflank

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9418]
**Name of app / service**
Northflank

**Link to developer documentation**
https://northflank.com/docs/v1/api/use-the-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I'm not even ready to use this to deploy any of my repos yet.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Run a pipeline, on trigger new release.

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/northflank?via=go
