### ISSUE TITLE
[APP] Semgrep

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9419]
**Name of app / service**
Semgrep

**Link to developer documentation**
https://semgrep.dev/docs/semgrep-cloud-platform/semgrep-api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Report vulnerabilities and other code findings to the app that the project came from.

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/semgrep?via=go
