### ISSUE TITLE
[ACTION] Coin Market Cap Metadata V2

### ISSUE THREAD

**Issue by Priaroy** [PipedreamHQ/pipedream#9431]
**Is there a specific app this action is for?**

CoinMarketCap API

**Please provide a link to the relevant API docs for the specific service / operation.**

https://coinmarketcap.com/api/documentation/v1/#operation/getV2CryptocurrencyInfo

Can we get the Cryptocurrency Metadata V2 available to the request?

**Comment by kurayami07734** [comment]
may I work on this issue?
