### ISSUE TITLE
Google Gemini

### ISSUE THREAD

**Issue by jkfletch** [PipedreamHQ/pipedream#9466]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**

This is Google's new AI model.
**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

https://ai.google.dev/docs

**Comment by malexanderlim** [comment]
Hi @jkfletch , this has been integrated. Please let us know if there are any components that you'd like to see built, and we can prioritize building some triggers and actions for the Google Gemini integration!
