### ISSUE TITLE
Govee

### ISSUE THREAD

**Issue by jkfletch** [PipedreamHQ/pipedream#9467]
**Name of app / service**
Govee
**Link to developer documentation**
https://developer.govee.com/
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, there is no workaround I can find.
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
All

**Comment by sergio-eliot-rodriguez** [comment]
Hi @jkfletch 

Happy to announce there is now a base integration for Govee available at https://pipedream.com/apps/govee?via=go

Please follow https://github.com/PipedreamHQ/pipedream/issues/9487 to track progress on Govee components.

Thanks
