### ISSUE TITLE
[BUG] Box - Python code snippet is incorrect

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9468]
**Describe the bug**
Selecting Use any Box API in Python shows incorrect code snippet
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/4be1693a-c509-40fa-8482-ab7089fc7f74)

![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/16858c68-71a5-45e3-baba-b95b78d36d93)

```
import requests

def handler(pd: "pipedream"):
  token = '⫷oauth.access_token⫸'
  authorization = f'Bearer {token}'
  headers = {"Authorization": authorization}
  r = requests.get('https://api.box.com/2.0/users/me', headers=headers)
  # Export the data for use in future steps
  return r.json()
```

**Expected Behavior:**
- The code snippet should use oauth token from the box app instead of requiring user input manually

**Additional context**
Raised by a user here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1703570974176609

**Comment by malexanderlim** [comment]
This has been fixed and validated.

**Comment by malexanderlim** [comment]
<img width="988" alt="Screenshot 2024-01-02 at 11 11 17 AM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/1e0cb421-29e7-444d-b096-a16e5419c6a0">
