### ISSUE TITLE
Duplication Page like Ctrl+D in Notion

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9469]
### App
Duplication Page like Ctrl+D in Notion
https://github.com/PipedreamHQ/pipedream/blob/master/components/notion/actions/duplicate-page/duplicate-page.mjs

**Comment by sergio-eliot-rodriguez** [comment]
This doesn't look like an app request.
It is not clear the app where the "Duplication Page" feature needs to be added.

Already in Notion: https://pipedream.com/apps/notion/actions/duplicate-page
