### ISSUE TITLE
[APP] rasa.io

### ISSUE THREAD

**Issue by vexersa** [PipedreamHQ/pipedream#948]
rasa.io
![image](https://user-images.githubusercontent.com/7994227/108566464-2527c880-730f-11eb-952a-7f39bbedfea3.png)

**Comment by todsac** [comment]
I don't see a Rasa API.  Is there one?

**Comment by todsac** [comment]
@vexersa - we have built a Rasa integration.  Given we don't have a paid account, can you confirm the integration is working for you?

https://pipedream.com/apps/rasa

**Comment by dylburger** [comment]
@vexersa I'm closing this ticket since we added Rasa as an integrated app. Please let us know if you encounter any issues with the integration - happy to take a look.
