### ISSUE TITLE
planyo

### ISSUE THREAD

**Issue by Proteus-hub** [PipedreamHQ/pipedream#9499]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi there, Planyo is integrated as "Planyo Online Booking": https://pipedream.com/apps/planyo-online-booking

but what are you trying to achieve?
Or did you mean another app?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
