### ISSUE TITLE
Include workflow name in original_context in error workflow, include in default Error Workflow e-mail

### ISSUE THREAD

**Issue by rcmontrose** [PipedreamHQ/pipedream#95]
**Is your feature request related to a problem? Please describe.**
When you receive a workflow E-mail, it says something like "[pipedream] Error in workflow p_k2Cbzr at 12:17:52 AM GMT+0000" and you have to dig into the Error flows to determine which work flow generated the error message.

**Describe the solution you'd like**
Have the subject line contain the workflow name. Something like "[pipedream] Error in workflow ReignCheck-p_k2Cbzr at 12:17:52 AM GMT+0000"

**Do you have a workaround?**
Dig through the Error Workflow report to see the step where this occurred and find which workflow had that step, or trap all errors inside the program and generate my own emails.

**Comparable features in other tools?**
Most other system exceptions list the generic name of the task that caused the error, not just the run number. 

**Additional context**
I don't see the workflow name in the event passed to the Workflow error e-mail, just "workflow_id:p_k2Cbzr". If there was an additional parameter "workflow_name" this could hold the name.

**Comment by nachocab** [comment]
Would love to see this implemented. I guess for now, I could manually create a dictionary object with workflow ids and names:

```
myWorkflows = {
 'p_WxCWAm': 'workflow 1',
 ...
}
```

**Comment by dylburger** [comment]
This is now implemented. You can access the workflow name of the original workflow that threw the error in `steps.trigger.event.original_context.workflow_name`. You can copy the code in [this workflow](https://pipedream.com/@dylburger/global-error-workflow-p_q6CzLL/edit) to pass the error name to your error emails.

<img width="748" alt="Screen Shot 2021-08-30 at 10 47 35 PM" src="https://user-images.githubusercontent.com/242668/131449126-eb8715e6-2076-4b7b-bbd4-3e192e7c85ac.png">

The workflow name is also available in `steps.trigger.context.workflow_name` within the original workflow run, so you have access to that variable if you'd like to e.g. send the workflow name in emails or write it to a Google sheet.

**Comment by dylburger** [comment]
I forgot to mention that you’ll need to deploy your workflows once before they’ll expose the workflow name in context, and before they’ll pass that context to the error workflow

**Comment by cfjedimaster** [comment]
Ok, I don't think this is fixed. I'm clicking around more, and it seems like the problem returns when there is a msg of some sort on top. This time it was the gray 'you are viewing a' something or another, the message letting you know it's an old thing. In the screenshot below, you can see it's "stuck" above the fold. I was able to see it once, but returned and it's unreachable.

![image](https://user-images.githubusercontent.com/393660/132098232-3a141c97-38db-4c6a-8eeb-12356982268e.png)

As I click around after this, the top in general is now cut off:

![image](https://user-images.githubusercontent.com/393660/132098252-46ca886a-5dd8-4fbf-9ac9-454a35c2f1d5.png)

Maybe the fix you did for an error message on top also needs to be applied to the gray message?

**Comment by dylburger** [comment]
@cfjedimaster would you mind sharing this specific workflow with dylan@pipedream.com? Can you also select the event from the event inspector on the left where you're seeing this issue? When you select an event, we append the `?e` query string parameter with the event ID, so I can take a look at the same event data that you are, which will help me reproduce the issue.

**Comment by cfjedimaster** [comment]
Omg, I'm so sorry. I must have had two tabs open, one with the UI issue, and I accidentally posted this update here. Please disregard!

**Comment by christo9090** [comment]
> I forgot to mention that you’ll need to deploy your workflows once before they’ll expose the workflow name in context, and before they’ll pass that context to the error workflow

@dylburger I am trying to set this up. As of right now, every error payload `workflow_name`  is null. Do I need to go back through every workflow I have and deploy it again?

**Comment by dylburger** [comment]
@christo9090 that’s correct. If you simply add a space at the end of a line of code (or make another trivial change) and redeploy your workflows, you should see the workflow name passed to the global error workflow.

**Comment by christo9090** [comment]
Thanks @dylburger. Worked fine for me.
