### ISSUE TITLE
I am a fresher in c++. i can not understand the function sec. can anyone help me plss?

### ISSUE THREAD

**Issue by AMLANSAIN** [PipedreamHQ/pipedream#950]

**Comment by AMLANSAIN** [comment]
![image](https://user-images.githubusercontent.com/79273903/108582852-bcb30880-735b-11eb-9350-d0aff0cbfbcb.png)
I am not understanding this why void print and others is written before the int main(){

**Comment by AMLANSAIN** [comment]
I am from a rural area i dont have any teacher so that i can teach.

**Comment by dylburger** [comment]
Hi @AMLANSAIN , this repo is used for issues related to Pipedream. I’d recommend asking for help on StackOverflow of another Q&A site.

**Comment by AMLANSAIN** [comment]
Sir after c++ which language is better for job? Python Or any other?
