### ISSUE TITLE
[APP] Skype

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9524]
**Name of app / service**
Skype

**Link to developer documentation**
https://learn.microsoft.com/en-us/skype-sdk/skypeuris/skypeuriapireference
https://learn.microsoft.com/en-us/skype-sdk/trusted-application-api/docs/overview
https://learn.microsoft.com/en-us/skype-sdk/ucwa/unifiedcommunicationswebapi2_0
https://learn.microsoft.com/en-us/skype-sdk/ucwa/ucwa2_0apireference
https://learn.microsoft.com/en-us/skype-sdk/ucma/unified-communications-managed-api-ucma-5-0-sdk-documentation

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
No.

**Comment by sergio-eliot-rodriguez** [comment]
Looking at this

**Comment by sergio-eliot-rodriguez** [comment]
Skype for Business is being retired and Microsoft is replacing different Skype APIs with solutions around Azure and Teams. See, for example:

> We will be retiring the Skype Developer Platform for Web ("Skype Web SDK") on September 30, 2024. After that time the SDK will no longer be available for download. Instead, we recommend [Azure Communication Services](https://learn.microsoft.com/en-us/azure/communication-services/concepts/sdk-options), where we will continue to invest our development resources.
> Skype for Business Online Retirement
> 
> Azure Communication Services (ACS) is a cloud-based communications service that lets you add voice, video, chat, and telephony to your apps. Azure communication services allow developers to extend their applications with Teams interoperability, where users [communicate as guests](https://learn.microsoft.com/en-us/azure/communication-services/concepts/join-teams-meeting) (Teams anonymous users)

In [Skype Web SDKs](https://learn.microsoft.com/en-us/skype-sdk/websdk/docs/skypewebsdk?source=recommendations

Or 

> 
> Microsoft® Teams replaces Skype for Business Online as Microsoft’s professional online meeting solution.
> 
> Teams combines instant messaging, video conferencing, calling, and document collaboration into a single, integrated app – and enables exciting new ways of working.

[Skype for Business](https://www.skype.com/en/business/)

Many other APIs and SDKs around Skype are already retired, decomissioned.
