### ISSUE TITLE
Facebook Graph API

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9528]
### App
Facebook Graph API
https://developers.facebook.com/docs/graph-api

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim unsure you'd like to have an app integration for the entire Facebook Graph API, or keep an app per features (i.e. Facebook Groups, Facebook Pages, etc.).

We have a request for Graph API for Facebook Pages at https://github.com/PipedreamHQ/pipedream/issues/3030

Here are the features available through Graph API, besides mentined:

https://developers.facebook.com/docs/features-reference

**Comment by sergio-eliot-rodriguez** [comment]
I guess it will be difficult that Facebook grant us scopes for the entire Graph API.

Perhaps this could be added as BYOA and let the user connect a client with whatever scopes they have granted from FB.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
