### ISSUE TITLE
[FEATURE] Add the absolute date in the event sidebar

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#953]
Sometimes I have to dig through something that happened at a specific date in the past (say, 2021-01-13). I go to the relevant workflow but I see this:

![image](https://user-images.githubusercontent.com/27538/108595123-7e7b1080-737e-11eb-8b2b-42166fb18bce.png)

It would be good to see the absolute dates instead of doing the math in my head. 😅

**Describe the solution you'd like**
A simple way to fix it without modifying the UI would be to add a `title` attribute to the relative date `div` so that it would show on hover. 

Another option would be adding a user setting to choose between showing relative or absolute dates.

**Comment by dylburger** [comment]
Noted, and shared with the team!

**Comment by dylburger** [comment]
This is out in [the newest version of our workflow builder](https://pipedream.com/docs/migrate-from-v1/)!
