### ISSUE TITLE
[APP] Firefox Marketplace

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9534]
**Name of app / service**
Firefox Marketplace

**Link to developer documentation**
https://marketplace.firefox.com/developers/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
No.

**Comment by sergio-eliot-rodriguez** [comment]
HI @MichaelHinrichs 

I am unable to access that URL, could you please double check?

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/ae542e8a-24d6-4f72-b892-73b8d8d5d20a)

"is it down" says that domain is down:

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/55d7d1ed-47d1-4992-b224-bc20c39a9e6e)

**Comment by MichaelHinrichs** [comment]
It doesn't work for me either.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
