### ISSUE TITLE
[APP] Docker Engine

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9553]
**Name of app / service**
Docker Engine

**Link to developer documentation**
https://docs.docker.com/engine/api/v1.25/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I'll probably need this integration at some point, considering I actually plan to use this service.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
No.

**Comment by sergio-eliot-rodriguez** [comment]
Docker engine, you mean

**Comment by sergio-eliot-rodriguez** [comment]
https://pipedream.com/apps/docker-engine
