### ISSUE TITLE
Postmark - Send batch with templates

### ISSUE THREAD

**Issue by erz-dev** [PipedreamHQ/pipedream#9621]
**Is there a specific app this action is for?**
Postmark

**Please provide a link to the relevant API docs for the specific service / operation.**
https://postmarkapp.com/developer/api/templates-api#send-batch-with-templates

**Comment by GTFalcao** [comment]
I've added the Messages prop alongside the current implementation, so that the user can pick what suits them best.

**Comment by erz-dev** [comment]
Thanks for the update. I look forward to this change.

**Comment by GTFalcao** [comment]
I've added safety checks to support these additional types that output errors (using a string instead of an array, etc.)

**Comment by GTFalcao** [comment]
`Unexpected token o in JSON at position 1` likely stems from parsing the string `[object Object]`, which means an object was passed where a string was expected. This can happen in any component in Pipedream that expects a value of one type (in this case, a string) and receives a custom value that evaluates to another type (in this case, an object).

I've added another check to specifically avoid this in the attachments array for the Postmark actions, though it can still certainly happen in other ways if different types are used (perhaps this is something that can be improved globally?)
