### ISSUE TITLE
exifer

### ISSUE THREAD

**Issue by sjn001tvh** [PipedreamHQ/pipedream#9622]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi there, thanks for the requests.

Could you please elaborate on the app you would like to see integrated at Pipedream?

Is it this one https://www.thexifer.net/ ?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
