### ISSUE TITLE
[Components] btcpay-server

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9662]
# btcpay-server
#### Prompt
Generates a new payment request for a user. Required props include the amount and currency, while optional props can include an expiry date or custom metadata.
#### Prompt
Fetches the balance of your on-chain store wallet. It only requires the store wallet ID as a prop.

**Comment by lcaresia** [comment]
Endpoint necessary to do `withdraw-from-custodian-account`  action don't work.
