### ISSUE TITLE
blogger[APP]

### ISSUE THREAD

**Issue by ussam-dri** [PipedreamHQ/pipedream#9686]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment]
Hi @ussam-dri , Blogger is integrated: https://pipedream.com/apps/blogger

If you were looking for something else, let us know.

Thanks
