### ISSUE TITLE
[ACTION] Travis CI - trigger a build

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#97]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
This was tackled properly,
sample workflow at:
https://pipedream.com/@sergio/travis-ci-trigger-build-p_3nCG1p/edit
action URL:
https://pipedream.com/actions/a_xqiqYV/edit
