### ISSUE TITLE
[BUG] Anthropic (Claude) - Chat always throw error "anthropic-version: header is required"

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9705]
**Describe the bug**
Anthropic (Claude) - Chat always throw error "anthropic-version: header is required"
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/bef33572-f2c7-46d1-b159-93baf12888ee)

**Expected behavior**
The action should be executed successfully

**Additional context**
Reported by a customer via email. Front ID: msg_1j005ypz

**Comment by malexanderlim** [comment]
Hey Leo, thanks for flagging - tracking this here!
https://github.com/PipedreamHQ/pipedream/issues/9697

**Comment by malexanderlim** [comment]
This is complete.
