### ISSUE TITLE
[TRIGGER] New comment on a Channel YouTube Trigger

### ISSUE THREAD

**Issue by AviVolah** [PipedreamHQ/pipedream#9708]
**Youtube**

**https://developers.google.com/youtube**

**preventing me from building workflows, dont have a workaround**

**I want a trigger for a new comment added to the CHANNEL, ON ANY VIDEO, like in Pabbly Connect**
![2024-01-05 08 39 21 connect pabbly com a284285ee939](https://github.com/PipedreamHQ/pipedream/assets/99116185/ef26edd7-aa57-4064-b6bd-a8aeaa523e5b)

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
@AviVolah Thanks for the request.

I have triaged accordingly. Feel free to follow Dylan's advice, in case you'd like to jump in to build the components yourself, or otherwise please wait and the components development team will get to this and build it for you.

Best,

**Comment by AviVolah** [comment]
@dylburger I would be happy to help, because i have the time, even looked at the option of building it, before submitting here in the first place.
But, unfortunately its a bit much above my understanding, too complicated for me. 
Wish there would be something more user-friendly like a template and a ready environment to start with, since all this CLI and the rest are overwhelming me atm.

**Comment by sergio-eliot-rodriguez** [comment]
no stress @AviVolah , the team will get to build the component for you.
appreciate the feedback, afaik PD is looking on ways for users to contribute easily e.g. via configuration instead coding, which is more user friendly.

**Comment by AviVolah** [comment]
@sergio-eliot-rodriguez I actually know how to code, its just the CLI and CMD that are overwhelming for now..
Maybe as a intermediary step you could have something that connects to something like Replit? 
Where the user that wants to develop a new action/trigger, dont need to set up anything, and can start with a template of the relevant API (if an action with that service/platform already exists) and just write the logic for the action they want.
