### ISSUE TITLE
[OAUTH SCOPE] Freshbooks

### ISSUE THREAD

**Issue by dalepgrant** [PipedreamHQ/pipedream#9744]
**Which application needs a scope added?**
Freshbooks

**What scope(s) need to be added?**
`user:retainers:read`
`user:retainers:write`

**Please provide a link to the relevant API docs for scopes.**
https://documenter.getpostman.com/view/3322108/S1ERwwza

```json
{"message":"insufficient_scope: The request requires higher privileges than provided by the access token. Provided: ['user:profile:read user:expenses:read user:expenses:write user:invoices:read user:invoices:write user:other_income:read user:other_income:write user:time_entries:read user:time_entries:write']. Required: ['user:retainers:read']."}
```

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues
