### ISSUE TITLE
Yahoo User Info API

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9765]
### App
Yahoo User Info API
https://developer.yahoo.com/sign-in-with-yahoo/#get-user-info-api

**Comment by sergio-eliot-rodriguez** [comment]
You can use the Yahoo Fantasy Sports app to query the get user info api:
https://pipedream.com/apps/yahoo-fantasy-sports

**Comment by sergio-eliot-rodriguez** [comment]
But feel free to reopen, if you believe this is an mistake.
