### ISSUE TITLE
[Components] Google Calendar - Status Events

### ISSUE THREAD

**Issue by seanparkross** [PipedreamHQ/pipedream#9768]
**Trigger:**
- New Event Status Start: similar to https://pipedream.com/apps/google-calendar/triggers/event-start, allow user to fire an event X minutes before a specific type of event start (focusTime, outOfOffice, workingLocation)

**Action:**
- List Calendar Status Events (Filter based on 'focusTime', 'outOfOffice' ,'workingLocation')

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.google.com/calendar/api/guides/calendar-status

**Describe the event source. What app is this for, and what event does the trigger correspond to?**
Google Calendar working location setting. Start and end events. 
<img width="734" alt="Screenshot 2024-01-09 at 13 34 17" src="https://github.com/PipedreamHQ/pipedream/assets/94021366/f6068743-a2ad-4758-92fe-565eee105821">

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by seanparkross** [comment]
Sorry about the reply delay folks. 

Google calendar has an event type called `workingLocation` which let's you do a start and end date which is meant to be used to define where you will be working from. [Docs here](https://developers.google.com/calendar/api/guides/calendar-status).

In the Google Calendar app they show up as a vertical line on the left of normal events. 

My use case (and a lot of others) is to show everyone in my company my working hours and location. I want to sync that to my slack status.

**Comment by seanparkross** [comment]
Hope this reply doesn't get lost because it's closed :(

**Comment by malexanderlim** [comment]
Hi @seanparkross  I looked at the docs, and from what you shared using `workingLocation`, we could build a trigger that does the following:
**Trigger:**
- New change in status event (focus time, out of office, working location) 

**Action:**
- List Calendar status events

Let me know if this encompasses your use case.

**Comment by seanparkross** [comment]
This is awesome. When in production?

🙏 🙏 🙏

**Comment by michelle0927** [comment]
> This is awesome. When in production?
> 
> 🙏 🙏 🙏

Hi, @seanparkross. This has just been published!
