### ISSUE TITLE
[IMPROVEMENT] Improve Happy Scribe connection popup

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9783]
**Is your feature request related to a problem? Please describe.**
On the Happy Scribe connection popup, the instruction is outdated
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/5590cf2f-be1c-4e51-bcd3-b52bc51c3e7b)

To get the Happy Scribe API Key, we need to tap into the "My Workspace" section > Personal Settings > API
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/9b57b3d5-ac66-4a42-bf84-6779c3fa6ee5)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/922b96ec-7a87-4da6-a7d3-a7194bf82d4c)

Also the Organization ID is required for some actions, so I would suggest to add a new Organization ID field

**Describe the solution you'd like**
1. Update the instruction to get the API Key to 
```
To get the API key and Organization ID,
1. Navigate to your Happy Scribe account and sign in
2. Go to "My Workspace" > "Personal Settings" > "API"
```
2. Add the Organization ID field to this popup

**Do you have a workaround?**
No

**Comment by malexanderlim** [comment]
<img width="799" alt="Screenshot 2024-01-09 at 9 28 30 PM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/7b123ed8-be10-4fd0-8348-8d28aee289e1">

All set! Thank you for the improved instructions, Leo.
