### ISSUE TITLE
Automatically delete / do not save workflow event data

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#982]
In some instances we may send sensitive data through Pipedream and do not want it saved in a Workflow's Event history. I know it is possible to delete events one-by-one but is it possible to automate any of the following:
1. Do not write certain data point to the event history.
2. Do not write any data, or the entire event, to the event history.
3. Delete certain data points from the event history.
4. Delete all events from the event history.

Any one of the above suggestions, or others not mentioned, would be helpful.

Thanks 🙏

_Originally posted by @MikeElfassy in https://github.com/PipedreamHQ/pipedream/discussions/981_

**Comment by dylburger** [comment]
An API for deleting workflow events should satisfy 3 and 4.

**Comment by skwaer** [comment]
Facing the same thing over here. Some way to programmatically delete individual history events would be fantastic.

A way to hide / obscure / obfuscate certain fields from history might be even better. That way we can see that a workflow was executed but maintain privacy for sensitive data. 

Having that be programmatically optional would be the best of the above. Being able to hide real user data while still keeping test data available would allow for best case debugging / problem solving.

**Comment by dannyroosevelt** [comment]
This is done: https://pipedream.com/docs/workflows/settings#data-retention-controls
