### ISSUE TITLE
[TRIGGER] Infusionsoft - New Contact Record / New Order

### ISSUE THREAD

**Issue by niteshsharoff** [PipedreamHQ/pipedream#983]
I'd like automation to work off of a new record created in Infusionsoft (and write it to Bigquery ideally)

**Comment by lcaresia** [comment]
@niteshsharoff Hello, can you give me a documentation link ou a example what exactilly is a record on Infusionsoft? Thanks!

**Comment by dannyroosevelt** [comment]
### App
`infusionsoft`
https://developer.infusionsoft.com/docs/rest/

### Triggers
- New payment
- New invoice
- New appointment
- New order

### Actions
- Get contact
- Get company
- Create invoice
- Add product to invoice
