### ISSUE TITLE
[FEATURE] Longer retention history for logs, events

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#984]
Currently, Pipedream stores up to the last 100 events / logs entries for both event sources and workflows. I'd like to see a longer history of events and logs in the Pipedream UI.

Related to #489 .

**Comment by pedropedruzzi** [comment]
Just adding some notes on the customer impact of not having a longer workflow history. Most meaningful real-life workflows will likely process at least a few hundreds of events per day. In this scenario, 100 events history cap spans a few hours at most so you just can't debug a given non-errored execution, unless you detect the problem right after the fact.

The workaround is to integrate with a logging service (e.g. AWS CloudWatch Logs) with the down-side of loosing the nice UX of the Pipedream UI for inspecting executions.

**Comment by dylburger** [comment]
Paid plans (Pro / Team / Enterprise) now support 1,000 events per workflow! See https://pipedream.com/docs/limits/#event-execution-history .

We're planning further updates here to let you store even more history. Stay tuned for updates!
