### ISSUE TITLE
Coincatch Exchange

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9858]
### App
Coincatch Exchange
https://coincatch.github.io/github.io/en/mix/#welcome

### Sources
exactly like the BingX app you currently offer usage for

### Actions
exactly like the BingX app you currently offer usage for

**Comment by sergio-eliot-rodriguez** [comment]
We are tracking Coincatch here https://github.com/PipedreamHQ/pipedream/issues/9180
