### ISSUE TITLE
[APP] Shadertoy

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9861]
**Name of app / service**
Shadertoy

**Link to developer documentation**
https://www.shadertoy.com/howto#q2

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Query shaders, get shader from ID, Access shader assets, Get all shaders using appkey.

**Comment by sergio-eliot-rodriguez** [comment]
Shadertoy is integrated https://pipedream.com/apps/shadertoy?via=go
