### ISSUE TITLE
Modelry

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9862]
### App
Modelry
https://files.cgtarsenal.com/api/doc/index.html

### Actions
Approve, create, or reject a modeling request.
Return a list of modeling requests and assets.
Return a single modeling request.
Create or delete a product asset.
Download assets.
Create, delete, publish, or return product embeds.
Return a list of product's embeds.
Create, delete, return and update a product.
Return a list of products.
Create Modeling Request Review Issues.
Create a blob.
Upload a file.
Return a list of all user's workspaces.

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated https://pipedream.com/apps/modelry
