### ISSUE TITLE
RE: Payhere

### ISSUE THREAD

**Issue by Evyn7** [PipedreamHQ/pipedream#987]
**Use Case:**
Record would be submitted from PayHere (@ https://payhere.co).

Each time a Payhere Subscriber hits “Submit” button [Trigger],
an API would submit request to update my FaunaDB [Action].

**App Search Results reveal that:**
Payhere is registered with Zapier @ https://zapier.com/apps/payhere/integrations
FaunaDB is registered with PipeDream @ https://pipedream.com/apps/faunadb

**What would be the best way to reconcile the two?**
Would it be better to use PipeDream -or- Zapier (one or the other)?
Or use both - where Zapier submits the request to PipeDream,
which in turn submits the Update request to FaunaDB?

**Comment by todsac** [comment]
I integrated Payhere.  Are you comfortable adding the triggers necessary for this use case?
Example workflow - https://pipedream.com/@tod/payhere-api-integration-example-p_wOCg6vZ/
Marketplace - [Payhere API Integrations](https://pipedream.com/apps/payhere)

Here is the Payhere / Fauna integration page - https://pipedream.com/apps/payhere/integrations/faunadb

**Comment by Evyn7** [comment]
Thanks todsac.

Please allow me to look over the links you've provided,
then I can better advise regarding adding the triggers.

**Comment by dylburger** [comment]
@Evyn7 I opened up a separate issue to track the request for the Payhere trigger: https://github.com/PipedreamHQ/pipedream/issues/1086 . I'm closing this ticket to track the fact that we added Payhere as an integrated app.
