### ISSUE TITLE
[APP] Spline

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9872]
**Name of app / service**
Spline

**Link to developer documentation**
https://www.npmjs.com/package/@splinetool/runtime#api
https://docs.spline.design/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Emit event, find an object by it's name or ID, get and set variables, get all objects, get spline events.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @MichaelHinrichs 

Thanks for the request, and for being a Pipedream user.

That software you linking to is a JavaScript library not an application Pipedream would need to integrate with.

For now, we are not onboarding applications where Pipedream is required to provide a run environment, whereas we would expect a host provider running/deploying the app and Pipedream connecting to it (via API Keys, or OAuth, etc.).

You can try adding a node.js code step and import the npm to use it. the events described in the libraries' npm page aren't supported
