### ISSUE TITLE
Receiving an error - APIResponseError

### ISSUE THREAD

**Issue by sigythomas** [PipedreamHQ/pipedream#9876]
**Describe the bug**
I receive an email from Pipedream stating that there is an issue with a task that I have schedule. I have created a pipedream called Notion to Google Calendar. The function of this pipedream task is when I create a task in a Notion database, through the pipedream task, it creates a Google Calendar. The email that I am receiving states this "APIResponseError — Could not find page with ID: a83bd25c-1bb6-4d6e-b828-5b9f7b089292. Make sure the relevant pages and databases are shared with your integration."

When I enter my pipedream account, I click on the project "Notion to Google Calendar (New, Updated, Deleted)". I then click on the task which is named the same as the project. Then on the left side, I see the events that happened today and I click on the event that has the red exclamation mark. On the right side, I see the following error.

**APIResponseError**
Could not find page with ID: a83bd25c-1bb6-4d6e-b828-5b9f7b089292. Make sure the relevant pages and databases are shared with your integration. 
    at null.buildRequestError (/pipedream/dist/code/c7c7ffb8ff4aa2cf2eaf983f1d0da1aa5c28650f4569e39432df9a79c9a4c2a4/node_modules/.pnpm/@notionhq+client@2.2.13/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/pipedream/dist/code/c7c7ffb8ff4aa2cf2eaf983f1d0da1aa5c28650f4569e39432df9a79c9a4c2a4/node_modules/.pnpm/@notionhq+client@2.2.13/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.retry.retries

Here are the items that show in the **details** section.
Message: Could not find page with ID: a83bd25c-1bb6-4d6e-b828-5b9f7b089292. Make sure the relevant pages and databases are shared with your integration.
Total Duration: 5,982 ms
Compute Time: 5,642 ms
Execution Start: 2024-01-16T02:49:26.370Z
Execution End: 2024-01-16T02:49:32.352Z
Steps Executed: 1 / 1
Credits: 1
Version: 17 (d_xRsaG9KW)

Can you help fix this issue?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
