### ISSUE TITLE
[FEATURE] Update Google Drive Trigger - New or Modified File - Watch Specific Folders

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#9877]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to watch a specific folder for any new or modified files.

Google Drive - New File (Instant) has a prop for folders, this request is to have the same prop for New or Modified File source.

**Comment by michelle0927** [comment]
@malexanderlim @andrewjschuang I guess this isn't needed anymore? https://github.com/PipedreamHQ/pipedream/pull/9886

**Comment by andrewjschuang** [comment]
My bad, Michelle! I didn't see the open issue
