### ISSUE TITLE
[ACTION] Save web page to omnivore by sending HTML content instead of a URL

### ISSUE THREAD

**Issue by odebroqueville** [PipedreamHQ/pipedream#9898]
**Is there a specific app this action is for?**
OMNIVORE

**Please provide a link to the relevant API docs for the specific service / operation.**
savePage: Save a page with supplied HTML content
https://docs.omnivore.app/integrations/api.html
https://github.com/omnivore-app/omnivore/blob/main/packages/api/src/services/save_page.ts

**Comment by GTFalcao** [comment]
Regarding the 'Save Page' action, which was added on this PR (and no other components were modified, except Save URL that had props moved to propDefinitions):

I was successfully saving pages with other inputs. I managed to reproduce the error @vunguyenhung reported when I copied his inputs, multiple times in a row. However, I was then able to successfully save the page again several times in a row, including with the exact same inputs used:
![image](https://github.com/PipedreamHQ/pipedream/assets/48412907/e0a915f0-286f-481a-b258-e9fd644fbf6a)

I was able to save more than a dozen pages with different inputs as well as this one. Let me know if you're stuck with a consistent error @vunguyenhung and I'll try to debug it.

About the other actions, it would be helpful to know if the same problem happens in the live components - as explained above, their behavior was not changed in this PR. If so, perhaps a new bugfix issue should be created for them.

**Comment by GTFalcao** [comment]
Hey @vunguyenhung , thanks for sharing your credentials. After several more attempts of successful and failed runs, I believe I've narrowed down the issue to the Client Request ID, which should be a unique and valid UUID - I can consistently save a new page every time when generating a new UUID.

I've marked the prop as optional and a v4 UUID will be generated automatically if it is not specified (updated the prop description to reflect this).

**Comment by GTFalcao** [comment]
Since this error happens in the currently live "Get Article" component, which was not modified in this PR, I'll create a separate issue for this.

I've already contacted the Omnivore support regarding this issue, as the query to list users seems to be correct.
