### ISSUE TITLE
[APP] Revue

### ISSUE THREAD

**Issue by rawkode** [PipedreamHQ/pipedream#995]
**Name of app / service**
Revue by Twitter

**Link to developer documentation**

https://www.getrevue.co/api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

nope

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

managed auth please

**Comment by todsac** [comment]
Workflow Example - https://pipedream.com/@tod/revue-api-integration-example-p_A2CQwpj/
Marketplace - [Revue API Integrations](https://pipedream.com/apps/revue)
