### ISSUE TITLE
[FEATURE] Improve SurveyCTO connection popup: add Allow server API access setting

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9967]
**Is your feature request related to a problem? Please describe.**
In order for Pipedream to calls SurveyCTO API, it is required that user enable `Allow API server API access` as in the image below
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/a6885912-c998-48a5-bae7-ddd17306eda8)

**Describe the solution you'd like**
On SurveyCTO connection popup, add a new step to instruct user enable `Allow API server API access`:
1. On SurveyCTO Web UI, access Configure tab
2. On the Configure tab, scroll down to `User roles and permissions` section
3. Under `Administrator (full access, plus subscription management)` role, click `Edit`, then enable `Allow server API access`
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/a6885912-c998-48a5-bae7-ddd17306eda8)

**Comment by malexanderlim** [comment]
Thank you for clarifying, Leo - I've added this in the account connection instructions.

**Comment by malexanderlim** [comment]
<img width="747" alt="Screenshot 2024-01-19 at 10 31 12 AM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/66f22aa1-3581-46ce-bd99-17e6f97876fb">
