### ISSUE TITLE
[APP] Uberduck

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9968]
**Name of app / service**
Uberduck

**Link to developer documentation**
https://docs.uberduck.ai/reference/list-voices

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
- List voices, voice samples, and backing tracks.
- Get voice details.
- Generate lyrics and speech.
- Add reference audio.

**Comment by sergio-eliot-rodriguez** [comment]
Uberduck has been integrated, https://pipedream.com/apps/uberduck
