### ISSUE TITLE
Gmail attachment bug after new update

### ISSUE THREAD

**Issue by asharejazswati** [PipedreamHQ/pipedream#9977]
**Describe the bug**
Gmail API does not take an object/array of attachments to send in email anymore

**To Reproduce**
1. Create a step
2. Select "Gmail"
3. Select send an email
4. You can not add multiple attachments from an array or object from previous steps.

**Expected behavior**
The feature to add multiple attachments from previous steps directly as an object/array used to be available 2 days ago, but then there was the following update : 
Gmail Send Email - attachments prop refactor (#9925)

Since then we can only manually attach multiple emails one by one and not dynamically add multiple attachments from an object/array

**Comment by malexanderlim** [comment]
Hi @asharejazswati , we just reverted the change - can you please re-add the action and let me know if this is working for you now?
