### ISSUE TITLE
Zoho CRM - New scope

### ISSUE THREAD

**Issue by endreoo** [PipedreamHQ/pipedream#999]
**Name of app / service**
Zoho CRM

Can you add scope=ZohoCRM.coql.READ so that we can use the Query API?

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by todsac** [comment]
done - https://pipedream.com/apps/zoho-crm
