### ISSUE TITLE
[Planning Center]

### ISSUE THREAD

**Issue by jkfletch** [PipedreamHQ/pipedream#9991]
**Name of app / service**
Planning Center
**Link to developer documentation**
https://developer.planning.center/docs/#/apps/services/2018-11-01/vertices/songbook_status
**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes
**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
All

**Comment by sergio-eliot-rodriguez** [comment]
Hi there @jkfletch 

Planning Center is integrated: https://pipedream.com/apps/planning-center

Regarding actions/triggers, can you be more specific about what you are trying to do so that I can specify for the team the actions/triggers needed?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergio-eliot-rodriguez** [comment]
Btw nice Machu Pichu profile pic
