### ISSUE TITLE
HighLevel

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9992]
### App
HighLevel
https://highlevel.stoplight.io/docs/integrations/0443d7d1a4bd0-overview

### Actions
create new contact, add to workflow,

**Comment by sergio-eliot-rodriguez** [comment]
HighLevel integrated 

https://pipedream.com/apps/highlevel-oauth
https://pipedream.com/apps

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.
